### PR TITLE
http: proxying 104s `Upload Resumption Supported`

### PR DESCRIPTION
**Pull request by Nealsoni00**
Proxying 104s from upstream.

`104  Upload Resumption Supported` is introduced in [`draft-ietf-httpbis-resumable-upload`](https://datatracker.ietf.org/doc/draft-ietf-httpbis-resumable-upload/) spec. 

Continuation of the discussion in https://github.com/envoyproxy/envoy/issues/19044
Modeled after: https://github.com/envoyproxy/envoy/pull/19023

Risk Level: Low (minor refactor)
Testing: new integration test
Docs Changes: N/A

Release Notes: 

> http: envoy will now proxy 104 headers from upstream, though as with 100s only the first 1xx response headers will be sent. This behavior can be temporarily reverted by setting runtime guard `envoy.reloadable_features.proxy_104` to false. 104 headers are designated by [ietf's draft-ietf-httpbis-resumable-upload rfc](https://datatracker.ietf.org/doc/draft-ietf-httpbis-resumable-upload/).

Runtime guard: 
> `envoy.reloadable_features.proxy_104`

### CODE REVIEW

**Comment by Nealsoni00** [comment]
@RyanTheOptimist Build fix incoming. 

Where should I add release notes (other than in the PR description)?

> http: envoy will now proxy 104 headers from upstream, though as with 100s only the first 1xx response headers will be sent. This behavioral change by can temporarily reverted by setting runtime guard `envoy.reloadable_features.proxy_104` to false. 104 headers are designated by [`104 Upload Resumption Supported`](https://datatracker.ietf.org/doc/draft-ietf-httpbis-resumable-upload/).

**Comment by Nealsoni00** [comment]
@RyanTheOptimist I'm not entirely sure why the Linux test is failing, do you think it is ephemeral? Happy to keep digging if it is a change I made. Maybe a `/retest` would help? 

Lmk if there is anything else I should change :) Really appreciate your help!

**Comment by RyanTheOptimist** [comment]
> @RyanTheOptimist Build fix incoming.
> 
> Where should I add release notes (other than in the PR description)?
> 
> > http: envoy will now proxy 104 headers from upstream, though as with 100s only the first 1xx response headers will be sent. his behavioral can be temporarily reverted by setting runtime guard `envoy.reloadable_features.proxy_104` to false. 104 headers are designated by [ietf's draft-ietf-httpbis-resumable-upload rfc](https://datatracker.ietf.org/doc/draft-ietf-httpbis-resumable-upload/).

From this doc https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md you can find a link to the release notes, which are here: https://github.com/envoyproxy/envoy/blob/main/changelogs/current.yaml

**Comment by RyanTheOptimist** [comment]
Looking at the draft for resumable uploads, I notice that it's not yet an RFC and in particular there is this section about draft identification. Should this be taken into consideration in Envoy?

https://www.ietf.org/archive/id/draft-ietf-httpbis-resumable-upload-01.html#name-draft-version-identificatio

**Comment by Nealsoni00** [comment]
Hey @RyanTheOptimist the biggest motivation for support of the draft version is [the adoption in iOS 17](https://developer.apple.com/documentation/foundation/url_loading_system/pausing_and_resuming_uploads?language=objc) and it's wide-scale rollout. Applications that use envoy proxy cannot take advantage of this functionality as it uses the 104 informational responses to indicate that resumable uploads are supported. 

I'm curious if there are other hesitations to support this header!

I also believe I've added the runtime guard and release notes properly! Lmk if there is anything else i need to do!

**Comment by RyanTheOptimist** [comment]
> Hey @RyanTheOptimist the biggest motivation for support of the draft version is [the adoption in iOS 17 (and iOS 18)](https://developer.apple.com/documentation/foundation/url_loading_system/pausing_and_resuming_uploads?language=objc) and it's wide-scale rollout. Applications that use envoy proxy cannot take advantage of this functionality as it uses the 104 informational responses to indicate that resumable uploads are supported.
> 
> I'm curious if there are other hesitations to support this header!
> 
> I also believe I've added the runtime guard and release notes properly! Lmk if there is anything else i need to do!

I understand the motivation and am certainly supportive of adding this to Envoy. But my question is about [this section of the draft](https://www.ietf.org/archive/id/draft-ietf-httpbis-resumable-upload-01.html#name-draft-version-identificatio) which talks about the `Upload-Draft-Interop-Version` field values and the responsibility of client and server implementations. Does Envoy need to adhere to the server-side of this?

**Comment by Nealsoni00** [comment]
> [this section of the draft](https://www.ietf.org/archive/id/draft-ietf-httpbis-resumable-upload-01.html#name-draft-version-identificatio) which talks about the Upload-Draft-Interop-Version field values and the responsibility of client and server implementations. Does Envoy need to adhere to the server-side of this?

Appreciate this call out! In my situation, the ultimate server that receives the initial upload request containing the `Upload-Draft-Interop-Version` header is the one that sends back the 104 information response containing the same `Upload-Draft-Interop-Version`. It is my understanding that Envoy would not need adhere to that spec process. Envoy only needs to proxy the response from the receiving server back to the client. 

Q: In this particular situation, does proxying the informational 10X response through envoy filter what headers are returned to the client?

**Comment by RyanTheOptimist** [comment]
> > [this section of the draft](https://www.ietf.org/archive/id/draft-ietf-httpbis-resumable-upload-01.html#name-draft-version-identificatio) which talks about the Upload-Draft-Interop-Version field values and the responsibility of client and server implementations. Does Envoy need to adhere to the server-side of this?
> 
> Appreciate this call out! In my situation, the ultimate server that receives the initial upload request containing the `Upload-Draft-Interop-Version` header is the one that sends back the 104 information response containing the same `Upload-Draft-Interop-Version`. It is my understanding that Envoy would not need adhere to that spec process. Envoy only needs to proxy the response from the receiving server back to the client to indicate that resumable uploads are supported.
> 
> Q: In this particular situation, does proxying the informational 10X response through envoy filter what headers are returned to the client?

That's a good question. I'm not entirely sure. @alyssawilk to clarify.

**Comment by alyssawilk** [comment]
envoy should be passing through the headers the upstream sent, but if there are other important headers accompanying the 104 I suggest we add them to the e2e test to futureproof.

**Comment by Nealsoni00** [comment]
@RyanTheOptimist Is the change I made sufficient to test the propagation of the `Upload-Draft-Interop-Version` header?

**Review by RyanTheOptimist — DISMISSED** [review]

**Comment by RyanTheOptimist** [comment]
/wait
Looks like it needs a main merge?

**Comment by Nealsoni00** [comment]
@RyanTheOptimist not sure why tests are failing — verified those same tests are failing on master.

Screenshot 2024-07-02 at 3 46 58 PM

**Comment by Nealsoni00** [comment]
@RyanTheOptimist It should be good now!

**Comment by Nealsoni00** [comment]
@RyanTheOptimist sorry to re-ping. Would love to get this into master before it becomes out of date! 

Once in, what's the process to deprecate the runtime flag? Should I create a PR to remove it leave it to y'alls discretion to merge when appropriate?

**Comment by alyssawilk** [comment]
I've sent you an invite to the "assignable" group - in ~6m when we cut the release where this is no longer needed the tool will file an issue your way that removal is appropriate.

**Comment by Nealsoni00** [comment]
@alyssawilk happy to help clean up the runtime flag here — is there a ticket i should associate it to?

**Pull request merged**
