### PR TITLE
`envoy.filters.http.oauth2`: Change to `%REQ(x-forwarded-proto)%`

### PR DESCRIPTION
**Pull request by mbana**
`redirect_uri` should not be `"%REQ(:x-forwarded-proto)%://%REQ(:authority)%/callback"` in the files below:

* `test/extensions/filters/http/oauth2/config_test.cc`
* `test/extensions/filters/http/oauth2/oauth_integration_test.cc`

Signed-off-by: Mohamed Bana <mohamed@bana.io>

### CODE REVIEW

**Comment by mbana** [comment]
**Note:** One integration test is failing in totally unrelated test which I haven't touched and that the tests for `envoy.filters.http.oauth2` which I've changed continue to pass, unless I am totally misunderstanding this. This makes me wonder how the `envoy.filters.http.oauth2` integration tests were passing in the beginning with the `redirect_uri` being `"%REQ(:x-forwarded-proto)%://%REQ(:authority)%/callback"` instead of what I've changed it to in this pull request.

**Comment by adisuissa** [comment]
/retest
@rgs1 gentle ping :)

**Comment by adisuissa** [comment]
@snowp can you PTAL as a codeowner of oauth2?
/assign @snowp

**Review by rgs1 — APPROVED** [review]
Thanks!

**Review by snowp — APPROVED** [review]
Thanks!

**Pull request merged**
