### PR TITLE
Fix logging of incorrect data in http access logs for response duration.

### PR DESCRIPTION
**Pull request by ggreenway**
Signed-off-by: Greg Greenway <ggreenway@apple.com>

### CODE REVIEW

**Comment by ggreenway** [comment]
I stumbled across this while working on tcp_proxy access logging.  @mrice32

**Comment by mattklein123** [comment]
Is there some test that could have caught this?

**Comment by ggreenway** [comment]
I thought about how to test this, and the only thing I came up with seemed really specific to this very specific issue:

In a single test, set both of these values to different things, and read them both back to make sure they're correct.  

But if we want to go down that road, it seems like there's a huge number of tests in that category and they don't seem that useful to me.

**Comment by mattklein123** [comment]
Yeah fair enough.

**Pull request merged**
