### PR TITLE
Redact sensitive fields before outputting the configuration when it failed to start

### PR DESCRIPTION
**Pull request by shixiong-jiang**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
When Envoy failed to parse the config, Envoy print the config to the log file. Some sensitive fields, such as private_key should be redacted before the output.

Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by adisuissa — COMMENTED** [review]
Thanks for your contribution!
Overall LGTM.
This is a user-facing change. Can you please adda runtime-flag, and a release note?

**Comment by shixiong-jiang** [comment]
> Thanks for your contribution! Overall LGTM. This is a user-facing change. Can you please add a runtime-flag, and a release note?

Hello, adisuissa

1. Add a runtime-flag: 
Sorry. Do you mean: above change should be control by a flag?

2. And a release note?
Done. Updated the release note.

**Comment by adisuissa** [comment]
> > Thanks for your contribution! Overall LGTM. This is a user-facing change. Can you please add a runtime-flag, and a release note?
> 
> Hello, adisuissa
> 
> 1. Add a runtime-flag:
>    Sorry. Do you mean: above change should be control by a flag?

See https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md#runtime-guarding.

> 2. And a release note?
>    Done. Updated the release note.

Was this commit pushed? this is the file that needs to be updated: https://github.com/envoyproxy/envoy/blob/main/changelogs/current.yaml

**Comment by shixiong-jiang** [comment]
> /wait

Done. Plz review again. Thx a lot.!!!

**Review by adisuissa — COMMENTED** [review]
Can you please add tests to ensure that this is working as expected.
Also please add the runtime guard to https://github.com/envoyproxy/envoy/blob/main/source/common/runtime/runtime_features.cc

/wait

**Pull request closed without merging**
