### PR TITLE
[utility]: Change behavior of main thread verification utility

### PR DESCRIPTION
**Pull request by chaoqin-li1123**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message: Change the behavior of main thread checking utility(https://github.com/envoyproxy/envoy/pull/14457). Currently, the isMainThread function can only be called during the lifetime of thread local instance because the singleton that store main thread id is initialized in the constructor of tls instance and cleared in the destructor of tls instance. Change the utility so that outside the lifetime of tls instance, the function return true by default because everything is in main thread when threading is off.
Additional Description:
Risk Level: low
Testing: change unit to reflect change of behavior. 
Docs Changes: none
Release Notes: none
Platform Specific Features: none
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Review by htuch — DISMISSED** [review]
LGTM, thanks!

**Comment by htuch** [comment]
@chaoqin-li1123 looks like coverage has regressed?

**Comment by chaoqin-li1123** [comment]
yes, I am fixing the coverage problem, will retest later.

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
