### PR TITLE
Removes unused and unreferenced run_clang_tidy.sh

### PR DESCRIPTION
**Pull request by mathetake**
`run_clang_tidy.sh` has been removed from the CI in https://github.com/envoyproxy/envoy/pull/29848
and not used anymore. Furthermore, it's broken on the main branch, so it's better
to remove the file completely to avoid confusing new contributors.

@phlax

### CODE REVIEW

**Comment by mathetake** [comment]
wait, no i am suspicious that clang-tidy is not working on CI at all now

**Comment by mathetake** [comment]
that sounds bad to be honest, the more we hold on, the more difficult to get it back on track ...

**Comment by mathetake** [comment]
yeah clang-tidy must match the LLVM version we use (currently LLVM 14 )

**Comment by mathetake** [comment]
anyways can we merge this? no need to maintain this shell anymore regardless of what we are going to do

**Comment by phlax** [comment]
really up for getting it working - even initially just running on a schedule so we can see and fix any residual issues until its good

the replacement code uses aspects rather than the older way of building ~everything and reusing any artefacts, so theoretically be faster, but with bazel overheads thrown in

**Review by phlax — APPROVED** [review]
lgtm, thanks @mathetake

**Pull request merged**
