### PR TITLE
Update opencensus-proto dependency to v0.1.0 release.

### PR DESCRIPTION
**Pull request by g-easy**
Signed-off-by: Emil Mikulic <g-easy@users.noreply.github.com>

Part of #2456

### CODE REVIEW

**Comment by zuercher** [comment]
Looks like you're hitting https://github.com/lyft/protoc-gen-validate/issues/41

**Comment by htuch** [comment]
@akonradi @rodaine any thoughts on how best to tackle https://github.com/lyft/protoc-gen-validate/issues/41?

**Comment by rodaine** [comment]
Similar to the override presented here for the Java path, something similar should be done for C++ (otherwise, it'll follow the protoc-gen-go rules): https://github.com/lyft/protoc-gen-validate/blob/a346734/templates/pkg.go#L34

**Comment by htuch** [comment]
@rodaine I'll give this a go this arvo.

**Comment by g-easy** [comment]
Thanks for the PGV fix!

I'm not authorized to merge this pull request.

**Pull request merged**
