### PR TITLE
http3: deprecate envoy.reloadable_features.quic_defer_send_in_response_to_packet

### LINKED ISSUE #26906: envoy_reloadable_features_quic_defer_send_in_response_to_packet deprecation
Your change #22796 (quic: make server connection defer sending packets during processing incoming packets) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

### PR DESCRIPTION
**Pull request by danzh2010**
Commit Message: deprecate above runtime guard

Risk Level: low
Testing: existing tests passed
Docs Changes: N/A
Release Notes: runtime guard deprecation
Platform Specific Features: N/A
Fixes #26906
Deprecated: envoy.reloadable_features.quic_defer_send_in_response_to_packet

### CODE REVIEW

**Review by alyssawilk — DISMISSED** [review]

**Comment by alyssawilk** [comment]
Azure Pipelines / envoy-presubmit (Checks (Linux x64) Linux x64 fuzz_coverage)
Started 23h 18m 37s ago

well taht's new

**Comment by alyssawilk** [comment]
I don't know how to cancel thjat - maybe push a main merge?

**Comment by alyssawilk** [comment]
cc @phlax can we add a timeout to the CI that's taking 2 days?

**Comment by phlax** [comment]
> well taht's new

i think its not new - i believe ive seen it in the past - if you click through the actual test (and the agent i hope - gonna check) timed out after 90mins, so the problem seems to be with azp

**Comment by phlax** [comment]
the actual error is v suspect:

```console
time="2023-04-25T17:37:06Z" level=error msg="error waiting for container: "
```

this is docker timing out, i didnt think there was any docker containers involved in fuzz/coverage but not sure how it works

**Pull request merged**
