### PR TITLE
Fix #35369.

### LINKED ISSUE #35369: envoy_reloadable_features_grpc_http1_reverse_bridge_handle_empty_response deprecation
Your change #31065 (Handle empty responses correctly in grpc_http1_reverse_bridge.) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.
cc @hq6

### PR DESCRIPTION
**Pull request by hq6**
This commit removes the runtime flag introduced in #31065 since it has been 6 months since that change.

### CODE REVIEW

**Comment by hq6** [comment]
I'm not sure what's happening in the workflow run, but I'll resolve the merge conflicts for starters:
```
Merge commit information not found for pull request 35386.
Error: Process completed with exit code 1.
Error: The template is not valid. envoyproxy/toolshed/actions-v0.2.31/gh-actions/github/checkout/action.yml (Line: 143, Col: 12): Error reading JToken from JsonReader. Path '', line 0, position 0.```

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Comment by hq6** [comment]
> LGTM, thanks!

@adisuissa I had to rebase again to deal with a new conflict on the changelog, and it looks like that killed your review.
Should I use merge commits instead of rebasing to resolve this kind of conflict in the future?

**Review by adisuissa — DISMISSED** [review]
LGTM, thanks!

**Comment by adisuissa** [comment]
> @adisuissa I had to rebase again to deal with a new conflict on the changelog, and it looks like that killed your review. Should I use merge commits instead of rebasing to resolve this kind of conflict in the future?

Yes, merge is better than rebase+force-push. See contribution guidelines.

**Comment by hq6** [comment]
> > @adisuissa I had to rebase again to deal with a new conflict on the changelog, and it looks like that killed your review. Should I use merge commits instead of rebasing to resolve this kind of conflict in the future?
> 
> Yes, merge is better than rebase+force-push. See contribution guidelines.

I did a merge instead of a rebase this time and Github still dismissed your review.
Is there some other way I should be fixing the merge conflicts?

Or should I let someone with write access fix the merge conflicts in the changelog, so that they can merge immediately instead of needing to fix it multiple times?

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
