### PR TITLE
reokitteh: bring in wait module

### PR DESCRIPTION
**Pull request by itayd**
Signed-off-by: Itay Donanhirsh <itay@bazoo.org>

*Description*:
Bring in `/wait' command - see inside for doc changes.

*Risk Level*:
None.

*Testing*:
See this PR.

*Docs Changes*:
See inside.

*Release Notes*:
None

### CODE REVIEW

**Comment by itayd** [comment]
look at me waiting for something

/wait

**Comment by itayd** [comment]
now i say something without '/waiting' to cause the label to go away

**Comment by itayd** [comment]
now i'll wait again AND assign this to someone

/assign @mattklein123 
/wait

**Comment by itayd** [comment]
ok @mattklein123 i hope this makes you happy :)

/wait

**Comment by itayd** [comment]
(do not merge yet - i need to do docs)

**Comment by itayd** [comment]
@mattklein123 your turn.

/assign @mattklein123 
/wait

**Comment by itayd** [comment]
got an issue with blessing after push i think. will check.

now work!

/wait

**Comment by itayd** [comment]
this should work fine after merge. i'll debug the weird behavior anyway.

/wait

**Comment by itayd** [comment]
@mattklein123 yes - see https://github.com/envoyproxy/envoy/pull/4956#issuecomment-435623667. 

if anything was active once pr is active, some evil actor could just open a pr and do what they want. that's why only specific people (currently me and @htuch) can bless prs. who can do it is in a configuration file on the kitteh's side. down they road it'll all be available through some kind of ui and/or api.

**Comment by mattklein123** [comment]
Got it. OK this is amazing. I'm going to go wait all my PRs!

**Comment by itayd** [comment]
👍 i'm pretty sure we'll wont adjustments to this, so feel free to ask.

**Pull request merged**
