### PR TITLE
stats: revert "Prom stats perf improvements"

### PR DESCRIPTION
**Pull request by jmarantz**
Commit Message: Reverts https://github.com/envoyproxy/envoy/pull/24998

See https://github.com/envoyproxy/envoy/issues/27173

Additional Description:
Risk Level: n/a
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by jmarantz** [comment]
@rulex123 fyi

**Comment by jmarantz** [comment]
I'd suggest only merging this if someone can post an actual repro.

**Comment by zirain** [comment]
This is a major regression, should revert first.

**Review by kyessenov — APPROVED** [review]
Revert to root cause without the time pressure.

**Pull request merged**
