### PR TITLE
build: enable -Wrange-loop-analysis rule

### PR DESCRIPTION
**Pull request by rebello95**
Xcode 12 builds with this enabled, so adding this to Envoy will ensure compatibility and prevent breakages in Envoy Mobile's iOS build.

Resolves https://github.com/envoyproxy/envoy/pull/13140.

Risk Level: Low
Testing: Existing unit tests

Signed-off-by: Michael Rebello <me@michaelrebello.com>

### CODE REVIEW

**Review by mattklein123 — DISMISSED** [review]
Thanks!

**Comment by yanavlasov** [comment]
Looks like the build is failing because of the new option.

**Comment by rebello95** [comment]
Looks like we are still getting errors from absl. Will probably need to wait until those are fixed upstream (or is there a way to only apply `-Wrange-loop-analysis` to Envoy's code?)

```
external/com_google_absl/absl/strings/internal/str_split_internal.h:404:23: error: loop variable 'sp' of type 'const std::__1::basic_string_view<char, std::__1::char_traits<char> >' creates a copy from type 'const std::__1::basic_string_view<char, std::__1::char_traits<char> >' [-Werror,-Wrange-loop-analysis]
      for (const auto sp : splitter) {
                      ^
external/com_google_absl/absl/strings/internal/str_split_internal.h:305:12: note: in instantiation of member function 'absl::strings_internal::Splitter<absl::ByChar, absl::SkipEmpty>::ConvertToContainer<std::__1::map<std::__1::basic_string<char>, std::__1::basic_string<char>, std::__1::less<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, std::__1::basic_string<char> > > >, std::__1::pair<const std::__1::basic_string<char>, std::__1::basic_string<char> >, true>::operator()' requested here
    return ConvertToContainer<Container, typename Container::value_type,
           ^
source/extensions/filters/network/postgres_proxy/postgres_decoder.cc:360:17: note: in instantiation of function template specialization 'absl::strings_internal::Splitter<absl::ByChar, absl::SkipEmpty>::operator map<std::__1::map<std::__1::basic_string<char>, std::__1::basic_string<char>, std::__1::less<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, std::__1::basic_string<char> > > >, void>' requested here
  attributes_ = absl::StrSplit(message_.substr(4), absl::ByChar('\0'), absl::SkipEmpty());
                ^
external/com_google_absl/absl/strings/internal/str_split_internal.h:404:12: note: use reference type 'const std::__1::basic_string_view<char, std::__1::char_traits<char> > &' to prevent copying
      for (const auto sp : splitter) {
           ^~~~~~~~~~~~~~~
```

**Comment by mattklein123** [comment]
It's not going to be easily possible for headers like this. I would recommend opening an abseil issue and linking it to the tracking issue and not setting it here project wide.

**Comment by rebello95** [comment]
Sounds good, I'll close this PR for now until https://github.com/abseil/abseil-cpp/issues/787 is fixed

**Pull request closed without merging**
