### PR TITLE
fix invalid ruby_package gen from protoxform

### LINKED ISSUE #19814: `ruby_package` syntax for proto packages that export it are not using valid identifiers
*Description*:

Ever since: https://github.com/envoyproxy/envoy/commit/08b123a8321d359ea66cbbc0e2926545798dabd3 (the protoxform upgrader), we started writing the `ruby_package` lines as invalid ruby identifiers: https://github.com/envoyproxy/envoy/commit/08b123a8321d359ea66cbbc0e2926545798dabd3#diff-1a29a28d0715e9dd3053d113225d6d24807dcd4fe497f3d503f49a76621a8000L9 . Specifically note the change from `::`, to `.`.

We noticed then when trying to import it at Stripe in our ruby codebase. Happy to fix forward.

*Repro steps*:

- Try to import the protobufs of ruby.
- Notice it generates invalid identifiers. Specifically it uses `.`'s instead of `::` for the package seperator.

### PR DESCRIPTION
**Pull request by Mythra**
Commit Message:

fixes us generating an invalid ruby_package for protobuf.

Signed-off-by: Cynthia <cynthia@coan.dev>

Additional Description:

We should probably talk about back-porting as right now generating any packages with ruby is broken.

Risk Level: Should be none, this only changes `ruby_package` which was broken before.

Testing:
  - Generated the protobufs with the changed package names, and validated that generation succeeds.

Docs Changes: N/A
Release Notes: Pending backport discussions.
Fixes #19814

### CODE REVIEW

**Comment by Mythra** [comment]
FWIW although I opened this PR for exposure about the issue, and making sure there was a PR associated with the issue. I think there's still lots of talk to be had about whether or not we should change protobuf again (as there are some old projects which haven't been checked in years , that also generate invalid package names -- there are also plenty that do '::'). Protobuf should probably at least document this format , rather than just changing it randomly, and we should switch to it?

I opened these merely for discussion of what it'd look like -- not necessarily saying this is the approach we should take.

**Comment by htuch** [comment]
@Mythra I think it's fine to make the change if there is no possibility it was working before. The value of changing v2 at this point is maybe questionable though, but not out of question. You mention that: 
>as there are some old projects which haven't been checked in years , that also generate invalid package names -- there are also plenty that do '::'

Does this mean that you can make use of "invalid package names" in Ruby, or that lots of other people are also doing broken things?

**Comment by Mythra** [comment]
That's a fair point about V2. I mostly changed it just incase people are for any reason say just trying to generate everything in Ruby.

> Does this mean that you can make use of "invalid package names" in Ruby, or that lots of other people are also doing broken things?

There are some other broken things we found when searching all of GitHub, and even when importing this project. e.g. OpenCensus also has some broken proto's.

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Comment by htuch** [comment]
@Mythra we can tag this for backports if it will help a concrete use case someone has; do you need this? If not, I'm not inclined to add it to the list, as it's not super critical I think.

**Comment by Mythra** [comment]
@htuch , wow merged faster than I was thinking -- yeah it'd be nice to have a backport for the team at Stripe, but not super critical. I think adding to the list is fine.

**Pull request merged**
