### PR TITLE
Fixing ECDS config dump flaky issue.

### PR DESCRIPTION
**Pull request by yanjunxiang-google**
Signed-off-by: Yanjun Xiang <yanjunxiang@google.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by alyssawilk** [comment]
/wait on main merge
As a note: if we land this before @tyxia bumps coverage back up he's going to be on the hook for test per https://github.com/envoyproxy/envoy/issues/24353

**Comment by alyssawilk** [comment]
oh sorry this wasn't the bump forward, please ignore prior comment

**Comment by yanjunxiang-google** [comment]
Since https://github.com/envoyproxy/envoy/pull/23902 is now reverted by https://github.com/envoyproxy/envoy/pull/24354,  we can massage this change into https://github.com/envoyproxy/envoy/pull/23902 and create a separate PR.

**Comment by yanavlasov** [comment]
Do you still need this PR after #24384 was merged? If not please close it.

**Comment by yanjunxiang-google** [comment]
> Do you still need this PR after #24384 was merged? If not please close it.

Yeah, this PR is not needed.

**Pull request closed without merging**
