### PR TITLE
[test] Convert load_balancer_benchmark to benchmark cc binary and test framework

### PR DESCRIPTION
**Pull request by antoniovicente**
Description: Convert load_balancer_benchmark to benchmark cc binary and test framework
Risk Level: n/a
Testing: n/a
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by tonya11en** [comment]
Looks like the tsan build is failing due to the benchmark. I'll wait until that's sorted out- seems like it's related to this benchmark.

/wait-any

**Comment by antoniovicente** [comment]
> Looks like the tsan build is failing due to the benchmark. I'll wait until that's sorted out- seems like it's related to this benchmark.
> 
> /wait-any

Ugh TIMEOUT.  Please look at #10538 first which adds bazel params to increase test timeout values.

**Comment by mattklein123** [comment]
I just merged the other one so I assume the same fix will work here. Sorry for the trouble!

/wait

**Comment by antoniovicente** [comment]
> I just merged the other one so I assume the same fix will work here. Sorry for the trouble!
> 
> /wait

Thanks for the help getting these changes through.

**Pull request merged**
