### PR TITLE
Refactor primitive stats and add null primitive stats

### PR DESCRIPTION
**Pull request by zyfjeff**
Signed-off-by: tianqian.zyf <tianqian.zyf@alibaba-inc.com>

Description: Refactor primitive stats and add null primitive stats, the main purpose is to provide an implementation of null host stats to make it easy to disable host stats when necessary
Risk Level: low
Testing:  existing tests
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by zyfjeff** [comment]
It seems that the introduction of the vtable caused per host's memory to increase

**Comment by jmarantz** [comment]
Rather than adding a vtable to a stats-struct that's trying to be tiny, can you just use a single shared instance of a single primitive counter for all the null primitive counters?

Granted the value of the null counters will not be zero, but does that matter? You could fix those up when outputting them (or just exclude them).

**Comment by zyfjeff** [comment]
@jmarantz thanks,  I'll see if there's a better way, but I need to limit my goals, and I'd like to turn off host stats at compile time.

**Comment by zyfjeff** [comment]
@jmarantz using pointer does not solve this problem, because where the call is made requires direct access to the HostStats member for statistics, and it is not possible to determine whether the pointer is empty everywhere.

**Comment by zyfjeff** [comment]
@jmarantz I initially wanted to close HostStats at runtime, but the results were not ideal, with the introduction of many variables and a lot of memory overhead, and only 35 bytes were saved when HostStats was actually closed. #9529 

So I wanted to see if I could make it compile-time closed to avoid introducing extra variables to increase the memory overhead

**Pull request closed without merging**
