### PR TITLE
honor connection_pool_per_downstream_connection in tcp_conn_pool

### LINKED ISSUE #34762: honor connection_pool_per_downstream_connection in tcp conn-pool
*Title*: connection_pool_per_downstream_connection is only read in [httpConnPoolImpl](https://github.com/envoyproxy/envoy/blob/63621d07e0088b5dce076b3436ab0e1e8367f568/source/common/upstream/cluster_manager_impl.cc#L1993-L1997) today. Which means this flag can't be used with filters relying on [tcp_pool](https://github.com/envoyproxy/envoy/blob/63621d07e0088b5dce076b3436ab0e1e8367f568/source/common/upstream/cluster_manager_impl.cc#L1087) (eg. thrift_proxy) 

*Description*:
the flag is a cluster level flag and should be honored in thrift_proxy etc (which uses tcppool)

### PR DESCRIPTION
**Pull request by Pawan-Bishnoi**
Commit Message: this flag is already supported by httpConnPool. Adding to tcpConnPool as well so that thrift_proxy etc can use this feature.
Risk Level: low
Fixes #34762

### CODE REVIEW

**Comment by tyxia** [comment]
@zuercher  Could you please take a look at this PR when you have time.

Looks like you are the domain expert on tcp connection pool (original author) and code owner of thrift proxy.

Thanks

**Comment by zuercher** [comment]
This needs a test, similar to the existing one that exercises the HTTP version of this feature (See ClusterManagerImplTest's ConnectionPoolPerDownstreamConnection in test/common/upstream/cluster_manager_impl_test.cc.

**Comment by Pawan-Bishnoi** [comment]
added ConnectionPoolPerDownstreamConnection_TCP
can use a better name if needed :)

**Comment by Pawan-Bishnoi** [comment]
The CI is acting really flaky for me

/retest failed

**Comment by zuercher** [comment]
I was able to get some to pass, but the publish and verify test is failing on master as well.

**Comment by Pawan-Bishnoi** [comment]
> I was able to get some to pass, but the publish and verify test is failing on master as well. However, the failure here is different. It might be the base that merging master will help.

I did rebase 15h ago. Can try again later today

**Comment by Pawan-Bishnoi** [comment]
rebase doesn't help. Failure this time was
`Error: ENOSPC: no space left on device, write
`

/retest failed

**Comment by zuercher** [comment]
The other thing this PR needs is a release note for the change. Up to you whether you call it a bug fix or a minor behavior change.

**Comment by Pawan-Bishnoi** [comment]
done @zuercher

**Comment by Pawan-Bishnoi** [comment]
I have never had so much trouble with Envoy CI before 😄 

`System.IO.IOException: No space left on device : '/home/runner/runners/2.317.0/_diag/Worker_20240715-035746-utc.log'
`
My other PR passed without issues. This error doesn't look related to my changes but haven't seen a single success after so many re-runs 🤔 


/retest

**Comment by Pawan-Bishnoi** [comment]
@zuercher CodeQL isn't a mandatory check it seems. 
Do you think it is worth blocking on this 'no disk space' failure or is this PR good to go 🤔

**Comment by Pawan-Bishnoi** [comment]
it was fixed here: https://github.com/envoyproxy/envoy/pull/35231

retrying the build

**Comment by zuercher** [comment]
> @zuercher CodeQL isn't a mandatory check it seems. Do you think it is worth blocking on this 'no disk space' failure or is this PR good to go 🤔

I was out last week in any event, but I don't have permissions to bypass the checks. Looks like it's working now, though.

**Review by zuercher — APPROVED** [review]

**Pull request merged**
