### PR TITLE
Add /nostalebot repokitteh option

### PR DESCRIPTION
**Pull request by DavidSchinazi**
Commit Message: Add /nostalebot repokitteh option
Additional Description: This will reduce user toil and maintainer load.
Risk Level: Low
Testing: NA
Docs Changes: None
Release Notes: None
Platform Specific Features: None

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by RyanTheOptimist** [comment]
/assign @phlax
This looks good to me, but can you take a look too?

**Comment by phlax** [comment]
hi @DavidSchinazi not sure about this - as annoying as it is, the stalification system does serve a purpose, and im thinking its probably a maintainer responsibility to override that

no strong opinion tho - ive canvassed the maintainer channel for further thoughts

**Comment by DavidSchinazi** [comment]
Thanks!

**Pull request merged**
