### PR TITLE
Set span as error only if grpc error can be translated to 5xx

### PR DESCRIPTION
**Pull request by jakubednarek**
Signed-off-by: Jakub Bednarek <jakub.bednarek@fresha.com>

Commit Message:
Set span as error only if grpc error can be translated to 5xx
Additional Description:
Due to the fact that all the grpc error codes are marked as errors currently, we had a very high error rates in our services, mainly because our services return a lot of GRPC::NotFound errors. Such an error is an equivalent of HTTP 404 and it is properly handled by the clients. And HTTP 404 is not tagged as en error in envoy. I thought about taking a similar approach when it comes to gRPC status codes.
Fixes: https://github.com/envoyproxy/envoy/issues/15883
Risk Level:Low
Testing: I manually verified in DataDog APM that non 5xx are not tagged as errors. I also checked that 5xx errors are still tagged as errors.
Docs Changes: I changed the information about tagging span as erroneous to match new implementation.
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by asraa — COMMENTED** [review]
Thanks for the change! In the meantime, I think this should be guarded by an option, could you add one please?

**Comment by jakubednarek** [comment]
> Thanks for the change! In the meantime, I think this should be guarded by an option, could you add one please?

Thanks for your reply. Just to be sure, you mean something like a runtime guard described here: https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md#runtime-guarding ?

**Comment by yanavlasov** [comment]
Looks like an indentation issue

/wait

**Comment by fcervantes2** [comment]
The name of the runtime guard seem misleading. If `add_error_tag_when_grpc_status_is_5xx ` is set to `false`, one would assume that no error tag would be set. I think the guard should be `add_error_tag_only_when_grpc_status_is_5xx` ("only" added to the name).

**Pull request closed without merging**
