### PR TITLE
bazelci: add coverage

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Hi, there is some failures on Bazel CI after merging this.
https://buildkite.com/bazel/envoy/builds/1151

Is there already a fix coming in?

**Comment by lizan** [comment]
@meteorcloudy this doesn't fail in my local, what does the clang/llvm version installed in the CI image?

**Comment by meteorcloudy** [comment]
So from [the log](https://buildkite.com/bazel/envoy/builds/1151#87015f85-062f-4a7c-aa16-60913f813868);
```
The C compiler identification is Clang 9.0.0
```

**Comment by lizan** [comment]
@meteorcloudy that's from RBE, which is managed by our build-tools repo. But seems the local (i.e. where `llvm-profdata` runs, with `--TestRunner=sandboxed,local`) having different version of clang.

**Pull request merged**
