### PR TITLE
Cherry-picking "Configurable heap memory release rate - #32589"

### PR DESCRIPTION
**Pull request by sakatkoori**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by nezdolik** [comment]
Don't think we backport features, is it possible to upgrade to Envoy version that contains the feature?

**Comment by phlax** [comment]
branches are currently not working - trying to resolve that now - should be back up and running by early next week

**Comment by sakatkoori** [comment]
> Don't think we backport features, is it possible to upgrade to Envoy version that contains the feature?

No, it is not possible, that is the reason trying for backport.

**Comment by nezdolik** [comment]
> @sakatkoori we don't backport features, only bug/security fixes. Best course of action for you would be either to upgrade or to maintain a private build for v1.29+memory release feature.

**Pull request closed without merging**
