### PR TITLE
Sipproxy update for routing affinity

### PR DESCRIPTION
**Pull request by dorisd0102**
Commit Message: update the routing affinity in sip proxy
Additional Description: NA
Risk Level: Medium
Testing: unit test & manual testing
Docs Changes: update sip proxy docs
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

@durd07 @nearbyfly @dorisd0102

### CODE REVIEW

**Comment by dorisd0102** [comment]
@lizan please help to review this code change of sip proxy routing enhancement. Thanks.

**Comment by dorisd0102** [comment]
@lizan Hi, this code is pending for your review. Thanks.

**Comment by alyssawilk** [comment]
Sorry, Lizan has been out sick.  Would one of the folks you tagged be up for reviewing in the interim? There's definitely things to be cleaned up, like I think the spelling additions aren't necessary and are due to commented out code which could be cleaned up etc.
/wait

**Comment by dorisd0102** [comment]
@durd07 Could you help to review this change first? It is mainly for routing affinity enhancement. Thanks.

**Comment by dorisd0102** [comment]
@alyssawilk I just update based on your comments and this PR is also reviewed by @durd07 and @dorisd0102. Thanks.

**Review by durd07 — APPROVED** [review]

**Comment by alyssawilk** [comment]
Great, thanks!  I think @lizan is back so I'll let him do the merge

**Comment by lizan** [comment]
Can you resolve conflicts?

**Comment by durd07** [comment]
> Can you resolve conflicts?
@lizan the conflict has been resolved. thanks.

**Review by lizan — APPROVED** [review]

**Pull request merged**
