### PR TITLE
upstreamHttpProtocol: choose HTTP11 when use_downstream_protocol_config is enabled and downstream protocol is HTTP10.

### PR DESCRIPTION
**Pull request by doujiang24**
Commit Message:
Additional Description:
Otherwise, we'll hit assert in allocateConnPool.

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by alyssawilk** [comment]
Sorry I'm not the assigned.  @lizan please make sure new PRs are assigned promtly.
doujiang24 Can you explain the context you hit this assert?  While Envoy supports HTTP/1.0 downstream I didn't think one could configure Envoy to send it upstream so I'm a bit confused how this was hit.
/wait-any

**Comment by doujiang24** [comment]
Oh, thanks, your suggestion is the proper way.

**Review by alyssawilk — APPROVED** [review]
Code looks good.  Can you please update the PR description as well?

**Comment by doujiang24** [comment]
Thanks, updated the PR title and description.

**Pull request merged**
