### PR TITLE
docs: add search extension

### LINKED ISSUE #15934: Inconsistent Search Results Behaviour
*Title*: 
*On the envoy docs, search results are inconsistent across similar search terms.*

*Description*:
I noticed when searching for [ip tagging](https://www.envoyproxy.io/docs/envoy/v1.17.0/api-v3/extensions/filters/http/ip_tagging/v3/ip_tagging.proto.html), that I could only find the page when i matched text in the qualified names referenced on the page.   Other pages I could find by matching any text on the page.

*Repro steps*:
.
_I reproduced the below behaviour on firefox, chrome, and safari. I did not test on all versions, but reproduced using latest, 1.17.1, 1.16.1, and 1.13.1_
- in the search field of [the docs](https://www.envoyproxy.io/docs/envoy/latest/) enter any of these terms: "ip tagging", "ip tag", "ip" and note the results.
- enter "iptag" and note the results.
- enter "kafka broker", "kafka", "kafka b", "emitting results", then note results.

The first set of terms will not bring up the ip tagging page.  "iptag" will return the page by matching on the qualified names in the page.  Any of the last terms will bring up the correct [kafka broker page](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/kafka_broker/v3/kafka_broker.proto.html) among its results.

*Admin and Stats Output*:
n/a

*Config*:
n/a

*Logs*:
n/a

*Call Stack*:
n/a

### PR DESCRIPTION
**Pull request by daixiang0**
Commit Message:

Search extension would optimize search logic.

Fix #15934

Additional Description:
Risk Level: low

### CODE REVIEW

**Comment by phlax** [comment]
hi @daixiang0 you will need to fix DCO 

also, its conflicting on docs/conf.py - do you want to rebase to master

**Comment by daixiang0** [comment]
Sorry for mistakes, now they pass.

**Comment by phlax** [comment]
no problem. When the docs are rendered we can take a look...

**Comment by daixiang0** [comment]
Why no readthedocs build/review here? It would be helpful for review.

**Comment by phlax** [comment]
its not actually hosted on readthedocs - but we do have pre-submit rendering.

once they are built ill post the link

**Comment by daixiang0** [comment]
Thanks for quick input.

**Comment by daixiang0** [comment]
How can I add python dependence with format in envoy?

**Comment by phlax** [comment]
probs the easiest is to use `pip-compile` to automatically generate the hashes

currently most of the requirements files have been created by hand (ie not using pip-compile and adding hashes manually) - altho in this case i have just added  a PR which does use pip-compile for this requirements file specifically

to add your dependency...

- get the current version from pypi
- add the dependency in the reqs file like `mydep==X.Y.Z`
- install pip-compile - eg with pip
- run `pip-compile --generate-hashes docs/requirements.txt`

**Comment by phlax** [comment]
@daixiang0 this is failing as you didnt actually add the dependency before running `pip-compile`

doing a bit of further research on this i think the pypi package you are trying to add is this one https://github.com/readthedocs/readthedocs-sphinx-search

its not clear to me whether this will work outside of readthedocs - which we are not hosted by

it may be that it works with the rtd theme - which we do use - but it would then tie us to that theme

the other issue im thinking is that this module doesnt appear to support multicore sphinx/rst builds - which we dont currently use but would like to

try adding the correct package to requirements and if it works we can figure out whether the pros outweigh the cons

**Comment by daixiang0** [comment]
I install at local by pip while I can not add it by pip-compile :(

**Comment by phlax** [comment]
follow the steps here https://github.com/envoyproxy/envoy/pull/16093#issuecomment-823900326

**Comment by daixiang0** [comment]
I get key issue about why I failed to add deps, there is no requirement_in and `pip-compile` can not add deps with generated requirement 
 files. refer to [doc](https://github.com/jazzband/pip-tools#should-i-commit-requirementsin-and-requirementstxt-to-source-control)

**Comment by phlax** [comment]
you dont need requirements,in etc

try this:

```console
$ echo readthedocs-sphinx-search > myrequirements.txt
$ pip-compile --generate-hashes myrequirements.txt 
```

and then check `myrequirements,txt`

**Comment by daixiang0** [comment]
Seems my `pip-compile` version may be higher than your:
```
(venv) root:[docs]$  pip-compile --generate-hashes myrequirements.txt
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --generate-hashes myrequirements.txt
#
readthedocs-sphinx-search==0.1.0 \
    --hash=sha256:5c0a90068c9c0ca639aa3a1c14a7fe8587b0332f2349bc3fd86b968ca82db238 \
    --hash=sha256:7ed45d83b11af9681d5439529c7fbd4289c5be3f9ac4688436e28cb669da87a2
    # via -r myrequirements.txt
```

It would add some comment. Anyway, I add hash by hand.

**Comment by phlax** [comment]
> version may be higher than your:

its the same - i just copied the commands

>  I add hash by hand.

great. lets see if the docs build

**Comment by phlax** [comment]
docs are rendered here https://storage.googleapis.com/envoy-pr/16093/docs/index.html

**Comment by daixiang0** [comment]
This extension does not work :(

**Comment by phlax** [comment]
you need to enable it in `conf.py`

also - once you have reviewer/s please dont force push

**Comment by phlax** [comment]
another issue i think we will have if we enable this https://github.com/readthedocs/readthedocs-sphinx-search/issues/82

**Comment by daixiang0** [comment]
Ohh, I miss it, let's try again.

**Comment by phlax** [comment]
yep - it turns out it does need to be on rtd for this extension to work (at least out of the box)

from my browser console

```
[INFO] Docs are not being served on Read the Docs, readthedocs-sphinx-search will not work.
```

**Comment by phlax** [comment]
@daixiang0 my feeling is close this PR 

if you are willing to work on the original bug #15934 - lets look at tweaking the search config - or at a push adding a `SearchAdapter`

**Comment by daixiang0** [comment]
Let's close.

**Pull request closed without merging**
