### PR TITLE
Fix/build outlier detection

### PR DESCRIPTION
**Pull request by jparklab**
This PR contains changes in https://github.com/envoyproxy/envoy/commit/f3f58333f161199946522e4dcdb0c4048e1848e8 with a fix for a compilation error. I verifed the test builds and runs successfully.

Commit Message: Fix a compilation error in test/common/upstream/outlier_detection_impl_test.cc
Additional Description: This fixes build error of https://github.com/envoyproxy/envoy/commit/f3f58333f161199946522e4dcdb0c4048e1848e8 (https://github.com/envoyproxy/envoy/pull/19205) 
Risk Level: Low

### CODE REVIEW

**Comment by rojkov** [comment]
/assign @adisuissa 
Adi, could you please check once again? and I'll merge the PR.

**Review by adisuissa — APPROVED** [review]
Code changes LGTM, thanks for fixing this!

**Review by rojkov — APPROVED** [review]
Thank you for fixing it again!

**Pull request merged**
