### PR TITLE
build: include validation listener manager in the envoy exe build

### LINKED ISSUE #26822: envoy configuration validate error (v 1.26.0)
#>  docker run --rm -d envoyproxy/envoy:v1.26.0

------ in docker container ------------
#>  root@f7e414ec5303:/# ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
envoy          1       0  0 00:56 ?        00:00:00 envoy -c /etc/envoy/envoy.yaml
root          31       0  0 00:56 pts/0    00:00:00 bash
root          50      31  0 00:57 pts/0    00:00:00 ps -ef

root@f7e414ec5303:/#  envoy --mode validate -c /etc/envoy/envoy.yaml
[2023-04-19 00:57:41.979][51][critical][main] [source/server/config_validation/server.cc:66] error initializing configuration '/etc/envoy/envoy.yaml': Didn't find a registered implementation for name: 'envoy.listener_manager_impl.validation'
root@f7e414ec5303:/#

### PR DESCRIPTION
**Pull request by soulxu**
Commit Message: build: include validation listener manager in the envoy exe build
Additional Description:
Risk Level: low
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features:
Fixes #26822

### CODE REVIEW

**Comment by soulxu** [comment]
cc @phlax @alyssawilk 

Wasn't sure we have a way to test this

**Review by htuch — APPROVED** [review]

**Comment by htuch** [comment]
@phlax any thoughts on how to prevent this kind of regression in CI?

**Comment by phlax** [comment]
not sure but im thinking more about how to remove this

**Comment by soulxu** [comment]
> not sure but im thinking more about how to remove this (edit: qualifying this remark, for testing purposes im trying to get the minimal deps possible)
> 
> what is the symptom of not including this? - im guessing no current tests fail

Yes, no test can cover this. Should we let the integration test depends on `envoy_main_common_lib`?

**Comment by soulxu** [comment]
the websocket example keep failure, but it shouldn't be related.

**Review by phlax — APPROVED** [review]
lgtm, thanks @soulxu

**Comment by phlax** [comment]
aplogies i didnt see the "Fix #26822" at first, now i understand what the symptom is

> Yes, no test can cover this. Should we let the integration test depends on envoy_main_common_lib?

not sure i follow exactly - currently `//test:main` pulls in a huge amount - but surprisingly not this lib

```console
$ bazel cquery 'deps(//test:main)'  | grep -E "entry_lib|common_lib"
...
```

i think we do want something to test this - perhaps we can add a validation sandbox, or perhaps just some other integration tests for the finished binary

**Comment by soulxu** [comment]
> aplogies i didnt see the "Fix #26822" at first, now i understand what the symptom is
> 
> > Yes, no test can cover this. Should we let the integration test depends on envoy_main_common_lib?
> 
> not sure i follow exactly - currently `//test:main` pulls in a huge amount - but surprisingly not this lib
> 
> ```
> $ bazel cquery 'deps(//test:main)'  | grep -E "entry_lib|common_lib"
> ...
> ```
> 
> i think we do want something to test this - perhaps we can add a validation sandbox, or perhaps just some other integration tests for the finished binary

thanks, I will take a look at it

**Comment by phlax** [comment]
great, thanks - please avoid adding anything as a general test dep and only add for the test that actually needs it (apologies if this is obvious, but im trying to unpick that situation atm)

**Pull request merged**
