### PR TITLE
wasm: use wasm_cc_binary from cpp-sdk and simplify BUILD rules

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Review by PiotrSikora — DISMISSED** [review]
cc @bianpengyuan

**Comment by lizan** [comment]
@envoyproxy/dependency-shepherds friendly ping.

**Review by bianpengyuan — COMMENTED** [review]
I think you can remove the js file as https://github.com/envoyproxy/envoy/pull/14020/files#diff-ff626466deb30eedb4d29000b21554f3ed53a7825ce3229e1f4e6de9161fcbed and emscripten toolchain dep?

**Comment by lizan** [comment]
No you can't remove emscripten toolchain dep, that's where #14020 CI fails. The glue js is already removed.

**Review by bianpengyuan — APPROVED** [review]

**Comment by bianpengyuan** [comment]
@lizan Actually looks like the js file is still there: https://github.com/envoyproxy/envoy/blob/master/source/extensions/common/wasm/ext/envoy_wasm_intrinsics.js

**Review by moderation — CHANGES_REQUESTED** [review]

**Review by htuch — APPROVED** [review]
/lgtm deps

**Pull request merged**
