### PR TITLE
kafka: 2.4.0 support - add support for new data types added in 2.4

### PR DESCRIPTION
**Pull request by adamkotwasinski**
Description:
Provide codec support for data types added in 2.4.0.

In detail, we Kafka 2.4 added some new things in protocol:
* variable-length uint32
* new _compact_ strings / byte-arrays / generic arrays that keep length using this varint, instead of fixed-len types
* predefined "tagged_fields" structure (that's very similar to generic array, but doesn't do the +1 length)

This PR should not have any impact on existing codebase, just the volume of changes (if everything was posted at once) is IMHO too large to comfortably review.
Relates to https://github.com/envoyproxy/envoy/issues/2852

These deserializers are working with 2.4 request types (they are not part of this PR as I'm still working on that and want to make another PR with them).
 
Risk Level: Low
Testing: Automated unit tests; embedded integration test (ensures compatibility with 2.3 client); manual tests with 2.3 client
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by adamkotwasinski** [comment]
All right, so now the json files that are bundled with 2.4 should be okay to process, but we are now ignoring "flexible version" messages, as these things will need more C++ code (e.g. deserializer for VARINT values etc.).

/wait

**Comment by junr03** [comment]
@adamkotwasinski are you waiting on a review here, or still iterating?

**Comment by adamkotwasinski** [comment]
@junr03 still iterating, didn't expect that build failure!
will assign the reviewer when I'm done

**Comment by adamkotwasinski** [comment]
This PR should not have any impact on existing Kafka protocol coverage, as the new classes are not yet referenced from (generated) requests.h / responses.h protocol files.

It can be noticed that there's some duplication here, as we are handling very similar data types all the time (e.g. (nullable) (compact) byte array). I will want to revisit this place to refactor it later, to avoid PR noise.

/assign @mattklein123 
/assign @junr03

**Comment by moderation** [comment]
@adamkotwasinski will the dependency updates come in a follow up PR?
- https://github.com/dpkp/kafka-python/releases/tag/2.0.0
- https://github.com/apache/kafka/releases/tag/2.4.0
- https://github.com/apache/kafka/releases/tag/2.4.0

**Comment by adamkotwasinski** [comment]
@moderation yes - when I'm done with https://github.com/envoyproxy/envoy/pull/10000

**Pull request merged**
