### PR TITLE
build: update jinja to 2.10.1.

### PR DESCRIPTION
**Pull request by htuch**
GitHub was complaining that 2.10 was problematic security wise; I don't
think it's an issue in our environment, but this should make the
warnings go away.

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

**Comment by moderation** [comment]
Prior to 2.10.1 they provided developer generated tars and shas. 2.10.1 doesn't have these so if we want to pull into `repository_locations.bzl` we need to change the download URL. Should we add that dependency to this PR? https://github.com/pallets/jinja/releases/tag/2.10.1

**Comment by htuch** [comment]
@moderation I'm not so concerned about bumping to 2.10.1 for the Bazel side, since this is only test code consuming, but I think it would be a valuable followup to ensure that we are able to maintain consistent versions of Jinja going forward. I wonder if we can mechanically extract the version and verify it in some test from the requirements.txt and repository_locations.bzl.

**Comment by mattklein123** [comment]
Going to merge this to remove the warning. Let's definitely get the other issue opened per @junr03

**Comment by htuch** [comment]
Tracking at https://github.com/envoyproxy/envoy/issues/6634

**Pull request merged**
