### PR TITLE
examples/verify-common.sh: hide grep output

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long Dai <long0dai@foxmail.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message:

Hide grep output since it is what we expected, no need to print again.

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@daixiang0 im not sure of the benefit of this - i think its helpful to see the grep output - did you have a reason for suggesting this change ?

**Comment by daixiang0** [comment]
Since we expect it has, print the result it has is useless I think.

**Comment by daixiang0** [comment]
ping @phlax

**Comment by phlax** [comment]
@daixiang0 i dont think this is helpful 

i think it *is* helpful to see the grep output when running the `verify.sh` script

**Comment by daixiang0** [comment]
I think it is helpless since if succeed, the grep output is what we expect, if failed, the grep output is none. For both side, it do not help debug.

**Comment by phlax** [comment]
> I think it is helpless since if succeed, the grep output is what we expect, if failed, the grep output is none. For both side, it do not help debug.

its not about debugging - its about running the script and seeing what it is doing without having to read the source code

**Comment by phlax** [comment]
cool - added a ticket for it here #16747

**Pull request closed without merging**
