### PR TITLE
docs: fix fav icon

### PR DESCRIPTION
**Pull request by mattklein123**

### CODE REVIEW

**Comment by htuch** [comment]
Where is the favicon stored?

**Comment by mattklein123** [comment]
What do you mean? It's in this PR.

**Comment by htuch** [comment]
Whoops, missed that. Is the favicon compliant with the new logo? ;)

**Comment by mattklein123** [comment]
It's generic, yes it still works.

**Comment by htuch** [comment]
Just looked, it is!

**Pull request merged**
