### PR TITLE
[admin] extract logs and profiler handlers to separate classes

### PR DESCRIPTION
**Pull request by rulex123**
Description: extract logging and profiling-related handlers from `admin.h|cc` and into separate classes (part of #5505 )
Risk Level: low
Testing: pre-existing tests
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by mattklein123** [comment]
> @mattklein123 I'm wondering, is there anything under source/server/http that is not for the admin endpoint? I wonder if we should rename that directory sourcer/server/admin. Also note that in the future the admin handling may occur via some gRPC mechanism in addition to via http, and in fact it's already available via direct call from outside the server, bypassing HTTP. WDYT?

You read my mind, I was going to suggest renaming the directory when this was complete. Sounds great. Agreed we can do as a follow up so should we just merge this?

**Comment by jmarantz** [comment]
yup, follow-up would be great.

**Comment by rulex123** [comment]
Cool, will do a follow-up PR to rename the directory.

**Pull request merged**
