### PR TITLE
Allow specifying samplers for the OpenTelemetry tracer via a new configuration.

### LINKED ISSUE #29578: OpenTelemetry tracer - Hability to configure a custom sampler
*Description*:

The OpenTelemetry project defines the concept of a [Sampler API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampler). A sampler allows controlling the spans you send to your observability backend, resulting in many benefits, such as lowering costs.

A sampler is associated with a `TracerProvider` in OpenTelemetry and there's a few [built-in samplers](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#built-in-samplers).

In Envoy, we have the [OpenTelemetry tracer](https://github.com/envoyproxy/envoy/tree/main/source/extensions/tracers/opentelemetry), which can be seen as similar to the `TracerProvider` in OTel. The OTel tracer in Envoy is not flexible in regards to sampling. It only "forwards" the tracing decision that is passed down from Envoy via the `Tracing::Decision tracing_decision`. From my understanding that's a "custom" thing, that is also based on an "request id" https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/request_id/uuid/v3/uuid.proto#envoy-v3-api-field-extensions-request-id-uuid-v3-uuidrequestidconfig-use-request-id-for-trace-sampling. Meaning, this is not really "compliant" with what the OpenTelemetry project defines.

Users of OTel might want to control sampling in different ways, following the samplers that the OTel project defines. Moreover, observability vendors might also want to offer their own samplers which aligns with the decisions done by monitoring Agents for example, resulting in a higher chance of having complete traces, and be able to achieve things such as extracting metrics from spans.

By having the flexibility to configure a custom sampler in the OpenTelemetry tracer in Envoy, users have then full control on the volume of data it produces.

*Feature request*

1. Introduce a new interface inside the `opentelemetry` folder for a sampler. The interface would follow the [Sampler interface](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampler) as defined in the OpenTelemetry specification. It would leverage the Envoy extension framework.

2. When `startSpan` is called, the OpenTelemetry tracer in Envoy would then check if it was configured with a custom sampler. If it was, it defers the sampling decision to it, otherwise it falls back to the current behavior of using the `Tracing::Decision tracing_decision`.

3. This then allows anyone (Cloud vendors, Observability back-ends etc) to define their own samplers in a new folder `tracers/opentelemetry/samplers`

4. Allow the sampler to be configured by the user: Something like this:

```yaml
tracing:
  provider:
    name: envoy.tracers.opentelemetry
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
      sampler:
        name: envoy.opentelemetry.samplers.ParentBasedSampler
```

I believe the addition of this interface will benefit everyone and will open up for a lot of great opportunities in the observability space for Envoy.

### PR DESCRIPTION
**Pull request by samohte**
**Commit Message:** Allow specifying samplers for the [OpenTelemetry tracer](https://github.com/envoyproxy/envoy/tree/main/source/extensions/tracers/opentelemetry) via a new configuration. Add [AlwaysOnSampler](https://opentelemetry.io/docs/specs/otel/trace/sdk/#alwayson) as reference implementation.
**Additional Description:** The OpenTelemetry project defines the concept of a [Sampler API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampler). This PR adds a generic interface to allow to implement a sampler which is used in the existing [OpenTelemetry tracer](https://github.com/envoyproxy/envoy/tree/main/source/extensions/tracers/opentelemetry). The change allows to add different samplers in the future, e.g. probabilistic sampler, vendor specific sampler, .. 
An [AlwaysOnSampler](https://opentelemetry.io/docs/specs/otel/trace/sdk/#alwayson) is added as reference implementation.
**Risk Level:** Low
**Testing:** multiple unit test, no functional 
**Docs Changes:** Added  _OpenTelemetry Samplers_ to trace overview page (see change set)
**Release Notes:** N/A
**Platform Specific Features:** N/A
Fixes #29578

### CODE REVIEW

**Comment by joaopgrassi** [comment]
@htuch Thomas works with me in Dynatrace, this is the initial/foundation Sampler addition we discussed in Slack.

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks LGTM. Can you add some type of integration test for this? Thank you.

/wait

**Comment by samohte** [comment]
> Thanks LGTM. Can you add some type of integration test for this? Thank you.
> 
> /wait
Thanks for your feedback. I have added an integration test following https://github.com/envoyproxy/envoy/blob/main/test/integration/README.md. The test uses the opentelemetry tracer with the AlwaysOnSampler.

**Comment by joaopgrassi** [comment]
@mattklein123 hi! We pushed an integration test. Should be good for another look. Thank you!

**Comment by mattklein123** [comment]
Can you merge main please?

/wait

**Comment by joaopgrassi** [comment]
> Can you merge main please?

@mattklein123 done!

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
