### PR TITLE
Adding API to disable ext_proc immedate response

### PR DESCRIPTION
**Pull request by yanjunxiang-google**
This is the API change to address issue: https://github.com/envoyproxy/envoy/issues/28698

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by tyxia — APPROVED** [review]
LGTM, Thanks!

If review/merge of this PR takes longer, we probably can consider starting/adding the implementation to this PR.

**Comment by yanjunxiang-google** [comment]
@envoyproxy/api-shepherds PTAL

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
