### PR TITLE
Ext proc & authz duration stats in custom access logs [Issue #19255]

### PR DESCRIPTION
**Pull request by llu94**
Risk Level: low
Testing: integration
Docs Changes: n/a
Release Notes: inline

Issue Link: https://github.com/envoyproxy/envoy/issues/19255

### CODE REVIEW

**Comment by phlax** [comment]
hi @llu94 thanks for this, can you fix DCO please

also, there is trailing whitespace in the PR which is failing the formatting checks - best to set your editor with:

- no trailing whitespace
- newline at end of all files
- no mixed preceding spaces and tabs (or just no tabs)

**Comment by llu94** [comment]
> hi @llu94 thanks for this, can you fix DCO please
> 
> also, there is trailing whitespace in the PR which is failing the formatting checks - best to set your editor with:
> 
>     * no trailing whitespace
> 
>     * newline at end of all files
> 
>     * no mixed preceding spaces and tabs (or just no tabs)

I think I fixed all the formatting issues and corrected some issues I had with the signoffs. Please take another look.

**Comment by phlax** [comment]
seems like there are some further formatting issues - diff produced by ci is here https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/96663/artifacts?artifactName=format&api-version=6.0&%24format=zip

**Comment by llu94** [comment]
> seems like there are some further formatting issues - diff produced by ci is here https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/96663/artifacts?artifactName=format&api-version=6.0&%24format=zip

Got it. Will comment when I fix it.

**Comment by llu94** [comment]
@phlax I am in a bit of a catch-22 here. The changes you showed me from Azure-Ci are changes that the ./tools/code_format/check_format.py tool won't let me push commits without. What should I do?

**Comment by phlax** [comment]
hi @llu94 this can be a pain to get right, but should work

there are still a couple of formatting issues, if you click on "details" for the failing (format) check, and the click through to azure, you should be able to get the diff from the CI artefacts

**Comment by esmet** [comment]
I'm not sure we should expose ext_auth and ext_proc details in the stream_info any more than we have to. Would it be possible to emit these timings as dynamic metadata? We'd then tell users to configure their access log formats to read those dynamic metadata values.

**Comment by llu94** [comment]
> I'm not sure we should expose ext_auth and ext_proc details in the stream_info any more than we have to. Would it be possible to emit these timings as dynamic metadata? We'd then tell users to configure their access log formats to read those dynamic metadata values.

I don't think sending timings would be a security issue. Did you have another PR in mind as a reference for emitting this data as dynamic metadata?

**Comment by llu94** [comment]
> hi @llu94 this can be a pain to get right, but should work
> 
> there are still a couple of formatting issues, if you click on "details" for the failing (format) check, and the click through to azure, you should be able to get the diff from the CI artefacts

I'm honestly at a loss here. The format checking python script and the format_pre script are forcing to me make contradictory/mutually exclusionary formatting changes.

**Comment by phlax** [comment]
im looking at the diff now and i dont see anything that it introduces that would fail the pre_format check

im thinking there is an editor involved

did you set your editor to auto fix the issues i posted above ?

can you download the current diff and use `git apply` to apply it, that should resolve the issue i think

**Comment by llu94** [comment]
> im looking at the diff now and i dont see anything that it introduces that would fail the pre_format check
> 
> im thinking there is an editor involved
> 
> did you set your editor to auto fix the issues i posted above ?
> 
> can you download the current diff and use `git apply` to apply it, that should resolve the issue i think

I'm using VS Code and I went into preferences and changed all the settings related to the  things you mentioned. Running the git apply method now.

**Comment by llu94** [comment]
Code coverage is below limit for stream_info namespace as per latest CI run. Will add additional coverage.

**Comment by esmet** [comment]
> > I'm not sure we should expose ext_auth and ext_proc details in the stream_info any more than we have to. Would it be possible to emit these timings as dynamic metadata? We'd then tell users to configure their access log formats to read those dynamic metadata values.
> 
> I don't think sending timings would be a security issue. Did you have another PR in mind as a reference for emitting this data as dynamic metadata?

I should have mentioned that I was commenting on this from the perspective of code abstractions and not from a security perspective.

Using dynamic metadata is relatively straightforward (e.g. https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/ext_authz/ext_authz.cc#L212) and would require no changes to the stream info. That's a win since stream_info is part of the core while ext_authz/proc are extensions.

The downside is that dynamic metadata is dynamic and untyped, but I think for diagnostic information like this it is a great fit.

**Comment by llu94** [comment]
> 



> > > I'm not sure we should expose ext_auth and ext_proc details in the stream_info any more than we have to. Would it be possible to emit these timings as dynamic metadata? We'd then tell users to configure their access log formats to read those dynamic metadata values.
> > 
> > 
> > I don't think sending timings would be a security issue. Did you have another PR in mind as a reference for emitting this data as dynamic metadata?
> 
> I should have mentioned that I was commenting on this from the perspective of code abstractions and not from a security perspective.
> 
> Using dynamic metadata is relatively straightforward (e.g. https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/ext_authz/ext_authz.cc#L212) and would require no changes to the stream info. That's a win since stream_info is part of the core while ext_authz/proc are extensions.
> 
> The downside is that dynamic metadata is dynamic and untyped, but I think for diagnostic information like this it is a great fit.

I took a look at what you were talking about and I think you are right. I will take a day or two and rework this PR in line with your comments.

**Comment by llu94** [comment]
As per commentary in this PR and the issue. I am changing the implementation. Closing this branch.

**Pull request closed without merging**
