### PR TITLE
tools: Improve the error message in tools/docs/rst_check.py for invalid backticks

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
tools: Improve the error message in tools/docs/rst_check.py for invalid backticks

Risk Level: Low
Testing: None
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
@phlax  I changed the error message and verified that I see the message when I run the tool. I noticed that it looks like there are tests which I would expect to fail and need to be changed. However, this seems to pass:

`ev test //tools/docs:tests/test_rst_check.py`

Any idea what I'm doing wrong?

**Comment by alyssawilk** [comment]
where I couldn't answer what was off 5 minutes ago, I'd now suggest checking what the precheck_tooling ci does ;-)
/wait

**Comment by RyanTheOptimist** [comment]
> where I couldn't answer what was off 5 minutes ago, I'd now suggest checking what the precheck_tooling ci does ;-)
> /wait

Yes! I'm very excited about that :) It seems to run `ci/run_envoy_docker.sh 'ci/do_ci.sh tooling'` which fails locally. Woo hoo! New patch coming soon.

**Review by alyssawilk — APPROVED** [review]

**Review by phlax — APPROVED** [review]
lgtm, thanks @RyanTheOptimist

**Pull request merged**
