### PR TITLE
docs: fix edge example

### PR DESCRIPTION
**Pull request by rgs1**
I copy pasted this today to try something out and it took me a while
to notice that there was no router filter configured.

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

### CODE REVIEW

**Comment by rgs1** [comment]
cc: @phlax

**Comment by rgs1** [comment]
Btw, what's the use case for allowing `http_filters` to be empty or to not have a terminal filter (e.g.: router)?

**Comment by phlax** [comment]
> Btw, what's the use case for allowing http_filters to be empty or to not have a terminal filter (e.g.: router)?

not sure - i have been trying to simplify the config wherever i can - im wondering whether this could/should just be the default

**Comment by snowp** [comment]
I can't really think of a use case of there being no filters, so maybe we can add a pgv validation there? @alyssawilk @mattklein123

**Comment by alyssawilk** [comment]
yeah I think this is fine to land as-is, with a filed issue to follow-up on pgv validation.

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
