### PR TITLE
WIP deps: Update yaml_cpp

### PR DESCRIPTION
**Pull request by vehre-x41**
Commit Message: deps: Update yaml_cpp
Additional Description:
Signed-off-by: Andre Vehreschild <vehre@x41-dsec.de>
Risk Level: low
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: windows

### CODE REVIEW

**Comment by moderation** [comment]
Related: https://github.com/envoyproxy/envoy/pull/20765. As per https://github.com/envoyproxy/envoy/pull/20765#commitcomment-71124957= it would be good to fix this upstream so we don't need to carry a patch

**Comment by vehre-x41** [comment]
@adisuissa, the compile works now, but tests are failing. I am not sure, what has caused this. I'll look into that on Tuesday.

**Comment by vehre-x41** [comment]
Just checking, if test issues reported by the previous build are already fixed upstream. Sorry, for the big merge.

**Comment by vehre-x41** [comment]
Superceeded by [PR 20886](https://github.com/envoyproxy/envoy/pull/20886) now.

**Pull request closed without merging**
