### PR TITLE
clang tidy: use default member initializers

### PR DESCRIPTION
**Pull request by kyessenov**
Commit Message: use default initializers. This helps when a new constructor is introduced that does not initialize a field.
Risk Level: low
Testing: unit

### CODE REVIEW

**Comment by kyessenov** [comment]
oops, this is a C++20 extension.

**Comment by phlax** [comment]
```console
 Error: fatal error: too many errors emitted, stopping now [-ferror-limit=]
Error: external/envoy/source/common/http/filter_manager.h:189:31: error: default member initializer for bit-field is a C++20 extension [-Werror,-Wc++20-extensions]
```

i think possibly some of the other fixes that clang-tidy suggests might have similar problems - not sure how we resolve that - perhaps we need to exclude some checks or NOLINT some stuff

**Comment by KBaichoo** [comment]
Seems like this is stuck (as is) unless mobile moves to C++20. Should we just lint-skip it instead until that is figured out. I'm not sure what the blocker is for mobile.

**Comment by kyessenov** [comment]
I suggest we wait for mobile to move to C++20. It's waiting for a newer NDK release. Another one should be imminent based on the trends in https://developer.android.com/ndk/downloads/revision_history.

**Pull request closed without merging**
