### PR TITLE
http: seperate inline headers into independent list

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: http: seperate inline headers into independent list
Additional Description:

An exloratory refactor/fix to the HTTP header map. 

**The aim of this PR is to ensure the inline headers will not be added to lazy map and the number of inline headers will not be taken account in when make the lazy map creation decision.**

**This is not ready for merge. Just for discussion with the community.**

1. This PR split one header list to two, one for inline headers and one for normal headers.
2. Only normal headers will be taken account in when try to make the lazy map.

Risk Level: mid.
Testing: n/a.
Docs Changes: n/.a
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
I didn't add the runtime guard. Because the order of headers with different name never be kepted because the pseudo headers will always in the front of the list. So I assume it doesn't matter. cc @adisuissa

**Comment by wbpcode** [comment]
Another possible solution to our aim is to mark every inline header with a single bool, but it may bring much more memory overhead (esp considering the alignment).

**Comment by adisuissa** [comment]
> I didn't add the runtime guard. Because the order of headers with different name never be kepted because the pseudo headers will always in the front of the list. So I assume it doesn't matter. cc @adisuissa

Per the spec the pseudo headers must come before. Not in the spec, but still desired ,is to keep the order of the headers as they were.

**Comment by wbpcode** [comment]
> > I didn't add the runtime guard. Because the order of headers with different name never be kepted because the pseudo headers will always in the front of the list. So I assume it doesn't matter. cc @adisuissa
> 
> Per the spec the pseudo headers must come before. Not in the spec, but still desired ,is to keep the order of the headers as they were.

@adisuissa I mean because this rule, **the order of original headers has been broken**. For example, the `host` header will be moved to the front of the header list.

Anyway, if this is your strong concern, I will try to add a runtime guard. 😸

**Comment by adisuissa** [comment]
> @adisuissa I mean because this rule, **the order of original headers has been broken**. For example, the `host` header will be moved to the front of the header list.
> 
Yeah, pseudo header fields must come before the non-pseudo headers (per the [rfc](https://datatracker.ietf.org/doc/html/rfc9113#section-8.3)).
Nonetheless, we would like the order in each subgroup (the pseudo headers and non-pseudo headers) to be kept.

> Anyway, if this is your strong concern, I will try to add a runtime guard. 😸
This will need to be more permanent than a runtime guard, and should probably be a bootstrap field.

**Comment by wbpcode** [comment]
Thanks for your review/response. I got it. I will back to this PR after the inline map is done. 

/wait

**Pull request closed without merging**
