### PR TITLE
access_log: support UPSTREAM_CONNECTION_ID in UDP and TCP tunneling flows

### PR DESCRIPTION
**Pull request by ohadvano**
Additional Description: The following PR: https://github.com/envoyproxy/envoy/pull/31920, added support for ``%UPSTREAM_CONNECTION_ID`` substitution string for access logs. However, it's only supported for HTTP flows. Adding support for UDP and TCP tunneling
Risk Level: low
Testing: unit tests, integration tests
Docs Changes: none
Release Notes: none
Platform Specific Features: none

### CODE REVIEW

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Please add a release note.

/wait

**Comment by ohadvano** [comment]
I updated the changelog, but seems like something is broken with CodeQL step

**Comment by phlax** [comment]
codeql fail is unrelated https://github.com/envoyproxy/envoy/issues/36010

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
