### PR TITLE
[mobile] Add QUIC connection and stream error stats to allow list

### PR DESCRIPTION
**Pull request by RenjieTang**
Commit Message: Add QUIC connection and stream error stats to allow list in mobile
Additional Description: I'm still doing research on other QUIC related stats. But these 2 are definitely necessary
Risk Level: low
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: mobile only

### CODE REVIEW

**Review by abeyad — COMMENTED** [review]
should we add a check in one of the H3 tests in client_integration_test.cc to make sure they are surfaced, similar to https://github.com/envoyproxy/envoy/blob/c11574972860a40de36acf3ab8d930273f5ece65/mobile/test/common/integration/client_integration_test.cc#L1019 ?

**Comment by abeyad** [comment]
Thanks  @RenjieTang !

**Comment by RenjieTang** [comment]
> should we add a check in one of the H3 tests in client_integration_test.cc to make sure they are surfaced, similar to
> 
> https://github.com/envoyproxy/envoy/blob/c11574972860a40de36acf3ab8d930273f5ece65/mobile/test/common/integration/client_integration_test.cc#L1019
> 
> ?

done

**Review by abeyad — APPROVED** [review]

**Pull request merged**
