### PR TITLE
deps: Bump `rules_python` -> 0.13.0

### LINKED ISSUE #23277: Newer release available `rules_python`: 0.13.0 (current: 0.12.0)
Package Name: rules_python@0.12.0
Current Version: 0.12.0@2022-08-29
Available Version: 0.13.0@2022-09-25
Upstream releases: https://github.com/bazelbuild/rules_python/releases

### PR DESCRIPTION
**Pull request by phlax**
Fix #23277 

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by mattklein123 — DISMISSED** [review]

**Comment by phlax** [comment]
i think this failed as `pip_install` has been deprecated (and perhaps more)

**Comment by phlax** [comment]
digging a bit further ...

with the old way of install py deps (`pip_install`) running bazel query on the deps - ie `bazel query 'deps(set(@fuzzing_pip3//...))'` - you see the expected dependencies

using the newer `pip_parse` this returns an empty list - `pip_install` has been deprecated and afaict while still there is now a stub for `pip_parse` 

not getting the dep list appears to be fooing the dependency validation

ill investigate further

**Comment by phlax** [comment]
possibly related to https://github.com/bazelbuild/rules_python/issues/710

i have confirmed that just switching to `pip_parse` without updating `rules_python` throws the same error

**Comment by phlax** [comment]
switching the fuzzing dep to `pip_parse` and correctly configuring it seems to resolve

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
