### PR TITLE
Remove duplicated words

### PR DESCRIPTION
**Pull request by longkb**
Although it is spelling mistakes, it might make an affects while reading.

Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by mattklein123** [comment]
Needs master merge, thanks.

/wait

**Comment by moderation** [comment]
@longkb We should note there has been a history of small spelling change PRs being submitted one at a time in order to game Github statistics. If there are more than one PR, please batch into a larger PR for review.

**Comment by longkb** [comment]
> 
> 
> Needs master merge, thanks.
> 
> /wait

Oops, sorry. I have worked in older version of repo. I will update my PR with master code :)
Thank you so much!

**Comment by longkb** [comment]
> 
> 
> @longkb We should note there has been a history of small spelling change PRs being submitted one at a time in order to game Github statistics. If there are more than one PR, please batch into a larger PR for review.



> 
> 
> @longkb We should note there has been a history of small spelling change PRs being submitted one at a time in order to game Github statistics. If there are more than one PR, please batch into a larger PR for review.

Yes, I see. I will check these duplicated words agains and update if necessary :)
Thank you so much!

**Comment by mattklein123** [comment]
> Can we add a simple check_format regex to scan for this? The script uses Python regexes, https://docs.python.org/3/library/re.html provides the examples of (.+) \1 as a regex for picking out the the. It won't work across lines, but it would probably catch a lot of the main issues here.

+1. This would be a truly valuable contribution vs. just gaming the commit stats. Thanks!

/wait

**Pull request closed without merging**
