### PR TITLE
dep: dependency checker should ignore pre-releases

### LINKED ISSUE #19263: Dependency checker should ignore pre-releases
### description

currently the dependency checker doesnt discriminate pre-releases - eg https://github.com/envoyproxy/envoy/issues/19154

### PR DESCRIPTION
**Pull request by kfaseela**
Signed-off-by: Faseela K <faseela.k@est.tech>

Fixes #19263

### CODE REVIEW

**Comment by kfaseela** [comment]
cc @phlax

**Review by phlax — APPROVED** [review]
lgtm, thanks @kfaseela

**Comment by phlax** [comment]
@moderation any objections to me landing this fix? as explained this essentially reverts to the previous behaviour that we had using the github api `get_latest_release` of ignoring the pre-releases

i think this is what we want, but we could potentially customize it for specific deps - particularly the compgen one that only creates pre-releases

in most cases, even if we were using a pre-release we would be mostly interested in getting onto the release track - potentially we might detect that we are currently using a pre-release and act on that basis

**Comment by moderation** [comment]
This change appears to work well. Now if you can only figure out why the emscripten part goes crazy. All of the other repos correctly work out the latest and report that vs. iterating through all releases.  I can't figure it out
```
github_release:  GitHubRelease(organization='emscripten-core', project='emsdk', version='2.0.8', tagged=True)
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.9@<2020-11-16 22:58:38>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.10@<2020-12-04 16:53:37>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.11@<2020-12-17 22:47:38>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.12@<2021-01-09 15:25:52>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.13@<2021-01-30 02:25:41>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.14@<2021-02-14 19:46:10>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.15@<2021-03-06 07:18:22>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.16@<2021-03-26 02:00:07>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.17@<2021-04-11 00:41:55>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.18@<2021-04-24 01:35:03>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.19@<2021-05-04 22:25:01>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.20@<2021-05-06 21:31:10>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.21@<2021-05-18 15:39:21>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.22@<2021-05-25 14:21:40>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.23@<2021-05-27 01:10:10>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.24@<2021-06-10 16:02:19>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.25@<2021-06-30 17:24:41>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.26@<2021-07-26 22:26:01>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.27@<2021-08-13 02:34:34>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.28@<2021-08-23 20:37:00>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.29@<2021-08-28 00:27:29>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.30@<2021-09-15 19:03:43>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.31@<2021-10-01 23:02:25>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.32@<2021-10-20 00:55:27>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.33@<2021-11-01 22:30:30>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.34@<2021-11-04 21:53:04>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 3.0.0@<2021-11-22 23:09:10>
emscripten_toolchain has a GitHub release date 2020-10-24
```

**Pull request merged**
