### PR TITLE
listener: no io_handle for virtual listener

### LINKED ISSUE #16258: virtual listener should not assign listen socket
`Hard-coded ports cause issues in CI when multiple configurations run on the same machine. See other integration tests for examples of how to do this.`

_Originally posted by @ggreenway in https://github.com/envoyproxy/envoy/pull/15842#discussion_r621562832_

Envoy listener does not listen at the address if the listener doesn't bind to port. However, Envoy call SocketInterfaceImpl::socket() which fails fast if the socket is not available.

### PR DESCRIPTION
**Pull request by lambdai**
The io handle for tcp listener is to drive the accepted connection by event poller.

If the tcp listener doesn't bind to port, the io handle is not required.

Signed-off-by: Yuchen Dai <silentdai@gmail.com>

Commit Message:
Additional Description:
Risk Level: LOW
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
fix #16258
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by wrowe** [comment]
This seems to be an experimental PR, would you tag this is as draft till it's ready for review?

**Comment by lambdai** [comment]
> This seems to be an experimental PR, would you tag this is as draft till it's ready for review?

I think the product code is ready since it doesn't break any.
I guess I need add more tests cases to explain what is improved.

**Comment by lambdai** [comment]
@wrowe This PR is ready to review. Could you take a look? Thanks!

**Review by wrowe — APPROVED** [review]
This looks correct to me, thanks!

**Comment by wrowe** [comment]
Can you update the description to correspond to the final commit message you want, @lambdai, it still reads like a draft.

**Comment by lambdai** [comment]
> Can you update the description to correspond to the final commit message you want, @lambdai, it still reads like a draft.

Updated. Thanks!

**Comment by lambdai** [comment]
Thank you!

**Pull request merged**
