### PR TITLE
Allow prepending access log handler for HTTP stream filter

### LINKED ISSUE #14767: The order of `access_log` handler settings may not be the best.
*Title*: *The order of `access_log` handler settings may not be the best*

*Description*:
Now `access_log` is always executed before each filter log phase of HTTP, which will cause some operations in the log phase of http filter to not take effect in the access_log handler.
Forexample, if the metadata  `xxx :yy` is set in the log phase of HTTP filter, then `%DYNAMIC_METADATA(xxx :yy)%` in access_log format does not work.

[optional *Relevant Links*:]

analysis
====

`access_log` is registered at the [ActiveStream](https://github.com/envoyproxy/envoy/blob/main/source/common/http/conn_manager_impl.cc#L593).

```
ConnectionManagerImpl::ActiveStream::ActiveStream(ConnectionManagerImpl& connection_manager,
                                                  uint32_t buffer_limit) {
  ……
  for (const AccessLog::InstanceSharedPtr& access_log : connection_manager_.config_.accessLogs()) {
    filter_manager_.addAccessLogHandler(access_log); 
  }
  ……
}

```

 each filter log handler of HTTP is registered at the [decodeHeaders](https://github.com/envoyproxy/envoy/blob/main/source/common/http/conn_manager_impl.cc#L999).
```
void ConnectionManagerImpl::ActiveStream::decodeHeaders(RequestHeaderMapPtr&& headers,
                                                        bool end_stream) {
……
 const bool upgrade_rejected = filter_manager_.createFilterChain() == false;   // will call filter_manager_.addAccessLogHandler
……
}
```

The log handler is registered using [push_back](https://github.com/envoyproxy/envoy/blob/main/source/common/http/filter_manager.cc#L470), So it means FIFO.
```
void FilterManager::addAccessLogHandler(AccessLog::InstanceSharedPtr handler) {
  access_log_handlers_.push_back(handler);
}
```

expect
====
So the `access_log` handler may be better to execute after all log handler of http filter.

### PR DESCRIPTION
**Pull request by spacewander**
Commit Message: Allow prepending access log handler for HTTP stream filter
Additional Description: Also change the Golang filter to use this new feature
Risk Level: Low
Testing: Integration
Docs Changes:
Release Notes: Added
Platform Specific Features:
[Optional Runtime guard:]
Fixes #14767
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

CC @doujiang24

### CODE REVIEW

**Comment by spacewander** [comment]
The CI failed because of "tar: 91af38e56cd74a0fae3b2155c9ba4469_archive.tar: Cannot write: No space left on device
":
https://dev.azure.com/cncf/envoy/_build/results?buildId=177029&view=logs&jobId=4930ecaf-18f4-5b3c-dea3-309729c3b3ae&j=4930ecaf-18f4-5b3c-dea3-309729c3b3ae&t=ffac7daa-9351-4709-84b9-6a104105ce04

**Review by zuercher — COMMENTED** [review]
lgtm, but needs main merged

**Comment by spacewander** [comment]
> lgtm, but needs main merged

@zuercher 
Done

**Review by wbpcode — CHANGES_REQUESTED** [review]
this is a little late but I doubt if this a best way to do this.

The new interface results in a new problem: we can not ensure the loggers' order base on the filters' order of `http_filters` configuration.

I think maybe the better way is to make the access logger to be called at end directly.

And other loggers that added by filters will keep their order in filter chain.

This is a behavior change. But I think it's okay and could be guard by a runtime flag.

/wait-any

**Comment by spacewander** [comment]
> this is a little late but I doubt if this a best way to do this.
> 
> The new interface results in a new problem: we can not ensure the loggers' order base on the filters' order of `http_filters` configuration.
> 
> I think maybe the better way is to make the access logger to be called at end directly.
> 
> And other loggers that added by filters will keep their order in filter chain.
> 
> This is a behavior change. But I think it's okay and could be guard by a runtime flag.
> 
> /wait-any

The core reason for me to add a new `prepend` method is that it won't introduce any break change. So it can solve the years-old issue quickly, without more debates.

If a break change is acceptable by several Envoy maintainers, we can also solve this problem by reordering the access log added order.

**Comment by wbpcode** [comment]
Back compatibility is great. But if it is a detail that no one care or we can prove this new design is better, than I think behavior change is acceptable. I think this is why our change logs has a behavior change list and minor behavior change list.

Our access loggers do nothing except flushing log entries. So, I cannot image any one will depends on current logging order. 

An runtime guard is good enough, I think. cc @envoyproxy/senior-maintainers

**Comment by zuercher** [comment]
Thinking about this some more, I agree this doesn't seem like a great idea. I had just skimmed the discussion in #14767 without much thought.

It seems like putting filter-added access loggers ahead of HCM access loggers (e.g. #14767) makes some sense, but this doesn't actually do that. It just allows filters to puts themselves at the head of the queue.

You've changed the golang test to grab the filter's callback to mutate the `StreamInfo` during a call to `AccessLogHandler::log` (notably the `StreamInfo` passed to `log` is const so you couldn't do this in an AccessLogHandler that doesn't also happen to be a filter).

It seems to me that golang HTTP filters should modify dynamic metadata during HTTP decoding/encoding rather than trying to mutate the StreamInfo at log time. I don't think we'd allow a C++-only http filter that did this. It may be the case that there should be a way to register a callback on a filter that occurs before `AccessLogHandler` instances are invoked to indicate a point-in-time when all filters have reached a certain point (e.g. the request is complete) so they can do any final metadata management.

**Comment by wbpcode** [comment]
We have no way to forbid const_cast in extension implemention. Although this is not good practice and some times may dangerous.

**Comment by spacewander** [comment]
> It may be the case that there should be a way to register a callback on a filter that occurs before AccessLogHandler instances are invoked to indicate a point-in-time when all filters have reached a certain point

There is a callback named `onStreamComplete` which runs before `log(AccessLog::AccessLogType::DownstreamEnd)`.

So if the log handler is designed to be read-only, the solution may be to let the wasm/Golang filters utilize the `onStreamComplete` and generate the dynamic metadata here?

**Comment by zuercher** [comment]
> There is a callback named `onStreamComplete` which runs before `log(AccessLog::AccessLogType::DownstreamEnd)`.
> 
> So if the log handler is designed to be read-only, the solution may be to let the wasm/Golang filters utilize the `onStreamComplete` and generate the dynamic metadata here?

If that callback's invocation meets the needs then yes, that seems like a better implementation that doesn't perform actions that are unexpected in an access logger.

**Comment by spacewander** [comment]
Surpassed by https://github.com/envoyproxy/envoy/pull/35742

**Pull request closed without merging**
