### PR TITLE
Few small fixes to allow envoy to compile on ARM32

### PR DESCRIPTION
**Pull request by costinm**
Tested compilation for rasbperry pi and android (the 'endian' change is
required for android NDK - recent androids can compile with 64 bit).

(moved from PR #1781 due to git squashing/DCO issues)

Signed-off-by: Costin Manolache <costin@google.com>

### CODE REVIEW

**Comment by craffert0** [comment]
`#include <endian>` doesn't exist on OS X.

**Comment by costinm** [comment]
Ops, it is required on android - I'll add an ifdef.

**Comment by costinm** [comment]
Sorry for the breakage - since it was just an experiment on using envoy on android, and it doesn't really need mongodb - no need to complicate things with an ifdef, the PR removing it is enough.

**Comment by craffert0** [comment]
No big deal -- there was another unrelated os x breakage, and [1804](https://github.com/envoyproxy/envoy/pull/1804) keeps your change.

**Pull request merged**
