### PR TITLE
docs: fix whitespace typo in transcoder documentation.

### PR DESCRIPTION
**Pull request by psigen**
The documentation for `convert_grpc_status` had two leading spaces in the text following a code block, causing the text to be rendered as part of the code block.

image

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by rojkov** [comment]
Thank you for fixing it! Could you please remove the whitespaces also in api/envoy/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto?

**Comment by psigen** [comment]
> Thank you for fixing it! Could you please remove the whitespaces also in api/envoy/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto?

Sure thing, done in 98c9bc8

**Comment by rojkov** [comment]
Thanks! It seems your commits are missing signoffs (the DCO check is failing). You need to add them with
```
git rebase HEAD~2 --signoff
git push --force-with-lease origin patch-1
```

**Review by adisuissa — APPROVED** [review]
/lgtm api

**Review by phlax — APPROVED** [review]
lgtm, thanks @psigen

**Pull request merged**
