### PR TITLE
test: fix flake in ads_integration_test

### LINKED ISSUE #7089: IpVersionsClientType/AdsIntegrationTest.DuplicateWarmingListeners/1 tsan flakes
Failing infrequently on CI but pretty reproducable with
bazel test  //test/integration:ads_integration_test --config=clang-tsan --runs_per_test=200 --test_arg=--gtest_filter="IpVersionsClientType/AdsIntegrationTest.DuplicateWarmingListeners/1"

Example failure:
https://circleci.com/gh/envoyproxy/envoy/223256?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

Actual tsan warning: https://pastebin.com/zWtG77K2

@fredlas I think this might be related to 6879 - could you take a look?

### PR DESCRIPTION
**Pull request by fredlas**
Fixes #7089 (1500 passing runs)

### CODE REVIEW

**Comment by fredlas** [comment]
Oh dear... looks like the CI infrastructure is broken? ERROR: /source/bazel/repositories.bzl:265:5: no such package '@com_github_google_benchmark//': java.io.IOException: Error downloading [https://github.com/google/benchmark/archive/v1.5.tar.gz]

**Comment by moderation** [comment]
@fredlas The benchmark package changed. Fix is at https://github.com/envoyproxy/envoy/pull/7090

**Comment by fredlas** [comment]
Got it, thanks!

**Pull request merged**
