### PR TITLE
make test/integration:http_subset_lb_integration_test IP version envi…

### PR DESCRIPTION
**Pull request by stevenzzzz**
…ronment aware.

Signed-off-by: Xin Zhuang <stevenzzz@google.com>

Description: fix issue #8284 
Risk Level: LOW 
Testing: unit test
Docs Changes: N/A
Release Notes: N/A
Fixes 8284

### CODE REVIEW

**Comment by zuercher** [comment]
Nothing about this test depends on which IP version is used (except that it fails if IPv4 isn't available). Parameterizing it will just make it take twice as long without any benefit.

What do you think of just replacing `Network::Address::IpVersion::v4` with a call to a static helper function that returns the first value from getIpVersionsForTest()or  just `getIpVersionsForTest().front()`? You can use the `version_` field (from BaseIntegrationTest) to set the address in the config.

**Comment by stevenzzzz** [comment]
> Nothing about this test depends on which IP version is used (except that it fails if IPv4 isn't available). Parameterizing it will just make it take twice as long without any benefit.
I think the use of TestEnvironment::getIpVersionsForTest() will make sure it's tested with available IP versions. I'd actually prefer it has more coverage over different IP versions in case the code behaves differently when backends connection Ip version changes, right now the test finishes in 5s on my box.
> 
> What do you think of just replacing `Network::Address::IpVersion::v4` with a call to a static helper function that returns the first value from getIpVersionsForTest()or just `getIpVersionsForTest().front()`? You can use the `version_` field (from BaseIntegrationTest) to set the address in the config.
This should work, but WDYT we keep it this way.

**Comment by htuch** [comment]
+1 to @zuercher suggestion.

**Comment by stevenzzzz** [comment]
alright, PTAL.
Much smaller change now.

**Pull request merged**
