### PR TITLE
[mobile]Add a method that transfers ownership of HTTP headers to caller

### PR DESCRIPTION
**Pull request by RenjieTang**
Commit Message: Add a method that transfers ownership of HTTP headers to caller
Additional Description: This allows application to get the headers without copying.
Risk Level: Low
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: mobile only

### CODE REVIEW

**Comment by soulxu** [comment]
/wait

for ci

**Review by RyanTheOptimist — APPROVED** [review]
LGTM

**Comment by fredyw** [comment]
FYI, I plan on working removing all these wrappers and use native C++ `Envoy::Http::RequestHeaderMap` (I will do the same thing for trailers as well): https://github.com/envoyproxy/envoy/pull/33298

Eventually everything in `library/cc/headers.[h|cc]` will be removed.

**Pull request closed without merging**
