### PR TITLE
cleanup: Remove unused method ServerConnectionImpl::sendProtocolErrorOld. Uses were removed by #14684

### PR DESCRIPTION
**Pull request by antoniovicente**
Commit Message:
cleanup: Remove unused method ServerConnectionImpl::sendProtocolErrorOld. Uses were removed by #14684

Risk Level: n/a, removing dead code
Testing: n/a, removing dead code
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Review by alyssawilk — APPROVED** [review]

**Comment by asraa** [comment]
Cancelled is really bizarre, I can't figure out how to retest it. Could you try merging main and recommitting? (unless there's some other way to trigger it)

**Pull request merged**
