### PR TITLE
Inhibit attempted copying of missing crypto.if.lib for static win32 build

### PR DESCRIPTION
**Pull request by wrowe**
See discussion at;
https://github.com/envoyproxy/envoy/pull/8280/files/b84fc6bc69677d00bd3f8ddfcbd23efee0e44893#r332278621

This deserves attention by the boringssl bazel build maintainers, solving for short-term.

Signed-off-by: William A Rowe Jr <wrowe@pivotal.io>
Signed-off-by: Yechiel Kalmenson <ykalmenson@pivotal.io>

Description:
Risk Level: Low
Testing: Local on Windows
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by wrowe** [comment]
@lizan per discussion elsewhere, could you look at this?

**Comment by lizan** [comment]
Can you add a line `bazel --bazelrc=windows\.bazelrc build @boringssl//:ssl` to `ci/ci/windows_ci_steps.ps1`? So the build is testing in CI to reduce your moving target.

**Comment by wrowe** [comment]
That's very sensible. We've added other foreign_cc components which are building correctly, and can begin adding other bazel-based dependencies as well as we've reviewed them. This resolves all the issues of accepting this patch?

**Comment by wrowe** [comment]
We've reconfirmed this subset builds correctly on Windows, patched against master. We are likely missing one or more of the msys2 (bash), python, jdk8 or even perhaps go language tooling?

**Comment by wrowe** [comment]
/wait

I don't believe we want this patch as-is because on OS/X I understand we are building all objects dynamic.

**Comment by wrowe** [comment]
Since this was 3 mos stale, I've rebased and force-pushed.

@lizan could you have a look? I guess I misunderstood that everywhere we consuming boringssl we expect it to be simply a static lib dependency.

**Comment by lizan** [comment]
@wrowe can you open a new PR based on this? Since you force-pushed GH doesn't allow me to re-open.

**Comment by wrowe** [comment]
Good to learn that, thanks. Will do so over the weekend.

**Pull request closed without merging**
