### PR TITLE
tidy: Replace x.size() == 0 with x.empty()

### PR DESCRIPTION
**Pull request by jamessynge**
Signed-off-by: James Synge <jamessynge@google.com>

### CODE REVIEW

**Comment by jamessynge** [comment]
Not quite ready for review after all. Will update with a new commit soon.

**Comment by mattklein123** [comment]
@jamessynge if possible can we also change our OSS clang-tidy config to make this an error?

**Comment by jamessynge** [comment]
@mattklein123 I've not modified a clang-tidy config file before, but I think I need to add `readability-container-size-empty` to the WarningsAsErrors list, and possibly also to the Checks list. How does that sound?

**Comment by jamessynge** [comment]
@mattklein123 It might help consistency if we add an `empty` method to `Headers`.

**Comment by mattklein123** [comment]
Sounds good on the headers empty. @lizan can advise on how to edit the clang tidy file.

**Comment by lizan** [comment]
LGTM, feel free to add it to .clang-tidy

**Comment by jamessynge** [comment]
Added to `.clang-tidy` as requested.

**Comment by jamessynge** [comment]
Looks like the change to test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc isn't needed any more. I'm not sure what procedure to use wr.t. updating my PR vs. having @lizan do this during the merge (if that is possible).

**Comment by lizan** [comment]
@jamessynge yeah please merge latest master and resolve conflict.

**Comment by jamessynge** [comment]
Somehow my edit to resolve the conflict in redis_proxy_integration_test.cc didn't actually make it into the commit I pushed. Sigh. Will re-push soon.

**Comment by jamessynge** [comment]
@lizan @mattklein123 I'll add HeaderMap.empty in an upcoming PR (implemented, but I don't want to repeat the check for size() until this PR is merged)

**Comment by lizan** [comment]
LGTM, can you merge master?

**Comment by jamessynge** [comment]
Merged.

**Pull request merged**
