### PR TITLE
[1.17] Update markupsafe-1.1.1 hash

### PR DESCRIPTION
**Pull request by dmitri-d**
This should resolve build failures due to an unexpected checksum for MarkupSafe-1.1.1 pip package

### CODE REVIEW

**Comment by dmitri-d** [comment]
ping @lizan

**Comment by moderation** [comment]
The main branch is now using MarkSafe 2.0.1 - https://github.com/envoyproxy/envoy/blob/main/configs/requirements.txt#L4

Does this change only affect 1.17.x?

/lgtm deps

**Comment by dmitri-d** [comment]
> Does this change only affect 1.17.x?

Yes.

**Comment by lambdai** [comment]
I see the exact failure starting from yesterday. I end up with the exact patch here

**Pull request merged**
