### PR TITLE
owners: add Sotiris

### PR DESCRIPTION
**Pull request by mattklein123**
:tada: thank you @davinci26 for all your work!

### CODE REVIEW

**Comment by mattklein123** [comment]
cc @envoyproxy/maintainers

**Review by jmarantz — APPROVED** [review]
welcome!

**Review by alyssawilk — APPROVED** [review]
Hurrah, and welcome!

**Comment by davinci26** [comment]
Thanks! It's an honour. I am excited to continue working with all of you!

**Review by alyssawilk — COMMENTED** [review]
oh, though mind adding him to .github/actions/pr_notifier/pr_notifier.py in the same PR?

**Comment by phlax** [comment]
welcome @davinci26 !!!

**Comment by mattklein123** [comment]
@alyssawilk updated

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
