### PR TITLE
test: fuzzer binaries should parse gmock flags.

### PR DESCRIPTION
**Pull request by sqkerner**
Description: Parsing gmock flags is important for fuzzers that make use of NiceMock. The mocks log all interactions that are not expected. The volume of logging can be overwhelming. This change allows the use of the flag --gmock_verbose=error, which suppresses these logs.

Risk Level: Low
Testing: Run Fuzzers with the flag --gmock_verbose, see that they change their output level.
Docs Changes: None
Release Notes: None

Signed-off-by: Sam Kerner <skerner@chromium.org>

### CODE REVIEW

**Comment by sqkerner** [comment]
Here is a presubmit error I do not understand:

```
./test/fuzz/fuzz_runner.h:11:10: error: 'compiler_rt/fuzzer/utils/FuzzedDataProvider.h' file not found [clang-diagnostic-error]
#include "compiler_rt/fuzzer/utils/FuzzedDataProvider.h"
            ^
```
[Source](https://dev.azure.com/cncf/envoy/_build/results?buildId=36543&view=logs&j=3bf5ec37-bb6f-5fb6-2cf1-5134dc6106d6&t=41d571fe-3811-578d-07de-68468f467dae&l=1495)

It appears that the presubmit can't read a file in Complier-RT.  This change does not add an include on the file in question.  Reviewers:  What am I missing?

**Comment by asraa** [comment]
> It appears that the presubmit can't read a file in Complier-RT. This change does not add an include on the file in question. Reviewers: What am I missing?

I think there might be something up with clang-tidy... i'm looking in to it

**Comment by asraa** [comment]
I applied this diff to fix the clang-tidy warning, I'm not sure exactly why besides that other external_deps were working @lizan:
```
diff --git a/bazel/repositories.bzl b/bazel/repositories.bzl
index 415455e58..4986bba34 100644
--- a/bazel/repositories.bzl
+++ b/bazel/repositories.bzl
@@ -663,6 +663,10 @@ def _org_llvm_releases_compiler_rt():
         name = "org_llvm_releases_compiler_rt",
         build_file = "@envoy//bazel/external:compiler_rt.BUILD",
     )
+    native.bind(
+      name = "fuzzed_data_provider",
+      actual = "@org_llvm_releases_compiler_rt//:fuzzed_data_provider",
+    )
 
 def _fuzzit_linux():
     _repository_impl(
diff --git a/test/fuzz/BUILD b/test/fuzz/BUILD
index d46ae39a5..a9794393f 100644
--- a/test/fuzz/BUILD
+++ b/test/fuzz/BUILD
@@ -40,6 +40,9 @@ envoy_cc_test_library(
     name = "fuzz_runner_lib",
     srcs = ["fuzz_runner.cc"],
     hdrs = ["fuzz_runner.h"],
+    external_deps = [
+        "fuzzed_data_provider",
+    ],
     deps = [
         "//source/common/common:minimal_logger_lib",
         "//source/common/common:thread_lib",
@@ -49,7 +52,6 @@ envoy_cc_test_library(
         "//source/exe:process_wide_lib",
         "//test/test_common:environment_lib",
         "@com_github_google_libprotobuf_mutator//:libprotobuf_mutator",
-        "@org_llvm_releases_compiler_rt//:fuzzed_data_provider",
     ],
 )
 
diff --git a/test/fuzz/fuzz_runner.h b/test/fuzz/fuzz_runner.h
index e2279365c..3f3cc60aa 100644
--- a/test/fuzz/fuzz_runner.h
+++ b/test/fuzz/fuzz_runner.h
@@ -8,7 +8,7 @@
 #include "libprotobuf_mutator/src/libfuzzer/libfuzzer_macro.h"
 // Bring in FuzzedDataProvider, see
 // https://github.com/google/fuzzing/blob/master/docs/split-inputs.md#fuzzed-data-provider
-#include "compiler_rt/fuzzer/utils/FuzzedDataProvider.h"
+#include "utils/FuzzedDataProvider.h"
 #include "spdlog/spdlog.h"
 
 namespace Envoy {
```

**Comment by sqkerner** [comment]
> Thank! Would you mind commenting a before/after execution speed on local runs with a mock-heavy target, maybe `//test/common/http:conn_manager_impl_fuzz_test`?

Build the binary:

```
$ bazel build //test/common/http:conn_manager_impl_fuzz_test_with_libfuzzer --config asan-fuzzer -c opt
```

Running with the old setting gets 7-11 executions per second:

```
$ bazel-bin/test/common/http/conn_manager_impl_fuzz_test_with_libfuzzer --gmock_verbose=warn |& grep pulse
#32     pulse  cov: 76319 ft: 84636 corp: 27/2557b lim: 4096 exec/s: 10 rss: 284Mb
#64     pulse  cov: 76340 ft: 85878 corp: 49/5093b lim: 4096 exec/s: 11 rss: 332Mb
#128    pulse  cov: 76386 ft: 91483 corp: 76/9900b lim: 4096 exec/s: 9 rss: 427Mb
#256    pulse  cov: 76395 ft: 92642 corp: 122/21Kb lim: 4096 exec/s: 7 rss: 620Mb
```

Running with the new default gets 13-16 executions per second:
```
$ bazel-bin/test/common/http/conn_manager_impl_fuzz_test_with_libfuzzer --gmock_verbose=error |& grep pulse
#32     pulse  cov: 73843 ft: 80455 corp: 28/5747b lim: 4096 exec/s: 16 rss: 250Mb
#64     pulse  cov: 74201 ft: 81716 corp: 41/10632b lim: 4096 exec/s: 16 rss: 297Mb
#128    pulse  cov: 76531 ft: 88285 corp: 72/19Kb lim: 4096 exec/s: 16 rss: 424Mb
#256    pulse  cov: 76667 ft: 90313 corp: 119/33Kb lim: 4096 exec/s: 13 rss: 613Mb
```

> This seems like something we might want as a default when building fuzz targets, would you be able to add it to `.bazelrc` for the `asan-fuzzer` config? But then for our OSS-Fuzz builds, underlyingly we build the targets as `cc_library`, which can't take `args` in the build rule. Is it possible to set GMOCK_FLAG(verbose) to default error (`GMOCK_FLAG(verbose) = "error"`)?

I set the default in code in fuzz_runner.cc.  This applies to fuzzing runs, but not to cases where the binary is used to replay a corpus of tests.  When fuzzing, we want speed.  When replaying, having logs show the details of what is happing is helpfull.

**Comment by sqkerner** [comment]
Re the clang-tidy warning:  Let me know if I should apply that patch, rebase to a point where it is in the tree, or just ignore the errors.

**Comment by lizan** [comment]
@sqkerner @asraa the bind part does nothing. Let's do this patch:

```
diff --git a/bazel/external/compiler_rt.BUILD b/bazel/external/compiler_rt.BUILD
index e75ac2ef26..96d90b46ab 100644
--- a/bazel/external/compiler_rt.BUILD
+++ b/bazel/external/compiler_rt.BUILD
@@ -2,8 +2,6 @@ licenses(["notice"])  # Apache 2

 cc_library(
     name = "fuzzed_data_provider",
-    hdrs = ["utils/FuzzedDataProvider.h"],
-    # This is moving from lib/fuzzer/utils to include/fuzzer after LLVM 9.0.
-    include_prefix = "compiler_rt/fuzzer",
+    hdrs = ["fuzzer/utils/FuzzedDataProvider.h"],
     visibility = ["//visibility:public"],
 )
diff --git a/bazel/repository_locations.bzl b/bazel/repository_locations.bzl
index cebb98e124..306bf7f291 100644
--- a/bazel/repository_locations.bzl
+++ b/bazel/repository_locations.bzl
@@ -302,7 +302,7 @@ REPOSITORY_LOCATIONS = dict(
     org_llvm_releases_compiler_rt = dict(
         sha256 = "56e4cd96dd1d8c346b07b4d6b255f976570c6f2389697347a6c3dcb9e820d10e",
         # Only allow peeking at fuzzer related files for now.
-        strip_prefix = "compiler-rt-9.0.0.src/lib/fuzzer",
+        strip_prefix = "compiler-rt-9.0.0.src/lib",
         urls = ["http://releases.llvm.org/9.0.0/compiler-rt-9.0.0.src.tar.xz"],
     ),
     fuzzit_linux = dict(
diff --git a/test/fuzz/fuzz_runner.h b/test/fuzz/fuzz_runner.h
index e2279365ca..31a317a220 100644
--- a/test/fuzz/fuzz_runner.h
+++ b/test/fuzz/fuzz_runner.h
@@ -8,7 +8,7 @@
 #include "libprotobuf_mutator/src/libfuzzer/libfuzzer_macro.h"
 // Bring in FuzzedDataProvider, see
 // https://github.com/google/fuzzing/blob/master/docs/split-inputs.md#fuzzed-data-provider
-#include "compiler_rt/fuzzer/utils/FuzzedDataProvider.h"
+#include "fuzzer/utils/FuzzedDataProvider.h"
 #include "spdlog/spdlog.h"

 namespace Envoy {
```

**Comment by sqkerner** [comment]
@lizan , thanks for the patch.  I applied it to this CL, and clang format works.  Let me know if it should be submitted separately, or if it should be squashed in to this commit.

**Comment by asraa** [comment]
Thank you! The changes look good to me (thanks for the speed up logs!) besides I think you may have applied my patch instead of Lizan's.

**Comment by sqkerner** [comment]
> besides I think you may have applied my patch instead of Lizan's.

You are correct.  I altered the change to use Lizan's, as it avoids the external dep.  Also fixed some presubmit issues.

**Pull request merged**
