### PR TITLE
EDS-caching: multiple clusters using the same EDS resource fix

### PR DESCRIPTION
**Pull request by adisuissa**
Commit Message: EDS-caching: multiple clusters using the same EDS resource fix
Additional Description:
A wrong use of the Erase-Remove idiom is fixed in this PR.
This only impacts Envoys that enabled the `envoy.restart_features.use_eds_cache_for_ads` runtime flag, and have configs where multiple clusters reference the same EDS resource.

Risk Level: low
Testing: Added both unit and integration tests.
Docs Changes: N/A
Release Notes: Added
Platform Specific Features: N/A

### CODE REVIEW

**Review by abeyad — APPROVED** [review]
thanks @adisuissa !

**Review by lizan — APPROVED** [review]

**Pull request merged**
