### PR TITLE
mobile: Remove obsolete stats reporting check

### PR DESCRIPTION
**Pull request by abeyad**
https://github.com/envoyproxy/envoy/commit/7fd09ae21dacb0c36324dbbb158cb905c7ac8d9c removed ENVOY_MOBILE_STATS_REPORTING but we didn't remove the check in the test.

### CODE REVIEW

**Review by yanavlasov — APPROVED** [review]

**Review by RyanTheOptimist — APPROVED** [review]
Should we add some sort of CI which checks the `ENVOY_MOBILE_STATS_REPORTING` build?

**Comment by abeyad** [comment]
> Should we add some sort of CI which checks the ENVOY_MOBILE_STATS_REPORTING build?

Yup, I was going to follow up and do that, I just wanted to get this in ASAP since it is blocking the Envoy import.

**Comment by RyanTheOptimist** [comment]
> > Should we add some sort of CI which checks the ENVOY_MOBILE_STATS_REPORTING build?
> 
> Yup, I was going to follow up and do that, I just wanted to get this in ASAP since it is blocking the Envoy import.

Yeah, agreed!

**Review by alyssawilk — APPROVED** [review]

**Comment by alyssawilk** [comment]
re CI I think the plan is to remove it entirely so just verifying git's 100% gone should be enough.

**Pull request merged**
