### PR TITLE
add %HOSTNAME% to the access log & header formatters

### PR DESCRIPTION
**Pull request by rgs1**
Useful for log aggregation and eventual grouping/deconstruction
by hostname. Ditto for request/response headers.

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

### CODE REVIEW

**Comment by rgs1** [comment]
@dio we actually need to add this var -- `%HOSTNAME%` -- to headers as well, so pushing a change to reuse this from the header formatter. Thanks!

**Comment by dio** [comment]
Overall it looks good. Just one question: do you think we can query hostname when envoy does bootstrapping (and cache it), so we don't do system calls every time we log or format headers?

**Comment by rgs1** [comment]
@dio note that the `getHostname()` gets called outside of the field extract lambdas -- which is at config time I believe -- and then the result is just copied into the field extractor. This means that the call should only happen once -- when creating the header and logging formatters (e.g: when config is read). 

Surely we could move it closer to startup -- but reading it on config update doesn't sound too bad?

Or am I missing something?

**Comment by dio** [comment]
@rgs1 ah you're right. Seem like I wrongly skimmed the code.

**Pull request merged**
