### PR TITLE
deps: Bump `io_bazel_rules_go` -> 0.39.1

### LINKED ISSUE #26848: Newer release available `io_bazel_rules_go`: v0.39.1 (current: v0.38.1)
Package Name: io_bazel_rules_go@0.38.1
Current Version: v0.38.1@2023-01-26
Available Version: v0.39.1@2023-04-20
Upstream releases: https://github.com/bazelbuild/rules_go/releases

### PR DESCRIPTION
**Pull request by phlax**
and update `go_sdk` toolchain registration

Fix #26848

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
argg, ok, just ...

/retest

**Comment by phlax** [comment]
interesting, i think the mobile retest is not working as there are no available machines - might be worth moving this to rk

**Comment by keith** [comment]
I think we would have to explicitly download the other architectures if we ever wanted to cross compile on either platform

**Review by keith — APPROVED** [review]

**Pull request merged**
