### PR TITLE
Defer Processing: Parameterize test for filters to avoid bit rot

### PR DESCRIPTION
**Pull request by KBaichoo**
Commit Message: Defer Processing: Parameterize test for filters to avoid bit rot.
Additional Description: This is simply https://github.com/envoyproxy/envoy/pull/20244 which was reverted due to merge fails from https://github.com/envoyproxy/envoy/commit/1a1373f31e4d3854ac09451b057270d2b97ef0b2. No longer use the Runtime singleton which was removed. [This is the only real change from 20244](https://github.com/envoyproxy/envoy/pull/20405/files#diff-1f838ae62058b3d3f17be73d5e0a141598f3be9f2b8ad304ac65001490b08a94R924-R925)
Risk Level: Med
Testing: Parameterized test to work with deferred processing
Docs Changes: NA
Release Notes: NA
Platform Specific Features: NA
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by adisuissa — APPROVED** [review]
Code changes LGTM.

**Review by daixiang0 — APPROVED** [review]

**Comment by KBaichoo** [comment]
/assign @snowp

For non-googler pass / you did the original review of this PR.

**Comment by mattklein123** [comment]
I thought this was reverted due to a test flake? Did we fix the flake? cc @ggreenway

**Comment by RyanTheOptimist** [comment]
> I thought this was reverted due to a test flake? Did we fix the flake? cc @ggreenway

I think this is fixed in this PR: https://github.com/envoyproxy/envoy/pull/20405/files#diff-1f838ae62058b3d3f17be73d5e0a141598f3be9f2b8ad304ac65001490b08a94R924-R925

**Comment by mattklein123** [comment]
OK got it, sorry for the confusion.

**Comment by KBaichoo** [comment]
PTAL @snowp, this is the change from the last PR (so that we don't break CI): https://github.com/envoyproxy/envoy/pull/20405/commits/48b7fb01d25323ca7a1a4cad907cf1ca777d2e31

**Pull request merged**
