### PR TITLE
config: adding proxy connect config

### PR DESCRIPTION
**Pull request by alyssawilk**
At Envoycon it came up that we had examples for tunneling TCP over CONNECT, and decapculating TCP formerly in CONNECT but none for just proxying CONNECT.  Now we do.

Risk Level: n/a
Testing: manual
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by moderation** [comment]
In this recent PR @phlax cleaned up some of the remaining v2 references. This included taking a version reference like `v2` out of the file extensions.  None of the files in https://github.com/envoyproxy/envoy/tree/master/configs include references now. For consistency it would be good to rename your PR file to `configs/proxy_connect.yaml`

**Comment by moderation** [comment]
It would be a bonus to add instruction on how to use or test the config. Not suggesting a full example like in the sandboxes.  For example If I try the proxy connect config  with curl I get the following error.
```
curl -v --proxy 127.0.0.1:10001 https://www.google.com/
*   Trying 127.0.0.1:10001...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 10001 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.google.com:443
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> User-Agent: curl/7.68.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
< date: Tue, 20 Oct 2020 01:30:04 GMT
< server: envoy
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

Debug output from Envoy is:
```
[2020-10-19 18:46:10.078][419038][debug][conn_handler] [source/server/connection_handler_impl.cc:496] [C0] new connection
[2020-10-19 18:46:10.078][419038][debug][http] [source/common/http/conn_manager_impl.cc:248] [C0] new stream
[2020-10-19 18:46:10.078][419038][debug][http] [source/common/http/conn_manager_impl.cc:860] [C0][S12436179200589299345] request headers complete (end_stream=false):
':authority', 'www.google.com:443'
':method', 'CONNECT'
'user-agent', 'curl/7.68.0'
'proxy-connection', 'Keep-Alive'

[2020-10-19 18:46:10.078][419038][debug][router] [source/common/router/router.cc:429] [C0][S12436179200589299345] cluster 'service_google' match for URL ''
[2020-10-19 18:46:10.078][419038][debug][router] [source/common/router/router.cc:586] [C0][S12436179200589299345] router decoding headers:
':authority', 'www.google.com:443'
':method', 'CONNECT'
':scheme', 'https'
'user-agent', 'curl/7.68.0'
'x-forwarded-proto', 'http'
'x-request-id', '1c935131-625a-44d0-9e3c-a53fa5c74fcc'
'x-envoy-expected-rq-timeout-ms', '15000'

[2020-10-19 18:46:10.078][419038][debug][pool] [source/common/tcp/original_conn_pool.cc:98] creating a new connection
[2020-10-19 18:46:10.078][419038][debug][pool] [source/common/tcp/original_conn_pool.cc:383] [C1] connecting
[2020-10-19 18:46:10.079][419038][debug][connection] [source/common/network/connection_impl.cc:755] [C1] connecting to [2607:f8b0:4007:808::2004]:443
[2020-10-19 18:46:10.079][419038][debug][connection] [source/common/network/connection_impl.cc:771] [C1] connection in progress
[2020-10-19 18:46:10.079][419038][debug][pool] [source/common/tcp/original_conn_pool.cc:125] queueing request due to no available connections
[2020-10-19 18:46:10.122][419038][debug][connection] [source/common/network/connection_impl.cc:611] [C1] connected
[2020-10-19 18:46:10.223][419038][debug][pool] [source/common/tcp/original_conn_pool.cc:303] [C1] assigning connection
[2020-10-19 18:46:10.223][419038][debug][router] [source/common/router/upstream_request.cc:357] [C0][S12436179200589299345] pool ready
[2020-10-19 18:46:10.223][419038][debug][router] [source/common/router/router.cc:1177] [C0][S12436179200589299345] upstream headers complete: end_stream=false
[2020-10-19 18:46:10.223][419038][debug][http] [source/common/http/conn_manager_impl.cc:1458] [C0][S12436179200589299345] encoding headers via codec (end_stream=false):                                                                                                                                                          
':status', '200'
'date', 'Tue, 20 Oct 2020 01:46:10 GMT'
'server', 'envoy'

[2020-10-19 18:46:10.273][419038][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:215] [C1]
[2020-10-19 18:46:10.274][419038][debug][connection] [source/common/network/connection_impl.cc:579] [C1] remote close
[2020-10-19 18:46:10.274][419038][debug][connection] [source/common/network/connection_impl.cc:202] [C1] closing socket: 0
[2020-10-19 18:46:10.274][419038][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:288] [C1] SSL shutdown: rc=0
[2020-10-19 18:46:10.274][419038][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:215] [C1]
[2020-10-19 18:46:10.274][419038][debug][pool] [source/common/tcp/original_conn_pool.cc:140] [C1] client disconnected
[2020-10-19 18:46:10.274][419038][debug][router] [source/common/router/router.cc:1029] [C0][S12436179200589299345] upstream reset: reset reason: connection termination, transport failure reason:
[2020-10-19 18:46:10.274][419038][debug][http] [source/common/http/filter_manager.cc:770] [C0][S12436179200589299345] Resetting stream due to upstream_reset_after_response_started{connection termination}. Prior headers have already been sent
[2020-10-19 18:46:10.274][419038][debug][http] [source/common/http/conn_manager_impl.cc:187] [C0][S12436179200589299345] doEndStream() resetting stream
[2020-10-19 18:46:10.274][419038][debug][http] [source/common/http/conn_manager_impl.cc:1507] [C0][S12436179200589299345] stream reset
[2020-10-19 18:46:10.274][419038][debug][connection] [source/common/network/connection_impl.cc:106] [C0] closing data_to_write=0 type=2
```

**Comment by alyssawilk** [comment]
Thanks - I had missed the naming change.  I'll also tweak upstream - realistically google doesn't accept CONNECT requests so it should talk to a custom upstream which does.

**Review by snowp — APPROVED** [review]
Thanks!

**Comment by mattklein123** [comment]
@alyssawilk can we link to this example from the CONNECT docs? I'm not sure how anyone is going to find this? Thank you.

**Comment by mattklein123** [comment]
Also, is this config checked via the config checker? I'm not sure it is by default? cc @phlax

**Pull request merged**
