### PR TITLE
deps: revert upgrade to CEL to fix build

### LINKED ISSUE #31932: Envoy v1.29.0 build fails on Mac OS
*Title*: *Envoy v1.29.0 build fails on Mac OS*

*Description*:
When I am building Envoy v1.29.0 on MacOS 12.7.1 with clang 14.0.0 I noticed an error

```
ec2-user@Mac-mini envoy-builds % gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Envoy build error

```
Undefined symbols for architecture x86_64:
  "cel::interop_internal::ProtoStructValueToMessageWrapper(cel::Value const&)", referenced from:
      cel::interop_internal::ToLegacyValue(google::protobuf::Arena*, cel::Handle<cel::Value> const&, bool) in libinterop.a(interop.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //contrib/exe:envoy-static failed to build
INFO: Elapsed time: 136.522s, Critical Path: 46.32s
```

I've tried both conrtib and not contrib build but I have the same issue.

*Repro steps*:

1. Use mac 12.7.1 or 11.7.10 (on aws ami-06bf601fad285cc69 or ami-0da052d2225304b8f)
2. Setup CI tools
3. run bazel build -c opt envoy
4. Notice error at the last step

```
Undefined symbols for architecture x86_64:
  "cel::interop_internal::ProtoStructValueToMessageWrapper(cel::Value const&)", referenced from:
      cel::interop_internal::ToLegacyValue(google::protobuf::Arena*, cel::Handle<cel::Value> const&, bool) in libinterop.a(interop.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //contrib/exe:envoy-static failed to build
INFO: Elapsed time: 136.522s, Critical Path: 46.32s
```

I've noticed that more people have the same issue https://github.com/Homebrew/homebrew-core/pull/160068

### PR DESCRIPTION
**Pull request by ggreenway**
Commit Message: deps: revert upgrade to CEL to fix build
Additional Description: This upgrade broke building on macOS on the current major version of the OS (tested on 14.1).
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
Fixes #31932
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by RyanTheOptimist — COMMENTED** [review]
Wow, ouch! I thought we had mac test coverage. I know we do for Envoy Mobile. do we not have it for Envoy proper?

I gather we have to revert all 3 of these PR, and can't just revert on of them?

**Comment by ggreenway** [comment]
> Wow, ouch! I thought we had mac test coverage. I know we do for Envoy Mobile. do we not have it for Envoy proper?

It sounds like our mac CI is using a macOS version that's two years old. We should probably keep CI using the latest major version in the future.

> I gather we have to revert all 3 of these PR, and can't just revert on of them?

It appeared, at least at first glance, that both of the later PRs were fixes for changes in the CEL upgrade PR. I couldn't get the revert to apply cleanly without all 3.

**Comment by phlax** [comment]
> We should probably keep CI using the latest major version in the future

we generally dont want it to be set to "latest" as we want reproducible/explicit ci - but keeping the version up to date with latest is defo a good idea

> We should probably keep CI using the latest major version in the future

i think this would definitely be preferable to fix forward - not least because its now in the 1.29 branch/release also, which kinda complicates things

also not sure that the fix will be so hard if we can pinpoint the actual issue - most likely compiler flags or somesuch

**Comment by phlax** [comment]
cc @kyessenov

**Comment by phlax** [comment]
also wondering - if its not easy to fix/workaround - can we just disable cel for macos (as win was previously) ?

**Comment by ggreenway** [comment]
> also wondering - if its not easy to fix/workaround - can we just disable cel for macos (as win was previously) ?

That's removing functionality from a supported platform. I think I'd rather revert and keep things building. It sounds like this update caused issues with some linux distro/compiler combos as well. I don't know why CEL is making compilers so unhappy, but we should probably figure it out and fix before keeping this update.

**Comment by ggreenway** [comment]
The list of stuff that would have to be removed if CEL is excluded from macOS is getting to be significant. From https://github.com/envoyproxy/envoy/pull/32133/files#diff-8e1b8edd0dd49f5a7468a7071405b488c7ffb93fd46c68de99df0a8d7d25b0d4L17:

```
  # Extensions that require CEL.
     "envoy.access_loggers.extension_filters.cel",
     "envoy.rate_limit_descriptors.expr",
     "envoy.filters.http.rate_limit_quota",
     "envoy.filters.http.ext_proc",
     "envoy.formatter.cel",
     "envoy.matching.inputs.cel_data_input",
     "envoy.matching.matchers.cel_matcher",
     # Wasm and RBAC extensions have a link dependency on CEL.
     "envoy.access_loggers.wasm",
     "envoy.bootstrap.wasm",
     "envoy.filters.http.wasm",
     "envoy.filters.network.wasm",
     "envoy.stat_sinks.wasm",
     # RBAC extensions have a link dependency on CEL.
     "envoy.filters.http.rbac",
     "envoy.filters.network.rbac",
     "envoy.rbac.matchers.upstream_ip_port",
 ```

**Comment by phlax** [comment]
> ...  a supported platform. 

at least in terms of CI ive yet to see anywhere its not working - not to say its not failing, but that where its failing may not be a supported platform if we cant test it

**Comment by ggreenway** [comment]
I may have found a way to fix-forward this. Marking this PR as a draft for now.

**Comment by ggreenway** [comment]
Closing this for now in favor of fixing forward

**Comment by RyanTheOptimist** [comment]
Thanks so much for working through this, @ggreenway!

**Pull request closed without merging**
