### PR TITLE
[WIP] deps: Remove opencensus

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @envoyproxy/dependency-shepherds 

turns out this project is also archived now so i think we should land this immediately

**Comment by moderation** [comment]
Another nice cleanup

/lgtm deps

**Comment by htuch** [comment]
@wbpcode @Shikugawa @basvanbeek

**Comment by kyessenov** [comment]
This would break Istio unfortunately.

**Comment by kyessenov** [comment]
CC @lei-tang - we'd need some policy what to do with opencensus in Istio since it's now unmaintained.

**Comment by kyessenov** [comment]
https://github.com/istio/istio/issues/44743

**Comment by lei-tang** [comment]
To avoid breaking Istio customers, Istio needs to follow a proper deprecation procedure (e.g., provide an advance notice for the Opencensus deprecation). Before Istio completes its deprecation procedure for Opencensus, it should not be removed.

**Comment by moderation** [comment]
> To avoid breaking Istio customers, Istio needs to follow a proper deprecation procedure (e.g., provide an advance notice for the Opencensus deprecation). Before Istio completes its deprecation procedure for Opencensus, it should not be removed.

Can Istio start that formal process for OpenTracing and OpenCensus now (if it hasn't already).

In parallel, can't Istio continue to ship / use 1.27.0 throughout this deprecation period and no one gets broken?

**Comment by kyessenov** [comment]
> Can Istio start that formal process for OpenTracing and OpenCensus now (if it hasn't already).

+1 I think Istio should announce and start emitting warnings.
 
> In parallel, can't Istio continue to ship / use 1.27.0 throughout this deprecation period and no one gets broken?

I don't think that's a good idea as we support Istio versions for several releases, so that extend 1.27 support window much longer than desirable. Releasing at head of Envoy allows Istio to shorten Envoy support windows.

**Comment by nareddyt** [comment]
https://github.com/GoogleCloudPlatform/esp-v2 would also be broken by this change. We rely on OpenCensus today.

BTW I see https://github.com/envoyproxy/envoy/issues/9958 (Transition to OpenTelemetry from OpenTracing and OpenCensus) is still open. Seems odd to remove support for OpenCensus while transition isn't ready yet.

Also https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/opentelemetry.proto mentions the following:

> This extension is work-in-progress. Functionality is incomplete and it is not intended for production use. This extension has an unknown security posture and should only be used in deployments where both the downstream and upstream are trusted.

Are there any tangible steps to get OpenTelemetry tracer extension ready for production use? Is it a matter of adhering to Envoy's extension guidelines, or does it also involve changes to the OpenTelemetry libraries?

https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md#extension-stability-and-security-posture

Ideally this is resolved before deprecating OpenCensus

**Comment by lei-tang** [comment]
Advance notice of Istio deprecating Opencensus: https://github.com/istio/istio.io/pull/13715.

**Comment by nareddyt** [comment]
I see. Correct, we are using it for Cloud Trace. My understanding is that OpenTelemetry is the recommended migration path for tracing, please correct me if I'm wrong.

**Comment by kyessenov** [comment]
@nareddyt Cloud Trace does not expose an OpenTelemetry endpoint. That means you have to run some collector to proxy telemetry. There's a [zipkin collector](https://cloud.google.com/trace/docs/zipkin) so you're not limited to Otel for tracing, but it's probably a good idea to start using Otel collector.

**Comment by phlax** [comment]
setting this to WIP in favour of #29063

**Comment by kyessenov** [comment]
@phlax are we removing opencensus this version?

**Comment by phlax** [comment]
> are we removing opencensus this version?

i was going to ping - i think in this version we should do the "hard" deprecation as we have done for opentracing #32421

**Comment by kyessenov** [comment]
No strong opinion. Istio will have to copy the code anyways when it's gone here since the dependency is used by other filters.

**Comment by basvanbeek** [comment]
Has any outreach to customers have happened?

I know we have said it would be removed in 1.30 and that has been messaged in release notes, I do notice that on the actual documentation site we don't even mention this in the API descriptions. It is very easy for people to have this information go unnoticed.

**Comment by phlax** [comment]
@basvanbeek its due to be actually removed in 1.31 now.

The plan for 1.30 is just hard deprecation - ie disabled by default

I believe some comms were sent out - not 100% - but it was marked deprecated, and the conversation has been pretty active here on github

**Comment by phlax** [comment]
cc @ggreenway - i can reactivate this now i think

**Comment by ggreenway** [comment]
Yep, it's time. Do you want to bring this PR up to date, or should we start fresh?

**Comment by ggreenway** [comment]
This is superseded by #37508

**Pull request closed without merging**
