### PR TITLE
tls: separate out cert validation logic from ContextImpl

### PR DESCRIPTION
**Pull request by mathetake**
The first step towards https://github.com/envoyproxy/envoy/issues/14614. Ref https://github.com/envoyproxy/envoy/issues/14614#issuecomment-758442255

Note that the change is almost moving codes from `context_impl` to `cert_validator/**` with a bit of necessary tweaks.

Commit Message: tls: separate out cert validation logic from ContextImpl
Additional Description: In order to create the extension point for certificate validation, separated out the cert validation logics from Tls::ContextImpl, and move them to Tls::DefaultCertValidator which implements Tls::CertValidator interface. Ref: #14614 and #9284
Risk Level: low (almost code moves)
Testing: unittest
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

cc @lizan

### CODE REVIEW

**Comment by lizan** [comment]
Overall this looks good, the coverage is missing from some error config part:
https://storage.googleapis.com/envoy-pr/7004480/coverage/source/extensions/transport_sockets/tls/cert_validator/default_validator.cc.gcov.html

were them covered before?

**Comment by mathetake** [comment]
looks like they haven't been covered before as well :https://storage.googleapis.com/envoy-pr/e1ca2ab/coverage/source/extensions/transport_sockets/tls/context_impl.cc.gcov.html 

but some of them are formatted into multiple lines in this PR plus the file size becomes smaller so I think that is why the coverage goes down in terms of the number of lines covered :confused:

**Comment by mathetake** [comment]
@lizan added the coverage exception. PTAL

**Review by lizan — APPROVED** [review]

**Comment by lizan** [comment]
@ggreenway for non-tetrands review

**Review by ggreenway — APPROVED** [review]
LGTM

**Pull request merged**
