### PR TITLE
tcp_proxy tests: Add more integration tests for upstream flushing.

### PR DESCRIPTION
**Pull request by ggreenway**
This adds coverage to the previously untested case of exiting Envoy
while flushing.

Signed-off-by: Greg Greenway <ggreenway@apple.com>

*Risk Level*: Low

### CODE REVIEW

**Comment by ggreenway** [comment]
@mattklein123 This adds coverage for one of the cases you mentioned yesterday in tcp_proxy.

However, I haven't figured out how to make the test work yet.  I need to close the fake_upstream_connection after I destroy test_server_, but that doesn't work.  Any thoughts?  I really want the fake_upstream_connection to be in a completely separate space (memory, threads, all dependencies) from the test_server_.

**Comment by alyssawilk** [comment]
Isn't fake upstream already split into its own thread?    I know we access it a lot but that's what the locks are for.

Are you more hoping it would process on its own without waiting on instructions from the main thread?  If so take a look at the autonomous upstream.  It's mostly wired up to auto-respond for HTTP but I think it could be extended to do TCP as well.

**Comment by ggreenway** [comment]
Something doesn't work, because the final waitForDisconnect() hangs forever.  After shutting down the test server, I'd expect the fake upstream to know that it is closed (via remote close).

**Comment by alyssawilk** [comment]
Huh, I'd try -l trace and/or cerr logging that the connection is torn down and the fd is closed on cleanup.  When a process goes away all open FDs are closed but I don't know if we close all fds for Envoy on connection destruction and server deletion.  That'd be my best guess as to what's going on

**Comment by alyssawilk** [comment]
(Will review this unless you fix everything tomorrow and Matt merges it before I even see it =P)

**Comment by ggreenway** [comment]
@alyssawilk I think I fixed the test, but I'm not happy with what I found.  I single-stepped through the test in the debugger with a tcpdump running.  Envoy correctly called ::close() on the connection, but no FIN was sent, according to tcpdump.  So that's a bit weird.  But there shouldn't be anything wrong with just closing the fake upstream connection, as the latest commit does.  And in a non-test case, when envoy is really exiting, I presume the kernel will fully clean up anything.

**Comment by alyssawilk** [comment]
Or he can go ahead and approve right after me, since Matt is ever vigilant :-P

I'm still calling not-it on the merge since it still has WIP in the title.

**Pull request merged**
