### PR TITLE
deps: update cel, absl, googleapis

### PR DESCRIPTION
**Pull request by kyessenov**
Commit Message: update CEL and its dependencies
Additional Description:
Risk Level: low
Testing: regression

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
Looks like the mobile build is broken somehow?

**Comment by yanavlasov** [comment]
It looks like a problem in uri_template_test.cc https://dev.azure.com/cncf/envoy/_build/results?buildId=165343&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=d1a98671-b7ba-5fbf-f06c-ff337c010df4&l=701

Hopefully it would need gtest update too.

/wait

**Comment by kyessenov** [comment]
I've tried to bump Google test - no luck. I'll fix the test directly and keep Google test bump - which seems like a good thing to have.

**Comment by kyessenov** [comment]
Undid googletest bump - that breaks something else, without fixing the build failure.

**Comment by yanavlasov** [comment]
Oh mad, this is difficult. It looks like for gcc failure we will need to patch protobuf. Not sure about the mobile build errors.

**Comment by soulxu** [comment]
/wait

for CI

**Comment by kyessenov** [comment]
The mobile failures appear to be in the base Envoy due to C++17 compiler flag. I think we can park this PR until mobile switches over to C++20 so that we don't have to bifurcate the code.

**Pull request closed without merging**
