### PR TITLE
docs: release note cleanup for 1.7

### PR DESCRIPTION
**Pull request by alyssawilk**
*Risk Level*: n/a
*Testing*: n/a
*Docs Changes*: release notes cleaned up.

### CODE REVIEW

**Comment by alyssawilk** [comment]
@envoyproxy/maintainers please take a pass for things I missed

@mattklein123 it's unclear to me from our governance docs if we should remove the "pending" tag from 1.7 docs here, or in a follow up.  Ditto adding 1.8.0 pending section.  Thoughts?

I assume the VERSION change should be done in a follow-up.

**Comment by alyssawilk** [comment]
Haha, oops, it's in fact super clear when I do the updates, I just completely read over it.

**Comment by alyssawilk** [comment]
@htuch : not easily

Our format checker doesn't do multi-line, so validating .\n* isn't there would require substantial rewrites.
Generally replacing foo: Bar with foo: bar* ends up picking up a ton of stuff we don't want even if we scope to rst.  We could apply it *just* do this file I guess, but we might still run up against legit cases.

method: pOST
:header: name, Type, Description
codec_type: aUTO
lb_policy: rOUND_ROBI

*something like
line = re.sub(r'(: )([A-Z])', lambda lower: lower.group(1) + lower.group(2).lower(), line)

**Comment by htuch** [comment]
@alyssawilk maybe you want a regex like `\* [^:]*: [A-Z]`, i.e. only match when this is following the summary at the beginning of a bullet point. Anyway, no big deal, I think it's fine to do manually, I just favor automation where it's not too hard.

**Pull request merged**
