### PR TITLE
github/ci: Improve action runner

### PR DESCRIPTION
**Pull request by phlax**
This improves github CI by bubbling notice, error, and warning to the github UI

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
adding a minor fix

**Comment by phlax** [comment]
breaks verify - fixing ...

**Review by wbpcode — APPROVED** [review]
LGTM, let's see it.

**Pull request merged**
