### PR TITLE
proto: Add PATCH method to RequestMethod enum

### LINKED ISSUE #6694: HTTP PATCH logged as METHOD_UNSPECIFIED when logging with ALS
*Title*: HTTP PATCH logged as METHOD_UNSPECIFIED when logging with ALS

*Description*:
I use PATCH requests that go through envoy and logs are written with als implemented on golang. I expect to see "PATCH" as a result of this code:

Instead, I see "METHOD_UNSPECIFIED". 
When I tried to find the reason in the library code, I found that PATCH is not in the list of request methods in base.proto (which is used in the library)
https://github.com/envoyproxy/envoy/blob/3cb3571f093602b7d6a06945906802666febcf66/api/envoy/api/v2/core/base.proto

However, if I don't use ALS and let envoy log requests, PATCH is written as expected.

I created an issue in the go-control-plane and they advised to ask here: https://github.com/envoyproxy/go-control-plane/issues/176

*Repro steps*:
golang sample:
import (
	envoy "github.com/envoyproxy/go-control-plane/envoy/data/accesslog/v2"
)

func RequestMethod(ent *envoy.HTTPAccessLogEntry) string {
	return ent.GetRequest().GetRequestMethod().String()
}

*Config*:
            access_log:
            - name: envoy.http_grpc_access_log
              config:
                common_config:
                  log_name: access_log
                  grpc_service: { envoy_grpc: { cluster_name: als } }
                additional_request_headers_to_log: []
                additional_response_headers_to_log: []
                additional_response_trailers_to_log: []

  - name: als
    connect_timeout: 0.25s
    http2_protocol_options: {}
    common_http_protocol_options:
      idle_timeout: 30s
    upstream_connection_options:
      tcp_keepalive:
        keepalive_probes: 1
        keepalive_time: 10
        keepalive_interval: 10
    type: STATIC
    hosts:
      - socket_address:
          address: 127.0.0.1
          port_value: 4436

### PR DESCRIPTION
**Pull request by glebmish**
Description: Add PATCH method to protobuf so that ALS can receive and log it properly
Risk Level: Low
Testing: None
Docs Changes: -
Release Notes: -
Fixes #6694

### CODE REVIEW

**Comment by glebmish** [comment]
> The change looks good. I'm wondering if we can solidify this by adding a test. @junr03 thoughts?

Yes, it would be good. Couldn't think of appropriate place to test it though, will be glad to hear suggestions.

**Comment by venilnoronha** [comment]
@glebmish somewhere under https://github.com/envoyproxy/envoy/blob/master/test/common/access_log/?

**Comment by glebmish** [comment]
> @glebmish somewhere under https://github.com/envoyproxy/envoy/blob/master/test/common/access_log/?

will it be tested there? @junr03 said that text logs work without proto so it seems that tests for access_log will work anyway. It probably makes sense to test the part that works with proto to make sure it really works.

Or do this tests actually work with proto and I'm missing something here?

**Comment by junr03** [comment]
I think @venilnoronha linked for inspiration, not necessarily suggesting that the test would be written there. Yes, those tests are not for the ALS, they are for text logs. I haven't looked closely at the test suite for the ALS, let me know if you'd like me to take a look for guidance.

**Comment by glebmish** [comment]
Added test similar to the part below that checks METHOD_UNSPECIFIED

However, I see that in the part below "request_headers" is initialized but not passed to access_log_->log (nullptr is passed instead). And when I modified it to pass headers, new field "request_headers_bytes" appeared in the result and test failed. I guess it just doesn't work correctly right now, what do you think?

**Comment by dio** [comment]
@glebmish what if:

Create a `void expectLogRequestMethod(const std::string& request_method)` as a member method of `HttpGrpcAccessLogTest` class and have a `TEST_F` e.g.

```c++
TEST_F(HttpGrpcAccessLogTest, LogWithRequestMethod) {
  InSequence s;
  expectLogRequestMethod("GET");
  expectLogRequestMethod("HEAD");
  expectLogRequestMethod("POST");
  expectLogRequestMethod("PUT");
  expectLogRequestMethod("DELETE");
  expectLogRequestMethod("CONNECT");
  expectLogRequestMethod("OPTIONS");
  expectLogRequestMethod("TRACE");
  expectLogRequestMethod("PATCH");
}
```

The body of `expectLogRequestMethod` skeleton surely can be as simple as:

```c++
    NiceMock<StreamInfo::MockStreamInfo> stream_info;
    stream_info.host_ = nullptr;

    Http::TestHeaderMapImpl request_headers{
        {":scheme", "scheme_value"},
        {":authority", "authority_value"},
        {":path", "path_value"},
        {":method", request_method},
    };

    expectLog(fmt::format(R"EOF(
// !!!TODO: replace with the expected structured log here (yes in yaml format). The `fmt::format` helps you to build the string. hint: {} as placeholder, while {{}} to escape.
)EOF",
                          request_method, /* more parameters here, hint: related to `request_headers_bytes` */ ));
    access_log_->log(&request_headers, nullptr, nullptr, stream_info);
```

**Comment by glebmish** [comment]
@dio it looks good, I can do that.

Do you think it also make sense to move METHOD_UNSPECIFIED there? Something like `expectLogRequestUnspecifiedMethod("WHACKADOO");` which is basically the same method but checks that result is METHOD_UNSPECIFIED. 
If you think it make sense, can you please explain the difference between two tests that check METHOD_UNSPECIFIED? One of them seems more complicated but it's not clear for me why two separate tests are needed there

**Comment by dio** [comment]
You can be as creative as you want 😄. 

> can you please explain the difference between two tests that check METHOD_UNSPECIFIED? 

I think those two tests check different things i.e. the second one checks on marshaling `tls_properties`.

**Comment by glebmish** [comment]
@dio added changes you proposed, thanks! Decided to leave METHOD_UNSPECIFIED tests as it is, just fixed them there.

**Comment by glebmish** [comment]
I see failed test suites, but I can't understand the reason. Can somebody help me with this?

**Comment by dio** [comment]
@glebmish I think you need to run the formatter. In this case against this file: test/extensions/access_loggers/http_grpc/grpc_access_log_impl_test.cc. 

```
$ ./tools/check_format.py fix test/extensions/access_loggers/http_grpc/grpc_access_log_impl_test.cc
```
And add and commit that.

**Comment by glebmish** [comment]
@dio thank you! fixed

**Comment by glebmish** [comment]
I see that coverage suite is failing with exit code 36. I took a look on bazel exit codes and it seems like it some environment issue, I guess some process is not stopping correctly. What can I do about it?

https://docs.bazel.build/versions/master/guide.html
> 36 - Local Environmental Issue, suspected permanent.

**Comment by glebmish** [comment]
Well, it doesn't seem to be healed by restart :(
And the only error I see is

> FATAL: Attempted to kill stale server process (pid=83) using SIGKILL, but it did not die in a timely fashion.
Did you see this in other PRs? If it's something with environment it should probably fail everywhere

**Comment by dio** [comment]
@glebmish hum, while investigating the build errors, would you mind to merge master?

**Comment by glebmish** [comment]
@dio it definitely helped, thanks! Now I understand what's the problem there, coverage is less than threshold. This is funny, I added 1 line of code and several tests and somehow decreased coverage :)

**Comment by glebmish** [comment]
thanks @mattklein123 !

**Pull request merged**
