### PR TITLE
runtime: removing envoy.reloadable_features.dns_multiple_addresses

### PR DESCRIPTION
**Pull request by alyssawilk**
(Not removing the moble APIs as they still control the DNS lookup type and so are still functional)

Risk Level: low
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Fixes https://github.com/envoyproxy/envoy/issues/25008

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]

**Review by jpsim — APPROVED** [review]
+1 apologies for the `ios_tests` CI issues, should be addressed by https://github.com/envoyproxy/envoy/pull/25140

**Review by jpsim — CHANGES_REQUESTED** [review]
Actually since this PR makes the `enableHappyEyeballs` builder functions unused, could you please remove them as part of this PR and update the Envoy Mobile changelog & docs to reflect that?

**Comment by alyssawilk** [comment]
@jpsim please see PR description.  the happy eyeballs functions still work (v4 preferred vs all) so I'd prefer to remove them separately

**Review by jpsim — APPROVED** [review]
👍 now I understand that the happy eyeballs control knob is still functional with this change.

**Pull request merged**
