### PR TITLE
[ZK filter] Add per opcode decoder error metrics 2nd attempt

### PR DESCRIPTION
**Pull request by Winbobob**
Commit Message: [ZK filter] Add per opcode decoder error metrics 2nd attempt
Additional Description: Reapply https://github.com/envoyproxy/envoy/pull/31138 after fixing the ZK proxy filter "Uncaught Exception" issue in https://github.com/envoyproxy/envoy/pull/31485.
Risk Level: Low
Testing: Unit test
Docs Changes: docs/root/configuration/listeners/network_filters/zookeeper_proxy_filter.rst
Release Notes: changelogs/current.yaml

### CODE REVIEW

**Comment by Winbobob** [comment]
cc @JuniorHsu , please review if you have a chance, thank you!

**Review by JuniorHsu — APPROVED** [review]
based on I approved https://github.com/envoyproxy/envoy/pull/31138

**Pull request merged**
