### PR TITLE
[bp/1.30] ext_authz test deflaking

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @stevenzzzz

**Review by botengyao — APPROVED** [review]
LGTM, thanks!

**Comment by antoniovleonti** [comment]
I'm still a bit new to git. For my learning, why have you explicitly included my commit in your PR?

**Comment by phlax** [comment]
we have release branches - when we backport we do it onto those branches, ideally ~preserving commit history from `main`

the releases themselves are cut from those branches

in this case i saw 2 commits that seemed to be making CI less flakey so figured good to have on the branch/es

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
