### PR TITLE
Fix problems with bazel query

### PR DESCRIPTION
**Pull request by robertpanzer**
*Description*:
At the moment it is impossible for me to import the Envoy repository into VS Code using the "official" Bazel plugin.
This is because it calls `bazel query` which fails on problems with the BUILD files in the api folder:
```
$ /usr/local/bin/bazel query ... --output=package --output=package
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/robert/dev/envoy/tools/bazel.rc
INFO: Invocation ID: 5a9ca157-f351-4424-ace6-524cb935659a
ERROR: error loading package 'api/envoy/config/metrics/v2': Unable to load file '//bazel:api_build_system.bzl': file doesn't exist
```
This PR fixes this by changing the load path.

Additionally I renamed the file `examples/grpc-bridge/script/build` to `examples/grpc-bridge/script/build.sh` as `bazel query` identifies this as a Bazel build file on OS X due to the case insensitive file system. 

*Risk Level*:
If the build passes it should be fine.

*Testing*:
Test that the API still works.

*Docs Changes*:
None

*Release Notes*:
None
[Optional Fixes #Issue]
[Optional *Deprecated*:]

### CODE REVIEW

**Comment by robertpanzer** [comment]
Thanks for the super fast feedback! :)
I updated the document, and also moved the script `bootstrap` to `bootstrap.sh`.
I think it makes sense to have these 2 shell scripts both have the extension `.sh`.

**Comment by htuch** [comment]
Please merge master to pick up https://github.com/envoyproxy/envoy/pull/5827.

**Comment by htuch** [comment]
@robertpanzer re: your local error, sometimes you get this if you clang-format is a different version to the one used in CI, so that might be a place to look. I don't personally use the precommit hooks.

**Comment by htuch** [comment]
@robertpanzer can you merge master?

**Comment by htuch** [comment]
Closing this out in favor of #5886 which just merged

**Comment by robertpanzer** [comment]
@htuch Sorry I wasn't able to catch up as I was traveling over the weekend.
I just checked the latest master and the problem I reported still exists.
But maybe it's just me.

**Comment by htuch** [comment]
@robertpanzer @mergeconflict also uses vscode and was the author of #5886. Maybe you can sync on Slack to discuss the workflow?

**Comment by robertpanzer** [comment]
I created https://github.com/envoyproxy/envoy/issues/5909 to track the problem that this PR tried to solve.

**Pull request closed without merging**
