### PR TITLE
exceptions : normalizing 3 more exceptions

### PR DESCRIPTION
**Pull request by alyssawilk**
moving  ProtoValidationException,  MissingFieldException OutOfRangeException to EnvoyException

Additional Description:
Risk Level: low
Testing: updated unit tests
Docs Changes: n/a
Release Notes: n/a

https://github.com/envoyproxy/envoy/issues/30857

### CODE REVIEW

**Comment by alyssawilk** [comment]
Ryan you're just on the hook for "code was removed so coverage went down" - feel free to recuse after checking that.

**Review by RyanTheOptimist — COMMENTED** [review]
Coverage changes LGTM

**Review by zuercher — APPROVED** [review]

**Pull request merged**
