### PR TITLE
api: Document default CidrRange prefix_len

### LINKED ISSUE #15579: Behavior for CidrRange with unspecified prefix_len
As part of https://github.com/grpc/proposal/pull/231 I was digging through some detailed behavior of Envoy.

CidrRange has a `google.protobuf.UInt32Value prefix_len`. Since UInt32Value was used instead of `uint32` it would imply that if prefix_len is not set some reasonable default behavior should be made. There is no documentation describing what should happen in this case.

https://github.com/envoyproxy/envoy/blob/48c4fb87e9632baa6145a21771fb4d67d4aa4231/api/envoy/config/core/v3/address.proto#L158-L159

The most obvious behavior is to use a prefix_len of 32 for IPv4 and 128 for IPv6, since `0` would've just used `uint32`. However, it appears Envoy treats this case as a prefix_len of 0.

https://github.com/envoyproxy/envoy/blob/54c74450e82a3767a677ebe5406e88f0d045fb4b/source/server/filter_chain_manager_impl.cc#L181-L184
https://github.com/envoyproxy/envoy/blob/5b875969d4571fc5bda77d6340d100142ed98797/source/common/network/cidr_range.cc#L115-L117

Am I reading this right? Is that a bug or intended? Digging through history, it appears using UInt32Value instead of uint32 was likely a [simple mistake](https://github.com/envoyproxy/data-plane-api/pull/49). Although it's not clear what the previous behavior was at that point and I didn't feel like cross-referencing that change with Envoy's code.

Even if this _was_ a bug, this is looking to be pretty old behavior so it seems likely a "feature" at this point (until v4, obviously :smile:). Just add a comment describing behavior and move on?

CC @htuch

### PR DESCRIPTION
**Pull request by ejona86**
Commit Message:
Fixes #15579

Additional Description: n/a
Risk Level: n/a (no functional change)
Testing: Unit test to verify case added to docs
Docs Changes: Added definition of default value
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by ejona86** [comment]
CC @htuch 

I'll note that I had to disable the pre-push hook, because it gave me trash. Seems it is bazel-based, so unclear how my environment could mess it up; I'd expect just a build error if anything. I had already run with `./ci/run_envoy_docker.sh './ci/do_ci.sh fix_format'` so I ignored it.

```
Please apply following patch to directory './api'
diff -Npur a/envoy/config/filter/http/jwt_authn/v2alpha/config.proto b/envoy/config/filter/http/jwt_authn/v2alpha/config.proto
--- a/envoy/config/filter/http/jwt_authn/v2alpha/config.proto	2021-03-22 17:16:20.123776207 -0700
+++ b/envoy/config/filter/http/jwt_authn/v2alpha/config.proto	2021-03-22 17:32:31.491070064 -0700
@@ -390,7 +390,8 @@ message FilterStateRule {
 
   // A map of string keys to requirements. The string key is the string value
   // in the FilterState with the name specified in the *name* field above.
-  map<string, JwtRequirement> requires = 3;
+  map<string, JwtRequirement>
+  requires = 3;
 }
 
 // This is the Envoy HTTP filter config for JWT authentication.
...
```

**Review by lambdai — APPROVED** [review]
LGTM!

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Comment by htuch** [comment]
@phlax re: https://github.com/envoyproxy/envoy/pull/15617#issuecomment-804501313, I think there is a weird bug in `protoxform` here. @ejona86 can you file a bug on this? We can track there.

**Pull request merged**
