### PR TITLE
style: pragma once in header file

### LINKED ISSUE #15264: enforce pragma once in header file
I find my newly added header file not following the style guide `Header guards should use #pragma once.`

Looks like this is not unique 
```
$ for f in `find include/ source/ test/ -name "*.h"`; do grep "pragma once" $f >/dev/null|| echo $f; done | wc -l
81
```

I will blindly add the pragma directive to make the future include no-brain.

Do we need a rule formatter to check/fix after the above change?

### PR DESCRIPTION
**Pull request by lambdai**
Commit Message:
Add pragma once almost every header.
Signed-off-by: Yuchen Dai <silentdai@gmail.com>

Additional Description:
```
for f in `find include/ source/ test/ -name "*.h"`; do grep "pragma once" $f >/dev/null|| echo $f; done | grep -v test_data |grep -v test/config/integration/certs |grep -v chromium |  xargs sed -i '1s/^/#pragma once\n\n/'
```

Exceptions
```
ource/common/chromium_url/url_parse.h
source/common/chromium_url/url_parse_internal.h
source/common/chromium_url/url_canon_stdstring.h
source/common/chromium_url/url_canon_internal.h
source/common/chromium_url/url_canon.h
test/config/integration/certs/clientcert_hash.h
test/config/integration/certs/client_ecdsacert_hash.h
test/config/integration/certs/upstreamlocalhostcert_hash.h
test/config/integration/certs/upstreamcert_hash.h
test/config/integration/certs/server_ecdsacert_hash.h
test/config/integration/certs/servercert_hash.h
test/extensions/transport_sockets/tls/test_data/extensions_cert_info.h
test/extensions/transport_sockets/tls/test_data/ca_cert_info.h
test/extensions/transport_sockets/tls/test_data/no_subject_cert_info.h
test/extensions/transport_sockets/tls/test_data/san_uri_cert_info.h
test/extensions/transport_sockets/tls/test_data/san_dns2_cert_info.h
test/extensions/transport_sockets/tls/test_data/selfsigned_rsa_1024_cert_info.h
test/extensions/transport_sockets/tls/test_data/selfsigned_ecdsa_p256_cert_info.h
test/extensions/transport_sockets/tls/test_data/no_san_cert_info.h
test/extensions/transport_sockets/tls/test_data/san_only_dns_cert_info.h
test/extensions/transport_sockets/tls/test_data/san_multiple_dns_cert_info.h
test/extensions/transport_sockets/tls/test_data/selfsigned_rsa_3072_cert_info.h
test/extensions/transport_sockets/tls/test_data/selfsigned_rsa_4096_cert_info.h
test/extensions/transport_sockets/tls/test_data/unittest_cert_info.h
test/extensions/transport_sockets/tls/test_data/selfsigned2_ecdsa_p256_cert_info.h
test/extensions/transport_sockets/tls/test_data/password_protected_cert_info.h
test/extensions/transport_sockets/tls/test_data/san_ip_cert_info.h
test/extensions/transport_sockets/tls/test_data/intermediate_ca_cert_info.h
test/extensions/transport_sockets/tls/test_data/san_dns3_cert_info.h
test/extensions/transport_sockets/tls/test_data/selfsigned_ecdsa_p384_cert_info.h
test/extensions/transport_sockets/tls/test_data/selfsigned_cert_info.h
test/extensions/transport_sockets/tls/test_data/fake_ca_cert_info.h
test/extensions/transport_sockets/tls/test_data/selfsigned2_cert_info.h
test/extensions/transport_sockets/tls/test_data/long_validity_cert_info.h
test/extensions/transport_sockets/tls/test_data/san_dns_cert_info.h
test/extensions/transport_sockets/tls/test_data/san_dns4_cert_info.h
test/extensions/transport_sockets/tls/test_data/expired_cert_info.h
test/extensions/transport_sockets/tls/test_data/expired_san_uri_cert_info.h
```

Risk Level: LOW
Testing: self-contained
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
Part of #15264
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by alyssawilk — APPROVED** [review]
LGTM, thanks!  Optionally, would you be willing to also extend the format scripts to catch this, to future-proof?

**Comment by alyssawilk** [comment]
also, why the exceptions?

**Comment by lambdai** [comment]
> LGTM, thanks! Optionally, would you be willing to also extend the format scripts to catch this, to future-proof?

Yes, it's on my plate. Not started yet though. Any help is welcomed. I will label the issue

**Comment by lambdai** [comment]
> also, why the exceptions?

test data seems auto generated and not linked in C++ code. 
chromium_url: I need to understand if this requirement is adding the overhead to chomium_url owner when updating the new version.

I have no immediate answer in the night :(

**Comment by alyssawilk** [comment]
Gotcha, thanks for the explanation :-)

**Pull request merged**
