### PR TITLE
quiche: restore quic test coverage

### LINKED ISSUE #8184: Add quiche code back to coverage test
Currently, the code under source/extensions/quic_listeners/quiche/ is excluded from coverage test in https://github.com/envoyproxy/envoy/pull/7721. This is necessary because there are a lot of NOT_REACHED_GCOVR_EXCL_LINE, NOT_IMPLEMENTED_GCOVR_EXCL_LINE added in that PR which if included in coverage test would raise the bar of code coverage much higher than required (97%) for other PRs in the future. And also there are code hard to tests in non-integration tests.

When the integration is done, those macros should be replaced by real implementation or ASSERT with dummy tests. And integration tests should cover those currently hard-to-test lines. And we should add source/extensions/quic_listeners/quiche/ back to coverage test then.

### PR DESCRIPTION
**Pull request by danzh2010**
Re-enable test coverage check under source/extensions/quic_listeners/quiche

Fixes #8184

### CODE REVIEW

**Comment by danzh2010** [comment]
Coverage test fails with seg fault in Protocols/BufferIntegrationTest.RouterRequestPopulateContentLengthOnTrailers/IPv4_Http2Downstream_HttpUpstream.

**Comment by mattklein123** [comment]
This is now a legit coverage failure due to the coverage amount being too low.

/wait

**Comment by danzh2010** [comment]
Most of the coverage gap is in redundant platform implementations for QUIC, HTTP2 and Spdy. Sync's with the lasted QUICHE which moves a lot of them into shared QUICHE platform implementations.

**Comment by mattklein123** [comment]
Can you merge master? The coverage build should be fixed.

/wait

**Comment by danzh2010** [comment]
Coverage is still lower than 97%, will add more tests.

**Comment by danzh2010** [comment]
Can someone reopen this PR?

**Comment by mattklein123** [comment]
@danzh2010 done

**Comment by mattklein123** [comment]
Needs master merge.

/wait

**Comment by mattklein123** [comment]
Looks like coverage is below threshold. :(

/wait

**Pull request closed without merging**
