### PR TITLE
docs: updating config links

### PR DESCRIPTION
**Pull request by alyssawilk**

### CODE REVIEW

**Review by mattklein123 — COMMENTED** [review]
Awesome, thank you. Can you confirm that these configs are checked by the config checker? See https://github.com/envoyproxy/envoy/blob/master/configs/BUILD#L16. I think they might be but I'm not sure? cc @phlax who has done a lot of work in this area.

/wait-any

**Comment by phlax** [comment]
> Can you confirm that these configs are checked by the config checker? 

they arent - im happy to add after

**Comment by mattklein123** [comment]
> they arent - im happy to add after

Either way. Can we potentially make it automatic with globbing like you did in the other places?

**Comment by phlax** [comment]
> Either way. Can we potentially make it automatic with globbing like you did in the other places?

yep

**Comment by mattklein123** [comment]
OK let's merge and I will let you follow up. Thank you!

**Pull request merged**
