### PR TITLE
deps: Bump `upb` -> e074c038

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
i optimistically hoped that it was using the prebuilt header files in the repo but it seems its not and is generating them from the upb lib

i will take a look and see if there is a hack there, also wondering about any better way to resolve

**Comment by phlax** [comment]
looks like this may have been fixed upstream https://github.com/protocolbuffers/upb/issues/1340

ill try bumping the version

**Comment by phlax** [comment]
half worked, its sprung another log hog - ill update ...

**Comment by phlax** [comment]
cc @RyanTheOptimist

**Comment by phlax** [comment]
testing a fix for GCC

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by phlax** [comment]
/retest mobile

arggh swift test

**Pull request merged**
