### PR TITLE
wasm: upgrade proxy-wasp-cpp-host for shared data apis

### PR DESCRIPTION
**Pull request by jamesmulcahy**
- Exposes keys() and remove() methods (though not directly through the
  ABI).

Signed-off-by: James Mulcahy <jmulcahy@netflix.com>

Commit Message:
Additional Description: This updates the wasm host dependency so envoy users can start accessing the SharedData::keys() and SharedData::remove() functions via the WASM foreign functions interface.
Risk Level: low
Testing: no additional testing beyond the automated testing in 
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Comment by jamesmulcahy** [comment]
Commits between these two versions:

```
$ git log --decorate=off --oneline 44a63ebe58770a07e36ff1ff149f176fd8371810..819dcc02bd2bc6fdec07720379c4d522d6b7da08
819dcc0 Add keys() and remove() methods to SharedData. (#203)
10d5b06 wamr: remove dependency on LLVM. (#239)
d6b6d50 build: increase reach of the buildifier check. (#238)
bab2ef1 Update Bazel to v5.0.0. (#235)
b42c336 Update rules_foreign_cc to v0.7.1. (#236)
8a38042 Update rules_rust to latest (with Rust v1.58.1). (#237)
6640fcf build: stop installing Ninja. (#234)
```

**Comment by jamesmulcahy** [comment]
cc/ @PiotrSikora @mathetake

**Comment by PiotrSikora** [comment]
> ```
> 10d5b06 wamr: remove dependency on LLVM. (#239)
> ```

Since you're propagating this change, could you remove the LLVM dependency from WAMR in `bazel/foreign_cc/BUILD`?

Also, it might be best not to mention those Shared Data APIs, since we're not exposing them to the end users.

**Comment by jamesmulcahy** [comment]
> Since you're propagating this change, could you remove the LLVM dependency from WAMR in bazel/foreign_cc/BUILD?

Sure, does that involve removing the LLVM_DIR cache entry too? Or just the `deps = [":llvm"]` line?

> Also, it might be best not to mention those Shared Data APIs, since we're not exposing them to the end users.

It's not mentioned in any release notes, and the commit message is clear that we're not exposing them in the ABI.  I did want to convey my intent for the PR though, which seems reasonable.

**Comment by mathetake** [comment]
curious what's the plan/timeline for user facing ABI change?

**Comment by PiotrSikora** [comment]
> Sure, does that involve removing the LLVM_DIR cache entry too? Or just the `deps = [":llvm"]` line?

Both.

> It's not mentioned in any release notes, and the commit message is clear that we're not exposing them in the ABI. I did want to convey my intent for the PR though, which seems reasonable.

Sure, although we update dependencies without any justification other than "there is new version" all the time.

> curious what's the plan/timeline for user facing ABI change?

There is no plan to expose those functions in 0.2.x ABI (although, I might revisit this if the next ABI slips again).

In the meantime, @jamesmulcahy is going to access them via Foreign Functions.

**Comment by phlax** [comment]
> Sure, although we update dependencies without any justification other than "there is new version" all the time.

wfm

ill look at removing alpine in the next day or two

**Comment by phlax** [comment]
cc @moderation ^^

**Comment by jamesmulcahy** [comment]
@PiotrSikora Added a commit to remove the wamr LLVM dependency

**Review by PiotrSikora — APPROVED** [review]
Thanks!

**Review by wrowe — COMMENTED** [review]
LGTM

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
