### PR TITLE
mobile: Fix RTDS integration test

### PR DESCRIPTION
**Pull request by abeyad**

### CODE REVIEW

**Review by fredyw — APPROVED** [review]

**Comment by botengyao** [comment]
@abeyad @fredyw Just run into this for our import, and do we need any improvement for the CI to catch this problem?

**Comment by fredyw** [comment]
> @abeyad @fredyw Just run into this for our import, and do we need any improvement for the CI to catch this problem?

Yeah, we are planning to enable CI with xDS enabled to catch this.

**Pull request merged**
