### PR TITLE
protos: Remove squash from api:v2_protos

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: protos: Remove squash from api:v2_protos
Additional Description:

this is a follow up to #16336 as in a subsequent PR `proto_format` was trying to remove this

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@htuch i separated this out from #16903 as i wanted to check its safe to do this - that PR was trying to remove this and also the same for other protos that are being removed

**Comment by phlax** [comment]
...also im concerned that something similar might start happening on other peoples PRs - ie trying to remove this proto

**Comment by htuch** [comment]
Why wasn't this caught in CI on #16336?

**Comment by phlax** [comment]
> Why wasn't this caught in CI on #16336?

i was rather hoping you would know the answer to that

`proto_sync.py` etc is a bit of a mystery to me - mostly i have been using trial and error to make it happy as im not entirely clear as to what its doing

**Comment by phlax** [comment]
@htuch i tried making some arbitrary changes to proto files to see if i could trigger the problem (#16923 ) - it did not

its a mystery to me why removal is being enforced in https://github.com/envoyproxy/envoy/pull/16903

either way - i think we want to do this - no ?

**Review by htuch — APPROVED** [review]

**Comment by htuch** [comment]
Yep, sure. I think once v2 is gone we get rid of `proto_sync.py` anyway.

**Pull request merged**
