### PR TITLE
bump protobuf to 28.2

### PR DESCRIPTION
**Pull request by asedeno**
Bump protobuf to 28.2

Risk Level: low
Testing: CI

### CODE REVIEW

**Comment by asedeno** [comment]
Since my patch to clean up protoconverter landed in #36290, let's try this again.
This should still not be merged before the 1.32.0 release gets cut.

**Comment by asedeno** [comment]
All set. One more piece of #36167.

**Comment by tyxia** [comment]
@moderation  PTAL. 

cced @phlax as well

**Review by phlax — APPROVED** [review]
lgtm, thanks @asedeno

**Pull request merged**
