### PR TITLE
docs: Add info about xDS cluster ordering in the Bootstrap

### PR DESCRIPTION
**Pull request by abeyad**
Clarification for a workaround to https://github.com/envoyproxy/envoy/issues/27702.

### CODE REVIEW

**Comment by abeyad** [comment]
cc @adisuissa

**Review by alyssawilk — COMMENTED** [review]
thanks for the follow-up.  I'm going to tag @htuch as well in Adi's absence.  Harvey, see linked issue for details.

**Review by alyssawilk — APPROVED** [review]

**Review by htuch — APPROVED** [review]
Sure, thanks. Please remove the doc when you address the issue but this is a useful callout for now. I agree it's not ideal.

**Review by htuch — APPROVED** [review]
Sure, thanks. Please remove the doc when you address the issue but this is a useful callout for now. I agree it's not ideal.

**Pull request merged**
