### PR TITLE
Revert "build(deps): bump orjson from 3.6.7 to 3.7.7 in /tools/base (…

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
pending outcome of https://dev.azure.com/cncf/envoy/_build/results?buildId=112577&view=logs&s=38ceb128-5055-565c-88b0-b52f284e9b30 

...we probably want to land this quickly

**Comment by phlax** [comment]
yep, the dep is broken so we do want this for now - i can land a better fix tomorrow once ci is green again

cc @adisuissa

**Review by wrowe — APPROVED** [review]
LGTM as a stop gap until packaging on arm64 can be resolved

**Pull request merged**
