### PR TITLE
dependabot: Updates

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: dependabot: Updates
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
docs are rendered here https://storage.googleapis.com/envoy-pr/17915/docs/index.html

**Comment by phlax** [comment]
it seems like there is a small bug with the tabs update - its pretty minor (tab content disappears if you click an open tab)

ill follow this up upstream, but my feeling is just to land anyway

**Comment by phlax** [comment]
seems like its a feature not a bug https://github.com/executablebooks/sphinx-tabs/pull/73

**Review by htuch — APPROVED** [review]
LGTM, thanks!
/lgtm deps

**Pull request merged**
