### PR TITLE
repokitteh: Secure azure creds

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

use `secret_headers` for creds

Commit Message: repokitteh: Secure azure creds
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Review by itayd — DISMISSED** [review]

**Review by lizan — DISMISSED** [review]

**Comment by itayd** [comment]
@phlax it's not in effect since this is not blessed.

**Comment by itayd** [comment]
well uh something need to fail to test this :/

**Comment by phlax** [comment]
i can push failure 8/

**Comment by phlax** [comment]
@itayd works

```
 secret_headers="redacted",
```

**Review by itayd — APPROVED** [review]

**Review by lizan — APPROVED** [review]

**Pull request merged**
