### PR TITLE
api: add annotation deps to all packages

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Comment by htuch** [comment]
@lizan thanks, need to pass CI though.

**Comment by lizan** [comment]
ugh this CI is slightly hard to resolve, basically the protoc has too long argument list. I think it requires a patch to protoc.

**Comment by htuch** [comment]
@lizan not sure why it became too large with this PR, but I know `protoc` can take an `@<filename>` argument similar to gcc etc., which gives extended args. Probably doesn't help if `protoc` is invoked by other rules like PGV. We can always just do this manually for now and bypass this PR if it turns into too much of a pain.

**Comment by lizan** [comment]
@htuch seems the python protoc command doesn't dedup and doesn't use param file, so it needs a prrotobuf.bzl patch. I guess because this adds multiple `-I` args.

**Comment by htuch** [comment]
@lizan can we work around this for 1.13.0 somehow?

**Pull request closed without merging**
