### PR TITLE
multi-envoy: fixing shutdown ordering bugs

### PR DESCRIPTION
**Pull request by alyssawilk**
the envoy bug stats are global and complicated, and I think we can just skip them for multi-envoy rather than switch to getpid() and hash maps.

### CODE REVIEW

**Review by snowp — DISMISSED** [review]
LGTM! Are there any other server stats that are accessed in this way?

**Comment by alyssawilk** [comment]
that was the only one I saw so should be good pending asan/msan run :-)

**Comment by alyssawilk** [comment]
Can I get a stamp on resolving merge conflicts?

**Review by snowp — APPROVED** [review]

**Comment by alyssawilk** [comment]
cc @jpsim for visibility

**Pull request merged**
