### PR TITLE
xds: bumping deps

### PR DESCRIPTION
**Pull request by alyssawilk**
Gets rid of a few more build warnings

### CODE REVIEW

**Review by phlax — APPROVED** [review]
/lgtm deps

thanks @alyssawilk

**Comment by alyssawilk** [comment]
in my defense, the target is com_github_cncf_udpa but yeah, updated :-P

**Comment by moderation** [comment]
True. I really want to change that but when I dug under the covers the usage of udpa in v2 stuff is everywhere in the code so not as straight forward as I was hoping

**Comment by alyssawilk** [comment]
It's yaks all the way down...

**Pull request merged**
