### PR TITLE
[api] fix address configuration bugs 

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Commit Message: The introduction an Envoy internal address in API caused a few fuzz bug crashes.
Additional Description:
(1 +2) Since internal addresses aren't implemented for endpoints or listeners, remove them in the fuzzer.
(3) Some messages optionally include an `Address`, which means that if the address is unset and the address is resolved, Envoy would crash `NOT_REACHED_GCOVR_EXCL_LINE`. Options for fixing this would be requiring the field anywhere that a `core.v3.Address` is used, or throwing if nothing is set, which was the old behavior before PR https://github.com/envoyproxy/envoy/pull/12837. I re-introduced the throw. E.g.  the particular crash happened from https://github.com/envoyproxy/envoy/blob/64bd6311bcc8f5b18ce44997ae22ff07ecccfe04/api/envoy/config/endpoint/v3/endpoint_components.proto#L56. I think it's reasonable that this is required, but I'm not sure if it's worth adding required to every API field.

Risk Level: Low
Testing: Corpus entries added
Fixes Issues:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25628
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25616
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25608

### CODE REVIEW

**Comment by mattklein123** [comment]
Sorry I thought about this but didn't say anything. My bad. :facepalm: 

@lambdai can you PTAL? We should make sure we have follow ups to turn on fuzzing once the feature is complete.

**Review by lambdai — APPROVED** [review]
Sorry for the late response.
As we expect internal address is not included in listener/endpoint, either throw exception and panic is good IMO.

**Comment by mattklein123** [comment]
Can you merge main?

/wait

**Comment by asraa** [comment]
all set! sorry about that

**Comment by mattklein123** [comment]
gcc failure looks legit. check CI?

/wait

**Review by mattklein123 — DISMISSED** [review]

**Comment by asraa** [comment]
Looking into why IpVersions/SslIntegrationTest.RouterRequestAndResponseWithBodyNoBufferHttp2VerifySAN/IPv6
 times out

**Comment by mattklein123** [comment]
> Looking into why IpVersions/SslIntegrationTest.RouterRequestAndResponseWithBodyNoBufferHttp2VerifySAN/IPv6
times out

It's possible the test just needs to be sharded, not sure.

**Comment by asraa** [comment]
I ran 5000 times on my machine and didn't repro the timeout, so i added a small shard count

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
