### PR TITLE
Windows CI: Upload test results to AZP

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Commit Message:
Windows: Upload test results to AZP

- Requires modifying --output_base flag to Bazel startup options
- The TEST_TMPDIR and BUILD_DIR bind mounts from the host are where
  Bazel will place build output etc.
- Allowing Bazel to place build and test output there will give the host
  access to the data to upload
- Only riskiness involves Windows and long paths, adds a couple characters
  to the exec root/output base Bazel uses
- Should help with diagnosing test flakiness on Windows, having test results actually
  uploaded to AZP so we can track failures over time

Additional Description: N/A
Risk Level: Low
Testing: N/A, CI change
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
@envoyproxy/windows-dev

**Comment by sunjayBhatia** [comment]
See https://dev.azure.com/cncf/envoy/_build/results?buildId=57958&view=ms.vss-test-web.build-test-results-tab should be able to filter now for windows test results

**Comment by sunjayBhatia** [comment]
/wait

trying to minimize path length increases

**Comment by sunjayBhatia** [comment]
merged master to get coverage to hopefully pass, shouldnt be affected by this change

**Review by lizan — APPROVED** [review]

**Pull request merged**
