### PR TITLE
dependabot: Updates

### PR DESCRIPTION
**Pull request by phlax**
Commit Message: dependabot: Updates
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
seems like dependabot runs `pip-compile` in the requirements.txt dir which is generated a lot of noise

im thinking we might want to add a pip-compile wrapper script to prevent this and ensure that its always called consistently etc

**Review by alyssawilk — APPROVED** [review]
LGTM modulo shephard sign-off

**Pull request merged**
