### PR TITLE
Add `rules_shell` in advance of Protobuf 29.0+ update.

### PR DESCRIPTION
**Pull request by asedeno**
`rules_shell` is new, and currently largely delegates back to the bazel native `sh_binary`, `sh_library`, and `sh_test`.

Protobuf 29.0+ explicitly depends on it, though BCR[^1] suggests a lot of other things do too, so we'll load it just before `rules_cc`.

[^1]: https://registry.bazel.build/modules/rules_shell/0.3.0

Risk Level: low
Testing: CI

### CODE REVIEW

**Comment by phlax** [comment]
do we want any of this? ...

https://github.com/bazelbuild/rules_shell/blob/104505faea10e1fe50bb7f7a5b3142b63181e644/WORKSPACE#L3-L7

**Comment by asedeno** [comment]
`rules_shell_dependencies()` just brings in skylib, which we already have. Maybe we want `rules_shell_toolchains()`?

**Comment by phlax** [comment]
probably - not sure - but not clear exactly what it does - if it unblocks the protobuf update im happy either way

**Comment by asedeno** [comment]
This PR, as is, is enough for now. Our existing `sh_*` rules still build, and when added to my local protobuf update branch, unblocks it. We can always pull in more later, though hopefully we'll get to bzlmod before it becomes relevant.

**Review by phlax — APPROVED** [review]
lgtm, thanks @asedeno

**Pull request merged**
