### PR TITLE
Contributing: document hosting requirements for design docs

### PR DESCRIPTION
**Pull request by ggreenway**
Signed-off-by: Greg Greenway <ggreenway@apple.com>

*Risk Level*: None

### CODE REVIEW

**Comment by ggreenway** [comment]
@envoyproxy/maintainers

**Comment by ggreenway** [comment]
Another option is to require the use of a github wiki attached to the project. Even with externally-hosted world-readable source, the owner could delete the doc at some later time, and we'd still lose important information. But I've never used a github wiki; is it good enough for this use?

**Comment by alyssawilk** [comment]
I may be biased but I'm a huge fan of the comment workflow of Google docs, so I'd be sad if we locked into wiki use.

**Comment by ggreenway** [comment]
> I may be biased but I'm a huge fan of the comment workflow of Google docs, so I'd be sad if we locked into wiki use.

I agree that the editing workflow on google docs is superior. So it's a question of weighing that editing experience vs the account-management and history-preservation aspects of hosting it on github. I don't feel strongly. I'd be satisfied with world-readable google docs.

**Comment by lizan** [comment]
> Even with externally-hosted world-readable source, the owner could delete the doc at some later time, and we'd still lose important information.

Should we require the docs to be in a Team Drive? After moving the owner cannot delete the doc unless the Team Drive owner granted access.

**Comment by mattklein123** [comment]
> Should we require the docs to be in a Team Drive? After moving the owner cannot delete the doc unless the Team Drive owner granted access.

Is this possible without an enterprise account? I'm not sure how this works.

**Comment by alyssawilk** [comment]
While I'm a big fan of Google docs for iterative design purposes, we could handle doc lifetime by saying that as the code lands, the doc should be converted to Envoy docs living in the repo for easy discovery.  That'd allow us to iterate as the design changes but also not worry about the lifetime or location in the long run. WDYT?

**Comment by mattklein123** [comment]
Moving the doc once it's finalized to markdown SGTM, though, I think that would be annoying for people to have to reformat it.

**Comment by ggreenway** [comment]
I think for now let's leave this as-is, and we can amend in the future if we want to add more requirements around re-hosting docs into envoy documentation.

**Pull request merged**
