### PR TITLE
network filters: avoid unnecessary std::shared_ptrs

### PR DESCRIPTION
**Pull request by rgs1**
While debugging a crash in:

https://github.com/envoyproxy/envoy/pull/13592

I ended up discussing with @lambdai and @mattklein123 whether
network filters can hold references to things owned by their
corresponding FactoryFilterCb. The answer is yes and the HCM
and some other notable filters already use references instead
of std::shared_ptrs.

So let's consistently do this everywhere to avoid someone
else asking this same question in the future. Plus, it's
always nice to create fewer std::shared_ptrs.

Follow-up on: https://github.com/envoyproxy/envoy/issues/8633

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

### CODE REVIEW

**Comment by mattklein123** [comment]
Seems good to be consistent here, thanks. Can you merge main?

/wait

**Comment by rgs1** [comment]
> Seems good to be consistent here, thanks. Can you merge main?
> 

Yup done.

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Comment by kyessenov** [comment]
Does this also apply to HTTP filters? ECDS returns callbacks by-value, so that would need to be fixed.

**Comment by rgs1** [comment]
> Does this also apply to HTTP filters? ECDS returns callbacks by-value, so that would need to be fixed.

See #14737.

**Comment by kyessenov** [comment]
OK, so the shared pointers are still captured in the lambda, and it should be fine to copy the functors.

**Pull request merged**
