### PR TITLE
WIP bots: initial config for probot/stale

### PR DESCRIPTION
**Pull request by alyssawilk**
This will currently result in 
-PRs getting flagged as stale after 7d, and closed after 14
-Issues not tagged with "help wanted" being flagged as stale after 30d and closed after 37.

WIP because we probably shouldn't submit until we've flagged the 3 pages of not-assigned not-help-wanted issues with help wanted, which I'm happy to do once we've done some bikeshedding
(is:issue is:open -label:"help wanted" no:assignee)

Happy to change time scales, turn off staleness for one or the other.  Suggest away!

I'm also mildly concerned that the + in help wanted will be incorrect and we'll have to untag a ton of bugs as stale.  I've limited tags per run to 1 and I'll turn it up on a day when I'm around to minimize that.  We can up the limit when we get busy enough we need to flag more frequently :-)

*Testing*: I wish
*Docs Changes*: Nope
*Release Notes*: n/a
Part of #2797

@envoyproxy/maintainers

### CODE REVIEW

**Comment by mattklein123** [comment]
My gut feeling is we should start without the help wanted staleness check right now. WDYT?

**Comment by alyssawilk** [comment]
Sorry, I'm not entirely clear what you're suggesting.   Should we not triage stale issues yet, or are you suggesting we flag them as stale even if they're marked help wanted?

**Comment by mattklein123** [comment]
I was just suggesting that we start with only using the bot to mark staleness on PRs, and not use the bot for doing the help wanted triage. (Just because I share your concern of things not working out correctly and stuff getting closed, and I don't feel that's been a huge issue for us so far).

**Comment by alyssawilk** [comment]
Gotcha.  I figured we could close off questions after a couple of months but if a combination of maintainer rotation and our preexisting and much appreciated MattBot have that covered I don't have a strong preference either way. :-)

**Comment by mattklein123** [comment]
I don't have a strong opinion either. I just was worried that things might get auto closed. If you think it's best to do the help wanted thing, that sounds fine to me as long as we keep a careful eye on it.

**Comment by zuercher** [comment]
(I'm not going to assign anyone else -- my gut feeling is that if @mattklein123 and @alyssawilk agree on a config for this, it's good enough to start with.)

**Comment by alyssawilk** [comment]
Stale for a week after comments addressed - I'll close this one off and we can revisit later when we care more :-)

**Comment by alyssawilk** [comment]
Nah, it's not you it's me ;-)  I'm flat out this week (so wouldn't have time to play around with it in any case) so closed off instead of pinging you for review.

**Pull request closed without merging**
