### PR TITLE
backport: ocsp: rotate certs of test data to fix flaky tests (#23635)

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: backport: ocsp: rotate certs of test data to fix flaky tests (#23635)
Additional Description:

See #23635 

Risk Level: low.
Testing: n/a.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
cc @phlax

**Comment by dio** [comment]
Required for: https://github.com/envoyproxy/envoy/pull/23639.

**Review by phlax — APPROVED** [review]
lgtm, thanks @wbpcode

**Pull request merged**
