### PR TITLE
Update QUICHE from cf8d05ab4 to c7adfa0fb

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
https://github.com/google/quiche/compare/cf8d05ab4..c7adfa0fb

```
$ git log cf8d05ab4..c7adfa0fb --date=short --no-merges --format="%ad %al %s"

2024-06-24 wub Fix a bug in libevent-based QuicEventLoop where artificial events are notified in the same epoll iteration.
2024-06-21 birenroy Adds a visitor-based metadata sending API to Http2Adapter and subclasses.
```

### CODE REVIEW

**Review by yanavlasov — APPROVED** [review]

**Comment by htuch** [comment]
@RyanTheOptimist is this one going to land?

**Comment by RyanTheOptimist** [comment]
> @RyanTheOptimist is this one going to land?

Gah! I thought it landed. But it looks like #35001 included these changes, so I'll close.

**Pull request closed without merging**
