### PR TITLE
mobile: Add Apple proxy resolution APIs to the C++ EngineBuilder

### PR DESCRIPTION
**Pull request by abeyad**
Previously, Apple proxy resolution API registration only happened in the Objective-C engine. For those Apple/iOS users using the C++ APIs directly, we need to support proxy resolution API registration in the C++ EngineBuilder as well.

This commit also moves the Objective-C API registration to the same place where other API registration (e.g. key-value store) takes place.

Lastly, to add tests for this, we had to add the Apple CFNetwork and CoreFoundation frameworks to the linkopts, which required envoy_cc_test being able to take in an optional linkopts to add to its defaults.

### CODE REVIEW

**Comment by abeyad** [comment]
added @phlax to review bazel/envoy_test.bzl, thanks!

**Review by RenjieTang — APPROVED** [review]
Thanks Ali!

**Review by fredyw — APPROVED** [review]

**Review by phlax — APPROVED** [review]
bazel changes lgtm

**Pull request merged**
