### PR TITLE
api_proto_plugin: Remove debugging code

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by wrowe** [comment]
Requesting review from @htuch who introduced the code now gated by cprofile_enabled.

From the slack, further comments from phlax;

> To give more context, these are FileDescriptorProtos ie files including source codek, atm they are created as outputs but not used anywhere (afaict)
> Also bazel recently added FileDescriptorProtos to ProtoSets so where we do actually need the source, which is going through this code we can grab it.
> Re cprofile_enabled - mho is just remove the code guarded by it as it would require use of an action_env var to get the var there and that is not documented anywhere

It sounds to me that these are redundant and this was early diagnostic logic that never got mopped up from https://github.com/envoyproxy/envoy/pull/8309?

**Comment by htuch** [comment]
Yeah, we can drop the cprofile stuff I think. But the this PR is now only about this, so the title no longer makes sense?

**Comment by phlax** [comment]
title updated

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
