### PR TITLE
access_log: refactored SubstitutionFormatParser::parseCommand

### PR DESCRIPTION
**Pull request by cpakulski**
Commit Message:
refactored SubstitutionFormatParser::parseCommand

Additional Description:
This PR addresses few items:
 - tech debt: there was a TODO comment that parsing access_log command should use string_view to avoid copying. After using string_view `SubstitutionFormatParser::parseCommand` method is around 40% faster. Microbenchmark reports the following results:

Benchmark                                                  Time             CPU   Iterations
BM_FormatterCommandParsingOld         2194 ns         2194 ns       319163
BM_FormatterCommandParsingNew       1260 ns         1260 ns       554762

 - `SubstitutionFormatParser::parseCommand` has been implemented using variadic template. This is done in preparation for issue #3006. The idea has been proposed on envoy-dev slack on April 14th 2021. In a nutshell, there will be one tag for all metadata in form `METADATA(TYPE:NAMESPACE:KEY):Z`. Notice that there is additional tag `TYPE`. Using Variadic template for parsing commands will automatically address the presence of extra tag.
 
Risk Level: Low
Testing: Added new unit tests and microbenchmark
Docs Changes: Not required
Release Notes: Not required

Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by yanavlasov** [comment]
Thanks, this looks really good. Could you add some negative tests as well, i.e. when command is malformed to test parsing error handling, please?

**Review by yanavlasov — APPROVED** [review]

**Comment by cpakulski** [comment]
@yanavlasov Thanks for reviewing and merging.

**Comment by rgs1** [comment]
FYI this broke our internal formatter extensions:

```
16:48:27 pinterest/formatters/dynamic_metadata_unquoted/formatter.cc:54:5: error: no matching function for call to 'parseCommand'
16:48:27     Envoy::Formatter::SubstitutionFormatParser::parseCommand(token, start, ":", filter_namespace,
16:48:27     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Not a huge deal, but something to take in account code that might be relied upon by extensions...

**Comment by cpakulski** [comment]
@rgs1 I apologize for that. I could probably leave original methods with original signatures and map it to the new ones.
I am guessing that the problem is with different order of parameters.

**Comment by rgs1** [comment]
@cpakulski no worries at all, the change was easy. Mostly just posted for visibility, since eventually formatter extensions might become more popular (I suspect they are not heavily used right now).

**Pull request merged**
