### PR TITLE
[Backport 1.22] stateful session: allow empty filter config (#20960)

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message:

Backport https://github.com/envoyproxy/envoy/pull/20960 to 1.22. Check https://github.com/envoyproxy/envoy/pull/20960#issuecomment-1134572736 for some more context.

Additional Description: n/a.
Risk Level: Low.
Testing: n/a.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Comment by iglin** [comment]
Hi everyone! Thank you very much for the backport. 

Could you please tell me, why there is still no envoyproxy/envoy-alpine build with v1.22 in docker hub? Can it be published?

**Comment by phlax** [comment]
@iglin alpine support was deprecated some time ago and is now discontinued - consider using the distroless image instead

**Pull request merged**
