### PR TITLE
wasm: fix canary configuraton performance regression

### PR DESCRIPTION
**Pull request by kyessenov**
Commit Message: update Wasm host implementation to fix a performance problem. There was a regression (https://github.com/envoyproxy/envoy/pull/22469) with applying a new Wasm config. If Wasm filter is used in many listeners, the change would run Wasm module `onConfigure` for every listener instead of once per plugin config. This would block xDS main execution for many seconds in some cases.
Fixes: https://github.com/proxy-wasm/proxy-wasm-cpp-host/issues/350 
Risk Level:  low
Testing: done upstream
Docs Changes: none
Release Notes: yes

### CODE REVIEW

**Comment by phlax** [comment]
@htuch would you mind giving this a review

@kyessenov we can backport this as soon as it lands

**Comment by kyessenov** [comment]
@mpwarres Can you please stamp this?

**Comment by phlax** [comment]
@kyessenov needs merge and then im happy to land

**Comment by kyessenov** [comment]
@phlax you beat me to it with 487cedbc8bdccff80d497be95ac58a71b5244b64.

**Pull request closed without merging**
