### PR TITLE
test: refactoring integration tests to lower extension use

### PR DESCRIPTION
**Pull request by alyssawilk**
Removing visibility for a bunch of extensions, with a few test rewrites where the deps were still in use.
pass-through filter is encoder/decoder so handles 100 responses.
overload tests were copy-pasted to HTTP/3, so copied the edits back to the overload test 

may improve our build time by a whole 2-3s ;-)

Risk Level: n/a (test only)
Testing: yes
Docs Changes: n/a
Release Notes: n/a
Part of #9953

### CODE REVIEW

**Comment by yanavlasov** [comment]
Thanks for cleaning this up. It does look like these filters actually lack coverage in their own tests.

**Comment by alyssawilk** [comment]
ugh, still some coverage loss
/wait

**Comment by alyssawilk** [comment]
OK, finally got CI happy!  PTAL when you get a few

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
