### PR TITLE
api: fix bazel query again

### PR DESCRIPTION
**Pull request by mergeconflict**
Description: fix "bazel query ..." again.
Risk Level: low
Testing: "bazel query ..." works.
Docs Changes: n/a
Release Notes: n/a

Signed-off-by: Dan Rosen <mergeconflict@google.com>

### CODE REVIEW

**Comment by htuch** [comment]
Yeah, would be ideal to just make this part of the `api` CI job.

**Comment by silentdai** [comment]
What do you think if we make /api a fully considered as a external repository?
Below has the partial effort. 
https://github.com/envoyproxy/envoy/blob/master/bazel/repositories.bzl#L133

**Comment by lizan** [comment]
> What do you think if we make /api a fully considered as a external repository?
> Below has the partial effort.
> https://github.com/envoyproxy/envoy/blob/master/bazel/repositories.bzl#L133

+1, I also made a partial effort at https://github.com/envoyproxy/envoy/pull/6186

**Comment by silentdai** [comment]
@lizan  not #6229 ?

**Comment by lizan** [comment]
Yes #6229 as well, as a consequence they need to be in one PR, but I haven't resolve the CI Issue with that.

**Comment by silentdai** [comment]
Of course landing this PR is the priority.

If you guys don't mind, I can work on /api isolation to prevent future breakage.

**Comment by lizan** [comment]
Sure feel free to take it. @silentdai

**Pull request merged**
