### PR TITLE
Fix mysql filter extra authn data packet handling

### PR DESCRIPTION
**Pull request by Licht-T**
This fixes https://github.com/envoyproxy/envoy/issues/21881.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by wbpcode** [comment]
@rshriram

**Comment by Licht-T** [comment]
Sorry for overlooking the notice. This should not be closed. Can anyone reopen this?

@adisuissa Thank you for reviewing.

The methods with `is_upstream` are utilized in `onData/onWrite` methods. `is_upstream` sets to `true` while `onData`, but `false` while `onWrite`. I think the `is_upstream` specific tests are not required because there are many `onData/onWrite` tests.
> I suggest adding more tests to validate the modified changes (specifically exercise the methods with is_upstream set to true and false).

**Pull request closed without merging**
