### PR TITLE
build: update LLVM to 14.0.0

### PR DESCRIPTION
**Pull request by keith**
Closes https://github.com/envoyproxy/envoy/issues/20803

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Comment by moderation** [comment]
Have they fixed the `14.0.1` artifact uploads you mention at https://github.com/envoyproxy/envoy/issues/20803#issuecomment-1106019648= yet?

**Comment by keith** [comment]
It's still missing `x86_64-linux-gnu-ubuntu`

**Comment by htuch** [comment]
LGTM, let me know when this is ready for merge review.
/wait

**Comment by moderation** [comment]
`14.0.2` just released - https://github.com/llvm/llvm-project/releases

**Comment by keith** [comment]
https://github.com/envoyproxy/envoy/pull/21055

**Comment by keith** [comment]
New warning fixing here https://github.com/envoyproxy/envoy/pull/21055

**Pull request closed without merging**
