### PR TITLE
dynamic forward proxy: allow host rewrite to take effect

### PR DESCRIPTION
**Pull request by rgs1**
This is needed so that a route action, when using the dynamic
forward proxy, can set a host rewrite.

Fixes: #8607

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

### CODE REVIEW

**Comment by rgs1** [comment]
@mattklein123 hmm, on a 2nd thought using `host_rewrite` for this doesn't feel quite right, given it has a different meaning in other uses cases. Maybe we should use metadata -- in the route -- for this?

cc: @fishcakez

**Comment by mattklein123** [comment]
@rgs1 @fishcakez can you describe your complete use case? How would you propose to use metadata? I agree host_rewrite is not awesome, but it's not terrible either. Perhaps if we better understand your use case we can come up with something better.

One other option would be to build explicit rewrite capability into the dynamic proxy filter config itself, but this also doesn't feel great.

**Comment by rgs1** [comment]
> @rgs1 @fishcakez can you describe your complete use case? How would you propose to use metadata? I agree host_rewrite is not awesome, but it's not terrible either. Perhaps if we better understand your use case we can come up with something better.

Yeah fair -- moving it to metadata doesn't improve things much except that it doesn't overload `host_rewrite`.

The use case is quite simple: for some bazel builds, we'd like to intercept calls to fetch artifacts from (say) github and instead redirect to something internal (but not just changing the upstream, also changing the prefix). Hmmm maybe we could use a redirect and a path rewrite?

**Comment by rgs1** [comment]
I take it back, redirect is not quite we want -- we do want to modify `host:` and rewrite the prefix. So this diff -- with the right API/property name -- might be the way to go after all.

**Comment by rgs1** [comment]
> What about a per-route filter config for the dynamic proxy filter? This would be explicitly typed and specific to the filter and not involve metadata?

Yeah I like that more. Let me rework the diff. Hmm, not sure about the name... `host_rewrite` is still overloaded, maybe just `host` or `host_target`?

**Comment by mattklein123** [comment]
> Yeah I like that more. Let me rework the diff. Hmm, not sure about the name... host_rewrite is still overloaded, maybe just host or host_target?

I could go either way. Technically you are rewriting the host so that seems fine also.

**Comment by rgs1** [comment]
Per above discussions, closing this one in favor of #8619.

**Pull request closed without merging**
