### PR TITLE
Fix HTTP3 demo config

### LINKED ISSUE #16843: HTTP3 demo config has errors
### description

the http3 demo configuration has a configuration error here:

https://github.com/envoyproxy/envoy/blob/72bf41fb0ecc039f196be02f534bfc2c9c69f348/configs/envoyproxy_io_proxy_http3_downstream.yaml#L16-L28

trying to load this throws the following error:

```
ERROR (validation failed): configs/envoyproxy_io_proxy_http3_downstream.yaml
Failed to parse static_resources field: Failed to parse listeners field: Failed to parse filter_chains field: Failed to parse transport_socket field: Message type "envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext" has no field named "downstream_tls_context".
 Available Fields(except extensions): ['commonTlsContext', 'requireClientCertificate', 'requireSni', 'sessionTicketKeys', 'sessionTicketKeysSdsSecretConfig', 'disableStatelessSessionResumption', 'sessionTimeout', 'ocspStaplePolicy']....
```

currently this problem is hidden from CI as the `listeners` field is repeated and this entire block is ignored (i found this linting the yaml)

### PR DESCRIPTION
**Pull request by mk46**
Signed-off-by: Manish Kumar <manish.kumar1@india.nec.com>

Commit Message:  Fix HTTP3 demo config
Additional Description: Please see https://github.com/envoyproxy/envoy/issues/16843. 
Risk Level:
Testing: 
Docs Changes: n/a
Release Notes: n/a
Fixes #16843

### CODE REVIEW

**Comment by mk46** [comment]
CC @phlax  @alyssawilk

**Comment by phlax** [comment]
@mk46 you also need to remove the extra `listeners` - there are 2 which is preventing the issue from surfacing (also incorrect yaml)

**Comment by alyssawilk** [comment]
Ooh, sorry there's issues with the example config - I wonder why the tests didn't pick it up?  

It is it's intention that there's 2 listeners here though.  

listener_udp should be listening for QUIC, but most client stacks won't attempt QUIC without first starting with TCP, and getting an alt-svc response which tells them to try QUIC.  I'm not sure caused the issue reported but I don't think changing the TCP listener is the right fix

**Comment by mk46** [comment]
Can we divide the config into two separate configs for TCP and UDP?

**Comment by alyssawilk** [comment]
Two files?  I don't think so - generally one wants to have the same Envoy listening for both to really work in production, though it is possible to have a TCP deployment and a separate HTTP/3 deployment it's not the norm AFIK.

**Comment by alyssawilk** [comment]
I think https://github.com/envoyproxy/envoy/pull/16848 fixes - WDYT?

**Comment by phlax** [comment]
@mk46 i think we should probs just land #16848 as i think that is the fix - thanks for jumping in!

**Comment by mk46** [comment]
Thanks @phlax,  I am closing this.

**Pull request closed without merging**
