### PR TITLE
matcher: fix UB bug caused by dereferencing a bad optional

### PR DESCRIPTION
**Pull request by snowp**
This fixes a flaky test on master.

Signed-off-by: Snow Pettersen <snowp@lyft.com>

Risk Level: Low, fixes unused code
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Review by mattklein123 — COMMENTED** [review]
This makes sense to me but how does this not fail every time on every build? I'm confused.

/wait-any

**Comment by snowp** [comment]
I'm guessing it has something to do with the difference between libstdc++ and libc++: the compile_time_options target is the only build that runs these tests with libstdc++. Best guess is that the implementation of std::optional (which absl::optional delegates to when present iiuc) is different between enough between the two that the behavior when invoking UB is different. They both seem to rely on `union`, but the libstdc++ one has some additional indirection. 

Not sure if it's worth it to dig into this to understand the specifics, lmk

**Comment by mattklein123** [comment]
> Not sure if it's worth it to dig into this to understand the specifics, lmk

It's not a huge deal, but I thought the standard says that when an optional does not contain a value it's supposed to throw a bad optional exception. How can this be non-deterministic one way or the other? Something seems off here. Is this test not deterministic?

**Comment by snowp** [comment]
https://en.cppreference.com/w/cpp/utility/optional/operator* is UB when the optional does not contain a value, while https://en.cppreference.com/w/cpp/utility/optional/value throws an exception when the optional does not contain a value. This was surprising to me, I thought they were identical until I looked into it for this issue. 

Seems possible that the result can be non-deterministic if we're invoking UB? I guess you could expect subsequent test runs to have the same data left on the stack if we're just dealing with an uninitialized variable, so maybe that's not a great explanation?

**Comment by mattklein123** [comment]
Sigh C++. Pretty annoying that they have different behavior but I guess it's similar to array indexing vs. at() in vector, etc. OK makes sense for some definition of making sense.

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
