### PR TITLE
singleton manager: enhance singleton manager to support pin

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: singleton manager: enhance singleton manager to support pin
Additional Description:

A new enhancement to the singleton manager:
`pin` support: By default, the singleton manager only stores a weak pointer to the instance and  the instance will be destroyed if no one keep its shared pointer. But now, if the `pin` is enabled, the manager will keep a shared pointer of the instance.

This is caused by the #29289. The #29289 introduced a new server factory context method because an object require server wide lifetime. But I think bringing these objects/methods that only make sense for specific modules/features to server factory context is not a good design. And a pinned singleton should be enough for this scenario. (And I think it could do more)

Risk Level: low, no change for now.
Testing: unit.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
Hi, @mattklein123 I think you are the initial designer of the singleton manager, so could you take a look when you have free time to see if this a reasonable enhancement? Thanks.

**Comment by wbpcode** [comment]
cc @alyssawilk

**Comment by mattklein123** [comment]
The pin part of the change seems reasonable to me, but I'm not sure that the name -> type change is a good idea. There may be cases (perhaps already?) where a type could be registered multiple times? The existing naming structure seems better to me since it forces uniqueness even if the type is different. It's a bit more boilerplate in the common case but it doesn't seem all that bad to me?

/wait

**Comment by wbpcode** [comment]
> The pin part of the change seems reasonable to me, but I'm not sure that the name -> type change is a good idea. There may be cases (perhaps already?) where a type could be registered multiple times? The existing naming structure seems better to me since it forces uniqueness even if the type is different. It's a bit more boilerplate in the common case but it doesn't seem all that bad to me?

Yeah. I also hesitate to do this. So I didn't change any exist code. Then, let's just land the pin first.

**Comment by wbpcode** [comment]
Sorry for the force push :(

**Review by mattklein123 — APPROVED** [review]
LGTM!

**Pull request merged**
