### PR TITLE
build: fixing brokend dead strip

### PR DESCRIPTION
**Pull request by alyssawilk**
Signed-off-by: Alyssa Wilk <alyssar@chromium.org>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by alyssawilk** [comment]
cc @jpsim @Augustyniak

**Comment by jpsim** [comment]
Is there more context here? How can you tell it was broken before and how can you tell that this fixes the issue?

**Comment by keith** [comment]
if nothing else `--dead_strip` isn't a valid arg to any linker, but definitely not at the same time as `--gc-sections` which is ELF only

**Comment by keith** [comment]
I imagine we don't need either of those since bazel should be flipping those for us and solve the platform dependent issue

**Review by jpsim — APPROVED** [review]

**Pull request merged**
