### PR TITLE
[bp/1.24] Backport stack

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by RyanTheOptimist — DISMISSED** [review]

**Comment by phlax** [comment]
this needs a fix which im just working on

**Comment by phlax** [comment]
seems it needs another fix - the gcc job is running out of disk space, which is new i think

wondering if something chanaged with the ms-hosted agents that is reducing disk size or somesuch

**Review by RyanTheOptimist — DISMISSED** [review]
Looks like CI is still unhappy, but LGTM

**Comment by phlax** [comment]
testing a fix here https://github.com/envoyproxy/envoy/pull/28519

**Comment by phlax** [comment]
fix added, hopefully it should work

**Review by wbpcode — APPROVED** [review]
Lgtm, thanks

**Pull request merged**
