### PR TITLE
Use tcmalloc instead of gperf tcmalloc for coverage builds

### PR DESCRIPTION
**Pull request by nezdolik**
We use tcmalloc allocator for most of our builds/ci steps currently except of coverage and compile time options builds. Switching to tcmalloc should be no/low impact (as most builds use it) and unblock #32589, where tcmalloc gets extra feature (configurable memory releasing) compared to gperf tcmalloc (in this case coverage build will always fail for gperf as new feature code is not invoked for gperf).

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Comment by soulxu** [comment]
/wait

for ci

**Comment by nezdolik** [comment]
Couple of PRs are failing with similar CI error:
```
Adding cache dir (/home/vsts/work/1/a/.cache): 77M
Adding cache dir (/home/vsts/work/1/a/bazel_root/install): 175M
Adding cache dir (/home/vsts/work/1/a/bazel_root/base/external): 5.6G
Adding cache dir (/home/vsts/work/1/a/repository_cache): 1.3G
zstd: error 70 : Write error : cannot write block : No space left on device 
```

**Comment by phlax** [comment]
looks like a network transient - unable to checkout github repo

/retest

**Comment by phlax** [comment]
github seems to have recovered

/retest

**Comment by nezdolik** [comment]
Oh, looks like there is some extra features for grepf tcmalloc allocator that don't get invoked for tcmalloc. So switching is not an option cc @KBaichoo

**Comment by nezdolik** [comment]
Closing this one, as it is not feasible. (We have some gperf tcmalloc only features, so switching to tcmalloc in coverage build would fail coverage for non invoked features in tcmalloc code path)

**Comment by KBaichoo** [comment]
hmm, @nezdolik  not sure if there's a way for us to maybe define the test target twice each time using a different tcmalloc. Otherwise maybe we need to lower the coverage.

**Comment by nezdolik** [comment]
@KBaichoo apologies for delay, it took much time to fully debug gperf tcmalloc on osx arm. I will share updates in this PR: https://github.com/envoyproxy/envoy/pull/32589

**Pull request closed without merging**
