### PR TITLE
grpc: moving async client creation to statusOr

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: low
Testing: updated tests
Docs Changes: n/a
Release Notes: n/a
https://github.com/envoyproxy/envoy-mobile/issues/176

### CODE REVIEW

**Review by wbpcode — APPROVED** [review]
LGTM. Thanks.

**Comment by alyssawilk** [comment]
finally!  Sorry for the delay, PTAL!

**Review by wbpcode — APPROVED** [review]

**Pull request merged**
