### PR TITLE
Revert "HTTP2: Add DumpState support for HTTP2 (#14923)"

### PR DESCRIPTION
**Pull request by rgs1**
This reverts commit 3f740bc90d32ac442e70da46ebf4d03a1bdb479d.

Because it breaks builds on RHEL 8 and Ubuntu 18. See:

https://github.com/envoyproxy/envoy/pull/15093

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

### CODE REVIEW

**Comment by KBaichoo** [comment]
There's also been a way forward from this for several days: #15093. This handles the root cause of the breakage. Seems like @envoyproxy/senior-maintainers need to make a call.

**Comment by antoniovicente** [comment]
@lizan please chime in.  It would be better to accept #15093 than a rollback.

**Comment by KBaichoo** [comment]
See also: #15154 which just replaces the for-each-n without the lint change. I hope that's less controversial 🤞

**Comment by mattklein123** [comment]
We discussed and we will just disallow the breaking function.

**Pull request closed without merging**
