### PR TITLE
Fix ASSERT's namespace issues with abort()

### PR DESCRIPTION
**Pull request by ravenblackx**
Signed-off-by: Raven Black <ravenblack@dropbox.com>
Commit Message: Fix ASSERT having namespace issues with abort()
Additional Description: ASSERT calls abort(), which makes it do the wrong thing if ASSERT is used in a namespace with its own abort() function. This change makes ASSERT instead call ::abort(), ensuring it's using the intended version. This is a no-op for existing code, so should be no risk.
Risk Level: Low
Testing: That it doesn't change anything significant is covered by existing tests.
Docs Changes: None, this just makes ASSERT have the expected behavior in more contexts.
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by rojkov** [comment]
/assign-from @envoyproxy/first-pass-reviewers 
/wait
on CI

**Comment by ravenblackx** [comment]
To be clear about what's happening now since it's not shown in the history; each retest got it some steps further in the CI presubmits, the last one passed everything but the 'waiting' label persisted which I assume prevented reviewer attention, so now I've merged up to current to get rid of that label, and it's running the tests again, which is probably going to require several retests again to get it to pass everything.

**Review by KBaichoo — APPROVED** [review]
nice catch

**Pull request merged**
