### PR TITLE
Exclude hosts on passive healthcheck failure

### PR DESCRIPTION
**Pull request by jyotimahapatra**
Currently working on tests and docs

### CODE REVIEW

**Comment by jyotimahapatra** [comment]
https://github.com/envoyproxy/envoy/issues/9246

**Comment by jyotimahapatra** [comment]
@mattklein123 @snowp Thanks for helping with the implementation strategy.
I took a stab at it and I would like to run some thoughts by you and seek opinions/help:

1. Would changing the behaviour of `/healthcheck/fail` endpoint to exclude hosts be considered as a breaking change for any folks that might be depending on the drain behavior for their own custom assumptions. Are you aware of any edge case use cases of the drain behavior we might be breaking?
2. Do you foresee any breaking behavior wrt panic routing? Draining hosts will be excluded from panic routing calculations, and i'm worried if panic routing should still consider them to prevent scenarios where membership dropping to 0.
3. Should a host in EXCLUDE_FROM_LB state considered healthy/unhealthy? My opinion is to treat it as [unhealthy](https://github.com/envoyproxy/envoy/pull/9967/files#diff-583237ddb4e16f38ccda2e9affdb0ad8L215). I'm still looking for the implications of it, but seeking your opinion on it.
4. I'm speculating if the recovery path should include a successful healthcheck. A host which flips back to reset the exclude_from_lb state should go through a failed_active_hc and then takes usual course to become healthy. IMO it becomes easier to reason this way, but I would like to know what you feel about it.
5. Does `envoy::data::core::v3::PASSIVE` always represent a code path involving `healthcheck/fail`? From the code it looks so, but the name `PASSIVE` is probably opaque about the reason behind its occurance.

**Comment by snowp** [comment]
1. I think you'd probably want to gate this behavior on a config flag - probably on the health check config on the cluster. 

2/3. Today excluded hosts aren't really healthy/unhealthy, they are completely ignored when computing the healthy/unhealthy host sets. They are only ever routed to during panic mode, where all hosts are considered regardless of health. I'd say treat these new hosts the same as how excluded hosts are treated currently - this should address both your concerns about panic calculation + panic behavior. 

It might be nice to have health() return something indicating that this host is ignored, for the purpose of displaying this in the /clusters output. 

4. Conceptually I think it would make sense to have the first HC that a host responds with that clears the immediate health check fail be treated similar to how the first health check result is. This would mean that the host either becomes health or unhealthy depending on the success of the health check.

5. Looks like that's the case from looking at the code, I agree that it's not super well named/documented.

**Comment by mattklein123** [comment]
> 1. I think you'd probably want to gate this behavior on a config flag - probably on the health check config on the cluster.

I could go either way on this. I really don't see any downside of having this be the way that it always works as long as it is documented, and then we can avoid new configuration. Assuming we come to agree on this, I would still have a temporary runtime kill switch that we can remove later if no one complains about the new behavior.

> It might be nice to have health() return something indicating that this host is ignored, for the purpose of displaying this in the /clusters output.

This is already handled by the new enum switch for the added flag.

**Comment by jyotimahapatra** [comment]
> Today excluded hosts aren't really healthy/unhealthy, they are completely ignored when computing the healthy/unhealthy host sets.
@snowp Looks like this place considers the host `Healthy` by default if none of the conditions meet. We use `host.health()` and `host.healthFlagGet` in a combination to make decisions in many places([this](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/upstream_impl.cc#L908-L911), [this](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/upstream_impl.cc#L196), [this](https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc#L106))
I think introducing a new state [here](https://github.com/envoyproxy/envoy/blob/master/include/envoy/upstream/upstream.h#L135-L151) makes sense, I will look if that might break any scenarios

**Comment by mattklein123** [comment]
@jyotimahapatra I would need to analyze in more detail but you should not need to introduce any new states. The hosts will end up being excluded from panic, etc. calculations as desired. The new flag is orthogonal to health state.

**Comment by jyotimahapatra** [comment]
@mattklein123 Thank you for your help and I do agree with your point. The question came up because we have to add the `EXCLUDE_FROM_LB` to one of the states [here](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/upstream_impl.h#L210-L226). I'm making the function return `Unhealthy` in this PR, and it seems to work fine. Im trying to discuss if `EXCLUDE_FROM_LB` should return `Healthy` instead (to keep it consistent with the previous exclude scenario) and its implications elsewhere where the function is used to make decisions.

**Comment by mattklein123** [comment]
It should show up in the ASSERT here: https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/upstream_impl.h#L225 most likely and should not effect health state one way or the other.

/wait

**Comment by jyotimahapatra** [comment]
closing this for now

**Pull request closed without merging**
