### PR TITLE
build: Update bazel to 4.2.1

### PR DESCRIPTION
**Pull request by yanavlasov**
Signed-off-by: Yan Avlasov <yavlasov@google.com>

### CODE REVIEW

**Review by lizan — APPROVED** [review]

**Comment by wrowe** [comment]
Confirmed that the change to bazel 4.2.1 even with clang-cl 12.0.1 still causes the following error optimizing external/com_github_grpc_grpc/_objs/grpc_lb_policy_xds_cluster_resolver/xds_cluster_resolver.obj
Appears that we have to now drop clang-cl for the time being until we get this sorted out. This is probably
closely related to clang dropping the default of -g2, and missing a unix clang flag in the corresponding 
windows clang-cl compilation flags.

```
0x00007FF7FB9A09E0 (0x0000005D8B78D698 0x0000005D8B78D6B8 0x000002458BDEE9B0 0x00007FF7F9E7FFDA)
0x00007FF7FAB535F3 (0x000000010000000F 0x0000CF72063AA3D6 0x0000000000000000 0x000000000000000F)
0x00007FF7F9EBB562 (0x0000000000000018 0x00007FF7FB9BE2E3 0x00000000000000E8 0x000003FA000003F7)
0x00007FF7F9E8250C (0x000002458BDFBC90 0x0000005D00000000 0x0000000000000104 0x000000000000000F)
0x00007FF7F9F22A2E (0x0000000000000000 0x00007FF7FC67B2C0 0x0000000000000020 0x0000000000000004)
0x00007FF7F7C37164 (0x0000000000000005 0x000000000000003F 0x0000005D8ACED080 0x0000024500000000)
0x00007FF7F7C34344 (0x0000000000000120 0x000002458BDEE160 0x0000005D8B78E288 0x0000005D8B78E270)
0x00007FF7F9E0AAC6 (0x000002458BDEE160 0x0000005D8B78E270 0x0000005D8B78E288 0x00007FF7F96FC87B)
0x00007FF7F96FCBCF (0x0000005D8B78E2D8 0x000002458BE51320 0x000002458BE51320 0x00007FF7F96D071C)
0x00007FF7F9E0A206 (0x0000000000000000 0x0000001000000000 0x0000000000000104 0x0000000000000050)
0x00007FF7F9D042A7 (0x000002458BE10770 0x000002458BE101D0 0x000002458BE0A670 0x0000000000000026)
0x00007FF7F9D04839 (0x00007FF7F96FCEF0 0x00007FF7F9752E41 0x000002458BDBA3B0 0x00007FF7F96FCF0F)
0x00007FF7F9CEFDF6 (0x000000000000006B 0x00007FFE00000000 0x000002458BDB0000 0x0000000000000002)
0x00007FF7F7C33C35 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF7FB9BE9B8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFE25107974 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFE41B5A2F1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
clang-cl: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 12.0.1
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:/Program Files/LLVM/bin
clang-cl: note: diagnostic msg: 
********************
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-cl: note: diagnostic msg: C:\Windows\Temp\xds_cluster_resolver-31bafb.cpp
clang-cl: note: diagnostic msg: C:\Windows\Temp\xds_cluster_resolver-31bafb.sh
clang-cl: note: diagnostic msg: 
********************
```

**Comment by yanavlasov** [comment]
I see. I'll have to figure out how to fix this.

**Comment by phlax** [comment]
closing this as these changes have landed already

**Pull request closed without merging**
