### PR TITLE
Add Source Attribution to hot-restarter.py

### PR DESCRIPTION
**Pull request by JakeCooper**
Super simple PR

Basically adds a single comment with the link back to the "original" hot restart script

This way, people can depend on it in external repositories and know the files origin

Commit Message: add source attribution to hot-restarter
Additional Description: Adds a source link to the hot-restart python script. This is useful in case people pull it into external repositories.
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: Adds source attribution to hot-restarter
Platform Specific Features: N/A

### CODE REVIEW

**Comment by daixiang0** [comment]
Are there other places to download this script?

BTW, please fix DCO.

**Comment by snowp** [comment]
Per @daixiang0's comment I'm curious what the actual use for this is? Seems safe enough just not sure what the value is

Also DCO needs resolving: https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md#dco-sign-your-work

/wait

**Comment by daixiang0** [comment]
> Per @daixiang0's comment I'm curious what the actual use for this is? Seems safe enough just not sure what the value is

yep, this is what I am concerned.

**Pull request closed without merging**
