### PR TITLE
Update to c++ 20 for windows

### PR DESCRIPTION
**Pull request by akshaysngupta**
Commit Message: Update c++ to 20 for windows.
Additional Description:
Risk Level:
Testing:
Successful Local build
image

Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by yanavlasov** [comment]
Ah, the linker now runs out of memory: https://dev.azure.com/cncf/envoy/_build/results?buildId=153726&view=logs&j=b840a642-5ff3-5357-2e4b-e06e40b0cffd&t=67965174-5100-5631-9dc0-68b9f0aacb53&l=20976

@akshaysngupta do you know if some linker options may help memory usage? I will also check RBE set-up to see what size VMs are used and if larger VM is possible.

/wait-any

**Comment by akshaysngupta** [comment]
@yanavlasov for oom issue, phlax and I will try a few things like concurrency, larger build machine, etc.
for this pr, can you help with a re-attempt on failed jobs?

**Comment by yanavlasov** [comment]
Restarted failed jobs.

/wait-any

**Comment by akshaysngupta** [comment]
@yanavlasov new github ci for windows is passing for this. I still see the old failed azp win build check as failed.
Any way to remove it from pr checks?

image

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
