### PR TITLE
connect_grpc_bridge: Support HTTP Get requests.

### PR DESCRIPTION
**Pull request by jchadwick-buf**
Adds support for the new [Buf Connect HTTP Get requests specification](https://connect.build/docs/protocol/#unary-get-request) for `connect_grpc_bridge`. No API changes were necessary.

This also adds better support for Connect unary encoding, and adds additional unit tests to ensure correct behavior. Before, Connect unary requests and responses were forced to use identity encoding.

### CODE REVIEW

**Comment by akshayjshah** [comment]
@mattklein123 FYI, we added GETs to the Connect protocol for side-effect-free RPCs (as indicated in the Protobuf schema, [like this](https://github.com/bufbuild/connect-go/blob/main/internal/proto/connect/ping/v1/ping.proto#L65)).

**Comment by mattklein123** [comment]
CI issue looks real.

/wait

**Comment by jchadwick-buf** [comment]
@mattklein123 Fixed, apologies.

**Review by mattklein123 — CHANGES_REQUESTED** [review]
LGTM can you add a release note and any other relevant docs?

/wait

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
