### PR TITLE
Added invalid regex for start time

### PR DESCRIPTION
**Pull request by zasweq**
Signed-off-by: Zach Reyes <zasweq@google.com>

Commit Message: Added invalid regex for start time
Additional Description: En was getting transformed into \n in substitution format parser, which is an invalid character in a HTTP Header.
Risk Level: Low
Testing: Added case in unit test
Docs Changes:
Release Notes:

### CODE REVIEW

**Review by asraa — COMMENTED** [review]
Thanks, here's some documentation about time formatting, it might explain what the E is. http://www.cplusplus.com/reference/ctime/strftime/

Are you sure that %E4n% won't create a newline?

**Comment by zasweq** [comment]
Just added corpus - seems to work.

**Comment by zasweq** [comment]
For some reason, %E4n% gets caught somewhere as invalid.

**Comment by asraa** [comment]
Sounds good. Yes, what I meant was (1) Does your regex intend to catch %E4n as invalid? (2) Is it invalid?
https://man7.org/linux/man-pages/man3/strftime.3.html

To answer one question, I think the regex catches %E4n% as invalid. But I'm not sure that it causes a newline. What about %4En%?

**Comment by zasweq** [comment]
Good point. Checking now. E shouldnt be in kleene star perhaps.

**Review by asraa — DISMISSED** [review]
Thank you so much for working through that regex!

**Review by asraa — APPROVED** [review]

**Pull request merged**
