### PR TITLE
ci: mark coverage flaky and multiple attempts in CI

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Comment by mattklein123** [comment]
Seems like this is not going to help per your Slack comment?

**Comment by lizan** [comment]
@mattklein123 yeah the failure was consistent but with GTEST_SHUFFLE it is gone. The crash is from gRPC completion queue thread which might caused by testing order.

**Comment by mattklein123** [comment]
> @mattklein123 yeah the failure was consistent but with GTEST_SHUFFLE it is gone. The crash is from gRPC completion queue thread which might caused by testing order.

Hmm OK do you mind opening a tech debt/flake issue to track the actual issue and put a link to the issue in a comment above the shuffle option? Thank you for looking into this!

**Comment by lizan** [comment]
@mattklein123 done

**Pull request merged**
