### PR TITLE
readme: badges

### PR DESCRIPTION
**Pull request by mattklein123**
Fixes https://github.com/envoyproxy/envoy/issues/1664

Signed-off-by: Matt Klein <mklein@lyft.com>

### CODE REVIEW

**Comment by mattklein123** [comment]
@caniszczyk

**Comment by caniszczyk** [comment]
Awesome!

**Comment by caniszczyk** [comment]
LGTM

**Comment by htuch** [comment]
LGTM, I hope someone is tracking those 95 defects that Coverity flags! :)

**Pull request merged**
