### PR TITLE
refactor to remove QueryParams in favor of QueryParamsMulti

### PR DESCRIPTION
**Pull request by turettn**
Commit Message:

remove old version of QueryParams data structure

Additional Description:

This is the final piece of series of PRs that began with #28788.  That PR fixed a bug in ext_authz query parameter mutation which was caused by treating query params as a `map<string, string>` when in fact they are a `map<string, vector<string>>`.

The `QueryParams` type also had a bunch of `TODO` comments around it.  @ggreenway suggested that we just replace it entirely with the new, nicely encapsulated type, and I agreed to do that.  This led to #29385, #29756, #29757, #29909, and #29910.

This PR:
* Converts the remaining usages of `QueryParams` to `QueryParamsMulti`
* Removes `QueryParams`
* Removes associated unit tests.

Risk Level: Low

Testing: Existing unit tests appear to provide sufficient coverage.  There's one test that still seems unhappy - looking at the logs, it just a flake: `failed to authorize: failed to fetch oauth token: Post "https://auth.docker.io/token": EOF`.  I tried to `/retest` it, but that didn't seem to take.  Let me know if there's anything I need to do on my end to make it happy.

Docs Changes: N/A

Release Notes: N/A

Platform Specific Features: N/A

### CODE REVIEW

**Review by ggreenway — APPROVED** [review]
LGTM. Thanks!

/retest

**Comment by jmarantz** [comment]
I hadn't noticed this refactor before; @turettn did you try using the admin-console UI for config_dump before/after this change?

**Comment by jmarantz** [comment]
The html forms used in the admin console do generate blank values. So we need to handle those as if they are not specified, unfortunately.

**Comment by jmarantz** [comment]
I'm think also that we need to test the admin console UI manually for every place in the admin system where we replaced the query-params structure.

**Comment by turettn** [comment]
Got it.  There are certainly no objections from me on either of those.

Whenever I try to work on envoy I need to block off around 2 days to get my local dev environment working again, remember how to write C++, and re-familiarize myself with the code base.  I'm swamped this week, but can probably get a PR up towards the end of next week.  If someone else can get it done faster, please feel free to fire away.

**Comment by jmarantz** [comment]
Thanks @turettn -- for some reason I can't assign the bug to you; I'm not sure why.

When ready, can you add me as a 1st pass reviewer before Greg's final sign-off?

**Pull request merged**
