### PR TITLE
ext_proc filter allow_mode_override API implemenation

### PR DESCRIPTION
**Pull request by yanjunxiang-google**
ext_proc filter allow_mode_override API implemenation.

This is a follow up commit for https://github.com/envoyproxy/envoy/pull/27542.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by yanavlasov — DISMISSED** [review]

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Comment by yanjunxiang-google** [comment]
kind ping @envoyproxy/api-shepherds

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
