### PR TITLE
deps: Bump `flake8` -> 6.0.0

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
`envoy.code.check` needs a compat update

**Comment by wbpcode** [comment]
friendly ping @moderation

**Comment by moderation** [comment]
@wbpcode I approved the deps on this already and it doesn't look like it needs re-approval

**Comment by wbpcode** [comment]
> @wbpcode I approved the deps on this already and it doesn't look like it needs re-approval

Thanks. Get it.

**Review by wbpcode — APPROVED** [review]
LGTM. Thanks for all your great work.

**Pull request merged**
