### PR TITLE
Greenlight and reclassify //test/... with the current progress for Windows

### PR DESCRIPTION
**Pull request by wrowe**
Commit Message: Greenlight and reclassify //test/... with the current progress for Windows

Additional Description:
- Unmark now-passing tests on windows, addressed by various PRs including https://github.com/envoyproxy/envoy/pull/12527
- Mark sometimes-failing tests as flaky_on_windows
- Inventory the flaky_ and fails_ items for re-review when examining windows CI build logs

Based on the research conducted over the past week;
  https://github.com/envoyproxy/envoy/pull/11904

Co-authored-by: William A Rowe Jr <wrowe@vmware.com>
Co-authored-by: Sunjay Bhatia <sunjayb@vmware.com>
Signed-off-by: William A Rowe Jr <wrowe@vmware.com>
Signed-off-by: Sunjay Bhatia <sunjayb@vmware.com>

Risk Level: low
Testing: exhaustive on local Windows environment and 7 passes through the GCP CI pipeline bringing confidence to 99%
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by wrowe** [comment]
Windows passed... picked up additional accepted Windows PR's for a final pre-flight check through CI, although it looks like someone has merged something very disruptive to master.

**Comment by wrowe** [comment]
cc @envoyproxy/windows-dev

**Comment by wrowe** [comment]
Looks like the chaos in the linux x86_64 build has been resolved. @mattklein123 this is the patch you were looking for that validates much of your efforts on simtime and test infrastructure last week.

**Comment by wrowe** [comment]
This should go green again in CI, and is ready for review/merge.

**Comment by sunjayBhatia** [comment]
Something looks up with RBE seeing this in the test logs and the Windows build is taking a while:

```
[4,419 / 5,716] Compiling source/common/version/manual_linkstamp.cc; 1693s remote ... (75 actions running)
```

Shouldn't be related to anything we changed I believe

**Pull request merged**
