### PR TITLE
deps: Bump com_github_nghttp2_nghttp2 -> 1.60.0

### PR DESCRIPTION
**Pull request by birenroy**
Cloned from https://github.com/envoyproxy/envoy/pull/32934.

Fix https://github.com/envoyproxy/envoy/issues/32668

### CODE REVIEW

**Review by phlax — APPROVED** [review]
lgtm, thanks @birenroy

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by phlax** [comment]
@birenroy looks like the mobile fails are real - at least they are failing on rerun

**Comment by birenroy** [comment]
> @birenroy looks like the mobile fails are real - at least they are failing on rerun

Oops, just saw this.

@RyanTheOptimist @danzh2010 Do you know how to run these tests locally? I don't know anything about the Envoy mobile test targets.

**Comment by RyanTheOptimist** [comment]
> > @birenroy looks like the mobile fails are real - at least they are failing on rerun
> 
> Oops, just saw this.
> 
> @RyanTheOptimist @danzh2010 Do you know how to run these tests locally? I don't know anything about the Envoy mobile test targets.

You should be able to cd in the mobile/ subdirectory and run `./bazelw test test/kotlin/integration/...`. But you'll need to have your Android dev environment set up. https://envoymobile.io/docs/envoy-mobile/latest/start/building/building.html#android-requirements

**Comment by phlax** [comment]
@RyanTheOptimist afaict ios/tests are permafailing - certainly all recent runs (today) have been failing with the same issue

i was just trying to track where it started - seems here https://github.com/envoyproxy/envoy/commit/716353e26ca36b738a5e4e61230856e0d3fa7f07 altho im not convinced its the cause

**Pull request merged**
