### PR TITLE
proto: Handle maps correctly in `redact`.

### PR DESCRIPTION
**Pull request by paul-r-gall**
Signed-off-by: Paul Gallagher <pgal@google.com>

Commit Message: proto: handle maps correctly in `redact`.
Additional Description: Currently, when a map is marked as sensitive, `redact` will turn every key into the string "[redacted]", thereby invalidating the map. This change causes the map to only have values converted to "[redacted]".
Risk Level: low
Testing: unit tested.
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by paul-r-gall** [comment]
flaky.

/retest

**Comment by paul-r-gall** [comment]
@lizan please assign to maintainer?

**Review by lizan — APPROVED** [review]

**Pull request merged**
