### PR TITLE
[1.19] backport #19971 SDS: reduce cost of secret update

### PR DESCRIPTION
**Pull request by lambdai**
Commit Message:
Backport #19971
Signed-off-by: Yuchen Dai silentdai@gmail.com

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by lambdai** [comment]
It seems the macos failure is unrelated

```
ERROR: /Users/runner/work/1/s/source/exe/BUILD:23:16: Linking source/exe/envoy-static failed: (Aborted): cc_wrapper.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_runner/3d1a7f52fd47fc9a8db71770aacd13e5/sandbox/darwin-sandbox/3950/execroot/envoy && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=12.1 \
    PATH=/usr/local/bin:/opt/local/bin:/usr/bin:/bin \
    XCODE_VERSION_OVERRIDE=13.2.1.13C100 \
  external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-fastbuild/bin/source/exe/envoy-static-2.params)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]

```

**Comment by ggreenway** [comment]
I tried building this locally to debug, and realized I can't build 1.19 on mac at all, because something in cmake_external for zlib can't find cmake in the PATH.

**Comment by lambdai** [comment]
@ggreenway And the issue at your side and in this macos ci are irrelevant because CI failed at the last step linking envoy-static binary

Does it mean there are two issues?

**Comment by ggreenway** [comment]
> @ggreenway And the issue at your side and in this macos ci are irrelevant because CI failed at the last step linking envoy-static binary
> 
> Does it mean there are two issues?

I think my local issue is because cmake is at `/opt/brew/bin`, which I think is not standard but it is in my PATH, but bazel/cmake overrides my PATH. It fails for me very early in the build, so that doesn't affect CI.

It just means I can't help debug it locally.

**Comment by phlax** [comment]
@ggreenway im wondering if we can land this address the macos fail separately - checking the postsubmit queue for this branch, it seems the error was already there

**Comment by ggreenway** [comment]
@phlax that's fine with me.

**Comment by lambdai** [comment]
Great! @ggreenway Will you merge this?

**Comment by ggreenway** [comment]
> Great! @ggreenway Will you merge this?

No, I don't have permission. You need a repo-admin to do it. cc @mattklein123 or @alyssawilk or @lizan

**Comment by alyssawilk** [comment]
Can we make sure to get a tracking bug for the test failure?

**Comment by lambdai** [comment]
@alyssawilk I created issue 
I can create another backport to verify :)

**Comment by alyssawilk** [comment]
Thanks @lambdai !  assigned it to the release folks :-)

**Pull request merged**
