### PR TITLE
Fix bazel build against release 0.6.0 for Ubuntu.

### PR DESCRIPTION
**Pull request by mrice32**
Fixed bazel 0.6.0 release issue stemming from a missing symlink.  Not sure if other build targets will have issues.

### CODE REVIEW

**Comment by mrice32** [comment]
cc @htuch 
I'm assuming we'll need to push out a new image to get bazel 0.6.0 for CI runs?

**Comment by mattklein123** [comment]
@mrice32 yes just do a whitespace change somewhere in build_container to kick the image build. (We really should pin Bazel, free to do that somehow also). Then you can update as part of this change.

**Comment by mrice32** [comment]
@mattklein123 see #1770.  Cool, I'll discuss pinning bazel with @htuch.

**Comment by htuch** [comment]
LGTM, will we hit the same issues pinning Bazel as we did with Clang?

**Comment by mattklein123** [comment]
@mrice32 image build is here: https://circleci.com/gh/envoyproxy/envoy/1044?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Pull request merged**
