### PR TITLE
contrib-sip-proxy: Fix Issues of request_active_ counter and mismatched tra context

### PR DESCRIPTION
**Pull request by durd07**
1. Fix issue 22306
2. Fix issue of mismatched tra context

Signed-off-by: Felix Du <durd07@gmail.com>

Commit Message:
Additional Description:
Risk Level: Low
Testing: UT
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/22306
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by durd07** [comment]
@dorisd0102 Please help to review this, 
Thanks.

**Comment by durd07** [comment]
@phlax  Please help to merge this,
Thanks in advance.

**Comment by dorisd0102** [comment]
LGTM

**Review by htuch — APPROVED** [review]
Not vouching for correctness here, but providing contrib-level code approval.

**Pull request merged**
