### PR TITLE
clang-tidy: performance-noexcept-move-constructor

### PR DESCRIPTION
**Pull request by derekargueta**
Description: `performance-noexcept-move-constructor` checks for move constructors that aren't declared `noexcept`, the reason being that STL containers will use the copy constructor for operations like `emplace_back` if the move constructor is not declared `noexcept` due to exception safety guarantees.
http://www.hlsl.co.uk/blog/2017/12/1/c-noexcept-and-move-constructors-effect-on-performance-in-stl-containers
https://stackoverflow.com/a/32225460
Risk Level: low
Testing: existing
Docs Changes: N/A
Release Notes: N/A

Relates to #4863 

Signed-off-by: Derek Argueta <dereka@pinterest.com>

### CODE REVIEW

**Comment by silentdai** [comment]
This is subtle. TIL

**Comment by derekargueta** [comment]
hmm coverage keeps core-dumping, seemingly on `IpVersions/ProxyFilterIntegrationTest.RemoveHostViaTTL/IPv4`

`external/bazel_tools/tools/test/test-setup.sh: line 310:  2368 Aborted                 (core dumped) "${TEST_PATH}" "$@" 2>&1`

Not seeing anything on master relating to a "fix" for this, gonna give it one more retest, and if that fails will merge master. BTW is there a way to access the error log file from Circle CI? I haven't figured that out yet for looking at the exact error log.

**Comment by mattklein123** [comment]
@derekargueta that test flake is fixed in https://github.com/envoyproxy/envoy/pull/7361

**Pull request merged**
