### PR TITLE
fix changelog.yaml

### PR DESCRIPTION
**Pull request by ohadvano**
Commit Message: fix changelog.yaml for code format checks
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Review by jchadwick-buf — APPROVED** [review]
Sorry about this! the git hooks don't work correctly on my machine, so I normally have to run the format checks manually and i must've missed this.

**Comment by ohadvano** [comment]
No worries @jchadwick-buf, @phlax can you please force-push this so the code format checks pass?

**Comment by cpakulski** [comment]
Thanks! Noticed the same and was working on the fix and then saw your PR.

**Review by phlax — APPROVED** [review]
lgtm, thanks @ohadvano

**Pull request merged**
