### PR TITLE
mocks: Add MockClusterTypedMetadata and expose from MockClusterInfo.

### PR DESCRIPTION
**Pull request by jeffpiazza-google**
Signed-off-by: Jeff Piazza <jeffpiazza@google.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:Adds a MockClusterTypedMetadata class and exposes a default instance from MockClusterInfo.
Risk Level:Low
Testing:n/a
Docs Changes:n/a
Release Notes:n/a
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by zuercher** [comment]
@junr03 I think this replaces an earlier PR you were waiting on.

**Comment by jeffpiazza-google** [comment]
I have some Google-internal tests for which I was looking for something
like this, but I don't otherwise have any tests that exercise this.
/JEP

**Comment by junr03** [comment]
@alyssawilk do you mind taking a quick look?

**Comment by jeffpiazza-google** [comment]
I looked a bit, but didn't see any upstream tests that were natural consumers of these mocks.  Nonetheless, we have some in-house tests for which we'd like to have these mocks available.

**Pull request merged**
