### PR TITLE
owners: add Keith Smiley

### PR DESCRIPTION
**Pull request by mattklein123**
Welcome and thank you so much!!!

### CODE REVIEW

**Comment by mattklein123** [comment]
cc @keith @envoyproxy/envoy-maintainers. :tada: :tada: :tada:

**Review by keith — APPROVED** [review]
❤️ thanks everyone!

**Review by lizan — APPROVED** [review]

**Comment by phlax** [comment]
welcome @keith - great to have you on board

**Review by phlax — APPROVED** [review]
lgtm!

**Pull request merged**
