### PR TITLE
test: Flag-guard the XdsBuilder copy constructor test

### PR DESCRIPTION
**Pull request by abeyad**

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]
Ah! That explains it!

**Comment by RyanTheOptimist** [comment]
> Ah! That explains it!

Do you know why the compile time options build did not catch this?

**Comment by abeyad** [comment]
> > Ah! That explains it!
> 
> Do you know why the compile time options build did not catch this?

B/c it's only building the android-dist target, not the tests: https://github.com/envoyproxy/envoy/blob/4876e6911e439b68c82040a3774a37de0d3e78c0/.github/workflows/mobile-compile_time_options.yml#L98

**Comment by abeyad** [comment]
Might be a good idea to build the tests as part of compile_time_options

**Comment by RyanTheOptimist** [comment]
> > > Ah! That explains it!
> > 
> > 
> > Do you know why the compile time options build did not catch this?
> 
> B/c it's only building the android-dist target, not the tests:
> 
> https://github.com/envoyproxy/envoy/blob/4876e6911e439b68c82040a3774a37de0d3e78c0/.github/workflows/mobile-compile_time_options.yml#L98

Oh, of course! Thanks!

**Pull request merged**
