### PR TITLE
Reduce Route/VirtualHost memory utilization by avoiding HeaderParser instances when not needed

### PR DESCRIPTION
**Pull request by yurykats**
Reduce Route/VirtualHost memory utilization by avoiding HeaderParser instances when not needed.

Currently 2 instances of HeaderParsers are created in each vhost and route, even if no custom headers are configured. This PR only creates HeaderParser objects when actually configured. Otherwise a singleton default parser is used.

This is a step towards more memory efficient config data structures. Issue #24154.

Signed-off-by: Yury Kats <ykats@google.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by zuercher** [comment]
I think this looks good, but needs main merged in.

**Comment by yurykats** [comment]
Thanks for the review! Main merged, PTAL.

**Comment by yurykats** [comment]
@adisuissa PTAL, thanks!

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Comment by yurykats** [comment]
@zuercher please take a look, thanks!

**Review by zuercher — APPROVED** [review]

**Pull request merged**
