### PR TITLE
tests: Enforce extracted tags in TagExtractedNameGenerationTest 

### LINKED ISSUE #17687: TEST_P(XfccIntegrationTest, TagExtractedNameGenerationTest) has lots of stale test cases
This test contains a list of stat names to check how they are tag extracted. While making a small change to this test, I noticed that many of the elements in the list are never checked at all (I think the count was 174). 

This test should be cleaned up to reflect current stats that are emitted, and then modified so that un-tested cases make the test fail, so that it doesn't become stale in the future.

### PR DESCRIPTION
**Pull request by tpetkov-VMW**
Along with this, remove stale test cases

Signed-off-by: Toma Petkov <tpetkov@vmware.com>

Commit Message: Enforce extracted tags in TagExtractedNameGenerationTest
Additional Description: Many test cases are not hit at all, because of code changes.
Risk Level: Low
Testing: Integration test
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
Fixes #17687
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by daixiang0** [comment]
Let's check the coverage to ensure no delete by mistake.

**Review by ggreenway — CHANGES_REQUESTED** [review]
For cases that weren't being hit, can we try to fix at least some of them to match the current stats? I realize that they were all dead test cases before, but they were at least a record of what we wanted to cover in the test.

/wait

/wait

**Comment by tpetkov-VMW** [comment]
> For cases that weren't being hit, can we try to fix at least some of them to match the current stats? I realize that they were all dead test cases before, but they were at least a record of what we wanted to cover in the test.

I'm not sure how to track down changed statistics, given that they would have different keys and are in the hundreds.
But I can just add new testcases for some of the missing metrics. Is there a list of all the metrics somewhere?

**Comment by tpetkov-VMW** [comment]
Found this script in the test itself, to regenerate the tags.
I think this achieves what we want, doesn't it?
```c++   
  // Commented sample code to regenerate the map literals used below in the test log if necessary:
   std::cout << "tag_extracted_counter_map = {";
   std::vector<Stats::CounterSharedPtr> counters = test_server_->counters();
   for (auto it = counters.begin(); it != counters.end(); ++it) {
     if (it != counters.begin()) {
       std::cout << ",";
     }
     std::cout << std::endl << "{\"" << (*it)->name() << "\", \"" << (*it)->tagExtractedName() <<
     "\"}";
   }
   std::cout << "};" << std::endl;
   std::cout << "tag_extracted_gauge_map = {";
   std::vector<Stats::GaugeSharedPtr> gauges = test_server_->gauges();
   for (auto it = gauges.begin(); it != gauges.end(); ++it) {
     if (it != gauges.begin()) {
       std::cout << ",";
     }
     std::cout << std::endl << "{\"" << (*it)->name() << "\", \"" << (*it)->tagExtractedName() <<
     "\"}";
   }
   std::cout << "};" << std::endl;
```

**Review by jmarantz — APPROVED** [review]
I don't have a ton of insight into what the value of this test was in the first place, but I'm fine with updating it.

**Review by jmarantz — APPROVED** [review]
If I'm reading the history right this test was created by @myidpt who's last commit was 2020.

But I'm tempted to just merge this change.

**Review by ggreenway — APPROVED** [review]
LGTM. Thanks for fixing this!

**Pull request merged**
