### PR TITLE
[balsa] Delay resetting BalsaFrame.

### LINKED ISSUE #34096: HTTP/1 balsa parser prematurely purges parsed headers resulting in status monitor failure
During [UpstreamHttp11ConnectSocket::isValidConnectResponse()]( https://github.com/RenjieTang/envoy/blob/5d797fb4ef04d67b68a8c5c947cb64e9473d073c/source/extensions/transport_sockets/http_11_proxy/connect.cc#L23), a framer is used under the hood to parse the header. Later its statusCode() is used to determine validity.

However, when the response header contains `content-length: 0`, [BalsaParser::MessageDone()](https://github.com/RenjieTang/envoy/blob/5d797fb4ef04d67b68a8c5c947cb64e9473d073c/source/common/http/http1/balsa_parser.cc#L356) will be invoked which purges the parsed header. Later when statusCode() is called, since the header is empty, the default 0 status code is returned and the response is mistaken as invalid.

This bug is sneaky because when `content-length` isn't present, the framer will [wait](https://github.com/google/quiche/blob/ee237e96f18ef123af9992f74645a8a0ce9ef6ef/quiche/balsa/balsa_frame.cc#L719) to read more data until the connection close, and thus  MessageDone() is never called.

I think the correct fix should be to not reset the header when the framer is [cleared](https://github.com/google/quiche/blob/ee237e96f18ef123af9992f74645a8a0ce9ef6ef/quiche/balsa/balsa_frame.cc#L80), because the header is owned by the BalsaParser.

### PR DESCRIPTION
**Pull request by bencebeky**
Delay resetting BalsaFrame until the first byte of the next message is parsed. This is necessary for being able to access information about the parsed headers after the message is fully parsed, for example, response status code, and content-length and transfer-encoding headers.

Fixes #34096

Balsa implementation tracking issue: #21245

Commit Message: [balsa] Delay resetting BalsaFrame.
Additional Description:
Risk Level: low
Testing: test/extensions/transport_sockets/http_11_proxy:connect_test
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a
Runtime guard: envoy.reloadable_features.http1_balsa_delay_reset (default true)

### CODE REVIEW

**Review by alyssawilk — APPROVED** [review]
My only question is if we should runtime guard.  cc @RyanTheOptimist for a thoughts before I merge

**Comment by RyanTheOptimist** [comment]
> My only question is if we should runtime guard. cc @RyanTheOptimist for a thoughts before I merge

Yeah this seems wise to me. I think we can use a default true flag so it will take effect immediately, but it just gives us a backup in case there is an edge case here we have not discovered.

**Comment by bencebeky** [comment]
> > My only question is if we should runtime guard. cc @RyanTheOptimist for a thoughts before I merge
> 
> Yeah this seems wise to me. I think we can use a default true flag so it will take effect immediately, but it just gives us a backup in case there is an edge case here we have not discovered.

Done.

**Review by alyssawilk — DISMISSED** [review]

**Comment by alyssawilk** [comment]
LGTM modulo ci unhappiness

**Review by alyssawilk — APPROVED** [review]
LGTM, ci willing

**Comment by sschepens** [comment]
@alyssawilk @bencebeky shouldn't this kind of fixes be backported to 1.30, 1.29 and 1.28 since Balsa is the default parser?

**Comment by bencebeky** [comment]
@sschepens Normally yes, it should. However, it turns out that the way ConnectionImpl is using the Parser interface, this issue never comes in practice. This issue was only discovered when UpstreamHttp11ConnectSocket started to use BalsaParser differently, through SelfContainedParser, and it is believed that this fix does not actually affect HTTP/1 parsing other than in that one extension (which still seems to be under development). Therefore I believe that a backport is not necessary in this case.

**Pull request merged**
