### PR TITLE
build: Update build image

### PR DESCRIPTION
**Pull request by ggreenway**
This pulls in the dependency version changes that @moderation recently made.

*Risk Level*: Low
*Testing*: Existing tests
*Docs Changes*: none
*Release Notes*: none

### CODE REVIEW

**Comment by ggreenway** [comment]
The clang_tidy build is hitting an internal bazel error. The previous build image was on bazel 0.20.0; this one is picking up 0.21.0 (build image takes the latest available from `deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8` at build time). Any bazel experts know what's going on? @jmillikin-stripe ?

```
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/source/ci/tools/bazel.rc
INFO: Invocation ID: 0508b1b9-c9e2-4599-9d17-c13669461a07
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/source/ci/tools/bazel.rc
INFO: Invocation ID: 6e1c6d90-9822-4775-8d96-87a10cac31df
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/source/ci/tools/bazel.rc
INFO: Invocation ID: c0b10b66-8fa9-401f-93d7-06624e7b69ce
ERROR: error loading package '': Unable to load package for '//bazel:repositories.bzl': BUILD file not found on package path
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/source/ci/tools/bazel.rc
INFO: Invocation ID: 7288aac5-b5eb-4ba9-8853-31919c956acf
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: Bad ch: InMemoryNodeEntry{identity=545000371, value=null, lastChangedVersion=IntVersion: 5829, lastEvaluatedVersion=IntVersion: 5829, directDeps=GroupedList{elements=[FILE:[/source/ci]/[tools], FILE_STATE:[/source/ci]/[tools/bazel.rc], FILE:[/source]/[tools], FILE_STATE:[/source]/[tools/bazel.rc]], size=4}, signaledDeps=4, reverseDeps=ReverseDeps{reverseDeps=RECURSIVE_PKG rootedPath=[/source/ci]/[tools/bazel.rc], excludedPaths=<omitted>, singleReverseDep=true, dataToConsolidate=[RECURSIVE_PKG rootedPath=[/source/ci]/[tools/bazel.rc], excludedPaths=<omitted>]}, dirtyBuildingState=FullDirtyBuildingState{dirtyState=REBUILDING, dirtyDirectDepIndex=0, lastBuildDirectDeps=GroupedList{elements=[FILE:[/source/ci]/[tools], FILE_STATE:[/source/ci]/[tools/bazel.rc], FILE:[<absolute root>]/[/source/tools], FILE_STATE:[<absolute root>]/[/source/tools/bazel.rc]], size=4}, lastBuildValue=symlink (real_path=[<absolute root>]/[/source/tools/bazel.rc], real_state=RegularFileStateValue{digest=null, size=2172, contentsProxy=ctime of 1546643563712 and nodeId of 3555}, link_value=/source/tools/bazel.rc)}}, IntVersion: 1, symlink (real_path=[/source]/[tools/bazel.rc], real_state=RegularFileStateValue{digest=null, size=2172, contentsProxy=ctime of 1546643563712 and nodeId of 3555}, link_value=/source/tools/bazel.rc)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.assertVersionCompatibleWhenSettingValue(InMemoryNodeEntry.java:340)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.setValue(InMemoryNodeEntry.java:301)
	at com.google.devtools.build.skyframe.SkyFunctionEnvironment.commit(SkyFunctionEnvironment.java:752)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:534)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

INFO: Elapsed time: 1.190s
INFO: 0 processes.
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: Bad ch: InMemoryNodeEntry{identity=545000371, value=null, lastChangedVersion=IntVersion: 5829, lastEvaluatedVersion=IntVersion: 5829, directDeps=GroupedList{elements=[FILE:[/source/ci]/[tools], FILE_STATE:[/source/ci]/[tools/bazel.rc], FILE:[/source]/[tools], FILE_STATE:[/source]/[tools/bazel.rc]], size=4}, signaledDeps=4, reverseDeps=ReverseDeps{reverseDeps=RECURSIVE_PKG rootedPath=[/source/ci]/[tools/bazel.rc], excludedPaths=<omitted>, singleReverseDep=true, dataToConsolidate=[RECURSIVE_PKG rootedPath=[/source/ci]/[tools/bazel.rc], excludedPaths=<omitted>]}, dirtyBuildingState=FullDirtyBuildingState{dirtyState=REBUILDING, dirtyDirectDepIndex=0, lastBuildDirectDeps=GroupedList{elements=[FILE:[/source/ci]/[tools], FILE_STATE:[/source/ci]/[tools/bazel.rc], FILE:[<absolute root>]/[/source/tools], FILE_STATE:[<absolute root>]/[/source/tools/bazel.rc]], size=4}, lastBuildValue=symlink (real_path=[<absolute root>]/[/source/tools/bazel.rc], real_state=RegularFileStateValue{digest=null, size=2172, contentsProxy=ctime of 1546643563712 and nodeId of 3555}, link_value=/source/tools/bazel.rc)}}, IntVersion: 1, symlink (real_path=[/source]/[tools/bazel.rc], real_state=RegularFileStateValue{digest=null, size=2172, contentsProxy=ctime of 1546643563712 and nodeId of 3555}, link_value=/source/tools/bazel.rc)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.assertVersionCompatibleWhenSettingValue(InMemoryNodeEntry.java:340)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.setValue(InMemoryNodeEntry.java:301)
	at com.google.devtools.build.skyframe.SkyFunctionEnvironment.commit(SkyFunctionEnvironment.java:752)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:534)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException: Bad ch: InMemoryNodeEntry{identity=545000371, value=null, lastChangedVersion=IntVersion: 5829, lastEvaluatedVersion=IntVersion: 5829, directDeps=GroupedList{elements=[FILE:[/source/ci]/[tools], FILE_STATE:[/source/ci]/[tools/bazel.rc], FILE:[/source]/[tools], FILE_STATE:[/source]/[tools/bazel.rc]], size=4}, signaledDeps=4, reverseDeps=ReverseDeps{reverseDeps=RECURSIVE_PKG rootedPath=[/source/ci]/[tools/bazel.rc], excludedPaths=<omitted>, singleReverseDep=true, dataToConsolidate=[RECURSIVE_PKG rootedPath=[/source/ci]/[tools/bazel.rc], excludedPaths=<omitted>]}, dirtyBuildingState=FullDirtyBuildingState{dirtyState=REBUILDING, dirtyDirectDepIndex=0, lastBuildDirectDeps=GroupedList{elements=[FILE:[/source/ci]/[tools], FILE_STATE:[/source/ci]/[tools/bazel.rc], FILE:[<absolute root>]/[/source/tools], FILE_STATE:[<absolute root>]/[/source/tools/bazel.rc]], size=4}, lastBuildValue=symlink (real_path=[<absolute root>]/[/source/tools/bazel.rc], real_state=RegularFileStateValue{digest=null, size=2172, contentsProxy=ctime of 1546643563712 and nodeId of 3555}, link_value=/source/tools/bazel.rc)}}, IntVersion: 1, symlink (real_path=[/source]/[tools/bazel.rc], real_state=RegularFileStateValue{digest=null, size=2172, contentsProxy=ctime of 1546643563712 and nodeId of 3555}, link_value=/source/tools/bazel.rc)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.assertVersionCompatibleWhenSettingValue(InMemoryNodeEntry.java:340)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.setValue(InMemoryNodeEntry.java:301)
	at com.google.devtools.build.skyframe.SkyFunctionEnvironment.commit(SkyFunctionEnvironment.java:752)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:534)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException: Bad ch: InMemoryNodeEntry{identity=545000371, value=null, lastChangedVersion=IntVersion: 5829, lastEvaluatedVersion=IntVersion: 5829, directDeps=GroupedList{elements=[FILE:[/source/ci]/[tools], FILE_STATE:[/source/ci]/[tools/bazel.rc], FILE:[/source]/[tools], FILE_STATE:[/source]/[tools/bazel.rc]], size=4}, signaledDeps=4, reverseDeps=ReverseDeps{reverseDeps=RECURSIVE_PKG rootedPath=[/source/ci]/[tools/bazel.rc], excludedPaths=<omitted>, singleReverseDep=true, dataToConsolidate=[RECURSIVE_PKG rootedPath=[/source/ci]/[tools/bazel.rc], excludedPaths=<omitted>]}, dirtyBuildingState=FullDirtyBuildingState{dirtyState=REBUILDING, dirtyDirectDepIndex=0, lastBuildDirectDeps=GroupedList{elements=[FILE:[/source/ci]/[tools], FILE_STATE:[/source/ci]/[tools/bazel.rc], FILE:[<absolute root>]/[/source/tools], FILE_STATE:[<absolute root>]/[/source/tools/bazel.rc]], size=4}, lastBuildValue=symlink (real_path=[<absolute root>]/[/source/tools/bazel.rc], real_state=RegularFileStateValue{digest=null, size=2172, contentsProxy=ctime of 1546643563712 and nodeId of 3555}, link_value=/source/tools/bazel.rc)}}, IntVersion: 1, symlink (real_path=[/source]/[tools/bazel.rc], real_state=RegularFileStateValue{digest=null, size=2172, contentsProxy=ctime of 1546643563712 and nodeId of 3555}, link_value=/source/tools/bazel.rc)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.assertVersionCompatibleWhenSettingValue(InMemoryNodeEntry.java:340)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.setValue(InMemoryNodeEntry.java:301)
	at com.google.devtools.build.skyframe.SkyFunctionEnvironment.commit(SkyFunctionEnvironment.java:752)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:534)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Server terminated abruptly (error code: 14, error message: '', log file: '/build/tmp/_bazel_bazel/436badd4919a15958fa3800a4e21074a/server/jvm.out')
```

**Comment by lizan** [comment]
@ggreenway I'm looking at it.

**Comment by lizan** [comment]
Hm, it doesn't reproduce in my local env, looks like OOM or something, re kicking CI with SSH.

**Comment by mattklein123** [comment]
Closing due to other fix.

**Pull request closed without merging**
