### PR TITLE
network: Use std::make_unique and std::make_shared in source/common/network instead of bare new()

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
network: Use std::make_unique and std::make_shared in source/common/network instead of bare new()

Risk Level: Low
Testing: None - no behavior change
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by RenjieTang — APPROVED** [review]

**Review by lizan — APPROVED** [review]

**Review by alyssawilk — APPROVED** [review]
thanks for the clean up!

**Pull request merged**
