### PR TITLE
Update sidebar aesthetic

### PR DESCRIPTION
**Pull request by lucperkins**
In anticipation of diving into the structure and content of the docs, I'd like to spend a bit of time upgrading the aesthetic. This PR builds on #9760 and provides CSS overrides that should make the docs feel more "branded" and less generic. Later PRs will spiff up other parts of the site.

### CODE REVIEW

**Comment by mattklein123** [comment]
Nice. The version test is lost though now. Can you fix that?

/wait

**Comment by lucperkins** [comment]
@mattklein123 What's the current state of the art for viewing the docs locally? I have not yet been able to so I'm flying a bit blind.

**Comment by mattklein123** [comment]
`docs/build.sh`

**Comment by mattklein123** [comment]
If you don't want to install all the deps locally you can also use docker to do the doc build: https://github.com/envoyproxy/envoy/tree/master/ci#building-and-running-tests-as-a-developer

**Comment by lucperkins** [comment]
I'm going to close this until I'm able to get the docs building locally and thus to establish a reasonable workflow

**Pull request closed without merging**
