### PR TITLE
config: removing deprecated std::hash option from RingHashLbConfig

### LINKED ISSUE #5379: [v1.9.0 deprecation] Remove features marked deprecated in #4874
#4874 (upstream: switching the default hash algorithm for ring hash) introduced a deprecation notice for v1.9.0. This issue tracks source code cleanup.

### PR DESCRIPTION
**Pull request by alyssawilk**
*Risk Level*: Medium (ideally folks have moved over but you never know)
*Testing*: n/a
*Docs Changes*: n/a (I don't see any docs referencing the hash algorithm)
*Release Notes*: inline
Fixes #5379

### CODE REVIEW

**Comment by alyssawilk** [comment]
Paging @junr03 @mattklein123 to confirm you folks have moved over.  If not I can close this out for a couple of weeks.

**Comment by mattklein123** [comment]
cc @danielhochman @HenryYYang. IIRC Lyft still has not done this migration, but it has to happen at some point so that point should be soon IMO.

**Comment by junr03** [comment]
@alyssawilk, not yet. I'm ooo through the rest of the week. 

cc @danielhochman and @henryyyang, who is now leading caching/redis.

**Comment by alyssawilk** [comment]
Ok, will ping back in a few weeks to see how things are going.  No real hurry mind you - it's not a lot of code or painful to merge - I just like closing out my open issues :-P

**Comment by HenryYYang** [comment]
I talk to @danielhochman offline, looks like the std::hash<std::string> is using MurmurHashUnaligned2, maybe it's easier to include that as an option.  This way we will not be impacted by compiler/platform changes and we don't have to rehash all our redis clusters.

**Comment by mattklein123** [comment]
@HenryYYang yup that would be fine. Can you potentially work on a change to do that?

**Comment by HenryYYang** [comment]
ok, let me work on that.  In the meantime please don't remove the use_std_hash yet.

**Comment by alyssawilk** [comment]
holy bad merge!  Will fix and reopen :-P

**Pull request closed without merging**
