### PR TITLE
[WIP] adds zipkin span serializer interface and sets v1 as the default serializer.

### LINKED ISSUE #4839: Add support for sending data in Zipkin v2 format
*Title*:  Add support for sending data in Zipkin format

*Description*:
It would be really helpful to support sending data in zipkin v2 json for reasons of efficiency and reduced tech debt in trace data pipelines. This could go alongside the existing functionality. While proto3 is even more efficient, it could be optional as most don't use that.

---

Zipkin's data format has been historically criticized for its heft. Through community effort, last August 2017 we formalized a compact v2 json, accepted on all transports including http, kafka, rabbit, etc. Later, we introduced a proto3 encoding of the same, also accepted on all transports.

Between last August and now, this format has become the primary and preferred format, especially to those trying to work with the data.  For example, at a recent meeting we've found that envoy is a key piece of the network that still emits the v1 format, requiring "rosetta stone" style proxies.

This is fine in pure zipkin installs as the server reads all historical formats, but is limiting for those using different pipelines. A switch to v2 would also work with zipkin clones such as jaeger who also support that format.

[original spec for zipkin and envoy](https://docs.google.com/document/d/1q3F_RVf6Rozn69KbqhrKknOZP9_17WH1RK3wIc7AnuE/edit#)
[json v2 encoding](https://github.com/openzipkin/zipkin-api/blob/master/zipkin2-api.yaml)
[proto3 encoding](https://github.com/openzipkin/zipkin-api/blob/master/zipkin.proto)
[trace data pipeline meeting](https://cwiki.apache.org/confluence/display/ZIPKIN/2018-09-20+Filtering%2C+Aggregations+and+Proxies+at+Salesforce) 
[jaeger's v2 support](https://github.com/jaegertracing/jaeger/blob/7262bdc9e59933f15fb0802f0d3ba7fb642a8955/cmd/collector/app/zipkin/http_handler.go#L112)

### PR DESCRIPTION
**Pull request by jcchavezs**
Description: This PR **will** add support for V2 format in zipkin.
Risk Level: low
Testing: we are not including changes yet
Docs Changes: will come when the change is done
Release Notes: Adds support for Zipkin V2 format

Question: Should we support both formats or just migrate to v2?

Ping @adriancole @Dudi119 @devinsba 

Fixes #4839

### CODE REVIEW

**Comment by devinsba** [comment]
There are some third-party tools (ex: 1) that support the V1 format, and Jaeger does as well though it has first class support. It's probably best to leave in V1 until we are fairly certain that has stopped proliferating

1. https://github.com/honeycombio/honeycomb-opentracing-proxy

**Comment by adriancole** [comment]
agree adding v2 doesn't mean removing v1. Also be careful as I think @dio has some work in progress on proto

**Comment by adriancole** [comment]
because envoy is historically v1 we probably need to keep default that way unless a "poke" request succeeds. eg use OPTIONS or empty POST on /api/v2/spans. If that works (202), then we can safely use v2 unless overridden by property.

**Comment by mattklein123** [comment]
Assigning over to @objectiser who can hopefully help with review.

**Comment by dio** [comment]
@jcchavezs interesting approach to introduce the span serializer. I think we can have a config entry that tells which version to use? I have a WIP on that one. So here: https://github.com/envoyproxy/envoy/pull/6798/files#diff-eefabe600af784c84a1989f7cb174f2bR151 we can construct the serializer based on user preference. My suggestion on the enum will be: `v1_http_json`, `v2_http_json`, `v2_http_proto` (seems like `v2_grpc_stream` (or `v2_grpc_unary`?) will be there soon).

**Comment by adriancole** [comment]
my suggestion is to qualify when strange. for example, v1 is strange in
2019.. leave off the suffix for the other options as v2 is implied or
irrelevant (ex there was no v1 proto)

**Comment by adriancole** [comment]
another option would be to inherit exactly the same encoding types from
zipkin
https://github.com/apache/incubator-zipkin/blob/master/zipkin/src/main/java/zipkin2/codec/SpanBytesEncoder.java

then separate out transport/collector type from encoding as they are
definitely independent except in the rare case of grpc.

**Comment by jcchavezs** [comment]
Thanks all for the feedback!

> My suggestion on the enum will be: v1_http_json, v2_http_json, v2_http_proto (seems like v2_grpc_stream (or v2_grpc_unary?) will be there soon). WDYT?

Sounds good, tho I would follow the @adriancole's wisdom and have `v1_http_json`, `http_json` and `http_proto`. What do you think?

As soon as this one is green I will include the v2 http serializer. Also at some point we need to see how we merge our branches @dio.

**Comment by adriancole** [comment]
nit put the v1 at the end.

**Comment by dio** [comment]
@jcchavezs sorry for the late reply, this is my current WIP: https://github.com/envoyproxy/envoy/compare/master...dio:zipkin-v2?expand=1 I think the HTTP_JSON (v2) works, but not sure why sending serialized proto is still failing.

**Comment by dio** [comment]
@jcchavezs so since we agreed on doing this together, would you close this and open a new PR from our common branch? Thanks!

**Comment by jcchavezs** [comment]
Totally!

**Pull request closed without merging**
