### PR TITLE
Correct naming of  com_github_lyft_protoc_gen_star go_repository

### PR DESCRIPTION
**Pull request by alexbozhenko**
Commit Message:Correct naming of  com_github_lyft_protoc_gen_star go_repository 
Additional Description:
Similar to https://github.com/bufbuild/protoc-gen-validate/pull/900
correct naming should include the major version.

https://go.dev/ref/mod#module-path
> If the module is released at major version 2 or higher, the module path must end with a [major version suffix](https://go.dev/ref/mod#major-version-suffixes) like /v2. This may or may not be part of the subdirectory name. For example, the module with path golang.org/x/repo/sub/v2 could be in the /sub or /sub/v2 subdirectory of the repository golang.org/x/repo.

So go_repository stanza also should include the major version, to distinguish between the different major versions of the module, that can coexist.

After the change, the naming is consistent:
```
$ rg 'com_github_lyft_protoc_gen_star'
bazel/dependency_imports.bzl
128:        name = "com_github_lyft_protoc_gen_star_v2",

api/bazel/repository_locations.bzl
27:            "com_github_lyft_protoc_gen_star_v2",
```

Risk Level: None
Testing: CI passes...?
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

Signed-off-by: Alex Bozhenko <alexbozhenko@gmail.com>

### CODE REVIEW

**Comment by alexbozhenko** [comment]
@fishcakez @JuniorHsu

**Comment by htuch** [comment]
Seems fine, but maybe I'm a bit dense - how does the Bazel internal name matter?

**Comment by alexbozhenko** [comment]
@htuch: we have a setup where we import this repo and use `envoy_dependency_imports` from this repo. On top of that, we have some extra go code, that also has a dependency on `protoc_gen_star`, but on v1 of it. Because the names of those two `go_repositroes` are the same, we have a conflict, similar to what I described at https://github.com/bufbuild/protoc-gen-validate/pull/900

**Review by htuch — APPROVED** [review]
OK, seems harmless and technically right.

**Comment by phlax** [comment]
@alexbozhenko unfortunately we have just updated our ci framework so `/retest` wont work to resolve - you will need to merge `main`

**Pull request merged**
