### PR TITLE
format: fix to work with python3 walk

### PR DESCRIPTION
**Pull request by mattklein123**

### CODE REVIEW

**Comment by mattklein123** [comment]
@cclauss

**Comment by mattklein123** [comment]
@cclauss this is failing CI but it works for me locally. Unless you are around and have any ideas in the next 15-20 minutes I'm just going to revert your other change.

**Comment by mattklein123** [comment]
```check_format...
ERROR: Traceback (most recent call last):
ERROR:   File "./tools/check_format.py", line 522, in checkFormatReturnTraceOnError
ERROR:     return checkFormat(file_path)
ERROR:   File "./tools/check_format.py", line 512, in checkFormat
ERROR:     error_messages += checkSourcePath(file_path)
ERROR:   File "./tools/check_format.py", line 441, in checkSourcePath
ERROR:     error_messages = checkFileContents(file_path, checkSourceLine)
ERROR:   File "./tools/check_format.py", line 281, in checkFileContents
ERROR:     for line_number, line in enumerate(fileinput.input(file_path)):
ERROR:   File "/usr/lib/python3.5/fileinput.py", line 248, in __next__
ERROR:     line = self._readline()
ERROR:   File "/usr/lib/python3.5/fileinput.py", line 362, in _readline
ERROR:     return self._readline()
ERROR:   File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
ERROR:     return codecs.ascii_decode(input, self.errors)[0]
ERROR: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1738: ordinal not in range(128)
ERROR: 
ERROR: Traceback (most recent call last):
ERROR:   File "./tools/check_format.py", line 522, in checkFormatReturnTraceOnError
ERROR:     return checkFormat(file_path)
ERROR:   File "./tools/check_format.py", line 512, in checkFormat
ERROR:     error_messages += checkSourcePath(file_path)
ERROR:   File "./tools/check_format.py", line 441, in checkSourcePath
ERROR:     error_messages = checkFileContents(file_path, checkSourceLine)
ERROR:   File "./tools/check_format.py", line 281, in checkFileContents
ERROR:     for line_number, line in enumerate(fileinput.input(file_path)):
ERROR:   File "/usr/lib/python3.5/fileinput.py", line 248, in __next__
ERROR:     line = self._readline()
ERROR:   File "/usr/lib/python3.5/fileinput.py", line 362, in _readline
ERROR:     return self._readline()
ERROR:   File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
ERROR:     return codecs.ascii_decode(input, self.errors)[0]
ERROR: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1424: ordinal not in range(128)
ERROR: 
ERROR: Traceback (most recent call last):
ERROR:   File "./tools/check_format.py", line 522, in checkFormatReturnTraceOnError
ERROR:     return checkFormat(file_path)
ERROR:   File "./tools/check_format.py", line 508, in checkFormat
ERROR:     error_messages += checkBuildPath(file_path)
ERROR:   File "./tools/check_format.py", line 422, in checkBuildPath
ERROR:     error_messages += checkFileContents(file_path, checkBuildLine)
ERROR:   File "./tools/check_format.py", line 281, in checkFileContents
ERROR:     for line_number, line in enumerate(fileinput.input(file_path)):
ERROR:   File "/usr/lib/python3.5/fileinput.py", line 95, in input
ERROR:     raise RuntimeError("input() already active")
ERROR: RuntimeError: input() already active```

...

**Comment by mattklein123** [comment]
I guess hitting this: http://python-notes.curiousefficiency.org/en/latest/python3/text_file_processing.html

**Comment by mattklein123** [comment]
I tried a fix but it didn't work so I'm just going to revert.

**Comment by cclauss** [comment]
Understood.  Do the right thing.

**Pull request closed without merging**
