### PR TITLE
dependencies: Bump go version

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Commit Message:
dependencies: Bump go version

rules_go version we are using supports the latest 1.13 line go 1.13.12
Additional Description: N/A
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by lizan** [comment]
LGTM but let's hold for merge, I'm looking into why go-control-plane is broken https://github.com/envoyproxy/go-control-plane/pull/312

**Comment by moderation** [comment]
With Go 1.15 about to land why not update this to Go 1.14.4 which is supported by the version of rules_go that we are using https://github.com/bazelbuild/rules_go/releases/tag/v0.22.6 ?

Whatever version we go with should be updated at https://github.com/envoyproxy/envoy/blob/master/ci/verify_examples.sh#L26-L27 too

**Comment by lizan** [comment]
@moderation we're already on rules_go 0.23.3

**Comment by sunjayBhatia** [comment]
I can bump this to go 1.14.4, held off since I wasn't sure if we were ready, some other projects I worked on had minor changes required in that bump

**Comment by sunjayBhatia** [comment]
Is it possible to set up some automation for dependency bumps like this (some azure pipeline or other CI to check on the dependency version and bump it in/submit a PR for all the required places in Envoy)? Has this been something youve discussed before (also lmk if this is worth an issue rather than just these comments)?

**Pull request merged**
