### PR TITLE
config: Update CONNECT-UDP forwarding proxy config

### PR DESCRIPTION
**Pull request by jeongseokson**
Commit Message:
I removed the unnecessary certificates provided in the client context and added SNI field that matches the testing certificate in the repo.
Additional Description:
Risk Level: Low, this PR changes an example config.
Testing: N/A
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by jeongseokson** [comment]
/assign @danzh2010 

Hi Dan, can you review this PR related to #33775? Thank you.

**Review by danzh2010 — APPROVED** [review]
Thanks for the clarification! I don't think we support client certs yet.

**Comment by jeongseokson** [comment]
Thanks for reviewing, Dan. Do you have a write access to merge this @danzh2010? Should I ask someone else?

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by rishabh78** [comment]
I am still seeing error 
stream reset: reset reason: protocol error, response details: http3.invalid_header_field

**Pull request merged**
