### PR TITLE
tools: add option to gen_compilation_db for system clang

### PR DESCRIPTION
**Pull request by ggreenway**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by phlax — COMMENTED** [review]
im wondering if it would be better to just move this script to bazel (kinda my plan) so we can guarantee the clang version rather than adding any workarounds

also wondering - currently clang should still be available

cc @wbpcode

**Comment by phlax** [comment]
also worth mentioning - the reason i didnt move this to bazel already is im looking at shifting the clang-tidy part to using a bazel aspect

this would negate the need to run compdb first and almost certainly means we can run clang-tidy in presubmit/hooks/local formatting 

this is kinda an aside as we still need to be able to generate compdb pref with pinned versions

**Comment by ggreenway** [comment]
On my Mac, the generated command always gives error `Error: DEVELOPER_DIR not set.` With this new flag, clangd works correctly.

**Comment by phlax** [comment]
> With this new flag, clangd works correctly.

ok, cool - was flagging as i was already looking at this and trying to figure a better strategy

**Review by phlax — APPROVED** [review]
lgtm, thanks @ggreenway

**Review by phlax — APPROVED** [review]

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
