### PR TITLE
deps: Add dependabot.yml

### LINKED ISSUE #15628: Not all dependencies are being updated by dependabot
### description

currently we have several `requirements.txt` files for different python bazel targets

dependabot should update all of them (one way or another)

i created a test repo to figure out how to get it to do so - but i seem to have hit a bug which i created a ticket for upstream:

https://github.com/dependabot/dependabot-core/issues/3324

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: deps: Add dependabot.yml
Additional Description:

adds a dependabot.yml file to ensure all deps are monitored/updated

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #15628 
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@moderation this adds a dependabot.yml with all the requirements.txt that i found

not sure if we need to add some stanzas for other languages

**Comment by phlax** [comment]
also worth mentioning - i think this will create a waterfall of PRs !!!

**Comment by phlax** [comment]
the other thing im thinking is that we might want to add some ci to ensure that all requirements.txt (or similar) are added

**Comment by moderation** [comment]
It might trigger an avalanche of PRs but once we fix up the deps it shouldn't be high volume after that (famous last words).

**Comment by phlax** [comment]
checking whether dependabot can analyze bazel deps (not sure about our bazel setup specifically) there is a ticket for it but not atm support i think https://github.com/dependabot/dependabot-core/issues/2196

**Review by mattklein123 — COMMENTED** [review]
Thanks this is great. Do we have any way of making sure this stays up to date?

/wait-any

**Comment by phlax** [comment]
i can add now/after lmk what you would prefer

i think the bigger issue to landing this is more when @moderation is ready to deal with the fallout - theres gonna be quite a lot of PRs i think

**Comment by mattklein123** [comment]
OK SGTM. I think it's fine, we can deal with the PR fallout. It's the right thing to do. Thank you!

/wait

**Comment by phlax** [comment]
either way i added a ticket re CI - so we can land this and deal with that after if thats how it happens

**Comment by moderation** [comment]
LGTM and I think after catching up it shouldn't be too frequent. One thing I thought was interesting was that Dependabot raised PRs for Jinja but ignored everything else. Using `docs/requirements.txt` as an example, what we currently have is:
```
Babel==2.8.0 \
certifi==2020.6.20 \
chardet==3.0.4 \
GitPython==3.1.8 \
packaging==20.4 \
Pygments==2.7.1 \
pytz==2020.1 \
requests==2.24.0 \
snowballstemmer==2.0.0 \
sphinx-copybutton==0.3.0 \
sphinx-rtd-theme==0.5.0 \
sphinx-tabs==1.3.0 \
Sphinx==3.2.1 \
urllib3==1.25.10 \
```
What is current:
```
Babel==2.9.0 \
certifi==2020.12.5 \
chardet==4.0.0 \
GitPython==3.1.12 \
packaging==20.9 \
Pygments==2.7.4 \
pytz==2021.1 \
requests==2.25.1 \
snowballstemmer==2.1.0 \
sphinx-copybutton==0.3.1 \
sphinx-rtd-theme==0.5.1 \
sphinx-tabs==2.0.0 \
Sphinx==3.4.3 \
urllib3==1.26.3 \
```

**Comment by mattklein123** [comment]
OK LMK what you want. Merge this or wait?

**Comment by moderation** [comment]
Merge :rocket:

**Review by mattklein123 — APPROVED** [review]

**Comment by moderation** [comment]
Boom!
image

**Pull request merged**
