### PR TITLE
deps: Bump `envoy.code.check` -> 0.3.4 (and cleanup yaml)

### LINKED ISSUE #24195: Yamllint is only checking `.yaml` files (and not `.yml`)
This has allowed the inclusion of a lot of files that fail linting

I can fix the linter and the files

### PR DESCRIPTION
**Pull request by phlax**
Fix #24195 

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by alyssawilk** [comment]
needs main merge
/wait

**Review by jpsim — DISMISSED** [review]

**Review by RyanTheOptimist — COMMENTED** [review]
/lgtm deps

**Comment by alyssawilk** [comment]
This is going to get stomped by JP's change where we fix git history.  I'd say we should either land in mobile repo, or we should wait until after we change source-of-truth to this repo ~Thursday
/wait

**Comment by alyssawilk** [comment]
oh no wait I'm totally wrong this is workflow only. looking now :-)

**Comment by phlax** [comment]
actually - there is also this one `mobile/.swiftlint.yml` but i think it will create minimal conflict

**Pull request merged**
