### PR TITLE
[mobile]make location header lookup stricter

### PR DESCRIPTION
**Pull request by RenjieTang**
Commit Message: make location header lookup stricter
Additional Description:
Risk Level: Low
Testing: existing tests
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: android only

### CODE REVIEW

**Review by abeyad — COMMENTED** [review]
is there a way we can write a test for this?

**Comment by RenjieTang** [comment]
> is there a way we can write a test for this?

I modified the existing test to cover this situation.

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by RyanTheOptimist** [comment]
@abeyad does this LGTY?

**Review by abeyad — APPROVED** [review]
LGTM, sorry I think I missed the updates on this one.

**Pull request merged**
