### PR TITLE
docs: Move envoy config snippets to include files

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: docs: Move snippets to include files
Additional Description:

this moves any (lintable) snippets currently embedded in docs rst files into include files.

this will:

- make linting config and/or code snippets much easier in CI/locally
- make it easier to use code editors etc when editing the snippets
- make it easier to edit the copy and structure of rst files

Risk Level: low
Testing: potentially
Docs Changes: yep
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue] touch #8837 
[Optional Deprecated:]

----

### update to scope

after looking through the docs - i realised that there are quite a lot of partial snippets. I have avoided these and just moved out the (full) envoy yaml snippets.

i think we might want to move the partial snippets after (and perhaps some non-yaml ones)

there are some funky things we can do with partial snippets - like add context and highlight certain lines, or sequentially show parts of an included full config, but all of these things are a bit more complex - so getting lintable/testable envoy configs out seems a greater priority.

also, im seeing that there is a `validated-code-block` extension - so i need to look at that more.

### CODE REVIEW

**Comment by phlax** [comment]
@mattklein123 as this means moving quite a bit of config - i just did the first one i found for testing - if you are happy with this general direction - ill move the rest/more

**Comment by mattklein123** [comment]
Yeah this is totally fine with me. Whatever you think is best to getting to a path where everything is validated and won't bit rot. (See also the inline validation code that already exists that I mentioned elsewhere.)

Let me know when this is ready to review.

/wait

**Comment by phlax** [comment]
@mattklein123 i have updated the scope (see description) and deWIPped this

**Review by mattklein123 — APPROVED** [review]
Nice, thanks.

**Pull request merged**
