### PR TITLE
ci: Dont use azp cache in postsubmit

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: ci: Dont use azp cache in postsubmit
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
sometimes the cache goes very slow - see here for example (cache is orange)

cache

iiuc the cache is pointless in the postsubmit queue as the jobs are not expected to be repeated, and the cache is created separately for each pr/commit

**Comment by lizan** [comment]
> sometimes the cache goes very slow - see here for example (cache is orange)
> 
> cache
> 
> iiuc the cache is pointless in the postsubmit queue as the jobs are not expected to be repeated, and the cache is created separately for each pr/commit

No the cache is valid as long as the external dependencies are not changed. ( https://dev.azure.com/cncf/envoy/_build/results?buildId=81349&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=b8249413-28a3-5978-1759-949e5ad2fa8c ) The 80 percentiles is where the cache need to be invalidated. The cache exists to mitigate GH transient download error, which will make CI flaky if we don't cache.

**Comment by phlax** [comment]
>  No the cache is valid as long as the external dependencies are not changed.

ok - i see - i guess it must be per-branch or something - when i tested in pr the cache was empty on first run

ill close this - apologies for noise - just trying to find whatever optis for ci that i can

**Comment by phlax** [comment]
@lizan heres a case of the cache going mega slow - taking > 4 mins to download ~600MB

https://dev.azure.com/cncf/envoy/_build/results?buildId=81573&view=logs&j=c7b38d03-eb42-58f3-f725-18757c1ab91e&t=64f54edd-4aee-5907-b665-0cdb73f0654b&l=126

it doesnt happen happen that often - but it can go v slow across a few jobs

fwiw

not sure it makes the case for this PR at all, if the cache is generally helpful

**Pull request closed without merging**
