### PR TITLE
typo corrections

### PR DESCRIPTION
**Pull request by ankatare**
Signed-off-by: Abhay Narayan Katare <abhay.katare@india.nec.com>

Commit Message: Typo Corrections
Additional Description: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/cors_filter
Risk Level: LOW
Testing: Unit
Docs Changes: Yes
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by ankatare** [comment]
@phlax Hi, just for my knowledge Could you please tell, when is the plan to release current ongoing version i.e. v1.20 ?

**Comment by ankatare** [comment]
As per https://github.com/envoyproxy/envoy/blob/main/RELEASES.md it is expected today  ?

**Review by phlax — APPROVED** [review]
lgtm, thanks @ankatare

**Comment by phlax** [comment]
> Could you please tell, when is the plan to release current ongoing version i.e. v1.20 ?

my understanding is that a release is fairly imminent, altho there is quite a lot left on the current milestone

https://github.com/envoyproxy/envoy/milestone/20

**Comment by ankatare** [comment]
> > Could you please tell, when is the plan to release current ongoing version i.e. v1.20 ?
> 
> my understanding is that a release is fairly imminent, altho there is quite a lot left on the current milestone
> 
> https://github.com/envoyproxy/envoy/milestone/20

Ok, Thanks for quick reply !!!

**Pull request merged**
