### PR TITLE
[ci] Pin CodeQL workflow dependencies by hash

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Commit Message: Pins CodeQL workflow dependencies by hash
Risk Level: Low
Fixes https://github.com/envoyproxy/envoy/issues/16579

### CODE REVIEW

**Review by phlax — APPROVED** [review]
hi @asraa similar to pinning the dockerfiles, doing this means we need to keep these up-to-date

luckily, dependabot has support for github actions (also dockerfiles i think) - info on actions here https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot

if you want to land this first, im happy to add a follow up to update the dependabot config for actions while i address the dockerfiles

**Comment by asraa** [comment]
oooh thanks! i can go ahead and give the github-actions dependabot config a shot and update this PR :)

**Comment by phlax** [comment]
this also seems related/interesting https://github.com/marketplace/actions/ensure-sha-pinned-actions

@asraa shall we land this and figure out how to enhance after ?

**Comment by asraa** [comment]
added the dependabot! i didn't add the github action though

**Review by phlax — APPROVED** [review]
lgtm, thanks @asraa

**Pull request merged**
