### PR TITLE
deps: Bump `bazel_gazelle` -> v0.25.0

### LINKED ISSUE #20501: Newer release available `bazel_gazelle`: v0.25.0 (current: v0.24.0)
Package Name: bazel_gazelle@0.24.0
Current Version: v0.24.0@2021-10-11
Available Version: v0.25.0@2022-03-23
Upstream releases: https://github.com/bazelbuild/bazel-gazelle/releases

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #20501
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
> might be a long shot

seems it didnt work

the failure seems to relate to github.com/lyft/protoc-gen-star

cc @keith

**Comment by moderation** [comment]
I hit the same errors in my local and RBE environments

**Comment by keith** [comment]
I haven't dug into gazelle much in general, do we need to regenerate a BUILD file for this somehow? The files from the error just include this lib https://github.com/lyft/protoc-gen-star/blob/v0.6.0/init_option.go#L7 is that not enough?

**Comment by phlax** [comment]
> I haven't dug into gazelle much in general

i always seem to just about understand it once i have done what i need to do, and then have no clue when i come back to it 8/

**Comment by phlax** [comment]
one thing that has always confused me - what we are using it for - eg:

```console

$ git grep gazelle
bazel/dependency_imports.bzl:load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")
bazel/dependency_imports.bzl:    gazelle_dependencies()
bazel/repositories.bzl:        external_http_archive("bazel_gazelle")
bazel/repository_locations.bzl:    bazel_gazelle = dict(
bazel/repository_locations.bzl:        project_url = "https://github.com/bazelbuild/bazel-gazelle",
bazel/repository_locations.bzl:        urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/v{version}/bazel-gazelle-v{version}.tar.gz"],

```

seems to suggest it is not used other than to set up its dependencies - we dont have any `bazel run //:gazelle` commands set up, and there is no readme anywhere saying "now run gazelle etc"

**Comment by phlax** [comment]
> Agree it doesn't look like it is being used

turns out that it is - we are using `go_repository` from gazelle so we need it for that at least i think

**Comment by phlax** [comment]
i reverted the afero dep as `protoc-gen-validate` deps on the version we had, and we only use `protoc-gen-star` for `protoc-gen-validate`

it seems the issue is here https://github.com/bazelbuild/bazel-gazelle/pull/1201

afaict gazelle (`go_repository`) has switched from a mode where it will resolve unlisted deps to one where they have to be explicitly listed

**Comment by phlax** [comment]
k, after a bit of poking around i ~figured out the issue

previously, the behaviour of `go_repository` was such that any dependencies that were not explicitly set were dynamically resolved

afaict this behaviour has changed such that all go deps have to be explicitly listed

from a security pov the new behaviour is pretty desirable and speeds up builds a lot apparently - so we dont want to revert if we can avoid it

i have reverted 2 of the deps to the old behaviour of dynamic resolution as both seem to be required 

there seems to be some mismatch in transient deps

- `protoc-gen-validate` -> `afero`
- `protoc-gen-validate` -> `protoc-gen-star` -> `afero`

and also with `golang.org/x/text`

afaict our go_deps are basiclly all from `protoc-gen-validate`, so im wondering whether we want to be importing its deps (with `//dependencies:go_third_party` https://github.com/envoyproxy/protoc-gen-validate/blob/0e25aabb25c0709aff19aea176a1da13328b12fb/dependencies.bzl#L3) 

im not sure whether just directly importing will work - or whether they need to do some work on resolving their (conflicting) go_deps

**Comment by phlax** [comment]
seems the grpc dep is borking on missing `"google.golang.org/protobuf/types/known/timestamppb"`

**Comment by RyanTheOptimist** [comment]
@phlax is the check linux_x64 api check a flake, or real?

**Comment by phlax** [comment]
updated and added a note/TODO about the undesirability of the workaround - it keeps existing behaviour, so i think its the right thing to do for now

**Comment by ggreenway** [comment]
@phlax what's the status of this? Are you waiting for deps signoff from @moderation, or is there anything else to discuss/decide/fix?

**Comment by phlax** [comment]
yep, i think so re waiting - it was languishing a while while i figured out why it wasnt working

its also not the perfect solution - but is the status quo

/wait-any

**Pull request merged**
