### PR TITLE
docs: Update quick-start logging info

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: docs: Update quick-start logging info
Additional Description:

Follow up from #13935 

Provides basic info/example of access logging

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by phlax** [comment]
worth  mentioning - this makes Envoy work similar to other comparable containers:

https://docs.docker.com/config/containers/logging/

**Comment by phlax** [comment]
latest render is here:

https://storage.googleapis.com/envoy-pr/1125923/docs/start/quick-start/run-envoy.html#envoy-logging

**Review by mattklein123 — APPROVED** [review]
Nice!

**Comment by phlax** [comment]
eek! just spotted some places where changing the config messes up - ill pr to clean up

**Pull request merged**
