### PR TITLE
http: minor code clean up to the http filter manager

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: http: minor code clean up to the http filter manager
Additional Description:

1. simplify the code and remove unnecessary flag.
2. resolve clang tidy warning.

Risk Level: low.
Testing: n/a.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Review by ggreenway — COMMENTED** [review]
Can you elaborate on the reasoning for this change? My understanding is that this will make some of the callbacks be called twice now for filters that are both an encoder and decoder. Was that protection unnecessary?

/wait-any

**Comment by wbpcode** [comment]
> My understanding is that this will make some of the callbacks be called twice now for filters that are both an encoder and decoder. Was that protection unnecessary?

Long time ago, we only have decoder_filters_ and encoder_filters, this protection is necessary. But at #15172, we introduce a new containers to store the StreamFilterBase pointer for **every unique filter**. We can iterate the that container directly and needn't any additional branch.

> Can you elaborate on the reasoning for this change? 

I want to optimize the implementation of filter manager and reduce the scattered memory allocations of http filter chain creation. And this is a minor pre-PR to simplify that optimization PR.

**Review by ggreenway — APPROVED** [review]
Got it; makes sense now.

**Pull request merged**
