### PR TITLE
http: minor perf fix, not copying strings

### PR DESCRIPTION
**Pull request by alyssawilk**
We're good for this, right?

Risk Level: Low 
Testing: existing tests pass
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by mattklein123** [comment]
If you have this fixed internally (!!!), I think there are a lot more examples than these but I don't think we have been tracking them carefully.

**Comment by jmarantz** [comment]
I also have this fixed differently in https://github.com/envoyproxy/envoy/pull/6733 though I might not have pushed that change yet.

Basically the strings in this need to become StatNames so they can be used to quickly joined into larger StatNames. Checking this in now is fine if urgent; I can deal with the merge conflict later.

**Comment by alyssawilk** [comment]
It's not urgent but yeah, in your current version I still see the std::strings and TODOs and I don't see the test change?

**Comment by alyssawilk** [comment]
Yeah, FWIW I did a quick grep for const std::string not in a function signature and it didn't help me find other things to clean up.  I wonder if I can turn up more poking around our import logs and PR history for "string"

**Comment by mattklein123** [comment]
> Yeah, FWIW I did a quick grep for const std::string not in a function signature and it didn't help me find other things to clean up. I wonder if I can turn up more poking around our import logs and PR history for "string"

If you can somehow search GH comments for me saying "sigh" you will probably fine some. :)

**Comment by alyssawilk** [comment]
Matt, apparently you sigh in your head more than you sigh in PRs, but going through logs was a pretty good idea :-)

If we want to get really fancy we could remove Protobuftypes::String and utilities entirely.
if some combination of @htuch and @jmarantz agree I'll go do that cleanup as well.

https://github.com/envoyproxy/envoy/pull/4848/files
https://github.com/envoyproxy/envoy/pull/5139/files
https://github.com/envoyproxy/envoy/pull/5332/files
https://github.com/envoyproxy/envoy/pull/5685/files
https://github.com/envoyproxy/envoy/pull/4320/files TODO
https://github.com/envoyproxy/envoy/pull/4238/files TODO
https://github.com/envoyproxy/envoy/pull/3885/files TODO generally remove ProtobufTypes::String?
https://github.com/envoyproxy/envoy/pull/3696/files
https://github.com/envoyproxy/envoy/pull/3142/files TODO
https://github.com/envoyproxy/envoy/pull/3053/files
https://github.com/envoyproxy/envoy/pull/2964/files
https://github.com/envoyproxy/envoy/pull/2653/files TODO
[stopped here]

**Comment by jmarantz** [comment]
Yeah it's not fully compiling yet but I pushed it anyway just now to make it visible.

https://github.com/envoyproxy/envoy/pull/6733/files#diff-a00f27eaffcd28ed6b74102912eb1d65L219

not ready for review obviously but early feedback on the approach would be great.

**Pull request merged**
