### PR TITLE
Update QUICHE from 2381ebbb6 to 393de7511

### PR DESCRIPTION
**Pull request by DavidSchinazi**
Commit Message: Update QUICHE from 2381ebbb6 to 393de7511
Additional Description:
    https://github.com/google/quiche/compare/2381ebbb6..393de7511
    $ git log 2381ebbb6..393de7511 --date=short --no-merges --format="%ad %al %s"
    2022-09-30 dschinazi Fix open-source build
    2022-09-30 martinduke Allow client to buffer Handshake packets when the server Initial is delayed, even if the connection ID changes.
    2022-09-30 quiche-dev Fix "non-constant-expression cannot be narrowed from type 'uint8_t' (aka 'unsigned char') to 'char' in initializer list [-Wc++11-narrowing]" in chromium build.
    2022-09-30 quiche-dev Use absl::variant to reduce storage space of structured header items
    2022-09-29 martinduke Add test to verify LoadBalancerConfig remains copyable.
    2022-09-29 haoyuewang Deprecate --gfe2_reloadable_flag_quic_session_map_consistency_check
    2022-09-29 fayang Stop logging gQUIC only Net.QuicClientHelloRejectReasons.*
    2022-09-27 ianswett Deprecate --gfe2_reloadable_flag_quic_bbr2_no_probe_up_exit_if_no_queue.
    2022-09-27 ianswett Deprecate --gfe2_reloadable_flag_quic_fix_pacing_sender_bursts.
    2022-09-27 vasilvv Explicitly call Join() in EventLoopConnectingClientSocketTest
    2022-09-26 renjietang Set alternative path as validated once multi-port probing succeeds.
    2022-09-26 vasilvv Make the I/O part of QUICHE compile under Bazel.
    2022-09-26 ericorth Fix threading issue in connecting client socket tests
    2022-09-26 ericorth CONNECT-UDP datagram payload parse/serialization
    2022-09-26 fayang False deprecate gfe2_reloadable_flag_quic_donot_reset_ideal_next_packet_send_time.
    2022-09-23 martinduke Deprecate gfe2_restart_flag_quic_map_original_connection_id2.
    2022-09-23 ericorth Give toy server backends direct access to the QuicSpdyStream
    2022-09-23 bschneider Switch EXPECT_OK an ASSERT_OK to EXPECT_TRUE and ASSERT_TRUE.
    2022-09-22 ericorth Generalize EventLoopTcpClientSocket between TCP and connected-UDP
    2022-09-22 martinduke Internal change
Risk Level: Low
Testing: Existing Tests
Docs Changes: None
Release Notes: None
Platform Specific Features: None

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by RyanTheOptimist** [comment]
I think you'll need a main merge because of the broken coverage on main

**Comment by ggreenway** [comment]
@DavidSchinazi is it possible that this upgrade caused #23370? It's the only change recently that seems to touch anything near the failure.

**Comment by DavidSchinazi** [comment]
@ggreenway I don't think so. From looking at the changelog I'm not seeing anything that would impact that test.

**Comment by ggreenway** [comment]
> @ggreenway I don't think so. From looking at the changelog I'm not seeing anything that would impact that test.

Ok, thanks for checking.

**Pull request merged**
