### PR TITLE
deps: Bump `com_github_grpc_grpc` from 1.59.3 -> 1.59.4

### PR DESCRIPTION
**Pull request by tonya11en**
Bump gRPC from 1.59.3 -> 1.59.4

Risk Level: Low. Minor version.
Testing: CI
Release Notes: n/a

### CODE REVIEW

**Review by phlax — APPROVED** [review]
lgtm, thanks @tonya11en

**Comment by phlax** [comment]
pushing past unrelated flake

**Comment by kyessenov** [comment]
@tonya11en I think the real change is updating from `SslCredentials` to `TlsCredentials` in Google gRPC client in Envoy.

**Pull request merged**
