### PR TITLE
Sds api: implement SDS api

### LINKED ISSUE #1194: Secret Discovery Service for v2 APIs
Hi,

We want to be able to rotate Envoy certs/keys without having to restart the Envoy.  We're particularly interested in the client cert/key for connecting to upstream clusters.  We recognize the CDS allows us to dynamically change clusters, but that doesn't let us rotate the cert used to connect to the CDS itself.

We see prior discussion about supporting cert rotation (https://github.com/lyft/envoy/issues/891) which was answered by pointing people towards the in-development LDS (https://github.com/lyft/envoy/issues/315).  However, we don't see how the LDS solves the problem of rotating certs used to connect to the CDS.

What work would be required for support cert/key rotation for CDS without having to restart Envoy?  This issue is a blocker for us using Envoy (we're looking at integrating it, and perhaps Istio, into Cloud Foundry).

We might be able to contribute the feature, if we had some guidance.

Cheers,
Angela and @rosenhouse

### PR DESCRIPTION
**Pull request by JimmyCYJ**
Implement SDS api which fetches dynamic secrets.

*Description*:
Implement SDS api that fetches secrets from remote SDS server. Secrets are stored in Secret Manager.
Updating secrets at listener and cluster will follow.

*Risk Level*: Low 

Fixes #1194 

Signed-off-by: Jimmy Chen jimmychen.0102@gmail.com

### CODE REVIEW

**Comment by mattklein123** [comment]
@PiotrSikora @lizan please take first pass.

**Comment by lizan** [comment]
@JimmyCYJ can you create a PR from istio repo, [here](https://github.com/envoyproxy/envoy/compare/master...istio:sds_api?expand=1)? I have made some changes to merge recent changes.

**Comment by JimmyCYJ** [comment]
@lizan Sure. Will close this one and open another PR. Thanks!

**Comment by JimmyCYJ** [comment]
@lizan @PiotrSikora Please review https://github.com/envoyproxy/envoy/pull/3700, thanks!

**Pull request closed without merging**
