### PR TITLE
hot restart: send used stats only during hot restart

### PR DESCRIPTION
**Pull request by ramaraochavali**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description: During hot restart, when copying parent stats, we are not checking if stat is used or not. As a result of this, the gauges of type ACCUMULATED, are copied with zero values even though they are not used on the parent Envoy. Following are some of the example stats

```
upstream_rq_active
upstream_rq_pending_active
upstream_cx_active
upstream_cx_rx_bytes_buffered
upstream_cx_tx_bytes_buffered
```
Risk Level: low
Testing: Added
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by mattklein123** [comment]
@ramaraochavali thanks, this LGTM, but is this fixing a bug or is this just a perf improvement?

/wait-any

**Comment by ramaraochavali** [comment]
It originated as a bug - We are trying to look the cluster usage from stats  i.e. whether a cluster has active requests from another service- we found these stats generated for a cluster which is supposed to not have any requests. Digging deeper, found this as issue. But can help with perf as well.

**Comment by mattklein123** [comment]
@ramaraochavali the output was still 0, it just counted as "used." Is that right?

**Comment by ramaraochavali** [comment]
@mattklein123 Yes. That is correct. We are checking for existence of the stats "upstream_rq_", "upstream_cx" - not the values actually. If a cluster is not used, we do not see any of those stats.

**Pull request merged**
