### PR TITLE
ci: Use local (named) cache for non-RBE jobs

### LINKED ISSUE #25735: Add `--enable_ac_key_instance_mangling` to local build cache in/for CI
This will allow release branches to use a separate local (non-RBE) cache to `main`

currently this is disabled on release branches to prevent clashing with `main` and they fail very often (arm64, coverage) due to running uncached

remembering to disable the cache is manual and frequently forgotten causing CI chaos

resolving would fix #24001

there is an argument for doing test runs uncached eg on a schedule, but the release branches arent the place to do this and need to be as reliable as possible

### PR DESCRIPTION
**Pull request by phlax**
Fix #25735 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
requires https://github.com/envoyproxy/ci-infra/pull/10 to be landed/activated

**Comment by phlax** [comment]
afaict this is working correctly - altho im not sure its having any effect yet

```console
instance_name: instances/main.
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=129447&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=1fb0b72f-6293-562d-a4d1-bb649223eaca&l=34

**Comment by phlax** [comment]
testing on a release branch PR and it sets

```console
instance_name: instances/release/v1.23

```

i need to confirm how `SourceBranch` works i have a feeling it will have a `refs/heads` prefix

**Comment by phlax** [comment]
seems `SourceBranchName` should do the trick ...

https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

**Comment by phlax** [comment]
@lizan this should be gtg as soon as CI has been re-terraformed

**Review by lizan — APPROVED** [review]

**Pull request merged**
