### PR TITLE
build: always build test binaries dynamically

### PR DESCRIPTION
**Pull request by akonradi**
Commit Message: Always build test binaries dynamically
Additional Description:
Defaulting to linkstatic=1 results in bloated binaries that contain duplicated code
instead of leaving it in shared objects that can be loaded dynamically and
shared among multiple binaries.

Risk Level: low
Testing: built and ran tests
Docs Changes: none
Release Notes: none

### CODE REVIEW

**Comment by akonradi** [comment]
It's worth noting that the default value for `cc_test`'s `linkstatic` argument [is 0 (false)](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_test.linkstatic). I don't know why we started building tests statically, but it seems like we don't need to be paying for the overhead.

**Comment by mattklein123** [comment]
Per slack convo, I tried to do a variant of this in https://github.com/envoyproxy/envoy/pull/13257 (see older commits) and I couldn't get CI to pass.

**Comment by akonradi** [comment]
Looks like the macOS issue is known: https://github.com/grpc/grpc/issues/13856

**Comment by lizan** [comment]
@akonradi macOS doesn't work with dynamic linking because it will exceed the number of dynamic link library it can load. Since the dynamic link test will also dynamic link envoy_cc_libraries, I'm inclined to keep release build static, we already do split dwarf so their size isn't that large.

**Comment by lizan** [comment]
> It's worth noting that the default value for `cc_test`'s `linkstatic` argument [is 0 (false)](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_test.linkstatic). I don't know why we started building tests statically, but it seems like we don't need to be paying for the overhead.

the linkstatic semantics is different between cc_test/binary and cc_library, if we specify linkstatic=1 in cc_library, that library will be statically linked.

**Pull request closed without merging**
