### PR TITLE
[server] fix uncaught throws in secondary cluster initialization

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Commit Message:
Fuzzing testcases produced cases where callbacks after server initialization caused crashes, due to secondary cluster initialization. They're due to exceptions somewhere in the callstack of `factoryForGrpcApiConfigSource`, due to bad configuration for the grpc service configuration.

The secondary clusters are initialized in the server callback `onRuntimeReady`, so we fix this by guarding the cluster initialization by a try/catch block and warning if initialization for these clusters fails.

Risk Level: Low
Testing: Regression tests added
Fixes:
https://github.com/envoyproxy/envoy/issues/12520
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24065
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23673
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22108

I'm not thrilled by adding try/catches everywhere, welcome to suggestions for better fixes.

### CODE REVIEW

**Comment by yanavlasov** [comment]
These errors happen because of malformed bootstrap, right? I just don't know if we should exit in this case instead of skipping problematic section. I'll ask in Slack

**Comment by asraa** [comment]
Yep, that's right. Yeah, I'm not sure which way makes the most sense -- some errors are handled by skipping that initialization (https://github.com/envoyproxy/envoy/blob/cee25addc5a0f34a9c98b4e19abfbe45e16009c9/source/server/server.cc#L445),  but maybe the server should just be `terminate()`d

**Comment by asraa** [comment]
Decided to catch and `shutdown()` -- I wasn't 100% sure of whether to terminate the server, but that doesn't seem to clear other callbacks and hits other failures. wdyt?

**Comment by yanavlasov** [comment]
This looks good. Are the fuzz tests enough to verify this functionality? Will they test that shutdown works correctly in this context?

**Pull request closed without merging**
