### PR TITLE
transport_sockets: removed well_known_names.h file

### PR DESCRIPTION
**Pull request by daixiang0**
Commit Message:
Removed transport_sockets/well_known_names.h file.

Risk Level: Low
Testing: Make sure that all unit and integration tests pass
Docs Changes: No
Release Notes: No
Platform Specific Features:
Partially fixes: #7238

### CODE REVIEW

**Comment by yanavlasov** [comment]
Thanks for making this change.
I think you have missed a reference in source/common/quic/BUILD line 266

**Comment by yanavlasov** [comment]
Looks like QUIC test is failing: https://dev.azure.com/cncf/envoy/_build/results?buildId=73616&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=6b0ace90-28b2-51d9-2951-b1fd35e67dec&l=19985

**Comment by daixiang0** [comment]
I am looking at it.

**Comment by daixiang0** [comment]
@yanavlasov now all tests pass.

**Comment by daixiang0** [comment]
@mattbailey hi, please help review.

**Comment by yanavlasov** [comment]
Ugh, looks like the game of merge whack-a-mole on this large PR. Please ping me on slack when you fix conflicts so I can merge it as soon as possible to avoid getting merge conflicts.

**Comment by yanavlasov** [comment]
I think there are still includes of well_known_names.h in the quic code.

/wait

**Comment by daixiang0** [comment]
@yanavlasov could you please review this?

**Comment by daixiang0** [comment]
re-push to re-run test.

**Comment by daixiang0** [comment]
@yanavlasov seems windows test flasky :(

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
