### PR TITLE
double word "to"

### PR DESCRIPTION
**Pull request by vonsago**
There are double words "to".

Description:
Risk Level:  n/a 
Testing: yes
Docs Changes: no
Release Notes: no

### CODE REVIEW

**Comment by dio** [comment]
@vonsago thank you for your contributions. However, seems like you need to [fix DCO](https://github.com/envoyproxy/envoy/blob/master/CONTRIBUTING.md#fixing-dco). Enabling [`./support/bootstrap`](https://github.com/envoyproxy/envoy/blob/master/CONTRIBUTING.md#dco-sign-your-work) might be helpful too.

If you can find more similar "mistakes" like this, and combine it into this PR, that will be great. Thanks again!

**Comment by vonsago** [comment]
@dio Thank you a lot.I fixed DCO

**Comment by mattklein123** [comment]
@vonsago while I appreciate this fix, I'm sorry but we cannot accept this PR. We have already reached out to DaoCloud and kindly asked you to stop trying to game commit statistics with this kind of fixes. Thank you!

**Comment by vonsago** [comment]
@mattklein123 Thank you! I will make a small contribution in my own name in the future.

**Pull request closed without merging**
