### PR TITLE
async_tcp_client: fix debug log

### PR DESCRIPTION
**Pull request by ohadvano**
Additional Description: If ``AsyncTcpClientImpl`` is not called with ``connect()`` during the ``connect_timeout`` period, the ``connection_`` object is ``nullptr``. If debug logs are enabled, the modified line causes seg fault
Risk Level: low
Testing: none
Docs Changes:  none
Release Notes:  none
Platform Specific Features: none

### CODE REVIEW

**Review by botengyao — APPROVED** [review]
LGTM, thanks for the fix!

**Review by ggreenway — APPROVED** [review]

**Review by adisuissa — COMMENTED** [review]
LGTM, thanks for fixing this!
Coverage CI failure seems related.

**Comment by ggreenway** [comment]
@ohadvano there was a coverage issue that I think was fixed in `main` yesterday. Can you merge `main` to fix CI? /wait

**Pull request merged**
