### PR TITLE
backport 1.14: ci: fix docs tag build

### PR DESCRIPTION
**Pull request by Shikugawa**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by asraa** [comment]
@Shikugawa are the toolchain failure the result of another missing backport?

```
ERROR: Analysis of target '//:echo2_integration_test' failed; build aborted: invalid registered toolchain '@rules_foreign_cc//tools/build_defs/shell_toolchain/toolchains:linux_commands': error loading package '@rules_foreign_cc//tools/build_defs/shell_toolchain/toolchains': in /build/tmp/_bazel_bazel/400406edc57d332f0b9b805d2b8e33a1/external/rules_foreign_cc/tools/build_defs/shell_toolchain/toolchains/defs.bzl: in /build/tmp/_bazel_bazel/400406edc57d332f0b9b805d2b8e33a1/external/commands_overloads/toolchain_data_defs.bzl: Extension 'default_commands.bzl' has errors```

**Comment by Shikugawa** [comment]
@moderation Could you approve this?

**Pull request merged**
