### PR TITLE
add opencensus example

### PR DESCRIPTION
**Pull request by zirain**
Commit Message: add opencensus demo, this will not success with https://github.com/envoyproxy/envoy/pull/33880
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by phlax — COMMENTED** [review]
@zirain my understanding is that opencensus is about to be removed - we deprecated it previously - and its scheduled for removal in this release cycle - the reason being that upstream is archived and no longer supported 

checking through recent changes it seems that opencensus has not yet been marked `disabled_by_default` so more likely it will be the next release cycle when it will be removed

i believe @kyessenov had a plan to just downstream the code to istio

**Comment by adisuissa** [comment]
Assigning Kuat who may have more context. Feel free to reassign.
/assign @kyessenov

**Comment by zirain** [comment]
> @zirain my understanding is that opencensus is about to be removed - we deprecated it previously - and its scheduled for removal in this release cycle - the reason being that upstream is archived and no longer supported
> 
> checking through recent changes it seems that opencensus has not yet been marked `disabled_by_default` so more likely it will be the next release cycle when it will be removed
> 
> i believe @kyessenov had a plan to just downstream the code to istio

I thought it would be part of CI and it will be failed because of c-ares issue.

**Comment by phlax** [comment]
> I thought it would be part of CI and it will be failed because of c-ares issue.

not sure iiuc but i believe Envoy is going to remove opencensus altogether

either way, i dont think we want to add an example for something that is no longer supported (by us or upstream)

(thanks for working on this all the same)

**Comment by zirain** [comment]
yes, we should close this.

**Comment by kyessenov** [comment]
Yes, let's not forget to mark opencensus to be deleted. Google will take the code private since the OSS version is no longer maintained, and we can also remove it in Istio Proxy.

**Comment by phlax** [comment]
it was already marked as deprecated - ive added a PR to make it `disabled_by_default` https://github.com/envoyproxy/envoy/pull/33912

**Pull request closed without merging**
