### PR TITLE
Add posix file operations to OsSysCalls

### PR DESCRIPTION
**Pull request by ravenblackx**
Signed-off-by: Raven Black <ravenblack@dropbox.com>

Commit Message: Add posix file operations to OsSysCalls
Additional Description: Per a request in PR#20332, mocking file operations integrated into OsSysCalls rather than done separately.
Risk Level: Low.
Testing: No direct tests, same as the rest of OsSysCalls. The tests from PR#20332 will add coverage.
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by ravenblackx** [comment]
@rojkov as the person who suggested making filesystem mocks this way.

**Comment by ggreenway** [comment]
Please separate out the const change into a separate PR. I'm not sure if it's worth doing, but we can discuss that separately.

**Review by rojkov — APPROVED** [review]
Thanks! Looks good to me.

I don't have strong opinion whether the methods should be marked `const` or not for consistency with the rest. I'll defer to a second reviewer.

/assign-from @envoyproxy/senior-maintainers

**Review by lizan — DISMISSED** [review]

**Review by rojkov — APPROVED** [review]
reinstating my approval

**Pull request merged**
