### PR TITLE
WiP test: use await() rather than condvar in a few places, and make condvar wait return void.

### PR DESCRIPTION
**Pull request by jmarantz**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by jmarantz** [comment]
@mattklein123 @antoniovicente I had been working on this a while back and finally brought it up to date again.

It moves to an await() model in many cases, reducing races because the time-system condvar interface lacked a condition.

**Comment by jmarantz** [comment]
It's possible this will work better now than it did when I was trying to iterate on it back in March/April, because @antoniovicente fixed some issues in sim-time.

**Comment by mattklein123** [comment]
Thanks @jmarantz let me merge the ideas here into my ongoing PR and see how it goes.

**Comment by mattklein123** [comment]
I think we are merging this into my ongoing PR.

**Pull request closed without merging**
