### PR TITLE
[bp/1.24] Kafka + deps

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by adamkotwasinski** [comment]
:+1: LGTM looks like a backport of multiple PRs

I'm wondering why clang_tidy is failing for that code while it was not complaining for the original source (maybe we are _not_ running them there as it's contrib?) - kinda busy to investigate now, but if you really want to merge it, just [delete this file](https://github.com/envoyproxy/envoy/pull/29171/files#diff-d68bb92e5bb3c37a5f87d02932d383d50038fe6b986067fdfd1399194efad511) and this [UT section](https://github.com/envoyproxy/envoy/pull/29171/files#diff-af8bf41c75780d423353fe41718f50d5fe687094d02db0dc2779be30bc68a81bR42). I'm also wondering if that could be a false positive.... needs further looking.

Or maybe you don't want to backport the whole filter work and just a dependency?

**Comment by phlax** [comment]
> drive-by: Why are we back-porting these kafka changes? (I'm sure there's a good reason, just curious what it is)

posting previous answer - https://github.com/envoyproxy/envoy/pull/28441#issuecomment-1639487686

**Comment by RyanTheOptimist** [comment]
> > drive-by: Why are we back-porting these kafka changes? (I'm sure there's a good reason, just curious what it is)
> 
> posting previous answer - [#28441 (comment)](https://github.com/envoyproxy/envoy/pull/28441#issuecomment-1639487686)

Thanks. That question was about why we're updating dependencies, i.e. why are we updating the kafka dep. But in this PR we are changing a bunch of Envoy-specific Kafka code. Is that required for some reason? In any case, please update the PR description to explain.

**Comment by phlax** [comment]
in that case i think the question is answered here https://github.com/envoyproxy/envoy/pull/29171#issuecomment-1687807615

**Comment by phlax** [comment]
> In any case, can you please update the PR description to explain these changes? As CONTRIBUTING.md says, "Your PR description should have details on what the PR does." So maybe you want to say something like:

sure but as explained these backport PRs get rebased - i get that a description is useful but this is not the usual case (the commits contain the descriptions/pr refs etc)

>  Do we really need to do all of this?

that remains to be seen and is the reason that i separated these updates for the 2 branches that required code changes

**Pull request closed without merging**
