### PR TITLE
improvement CEL doc

### PR DESCRIPTION
**Pull request by zirain**
Commit Message: improvement CEL doc
Additional Description: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/formatter/cel/v3/cel.proto#extensions-formatter-cel-v3-cel
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by wbpcode** [comment]
Thanks, nice catch. Seems you have fixed the docs of access log cel filter, could you also update the cel formatter? Thanks.

See https://storage.googleapis.com/envoy-pr/ef3825f/docs/api-v3/extensions/formatter/cel/v3/cel.proto.html#extensions-formatter-cel-v3-cel

**Comment by zirain** [comment]
https://storage.googleapis.com/envoy-pr/ef3825f/docs/api-v3/extensions/access_loggers/filters/cel/v3/cel.proto.html

this page is better, and I think another page need improvement.

**Comment by zirain** [comment]
https://storage.googleapis.com/envoy-pr/4fddcae/docs/api-v3/extensions/formatter/cel/v3/cel.proto.html#extensions-formatter-cel-v3-cel is better now.

**Comment by zirain** [comment]
@wbpcode ptal again.

**Review by wbpcode — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
