### PR TITLE
V2 to V3 fragment changes for http and access_log folders under test/.. 

### LINKED ISSUE #10843: Convert v2 API test fragments to v3
While all programatically constructed test configs will be v3 (via API boosting rewriting), there are still v2 JSON/YAML fragments in test code. Many of these will "just work" as v3, but some may have v2 features that will have them treated as v2. This becomes confusing when they are extended by developers who want to model v3 features.

These need to be audited and updated as appropriate. Also, the names of methods such as `parseAccessLogFromV2Yaml` should be updated to reflect v3 when operating on fragments that should be v3.

This is somewhat similar to the work done by @dmitri-d for examples in https://github.com/envoyproxy/envoy/pull/10644 as part of https://github.com/envoyproxy/envoy/issues/9735.

CC @alyssawilk

### PR DESCRIPTION
**Pull request by ankatare**
Signed-off-by: Abhay Narayan Katare <abhay.katare@india.nec.com>

Commit Message: changes for http and access_log folders
Additional Description: V2 to V3 APIs fragment changes and forcing **ParseFoofromV2Yaml** for V3. this commit focuses on changes for http and access_log folders under test/common/.. 
Risk Level:NA
Testing: Unit and format testing
Docs Changes: NA
Release Notes:
[Optional Runtime guard:]
[Optional Fixes:] 
[Optional Deprecated:]
part of #10843

### CODE REVIEW

**Comment by junr03** [comment]
@ankatare do you mind editing to a more descriptive title and description. Also looks like tests are failing?

**Comment by ankatare** [comment]
@junr03 Hi, thanks for review. i updated details ( title and description ) as per suggestions. regarding test cases failing  in CI it seems environment issues in build. please help.

**Comment by ankatare** [comment]
@junr03 i checked the code which is failing.  i have not touched it while working and also that test file "test/common/access_log/access_log_impl_test.cc"is passing in my local build. please suggest how to proceed here.

**Comment by junr03** [comment]
@ankatare do you mind merging master again? We have had some CI issues, but it should be resolved on master now.

**Comment by ankatare** [comment]
@junr03  Sure , i will do it ASAP .  thanks for help.

**Comment by ankatare** [comment]
@junr03 done. please review

**Pull request merged**
