### PR TITLE
upstream: remove thread local cluster after callbacks

### LINKED ISSUE #7990: Envoy crashes with assertion failure on redis cluster removal
*Description*:
Envoy crashes with assertion failure if a redis cluster is removed.

- Management server sends redis cluster with CDS response
- Envoy is fully initialized
- Management server sends CDS update with out redis cluster
- Envoy tries to remove the cluster and crashes with the following assertion while removing membership update callback.

```
[2019-08-21 13:35:56.778][1462770][critical][assert] [bazel-out/darwin-fastbuild/bin/source/common/common/_virtual_includes/callback_impl_lib/common/common/callback_impl.h:70] assert failure: std::find_if(callbacks_.begin(), callbacks_.end(), [handle](const CallbackHolder& holder) -> bool { return handle == &holder; }) != callbacks_.end().
```
If I look at the `callbacks_.size() `here - it is actually zero.

https://github.com/envoyproxy/envoy/blob/master/source/common/common/callback_impl.h#L60

Any idea on callback is not present during removal?

### PR DESCRIPTION
**Pull request by ramaraochavali**
Description:  Remove thread local cluster after clusterRemoval callback is fired. Fixes https://github.com/envoyproxy/envoy/issues/7990.
Risk Level: Low
Testing: Updated
Docs Changes: N/A
Release Notes: N/A
Fixes #7990

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@msukalski This seems to fix the issue. Can you PTAL?

@mattklein123  Does this change make sense?

**Comment by mattklein123** [comment]
Thanks @ramaraochavali this does seem correct to me. It would make me feel better though if there was some integration test that covered this, but that might be pretty hard. @snowp any thoughts on this one?

**Comment by snowp** [comment]
Yeah makes sense to me. Maybe it would be possible to add a regression test for the Redis cluster case if setting up a dedicated test for this is too hard?

**Comment by ramaraochavali** [comment]
@mattklein123 @snowp I tried to see if it is possible to add a test, it seems pretty hard to set that up. Can we merge this and I will continue to see if it is possible to add and do it as a follow-up if I can add?

**Comment by ramaraochavali** [comment]
New commits are not reflecting here. Will close this and open another PR

**Pull request closed without merging**
