### PR TITLE
thrift_proxy: Fix payload_to_metadata filter which might fail on multiple rules on same node

### PR DESCRIPTION
**Pull request by JuniorHsu**
Commit Message:
We found a bug in test `MultipleRulesOnMultiStruct` that we might fail to match the payload
if we have multiple rules and the first rule doesn't match the method/service.

Also wrote a minimum test `MultipleRulesInSamePathFirstRuleUnmatched` to verify the fix.

Additional Description:
Risk Level: low
Testing: unit
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Review by rgs1 — APPROVED** [review]
Thanks!

**Review by zuercher — APPROVED** [review]
lgtm. Re-ran the tests again, hopefully they succeed this time. Otherwise, maybe see if something's been fixed on master that might help with the test.

**Comment by JuniorHsu** [comment]
thanks Stephen.
This is on the same head with https://github.com/envoyproxy/envoy/pull/26386 so probably just busy ci. And I got green check on my first commit and just upstream-merge commits after that.

**Comment by JuniorHsu** [comment]
ci pass 🚀

**Pull request merged**
