### PR TITLE
WIP: Local cert provider

### PR DESCRIPTION
**Pull request by liverbirdkte**
Local certificate provider instance

A certificate provider instance to generate certificates locally.  It's based on the certificate provider framework and bumping filter could use this instance for testing.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by vermajit** [comment]
Hi @liverbirdkte Would you be able to share a sample envoy config that I could use to try this out locally ?

**Comment by vermajit** [comment]
> Hi @liverbirdkte Would you be able to share a sample envoy config that I could use to try this out locally ?
> 
> I tried out the following
> 
> ```
> certificate_provider_instances:
>   local_certificate_provider:
>     name: envoy.certificate_providers.local_certificate
>     typed_config:
>       "@type": type.googleapis.com/envoy.extensions.certificate_providers.local_certificate.v3.LocalCertificate
>       rootca_cert: {"filename": "./root-ca.pem"}
>       rootca_key: {"filename": "./root-ca.key"}
> static_resources:
>   listeners:
>   - name: https_listener
> ... rest of config ...
> ```
> 
> But envoy fails to start with following error
> 
> ```
> [2022-09-14 17:39:52.884][31771][debug][config] [source/server/configuration_impl.cc:99] add certificate provider: local_certificate_provider
> [2022-09-14 17:39:52.884][31771][critical][main] [source/server/server.cc:117] error initializing configuration 'config.yaml': Didn't find a registered implementation for 'envoy.certificate_providers.local_certificate' with type URL: 'envoy.extensions.certificate_providers.local_certificate.v3.LocalCertificate'
> [2022-09-14 17:39:52.884][31771][info][main] [source/server/server.cc:966] exiting
> Didn't find a registered implementation for 'envoy.certificate_providers.local_certificate' with type URL: 'envoy.extensions.certificate_providers.local_certificate.v3.LocalCertificate'
> ```

Found the issue. I was able to load the extension successfully after adding the missing `REGISTER_FACTORY(LocalCertificateFactory,  CertificateProvider::CertificateProviderFactory);` in `source/extensions/certificate_providers/local_certificate/config.cc`

**Comment by liverbirdkte** [comment]
> > Hi @liverbirdkte Would you be able to share a sample envoy config that I could use to try this out locally ?
> > I tried out the following
> > ```
> > certificate_provider_instances:
> >   local_certificate_provider:
> >     name: envoy.certificate_providers.local_certificate
> >     typed_config:
> >       "@type": type.googleapis.com/envoy.extensions.certificate_providers.local_certificate.v3.LocalCertificate
> >       rootca_cert: {"filename": "./root-ca.pem"}
> >       rootca_key: {"filename": "./root-ca.key"}
> > static_resources:
> >   listeners:
> >   - name: https_listener
> > ... rest of config ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But envoy fails to start with following error
> > ```
> > [2022-09-14 17:39:52.884][31771][debug][config] [source/server/configuration_impl.cc:99] add certificate provider: local_certificate_provider
> > [2022-09-14 17:39:52.884][31771][critical][main] [source/server/server.cc:117] error initializing configuration 'config.yaml': Didn't find a registered implementation for 'envoy.certificate_providers.local_certificate' with type URL: 'envoy.extensions.certificate_providers.local_certificate.v3.LocalCertificate'
> > [2022-09-14 17:39:52.884][31771][info][main] [source/server/server.cc:966] exiting
> > Didn't find a registered implementation for 'envoy.certificate_providers.local_certificate' with type URL: 'envoy.extensions.certificate_providers.local_certificate.v3.LocalCertificate'
> > ```
> 
> Found the issue. I was able to load the extension successfully after adding the missing `REGISTER_FACTORY(LocalCertificateFactory, CertificateProvider::CertificateProviderFactory);` in `source/extensions/certificate_providers/local_certificate/config.cc`

Hi [vermajit](https://github.com/vermajit),

Sorry for not seeing this in time, this is a draft of local cert provider instance and not totally ready. You have to integrate with other patches to make it work.  We are going to submit a PR to include all the related patches together for testing. I'll ping you when the code is ready. Thanks.

**Comment by liverbirdkte** [comment]
Hi @vermajit, we have an integration patch to demo TLS bumping scenario, https://github.com/envoyproxy/envoy/pull/23192. You could try it out locally. Any feedback is welcome.

**Pull request closed without merging**
