### PR TITLE
Update com_github_cyan4973_xxhash to v0.8.1 (current: v0.8.0)

### LINKED ISSUE #19135: Newer release available `com_github_cyan4973_xxhash`: v0.8.1 (current: v0.8.0)
Package Name: com_github_cyan4973_xxhash
Current Version: v0.8.0@2020-07-27 18:57:47
Available Version: v0.8.1@2021-11-29 18:34:10
Upstream releases: https://github.com/Cyan4973/xxHash/releases

### PR DESCRIPTION
**Pull request by kfaseela**
Signed-off-by: Faseela K <faseela.k@est.tech>

Commit Message: Update com_github_cyan4973_xxhash to v0.8.1 (current: v0.8.0)
Additional Description:
      Fixes #19135

### CODE REVIEW

**Comment by kfaseela** [comment]
cc @phlax

**Comment by phlax** [comment]
@wrowe would you mind reviewing or assigning, thanks

**Review by wrowe — APPROVED** [review]
LGTM, merging

**Pull request merged**
