### PR TITLE
Add robots.txt to index only the "latest" docs

### PR DESCRIPTION
**Pull request by lucperkins**
Description: Adds a `robots.txt` that instructs Google not to index docs versions that are not latest.
Risk Level: low
Fixes issue: #8838

I was hoping to find a more programmatic way to do this that doesn't require adding new entries for each docs version, but I haven't found one just yet.

### CODE REVIEW

**Comment by mattklein123** [comment]
Thanks @lucperkins for working on this. Is there someone we can ask about how to make a robots.txt that would allow wildcard exclusion? It seems like there must be some way of doing this? Or should we just move the latest docs to some other location?

**Comment by moderation** [comment]
I had a quick look at the robots.txt spec a while back and there isn't a way to perform wildcard or regex exclusion in the robots.txt file. 

Are you wondering if we could script the file on each PR merge?

**Comment by mattklein123** [comment]
It seems like there are two options:
1) Move the latest docs to `/docs/envoy_latest/...` or something like that. I think this would allow us to have a prefix match that would work for everything else?
2) As @moderation says, generate the file during the publish phase? https://github.com/envoyproxy/envoy/blob/master/docs/publish.sh

/wait

**Comment by moderation** [comment]
My bash foo is very poor and I'm sure this could be improved a lot but the following generates the `robots.txt` file we want via iterating through git tags. Obvious benefit is that a manual change to robots.txt wouldn't be required on each release.

```bash
#!/bin/bash

ROBOTS='User-agent: *\n'
DISALLOW="Disallow: /docs/envoy/"
TAGS=( $( git tag | sort --version-sort ) )

for (( i=0; i<${#TAGS[@]}-1; i++ ));
do
  OUTPUT=$OUTPUT${DISALLOW}${TAGS[$i]}"/\n"
done

echo -e $ROBOTS$OUTPUT
```

**Comment by moderation** [comment]
Not stale. Going to test out the auto generation script above this week.

**Pull request closed without merging**
