### PR TITLE
json: drop exceptions from the json sanitizer

### PR DESCRIPTION
**Pull request by jmarantz**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by jmarantz** [comment]
@wbpcode fyi -- we can make sure CI is cool before review.

**Comment by wbpcode** [comment]
I believe the graph ql is failed because other reasons. And this lgtm. Thanks.

**Review by wbpcode — DISMISSED** [review]

**Comment by phlax** [comment]
apologies @jmarantz i marked this as draft on the basis that the title says WIP

**Comment by jmarantz** [comment]
Good call on the fuzzing branch. This runs through the default corpus just fine, but I couldn't figure out how to let the fuzzer explore for a long time. I have done that in the past but failed to save a script, and [the](https://github.com/envoyproxy/envoy/blob/main/test/fuzz/README.md) is wrong.

**Comment by wbpcode** [comment]
I think the code is safe.

If it actually has a problem, after we merged it to main, it will be tested lots of times everyday by our CI. We can find it in our CI report.

**Review by wbpcode — APPROVED** [review]

**Pull request merged**
