### PR TITLE
owners: bumping phlax and RyanTheOptimist to senior maintainers

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: negative
Testing: trial by fire
Docs Changes: many, over time thank you phlax
Release Notes: n/a

### CODE REVIEW

**Comment by keith** [comment]
congrats folks!

**Review by RyanTheOptimist — APPROVED** [review]
Wow! How amazing! Thank you. LGTM :)

**Review by phlax — APPROVED** [review]
lgtm!

**Comment by mattklein123** [comment]
Thank you @RyanTheOptimist and @phlax for everything that you do!

**Pull request merged**
