### PR TITLE
Clean up QUICHE EpollServer related targets

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
Clean up QUICHE EpollServer related targets
* Use quic/core/quic_epoll_clock instead of a platform impl.
* Implement the (recent) QUICHE Epoll api instead of the (old) QUIC api

Signed-off-by: Ryan Hamilton <rch@google.com>

Risk Level: N/A - test-only
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by phlax** [comment]
@danzh2010 would you mind reviewing this PR

/wait-any

**Review by danzh2010 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
