### PR TITLE
ci: Cleanups/optimizations for azp, Docker build and bazel

### PR DESCRIPTION
**Pull request by phlax**
- fix bazel invokation in build_setup.sh
- use bazel.yml and matrix for precheck jobs
- separate env -> `env.yml`
- add cache for bazel artefacts - external directory, install dir, .cache
- mount more tmpfs in self-hosted
- ensure all bazel invokations use correct options to prevent creation of duplicate build environments

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Comment by alyssawilk** [comment]
Hey @phlax did this perhaps break  mobile coverage?
It's failing with gcc errors on my PR which I think are unrelated and looks like it failed the final run here

 https://github.com/envoyproxy/envoy/actions/runs/4789920456/jobs/8518358939

**Comment by phlax** [comment]
its possible, but im struggling to think why

this seems to be the error

```console


Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
gcc: error: unrecognized command line option '-fprofile-instr-generate'; did you mean '-fprofile-generate'?
gcc: error: unrecognized command line option '-fcoverage-mapping'

```

is it possible something changed there somewhere ?

ill see if i can see any related settings/change

**Comment by phlax** [comment]
these settings seem to be mobile-specific

```console

$ git grep coverage-mapping
mobile/third_party/rbe_configs/cc/cc_toolchain_config.bzl:                            "-fcoverage-mapping",
$ git grep profile-instr-gen
mobile/third_party/rbe_configs/cc/cc_toolchain_config.bzl:                            "-fprofile-instr-generate",
mobile/third_party/rbe_configs/cc/cc_toolchain_config.bzl:                    flag_group(flags = ["-fprofile-instr-generate"]),

```

trying to think why gcc would have changed or the args given to it

**Comment by phlax** [comment]
also mostly this is changes to azp - other than to the scripts in `ci/ ` which i dont think mobile calls

**Comment by alyssawilk** [comment]
mobile coverage calls the coverage script changed in this PR
https://github.com/envoyproxy/envoy/blob/main/.github/workflows/mobile-coverage.yml#L42
It's why I thought the PR might be related to the regression

**Pull request merged**
