### PR TITLE
Add a startup option to exit Envoy if it encounters a bind failure

### PR DESCRIPTION
**Pull request by abaptiste**
Use a startup option to instruct the server it should exit if it cannot bind to a dynamic listener socket.

Signed-off-by: Alvin Baptiste <alvinsb@gmail.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level: Low
Testing: Manual testing of the startup option, as well as `bazel test //test/...`
Docs Changes: Updated `cli.rst` to include new option.  Updated `version_history.rst`
Release Notes: N/A
Fixes: https://github.com/envoyproxy/envoy/issues/3395

### CODE REVIEW

**Comment by htuch** [comment]
@abaptiste is the idea that this only applies to bootstrap listener or also dynamic listeners? Could you update the GitHub top comment above with that information?

**Comment by htuch** [comment]
Thanks for clarifying the comment. @PiotrSikora @mattklein123 is this the solution you envisaged for #3395? Exiting seems a fairly severe behavior, I'd like to have at least one real world situation where shutting down on a bad config update is a reasonable thing to do.

**Comment by mattklein123** [comment]
>  @PiotrSikora @mattklein123 is this the solution you envisaged for #3395? Exiting seems a fairly severe behavior, I'd like to have at least one real world situation where shutting down on a bad config update is a reasonable thing to do.

I think the reason I originally put that comment in there was because if a bind fails it might later succeed. Shutting down and having a process manager restart seems simpler than having some type of retry logic. This is related to the fact that we ACK xDS configs before we know they have been fully applied. Optimally, we would just fail the config and have the management server deal with this case somehow.

With all of that said, this has never been an issue for us at Lyft and I'm not sure if it has been for anyone else. @abaptiste is this needed to solve a real customer issue? I'm wondering if the this could be "fixed" a different way which is to detect addresses that might overlap/conflict and just fail directly? I'm not sure how hard that would be.

**Comment by abaptiste** [comment]
@mattklein123, this isn't required for solving a customer issue.  I saw the open issue and picked it up.

I'm certainly open to trying a different approach.  When we detect the conflict, and "fail directly", I'm not sure exactly what this means.  I'd like to assume that in this case, we do not exit the server, but skip trying to configure and bring up that detected listener.

Alternatively, with the recent `SO_REUSEPORT` changes, this specific issue may not even be a problem moving forward.

**Comment by mattklein123** [comment]
> I'd like to assume that in this case, we do not exit the server, but skip trying to configure and bring up that detected listener.

In a totally optimal world we would delay the xDS ACK until the listener actually starts up on all workers, and if it fails, delete the listener and then signal a failure to the management server. This would be a huge change and I'm not sure the churn/risk is really worth it.

To be completely honest, I'm not sure what the best path forward here is. Given that no one has complained about this in a very long time my inclination is to do nothing. :)

**Comment by abaptiste** [comment]
> my inclination is to do nothing

OK, I can close this PR then ...

**Comment by l8huang** [comment]
> In a totally optimal world we would delay the xDS ACK until the listener actually starts up on all workers, and if it fails, delete the listener and then signal a failure to the management server. 

This is the behavior we are looking for. In our gateway use case, after a gateway Pod created, a node-level agent provisions VIP addresses on a tunnel interface, and in the initial XDS config, listeners bind to these VI addresses. Because VIP address provisioning could take time, listeners could fail to bind before they are in-place.

As an option, does it make sense to reply a xDS NACK to let control plan manager retry the LDS push? @mattklein123 @htuch what do you think?

**Comment by mattklein123** [comment]
> As an option, does it make sense to reply a xDS NACK to let control plan manager retry the LDS push? @mattklein123 @htuch what do you think?

cc @adisuissa for current thinking on this. In general, yes, I still believe it would be better to not ACK until applied / NACK if there is an eventual failure.

**Comment by adisuissa** [comment]
This was also discussed in #9447, and relates to #11396.
The xDS protocol sends an ACK when a config is valid, and delaying it may have undesired consequences (for example an ACK is sent while waiting for RDS, and it is unknown if the listener with its routes will be in a valid state or not). Typically send the ACK/NACK is not coupled with whether the resource is ready to use or not.
I saw some cases where an additional stat counter was introduced to signify the readiness of the resource usage. That said, I do see the benefits of sending an explicit NACK/error indication when a resource has failed.

Personally I think there should be a way for an external entity to know when a resource is ready. This is more generic than sending an ACK/NACK to an xDS-server, and allows other components to observe the resource state.

**Pull request closed without merging**
