### PR TITLE
router: deprecating total_weight

### PR DESCRIPTION
**Pull request by adisuissa**
Commit Message: router: deprecating total_weight
Additional Description:
The `total_weight` [field](https://github.com/envoyproxy/envoy/blob/a8c6db99127206bcea0a27df647a11d279f1df72/api/envoy/config/route/v3/route_components.proto#L462) in weighted clusters was used to validate that the sum of weights isn't 0.
This PR deprecates the field, and uses the sum of the clusters weights instead. This PR also validates that the sum of weights is above 0 (this constraint was relaxed in #21892).

Risk Level: Low
Testing: Updated current tests.
Docs Changes: Updated
Release Notes: Updated
Platform Specific Features: N/A.
Deprecated: `total_weight` from weights clusters.

Signed-off-by: Adi Suissa-Peleg <adip@google.com>

### CODE REVIEW

**Comment by adisuissa** [comment]
Assigning Matt for !Google review. This PR is a follow up to the 0 total-weight for weighted-clusters issue, which we discussed offline.
/assign @mattklein123

**Review by mattklein123 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
