### PR TITLE
crypto: moving core code to core

### PR DESCRIPTION
**Pull request by alyssawilk**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Part of #9953

### CODE REVIEW

**Comment by lizan** [comment]
I believe this still have to use extension build system to be able to swapped by other implementation such as OpenSSL.

**Comment by rojkov** [comment]
> I believe this still have to use extension build system to be able to swapped by other implementation such as OpenSSL.

That's correct. The plan is to drop this ability of swapping because patching proved to be easier for the folks supporting the OpenSSL flavor of Envoy.

/retest

**Comment by dmitri-d** [comment]
lgtm, thanks!

**Review by dmitri-d — APPROVED** [review]

**Review by rojkov — APPROVED** [review]
LGTM

**Pull request merged**
