### PR TITLE
factory context simplification: update code in source to access server-wide resource only by server context

### PR DESCRIPTION
**Pull request by wbpcode**
See https://github.com/envoyproxy/envoy/issues/26476 for related context.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Review by alyssawilk — DISMISSED** [review]
Yay!  Very excited for this clean up.  Surprised the test cleanup wasn't uglier but thanks for wading through all the mock updates :-)

**Comment by wbpcode** [comment]
I couldn't ensure all usage case of factory context was updated. But believe most of that were done. And the potential remaining little could be updated when we clean up the method list of `FactoryContext`.

**Comment by wbpcode** [comment]
Another factor is that the `scope()` of `FactoryContext` actually return root scope for now. So all scope() call of `FactoryContext` should also be updated to scope() call of `ServerFactoryContext`.

**Comment by wbpcode** [comment]
This PR diminished coverage threshold of `wasm` filter (from 1.9 to 1.8). Because the  test is not executed in the coverage mode, so I think this should be fine.

**Comment by wbpcode** [comment]
Friendly ping for a new stamp @alyssawilk

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
