### PR TITLE
process: lowering stale timeout for PRs

### PR DESCRIPTION
**Pull request by alyssawilk**
Changing the stale-out for PRs to 2 weeks.

### CODE REVIEW

**Review by mattklein123 — APPROVED** [review]
Nice! Please monitor the workflow(s) to make sure they are still working.

**Comment by alyssawilk** [comment]
I'm taking off a bit early today, so I'll merge monday and keep an eye on it then.

**Review by lizan — APPROVED** [review]

**Comment by mattklein123** [comment]
FYI it looks like there is action on the upstream PR, so we might want to hold this a bit. No strong feelings.

**Comment by mattklein123** [comment]
Looks like the other PR got merged so I think we should be able to use the new version of the action!

**Pull request closed without merging**
