### PR TITLE
upstream: remove unused message UpstreamBindConfig

### PR DESCRIPTION
**Pull request by soulxu**
Signed-off-by: He Jie Xu <hejie.xu@intel.com>

Commit Message: upstream: remove unused message UpstreamBindConfig
Additional Description:
Risk Level: low
Testing: n/a
Docs Changes: API doc
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Review by adisuissa — COMMENTED** [review]
This a breaking change, and generally is not allowed.
The message was first added into Envoy in #3036, and at the time there was no use of this field.
I think it is ok to remove, but would like to hear from others @envoyproxy/api-shepherds

**Comment by htuch** [comment]
If there are literally zero other references, I think it's fine to remove.

**Comment by soulxu** [comment]
@adisuissa @htuch thanks for the review!

I found this very old PR https://github.com/envoyproxy/data-plane-api/pull/150, it seems we add BindConfig message to instead of UpstreamBindConfig, since we want to support BindConfig both in bootstrap config and cluster config.

**Review by htuch — APPROVED** [review]

**Pull request merged**
