### PR TITLE
Add support for "=" character in pattern rewrite and matching

### PR DESCRIPTION
**Pull request by silverstar194**
Commit Message:
Add fix to allow path matching and rewrites for "=" character. Previous to change "=" was an excluded character and matching/rewrites were not allowed.

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by alyssawilk** [comment]
throwing over to Yan as AFIK he's more familiar with path rewrite corner cases

**Comment by yanavlasov** [comment]
@silverstar194 waiting for the test failures to be addressed https://source.cloud.google.com/results/invocations/7a0ec5a8-2775-428d-8204-9758c7e6cdd8

/wait

**Comment by silverstar194** [comment]
//retest

**Review by yanavlasov — DISMISSED** [review]

**Comment by silverstar194** [comment]
@yanavlasov  Thanks for the review! Can we please merge this?

**Comment by silverstar194** [comment]
@yanavlasov I see `Debs (x64)` test failing with `zstd: error 70 : Write error : cannot write block : No space left on device 
##[error]Bash exited with code '70'.`

Is this a know testing framework issue?

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
