### PR TITLE
update re2 to latest release

### LINKED ISSUE #19762: Newer release available `com_googlesource_code_re2`: 2022-02-01 (current: 2021-11-01)
Package Name: com_googlesource_code_re2
Current Version: 2021-11-01@2021-11-01 04:07:43
Available Version: 2022-02-01@2022-01-31 13:00:00
Upstream releases: https://github.com/google/re2/releases

### PR DESCRIPTION
**Pull request by Mythra**
Commit Message:

update re2 to latest release

Signed-off-by: Cynthia <cynthia@coan.dev>

Additional Description:

A new release of re2 is out, although there's no pressing need to update might as well update now. Looking at the total changes, between the two releases: https://github.com/google/re2/compare/2021-11-01...2022-02-01 the changes:

- Updates to their CI (this doesn't affect us).
- Changes to CMake/Make+.pc (which we don't consume).
- Python scripts changing to python3 (which we already use)

- Addressing a '-Wunused-but-set-variable' warning.
- Switching to a new "FuzzedDataProvider", which while adding new things contains the same methods from what I could see.
- removing a map lookup.

Risk Level: Small
Testing: Should be handled by CI as besides not doing a single map lookup -- there is no functional changes.
Docs Changes: N/A no user facing changes.
Release Notes: N/A no user facing changes.
fixes #19762

### CODE REVIEW

**Comment by moderation** [comment]
I've been running this version in my local setup without issue. One suggestion for consistency is that we could change the way we bring `re2` in. I've been running the code below for a couple of months (you can ignore the unused tclap patch removal).
```diff
diff --git a/bazel/repositories.bzl b/bazel/repositories.bzl    
index ae048e600..bdc98bf2a 100644                               
--- a/bazel/repositories.bzl                                    
+++ b/bazel/repositories.bzl                                    
@@ -199,13 +199,13 @@ def envoy_dependencies(skip_targets = []):
     _net_zlib()
     _com_github_zlib_ng_zlib_ng()
     _org_brotli()
+    _re2()                                                     
     _upb()
     _proxy_wasm_cpp_sdk()
     _proxy_wasm_cpp_host()
     _emscripten_toolchain()
     _rules_fuzzing()
     external_http_archive("proxy_wasm_rust_sdk")
-    external_http_archive("com_googlesource_code_re2")         
     _com_google_cel_cpp()
     _com_github_google_perfetto()
     external_http_archive("com_github_google_flatbuffers")
@@ -303,7 +303,6 @@ def _com_github_mirror_tclap():             
     external_http_archive(
         name = "com_github_mirror_tclap",
         build_file = "@envoy//bazel/external:tclap.BUILD",
-        patch_args = ["-p1"],                                  
     )
     native.bind(
         name = "tclap",
@@ -926,6 +925,14 @@ def _com_github_grpc_grpc():               
         actual = "@upb//:json",
     )

+def _re2():                                                    
+    external_http_archive("com_googlesource_code_re2")         
+                                                               
+    native.bind(                                               
+        name = "re2",                                          
+        actual = "@com_googlesource_code_re2//:re2",           
+    )                                                          
+                                                               
 def _upb():
     external_http_archive(name = "upb")
```

**Comment by KBaichoo** [comment]
ping @moderation  for dependency sign-off

**Review by phlax — APPROVED** [review]
lgtm, thanks @Mythra

**Pull request merged**
