### PR TITLE
Adds documentation note for features not supported on Windows

### PR DESCRIPTION
**Pull request by davinci26**
Commit Message:
Adds note in the docs for features that are not supported on Windows
See #13322

Risk Level: N/A
Testing: N/A
Docs Changes: Only docs
Release Notes: N/A

### CODE REVIEW

**Comment by davinci26** [comment]
@envoyproxy/windows-dev do you think we should leave the issue open for extra documentation or close the issue with this PR?

**Comment by davinci26** [comment]
Also chime in with other features that you know that they are not working on Windows

**Comment by alyssawilk** [comment]
Sorry, cI was having some issues yesterday - can you do a main merge?

**Comment by alyssawilk** [comment]
Awesome, LGTM from a docs perspective but I'd like one of the @envoyproxy/windows-dev  (@wrowe ? ) to sign off for correctness :-)

**Review by sunjayBhatia — COMMENTED** [review]
As far as I remember, these notes sound correct 👍🏽

**Review by alyssawilk — APPROVED** [review]

**Review by mattklein123 — COMMENTED** [review]
High level comment: this kind of thing will inevitably get out of date. This is fine for now but can we work towards codifying this in source code probably via a bazel tag that is then used to render extension specific documentation like we are now starting to do elsewhere? It would be nice to open a tracking issue on this.

cc @phlax @davinci26

**Pull request merged**
