### PR TITLE
mobile: Add the `no-remote-exec` tag to the Swift stats tests

### PR DESCRIPTION
**Pull request by abeyad**
For reasons we haven't figured out yet, RBE does not work well with the Swift tests and causes frequent timeouts on CI.

See https://github.com/envoyproxy/envoy/issues/32551 for details.

We tagged the Swift tests with `no-remote-exec` but forgot to do so for the swift/stats tests, so we're doing that here. This test timed out recently on CI because we didn't have the `no-remote-exec` tag.

### CODE REVIEW

**Comment by phlax** [comment]
```console
 ERROR: /Users/runner/work/envoy/envoy/mobile/WORKSPACE:98:18: fetching android_sdk_repository rule //external:androidsdk: Android SDK api level 30 was requested but it is not installed in the Android SDK at /Users/runner/Library/Android/sdk. The api levels found were [34, 33, 32, 31]. Please choose an available api level or install api level 30 from the Android SDK Manager.
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 25. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]. Bazel will attempt to treat the NDK as if it was r21. This may cause compilation and linkage problems. Please download a supported NDK version.
ERROR: Analysis of target '//examples/objective-c/hello_world:app' failed; build aborted: Android SDK api level 30 was requested but it is not installed in the Android SDK at /Users/runner/Library/Android/sdk. The api levels found were [34, 33, 32, 31]. Please choose an available api level or install api level 30 from the Android SDK Manager.
```

which is wierd - i thought we resolved the android/ndk stuff for ios - cc @keith

**Comment by keith** [comment]
It must be something about how that matrix is configured that leads the source to not happen in the right invocation? I think your change might help

**Comment by phlax** [comment]
yeah - i think its fixed now - i tested in staging repo

**Pull request merged**
