### PR TITLE
docker: Publish images from release branches/commits

### PR DESCRIPTION
**Pull request by phlax**
not from the tag

Partial fix for #23773

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
with this PR the version is taken from `VERSION.txt` where required rather than from the branch name

the branch names are still significant in determining whether its a `main` or `release` branch or a now ~ignored `tag` branch

**Comment by phlax** [comment]
```console
$ cat VERSION.txt 
1.26.0-dev
(dev) phlax@scratch:~/dev/envoydev/envoy$ DOCKER_CI_DRYRUN=true AZP_BRANCH=refs/heads/main ./ci/docker_ci.sh | grep -E "^>> "
>> BUILD: envoyproxy/envoy-dev:MOCKSHA
>> BUILD: envoyproxy/envoy:dev-MOCKSHA
>> BUILD: envoyproxy/envoy-debug-dev:MOCKSHA
>> BUILD: envoyproxy/envoy:debug-dev-MOCKSHA
f>> BUILD: envoyproxy/envoy-contrib-dev:MOCKSHA
>> BUILD: envoyproxy/envoy:contrib-dev-MOCKSHA
>> BUILD: envoyproxy/envoy-contrib-debug-dev:MOCKSHA
>> BUILD: envoyproxy/envoy:contrib-debug-dev-MOCKSHA
>> BUILD: envoyproxy/envoy-distroless-dev:MOCKSHA
>> BUILD: envoyproxy/envoy:distroless-dev-MOCKSHA
>> BUILD: envoyproxy/envoy-google-vrp-dev:MOCKSHA
>> BUILD: envoyproxy/envoy-tools-dev:MOCKSHA
>> PUSH: envoyproxy/envoy-dev:MOCKSHA
>> PUSH: envoyproxy/envoy:dev-MOCKSHA
>> PUSH: envoyproxy/envoy-dev:latest
>> PUSH: envoyproxy/envoy:dev
>> PUSH: envoyproxy/envoy-debug-dev:MOCKSHA
>> PUSH: envoyproxy/envoy:debug-dev-MOCKSHA
>> PUSH: envoyproxy/envoy-debug-dev:latest
>> PUSH: envoyproxy/envoy:debug-dev
>> PUSH: envoyproxy/envoy-contrib-dev:MOCKSHA
>> PUSH: envoyproxy/envoy:contrib-dev-MOCKSHA
>> PUSH: envoyproxy/envoy-contrib-dev:latest
>> PUSH: envoyproxy/envoy:contrib-dev
>> PUSH: envoyproxy/envoy-contrib-debug-dev:MOCKSHA
>> PUSH: envoyproxy/envoy:contrib-debug-dev-MOCKSHA
>> PUSH: envoyproxy/envoy-contrib-debug-dev:latest
>> PUSH: envoyproxy/envoy:contrib-debug-dev
>> PUSH: envoyproxy/envoy-distroless-dev:MOCKSHA
>> PUSH: envoyproxy/envoy:distroless-dev-MOCKSHA
>> PUSH: envoyproxy/envoy-distroless-dev:latest
>> PUSH: envoyproxy/envoy:distroless-dev
>> PUSH: envoyproxy/envoy-google-vrp-dev:MOCKSHA
>> PUSH: envoyproxy/envoy-google-vrp-dev:latest
>> PUSH: envoyproxy/envoy-tools-dev:MOCKSHA
>> PUSH: envoyproxy/envoy-tools-dev:latest

```

**Comment by phlax** [comment]
```
$ cat VERSION.txt 
1.26.0-dev
$ DOCKER_CI_DRYRUN=true AZP_BRANCH=refs/heads/release/vXXX ./ci/docker_ci.sh | grep -E "^>> "
>> BUILD: envoyproxy/envoy-dev:MOCKSHA
>> BUILD: envoyproxy/envoy:dev-MOCKSHA
>> BUILD: envoyproxy/envoy-debug-dev:MOCKSHA
>> BUILD: envoyproxy/envoy:debug-dev-MOCKSHA
>> BUILD: envoyproxy/envoy-contrib-dev:MOCKSHA
>> BUILD: envoyproxy/envoy:contrib-dev-MOCKSHA
>> BUILD: envoyproxy/envoy-contrib-debug-dev:MOCKSHA
>> BUILD: envoyproxy/envoy:contrib-debug-dev-MOCKSHA
>> BUILD: envoyproxy/envoy-distroless-dev:MOCKSHA
>> BUILD: envoyproxy/envoy:distroless-dev-MOCKSHA
>> BUILD: envoyproxy/envoy-google-vrp-dev:MOCKSHA
>> BUILD: envoyproxy/envoy-tools-dev:MOCKSHA
>> PUSH: envoyproxy/envoy-dev:MOCKSHA
>> PUSH: envoyproxy/envoy:dev-MOCKSHA
>> PUSH: envoyproxy/envoy-debug-dev:MOCKSHA
>> PUSH: envoyproxy/envoy:debug-dev-MOCKSHA
>> PUSH: envoyproxy/envoy-contrib-dev:MOCKSHA
>> PUSH: envoyproxy/envoy:contrib-dev-MOCKSHA
>> PUSH: envoyproxy/envoy-contrib-debug-dev:MOCKSHA
>> PUSH: envoyproxy/envoy:contrib-debug-dev-MOCKSHA
>> PUSH: envoyproxy/envoy-distroless-dev:MOCKSHA
>> PUSH: envoyproxy/envoy:distroless-dev-MOCKSHA
>> PUSH: envoyproxy/envoy-google-vrp-dev:MOCKSHA
>> PUSH: envoyproxy/envoy-tools-dev:MOCKSHA

```

**Comment by phlax** [comment]
```console
$ cat VERSION.txt 
1.26.0
$ DOCKER_CI_DRYRUN=true AZP_BRANCH=refs/heads/main ./ci/docker_ci.sh | grep -E "^>> "
>> BUILD: envoyproxy/envoy:v1.26.0
>> BUILD: envoyproxy/envoy:v1.26.0
>> BUILD: envoyproxy/envoy-debug:v1.26.0
>> BUILD: envoyproxy/envoy:debug-v1.26.0
>> BUILD: envoyproxy/envoy-contrib:v1.26.0
>> BUILD: envoyproxy/envoy:contrib-v1.26.0
>> BUILD: envoyproxy/envoy-contrib-debug:v1.26.0
>> BUILD: envoyproxy/envoy:contrib-debug-v1.26.0
>> BUILD: envoyproxy/envoy-distroless:v1.26.0
>> BUILD: envoyproxy/envoy:distroless-v1.26.0
>> BUILD: envoyproxy/envoy-google-vrp:v1.26.0
>> BUILD: envoyproxy/envoy-tools:v1.26.0
>> PUSH: envoyproxy/envoy:v1.26.0
>> PUSH: envoyproxy/envoy:v1.26.0
>> PUSH: envoyproxy/envoy:v1.26-latest
>> PUSH: envoyproxy/envoy:v1.26-latest
>> PUSH: envoyproxy/envoy-debug:v1.26.0
>> PUSH: envoyproxy/envoy:debug-v1.26.0
>> PUSH: envoyproxy/envoy-debug:v1.26-latest
>> PUSH: envoyproxy/envoy:debug-v1.26-latest
>> PUSH: envoyproxy/envoy-contrib:v1.26.0
>> PUSH: envoyproxy/envoy:contrib-v1.26.0
>> PUSH: envoyproxy/envoy-contrib:v1.26-latest
>> PUSH: envoyproxy/envoy:contrib-v1.26-latest
>> PUSH: envoyproxy/envoy-contrib-debug:v1.26.0
>> PUSH: envoyproxy/envoy:contrib-debug-v1.26.0
>> PUSH: envoyproxy/envoy-contrib-debug:v1.26-latest
>> PUSH: envoyproxy/envoy:contrib-debug-v1.26-latest
>> PUSH: envoyproxy/envoy-distroless:v1.26.0
>> PUSH: envoyproxy/envoy:distroless-v1.26.0
>> PUSH: envoyproxy/envoy-distroless:v1.26-latest
>> PUSH: envoyproxy/envoy:distroless-v1.26-latest
>> PUSH: envoyproxy/envoy-google-vrp:v1.26.0
>> PUSH: envoyproxy/envoy-google-vrp:v1.26-latest
>> PUSH: envoyproxy/envoy-tools:v1.26.0
>> PUSH: envoyproxy/envoy-tools:v1.26-latest
```

**Comment by phlax** [comment]
```console
$ cat VERSION.txt 
1.26.1
$ DOCKER_CI_DRYRUN=true AZP_BRANCH=refs/heads/release/vXXX ./ci/docker_ci.sh | grep -E "^>> "
>> BUILD: envoyproxy/envoy:v1.26.1
>> BUILD: envoyproxy/envoy:v1.26.1
>> BUILD: envoyproxy/envoy-debug:v1.26.1
>> BUILD: envoyproxy/envoy:debug-v1.26.1
>> BUILD: envoyproxy/envoy-contrib:v1.26.1
>> BUILD: envoyproxy/envoy:contrib-v1.26.1
>> BUILD: envoyproxy/envoy-contrib-debug:v1.26.1
>> BUILD: envoyproxy/envoy:contrib-debug-v1.26.1
>> BUILD: envoyproxy/envoy-distroless:v1.26.1
>> BUILD: envoyproxy/envoy:distroless-v1.26.1
>> BUILD: envoyproxy/envoy-google-vrp:v1.26.1
>> BUILD: envoyproxy/envoy-tools:v1.26.1
>> PUSH: envoyproxy/envoy:v1.26.1
>> PUSH: envoyproxy/envoy:v1.26.1
>> PUSH: envoyproxy/envoy:v1.26-latest
>> PUSH: envoyproxy/envoy:v1.26-latest
>> PUSH: envoyproxy/envoy-debug:v1.26.1
>> PUSH: envoyproxy/envoy:debug-v1.26.1
>> PUSH: envoyproxy/envoy-debug:v1.26-latest
>> PUSH: envoyproxy/envoy:debug-v1.26-latest
>> PUSH: envoyproxy/envoy-contrib:v1.26.1
>> PUSH: envoyproxy/envoy:contrib-v1.26.1
>> PUSH: envoyproxy/envoy-contrib:v1.26-latest
>> PUSH: envoyproxy/envoy:contrib-v1.26-latest
>> PUSH: envoyproxy/envoy-contrib-debug:v1.26.1
>> PUSH: envoyproxy/envoy:contrib-debug-v1.26.1
>> PUSH: envoyproxy/envoy-contrib-debug:v1.26-latest
>> PUSH: envoyproxy/envoy:contrib-debug-v1.26-latest
>> PUSH: envoyproxy/envoy-distroless:v1.26.1
>> PUSH: envoyproxy/envoy:distroless-v1.26.1
>> PUSH: envoyproxy/envoy-distroless:v1.26-latest
>> PUSH: envoyproxy/envoy:distroless-v1.26-latest
>> PUSH: envoyproxy/envoy-google-vrp:v1.26.1
>> PUSH: envoyproxy/envoy-google-vrp:v1.26-latest
>> PUSH: envoyproxy/envoy-tools:v1.26.1
>> PUSH: envoyproxy/envoy-tools:v1.26-latest

```

**Comment by phlax** [comment]
### TAG (DO NOTHING)

```console
$ cat VERSION.txt 
1.26.1
$ DOCKER_CI_DRYRUN=true AZP_BRANCH=refs/tags/1.23 ./ci/docker_ci.sh | grep -E "^>> "
>> BUILD: envoyproxy/envoy:v1.26.1
>> BUILD: envoyproxy/envoy:v1.26.1
>> BUILD: envoyproxy/envoy-debug:v1.26.1
>> BUILD: envoyproxy/envoy:debug-v1.26.1
>> BUILD: envoyproxy/envoy-contrib:v1.26.1
>> BUILD: envoyproxy/envoy:contrib-v1.26.1
>> BUILD: envoyproxy/envoy-contrib-debug:v1.26.1
>> BUILD: envoyproxy/envoy:contrib-debug-v1.26.1
>> BUILD: envoyproxy/envoy-distroless:v1.26.1
>> BUILD: envoyproxy/envoy:distroless-v1.26.1
>> BUILD: envoyproxy/envoy-google-vrp:v1.26.1
>> BUILD: envoyproxy/envoy-tools:v1.26.1
```

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
