### PR TITLE
docs: delete unused svg

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Loong <loong.dai@intel.com>

Use shell pipe to check useless svg:
```
root:[envoy]$ find -name "*.svg" | xargs -n1 basename |sort -u | xargs -n1 -I@ bash -c "if ! git grep -q @; then echo @ ; fi"
check-solid.svg
copy-button.svg
envoy-perf-script.svg
fontawesome-webfont.svg
```

After double check, only `envoy-perf-script.svg` need delete.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@daixiang0 grepping for the others - i dont seem them - where are they used ?

**Comment by daixiang0** [comment]
The others are css or js used, like
```
root:[envoy]$ find -name copy-button.svg
./generated/docs/_static/copy-button.svg
```

**Review by phlax — APPROVED** [review]
lgtm, thanks @daixiang0

**Comment by phlax** [comment]
looks like this needs an api stamp

**Comment by daixiang0** [comment]
@envoyproxy/api-shepherds please take a look, although it is not related to API indeed.

**Review by adisuissa — COMMENTED** [review]
/lgtm api

**Pull request merged**
