### PR TITLE
[Windows CI] Fix issue with Slack message for flaky tests

### PR DESCRIPTION
**Pull request by davinci26**
Signed-off-by: Sotiris Nanopoulos <sonanopo@microsoft.com>
See recent CI build runs and https://github.com/slackapi/python-slack-sdk/issues/334#issuecomment-520246083

Risk Level: Low
Testing: CI

### CODE REVIEW

**Comment by davinci26** [comment]
cc @envoyproxy/windows-dev creating as Draft and I will push a few empty commits to hopefully get some flakes and see the message in the chat.

**Comment by sunjayBhatia** [comment]
> cc @envoyproxy/windows-dev creating as Draft and I will push a few empty commits to hopefully get some flakes and see the message in the chat.

you might have to turn off caching [here](https://github.com/envoyproxy/envoy/blob/7554d61bccf136638bdfb383c10d049dc8bd3790/ci/windows_ci_steps.sh#L45) otherwise all the tests will always pass in this PR and we wont see flakes

**Comment by davinci26** [comment]
@lizan @sunjayBhatia you can review now.

**Comment by sunjayBhatia** [comment]
@davinci26 maybe just add a comment in the script describing why this is necessary? otherwise LGTM, seems to work 👍

**Comment by sunjayBhatia** [comment]
> @davinci26 maybe just add a comment in the script describing why this is necessary? otherwise LGTM, seems to work 👍

for posterity, there was a flaky test here: https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/59567/logs/158

**Comment by davinci26** [comment]
> @davinci26 maybe just add a comment in the script describing why this is necessary? 
Added a small comment

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
