### PR TITLE
brotoli: fix CI by adding category field to bazel BUILD files

### PR DESCRIPTION
**Pull request by esmet**
Commit Message: brotoli: fix CI by adding category field to bazel BUILD files
Additional Description:
Risk Level: low
Testing: ci/run_envoy_docker.sh 'ci/do_ci.sh deps'
Docs Changes: none
Release Notes: none

### CODE REVIEW

**Comment by davinci26** [comment]
@lizan @yanavlasov PTAL this currently blocks the CI

**Review by antoniovicente — APPROVED** [review]
Seems correct, waiting for CI before I can merge.

cc @envoyproxy/senior-maintainers or @envoyproxy/admins who AFAIK can force submit without waiting for CI

**Comment by phlax** [comment]
lgtm

**Comment by moderation** [comment]
Thanks - fixes issue reported https://github.com/envoyproxy/envoy/pull/12998#issuecomment-775479650

**Review by lizan — APPROVED** [review]

**Pull request merged**
