### PR TITLE
http2: removes an unnecessary ASSERT

### PR DESCRIPTION
**Pull request by birenroy**
This ASSERT triggers with a specific `codec_impl_fuzz_test.cc` input, but the condition itself appears arbitrary. For the purpose of code correctness, it doesn't matter whether the error code passed in is NO_ERROR or something else.

All unit and integration tests continue to pass without the ASSERT in place.

```
$ bazel test --config=remote test/integration/... test/common/http/...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: a59c05fc-a314-4957-8e1c-188bfbec3704
INFO: Analyzed 507 targets (714 packages loaded, 37077 targets configured).
INFO: Found 361 targets and 146 test targets...
INFO: Elapsed time: 920.573s, Critical Path: 849.49s
INFO: 4318 processes: 2722 remote cache hit, 158 internal, 1438 remote.
INFO: Build completed successfully, 4318 total actions

Executed 146 out of 146 tests: 146 tests pass.
```

Commit Message: removes an unnecessary ASSERT
Additional Description:
Risk Level: low
Testing: ran all unit and integration tests locally
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Comment by yanavlasov** [comment]
@birenroy can you add the fuzz corpus that was hitting this ASSERT, please?

**Comment by birenroy** [comment]
> @birenroy can you add the fuzz corpus that was hitting this ASSERT, please?

Done.

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
