### PR TITLE
docs: clarifying upstream filter docs

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: n/a
Testing: n/a
Docs Changes: yes
Addressing concerns from #16599

### CODE REVIEW

**Review by phlax — APPROVED** [review]
lgtm

im wondering if there is a list of `upstream filters` somewhere

**Comment by alyssawilk** [comment]
as said elsewhere in docs upstream Envoy doesn't have any.  I could add that in the API docs if you think it's worth it, I'm just concerned it would get out of date.

**Comment by phlax** [comment]
not sure - it just seems a bit odd to only link to the filters that dont work

**Review by adisuissa — COMMENTED** [review]
/lgtm API

Maybe add a link to the list of valid upstream filters.

**Pull request merged**
