### PR TITLE
[backport/v1.24] tools, github: Avoid rate-limited calls when calling GitHub API

### PR DESCRIPTION
**Pull request by dio**
Commit Message: This makes sure we are not rate-limited when calling GitHub API 

Cherry-picked from:

- ceb45a32da8c9886c0eb87f8723068b6cd96c5f8
- 36fc1ccc1de30b79594ca5ef9d8f0799a0f399a0
- 3ea63d73407f5af8992e20e1bf0fb4b481b71d13

Risk Level: Low
Testing: Manual
Docs Changes: N/A
Release Notes: N/A
Platform-Specific Features: N/A

### CODE REVIEW

**Comment by dio** [comment]
wait for https://github.com/envoyproxy/envoy/pull/23766.

**Comment by dio** [comment]
Will check if this is flaky

**Comment by dio** [comment]
Probably `//test/extensions/transport_sockets/tls/ocsp:ocsp_test` and `//test/extensions/transport_sockets/tls:ssl_socket_test` are indeed flaky on 1.24.x? But mostly unknown file failure.

**Comment by phlax** [comment]
seems like this has triggered all of the flakes

/retest

**Review by phlax — APPROVED** [review]
lgtm, thanks @dio

**Pull request merged**
