### PR TITLE
test: remove superfluous test dependencies

### PR DESCRIPTION
**Pull request by foreseeable**
Signed-off-by: Muge Chen <mugechen@google.com>

Commit Message: remove superfluous includes
Additional Description: The monolith mock library mocks/server/mocks.h is included by several tests but never used. Remove them to speed up building phase
Risk Level: low
Testing: existing tests
Docs Changes: N/A
Release Notes: no
Related Issues: #10917

/cc @ahedberg

### CODE REVIEW

**Comment by alyssawilk** [comment]
Nice clean up!  Looks like this may have removed it from a test that needed it though - mind checking out CI?

**Comment by foreseeable** [comment]
> Thanks! Did we run comparisons of compile time before/after this change?

@ahedberg yes, we can talk about this at the standup

**Comment by jmarantz** [comment]
Would be curious to see the build-time comparison once everything is working.

Did you use a tool to discover which dependencies were superfluous?

**Comment by foreseeable** [comment]
> Would be curious to see the build-time comparison once everything is working.
> 
> Did you use a tool to discover which dependencies were superfluous?

I will post the comparison to the issue page referred by this pr.

Currently the superfluous dependencies are detected by simple keyword matching. i.e. find whether there're keyword 'Server::Mock***' appeared in the code file which includes 'test/server/mocks.h'. I wrote some scripts to refactor the code base and will upload it later.

**Comment by alyssawilk** [comment]
+1 would love to see numbers iff you have them handy, but this looks like an improvement either way :-)

**Pull request merged**
