### PR TITLE
Example: Update gzip example verify.sh with docker-compose.yaml

### PR DESCRIPTION
**Pull request by a180285**
Signed-off-by: HuangWei <huangwei.a180285@gmail.com>

Commit Message: Update gzip example verify.sh with docker-compose.yaml
Additional Description:

The default ports in latest verify.sh is not synced with [docker-compose.yaml](https://github.com/envoyproxy/envoy/blob/main/examples/gzip/docker-compose.yaml)

Risk Level: low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
thanks for raising this @a180285 but i think this change is incorrect

the ports are not supposed to match between the composition and the verify.sh script

was there a particular issue that you were trying to address ?

**Comment by a180285** [comment]
@phlax En, I'm a starter to envoy. I notice this is, When I following the tutorial here: https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/gzip.html

It tell me to use docker-compose to start testing env. After doing that I found there is a verify.sh. So it confuse me to use that verify.sh to verify my docker-compose.

Actually. I remember when I changed the ports in verify.sh. It's works. So I think it's a mistake.

But anyway, it's in the same folder, but not match each other. I think will confuse somebody, especially like me new one to this project.

**Comment by a180285** [comment]
May be we can add some notice in the tutorial doc above to tell that: "Don't use verify.sh directly".

**Comment by phlax** [comment]
> Actually. I remember when I changed the ports in verify.sh. It's works. So I think it's a mistake.

not sure i follow exactly - but if changing the ports worked its for the same reason that verify.sh does this - to prevent clashing ports

many of the examples expose the same ports on the host as each other

this is fine for end users, it assumes you dont run all of the examples simultaneously

the port override in verify.sh is there to allow the tests to run concurrently (altho that is yet to be implemented)

**Comment by phlax** [comment]
perhaps we can add something in the example setup page that says "only run one example at a time and stop any others to prevent port clashes" or something like that

**Comment by a180285** [comment]
Yes, I'm not following the doc exactly. Because when I run following commands:
```bash
pwd
envoy/examples/gzip
docker-compose pull
docker-compose up --build -d
docker-compose ps
```

It failed to build & run. I spend some time to make it being able to build & run. Maybe it interupte me to following the doc.


BTW: do you know where to submit changes to the doc. Maybe later I will try to submit a change to the doc?

**Comment by phlax** [comment]
> It failed to build & run

what is the error ?

> BTW: do you know where to submit changes to the doc. Maybe later I will try to submit a change to the doc?

yep - https://github.com/envoyproxy/envoy/tree/main/docs/root/start/sandboxes

contributions are greatly appreciated, and i would be happy to review

**Comment by a180285** [comment]
Here is the output
```
docker compose pull
[+] Running 2/3
 ⠿ service Skipped - No image to be pulled                                                                                                                                                                       0.0s
 ⠿ envoy-stats Skipped - No image to be pulled                                                                                                                                                                   0.0s
 ⠿ flask_service Warning                                                                                                                                                                                         4.5s
WARNING: Some service image(s) must be built from source by running:
    docker compose build flask_service
1 error occurred:
        * Error response from daemon: pull access denied for flask_service, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

```

Maybe it's because I'm useing docker compose not docker-compose?

**Comment by a180285** [comment]
Next command has similar error.
```
docker compose up --build -d
[+] Building 3.2s (16/16) FINISHED
 => [gzip-service internal] load build definition from Dockerfile-service                                                                                                                                        0.1s
 => => transferring dockerfile: 40B                                                                                                                                                                              0.0s
 => [flask_service:python-3.10-slim-bullseye internal] load build definition from Dockerfile                                                                                                                     0.1s
 => => transferring dockerfile: 32B                                                                                                                                                                              0.0s
 => [gzip-envoy-stats internal] load build definition from Dockerfile-gzip                                                                                                                                       0.1s
 => => transferring dockerfile: 37B                                                                                                                                                                              0.0s
 => [gzip-service internal] load .dockerignore                                                                                                                                                                   0.1s
 => => transferring context: 2B                                                                                                                                                                                  0.0s
 => [gzip-envoy-stats internal] load .dockerignore                                                                                                                                                               0.1s
 => => transferring context: 2B                                                                                                                                                                                  0.0s
 => [flask_service:python-3.10-slim-bullseye internal] load .dockerignore                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                                                  0.0s
 => ERROR [gzip-service internal] load metadata for docker.io/library/flask_service:python-3.10-slim-bullseye                                                                                                    2.2s
 => [gzip-envoy-stats internal] load metadata for docker.io/envoyproxy/envoy-dev:latest                                                                                                                          0.0s
 => [gzip-envoy-stats internal] load build context                                                                                                                                                               0.0s
 => => transferring context: 37B                                                                                                                                                                                 0.0s
 => [gzip-envoy-stats 1/3] FROM docker.io/envoyproxy/envoy-dev:latest                                                                                                                                            0.0s
 => [flask_service:python-3.10-slim-bullseye internal] load metadata for docker.io/library/python:3.10.7-slim-bullseye@sha256:f2ee145f3bc4e061f8dfe7e6ebd427a410121495a0bd26e7622136db060c59e0                   2.2s
 => CACHED [gzip-envoy-stats 2/3] COPY ./gzip-envoy.yaml /etc/gzip-envoy.yaml                                                                                                                                    0.0s
 => CACHED [gzip-envoy-stats 3/3] RUN chmod go+r /etc/gzip-envoy.yaml                                                                                                                                            0.0s
 => [gzip-envoy-stats] exporting to image                                                                                                                                                                        0.1s
 => => exporting layers                                                                                                                                                                                          0.0s
 => => writing image sha256:85b946b2f0a4ca944a4c2f57630ddd00ac240b514377158585e24b9eef48a245                                                                                                                     0.0s
 => => naming to docker.io/library/gzip-envoy-stats                                                                                                                                                              0.0s
 => [auth] library/flask_service:pull token for registry-1.docker.io                                                                                                                                             0.0s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                                                                                    0.0s
------
 > [gzip-service internal] load metadata for docker.io/library/flask_service:python-3.10-slim-bullseye:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**Comment by phlax** [comment]
> Maybe it's because I'm useing docker compose not docker-compose?

yes - quite possible - its not tested and i believe has caused similar problems

i would like to convert the examples to use `docker compose` but testing it hit various issues so will take some time

**Comment by a180285** [comment]
En I use another env to run `docker-compose` instead. the above issue not occured.

But that env don't have global internal access, (In China). It should work with docker-compose. I think.

**Pull request closed without merging**
