### PR TITLE
Make ABSL use STL types.

### PR DESCRIPTION
**Pull request by yanavlasov**
Commit Message:
Switch ABSL to alias corresponding STL types. This is to make transition to c++20 easier.

Additional Description:
We have been running internal binaries in this mode for some time and had no problems so far.

Risk Level: Medium
Testing: Unit Test
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

Signed-off-by: Yan Avlasov <yavlasov@google.com>

### CODE REVIEW

**Review by mattklein123 — APPROVED** [review]

**Review by ravenblackx — APPROVED** [review]

**Review by mattklein123 — DISMISSED** [review]

**Comment by yanavlasov** [comment]
Working on fixing QUICHE Windows build with the team. Will update this PR when it is ready.

**Comment by lizan** [comment]
Is envoy mobile good with this change? I believe we disabled this because some mobile platforms are lack of runtime library for std::optional, variant and string_view. @envoyproxy/envoy-mobile-maintainers

**Review by htuch — APPROVED** [review]

**Comment by yanavlasov** [comment]
> Is envoy mobile good with this change? I believe we disabled this because some mobile platforms are lack of runtime library for std::optional, variant and string_view. @envoyproxy/envoy-mobile-maintainers

Wouldn't it be covered by mobile CI?

**Comment by jpsim** [comment]
> Wouldn't it be covered by mobile CI?

mobile CI only runs on a subset of PRs right now due to limited availability of the CI machines. To run the full Envoy Mobile CI suite you can make any change to `mobile/**` (e.g. temporarily add a trailing newline to `mobile/.bazelrc`).

**Comment by RyanTheOptimist** [comment]
> > Is envoy mobile good with this change? I believe we disabled this because some mobile platforms are lack of runtime library for std::optional, variant and string_view. @envoyproxy/envoy-mobile-maintainers
> 
> Wouldn't it be covered by mobile CI?

Envoy Mobile CI doesn't really run unless there are changes to mobile. The jobs start, but they become a no-op (via mobile/tools/should_run_ci.sh). It would be a good idea to make a trivial change to a file in mobile/ and push in order to run all mobile jobs. Could you do this, please?

That being said, we believe that the android and iOS platforms we target *should* have support for these library features but I'll do some more investigation.

**Comment by yanavlasov** [comment]
> > Wouldn't it be covered by mobile CI?
> 
> mobile CI only runs on a subset of PRs right now due to limited availability of the CI machines. To run the full Envoy Mobile CI suite you can make any change to `mobile/**` (e.g. temporarily add a trailing newline to `mobile/.bazelrc`).

Done

**Comment by jpsim** [comment]
`std::optional` should be ok now that Envoy Mobile [targets iOS 12.0 and up](https://github.com/envoyproxy/envoy/blob/8a44fd09d9c0b276ad1812326b579c23d7e1f331/mobile/.bazelrc#L19) according to this [Apple developer forums thread](https://developer.apple.com/forums/thread/120977).

**Comment by yanavlasov** [comment]
Looks like mobile CI is happy. Still working with QUICHE dev to fix non compliant code in Balsa.

**Comment by yanavlasov** [comment]
I'm unsure if the windows test timeout is related to this change or not. I'm going to try to reproduce it locally.

**Comment by yanavlasov** [comment]
I had to disable one test that became more flaky on Windows. It is a death test and I'm unsure how flakiness is related to this change. I do not have a set-up where I can debug this issue, so will need help from Windows devs to look into re-enabling this test.

**Comment by yanavlasov** [comment]
Some mobile tests failed for unknown reasons (no visible diagnostics). @jpsim @RyanTheOptimist

**Comment by RyanTheOptimist** [comment]
> Some mobile tests failed for unknown reasons (no visible diagnostics). @jpsim @RyanTheOptimist

I'm re-running those two failed tests to see if the failure were flakes.

**Comment by jpsim** [comment]
> Some mobile tests failed for unknown reasons (no visible diagnostics).

Could you please share a link to the failed job next time? The failures are gone now so I can't look into what failed and why.

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
