### PR TITLE
pr/notifier: Switch to bazel and update

### LINKED ISSUE #29961: PR-reminder bot in Slack is currently not working
*Title*: PR-reminder bot is currently not working

*Description*:
Both I and the maintainers channel on Slack did not receive the usual daily pings since Oct 2nd.

### PR DESCRIPTION
**Pull request by phlax**
The newer tool has 3 modes - normal, dry_run, and report

report dumps a report, whereas dry_run shows what would be posted to slack

This PR enables the ci in pr runs using `--dry_run` so you can see what would be posted

Fix #29961 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by jmarantz — APPROVED** [review]

**Comment by phlax** [comment]
you can see output here https://github.com/envoyproxy/envoy/actions/runs/6470490290/job/17566815179?pr=30054#step:3:88

**Comment by phlax** [comment]
@jmarantz i spotted a couple of mistakes, will update now ...

**Comment by phlax** [comment]
updated, hopefully should be good to land

**Comment by phlax** [comment]
arg, still not quite right - debugging

**Comment by phlax** [comment]
seems to work correctly now

**Pull request merged**
