### PR TITLE
http/2: set max concurrent streams to a high value and pass it

### LINKED ISSUE #3076: BUG : MAX 100 HTTP2 streams limit between two Envoy Proxy
# description

When doing HTTP2 Streams (ex using gRPC), there is a limit of 100 Streams per TCP connexions between two Envoy proxy.

This situation shows up, for example, when you have 2 pods with Istio Sidecar (which is using Envoy) and talking to each other using gRPC.

Envoy creates ONE TCP connexion to the upstream server per CPU. In my tests with 2 CPUs --> 2 TCP connexions
Then Envoy will multiplex HTTP/2 gRPC calls into the two TCP cnx.
Here are the scenarios for N clients on servers with 1 CPU (so only one TCP cnx between Envoys) :

## one Envoy
N client --> 1TCP/1Stream * N --> Envoy --> 1TCP/N Stream --> server

Everything working as expected, can go up to 1024 Streams as per Envoy's default. If I try more, I do get some 503's, which is the expected behaviour

## two Envoy
N client --> 1TCP/1Stream * N --> Envoy --> 1TCP/N Stream --> Envoy --> 1TCP/N Stream --> server

When N is > 100, Envoy start queuing the other Streams. As these Streams are long live, they never end, blocking the communication.
What happen is : 
N client --> 1TCP/1Stream * N --> Envoy --> 1TCP/100 Stream --> Envoy Sidecar --> 1TCP/100 Stream --> server

Which means if N > 100, I lose connexions.

I can't find why the limit is 100, but I can reproduce this situation every time.
If I have 2 CPUs, I see 2 TCP cnx and 100 streams in each...

I opened an issue in Istio's repo : https://github.com/istio/istio/issues/4940

I also first commented to issue https://github.com/envoyproxy/envoy/issues/2941 which in fact is not related.

### PR DESCRIPTION
**Pull request by gumpt**
*Description*:
Always pass a max concurrent streams setting, instead of only passing if it isn't the default.
Set the default max concurrent streams for client connections to practically infinite.

*Risk Level*: Low

*Testing*: Added regression tests, `bazel test //test/...`

*Docs Changes*: N/A

Fixes #3076

### CODE REVIEW

**Comment by mattklein123** [comment]
I think this is the right fix, but can you look into adding a test in the http/2 codec_impl_test? https://github.com/envoyproxy/envoy/blob/master/test/common/http/http2/codec_impl_test.cc.

You should be able to make a test in which before your change, the 101 stream gets reset, but with your fix it does not and you can safely start/complete 101 streams.

cc @PiotrSikora since you had concerns about this being the issue (I'm positive it is FWIW).

**Comment by alyssawilk** [comment]
I was trying real hard to look the other way :-P
My preference was and is to default to something smaller even if it's a functional change.  I default to 100 as that's was the default back in the day, but unless I'm misunderstanding things, nghttp2 docs look like they back this up:

https://nghttp2.org/documentation/nghttp2_option_set_peer_max_concurrent_streams.html

Without specifying this option, before the local endpoint receives SETTINGS_MAX_CONCURRENT_STREAMS in SETTINGS frame from remote endpoint, SETTINGS_MAX_CONCURRENT_STREAMS is unlimited. This may cause problem if local endpoint submits lots of requests initially and sending them at once to the remote peer may lead to the rejection of some requests. Specifying this option to the sensible value, say 100, may avoid this kind of issue.

**Comment by PiotrSikora** [comment]
Yeah, I'll take a look at it later today.

**Comment by mattklein123** [comment]
@alyssawilk yes, nghttp2 defaults on the client side to 100 outbound streams, assuming that a settings frame will eventually come to override it. The issue here is that we never send the settings frame if the setting is the default (unlimited).

We can definitely change the default to something less than unlimited, but we still need to this fix on both sides to properly deal with the new default.

I'm less convinced the server side default should be 100, and if we make it so, we should explicitly change the Envoy code to reflect that and still send the settings frame in all cases IMO.

**Comment by gumpt** [comment]
Awesome!

I'll close this PR since it isn't needed.  The issue should remain open until the upstream fix is merged in.

**Comment by mattklein123** [comment]
Thank you @PiotrSikora. Agreed upstream fix LGTM. Can you track when that gets merged and update us? They are usually pretty fast about doing releases.

**Comment by PiotrSikora** [comment]
Yeah, I'll make sure to update nghttp2 as soon as there is new release.

**Pull request closed without merging**
