### PR TITLE
fix: catched all exceptions from cpp2sky to avoid possible runtime exception

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: fix: catched all exceptions from cpp2sky to avoid possible runtime exception
Additional Description:

Influence range: this bug was introduced by the #[14493](https://github.com/envoyproxy/envoy/pull/14493). So, all versions after 1.18 have this bug.
How to reproduce: enable skywalking tracer and send a request with illegal sw8 to envoy. The sw8 header should contains 8 fields and the first field should be legal and fouth field shoul be illegal. Then envoy will crash.

Risk Level: low.
Testing: unit.
Docs Changes: n/a.
Release Notes: added.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
/assign-from @envoyproxy/senior-maintainers 

seems that @lizan is too busy recently to handle this PR.

**Review by snowp — APPROVED** [review]
Seems reasonable to, thanks! Is the plan to eventually fix upstream?

**Comment by wbpcode** [comment]
> Seems reasonable to, thanks! Is the plan to eventually fix upstream?

It's in my TODO list

**Comment by wilsonwu** [comment]
This problem maybe as a vulnerability for cyber attack, suggest pick to nearly 3 release and publish hotfix.

**Pull request merged**
