### PR TITLE
http: Add metric for active outbound frames

### PR DESCRIPTION
**Pull request by deveshkandpal1224**
- Want to add the ability to detect current number of active outbound frames.
- While outbound_frame_flood counter helps us understand how many connections were destroyed but without knowing about what's the current value for active frames, its hard to tune max_outbound_frames.

Commit Message: Add metric for active outbound frames / control frames
Additional Description: Want to add the ability to detect current number of active outbound frames. While outbound_frame_flood counter helps us understand how many connections were destroyed but without knowing about what's the current value for active frames, its hard to tune max_outbound_frames.
Risk Level: Low
Testing: Unit Test added
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA] - Reopens / Fixes this stale PR -> https://github.com/envoyproxy/envoy/pull/24285
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by deveshkandpal1224** [comment]
@yanavlasov - this is the same PR that you were reviewing few months ago https://github.com/envoyproxy/envoy/pull/24285 but I did not get a chance earlier to work on the integration test enhancement and eventually got stale and closed. When you have a moment, could you please take a look at this ? Thanks!

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
