### PR TITLE
test: making assert required

### PR DESCRIPTION
**Pull request by alyssawilk**
follow-up on #15812 and https://github.com/envoyproxy/envoy-filter-example/pull/143

Risk Level: n/a (test only)
Testing: n/a
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Review by htuch — DISMISSED** [review]
LGTM, thanks!

**Comment by alyssawilk** [comment]
apologies for force push - screwed up local state somehow

**Comment by qinggniq** [comment]
@alyssawilk Hello, have you solved the ci flakes of `http_filter_integration_test` at ci `asan` or `tsan`? My pr #15803 is rely on it. I change `ci/filter_example_setup.sh`, set SHA to my commit at my fork repo, but it failed at `http_filter_integration_test`. After test, I found this [commit](https://github.com/envoyproxy/envoy-filter-example/commit/b602ea3007d62c1846c73aab864cbd6763f418f6) lead to the failure of test.

**Comment by alyssawilk** [comment]
@qinggniq sorry about that - ironically the new ASSERT was designed to catch timeouts like this, I just didn't realize that test was already broken!
https://github.com/envoyproxy/envoy-filter-example/pull/146 should hopefully fix but if not I'll get it sorted out somehow today, either by reverting the two changes or actually getting that test working as it was intended to!

**Comment by alyssawilk** [comment]
To confirm, CI is happy with this hash, sorry about the temporary breakage!

**Review by mattklein123 — APPROVED** [review]
Nice!

**Pull request merged**
