### PR TITLE
Build test - please ignore

### PR DESCRIPTION
**Pull request by ChrisPorterDevEx**
This is a bug bounty test which communicated with your team, please don't merge or accept it

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by ChrisPorterDevEx** [comment]
@keith I got permission to perform this tests, please stop to close my PRs.

**Comment by keith** [comment]
@ChrisPorterDevEx who on the envoy and bazel teams did you talk to about this

**Comment by ChrisPorterDevEx** [comment]
I discussed about it with Google security team (VRP), I'm a security contributor.
Please confirm it with your team.

**Comment by keith** [comment]
it's clear you're trying to exfiltrate env vars, you wouldn't have to do that to prove there was an issue.

**Comment by ChrisPorterDevEx** [comment]
This is what the security team asked as evidence for sensitive information.
They said that ping backs is not enough

**Comment by keith** [comment]
Feel free to have someone from the bazel team reach out to me confirming this info

**Comment by ChrisPorterDevEx** [comment]
I already sent a message to Google's security team to contact you

**Comment by phlax** [comment]
> I already sent a message to Google's security team to contact you

please stop testing until you have gotten confirmation from maintainers that its ok to continue

the maintainer email is `Envoy maintainers <envoy-maintainers@googlegroups.com>`

**Pull request closed without merging**
