### PR TITLE
mobile: Improve the gRPC initial metadata headers API for xDS

### PR DESCRIPTION
**Pull request by abeyad**
Initially, we introduced the setAuthenticationToken() method to the XdsBuilder to enable setting authentication tokens (e.g. API keys) on the xDS gRPC stream. However, authentication sometimes requires more than one header to be added to the gRPC stream (e.g. `x-android-package` and `x-android-cert` for API keys). Also, it's nice to have a general API for adding gRPC metadata headers, not just authentication-specific ones.

In this commit, we remove the setAuthenticationToken() API on XdsBuilder, and replace it with a addInitialStreamMetadata() API.

### CODE REVIEW

**Comment by abeyad** [comment]
@fredyw note, I don't use the proto APIs directly in the language builders, mainly b/c I wanted to keep API consistency with other similar functions, where we use addXXX to add some header value or some other key/value pair (e.g. addQuicHints).

**Review by RyanTheOptimist — APPROVED** [review]
Nice! This looks very clean.

**Review by fredyw — APPROVED** [review]
Thanks for working on this!

**Comment by fredyw** [comment]
> @fredyw note, I don't use the proto APIs directly in the language builders, mainly b/c I wanted to keep API consistency with other similar functions, where we use addXXX to add some header value or some other key/value pair (e.g. addQuicHints).

Makes sense. SGTM.

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
