### PR TITLE
[api] Fix header validations

### PR DESCRIPTION
**Pull request by asraa**
This enables "non-strict" header validations, that match the ones in place with Envoy's `ASSERT(valid())` code. The default `strict: true` checks checked for RFC-compliance, which may break previously valid configs.

Part of https://github.com/envoyproxy/envoy/issues/10318

Signed-off-by: Asra Ali <asraa@google.com>

### CODE REVIEW

**Comment by asraa** [comment]
@antoniovicente @htuch @hennna

**Comment by asraa** [comment]
I wanted to get this patch ready ASAP as a fix, but TODO to find the appropriate way to flip the strict validations. Thoughts? Deprecation and new wrapped message? Add hook (with flag to flip) to make strict in a newer version/log message about it `MessageUtility::Validate`?

**Comment by alyssawilk** [comment]
@htuch, are we comfortable with this from a stable API perspective?

**Comment by asraa** [comment]
> @htuch, are we comfortable with this from a stable API perspective?

The goal was to align them to stable API policy :) the checks here mimic those done in debug asserts, which provides the implied contract we don't expect to have `\r\n\0` in header names/values

**Comment by htuch** [comment]
@alyssawilk yeah, this basically undoes the API breaking change in #10093 by replacing it with something that was strongly implied in the API.

**Pull request merged**
