### PR TITLE
deps: Merge dependabot updates

### PR DESCRIPTION
**Pull request by phlax**
Commit Message: deps: Merge dependabot updates
Additional Description:

merge the update prs into one to ensure they work together and lessen commit noise

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
idna cant be updated until requests has been - see https://github.com/psf/requests/issues/5710 and https://github.com/psf/requests/pull/5711

**Review by mattklein123 — APPROVED** [review]
Thank you for all this cleanup!!! :)

**Pull request merged**
