### PR TITLE
macos/homebrew: bazelisk is in homebrew-core now

### PR DESCRIPTION
**Pull request by srenatus**
See https://formulae.brew.sh/formula/bazelisk and
https://github.com/bazelbuild/homebrew-tap/pull/98

----

This should have been a trivial README change. I've also changed the other occurance of `bazelbuild/tap/bazelisk`, so let's see what CI thinks about that.

### CODE REVIEW

**Comment by srenatus** [comment]
https://dev.azure.com/cncf/envoy/_build/results?buildId=50072&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=7d499b5d-1d92-5096-7919-3c7f8065da78 looks like osx is happy

**Comment by lizan** [comment]
@srenatus I doubt it works as intended, can you add a line `bazel verison` to the end of the script?

I'm seeing following log in the job:

```
2020-09-01T08:53:21.5298810Z 🍺  /usr/local/Cellar/bazelisk/1.6.1: 7 files, 7MB
2020-09-01T08:53:22.7984120Z Warning: Already linked: /usr/local/Cellar/bazelisk/1.6.1
2020-09-01T08:53:22.7990100Z To relink:
2020-09-01T08:53:22.7990840Z   brew unlink bazelisk && brew link bazelisk
```

And From the log https://dev.azure.com/cncf/envoy/_build/results?buildId=50072&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=5852bf5a-5a02-52f3-bee8-4fdc90cda9d0. I don't see bazelisk is downloading a Bazel binary.

The CI is happy because currently we're at latest version of Bazel 3.4.1, which is also installed in the [Azure pipelines macOS image](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md), but when there are a new version of bazel is released this would break.

**Comment by srenatus** [comment]
@lizan thanks for reviewing this! I'll add a line, and look into fixing the warning... 😃

**Comment by srenatus** [comment]
Running the call locally for comparison, I get this:
```console
$ brew link --overwrite bazelisk
Warning: Already linked: /usr/local/Cellar/bazelisk/1.6.1
To relink:
  brew unlink bazelisk && brew link bazelisk
```
So, the link has succeeded, I suppose; since it was already the case.  I've pushed a commit including `bazel version`. ⏳

**Comment by srenatus** [comment]
I can't see a change from my second commit... I'm unsure if the CI run has happened a second time... there shouldn't be _no output at all_ from `bazel version`. 😕

**Comment by lizan** [comment]
Seems it worked:

https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/50083/logs/30

```
2020-09-01T10:30:46.5205120Z Bazelisk version: 1.6.1
2020-09-01T10:30:46.6810130Z Starting local Bazel server and connecting to it...
2020-09-01T10:30:50.5574010Z Build label: 3.4.1
2020-09-01T10:30:50.5576560Z Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
2020-09-01T10:30:50.5578010Z Build time: Tue Jul 14 06:32:14 2020 (1594708334)
2020-09-01T10:30:50.5578420Z Build timestamp: 1594708334
2020-09-01T10:30:50.5578880Z Build timestamp as int: 1594708334
```

**Review by lizan — APPROVED** [review]

**Pull request merged**
