### PR TITLE
Upgrade version of googletest used by Envoy

### PR DESCRIPTION
**Pull request by curiouserrandy**
Description: Upgrade version of googletest used by Envoy
Risk Level: Low (test only, stable API)
Testing: Run all envoy tests.
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by curiouserrandy** [comment]
Current status: Waiting on review of https://github.com/envoyproxy/envoy-filter-example/pull/92, which is required for the tests currently failing above to pass.

**Comment by curiouserrandy** [comment]
If anyone can give me a pointer as to how to get the uploaded build artifact for the "release" test failure, I'd be grateful; I can't reproduce that failure locally.  The "Uploading artifacts" section of the CircleCI build result @ https://circleci.com/gh/envoyproxy/envoy/242223?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link says 

Uploading /build/envoy/generated/failed-testlogs/test/integration/integration_admin_test/test.log (7.6 kB): DONE

but the CircleCI documentation suggests I need to be running a CircleCI application to create a personal token to download that artifact.

**Comment by mattklein123** [comment]
You should be able to go to the bottom of the failing job and click the link called "download full log" (or something like that).

/wait

**Comment by curiouserrandy** [comment]
Are you referring to the link "Download the full output as a file." at the end of the step "ci/do_circle_ci.sh bazel.release"?   That only gets the text of the output displayed in the browser, and it's only really useful when the output is too long to fit in the browser.  Bazel saved the output of that particular failing test into a file on the CircleCI server (/build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-opt/testlogs/test/integration/integration_admin_test/test.log) and CircleCI uploaded that somewhere at the end of the run (see the "Uploading Artifacts" step).  But that file isn't accessible through that link.  (My apologies if I misinterpreted what you were talking about.)

Trying a retest in case it's flake, also to get the other two filter example tests to pass.

/retest

**Comment by mattklein123** [comment]
yeah that's what I was referring to. AFAIK we don't upload all the individual logs, but I thought they are all printed out in the output. @jmarantz do you know?

**Comment by jmarantz** [comment]
I too feel like there's something missing in what we can see in the CircleCI logs. Most of the time though, once I download the log and search around it with Emacs, I can find the smoking gun. Randy -- come find me if you want help poking around logs.

I wish we could see all the individual log artifacts though; my hope is that would make things easier, but I don't know for sure.

Mostly I try to repro locally when I can.

**Comment by mattklein123** [comment]
FWIW we should be able to alter the CI jobs to upload whatever logs we want into artifacts, someone just needs to work on it.

**Comment by curiouserrandy** [comment]
The problem that I wanted that artifact log for appears to have been flake, so yay for not needing to worry about it :-}.  Still blocked on the other two failures, which I thought I would have fixed with envoyproxy/envoy-filter-example#92 (see above for link).  Looking at envoy/ci/build_setup.sh it looks like that directory is cloned if it doesn't already exist.  Does anyone know if CircleCI re-uses build areas for individual PRs?

Retesting in case it's just a race with the CircleCI build system.

/retest

**Pull request merged**
