### PR TITLE
tooling: Improve runner/checker log/error handling

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:  tooling: Colorize and improve formatting for runner/checker logs
Additional Description:

This will colorize warnings/errors/jobs appropriately for any runners/checkers

It also improves error and log handling more generally

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
coverage is here https://storage.googleapis.com/envoy-pr/17388/tooling/index.html

**Comment by moderation** [comment]
/lgtm deps

@htuch should review from a Python point of view

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
