### PR TITLE
Plumb ServerFactoryContext into header validator factory

### PR DESCRIPTION
**Pull request by yanavlasov**
Additional Description:
This PR adds the `ServerFactoryContext& TransportSocketFactoryContext::getServerFactoryContext()` method and modifies the `HeaderValidatorFactoryConfig::createFromProto(...)` method parameter to `ServerFactoryContext&`
This is needed to access runtime snapshot in the UHV factory in followup PRs.

Risk Level: Low
Testing: Unit Tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

/assign-from @envoyproxy/senior-maintainers

**Comment by yanavlasov** [comment]
@zuercher for non Google review

**Review by zuercher — APPROVED** [review]
lgtm

**Pull request merged**
