### PR TITLE
router: remove unused internal redirects member variable

### PR DESCRIPTION
**Pull request by derekargueta**
Commit Message: remove unused internal redirects member variable attempting_internal_redirect_with_complete_stream_.
Additional Description: The code comment that goes with it is also stale.
Risk Level: low
Testing: existing
Docs Changes: n/a
Release Notes: n/a, no functionality change
Platform Specific Features: n/a

### CODE REVIEW

**Review by junr03 — COMMENTED** [review]
lgtm, seems like format is failing?

**Comment by derekargueta** [comment]
hmm, looks like it keeps failing on
```
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/93/934ad7f43563585d8a4ace7ee527542d6c3ee112ec841fa20abc9b828b2755b4/data?verify=1630479832-l4TTmbAIZ10JwWahE6jgw%2FtDBs0%3D: dial tcp 104.18.123.25:443: i/o timeout
```
I'll try one more kick

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
