### PR TITLE
quiche: fix macOS build

### PR DESCRIPTION
**Pull request by jpsim**
The patch from #19360 and other similar implicit type cast fixes have now landed upstream in quiche, so this PR bumps quiche to b0fda33 and deletes the local patch as it is no longer needed.

Changes: https://github.com/google/quiche/compare/c8c21d0...b0fda33

### CODE REVIEW

**Comment by moderation** [comment]
Any update on the upstream fix https://github.com/envoyproxy/envoy/pull/19360#issuecomment-1002247908 @birenroy @RyanTheOptimist ?

**Comment by jpsim** [comment]
I'm happy to make a PR with this patch over at https://github.com/google/quiche as well but I'm not a googler so I don't know if that would be accepted given it won't come from the google-internal version of the repo.

**Comment by jpsim** [comment]
Opened a PR with the patch in case it's helpful: https://github.com/google/quiche/pull/12

**Comment by moderation** [comment]
Always good to remove patches. Thanks

/lgtm deps

**Review by RyanTheOptimist — APPROVED** [review]
Thanks for doing this!

**Comment by RyanTheOptimist** [comment]
@jpsim, shall I go ahead and merge this?

**Comment by jpsim** [comment]
My pleasure. Can someone with merge access please merge this PR?

**Pull request merged**
