### PR TITLE
fix local_ratelimit example readme doc

### PR DESCRIPTION
**Pull request by StarryVae**
Signed-off-by: wangkai19 <wangkai19@corp.netease.com>

Commit Message: fix local_ratelimit example readme doc
Additional Description: N/A
Risk Level: low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by StarryVae** [comment]
cc @phlax

**Review by phlax — APPROVED** [review]
lgtm, thanks @StarryVae

**Pull request merged**
