### PR TITLE
quic: fixing hostname consistency

### PR DESCRIPTION
**Pull request by alyssawilk**
Fixing hostname issues for upstream HTTP/3.

Consistently using correct SNI (configured or auto) as server ID and alt-svc origin everywhere.
This also unfortunately required tweaking a LOT of integration tests, as it meant the hostname for SNI was pulled from host headers (as we auto-sni by default in integrationt tests) and HTTP/3 validates that hostname against the certs (test certs are for "foo.lyft.com" but default host for request headers was "host")

Risk Level: Low (uptream HTTP/3)
Testing: fixed a lot of integration tests.
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by alyssawilk** [comment]
@RyanTheOptimist opened this as draft to check CI and I'm working on merge conflicts, but if you can take a look at the test changes and lmk if you want them split into their own Pr, that'd be great.

**Comment by alyssawilk** [comment]
(not that they're super major, but I tend to not like mixing functional changes and large test changes, and the test changes are borderline large)

**Review by RyanTheOptimist — COMMENTED** [review]
I think I'd be inclined to split the test changes out into their own PR. As you say, they are quite big. But I could live with them here in this PR.

**Review by RyanTheOptimist — APPROVED** [review]
Looks great!

**Comment by alyssawilk** [comment]
@ggreenway ping?

**Review by ggreenway — APPROVED** [review]
LGTM, but CI is failing

/wait

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
