### PR TITLE
remove expired runtime flag: envoy.reloadable_features.validate_detailed_override_host_statuses

### LINKED ISSUE #29103: envoy_reloadable_features_validate_detailed_override_host_statuses deprecation
Your change #24094 (upstream: verify all statuses of the override host) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: remove expired runtime flag: envoy.reloadable_features.validate_detailed_override_host_statuses
Additional Description:

To close #29103.

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by alyssawilk — APPROVED** [review]
baffled as to why this doesn't need main merge for the other flag update but if it works it works :-)

**Comment by TAOXUY** [comment]
Hi @wbpcode , removing this flag makes this [flow](https://github.com/envoyproxy/envoy/issues/28626#issuecomment-1763703572)(call route() in log() time when localReply is called before and route isn't inited) won't work anymore. Could you shed some light on how to this issue?

**Comment by wbpcode** [comment]
@TAOXUY are you sure that it's this patch that effect your flow?

This is only for a upstream host statues validation.

**Comment by wbpcode** [comment]
We do removed a related flag in the #30444. But it only effect the Envoy 1.29+ (note the 1.29 still in the development phase). And the bug that you noticed in the #28626 should has been fixed by #28875. That fix patch is available in the Envoy 1.28.

**Comment by TAOXUY** [comment]
Thanks for the quick response! We will check after upgrading to 1.28.

**Comment by TAOXUY** [comment]
> We do removed a related flag in the #30444. But it only effects the Envoy 1.29+ (note the 1.29 still in the development phase). And the bug that you noticed in the #28626 should has been fixed by #28875. That fix patch is already available in the Envoy 1.28.

**Comment by wbpcode** [comment]
Then any new reporting would be appreciated. 😄

**Pull request merged**
