### PR TITLE
Windows: Add note regarding the usage of `./ci/run_envoy_docker`

### PR DESCRIPTION
**Pull request by davinci26**
Signed-off-by:  Sotiris Nanopoulos <sonanopo@,microsoft.com>

Windows Build: Add note regarding the usage of `./ci/run_envoy_docker.sh './ci/windows_ci_steps.sh'`

### CODE REVIEW

**Comment by davinci26** [comment]
@wrowe as discussed offline

cc @envoyproxy/windows-dev

**Comment by sunjayBhatia** [comment]
Probably also worth eventually emulating the Linux helper script pattern or maybe even merging the two

**Comment by davinci26** [comment]
We already have https://github.com/envoyproxy/envoy/issues/15819

**Review by wrowe — APPROVED** [review]
LGTM, thanks for creating an issue for follow-up.

**Comment by davinci26** [comment]
@envoyproxy/senior-maintainers can someone merge this small doc change?

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
