### PR TITLE
quiche: support connection ID longer than 8 bytes with multiple worker threads

### LINKED ISSUE #15988: QUIC issues with concurrency > 1
Example configs from https://github.com/envoyproxy/envoy/pull/15987 load, but downstream doesn't work with concurrency > 1

We should either fix the bug causing QUIC to fail with this set up, or reject the config if we know something isn't set up properly.

cc @danzh2010

### PR DESCRIPTION
**Pull request by danzh2010**
Signed-off-by: Dan Zhang <danzh@google.com>

Commit Message: fix an issue where CID longer than 8 bytes is replaced by a hashed 8-byte CID which isn't compatible with existing BPF filter which requires stable first 4-byte in CID.

Testing: added integration tests for 9-byte CID
Fixes #15988

### CODE REVIEW

**Comment by ggreenway** [comment]
How is a longer-than-8-byte CID generated in the first place? Aren't the CIDs generated by quiche?

**Comment by alyssawilk** [comment]
Awesome!  So glad this is tracked down :-)

@moderation can you confirm this fixes your set up for concurrency > 1?

**Review by alyssawilk — APPROVED** [review]

**Comment by danzh2010** [comment]
> How is a longer-than-8-byte CID generated in the first place? Aren't the CIDs generated by quiche?

Google QUICHE client uses 8-byte CID, which is why we didn't catch this issue earlier. But other implementations, i.e. Cloudflare QUICHE,  use longer CID to start with.

**Comment by ggreenway** [comment]
> > How is a longer-than-8-byte CID generated in the first place? Aren't the CIDs generated by quiche?
> 
> Google QUICHE client uses 8-byte CID, which is why we didn't catch this issue earlier. But other implementations, i.e. Cloudflare QUICHE, use longer CID to start with.

Oh, so this is the peer's ID? How is it valid to truncate it (or hash it)? I read through https://quicwg.org/base-drafts/rfc9000.html#name-connection-id and didn't see anything about modifying the peer's CID. 

Is it possible that by truncating, there could be duplicates, eg the peer uses the same first 8 bytes of CID?

**Comment by ggreenway** [comment]
Nevermind, this is all coming back to me now. Described here: https://quicwg.org/base-drafts/rfc9000.html#name-negotiating-connection-ids

Given that envoy only looks at the first 4 bytes in the BPF to steer, would it be safer to hash all bytes beyond the first 4 into a 4-byte hash for the last 4 bytes of the CID?

**Comment by moderation** [comment]
With @alyssawilk help I can confirm that concurrency > 1 is now working in my environment! Woohoo

**Comment by alyssawilk** [comment]
Awesome!  Thanks so much for checking!

**Comment by danzh2010** [comment]
> Nevermind, this is all coming back to me now. Described here: https://quicwg.org/base-drafts/rfc9000.html#name-negotiating-connection-ids
> 
> Given that envoy only looks at the first 4 bytes in the BPF to steer, would it be safer to hash all bytes beyond the first 4 into a 4-byte hash for the last 4 bytes of the CID?

Done

**Comment by ggreenway** [comment]
Thanks for fixing this! CI is failing with `ERROR: ./source/common/quic/envoy_quic_dispatcher.cc:96: Don't call memcpy() directly; use safeMemcpy, safeMemcpyUnsafeSrc, safeMemcpyUnsafeDst or MemBlockBuilder instead.`.

**Comment by danzh2010** [comment]
Ping?

**Review by ggreenway — APPROVED** [review]
LGTM. Thanks!

**Comment by moderation** [comment]
I've been trying to look for ways to verify that BPF is being used. I've installed the `bcc` tools and can run `bps` https://github.com/iovisor/bcc#bpf-introspection which is described as `ps` for BPF programs. With Envoy running either as `sudo` or with `sudo setcap cap_bpf+ep envoy` I don't see anything in the `bps` or `bpflist` output. Is this expected? Is there another way to verify that BPF is being used? /cc @ggreenway @alyssawilk @danzh2010

**Comment by moderation** [comment]
Yes Envoy starts with multiple workers. I'm testing on 6 core 12 thread Linux machine and on startup I get 12:
```
[2021-05-07 10:20:11.016][403778][info][quic] [bazel-out/k8-opt/bin/external/com_googlesource_quiche/quiche/quic/core/batch_writer/quic_gso_batch_writer.cc:36] Release time is not enabled.
```
And on shutdown 12:
```
[2021-05-07 10:20:14.979][403772][info][quic] [source/common/quic/active_quic_listener.cc:107] Quic listener listener_udp shutdown.
```
So I _think_ it is working OK. However I thought in order for BPF filters to work either `setcap` or `sudo` would be required. As I don't see any log change either with or without these settings on the binary I thinking that they are not required and Envoy is leveraging an existing BPF filter?

I do get the warning when running on MacOS as expected.

**Pull request merged**
