### PR TITLE
Update jwt_verify_lib to latest commit

### PR DESCRIPTION
**Pull request by bochengchu**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by bochengchu** [comment]
cc @qiwzhang

**Comment by moderation** [comment]
Updates look OK but DCO needs to be fixed first

**Comment by bochengchu** [comment]
> Updates look OK but DCO needs to be fixed first

Fixed.

**Review by phlax — APPROVED** [review]
lgtm, thanks @bochengchu

**Pull request merged**
