### PR TITLE
remove unused function declaration

### PR DESCRIPTION
**Pull request by delphisfang**
Commit Message: Remove unused funtion declaration of setupTracking( )
Additional Description:
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by KBaichoo — COMMENTED** [review]
Thank you for cleaning this up. CI failure looks real.

/wait

**Comment by delphisfang** [comment]
> Thank you for cleaning this up. CI failure looks real.
> 
> /wait

@KBaichoo I am a little bit confused of why CI fails. This function is not used already...

**Comment by KBaichoo** [comment]
@delphisfang I think the issue is now the field is unused:

```
In file included from source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.cc:1:
./source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.h:63:18: error: private field 'context_' is not used [-Werror,-Wunused-private-field]
  Grpc::Context& context_;
```

**Comment by delphisfang** [comment]
> @delphisfang I think the issue is now the field is unused:
> 
> ```
> In file included from source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.cc:1:
> ./source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.h:63:18: error: private field 'context_' is not used [-Werror,-Wunused-private-field]
>   Grpc::Context& context_;
> ```

@KBaichoo Yes, Like you said. I have fixed it now.

**Comment by KBaichoo** [comment]
Thank you for fixing that @delphisfang .

I think the commit wasn't signed off properly (DCO is failing). See https://github.com/envoyproxy/envoy/blob/b8c62e7bc23b39752a608781225b650f6beae696/CONTRIBUTING.md#fixing-dco on how to fix that error.

**Comment by delphisfang** [comment]
> Thank you for fixing that @delphisfang .
> 
> I think the commit wasn't signed off properly (DCO is failing). See https://github.com/envoyproxy/envoy/blob/b8c62e7bc23b39752a608781225b650f6beae696/CONTRIBUTING.md#fixing-dco on how to fix that error.

Thanks for pointing out this. I am trying to figure out how to solve this

**Comment by delphisfang** [comment]
I've tried to use 'git rebase' to solve DCO problems, but it seems that it involves commits of other contributors. In order not to mess up the repository, I've closed this PR without merging already. Many thanks for your review. @KBaichoo I would open another clean PR maybe. @KBaichoo

**Pull request closed without merging**
