### PR TITLE
add StarryVae to go extension code owner

### PR DESCRIPTION
**Pull request by StarryVae**
Commit Message: add StarryVae to go extension code owner
Additional Description: N/A
Risk Level: low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by StarryVae** [comment]
@doujiang24 could i apply to become a code owner of Go Filter? thanks. ❤️ cc @wbpcode @mattklein123

**Review by doujiang24 — APPROVED** [review]
Cool! Welcome & enjoying!

**Comment by StarryVae** [comment]
thanks!

**Review by wbpcode — APPROVED** [review]
LGTM.

**Pull request merged**
