### PR TITLE
build: Move bazel/utils.bzl into api/bazel

### PR DESCRIPTION
**Pull request by pugmajere**
Commit Message:
The api/... subtree depends on utils.bzl, but it is stored in //bazel, not //api/bazel.  When the api sub-tree is exported as "data-plane-api", the resulting repository is not buildable.

This attempts to fix that by changing the canonical location of utils.bzl and updating the references to it.

This seems to have been broken by c74b352b29e3042ab35893e83d0e9b56ba67989f on 2021-09-15.

Additional Description:
Risk Level: low
Testing: built Envoy with this change
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA] c74b352b29e3042ab35893e83d0e9b56ba67989f
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@pugmajere im not sure this is as easy as you suggest or i think i would have done it that way originally

im aware that the code here is not ideally set up, the underlying problem being that more than workspace are sharing a repo - the solution i had in mind was to move this macro to a separate tooling repo that we have

**Comment by phlax** [comment]
seems to have worked

**Comment by pugmajere** [comment]
I suppose the alternative approach would be to just copy it, instead of moving it, as a short-term fix that unbreaks the data-plane-api mirror repo, but that felt like it was just making the whole thing even more messy.

**Comment by phlax** [comment]
> I suppose the alternative approach would be to just copy it, instead of moving it

lets try and avoid doing that

if CI works and is happy with moving, then im ok with that for now, just would prefer the cleaner solution of moving it out of the repo longer term

**Comment by pugmajere** [comment]
The things that failed compile, so I'm not sure how this change could be making them fail. Also, one of them passed locally.  Are these, possibly, somewhat flaky tests?

**Comment by phlax** [comment]
> flaky tests?

sadly, yes

/retest

**Comment by moderation** [comment]
Looks like coverage failure is real?

```
2023-04-21T00:40:41.5902212Z [  FAILED  ] 1 test, listed below:
2023-04-21T00:40:41.5904030Z [  FAILED  ] StreamingProtocols/StreamingIntegrationTest.PostAndProcessStreamedRequestBodyPartially/IPv4_EnvoyGrpc_NoDeferredProcessing, where GetParam() = ((4-byte object <00-00 00-00>, 4-byte object <00-00 00-00>), false)
2023-04-21T00:40:41.5905172Z 
```

**Comment by phlax** [comment]
> Looks like coverage failure is real?

seems unrelated - it failed on 2 ext_proc tests on first run, and one on second - this test is endemically flakey tbh

**Comment by pugmajere** [comment]
Looks like everything passed on the retry, thankfully.

**Review by phlax — APPROVED** [review]
lgtm, thanks @pugmajere

**Pull request merged**
