### PR TITLE
ci: making sure we test building sans quic

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: n/a (ci only)
Testing: n/a
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by alyssawilk** [comment]
ah, I can't test inline because the compile time build is gated on other builds.  boo.

**Comment by alyssawilk** [comment]
cc @moderation this should futureproof - I'll double check with a follow-up "bad" PR

**Comment by moderation** [comment]
Thanks @alyssawilk. I've tried a bunch of different ways to build with `--//bazel:http3=False` but am still blocked by https://github.com/envoyproxy/envoy/pull/15635 as no matter what the build tries to compile QUIC / h3. (This is on Red Hat 8 with Clang 10).

**Comment by alyssawilk** [comment]
So that's weird.
Locally if I add gibberish (things that simply won't compile) I can't build the integration tests, but --//bazel:http3=False works.
What are you building that isn't "working" with --//bazel:http3=False" so I can try to repro?

**Comment by mattklein123** [comment]
Superseded by https://github.com/envoyproxy/envoy/pull/15720

**Pull request closed without merging**
