### PR TITLE
rk: improve azp retry

### LINKED ISSUE #13725: repokitteh /retest seems to be broken
### description

/retest seems to no longer work, instead gives the message

```
Cannot retry non-completed check: envoy-presubmit, please wait.
```

### PR DESCRIPTION
**Pull request by lizan**
- use subcheck IDs (which is required check)
- retrying partially failed pipelines

Fixes #13725

Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Review by phlax — APPROVED** [review]
i cant test, but visual review of the code lgtm

**Review by htuch — APPROVED** [review]

**Pull request merged**
