### PR TITLE
build: update bazel to latest rolling release

### PR DESCRIPTION
**Pull request by jpsim**
Recent changes to rules_apple require this commit: https://github.com/bazelbuild/bazel/commit/68f29c67098cedbfaa3ef011eef4df661860ac36

So bumping to the latest rolling release of bazel now to unblock further downstream updates.

Risk Level: Low
Testing: CI
Docs Changes: N/A
Release Notes: N/A

Signed-off-by: JP Simard <jp@jpsim.com>

### CODE REVIEW

**Review by keith — APPROVED** [review]
Thanks I have been meaning to do this. Let's see what CI says. We might have to bump some rules at the same time

**Comment by phlax** [comment]
related #22277

**Comment by keith** [comment]
great, i think we should be pretty safe on rules_apple since i don't think we hit much of that code here, we just pull it transitively for grpc

**Pull request merged**
