### PR TITLE
grpc_transcoder: fix a bug with http2 when request body is Http.Body

### PR DESCRIPTION
**Pull request by qiwzhang**
Signed-off-by: Wayne Zhang <qiwzhang@google.com>

To fix: https://github.com/envoyproxy/envoy/issues/16629

When using http2, and request body has google.api.HttpBody, the size is < 16KB, it will cause EOF.

Risk Level: Low
Testing:  unit-tested
Docs Changes:
Release Notes: Yes
Platform Specific Features:
[

### CODE REVIEW

**Comment by lizan** [comment]
Can you check CI?

**Review by lizan — DISMISSED** [review]
can you resolve conflicts for 1.24.0 release?

**Review by lizan — APPROVED** [review]

**Comment by ravi-gopalan-1972** [comment]
@lizan, is this part of the release v1.24.0? We are currently hitting this issue in our environments and can we get this fix rolled out and one related question, when istio cuts a release, do they update envoy release as well? Please let me know. Thanks

**Comment by qiwzhang** [comment]
Unfortunately, this fix did not get into v1.24.0.

**Comment by ravi-gopalan-1972** [comment]
@lizan, is there a release planned in the near future in which the fix for this issue is included? Please let me know. Thanks

**Pull request merged**
