### PR TITLE
repo: Dev `1.23.2`

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @ggreenway

**Review by ggreenway — DISMISSED** [review]

**Comment by ggreenway** [comment]
@phlax I think we need to backport #22935 to make CI pass. But we have to open the branch first. Do we need to force-merge?

**Comment by phlax** [comment]
ive cherry-picked the backport to here - hopefully we can land without needing to force

**Comment by phlax** [comment]
so it looks like the updated cel is incompatible with the protobuf version here https://dev.azure.com/cncf/envoy/_build/results?buildId=116093&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=6b0ace90-28b2-51d9-2951-b1fd35e67dec&l=131

```console
external/com_google_cel_cpp/extensions/protobuf/memory_manager.cc:26:18: error: 'AllocateAligned' is a private member of 'google::protobuf::Arena'
  return arena_->AllocateAligned(size, align);
                 ^
```

**Comment by LithiumSR** [comment]
> so it looks like the updated cel is incompatible with the protobuf version here https://dev.azure.com/cncf/envoy/_build/results?buildId=116093&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=6b0ace90-28b2-51d9-2951-b1fd35e67dec&l=131
> 
> ```
> external/com_google_cel_cpp/extensions/protobuf/memory_manager.cc:26:18: error: 'AllocateAligned' is a private member of 'google::protobuf::Arena'
>   return arena_->AllocateAligned(size, align);
>                  ^
> ```

Yes, I think this one would be needed too: https://github.com/envoyproxy/envoy/pull/21336/
Maybe it is worth waiting for the antlr project to fix the tags

**Comment by phlax** [comment]
> Yes, I think this one would be needed too: https://github.com/envoyproxy/envoy/pull/21336

i think we dont want to change protobuf version in an existing release branch if possible

**Comment by phlax** [comment]
>  Maybe it is worth waiting for the antlr project to fix the tags

yep, it seems that way

@kyessenov do you know if the plan is to retag the existing antlr tags ?

it seems like upgrade is not an (easy) option for our release branches

im guessing this will affect other release branches also

**Comment by phlax** [comment]
nm - i see https://github.com/antlr/antlr4/issues/3854

**Comment by phlax** [comment]
it seems the tag has been restored

/retest

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
