### PR TITLE
build: remove protobuf_link_hacks.

### PR DESCRIPTION
**Pull request by htuch**
It's unclear if these are still needed given a number of protobuf library bumps, changes to the API
build system and https://github.com/protocolbuffers/protobuf/issues/4221. Removing the target
doesn't cause any tests to fail.

Risk level: Low
Testing: bazel test //test/... This PR merging is conditional on the Envoy Mobile team confirming
  that there is no breakage.

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

**Comment by htuch** [comment]
@junr03 and @goaway kindly offered to test this out in Envoy Mobile land, so will wait to hear back.

**Comment by junr03** [comment]
I am building and running, will report back when done.

**Comment by junr03** [comment]
update: Android ran fine. iOS crashes with the following assertion failure:

```
2019-12-03 13:06:05.294 app[10203:2561110] Starting Envoy...
2019-12-03 13:06:05.331 app[10203:2561110] Started Envoy, beginning requests...
2019-12-03 13:06:05.350 app[10203:2561110] Finished launching!
[2019-12-03 13:06:05.410][2561517][critical][assert] [external/envoy/source/server/proto_descriptors.cc:44] assert failure: Protobuf::DescriptorPool::generated_pool()->FindMethodByName(method) != nullptr. Details: Unable to find method descriptor for envoy.service.discovery.v2.AggregatedDiscoveryService.StreamAggregatedResources
```

**Comment by htuch** [comment]
@junr03 looking at https://github.com/envoyproxy/protoc-gen-validate/blob/master/bazel/pgv_proto_library.bzl#L74, which is where the C++ proto library is declared for our API deps, it seems we are setting `alwaylinks` as expected.

**Comment by htuch** [comment]
@junr03 if I look at `cat bazel-out/k8-fastbuild/bin/source/exe/envoy-static-2.params` (as per the link command line), I get:
```
...
-Wl,-whole-archive
bazel-out/k8-fastbuild/bin/external/envoy_api/envoy/service/discovery/v2/_objs/pkg_cc_proto/ads.pb.pic.o
-Wl,-no-whole-archive
...
```
Do you see something similar when you search for `ads.pb` on iOS builds?

```

**Comment by junr03** [comment]
not stale. Waiting on @goaway in offline conversation with @htuch

**Comment by junr03** [comment]
I was working on a stale branch that did not include @htuch merge from last night (https://github.com/envoyproxy/envoy/pull/9526/files#diff-2c3e3c94185709f57afc11c488277313R3). I spent some time fixing before realizing that @htuch had already merged. It would be ideal if we no longer needed this.

@goaway do you mind taking a look at this and seeing if we can get to a place where we don't need the link hack?

**Pull request closed without merging**
