### PR TITLE
golang http: fix memory leaking.

### PR DESCRIPTION
**Pull request by doujiang24**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by spacewander — APPROVED** [review]
Does the network filter in examples/golang-network/simple/filter.go also have circular reference? (DownstreamFilter -> UpstreamFilter -> DownstreamFilter)

**Comment by doujiang24** [comment]
yep, nice catch, there is a circular reference too.
but it may need to be fixed in another way, seems not as easy as the HTTP filter.
So, created issue #30210  for it.

For this PR, it's good to merge, thanks~

**Comment by doujiang24** [comment]
Thanks Lance's reporting from:
https://envoyproxy.slack.com/archives/C04QNSXC7U0/p1697144047233609?thread_ts=1697144047.233609&cid=C04QNSXC7U0

**Review by phlax — APPROVED** [review]
lgtm, thanks @doujiang24

**Pull request merged**
