### PR TITLE
deps: update abseil

### PR DESCRIPTION
**Pull request by kyessenov**
Commit Message: update abseil to head
Additional Description: there's a problem with cel-cpp using an internal macro from abseil. To decouple absl from cel-cpp update, we have to patch cel-cpp temporarily.
Risk Level: low
Testing: regression

### CODE REVIEW

**Comment by phlax** [comment]
related #27303

**Review by mattklein123 — DISMISSED** [review]

**Comment by yanavlasov** [comment]
@kyessenov windows build error seems legit. Not sure why it was not failing before. https://dev.azure.com/cncf/envoy/_build/results?buildId=137572&view=logs&j=b840a642-5ff3-5357-2e4b-e06e40b0cffd&t=67965174-5100-5631-9dc0-68b9f0aacb53&l=898

A cast should solve it.

**Pull request merged**
