### PR TITLE
xds-failover: disabling flaky and potential flaky tests

### PR DESCRIPTION
**Pull request by adisuissa**
Commit Message: xds-failover: disabling flaky and potential flaky tests
Additional Description:
Temporarily disabling some of the xds-failover integration tests, as they are flaky.

Risk Level: low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by adisuissa** [comment]
@htuch I'm disabling most of the integration tests as I'm not sure which one are flaky.

**Review by htuch — APPROVED** [review]
Thanks

**Comment by htuch** [comment]
@adisuissa you'll need to add a coverage exception, coverage tests failing.

**Review by phlax — APPROVED** [review]
lgtm, thanks @adisuissa

**Pull request merged**
