### PR TITLE
Stop lowercase thrift THeader key

### PR DESCRIPTION
**Pull request by fishy**
Fixes https://github.com/envoyproxy/envoy/issues/20595.

Signed-off-by: Yuxuan 'fishy' Wang <yuxuan.wang@reddit.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by fishy** [comment]
This fix attempt does not work because thrift filter shares the same Metadata type with other transports (e.g. http), which only allows `LowerCaseString` as the key.

The proper fix probably needs to change how `LowerCaseString` is implemented, that it needs to store the original string, but allows output either lower case version or the original version (so http and co. uses lower case version when encoding while thrift uses the original version when encoding). I'll leave that to someone more familiar with the code.

**Comment by fishy** [comment]
The failed test passed on my local machine:
```
$ bazel test --local_cpu_resources=HOST_CPUS-1 //test/extensions/filters/network/thrift_proxy:integration_test
Starting local Bazel server and connecting to it...
INFO: Analyzed target //test/extensions/filters/network/thrift_proxy:integration_test (426 packages loaded, 19951 targets configured).
INFO: Found 1 test target...
INFO: Deleting stale sandbox base /home/fishy/.cache/bazel/_bazel_fishy/8c83130887a2b94202b865b9b6aa6979/sandbox
Target //test/extensions/filters/network/thrift_proxy:integration_test up-to-date:
  bazel-bin/test/extensions/filters/network/thrift_proxy/integration_test
INFO: Elapsed time: 680.928s, Critical Path: 579.50s
INFO: 80 processes: 1 internal, 79 linux-sandbox.
INFO: Build completed successfully, 80 total actions
//test/extensions/filters/network/thrift_proxy:integration_test          PASSED in 21.7s
  Stats over 4 runs: max = 21.7s, min = 21.3s, avg = 21.5s, dev = 0.2s

Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 80 total actions
```

and I cannot see the full log in the CI so I have no idea why it failed in the CI.

**Review by zuercher — COMMENTED** [review]
I think this is ok. I have one small request in the tests.

I will also point out that this sort of abuses the Http::HeaderMap, since it's designed for all-lowercase keys. I think it's probably alright, but might cause problems in the future.

**Comment by zuercher** [comment]
Adding @rgs1 for his input.

We'll also want to figure out why that integration test fails on Windows.

**Review by rgs1 — CHANGES_REQUESTED** [review]
Thanks for working on this. A few thoughts/asks:

* can we add a changelog entry (in `docs/root/version_history/current.rst`)
* what do you think of keeping the old code and gating your new code with a config option? The reason I ask is since technically this would change the assumption for current deployments (not even sure if would break our deployment cc: @fishcakez )
* can you also add something in `docs/root/configuration/listeners/network_filters/thrift_proxy_filter.rst` ?

**Comment by fishy** [comment]
> I think this is ok. I have one small request in the tests.
> 
> I will also point out that this sort of abuses the Http::HeaderMap, since it's designed for all-lowercase keys. I think it's probably alright, but might cause problems in the future.

I think long term someone probably need to refactor the code to completely decouple them as thrift headers and http headers have different requirements. But that's out of my expertise so I'll just leave that to people more familiar with the code. This is a short term fix on the spec violation bug.

**Comment by fishy** [comment]
@rgs1 I can update the doc. but regarding the config gate:

1. The current behavior is a bug that violates the spec
2. I don't really know how to do that in envoy code
3. If a thrift server actually relies on the envoy proxy to lowercase the header keys, that means a direct connection (client to server without envoy) will also break. That sounds like a bug on the server and/or client to me

**Comment by fishy** [comment]
@rgs1 I updated`docs/root/version_history/current.rst`. `docs/root/configuration/listeners/network_filters/thrift_proxy_filter.rst` doesn't really mention it converts key to lower case right now so I'm not sure what to add there when we stop doing that.

**Comment by fishcakez** [comment]
> 3\. If a thrift server actually relies on the envoy proxy to lowercase the header keys, that means a direct connection (client to server without envoy) will also break. That sounds like a bug on the server and/or client to me

I couldn't say off the top of my head if this will break any of our use cases because some have only every worked with envoys in between. I'm not sure the attitude of sounds like a bug elsewhere is quite the right approach we want. Perhaps the flag should be there to allow opting into the old behavior in case the new and correct behavior breaks existing use cases.

**Comment by fishy** [comment]
I'm OK with having a flag to opt in for the old behavior. I'm jut not comfortable doing that myself (I'm not really familiar with the envoy codebase enough to do that). Someone can do a follow up PR after this is merged to add the flag and old behavior back, or someone can take this PR over from me to fix the bug and also add a flag in the same go.

**Comment by fishy** [comment]
I don't have to be the one to fix this bug. I'm just finding it not too hard to fix so here's my fixing PR.

**Comment by zuercher** [comment]
@fishcakez is anyone on your team going to pick this up?

**Comment by rgs1** [comment]
> @fishcakez is anyone on your team going to pick this up?

I can pick it up.

**Comment by rgs1** [comment]
> > @fishcakez is anyone on your team going to pick this up?
> 
> I can pick it up.

Or maybe @JuniorHsu if I get derailed.

**Comment by zuercher** [comment]
Should we close this PR?

**Comment by rgs1** [comment]
> Should we close this PR?

Yes I think so since there'll be a follow-up. Thanks.

**Comment by fishy** [comment]
can someone link the follow-up PR? I don't see anything referencing the issue.

**Comment by rgs1** [comment]
> can someone link the follow-up PR? I don't see anything referencing the issue.

Haven't send one yet, should get to it today/tomorrow.

**Comment by rgs1** [comment]
Follow-up here #20893.

**Pull request closed without merging**
