### PR TITLE
repokitteh: Ignore non-envoy repo prs

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: repokitteh: Ignore non-envoy repo prs
Additional Description:

this should eliminate at least some of the error traces we currently get

also removes a now redundant rk file

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
there is a separate error which is triggered by check_runs, not sure why, but something to do with importing the newpr.star module

cc @itayd

**Review by alyssawilk — APPROVED** [review]

**Comment by alyssawilk** [comment]
If you merge without itay sign-off, please make sure you're on the repokitteh slack channel to monitor any failures after merge :-)
for example I added back that dup'd file after realizing folks not synced to head were triggering the old code.  It's been long enough that hopefully won't be a problem!

**Comment by phlax** [comment]
> If you merge without itay sign-off, please make sure you're on the repokitteh slack channel to monitor any failures after merge :-)

yep, for sure, will do

**Comment by itayd** [comment]
sorry just seen this. next time it'll help if you slack me that there's something that needs my attention :)

in any case - how can a non-envoy  pr be made in the envoy repo?

**Comment by phlax** [comment]
> how can a non-envoy pr be made in the envoy repo?

if you check the repokitteh logs it should be obvious what this fixed

**Pull request merged**
