### PR TITLE
WiP clang-tidy: add bugprone-unchecked-optional-access to config

### PR DESCRIPTION
**Pull request by jmarantz**
Commit Message: Adds a clang-tidy check that optionals are checked prior to referencing them.
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Review by RyanTheOptimist — COMMENTED** [review]
Thanks, I *super* love this! I'm mildly apprehensive about adding new warning without fixing existing code since this means that a future PR which simply moves some code will end up hitting an error. Do we have any way to evaluate how many instances of this error exist in the codebase?

**Comment by jmarantz** [comment]
@phlax @lizan I was expecting this PR to fail clang-tidy. That's because a line I modified in source/common/upstream/load_balancer_impl.cc had a pre-existing false-positive that (based on internal tools) should have been flagged by clang with the option.

However I did not see clang-tidy listed as a test-phase at all.

**Comment by phlax** [comment]
> However I did not see clang-tidy listed as a test-phase at all.

as mentioned offline - its currently disabled - im working on bringing it back atm

**Comment by jmarantz** [comment]
Ah ok, thanks. I'm going to demote this to a WiP in the meantime.

**Pull request closed without merging**
