### PR TITLE
deps: Update pytooling deps

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @kfaseela

**Comment by phlax** [comment]
we might want to add `-werror` for any tools that are based on the checker as the default has flipped (code_format in particular)

**Review by kfaseela — APPROVED** [review]

**Comment by phlax** [comment]
yep, the default had already flipped and there is a lurking warning/error that needs to be resolved....

**Review by kfaseela — APPROVED** [review]

**Review by wrowe — APPROVED** [review]
LGTM

**Pull request merged**
