### PR TITLE
tls: update FIPS version to 2022-06-13

### PR DESCRIPTION
**Pull request by ggreenway**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by ggreenway** [comment]
The boringssl-fips tests are failing, and I don't understand why:

```
2024-07-31T23:54:13.0852109Z [ RUN      ] SSLTest.HostMatching
2024-07-31T23:54:13.0852313Z Client error: SSL
2024-07-31T23:54:13.0852609Z /b/f/w/external/boringssl_fips/boringssl/ssl/ssl_test.cc:8112: Failure
2024-07-31T23:54:13.0852873Z Expected equality of these values:
2024-07-31T23:54:13.0853085Z   test.should_match
2024-07-31T23:54:13.0853283Z     Which is: true
2024-07-31T23:54:13.0853542Z   ConnectClientAndServer(&client, &server, client_ctx.get(), server_ctx.get(), config)
2024-07-31T23:54:13.0853799Z     Which is: false
2024-07-31T23:54:13.0853971Z Google Test trace:
2024-07-31T23:54:13.0854221Z /b/f/w/external/boringssl_fips/boringssl/ssl/ssl_test.cc:8099: example1.com
2024-07-31T23:54:13.0854472Z Client error: SSL
2024-07-31T23:54:13.0854718Z /b/f/w/external/boringssl_fips/boringssl/ssl/ssl_test.cc:8112: Failure
2024-07-31T23:54:13.0854978Z Expected equality of these values:
2024-07-31T23:54:13.0855190Z   test.should_match
2024-07-31T23:54:13.0855383Z     Which is: true
2024-07-31T23:54:13.0855639Z   ConnectClientAndServer(&client, &server, client_ctx.get(), server_ctx.get(), config)
2024-07-31T23:54:13.0855895Z     Which is: false
2024-07-31T23:54:13.0856065Z Google Test trace:
2024-07-31T23:54:13.0856313Z /b/f/w/external/boringssl_fips/boringssl/ssl/ssl_test.cc:8099: example2.com
2024-07-31T23:54:13.0856562Z Client error: SSL
2024-07-31T23:54:13.0856757Z Client error: SSL
2024-07-31T23:54:13.0857001Z /b/f/w/external/boringssl_fips/boringssl/ssl/ssl_test.cc:8112: Failure
2024-07-31T23:54:13.0857255Z Expected equality of these values:
2024-07-31T23:54:13.0857467Z   test.should_match
2024-07-31T23:54:13.0857640Z     Which is: true
2024-07-31T23:54:13.0857892Z   ConnectClientAndServer(&client, &server, client_ctx.get(), server_ctx.get(), config)
2024-07-31T23:54:13.0858145Z     Which is: false
2024-07-31T23:54:13.0858337Z Google Test trace:
2024-07-31T23:54:13.0858586Z /b/f/w/external/boringssl_fips/boringssl/ssl/ssl_test.cc:8099: example3.com
2024-07-31T23:54:13.0858960Z Client error: SSL
2024-07-31T23:54:13.0859158Z Client error: SSL
2024-07-31T23:54:13.0859351Z Client error: SSL
2024-07-31T23:54:13.0859572Z /b/f/w/external/boringssl_fips/boringssl/ssl/ssl_test.cc:8112: Failure
2024-07-31T23:54:13.0877187Z Expected equality of these values:
2024-07-31T23:54:13.0877523Z   test.should_match
2024-07-31T23:54:13.0877727Z     Which is: true
2024-07-31T23:54:13.0877993Z   ConnectClientAndServer(&client, &server, client_ctx.get(), server_ctx.get(), config)
2024-07-31T23:54:13.0878256Z     Which is: false
2024-07-31T23:54:13.0878451Z Google Test trace:
2024-07-31T23:54:13.0878721Z /b/f/w/external/boringssl_fips/boringssl/ssl/ssl_test.cc:8099: abc.example5.com
2024-07-31T23:54:13.0878958Z Client error: SSL
2024-07-31T23:54:13.0879151Z Client error: SSL
2024-07-31T23:54:13.0879506Z 12135672:error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:/b/f/w/external/boringssl_fips/boringssl/ssl/handshake.cc:393:
2024-07-31T23:54:13.0879860Z [  FAILED  ] SSLTest.HostMatching (5 ms)
```

**Comment by dio** [comment]
@ggreenway I think the cert in that particular test (e.g. https://github.com/google/boringssl/blob/0c6f40132b828e92ba365c6b7680e32820c63fa7/ssl/ssl_test.cc#L8014 is "expired" ("Not After" 2022-12-06).

I think there are two options:

1. Replace the certs
2. Set `X509_VERIFY_PARAM_set_flags` with the `X509_V_FLAG_NO_CHECK_TIME` (this is added in later commits, I tested the following patch, and it works: https://gist.github.com/dio/f1de152a4cc2af5508a962ed43d10a98)

**Comment by ggreenway** [comment]
@dio thanks for investigating! I'd rather not patch the source; I'm leaning towards excluding that test entirely.

**Comment by dio** [comment]
> I'm leaning towards excluding that test entirely.



@ggreenway yeah, that makes sense. Thanks for working on this.

**Review by kyessenov — COMMENTED** [review]
We probably need a follow up to set FIPS security policy for TLSv1.3 support - but it's a good idea to split the PRs.

**Comment by ggreenway** [comment]
@moderation can you review please?

**Comment by moderation** [comment]
/lgtm deps

Apologies for delay - offline due to vacation

**Pull request merged**
