### PR TITLE
bazel: fix quiche compilation error on Android

### PR DESCRIPTION
**Pull request by jpsim**
`llround` is not constexpr on Android.

### CODE REVIEW

**Comment by jpsim** [comment]
> Should we add a TODO or file an issue somewhere to make sure don't lose track of this?

I can open a PR to apply this change directly in quiche if you think it's likely to be considered.

**Comment by jpsim** [comment]
I opened https://github.com/google/quiche/pull/18, let's see what the quiche folks say.

**Comment by moderation** [comment]
Definitely preferable fix upstream vs. carry a patch here. Agree with @RyanTheOptimist on adding a TODO so we can track to removal

**Comment by RyanTheOptimist** [comment]
> Definitely preferable fix upstream vs. carry a patch here. Agree with @RyanTheOptimist on adding a TODO so we can track to removal

I should have mentioned that there is an upstream fix in flight. (though it will probably not land in envoy until next week)

**Comment by jpsim** [comment]
I added a todo comment.

I'm glad to hear that an upstream fix is in flight, although I'd appreciate if we could merge this to unblock Envoy Mobile from being up to date in the meantime.

**Review by RyanTheOptimist — APPROVED** [review]
LGTM, but perhaps we should wait for https://github.com/envoyproxy/envoy/pull/22186 to land instead?

**Comment by jpsim** [comment]
Closing in favor of https://github.com/envoyproxy/envoy/pull/22186

**Pull request closed without merging**
