### PR TITLE
filter state: add an object factory

### PR DESCRIPTION
**Pull request by kyessenov**
Commit Message: add a factory to instantiate filter state objects from raw bytes in the dynamic extensions (Wasm/Lua)
Risk Level: low
Testing: added
Docs Changes: yes
Release Notes: none, not exposed yet

### CODE REVIEW

**Comment by phlax** [comment]
unassigning myself as this is not my area

**Review by RyanTheOptimist — APPROVED** [review]
Looks good! Should we update the changelog too?

**Comment by RyanTheOptimist** [comment]
/assign @zuercher
Cross-company review

**Comment by kyessenov** [comment]
I was thinking to add it when we add the setter in the ABIs, this is an internal refactor mostly.

**Review by zuercher — APPROVED** [review]

**Pull request merged**
