### PR TITLE
kafka: dependency upgrades

### LINKED ISSUE #18674: Newer release available `edenhill_librdkafka`: v1.8.2 (current: v1.7.0)
Package Name: edenhill_librdkafka
Current Version: v1.7.0@2021-05-10 09:28:20
Available Version: v1.8.2@2021-10-11 20:15:44
Upstream releases: https://github.com/edenhill/librdkafka/releases

### PR DESCRIPTION
**Pull request by adamkotwasinski**
Commit Message: kafka: dependency upgrades (kafka source for protocol, librdkafka, test utils) - https://github.com/envoyproxy/envoy/issues/18674
Additional Description: dependency upgrades - the newest messages are going to be developed a bit later as they appear to introduce one more data type, so custom code will be needed
Risk Level: Low
Testing: Integration tests, manual tests with [2.8.1 & 3.0.0](https://github.com/adamkotwasinski/envoy-kafka-tests)
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

Fix #18674

### CODE REVIEW

**Comment by adamkotwasinski** [comment]
oh my goodness release dates
/wait-any

**Comment by adamkotwasinski** [comment]
good for review
/assign @mattklein123 @moderation

**Comment by moderation** [comment]
Great to get these deps upgraded! Thanks

/lgtm deps

**Review by kfaseela — APPROVED** [review]

**Review by phlax — APPROVED** [review]
lgtm, thanks all

**Pull request merged**
