### PR TITLE
Bump c-ares to 1.26.0

### PR DESCRIPTION
**Pull request by fredyw**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by htuch** [comment]
Looks like legit failures in CI https://dev.azure.com/cncf/envoy/_build/results?buildId=162441&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=2181edf2-f610-59f2-c43a-04bb9d0bca00

**Comment by fredyw** [comment]
> Looks like legit failures in CI https://dev.azure.com/cncf/envoy/_build/results?buildId=162441&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=2181edf2-f610-59f2-c43a-04bb9d0bca00

Yeah, there are behavior changes in c-ares 1.26, for example when the search domain is empty, it will return `ARES_ENOBADNAME` instead of `ARES_ENODATA` or `ARES_ENOTFOUND`, etc, which is probably the correct thing to do, but a lot of the existing tests expect `ARES_NODATA` or `ARES_NOTFOUND` when the search domain is empty.

**Comment by moderation** [comment]
`1.27.0` was just released - https://github.com/c-ares/c-ares/releases/tag/cares-1_27_0. It would be good to catch this dep up. I'll try to look at the changed behavior over the weekend

**Comment by zirain** [comment]
> > Looks like legit failures in CI https://dev.azure.com/cncf/envoy/_build/results?buildId=162441&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=2181edf2-f610-59f2-c43a-04bb9d0bca00
> 
> Yeah, there are behavior changes in c-ares 1.26, for example when the search domain is empty, it will return `ARES_ENOBADNAME` instead of `ARES_ENODATA` or `ARES_ENOTFOUND`, etc, which is probably the correct thing to do, but a lot of the existing tests expect `ARES_NODATA` or `ARES_NOTFOUND` when the search domain is empty.

looks like it will return `ARES_EBADNAME` in 1.27.0 instead of `ARES_EDESTRUCTION` in 1.20.1

**Pull request closed without merging**
