### PR TITLE
adaptive concurrency: adding response body

### LINKED ISSUE #13138: Adaptive concurrency rejects should put reason into `grpc-message` header
https://github.com/envoyproxy/envoy/blob/a8b946e1c30618dfcab6c7e90333301c16b56a65/source/extensions/filters/http/adaptive_concurrency/adaptive_concurrency_filter.cc#L40-L42

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: low
Testing: updated tests
Docs Changes: n/a
Release Notes: inline
Fixes #13138

### CODE REVIEW

**Review by mattklein123 — APPROVED** [review]
Nice! IMO you don't need to runtime guard this since the adaptive concurrency filter is still marked experimental, but up to you.

**Comment by alyssawilk** [comment]
Oh excellent - I felt totally silly runtime guarding, but I'd been lazy and done git blame rather than checking extension status, and was trying to be a good role model :-P  I'll back that out.

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Comment by mattklein123** [comment]
Merge main to fix CI?

/wait

**Pull request merged**
