### PR TITLE
utility: handle the failure of dynamic_cast gracefully

### PR DESCRIPTION
**Pull request by tyxia**
In `getMergedPerFilterConfig`(which is used by ext_authz, ext_proc), the failure of dynamic_cast should be handled gracefully. We should not crash (deference the nullptr) if resolving per route config failed (i.e., dynamic_cast failed) since it is on data plane path.

### CODE REVIEW

**Review by htuch — CHANGES_REQUESTED** [review]
A few things:
1. Should we have a static assert to assist debugging in non-prod builds as with `resolveMostSpecificPerFilterconfig`?
2. Any thoughts on whether the merge semantics here are needed or we could just do `resolveMostSpecificPerFilterconfig`?
3. Need to add a test in any case.

Otherwise looks like the right fix.

**Comment by tyxia** [comment]
> A few things:
> 
> 1. Should we have a static assert to assist debugging in non-prod builds as with `resolveMostSpecificPerFilterconfig`?
> 2. Any thoughts on whether the merge semantics here are needed or we could just do `resolveMostSpecificPerFilterconfig`?
> 3. Need to add a test in any case.
> 
> Otherwise looks like the right fix.

Thanks for review! Regarding the review comments:
1. Good idea! I added the static_assert
2. I actually did test `resolveMostSpecificPerFilterconfig` first, it probably should work (as most need some tweaks). But I finally went with this fix since I think it is a issue needs to be fixed in this method anyways.
3. I am not sure if such invalid dynamic_cast is easy to be triggered in a unit test. Though It is exposed in a more complicated integration test. AFAICT, This is not tested in `resolve` method but I can try to add one if it is strongly preferred.

**Review by htuch — COMMENTED** [review]
Yeah, please add a test. It should be easy, just use config of the wrong type. At least validate the positive case, that this fails with a log mesage.

**Comment by tyxia** [comment]
@htuch As Envoy currently doesn't have `negative complication test` setup (which is available internally), test will fail to build with static_assert. So I removed `static_assert` from the code but verify the log message with `EXPECT_LOG_CONTAINS`.

PTAL, thanks!

**Comment by tyxia** [comment]
The `Verify/examples` failure should be irrelevant. @phlax  do you have some insights on how to re-trigger it (I tried /retest and merge main)

Or can we merge this PR with `Verify/examples` failure once @htuch's approves.

**Comment by phlax** [comment]
>  do you have some insights on how to re-trigger it 

i added a comment here https://github.com/envoyproxy/envoy/issues/27756#issuecomment-1612726556 but i suspect this will still require a maintainer to kick it  - when i find some time i will look into resolving this using `/retest`

> Or can we merge this PR with Verify/examples failure

preferably dont - i want to make this required again once we have a reasonable way to retest 

it it is necessary tho - please do what you can to ensure that any failure is genuinely not connected

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
