### PR TITLE
Update protoconverter patch

### PR DESCRIPTION
**Pull request by asedeno**
This serves to decouple protoconverter from the protobuf version it was forked off of.

These changes should really be upstream, but upstream is experiencing technical issues taking patches right now, so we'll carry them here until those are resolved.

Risk Level: low
Testing: CI

### CODE REVIEW

**Comment by mattklein123** [comment]
Do you have any more context on this? This is a huge patch. What was actually changed here?

**Comment by asedeno** [comment]
When protoconverter forked off of protobuf, it brought with it things it should not have. The crippling one was `port_def.h`, which is a protobuf internal header that among other things defines of `PROTOBUF_VERSION`, errors out if it finds it is already defined, and checks for a minimum version of `GOOGLE_PROTOBUF_VERSION`.
https://github.com/grpc-ecosystem/proto-converter/blob/main/src/google/protobuf/util/converter/port_def.inc#L224-L227

Since the fork, this file has changed in protobuf, and importantly, the definition of `PROTOBUF_VERSION` moved to [runtime_version.h](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/runtime_version.h).

This parch is large, yes, but also very negative. Some of it is already in upstream, but not exported to github due to technical issues.

The patch removes these files:
- common.h
- common.cc
- common_unittests.cc
- port_def.inc
- port_undef.inc

Additionally, it:
- Removes `#includes` for the .h and .inc files that were removed.
- Remvoes the use of the `PROTOBUF_EXPORT` macro.
- Replaces `PROTOBUF_PREDICT_FALSE` with `ABSL_PREDICT_FALSE`

And in a few places it reformats things slightly. I tried to filter these formatting-only changes out, but some crept in.

**Comment by asedeno** [comment]
I've gone ahead and moved the file deletions to separate `patch_cmds` to make the patch itself a little easier to digest.

**Comment by asedeno** [comment]
Okay, I don't know what's up with Envoy/Publish and verify.

```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 51df4730-5be8-4a3b-8e97-52d8f99ea0ce
ERROR: io.grpc.StatusRuntimeException: UNAUTHENTICATED
```

**Comment by phlax** [comment]
>  I don't know what's up with Envoy/Publish and verify.

that _should_ be fixed now - i broke it earlier and landed a patch soon after

**Comment by asedeno** [comment]
@phlax, when I merged in `main` it had all your recent changes up to fcfae60533.

**Comment by phlax** [comment]
argh - another 8( - ill fix it now ...

**Comment by phlax** [comment]
should be half fixed - will follow up asap when i figure out the issue

**Comment by asedeno** [comment]
Carving off more of #36167.

**Comment by asedeno** [comment]
Nope, still fails.

```
2024/09/24 21:16:11 Downloading https://releases.bazel.build/6.5.0/release/bazel-6.5.0-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 3dafc16c-40a1-4dc6-8559-8708e30f4d82
ERROR: io.grpc.StatusRuntimeException: UNAUTHENTICATED
```

**Comment by phlax** [comment]
im debugging it atm - but its taking a while

**Comment by asedeno** [comment]
Okay, we're good to go on CI again. Anything else on your end, @mattklein123?

**Comment by phlax** [comment]
im really concerned about the amount of patching going on here - if we are going to land this there needs to be a strong justification for doing so

my 2 questions are

- do we need to update this dep right now
- can we upstream these changes instead

**Comment by asedeno** [comment]
We can't update protobuf without landing this because it is tightly coupled to protobug <27 and will break future builds.

We can't upstream these changes until upstream fixes their export process from Google's internal repo. Or, rather, I can upstream them but it won't do _us_ any good here until the export is fixed.

**Comment by phlax** [comment]
if its to update protobuf - we arent going to do that until after the release anyway - so probably i would say take this one slowly and try to get the upstream issues resolved in the meantime

**Comment by asedeno** [comment]
I asume you mean 1.32.0, and not the 1.31.2 that just happened?

**Comment by phlax** [comment]
yeah 1.32 is due in the next few weeks

**Comment by asedeno** [comment]
I've attempted to fix protoconverter upstream, but it has gotten itself tangled up with unexportable google-internal stuff and is currently not exportable in a way that builds.

**Comment by mattklein123** [comment]
We can merge this to unblock things as long as you are still working towards fixing the upstream issues. Thank you!

**Review by mattklein123 — APPROVED** [review]

**Comment by asedeno** [comment]
Thanks @mattklein123; to alleviate concerns, as soon as upstream export issues are fixed it is my intention that we be able to import this with no patches.

**Pull request merged**
