### PR TITLE
Plumb BoolIndicator through stats sink and admin

### PR DESCRIPTION
**Pull request by taion809**
WIP
Description: Plumb the boolIndicators through various stats sinks and handlers.  This also needs to cast from bool to int for collectors like statsd and prometheus.
Risk Level: Low
Testing: Manual testing

Fixes: #6277

Signed-off-by: Nicholas J <nicholas.a.johns5@gmail.com>

### CODE REVIEW

**Comment by mattklein123** [comment]
@fredlas can you do an initial pass on this and/or pair with @taion809? I don't want to skimp on tests here, so if it's easier to just revert your other PR for now we can also do that. Let us know what you think.

**Comment by taion809** [comment]
SGTM, i'm currently working on tests right but but I agree if it's easier to revert we should do that so prod deployments dont get blocked

**Comment by mattklein123** [comment]
@taion809 I think my feeling is to revert the other change, and then @fredlas can fix at a more convenient pace? WDYT?

**Comment by mattklein123** [comment]
https://github.com/envoyproxy/envoy/pull/6280

**Comment by taion809** [comment]
SGTM, one thing to consider though is that when outputting the metrics statsd and prometheus both have no boolean datatype, they need to be converted to an int :)

**Pull request closed without merging**
