### PR TITLE
owners: add nezdolik as maintainer.

### PR DESCRIPTION
**Pull request by htuch**

### CODE REVIEW

**Comment by htuch** [comment]
PTAL and provide any suggestions to update areas of expertise, thanks.

**Review by botengyao — APPROVED** [review]
Congrats @nezdolik!! ;0

**Review by nezdolik — APPROVED** [review]
Info looks correct to me. Excited, thank you!

**Review by KBaichoo — APPROVED** [review]

**Review by phlax — COMMENTED** [review]
post-hoc approval - welcome!!!

**Pull request merged**
