### PR TITLE
[bp/1.32] opentelemetrytracer: limit calculated sampling exponent in Dynatrace sampler

### LINKED ISSUE #37199: opentelemetrytracer: Dynatrace sampler adds invalid span attributes
*Title*: *Dynatrace sampler adds invalid span attributes*

*Description*:
Dynatrace sampler calculates a sampling exponent for requests. This sampling exponent should always be lower than 15 and is used to calculate the span attributes `sampling.threshold` and `supportability.atm_sampling_ratio`. However, there is a scenario which results in a sampling exponent larger than 31. This causes an overflow and leads to invalid values.

### PR DESCRIPTION
**Pull request by samohte**
Commit Message: Backport #37240
Additional Description:
Risk Level: Low
Testing: Manual
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:] N/A
[Optional Fixes #37199]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by joaopgrassi — APPROVED** [review]

**Comment by phlax** [comment]
@samohte @joaopgrassi is this not required for 1.29.x ?

**Review by phlax — APPROVED** [review]
lgtm, thanks @samohte

**Comment by samohte** [comment]
> @samohte @joaopgrassi is this not required for 1.29.x ?

@phlax, Thanks for taking care. This code was added in https://github.com/envoyproxy/envoy/commit/97ef386aeb4d12a3fd38f151c38be7decc5c37bf and is not contained in 1.29.

**Pull request merged**
