### PR TITLE
QUIC: remove all usage of quic::kRVCM

### PR DESCRIPTION
**Pull request by ericorth**
Commit Message: remove all usage of quic::kRVCM
Additional Description: This QUIC connection option no longer does anything and is no longer needed after some recent (~1 month ago) changes in QUICHE.  Now, QUICHE is removing the definition of `quic::kRVCM`. Removing all usage from Envoy to unblock QUICHE rolls to Envoy. 
Risk Level: Low
Testing: Covered by existing unit tests
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Review by RenjieTang — APPROVED** [review]

**Comment by ericorth** [comment]
(I don't know what I need to do for repokitteh to let me assign people, but running this command anyway seems to be pretty good at getting people's attention and communicating that I would like them to take a look.)

**Comment by alyssawilk** [comment]
you need an admin to invite you to the org.  done :-)

**Review by alyssawilk — APPROVED** [review]
LGTM but I'm going to ask Ryan or Dan to take a look to get an LGTM from someone a little more quiche savvy than I am today :-P

**Comment by alyssawilk** [comment]
happy to merge once I've got either of their LGTM

**Review by RyanTheOptimist — APPROVED** [review]
Thanks for the cleanup!

**Pull request merged**
