### PR TITLE
deps: bump datadog distributed tracing -> 0.1.7

### LINKED ISSUE #26354: Newer release available `com_github_datadog_dd_trace_cpp`: v0.1.7 (current: v0.1.5)
Package Name: com_github_datadog_dd_trace_cpp@0.1.5
Current Version: v0.1.5@2022-12-06
Available Version: v0.1.7@2023-03-17
Upstream releases: https://github.com/DataDog/dd-trace-cpp/releases

### PR DESCRIPTION
**Pull request by RiverPhillips**
Commit Message: deps: bump datadog distirbuted tracing -> 0.1.7
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]    Fixes  #26354
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@cgilmour @palazzem would you mind taking a look

**Comment by cgilmour** [comment]
This is fine, but also covered by #26284.

**Comment by phlax** [comment]
> also covered by https://github.com/envoyproxy/envoy/pull/26284.

ill leave it up to you whether we land this separately

**Comment by cgilmour** [comment]
After checking with @dgoffredo, we're happy if this is merged before #26284 is reviewed and merged.

**Review by cgilmour — APPROVED** [review]

**Review by phlax — APPROVED** [review]
lgtm @RiverPhillips 

thanks all!

**Pull request closed without merging**
