### PR TITLE
deprecations: remove DOWNSTREAM_ADDRESS and CLIENT_IP formatters

### PR DESCRIPTION
**Pull request by mattklein123**
Fixes https://github.com/envoyproxy/envoy/issues/2900

*Risk Level*: Low 
*Testing*: Fixed existing tests
*Docs Changes*: N/A
*Release Notes*: N/A

### CODE REVIEW

**Comment by danielhochman** [comment]
Should you remove DOWNSTREAM_ADDRESS from the docs? https://github.com/envoyproxy/envoy/blob/master/docs/root/configuration/access_log.rst

**Comment by mattklein123** [comment]
Oops yes, thanks. Will fix.

**Comment by zuercher** [comment]
lgtm (modulo docs)

**Comment by mattklein123** [comment]
@danielhochman @zuercher PTAL

**Pull request merged**
