### PR TITLE
Overload Manager: Add loop delay histogram for overload manager resource refresh loop.

### PR DESCRIPTION
**Pull request by KBaichoo**
Commit Message: : Add loop delay histogram for overload manager resource refresh loop.
Additional Description: 
Risk Level: low
Testing: added unit test
Docs Changes: included
Release Notes:  included
Platform Specific Features: n/a
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]

**Review by zuercher — COMMENTED** [review]
In general, this looks fine, but I wanted to point out that you're combining two measurements into one here.

One is the timer delay: if the dispatcher thread that handles the timer event is overloaded (too many events), then the timer event can be delayed.

The other is the amount of time it takes to execute the timer event. I wonder if you just want to use a histogram to record the the execution time of the event? I think there's already a metric that tracks the timer delay.

**Comment by KBaichoo** [comment]
Thanks for the review @zuercher.

Yes this is combining both the delay of the timer + the latency for the refresh to run which would capture the latency of the last refresh of resource monitors. 

There's currently no metric for the timer delay AFAICT. The underlying context is that given that this runs on the main thread there are times where I expect the timer to be delayed (large config, stat flushing, etc); I'd expect the resource refresh to be mostly negligible compared to that delay / the timer interval.

**Review by zuercher — APPROVED** [review]

**Pull request merged**
