### PR TITLE
test: fix missing clean up host raw connection in HDS

### PR DESCRIPTION
**Pull request by zhxie**
Signed-off-by: Xie Zhihao <zhihao.xie@intel.com>

Commit Message: test: fix missing clean up host raw connection in HDS
Additional Description:
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by tyxia** [comment]
LGTM.
@zhxie  Do you want to open it up for review? Or there are other things pending.

**Comment by zhxie** [comment]
We found it when we are implementing io_uring, but we are not sure if it is really needed.

**Comment by tyxia** [comment]
> We found it when we are implementing io_uring, but we are not sure if it is really needed.

Thanks for context! IMO, this PR is good to have even though there is no issue currently.

**Pull request closed without merging**
