### PR TITLE
xds: add api ref to the extension

### PR DESCRIPTION
**Pull request by botengyao**
Add api ref to the extension config creation. 
E.g., sometimes some objects stored in the processContext are needed.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by adisuissa — COMMENTED** [review]
Changes LGTM.

Typically it is better to pass a more specific type. Can you provide more context why this is needed?

**Comment by botengyao** [comment]
Thanks @adisuissa, e.g., sometimes some objects stored in the processContext are needed.

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

Assigning a senior maintainer due to core code changes.
/assign-from @envoyproxy/senior-maintainers

**Pull request merged**
