### PR TITLE
Support to disable adding 'x-forwarded-proto'

### PR DESCRIPTION
**Pull request by ramachaitanyak**
Description:
  * Envoy currently is adding the 'x-forwarded-proto' header to the requests from downstream
    clients to its upstream by default. This patch helps this operation be configuration driven, where in
    by setting the exclude_request_forwarded_proto variable to true, the header is not added to Envoy's
    upstream and the header is added all otherwise.
  * The boolean 'exclude_request_forwarded_proto' does not have any effect on upstream requests where the
    'x-forwarded-proto' header is explicitly configured by the client.

  Changes made:
  * Defined a new boolean in 'http_connection_manager.proto' file called 'exclude_request_forwarded_proto'
    that can be configured to disable adding the 'x-forwarded-proto' header during upstream request from Envoy
  * Included the 'excludeRequestForwardedProto()' to be extended by all inheriting classes in file
    'conn_manager_config.h'
  * Included the logic to exclude adding the header in file 'conn_manager_utility.cc'
  * Included support for populating variable 'exclude_request_forwarded_proto_' from config in file
    'config.cc'
  * Implemented mock tests in file 'conn_manager_utility_test.cc' checking default, true and false states for
    'exclude_request_forwarded_proto_' variable
  * Implemented integration tests in file 'http_integration.cc' and validated true and default states driven by config

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by ramachaitanyak** [comment]
Hi, I realized I am using some older APIs in my code as I made my changes with an older branch. I will update with corrected API soon.

Thanks!
Rama

**Comment by alyssawilk** [comment]
Can you comment a bit more about your use case?

The scheme in Envoy is set based on the security of the underlying transport, rather than the URL than the URL that the client requested, so if you don't preserve this header you're losing pretty important information about the original request.  It'd be good to understand where this would be useful to lose.

Beyond that I suspect Dan will take a look once you've got the various CircleCI builds happy :-)

**Comment by ramachaitanyak** [comment]
@alyssawilk  there are few web applications hosted on ebay that behave erroneously when the 'x-forwarded-proto' header is seen in the request. This issue and the change-set addresses this concern; where there is support for directing correct requests to the apps deployed in the datacenter.

AFAIK, ebay has all its connections made https; probably the underlying applications are taking this for granted and behaving differently when this header is added. More to understand on the behavior of these apps, but will address this issue internally.

Thx!

**Comment by mattklein123** [comment]
Responding for @alyssawilk since she is OOO today, can you just use the `request_headers_to_remove` config param on the routes where you want to remove the header? I don't think we need a code change for this?

/wait-any

**Comment by ramachaitanyak** [comment]
> Responding for @alyssawilk since she is OOO today, can you just use the `request_headers_to_remove` config param on the routes where you want to remove the header? I don't think we need a code change for this?
> 
> /wait-any

Hi Matt, thanks for the advice, I will update as soon as I experiment with your suggestion and find out about the results.

Thx

**Comment by ramachaitanyak** [comment]
Hi Matt, I have used the 'add_request_headers_to_remove("x-forwarded-proto")' API in my integration tests and this is solving the problem as desired. I should have perhaps, consulted before working on the patch-set. I will withdraw this PR. Thanks for the time and help!

R

**Comment by ramachaitanyak** [comment]
On a different note for the purpose of understanding for future work, while I was getting my test cases in 'http2_integration_test' to run with the changes here in this PR; I was getting this error '`error [2019-05-31 19:07:55.053][14][critical][assert] [test/integration/http_integration.cc:315] assert failure: result. Details: Timed out waiting for new connection., returned from Envoy::HttpIntegrationTest::waitForNextUpstreamRequest()' `.

This errors was only generated when I set my exclude flag (using set_request_exclude_forwarded_proto(true)) as generated by the changes in `api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto`; I did not see these in my older envoy repository where I had made these changes. Did I make any obvious mistakes or is it that Envoy behaves differently on explicitly not adding this header.

I will spend some time understanding this case and traversing the code in gdb, however if any of you wiser people see something I have missed, please enlighten me! :)

Thanks!

**Comment by alyssawilk** [comment]
Generally when that happens, it's because some layer of the stack failed, such as Envoy deciding to do an sendLocalReply (so never creating the upstream connection).  If you run the tests with 
--test_arg="-l trace"
you get verbose logging, and can often see what unexpected event occurred, especially if you do a run before your change or with a similar test where you can see what happens in the success case, and compare to a failing run.

**Comment by ramachaitanyak** [comment]
Thanks @alyssawilk !

**Pull request closed without merging**
