### PR TITLE
[backport/v1.23] repo: Dev `1.23.1-dev`

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
arggh - just saw the commit author - will fix now...

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Comment by phlax** [comment]
@adisuissa ive backported a fix for the persistently failing test - would you mind stamping again

**Review by adisuissa — DISMISSED** [review]
LGTM, thanks!

**Comment by phlax** [comment]
seems this also needs #22379 to be backported

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!
please double check that the date in`changelogs/1.23.0.yaml` makes sense.

**Pull request merged**
