### PR TITLE
wasm: fix remote code without specified runtime

### PR DESCRIPTION
**Pull request by LawlietLi**
Signed-off-by: Yiheng Li <lyhutopi@gmail.com>

Commit Message: fix remote code without specified runtime
Additional Description:
When I use the remote code of the wasm plugin threre is a warning log tells:
`2021-06-11 10:14:41.794][184533][warning][wasm] [source/extensions/common/wasm/wasm_vm.cc:79] Failed to create Wasm VM with unspecified runtime`
Plugin does not start correctly.
I found that the plugin only saves references to ProtoConfig. The ProtoConfig may have been released when the asynchronous download of the remote code is complete.
So copy ProtoConfig to fix this problem

Risk Level: Low, no behavior change
Testing: UTs
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Review by mathetake — COMMENTED** [review]
Thanks, the change LGTM. I believe this PR and https://github.com/envoyproxy/envoy/pull/16795 harden Wasm extensions wrt ECDS async loads.

ping @PiotrSikora for the second pass.

**Review by PiotrSikora — COMMENTED** [review]
I think this looks fine, but could you either add a new test or modify `RemoteCode` in a way that breaks without your fix? Perhaps add scope around `plugin_config`?

**Comment by LawlietLi** [comment]
I considered other ways before I modify this, but I think the plugin should keep a copy of the configuration internally for later use, like other plugins do. Copying only happens once when constructing the factory and doesn't brings a lot of extra cost.
I can add a test. Is this test you mention about testing how the plugin behaves after the configuration is released?

**Comment by LawlietLi** [comment]
> I think this looks fine, but could you either add a new test or modify `RemoteCode` in a way that breaks without your fix? Perhaps add scope around `plugin_config`?

I considered other ways before I modify this, but I think the plugin should keep a copy of the configuration internally for later use, like other plugins do. Copying only happens once when constructing the factory and doesn't brings a lot of extra cost.
I can add a test. Is this test you mention about testing how the plugin behaves after the configuration is released?

**Comment by LawlietLi** [comment]
> I think this looks fine, but could you either add a new test or modify `RemoteCode` in a way that breaks without your fix? Perhaps add scope around `plugin_config`?

Thanks, it is necessary to optimize the tests. I modified `RemoteCode` to add scope to `plugin_config`.

**Review by PiotrSikora — DISMISSED** [review]
LGTM, other than a small style nit.

Thanks!

**Comment by LawlietLi** [comment]
> LGTM, other than a small style nit.
> 
> Thanks!

Thanks, I fixed it.

**Review by mathetake — APPROVED** [review]
Thank you!

**Pull request merged**
