### PR TITLE
docs: upstream_rq_per_try_timeout with hedged requests

### PR DESCRIPTION
**Pull request by ikonst**
Per
https://github.com/envoyproxy/envoy/blob/5fd73ca889aa12618c626c96bb33fde4707f8bf0/source/common/router/router.cc#L869-L874
upstream_rq_per_try_timeout is not incremented for hedged requests.

### CODE REVIEW

**Comment by ikonst** [comment]
@mpuncel @snowp

**Review by snowp — APPROVED** [review]
Thanks for the docs fix!

I'm not sure if this is the ideal state of things in terms of stats, but for now fixing the docs seems fine

**Comment by snowp** [comment]
Seems like CI is stuck, could you push an empty commit to restart it?

**Comment by snowp** [comment]
Seems like CI is really broken for this PR, could you create a new PR with the same change? Sorry for the inconvenience

**Pull request closed without merging**
