### PR TITLE
deps: Bump `com_github_curl` -> 8.4.0

### PR DESCRIPTION
**Pull request by suniltheta**
Commit Message: deps: Bump `com_github_curl` -> 8.4.0
Additional Description: CVE fix from https://github.com/curl/curl/releases/tag/curl-8_4_0
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by suniltheta** [comment]
cc: @moderation & @phlax for the review

**Comment by suniltheta** [comment]
hopefully in future we don't need to do this from the virtue of https://github.com/envoyproxy/envoy/pull/29880

**Comment by phlax** [comment]
windows fail seems real:

```console
//test/dependencies:curl_test                                            FAILED in 2 out of 2 in 0.3s
  Stats over 2 runs: max = 0.3s, min = 0.2s, avg = 0.3s, dev = 0.0s
  C:/build/tmp/execroot/envoy/bazel-out/x64_windows-opt/testlogs/test/dependencies/curl_test/test.log
  C:/build/tmp/execroot/envoy/bazel-out/x64_windows-opt/testlogs/test/dependencies/curl_test/test_attempts/attempt_1.log
```
https://dev.azure.com/cncf/envoy/_build/results?buildId=151981&view=logs&j=b840a642-5ff3-5357-2e4b-e06e40b0cffd&t=67965174-5100-5631-9dc0-68b9f0aacb53&l=12501

im in 2 minds about updating this prior to the 1.28 release - while its better for this to be updated its just doesnt leave much burn in time

**Comment by suniltheta** [comment]
yes, don't have to jeopardize upcoming v1.28 release for this. Meanwhile, if a new curl patch version arrives with the fix for above windows problem we can update or discard this PR based on dependabot.

**Comment by suniltheta** [comment]
Updated the curl_test.cc to ignore testing whether NTLM feature is enabled.

**Comment by suniltheta** [comment]
Hi @phlax, is this change safe to ship?

**Review by phlax — APPROVED** [review]
lgtm, thanks @suniltheta

**Pull request merged**
