### PR TITLE
Quiche roll 20220720202953

### PR DESCRIPTION
**Pull request by DavidSchinazi**
Commit Message: Update QUICHE from 8eb90efcb to d23adb74d
Additional Description: This is a standard dependency roll, no notable changes.
Risk Level: Low
Testing: Existing tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by RyanTheOptimist** [comment]
Looks like there's a clang-tidy issue:

    Message: invalid case style for function 'Http2HeaderBlockToEnvoyTrailers'
      ReplacementText: http2HeaderBlockToEnvoyTrailers

**Review by htuch — APPROVED** [review]
/lgtm deps

**Comment by DavidSchinazi** [comment]
Thanks for the reviews. I fixed the clang-tidy issue.

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
