### PR TITLE
fix: prevent NULL pointer dereference in lua filter extension

### PR DESCRIPTION
**Pull request by phil777**
Commit Message: FIX: prevent NULL pointer dereference in lua filter extension
Additional Description:
Risk Level: Low
Testing: manual testing
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Comment by snowp** [comment]
Thanks for the fix! Do you think you could include a test case that crashes without this fix?

**Comment by dio** [comment]
Thanks for this @phil777! I'm interested in how you do manual testing for this.

**Comment by phil777** [comment]
@dio here is how to reproduce it:

```
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
              inline_code: |
                function envoy_on_request(handle)
                   error()
                end
```

If you call `error()` with a parameter (e.g. `error("XXX error message XXX"`)`), it will not crash.

**Comment by mattklein123** [comment]
@phil777 would you mind adding a test? It should be simple?

**Comment by tzuryby** [comment]
@aguinet can you reopen this and add the tests required?

**Comment by aguinet** [comment]
> @aguinet can you reopen this and add the tests required?

@tzuryby done in https://github.com/envoyproxy/envoy/pull/21463

**Pull request closed without merging**
