### PR TITLE
deps: update cel-cpp

### PR DESCRIPTION
**Pull request by kyessenov**
Commit Message: Updates cel-cpp to latest in OSS. There's another export coming so this PR will be followed up. However, the new export needs the latest protoc, absl, and re2 - which may cause other problems. There is a macro pollution problem with https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/issues/154 addressed by a local patch. I will upstream cel-cpp patch separately.

Risk Level: low
Testing: unit
Docs Changes: none

### CODE REVIEW

**Comment by kyessenov** [comment]
MSVC does not support weak linkage with ABSL_ATTRIBUTE_WEAK.
I'm not sure how to resolve this apart from disabling CEL on windows. CC @jcking

**Comment by kyessenov** [comment]
It turns out the weak linkage is not necessary for this version of CEL since the new code is not active.

**Review by htuch — DISMISSED** [review]
+1 on upstreaming the CEL patches, they look painful to maintain.

**Review by tyxia — APPROVED** [review]
Thank you very much for the help with updating CEL!

**Review by yanavlasov — APPROVED** [review]

**Comment by kyessenov** [comment]
A new update to cel-cpp is in progress https://github.com/google/cel-cpp/pull/167, but it requires very recent protoc/absl - which will not happen quickly.

**Pull request merged**
