### PR TITLE
generic proxy: make sure the execute order of encoder filters is the reverse of decoder filters'

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: generic proxy: make sure the execute order of encoder filters is the reverse of decoder filters'
Additional Description:

Minor fix to the execute order of generic l7 filters.

Risk Level: Low. WIP extension.
Testing: unit test added.
Docs Changes: n/a.
Release Notes: added.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by KBaichoo** [comment]
/assign @zhaohuabing 

As code owner can you take a look? Thank you!

**Comment by htuch** [comment]
Since this is contrib, defer to @zhaohuabing

**Review by zhaohuabing — APPROVED** [review]

**Comment by zhaohuabing** [comment]
LGTM.

**Comment by wbpcode** [comment]
cc @htuch LGTM from maintainer is still necessary. 🤣

**Review by lizan — APPROVED** [review]

**Comment by wbpcode** [comment]
@lizan Thanks. 😺

**Pull request merged**
