### PR TITLE
docs: Only use latest minor version for histories

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:  docs: Only use latest minor version for histories
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
docs are rendered here https://storage.googleapis.com/envoy-pr/18427/docs/index.html

**Comment by phlax** [comment]
this is the first step on the path to reducing the number of published docs

**Review by mattklein123 — COMMENTED** [review]
This makes sense to me. Are you planning on removing the old dot releases? I'm trying to understand what the end game here is?

/wait-any

**Comment by phlax** [comment]
so im going to move all patch versions other than the latest

there are several steps required to get there - this is the first - essentially only linking to the latest

**Comment by phlax** [comment]
the lateral benefit to this is that currently netlify sometimes flakes when downloading the old versions `.inv` files - this wont entirely fix that, but it will make it a load less likely

**Review by mattklein123 — APPROVED** [review]
Cool SGTM, will need to be updated once we cut the release I guess.

**Comment by phlax** [comment]
yep, we will probs want to figure out some automation on this, but initially im thinking to get it working i can fix envoy <> website repos manually

**Pull request merged**
