### PR TITLE
examples/ci: Warn, dont error on `websocket` example

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
example fail https://github.com/envoyproxy/envoy/actions/runs/5624322366/job/15240919988#step:9:15720

**Comment by phlax** [comment]
related to #28546

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
