### PR TITLE
Update QUICHE from f326e9346 to 667c58656

### PR DESCRIPTION
**Pull request by alyssawilk**
https://github.com/google/quiche/compare/f326e9346..667c58656

```
$ git log f326e9346..667c58656 --date=short --no-merges --format="%ad %al %s"

2023-09-13 birenroy Adds an OgHttp2Session option for the initial assumed value of the remote endpoint's max concurrent streams setting.
2023-09-13 quiche-dev Add missing absl includes
2023-09-13 quiche-dev Allow truncating of binaryhttp request
2023-09-12 vasilvv Set a fixed CC algorithm in quic_generic_session_test
2023-09-11 bnc Make QuicErrorCode underlying type uint32_t, avoid narrowing when parsing.
2023-09-11 quiche-dev Registering a new use case to test out go/at-integration-guide.
2023-09-11 vasilvv Introduce support for basic WebTransport stats.
2023-09-11 vasilvv Add missing QUICHE_EXPORT directives.
2023-09-07 vasilvv Fix QUICHE_EXPORT directives for Chromium merge
2023-09-07 vasilvv Add missing QUICHE_EXPORT annotations
```

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
I see there is also https://github.com/envoyproxy/envoy/pull/29602, which is marked as draft too. Are these PRs coordinated?

**Comment by alyssawilk** [comment]
I have no idea.  @birenroy asked me to make sure I got his change in and I did?

**Comment by birenroy** [comment]
Sorry, I decided to work through the Envoy QUICHE import instructions, and forgot that this would end up being publicly visible. I was just practicing, and didn't mean to start a competing PR.

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by RyanTheOptimist** [comment]
> Sorry, I decided to work through the Envoy QUICHE import instructions, and forgot that this would end up being publicly visible. I was just practicing, and didn't mean to start a competing PR.

AH! Thanks for the backstory. If it's any consolation, GH is profoundly terrible about PRs, visibility, reviews, etc. You did everything right... GH just sucks.

**Pull request merged**
