### PR TITLE
Docs: tls minimum protocol version

### PR DESCRIPTION
**Pull request by gsalisbury**
Commit Message: docs: add note for tls protocol versions below tlsv1_2
Additional Description:
Risk Level: Low
Testing: N/A
Docs Changes: Adds a note that the cipher_suites setting needs to be manually set if using tls_minimum_protocol_version below TLSv1_2.
Release Notes: N/A
Platform Specific Features: N/A
Fixes https://github.com/envoyproxy/envoy/issues/22842

Signed-off-by: George Salisbury [gsalisbury@apnic.net](mailto:gsalisbury@apnic.net)

### CODE REVIEW

**Comment by yanavlasov** [comment]
@gsalisbury Thanks for updating docs. Looks like there are trailing spaces that format checks are unhappy about.

Link to diff: https://dev.azure.com/cncf/envoy/_build/results?buildId=117724&view=logs&j=f0537f27-2e39-530f-1fd2-a5ecd0924017&t=388a504b-3b8d-52aa-33e0-1e12bca05378&l=201

**Comment by gsalisbury** [comment]
Thanks @yanavlasov, removed those trailing spaces.

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
