### PR TITLE
WIP: ci trying for #7478

### PR DESCRIPTION
**Pull request by mnktsts2**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description: CI test for PR #7478 
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #7478 
[Optional Deprecated:]

### CODE REVIEW

**Comment by mnktsts2** [comment]
Same build error: #7478 .

**Comment by mnktsts2** [comment]
ok

**Comment by zuercher** [comment]
Looks like you got the other PR to build, so closing this.

**Pull request closed without merging**
