### PR TITLE
mobile: update `bazelw` to pull bazelisk 1.15.0

### PR DESCRIPTION
**Pull request by jpsim**
This pulls in a number of small but useful fixes: https://github.com/bazelbuild/bazelisk/compare/v1.10.1...v1.15.0

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by jpsim** [comment]
Now that we have this wrapper in this repo, perhaps we could consider moving it up to the root directory so it's available even outside of `mobile/` stuff.

**Review by keith — APPROVED** [review]
i also like the idea of moving to the root, i've toyed with adding this there in the past as well

**Review by Augustyniak — APPROVED** [review]

**Pull request merged**
