### PR TITLE
[mobile]add api to try disabling forceV6 on Android

### PR DESCRIPTION
**Pull request by RenjieTang**
Commit Message: add api to try disabling forceV6 on Android
Additional Description: I tried with it disabled on my Android phone and things were fine. Adding a config knob to try it in prod.
Risk Level: Low
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: android only

### CODE REVIEW

**Review by abeyad — APPROVED** [review]

**Comment by abeyad** [comment]
the test failure looks real, it was added by @fredyw a month ago; not sure if it's a flake or if this PR caused it.

**Comment by RenjieTang** [comment]
> the test failure looks real, it was added by @fredyw a month ago; not sure if it's a flake or if this PR caused it.

It seems flaky

**Comment by fredyw** [comment]
> > the test failure looks real, it was added by @fredyw a month ago; not sure if it's a flake or if this PR caused it.
> 
> It seems flaky

Which test is it?

**Comment by abeyad** [comment]
> > > the test failure looks real, it was added by @fredyw a month ago; not sure if it's a flake or if this PR caused it.
> > 
> > 
> > It seems flaky
> 
> Which test is it?

it was this test: https://github.com/envoyproxy/envoy/blob/b661f52c82218f1d1159ed1c5bd4c6436649d350/mobile/test/common/integration/client_integration_test.cc#L1339

**Pull request merged**
