### PR TITLE
test: deflake admin test by not using LDS

### PR DESCRIPTION
**Pull request by alyssawilk**
TBD (someone else) why the two don't play well together - I've done my debug duty for the week :-)

#7215

### CODE REVIEW

**Comment by mattklein123** [comment]
Thanks. Can you fix format?

/wait

**Comment by mattklein123** [comment]
@alyssawilk FYI I think the issue here is that the admin endpoint comes up before LDS completes so there is an inherent race condition.

**Comment by alyssawilk** [comment]
Can you give more detail?  The admin endpoint may come up first, but AFIK the test framework should block until the worker thread listeners are up. The stat should be incremented even if the stat matcher isn't applied, so I'm still not quite following what the race is.

**Comment by mattklein123** [comment]
> Can you give more detail? 

I don't have more detail, this was a "30s thought." :) I just figured that since admin comes up first there might be a related timing issue. That's all I've got.

**Pull request merged**
