### PR TITLE
examples: Warn dont error on `wasm-cc` sandbox fail

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
allowing flakey sandboxes to warn is one of those things i think im going to regret

having said that i would like to make this CI required again and supressing known flakes seems like the best way to do that for now

**Review by adisuissa — DISMISSED** [review]
LGTM, thanks.
Please add an issue to track these.

**Comment by phlax** [comment]
>  Please add an issue to track these.

let me add an issue for each and add links here ...

**Comment by phlax** [comment]
issues/links added @adisuissa - PTAL

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
