### PR TITLE
mac: re-enable macOS ci

### PR DESCRIPTION
**Pull request by zuercher**
I'll keep an eye on the pull request CI.

### CODE REVIEW

**Comment by htuch** [comment]
@zuercher FTR can you provide a quick summary of "what's changed" to make this now work. Also, let me know when you want a merge.

**Comment by zuercher** [comment]
In our Friday call with Circle they said it was two problems: 1) their macOS host cluster for 2.0 builds was very small and they needed time to bring more hosts online, 2) a bug that caused queuing of the linux-based builds even though only the macOS builds were resource constrained.

They thought their macOS cluster would have sufficient capacity on Friday, but asked that we wait till Monday.

Meantime, Homebrew seems to have a bug where updating the version of ruby that homebrew requires while installing a formula fails, so I split out the Homebrew update from the formula installation.

**Comment by zuercher** [comment]
I think we can merge this. It built twice today and the queuing appeared to work correctly both times.

**Comment by htuch** [comment]
@zuercher SGTM. Please keep an eye on things and submit a rollback if things go pear shaped.

**Pull request merged**
