### PR TITLE
redis_proxy: fix crash if catch_all_route is not defined

### PR DESCRIPTION
**Pull request by deveshkandpal1224**
Commit Message: Fix proxy crash if catch_all_route is not defined
Additional Description: If an incoming redis key does not match against any of the prefix_routes that maybe defined, the proxy crashes if catch_all_route is not defined. This bug handles "no route" matching scenario. 
Risk Level: Low
Testing: Unit test
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/29120
[Optional Fixes commit #PR or SHA] https://github.com/envoyproxy/envoy/pull/27902
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by deveshkandpal1224** [comment]
@mattklein123 @weisisea - could you PTAL ? CC - @nickamorim

**Comment by RyanTheOptimist** [comment]
Looks like this needs a main merge.
/assign @mattklein123 
/wait

**Comment by phlax** [comment]
hi @deveshkandpal1224 we had to revert this PR as it broke CI - im guessing the PR that landed immediately prior may have caused a bad merge - please do resubmit!

**Comment by deveshkandpal1224** [comment]
@phlax - will resubmit my changes.

**Pull request merged**
