### PR TITLE
test: Cleanup multiplexed_integration_test.cc

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
Inline multiplexed_integration_test.h into multiplexed_integration_test.cc
Rename Http2IntegrationTest to MultiplexedIntegrationTest and
rename Http2RingHashIntegrationTest to MultiplexedRingHashIntegrationTest
and make both also cover HTTP/3.
Reorder the tests so that the various tests are contiguous instead of interspersed through the file.

Signed-off-by: Ryan Hamilton <rch@google.com>

Risk Level: N/A
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
@alyssawilk this file was a bit of a jumble and this PR cleans it up. It does move a bunch of tests around the the PR is a tad messy, but I think it's worth it?

**Comment by alyssawilk** [comment]
I'm fine with inlining but I don't think the reordering is worth it.  having tests contiguous is nice but IMO not worth losing the git history.
/wait

**Comment by RyanTheOptimist** [comment]
> I'm fine with inlining but I don't think the reordering is worth it. having tests contiguous is nice but IMO not worth losing the git history. /wait

Ok, un-moved. The file has only existed since April and is test-only so it doesn't have a ton of history in it. It's also about 2000 lines with 4 somewhat unrelated test fixtures (multiplexed integration, ring hash, http2 frames, http2 metadata). I wonder if it might makes sense to split these into different test.cc files in a follow up?

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
