### PR TITLE
Revert "stats: add new BoolIndicator stat type (#5813)"

### PR DESCRIPTION
**Pull request by mattklein123**
This reverts commit 67d1eb4474461f41ee4cf388a98043b84f671b1f.

See https://github.com/envoyproxy/envoy/pull/6279

### CODE REVIEW

**Comment by mattklein123** [comment]
@taion809 @fredlas

**Comment by taion809** [comment]
I think this is the right move, one thing to note for the future implementation is that we will need a set of BoolIndicator tests for the prometheus handler in /test/server/html/admin_test.cc and ensure both the metric is a gauge and the type is an int.

Example:
```
# TYPE envoy_server_live gauge
envoy_server_live{} 0
```

**Comment by fredlas** [comment]
SGTM if it's causing problems; it's not yet really needed for anything, and the initial motivation was just to more cleanly express how various stats should move across hot restart.

**Comment by ramaraochavali** [comment]
@mattklein123  Thanks much for reverting this quickly

**Pull request merged**
