### PR TITLE
maintainers: welcome Antonio!

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: low
Testing: he always does!
Docs Changes: yes
Release Notes: no

### CODE REVIEW

**Comment by alyssawilk** [comment]
cc @envoyproxy/maintainers

**Review by antoniovicente — APPROVED** [review]
Woohoo! I'm super excited to increase my level of involvement, commitment to OSS and continue working closely with all of you.

**Review by ggreenway — APPROVED** [review]
Welcome!

**Review by htuch — APPROVED** [review]

**Review by asraa — APPROVED** [review]

**Review by mattklein123 — APPROVED** [review]
:tada: Yay!

**Review by snowp — APPROVED** [review]
Welcome!

**Review by jmarantz — APPROVED** [review]
Awesome!

**Pull request merged**
