### PR TITLE
build: standardize on PY3

### PR DESCRIPTION
**Pull request by mattklein123**
This fixes spurious protobuf rebuilds for me.

Risk Level: Low
Testing: Existing tests
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by moderation** [comment]
I'm pretty sure this is going to unblock some build deps stuff I was working in. Jinja2 update wasn't working with Kafka extension due to PY2 vs. PY3 conflict. Definitely time to kill PY2

**Comment by moderation** [comment]
What about the two locations that contain PY2 overrides - https://github.com/envoyproxy/envoy/search?q=PY2&unscoped_q=PY2 ? May have to check with @zuercher if PY3 will impact the Thift filter.

**Comment by lizan** [comment]
@moderation Host python is fine, which is only used for proto format tools. Kafka and Thrift are the target python configuration which is not forced to PY3 in this PR

**Comment by htuch** [comment]
@mattklein123 can you merge master and push again?

**Comment by mattklein123** [comment]
> What about the two locations that contain PY2 overrides 

Yeah per @lizan I would rather have these covered in other PRs. I don't think there should be any issue moving to PY3 but it's possible the tools might need some fixes.

**Pull request merged**
