### PR TITLE
CVE/http: Fix memory leak in nghttp2 codec

### PR DESCRIPTION
**Pull request by phlax**
Fix memory leak in nghttp2 when it processes pending requests after receiving the GOAWAY frame.

Fix https://github.com/envoyproxy/envoy/security/advisories/GHSA-jfxv-29pc-x22r

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by RyanTheOptimist — DISMISSED** [review]

**Comment by phlax** [comment]
> I'm not sure where it is coming from,

yeah, that was why i wanted to flag it - in case it was showing something undesirable

> but to get this PR unblocked I suggest to temporarily lower the coverage threshold for that file.

yep, will do if the reason/fix is not obvious

**Review by alyssawilk — APPROVED** [review]
the coverage drop makes no sense to me, so in the lamest test ever I added a release assert to the "uncovered" function in b/source/extensions/access_loggers/grpc/http_config.cc and it trips (fails) with and without this patch being applied locally.  I think it's coverage weirdness and I'm comfortable dropping coverage and investigating later.

**Comment by yanavlasov** [comment]
The coverage drop is due to the addition of the new factory method for creating extensions with the listener factory context. I think this was done for the composite filter and some factories with the new code dipped below the limit. Not sure why it is failing now though.

I think just to make progress with the 0-day we can lower the coverage for affected extensions and I can fix it in the followup PRs.

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
