### PR TITLE
http/protocol: uint8_t is defined in cstdint

### PR DESCRIPTION
**Pull request by sitano**
fix compilation issues on Arch and Fedora 32 with Clang

Commit Message: `http/protocol: uint8_t is defined in cstdint`
Risk Level: Low
Testing: None

### CODE REVIEW

**Comment by sitano** [comment]
@phlax the smallest fix from the list of https://github.com/envoyproxy/envoy/issues/29311

**Review by phlax — APPROVED** [review]
lgtm, thanks @sitano for follow up

**Comment by yanavlasov** [comment]
@sitano I think this will need main merge to resolve the error in the golang filter.

**Comment by phlax** [comment]
pushing past flakey CI

**Pull request merged**
