### PR TITLE
Reverts the new HTTP/2 wrapper API to default-disabled

### PR DESCRIPTION
**Pull request by birenroy**
Signed-off-by: Biren Roy <birenroy@google.com>

Commit Message: Reverts the new HTTP/2 wrapper API to default-disabled
Additional Description: A user reports increased memory consumption in #19761
Fixes commit #20095

### CODE REVIEW

**Comment by birenroy** [comment]
/assign @alyssawilk 

Do you think we should try to get an additional repro before re-disabling?

**Comment by mattklein123** [comment]
> Do you think we should try to get an additional repro before re-disabling?

IMO the report here looks well researched and legitimate: https://github.com/envoyproxy/envoy/issues/19761#issuecomment-1079386745. cc @kvcache

I think if you want to try to connect with each other and debug before reverting that's OK with me but given the wide impact of something like this I would rather by cautious and revert. Happy to wait a couple of days though.

**Review by alyssawilk — APPROVED** [review]

**Comment by birenroy** [comment]
@mattklein123 Please approve and merge. Thanks!

**Comment by alyssawilk** [comment]
Sorry was out Friday.
added the "Fixes commit https://github.com/envoyproxy/envoy/pull/20095" since that lets folks know to watch out for regressions (please try to set next time!)

**Pull request merged**
