### PR TITLE
api: freeze of v2 API, cut v4alpha API.

### LINKED ISSUE #10355: Freeze v2 API
As per the stable API verisoning policy, we should ideally be freezing the v2 API additions at EOQ. At this point, any API additions/deprecations would take place in the v3 APIs. To do this, we need to open up `v4alpha` and make `v3` canonical. There should be an escape hatch available for any `v2` changes that are strongly motivated after EOQ.

### PR DESCRIPTION
**Pull request by htuch**
This patch performs a major version freeze and bump by modifying package_version_status, using the tooling developed in #10636. Specifically:

* v2 APIs are frozen (except for where they are the latest in their package history and still active)
* v3 APIs are transitioned to be active
* Candidate v4alpha APIs are generated (not used by Envoy yet)

Fixes #10355

Risk level: medium (entire API's files are modified, visually verified to ensure things look sane, all tests pass)
Testing: CI

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

**Comment by htuch** [comment]
FYI @mattklein123 @lizan. I'm going to be force pushing here etc. until it's ready to review, but this is a snapshot of where we're heading.

**Comment by htuch** [comment]
This is now working for build/test/docs, generated APIs look sane (to me). What remains is cleanup of the Python code and `protoxform_test` tests. Need to merge #10585  as well.

**Comment by Shikugawa** [comment]
@htuch looks good for me only this API changes.

**Comment by htuch** [comment]
@lizan @mattklein123 this is now ready for review for real.

**Comment by lizan** [comment]
@htuch Is it possible to split the tooling part out to another PR?

**Comment by lizan** [comment]
re: CI I think this doubles the format job which now takes 20 minutes, I guess we can split it to two part, format and protoxform. WDYT?

**Comment by htuch** [comment]
@lizan I've corrected a performance problem and it's back to 12m. Will split out the tools diff to a distinct PR.

**Comment by htuch** [comment]
@lizan tools/doc aspect of this PR is now split out in https://github.com/envoyproxy/envoy/pull/10636

**Comment by htuch** [comment]
Closing this out, will do a pure API PR instead.

**Pull request closed without merging**
