### PR TITLE
Revert "docs: Move cve_scan and generation of external dependencies r…

### PR DESCRIPTION
**Pull request by mattklein123**
…st to bazel (#15328)"

This reverts commit 498d65b2fabceebbda9c0b993ba63c127fd16f27.

### CODE REVIEW

**Comment by mattklein123** [comment]
cc @phlax this appears to be breaking CI

**Review by ggreenway — APPROVED** [review]

**Comment by phlax** [comment]
> cc @phlax this appears to be breaking CI

just to confirm my investigataions - i think this wasnt breaking anything in ci, but it was breaking a python module

@mattklein123  am i wrong ? is there a breakage somewhere im not seeing ?

**Comment by mattklein123** [comment]
See https://dev.azure.com/cncf/envoy/_build/results?buildId=68813&view=logs&jobId=1c04237c-5f52-5959-5f83-5522b3556331&j=1c04237c-5f52-5959-5f83-5522b3556331&t=db3f3889-c922-566b-fa2e-4bc4948bc467 for an example job that broke

**Comment by phlax** [comment]
i can see the problem (and i can fix it) but im struggling to understand why this didnt fail in the ci for this PR and afaict was not failing in post-submit

**Comment by mattklein123** [comment]
> i can see the problem (and i can fix it) but im struggling to understand why this didnt fail in the ci for this PR and afaict was not failing in post-submit

That I don't know. :(

**Comment by phlax** [comment]
i guess my initial question was "is this just caused by not merging main"

seeing that it does actually break somethign my question now is more like "why didnt ci tell me this would break something"

ill investigate further before resubmitting

**Comment by phlax** [comment]
added PR #15427 

i can see why it didnt fail - continuing conv on pr...

**Pull request merged**
