### PR TITLE
fix image sha for devcontainer

### PR DESCRIPTION
**Pull request by jbohanon**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] #29484
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by jbohanon** [comment]
cc @phlax

**Comment by phlax** [comment]
hmm @jbohanon seems like our upstream ci must have overwritten the image - it obviously worked originally

confirming locally the change is correct

would you be able to update all of the other instances - you can find them with:

```console
$ git grep 6a6a6
```

**Comment by phlax** [comment]
hmm - wait - something is off here

```console
$ docker buildx imagetools inspect envoyproxy/envoy-build-ubuntu:1f2f7ee78f894859de0fa7a415b0bedde1f6c560
Name:      docker.io/envoyproxy/envoy-build-ubuntu:1f2f7ee78f894859de0fa7a415b0bedde1f6c560
MediaType: application/vnd.oci.image.index.v1+json
Digest:    sha256:6a6a64be3f4e3c4380531ad1624f9419d1fe99dde4e5eeb04e2d538a92f27205
...
```
$ docker buildx imagetools inspect gcr.io/envoy-ci/envoy-build:1f2f7ee78f894859de0fa7a415b0bedde1f6c560
Name:      gcr.io/envoy-ci/envoy-build:1f2f7ee78f894859de0fa7a415b0bedde1f6c560
MediaType: application/vnd.oci.image.index.v1+json
Digest:    sha256:9db54410ba9f8216cac84391ebcfb18a297c2217690c7c77bb050f78f56bb629

```console

```

i think these should match - ill investigate further ...

**Review by phlax — DISMISSED** [review]
seems like they never matched (ive been rebuilding the images _and_ added the shas recently)

i checked against last image before changes (41c5a05d708972d703661b702a63ef5060125c33) and they also differ - i guess just in metadata as they are the same image/s

not sure why this doesnt use dockerhub but perhaps we should switch as it would make maintenance easier

anyhow, lgtm, thanks @jbohanon

**Comment by phlax** [comment]
i think dont add teh comments at least not with hardcoded shas - it will make maintenance a nightmare

**Comment by jbohanon** [comment]
sorry @phlax I pushed as soon as you sent that. I reverted the comments

**Review by phlax — APPROVED** [review]

**Pull request merged**
