### PR TITLE
configs: remove codec:auto from google proxy example (#2824)

### LINKED ISSUE #2824: Remove codec from google proxy example
**Issue Template**

*Remove codec from google proxy example (v2)*

*Description*:
This is supposed to be rarely used as the default is AUTO, and it specifies AUTO.

### PR DESCRIPTION
**Pull request by francisu**
configs: remove codec:auto from google proxy example (#2824)

Description:
As stated in issue #2824 the codec: AUTO is not necessary in v2, since that's the default and otherwise codec should rarely be used. So I imagine a best practice is to not have it.

Risk Level: Low

Testing:
Tested google example config according to documentation.

Docs Changes:
This corresponds (and aligns) to: envoyproxy/data-plane-api#548

Release Notes:
N/A

Fixes #2824

### CODE REVIEW

**Comment by mattklein123** [comment]
@francisu your PR keeps failing TSAN, and @htuch and I have no idea why. I'm looking into it.

**Comment by francisu** [comment]
I'm looking at it too, I just merged upstream master so maybe that will make a difference.

**Comment by mattklein123** [comment]
@francisu hmm. it's passing now. I'm very confused. I can't repro locally either what I was seeing in the TSAN test. Confused.

**Comment by mattklein123** [comment]
OSX flake is unrelated. Merging.

**Pull request merged**
