### PR TITLE
mobile: cleaning up E-M headers for protocol based routing.

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: low
Testing: n/a
Docs Changes: n/a
Release Notes: inline
Part of https://github.com/envoyproxy/envoy/issues/25813

### CODE REVIEW

**Review by jpsim — DISMISSED** [review]
+1 changelog entry?

**Review by RyanTheOptimist — APPROVED** [review]
Wow, nice cleanup! I'm amazed by how many places we were setting the upstream protocol.

**Comment by alyssawilk** [comment]
you're telling me - I kept thinking I found them all then I'd grep for a different case and no.... there's another 12 files to clean up :-P

**Review by jpsim — APPROVED** [review]

**Pull request merged**
