### PR TITLE
qat: fix the pipe callback's return value

### PR DESCRIPTION
**Pull request by soulxu**
Commit Message: qat: fix the pipe callback's return value
Additional Description:
The PR https://github.com/envoyproxy/envoy/pull/34141 added a return value for the file event callback, but it return too early in the QAT code.

Risk Level: low
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Review by alyssawilk — APPROVED** [review]

**Comment by alyssawilk** [comment]
I think you'll have better luck with a main merge now the BES issue is (theoretically) fixed.  feel free to merge once CI is happy

**Comment by soulxu** [comment]
> I think you'll have better luck with a main merge now the BES issue is (theoretically) fixed. feel free to merge once CI is happy

Got it, thanks!

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
