### PR TITLE
do not initiate parent shutdown sequence when hot restart is disabled

### PR DESCRIPTION
**Pull request by ramaraochavali**
Commit Message: do not initiate parent shutdown sequence when hot restart is disabled
Additional Description:
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by mattklein123** [comment]
Is there a reason fro this change? Is it just to avoid confusing logs? Thank you.

/wait-any

**Comment by ramaraochavali** [comment]
Yes. Just to avoid confusing log lines.

**Comment by mattklein123** [comment]
The log is in `void DrainManagerImpl::startParentShutdownSequence()` right? Perhaps just put an early return there to keep the logic closer to where you don't want the code to execute? Thanks.

/wait

**Pull request merged**
