### PR TITLE
fix broken main

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: fix broken main
Additional Description:

seems that main is broken by the #33078 and some other changes.

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@wbpcode i landed the fix from @yanavlasov (#33103 )

there is another separate issue which i suspect will still occur

**Comment by wbpcode** [comment]
@phlax great. I think that fix is better.

**Pull request closed without merging**
