### PR TITLE
backport: tools, github: Add current SOURCE_VERSION writer

### PR DESCRIPTION
**Pull request by dio**
Commit Message: This adds a script to write the current SOURCE_VERSION.

Cherry-picked from:
 - 9dcd8063a93bb7aec2cc271eb3fc05dfa96b177e
 - 8e73e50126094174054c5dcfbef5bacae00af65f
 
Signed-off-by: Dhi Aurrahman <dio@rockybars.com>
  
Additional Description: To provide the script inside the source code tarball for each release version. The next tag will have this, but even before I can use the merged patch to get it, without `curl`-ing directly from https://raw.githubusercontent.com.
Risk Level: N/A
Testing: Manual
Docs Changes: Updated. 
Release Notes: N/A
Platform-Specific Features: N/A

### CODE REVIEW

**Review by phlax — APPROVED** [review]
lgtm, thanks @dio

**Comment by wbpcode** [comment]
Please merge the main to fix the flaky ci.

**Comment by phlax** [comment]
> Please merge the main to fix the flaky ci.

this is a backport - i think ci is just flaky on that branch

/retest

**Comment by wbpcode** [comment]
cc @phlax The ci is flaky because the certs of `ocsp` are expired. So, maybe we should backport the certs refresh first. 🤣

**Comment by phlax** [comment]
ah - yep - i see - yep, lets backport the cert update

**Comment by dio** [comment]
Depends on https://github.com/envoyproxy/envoy/pull/23641.

**Comment by phlax** [comment]
@dio do you want to merge - ci should be good now

**Comment by dio** [comment]
Thanks, @phlax!

**Comment by dio** [comment]
Not sure why `bazel.coverage` takes forever to run :(.

**Comment by dio** [comment]
Thanks for merging, @phlax!

**Comment by phlax** [comment]
> Not sure why bazel.coverage takes forever to run :(.

to do with caching or rather not caching i think

**Pull request merged**
