### PR TITLE
contrib: avoid building unnecessary vpp targets

### PR DESCRIPTION
**Pull request by florincoras**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by florincoras** [comment]
> looks like this needs a couple of fixes (putting back the py hack, maybe removing the now unused `CMAKE_ENABLE_TESTING` cmake var

Interesting, that was working fine locally. Probably some caching issue. 

> 
> overall, looks great - what i would have done when i updated if i had known how

Only got to this solution after fiddling with and retrying locally all options we chatted about. Should've thought about it but I somehow missed it ...

**Review by phlax — APPROVED** [review]
lgtm, thanks for following up @florincoras - really appreciated

ill run a build locally later today and see how it compares. lmk if it throws up any issues on your end

**Comment by florincoras** [comment]
Awesome!! Thank you @phlax, you did all of the heavy lifting! ;-)

**Pull request merged**
