### PR TITLE
tracing: Set span.kind tag when creating client/server spans

### LINKED ISSUE #3435: tracing: Set span.kind tag when creating client/server spans
Currently the zipkin tracer derives the span.kind (or cs/cr/ss/sr annotations) from the tracing config "operation_name" - however the LightStep or other OpenTracing API compatible tracers don't have this tag set.

The proxy needs to explicitly set this tag when creating the tag, along with the other standard OpenTracing tags.

This is a followup issue from #2081.

### PR DESCRIPTION
**Pull request by objectiser**
Signed-off-by: Gary Brown <gary@brownuk.com>

Resolves #3435 

*Description*:
Uses the config "operation name" (Egress/Ingress) to determine whether the OpenTracing span should have the `span.kind` tag of `server` or `client`.

The zipkin tracer has this logic, although it represents the span kind using CLIENT_SEND/RECV and SERVER_SEND/RECV annotations. This PR is just making the OpenTracing tracers have the same level of information, but using the OpenTracing standard `span.kind` tag.

*Risk Level*: Low

*Testing*:
Additional unit tests have been provided.

@mburn Could you take a look at this, to make sure you are ok with the impact on LightStep and dynamic OT impl?

### CODE REVIEW

**Comment by mattklein123** [comment]
@objectiser I think you meant @rnburn so tagging him.

**Comment by rnburn** [comment]
Looks good. 👍

**Comment by objectiser** [comment]
@mattklein123 whoops, thanks :)

**Comment by verysonglaa** [comment]
Hi @objectiser 

Unfortunately this feature is also not yet implemented in opencensus tracer. Would it be alot of work to implement it there as well, so in https://github.com/envoyproxy/envoy/blob/master/source/extensions/tracers/opencensus/opencensus_tracer_impl.cc ? I would do it myself but lack the C++ skill to do it properly.

**Comment by objectiser** [comment]
@verysonglaa Could you create an issue for this? Hopefully I will be able to take a look sometime next week - but otherwise someone else may pick it up.

**Comment by verysonglaa** [comment]
@objectiser , thank you I created #12538

**Pull request merged**
