### PR TITLE
backport 1.15: http: fixing a bug with IPv6 hosts

### PR DESCRIPTION
**Pull request by Shikugawa**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Review by alyssawilk — APPROVED** [review]

**Comment by cpakulski** [comment]
@Shikugawa Would you mind merging release/v1.15 branch to your dev branch? I recently closed 1.15.3 patch and the file containing release notes changed.

**Review by alyssawilk — APPROVED** [review]

**Comment by cpakulski** [comment]
LGTM. Thanks.

**Comment by Shikugawa** [comment]
@cpakulski Can you face this problem, which would encounter when you build components that failed [here](https://dev.azure.com/cncf/envoy/_build/results?buildId=61595&view=logs&jobId=6fde23b8-d050-528a-41c5-ee3fcffe067e&j=6fde23b8-d050-528a-41c5-ee3fcffe067e&t=d3189bca-09a9-55c6-e7ba-8b9ba21848fc)? For example, when you run `bazel test //test/integration:sds_static_integration_test`, it will be failed on the successfully released branch such as `release/1.15`. 
The CI tasks after alyssa approved had also failed.

**Comment by cpakulski** [comment]
@Shikugawa The further back you go with backports, it gets harder. I am investigating why it fails.

**Comment by cpakulski** [comment]
@Shikugawa I figured out why tests started to fail:  certificates used in tests expired. This PR: https://github.com/envoyproxy/envoy/pull/14458 contains renewed certs. Once it it merged to branch 1.15, you can sync your branch and all should be good.

**Review by alyssawilk — APPROVED** [review]
LGTM!

In future can you copy the release notes from the original PR over?  I assume we should merge in things like

Fixing a bug where HTTP parser offsets for IPv6 hosts did not include [] and Envoy assumed it did.
This results in mis-parsing addresses for IPv6 CONNECT requests and IPv6 hosts in fully URLs over HTTP/1.1

Risk Level: low
Testing: new unit, integration tests
Docs Changes: n/a
Release Notes: inline

**Pull request merged**
