### PR TITLE
[Backport 1.22] regex: restoring regex behavior prior to runtime load (#21069)

### PR DESCRIPTION
**Pull request by pradeepcrao**
Commit Message:
Additional Description:
Backport #21069 to 1.22
Risk Level: Low
Testing: New integration test
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by pradeepcrao** [comment]
@alyssawilk, #21056 states that the issue was not reproducible. Could you please confirm that the backport is only required for 1.22?

**Review by alyssawilk — APPROVED** [review]
Thanks!  Yeah it should just be the one release.

**Pull request merged**
