### PR TITLE
repo: Release `1.23.1`

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by lizan — APPROVED** [review]

**Comment by mbana** [comment]
When will this make it into DockerHub? I just tried running:

## amd64 Host

```
$ docker run --rm -it docker.io/envoyproxy/envoy:v1.23.1
Unable to find image 'envoyproxy/envoy:v1.23.1' locally
docker: Error response from daemon: manifest for envoyproxy/envoy:v1.23.1 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

I guess this is expected.

## arm64 Host

```sh
$ uname -a
Linux arm64-oracle 5.15.0-1016-oracle #20-Ubuntu SMP Mon Aug 8 07:08:08 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
$ docker run --rm -it docker.io/envoyproxy/envoy:v1.23.0
/docker-entrypoint.sh: 29: exec: su-exec: Exec format error
$ docker run --rm -it docker.io/envoyproxy/envoy:v1.23.
Unable to find image 'envoyproxy/envoy:v1.23.1' locally
docker: Error response from daemon: manifest for envoyproxy/envoy:v1.23.1 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

**Comment by phlax** [comment]
its published now

**Comment by mbana** [comment]
Thanks.

**Pull request merged**
