### PR TITLE
Update QUICHE from c5d1ed730 to 134dcbea6

### PR DESCRIPTION
**Pull request by birenroy**
https://github.com/google/quiche/compare/c5d1ed730..134dcbea6

```
$ git log c5d1ed730..134dcbea6 --date=short --no-merges --format="%ad %al %s"

2024-06-17 martinduke Fix uninitialized pointer in CLI for moqt chat client.
2024-06-17 bnc Add Balsa tests documenting \r detection behavior.
2024-06-17 martinduke Fix scope of SubscribeWindow argument to fix ASAN error.
2024-06-17 quiche-dev Enabling rolled out flags.
2024-06-15 martinduke Add Object Status to MoQT Object Messages.
2024-06-14 wub Move PacketCollector from `quic_dispatcher.cc` to `quic_buffered_packet_store.h`.
2024-06-14 martinduke MoQT tracking of largest object ID in each group.
2024-06-14 martinduke Send MoQT SUBSCRIBE_DONE when all objects are delivered. Tracks objects published and not yet published separately.
2024-06-13 wub Refactor QuicBufferedPacketStore::EnqueuePacket to take a ReceivedPacketInfo instead of pieces of information from ReceivedPacketInfo.
2024-06-13 wub Enhance the QUIC connection close details when peer address changed before handshake is confirmed, by adding the peer addresses before and after the change.
2024-06-12 quiche-dev Refactor quic's RawPacketComposer to share more code for CMSG with GfeQuicGsoBatchWriter using the QuicMsgHdr class.
2024-06-12 birenroy Fixes handling for DATA frames with padding in combination with Content-Length.
2024-06-12 birenroy Adds test cases for OgHttp2Adapter as a client receiving a response with Content-Length and padding.
2024-06-12 vasilvv Fix MSAN failures in MoQT integration tests.
2024-06-11 vasilvv Implement a very basic MoQT simulator.
2024-06-11 vasilvv Split MoQT simulated endpoints into a separate header file.
2024-06-11 quiche-dev Add `GeoHint` to `BlindSignToken`.
2024-06-11 bnc Set `header_decoding_delay_` before calling methods.
2024-06-10 ericorth No public description
2024-06-10 martinduke Update MoQT to draft-04
2024-06-07 wub Split `QuicConnectionTracer` into two interfaces: - A `QuicPlatformConnectionContext` interface that get notified when a `QuicConnection` becomes active or inactive. - A new smaller `QuicConnectionTracer` that only contains PrintXXX methods.
2024-06-06 dschinazi Disable capsule parsing for failed requests
2024-06-05 quiche-dev Introduce new QUICHE_PROTOCOL_FLAG of type uint32_t
2024-06-04 danzh Limit the number of port migrations a QUIC client will attempt upon path degrading signals. This is to prevent the client from migrating port too frequently, which may cause port exhaustion.
```

Fixes https://github.com/envoyproxy/envoy/issues/34693.

Commit Message:
Additional Description:
Risk Level:
Testing: ran unit and integration tests locally
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
Looks like a memory leak. Is this real?

https://github.com/envoyproxy/envoy/actions/runs/9571210800/job/26387752092

**Comment by birenroy** [comment]
> Looks like a memory leak. Is this real?
> 
> https://github.com/envoyproxy/envoy/actions/runs/9571210800/job/26387752092

Looks like the check passed on re-run. I also could not reproduce with a local run.

**Comment by birenroy** [comment]
Not sure why the `Envoy/Publish and verify` check is failing. It does not appear to be related to this PR.

/retest

**Review by RyanTheOptimist — APPROVED** [review]
LGTM, assuming we can get CI to pass

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
