### PR TITLE
test: increase test coverage of crypto utils

### PR DESCRIPTION
**Pull request by agrawroh**
## Changes

This PR add some additional tests for `importPublicKey()` and `verifySignature()` methods to increase the unit test coverage of the crypto utils class. 

**Old:** 88.1% | **New:** 95.5%

Screenshot 2023-10-28 at 17 35 31

[Coverage Report Link](https://storage.googleapis.com/envoy-pr/444c1b8/coverage/index.html)

Commit Message: increase test coverage of crypto utils.
Additional Description: added additional tests for `importPublicKey()` and `verifySignature()` to increase the unit test coverage of crypto utils.
Risk Level: Very Low
Testing: Yes
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by alyssawilk — APPROVED** [review]
Holy cow this is awesome!  Thanks so much for improving Envoy test coverage!!

**Comment by agrawroh** [comment]
@alyssawilk Looks like one of the checks are stuck in "pending" and I don't see an option to manually re-trigger it.

**Pull request merged**
