### PR TITLE
Update owner file

### PR DESCRIPTION
**Pull request by tyxia**
ext_proc is now heavily used in our projects. Update the file per offline conversation, @pradeepcrao is not working closely on any projects in this domain. Also, update ext_authz as discussed offline.

### CODE REVIEW

**Review by pradeepcrao — APPROVED** [review]
LGTM

**Review by yanavlasov — APPROVED** [review]

**Comment by tyxia** [comment]
/retest 

totally irrelevant failure :)

**Review by htuch — APPROVED** [review]

**Pull request merged**
