### PR TITLE
wasm: update Proxy-Wasm C++ host to the latest (2021-08-02).

### PR DESCRIPTION
**Pull request by mathetake**
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

Depends on https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/183

### CODE REVIEW

**Comment by mathetake** [comment]
ping @moderation for dep:)

**Review by PiotrSikora — APPROVED** [review]
Thanks!

It looks that coverage is broken because of https://github.com/envoyproxy/envoy/pull/17564.

**Comment by mathetake** [comment]
made a PR for coverage failure https://github.com/envoyproxy/envoy/pull/17573

**Pull request merged**
