### PR TITLE
Add OTLP proto dependencies

### PR DESCRIPTION
**Pull request by itamarkam**
Signed-off-by: Itamar Kaminski <itamark@google.com>

Commit Message: Add a dependency on OTLP protos.
Additional Description: This will be used as part of the [OTLP logger](https://github.com/envoyproxy/envoy/issues/13801)
Risk Level: Low (only adding a dependency)
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by moderation** [comment]
The dependency itself looks OK but do we want to bring this into the project without the code to use it?

**Comment by itamarkam** [comment]
> The dependency itself looks OK but do we want to bring this into the project without the code to use it?

I just thought I'd split it, but I'll convert this to a draft until [PR #14469](https://github.com/envoyproxy/envoy/pull/14469) is in and I'll add the code that uses this dependency. Thanks!

**Comment by yanavlasov** [comment]
Looks like master merge was not right.

**Pull request closed without merging**
