### PR TITLE
repokitteh: Add `/coverage` command

### PR DESCRIPTION
**Pull request by phlax**
Similar to how repokitteh works for docs currently, this PR will print the coverage link if either the title of the Pr starts with `coverage: ` or if a comment has a line starting `/coverage`

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @tyxia

**Review by tyxia — APPROVED** [review]
It is a great utility tool to have. Thank you  for adding it!

**Comment by alyssawilk** [comment]
@lizan this is over to you for final pass

**Comment by phlax** [comment]
@htuch i think this one is pretty useful, and not likely to break anything, if you get a moment to review

**Comment by htuch** [comment]
Yeah, this is great. Out of curiosity, why not unconditionally have RK write the coverage link? It's pretty useful during any review and might make it generally lower activation energy to have folks take a quick peak.

**Review by htuch — APPROVED** [review]
That said, TBH I should just add an Omnibox thing for this locally :P Up to you.

**Comment by phlax** [comment]
> why not unconditionally have RK write the coverage link?

it would generate too much noise - also the same for docs etc - its not always relevant i think

**Comment by phlax** [comment]
i think the command is useful because it draws attention to it

that said - every build creates docs, outputs coverage, etc - im wondering again about my original plan with docs which was to put a link the ci box (at the bottom of pr - eg with test results)

**Comment by phlax** [comment]
> Yeah, can a link in the CI box work in GH as an action?

i think it can be triggered by anything with gh creds

**Pull request merged**
