### PR TITLE
[backport/1.23] Backport stack

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by wbpcode** [comment]
the new websocket example was failed.

**Comment by phlax** [comment]
seems like i inadvertently committed the certs when i was fixing it - hopefully works now

**Comment by phlax** [comment]
arggh - i see what the problem is - its invoking buildkit - which works for me locally but not in the examples here - ill fix

**Comment by phlax** [comment]
@wbpcode this should be good to land now i think

**Review by wbpcode — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
