### PR TITLE
deps: Bump `io_hyperscan` -> 5.4.2

### LINKED ISSUE #26849: Newer release available `io_hyperscan`: v5.4.2 (current: 5c724f7)
Package Name: io_hyperscan@5c724f73d1
Current Version: 5c724f7@2023-03-23
Available Version: v5.4.2@2023-04-19
Upstream releases: https://github.com/intel/hyperscan/releases

### PR DESCRIPTION
**Pull request by phlax**
Fix #26849 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@zhxie my read of the CI run here is that cmake must be using multiple cores

image

this exemplifies the problem i mentioned offline where for these cmake builds the arm machine builds locally much faster whereas the x86 sends the job off to a lesser-cored RBE worker and waits

**Comment by phlax** [comment]
you can see the same effect (only worse) with the clang_tidy job as it also generates the compile db which i think triggers a rebuild of hyperscan https://dev.azure.com/cncf/envoy/_build/results?buildId=137630&view=results

mostly this is not being recompiled - but if we change anything about the build env, change the version, and on release branches then it does and (along with other cmake builds) causes very long ci times

**Review by mattklein123 — APPROVED** [review]

**Comment by phlax** [comment]
ive just realized that hypsercan is not building at all on arm - which explains why its quicker in this case

**Pull request merged**
