### PR TITLE
http: refactor out stream rate limiter to common

### PR DESCRIPTION
**Pull request by nitgoy**
Commit Message: Refactor out stream rate limiter class from the fault filter to common. This enables the code to be shared with other extensions such as the bandwidth limit filter. The change is just simple refactoring and shouldn't affect/be visible to users.
Additional Description:
Risk Level: Low
Testing: All unit tests passed.
Docs Changes: None

### CODE REVIEW

**Comment by yanavlasov** [comment]
Thanks for the PR. Looks like you need to run `./tools/code_format/check_format.py fix` to fix code forma errors.

**Comment by nitgoy** [comment]
> Thanks for the PR. Looks like you need to run `./tools/code_format/check_format.py fix` to fix code forma errors.

I'm having some permission issues running that script today. Working on fixing them.

**Comment by nitgoy** [comment]
> Thanks for the PR. Looks like you need to run `./tools/code_format/check_format.py fix` to fix code forma errors.

@yanavlasov Addressed the format issue. Any idea about the current presubmit (examples) failure? It doesn't seem related to my changes. Looks like disk ran out of space or something.

**Comment by ggreenway** [comment]
@nitgoy a fix for the verify-examples CI job is in main now; merge main into this PR and it should pass.

**Comment by yanavlasov** [comment]
Thanks for refactoring this. Would it be possible to extract unit tests for the `StreamRateLimiter` class from the `test/extensions/filters/http/fault/fault_filter_test.cc` ? It may need some refactoring as well. Otherwise we now have some common class that is tested by an extension.

**Comment by nitgoy** [comment]
Hi @yanavlasov. sorry for the long wait but I just got the chance to finalize the changes. Can you help to reopen the PR? I'm not able to see that option on my side.

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
