### PR TITLE
Remove support for hidden_envoy_deprecated_hosts

### PR DESCRIPTION
**Pull request by tyxia**
- Remove the code related to `hidden_envoy_deprecated_hosts`
- Remove the helper function `translateClusterHosts()` which is used to translated hosts to load_assignment and becomes redundant now.
- Modify the test to not add deprecated hosts.

Note to reviewer: I also removed the RELEASE_ASSERT for deprecated_hosts in utility.cc, which could still be useful for asserting the regression. Please let me know if you want to keep them.

Signed-off-by: Tianyu Xia <tyxia@google.com>

Risk Level: Low
Testing:  All tests locally (i.e. bazel test //test/...)

### CODE REVIEW

**Comment by daixiang0** [comment]
Is it marked as deprecated in docs?

**Comment by tyxia** [comment]
> Is it marked as deprecated in docs?

Hi, 
+ @htuch 

I am not sure if this is documented specifically. My understanding is that all the fields have `hidden_envoy_deprecated` are deprecated in xD3 V3. Also, the variable naming itself and code indicate they are deprecated: we can see we already have the asserts to make sure this `hidden_envoy_deprecated_hosts` is not in use. (i.e. Assert in test/config/utility.cc).

**Comment by htuch** [comment]
Yes, this has been long deprecated and is no longer available in v3.

**Review by htuch — DISMISSED** [review]
Awesome, thanks!

**Comment by tyxia** [comment]
> Awesome, thanks!

Thanks for review, Harvey! There was a CL failure introduced by my last minute exception string update. Sorry I didn't catch/run it locally (I thought it was just string message update).

The other failure in CI just seems to be the flakiness of the health_check_integration test itself. 
I checked the recent history of envoy pre-submit here(https://dev.azure.com/cncf/envoy/_build?definitionId=5&_a=summary). This test failure has happened quite often. 

Please take another look. Thanks!

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Review by zuercher — APPROVED** [review]

**Pull request merged**
