### PR TITLE
http: unifying grpc local reply logic

### PR DESCRIPTION
**Pull request by alyssawilk**
Additional Description:
Prior to this PR, if a non-gRPC request came in to Envoy, filter A turned it into a gRPC request, filter B switched it back, the response sent would be a gRPC response if sent from A, and a non-gRPC response if sent from B, and maybe gRPC maybe not if sent by the router or HCM (depending on the current state of the headers).

This seems unnecessarily complex as all response always traverse the full filter chain, so this PR unifies the response based on the original downstream request.  If a request comes in as gRPC and is transformed to not-gRPC, sendLocalReply will now always send a gRPC response.  If a request comes in as not gRPC and is transformed to gRPC, sendLocalReply will always send a non-gRPC response.

Risk Level: medium (changes to L7 processing)
Testing: gRPC json test reflects plaintext response
Docs Changes: n/a
Release Notes: inline
Runtime guard: envoy.reloadable_features.unify_grpc_handling

### CODE REVIEW

**Comment by alyssawilk** [comment]
@snowp you up for first pass?  This was motivated by that sendLocalReply clean up we both want and can't do for 6 months.
I'll tag Matt once it has your OK :-)

**Review by snowp — DISMISSED** [review]
Thanks this looks right to me. Do we want a HCM/FM test that explicitly tests this or does the transcoder test suffice?

**Comment by alyssawilk** [comment]
I'm fine with the transcoder test but LMK if you want a separate unit test.

**Review by mattklein123 — APPROVED** [review]
Nice cleanup!

**Pull request merged**
