### PR TITLE
Promote tyxia to maintainer status

### PR DESCRIPTION
**Pull request by yanavlasov**
Per Slack discussion

### CODE REVIEW

**Review by tyxia — APPROVED** [review]
Thank you! I feel honored and excited!

**Review by adisuissa — APPROVED** [review]
Welcome Tianyu!

cc @envoyproxy/envoy-maintainers

**Comment by soulxu** [comment]
@tyxia congratulations!

**Review by soulxu — APPROVED** [review]

**Review by nezdolik — APPROVED** [review]

**Review by KBaichoo — APPROVED** [review]
Congrats 🥳

**Pull request merged**
