### PR TITLE
proto: correct go_package of contrib

### PR DESCRIPTION
**Pull request by howardjohn**
Commit Message: proto: correct go_package of contrib
Additional Description:
This fixes up the go_package descriptor on contrib/ protos. I am not sure how the bazel protoc stuff works, but standard proto compiler seems trip up on this being incorrect, and generate invalid imports

Risk Level: Low
Testing: Manual
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by kyessenov** [comment]
There's a proto validator that probably needs to be updated. Otherwise, LGTM.

**Comment by howardjohn** [comment]
> There's a proto validator that probably needs to be updated. Otherwise, LGTM.

Thanks, found it and updated it

**Review by kyessenov — APPROVED** [review]
Please fix the CI, and then we can merge:

```
-    options.go_package = "".join([
-        "github.com/envoyproxy/go-control-plane/",
-        golang_package_base, golang_package_name
-    ])
+    options.go_package = "".join(
+        ["github.com/envoyproxy/go-control-plane/", golang_package_base, golang_package_name])
```

**Comment by kyessenov** [comment]
Not quite:
```
-    options.go_package = "".join([
-        "github.com/envoyproxy/go-control-plane/", golang_package_base, golang_package_name])
+    options.go_package = "".join(
+        ["github.com/envoyproxy/go-control-plane/", golang_package_base, golang_package_name])
```

**Comment by howardjohn** [comment]
> ["github.com/envoyproxy/go-control-plane/", golang_package_base, golang_package_name])

Thanks! I am a bit slow :slightly_smiling_face:

**Review by kyessenov — APPROVED** [review]

**Pull request merged**
