### PR TITLE
mobile: Don't turn on GRO for Apple

### PR DESCRIPTION
**Pull request by abeyad**

### CODE REVIEW

**Comment by abeyad** [comment]
@RyanTheOptimist

**Review by RyanTheOptimist — APPROVED** [review]
LGTM but should we update release notes and/or link to an issue which explains the motivation?

**Comment by abeyad** [comment]
> LGTM but should we update release notes and/or link to an issue which explains the motivation?

Actually, I'm going to close this one... we already have checks to ensure we don't use UDP GRO if the platform doesn't support it (e.g. https://github.com/envoyproxy/envoy/blob/e4d5ceb3d3a620b809a6ef26c1e6f738f2547cbf/source/common/network/utility.cc#L752), so there's no reason to add this check here as well.  Instead, we should let the platform decide if it supports UDP GRO or not.

**Pull request closed without merging**
