### PR TITLE
network: Refactor Network::Utility functions

### PR DESCRIPTION
**Pull request by abeyad**
1. Wraps non-Utility-class functions in the anonymous namespace.
2. Moves different readFromSocket modes (GRO, mmsg) to separate functions to improve readability.

This change is a no-op in terms of functionality/behavior; it's a straightforward refactor.

### CODE REVIEW

**Comment by alyssawilk** [comment]
hmmm, I agree that moving for namespace reasons is cleaner but I tend to think moving code location for namespacing isn't worth losing the git history for.  Throwing over to @lizan for a second opinion

**Comment by abeyad** [comment]
> hmmm, I agree that moving for namespace reasons is cleaner but I tend to think moving code location for namespacing isn't worth losing the git history for. Throwing over to @lizan for a second opinion

I think that's a fair argument.  I can just make multiple anonymous namespaces in the file, wrapping anonymous namespace around the function(s) that should have it but don't currently.  

What do you think about refactoring `readFromSocket` into 3 separate functions, one for each case (GRO, mmsg, regular recvmsg)?  That will also lose the `git blame`, but also make the code a bit easier to read IMO.

**Comment by lizan** [comment]
I don't think the lose of history is huge as you can still track that with a few more steps. So I think 2. is fine but I would just wrap unnamed namespace multiple times for 1.

**Comment by abeyad** [comment]
> I don't think the lose of history is huge as you can still track that with a few more steps. So I think 2. is fine but I would just wrap unnamed namespace multiple times for 1.

thanks for the feedback!  Done, PTAL.

**Review by lizan — APPROVED** [review]

**Pull request merged**
