### PR TITLE
tools: slack notification for first pass reviewers

### PR DESCRIPTION
**Pull request by botengyao**
I assume this change will let first-pass reviewers receive slack notifications.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by botengyao** [comment]
@silverstar194, @nezdolik, @daixiang0, @tyxia for the double check of slack user ids.

**Review by tyxia — APPROVED** [review]
AFAIR, `/assign-from @envoyproxy/first-pass-reviewers` worked before.

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
