### PR TITLE
The ORIGINAL_DST_LB load balancing policy is deprecated, use CLUSTER_PROVIDED policy instead when configuring an original destination cluster.

### PR DESCRIPTION
**Pull request by tyxia**
Signed-off-by: Tianyu Xia <tyxia@google.com>

Risk Level: low
Testing: bazel test //test/...

### CODE REVIEW

**Review by asraa — APPROVED** [review]
Sorry about the wait, I was OOO. Changes LGTM

**Comment by tyxia** [comment]
> Sorry about the wait, I was OOO. Changes LGTM

No worries at all. Thanks for the review!

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
