### PR TITLE
kafka: upgrade to kafka 3.3.1

### PR DESCRIPTION
**Pull request by adamkotwasinski**
Commit Message: kafka: upgrade to kafka 3.3.1
Additional Description: upgrade protocol files to 3.3.1
The extra python code is caused by the fact that at least one Kafka message spec file uses pure-language booleans (like [here](https://github.com/apache/kafka/blob/3.3.1/clients/src/main/resources/common/message/UpdateFeaturesRequest.json#L37)) instead of stringified-booleans (like [here](https://github.com/apache/kafka/blob/3.3.1/clients/src/main/resources/common/message/DescribeConfigsRequest.json#L38)).
Risk Level: Low
Testing: automated + manual ([link](https://github.com/adamkotwasinski/envoy-kafka-tests/pull/5))
Docs Changes: minor version bump in filter descriptions
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by adamkotwasinski** [comment]
DRAFT,
need to verify new requests manually (and this might take me into next week unfortunately due to other work)

**Comment by adamkotwasinski** [comment]
need one more week, sorry :(

**Comment by adamkotwasinski** [comment]
Ready for review! (sorry it took so long)

**Review by mattklein123 — APPROVED** [review]

**Comment by adamkotwasinski** [comment]
Thank you!

**Pull request merged**
