### PR TITLE
network: remove weell_known files

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long Dai <long0dai@foxmail.com>

Commit Message:

Remove well_known_names in netowrk field, part of #7238

Additional Description:
Risk Level:Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by jmarantz** [comment]
Probably you want to 'merge main' given that I just merged your other PR.

I'll assign a maintainer once this is passing CI.

**Comment by daixiang0** [comment]
@jmarantz Hi, I have trouble in this error:
```
./source/extensions/common/sqlutils/sqlutils.h:5:10: error: 'include/sqlparser/SQLParser.h' file not found [clang-diagnostic-error]
#include "include/sqlparser/SQLParser.h"
         ^
/build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/source/extensions/filters/network/mysql_proxy/mysql_config.h:22:3: error: use '= default' to define a trivial default constructor [modernize-use-equals-default,-warnings-as-errors]
  MySQLConfigFactory() : FactoryBase(MySQL_Proxy) {}
  ^                                               ~~
                                                  = default;
```

I do not change deps about sql :(

**Comment by daixiang0** [comment]
@phlax now it can not use prefix to detect extension test, could I remove it directly?

**Comment by phlax** [comment]
@daixiang0 are you still working on this ?

**Comment by daixiang0** [comment]
I am still looking for a way to fix clang error.

**Pull request closed without merging**
