### PR TITLE
dns: abstraction c-ares pending resolution

### PR DESCRIPTION
**Pull request by Shikugawa**
Signed-off-by: Shikugawa <rei@tetrate.io>

Commit Message: dns: abstraction c-ares pending resolution
Additional Description: The purpose of this abstraction is to make the resolution process as common as possible when adding support for SRV query lookup in c-ares. With this abstraction, starting a pending resolution is as simple as calling `startResolution()`. The introduction of this function is the core of this refactor, and the implementation of `startResolution()` in the pending resolution object for SRV queries also simplifies the process of `DnsResolverImpl::resolve()`. Also, the DNS Response structure is abstracted by one level, and it can store the resolution of A/AAAA/SRV queries.
Risk Level: Low
Testing: N/A
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

Related with #19091

### CODE REVIEW

**Comment by yanavlasov** [comment]
II think the change looks fine. I have one concern is that now the code that makes A/AAAA queries expects A/AAAA responses. I could not get it through the code review what happens if the server responds with SRV response (i.e. due to a bug or maliciously). Will we put SRV response in the variant and crash when trying to read it as a different type?

/wait-any

**Comment by Shikugawa** [comment]
> II think the change looks fine. I have one concern is that now the code that makes A/AAAA queries expects A/AAAA responses. I could not get it through the code review what happens if the server responds with SRV response (i.e. due to a bug or maliciously). Will we put SRV response in the variant and crash when trying to read it as a different type?

Yes. I expect to receive only A/AAAA record in this PR. The behavior to accept SRV records is out of scope. It will be added [here](https://github.com/envoyproxy/envoy/pull/19091) after this PR merged.

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
