### PR TITLE
mobile: Adds support for setting network thread priority in the C++ API

### PR DESCRIPTION
**Pull request by abeyad**
A new method, `setNetworkThreadPriority`, is added to the EngineBuilder, which enables the user to set the thread priority of the Envoy Mobile engine thread.

The thread priority is set using the setpriority() system call, which takes in "nice" values in the range of -20 to 19, where -20 is the highest priority and 19 is the lowest priority.

### CODE REVIEW

**Comment by abeyad** [comment]
@fredyw this should be ready for review now

**Review by fredyw — APPROVED** [review]
Nice!

**Pull request merged**
