### PR TITLE
wasm: remove redundant xds attributes

### PR DESCRIPTION
**Pull request by kyessenov**
Change-Id: I152e259f3f8e5f69463a64fedce4181ce606824b

Commit Message: Remove attributes that were marked as deprecated in https://github.com/envoyproxy/envoy/commit/ff991f3454b426bfec49c752d1e7ffbafa9fdd76. This improves the alignment of `get_property` ABI with the generic attribute support in Envoy in CEL, for example, and simplifies the implementation.

Additional Description:
Risk Level: low, experimental filter, advanced warning to stop using attributes was given
Testing: updated
Docs Changes: yes
Release Notes: yes

### CODE REVIEW

**Comment by tyxia** [comment]
/assign @mpwarres 

based on CODEOWNER

**Comment by tyxia** [comment]
Side note: @kyessenov @alyssawilk  looks like WSAM doesn't have maintainer sponsor currently given Lizan has left? https://github.com/envoyproxy/envoy/blob/main/CODEOWNERS#L106-L116

**Comment by kyessenov** [comment]
I'm willing to sponsor the improvements to Wasm, as previously discussed.

**Review by mattklein123 — APPROVED** [review]

**Review by mpwarres — APPROVED** [review]

**Pull request merged**
