### PR TITLE
redis: add BLPOP BRPOP command support

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Loong Dai <loong.dai@intel.com>

Commit Message: add BLPOP BRPOP command support
Additional Description:
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by daixiang0** [comment]
Test at local:
```
root:[redis]$ redis-cli -h localhost -p 1999 DEL list1 list2
(integer) 0
root:[redis]$ redis-cli -h localhost -p 1999 RPUSH list1 a b c
(integer) 3
root:[redis]$ redis-cli -h localhost -p 1999 BLPOP list1 list2 0
1) "list1"
2) "a"
root:[redis]$ redis-cli -h localhost -p 1999 DEL test
(integer) 0
root:[redis]$ redis-cli -h localhost -p 1999 BLPOP test 1
(nil)
root:[redis]$ redis-cli -h localhost -p 1999 BLPOP test 0
(error) upstream failure
```

Multiple keys and blocking behavior with non-zero timeout work.

For the block indefinitely case, let me dig.

**Comment by mattklein123** [comment]
The way you have implemented it as a simple command multiple keys don't work. It needs a special implementation like mget.

**Comment by daixiang0** [comment]
Thanks a lot, I will look at it.

BTW, I use Envoy at local as Redis proxy and it can work with multiple keys:
```
root:[redis]$ redis-cli -h localhost -p 1999 DEL list1 list2
(integer) 0
root:[redis]$ redis-cli -h localhost -p 1999 RPUSH list1 a b c
(integer) 3
root:[redis]$ redis-cli -h localhost -p 1999 BLPOP list1 list2 0
1) "list1"
2) "a"
```
I create key `list1` and try pop key `list1` and `list2`, it returns.
What do you mean about "multiple keys"?

**Comment by daixiang0** [comment]
Sure, I convert this to draft, and back when I think of a solution.

**Comment by Jacobien1** [comment]
Hello can I know how to use this repository at my local. and how to make a docker image from it please

**Pull request closed without merging**
