### PR TITLE
async_client: Fix yoda condition

### PR DESCRIPTION
**Pull request by tyxia**
Coding style clean up, non-yoda style is generally preferred and consistent with Envoy code base.

### CODE REVIEW

**Comment by tyxia** [comment]
/assign @wbpcode 

As this PR touches tracing/span code

**Review by ggreenway — APPROVED** [review]

**Review by wbpcode — APPROVED** [review]

**Comment by wbpcode** [comment]
Could you kick the ci with an empty commit. I can re-run the azure jobs. But cannot do that to the github workflow.

**Comment by tyxia** [comment]
@phlax  Looks like `retest` is not working and I have multiple PRs run into this issue.

Could you take a look when you have time (I know you are busy with security release now) :) Thank you!

**Comment by phlax** [comment]
seems to be working again

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
