### PR TITLE
quic: allow port migration to config the number of timeouts needed to trigger path degrading

### PR DESCRIPTION
**Pull request by RenjieTang**
Commit Message: allow port migration to config the number of timeouts needed to trigger path degrading
Additional Description:
Risk Level: Low
Testing: Integration tests
Docs Changes: api/envoy/config/core/v3/protocol.proto
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Review by ggreenway — APPROVED** [review]
LGTM.

@markdroth can you review API please?

**Comment by RyanTheOptimist** [comment]
@markdroth ping. can you please review the small API changes here?

**Review by markdroth — COMMENTED** [review]
/lgtm api

**Pull request merged**
