### PR TITLE
mobile/deps: Bump `rules_detekt` -> 0.8.1.2

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
this is required to update `rules_proto`

**Review by fredyw — APPROVED** [review]
Thanks!

**Comment by fredyw** [comment]
A temporary fix https://github.com/envoyproxy/envoy/pull/35345 was merged. Please rebase.

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
