### PR TITLE
add scaled timeout docs faq

### PR DESCRIPTION
**Pull request by saiskee**
Signed-off-by: Keerthan Ekbote <saiskee@gmail.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message: Add scaled timeout docs.
Additional Description: Adds section about scaled timeout to FAQ docs.
Risk Level: low
Testing: --
Docs Changes: Timeout FAQs - scaled timeouts
Release Notes: --
Platform Specific Features: --

### CODE REVIEW

**Comment by phlax** [comment]
hi @saiskee this is failing due to trailing whitespace

you probably want to configure your editor to ensure

- no trailing whitespace
- newline at end of all files
- no mixed tab and space indents (ie only spaces)

**Comment by phlax** [comment]
@saiskee can you fix the format issue please

docs are rendered here - https://storage.googleapis.com/envoy-pr/16271/docs/index.html

@akonradi could you take a look at the docs that are added please

**Review by akonradi — CHANGES_REQUESTED** [review]

**Review by akonradi — APPROVED** [review]
Sorry for dropping the ball. LGTM!

**Review by phlax — APPROVED** [review]
lgtm, thanks @saiskee

**Pull request merged**
