### PR TITLE
[extension inplace change the ImmediateResponse::body type from string to bytes

### PR DESCRIPTION
**Pull request by stevenzzzz**
Commit Message: inplace change the ImmediateResponse::body type from string to bytes
Additional Description: in issue https://github.com/envoyproxy/envoy/issues/32071 Folks found the immediateResponse::body was a string, which fails Envoy ext_proc filter to receive a non-utf8 payload 
Risk Level: LOW  (the in-place type change only drops the utf8 verification in generated code).
Testing: existing tests. 
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!
Will leave to @wbpcode for API review and !Googler review.

**Comment by wbpcode** [comment]
cc @adisuissa This is fine to me. But is this OK from the perspective of API policy? It change the field type directly?

cc @envoyproxy/api-shepherds

**Comment by adisuissa** [comment]
> cc @adisuissa This is fine to me. But is this OK from the perspective of API policy? It change the field type directly?
> 
> cc @envoyproxy/api-shepherds

There was a discussion in #32071 and we got some buy-in, but if anyone in @envoyproxy/api-shepherds disapproves, then please do so soon :)

**Comment by wbpcode** [comment]
It should be fine for C++ xDS client. But may be a trouble for others. The only one well-known client should be gRPC. So, I think we should let @markdroth to check this.

I just found that @markdroth has no envoy-review activities recently. If there is no objection from mark after tomorrow, then let do that in current way. WDYT?

**Comment by stevenzzzz** [comment]
Thanks @wbpcode 

Ping @markdroth 

I am not sure of any prod use of ext_proc in other languages than C++, worth checking.

**Pull request merged**
