### PR TITLE
WiP: Add internal listener 

### PR DESCRIPTION
**Pull request by lambdai**
Commit Message:
Add the listener for internal address.
This PR provide the add/remove functionality but the connection establishment to internal listener is not added yet.

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by alyssawilk** [comment]
@lambdai is this ready for review, or will you remove the draft status when it is?

**Comment by lambdai** [comment]
> @lambdai is this ready for review, or will you remove the draft status when it is?

@alyssawilk Thank you for watching this! This PR is too big to review so the first part should be #16763. WDTY?

**Comment by junr03** [comment]
@lambdai given you are breaking this PR into smaller ones, I am going to close this one. The maintainers are trying to keep PR assignment fresh, so we want to close PRs that don't have active development.

**Comment by lambdai** [comment]
> @lambdai given you are breaking this PR into smaller ones, I am going to close this one. The maintainers are trying to keep PR assignment fresh, so we want to close PRs that don't have active development.

I see. Thank you for letting me know

**Pull request closed without merging**
