### PR TITLE
router: remove do_not_await_headers_on_upstream_timeout_to_emit_stats flag (#23594)

### PR DESCRIPTION
**Pull request by agrawroh**
This PR removes the reloadable flag `do_not_await_headers_on_upstream_timeout_to_emit_stats` from the `router` which was introduced in [this](https://github.com/envoyproxy/envoy/pull/20072) PR.

**Commit Message:** Remove reloadable flag `do_not_await_headers_on_upstream_timeout_to_emit_stats`.
**Additional Description:** This PR removes the reloadable flag `do_not_await_headers_on_upstream_timeout_to_emit_stats` which was introduced in [this](https://github.com/envoyproxy/envoy/pull/20072) PR. (**Fixes**: https://github.com/envoyproxy/envoy/issues/23594)
**Risk Level:** Very Low
**Testing:** N/A
**Docs Changes:** N/A
**Release Notes:** Added the removal notice for the runtime guard `do_not_await_headers_on_upstream_timeout_to_emit_stats` in the docs.
**Platform Specific Features:** N/A

**Signed-off-by:** Rohit Agrawal <rohit.agrawal@databricks.com>

### CODE REVIEW

**Comment by agrawroh** [comment]
@alyssawilk Could you please take a look if you have some free time?

**Review by wbpcode — APPROVED** [review]
LGTM. Thanks.

**Review by alyssawilk — APPROVED** [review]

**Comment by phlax** [comment]
ill cancel and restart the coverage job ...

**Pull request merged**
