### PR TITLE
build: upgrade to C++17

### LINKED ISSUE #9091: build: upgrade to C++17
We've discussed this in the community meeting in June. Now the Google C++ Style Guide is updated to C++17 too, so I guess it is about the right timing to do. Any objections? If so what is the toolchain you use can't support C++17?

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

Description:
Risk Level: Med
Testing: CI
Docs Changes: N/A
Release Notes:
Fixes #9091

### CODE REVIEW

**Comment by kyessenov** [comment]
Hey, let me know how best to patch CEL OSS build. copts is added via copybara, so I can change it easily.

**Comment by mattklein123** [comment]
Have we confirmed this will work for Envoy Mobile? cc @keith @goaway @junr03. I think not having filesystem is fine on that platform, but we do need to not run into potential runtime issues if for example the C++ stdlib is dynamically linked on that platform (I'm not sure if it is or it isn't).

**Comment by lizan** [comment]
That's why this is draft, I haven't even confirm on all CI yet.

Based on my research iOS and Android should be fine with C++17 (without filesystem on iOS yet), but yeah need @keith @junr03 @goaway to confirm.

**Comment by lizan** [comment]
@kyessenov Thanks, yeah I'm not intended to merge with the patch and will sync with you for that.

**Comment by junr03** [comment]
We have not verified yet. I can work with @goaway and @keith to do so for both platforms. @lizan what is your timeline for upgrading? Just so I know how to prioritize this.

**Comment by keith** [comment]
Definitely worth a try with enovy-mobile

**Comment by lizan** [comment]
@junr03 I'm out next week, so the week after?

**Comment by lizan** [comment]
@junr03 @keith have you tried with envoy-mobile?

**Comment by junr03** [comment]
@lizan we have not tried yet. @goaway and I will do so this week.

**Comment by junr03** [comment]
@lizan I tried building yesterday and faced some challenges that make me doubt the feasibility of updating as we stand. 

For instance, now that abseil's optional points to std we depend on iOS versions to actually support it. In the <optional> case iOS 12+ is needed, but Lyft and Envoy Mobile need to support previous versions.

@goaway suggested us jumping on a quick call to sync on this and get some resolution. Do you mind if I DM you and we arrange something?

**Comment by lizan** [comment]
@junr03 yeah sure just ping me on Slack

**Comment by lizan** [comment]
@junr03 @goaway 
Seems abseil offers backward compatibility for that if you `__ENVIRONMENT_IPHONE_OS_VERSION_MIN_REQUIRED__` is defined:
https://github.com/abseil/abseil-cpp/blob/63ee2f8877915a3565c29707dba8fe4d7822596a/absl/base/config.h#L425-L444

https://github.com/abseil/abseil-cpp/issues/207

Will that work for Envoy mobile?

**Comment by junr03** [comment]
@lizan thanks for suggesting, I did not see that in my own exploration. Let me try and get back to you.

**Comment by junr03** [comment]
For posterity: a couple weeks ago I tried @lizan's suggestion above and compiled Envoy Mobile successfully for iOS. However, there were a couple runtime issues (which in honesty I did not dig into due to lack of time). 

Instead, @lizan, @goaway, and I had a conversation about prioritization and timeline for getting C++17 support into Envoy and hence Envoy Mobile. The team at Lyft (Envoy Mobile maintainers) is working steadfast for a production release of Envoy Mobile, and thus has few resources to spare. Given that there is not an urgent forcing function to upgrade @lizan agreed that we could deprioritize bringing C++17 support for several weeks. The Envoy Mobile team would have more spare cycles to resolved remaining unknowns sometime in late march. 

If anyone reading this PR has any concerns or needs that are addressed by a faster upgrade timeline please drop a comment here and let us know what your needs are.

**Comment by lizan** [comment]
@junr03 @goaway any progress on Envoy mobile side?

**Comment by junr03** [comment]
Unfortunately, no. We have not had the chance to prioritize this. Any changes in timeline for you, i.e., should we prioritize this?

**Comment by lizan** [comment]
This is a blocker of https://github.com/envoyproxy/envoy/issues/10053, but we can explore to make Envoy build under both C++14/17 with compile_time_options.

**Comment by wrowe** [comment]
I'd just like to /bump this issue.

@sunjayBhatia and I are looking to purse the FilesystemImpl in Envoy, ensuring we can grok the error results in a consistent manner, and that we can have utf-8 file-system naming conventions as on Linux. But it seems foolish to attack our pet project without first addressing whether we can get to a uniform std::filesystem ahead of those design decisions.

Can you enumerate the current blockers, @lizan ?

**Comment by lizan** [comment]
@stedsome is working on it.

**Pull request closed without merging**
