### PR TITLE
route: fast return when route matches failed

### PR DESCRIPTION
**Pull request by soulxu**
Signed-off-by: He Jie Xu <hejie.xu@intel.com>

Commit Message: route: fast return when route matches failed
Additional Description:
Risk Level: low
Testing: unit-test added
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by dmitri-d** [comment]
The changes lgtm. Do you think it would be possible to add tests for `RouteEntryImplBase::matchRoute()` that cover the matching logic? It's a heavy object, but looks like its state is mostly derived from a Route protobuf and Vhost...

**Comment by soulxu** [comment]
> The changes lgtm. Do you think it would be possible to add tests for `RouteEntryImplBase::matchRoute()` that cover the matching logic? It's a heavy object, but looks like its state is mostly derived from a Route protobuf and Vhost...

I added a test. Although I can't assert each check is done or not(since they are class static method), but I test the case when all the conditions are matched, and the case one of them doesn't match.

**Comment by mattklein123** [comment]
Thanks this LGTM. Did you verify that all of these new branches have code coverage?

/wait-any

**Comment by soulxu** [comment]
Forget test the query_parameter, so added it

**Comment by soulxu** [comment]
> Thanks this LGTM. Did you verify that all of these new branches have code coverage?
> 

yes, I verified that 


> Thanks this LGTM. Did you verify that all of these new branches have code coverage?
> 
Do you mean all those fast return branch?  the test I added test the case one of them doesn't match. so it should cover all of those fast return branches.

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
