### PR TITLE
do/ci: Reorder case statements and improve block spacing

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by RyanTheOptimist — COMMENTED** [review]
There are a lot of lines changed in this PR, but from the description, I THINK it's all simply a mechanical move of the code. Is that right?

**Comment by phlax** [comment]
> There are a lot of lines changed in this PR, but from the description, I THINK it's all simply a mechanical move of the code. Is that right?

i can update the title

the spacing allows you to jump through the file much more easily (at least worth my editor/workflow)

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
