### PR TITLE
decompression: deprecate runtime guard append_to_accept_content_encoding_only_once.

### LINKED ISSUE #23591: envoy_reloadable_features_append_to_accept_content_encoding_only_once deprecation
Your change #19394 (decompressor: do not add accepted content encoding twice.) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

### PR DESCRIPTION
**Pull request by ipuustin**
Commit Message:

Deprecate envoy_reloadable_features_append_to_accept_content_encoding_only_once runtime guard and remove the old code path. 

Additional Description:
Risk Level: Low
Testing: Unit tests.
Docs Changes: N/A
Release Notes: inline
Platform Specific Features: N/A
Fixes #23591

### CODE REVIEW

**Comment by soulxu** [comment]
nit, forget to add a release for this https://github.com/envoyproxy/envoy/blob/ce49966ecb5f2d530117a29ae60b88198746fd74/changelogs/current.yaml#L15

**Comment by ipuustin** [comment]
> nit, forget to add a release for this
> 
> https://github.com/envoyproxy/envoy/blob/ce49966ecb5f2d530117a29ae60b88198746fd74/changelogs/current.yaml#L15

Thanks, fixed.

**Review by KBaichoo — APPROVED** [review]
Thank you for the cleanup

**Pull request merged**
