### PR TITLE
ads: fix MethodDescriptor resolution for ADS

### PR DESCRIPTION
**Pull request by joeyb**
Envoy currently segfaults if ADS is being used because resolution of the `envoy.service.discovery.v2.AggregatedDiscoveryService.StreamAggregatedResources` method fails. This fix uses the same hack as `descriptor_test.cc` to force linking so that the method is resolvable.

*Risk Level*: Low

*Testing*: Manual

*Docs Changes*: N/A

@kyessenov

### CODE REVIEW

**Comment by kyessenov** [comment]
Sorry, I hit the same issue, and have another dummy in #2495

**Comment by joeyb** [comment]
Ok, cool. I'll close this one in favor of that PR.

**Comment by mattklein123** [comment]
@kyessenov @htuch I'm not thrilled that there is no great way to test for this. I wonder if we should have a `RELEASE_ASSERT` in main_common which basically does the same thing as the test I wrote?

**Comment by htuch** [comment]
@mattklein123 yes, we could do that, maybe just factor that code out to somewhere in `server`. It's a cheap check and will give us consistency.

**Pull request closed without merging**
