### PR TITLE
docs/ci: Publish docs build artifacts

### LINKED ISSUE #13506: Generated docs are no longer published in (circle) CI
### description

since we moved to azure for docs generation in #13481 we lost the ability to click through to get the generated doc artefacts

i use this quite a lot and was in the process of adding a repokitteh command to make it easier to get the link to the artefact (#13326)

it would be great if we can publish the docs artefacts on azure too

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: docs/ci: Publish docs build artifacts
Additional Description:

see #13506 

Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue] Partial fix for #13506 
[Optional Deprecated:]

### CODE REVIEW

**Comment by phlax** [comment]
@mattklein123 @lizan this ~fix is not ideal but better than nothing - ie it gives a zip file dowload:

https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/53840/artifacts?artifactName=docs&api-version=6.0&%24format=zip

and requires even more clicks `8(`

ideally we want it to publish to eg a `hashed` branch in a docs-build repo with github pages or something (not sure atm if we can acheive similar with azure)

**Comment by phlax** [comment]
> not sure atm if we can acheive similar to what we had with azure

afaict - not - https://developercommunity.visualstudio.com/content/idea/491426/support-for-generic-html-publishing-inside-build-a.html

**Comment by mattklein123** [comment]
Yeah that's a huge bummer. I wonder, could we upload to S3 (or GCP equivalent) somewhere with a TTL that would cause it to get deleted after X time?

**Comment by phlax** [comment]
yep, re `GC` - not sure where is best to host - anywhere that dishes out `html` over `http`

**Comment by phlax** [comment]
using git has the advantage that if there is no change, there is no change

**Comment by mattklein123** [comment]
Take a look at how we publish coverage reports to Google storage (https://storage.googleapis.com/envoy-coverage/report-master/index.html used to work but seems broken right now).

**Comment by phlax** [comment]
right now im kinda looking at the actual publishing of the docs - to the website - im just wondering if that, or another staging repo could be used

**Comment by mattklein123** [comment]
It's possible we could somehow use netlify in this repo to do it?

**Comment by phlax** [comment]
tbh probs more than required - like the website - simple github pages should be enough (not sure how that works on branches...)

**Comment by phlax** [comment]
sadly it seems gh pages is not an option "GitHub Pages only lets you configure one publishing source for a particular repository." https://github.community/t/can-i-publish-multiple-branches-of-a-repository-on-github-pages/10314

so i guess something gitopsy like netlify is probably necessary

**Comment by phlax** [comment]
if we can land this in the meantime, i can script something for my own builds -> html

**Comment by mattklein123** [comment]
Yup agreed we can ship and iterate to something better, I think either posting to google storage or netlify might work. cc @lizan

**Review by mattklein123 — APPROVED** [review]

**Comment by lizan** [comment]
> Yeah that's a huge bummer. I wonder, could we upload to S3 (or GCP equivalent) somewhere with a TTL that would cause it to get deleted after X time?

We already do this, http://storage.googleapis.com/envoy-pr/13507/docs/index.html. This expires in 30 days.

**Comment by phlax** [comment]
@lizan not sure if you want to  revert my change

my only question is can we do it commit sha rather than pr issue number ?

its  not a big issue if not

**Comment by mattklein123** [comment]
Let's keep this PR but also push to GCP storage by SHA?

Also, can we look into why coverage push is broken?

**Comment by lizan** [comment]
@phlax yes, this takes a few mins for docs job. 
re: SHA, I didn't find SHA is more useful than branch/PR number, if you want you can fix this with the upload GCS script.

**Comment by phlax** [comment]
its just because it allows comparisons of rendered change

**Comment by lizan** [comment]
@mattklein123 https://storage.googleapis.com/envoy-postsubmit/master/coverage/index.html coverage seems fine, what's broken?

**Comment by mattklein123** [comment]
Hmm maybe nothing. When I clicked on it before I get an XML/key not found error. Maybe it was just in the middle of uploading.

**Comment by phlax** [comment]
i just realized the other reason why `sha` (ill PR when i get chance) - basically if you print a link saying "check here for blaa blaa"  and then make further changes - the link will work but the comment wont

**Comment by lizan** [comment]
@phlax sorry I don't follow. I assume you only want one comment for each PR for docs/coverage report, so PR number works fine and we only care about the latest. The other issue is that CI is on the PR's merge commit, so it's not the head of the PR branch anyway.

**Comment by phlax** [comment]
>  I assume you only want one comment for each PR for docs

no. as i said above it would be better to have per commit, as we had on circleci. I dont think it matters for coverage

> The other issue is that CI is on the PR's merge commit, so it's not the head of the PR branch anyway.

that doesnt matter, the `sha` was just for it to be ~uniquely tagged

**Pull request merged**
