### PR TITLE
dynamic_modules: Fix headers in bazel test setup

### PR DESCRIPTION
**Pull request by phlax**

### CODE REVIEW

**Comment by phlax** [comment]
cc @mathetake

**Comment by mathetake** [comment]
these build target is in C, not C++, so I was thinking just to ignore as in https://github.com/envoyproxy/envoy/pull/37426

**Comment by phlax** [comment]
i think the problem (iiuc) is that the aspect is visiting this node and seeing the header files as srcs

**Review by mathetake — APPROVED** [review]

**Comment by phlax** [comment]
@mathetake closing ths in favour of #37420 - add this change there

**Pull request closed without merging**
