### PR TITLE
config: add warming_state stat to clusters

### PR DESCRIPTION
**Pull request by ramaraochavali**
Commit Message: add warming_ state stat to clusters
Additional Description: With many envoys running with many clusters if few clusters fail to warm some times, it is difficult to identify the culprit cluster. This PR adds warming_state stat
Risk Level: Low
Testing: Updated
Docs Changes: Updated
Release Notes: Updated

### CODE REVIEW

**Review by zuercher — APPROVED** [review]
lgtm

**Comment by zuercher** [comment]
Needs a merge, though.

**Comment by ramaraochavali** [comment]
@zuercher done. PTAL.

**Review by zuercher — APPROVED** [review]

**Pull request merged**
