### PR TITLE
fuzz: Adding lazy map threshold config to headermap fuzzer

### PR DESCRIPTION
**Pull request by adisuissa**
Signed-off-by: Adi Suissa-Peleg <adip@google.com>

Commit Message: fuzz: Adding lazy map threshold config to headermap fuzzer
Additional Description:
Adding a configuration parameter to the headermap fuzzer testing the lazy-headermap.

Risk Level: Low (tests only)
Testing: Adding to a fuzzer
Docs Changes: None.
Release Notes: None.

### CODE REVIEW

**Comment by adisuissa** [comment]
@asraa please take a look

**Comment by asraa** [comment]
Thanks! Could you take a quick look at compile_time_options?

**Comment by adisuissa** [comment]
Ok, that was strange.
Building with clang's libc++ (--stdlib=libc++) doesn't trigger the assertion, but when building with GCC's it does.
The `remove_if` code where the assertion has triggered was recently updated (merged latest main), and by using both libraries no assertion failed.

**Review by asraa — APPROVED** [review]
Very weird! I suppose I will keep that mind in case something else ever comes up with GCC builds.

Thank you :) LGTM!

**Pull request merged**
