### PR TITLE
Backport v1.23 deps: bumps Wasmtime to 6.0.1 (#26190)

### PR DESCRIPTION
**Pull request by RiverPhillips**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by mattklein123 — DISMISSED** [review]

**Comment by phlax** [comment]
this looks like it has a genuine fail

```console
ERROR: /build/tmp/_bazel_envoybuild/400406edc57d332f0b9b805d2b8e33a1/external/proxy_wasm_cpp_host/BUILD:137:11: Compiling src/wamr/wamr.cc failed: (Exit 1): clang-14 failed: error executing command (from target @proxy_wasm_cpp_host//:wamr_lib) 
  (cd /build/tmp/_bazel_envoybuild/400406edc57d332f0b9b805d2b8e33a1/execroot/envoy_filter_example && \
  exec env - \
    BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 \
    BAZEL_LINKLIBS=-l%:libstdc++.a \
    BAZEL_LINKOPTS=-lm \
    CC=clang \
    CLANG_FORMAT=clang-format \
    CXX=clang++ \
    PATH=/usr/sbin:/usr/bin:/sbin:/bin:/opt/llvm/bin \
    PWD=/proc/self/cwd \
  /opt/llvm/bin/clang-14 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g '-std=c++0x' -MD -MF bazel-out/k8-dbg/bin/external/proxy_wasm_cpp_host/_objs/wamr_lib/wamr.pic.d '-frandom-seed=bazel-out/k8-dbg/bin/external/proxy_wasm_cpp_host/_objs/wamr_lib/wamr.pic.o' -fPIC -gsplit-dwarf -g -DPROXY_WASM_HAS_RUNTIME_WAMR -DPROXY_WASM_HOST_ENGINE_WAMR -iquote external/proxy_wasm_cpp_host -iquote bazel-out/k8-dbg/bin/external/proxy_wasm_cpp_host -iquote external/proxy_wasm_cpp_sdk -iquote bazel-out/k8-dbg/bin/external/proxy_wasm_cpp_sdk -isystem bazel-out/k8-dbg/bin/external/envoy/bazel/foreign_cc/wamr/include '-DABSL_MIN_LOG_LEVEL=4' -fPIC -Wno-deprecated-declarations '-std=c++17' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/proxy_wasm_cpp_host/src/wamr/wamr.cc -o bazel-out/k8-dbg/bin/external/proxy_wasm_cpp_host/_objs/wamr_lib/wamr.pic.o)
# Configuration: 3cc8133fde6b50409a717b3d2b6f60f79635824f0988cd11378c2f8ad10b58f6
# Execution platform: @envoy_build_tools//toolchains:rbe_linux_clang_platform
In file included from external/proxy_wasm_cpp_host/src/wamr/wamr.cc:32:
external/proxy_wasm_cpp_host/src/wamr/types.h:24:47: error: use of undeclared identifier 'wasm_shared_module_t'
using WasmSharedModulePtr = common::CSmartPtr<wasm_shared_module_t, wasm_shared_module_delete>;
                                              ^
external/proxy_wasm_cpp_host/src/wamr/wamr.cc:111:3: error: unknown type name 'WasmSharedModulePtr'; did you mean 'WasmModulePtr'?
  WasmSharedModulePtr shared_module_;
  ^~~~~~~~~~~~~~~~~~~
  WasmModulePtr
external/proxy_wasm_cpp_host/src/wamr/types.h:23:7: note: 'WasmModulePtr' declared here
using WasmModulePtr = common::CSmartPtr<wasm_module_t, wasm_module_delete>;
      ^
external/proxy_wasm_cpp_host/src/wamr/wamr.cc:138:20: error: use of undeclared identifier 'wasm_module_share'
  shared_module_ = wasm_module_share(module_.get());
INFO: 7378 processes: 3180 remote cache hit, 2963 internal, 1235 remote.
@envoy//test/exe:win32_scm_test                                 FAILED TO BUILD

Executed 0 out of 948 tests: 21 tests pass, 1 fails to build and 926 were skipped.
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=131562&view=logs&j=e969334a-0e55-5c18-ac96-8b546753391e&t=b5329a9e-93c7-5412-9f4c-6f8d659e1b57&l=4312

not sure how essential the `win32_scm_test` is but we could possibly disable it

im guessing 1.22 will at least have a similar issue

**Comment by phlax** [comment]
(or possibly we just need to update some other deps im guessing)

**Comment by phlax** [comment]
yep re 1.22 https://dev.azure.com/cncf/envoy/_build/results?buildId=131563&view=logs&j=e969334a-0e55-5c18-ac96-8b546753391e&t=b5329a9e-93c7-5412-9f4c-6f8d659e1b57&l=1241

**Comment by RiverPhillips** [comment]
Looks like the problem is with `com_github_wamr` will give it  a try with this commit too https://github.com/envoyproxy/envoy/pull/24739

**Comment by phlax** [comment]
seems to still be failing https://dev.azure.com/cncf/envoy/_build/results?buildId=131596&view=logs&j=e969334a-0e55-5c18-ac96-8b546753391e&t=b5329a9e-93c7-5412-9f4c-6f8d659e1b57&l=9708

im guessing `rules_rust`

**Review by phlax — APPROVED** [review]
lgtm, really nice work, thanks @RiverPhillips

**Pull request merged**
