### PR TITLE
draft: golang extesnion: implement custom_ssl_handshaker.

### PR DESCRIPTION
**Pull request by doujiang24**
not works yet, but could be good enough for continue discussing this issue: https://github.com/envoyproxy/envoy/issues/29270

people could implement a golang interface to choose/generate certificate on demand(request runtime).
please see the demo under test_data dir.

workflow:
image

Golang do not return certificate to C++ directly, just a sds name instead.
so that C++ will watch that sds on demand, and will wait a certificate with a timeout limitation.
SSL handshake request will continue when get a certificate or timeout happens.

NOTE: as disscused in https://github.com/envoyproxy/envoy/issues/29270, `custom_handshaker` might be a bit heaviy, since it will shadown the SSL session/ticket capabilities.
maybe it's better to add a new `custom_certificate_specifier` extension way, and Golang implement such a smaller extension, so that we can still reuse the SSL session/ticket capabilities.

### CODE REVIEW

**Comment by ggreenway** [comment]
> NOTE: as disscused in https://github.com/envoyproxy/envoy/issues/29270, custom_handshaker might be a bit heaviy, since it will shadown the SSL session/ticket capabilities.
maybe it's better to add a new custom_certificate_specifier extension way, and Golang implement such a smaller extension, so that we can still reuse the SSL session/ticket capabilities.

This is also discussed in #29357. I agree that a full handshaker is too heavy for what you're trying to do.

**Comment by BenAgai** [comment]
Hi @doujiang24 and @ggreenway ,
Any news regarding this PR?

Thanks

**Comment by doujiang24** [comment]
@BenAgai Sorry for being busy these days. I'll propose a design in a new issue soon, maybe next week.

**Comment by BenAgai** [comment]
Hi @doujiang24 ,
Nothing to be sorry for!
Thank you for the effort on pushing this forward.

Looking forward to hear any updates.
Thanks

**Comment by BenAgai** [comment]
Thanks for the update @doujiang24.
I will make sure to follow it.

**Pull request closed without merging**
