### PR TITLE
OTel accesslog: allow configuration for resource attributes

### PR DESCRIPTION
**Pull request by zirain**
Signed-off-by: hejianpeng <hejianpeng2@huawei.com>

Commit Message: allow configuration for resource attributes
Additional Description:
base on https://github.com/envoyproxy/envoy/pull/20883#discussion_r870690674 , this PR replace https://github.com/envoyproxy/envoy/pull/20883.
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

cc @yanavlasov

### CODE REVIEW

**Comment by yanavlasov** [comment]
Looks good to me. Adding @itamarkam for additional review.

**Comment by itamarkam** [comment]
> Looks good to me. Adding @itamarkam for additional review.

Added a couple of minor comments. Other than that LGTM.

**Comment by zirain** [comment]
> > Looks good to me. Adding @itamarkam for additional review.
> 
> Added a couple of minor comments. Other than that LGTM.

sorry, do I missing something, I can not see any comments?

**Review by itamarkam — APPROVED** [review]

**Comment by zirain** [comment]
@yanavlasov PTAL

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
