### PR TITLE
PULL_REQUEST_TEMPLATE.md: hide example

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long Dai <long0dai@foxmail.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message:

It is useless for reviewers or anyone interested in see a PR example in each PR, so hide it.

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by phlax — APPROVED** [review]
lgtm, thanks @daixiang0 

tbh - personally i would rather remove this info from the template - its annoying having to remove it and im not sure everyone reads it. A simple link to more info might work better.

this is an improvent anyway i think

**Comment by daixiang0** [comment]
How about add PR template into developer.md?

**Comment by daixiang0** [comment]
@phlax Hi, could it merged?

**Comment by phlax** [comment]
> @phlax Hi, could it merged?

i would like to get a stamp from @htuch or @mattklein123 before landing this

**Review by htuch — APPROVED** [review]

**Pull request merged**
