### PR TITLE
use min_len instead of min_bytes for golang.proto.

### LINKED ISSUE #25198: format error in golang.proto: min_bytes is DEPRECATED, Use min_len.
*Title*: format error in golang.proto: min_bytes is DEPRECATED, Use min_len.

*Description*:
My PR (#25040) needed merging latest main. After doing so I get the following error when trying to push the PR:
```
  Checking format for .github/workflows/tsan.yml - PASS
  Checking format for CODEOWNERS - PASS
  Checking format for OWNERS.md - PASS
  Checking format for api/bazel/api_build_system.bzl - PASS
  Checking format for api/contrib/envoy/extensions/filters/http/golang/v3alpha/golang.proto - ERROR: From ./api/contrib/envoy/extensions/filters/http/golang/v3alpha/golang.proto
ERROR: ./api/contrib/envoy/extensions/filters/http/golang/v3alpha/golang.proto:54: min_bytes is DEPRECATED, Use min_len.
ERROR: check format failed. run 'tools/code_format/check_format.py fix'
```

Could be related to the changes from #25101.

### PR DESCRIPTION
**Pull request by wangfakang**
Signed-off-by: wangfakang <fakangwang@gmail.com>

Commit Message: use min_len instead of min_bytes for golang.proto.
Additional Description: use min_len instead of min_bytes for golang.proto.
Risk Level: low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #25198
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by wangfakang** [comment]
/review @phlax @adisuissa 
would you mind review it, thanks.

**Review by adisuissa — APPROVED** [review]
Thanks for the quick fix!
/lgtm api

**Review by phlax — APPROVED** [review]
lgtm, thanks @wangfakang

**Pull request merged**
