### PR TITLE
gRPC: Remove `x-envoy-internal` and `x-forward-for` headers in envoy gRPC

### PR DESCRIPTION
**Pull request by tyxia**
Follow up on the [discussion here](https://github.com/envoyproxy/envoy/pull/34179#discussion_r1605505427), removing `x-envoy-internal` and `x-forward-for` from envoy-gRPC with runtime guard.

The other option is removing them with individual gRPC client's stream option.

### CODE REVIEW

**Comment by tyxia** [comment]
/assign @htuch @mattklein123 

PTAL, This is the follow-up of this thread (https://github.com/envoyproxy/envoy/pull/34179#discussion_r1605505427)

**Review by mattklein123 — CHANGES_REQUESTED** [review]
I'm sorry that I didn't see the pings on the original issue, but I'm worried that this is going to break someone who might be depending on these headers. For example, remote services that expect XFF to be set. I think it's highly likely that something is going to break if we remove this.

Given keeping this doesn't seem like a big deal if this is bothering someone can we have the config option to turn it off?

/wait

**Comment by htuch** [comment]
Let's make it config guarded. We definitely need to remove this for Google use cases, since these headers leak information to 3rd party ext_proc destinations. 

I do agree that the risk of breaking people is higher than is comfortable. OTOH, these headers make relatively little sense when used for something like ext_proc callouts, since the gRPC connection to the destination is not being forwarded for some client in the usual request forwarding sense, the headers appear as gRPC metadata and there are other ways to know the client IP, e.g. via ext_* payload.

**Comment by tyxia** [comment]
Per discussion, closed this one in favor of config approach https://github.com/envoyproxy/envoy/pull/34179

**Pull request closed without merging**
