### PR TITLE
lua: Add setBytes() API to the buffer wrapper

### PR DESCRIPTION
**Pull request by dio**
Commit Message: This patch adds `setBytes()` API to the buffer wrapper by making the wrapped buffer to be mutable. This allows rewriting upstream data in the response path.

Risk Level: Low
Testing: Added unit and integration tests.
Docs Changes: Added
Release Notes: Added
Fixes https://github.com/envoyproxy/envoy/issues/5998

Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

### CODE REVIEW

**Review by mattklein123 — APPROVED** [review]
Nice! LGTM!

**Comment by ceastman-ibm** [comment]
@dio do you have an example of lua code to do this?

**Comment by dio** [comment]
@ceastman-ibm yes, sorry if it is not obvious: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#script-examples at the end of this section. https://github.com/envoyproxy/envoy/pull/13172/files#diff-6fdb0e5fbf091e65aebffac556d8a5bbR240.

**Comment by ikingye** [comment]
> in the response path.

Why not in the request path?

**Comment by dio** [comment]
@ikingye do you mean you want to add more data to the request to upstream as well?

**Comment by inkdude** [comment]
@dio Hello!
Please can you tell me how i can get concatenation in "setBytes"? For example i have body "hello" and i need to push to upstream body "123_hello", but its not working ((

```
                  - name: envoy.filters.http.lua
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                      default_source_code:
                        inline_string:
                          function envoy_on_request(request_handle)
                            local body = request_handle:body()
                            body:setBytes("123_" .. body)
                          end
```

**Comment by ssapunkova** [comment]
Hello, @dio. Does this allow to rewrite the downstream data (envoy_on_request) as well?

**Pull request merged**
