### PR TITLE
quic: remove duplicate code in QUIC encodeData(), encodeMetadata() and encodeTrailers() implementations

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
quic: remove duplicate code in QUIC `encodeData()`, `encodeMetadata()` and `encodeTrailers()` implementations

Add a `QuicSpdyStream&` member to `EnvoyQuicStream` so that the `encodeData()`, `encodeMetadata()` and `encodeTrailers()` implementation can be moved to EnvoyQuicStream and out of the subclasses.

Risk Level: Low
Testing: Existing
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
@danzh2010 friendly ping

**Review by danzh2010 — COMMENTED** [review]
This is a good movement! Thanks for doing it!

Just one question, is it possible to also move part of encodeHeaders(), i.e. ScopedWatermarkBufferUpdater, byte tracker and local_end_stream_ to EnvoyQuicStream?

**Review by danzh2010 — APPROVED** [review]

**Comment by danzh2010** [comment]
> This is a good movement! Thanks for doing it!
> 
> Just one question, is it possible to also move part of encodeHeaders(), i.e. ScopedWatermarkBufferUpdater, byte tracker and local_end_stream_ to EnvoyQuicStream?

Discussed offline, this can be done as a follow up.

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
