### PR TITLE
tools: linked all extensions to router check binary

### LINKED ISSUE #22648: Route Checker error on HTTP filters/extensions
*Title*: Route Checker INVALID_ARGUMENT Error

*Description*:
```
% bazel build //test/tools/router_check:router_check_tool

% bazel-bin/test/tools/router_check/router_check_tool -c envoy.yaml -t test.yaml
Protobuf message (type envoy.config.route.v3.RouteConfiguration reason INVALID_ARGUMENT:admin: Cannot find field.) has unknown fields
[2022-08-10 15:56:14.741][1414723][debug][init] [source/common/init/watcher_impl.cc:31] init manager RTDS destroyed
[2022-08-10 15:56:14.742][1414723][debug][init] [source/common/init/watcher_impl.cc:31] RTDS destroyed
```

*Additional Info*:
1. I forked the envoy repo and cloned to mac. Fork and local are synced with upstream.
2. Tried several config files - yaml & json filetype, sample config copied from envoy website, my custom config. All produce same error.
3. Error is non-deterministic. Can error on any top-level field. Ex. `INVALID_ARGUMENT:admin`, `INVALID_ARGUMENT:static_resources`

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: tools: linked all extensions to router check binary
Additional Description: 

To close #22648.

Risk Level: n/a.
Testing: n/a.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
cc @mattklein123 Is this what we want?

**Comment by wbpcode** [comment]
Hi, @keith could you take a look to the link error when you have free time? I build it successfully in my local machine. 🤔 

```
ld.lld: error: bazel-out/k8-fastbuild/bin/test/tools/router_check/_objs/router_check_main_lib/router.pic.o:(.rodata._ZN4absl16variant_internal18VisitIndicesSwitchILm2EE3RunINS0_36VariantStateBaseDestructorNontrivialIJNSt3__110shared_ptrIN5Envoy10StreamInfo11FilterStateEEENS5_4pairISA_NS9_8LifeSpanEEEEE9DestroyerEEENS0_22VisitIndicesResultImplIT_JmEE4typeEOSH_m+0x8): relocation R_X86_64_PC32 out of range: 3126258896 is not in [-2147483648, 2147483647]
>>> referenced by router.cc
```

**Comment by mattklein123** [comment]
Yeah this is what we want. I know we have hit the above issue in the past though I don't remember why or how we fixed it. Can you look at the schema validator tool as I'm sure it's the same?

**Comment by wbpcode** [comment]
I updated the BUILD file of router check to keep almost same with the schema validator. But it still failed.

**Comment by keith** [comment]
I see this failure locally on this branch running:

```
ci/run_envoy_docker.sh 'ci/do_ci.sh bazel.coverage //test/tools/router_check/test:router_tool_test'
```

Were you running locally with clang+lld?

**Comment by wbpcode** [comment]
> I see this failure locally on this branch running:
> 
> ```
> ci/run_envoy_docker.sh 'ci/do_ci.sh bazel.coverage //test/tools/router_check/test:router_tool_test'
> ```
> 
> Were you running locally with clang+lld? 

I build it with `bazel build` successfully.

And it also failed when I running coverage test. Orz

**Comment by keith** [comment]
Yea I think the difference in coverage configuration is probably the issue, is that enough for you to debug a bit?

**Comment by wbpcode** [comment]
> Yea I think the difference in coverage configuration is probably the issue, is that enough for you to debug a bit?

I am trying to modify the coverage config to find out the real cause. But I am a little busy these days. I will do some researches in this weekend.

**Comment by wbpcode** [comment]
Now the building is OK. Seems that the binary (contains all extensions) of coverage test is too large. We can solve this problem by use dynamic link for coverage test.

PS: The schema validator has no this problem because there is no any test that use the whole validator binary.

**Comment by wbpcode** [comment]
The CI is still failed because some tests have some errors. I will try to find out the reason .

**Comment by wbpcode** [comment]
What a wonder! I checked out to main branch and just run the `./ci/do_ci.sh bazel.release //test/extensions/transport_sockets/tls/cert_validator:default_validator_test`. And it just also failed.

**Comment by wbpcode** [comment]
hah, the ca_cert is expired.

```
$ openssl x509 -in ./test/extensions/transport_sockets/tls/test_data/ca_cert.pem -noout -dates
notBefore=Aug 20 16:57:46 2020 GMT
notAfter=Aug 20 16:57:46 2022 GMT
```

**Review by mattklein123 — APPROVED** [review]
Thank you!

**Comment by wbpcode** [comment]
Finally, we won't link the extensions to `route_check_tools` for **coverage test**. Although it can be build successfully by using dynamic link, but the `router_tool_test` in coverage take too much time (even I updated the test timeout to 1500s, it still failed because of timeout) after linked extensions.

**Comment by mattklein123** [comment]
Yeah I think it's ok to just not run the test in coverage. Sorry for all the trouble!

/wait

**Comment by wbpcode** [comment]
Dynamic linking is unnecessary if we don't link the extensions to router check tool in coverage test. 

Although I think the binaries should use dynamic link for coverage test according to the arg `build:coverage --define=dynamic_link_tests=true`.
Some external problems that introduced by the dynamic linking will block the CI.

So I reverted some unnecessary changes that used to enable dynamic linking for coverage test binaries. And this can make the PR more clean and independent.

I will add TODO to my list to make dynamic linking work as expected finally.

**Comment by wbpcode** [comment]
> Yeah I think it's ok to just not run the test in coverage. Sorry for all the trouble!
> 
> /wait

You are welcome. I learn some more about the building system by this PR. 😸

**Review by mattklein123 — APPROVED** [review]
Thank you!

**Pull request merged**
