### PR TITLE
Quic refactor

### PR DESCRIPTION
**Pull request by alyssawilk**
Refactoring quic transport factories into client and server classes.
Splitting the server class out of the default build.

Risk Level: low
Testing: n/a
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by alyssawilk** [comment]
splitting the client classes out causes a random coverage failure I'm looking into but I'd like to merge this as incremental progress
cc @RyanTheOptimist

**Review by RyanTheOptimist — APPROVED** [review]
Wow, awesome!

**Pull request merged**
