### PR TITLE
release: bump to 1.11.0

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: n/a
Testing: n/a
Docs Changes: 1.11!
Release Notes: 1.11!

### CODE REVIEW

**Comment by alyssawilk** [comment]
@envoyproxy/senior-maintainers for review!

**Comment by alyssawilk** [comment]
Assigning to @dnoe since he has a fix he wants to land first, but I'll wait for a thumbs up from him and at least one senior maintainer :-)

**Comment by lizan** [comment]
@alyssawilk Shall we get https://github.com/envoyproxy/envoy/pull/7533 in? I'm in favor of it but leaving it to your call.

**Comment by alyssawilk** [comment]
OK, #7539 is in so I think we're good to go!

**Pull request merged**
