### PR TITLE
Move dio to emeritus

### PR DESCRIPTION
**Pull request by dio**
Signed-off-by: Dhi Aurrahman <dio@rockybars.com>

### CODE REVIEW

**Comment by wbpcode** [comment]
Sad to see you go 😞, thank you for all your helps, both to Envoy and to me personally.

**Review by wbpcode — APPROVED** [review]

**Comment by phlax** [comment]
thanks @dio - really sad to see you go - i particularly remember how supportive you were when i first got involved with the project - thanks again

**Review by phlax — APPROVED** [review]
lgtm

**Comment by mattklein123** [comment]
Thank you for everything you have done over the years @dio. We will miss you. Hopefully you will come back some day. :)

**Pull request merged**
