### PR TITLE
[bp/1.28] Bump rules-go to 0.41.0

### PR DESCRIPTION
**Pull request by jwendell**
This version contains the fix for using local sdk with go >= 1.21

https://github.com/bazelbuild/rules_go/pull/3600

### CODE REVIEW

**Comment by phlax** [comment]
ci failures look ~real

```console
Repository rule http_archive defined at:
  /build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: /build/bazel_root/base/external/com_github_cncf_xds_go/xds/type/v3/BUILD.bazel:3:11: no such package '@go_googleapis//google/api/expr/v1alpha1': The repository '@go_googleapis' could not be resolved: Repository '@go_googleapis' is not defined and referenced by '@com_github_cncf_xds_go//xds/type/v3:type'
ERROR: Analysis of target '//contrib/golang/router/cluster_specifier/test/test_data/simple:plugin.so' failed; build aborted: 
INFO: Elapsed time: 49.836s
INFO: 0 processes.

```

this has come up before @mmorel-35 _might_ know why this happens

**Comment by jwendell** [comment]
that's weird, we already applied that change to our fork and it's building fine...

**Comment by moderation** [comment]
Current `main` branch `rules_go` is at [`0.46.0`](https://github.com/envoyproxy/envoy/blob/main/bazel/repository_locations.bzl#L1009) - should we bump to that version?

**Comment by phlax** [comment]
> Current main branch rules_go is at [0.46.0](https://github.com/envoyproxy/envoy/blob/main/bazel/repository_locations.bzl#L1009) - should we bump to that version?

i think lets land these (once ci issues are resolved)

we can bump `main` further and backport more if required

**Comment by phlax** [comment]
hmm - actually @jwendell i just realized that this isnt actually a backport - i think @moderation is right - that we should just pick the actual backport - same with PRs on other branches

**Comment by jwendell** [comment]
Yeah, you're right, this is not a backport. I was just trying to be moderate and bump the versions only to the minimal version required, but if bringing it in pair with `main` is not an issue, I'll do it.

Thanks for the review folks.

**Pull request closed without merging**
