### PR TITLE
protos: Remove unused proto import

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: protos: Remove unused proto import
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by daixiang0** [comment]
I am wondering is there a tool to check unused proto import?

**Comment by phlax** [comment]
> I am wondering is there a tool to check unused proto import?

not afaiaa but i would be very happy to be corrected

see #15589 for related discussion

**Comment by daixiang0** [comment]
Happy to see those clean :)

**Review by htuch — COMMENTED** [review]
@phlax can you add to CI some auto-detection of these warnings and then we can prevent regression? I don't mind approving this, but ideally we automate ourselves out of our job here.

**Comment by phlax** [comment]
one thing i would also say is that i was cleaning up 2-3 of these per week - but fixing the docs seems to have reduced this down to 1 or 2 a month

**Comment by htuch** [comment]
I was thinking something like `tee`-ing the output somewhere and grepping for the specific unused import warnings. I don't mind merging, but I rather not whackamole longer term.

**Review by htuch — APPROVED** [review]

**Pull request merged**
