### PR TITLE
deps: Bump `bazel` -> 6.2.0 (take 2)

### PR DESCRIPTION
**Pull request by phlax**
with added mobile fail condition

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
Sadly, it looks like this is still not resolved?

```
ERROR: /private/var/tmp/_bazel_runner/38952b625e1e7c72284b0f9be4a35639/external/rules_java/toolchains/BUILD:116:14: no such package '@remote_java_tools_darwin//': The repository '@remote_java_tools_darwin' could not be resolved: Repository '@remote_java_tools_darwin' is not defined and referenced by '@rules_java//toolchains:ijar_prebuilt_binary_darwin'
```

**Comment by phlax** [comment]
> Sadly, it looks like this is still not resolved?

currently we depend on a stack from @jpsim to work around similar issues in earlier versions (of `rules_java`) we probably need to figure something similar and/or push upstream to resolve

**Comment by moderation** [comment]
Bazel `6.2.1` is out - https://github.com/bazelbuild/bazel/releases/tag/6.2.1

**Pull request closed without merging**
