### PR TITLE
Added DurationTimeout as response flag for HCM.

### LINKED ISSUE #13142: Add DurationTimeout response flag for HCM.
In PR #12495, I have added the "DurationTimeout" response flag for TCP connection timeout and should be the same for HTTP also.
CC @htuch

### PR DESCRIPTION
**Pull request by mk46**
Signed-off-by: Manish Kumar <manish.kumar1@india.nec.com>

Commit Message: Added DurationTimeout as a response flag for HCM.
Additional Description: In #12495, "DurationTimeout" as a response flag produced at the TCP connection timeout. The timeout flag should have the same behavior for TCP and HTTP connection-level.   
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
Fixes #13142

### CODE REVIEW

**Review by asraa — DISMISSED** [review]
Thank you! Just a drive-by: would you be able to add a test for the response flag?

**Comment by alyssawilk** [comment]
Thanks for following up on that TODO!  I think if you add a unit test and update your PR description fields you'll be good to go!

**Comment by mk46** [comment]
> Thank you! Just a drive-by: would you be able to add a test for the response flag?

Haven't done this before. Any quick help. Thanks!

**Review by alyssawilk — APPROVED** [review]

**Comment by alyssawilk** [comment]
Sorry, the OS build is flaky right now, so @lizan can take a look even if it's not passing

**Comment by mk46** [comment]
@lizan Would you mind to take a look?

**Review by lizan — APPROVED** [review]
Seems CodeQL is irrelevant to this PR?

**Comment by mk46** [comment]
> Seems CodeQL is irrelevant to this PR?

Thanks for approving. I had checked the log, failing due to `eventual cause: IOException "No space left on device"`.See [13811](https://github.com/envoyproxy/envoy/issues/13811)

**Pull request merged**
