### PR TITLE
ci: Add `examplesOnly` condition

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
these conditions are not perfect, but will still catch most of the PRs - eg a sandbox PR which has just docs + example changes wont be caught but should. We can improve on these conditions once we have CI running a bit more optimally

**Comment by alyssawilk** [comment]
still a draft - want me to take a look anyway?

**Review by alyssawilk — COMMENTED** [review]
yeah looks fine.  want to exempt the relevant builds as part of it?

**Comment by alyssawilk** [comment]
LGTM but I'm going to throw over to Lizan as he's more likely to realize if we're excluding biulds we don't want to :-P

**Comment by phlax** [comment]
added windows to skipped jobs

**Review by lizan — APPROVED** [review]

**Pull request merged**
