### PR TITLE
ci: use bash for Windows and build more targets in CI

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

Description:
Risk Level: Low
Testing:
Docs Changes:
Release Notes:

### CODE REVIEW

**Comment by mattklein123** [comment]
cc @wrowe PTAL

**Comment by lizan** [comment]
@wrowe this addresses the issue you see in https://github.com/envoyproxy/envoy/pull/8754#issuecomment-548422586, powershell by default treating command write to stderr as a failure so I just switch to bash (which is Windows native, not WSL, already available in azp) for a couple more reasons (leveraging existing scripts such as setting up caches).

**Comment by wrowe** [comment]
Good stuff, thanks @lizan. This is a noop relative to the original correction to bazel/boringssl_static.patch in PR 8754 which is still need. The proposal looks good - we only launch from powershell so can't comment on launching bazel from bash, but this is supposed to work well.

Editorial nit; missed a trailing newline in ci/windows_ci_steps.sh

**Comment by wrowe** [comment]
> switch to bash (which is Windows native, not WSL, already available in azp)

I'm rather confused, I searched azp and found only reference to the ubuntu (wsl) flavor of bash. Pointer please? This may be fine in any case, I'm not sure it has been evaluated by the bazel authors but I'm fine with beginning experimental use of it in place of msys2. But bash isn't the only linux tool required of msys2 for building bazel, nevermind envoy.

**Comment by wrowe** [comment]
Last observation, the -fPIC change is good, but missed this change that's still needed to undo the recent breakage with pic/pie;

```
--- a/bazel/envoy_binary.bzl
+++ b/bazel/envoy_binary.bzl
@@ -71,6 +71,7 @@ def _envoy_linkopts():
         ],
     }) + select({
         "@envoy//bazel:boringssl_fips": [],
+        "@envoy//bazel:windows_x86_64": [],
         "//conditions:default": ["-pie"],
     }) + _envoy_select_exported_symbols(["-Wl,-E"])

```

**Comment by wrowe** [comment]
Re: pie/pic on Windows;

https://docs.microsoft.com/en-us/cpp/build/reference/dynamicbase-use-address-space-layout-randomization?view=vs-2019

confirms that ASLR-compatible .exe objects are the default for Windows (this was obviously true of .dll files, but also true of static .exe's by default since at least as far back as Visual Studio 2015.)

**Comment by lizan** [comment]
> > switch to bash (which is Windows native, not WSL, already available in azp)
> 
> I'm rather confused, I searched azp and found only reference to the ubuntu (wsl) flavor of bash. Pointer please? This may be fine in any case, I'm not sure it has been evaluated by the bazel authors but I'm fine with beginning experimental use of it in place of msys2. But bash isn't the only linux tool required of msys2 for building bazel, nevermind envoy.

From azp log:
```
[command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc -c pwd
/d/a/_temp

========================== Starting Command Output ===========================
[command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc /d/a/_temp/0c683591-eb2e-4fdc-a52f-de48257c41a6.sh
disk space at beginning of build:
Filesystem            Size  Used Avail Use% Mounted on
C:/Program Files/Git  128G  110G   19G  86% /
D:                     14G  1.9G   13G  14% /d
No remote cache bucket is set, skipping setup remote cache.
2019/11/03 06:42:37 Downloading https://releases.bazel.build/1.1.0/release/bazel-1.1.0-windows-x86_64.exe...
```

Seems azp agent is using bash under git installation, and from what bazelisk downloads it is obviously using native Windows bazel. (We don't install Linux binary of bazelisk anywhere either).

I'll update pie soon

**Pull request merged**
