### PR TITLE
buffer: remove old implementation

### PR DESCRIPTION
**Pull request by derekargueta**
Description: Removes the old libevent-based buffer implementation
Risk Level: low, no one should be using the old buffer at this point. It's gone through the deprecation policy
Testing: existing
Docs Changes: N/A
Release Notes: included
Fixes: #8575

Signed-off-by: Derek Argueta <dereka@pinterest.com>

### CODE REVIEW

**Comment by mattklein123** [comment]
@derekargueta the coverage failure looks legit?

```
[  FAILED  ] BufferHelperTest.PeekVarInt32BufferUnderflow
```

/wait

**Comment by mattklein123** [comment]
Looks like ```QuicMemSliceTest.MoveAssign``` is failing? Possibly real?

**Comment by derekargueta** [comment]
@mattklein123 should be sorted out - it was a naming collision on `QuicMemSliceTest` between our tests and quiche's tests. I guess `INSTANTIATE_TEST_SUITE_P` does a bit more name mangling (including the parameter info) that it avoided collisions previously. Addressed by prefixing with `Envoy`, which seems to be the pattern for other quiche tests.

**Pull request merged**
