### PR TITLE
deps: Remove unused dependencies from gh notifier

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: deps: Remove unused dependencies from gh notifier
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
afaict not all of the deps in requirements.txt were used 

i regenerated the file by removing everything apart from `pygithub` and `slack-sdk` and then reran `pip-compile`

**Comment by moderation** [comment]
I was wondering if their was a `pip` equivalent of something like `go mod tidy` that would remove unnecessary deps

**Comment by phlax** [comment]
i guess a difference between go and python is that with go you can ask "what is required to compile x binary" whereas in python its more like "what is going to be used in this env" which is more open-ended

**Comment by phlax** [comment]
ive updated this pr to incorporate bumping slack-sdk to v3.6

**Review by alyssawilk — APPROVED** [review]
nice catch, thanks

**Pull request merged**
