### PR TITLE
http utility: remove exception handling from parseAuthority

### PR DESCRIPTION
**Pull request by junr03**
Commit Message: http utility - remove exception handling from `parseAuthority`
Additional Description: before this PR `parseAuthority` had to handle exceptions thrown from `parseInternetAddress`. This occurs on the hot path for all Envoy deployments using http. Given the fact that nullptr can indicate failure to parse an internet address from a authority string, this PR removes exceptions in favor of nullptr return values via a new `parseInternetAddressNoThrow` (inspired from https://github.com/envoyproxy/envoy/pull/14015#discussion_r532769623) utility function.
Risk Level: low - although larger discussion about removing the exception throwing variants is open.
Testing: existing test suite

Signed-off-by: Jose Nino <jnino@lyft.com>

### CODE REVIEW

**Comment by junr03** [comment]
@yanavlasov @mattklein123 @rulex123 I started going down the path of removing the exception throwing utility functions (parseInternetAddress, and parseInternetAddressAndPort). However, I got into many places where exceptions are the acceptable expectation downstream. For example, during config parsing. (Although I know there is debate there cc @alyssawilk @htuch).

I know many of you have made strides on making the codecs exception free, and there is desire to make the data plane exception free. But given I was getting down to callers out of the data plane I wasn't sure if I should go the full mile and rip out the exception all the way at the root.

This PR is a more pointed and (I think) less polarizing change given that we are very often throwing and catching an exception with parsing authority. 

Let me know if you'd like to see a bigger PR removing exceptions from parsing internet addresses. I can also open an issue.

**Comment by mattklein123** [comment]
I think tackling removing exceptions from main thread / config parsing is not resourced right now. The goal is to remove them from workers. I think we may end up with variants of utility functions that throw and don't throw. My advice is just to stick to simple and incremental cleanups towards that goal.

**Comment by dmitri-d** [comment]
Could you add a test for `parseInternetAddressNoThrow()` that verifies it returns a nullptr on malformed ip?

**Comment by alyssawilk** [comment]
Yeah, I think starting incremental and focusing on the data plane is for sure the way to go.  AFIK there's plans for the data plane and debate about if it's easier to try to regression-proof against exceptions being added back to the data plane, or just tackle the control plane and compile-enforce no exceptions at all, and we'll see how that goes.  either way thanks for kicking this off! :-)

**Comment by htuch** [comment]
+1 on not having to tackle config yet. I'm interested in anything that reduces the amount of exception cognitive tax, but data plane is where the most acute issues exist (performance, security, reliability).

**Comment by junr03** [comment]
Ok great. Thanks for all the feedback.

Just to clarify the larger change I was working on was just the removal of two exception throwing utility functions (`parseInternetAddress`, and `parseInternetAddressAndPort`). But even that is decently wide in scope w.r.t config handling.

In the spirit of incremental change then, this PR is ready for review.

**Review by dmitri-d — APPROVED** [review]

**Comment by alyssawilk** [comment]
CI failures are fixed at head.  mind doing a main merge?

**Review by yanavlasov — APPROVED** [review]

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
