### PR TITLE
udp: deprecate `envoy.restart_features.udp_read_normalize_addresses`

### LINKED ISSUE #30430: envoy_restart_features_udp_read_normalize_addresses deprecation
Your change #26041 (udp: normalize local address if using dual stack socket) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

### PR DESCRIPTION
**Pull request by danzh2010**
Commit Message: remove `envoy.restart_features.udp_read_normalize_addresses` and update change log.

Risk Level: low
Testing: N/A
Docs Changes: N/A
Release Notes: Yes
Platform Specific Features: N/A
Fixes #30430

### CODE REVIEW

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Comment by soulxu** [comment]
@danzh2010 the CI just fixed last night, maybe worth a rebase.

**Review by adisuissa — APPROVED** [review]

**Pull request merged**
