### PR TITLE
docs: missing new line in usage.rst

### PR DESCRIPTION
**Pull request by GregHanson**
Commit Message: missing new line in access logs usage docs between operator name and first line of description
Additional Description: introduced here: https://github.com/envoyproxy/envoy/pull/15139
Risk Level: low
Testing:
Docs Changes: format fix
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by GregHanson** [comment]
I believe test failures are related to https://github.com/envoyproxy/envoy/pull/15282
cc @alyssawilk

**Comment by alyssawilk** [comment]
Mind doing a master merge now that's checked in?

**Comment by GregHanson** [comment]
@alyssawilk do you suggest another merge with master?  I still see the failing test `//test/extensions/quic_listeners/quiche/integration:quic_protocol_integration_test` after pulling in your merged fix here in PR #15282

**Comment by alyssawilk** [comment]
I believe CI is fixed at HEAD so yeah please merge.

**Review by alyssawilk — APPROVED** [review]
Thanks for the clean up!

**Pull request merged**
