### PR TITLE
[contrib-siporoxy] fix 28524

### PR DESCRIPTION
**Pull request by durd07**
Commit Message: fix 28524
Additional Description:
Risk Level:Low
Testing: Ut
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] #28524 
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by durd07** [comment]
@dorisd0102 Please help to review this. Thanks.

**Comment by dorisd0102** [comment]
LGTM

**Comment by durd07** [comment]
@lizan Please help to review and merge this.
Thanks.

**Comment by durd07** [comment]
@envoyproxy/senior-maintainers Could anyone help to merge this?
Thanks in advance.

**Review by adisuissa — APPROVED** [review]
LGTM, thank!

**Pull request merged**
