### PR TITLE
test: deflake upstream starttls integration test

### LINKED ISSUE #16365: StartTlsIntegrationTestSuite/StartTlsIntegrationTest.SwitchToTlsFromClient/0 flakes on coverage
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/74596/logs/245
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/74598/logs/241

I have no idea why this started flaking but @cpakulski could you take a look?

### PR DESCRIPTION
**Pull request by cpakulski**
Commit Message:
de-flake upstream starttls integration test.

Additional Description:
Risk Level: Low
Testing: unit and integration
Docs Changes: No
Release Notes: No
Platform Specific Features: No
Fixes #16365

### CODE REVIEW

**Comment by cpakulski** [comment]
@bryce-anderson PTAL.

linux_x64 gcc fails because of the known issue (params list is too long).

**Comment by antoniovicente** [comment]
> @bryce-anderson PTAL.
> 
> linux_x64 gcc fails because of the known issue (params list is too long).

Do you have info on failure rates before / after this change?

Looking at the changes now.

**Comment by cpakulski** [comment]
@antoniovicente `bazel test --runs_per_test=50 ...` used to fail each time I executed it. Now it never fails.

**Review by antoniovicente — APPROVED** [review]
This change seems like a massive improvement to the existing test.  Many thanks for doing this.

**Comment by antoniovicente** [comment]
Could you merge upstream/main to pickup the mitigation for the gcc CI failure?

/wait

**Comment by cpakulski** [comment]
CI is happy now after merging `main`.

**Pull request merged**
