### PR TITLE
wasm: envoy specific ABI to add tags to active span

### PR DESCRIPTION
**Pull request by mohit-a21**
Added an envoy specific wasm ABI: envoy_set_active_span_tag.
This ABI can be used for adding tag informations for an active
span while request processing in a WASM filter.

Signed-off-by: Mohit Agarwal <mohit@traceable.ai>

Risk Level: Low
Testing: Added test cases.
Docs Changes: Not sure. Will have to see how to add documentation for this.

### CODE REVIEW

**Comment by mohit-a21** [comment]
@PiotrSikora, @lizan  Seems like all the builds are passing now. Please suggest anything that is needed.

**Comment by pavolloffay** [comment]
@PiotrSikora @asraa @lizan any update on this one? We would like to start using this patch.

**Comment by mohit-a21** [comment]
@PiotrSikora @lizan Please suggest what is needed for this. Thanks!

**Comment by mohit-a21** [comment]
@PiotrSikora @lizan Any comments would be appreciated.

**Pull request closed without merging**
