### PR TITLE
Bump envoy-build-tools

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Commit Message:
Bump envoy-build-tools

Fixes flakiness in tls handshake test on Windows and issues with https://github.com/envoyproxy/envoy/pull/13264

Additional Description: N/A
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Review by mattklein123 — APPROVED** [review]
Thanks! cc @phlax this should have you shellcheck update also I think.

**Comment by sunjayBhatia** [comment]
/retest

Curious as to why only a few Linux steps failed, check for flakes

**Comment by phlax** [comment]
@mattklein123 @sunjayBhatia envoyproxy/envoy-build-tools#103 didnt land yet - not sure if you want to land that first - i can bump the hashes again if not

**Comment by sunjayBhatia** [comment]
> @mattklein123 @sunjayBhatia [envoyproxy/envoy-build-tools#103](https://github.com/envoyproxy/envoy-build-tools/pull/103) didnt land yet - not sure if you want to land that first - i can bump the hashes again if not

I just submitted this PR as a rush job to fix test flakiness, but if we want to wait for the shellcheck update we can bump in one go, I have no preference

**Pull request merged**
