### PR TITLE
xds: undo the revert (#9044) of delta+SotW unification

### PR DESCRIPTION
**Pull request by fredlas**
Originally #8478. Also includes a bit of cleanup and renaming that happened after:
#8918 and #8919.

### CODE REVIEW

**Comment by mattklein123** [comment]
@rgs1 @fredlas one last question on this: @rgs1 do you have xDS init timeouts disabled in your environment? If you do not, and Envoy would still hang in some case, I think we do have to understand the original cause of the hang. If you have the init timeouts disabled for some reason I can potentially accept this though I'm uncomfortable. cc @wgallagher @kyessenov 

/wait-any

**Comment by rgs1** [comment]
> @rgs1 @fredlas one last question on this: @rgs1 do you have xDS init timeouts disabled in your environment? If you do not, and Envoy would still hang in some case, I think we do have to understand the original cause of the hang. If you have the init timeouts disabled for some reason I can potentially accept this though I'm uncomfortable. cc @wgallagher @kyessenov
> 

@mattklein123 you mean `initial_fetch_timeout` (https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/core/config_source.proto#L151) right? If so, it's set to 10s.

**Comment by mattklein123** [comment]
> @mattklein123 you mean initial_fetch_timeout (https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/core/config_source.proto#L151) right? If so, it's set to 10s.

OK, that's what I was afraid of. Sorry, we can't merge this until we understand what is going on. Something has changed with regard to the init timeout handling. @rgs1 are you able to re-break your SDS implementation and potentially get more logs? Thank you hugely in advance.

**Comment by fredlas** [comment]
Nice, that's a pretty solid lead. After a quick look, I notice one perhaps important difference in when the old/new code calls `disableInitFetchTimeoutTimer()`. In `onConfigUpdate()`, i.e. handling an update and nothing has yet thrown an exception, there is a call through to the `onConfigUpdate()` of the subscription's `callbacks_`. The old code disables the timer *before* calling that `onConfigUpdate()`, the new code calls it after.

I would expect the difference there to be that the old code gives up in the face of some failures, whereas the new code keeps trying. If the config setup was relying on that giving up, that might explain the hang?

**Comment by mattklein123** [comment]
> I would expect the difference there to be that the old code gives up in the face of some failures, whereas the new code keeps trying. If the config setup was relying on that giving up, that might explain the hang?

Possibly, but we should still be bound by the 10s timeout. So, perhaps there is some difference in which we are not adhering to the timeout. cc @ramaraochavali who has looked at this a lot.

**Comment by fredlas** [comment]
Hmm... yes, that is true, but it looks like there might be an exception if the particular error was a connection failure.

I think what would happen in the new code, if the issue is that there is an exception-throwing failure involved, is that actually the `disableInitFetchTimeoutTimer()` `onConfigUpdate()` would never even get called, because the exception makes us jump out of the function first.

Now, when the init timeout fires, the result is a `onConfigUpdateFailed()`, which disables the timer in 2 of 3 cases. However, the `ConfigUpdateFailureReason::ConnectionFailure` case in there does not disable the timer (in both the old and new code).

**Comment by mattklein123** [comment]
> Now, when the init timeout fires, the result is a onConfigUpdateFailed(), which disables the timer in 2 of 3 cases. However, the ConfigUpdateFailureReason::ConnectionFailure case in there does not disable the timer (in both the old and new code).

I will let @ramaraochavali chime in but I think the expected behavior is that we always timeout after the timeout period, but allow retries if there are connection errors. This must be where the functional change is and this definitely needs to be fixed. Great though that we are getting close to understand the problem!

**Comment by ramaraochavali** [comment]
Yes. The original implementation was, Envoy initialization should always timeout and proceed with initialization,  with in configured time making best effort to get the initial config during that configured time (and retries will continue in the background to get the config even after the initialization is done). 

The relevant PRs that made this change are https://github.com/envoyproxy/envoy/pull/7571 and https://github.com/envoyproxy/envoy/pull/7427. 

Based on what is being discussed here, it is not finishing initialization after 10s, which seems to be the regression. I have n't looked at the new code to see what the problem is though

**Comment by fredlas** [comment]
It's not clear from Event::Timer's comments whether that timer is a one-time thing, or a "fire every <interval> until disabled". But, if the latter, then there would be an ongoing stream of onConfigUpdateFailed() calls, forever. Would that be an issue for init completing?

If so, then the reordering of the two lines in `onConfigUpdate()` that I described would explain the different behavior. (I will swap those two lines regardless of whether we decide that was the cause, to match the existing ordering).

**Comment by ramaraochavali** [comment]
BTW, you can check init_timed_out stat (do not remember exactly the stat name) on the setup where it is initializing successfully to see if the initialization finished because of timeout(10s) with old code?

**Comment by mattklein123** [comment]
@fredlas friendly ping here. Where are we with this investigation? We need to move this forward one way or the other (the other way being to abandon this large change and have @wgallagher resubmit it in smaller chunks). If we think there is an issue with timer ordering we definitely need to get a test in place that exhibits the problem and the fix.

**Comment by fredlas** [comment]
The timer being disabled only after a successful update (as opposed to as soon as the update is even attempted, like the existing code) is a real difference that seems, as far as I understand things, likely to be causing the observed difference. I'm not sure whether @ramaraochavali agrees, disagrees, or no opinion yet.

The current state of the PR (with timer disabling logic now matching the existing code) hasn't been tested with the particular config that is the issue here. I think the fact that it was actually bad config is kind of confusing the issue. It sounds like @rgs1 and company, having noticed the bug in their config, now actually prefer the new overall behavior? However, it's not established whether it was the timer-disabling that causes the difference. From this discussion about the timer disabling, it sounds like the old (timer-disabling) behavior is intentional and well considered.

So, if the timer disabling difference really did cause the hang, then (completely ignoring this whole overhaul) we have users who potentially view Envoy's current behavior as wrong (i.e. not an accidental bug, but the intended behavior actually being wrong). That maybe needs discussion of its own, but this change can sidestep the issue by just keeping the current behavior. If the timer disabling did *not* cause the hang, then the existing code is buggy in an unknown way, and this change fixes it. In that case, it would not make sense for investigation to happen in the context of this change, since it's a pre-existing issue in the Envoy code.

@rgs1 , are you up for another test? Should I add in trace logging anywhere it could possibly be relevant, first?

Finally: have you identified the smaller chunks you would be targeting? I originally broke it up as much as I thought was possible. The existing SotW GrpcMux is pretty intricately woven into itself, in particular with the watches and subscription state all being internal, not particularly modular logic. I'm afraid it may not be possible to replace any of it without effectively doing as much of a rewrite as I already am.

**Comment by fredlas** [comment]
Actually, having now arranged my thoughts, I realize the only investigation left to be done in the context of this change is the yes/no question of whether the timer-disabling logic difference caused the hang. If a test of the current state of the PR (matching the existing timer-disabling logic) no longer exhibits the hang, then (IIUC) @rgs1 and company find the current intended timer-disabling logic to be wrong. In that case, this PR can just continue matching the existing behavior, and the whole discussion should continue separately. If the PR still exhibits the hang, then we have uncovered a bug in the existing code, but one that is not relevant to this PR other than having been discovered by it.

**Comment by rgs1** [comment]
> Actually, having now arranged my thoughts, I realize the only investigation left to be done in the context of this change is the yes/no question of whether the timer-disabling logic difference caused the hang. If a test of the current state of the PR (matching the existing timer-disabling logic) no longer exhibits the hang, then (IIUC) @rgs1 and company find the current intended timer-disabling logic to be wrong. In that case, this PR can just continue matching the existing behavior, and the whole discussion should continue separately. If the PR still exhibits the hang, then we have uncovered a bug in the existing code, but one that is not relevant to this PR other than having been discovered by it.

So let's leave aside for now the fact that some members of my team were happy with this stopping a bad config from creeping in, to make it simpler.

Can you update your PR to reconcile the timer-disabling logic difference and then I can try that with our "bad config" and see if Envoy still starts? Regardless of that being good for us, at least it gets us back with previous behavior/expectations which I think would unblock you to get this merged?

**Comment by fredlas** [comment]
Sure, the current state has that logic now made to be equivalent to current head of master. If you would like to test it out, go right ahead with how it is now, although if you would like more logs to shed better light in case it doesn't fix it, then I will need to add those first!

**Comment by mattklein123** [comment]
Thanks @fredlas @rgs1. Agreed that we can defer conversation about the correctness of the existing behavior to later (IMO it is correct) but we definitely need to match the existing behavior. If we can verify that is the case and add a test, we can then get this merged.

**Comment by fredlas** [comment]
Ok, added some more logging; @rgs1 please give it a run! Even if it doesn't work, the logs will hopefully  be enough to point me to the real problem...

**Comment by mattklein123** [comment]
@rgs1 friendly ping on this. Did you have a chance to test this out? Thank you!

**Comment by fredlas** [comment]
In progress - I merged just now so that the thing being tested would include the recent security patches.

**Comment by rgs1** [comment]
> @rgs1 friendly ping on this. Did you have a chance to test this out? Thank you!

Sorry, getting to this now... should have something to share by tomorrow.

**Comment by rgs1** [comment]
@mattklein123 so I just dropped @fredlas' branch on top of master as of yesterday, and got two hosts stuck now... And what's interesting is, they are not even running the "problematic" spiffe config that triggered this in the first place. 

I'll get some logs entries and follow-up offline with @fredlas.

**Comment by mattklein123** [comment]
> I'll get some logs entries and follow-up offline with @fredlas.

Awesome thank you!

**Comment by rgs1** [comment]
So, it seems we are stuck at `GrpcMuxImpl::trySendDiscoveryRequests()` in `source/common/config/grpc_mux_impl.cc` :

```
void GrpcMuxImpl::trySendDiscoveryRequests() {                                                                                                                                  
  while (true) {                                                                                                                                                                
    // Do any of our subscriptions even want to send a request?                                                                                                                 
    absl::optional<std::string> request_type_if_any = whoWantsToSendDiscoveryRequest();                                                                                         
    if (!request_type_if_any.has_value()) {                                                                                                                                     
      break;                                                                                                                                                                    
    }                                                                                                                                                                           
    // If so, which one (by type_url)?                                                                                                                                          
    std::string next_request_type_url = request_type_if_any.value();                                                                                                            
    SubscriptionState& sub = subscriptionStateFor(next_request_type_url);                                                                                                       
    ENVOY_LOG(debug, "GrpcMuxImpl wants to send discovery request for {}", next_request_type_url);                                                                              
    // Try again later if paused/rate limited/stream down.                                                                                                                      
    if (!canSendDiscoveryRequest(next_request_type_url)) {                                                                                                                      
      break;                                                                                                                                                                    
    }                                                                                                                                                                           
    // Get our subscription state to generate the appropriate discovery request, and send.                                                                                      
    if (!pausable_ack_queue_.empty()) {                                                                                                                                         
      // Because ACKs take precedence over plain requests, if there is anything in the queue, it's                                                                              
      // safe to assume it's of the type_url that we're wanting to send.                                                                                                        
      //                                                                                                                                                                        
      // getNextRequestWithAck() returns a raw unowned pointer, which sendGrpcMessage deletes.                                                                                  
      sendGrpcMessage(sub.getNextRequestWithAck(pausable_ack_queue_.front()));                                                                                                  
      pausable_ack_queue_.pop();                                                                                                                                                
      ENVOY_LOG(debug, "GrpcMuxImpl sent ACK discovery request for {}", next_request_type_url);                                                                                 
    } else {                                                                                                                                                                    
      // getNextRequestAckless() returns a raw unowned pointer, which sendGrpcMessage deletes.                                                                                  
      sendGrpcMessage(sub.getNextRequestAckless());                                                                                                                             
      ENVOY_LOG(debug, "GrpcMuxImpl sent non-ACK discovery request for {}", next_request_type_url);                                                                             
    }                                                                                                                                                                           
  }                                                                                                                                                                             
  maybeUpdateQueueSizeStat(pausable_ack_queue_.size());                                                                                                                         
}
```

From our logs, we never leave that loop (timestamps removed for readability, but it loops every ~2 secs):

```
 GrpcMuxImpl wants to send discovery request for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
 GrpcMuxImpl sent ACK discovery request for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
 type.googleapis.com/envoy.api.v2.ClusterLoadAssignment received SotW update
 type.googleapis.com/envoy.api.v2.ClusterLoadAssignment SotW update successful
 GrpcMuxImpl wants to send discovery request for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
 GrpcMuxImpl sent ACK discovery request for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
 type.googleapis.com/envoy.api.v2.ClusterLoadAssignment received SotW update
 type.googleapis.com/envoy.api.v2.ClusterLoadAssignment SotW update successful
 GrpcMuxImpl wants to send discovery request for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
 GrpcMuxImpl sent ACK discovery request for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
 type.googleapis.com/envoy.api.v2.ClusterLoadAssignment received SotW update
 type.googleapis.com/envoy.api.v2.ClusterLoadAssignment SotW update successful
 GrpcMuxImpl wants to send discovery request for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
 GrpcMuxImpl sent ACK discovery request for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
 type.googleapis.com/envoy.api.v2.ClusterLoadAssignment received SotW update
 type.googleapis.com/envoy.api.v2.ClusterLoadAssignment SotW update successful
```

**Comment by rgs1** [comment]
So our two possibilities for exiting that loop are:

1)
```
    // Do any of our subscriptions even want to send a request?                                                                                                                 
    absl::optional<std::string> request_type_if_any = whoWantsToSendDiscoveryRequest();                                                                                         
    if (!request_type_if_any.has_value()) {                                                                                                                                     
      break;                                                                                                                                                                    
    }  
```

2)
```
    // Try again later if paused/rate limited/stream down.                                                                                                                      
    if (!canSendDiscoveryRequest(next_request_type_url)) {                                                                                                                      
      break;                                                                                                                                                                    
    }  
```

Let me check what's going on in those...

**Comment by fredlas** [comment]
I think (and looks confirmed by other lines in the log showing messages from the server) that it is not an infinite loop, but rather repeated visits to that loop. The server is sending a new DiscoveryResponse every ~2 seconds, prompting those bursts of activity.

**Comment by rgs1** [comment]
Quick update:

I can't repro the prev loop anymore:

```
GrpcMuxImpl wants to send discovery request for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
GrpcMuxImpl sent ACK discovery request for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
type.googleapis.com/envoy.api.v2.ClusterLoadAssignment received SotW update
type.googleapis.com/envoy.api.v2.ClusterLoadAssignment SotW update successful
```

but, on the other hand although it's still failing to load listeners/clusters the fetch timeout seems to be working because I am getting:

```
[2019-12-13 00:08:17.122][15][debug][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:87] type.googleapis.com/envoy.api.v2.Cluster update failed: FetchTimedout
[2019-12-13 00:08:27.122][15][debug][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:87] type.googleapis.com/envoy.api.v2.Listener update failed: FetchTimedout

```

And server state gets to `LIVE`:

```
$ curl -s 0:9901/server_info  |egrep state
 "state": "LIVE",
```

which I think we believe was the original behavior that regressed?

**Comment by rgs1** [comment]
And.... ignore what I just set. I moved the repro to the wrong env where configs were missing, thus the above error... Trying again.

**Comment by rgs1** [comment]
Ok, sorry for the above confusion when my repro got mixed up with other ongoing experiments.

This is what we have when setting the log level to `trace`:

```
[2019-12-13 00:41:13.894][15][debug][config] [external/envoy/source/common/config/sotw_subscription_state.cc:80] Config update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment (version 2019-12-12 22:52:06.730034005 +0000 UTC m=+0.022213113#3274) accepted with 1 resources
[2019-12-13 00:41:15.774][15][debug][config] [external/envoy/source/common/config/sotw_subscription_state.cc:80] Config update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment (version 2019-12-12 22:52:06.730034005 +0000 UTC m=+0.022213113#3275) accepted with 1 resources
[2019-12-13 00:41:17.799][15][debug][config] [external/envoy/source/common/config/sotw_subscription_state.cc:80] Config update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment (version 2019-12-12 22:52:06.730034005 +0000 UTC m=+0.022213113#3276) accepted with 1 resources
[2019-12-13 00:41:21.899][15][debug][config] [external/envoy/source/common/config/sotw_subscription_state.cc:80] Config update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment (version 2019-12-12 22:52:06.730034005 +0000 UTC m=+0.022213113#3278) accepted with 1 resources
[2019-12-13 00:41:23.797][15][debug][config] [external/envoy/source/common/config/sotw_subscription_state.cc:80] Config update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment (version 2019-12-12 22:52:06.730034005 +0000 UTC m=+0.022213113#3279) accepted with 1 resources
[2019-12-13 00:41:27.801][15][debug][config] [external/envoy/source/common/config/sotw_subscription_state.cc:80] Config update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment (version 2019-12-12 22:52:06.730034005 +0000 UTC m=+0.022213113#3281) accepted with 1 resources
[2019-12-13 00:41:33.799][15][debug][config] [external/envoy/source/common/config/sotw_subscription_state.cc:80] Config update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment (version 2019-12-12 22:52:06.730034005 +0000 UTC m=+0.022213113#3284) accepted with 1 resources
```

We are accepting the same ClusterLoadAssignment version again and again...

@mattklein123 @ramaraochavali would that cause init to be stuck on `PRE_INITIALIZING` ?

**Comment by mattklein123** [comment]
> @mattklein123 @ramaraochavali would that cause init to be stuck on PRE_INITIALIZING ?

IMO it should not be stuck here and should continue one way or the other, so there is some bug, but TBH I'm pretty far removed from xDS client these days. cc @htuch @fredlas @wgallagher ^

**Comment by ramaraochavali** [comment]
interesting, I think it is because the init fetch timer is disabled on every config update here https://github.com/envoyproxy/envoy/blob/master/source/common/config/grpc_mux_subscription_impl.cc#L52 - the time out will not help. The timeout is also not intended for this case. But, once ClusterLoadAssignments are received for every EDS cluster, cluster initialization should move forward to next stage if all clusters have endpoints or will timeout if endpoints for some clusters were missing.

**Comment by fredlas** [comment]
I think it's worth mentioning #9206, which is a problem seen when using the existing DELTA_GRPC (so, basically identical logic to this). Unlike there, our current case does see an LDS request sent, so it's not exactly the same problem. However, it feels pretty close, since it's about init getting stuck.

The facts of that one point to something being wrong outside of the xDS client logic. That is, everything seen of the xDS client's behavior is correct (AFAICT), but Envoy is using GrpcSubscription in a way that gets it into trouble. (Or not using, more like: the problem there is that Envoy never even starts an LDS subscription).

**Comment by wgallagher** [comment]
I think that splitting up this change into smaller pieces is probably the best way to get it submitted. I don't have any specific ideas about what the split lines should be but I would be more than happy to help if that's the route we decide we want to take.

**Comment by fredlas** [comment]
It turns out the every-2-seconds update thing was a red herring; the exact same happens with the working head-of-master code (and everything is fine). It sounds like the only real problem is listeners not getting received. So, I think this problem is the same as #9206, or else very close.

**Comment by fredlas** [comment]
Yeah, doing as much as possible in small pieces might be necessary. "Something about init" is not much to go on, and if nobody who is familiar with the init code narrows it down, it will be hard to make progress.

Unfortunately I think breaking it up is going to be awkward. The old gRPC ADS code needed to be rewritten because it wasn't amenable to a slightly different sibling version like delta, and it wasn't amenable because the logic evolved to be interwoven in a single ball with itself, in places where the new code needs to be modular. I think at some point there will be fundamental mismatches.

But, at least as a start, the big `try` in `GrpcMuxImpl::onDiscoveryResponse()` should be replaceable pretty directly by the SotW variant of `WatchMap::onConfigUpdate()`. However, that will mean adding WatchMap to GrpcMuxImpl as the component responsible for watches. The current setup has watches being their own objects, with RAII behavior. GrpcMuxSubscriptionImpl will also need a little adjustment to its current interaction with the watches.

The only other logic touching watches is the "Maintain a set to avoid dupes" part of `GrpcMuxImpl::sendDiscoveryRequest()`. That is basically an on-the-fly reconstruction of what SotwSubscriptionState::names_tracked_ tracks. That can probably stay as-is, might just need to provide a way to reach into WatchMap and see resource names.

**Comment by mattklein123** [comment]
@fredlas I think @wgallagher has some thoughts on how to split this up. I'm going to close this out for now and @wgallagher will follow up with next steps. Thank you for helping to look into this issue. Really appreciate it.

**Pull request closed without merging**
