### PR TITLE
proxy protocol: add release note for PPv2 TLV pass through

### PR DESCRIPTION
**Pull request by botengyao**
Signed-off-by: Boteng Yao [boteng@google.com](mailto:boteng@google.com)

 Add release note for PP v2 pass through and polish the API comments.

Commit Message:
Additional Description:
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by wbpcode** [comment]
api only change. cc @markdroth

**Review by yanavlasov — APPROVED** [review]

**Comment by yanavlasov** [comment]
This is a doc only change. Not API changes in this PR.

**Pull request merged**
