### PR TITLE
grpc_stats: removed runtime feature after deprecation period

### PR DESCRIPTION
**Pull request by ggreenway**
Commit Message: Removing
`envoy.deprecated_features.grpc_stats_filter_enable_stats_for_all_methods_by_default` which has been deprecated since 2021.

Additional Description:
Risk Level: low
Testing: existing unit tests
Docs Changes: docs update
Release Notes: added
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by ggreenway** [comment]
This has been deprecated since https://github.com/envoyproxy/envoy/pull/14815 but somehow removing the old codepath was missed.

**Comment by alyssawilk** [comment]
@lizan ping!

**Review by jmarantz — APPROVED** [review]

**Pull request merged**
