### PR TITLE
optimize: rename `Success` to `Completed`

### PR DESCRIPTION
**Pull request by chenylh**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by zuercher** [comment]
Is there any purpose here beyond fixing the todo for the sake of it? In addition, there are at least 2 files that contain references to the enum that weren't updated.

**Comment by chenylh** [comment]
> Is there any purpose here beyond fixing the todo for the sake of it? In addition, there are at least 2 files that contain references to the enum that weren't updated.

There is no other purpose. I forgot to check the test file，I have fixed it

**Comment by zuercher** [comment]
cc @abeyad since you left the TODO originally

**Review by abeyad — APPROVED** [review]
Thanks for doing this!  LGTM, adding Alyssa as a senior maintainer reviewer

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
