### PR TITLE
Windows ci add bazel args

### PR DESCRIPTION
**Pull request by wrowe**
Commit Message: Windows ci add bazel args
Additional Description:

The linux do_ci.sh script has it's own unique syntax, earlier represented in windows_ci_steps.ps1.
It turns out this isn't the most obvious syntax, but bazel instead, as the macos_ci_steps.sh script
uses.

Enhance windows_ci_steps.sh to default to //source/exe:envoy-static + //test/... as was the current
default behavior, but recognize either of these independently, or allow pretty much any bazel
target to be named on the command line for development and diagnostics.

Risk Level: low
Testing: local msvc
Docs Changes: TBD
Release Notes: TBD
Platform Specific Features: Windows build only

### CODE REVIEW

**Comment by wrowe** [comment]
Note, that this commit moves //bazel/... to the end of the build. Yes, we want to ensure we catch anything dropped in on bazel/foreign_cc or bazel/external, but we don't have to delay 98% of all PR's to look at this upfront. Fail faster in the general case.

**Review by davinci26 — CHANGES_REQUESTED** [review]
LGTM, thanks! 

Do you mind also updating the docs at `bazel\Readme.md` and `ci\Readme.md`

**Review by sunjayBhatia — APPROVED** [review]
👍🏽

**Comment by wrowe** [comment]
@mattklein123 this is ready with the fix to the three too-long-named borken //test/... entities, let's see if CI passes and merge if so.

Will come back after bazel 5.0.0 is in our rbe to re-enable these.

**Review by davinci26 — APPROVED** [review]
LGTM, can you open an issue so we remember to turn these tests back on

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
