### PR TITLE
tracing: introduce `TracerFactoryContext` abstraction

### PR DESCRIPTION
**Pull request by yskopets**
Description: introduce `TracerFactoryContext` abstraction to replace `Server::Instance` as an argument to `TracerFactory::createHttpTracer(config, context)`
Risk Level: Medium
Testing: unit test
Docs Changes: N/A
Release Notes: N/A

Context:
* This PR lays groundwork for implementing #9998
* Before this PR, `TracerFactory::createHttpTracer(config, context)` implementations worked directly with `Server::Instance`, which will not be possible once the responsibility to instantiate `HttpTracer`s is passed to `envoy.http_connection_manager` filter
* This PR introduces a `TracerFactoryContext` abstraction to replace `Server::Instance` as an argument to `TracerFactory::createHttpTracer(config, context)`
* At the moment, `TracerFactoryContext` is roughly an equivalent of `ServerFactoryContext`

### CODE REVIEW

**Comment by mattklein123** [comment]
Sorry CI failure looks legit.

/wait

**Comment by yskopets** [comment]
Looking into it

**Comment by yskopets** [comment]
@mattklein123 

I've fixed the unit test that was affected by my changes.

Unfortunately, `coverage` build is still failing and I'm not competent enough to understand why.

I've re-run `coverage` build multiple times, and every time a different test fails, i.e.
* `PrometheusStatsFormatterTest.OutputWithUsedOnly`
* `PrometheusStatsFormatterTest.OutputWithAllMetricTypes`
* `QuicMemSliceStorageImplTest.MultipleIovInMultipleSlice`

I cannot reproduce these failures in my dev environment (`MacOS`), the tests succeed all the time.

I see that other PRs are failing with the same errors.

Sorry, I need some help.

**Pull request merged**
