### PR TITLE
oauth: add disable_id_token_set_cookie option

### LINKED ISSUE #33825: OAuth2 Filter - ID Token Cookie Too Large
*Title*: *It's possible ID token is too large for cookie*

*Description*:
Our IDP can return large amounts of data in ID tokens. This is causing SSO to fail with the filter as the ID token is never present
image

image

Can we either breakup the cookies to support larger payloads, or allow an option to exclude the ID token from the cookies?

*Repro steps*:

1. Setup Filter for SSO
2. Add over 4KB of payload to the ID token on the token issuer
3. Login with the filter and observe failure

### PR DESCRIPTION
**Pull request by derekargueta**
Commit Message: oauth: add disable_id_token_set_cookie option
Additional Description: When this is enabled, Envoy will stop setting the IdToken cookie. It will still take into account HMACs with IdTokens if they are available (to support existing auth sessions) but new authentication will not use the IdToken in the HMAC.
Risk Level: log
Testing: included
Docs Changes: included
Release Notes: included
Fixes #33825

### CODE REVIEW

**Comment by mattklein123** [comment]
LGTM. Can you check CI?

/wait

**Comment by derekargueta** [comment]
hit an unrelated test flake in generic_proxy

```
[ RUN      ] IpVersions/IntegrationTest.MultipleRequestsWithMultipleFrames/IPv6
[2024-06-10 21:48:02.764][93782][critical][assert] [contrib/generic_proxy/filters/network/test/integration_test.cc:756] assert failure: waitDownstreamResponseForTest(TestUtility::DefaultTimeout, 2). Details: unexpected timeout
[2024-06-10 21:48:02.764][93782][critical][backtrace] [./source/server/backtrace.h:127] Caught Aborted, suspect faulting address 0x3e900016e56
[2024-06-10 21:48:02.764][93782][critical][backtrace] [./source/server/backtrace.h:111] Backtrace (use tools/stack_decode.py to get line numbers):
[2024-06-10 21:48:02.764][93782][critical][backtrace] [./source/server/backtrace.h:112] Envoy version: 0/1.31.0-dev/test/RELEASE/BoringSSL
[2024-06-10 21:48:02.764][93782][critical][backtrace] [./source/server/backtrace.h:119] #0: __kernel_rt_sigreturn [0xeb295963b9d0]
[2024-06-10 21:48:02.764][93782][critical][backtrace] [./source/server/backtrace.h:119] #1: abort [0xeb29593b0aac]
[2024-06-10 21:48:02.775][93782][critical][backtrace] [./source/server/backtrace.h:119] #2: Envoy::Extensions::NetworkFilters::GenericProxy::(anonymous namespace)::IntegrationTest_MultipleRequestsWithMultipleFrames_Test::TestBody() [0xb3ece0]
[2024-06-10 21:48:02.786][93782][critical][backtrace] [./source/server/backtrace.h:119] #3: testing::internal::HandleExceptionsInMethodIfSupported<>() [0x1eed8c4]
[2024-06-10 21:48:02.797][93782][critical][backtrace] [./source/server/backtrace.h:119] #4: testing::Test::Run() [0x1eed760]
[2024-06-10 21:48:02.808][93782][critical][backtrace] [./source/server/backtrace.h:119] #5: testing::TestInfo::Run() [0x1eee980]
[2024-06-10 21:48:02.819][93782][critical][backtrace] [./source/server/backtrace.h:119] #6: testing::TestSuite::Run() [0x1eef798]
[2024-06-10 21:48:02.830][93782][critical][backtrace] [./source/server/backtrace.h:119] #7: testing::internal::UnitTestImpl::RunAllTests() [0x1efd7c8]
[2024-06-10 21:48:02.841][93782][critical][backtrace] [./source/server/backtrace.h:119] #8: testing::internal::HandleExceptionsInMethodIfSupported<>() [0x1efd298]
[2024-06-10 21:48:02.852][93782][critical][backtrace] [./source/server/backtrace.h:119] #9: testing::UnitTest::Run() [0x1efd0f4]
[2024-06-10 21:48:02.863][93782][critical][backtrace] [./source/server/backtrace.h:119] #10: Envoy::TestRunner::runTests() [0x1898d20]
[2024-06-10 21:48:02.875][93782][critical][backtrace] [./source/server/backtrace.h:119] #11: main [0x1897ac4]
[2024-06-10 21:48:02.875][93782][critical][backtrace] [./source/server/backtrace.h:119] #12: __libc_start_main [0xeb29593b0e10]
```

**Review by mattklein123 — DISMISSED** [review]

**Comment by derekargueta** [comment]
welp
```
time="2024-06-14T18:56:12Z" level=fatal msg="writing blob: saving image to docker engine: Error response from daemon: {\"message\":\"client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version\"}"
```

looks like this check is failing on other PRs as well

**Comment by tyxia** [comment]
@derekargueta Yes, Publish and verify CI failure is not related. Please merge main to resolve the conflict.

I will merge this commit once conflict is resolved, given the API and code have both been approved.

**Comment by tyxia** [comment]
/wait

merge conflict to be resolved.

**Review by tyxia — APPROVED** [review]
api has been approved [here](https://github.com/envoyproxy/envoy/pull/34613#issuecomment-2158810750) and implementation has been approved [here](https://github.com/envoyproxy/envoy/pull/34613#issuecomment-2159023276)

**Pull request merged**
