### PR TITLE
examples: Add (optional) image cleanup (rmi)

### PR DESCRIPTION
**Pull request by phlax**
if the env var `DOCKER_RMI_CLEANUP` is set, this will remove any images listed for the `RMI` variable in an example's verify.sh.

also:

- fixes some permissions in the build entrypoint
- adds some cleanups for the `wasm-cc` example

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @wangfakang

**Comment by phlax** [comment]
this runs `image prune -f` after every sandbox which was not my original intention - but i think its probably a good thing in terms of disk space

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Comment by phlax** [comment]
i had to merge/resolve this one

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
