### PR TITLE
deps: Aggregate dependabot updates

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
im going to look further to figure out why our attempts to fix dependabot so far have failed, in the meantime this aggregates the recent updates (need to fix...)

**Comment by phlax** [comment]
cc @kfaseela 

heads up that a recent update to pip-tools now means that dependabot replaces all package separators with `-` - who knows why, but no point trying to fight it - anyone updating pip locallly will need a recent version of pip-tools

```
$ pip freeze | grep pip-tools
pip-tools==6.5.1
```

**Comment by phlax** [comment]
...minus the twitter update which breaks the thrift test

**Comment by kfaseela** [comment]
thanks @phlax looks good!

**Review by kfaseela — APPROVED** [review]

**Review by daixiang0 — APPROVED** [review]

**Comment by phlax** [comment]
apologies for force-push - i have added the latest dependabot pr to this

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!
@phlax leaving it up to you to decide when to merge this.

**Pull request merged**
