### PR TITLE
Reverting 22c00c5a4bbb09d1a5cbd32063fd3123a44e307f

### PR DESCRIPTION
**Pull request by alyssawilk**
Problems reported in production, h/t @ravenblackx @jpsim 

Risk Level: low: revert
Testing: n/a
Docs Changes: n.a
Release Notes: n/a
Fixes commit: 22c00c5a4bbb09d1a5cbd32063fd3123a44e307f

### CODE REVIEW

**Review by jpsim — APPROVED** [review]
+1 I don't have a consistent repro for the issues I've been seeing, but it seems plausible that this would be causing it.

**Review by KBaichoo — APPROVED** [review]

**Comment by alyssawilk** [comment]
not sure why clang tidy is unhappy with a rollback so I'm going to force merge to get the fix in as I believe clang is diff based anyway

**Comment by ruwaifaa** [comment]
Curious, what was the issue?

**Comment by alyssawilk** [comment]
https://groups.google.com/g/envoy-announce/c/b9tQzVpJ5Ro

**Pull request merged**
