### PR TITLE
rlqs: fix time_elapsed logic and add more logging

### PR DESCRIPTION
**Pull request by tyxia**
- `last_report` should be updated every time the report is built.
- add more debug logging about request and response 
- check the periodical quota usage report content: # of request allowed; time_elapsed

### CODE REVIEW

**Comment by tyxia** [comment]
/assign @yanavlasov  

PTAL Thanks! The CI coverage failure (in source/common) is unrelated to this PR. Looks like all open PRs are affected by this coverage regression.

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
