### PR TITLE
tls: refactor to return the session context ID

### PR DESCRIPTION
**Pull request by jpeach**
Refactor the TLS session context ID generation to return the ID by
value. This separates the buffers that are used for intermediate
hashes from the buffer that stores the final session context ID hash.

*Risk Level:* Low
*Testing:* unit tests
*Docs Changes:* N/A
*Release Notes:* N/A
*Updates:* #9182

### CODE REVIEW

**Comment by mattklein123** [comment]
Can you provide my context for the rationale behind this change? It's not clear why it's needed. Thank you.

/wait-any

**Comment by jpeach** [comment]
This is a cleanup that was broken out of #9275. It clarifies the API because the session ID in/out result is no longer also used as a temporary buffer for intermediate hash results. The next patch will start throwing exceptions. By returning the result directly, we ensure that if an exception is thrown, no side-effects or partial results are ever visible (though in the way this API is currently used, that's only a problem in principle, not in practice).

**Comment by mattklein123** [comment]
> (though in the way this API is currently used, that's only a problem in principle, not in practice)

In general I'm not a fan of change for change sake but will defer to @lizan or @PiotrSikora to take a look. Thank you!

**Comment by jpeach** [comment]
> In general I'm not a fan of change for change sake

This does make it easier to write the final patch in this series, which will fix the actual issue :)

**Comment by jpeach** [comment]
@lizan @PiotrSikora Do you have any feedback on this?

**Comment by PiotrSikora** [comment]
This is purely a style change, so I have no objections, assuming that this is needed for something.

**Comment by jpeach** [comment]
@PiotrSikora This is extracted from PR #9275. IMHO returning the session ID directly makes the code cleaner when we start throwing exceptions.

**Comment by PiotrSikora** [comment]
@jpeach looking at that PR, I don't see why this change is needed. It might be slightly cleaner, but it doesn't seem necessary?

**Comment by jpeach** [comment]
> @jpeach looking at that PR, I don't see why this change is needed. It might be slightly cleaner, but it doesn't seem necessary?

My goal in the PR wasn't to necessarily to make the minimal change, rather to clean up and them make the easy change. If I wasn't making a fix I probably would not have bothered with a clean up. Is the goal here to make a minimal change without cleanup up any code?

**Comment by PiotrSikora** [comment]
@jpeach like I said, I don't have any objections, but it should be clear that this is a cleanup and not prerequisite to the next change. In any case, I don't have any powers here, so I'll let @lizan and/or @mattklein123 to decide what to do with it.

**Comment by jpeach** [comment]
> On Jan 14, 2020, at 10:19 AM, Piotr Sikora <notifications@github.com> wrote:
> 
> but it should be clear that this is a cleanup and not prerequisite to the next change

It’s a cleanup, but I meant prerequisite in the textual patch series sense. Assuming I can clean this up, subsequent patches will depend on it.

**Comment by mattklein123** [comment]
I will defer to @lizan on whether this makes sense or not as an aesthetic change.

**Comment by jpeach** [comment]
Done, thanks @lizan

**Pull request merged**
