### PR TITLE
golang filter: move go.mod & go.sum to the root directory.

### LINKED ISSUE #26527: Make envoy tags usable for golang filter SDK
*Title*:

Make envoy tags usable for golang filter SDK

*Description*:

I'm using the golang sdk in my golang filter, but since I'm  using Envoy v1.25.3 I had to reverse engineer the ref to be placed in my go.mod file to be

```
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go v0.0.0-20230112191108-90880d93a9bd
```

It would be nice to be able to specify the same envoy version to make sure they always match, such as 

```
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go v1.25.3
```

### PR DESCRIPTION
**Pull request by doujiang24**
Commit Message:

1. move go.mod to the root directory, fix #26527 

2. we also add some empty go.mod file in some directories, to exclude those directories, to make the root go.mod simple.
   see: https://github.com/golang/go/wiki/Modules#can-an-additional-gomod-exclude-unnecessary-content-do-modules-have-the-equivalent-of-a-gitignore-file

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by doujiang24** [comment]
/assign @phlax 
Thank you.

**Review by phlax — COMMENTED** [review]
do we need the empty go.mod files ?

**Comment by doujiang24** [comment]
Yep, without those empty go.mod files, the root go.mod will be like this, after run `go mod tidy` in the root directory:
(in golang world, we usually use `go mod tidy` to format the go.mod file automatically).
```
module github.com/envoyproxy/envoy

go 1.18

require (
        github.com/envoyproxy/go-control-plane v0.11.0
        github.com/golang/protobuf v1.5.2
        google.golang.org/protobuf v1.30.0
)

require (
        github.com/census-instrumentation/opencensus-proto v0.4.1 // indirect
        github.com/cncf/xds/go v0.0.0-20220314180256-7f1daf1720fc // indirect
        github.com/envoyproxy/protoc-gen-validate v0.9.1 // indirect
        github.com/prometheus/client_model v0.3.0 // indirect
        golang.org/x/net v0.4.0 // indirect
        golang.org/x/sys v0.3.0 // indirect
        golang.org/x/text v0.5.0 // indirect
        google.golang.org/genproto v0.0.0-20221118155620-16455021b5e6 // indirect
        google.golang.org/grpc v1.52.0 // indirect
)
```

these empty go.mod files, means exclude the subdirectories:
see: https://github.com/golang/go/wiki/Modules#can-an-additional-gomod-exclude-unnecessary-content-do-modules-have-the-equivalent-of-a-gitignore-file

Remove those empty go.mod files will also work for users, but the go mod that people imported in other projects, will be a bit larger, since it will include those unnecessary go files.

**Review by phlax — APPROVED** [review]
lgtm, thanks @doujiang24

**Pull request merged**
