### PR TITLE
[WIP] deps: Bump `com_envoyproxy_protoc_gen_validate` -> 0.6.3

### LINKED ISSUE #19531: Newer release available `com_envoyproxy_protoc_gen_validate`: v0.6.3 (current: v0.6.2)
Package Name: com_envoyproxy_protoc_gen_validate
Current Version: v0.6.2@2021-10-21 19:17:00
Available Version: v0.6.3@2022-01-12 21:05:58
Upstream releases: https://github.com/envoyproxy/protoc-gen-validate/releases

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #19531
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
failing with

```console
external/com_envoyproxy_protoc_gen_validate/main.go:13:35: undefined: pgs.SupportedFeatures
```


https://dev.azure.com/cncf/envoy/_build/results?buildId=98945&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=6b0ace90-28b2-51d9-2951-b1fd35e67dec&l=1913

**Comment by phlax** [comment]
i fixed the dep problem above, but now getting

```console
bazel-out/k8-opt/bin/external/envoy_api/envoy/config/core/v3/protocol.pb.validate.cc:2095:18: error: unexpected type name 'string': expected expression
        const std::set<*string> _SchemeHeaderTransformation_SchemeToOverwrite_InLookup = {

```

**Comment by phlax** [comment]
@htuch ive tried updating all the upstream go deps to ensure they match what is in `go.mod`

i think the upstream change that is causing the breakage here is https://github.com/envoyproxy/protoc-gen-validate/commit/dc51e59d2e463996ef24e45621cf61f95fa64b0f but its a bit beyond my immediate knowledge to figure out the cause of breakage

**Comment by htuch** [comment]
@adisuissa we'll probably need this fixed for import.

**Comment by adisuissa** [comment]
Initial triage seems to point that using PGV's string "in" validator inside a `oneof` causes this breakage, but I'm unable to get the PGV dev env working to show where the test breaks.
I'll try to debug it further.

**Comment by adisuissa** [comment]
Opened https://github.com/envoyproxy/protoc-gen-validate/issues/563 with the issue

**Pull request closed without merging**
