### PR TITLE
bazelci: macos and rbe

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Comment by meteorcloudy** [comment]
This PR is probably causing Envoy to fail on Bazel CI:
https://buildkite.com/bazel/envoy/builds/944

**Comment by lizan** [comment]
@meteorcloudy yes I'm aware of that, will fix soon. Is there anyway I can test my local config against bazel CI without commit?

**Comment by meteorcloudy** [comment]
I think you can push a branch to the envoy repo, then create a new build at that branch.
https://buildkite.com/bazel/envoy

**Pull request merged**
