### PR TITLE
Add a comment just to trigger testing

### PR DESCRIPTION
**Pull request by ravenblackx**
Just trying to trigger a Windows test run because I can't do it locally.

### CODE REVIEW

**Comment by phlax** [comment]
try this:

```diff
diff --git a/.azure-pipelines/pipelines.yml b/.azure-pipelines/pipelines.yml
index ed83926ebc..23cf5ea0eb 100644
--- a/.azure-pipelines/pipelines.yml
+++ b/.azure-pipelines/pipelines.yml
@@ -836,7 +836,7 @@ stages:
         echo "macos tested"
 
 - stage: windows
-  dependsOn: ["env", "precheck"]
+  dependsOn: ["env"]  # , "precheck"]
   jobs:
   - job: release
     condition: and(not(canceled()), succeeded(), ne(stageDependencies.env.repo.outputs['changed.mobileOnly'], 'true'), ne(stageDependencies.env.repo.outputs['changed.docsOnly'], 'true'), ne(stageDependencies.env.repo.outputs['changed.examplesOnly'], 'true'))
```

**Comment by phlax** [comment]
ideally with ^^ diff - if you have to run it a few times (without force pushing) then make the rest of the pipeline fail

**Comment by ravenblackx** [comment]
Helpful - the test *was* broken by #24480 after all, it's just it was only broken for Windows because `size_t` is similar enough to `uint64_t` in Linux that a mock mixing them up doesn't cause a problem, and then Windows reported the error at completely unrelated lines in a long series of file because they happened to `#include` the mock containing that error and then the lines reporting the error used *a* mock, not a related one, not even one from that file, which somehow triggered the build warning-as-error, correctly describing the problem (casting uint64_t to Windows's size_t might lose something), but so far from describing the source of the problem that the compiler should probably be burned to the ground and started over.

**Comment by phlax** [comment]
> ... the compiler should probably be burned to the ground and started over.

so an upstream issue? i would file a ticket

cc @wrowe

**Comment by ravenblackx** [comment]
In case someone actually wants to investigate, here's a shorter version of the error than the one I was originally looking at (apparently it just picks whatever file happens to include the mock function first to fail on) (from [here](https://dev.azure.com/cncf/envoy/_build/results?buildId=123401&view=logs&j=4afecb4c-71c7-5b5c-ab99-a70ed4c927ad&t=4cd2fc51-3314-5d69-4df3-f765ae0c08dc&l=2344)):
```
ERROR: C:/source/test/server/BUILD:75:14: Compiling test/server/connection_handler_test.cc failed: (Exit 2): cl.exe failed: error executing command (from target //test/server:connection_handler_test) 
  cd /d C:/build/tmp/execroot/envoy
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET TEMP=C:\Windows\Temp
    SET TMP=C:\Windows\Temp
    SET TMPDIR=C:\Windows\Temp
    SET USE_CLANG_CL=
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe @bazel-out/x64_windows-opt/bin/test/server/_objs/connection_handler_test/connection_handler_test.obj.params
# Configuration: 5066b881b4653428d4d1a605b2f549b77915d096166c6fa81c84b433d7eaac7e
# Execution platform: @envoy_build_tools//toolchains:rbe_windows_msvc_cl_platform
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\memory(3381): error C2220: the following warning is treated as an error
test/server/connection_handler_test.cc(373): note: see reference to function template instantiation 'std::unique_ptr<Envoy::Server::`anonymous-namespace'::ConnectionHandlerTest::TestMultiAddressesListener,std::default_delete<Envoy::Server::`anonymous-namespace'::ConnectionHandlerTest::TestMultiAddressesListener>> std::make_unique<Envoy::Server::`anonymous-namespace'::ConnectionHandlerTest::TestMultiAddressesListener,Envoy::Server::`anonymous-namespace'::ConnectionHandlerTest&,uint64_t&,bool&,bool&,const std::string&,Envoy::Network::Socket::Type&,std::chrono::milliseconds,bool,std::shared_ptr<Envoy::AccessLog::MockInstance>&,absl::flat_hash_map<std::string,Envoy::Network::ConnectionBalancerSharedPtr,absl::container_internal::StringHash,absl::container_internal::StringEq,std::allocator<std::pair<const K,V>>>&,nullptr,int,bool,unsigned __int64,0>(Envoy::Server::`anonymous-namespace'::ConnectionHandlerTest &,uint64_t &,bool &,bool &,const std::string &,Envoy::Network::Socket::Type &,std::chrono::milliseconds &&,bool &&,std::shared_ptr<Envoy::AccessLog::MockInstance> &,absl::flat_hash_map<K,V,absl::container_internal::StringHash,absl::container_internal::StringEq,std::allocator<std::pair<const K,V>>> &,nullptr &&,int &&,bool &&,unsigned __int64 &&)' being compiled
        with
        [
            K=std::string,
            V=Envoy::Network::ConnectionBalancerSharedPtr
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\memory(3381): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
INFO: Elapsed time: 477.681s, Critical Path: 172.27s
INFO: 4251 processes: 797 remote cache hit, 2221 internal, 1233 remote.
FAILED: Build did NOT complete successfully
//test/server:connection_handler_test                           FAILED TO BUILD
```
And the erroneous thing causing the breakage was effectively the inverse of [this](https://github.com/envoyproxy/envoy/pull/24480/commits/03a2aefa752dafec140191eb41f88b82836f943c) change, as part of #24480.

**Pull request closed without merging**
