### PR TITLE
Simlify convertion from absl string_view

### PR DESCRIPTION
**Pull request by theidexisted**
Commit Message: rocketmq_proxy: Simplify the conversion for absl::string_view
Additional Description: N/A
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by theidexisted** [comment]
envoy-presubmit (check linux_x64 clang_tidy)

**Comment by asraa** [comment]
Could you please fix the DCO check? See here: https://github.com/envoyproxy/envoy/blob/ad63b1c385fe95ddd6d547a43583904c1f459abe/CONTRIBUTING.md#fixing-dco

**Comment by theidexisted** [comment]
> Could you please fix the DCO check? See here: https://github.com/envoyproxy/envoy/blob/ad63b1c385fe95ddd6d547a43583904c1f459abe/CONTRIBUTING.md#fixing-dco

Thank you for the guide, I will follow it. But for the clang-tidy check fails, the log doesn't tell the reason, could you please help me find the reason?

**Comment by asraa** [comment]
I think it was fine!

**Review by asraa — APPROVED** [review]

**Pull request merged**
