### PR TITLE
Fix bug by dividing by zero total_cluster_weight

### PR DESCRIPTION
**Pull request by hhuahh**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by adisuissa — COMMENTED** [review]
Thanks for trying to fix it.
Before getting into the details, can you explain how this can be triggered?

/wait-any

**Comment by hhuahh** [comment]
> Thanks for trying to fix it. Before getting into the details, can you explain how this can be triggered?
> 
> /wait-any

sometimes we set cluster weight to 0 to temporarily disable the cluster.

**Comment by adisuissa** [comment]
> sometimes we set cluster weight to 0 to temporarily disable the cluster.

But if the cluster-weights of all clusters is 0, then the update should be [rejected](https://github.com/envoyproxy/envoy/blob/1561bbbd4b413e3581f5c7f921b4af091efbc7b8/source/common/router/config_impl.cc#L582-L584).
Can you provide more details?

/wait-any

**Comment by hhuahh** [comment]
> > sometimes we set cluster weight to 0 to temporarily disable the cluster.
> 
> But if the cluster-weights of all clusters is 0, then the update should be [rejected](https://github.com/envoyproxy/envoy/blob/1561bbbd4b413e3581f5c7f921b4af091efbc7b8/source/common/router/config_impl.cc#L582-L584). Can you provide more details?
> 
> /wait-any

in tcp_proxy.cc:
// Weighted clusters will be enabled only if the default cluster is absent.
  if (default_route_ == nullptr && config.has_weighted_clusters()) {
    total_cluster_weight_ = 0;
    for (const envoy::extensions::filters::network::tcp_proxy::v3::TcpProxy::WeightedCluster::
             ClusterWeight& cluster_desc : config.weighted_clusters().clusters()) {
      WeightedClusterEntryConstSharedPtr cluster_entry(
          std::make_shared<const WeightedClusterEntry>(*this, cluster_desc));
      weighted_clusters_.emplace_back(std::move(cluster_entry));
      total_cluster_weight_ += weighted_clusters_.back()->clusterWeight();
    }
  }

and thrift_proxy/router/router_impl.cc:
if (route.route().cluster_specifier_case() ==
      envoy::extensions::filters::network::thrift_proxy::v3::RouteAction::ClusterSpecifierCase::
          kWeightedClusters) {

    total_cluster_weight_ = 0UL;
    for (const auto& cluster : route.route().weighted_clusters().clusters()) {
      std::unique_ptr<WeightedClusterEntry> cluster_entry(new WeightedClusterEntry(*this, cluster));
      weighted_clusters_.emplace_back(std::move(cluster_entry));
      total_cluster_weight_ += weighted_clusters_.back()->clusterWeight();
    }
  }

**Pull request closed without merging**
