### PR TITLE
Revert "upstream: enhance upstream filter state (#25917)"

### PR DESCRIPTION
**Pull request by phlax**
This reverts commit dd39b3aa1e8b649f48655350b57a3078ead1b143.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
This PR is causing a pretty frequent flake

image

**Comment by phlax** [comment]
not sure why but PRs are failing a lot more frequently - which was why i started tracking the issue

**Comment by htuch** [comment]
CC @paul-r-gall

**Review by htuch — APPROVED** [review]

**Comment by paul-r-gall** [comment]
Do you have an example failure I can take a look at?

**Comment by phlax** [comment]
if you check the (mostly useless) azp analytics ui you can find failed tests there

its more frequent in presubmit (which is a less reliable indicator) -  https://dev.azure.com/cncf/envoy/_test/analytics?definitionId=5&contextType=build

postsubmit should (theoretically) never be failing but there are a few fails there also https://dev.azure.com/cncf/envoy/_test/analytics?definitionId=11&contextType=build

**Pull request merged**
