### PR TITLE
generic proxy: new API to expose cluster and route to codec

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: generic proxy: new API to expose cluster and route to codec
Additional Description:

1. expose upstream cluster and route to the codec.
2. merge the upstreamconnection to generic upstream.
3. use ServerFactoryContext rather than FactoryContext for codec creation for upstream codec support.

Risk Level: low.
Testing: n/a.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
It's OK to give this PR a blindly approve because this is contrib only update and I am the only one active contributor and maintainer.

**Comment by htuch** [comment]
@wbpcode should https://github.com/envoyproxy/envoy/blob/6d1363a40824ee31dd6643e03e17568c8fa502df/CODEOWNERS#L390 be updated to reflect you as sole contributor / maintainer? I think ideally we have N > 1 as per the "spirit" of the extension policy.

Happy to rubber stamp, but want to use this opportuntiy to check-in on the status of this extension.

**Comment by wbpcode** [comment]
@soulxu helps a lot (I am very appreciated with all his help). But the review work also bring some burden to him. I think now I am the only active users for this extension. (some our production users will use it, but they rarely involved in the community.)

**Comment by wbpcode** [comment]
I will update the owners to me and @unknown until some new community users want to help with this.

**Review by htuch — APPROVED** [review]

**Pull request merged**
