### PR TITLE
Add Timer::enableHRTimer()

### PR DESCRIPTION
**Pull request by oschaaf**
Adds a way to set sub-millisecond timers. This generates an opportunity for Nighthawk to improve accuracy of request-release timings. The fault filter extension might leverage this as well to inject sub millisecond delays.

Implemented as an extra call instead of an overload or change to the existing one, because that way caller intent explicitly carries information about accuracy expectations. Also, adding an extra call minimizes changes needed to accomplish this.

For best results, libevent needs to be made aware too that we'd like to use precise timers.
One way to do that is by setting an environment variable called `EVENT_PRECISE_TIMER`.

```
EVENT_PRECISE_TIMER=1 bazel-bin/nighthawk_client ...
```

One thing to mind is that the max sleep time will go down from `std::chrono:millliseconds::duration::max()` to `std::chrono::microseconds::duration::max()` with this. AFAICT we will still be able to sleep for ~292277 years with that.

Description:
Risk Level: Low
Testing: By proxy, via existing tests

### CODE REVIEW

**Comment by oschaaf** [comment]
For best results, libevent needs to be made aware too that we'd like to use precise timers.
One way to do that is by setting an environment variable called EVENT_PRECISE_TIMER.

```
EVENT_PRECISE_TIMER=1 bazel-bin/nighthawk_client ...
```

**Comment by yanavlasov** [comment]
If the hi-res timers are used in the nighthawk for now, would it make sense to have this functionality just there?
Also would it make sense to make hi-res time enabled in the build files by default, instead of relying on users to remember to set on the command line during build?

**Comment by htuch** [comment]
@yanavlasov I think it's reasonable to add this to Envoy (I suggest this to @oschaaf). Why not make these the default though, rather than requiring specific enablement? Is there a performance or stability implication?

**Comment by oschaaf** [comment]
> If the hi-res timers are used in the nighthawk for now, would it make sense to have this functionality just there?

So I thought this might be nice to have here as it seemed the change wouldn't add a significant maintenance burden; as the implementation can be shared across the regular and non-HR versions (at least today).. and potentially Envoy extensions might benefit from it?

> Also would it make sense to make hi-res time enabled in the build files by default, instead of relying on users to remember to set on the command line during build?

Yes sure; alternatively this can also be set when initializing libevent instead of via setting an environment variable. But I was trying to minimize the change;

>  Why not make these the default though, rather than requiring specific enablement? Is there a performance or stability implication?

I was thinking that in Nighthawk this should be enabled by default but with an opt-out escape-latch for those who seek absolute highest throughput, as I remember there is a trade-off involved [1]. IMHO Envoy would probably better be off with an opt-in for those who run specific extensions with strict latency requirements..or maybe it would be nice to facilitate extensions that need it to enable the feature at server boot time automatically; e.g. a new interface call for extensions that Envoy can query as it starts to determine if any of those has strict latency requirements.

[1] From https://sourceforge.net/p/levent/mailman/message/29143607/
```
There are a bunch of backends that can give us a reasonably good
monotonic timer quickly, or a very precise monotonic timer less
quickly.  For example, Linux has CLOCK_MONOTONIC_COARSE (1msec
precision), which is over twice as fast as CLOCK_MONOTONIC.  Since
epoll only lets you wait with 1msec precision,
CLOCK_MONOTONIC_COARSE is a clear win.
```

**Comment by htuch** [comment]
@oschaaf this makes sense, but the implementation seems to be basically doing HR anyway for the regular timer case.

**Comment by oschaaf** [comment]
> @htuch this makes sense, but the implementation seems to be basically doing HR anyway for the regular timer case.

correct, but imho consumers shouldn't care about how the two calls are implemented internally; from the outside my idea is that one of them is to express the desire for a reasonably precise but efficient timer, and the other one is to express the desire of favoring high precision. 

(the doxygen comments might be a good place to clarify this in case we want to take this forward)

I was thinking that this distinction might some day be useful, perhaps knowledge about caller intent might be leveraged some day to optimize with coarse grained timer coalescing when favoring efficiency

**Comment by htuch** [comment]
@oschaaf yeah, that's reasonable. Can you add some tests for the new method?

**Comment by oschaaf** [comment]
> @oschaaf yeah, that's reasonable. Can you add some tests for the new method?

I took a stab at that. 9f00ad8b68374b148926399b986b48ef7c0022dc explicitly shares some test code between `enableTimer()` and `enableHRTimer()`.

**Comment by oschaaf** [comment]
> Thanks.. one thing I'd be curious about is whether it's possible to use simulated time to actually capture the timing precision? Not sure how feasible that is, LGTM otherwise.

Nice, that works, and the new tests also functionally covers theoretical precision for the regular `enableTimer()` implementation: https://github.com/envoyproxy/envoy/pull/9155/commits/2dca2133532280c41c829e55368fa99e0985990a

**Pull request merged**
