### PR TITLE
build: Bump image -> `7304f974de2` (take 2)

### PR DESCRIPTION
**Pull request by phlax**
and revert:

- #24979
- #25061

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @wrowe @lizan - the postsubmit key is an easy fix i think, not sure what to do about win fail

**Comment by phlax** [comment]
would be good to get this landed (and onto release branches) asap!

**Review by jpsim — APPROVED** [review]

**Comment by jpsim** [comment]
You'll need to merge `main` to get https://github.com/envoyproxy/envoy/pull/25166

I apologize for the inconvenience.

**Comment by phlax** [comment]
np, thanks - i think there are other fixes pending also

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
