### PR TITLE
Revert "bazel: update rules_foreign_cc (#17445)"

### PR DESCRIPTION
**Pull request by junr03**
This reverts commit 5e48a19b20c10f31750ce430721ea868e7b1c457. 

The update breaks the ability to compile from a MacOS host for an iOS device. For example the sysroot choice [here](https://github.com/bazelbuild/rules_foreign_cc/blob/be7269694444249ee48ac7bca285bc4443b127f9/foreign_cc/private/framework.bzl#L284) is broken. @keith is working on a fix, but for the time being we can revert to unblock consumers e.g., Envoy Mobile.

Signed-off-by: Jose Nino <jnino@lyft.com>

### CODE REVIEW

**Review by keith — APPROVED** [review]

**Comment by junr03** [comment]
discussed with @keith. He is going to work on a fix on rules_foreign_cc upstream to allow us to actually update.

**Review by snowp — APPROVED** [review]

**Comment by junr03** [comment]
thanks @snowp!

**Comment by junr03** [comment]
For posterity: https://github.com/bazelbuild/rules_foreign_cc/pull/767/

**Review by snowp — APPROVED** [review]

**Pull request merged**
