### PR TITLE
http: fixing a content length bug in the grpc_http1_reverse_bridge fi…

### LINKED ISSUE #11099: http2_protocol_options.stream_error_on_invalid_http_messaging with reverse bridge
Hi,

I'm configuring envoy (v1.12.2) as level two proxy (sidecar) within reverse bridge filter enabled only, and using an ingress controller envoy based as level one proxy.

I've read [this article](https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/level_two) and I checked using http2_protocol_options.stream_error_on_invalid_http_messaging=true, but I continue getting this error (only for grpc errors; for grpc succesful responses works correctly):
```
{
  "error": "14 UNAVAILABLE: upstream connect error or disconnect/reset before headers. reset reason: connection termination"
}
```

If I do the calls directly to the service (which contains the sidecar), both cases (grpc errors and grpc successful responses) work correctly, and there is no connection termination.

Is it possible that this config does not apply to the reverse bridge?
Would there be any workaround?

This is the filter config (the upstream doesn't understand grpc semantics):
```
- name: envoy.filters.http.grpc_http1_reverse_bridge
   config:
     content_type: application/grpc+proto
     withhold_grpc_frames: true
```

This is the http connection manager config:
```
 - name: envoy.http_connection_manager
    config:
      http2_protocol_options:
        stream_error_on_invalid_http_messaging: true
```

Thank you in advance.

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: Low (minor bugfix)
Testing: new unit test
Docs Changes: n/a
Release Notes: added
Runtime guard: not guarded: prior served HTTP was invalid.
Fixes #11099

### CODE REVIEW

**Comment by alyssawilk** [comment]
The one thing I don't like about this is if you send a header-only reply vs a header with a 0 byte data frame, you get a different response.
Should we special case encodeData to not wrap the body if the buffer is empty?

cc @zuercher @lizan

**Comment by snowp** [comment]
If we handled zero length bodies like that I think we'd need some additional logic (e.g. grpc-status != 0) as to not break legit responses trying to respond with the default proto message (serialized to empty string). I think just gating this on `end_stream` is fine, but others might disagree

**Comment by alyssawilk** [comment]
Hm, if that's the case is it safe to leave header only replies as-is?
Basically if grpc status is 0 for a header-only reply should we add a body so we can encapsulate the theoretical zero length proto?

**Comment by snowp** [comment]
I think gRPC tends to ignore the body of error responses (which all header-only responses are afaik?) so I don't think we need to do anything to the body in those cases. That said I always felt that this part of gRPC felt under-documented so I might not be right here

**Comment by alyssawilk** [comment]
@lizan or @PiotrSikora any thoughts on correctness or should we just land this as less buggy?

**Pull request merged**
