### PR TITLE
build: fix mac build on xcode 12

### PR DESCRIPTION
**Pull request by ramaraochavali**
Commit Message: fix mac build on xcode 12
Additional Description:
Build with Xcode 12 on Mac fails with the following error as abseil while constructing map uses non reference range loop.
```

source/extensions/filters/network/postgres_proxy/postgres_decoder.cc:502:19: error: loop variable 'sp' of type 'const absl::string_view' creates a copy from type 'const absl::string_view' [-Werror,-Wrange-loop-analysis]
  for (const auto sp : splitter) {
                  ^
source/extensions/filters/network/postgres_proxy/postgres_decoder.cc:502:8: note: use reference type 'const absl::string_view &' to prevent copying
  for (const auto sp : splitter) {
       ^~~~~~~~~~~~~~~
```
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by PiotrSikora** [comment]
FWIW, I believe this is a false-positive (see: https://reviews.llvm.org/D73007), so adding `-Wno-range-loop-analysis` on macOS might be better than this expensive fix.

**Comment by codefromthecrypt** [comment]
see also https://github.com/envoyproxy/envoy/pull/13184 as this happened before it seems

**Comment by codefromthecrypt** [comment]
https://github.com/Homebrew/homebrew-core/pull/81490 will try to work around this until merged as currently homebrew is busted

**Comment by htuch** [comment]
@ramaraochavali what is the status of this? Should we close or revise as per comments?

**Comment by ramaraochavali** [comment]
I am fine with the workaround of removing `-Wrange-loop-analysis` for mac.  Is this the right place to disable https://github.com/envoyproxy/envoy/blob/a12869fa9e9add4301a700978d5489e6a0cc0526/bazel/envoy_internal.bzl#L69 ? 

Is that fine with every one @rebello95 ?

**Comment by codefromthecrypt** [comment]
project team: (for lack of knowing how escalations work @mattklein123 )

I don't know how severity works here, but this should be a dev 1. only thing worse would be all platforms unable to build (dev 0). That os/x doesn't build due to this means no one can upgrade homebrew to envoy 1.19. To understand the full context is basically knowing that many projects rely on github actions, who have finally stopped installing ancient xcode.

Note: this is also hurting the homebrew project as it is causing broken builds on the existing versions. In other words envoy's config is causing stalls on unrelated forumulas such as go. Can someone with deep knowledge on the build please pitch in and resolve this!

**Comment by mattklein123** [comment]
@ramaraochavali yes let's just disable range-loop-analysis on macOS. cc @keith or @lizan for help on how to do that or just ask them in the #bazel slack room. Thank you!

/wait

**Comment by keith** [comment]
https://github.com/envoyproxy/envoy/pull/17428

**Comment by mattklein123** [comment]
Thanks Keith! Closing this one.

**Comment by ramaraochavali** [comment]
makes sense. Will look forward for the other PR getting merged :-)

**Pull request closed without merging**
