### PR TITLE
Improve the example for the Kafka Broker filter

### PR DESCRIPTION
**Pull request by adamkotwasinski**
Commit Message: Improve the example for the Kafka Broker filter
Additional Description: Makes the client traffic actually go through Envoy
Risk Level: Low
Testing: README.md guideline
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by adamkotwasinski** [comment]
@nguyenptk @phlax Sorry it took so long (back from holidays). There was a small mis-config in Confluent Docker image that made the traffic reach the "internal" Kafka server socket, making the connections work (surprising) but all the traffic actually went `client <-> Kafka`, instead of `client <-> Envoy <-> Kafka`. This PR should fix that and we finally got the metrics (like the `create_topics` one).

**Comment by adamkotwasinski** [comment]
(just realized there's a verify check I need to amend a little)

**Review by phlax — APPROVED** [review]
lgtm, thanks @adamkotwasinski for cleaning this up

**Pull request merged**
