### PR TITLE
Fix: doc typo

### PR DESCRIPTION
**Pull request by hbrls**
doc typo

### CODE REVIEW

**Review by phlax — APPROVED** [review]
lgtm. Thanks @hbrls

**Comment by phlax** [comment]
@hlbris you  will need to fix DCO - see here for more information 

https://github.com/envoyproxy/envoy/blob/master/CONTRIBUTING.md#dco-sign-your-work

**Comment by hbrls** [comment]
I have followed the instructions and seen a `Signed-off-by` by the end of commit message. Please check if it's correct.

**Comment by phlax** [comment]
all seems good now - thanks @hbrls

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
