### PR TITLE
deps: Bump `proxy_wasm_cpp_host` -> 5d76116 (+ related deps)

### LINKED ISSUE #27748: Newer release available `com_github_wasmtime`: v9.0.3 (current: v6.0.1)
Package Name: com_github_wasmtime@6.0.1
Current Version: v6.0.1@2023-03-08
Available Version: v9.0.3@2023-05-31
Upstream releases: https://github.com/bytecodealliance/wasmtime/releases

### PR DESCRIPTION
**Pull request by phlax**
Also bump 

- `com_github_wamr` -> 1.2.2
- `com_github_wasmtime` -> 9.0.3

Fix #27748

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
requires https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/355

**Comment by phlax** [comment]
cc @PiotrSikora thanks for help - seems to work once everything is updated

cc @RyanTheOptimist i think this one is high priority as i would like to backport it to pending releases

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by kyessenov** [comment]
Are you going to backport proxy-wasm-cpp-host?

**Comment by phlax** [comment]
> Are you going to backport proxy-wasm-cpp-host?

yeah its there already on the bp stacks - im just adding some final stuff to them

**Comment by phlax** [comment]
https://github.com/envoyproxy/envoy/pulls?q=is%3Apr+is%3Aopen+bp

**Pull request merged**
