### PR TITLE
kafka: upgrade to 3.8, add support for more requests

### PR DESCRIPTION
**Pull request by adamkotwasinski**
Commit Message: kafka: upgrade to 3.8, add support for more requests
Additional Description: upgrade kafka dependency to 3.8, add necessary parsing code and deserializer to process new stuff present in 3.8 (nullable struct)
Risk Level: low
Testing: automated suite + manual with [envoy-kafka-tests](https://github.com/adamkotwasinski/envoy-kafka-tests/pull/13)
Docs Changes: readme updates due to version bump
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by adamkotwasinski** [comment]
good for review
/assign @mattklein123

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
