### PR TITLE
tls: split ServerContextConfigImpl into it's own compilation unit

### PR DESCRIPTION
**Pull request by ggreenway**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by ggreenway** [comment]
Ideally I'd like to put the ClientContextConfigImpl into it's own file as well, but I'm short on time.

**Comment by alyssawilk** [comment]
/wait CI failure looks real - if you cd mobile and build //test/common/... you should be able to repro
bonus points for adding the file to mobile/test/performance/files_em_does_not_use which is the real test for "are we not compiling this for E-M"

**Review by alyssawilk — APPROVED** [review]
Not sure if the gcc failure is real - LGTM modulo CI being happy and thanks for the clean up!

**Pull request merged**
