### PR TITLE
release: removing dev tag from 1.7.0

### PR DESCRIPTION
**Pull request by alyssawilk**
Also removing "pending" from 
DEPRECATED.md
and
docs/root/intro/version_history.rst

*Risk Level*:  n/a
*Testing*: Will wait for LGTM from whoever canaries at Lyft
*Docs Changes*: n/a
*Release Notes*: cut.

Signed-off-by: Alyssa Wilk <alyssar@chromium.org>

### CODE REVIEW

**Comment by mattklein123** [comment]
@alyssawilk I think our instructions are missing a step since we started putting "pending" on the release note version as well as I believe in deprecated.md. Do you mind removing the "pending" text as part of this change and also updating the release instructions? (When updating version to 1.8.0-dev we also need to add the new section with pending back).

**Comment by alyssawilk** [comment]
Current instructions have us removing the pending and adding a release date for the final step, after it's cut.  I'm happy to do it here and update the instructions.

**Comment by mattklein123** [comment]
I think that's a little out of date/confusing, mainly because DEPRECATED.md is just in the repo, where as the docs get locked as part of the release, so we need to do it before which is new.

**Comment by alyssawilk** [comment]
makes sense - I'd been confused about where to do it as it was later in the instructions than I expected.
Updates to GOVERNANCE.md will be in a separate PR since there's a few and they're unrelated.

**Comment by alyssawilk** [comment]
Yep, I'll send out https://github.com/alyssawilk/envoy/tree/release_instructions once I finish the release, in case I think of more hopefully-helpful additions, like maybe cut-and-paste instructions for deprecate_versions.py onve I've actually run it.

**Pull request merged**
