### PR TITLE
kafka: fetch request

### PR DESCRIPTION
**Pull request by adamkotwasinski**
Commit Message: kafka: add Fetch request handling
Additional Description: Fetch request represents a single request coming from downstream clients "_please give me records for partitions p1, p2, ... pN_". In our implementation this will mean we will ask SharedConsumerManager to [process](https://github.com/adamkotwasinski/envoy/blob/59cfbef8571472ed7f37b741b59304e687dca3fc/contrib/kafka/filters/network/source/mesh/shared_consumer_manager_impl.cc#L55) our request (== fill it with records, if any stored; register as callback if nothing). When our processing is finished (which can happen in one of two ways: record times out (no records!) / stuff got provided (either [initial seeding](https://github.com/adamkotwasinski/envoy/blob/59cfbef8571472ed7f37b741b59304e687dca3fc/contrib/kafka/filters/network/source/mesh/shared_consumer_manager_impl.cc#L198) or by SCM's [consumer workers](https://github.com/adamkotwasinski/envoy/blob/59cfbef8571472ed7f37b741b59304e687dca3fc/contrib/kafka/filters/network/source/mesh/shared_consumer_manager_impl.cc#L156)), we finally let the filter/dispatcher know we are ready to go downstream. Part of https://github.com/envoyproxy/envoy/issues/24372.
Risk Level: Low
Testing: unit tests, integration tests with full stack
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by adamkotwasinski** [comment]
draft: I left some debugs in and need to write some UTs

**Comment by adamkotwasinski** [comment]
On holidays until mid-Jan, so don't get angry with me, repokitteh ;)

**Review by mattklein123 — APPROVED** [review]

**Comment by adamkotwasinski** [comment]
Thank you!

**Pull request merged**
