### PR TITLE
build: enable logging by default

### PR DESCRIPTION
**Pull request by adisuissa**
Commit Message: build: enable logging by default
Additional Description:
PR #24174 introduced the `--define=enable_logging=disabled` build option to disable logging at build time.
To this end, #24174 introduced the `ENVOY_ENABLE_LOGGING` macro that is added into the build process.
To make this feature more-backwards compatible with build platforms that use other default flags and bazel files, this PR changes the macro to `ENVOY_DISABLE_LOGGING` that is explicitly added if `--define=enable_logging=disabled` is set.
Also updated Envoy-Mobile default flags to explicitly disable logging.

Risk Level: low, should maintain backward compatibility 
Testing: N/A.
Docs Changes: N/A.
Release Notes: N/A.
Platform Specific Features: N/A.

Signed-off-by: Adi Suissa-Peleg <adip@google.com>

### CODE REVIEW

**Comment by adisuissa** [comment]
Strange... The errors in Envoy-mobile (e.g., https://github.com/envoyproxy/envoy/actions/runs/3578127713/jobs/6017922820#step:4:331) seem to be due to missing log notifications.
Could it be that PR #24174 did not disable logs for Envoy-Mobile?

**Comment by jpsim** [comment]
Yes please keep logs enabled for Envoy Mobile. They are an actively used feature. Sorry for the confusion.

**Comment by adisuissa** [comment]
> Yes please keep logs enabled for Envoy Mobile. They are an actively used feature. Sorry for the confusion.

Thanks for clarifying! Re-enabled logging by default.

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
