### PR TITLE
wasm/extensions: Wasm extension policy.

### PR DESCRIPTION
**Pull request by htuch**
Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

**Comment by htuch** [comment]
CC @envoyproxy/maintainers @envoyproxy/wasm-dev

**Review by ggreenway — APPROVED** [review]

**Review by PiotrSikora — APPROVED** [review]

**Review by lizan — APPROVED** [review]

**Comment by kyessenov** [comment]
SG, what about foreign functions and custom Wasm contexts? Where should those live to be shared?

**Comment by mattklein123** [comment]
> SG, what about foreign functions and custom Wasm contexts? Where should those live to be shared?

What do you mean by this exactly?

**Review by mattklein123 — APPROVED** [review]

**Comment by kyessenov** [comment]
Wasm can be extended in downstream envoy forks. I think the modules for those downstream envoys may not run on upstream envoy. This is done via https://github.com/envoyproxy/envoy/blob/319a9a647f19036d831a75f68350c90e98bfc365/source/extensions/common/wasm/foreign.cc and https://github.com/istio/proxy/blob/master/src/envoy/extensions/wasm/context.h#L23

**Comment by htuch** [comment]
@kyessenov I think we can do these extensions in the main Envoy repo, but they should be self-contained and have few external dependencies. Also, ideally we are aiming for as many of these to be part of the ABI directionally, but there will always be proxy specific bits.

**Comment by kyessenov** [comment]
@mattklein123 The problem is the portability of extensions. FFI and custom contexts effectively extend ABI in ways that can make extensions for downstream proxies not be compatible with Envoy.

**Comment by mattklein123** [comment]
I think that is the problem of downstream forks, not us. Anything that is in the "real" ABI must be upstream.

**Pull request merged**
