### PR TITLE
Fixing a CEP filter test failure due to using private mutable_type_url() methods of any.proto

### PR DESCRIPTION
**Pull request by yanjunxiang-google**
mutable_type_url() methods of any.proto is a private method in some systems.
Using mutable_type_url()->assign() in those systems cause build failure. Replacing it with set_type_url() which is a public method.

Signed-off-by: Yanjun Xiang <yanjunxiang@google.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by yanavlasov — DISMISSED** [review]

**Comment by yanavlasov** [comment]
@yanjunxiang-google please fix format error.

**Comment by yanjunxiang-google** [comment]
> 

Done

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
