### PR TITLE
rbac: add DNS SAN as principal

### LINKED ISSUE #7836: RBAC Authenticated Principal
Is there any specific reason why RBAC authenticated principle looking URI SAN and if it is not available looking at Subject? Would it be OK to check URI SAN or **DNS SAN** of Subject in that order? It would be useful for people who does not have URI SAN in the certs. 

Relevant links :
Docs :
 https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/rbac/v2/rbac.proto#config-rbac-v2-principal-authenticated

Code:

https://github.com/envoyproxy/envoy/blob/3e63182c3e74e0d517d2f0d1fc2ee950bbfe21e1/source/extensions/filters/common/rbac/matchers.cc#L145

### PR DESCRIPTION
**Pull request by ramaraochavali**
Description: Adds support for DNS SAN as Principal in RBAC filter.
Risk Level: Low
Testing: Added automated tests
Docs Changes: Updated
Release Notes: Added
Fixes #7836

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@lizan @mattklein123 PTAL

**Comment by ramaraochavali** [comment]
@lizan can you PTAL when you get chance?

**Comment by lizan** [comment]
Can you merge master?

**Comment by ramaraochavali** [comment]
@lizan merged master. PTAL

**Comment by lizan** [comment]
@htuch turns out this PR needs your approval

**Pull request merged**
