### PR TITLE
Add googleurl as external dependency

### PR DESCRIPTION
**Pull request by danzh2010**
Add googleurl as external dependency.

Risk Level: low, not in use.
Part of #6588

### CODE REVIEW

**Comment by danzh2010** [comment]
> Are you planning on replacing the use of https://github.com/envoyproxy/envoy/tree/master/source/common/chromium_url with this?
> 
> We should do that for #6588.

I'm just addressing the request in that issue. And Envoy/Quic also needs it to build a quic toy client in Envoy. I'm not sure if I'm the right person to replace all the usage of chromium_url with this external dep and I'm afraid I don't have the cycle to do this in near future (~2month).

**Comment by htuch** [comment]
@danzh2010 fair enough, but can you leave the issue open? I.e. edit the commit message to remove "fixes". I think the issue really is covering the full replacement. Happy to take some progress towards that.

**Comment by danzh2010** [comment]
> @danzh2010 fair enough, but can you leave the issue open? I.e. edit the commit message to remove "fixes". I think the issue really is covering the full replacement. Happy to take some progress towards that.

done

**Comment by danzh2010** [comment]
I have to push some fix to this PR. PTAL again. 

As to release policy, this is directory is a  partial copy of https://cs.chromium.org/chromium/src/url/ and https://cs.chromium.org/chromium/src/base/. Chromium has its own versioned release. Right now this directory is an arbitrary snap of that. But in the future, we can definitely use the same cut as Chrome use, like M80. Their security bugs can be tracked at https://bugs.chromium.org/p/chromium/issues/list?q=Type%3DBug-Security, but not all of them are relevant to url parsing. A tracked change between versions can be found here: https://chromium.googlesource.com/chromium/src/+log/82.0.4085.12..83.0.4093.3?pretty=fuller&n=10000

I just push all the info here. But we should definitely develop a plan about how to update and monitor this repo. As QUICHE is not the only user of this repo (we only use it for toy client), I think other users will be more alert and watchful to any security bugs than us. I would be happy to discuss and work out a plan for that.

**Comment by htuch** [comment]
@danzh2010 ack, thanks for the explanation. I've left a comment in #6588 for later followup.

**Comment by dio** [comment]
@htuch @danzh2010 to make it usable do we need ICU support for this? Seems like e.g. `url/url_idna_icu.cc` requires `unicode/uidna.h`.

**Comment by danzh2010** [comment]
> @htuch @danzh2010 to make it usable do we need ICU support for this? Seems like e.g. `url/url_idna_icu.cc` requires [`unicode/uidna.h`](https://raw.githubusercontent.com/unicode-org/icu/master/icu4c/source/common/unicode/uidna.h).

Yes

**Pull request merged**
