### PR TITLE
[WIP] proxy protocol: skip TLS connections

### PR DESCRIPTION
**Pull request by rgs1**
This is useful when turning on proxy protocol on an NLB that's already
in production, since it's hard (or impossible) to turn this feature
on atomically in those cases which is necessary to avoid rejections
of connections that aren't using proxy protocol (yet).

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

### CODE REVIEW

**Comment by rgs1** [comment]
I'll add more tests and put a config/runtime guard around this feature, if we agree that it's a good idea and generally useful.

Tagging people who've worked on this filter before:

@fishcakez @donbowman @songhu @wez470 @florincoras @rulex123

**Comment by mattklein123** [comment]
I'm a little confused: How does non-TLS help? Don't you have non-TLS traffic that would also have the same problem? 

Could you potentially use DNS and multiple NLBs to control the rollout?

**Comment by rgs1** [comment]
> I'm a little confused: How does non-TLS help? Don't you have non-TLS traffic that would also have the same problem?
> 
> Could you potentially use DNS and multiple NLBs to control the rollout?

Commented offline, in our case we force https redirect o non TLS so we don't need proxy proto there. So only TLS in our case.

This is nice because it means not dealing with multiple NLBs and shifting traffic around, since with this Envoy can just tolerate proxy protocol being off in the NLB without problem which helps us in the rollout of proxy proto for existing NLBs.

**Comment by rgs1** [comment]
Chatted a bit more with Matt offline, in its current form this patch is not ready for general consumption (though it might be educational for others doing something similar). Closing for now, but we can reopen in the future and explore a way to make it more general.

**Pull request closed without merging**
