### PR TITLE
tcp_proxy: remove support for v1 routes

### PR DESCRIPTION
**Pull request by venilnoronha**
*Description*: This PR removes the previously deprecated v1 routes support in the TCP Proxy implementation. See #4622, #4487 and #4430 for more information.
*Risk Level*: Med
*Testing*: Existing tests suffice
*Docs Changes*: Added feature removal notice to `version_history.rst`
*Release Notes*: NA

Signed-off-by: Venil Noronha <veniln@vmware.com>

/cc @ggreenway @rshriram

### CODE REVIEW

**Comment by ggreenway** [comment]
Unfortunately, (and I feel bad saying this after all the back and forth about when we can do this), I'm not sure we can delete this yet, because in FilterChainMatch (the new way of doing this), we still have:

```
  // [#not-implemented-hide:]
  repeated core.CidrRange source_prefix_ranges = 6;
```

So if we delete this, there's no way to configure routing based on source address (to the best of my understanding).

@rshriram Does this seem correct? Or am I missing something?

**Comment by mattklein123** [comment]
> So if we delete this, there's no way to configure routing based on source address (to the best of my understanding).

FYI this was recently asked about: https://github.com/envoyproxy/envoy/issues/4535#issuecomment-427684316. Perhaps we can just get it implemented?

**Comment by venilnoronha** [comment]
not stale.

**Comment by PiotrSikora** [comment]
IMHO, we need at least one release that supports both: the new-style filter chain matching based on source ports/IPs (#4457) and old-style v1 tcp proxy, which this PR removes.

**Comment by rshriram** [comment]
sorry I missed this. Yes, we will miss source matching. But I don't think anyone is using it are they? docs are hiding source match. Istio isn't using it either for sure.
We have been saying that v1 is going to be deprecated and I view this as part of v1 removal.

**Comment by rshriram** [comment]
I mean v1 api is going away.. and this is part of that process

**Comment by venilnoronha** [comment]
not stale.

**Comment by venilnoronha** [comment]
This PR is synced with `master` now.

**Comment by mattklein123** [comment]
@ggreenway @PiotrSikora  I haven't been following the history here. Can we merge this now?

**Comment by ggreenway** [comment]
I quick check shows no change in the blockers for this: `source_prefix_ranges` is still not implemented.

**Comment by mattklein123** [comment]
OK then I will close this now since it's not going to get merged any time soon.

**Pull request closed without merging**
