### PR TITLE
docs: clarify the workflow to ensure the changes are effective 

### PR DESCRIPTION
**Pull request by tyxia**
Signed-off-by: Tianyu Xia [tyxia@google.com](mailto:tyxia@google.com)

### CODE REVIEW

**Comment by phlax** [comment]
copying out the ci advice...

```console
##[error]: TESTS FAILED:
##[error]:  main@ /source/ci/format_pre.sh :47 (glint)
##[error]:      Please fix your editor to ensure:
##[error]:        - no trailing whitespace
##[error]:        - no mixed tabs/spaces
##[error]:        - all files end with a newline
##[error]Bash exited with code '1'.

```

the easiest thing is to fix your editor to ensure these things on save for relevant files

**Review by rojkov — APPROVED** [review]
Thank you! That's a useful clarification.

**Pull request merged**
