### PR TITLE
tooling: Shift `api_proto_breaking_change_detector` to bazel

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: tooling: Shift `api_proto_breaking_change_detector` to bazel
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @htuch @adisuissa

**Review by adisuissa — APPROVED** [review]
Code changes LGTM.
Thanks for cleaning this.

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
