### PR TITLE
fix: typo in STYLE.md from handing to handling

### LINKED ISSUE #17785: STYLE.md has a typo for error handing, should be error handling
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *STYLE.md has a typo for error handing, should be error handling*

*Description*:
Exceptions are allowed and encouraged where appropriate. When using exceptions, do not add additional error *handing* that cannot possibly happen in the case an exception is thrown.
[optional *Relevant Links*:]

https://github.com/envoyproxy/envoy/blob/main/STYLE.md#deviations-from-google-c-style-guidelines

### PR DESCRIPTION
**Pull request by goodgeorge**
Fixes #17785

### CODE REVIEW

**Review by rojkov — APPROVED** [review]
Thank you for fixing it!

**Comment by rojkov** [comment]
@goodgeorge Could you please edit the description to contain "Fixes #17785"? So, merging this PR would close the issue automatically.

**Comment by mattklein123** [comment]
@rojkov @goodgeorge I will just go ahead and modify the description, thank you.

**Comment by goodgeorge** [comment]
Thank you very much @mattklein123 @rojkov , Will add specific description next time if I have. Thanks for help. Marking this contribution as my first open source milestone, Haha

**Pull request merged**
