### PR TITLE
ci/fuzz: Update to use `--extensions_fuzzed_count` flag for check

### LINKED ISSUE #27575: Make `code.check:extensions_fuzzed` configurable
Currently the `envoy.code.check` update is broken pending #27373 landing

that can probably land - so this issue is more about the code.check configurability

when i created the toolshed repo, i shifted everything, and then tried to make anything liable to change configurable in envoy - at least that has been the gradual intention

in this case the check is a bit kludgy in how it resolves the filters, now that it has been moved to bazel i think we should probably being using a bazel query to pass the filters to the tool

### PR DESCRIPTION
**Pull request by phlax**
Fix #27575 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @vehre-x41

**Comment by vehre-x41** [comment]
Looks reasonable to me, but note, that I don't have approval rights here!

**Comment by phlax** [comment]
> Looks reasonable to me, but note, that I don't have approval rights here!

or assignable - we should add you to the team i think!

**Comment by vehre-x41** [comment]
> > Looks reasonable to me, but note, that I don't have approval rights here!
> 
> or assignable - we should add you to the team i think!

Well, probably not. The engagement of my company is in the final steps and I have to devote my time to different projects in no time unfortunately. Sorry.

**Comment by phlax** [comment]
This didnt quite work - how i have set the code check test up is not ideal and this is buried in invisible logs:

```console
CodeChecker NOTICE Cannot run disabled check (extensions_fuzzed): `--extensions_fuzzed_count` not provided, disabling extensions fuzz checks                                      
```

ill pr a fix and try and think how to improve the check test

**Pull request merged**
