### PR TITLE
upstream: avoid copies of all cluster endpoints for every resolve target

### LINKED ISSUE #12138: CDS Updates with many clusters often fail
https://github.com/envoyproxy/envoy/blob/2966597391b9c7743dab1186f214229ca95e0243/source/common/upstream/cds_api_impl.cc#L52-L101

This is a performance issue, not a bug per se.

When doing CDS updates with many clusters, Envoy will often get "stuck" evaluating the CDS update. This manifests as EDS failing, and in more extreme cases, the envoy ceases to receive any XDS updates. When this happens, Envoy needs to be restarted to get it updating again.

In our case we're seeing issues with the current implementation of `void CdsApiImpl::onConfigUpdate` with a number of clusters in the 3000-7000 range. If envoy could speedily evaluate a CDS update with 10000 clusters  this would represent a HUGE improvement in Envoy's behavior for us. Right now, only around 2500 clusters in a CDS update seems to evaluate in reasonable amount of time.

Because the function `void CdsApiImpl::onConfigUpdate` pauses EDS while doing CDS evaluation, envoy's config will drift. With many clusters in CDS, this can mean envoy is **hundreds** of seconds behind what is current, and results in 503's.

Some context: 

- Envoy in my test environment is being run without constraints on 8 core VMs that are running at a max of 30% CPU utilization and max 40% memory (of 32 GB): 
```
        resources:
          limits:
            memory: "32212254720"
          requests:
            cpu: 100m
            memory: 256M
```
- We're using Project Contour as our Ingress Controller in K8s.
    - https://projectcontour.io/
    - https://github.com/projectcontour/contour

Contour currently doesn't use the incremental APIs of Envoy, so when K8s services change in the cluster it sends ALL of the current config again to Envoy, which means a small change like adding or removing a K8s SVC which maps to an envoy cluster results in Envoy having to re-evaluate ALL clusters.

With enough K8s Services behind an Ingress (7000+) envoy can spontaneously cease to receive any new updates indefinitely, and will fail to do EDS because it gets stuck in the CDS evaluation.

Given a high enough number of clusters this would be a Very Hard Problem, but given that we're in the low thousands, I'm hoping there are some things that could be done to improve performance without resorting to exotic methods.

**Please let me know if there's any information I can provide that could help!**

### PR DESCRIPTION
**Pull request by rojkov**
Commit Message: upstream: avoid copies of all cluster endpoints for every resolve target
Additional Description:
Currently `Envoy::Upstream::StrictDnsClusterImpl::ResolveTarget` when instantiated for every endpoint also creates a full copy of `envoy::config::endpoint::v3::LocalityLbEndpoints` the endpoint belongs to. Given the message contains all the endpoints defined for it this leads to exponential growth of consumed memory as the number of endpoints increases. Even though those copies of endpoints are not used.

Instead of creating a copy of `envoy::config::endpoint::v3::LocalityLbEndpoints` use a reference to a single copy stored in `Envoy::Upstream::StrictDnsClusterImpl` and accessible from all resolve targets during their life span.

Risk Level: Low
Testing: unit tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
May contribute to #12138, #14993

### CODE REVIEW

**Comment by htuch** [comment]
@rojkov do you have before/after performance figures or flame graphs? :D I can believe this had a major impact, curious what it was .

**Comment by dmitri-d** [comment]
Couldn't `load_assignment` (here: https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/strict_dns_cluster.cc#L27) be made into a member var, and then `locality_lb_endpoint` can be stored as a reference in `ResolveTarget`.

**Comment by rojkov** [comment]
> Couldn't `load_assignment` be made into a member var, and then `locality_lb_endpoint` can be stored as a reference in `ResolveTarget`.

Yes, that's possible with all the tests passing. Here's [the v2 patch](https://github.com/rojkov/envoy/commit/d0135d8738deaeebaa4e0d69227aae0ccf099d69).

I've measured how quickly `ResolveTarget`s are created for 9002 endpoints with perf annotations (and with `-c opt`):

the current master
```
Duration(us)  # Calls  Mean(ns)  StdDev(ns)  Min(ns)  Max(ns)  Category   Description
    13166317     9002   1462599     77592.5  1325699  2418618  done       create ResolveTarget
```
v1 with WeightedLocality (I did 4 runs)
```
Duration(us)  # Calls  Mean(ns)  StdDev(ns)  Min(ns)  Max(ns)  Category   Description
        6956     9002       772     1356.23      266    18082  done      create ResolveTarget
        6250     9002       694     1257.25      287    26519  done      create ResolveTarget
        6519     9002       724     1339.45      303    30662  done      create ResolveTarget
        5937     9002       659     1222.48      263    20861  done      create ResolveTarget
```
[v2](https://github.com/rojkov/envoy/commit/d0135d8738deaeebaa4e0d69227aae0ccf099d69) with `locality_lb_endpoints` kept around
```
Duration(us)  # Calls  Mean(ns)  StdDev(ns)  Min(ns)  Max(ns)  Category   Description
        7793     9002       865     1360.81      293    18177  done      create ResolveTarget
        5732     9002       636     1208.12      260    24967  done      create ResolveTarget
        6340     9002       704     1156.34      325    21298  done      create ResolveTarget
        7507     9002       833     1349.85      309    21394  done      create ResolveTarget
```

The v2 patch seems to be as fast as v1, but it makes `StrictDnsClusterImpl` keep endpoints data in memory longer than needed (only locality, priority and weight is used after `StrictDnsClusterImpl`'s ctor is done).

Though in both cases memory consumption is negligible (pprof doesn't show anything whose cumulative allocations <268k; I couldn't find how to make it show) comparing to the current code. For 9002 endpoints it consumes >20G and can probably explain #14993.

Screenshot (11)

**Comment by htuch** [comment]
Yeah, much prefer the v2 patch. Good call @dmitri-d. I am still somewhat convinced that using protos in various places where we don't need is going to bite us, but not this time.

**Comment by rojkov** [comment]
Switched to v2 and updated the description accordingly.

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
