### PR TITLE
kafka: provide Fetch support, giving mesh-filter stateful consumer proxy

### PR DESCRIPTION
**Pull request by adamkotwasinski**
Commit Message: kafka: provide Fetch support, giving mesh-filter stateful consumer proxy
Additional Description: final part of https://github.com/envoyproxy/envoy/issues/24372 to provide the Fetch support, SCM gets created per listener and provides a stateful proxy
Risk Level: Low
Testing: automated + manual ([link](https://github.com/adamkotwasinski/envoy-kafka-tests/pull/8))
Docs Changes: mesh-filter docs
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by adamkotwasinski** [comment]
left to do:
* docs
* tests
* Javadoc

**Review by mattklein123 — APPROVED** [review]

**Comment by adamkotwasinski** [comment]
Thank you!

**Pull request merged**
