### PR TITLE
DFP: move CM callbacks to thread local objects

### LINKED ISSUE #32427: Envoy occasionally segfaults from v1.27 in ProxyFilterConfig::onClusterAddOrUpdate
**Title**: Envoy occasionally segfaults from v1.27 in ProxyFilterConfig::onClusterAddOrUpdate

**Description**:
  Since we upgraded envoy version to v1.27.2, we see Envoy crashes a few times a day inside ProxyFilterConfig::onClusterAddOrUpdate function in extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc.
  
  The function was added to v1.27, (added by [#26420](https://github.com/envoyproxy/envoy/pull/26420)), and we verified that it also happens with envoy v1.28.1. After we rolled Envoy to v1.26.6, we do not see the issue.

  We use envoy binaries from the [prebuilt docker images](https://www.envoyproxy.io/docs/envoy/latest/start/install#pre-built-envoy-docker-images). We use the `debug` variant  which contains debug symbols. (e.g. [debug-v1.27.2](https://hub.docker.com/layers/envoyproxy/envoy/debug-v1.27.2/images/sha256-880a6ca106553d5ed1ca4a0f2459fb9fed591367526ff896aca7737e795c8372?context=explore)]

 We use envoy proxy as an edge proxy, and we are running multiple envoy proxies running that fetch configuration using ADS from the same management server written in go-control-plane(v0.11.1). Since a single envoy proxy crashes randomly, and the crash happens on a different envoy proxy each time, it appears that this happens when a certain race condition is met. 

 The segfault happens since `tls_slot_` has a null value. (see troubleshooting logs below). However, we are not sure when the value can be null. 

**Repro steps**:

 Unfortunately, we were not able to deterministically reproduce the issue. We have multiple services that use dynamic forwarding proxy to forward requests to upstream endpoints, and we frequently update the configurations. (updates can happen multiple times a minute)

**Call Stack**:

```
* thread #1, name = 'envoy-debug-1.2', stop reason = signal SIGSEGV
  * frame #0: 0x000056241c27a030 envoy-debug-1.27.2`Envoy::Extensions::HttpFilters::DynamicForwardProxy::ProxyFilterConfig::onClusterAddOrUpdate(Envoy::Upstream::ThreadLocalCluster&) at thread_local.h:48:29
    frame #1: 0x000056241d7cea51 envoy-debug-1.27.2`std::__1::__function::__func<Envoy::Upstream::ClusterManagerImpl::postThreadLocalClusterUpdate(Envoy::Upstream::ClusterManagerCluster&, Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterUpdateParams&&)::$_19, std::__1::allocator<Envoy::Upstream::ClusterManagerImpl::postThreadLocalClusterUpdate(Envoy::Upstream::ClusterManagerCluster&, Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterUpdateParams&&)::$_19>, void (Envoy::OptRef<Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl>)>::operator()(Envoy::OptRef<Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl>&&) at cluster_manager_impl.cc:1152:24
    frame #2: 0x000056241d7cac08 envoy-debug-1.27.2`decltype(static_cast<Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl>(fp)(static_cast<Envoy::ThreadLocal::TypedSlot<Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl>::makeSlotUpdateCb(std::__1::function<void (Envoy::OptRef<Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl>)>)::'lambda'(std::__1::shared_ptr<Envoy::ThreadLocal::ThreadLocalObject>)&>(fp0)...)) std::__1::__invoke<Envoy::ThreadLocal::TypedSlot<Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl>::makeSlotUpdateCb(std::__1::function<void (Envoy::OptRef<Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl>)>)::'lambda'(std::__1::shared_ptr<Envoy::ThreadLocal::ThreadLocalObject>)&, std::__1::shared_ptr<Envoy::ThreadLocal::ThreadLocalObject> >(Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl&&, Envoy::ThreadLocal::TypedSlot<Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl>::makeSlotUpdateCb(std::__1::function<void (Envoy::OptRef<Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl>)>)::'lambda'(std::__1::shared_ptr<Envoy::ThreadLocal::ThreadLocalObject>)&...) at function.h:507:16
    frame #3: 0x000056241d762c94 envoy-debug-1.27.2`std::__1::__function::__func<Envoy::ThreadLocal::InstanceImpl::SlotImpl::dataCallback(std::__1::function<void (std::__1::shared_ptr<Envoy::ThreadLocal::ThreadLocalObject>)> const&)::$_1, std::__1::allocator<Envoy::ThreadLocal::InstanceImpl::SlotImpl::dataCallback(std::__1::function<void (std::__1::shared_ptr<Envoy::ThreadLocal::ThreadLocalObject>)> const&)::$_1>, void ()>::operator()() at function.h:507:16
    frame #4: 0x000056241deb6ea7 envoy-debug-1.27.2`Envoy::Event::DispatcherImpl::runPostCallbacks() at any_invocable.h:859:1
    frame #5: 0x000056241e49c81a envoy-debug-1.27.2`event_process_active_single_queue + 666
    frame #6: 0x000056241e49b431 envoy-debug-1.27.2`event_base_loop + 1953
    frame #7: 0x000056241d7861fb envoy-debug-1.27.2`Envoy::Server::WorkerImpl::threadRoutine(Envoy::Server::GuardDog&, std::__1::function<void ()> const&) at worker_impl.cc:148:16
    frame #8: 0x000056241e4a3c53 envoy-debug-1.27.2`Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, std::__1::optional<Envoy::Thread::Options> const&)::'lambda'(void*)::__invoke(void*) at function.h:507:16
    frame #9: 0x00007fb5a2e0aea7 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #10: 0x00007fb5a2d2aa2f libc.so.6`__clone at clone.S:95
```
Below are outputs from lldb we obtained using the core dump file from a crash

disassembled output of frame #0
```
(lldb) disassemble
envoy-debug-1.27.2`Envoy::Extensions::HttpFilters::DynamicForwardProxy::ProxyFilterConfig::onClusterAddOrUpdate:
...
    0x55c2f69c4027 <+375>:  callq  0x1701130                 ; void spdlog::logger::log_<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(spdlog::source_loc, spdlog::level::level_enum, fmt::v9::basic_string_view<char>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
    0x55c2f69c402c <+380>:  movq   0x48(%r14), %rsi
->  0x55c2f69c4030 <+384>:  movq   (%rsi), %rax
```

we can see the value of `rsi` register is 0, which caused `movq` instruction to segfault
```
(lldb) register read $rsi
     rsi = 0x0000000000000000

```

`rsi` has the value at address `%r14 + 0x48`
```
(lldb) memory read --size 8 -fx -c 2 $r14+0x48
0x26d94193c3e0: 0x0000000000000000 0x0000000000001388
```

%r14 points to the `this` object, and %r14 + 0x48 points to `this->tls_slot` (the next value 0x1388(=5000) is the value of the next field "cluster_init_timeout_" )

### PR DESCRIPTION
**Pull request by cpakulski**
Commit Message:
DFP: move CM callbacks to thread local objects
Additional Description:
This is third attempt to fix #32427. (The previous are #32692 and #32798). 
The solution simply moves callbacks out of main object to thread local objects. Thread local objects do not hold any references to the main object, so both object types are independent and may have different lifespans.

This fixes the reported crash, but is not a generic solution.
I also played with combination of shared/weak pointers and modified signature of the function registering callbacks in CM. That also fixed the problem, but affected other modules (CM itself, aggregate cluster, redis proxy and udp proxy).
At this moment I believe that it is possible to build a generic mechanism which will take care of difference in lifespans of parent object and callbacks, but it will take me few weeks to build and test one and adjust other modules. I will open another PR when such framework is ready for review.

Risk Level: Low
Testing: Manual. Code which used to crash within 15 minutes runs without a crash.
Docs Changes: No
Release Notes: No
Platform Specific Features: No
Fixes #32427

### CODE REVIEW

**Review by alyssawilk — APPROVED** [review]
Oh!  Well that's a better workaround than either of us had thought of before.  Very very nice find!
Question, would it be possible to add a rapid config reload test which would flake before this change, or is that relatively implausible?
LGTM and throwing over to Matt for second pass either way

**Comment by cpakulski** [comment]
Thanks for reviewing @alyssawilk.

As for some sort of test, it is not trivial with the current code. The most problematic part is achieving certainty that code is robust when the test passes. I use 8 worker threads and reload config 100 times per second. Unit/integration tests use max 2 threads. Such test could run for many minutes and not crash. The proper way would be to orchestrate specific thread switching (for example pend on mutex, delete a resource on other thread and release mutex, etc). While my memory is fresh, I am willing to write a wrapper framework, which will take care of relationship between TLS object and parent object and invoke callbacks only when parent is valid. As part of that framework I can add some hooks (only in _DEBUG build), so test routines can orchestrate certain actions on each thread and delete parent object and then wake up worker thread.

**Comment by mattklein123** [comment]
> While my memory is fresh, I am willing to write a wrapper framework, which will take care of relationship between TLS object and parent object and invoke callbacks only when parent is valid. As part of that framework I can add some hooks (only in _DEBUG build), so test routines can orchestrate certain actions on each thread and delete parent object and then wake up worker thread.

Note that we have this: https://github.com/envoyproxy/envoy/blob/main/source/common/common/thread_synchronizer.h

Is there any way to use this to add a test or do you want to work on this as a follow up?

/wait-any

**Comment by cpakulski** [comment]
@mattklein123 Thanks for reviewing! I honestly think that writing a test for this particular case is not trivial. Additionally, there are 4-5 other filters which use similar pattern of registering callbacks in CM, so it would be nice to add tests for them as well. I think the the best way forward is to merge this PR as is. I know that this bug affects some users. I will backport it to the last 4 releases. I will open an issue to track development of generic framework (as I described above) and will use thread synchronizer (thanks for idea!) to test that framework. The scope of that generic framework is going to be fairly small and writing a test with a specific thread switching sequence should be much simpler.

**Pull request merged**
