### PR TITLE
examples: Fix healthcheck recipe

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @eitansuez

**Comment by eitansuez** [comment]
thanks for cc'ing me.  it helps me learn how this is all put together.  i sensed that the envoy admin port would need to be parameterized.

**Comment by phlax** [comment]
i need to check why but for some reason CI is not running on the necessary PRs - so wasnt possible to spot until it landed on `main`

ill hopefully add a fix for that to this PR tomorrow

**Comment by phlax** [comment]
triggered correctly this time https://github.com/envoyproxy/envoy/actions/runs/5969230566/job/16194697214

**Comment by phlax** [comment]
thinking further - `main`/PRs are broken now so ill push this through once its passing, and follow up

**Comment by phlax** [comment]
argg - it wont get tested again - the issue i mentioned

```console
env.outputs['changed.examplesOnly']: true
```

pushing through

**Pull request merged**
