### PR TITLE
WIP hcm: ensure that empty data frame is propagated during metadata decoding

### PR DESCRIPTION
**Pull request by snowp**
The HCM attempts to inject an empty DATA frame when processing METADATA
    frames within a header only request. These frames were never actually
    making it to the router filter, but was instead handled in
    UpstreamRequest. This fix this by making the encoding/decoding
    headers only a per filter property, which allows us to transform a
    filter chain that has been made header only back into a header + data
    when data has been injected for METADATA frames.

Risk Level: High
Testing:
Docs Changes:
Release Notes:

### CODE REVIEW

**Comment by snowp** [comment]
I ran into this when doing the router FM PR: the UpstreamRequest is currently doing the work to insert an empty DATA frame at the end of header only streams that inject METADATA frames.

This PR is incomplete but putting it up now in case I'm doing something completely nutty :) 

cc @mattklein123 @alyssawilk

**Comment by snowp** [comment]
Open question: which filters should see the injected data? All filters after the filter that injects this data? Including the filter that injects it?

**Comment by snowp** [comment]
So the current state here is that all tests now pass without doing the data frame insertion in UpstreamRequest, but I suspect that the encoding path is not properly tested (since I didn't run into any failing tests during my iteration) and we probably want more testing around adding trailers when this happens.

**Comment by alyssawilk** [comment]
I think with the other add things filters, only filters farther down the chain get the injected data.
I think especially because the metadata-injecting filter has already received end stream, it shouldn't get the data with end stream.
want me to take a look, or want to sort out the rest of the tests first?

**Comment by snowp** [comment]
Closing this in favor of removing ContinueAndEndStream altogheter

**Pull request closed without merging**
