### PR TITLE
golang network: fix issue 30210 (memory leaking caused by circular reference)

### PR DESCRIPTION
**Pull request by antJack**
https://github.com/envoyproxy/envoy/issues/30210

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by doujiang24 — APPROVED** [review]
lgtm~

**Review by alyssawilk — APPROVED** [review]
blind maintainer stamp - senior extension approval should be sufficient but github is github.

**Pull request merged**
