### PR TITLE
Docs: fix inconsistent search results behaviour

### LINKED ISSUE #15934: Inconsistent Search Results Behaviour
*Title*: 
*On the envoy docs, search results are inconsistent across similar search terms.*

*Description*:
I noticed when searching for [ip tagging](https://www.envoyproxy.io/docs/envoy/v1.17.0/api-v3/extensions/filters/http/ip_tagging/v3/ip_tagging.proto.html), that I could only find the page when i matched text in the qualified names referenced on the page.   Other pages I could find by matching any text on the page.

*Repro steps*:
.
_I reproduced the below behaviour on firefox, chrome, and safari. I did not test on all versions, but reproduced using latest, 1.17.1, 1.16.1, and 1.13.1_
- in the search field of [the docs](https://www.envoyproxy.io/docs/envoy/latest/) enter any of these terms: "ip tagging", "ip tag", "ip" and note the results.
- enter "iptag" and note the results.
- enter "kafka broker", "kafka", "kafka b", "emitting results", then note results.

The first set of terms will not bring up the ip tagging page.  "iptag" will return the page by matching on the qualified names in the page.  Any of the last terms will bring up the correct [kafka broker page](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/kafka_broker/v3/kafka_broker.proto.html) among its results.

*Admin and Stats Output*:
n/a

*Config*:
n/a

*Logs*:
n/a

*Call Stack*:
n/a

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long Dai <long0dai@foxmail.com>

Commit Message:

Upgrade Sphinx to fix inconsistent search result behaviour.

Fix #15934

Additional Description:

Upstream fix as https://github.com/sphinx-doc/sphinx/pull/8070

Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by daixiang0** [comment]
Sphinx-tabs only support sphinx<4 :(

**Comment by phlax** [comment]
> Sphinx-tabs only support sphinx<4 :(

there is a pr for sphinx-tabs which im expecting will land when sphinx4 comes out of beta

im wondering whether the stemmer fix could be applied outside of the sphinx4 upgrade - altho hopefully it will come out of beta soon

**Comment by daixiang0** [comment]
@phlax how about apply this patch by hand before deploy docs?

**Comment by phlax** [comment]
> how about apply this patch by hand before deploy docs?

it doesnt currently pass CI - besides i would rather wait until sphinx 4 is out of beta before landing that - i think it will make life easier with extensions etc

fixing the stemmer - ie the fix here https://github.com/sphinx-doc/sphinx/pull/8070 - maybe we can include what it does - not sure what is required to do that, or the cleanest way - i can check this further - its possible it could be included using a search adapter

hopefully sphinx4 will be stable soon

**Comment by daixiang0** [comment]
Got it, let's wait.

**Comment by daixiang0** [comment]
fixed by db066659049b03eca33452c4e07e65f622d1c4f5

**Pull request closed without merging**
