### PR TITLE
backport: v1.17 - ci: Publish artefacts for the exactly required docker images (#17080) 

### PR DESCRIPTION
**Pull request by phlax**
Commit Message: backport: v1.17 - ci docker save(#17080) 
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by dmitri-d** [comment]
This looks ok to me. Does this need to be ported to 1.18 too?

**Comment by phlax** [comment]
> Does this need to be ported to 1.18 too?

yep, i think it will want to be backported to all of the active branches

**Comment by dmitri-d** [comment]
@phlax: does this require any other changes (possibly in other repositories) other than the ones in this PR?

**Comment by phlax** [comment]
> does this require any other changes (possibly in other repositories) other than the ones in this PR?

it requires the same change to be applied to all of the release branches, ill create PRs shortly

**Comment by phlax** [comment]
in addition to this one, ive added backports for:

- v1.18 #17197 
- v1.16 #17198 

v1.15 did not require it as it doesnt have verify_examples

**Comment by phlax** [comment]
@dmitri-d @lizan i think this should be good to merge

**Review by lizan — APPROVED** [review]

**Pull request merged**
