### PR TITLE
[WIP/bp/1.31] Remove external_deps (mostly)

### PR DESCRIPTION
**Pull request by phlax**

### CODE REVIEW

**Comment by phlax** [comment]
trying to backport CI updates creates a lot of conflict with these PRs so figuring to bp these first

**Comment by phlax** [comment]
branches need some fixes before anything can pass/land - so marking WIP temporarily

**Comment by ggreenway** [comment]
This seems like a big change to backport. What's the reason for backporting this?

**Comment by phlax** [comment]
> This seems like a big change to backport. What's the reason for backporting this?

https://github.com/envoyproxy/envoy/pull/36351#issuecomment-2377213596

**Comment by phlax** [comment]
@ggreenway we are going to ~need to backport quite a lot  of change to make the release branches work with the migrated CI

doing that creates a huge amount of conflict with what is backported there - i could go through and resolve those conflicts but came to the conclusion that backporting these first would make life easier now and for any further backports that we try to add to these branches - ie they will be a lot closer to `main`. These changes are (bazel) config rather than code - i have asked @asedeno to review to ensure i didnt pick anything incorrectly

before this can land we need to just get the branches working again

**Comment by phlax** [comment]
pulling this - thinking further and @ggreenway is right this is too much change for a backport - finding a different path

**Pull request closed without merging**
