### PR TITLE
deps: Bump `rules_foreign_cc` -> 0.7.1

### LINKED ISSUE #19377: Newer release available `rules_foreign_cc`: 0.7.1 (current: 6c0c2af)
Package Name: rules_foreign_cc
Current Version: 6c0c2af@2021-09-22 00:35:40
Available Version: 0.7.1@2022-01-02 16:42:56
Upstream releases: https://github.com/bazelbuild/rules_foreign_cc/releases

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #19377
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
this seems to be failing the macos test

**Comment by moderation** [comment]
/lgtm deps

Looks likely to pass CI but is still in draft

**Comment by phlax** [comment]
i tried the mac test twice earlier and it failed, so not sure - kicked it again now to see if anything changed

**Comment by phlax** [comment]
mac test is still failing - not much useful in the way of logs that i can see, and im not sure where the fail logs go to from the Mac CI

**Comment by phlax** [comment]
4th time lucky! it worked!

**Review by lizan — APPROVED** [review]

**Pull request merged**
