### PR TITLE
http3: turn up the last upstream tests!

### PR DESCRIPTION
**Pull request by alyssawilk**
Several tests @danzh2010 fixed, plus one final test bug.

Risk Level: n/a
Testing:  yes!
Docs Changes: n/a 
Release Notes: n/a
#14829 among others

### CODE REVIEW

**Comment by alyssawilk** [comment]
Hmmm, windows failure looks real.

@envoyproxy/windows-dev we haven't solved the "have a repro environment for windows" issue yet have we?  If not can I get a volunteer to get me trace logs?

2021-05-03T15:01:37.6886147Z [ RUN      ] UpstreamProtocols/DownstreamProtocolIntegrationTest.VeryLargeRequestHeadersRejected/IPv6_HttpDownstream_Http3Upstream
2021-05-03T15:01:37.6888952Z test/integration/http_integration.cc(1192): error: Value of: response->complete()
2021-05-03T15:01:37.6890771Z   Actual: false
2021-05-03T15:01:37.6892168Z Expected: true
2021-05-03T15:01:37.6893243Z Stack trace:
2021-05-03T15:01:37.6894294Z   00007FF75A2B3310: (unknown)
2021-05-03T15:01:37.6895392Z   00007FF75A296035: (unknown)
2021-05-03T15:01:37.6897754Z   00007FF75A295EE3: (unknown)
2021-05-03T15:01:37.6899022Z   00007FF75A297A70: (unknown)
2021-05-03T15:01:37.6900225Z   00007FF75A298937: (unknown)
2021-05-03T15:01:37.6904210Z ... Google Test internal frames ...
2021-05-03T15:01:37.6904900Z 
2021-05-03T15:01:37.6906224Z unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.

**Comment by davinci26** [comment]
I can volunteer

**Comment by alyssawilk** [comment]
Awesome, thank you so much! :-)
your call if you want to patch now, or wait until it lands.  IMO there's no hurry.

**Review by ggreenway — APPROVED** [review]
Looks good.

**Pull request merged**
