### PR TITLE
owners: add @moderation as a Friend of Envoy.

### PR DESCRIPTION
**Pull request by htuch**
Many dependency bumps later :)

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

**Comment by htuch** [comment]
CC @envoyproxy/senior-maintainers

**Review by moderation — COMMENTED** [review]
LGTM and thanks. It's great to be involved with such a great community and maintainers.

**Review by mattklein123 — APPROVED** [review]
Yay!!! Thank you @moderation!

**Comment by mattklein123** [comment]
@htuch can you merge main? I want to see if I got the required checks correct.

/wait

**Review by lizan — APPROVED** [review]

**Review by ggreenway — APPROVED** [review]

**Comment by htuch** [comment]
@mattklein123 these all look like the right checks now. Will force merge.

**Pull request merged**
