### PR TITLE
ci/tests: Boost more worker cores for flakey integration tests

### PR DESCRIPTION
**Pull request by phlax**

### CODE REVIEW

**Review by tyxia — APPROVED** [review]
Thanks!

Do we need to bump every integration test?

**Comment by phlax** [comment]
> Do we need to bump every integration test?

i hope not

**Comment by tyxia** [comment]
> > Do we need to bump every integration test?
> 
> 
> 
> i hope not

This sounds like we will only know when failure shows up? I am curious any better ways to reliably fix/prevent it?

**Comment by phlax** [comment]
> This sounds like we will only know when failure shows up? I am curious any better ways to reliably fix/prevent it?

yeah - we have profiling data which i used initially to identify the memhogs

cpuhogs are a bit harder to profile in that way - but might be possible other ways - i expect this to settle down fairly quickly

profiling is expensive and also hogs resources so its not something we want to be doing without a clear purpose

**Pull request merged**
