### PR TITLE
[TESTING] Distroless  testing

### PR DESCRIPTION
**Pull request by phlax**
Commit Message: [TESTING] please ignore
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by oleksiyp** [comment]
Seems envoy is not able to find config file:
```
tls-inspector_1          | [2021-05-02 15:04:16.651][1][critical][main] [source/server/server.cc:113] error initializing configuration '/etc/envoy.yaml': unable to read file: /etc/envoy.yaml
```

**Comment by phlax** [comment]
> Seems envoy is not able to find config file:

i think i know what the problem is - ill try and fix it shortly...

**Comment by oleksiyp** [comment]
Maybe worth checking `static` base image variation which is used in istio-proxy:
```
https://github.com/istio/istio/blob/master/docker/Dockerfile.distroless
```

**Comment by oleksiyp** [comment]
I'm just wondering how they managed not to `chmod` everywhere: https://github.com/istio/istio/blob/master/pilot/docker/Dockerfile.proxyv2

**Comment by phlax** [comment]
> Maybe worth checking static base image variation which is used in istio-proxy

yep - sounds like a good idea - in my quick testing it works in a minimal way - not sure if it will work with envoy - it has no c libs at all afaict

```
$ docker run --rm -it distroless
~ $ /busybox/ls /lib/
~ $
```

**Comment by oleksiyp** [comment]
They have a fork of distroless with iptables: `https://github.com/GoogleContainerTools/distroless/compare/main...istio:iptables` and seems it is based on `nonroot` variation of the base image. Will try to play a bit with it in runtime to figure out either it is some compromise about security or there is some special trick.

**Comment by oleksiyp** [comment]
So, not yet 100% sure as official docs don't specify this behaviour, but COPY is copying host permissions. Thus make sense to chmod everything that is COPYied in Dockerfile before running `docker build`. Also `--chmod` flag seems to be quite recent things and as well not documented.

**Comment by phlax** [comment]
>  Also --chmod flag seems to be quite recent things and as well not documented.

yep - not sure if it will work - it works in multistage builds so im optimistic

this is just for testing so i can resolve another way if it doesnt

waiting...

**Comment by phlax** [comment]
re the iptables image - it seems like its debian 9

**Comment by phlax** [comment]
chmod didnt work (arrgghh!)

as youve picked the changes from here to your pr ill close this

**Pull request closed without merging**
