### PR TITLE
mobile: consistently compiling out admin code

### PR DESCRIPTION
**Pull request by alyssawilk**
Changing the default E-M build to not include the admin interface.  It is enabled for swift CI due to regression tests.

Risk Level: low
Testing: CI
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by alyssawilk** [comment]
@jpsim @Augustyniak if I fix up the C++ tests to work sans admin, what do you folks think about landing this, vs switching only some of the CI bots to not include admin?

**Review by RyanTheOptimist — DISMISSED** [review]
Nice!

**Review by abeyad — DISMISSED** [review]

**Comment by abeyad** [comment]
Probably want to change the title of the PR to remove "WIP"

**Review by jpsim — APPROVED** [review]

**Review by abeyad — APPROVED** [review]

**Pull request merged**
