### PR TITLE
Add missing words to dictionary

### PR DESCRIPTION
**Pull request by Augustyniak**
44eedc792ab64bba2358e0294b53294c6bc30526 broke spell checking that's run as part of the git pre-push hook. This PR is supposed to fix it by adding new words to dictionary.

Running `git push` prior to the fix:
```
Checking format for third_party/statusor/statusor.cc - PASS
Checking spelling for third_party/statusor/statusor.cc
third_party/statusor/statusor.cc:7: * Copyright 2019 Google LLC
third_party/statusor/statusor.cc:41:} // namespace internal_statusor
Checked 1 file(s) and 22 comment(s), found 2 error(s).
ERROR: spell check failed. Run 'tools/spelling/check_spelling_pedantic.py fix and/or add new words to tools/spelling/spelling_dictionary.txt'
```

Running `tools/spelling/check_spelling_pedantic.py fix` with the fix in:
```
Checked 2964 file(s) and 84314 comment(s), found 0 error(s).
```

Signed-off-by: Rafal Augustyniak <raugustyniak@lyft.com>

### CODE REVIEW

**Comment by yanavlasov** [comment]
Hmm, it looks like I missed the exclusion of the third_party in spell checker. The correct fix is to not check the third_party directory content at all. I will fix this.

**Comment by yanavlasov** [comment]
Actually how does your git hook invokes `tools/spelling/check_spelling_pedantic.py` ? By default the script should not check `third_partry`.

**Comment by Augustyniak** [comment]
1. I used standard git hook that comes with Envoy
1. I run `tools/spelling/check_spelling_pedantic.py` manually just to confirm that everything works - it was not involved by my git hook.

**Comment by yanavlasov** [comment]
Just to make sure. Does this `tools/spelling/check_spelling_pedantic.py check` fails for you?

**Pull request closed without merging**
