### PR TITLE
Reduce Route/VirtualHost memory utilization by avoiding RateLimitPolicy instances when not needed

### PR DESCRIPTION
**Pull request by yurykats**
Reduce Route/VirtualHost memory utilization by avoiding RateLimitPolicy instances when not needed.

Currently an instance of RateLimitPolicyImpl is created in each vhost and route, even if no rate limiting is configured. This PR switches instances to unique_ptr and only creates RateLimitPolicyImpl objects when actually configured. Otherwise a singletong default policy is used.

This is a step towards more memory efficient config data structures. Issue #24154.

Similar change to Retry, Hedge and InternalRedirect policies was made in PR #24182.

Signed-off-by: Yury Kats <ykats@google.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Review by zuercher — APPROVED** [review]
thanks!

**Pull request merged**
