### PR TITLE
ci: Timeout test result publishing if agent is hung

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
checking azp analytics the upload job can legitimately take a while - up to around 5 mins afaict - if it has taken 10 mins then i think we can assume it has hung

**Comment by phlax** [comment]
do the same for `PublishBuildArtefacts`

/wait

**Comment by lizan** [comment]
I doubt it has effect since the timeout is implemented in agent, if agent hungs it is likely no-op.

**Comment by phlax** [comment]
> the timeout is implemented in agent

can you point me to the docs that says this is a timeout _in_ agent

my reading of https://developercommunity.visualstudio.com/t/azure-devops-timeoutinminutes-is-being-ignored-in/567714 and https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts is that this should work

should we not at least try this - the arm agent is hanging fairly frequently during the publish steps - do you think we can set the timeout somewhere else to tackle this ?

**Comment by lizan** [comment]
https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Worker/StepsRunner.cs

If the agent didn't die but the upload task times out this works so we can definitely try.

**Comment by lizan** [comment]
@phlax did this work out?

**Comment by phlax** [comment]
no way to tell until we land it

**Review by lizan — APPROVED** [review]

**Pull request merged**
