### PR TITLE
ci: fix 'six' Python library download URL

### PR DESCRIPTION
**Pull request by fredlas**
Signed-off-by: Fred Douglas <fredlas@google.com>

### CODE REVIEW

**Comment by fredlas** [comment]
Stumbled across this when `./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.compile_time_options'` failed for me. The important part of this PR is updating the URL. While I was on the site finding the new link, I noticed the new version and figured I might as well update. If it's better to stay with 1.10, I can change it to that!

**Comment by dio** [comment]
cc. @lizan

**Comment by lizan** [comment]
it has to be 1.10 to align with protobuf: https://github.com/protocolbuffers/protobuf/blob/master/six.BUILD

**Comment by fredlas** [comment]
Got it, thanks. Reverted back to 1.10.

**Pull request merged**
