### PR TITLE
build: bazel 1.2.0

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

Description:
Risk Level: Low
Testing: CI
Docs Changes:
Release Notes:

### CODE REVIEW

**Comment by l8huang** [comment]
> /azp run envoy-macos

@lizan I have a fix for the failed test case  test case UdpListenerImplTest.SendData for envoy-macos. I saw you encountered that issue:  https://dev.azure.com/cncf/envoy/_build/results?buildId=20576

**Comment by lizan** [comment]
@l8huang that test is flaky, can you open a PR to fix it?

**Comment by l8huang** [comment]
@lizan yes, I did, PR is https://github.com/envoyproxy/envoy/pull/9119

**Pull request merged**
