### PR TITLE
Fix: flaky golang-network sandbox

### PR DESCRIPTION
**Pull request by antJack**
fix https://github.com/envoyproxy/envoy/issues/28543

```golang
func CreateUpstreamConn(addr string, filter api.UpstreamFilter) {
        // call envoy to async connect with the upstream addr
	h := uint64(uintptr(cgoAPI.UpstreamConnect(libraryID, addr)))  
 
       // store the golang filter for later used by 'onPoolReady' or 'onPoolFailure'
       // if the async connecting is faster than cgo callback, it cannot find the golang filter so it will panic
	_ = UpstreamFilters.StoreFilter(h, filter)  
```

the cgo callback from `cgoAPI.UpstreamConnect` may take times (depending on the golang runtime), if the async connecting with upstream returns faster then the cgo callback, then it will fail to get the golang filter and panic.

the solution is to store the golang filter earlier than the cgo call.

### CODE REVIEW

**Comment by antJack** [comment]
@doujiang24 @wangfakang @phlax PTAL, thanks

**Review by doujiang24 — APPROVED** [review]

**Review by phlax — APPROVED** [review]
lgtm, thanks @antJack

**Pull request merged**
