### PR TITLE
deps: Resolve conflicting python updates

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: deps: Resolve python requirement updates
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Close #15691 Close #15694 Close #15697 Close #15689 
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
`gitdb` requirement has some inconsistency preventing upgrade

upstream ticket here:

https://github.com/gitpython-developers/gitdb/issues/69

**Comment by phlax** [comment]
> gitdb requirement has some inconsistency preventing upgrade of smmap

this is now resolved upstream

**Comment by phlax** [comment]
merging other resolution PRs ...

/wait

**Comment by phlax** [comment]
@moderation @mattklein123 ci is passing - ill clear the related dependa prs once this  has landed and merge all the other prs

**Review by mattklein123 — APPROVED** [review]
Thank you!

**Pull request merged**
