### PR TITLE
aws_lambda: Update to support upstream filter usage

### PR DESCRIPTION
**Pull request by juanmolle**
Commit Message: aws_lambda: Update to support upstream filter usage

Additional Description: Minor change to aws_lambda extension to allow usage as an upstream http filter. This is so that path modifications during forwarding do not invalidate signatures calculated pre-forwarding stage. Code change based on template https://github.com/envoyproxy/envoy/blob/main/source/docs/upstream_filters.md

Risk Level: Low
Testing: yes
Docs Changes: yes
Release Notes: yes
Platform Specific Features: n/a

### CODE REVIEW

**Comment by juanmolle** [comment]
Is there any way to know in the filter if it was loaded as an upstream filter?

**Comment by juanmolle** [comment]
cc: @suniltheta

**Review by suniltheta — APPROVED** [review]
@juanmolle  sure, even I can't think of scenario where we would want to skip an upstream filter.

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
