### PR TITLE
deps: Bump python `cffi` -> 1.15.0

### LINKED ISSUE #20821: tools: dependency cffi==1.14.6 should be updated to cffi==1.15.0
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *dependency cffi==1.14.6 should be updated to cffi==1.15.0*

*Description*:
./tools/gen_compilation_database.py failed with error message:
```
ERROR: An error occurred during the fetch of repository 'base_pip3_cffi':                                                                                                                                                                                          Traceback (most recent call last):                                                                                                                                                                                                                                   File "/source/build/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/rules_python/python/pip_install/pip_repository.bzl", line 368, column 13, in _whl_library_impl                                                                                          fail("whl_library %s failed: %s (%s)" % (rctx.attr.name, result.stdout, result.stderr))                                                                                                                                                         Error in fail: whl_library base_pip3_cffi failed: Collecting cffi==1.14.6                                                                                                                                                                                         Downloading cffi-1.14.6.tar.gz (475 kB)                                                                                                                                                                                                                       Building wheels for collected packages: cffi                                                                                                                                                                                                                      Building wheel for cffi (setup.py): started                                                                                                                                                                                                                     Building wheel for cffi (setup.py): finished with status 'error'                                                                                                                                                                                                Running setup.py clean for cffi                                                                                                                                                                                                                               Failed to build cffi                                                                                                                                                                                                                                             (  ERROR: Command errored out with exit status 1:                                                                                                                                                                                                                 command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-_kcqe4op/cffi_887f849e2a0040518195fee7edce407e/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-_kcqe4op/cffi_887f849e2a0040518195fee7edce407e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-in98j32s                                                                                                                                                                                                                      cwd: /tmp/pip-wheel-_kcqe4op/cffi_887f849e2a0040518195fee7edce407e/                                                                                                                                                                                        Complete output (33 lines):                                                                                                                                                                                                                                     running bdist_wheel                                                                                                                                                                                                                                             running build                                                                                                                                                                                                                                                   running build_py                                                                                                                                                                                                                                                creating build                                                                                                                                                                                                                                                  creating build/lib.linux-x86_64-3.10                                                                                                                                                                                                                            creating build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                                       copying cffi/__init__.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                    copying cffi/api.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                         copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                              copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                 copying cffi/commontypes.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                 copying cffi/cparser.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                     copying cffi/error.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                       copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                 copying cffi/lock.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                        copying cffi/model.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                       copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                   copying cffi/recompiler.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                  copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                              copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                 copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                 copying cffi/verifier.py -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.10/cffi                                                                                                                                                                                                copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.10/cffi
  copying cffi/_embedding.h -> build/lib.linux-x86_64-3.10/cffi
  copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.10/cffi
  running build_ext
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/c
  clang -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g0 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.10 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.10/c/_cffi_backend.o
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -stdlib=libc++ -g0 build/temp.linux-x86_64-3.10/c/_cffi_backend.o -L/usr/lib -lffi -o build/lib.linux-x86_64-3.10/_cffi_backend.cpython-310-x86_64-linux-gnu.so
  x86_64-linux-gnu-gcc: error: unrecognized command line option ‘-stdlib=libc++’
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for cffi
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/source/build/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/rules_python/python/pip_install/parse_requirements_to_bzl/extract_single_wheel/__main__.py", line 4, in <module>
    main()
  File "/source/build/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/rules_python/python/pip_install/parse_requirements_to_bzl/extract_single_wheel/__init__.py", line 57, in main
    subprocess.run(pip_args, check=True, env=env)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--isolated', 'wheel', '--no-deps', '--require-hashes', '-r', '/tmp/tmpcoj6wlrk']' returned non-zero exit status 1.
)
ERROR: /source/WORKSPACE:21:25: fetching whl_library rule //external:base_pip3_cffi: Traceback (most recent call last):
        File "/source/build/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/rules_python/python/pip_install/pip_repository.bzl", line 368, column 13, in _whl_library_impl
                fail("whl_library %s failed: %s (%s)" % (rctx.attr.name, result.stdout, result.stderr))
Error in fail: whl_library base_pip3_cffi failed: Collecting cffi==1.14.6
  Downloading cffi-1.14.6.tar.gz (475 kB)
Building wheels for collected packages: cffi
  Building wheel for cffi (setup.py): started
  Building wheel for cffi (setup.py): finished with status 'error'
  Running setup.py clean for cffi
Failed to build cffi
 (  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-_kcqe4op/cffi_887f849e2a0040518195fee7edce407e/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-_kcqe4op/cffi_887f849e2a0040518195fee7edce407e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-in98j32s
       cwd: /tmp/pip-wheel-_kcqe4op/cffi_887f849e2a0040518195fee7edce407e/
```

`tools/base/requirements.txt` `cffi==1.14.6` should be upgraded to `cffi==1.15.0`

**The procedure to reproduce it:**
```sh
./ci/run_envoy_docker.sh bash
cd /source
./bazel/setup_clang.sh /opt/llvm
echo "build --config=libc++" > user.bazelrc
./tools/gen_compilation_database.py
```

### PR DESCRIPTION
**Pull request by phlax**
Fix #20821

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by durd07 — APPROVED** [review]
LGTM. Thanks.

**Comment by durd07** [comment]
@moderation could you please help to review and merge this PR?

**Review by durd07 — APPROVED** [review]

**Review by KBaichoo — APPROVED** [review]

**Pull request merged**
