### PR TITLE
build: Add `-fdebug-types-section`

### PR DESCRIPTION
**Pull request by phlax**
While this may slow builds down a little and result in slightly larger debug builds, it should reduce the size of production bins.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
For comparison this is the produced binaries:

```console
$ tar tfv compare/release.type-debug-sections.tar.zst 
drwxr-xr-x 0/0               0 2000-01-01 00:00 dbg/
-rw-r--r-- 0/0       519723776 2000-01-01 00:00 dbg/envoy
-rw-r--r-- 0/0       608085896 2000-01-01 00:00 dbg/envoy-contrib
-rw-r--r-- 0/0       463246616 2000-01-01 00:00 dbg/envoy-contrib.dwp
-rw-r--r-- 0/0       401576584 2000-01-01 00:00 dbg/envoy.dwp
-rw-r--r-- 0/0        69309432 2000-01-01 00:00 envoy
-rw-r--r-- 0/0        92852608 2000-01-01 00:00 envoy-contrib
drwxr-xr-x 0/0               0 2000-01-01 00:00 utils/
-rw-r--r-- 0/0           18744 2000-01-01 00:00 utils/su-exec
(dev) phlax@scratch:~/dev/envoydev/envoy$ tar tfv compare/release.current.tar.zst
drwxr-xr-x 0/0               0 2000-01-01 00:00 dbg/
-rw-r--r-- 0/0       523933000 2000-01-01 00:00 dbg/envoy
-rw-r--r-- 0/0       612726624 2000-01-01 00:00 dbg/envoy-contrib
-rw-r--r-- 0/0       463246616 2000-01-01 00:00 dbg/envoy-contrib.dwp
-rw-r--r-- 0/0       401576584 2000-01-01 00:00 dbg/envoy.dwp
-rw-r--r-- 0/0        69309432 2000-01-01 00:00 envoy
-rw-r--r-- 0/0        92852608 2000-01-01 00:00 envoy-contrib
drwxr-xr-x 0/0               0 2000-01-01 00:00 utils/
-rw-r--r-- 0/0           18744 2000-01-01 00:00 utils/su-exec
```

**Comment by phlax** [comment]
seems it only impacts the debug bins, and only a little but positively

**Comment by phlax** [comment]
Originally added here to unblock #30394 which has a related issue - but sadly didnt help

**Review by lizan — APPROVED** [review]

**Pull request merged**
