### PR TITLE
Fix typo discovered by codespell

### PR DESCRIPTION
**Pull request by cclauss**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by phlax** [comment]
@cclauss you need to fix DCO - see (https://github.com/envoyproxy/envoy/blob/master/CONTRIBUTING.md#dco-sign-your-work)

**Comment by cclauss** [comment]
What originally do we expect to find in the correction of typos?

**Comment by asraa** [comment]
> What originally do we expect to find in the correction of typos?

What do you mean @cclauss?

**Comment by asraa** [comment]
@cclauss Could you please fix DCO?
/wait

**Comment by cclauss** [comment]
A DCO is a Developer’s Certificate of Originality but there is no originality in fixing typos.

**Comment by phlax** [comment]
@clauss it makes continuous integration happy 8/

**Comment by asraa** [comment]
Ah! It also provides us an email in case there's a need for contact (for whatever reason?)

**Comment by cclauss** [comment]
Bump on this one...

**Pull request closed without merging**
