### PR TITLE
quic::Update QUICHE from e87010ff9 to 96a9f6bd7

### PR DESCRIPTION
**Pull request by danzh2010**
https://github.com/google/quiche/compare/e87010ff9..96a9f6bd7

$ git log e87010ff9..96a9f6bd7 --date=short --no-merges --format="%ad %al %s"

2021-12-16 quiche-dev Move oghttp2 shutdown tests to oghttp2_adapter_test.cc, and add analogous nghttp2 tests.
2021-12-16 quiche-dev Add ProcessBytesError entries for bad client magic and user callback failures.
2021-12-16 quiche-dev Refactor OgHttp2Session::ProcessBytes().
2021-12-14 quiche-dev Allow visitor_.OnFrameSent() to propagate a fatal send error, and do not retry sending on fatal send errors.
2021-12-14 quiche-dev Adds validation for 204 responses, which should carry no body.
2021-12-14 vasilvv Add public_key_type() accessor to quic::CertificateView.
2021-12-14 quiche-dev Return an nghttp2-compatible error value for OgHttp2Session::Send().
2021-12-14 quiche-dev Simplifies HeaderValidator error codes.
2021-12-14 quiche-dev Supports the `:protocol` pseudo-header for connect requests if SETTINGS_ENABLE_CONNECT_PROTOCOL is sent.
2021-12-13 quiche-dev Fix use-after-move in TlsConnection
2021-12-13 quiche-dev Don't crash if QuicServerConfigProtobuf is invalid.
2021-12-13 quiche-dev Return the vector of config ids by value, not via an output parameter.
2021-12-09 quiche-dev Tracks streams with ready metadata or trailers separately from write_scheduler_.
2021-12-09 haoyuewang Add knobs that enable QBONE to use IETF QUIC.
2021-12-08 quiche-dev Add `max_header_bytes` to OgHttp2Session::Options() and send in initial SETTINGS.

Signed-off-by: Dan Zhang <danzh@google.com>

Risk Level: Low
Testing: all existing tests passed
Docs Changes: N/A 
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by wrowe — APPROVED** [review]
Looks good

**Comment by danzh2010** [comment]
Can this PR be merged? @envoyproxy/senior-maintainers

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
