### PR TITLE
config: example config with runtime overrides of deprecated config

### LINKED ISSUE #9823: Example for overriding use of deprecated features?
This section here describes the use of the runtime configuration to enable the use of deprecated features:

 https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features
> In the second phase the field will be tagged as disallowed_by_default and use of that configuration field will cause the config to be rejected by default. This disallowed mode can be overridden in runtime configuration by setting envoy.deprecated_features:full_fieldname or envoy.deprecated_features:full_enum_value to true. For example, for a deprecated field Foo.Bar.Eep set envoy.deprecated_features:Foo.bar.Eep to true

Can anyone provide an example of this? Specifically I'd like to be able to use the Zipkin tracing config with HTTP_JSON_V1 for a little while until we can update our Jaeger collector configuration. 

```
tracing:
  http:
    name: envoy.zipkin
    config:
      collector_cluster: jaeger
      collector_endpoint: @COLLECTOR_ENDPOINT@
      collector_endpoint_version: HTTP_JSON_V1
```

I know that the link above has examples for configuring the Runtime with layers but I don't understand where envoy.deprecated_features:full_fieldname would fit in

### PR DESCRIPTION
**Pull request by alyssawilk**
Includes use of a deprecated field, and deprecated enum.

Risk Level: n/a
Testing: config tests covers it
Docs Changes: n/a
Release Notes: n/a
Fixes #9823

### CODE REVIEW

**Comment by alyssawilk** [comment]
I don't know of a great way to link this from existing runtime docs, but at least it gets it in the repo.
cc @htuch just so this is on your radar - we want to leave it as v2 as long sa v2 is supported.

**Comment by mattklein123** [comment]
> I don't know of a great way to link this from existing runtime docs, but at least it gets it in the repo.
cc @htuch just so this is on your radar - we want to leave it as v2 as long sa v2 is supported.

You can use the `:repo:` ref link type (search for other examples). Do you mind also adding a FAQ entry on this? I think that would be helpful. The FAQ can just generally describe the process and then link to various things? WDYT?

/wait

**Comment by ggreenway** [comment]
I was just searching for how to do this. This is useful! 

Please link to this from https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features, and also from the third bullet point (talking about schedule and making config not load anymore) under https://github.com/envoyproxy/envoy/blob/51a1ef7c3e1de657991630a8f31112318e2d26d6/CONTRIBUTING.md#breaking-change-policy

**Comment by alyssawilk** [comment]
@mattklein123 I think we explain the process pretty well in the contributing doc.  Think I should move it somewhere else or is that what you were looking for?
The runtime docs do link there, so both docs reference each other (now with up to date links)

**Pull request merged**
