### PR TITLE
Envoy Mobile: making exception-free build the default

### PR DESCRIPTION
**Pull request by alyssawilk**
This changes a number of Envoy throw EnvoyException calls to use the wrapper throwEnvoyExceptionOrPanic (which for Envoy should still resolve to "throw EnvoyException", so should be a no-op) 

Risk Level: low
Testing: existing CI
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by alyssawilk** [comment]
@phlax can you make sure I removed the compile time options build correctly?  After that you can remove yourself as a reviewer.

**Review by phlax — APPROVED** [review]
lgtm, thanks @alyssawilk

**Review by RyanTheOptimist — DISMISSED** [review]
LGTM. Sweet! Can you also update the PR description to mention the changes to non-mobile source (to use more throwOrPanics).

**Comment by alyssawilk** [comment]
ugh, did a main merge to handle conflicts, but that broke prechecks because it's broken at HEAD.
https://github.com/envoyproxy/envoy/pull/35119 
hard resetting away the main merge (sorry reset but hopefully won't break diffs as you didn't review that push)

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
