### PR TITLE
deps/ci: Use `envoy.dependency.check`

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
testing for https://github.com/envoyproxy/pytooling/pull/143

cc @kfaseela

**Comment by phlax** [comment]
cc @kfaseela @ME-ON1

**Comment by ME-ON1** [comment]
lgtm just a small query 

This action is a scheduled Cron it will not be triggered by a PR event. This looks unnecessary. 

      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

**Comment by phlax** [comment]
> This action is a scheduled Cron it will not..

yep. thanks @ME-ON1 ive updated the config to be closer to the original

**Comment by phlax** [comment]
@htuch this one is hopefully ready for final review - if you approve it would be good to land myself as i want to watch CI after it lands

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
