### PR TITLE
Dependencies: remove duplicate toolshed entry

### PR DESCRIPTION
**Pull request by moderation**
Commit Message: Dependencies: remove duplicate toolshed entry
Additional Description: Noop name and repo location change for libcircllhist
Risk Level: Low
Testing: `bazel --nohome_rc test //test/...`
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

Signed-off-by: Michael Payne [michael@sooper.org](mailto:michael@sooper.org)

### CODE REVIEW

**Review by phlax — APPROVED** [review]
lgtm, thanks @moderation

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by moderation** [comment]
Start emulator step on Java helloworld timing it

**Pull request merged**
