### PR TITLE
ci/github: Fix repo contexts

### PR DESCRIPTION
**Pull request by phlax**
- Improve names in newer/triggered github CI
- Attempt to ensure untrusted code is able to run in triggered (only correct) CI
- Dont checkout the repo for build image
- Remove fail supression from azp trigger
- make `.github/workflows/_env.yml` the authoritative source for build image config (doesnt require repo checkout)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
Example improved associated title for pr

image

this will almost certainly need some tweaking after it lands, its quite hard to test

**Comment by phlax** [comment]
making a final adjustment ...

**Comment by phlax** [comment]
other than a typo, seems like flakey ci

/retest mobile

**Review by ravenblackx — DISMISSED** [review]
Semi-blind approval; nothing looks malicious, what I understand looks fine, and I trust phlax to undo any harm that might result.

**Comment by phlax** [comment]
> I trust phlax to undo any harm that might result.

thanks, trying to lock down how this workflow can run both un/trusted code - review appreciated

**Review by ravenblackx — APPROVED** [review]

**Pull request merged**
