### PR TITLE
test: consolidating file logic

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: n/a (test only)
Testing:  n/a
Docs Changes: n./a
Release Notes: n/a

### CODE REVIEW

**Review by dio — DISMISSED** [review]
Thanks! I suspect CI failure is a flake?

**Review by dio — APPROVED** [review]

**Comment by alyssawilk** [comment]
ok, finally got windows working, sorry for the churn :-)

**Review by dio — APPROVED** [review]
Thanks, @alyssawilk!

**Pull request merged**
