### PR TITLE
Change mobile binary size comparison workflow to use release build

### PR DESCRIPTION
**Pull request by caschoener**
Was debugging a binary size increase in https://github.com/envoyproxy/envoy/actions/runs/4008291380/workflow and noticed that the comparison is based on --config=remote-ci-linux-clang.  Talked with JP and it seems more appropriate to compare a release build instead.

Test plan: Look at CI

### CODE REVIEW

**Comment by caschoener** [comment]
image
The number changed from 858 MB to 28.  This seems like a more accurate representation of our binary size though.  What do you think JP?

**Review by jpsim — APPROVED** [review]
I think this is appropriate. Thanks for the fixes!

**Comment by jpsim** [comment]
> The number changed from 858 MB to 28.

This isn't terribly surprising. On iOS, where we statically link and deadstrip some code at link time, we see a ~5MB size increase from using Envoy Mobile to the compressed single-architecture iOS app.

**Comment by caschoener** [comment]
image
Sweet

**Pull request merged**
