### PR TITLE
test: Add oghttp2 and wrapped-nghttp2 coverage to codec_impl_fuzz_test.cc

### PR DESCRIPTION
**Pull request by diannahu**
Commit Message: This PR updates codec_impl_fuzz_test.cc's HttpVersion to include oghttp2 and wrapped-nghttp2, then enables the appropriate runtime config in testing.
Additional Description: Other examples of the three HTTP/2 codec variations and associated runtime config enablement can be found at https://github.com/envoyproxy/envoy/search?q=setupHttp2Overrides. However, I chose not to use a dedicated method here because setup occurs at only one place.
Risk Level: Low
Testing: bazel test //test/common/http:codec_impl_fuzz_test --config=libc++
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:] 
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by wbpcode — APPROVED** [review]
LGTM.

**Comment by wbpcode** [comment]
Hi, can you rebase your commits to make the final merge commit info more clean? It seems that there are some outdated commits.

**Review by yanavlasov — APPROVED** [review]

**Comment by diannahu** [comment]
> Hi, thanks for your great contribution. tulip It's LGTM. Only one nit comment. Could you rebase your commits to make the final merge commit info more clean? It seems that there are some outdated commits.
> 
> /wait-any

Hi, thanks both for your reviews!

I tried to rebase my commits for squashing/cleaning the final merge commit info, but I ran into many merge conflicts along the way. I've opened envoyproxy#20837, which is an identical respin of this PR except with just a single commit for the proposed code. I will add you as a reviewer on this new PR.

Thanks!
Dianna

**Pull request closed without merging**
