### PR TITLE
tooling: Remove pytest and python coverage 

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
not yet, this is a couple of PRs away from being ready 

the main blocker is shifting the code that was previously being tested

i have upstreamed that code and just doing some final work on it (PR to make use of it is here #21126 )

**Comment by phlax** [comment]
@moderation should be good for review now

**Review by wrowe — APPROVED** [review]
Significant simplification, thanks for this effort!

**Pull request merged**
