### PR TITLE
*: update URLs

### PR DESCRIPTION
**Pull request by vbatts**
https://envoyproxy.github.io/ -> https://www.envoyproxy.io/

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

*Description*:
updates links to the new docs site

*Risk Level*: Low 

*Testing*:
Clink the URL and ensure it's not a 404

### CODE REVIEW

**Comment by vbatts** [comment]
oh there are more.. I only was looking at `./examples/` first. One sec

**Comment by vbatts** [comment]
ok, updated. PTAL

**Comment by htuch** [comment]
Do we need the `www.` prefix? It looks good, it just seems so long that I used this in front of anything..

**Comment by vbatts** [comment]
Fair. It's one fewer redirects, but I can remove it if you'd like

**Comment by htuch** [comment]
I see, if it's fewer redirects the keep it. I like the world wide web :)

**Pull request merged**
