### PR TITLE
Remove runtime guard envoy_reloadable_features_stateful_session_encode_ttl_in_cookie

### PR DESCRIPTION
**Pull request by cpakulski**
Commit Message:
Removed runtime guard  envoy_reloadable_features_stateful_session_encode_ttl_in_cookie
Additional Description:
Risk Level: Low
Testing: Adjusted tests.
Docs Changes: No
Release Notes: Yes 
Platform Specific Features:
Fixes: #31983

### CODE REVIEW

**Comment by yanavlasov** [comment]
LGTM. @cpakulski please resolve merge conflicts.

/wait

**Comment by cpakulski** [comment]
@yanavlasov I guess it is good for merge (before I have to rebase again :-)). Thanks!

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
