### PR TITLE
bazel: Shift deprecate_* tools to bazel and cleanup requirements

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: bazel: Shift deprecate_* tools to bazel and cleanup requirements
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
requires repo_path #17293

**Review by alyssawilk — COMMENTED** [review]
Thanks as always for tooling clean up! Do you mind updating deprecate_versions usage in GOVERNANCE.md as well?

@adisuissa @htuch I'm wondering what our plan is for deprecate_features, which previously annotated "deprecated" protos as "fatal-by-default" so we could start cleaning them up. What's the new plan for eventually doing config clean up in envoy and should we remove or replace that script?

**Comment by phlax** [comment]
> What's the new plan for eventually doing config clean up in envoy and should we remove or replace that script?

not sure, i was just going through any scripts that didnt use bazel, and moving them. Mostly that means the lesser used ones - some of which may no longer be required

@htuch ?

**Comment by htuch** [comment]
The fatal-by-default for deprecated should continue to be a part of the process. Minor versioning has its own tooling that @adisuissa has built out, which adds in additional annotations on when things are removed in Envoy and there is the 1 year cycle around this. But, this doesn't change the fact that we want to signal early to the community that deprecated features are going away, so +1 to keeping this process around.

**Comment by adisuissa** [comment]
We are still going to have a deprecation period, where deprecated features are still usable, but marked as fatal-by-default. This will serve as a final-warning and encourage upgrade before removing the support.

**Comment by alyssawilk** [comment]
Gotcha.  FWIW the script was removed from our release process a while back due to uncertainty around the longer term plan.  If we plan on using it it'd be good to make sure it's still WAI and add it back.

**Comment by phlax** [comment]
ive updated the GOVERNANCE doc

looking through these scripts, if we are going to keep them, we probably want to update them at some point, but this PR at least brings them into the bazel workflow and reduces dep noise

**Comment by adisuissa** [comment]
> Gotcha. FWIW the script was removed from our release process a while back due to uncertainty around the longer term plan. If we plan on using it it'd be good to make sure it's still WAI and add it back.

Ack.

Thanks @phlax for the cleanup.

**Review by alyssawilk — APPROVED** [review]

**Review by wrowe — APPROVED** [review]
/lgtm deps

**Pull request merged**
