### PR TITLE
Regenerate envoy-mobile toolchain to reflect newer tools

### PR DESCRIPTION
**Pull request by asedeno**
Since this was last generated, we've moved from bazel 4.2.1 to 6.5.0, and the version of ubuntu being used in our docker config has been updated.

Following the instructions in https://github.com/bazelbuild/bazel-toolchains

Specifically:

```
$ ./rbe_configs_gen \
  --bazel_version="6.5.0" \
  --toolchain_container="docker.io/envoyproxy/envoy-build-ubuntu:f94a38f62220a2b017878b790b6ea98a0f6c5f9c" \
  --exec_os="linux" \
  --target_os="linux" \
  --output_src_root="/path/to/envoy-mobile" \
  --output_config_path="third_party/rbe_configs" \
  --cpp_env_json=clang.json \
  --generate_java_configs=False
$ cat clang.json
{"CC": "/opt/llvm/bin/clang", "CXX": "/opt/llvm/bin/clang++"}
```

### CODE REVIEW

**Comment by phlax** [comment]
relatedly - i just moved the main envoy toolchains back into the repo - i was thinking to add a CI workflow to update these

**Comment by asedeno** [comment]
@phlax I saw that, and was meaning to ask you about it, and about whether or not this change makes sense. I do know that the generated toolchain is very outdated and think _something_ needs to be done here. As ever, vexed by mobile, though here it's resource exhaustion.

**Comment by phlax** [comment]
yeah - probs not high priority, but also probs good to keep up-to-date - im not 100% clear on what regenerating does if you have the same config - but also not exactly clear on the config

not sure on the resource exhaustion but my guess is _all caches blown_

with the envoy toolchains, they were being regenerated any time anything landed in the envoy-build-tools repo, so they should be fairly up-to-date, or at least recently rebuilt

this was kinda why i wanted to add some ci for this - i didnt want to get to a situation of not being able to regenerate

**Comment by asedeno** [comment]
Aside from a shebang line change earleir this year, `mobile/third_party/rbe_configs/cc` hasn't been updated since 2022. It includes such gems as:

```
cxx_flags = ["-std=c++0x"]
```

It definitely needs a refresh, and automated regeneration would be great.

**Comment by asedeno** [comment]
Closing this in favor of the smaller change in #36269.

**Pull request closed without merging**
