### PR TITLE
deps: update com_github_wasmtime: v0.33.0 (current: v0.32.0)

### LINKED ISSUE #19416: Newer release available `com_github_wasmtime`: v0.33.0 (current: v0.32.0)
Package Name: com_github_wasmtime
Current Version: v0.32.0@2021-12-13 19:56:49
Available Version: v0.33.0@2022-01-05 19:26:50
Upstream releases: https://github.com/bytecodealliance/wasmtime/releases

### PR DESCRIPTION
**Pull request by kfaseela**
Fixes #19416

Signed-off-by: Faseela K <faseela.k@est.tech>

### CODE REVIEW

**Comment by kfaseela** [comment]
cc @PiotrSikora @phlax

**Comment by PiotrSikora** [comment]
This is still blocked on https://github.com/envoyproxy/envoy/pull/19404.

**Comment by PiotrSikora** [comment]
> This is still blocked on #19404.

...and unblocked now, so you need to merge the `main` branch.

**Comment by phlax** [comment]
#19404 landed but i think you will need to main merge

**Review by phlax — APPROVED** [review]
lgtm, thanks @kfaseela

**Pull request merged**
