### PR TITLE
remove useless import

### PR DESCRIPTION
**Pull request by zirain**
Commit Message: remove unseless import, which broken macos build, see https://github.com/envoyproxy/envoy/pull/35933
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by dbarbosapn — APPROVED** [review]
Oops, my bad 😄 

Would be nice to know why this breaks macos build though.
Also, @mattklein123 could the formatting CI check (and tool) check (and remove) unused imports?

**Comment by zirain** [comment]
> Oops, my bad 😄
> 
> Would be nice to know why this breaks macos build though. Also, @mattklein123 could the formatting CI check (and tool) check (and remove) unused imports?

```console
Error: ./source/extensions/filters/network/redis_proxy/proxy_filter.h:3:10: fatal error: 'bits/types/time_t.h' file not found
Error: ERROR: /Users/runner/work/envoy/envoy/source/extensions/filters/network/redis_proxy/BUILD:120:17: Compiling source/extensions/filters/network/redis_proxy/proxy_filter.cc failed: (Exit 1): wrapped_clang_pp failed: error executing command (from target //source/extensions/filters/network/redis_proxy:proxy_filter_lib)
```
not sure why passed on linux but failed on mac m1.

**Review by phlax — APPROVED** [review]
lgtm, thanks @zirain

**Comment by phlax** [comment]
@dbarbosapn if you can suggest some tooling and we can make it work with bazel then i think that would be a great idea

this conversation has come up previously - but not sure how best to resolve - there is "include what you use" but that does something slightly different (if related)

**Pull request merged**
