### PR TITLE
backport: macOS: Allow to load .wasm on Apple silicon

### PR DESCRIPTION
**Pull request by dio**
Commit Message: This applies https://chromium-review.googlesource.com/c/v8/v8/+/3700352 as a fix for MemoryAllocator::PartialFreeMemory() which shouldn't try to change permissions of RWX pages.

This mainly affects macOS > 11.2 due to mprotect behavior changes (#23243) on Apple silicon.
    
This is cherry-picked from: https://github.com/envoyproxy/envoy/commit/63f27a6b6de0b2172f4721c31c69a050713c4c56
    
Signed-off-by: Dhi Aurrahman <dio@rockybars.com>

Risk Level: N/A
Testing: Existing
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: macOS

### CODE REVIEW

**Comment by dio** [comment]
cc. @wbpcode

**Review by RyanTheOptimist — APPROVED** [review]

**Review by wbpcode — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
