### PR TITLE
Update QUICHE from 7df7521b0 to 72ae18c47

### PR DESCRIPTION
**Pull request by birenroy**
https://github.com/google/quiche/compare/7df7521b0..72ae18c47

```
$ git log 7df7521b0..72ae18c47 --date=short --no-merges --format="%ad %al %s"

2023-12-04 quiche-dev No public description
2023-12-04 elburrito Remove the compatibility version of BlindSignAuth::GetTokens, now that Chrome is setting the ProxyLayer parameter.
2023-12-03 bnc Add more BalsaFrameTests for obs-fold and null characters.
2023-12-01 martinduke Revise interface to inform send algorithm ECN is active.
2023-12-01 birenroy Renames NoopHeaderValidator to MinimalHeaderValidator in oghttp2.
2023-12-01 birenroy Re-adds some minimal validation to NoopHeaderValidator.
2023-11-30 ericorth CONNECT-IP payload parse/serialization
2023-11-30 bnc Add test for HttpValidationPolicy::disallow_header_continuation_lines.
2023-11-30 bnc Remove BalsaVisitorInterface::OnHeader().
2023-11-29 martinduke No public description
2023-11-29 danzh Change QuicSession::PendingStreamMap from absl::flat_hash_map into quiche::QuicheLinkedHashMap(flat_hash_map with std::list) to preserve the insertion order during iteration.
```

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by RyanTheOptimist** [comment]
@birenroy looks like this is failing pretty consistently in the compile-time options build. i think it's a real failure. 
https://dev.azure.com/cncf/envoy/_build/results?buildId=157017&view=logs&jobId=9f092055-76f9-5378-8376-394fd70c1cf9&j=9f092055-76f9-5378-8376-394fd70c1cf9&t=fe966eaf-d4e8-52a3-e128-8c1ae9909be8

**Comment by birenroy** [comment]
> @birenroy looks like this is failing pretty consistently in the compile-time options build. i think it's a real failure. https://dev.azure.com/cncf/envoy/_build/results?buildId=157017&view=logs&jobId=9f092055-76f9-5378-8376-394fd70c1cf9&j=9f092055-76f9-5378-8376-394fd70c1cf9&t=fe966eaf-d4e8-52a3-e128-8c1ae9909be8

Yeah, I think the new "minimal rather than noop" validation is causing problems when UHV is enabled. I'm going to revert the upstream change and try to figure out another path forward for https://github.com/envoyproxy/envoy/pull/31086.

**Pull request closed without merging**
