### PR TITLE
quic: plumb ProcessContext reference into QUIC listener and server preferred address factory

### PR DESCRIPTION
**Pull request by danzh2010**
Commit Message: add ProcessContextOptRef into a bunch of factory interfaces.

Risk Level: low, no behavior change
Testing: existing tests passs
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]
Looks fine, but since this is unused, I'm curious what the context is?

**Comment by danzh2010** [comment]
> Looks fine, but since this is unused, I'm curious what the context is?

Our internal implementation will need this object which is also extended internally to get SPA. It is also widely used in filters as a container of global variables.

**Pull request merged**
