### PR TITLE
api_key_auth: make exception free

### PR DESCRIPTION
**Pull request by mathetake**
Commit Message: api_key_auth: make exception free
Additional Description:
Risk Level: low 
Testing: done
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by wbpcode** [comment]
duplicate to #37649

/wait

**Comment by mathetake** [comment]
lol

**Comment by mathetake** [comment]
ok which do you prefer ? you can close this or merge this up to you!

**Comment by wbpcode** [comment]
basically, we will keep the old one.

**Comment by mathetake** [comment]
ok sounds good!

**Pull request closed without merging**
