### PR TITLE
kafka: upgrade dependencies to 3.5.1

### PR DESCRIPTION
**Pull request by adamkotwasinski**
Commit Message: kafka: upgrade dependencies to 3.5.1
Additional Description: cherry-pick of https://github.com/envoyproxy/envoy/pull/28932 for envoy v1.25 (other commits were related to mesh-filter, but don't want to backport a whole feature)
Risk Level: Low
Testing: integration testing with full stack; manual testing with https://github.com/adamkotwasinski/envoy-kafka-tests/pull/9
Docs Changes: version numbers 
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by adamkotwasinski** [comment]
all right, so actually it was a very easy one - just a single PR had to be backported

**Review by phlax — APPROVED** [review]
nice, thanks @adamkotwasinski

**Pull request merged**
