### PR TITLE
mobile/android: Remove `rules_android_ndk` patch

### PR DESCRIPTION
**Pull request by phlax**
and ensure all ci is using the updated ndk

### CODE REVIEW

**Comment by phlax** [comment]
im a bit confused by this

we are definitely using the newer ndk:

```console
ANDROID_NDK_HOME=/.android/sdk/ndk/26.3.11579264
ANDROID_SDK_INSTALL_TARGET=/.android
ANDROID_HOME=/.android/sdk
ANDROID_NDK_VERSION=26.3.11579264
```

but then when removing this patch it says:

```console
-- The C compiler identification is Clang 9.0.9
```

and still fails with

```console
    ld.lld: error: unknown -z value: separate-code
```

there is a rules_android_ndk api level setting which is still set to 21 - i had come to the conclusion that it was ignored but ill try changing it

**Comment by phlax** [comment]
changing api level had no effect

checking locally and we seem to have the correct clang bin

```console
phlax@c39539a581db:/src/workspace/envoy/mobile$ $(./bazelw info output_base)/external/androidndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --version
Android (11349228, +pgo, +bolt, +lto, -mlgo, based on r487747e) clang version 17.0.2 (https://android.googlesource.com/toolchain/llvm-project d9f89f4d16663d5012e5c09495f3b30ece3d2362)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/phlax/.cache/bazel/_bazel_phlax/b33947240e660e5d2c6450ec6397a5d1/external/androidndk/toolchains/llvm/prebuilt/linux-x86_64/bin
```

really struggling to understand where clang 9.0.9 is coming from

**Comment by phlax** [comment]
argh - so the problem is that the build is non-hermetic

running locally (with same rbe) and this passes

checking the rbe cache that ci is running with, and downloading the clang bin i see

```console
$ ./clang --version
Android (7019983 based on r365631c3) clang version 9.0.9 (https://android.googlesource.com/toolchain/llvm-project a2a1e703c0edb03ba29944e529ccbf457742737b) (based on LLVM 9.0.9svn)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/phlax/dev/envoydev/envoy/.
```

not sure how to resolve that

**Comment by abeyad** [comment]
> > argh - so the problem is that the build is non-hermetic
> 
> the problem was actually that ndk gets installed another way - we need to ensure these get updated together in future

so there were two ndks being installed ?

**Review by abeyad — APPROVED** [review]
I'm not sue I understand what happened, but if this change gets it working, then that's great

**Pull request merged**
