### PR TITLE
IoUring: refactor IoSocketHandleImpl for sharing common code

### PR DESCRIPTION
**Pull request by soulxu**
Commit Message: IoUring: refactor IoSocketHandleImpl for sharing common code
Additional Description:
We will create the IoUringSocketHandleImpl, that will share some of code from IoSocketHandleImpl, so create the IoSocketHandleBaseImpl for those common code.

Risk Level: low
Testing: unittest and integration test
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a
Part of issue: https://github.com/envoyproxy/envoy/issues/28395

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
@yanavlasov friendly maintainer-on-call ping

**Comment by RyanTheOptimist** [comment]
@yanavlasov is OOO
/assign @pradeepcrao

**Comment by ravenblackx** [comment]
Ping @yanavlasov

**Comment by jmarantz** [comment]
needs main merge, but also Yan's review.

**Comment by alyssawilk** [comment]
@yanavlasov please review or comment why you are not reviewing.

**Review by yanavlasov — DISMISSED** [review]

**Comment by yanavlasov** [comment]
@soulxu sorry for the long delay, I did notice the review request. Please resolve merge conflict and I will merge right after it.

/wait

**Comment by soulxu** [comment]
@yanavlasov no worries, I've been distracted by other things in the last few weeks, just the right time to start this effort again.

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
