### PR TITLE
router: add regex substitution to header hashing

### LINKED ISSUE #11811: extend route's hashing policy to support hashing on a regex substitution
Currently, the hash policy for a route supports hashing on a header's entire value:

https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/route/v3/route_components.proto#L609

We have a use case in which we'd like to hash on a regex substitution on `:path` (e.g.: to extract a given id). 

There's two options I can think of:

1) add support for hashing on a metadata key (reusing what was added in ##11698)

2) add support for applying `type.matcher.v3.RegexMatchAndSubstitute` on a header and then hashing on that result

Any preferences/thoughts?

cc: @htuch @snowp @mattklein123

### PR DESCRIPTION
**Pull request by rgs1**
Commit Message:
Extend  hashing via header to support regex substitution.

Additional Description:
This is useful when you need to hash on a transformation
of a header value (e.g.: extract a part of `:path`).

Fixes #11811

Risk Level: low
Testing: unit test added
Docs Changes: none
Release Notes: added

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

### CODE REVIEW

**Comment by rgs1** [comment]
Hmm failure looks unrelated (on the windows build):

```
 //test/integration:cx_limit_integration_test                             FAILED in 300.7s
```

**Comment by rgs1** [comment]
Another unrelated timeout:

```
//test/integration:http2_integration_test                               TIMEOUT in 327.6s
  /build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-dbg/testlogs/test/integration/http2_integration_test/test.log
```

**Comment by dio** [comment]
re: windows: https://github.com/envoyproxy/envoy/commit/83841da7110b4ee87f78eff47c0f3555c55d1348

**Comment by dio** [comment]
re: timeout, probably this one: https://github.com/envoyproxy/envoy/pull/11842.

**Pull request merged**
