### PR TITLE
http: envoy.reloadable_features.internal_redirects_with_body deprecation

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Loong <loong.dai@intel.com>

Commit Message: http: envoy.reloadable_features.internal_redirects_with_body deprecation
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] #19506
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by daixiang0** [comment]
It is wired that x86 pass but arm fails.

**Review by alyssawilk — APPROVED** [review]
Thanks for the clean up!

**Pull request merged**
