### PR TITLE
Revert "[Envoy Mobile]Implement QUICHE_LOG with ABSL_LOG (#30160)"

### PR DESCRIPTION
**Pull request by phlax**
This reverts commit 5b4e1a6d57777836f858b377534a7ffdaa42a41a.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
fixing permafail:

```console
external/com_github_google_quiche/quiche/common/platform/api/quiche_bug_tracker.h:8:10: fatal error: 'quiche_platform_impl/quiche_bug_tracker_impl.h' file not found
#include "quiche_platform_impl/quiche_bug_tracker_impl.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //library/kotlin/io/envoyproxy/envoymobile:envoy
```

**Comment by phlax** [comment]
https://github.com/envoyproxy/envoy/actions/runs/6512770457/job/17691086927#step:5:53

**Comment by phlax** [comment]
cc @RyanTheOptimist main is permafailing currently

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
