### PR TITLE
backport 1.16: master -> main

### PR DESCRIPTION
**Pull request by Shikugawa**
Signed-off-by: Matt Klein <mklein@lyft.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by htuch** [comment]
@Shikugawa this makes sense I think for branch maintenance, is the plan to do a point release on this though? Not sure if there is any end user facing change, but I might have missed something.

**Comment by Shikugawa** [comment]
@htuch Without this patch, we will face failure to generate docs. (and releated envoyproxy org repositories that changed from master -> main) And this PR doesn't have direct effect to enduser, I think. because only to follow change.

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
