### PR TITLE
Quiche roll 20220922142546

### PR DESCRIPTION
**Pull request by danzh2010**
Update QUICHE from 3743c9285 to 2381ebbb6
    https://github.com/google/quiche/compare/3743c9285..2381ebbb6
    
    $ git log 3743c9285..2381ebbb6 --date=short --no-merges --format="%ad %al %s"
    
    2022-09-22 ianswett Deprecate --gfe2_reloadable_flag_quic_bbr2_startup_extra_acked.
    2022-09-22 ianswett Deprecate --gfe2_reloadable_flag_quic_bbr2_ignore_inflight_hi_in_probe_up.
    2022-09-22 vasilvv Remove QuicheStreamBufferAllocator platform API
    2022-09-21 quiche-dev Move QuicRandom functionality to QuicheRandom, and update `third_party/quic` ,`net/quic` to use alias `using QuicRandom = quiche::QuicheRandom;`
    2022-09-21 wub Change quic::CryptoUtils::GetSSLCapabilities to use ScopedCBB instead of CBB. This can avoid a memleak if SSL_serialize_capabilities fails.
    2022-09-21 ianswett Deprecate --gfe2_reloadable_flag_quic_bbr2_exit_startup_on_persistent_queue2.
    2022-09-20 bschneider Add equality operators for public data types in BinaryHttp*
    2022-09-19 vasilvv Fix QUICHE Bazel build.
    2022-09-19 haoyuewang Factor the header validation and response-code parsing/validation code in QuicSpdyClientStream::OnInitialHeadersComplete out such that they can be overriden in subclasses.
    2022-09-19 bschneider Add swap_body function to BinaryHttpMessage.
    2022-09-19 vasilvv Move API-only header files out of core/io into core
    2022-09-19 wub Deprecate --quic_dispatcher_send_connection_close_for_tls_alerts.
    2022-09-19 ianswett Deprecate --gfe2_reloadable_flag_quic_bbr2_startup_probe_up_loss_events.
    2022-09-19 danzh Add a transport socket config knob in quic_alia_transport_socket.proto to enable/disable early data.
    2022-09-16 kmg Add PrintTo() methods to BinaryHttpMessage and related classes
    2022-09-16 vasilvv Fix Bazel build for //quiche:quiche_core
    2022-09-15 martinduke QuicDispatcherTest uses MockConnectionIdGenerator instead of assuming connection IDs.
    2022-09-15 vasilvv Unexport //third_party/epoll_server
    2022-09-15 vasilvv Remove the leftover mentions of epoll in MASQUE class names.
    2022-09-15 vasilvv Deprecate quic_epoll API
    2022-09-14 vasilvv Move quic_epoll_* bindings into the internal part of QUIC
    2022-09-14 danzh Deprecate --gfe2_reloadable_flag_quic_not_bundle_ack_on_alternative_path
    2022-09-14 bnc Remove code to write unidirectional push stream type.
    2022-09-13 bnc Test that Http2HeaderBlock order is preserved.
    2022-09-13 vasilvv Deprecate QuicClient in favor of QuicDefaultClient.
    2022-09-13 martinduke Internal change
    2022-09-13 haoyuewang Deprecate --gfe2_reloadable_flag_quic_validate_header_field_value_at_spdy_stream.
    2022-09-13 wub Deprecate --gfe2_reloadable_flag_quic_spdy_stream_check_connected_after_process_input.
   
Risk Level: low
Testing: existing tests pass
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by alyssawilk — DISMISSED** [review]
thanks for all the clean up!

**Comment by alyssawilk** [comment]
Code coverage for source/common/quic is lower than limit of 91.6 (91.5) :-/

**Comment by danzh2010** [comment]
@wrowe mind doing a dependency pass?

**Comment by moderation** [comment]
@danzh2010 happy for @wrowe to review but I LGTM'ed the dependency check

**Comment by danzh2010** [comment]
@alyssawilk mind merging this?

**Comment by danzh2010** [comment]
> @alyssawilk mind merging this?

She is OOO... 
@RyanTheOptimist can you help here?

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
