### PR TITLE
Fix `--log-format-escaped` to only log one newline per log line

### PR DESCRIPTION
**Pull request by nareddyt**
Commit Message: Fix `--log-format-escaped` to only log one newline per log line

Additional Description:

Previously, when a log line contained multiple trailing newline characters, it would result in creating multiple empty lines in the log output. 

For example, `ENVOY_LOG(debug, "message\n message \n\n")` is translated to log line `message\n message \n\n\n`. With `--log-format-escaped` enabled, this is logged as:

```
message\n message



```

Because **all trailing whitespace characters** would not be escaped under the previous implementation. The correct behavior is for all `\n` to be escaped **except** the last one:

```
message\n message\n\n

```

Risk Level: Low

Testing: Unit tests, including platform specific ones

Docs Changes: Updated wording in flag documentation

Release Notes: `--log-format-escaped` now only logs one newline per log line

Platform Specific Features: N/A

### CODE REVIEW

**Comment by nareddyt** [comment]
cc @qiwzhang @TAOXUY

**Comment by nareddyt** [comment]
PTAL @snowp

**Comment by nareddyt** [comment]
> lgtm, can you add a note to the release notes at https://github.com/envoyproxy/envoy/blob/main/changelogs/current.yaml ?

Done

**Review by snowp — APPROVED** [review]
Thanks!

**Pull request merged**
