### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by mattklein123**
Fixes https://github.com/envoyproxy/envoy/issues/1663

### CODE REVIEW

**Comment by mattklein123** [comment]
@caniszczyk I looked and this still seems like the best way.

**Comment by mattklein123** [comment]
And ... I failed my own test. This kind of sucks for editing within the GH UI. Oh well.

**Comment by mattklein123** [comment]
And failed again

**Comment by caniszczyk** [comment]
@mattklein123 it super sucks you can't use the GitHub UI to enforce signed-off-by, so you have to use a client (been working with GitHub to enable this via their web ui but no dice yet)

**Pull request closed without merging**
