### PR TITLE
test: improving network coverage

### PR DESCRIPTION
**Pull request by alyssawilk**
Also ratcheting limits for improved areas of the code base.

Risk Level: Low (removing some unused code)
Testing: n/a
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by alyssawilk** [comment]
(unclear if this passes the bar - CI will tell)

**Comment by yanavlasov** [comment]
Looks like it croaked in the conn_manager_impl_test that I fixed. Merging main should unblock it.

**Review by yanavlasov — APPROVED** [review]
Thanks for cleaning this up.

**Comment by alyssawilk** [comment]
Ok, CI sorted, PTAL

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
