### PR TITLE
date formatter: fix/enhance the precision of date formatter

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: date formatter: fix the precision of date formatter
Additional Description:

In the previous implementation, the `DateFormatter` doesn't provide the full featured `absl::FormatTime` support. (Only seconds level precision is supported and the extended subseconds specifiers (`%E#S, %E*S, %E#f, %E*f` cannot work correctly).

This PR refactored the DateFormatter class to provide related support. 

Risk Level: mid, core class.
Testing: unit.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
Here is the benchmark results:

```
Original benchmark result:
---------------------------------------------------------------------------------------
Benchmark                                             Time             CPU   Iterations
---------------------------------------------------------------------------------------
bmAccessLogDateTimeFormatter                       39.4 ns         39.2 ns     17840213
bmDateTimeFormatterWithSubseconds                  75.1 ns         74.7 ns      9283327
bmDateTimeFormatterWithLongSubsecondsString     2734589 ns      2720562 ns          258
bmDateTimeFormatterWithoutSubseconds               64.8 ns         64.5 ns     10534870

Result of new implementation but without refactoring the regex parser. The parsing take much more time.
---------------------------------------------------------------------------------------
Benchmark                                             Time             CPU   Iterations
---------------------------------------------------------------------------------------
bmAccessLogDateTimeFormatter                       40.1 ns         40.1 ns     17165656
bmDateTimeFormatterWithSubseconds                  65.6 ns         65.5 ns     10644445
bmDateTimeFormatterWithLongSubsecondsString     3651582 ns      3624444 ns          189
bmDateTimeFormatterWithoutSubseconds               49.9 ns         49.4 ns     14084904

Final result which provide typically much better performance:
---------------------------------------------------------------------------------------
Benchmark                                             Time             CPU   Iterations
---------------------------------------------------------------------------------------
bmAccessLogDateTimeFormatter                       39.2 ns         39.2 ns     17841532
bmDateTimeFormatterWithSubseconds                  64.0 ns         63.9 ns     10826026
bmDateTimeFormatterWithLongSubsecondsString      263844 ns       263486 ns         2656
bmDateTimeFormatterWithoutSubseconds               48.0 ns         48.0 ns     14519839
```

**Comment by wbpcode** [comment]
By the way, the performance result of parsing is little scared to me. 10x speed up even we use more complex regex. May be we should replace all others std::regex to re2.

**Review by mattklein123 — CHANGES_REQUESTED** [review]
I think this should have a release note?

/wait

**Pull request merged**
