### PR TITLE
[backport/1.22] Updates and cleanups

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
i suspect that upstream is rebuilding/publishing these image even when there is no change

i will investigate further and raise a ticket if my suspicion is confirmed

**Comment by phlax** [comment]
upstream distroless issue is now resolved all updates squashed to 1

this PR is now a general branch update/cleanup PR

**Comment by phlax** [comment]
this should be good to land - i think there are no extra updates for 1.22 - ill create a release commit/PR shortly and we can publish tomorrow if there are no other issues/delays

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
