### PR TITLE
deps: Bump `rules_foreign_cc` -> 0.9.0

### LINKED ISSUE #22529: Newer release available `rules_foreign_cc`: 0.9.0 (current: 0.8.0)
Package Name: rules_foreign_cc@0.8.0
Current Version: 0.8.0@2022-04-18
Available Version: 0.9.0@2022-08-02
Upstream releases: https://github.com/bazelbuild/rules_foreign_cc/releases

### PR DESCRIPTION
**Pull request by phlax**
Fix #22529 

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
failing with:

```console

ragel/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
make: *** [Makefile:343: /b/f/w/external/net_colm_open_source_ragel/Makefile.in] Error 1

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=114223&view=logs&j=b7634614-24f3-5416-e791-4f3affaaed6c&t=21e6aa7d-f369-5abd-5e4e-e888cac18e9c&l=231

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by RyanTheOptimist** [comment]
I somehow missed this PR. Sorry for the delay. I think you'll need an admin to merge it though, since clang-tidy is failing.

**Comment by RyanTheOptimist** [comment]
@mattklein123 do you have the super powers to merge this? (or feedback that we should do something to avoid needing a force merge?)

**Comment by mattklein123** [comment]
Are we sure this isn't going to perma fail clang-tidy? I don't quite understand what is going on here. cc @keith 

/wait-any

**Comment by phlax** [comment]
i think the failure is genuine - best not to merge until we have figured out what is going on

**Comment by keith** [comment]
it looks to me like this log might be omitting the actual failure, does it repro locally?

**Comment by phlax** [comment]
> does it repro locally?

not sure, i didnt try

**Pull request closed without merging**
