### PR TITLE
[WIP] deps: Bump `com_github_msgpack_msgpack_c` -> 4.0.2

### LINKED ISSUE #18328: Newer release available com_github_msgpack_msgpack_c: c-4.0.0
*WARNING* com_github_msgpack_msgpack_c has a newer release than cpp-3.3.0@<2020-06-05 08:04:41>:c-4.0.0@<2021-09-01 02:10:58>

### LINKED ISSUE #18735: Newer release available `com_github_msgpack_msgpack_c`: cpp-4.0.3 (current: cpp-3.3.0)
Package Name: com_github_msgpack_msgpack_c
Current Version: cpp-3.3.0@2020-06-05 08:09:14
Available Version: cpp-4.0.3@2021-10-23 04:53:46
Upstream releases: https://github.com/msgpack/msgpack-c/releases

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: deps: Bump `com_github_msgpack_msgpack_c` -> 4.0.2
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #18735
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
fails on (at least) arm with

```
external/com_github_msgpack_msgpack_c/include/msgpack/sysdep.hpp:98:10: fatal error: 'boost/predef/other/endian.h' file not found
#include <boost/predef/other/endian.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=90860&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=1fb0b72f-6293-562d-a4d1-bb649223eaca&l=243

**Comment by moderation** [comment]
My understanding is that `msgpack` is Datadog only. My take on this is that the Datadog folks should likely manage this dep. It only goes stale for them.

**Comment by moderation** [comment]
OpenTracing is deprecated and about to be removed from the CNCF as a project. 

https://github.com/envoyproxy/envoy/issues/9958

**Comment by phlax** [comment]
@cgilmour the lightstep tracer has been removed in favour of using opentelemetry

any update on the datadog side?

im guessing our plan is to remove the opentracing code once we have no extensions that depend on it

cc @moderation

**Comment by moderation** [comment]
Now that the Otel tracer has [landed](https://github.com/envoyproxy/envoy/pull/20281), we have deprecated Lightstep. As per the issue @phlax [linked](https://github.com/envoyproxy/envoy/issues/21083) to I believe the agreement was that the unmaintained Datadog tracer can now be removed.  This would remove the following dependencies

```
    com_github_datadog_dd_opentracing_cpp = dict(
        project_name = "Datadog OpenTracing C++ Client",
        project_desc = "Datadog OpenTracing C++ Client",
        project_url = "https://github.com/DataDog/dd-opentracing-cpp",
        version = "1.2.1",
        sha256 = "ae44699e4aa2d21b70ed897a6c0cf3ed7dfb411e1aae4e686e39af75cec7c9bf",
        strip_prefix = "dd-opentracing-cpp-{version}",
        urls = ["https://github.com/DataDog/dd-opentracing-cpp/archive/v{version}.tar.gz"],
        use_category = ["observability_ext"],
        extensions = ["envoy.tracers.datadog"],
        release_date = "2021-01-27",
        cpe = "N/A",
    ),

    com_github_msgpack_msgpack_c = dict(
        project_name = "msgpack for C/C++",
        project_desc = "MessagePack is an efficient binary serialization format",
        project_url = "https://github.com/msgpack/msgpack-c",
        version = "4.0.3",
        sha256 = "9b3c1803b9855b7b023d7f181f66ebb0d6941275ba41d692037e0aa27736443f",
        strip_prefix = "msgpack-{version}",
        urls = ["https://github.com/msgpack/msgpack-c/releases/download/cpp-{version}/msgpack-{version}.tar.gz"],
        use_category = ["observability_ext"],
        extensions = ["envoy.tracers.datadog"],
        release_date = "2021-10-23",
        cpe = "N/A",
    ),
```

**Pull request closed without merging**
