### PR TITLE
[ci] limit number of codeql targets conservatively to 3

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Builds have been running out of space on the github action runners.

### CODE REVIEW

**Review by ggreenway — DISMISSED** [review]

**Review by alyssawilk — APPROVED** [review]
Pending CI :-)

Though I'm not sure if this runs if there's not code changes, not sure if it's worth faking one?

**Comment by asraa** [comment]
Yes, good question, this will pass. I can patch in your failing run, that would be a better test of CI!

**Comment by asraa** [comment]
Temporary test patch added, when codeQL job succeeds, I will remove.

**Comment by asraa** [comment]
Build succeeded, reverted test. Good for approval now!

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
