### PR TITLE
[docs] Remove outdated statements

### PR DESCRIPTION
**Pull request by derekargueta**
Description: v1 has been deprecated, remove statements about API methods being "optional until v1 is deprecated". Somewhat related to #2832.
Risk Level: none
Testing: N/A
Docs Changes: included
Release Notes: N/A

Signed-off-by: Derek Argueta <dereka@pinterest.com>

### CODE REVIEW

**Comment by zuercher** [comment]
There's one more function marked "compulsory when v1 is deprecated" in that file (for `createEmptyConfigProto`).

That said, I think the way these methods actually become compulsory is to remove their default implementations (such that it becomes a compile error not to implement them in subclasses). I'm not sure if all the current filter factories would pass in that case, however.

@htuch are we ready to start requiring these functions to be implemented or is there another step that needs to happen first?

**Comment by derekargueta** [comment]
@zuercher agreed about true compulsory would be removing the default implementations. Looks like `NamedListenerFilterConfigFactory::createEmptyConfigProto` is already `PURE` so it's at least safe to call that one compulsory.

For the others, I believe the only thing that would prevent us from removing the default implementation for now is testing code that still uses the v1 API. For production filters, I think it's safe to call v2 "compulsory" since
1) production Envoys don't use v1 APIs for the actual runtime
2) If a factory subclassing `NamedHttpFilterConfigFactory` or `NamedNetworkFilterConfigFactory` doesn't implement the `createEmptyConfigProto` methods (which will return `nullptr` by default), [this release assert](https://github.com/envoyproxy/envoy/blob/master/source/common/config/utility.h#L269) gets triggered when using the v2 API (the only version supported for running Envoy).

So they currently are "compulsory" in a way for actually running Envoy, but not for unit tests (yet). For example, when updating the listener manager impl tests, I had to [implement those methods](https://github.com/envoyproxy/envoy/commit/56f2f0d0161051a0b0eea1e1bad355a4668f1930#diff-e4b04f081bfb18c8fff03e7497bca901R468) to move those tests to v2 (here).

**Comment by htuch** [comment]
I agree, we should make these compulsory. The question is what is a sensible implementation for filters that don't require any configuration? It could just be `google.protobuf.Empty`. Maybe this should be the default?

I actually had an idea while looking at this and thinking about https://github.com/envoyproxy/envoy/issues/6271. We could avoid having filters explicitly provide their semantic release version if they couple it with their config protobuf type URL. There are pros/cons here, but this was a useful remind that this is possible.

**Comment by derekargueta** [comment]
I removed the default implementation for all these methods, making them `PURE`, and so far all builds are working fine. so far tested:
```
bazel build //source/exe:envoy-static
bazel test //test/common/...
bazel test //test/server/...
```


> _It could just be google.protobuf.Empty. Maybe this should be the default?_

Yeah that seems the default practice right now, i.e. in `EmptyHttpFilterConfig`
https://github.com/envoyproxy/envoy/blob/698009170e362f9ca0594f2b1927fbbee199bf98/source/extensions/filters/http/common/empty_http_filter_config.h#L37

**Comment by zuercher** [comment]
So sounds like remove the default, aborting implementations of the `createFilterFactoryFromProto` methods and change the `createEmptyConfigProto` methods to return an empty config message.

**Pull request closed without merging**
