### PR TITLE
ci: refactor docker ci script and enable docker job in presubmit

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Comment by jmarantz** [comment]
@lizan I'm not sure who best to assign this to; do you want to pick someone yourself after CI is clean?

**Comment by lizan** [comment]
@htuch can you take a look? I refactored docker CI script and the VRP image build.

**Comment by htuch** [comment]
@lizan have you tested the VRP build by following the VRP instructions (including the ones for local rebuild)?

**Comment by lizan** [comment]
@htuch yes I tried `ci/docker_rebuild_google-vrp.sh` and `ci/docker_rebuild_google-vrp.sh <path_to_binary>` locally

**Pull request merged**
