### PR TITLE
http2: removes the CallbackVisitor deprecation runtime guard and related code

### PR DESCRIPTION
**Pull request by birenroy**
This simplifies the HTTP/2 codec interaction, and should make it easier to reason about the code.

Commit Message: http2: removes the CallbackVisitor deprecation runtime guard and related code
Additional Description:
Risk Level:
Testing: ran unit and integration tests locally
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Review by RyanTheOptimist — DISMISSED** [review]
NICE!

**Review by diannahu — APPROVED** [review]
Glorious red!

**Comment by birenroy** [comment]
I think this one is ready to merge.

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
