### PR TITLE
config: reinstate #8478 (unification of delta and SotW xDS), reverted by #8939

### PR DESCRIPTION
**Pull request by fredlas**
Delta and state-of-the-world gRPC xDS now share the same GrpcMux and
Subscription implementations. These are the implementations added in #7293 for
delta. These implementations are a rewrite/extensive refactoring of the old
GrpcMuxImpl (deleted by this PR) and associated logic.

Risk Level: high (rewrite/large refactor of gRPC xDS)
Testing: added sotw_subscription_state_test, added regression test for #8927

### CODE REVIEW

**Comment by fredlas** [comment]
There was a minor merge conflict with #8886 to resolve. While doing that I noticed that some comments in new_grpc_mux_impl.cc wrongly referred to "DeltaDiscoveryRequest" when they should say a generic "discovery request". I can undo that if you'd prefer it to be a pure revert revert. Other than the new_grpc_mux_impl.cc cleanup and the WellKnownGrpcStatus merge, this should be identical to #8478.

**Comment by mattklein123** [comment]
@fredlas can you check CI?

@kyessenov once we get CI passing do you mind giving this branch a quick smoke test however you tested master last time? Thank you.

/wait

**Comment by kyessenov** [comment]
Sure, waiting for the CI to pass.

**Comment by fredlas** [comment]
Done, updated some more GrpcStatuses. I'm also seeing that any _speed_test test is failing to build, due to a problem when trying to link with libpthread. I'm not sure if that's a newly uncovered quirk with just my own machine's environment, or a recently introduced actual breakage that hasn't yet been caught and fixed, but it's hard to imagine something in these changes causing it (and not causing it before). I guess we'll see once the tests get there.

**Comment by mattklein123** [comment]
@kyessenov looks good for a quick smoke test. Thank you! cc @wgallagher 

/wait-any

**Comment by kyessenov** [comment]
I ran go-control-plane CI test, and it passes fine now. Thanks.

**Comment by fredlas** [comment]
Awesome, thanks. I'm relieved it got back in so quickly!

**Comment by rgs1** [comment]
@fredlas @mattklein123 hmm so apparently this change causes some of our instances to get stuck on startup -- unclear if it's CDS or SDS or something in XDS but something with XDS broke which prevents some of our binary/config configurations to start... Any ideas before I start carefully reading this PR?

cc: @fishcakez

**Comment by mattklein123** [comment]
@rgs1 if it's causing issues we will revert again, though a bit of debugging would be nice. Can you get any more info?

**Comment by rgs1** [comment]
@mattklein123 yeah, any ideas on what info would be useful?

**Comment by mattklein123** [comment]
Logs? Which xDS? Etc.? If you can reliably reproduce any/all info would be helpful.

**Comment by rgs1** [comment]
It might have to wait until later/Mon; do if it already caused issues a
revert might be appreciated so that we can fetch some other stuff from
master. Thanks!

**Comment by mattklein123** [comment]
Are you positive that if you revert the change the problem goes away?

**Comment by rgs1** [comment]
Positive -- tho honestly it's probably fine to wait until EOD Monday to
revert if we can't figure it out.

**Comment by mattklein123** [comment]
OK I think we should probably go ahead and start the revert to get master into a clean state and then we can debug in parallel, but I don't feel that strongly about it.

**Comment by mattklein123** [comment]
I opened https://github.com/envoyproxy/envoy/pull/9044 and we can decide on Monday whether to merge or not.

**Pull request merged**
