### PR TITLE
docs: cleanup for 1.11 release

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: n/a
Testing: n/a
Docs Changes: relnote cleanup
Release Notes: n/a

### CODE REVIEW

**Comment by moderation** [comment]
Skipping 1.11?

**Comment by alyssawilk** [comment]
er, for cutting over to 1.11 and starting 1.12, good catch :-)

**Comment by alyssawilk** [comment]
@envoyproxy/maintainers what'd I miss?

**Comment by alyssawilk** [comment]
For easy access: https://246398-65214191-gh.circle-artifacts.com/0/source/generated/docs/intro/version_history.html

**Comment by junr03** [comment]
@alyssawilk thanks for updating. I forgot to ask for notes on this PR's features https://github.com/envoyproxy/envoy/pull/7244. lmk if you can add them here.

**Comment by junr03** [comment]
Thanks!!!

**Pull request merged**
