### PR TITLE
formatter: templated formatter support

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: formatter: templated formatter support
Additional Description:

Continuous work of #28836. Prework to support cross-protocols access log support. (See #6138
 #13085
 #17898
 #18083 #28773)

This is a huge and very dirty PR. And I know it would be pretty hard to review this work. So, any suggesions to this work to make it more clear or easy to review would be welcome.

This PR main include following changes:
1. Make most classes/functions of formatter to be template classes or template functions. Template type parameter `FormatterContext` is used to represent the necessary context for the formatting. Different protocols or modules could define `FormatterContext` by themselves and they will have different built-in command parsers.
2. Use `HttpFormatterContext` to supplies request headers, response headers, response trailters, etc for the HTTP formatter.

Risk Level: mid.
Testing: n/a. No new logic and all exist tests should ensure all logic is same with previous implementation.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
All tests should be green now. CI is flaky because https://github.com/buchgr/bazel-remote/issues/688.

**Comment by wbpcode** [comment]
Anyway, it's ready for a formal review.

**Comment by wbpcode** [comment]
I just reviewed this PR by myself. It's pretty complex. Should I split this PR to more fine-grained sub PRs? But I am afraid the splited PRs will lost the complete view. 🤔 cc @mattklein123

**Comment by wbpcode** [comment]
Then splitting would be better. Maybe this PR is nightmare for anyone.

**Comment by RyanTheOptimist** [comment]
Looks like this needs a main merge now that #29201 has landed.

**Comment by wbpcode** [comment]
This PR is unnecessary now because #29210 has completed the templated formatter support.
The HTTP specialization reduced lots of code changes. By that way, the templated formatter support needn't bulk of change that we did in this PR.

**Pull request closed without merging**
