### PR TITLE
stats: remove symbol table interface file and rename files to be consistent

### PR DESCRIPTION
**Pull request by jmarantz**
Commit Message: follow-up to #19597 -- removes trivial forward decls from envoy/stats/symbol_table.h and renames all the files to reflect this is no longer an interface/impl pattern but a single implementation.

This PR has a lot of files but all the changes are renames of includes except for the removal of envoy/stats/symbol_table.h and the moving of its forward decls into envoy/stats/stats.h.
Additional Description:
Risk Level: llw
Testing: //test/...
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by jmarantz** [comment]
Hi @zuercher this is the follow-up to the PR you reviewed earlier, cleaning up filenames and removing the extinct interface file.

It's large but really mostly simple renames.

**Review by zuercher — APPROVED** [review]
Looks good!

**Comment by jmarantz** [comment]
Thanks Stephan!

**Pull request merged**
