### PR TITLE
deps: Bump `com_google_protobuf` -> 21.12

### LINKED ISSUE #24545: Newer release available `com_google_protobuf`: v21.12 (current: v21.7)
Package Name: com_google_protobuf@21.7
Current Version: v21.7@2022-09-29
Available Version: v21.12@2022-12-14
Upstream releases: https://github.com/protocolbuffers/protobuf/releases

### PR DESCRIPTION
**Pull request by phlax**
Fix #24545 

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
this is erroring with 

```console
ERROR: /source/source/server/BUILD:366:17: in cc_library rule //source/server:listener_manager_factory_lib: cycle in dependency graph:
    //test/common/grpc:grpc_client_integration_test (11e54ce379ae2a67bd855aff3054e8d311f377cde4ff2906a48234289f2d7e80)
    //test/common/grpc:grpc_client_integration_test_harness_lib (0af61cb2b306101c5e77f0ea15429ff702242e7cee777dd2423044c6b2bc36f9)
    //test/integration:integration_lib (0af61cb2b306101c5e77f0ea15429ff702242e7cee777dd2423044c6b2bc36f9)
    //source/server:server_lib (0af61cb2b306101c5e77f0ea15429ff702242e7cee777dd2423044c6b2bc36f9)
    //source/server/admin:admin_lib (0af61cb2b306101c5e77f0ea15429ff702242e7cee777dd2423044c6b2bc36f9)
    //source/server/admin:admin_lib_internal (0af61cb2b306101c5e77f0ea15429ff702242e7cee777dd2423044c6b2bc36f9)
    //source/extensions/listener_managers/listener_manager:listener_manager_lib (0af61cb2b306101c5e77f0ea15429ff702242e7cee777dd2423044c6b2bc36f9)
    //source/extensions/listener_managers/listener_manager:active_raw_udp_listener_config (0af61cb2b306101c5e77f0ea15429ff702242e7cee777dd2423044c6b2bc36f9)
    //source/extensions/listener_managers/listener_manager:connection_handler_lib (0af61cb2b306101c5e77f0ea15429ff702242e7cee777dd2423044c6b2bc36f9)
.-> //source/server:listener_manager_factory_lib (0af61cb2b306101c5e77f0ea15429ff702242e7cee777dd2423044c6b2bc36f9)
|   //source/server:worker_lib (0af61cb2b306101c5e77f0ea15429ff702242e7cee777dd2423044c6b2bc36f9)
`-- //source/server:listener_manager_factory_lib (0af61cb2b306101c5e77f0ea15429ff702242e7cee777dd2423044c6b2bc36f9)
```

probably just needs a dep removing somewhere i reckon

**Comment by phlax** [comment]
seems error is unrelated - `main` is broke

**Review by wrowe — APPROVED** [review]
LGTM, pending CI success

**Pull request merged**
