### PR TITLE
skywalking: simplify span interface

### PR DESCRIPTION
**Pull request by Shikugawa**
Signed-off-by: Shikugawa <rei@tetrate.io>

Commit Message: skywalking: simplify span interface
Additional Description:
Risk Level: Low
Testing: N/A
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by Shikugawa** [comment]
cc @wbpcode

**Review by daixiang0 — APPROVED** [review]
Codes looks good to me.

**Review by wbpcode — APPROVED** [review]
Thanks for this cleanup. It make sense. cc @lizan for final pass.

**Comment by phlax** [comment]
@wbpcode @lizan can we land this ?

**Pull request merged**
