### PR TITLE
[backport/1.21] deps: Bump `kafka_source` -> 3.3.1

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by RyanTheOptimist — COMMENTED** [review]
This looks reasonable, but the deps check is failing. Is that problematic?

**Comment by phlax** [comment]
> This looks reasonable, but the deps check is failing. Is that problematic?

not sure - its for api deps which this doesnt touch so seems like a flake - i just kicked it

**Comment by adamkotwasinski** [comment]
LGTM from Kafka side but there's something _weird_ coming from precheck dependencies build ... and I can't even tell what it wants?
```
2022-11-08T17:02:20.6225561Z [31mAn error occurred while processing ./api/bazel/repository_locations.bzl, please verify the correctness of the metadata: Mismatch with metadata release date of 2020-07-21[0m
2022-11-08T17:02:20.7425827Z ##[error]Bash exited with code '1'.
```

**Comment by adamkotwasinski** [comment]
Looks like we need to backport everything that happened in the meantime:
#19967 , #20006 , #21411 , #21414 , #23311 , #23354 

found by comparing `git log envoy/main  --oneline | grep kafka` vs `git log v1.21.0 --oneline | grep kafka`

**Comment by phlax** [comment]
brilliant! that worked - thanks for your help @adamkotwasinski - really appreciated

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
