### PR TITLE
[safe_memcpy_test] Explicit type for arguments of the vector constructor

### PR DESCRIPTION
**Pull request by rialg**
Signed-off-by: rialg <grial@google.com>

Commit Message: Explicit type for arguments of the vector constructor
Additional Description: Issue #16542 
Risk Level: N/A

### CODE REVIEW

**Comment by rialg** [comment]
Please, @jmarantz and @antoniovicente ,  could you add yourselves as reviewers?

**Review by jmarantz — APPROVED** [review]
thanks!

**Comment by antoniovicente** [comment]
Change looks good, but it would be good to hear from @Wyverald on wherever or not this fixes the issue he saw in the bazel build and how to repo that breakage.

**Comment by Wyverald** [comment]
Thanks for the PR. Unfortunately there isn't an easy way to do a test CI run on a PR (unless we turn the pipeline on for all future Envoy PRs -- which we could certainly do). Is there a way to push this PR to a branch in the main Envoy repo (envoyproxy/envoy)? That would give us a way to test beforehand if this fixes it.

**Comment by rialg** [comment]
The presubmit pipeline failed due to low code coverage in the tests.

```
Code coverage for source/common/quic is lower than limit of 88.4 (88.3)
```

Should we lower this target to match the current value?

**Comment by jmarantz** [comment]
I think once https://github.com/envoyproxy/envoy/pull/16570 merges you should be good? @alyssawilk has another PR also which might just improve the coverage.

**Comment by jmarantz** [comment]
go ahead an 'merge main' and this coverage issue should be resolved.

**Comment by antoniovicente** [comment]
> Thanks for the PR. Unfortunately there isn't an easy way to do a test CI run on a PR (unless we turn the pipeline on for all future Envoy PRs -- which we could certainly do). Is there a way to push this PR to a branch in the main Envoy repo (envoyproxy/envoy)? That would give us a way to test beforehand if this fixes it.

ok, we'll give it another shot if this change isn't sufficient.

**Pull request merged**
