### PR TITLE
mobile: Remove #ifdef ENVOY_ENABLE_QUIC

### PR DESCRIPTION
**Pull request by fredyw**
This PR enables Envoy Mobile to always have HTTP/3 support.

Risk Level: low
Testing: CI
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: mobile

### CODE REVIEW

**Comment by abeyad** [comment]
QUICHE is always linked into the binary now right?  In which case, this is a great cleanup.

**Comment by fredyw** [comment]
> QUICHE is always linked into the binary now right? In which case, this is a great cleanup.

Yup.

**Review by abeyad — APPROVED** [review]

**Pull request merged**
