### PR TITLE
backport to 1.16: aggregate cluster: fix TLS init issue

### PR DESCRIPTION
**Pull request by tbarrella**
Commit Message:

backport to 1.16: aggregate cluster: fix TLS init issue

Signed-off-by: Taylor Barrella <tabarr@google.com>

Additional Description: Based on #14388
Risk Level: Low
Testing: Build and run the repro from #14119 without crashing, `bazel test test/extensions/clusters/aggregate:cluster_test`
Docs Changes: N/A
Release Notes:
#14119

### CODE REVIEW

**Comment by lizan** [comment]
@tbarrella can you take the config from #14119 and make it to an integration test? That PR should go to master though.

**Comment by tbarrella** [comment]
I see why that would be useful, although should that block fixing this? In particular, I'm about to take a break for the rest of the year so I wouldn't likely have that done soon

**Review by lizan — APPROVED** [review]
No that isn't a requirement for this, as I said that should go to master branch.

**Comment by tbarrella** [comment]
I don't think the test failure is real (see #14047)

Would #14046 need to be backported and merged into this before this can be merged?

**Comment by lizan** [comment]
No we don't need #14046, can you fix the conflict then I can merge?

**Comment by tbarrella** [comment]
Ok cool, fixed

**Comment by tbarrella** [comment]
This macos test is failing when installing dependencies, and it was passing after the previous commit, so I don't think it's related to this PR (I also noticed that it failed in another 1.16 backport PR)

@lizan is it ok for this to be merged?

**Pull request merged**
