### PR TITLE
quiche: patch for MacOS build

### PR DESCRIPTION
**Pull request by junr03**
Signed-off-by: Jose Nino <jnino@lyft.com>

### CODE REVIEW

**Comment by junr03** [comment]
@RyanTheOptimist @htuch I found this type constraint error when updating Envoy in Envoy Mobile. I'll work on a quiche upstream patch to remove the local patch here. However, for the time being it would be nice to patch locally in order to unblock bringing Envoy into Envoy Mobile.

**Review by RyanTheOptimist — APPROVED** [review]
LGTM

@birenroy can you backport this fix? I wonder if we're building this on chromium, which also has a mac OS build

**Comment by junr03** [comment]
> I'll work on a quiche upstream patch to remove the local patch here

Awesome @RyanTheOptimist if @birenroy can help us with that I will sight tight :)

**Comment by RyanTheOptimist** [comment]
> > I'll work on a quiche upstream patch to remove the local patch here
> 
> Awesome @RyanTheOptimist if @birenroy can help us with that I will sight tight :)

Yeah, the actual source of truth for quiche is a google-internal repo so a Googler will have to land the fix at the end of the day. Hopefully one day we'll move to an open-source-first model for quiche!

**Pull request merged**
