### PR TITLE
kafka: add librdkafka dependency, provide upstream kafka client imple…

### PR DESCRIPTION
**Pull request by adamkotwasinski**
Commit Message: kafka: add librdkafka dependency, provide upstream kafka client implementation for mesh filter
Additional Description:
* add librdkafka dependency
* use librdkafka's producer to send records received by mesh filter
* keep one librdkafka producer per Envoy-worker-thread * upstream-kafka-cluster pair (so adding more worker threads on Envoy gives us more capacity)

Risk Level: Low
Testing: unit tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by adamkotwasinski** [comment]
replicated on my ubuntu 21.04:
```
ar rcsrcsD librdkafka++.a RdKafka.o ConfImpl.o HandleImpl.o ConsumerImpl.o ProducerImpl.o KafkaConsumerImpl.o TopicImpl.o TopicPartitionImpl.o MessageImpl.o HeadersImpl.o QueueImpl.o MetadataImpl.o
ar: two different operation options specified
```

**Comment by adamkotwasinski** [comment]
Managed to get librdkafka compiled without needing a patch. Let's wait until tests pass.

/wait-any

**Comment by adamkotwasinski** [comment]
All green.

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
