### PR TITLE
Reclaim one byte from HeaderString

### PR DESCRIPTION
**Pull request by dnoe**
Description:

With conversion to `getStringView()` access there is no longer any need to reserve a NUL byte at the end of the HeaderString since all accesses will be through string_views which are not required to be NUL terminated.

Ran `bazel test -c opt //test/... --config=asan --runs_per_test=10` without issue. There is some risk that someone has or will abuse the data() accessor on a string_view assuming it is NUL terminated. A comment is added to emphasize that the `HeaderString::getStringView()` is not NUL terminated.

By eliminating this wasted byte it is more likely that a HeaderString will fit into the existing embedded space, hopefully giving a small performance gain and reduction in memory allocations.

The original version of this PR caused a fuzz test issue due to missing one of the NUL clobbers as a result of searching for `\0` and not `0`. This issue is resolved in this PR. Additional test coverage added in this PR manually looks for the clobber and verifies it does not happen.

Header map fuzz test improvements made as part of this PR:

It is invariant that the input into the headermap code should not contain certain reserved characters, and this is enforced by assertion. The fuzzer would frequently hang up on these and just fail the valid()
check, often just when constructing a LowerCaseString before doing anything interesting.

To get past this, filter the reserved characters to spaces. The fuzzer ran for 30 minutes with this change.

Additionally, in the valid() routine, instead of scanning a header string once for each of the invalid characters (three) scan the header string once and use a switch statement to find invalid characters.

This seems to have improved the fuzz test executions per second somewhat, and will likely improve performance of binaries with asserts turned on marginally since most headers are more than three characters.

Signed-off-by: Dan Noé dpn@google.com

Risk Level: High
Testing: `bazel test -c opt //test/... --config=asan --runs_per_test=10`, manual oss-fuzz runs, added additional unit tests
Docs Changes: None
Release Notes: None
Part of: Issue #6580

### CODE REVIEW

**Comment by dnoe** [comment]
Let's review the heck out of this :)

**Comment by dnoe** [comment]
Investigating ASAN, though I doubt a failure of `//test/common/common:mutex_tracer_test` is related to this change .

**Comment by lizan** [comment]
That one seems unrelated to this PR but seems a flakiness from #6858, @htuch?
https://216013-65214191-gh.circle-artifacts.com/0/failed-testlogs/test/common/common/mutex_tracer_test/test.log

/retest

**Comment by dnoe** [comment]
Yes, I am cleaning up some of that `header_map_impl_fuzz_test` tech debt to get better coverage and get some more confidence first, let's wait on merging this PR until I report success with that. Right now it hangs up a lot of the time on the `valid()` assertion before getting anywhere useful. Corpus entry for the fuzz case that prompted the original PR revert was already added by @htuch.

**Comment by dnoe** [comment]
These changes to the fuzz test brought it from running for less than a second before choking on a `valid()` assertion to running for over an hour without finding anything.

**Comment by htuch** [comment]
FWIW, almost all our fuzzers are now stuck on the `valid()` assert according to oss-fuzz stats. We will probably address this more generally in the coming weeks.

**Pull request merged**
