### PR TITLE
[mobile]remove Java and GMScore impl from Cronvoy

### PR DESCRIPTION
**Pull request by RenjieTang**
Commit Message: remove Java and GMScore impl from Cronvoy
Additional Description: 
This change removes all the unnecessary Cronet implementations and only keeps the native Envoy Mobile one. 
Note that the other impls are never used.
This change should make Cronvoy a lot more simpler and should marginally reduce the binary size.
Risk Level: Low
Testing: Existing test
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: Android change only

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
I think this failure is real:

https://github.com/envoyproxy/envoy/actions/runs/4825808913/jobs/8597030720?pr=27039

```
test/java/org/chromium/net/testing/CronetTestRuleTest.java:68: error: cannot find symbol
    assertFalse(mTestRule.testingJavaImpl());
                         ^
  symbol:   method testingJavaImpl()
  location: variable mTestRule of type CronetTestRule
```

**Comment by adisuissa** [comment]
Assigning Ryan for triaging
/assign @RyanTheOptimist

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
