### PR TITLE
[bp/1.25] Backport stack

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by htuch** [comment]
@phlax how come we are backporting non-critical dependency changes?

**Comment by phlax** [comment]
> how come we are backporting non-critical dependency changes?

there are a few deps that are in the intersection of a) deps that issue CVEs, and b) deps that we have correctly configured to track - wasm/rust/kafka in particular

historically we have had to update/backport these deps in response to the CVEs, so now i just always backport them

**Review by htuch — DISMISSED** [review]
Ack, thanks.

**Comment by phlax** [comment]
landing to fix branch

**Pull request merged**
