### PR TITLE
Fix Envoy code format

### PR DESCRIPTION
**Pull request by RenjieTang**
Commit Message: PR is generated by running tools/code_format/check_format.py fix.
Additional Description: n/a
Risk Level: n/a
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by phlax** [comment]
@RenjieTang wondering why Envoy `main` is not picking these up, and whether this could be related to versions as this has come up before

**Comment by RenjieTang** [comment]
> @RenjieTang wondering why Envoy `main` is not picking these up, and whether this could be related to versions as this has come up before

I suspect that the CI and the local code_format tool are running different versions. This PR actually [failed](https://dev.azure.com/cncf/envoy/_build/results?buildId=147623&view=logs&j=c7de00aa-b0fb-52ba-707b-da6afd918eda&t=294dc2ce-3369-5e4f-90de-3ad0f72952a1) the CI format check. Not sure which one is correct.

**Comment by phlax** [comment]
iiuc this PR isnt requried and your local versions are producing this change

**Comment by RenjieTang** [comment]
> iiuc this PR isnt requried and your local versions are producing this change
> 
> (relatedly i really want to make this tooling hermetic so not dependent on host/local versions)

Agreed. I'd really hope that the check_format.py does the right job though. Otherwise a developer needs to wait for the CI failure message and then correct their format.

**Pull request closed without merging**
