### PR TITLE
build: Update bazel to 3.0.0

### PR DESCRIPTION
**Pull request by keith**
Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Comment by keith** [comment]
I don't expect many differences here, we'll see if CI agrees

**Comment by lizan** [comment]
@keith there's a bunch of issues says it will break though:

https://github.com/envoyproxy/envoy/issues?q=is%3Aopen+label%3Aarea%2Fbuild+label%3A%22no+stalebot%22

**Comment by lizan** [comment]
Also this need https://github.com/envoyproxy/envoy-build-tools/pull/42

**Comment by keith** [comment]
Ah interesting

**Comment by lizan** [comment]
If we're going to have release this week, then let's not merge this until then. cc @mattklein123

**Pull request closed without merging**
