### PR TITLE
Unrevert streaming shadows

### PR DESCRIPTION
**Pull request by paul-r-gall**
Commit Message: Revert the reversion of shadow streaming.
Additional Description: Shadow streaming was implemented in #24365, and rolled back in #25184 due to a bad interaction with retry buffering. This fixes the retry issue.
Risk Level: See #24365 
Testing: Regression test for the issue added.

### CODE REVIEW

**Comment by paul-r-gall** [comment]
@snowp can you review this?

**Review by jpsim — APPROVED** [review]
+1 I've confirmed this fixes the Envoy Mobile regressions we encountered in Lyft's iOS apps

**Comment by paul-r-gall** [comment]
I believe that the failure is due to an actual bug in the way QUIC downstreams interact with filters that add bodies to header-only requests.

**Comment by paul-r-gall** [comment]
Turns out I just didn't understand how QUIC works :)

**Review by alyssawilk — APPROVED** [review]
Looks like this largely boils down to https://github.com/envoyproxy/envoy/pull/25207/commits/86d5410f527a49a9aa672846aa4a4e39067be985 reverting an ordering change I'd missed.  Good find and thanks for the help reproducing, @jpsim !

**Review by snowp — APPROVED** [review]
Thanks!

**Pull request merged**
