### PR TITLE
docs: Move version history to top level out of intro

### PR DESCRIPTION
**Pull request by ggreenway**
Additionally, split the history for each version into its own file
and combine it with deprecations.

Signed-off-by: Greg Greenway <ggreenway@apple.com>

Risk Level: docs-only

### CODE REVIEW

**Comment by ggreenway** [comment]
@mattklein123 This mostly-works, but the `check_format_test` fails because it does a `chdir` for part of it and that means `check_format` can't find `VERSION` anymore. But I wasn't thrilled with looking up `VERSION` anyways. Think the latest one should always be named `current.rst` or somthing, and renamed as part of the release process? 

cc @envoyproxy/maintainers

**Comment by alyssawilk** [comment]
+1 to having the latest at latest or current or something, and moving it as part of the release process.  
I think that'll also fix the problem of having to ping everyone when we cut a release to move their release note to the current section of the doc, or the new doc - if we move current to 1.xx.0 and create a new current.md, anyone editing the old file will get warned of their merge conflict.

**Comment by mattklein123** [comment]
Thanks +1 this is great. Can you merge master and we can get this in before there are more merge conflicts?

/wait

**Comment by ggreenway** [comment]
@mattklein123 Merged master; I think we can merge this as soon as check_format and docs CI finish.

**Pull request merged**
