### PR TITLE
deps/cel: Resolve compiler warnings

### PR DESCRIPTION
**Pull request by phlax**

### CODE REVIEW

**Comment by phlax** [comment]
cc @kyessenov

**Comment by moderation** [comment]
/lgtm deps

Needs review from CEL [codeowners](https://github.com/envoyproxy/envoy/blob/main/CODEOWNERS) @kyessenov @tyxia @yanavlasov @zirain @douglas-reid @adisuissa

**Comment by zirain** [comment]
cc @kyessenov

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
