### PR TITLE
Revert "Revert "generic proxy: move generic proxy from contrib into extension

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by wbpcode** [comment]
now, precheck is happy, haha

**Comment by abeyad** [comment]
what's the original PR that this is a revert of?

**Comment by wbpcode** [comment]
> what's the original PR that this is a revert of?

My initial PR is #34892. Then @alyssawilk reverted in

**Review by abeyad — APPROVED** [review]
/lgtm api

**Comment by abeyad** [comment]
> > what's the original PR that this is a revert of?
> 
> My initial PR is #34892. Then @alyssawilk reverted it by #35119 because CI failure.
> 
> This PR fixed the CI problem.
> 
> cc @abeyad

Thanks @wbpcode !  Just FYI, Alyssa is OOO for the next week and a half.

**Comment by wbpcode** [comment]
@abeyad Thanks. I am not in a hurry. So, I will wait @alyssawilk back and give a final approval.

**Comment by wbpcode** [comment]
@alyssawilk I just merged main 2 hours ago. Is it necessary to merge main agt?

**Review by alyssawilk — APPROVED** [review]

**Comment by phlax** [comment]
@wbpcode not sure retesting will help - i gave up on it - see #31957

**Comment by wbpcode** [comment]
seems it works, at least, this time.

**Pull request merged**
