### PR TITLE
datadog: tracer_stats portion of new tracing library

### PR DESCRIPTION
**Pull request by dgoffredo**
This is part of the initiative described in https://github.com/envoyproxy/envoy/pull/23958.

This revision introduces a new library dependency for Datadog tracing, and adds a small component that will be used in the future when more of the new library is integrated into the Datadog tracing extension.

`tracer_stats` factors out the existing `DatadogTracerStats` and renames it to `TracerStats`. It also keeps the macros scoped to the header file, and omits some statistics.

The statistics omitted, `traces_sent` and `timer_flushed`, are those that could only be reported by the collector (`datadog::tracing::DatadogAgent`). Rather than create a statistics abstraction for the collector interface in `dd-trace-cpp`, I instead omitted the statistics from this extension. I think that the `reports_*` statistics (published by the HTTP client) are sufficient for tracking the behavior of the tracer.

### CODE REVIEW

**Review by jmarantz — APPROVED** [review]

**Comment by jmarantz** [comment]
/assign-from @envoyproxy/senior-maintainers

Ryan is a senior maintainer but he approved only for API.

**Comment by jmarantz** [comment]
needs main merge also

**Comment by ggreenway** [comment]
/wait

for main merge

**Review by ggreenway — APPROVED** [review]

**Comment by dgoffredo** [comment]
:tada: Thanks @jmarantz and @ggreenway

**Pull request merged**
