### PR TITLE
protobuf.patch: a bunch of updates, mostly backports

### PR DESCRIPTION
**Pull request by asedeno**
Backport several changes from protobuf upstream to reduce warnings during the build.

protoc warnings:
https://github.com/protocolbuffers/protobuf/commit/923ee767b9a783d807116aa92e43a1d7d2d3fb7b

hide clang pragmas from not-clang:
https://github.com/protocolbuffers/protobuf/commit/7d3e80ce9c522365bf78c44726e9946975f534e4

explicit `this` capture in some lambdas:
https://github.com/protocolbuffers/protobuf/commit/f8bf5eddb4e579c51ff2d98a11fc7dba91aa2950

explicit `inline` when `PROTOBUF_ALWAYS_INLINE`:
https://github.com/protocolbuffers/protobuf/commit/a7d47b3ebfd59574b89ff96a726ca176f18d4911

Finally, submitted for consideration upstream:
Do not inline a couple of functions when using gcc. When these functions
are inlined by gcc, the pragmas ignoring some warnings are not honored
at the inline site, and so it gets very noisy.

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by asedeno** [comment]
Not sure what's up with coverage.
main: https://storage.googleapis.com/envoy-postsubmit/db0873c/coverage/index.html
this: https://storage.googleapis.com/envoy-pr/023e0c3/coverage/index.html

**Comment by phlax** [comment]
i think coverage was just ratcheted a little too high for `source/common` (cc @alyssawilk )

wierdly the cov report doesnt give totals for this dir - but either way i think there are some non-deterministic code paths when testing so coverage can be a bit flakey

i would just adjust it

**Pull request merged**
