### PR TITLE
http: split strict_1xx_and_204_response_headers into two settings

### LINKED ISSUE #13868: [feature request] Fault-in-standard-out option on TE header at 1xx and 204
#11458 and #10811 fixed the `transfer-encoding: chunked` behavior.

Unfortunately the runtime-key is controlling both upstream and downstream.

Zero down time cannot be achieved unless the entire Envoy are upgraded atomically.

Is it possible to provide an option to tolerate non-standard upstream response and provide standard TE?

See the ideal state here.
https://github.com/istio/istio/pull/28450#issuecomment-719852578

### PR DESCRIPTION
**Pull request by tbarrella**
Commit Message:

http: split strict_1xx_and_204_response_headers into two settings

Signed-off-by: Taylor Barrella <tabarr@google.com>

Additional Description:
Risk Level: Low
Testing: unit
Docs Changes: N/A
Release Notes: added minor behavior change
Runtime guard: replaced `strict_1xx_and_204_response_headers` with `require_strict_1xx_and_204_response_headers` and `send_strict_1xx_and_204_response_headers`
Fixes #13868

### CODE REVIEW

**Review by lambdai — COMMENTED** [review]
Generally LGTM. Thanks!

Question: If `accept_strict_1xx_and_204_response_headers` == false and `send_strict_1xx_and_204_response_headers` == true
 Is TE stripped in downstream response when the upstream response contains TE?

It's not clear to me whether the downstream TE is always decided by `send_strict_1xx_and_204_response_headers` regardless the upstream response contains TE or not.

**Review by alyssawilk — COMMENTED** [review]
LG overall, thanks so much for picking this one up!

Two thoughts.  Do you think it should be strict_accept since we're making accepting strict, it's not that we're accepting strict headers (which I think we would either way?)

I think it's worth an integration test making sure that new-accept works with old-send, to make sure this actually addresses the problem.

**Comment by tbarrella** [comment]
> Do you think it should be strict_accept since we're making accepting strict, it's not that we're accepting strict headers (which I think we would either way?)

That's more grammatical yeah, although I think the flags should be consistent. So I can switch that as long as it's ok to switch the other to strict_send. Also, feel like I might as well use strict_allow because that seems a little better...

**Comment by alyssawilk** [comment]
Hm,  I feel like send_strict and strict_accept makes sense but I hear you about wanting to keep them parallel.  How about send_strict and require_strict so you can keep the ordering the same but the meaning clear?

**Comment by tbarrella** [comment]
>Question: If `accept_strict_1xx_and_204_response_headers == false` and `send_strict_1xx_and_204_response_headers == true`
Is TE stripped in downstream response when the upstream response contains TE?

I think so based on [this comment](https://github.com/envoyproxy/envoy/pull/11458/files#diff-8d3b9d0a839b05612561930ee8c58bf1b0ff0adc55cf27d79a7e3bbfbd81965eR171).

>I think it's worth an integration test making sure that new-accept works with old-send, to make sure this actually addresses the problem.

Do you mean `require_strict_1xx_and_204_response_headers = false` and `send_strict_1xx_and_204_response_headers = true` (what's desired in https://github.com/istio/istio/pull/28450#issuecomment-719852578)? Looking more, I'm not sure how valuable it would be to add an integration test for this. For example, I could duplicate the [BidirectionalChunkedData test](https://github.com/envoyproxy/envoy/blob/v1.17.0/test/integration/websocket_integration_test.cc#L408) with `require_strict_1xx_and_204_response_headers = false` (it passes, and also fails with `send_strict_1xx_and_204_response_headers = false` instead) but the only real place this is used is [here](https://github.com/envoyproxy/envoy/pull/15880/files#diff-8d3b9d0a839b05612561930ee8c58bf1b0ff0adc55cf27d79a7e3bbfbd81965eR1286). I think these paths are effectively covered by the tests in [`codec_impl_test.cc`](https://github.com/envoyproxy/envoy/pull/15880/files#diff-d0cef54c9175b0f6e5d74e6a1f8e6a1ea0450b93e30586b14e6dc789429c3cfe).

**Comment by alyssawilk** [comment]
Ah, is what you're saying that the codec tests, while looking the same, are actually testing the case which failed before, of a mix of old and new style headers, so are validating the bug fix despite not being end to end?  If so I think I'm good :-)

**Review by alyssawilk — APPROVED** [review]

**Comment by tbarrella** [comment]
Yeah, specifically the second half of [`204ResponseWithContentLength0`](https://github.com/envoyproxy/envoy/pull/15880/files#diff-d0cef54c9175b0f6e5d74e6a1f8e6a1ea0450b93e30586b14e6dc789429c3cfeR2315) is a situation that could result from this combination of flags. Thank you!

/retest

**Comment by tbarrella** [comment]
Hi @snowp, @alyssawilk said this is
>going to need a main merge around 12PDT when the new release is created and 1.19 notes are created.  ...  I've tagged snowp for second pass, and to do the merge while I'm out so you can ping him once it's re-ready.

Did I tag you too late? Which release will this be going into?

**Comment by tbarrella** [comment]
Hm, the format check failure looks unrelated to my change

**Comment by snowp** [comment]
This will go out with 1.19 as is. Can you try merging main and see it that helps resolve the format issue? It does seem unrelated to this code as you say

**Review by snowp — APPROVED** [review]
Thanks!

**Comment by jojofeng** [comment]
Hi, I'm new to envoy so I apologize for the naive question, but how do I actually configure these flags? I would like to set `require_strict_1xx_and_204_headers` to `False` in my configuration. Do I pass it from the command line? Or do I need to add something to my YAML config?

**Comment by rbalaraman-c** [comment]
Same as jojofeng, I would also like to know how to configure these flags.
I believe I can do it by calling "POST /runtime_modify" on the envoy sidecar admin interface. But what is a permanent way of configuring them?

**Comment by tbarrella** [comment]
@rbalaraman-c You can add a `static_layer` layer to `layered_runtime.layers` in [bootstrap config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto). The static layer should be a {runtime flag: value} map.

**Comment by jojofeng** [comment]
@rbalaraman-c this is the exact configuration block i use 😄 i hope it helps!

```
layered_runtime:
  layers:
    - name: base
      static_layer:
        envoy.reloadable_features.require_strict_1xx_and_204_response_headers: false
```

**Pull request merged**
