### PR TITLE
deps: Bump `rules_jvm_external` -> 6.6

### LINKED ISSUE #37360: Newer release available `rules_jvm_external`: 6.6 (current: 6.4)
Package Name: rules_jvm_external@6.4
Current Version: 6.4@2024-09-18
Available Version: 6.6@2024-11-25
Upstream releases: https://github.com/bazelbuild/rules_jvm_external/releases

### PR DESCRIPTION
**Pull request by phlax**
Fix #37360

### CODE REVIEW

**Comment by phlax** [comment]
Fix #37360

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
