### PR TITLE
unhide custom settings option in protocol options

### PR DESCRIPTION
**Pull request by ramaraochavali**
This has been implemented by https://github.com/envoyproxy/envoy/pull/9964
Commit Message:unhide custom settings option
Additional Description:unhide custom settings option in protocol options
Risk Level:N/A
Testing:N/A
Docs Changes:N/A
Release Notes:N/A
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by zuercher** [comment]
Reassigned @lizan as api shepherd

**Comment by lizan** [comment]
I don't have the original PR context, @alyssawilk did the deprecation PR described https://github.com/envoyproxy/envoy/pull/9964/files#r394441848 happen?

**Comment by alyssawilk** [comment]
allow_connect doesn't look deprecated so I'm going with "no"
I think to unhide this, we should deprecate allow_connect, and config-check that if custom_settings_parameters is used, that allow_connect is not true, and update the comments for this field as well as relevant docs.

**Comment by ramaraochavali** [comment]
Oh. I did not know the dependency on allow_connect. Will close this PR.

**Pull request closed without merging**
