### PR TITLE
stringmatcher: import updated xds types and support custom extension

### PR DESCRIPTION
**Pull request by ggreenway**
Commit Message: Update cncf/xds protos to get custom StringMatcher configuration
Additional Description:
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by phlax — APPROVED** [review]
/lgtm deps

thanks @ggreenway

**Review by ravenblackx — APPROVED** [review]

**Pull request merged**
