### PR TITLE
[fuzz] Prefer vector::data() to get a pointer to vector contents.

### PR DESCRIPTION
**Pull request by antoniovicente**
Commit Message: Prefer vector::data() over &v[0] as a way to get a pointer to vector contents  Use of &v[0] on an empty vector triggers undefined-behavior warnings under ASAN.
Additional Description:
Risk Level: n/a
Testing: new fuzz input
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by antoniovicente** [comment]
> Thank you so much! Is this a common enough pattern to consider linting for?

Yeah...  how would we do that?

**Comment by ggreenway** [comment]
> > Thank you so much! Is this a common enough pattern to consider linting for?
> 
> Yeah... how would we do that?

I think it would need to be done in clang_tidy. I don't know if clang_tidy supports this type of check or not.

**Comment by asraa** [comment]
> I think it would need to be done in clang_tidy. I don't know if clang_tidy supports this type of check or not.

It would definitely be a candidate for Semmle analysis https://github.com/envoyproxy/envoy/issues/9485

**Pull request merged**
