### PR TITLE
Updated Docker builds to persist Bazel cache.

### PR DESCRIPTION
**Pull request by asridharan**
*Title*:*Updated Docker builds to persist Bazel cache.*

*Description*:
Using the docker builds is currently painful since the Bazel cache is
not persisted. This implies that every build is a clean build and hence
the docker build system cannot be used during regular development
workflows.

In this change have introduced a data-volume to the Docker build system
that would persist the Bazel cache across different Docker runs. The
name of the data-volumen defaults to `bazel-cache` but can be changed by
the developer using the environment variable `ENVOY_DOCKER_BAZEL_CACHE`.

*Risk Level*: Low

*Testing*:
* Ran build with `./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.asan'` to test that the cache is working correctly, and we don't have any re-runs of the builds.
* Ran build with ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release.server_only' to test that the cache is working correctly, and we don't have any re-runs of the builds.

Signed-off-by: Avinash Sridharan <avinash.sridharan@gmail.com>

*title*: *one line description*

>Title can be a one or two words to describe the subsystem or the aspect
 this PR applies to. Title and description must be lower case. For example:
* ci: update build image to 44d539cb
* docs: fix indent, buffer: add copyOut() method
* router:add x-envoy-overloaded header
* tls: add support for specifying TLS session ticket keys

*Description*:
>What does this PR do? What was the behavior before the PR?
What is the behavior with the PR? If fixing a bug, please describe what
the original issue is and how the change resolves it. How does this
feature get enabled? By default, config change, etc...

*Risk Level*: Low | Medium | High
>Low: Small bug fix or small optional feature.

>Medium: New features that are not enabled(for example: new filter). Small-medium
features added to existing components(for example: modification to an existing
filter).

>High: Complicated changes such as flow control, rewrites of critical
components, etc.

>Note: The above is only a rough guide for choosing a level,
please ask if you have any concerns about the risk of the PR.

*Testing*:
>Explanation of what testing was done, for example: unit test,
integration, manual testing, etc.

>Note: It isn’t expected to do all
forms of testing, please use your best judgement or ask for guidance
if you are unsure. A good rule of thumb is the riskier the change, the
more comprehensive the testing should be.

*Docs Changes*:
>Link to [Data Plane PR](https://github.com/envoyproxy/data-plane-api/pulls)]
if your PR involves documentation changes. Please write in N/A if there were no
documentation changes.

*Release Notes*:
>If this change is user impacting you **must** add a release note to
[RAW_RELEASE_NOTES.md](RAW_RELEASE_NOTES.md). Thank you! Please write in N/A if
there are no release notes.

[Optional Fixes #Issue]

[Optional *API Changes*:]
>Link to [Data Plane PR](https://github.com/envoyproxy/data-plane-api/pulls)]

[Optional *Deprecated*:]
>Description of what is deprecated.

### CODE REVIEW

**Comment by htuch** [comment]
Isn't the cache already persisted in `ENVOY_DOCKER_BUILD_DIR/tmp/_bazel_bazel`?

**Comment by asridharan** [comment]
@htuch the `--output_base` is not being set anywhere so it looked like the default cache is set to ~/.cache/bazel. ?

**Comment by htuch** [comment]
@asridharan I think https://github.com/envoyproxy/envoy/blob/aa4737aa3f0b60c5f251dfc22e91c9b1d47a6a49/ci/build_setup.sh#L59 has the effect of changing the cache dir?

**Comment by asridharan** [comment]
@htuch the problem is that the cache still will need to be persisted on disk and mounted on each container, since the container filesystem layers are not going to be persisted across runs?

**Comment by htuch** [comment]
@asridharan The cache is in `/build`, which is bind mounted already. Do you not see a persisted cache in that directory? 

@jmillikin-stripe do you have any experience here with Bazel and cache placement? I thought `TEST_TMPDIR` was sufficient, and I can see this in my Docker setup working, but there's also the option of `--output_base`.

**Comment by lizan** [comment]
I don't think `TEST_TMPDIR` affect bazel cache, the `--output_base` is the parameter to set for its output. (symlinked as `bazel-out`)

**Comment by asridharan** [comment]
@htuch agree with @lizan.
@htuch 
https://github.com/envoyproxy/envoy/blob/master/ci/build_setup.sh#L78
seems to be copying some pre-built dependencies to `TEST_TMPDIR`, but it doesn't seem to change the `OUTPUT_BASE`
https://github.com/envoyproxy/envoy/blob/master/ci/build_setup.sh#L79
Where the same pre-built dependencies (or a superset) is copied over.

The document and google groups seem to suggest that `OUTPUT_BASE` defines where the `bazel cache` resides. 
https://docs.bazel.build/versions/master/command-line-reference.html

Not a `bazel` expert there, so still looking for some guidance for the right approach on this. That said atleast in my trial runs, without `output_base` I was seeing my builds be re-done when I use the docker builds. @htuch you don't see this issue?

**Comment by htuch** [comment]
@asridharan No, I don't see rebuilds, it caches. Historically, `TEST_TMPDIR` has been totally sufficient. I'd like to understand why we're seeing different behaviors here, I don't have any strong objection to your PR, but want to verify that we understand Bazel's cache placement behavior before merging.

**Comment by asridharan** [comment]
@htuch agreed. Let me re-run the builds to verify if bazel is doing a re-build or not.

**Comment by jmillikin-stripe** [comment]
I've been doing some testing with Bazel's new disk cache, and so far it works better than the hacky `$TEST_TMPDIR` stuff. We could try using this to put the cache under `/build`, by adding the following lines to the Docker container's `/etc/bazel.bazelrc`:

```
build --experimental_local_disk_cache
build --experimental_local_disk_cache_path=/build/bazel-disk-cache
build --experimental_repository_cache=/build/bazel-repo-cache
```

This caches the downloaded external repositories, and also all compilation action outputs. It persists across Docker container instances, and doesn't get cleared out when doing `-c opt` vs `-c dbg`.

**Comment by asridharan** [comment]
@htuch you were right. I tried doing the re-build and I do see the cache being used across builds (no re-builds). I think since the build directory is on a tmpfs I had re-started my laptop that caused the cache to get cleared ending up in a re-build. Should have investigated more. 

That said I guess @jmillikin-stripe seems to have a better solution than what I have anyway, so should I close this out?

**Comment by jmillikin-stripe** [comment]
I won't have time soon to poke at integrating the disk cache into the CI container, so if you want that to happen then this PR seems as good a place as any.

**Comment by asridharan** [comment]
@htuch I see this in the Bazel documentation:
> The outputRoot directory is ~/.cache/bazel. (Unless $TEST_TMPDIR is set, as in a test of bazel itself, in which case this directory is used instead.)

So that explains to me how `TEST_TMPDIR` seems to start being used for the cache. 
@jmillikin-stripe will see if I can incorporate your solution into this PR. Still building confidence with Bazel, so will have to play around with it to understand how the `/etc/bazel.bazelrc` affect the cache.

**Comment by htuch** [comment]
@asridharan yeah, if you want to incorporate @jmillikin-stripe suggestions that could be awesome, it would be a nice time saver for those of us who use the Docker image to do multiple conflicting non-standard things, e.g. ASAN and coverage. FYI, you can override where `/build` lives, getting it off the tmpfs, by changing `ENVOY_DOCKER_BUILD_DIR` (I do this routinely).

@jmillikin-stripe could you update https://github.com/envoyproxy/envoy/blob/master/bazel/README.md with the above steps? Thanks.

**Comment by htuch** [comment]
@asridharan I'm going to close this out while you work on that, feel free to reopen when it's ready. Thanks!

**Comment by asridharan** [comment]
sg @htuch thanks !!

**Pull request closed without merging**
