### PR TITLE
Adding an MxN integration test to test timeout mechanism works

### PR DESCRIPTION
**Pull request by yanjunxiang-google**
Adding an MxN integration test to test timeout mechanism works

This is to address a left-over comments of original MxN commit: https://github.com/envoyproxy/envoy/pull/34942

Fix: https://github.com/envoyproxy/envoy/issues/37065

### CODE REVIEW

**Comment by tyxia** [comment]
This solution will introduce a bad observability and customer experience, both of which are critical factors

If using timeout from component from regular mainstream, how can customer tell it is ext_proc sidestream issue when error is generated by regular stream like HCM

/wait

**Comment by yanjunxiang-google** [comment]
> IMHO this solution will introduce a bad observability and customer experience, both of which are critical factors
> 
> If mixing the errors by using timeout from regular mainstream's component, how can customer tell it is ext_proc sidestream issue when error is generated by regular stream like HCM
> 
> /wait

Thanks for the comments!

IIUC, timers are used to recover the system if bad things happen. Customer may uses stats to check what's going wrong. For example, if the ext_proc server is not responding, one can identify that by checking ext_proc filter: stream_msgs_received counter:
https://github.com/envoyproxy/envoy/blob/baa4c0554b6fedec09ba028f6a0bbf1d767dc76f/source/extensions/filters/http/ext_proc/ext_proc.h#L39

**Comment by yanjunxiang-google** [comment]
Kind Ping!

**Comment by yanjunxiang-google** [comment]
Kind Ping!

We can continue debate the necessity of adding a new ext_proc MxN timer.  However, regardless the final decision of that,  this test is able to show that the existing HCM stream_idle_timer is able to recover Envoy if ext_proc server failed to send response. In another words, this test won't be obsoleted even in the future we are going to add a new MxN timer.

**Pull request merged**
