### PR TITLE
examples/grpc: fix go.mod

### PR DESCRIPTION
**Pull request by doujiang24**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by doujiang24** [comment]
Hello @phlax , this could fix https://github.com/envoyproxy/envoy/pull/31294, hope it fix the error from dependabot-updater.
I haven't seen the error message from dependabot-updater, guess it complains an invalid go mod file.

**Comment by phlax** [comment]
yeah - lets see - i tried something similar - not sure why but then i ended up adding a go.sum file also - which didnt work

**Review by phlax — APPROVED** [review]
lgtm, thanks @doujiang24

**Comment by phlax** [comment]
@doujiang24 unfortunately this one didnt work - error is

```console

  proxy | 2023/12/12 13:27:33 [405] GET https://proxy.golang.org:443/github.com/envoyproxy/envoy/@v/list
  proxy | 2023/12/12 13:27:33 [405] 200 https://proxy.golang.org:443/github.com/envoyproxy/envoy/@v/list
updater | 2023/12/12 13:27:33 INFO <job_761393423> Handled error whilst updating golang.org/x/net: dependency_file_not_resolvable {:message=>"github.com/envoyproxy/envoy/examples/grpc-bridge/server/kv: cannot find module providing package github.com/envoyproxy/envoy/examples/grpc-bridge/server/kv"}
updater | 2023/12/12 13:27:33 INFO <job_761393423> Finished job processing
updater | 2023/12/12 13:27:33 INFO Results:

```

https://github.com/envoyproxy/envoy/network/updates/761393423

**Comment by doujiang24** [comment]
oh, I'll take a look tomorrow.
https://github.com/envoyproxy/envoy/network/updates/761393423 is 404 on my side, might be lack of permission.

**Pull request merged**
