### PR TITLE
logger: fix lifetime issue of AccessLogConfig in tls callback.

### PR DESCRIPTION
**Pull request by mathetake**
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

Commit Message: This commit fixes the lifetime issue of Http/TcpAccessLogConfig owned by HttpGrpcAccessLog and TcpGrpcAccessLog loggers. These logger objects may have died before the thread local callback for initializing thread local access loggers is actually executed in each thread. In the previous implementation, the callback only captures the reference to the AccessLogConfig object owned by HttpGrpcAccessLog/TcpGrpcAccessLog which might not outlive, and therefore potentially this causes the invalid memory access and crashes the Envoy in any thread. This happens especially when an xDS resource is NACKed.
Related Issues: https://github.com/envoyproxy/envoy/issues/18066

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by lambdai — DISMISSED** [review]
Thanks! The tls lambda removes `this` and replaced by either value or the scope.

Unlike the `config_` member,  scope is the topic should be resolve separately as in the comment.

**Review by tonya11en — APPROVED** [review]
LGTM on first pass. Thanks for fixing!

**Comment by lizan** [comment]
Is it possible to have a test around this?

**Comment by mathetake** [comment]
oh yeah will do!

**Comment by mathetake** [comment]
https://github.com/mathetake/envoy/commit/56518192734e16b276c512e01c8e0ba3fc1039c9 added

**Review by lizan — APPROVED** [review]

**Comment by lizan** [comment]
/assign-from @envoyproxy/maintainers
for non-tetrands review

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
