### PR TITLE
Revert 100 continue

### PR DESCRIPTION
**Pull request by mattklein123**
This reverts both https://github.com/envoyproxy/envoy/pull/2560 and https://github.com/envoyproxy/envoy/pull/2497. I've been chatting with @alyssawilk offline and there are still issues here that need investigation. We think it's better to revert for now.

### CODE REVIEW

**Comment by mattklein123** [comment]
cc @junr03

**Comment by mattklein123** [comment]
IMO we can close this revert. I think @alyssawilk has a full understanding of the underlying issue and the 2nd fix should get us into a decent state, at least no worse than we were previously. There are follow up fixes coming for robustness, etc. but I feel comfortable either way. @alyssawilk up to you whether you want to merge or close.

**Comment by mattklein123** [comment]
@junr03 can you go to canary with current master tomorrow if possible? If that fails we can merge this revert.

**Comment by junr03** [comment]
I'll canary current master once I'm back in Seattle (mid morning)

**Comment by mattklein123** [comment]
Looks like canary is working OK so will just close this out and we can roll forward from here with additional fixes.

**Comment by junr03** [comment]
Yes, not seeing any crashes up until now.

**Pull request closed without merging**
