### PR TITLE
gcp_authn: Override any existing value in the request header that includes authn: Bearer id token

### PR DESCRIPTION
**Pull request by tyxia**
Issue: If an incoming request includes an existing Authorization token, we should override instead of appending to the existing value.
Fix: Use `setCopy` instead of `addCopy` for the override behavior.

Signed-off-by: Tianyu Xia <tyxia@google.com>

### CODE REVIEW

**Comment by tyxia** [comment]
/assign @yanavlasov 

Could you please take a look? Thanks!

**Comment by tyxia** [comment]
@yanavlasov  The test coverage is added and  PTAL. Thanks!

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
