### PR TITLE
bazel: rename `@com_github_cncf_udpa` to `@com_github_cncf_xds`

### PR DESCRIPTION
**Pull request by sergiitk**
The repo has been renamed from cncf/udpa to cncf/xds long time ago, this is just to reflect this in the bazel repo name.
Otherwise this is a noop.

---

Commit Message: bazel: rename `@com_github_cncf_udpa` to `@com_github_cncf_xds`
Additional Description: 

> The repo has been renamed from cncf/udpa to cncf/xds long time ago, this is just to reflect this in the bazel repo name.
> Otherwise this is a noop.

Risk Level: Low
Testing: do_ci.sh
Docs Changes:  N/A (except some md files got updated)
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by sergiitk** [comment]
Addresses good point brought in https://github.com/envoyproxy/envoy/pull/30159#issuecomment-1786243825.

cc @moderation @phlax

**Review by phlax — APPROVED** [review]
lgtm, with the stub to maintain downstream compat

im wondering if there is a way to add a deprecated notice

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Comment by sergiitk** [comment]
For future references, corresponding downstream compat fix in grpc core: https://github.com/grpc/grpc/pull/35603. Thanks @eugeneo!

**Pull request merged**
