### PR TITLE
http: added OVERWRITE_IF_EXISTS header manipulator

### LINKED ISSUE #27907: response_header_to_add - not append to existing header instead create new header
Description:
Once Set-Cookie header existing in the response, trying to append a value will create new header with same name instead of appending the value to the existing header.

image
image

I tried also with append_action: OVERWRITE_IF_EXISTS_OR_ADD - same result. 
please see also thread https://github.com/envoyproxy/envoy/issues/27758 where I was requested to open an issue.

*Repro steps*:
1) Add response_header_to_add to the route
```
response_header_to_add 
   - header:
       key: "set-cookie"
       value: ";HttpOnly; Secure"
```
2) If in the response of the API you have "set-cookie" header, a new header is created instead of append to existing header

### PR DESCRIPTION
**Pull request by cpakulski**
Commit Message:
added OVERWRITE_IF_EXISTS header manipulator
Additional Description:
This is to address a use case when a header should be modified only when it exists and should not be added when it does not exist.
Risk Level: Low
Testing: Unit tests.
Docs Changes: Yes.
Release Notes: Yes
Platform Specific Features: No 
Fixes #27907

### CODE REVIEW

**Review by adisuissa — COMMENTED** [review]
Before reviewing this, seems that the original issue was [due to a different problem](https://github.com/envoyproxy/envoy/issues/27907#issuecomment-1586871210).
Is this PR still relevant?

/wait-any

**Comment by cpakulski** [comment]
Yes, it is still relevant. This is to address use case when an upstream server returns a header which should be modified. For example add some attributes to "set-cookie" header. But if that specific header is absent, nothing should be done. AFAIK it was not possible before this PR.

**Comment by cpakulski** [comment]
> Just for discussion, I am thinking if there is a more common way to resolve all these problem. This is essentially a conditional header rewrite, right?

I agree. The problem is that already existing manipulation commands already contain kind of conditional logic: `IF_EXISTS`, `IF_EXIST_OR_ADD`. It probably would be a bit cleaner to separate action and condition into separate fields. Action would be `ADD`, `OVERWRITE` and `DELETE` and condition would be `IF_EXISTS`, `IF_ABSENT`, `ALWAYS`.

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!
/lgtm api

**Comment by adisuissa** [comment]
Seems that latest main should be merged.

/assign-from @envoyproxy/senior-maintainers

**Comment by jmarantz** [comment]
needs main merge, which may also resolve CI failure

/wait

**Comment by cpakulski** [comment]
@adisuissa I changed nothing in proto file in the latest commit, but it looks that this PR needs another approval for api change.

**Review by adisuissa — COMMENTED** [review]
/lgtm api

**Review by adisuissa — DISMISSED** [review]

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Comment by htuch** [comment]
Needs a merge fix.

**Comment by cpakulski** [comment]
`main` is merged. For some reason each time I push an update, `api LGTM` is dropped. @adisuissa - sorry to bug you again for api approval. This PR was approved by @htuch and there is nothing to add on my side, so I think it is ready for merge.

**Pull request merged**
