### PR TITLE
formatter: escape percent sign in response format

### LINKED ISSUE #15159: Escape percent sign in log/custom response format
*Title*: *Escape percent sign in log/custom response format*

*Description*:

The "access log" format uses %s for format strings, such as `%RESPONSE_CODE%`, but I don't see any way to escape a literal percent sign. Couldn't find one documented, and tried both `\%` and `%%` and neither worked.

Use case: This isn't just a log format, it's also used for custom responses (by `type.googleapis.com/envoy.extensions.filters.http.response_map.v3.ResponseMap`, under `body_format_override.text_format`). If configuring HTML responses, inline CSS can very easily break the config.

[optional *Relevant Links*:]

* https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log-format-strings
* https://www.getambassador.io/docs/latest/topics/running/custom-error-responses/

### PR DESCRIPTION
**Pull request by aidanhahn**
Add a case in the SubstitutionFormatter to replace '%%' with '%'. 
This allows users to escape % in their configurations, fixing #15159.

Signed-off-by: Aidan Hahn <aidanhahn@datawire.io>

Commit Message: formatter: escape percent sign in response format 
Additional Description:
Risk Level: Low
Testing: Unit testing
Docs Changes:
Release Notes:
Platform Specific Features:
Fixes: #15159

### CODE REVIEW

**Comment by jmarantz** [comment]
/assign-from @envoyproxy/first-pass-reviewers

Can you clean up the description (remove optional fields and hints)?

**Comment by jmarantz** [comment]
Also, please don't force-push. More detail about this will be added to the developers doc in https://github.com/envoyproxy/envoy/pull/19381

**Comment by rojkov** [comment]
To rerun failed checks without making changes just add this line in a comment:

/retest

More info on this is in https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md#triggering-ci-re-run-without-making-changes

**Review by jmarantz — COMMENTED** [review]
I found a few superficial nits but I think this needs a look from someone who's worked with the formatters before.

**Comment by aidanhahn** [comment]
Previously you mentioned I should not force push, is it acceptable to force push in order to fix DCO?

**Comment by jmarantz** [comment]
That's the only reason to do it, but generally you should not have DCO problems if you set up the right git hooks.

The main reason it's OK to force-push to fix DCO is that usually happens exactly once, before anyone has started reviewing. If you force-push after people start reviewing it wipes out their comments.

So my suggestion is to force-push this time, but install the git hooks so this never needs to happen again, and we'll live with my precious review being wiped :)

**Pull request closed without merging**
