### PR TITLE
[backport/1.22] Release 1.22 build fix

### LINKED ISSUE #23156: Build broken for envoy 1.22.5
*Title*: *Build broken for envoy 1.22.5*

*Description*:
Build failure for envoy 1.22.5, used for istio 1.14

*Repro steps*:
git clone git@github.com:envoyproxy/envoy.git
git checkout 2ba6db6633d24dbe4aa2c5cf8ebba9f84767e3f4
bazel --output_base bazel_out build -c opt envoy

Build fails with error,
source/common/config/watch_map.cc: In member function 'virtual void Envoy::Config::WatchMap::onConfigUpdate(const google::protobuf::RepeatedPtrField<envoy::service::discovery::v3::Resource>&, const google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char> >&, const string&)':
source/common/config/watch_map.cc:215:69: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  215 |       type_url_, reinterpret_cast<std::vector<DecodedResourcePtr>&>(decoded_resources),
      |                                                                     ^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
Target //source/exe:envoy-static failed to build

### PR DESCRIPTION
**Pull request by phlax**
Fix #23156

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @adisuissa

**Review by mattklein123 — APPROVED** [review]

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
