### PR TITLE
bazelci: no rbe for coverage

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Comment by lizan** [comment]
@meteorcloudy this is a potential fix, can you (or some one at bazelci team) trigger a bazelci run for this? The other option is download and install LLVM-9 (and 10 in nearly future) to bazelci image (or via `shell_commands`).

**Comment by meteorcloudy** [comment]
Thanks! Can you push the `bazelci_cov_fix` branch to the envoy repo? That would make the test very easy!

**Comment by lizan** [comment]
@meteorcloudy done

**Comment by meteorcloudy** [comment]
@lizan Thanks for merging this! But I'm still seeing the same error in the latest build:
https://buildkite.com/bazel/envoy/builds/1163#4d5b4493-9c2a-42c6-8a4e-ab9c6d9b1b15

**Comment by meteorcloudy** [comment]
Ping~ Is there any update? Could remote caching be the problem?

**Pull request merged**
