### PR TITLE
wasm: Compile with AOT/JIT to get runtime performance

### PR DESCRIPTION
**Pull request by leyao-daily**
Signed-off-by: Le Yao <le.yao@intel.com>

Commit Message: Compile the runtime with AOT/JIT support to get the performance improvement
Additional Description:
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@leyao-daily ci fail looks genuine

**Comment by leyao-daily** [comment]
> 

Yes. Fix with adding llvm deps.

**Comment by leyao-daily** [comment]
I will close this PR to wait for the optimized wamr, which will give a more reasonable support. https://github.com/bytecodealliance/wasm-micro-runtime/issues/1291

**Pull request closed without merging**
