### PR TITLE
rbac: allowlist HttpAttributesCelMatchInput xDS matcher in RBAC

### PR DESCRIPTION
**Pull request by agrawroh**
### Background

Today HTTP RBAC filter allows `HttpRequestHeaderMatchInput` but does not allow a more generic `HttpAttributesCelMatchInput` to be used in the matcher. It could be quite useful to allow `HttpAttributesCelMatchInput` for some advanced use-cases.

For example, in our use-case we want to first evaluate a CEL based on some HTTP header and then further match on a list of IPs based on the result of the CEL evaluation.

[See This](https://github.com/envoyproxy/envoy/issues/30839) for more information.

### Changes

In this PR we are adding support for `HttpAttributesCelMatchInput` in RBAC filter.

---

Commit Message:  allowlist `HttpAttributesCelMatchInput` xDS matcher in the RBAC filter.
Additional Description: added support for `HttpAttributesCelMatchInput` to be allowed in the xDS matcher inside the RBAC filter.
Risk Level: Low
Testing: Added Integration & Unit Tests.
Docs Changes: N/A
Release Notes: Yes
Platform Specific Features: No
Fixes #Issue: https://github.com/envoyproxy/envoy/issues/30839

### CODE REVIEW

**Comment by agrawroh** [comment]
@kyessenov @htuch Could one of you please take a pass on this whenever you can?

**Comment by htuch** [comment]
@kyessenov for first pass.

**Review by kyessenov — APPROVED** [review]
LGTM, pass on to the senior approvers.

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
