### PR TITLE
Revert "CDS mobile builder API and integration test (#25123)"

### PR DESCRIPTION
**Pull request by abeyad**
This reverts commit 4c507479c5dbc30e59c39604e52a459bc911b9aa.

The commit triggered CI failures:
https://github.com/envoyproxy/envoy/actions/runs/4125892811
https://github.com/envoyproxy/envoy/actions/runs/4125892787

Signed-off-by: Ali Beyad <abeyad@google.com>

### CODE REVIEW

**Review by alyssawilk — APPROVED** [review]

**Review by jpsim — APPROVED** [review]
Will leave it up to you if you want to revert or merge the fix.

**Comment by abeyad** [comment]
closing this PR in favor of https://github.com/envoyproxy/envoy/pull/25438 which was merged

**Pull request closed without merging**
