### PR TITLE
logging: do not call the broken 0-arg constructor for spdlog::details::log_msg

### PR DESCRIPTION
**Pull request by jmarantz**
*Description*: This constructor does not init all its member vars and breaks in clang 'msan'. msan is not run by default in CI but is run at Google so this tripped us up on import.
*Risk Level*: low
*Testing*: just this one test.
*Docs Changes*: n/a
*Release Notes*: n/a

### CODE REVIEW

**Comment by jmarantz** [comment]
@curiouserrandy please take a look; I was able to repro the problem and this fixes it. a spdlog upgrade is not required for this issue.

/assign curiousrandy

**Comment by mattklein123** [comment]
@itayd can you PTAL at why assign didn't work above? I think @curiouserrandy is in the org.

**Comment by itayd** [comment]
@mattklein123 will take further look this evening, but you can check from the trace (https://prod.repokitteh.app/traces/ui/envoyproxy/envoy/55c93430-e0fc-11e8-83e9-21c0a716cc39#eval), github claims that @curiouserrandy cannot be an assignee:

trace__envoyproxy_envoy_55c93430-e0fc-11e8-83e9-21c0a716cc39

**Comment by itayd** [comment]
huh

**Comment by itayd** [comment]
@mattklein123 you misspelled:

```
curiouserrandy
curiousrandy
```

next time use `@` :)

**Comment by itayd** [comment]
just verified this works with `@`

**Pull request merged**
