### PR TITLE
http: simplify the logic of upstream filter chain factory

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: http: simplify the logic of upstream filter chain factory
Additional Description:

1. simplify the filter chain interface and implementation. The `only_create_if_configured` only make sense for upstream filter chain and it indicates that the factory may create something even nothing is configured. It's complete a implementation detail which shouldn't be a part of interface.
2. reduce memory overhead of cluster because we needn't keep the default codec filter factorycb for every cluster now in most case. (I believe only small parts users/scenarios require to upstream filter.)

Risk Level: low.
Testing: n/a.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Review by botengyao — APPROVED** [review]
LGTM, thanks for the improvement!

**Comment by wbpcode** [comment]
@assign-from @envoyproxy/senior-maintainers for a second pass.

**Comment by ggreenway** [comment]
Reassigning to @alyssawilk as she's more familiar with this

**Review by alyssawilk — APPROVED** [review]
nice!

**Pull request merged**
