### PR TITLE
[UDP Proxy] Fix a bug in UDP session filter

### PR DESCRIPTION
**Pull request by IssaAbuKalbein**
Commit Message:
Additional Description: onSessionComplete() is called twice when a session filter is a read write filter, because "ReadFilter" and "WriteFilter" is declared without virtual inheritance.
Risk Level: low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Comment by IssaAbuKalbein** [comment]
@danzh2010 @yanavlasov Can you, please, take a look on this PR as you were the reviewers of my previous PR:
[UDP Proxy] Add onSessionComplete for UDP session filters (https://github.com/envoyproxy/envoy/pull/31094)

**Review by danzh2010 — APPROVED** [review]

**Comment by IssaAbuKalbein** [comment]
@yanavlasov ping

**Comment by adisuissa** [comment]
Assigning Dan as codeowner
/assign @danzh2010

**Comment by adisuissa** [comment]
Assigning Yan as a senior-maintainer.
/assign @yanavlasov

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
