### PR TITLE
Pin rules_cc to 0.17.0

### PR DESCRIPTION
**Pull request by asedeno**
- populate rules_cc information in bazel/repository_locations.bzl
- load rules_cc in repositories.bzl
- stop listing rules_cc as an untracked dependency of rules_rust

Before this, we didn't track `rules_cc` at all, and were at the whim of whatever brought it in, which for a local build for me today was 0.0.4, from circa 2022.

This does introduce some noise as the `cc_proto_library` rules in `rules_cc` now delegates to the one from `@com_google_protobuf` with a deprecation warning. We can silence these with a few small patches to our dependencies to bring them up to date if just updating them is insufficient. 

Risk Level: low
Testing: ci

### CODE REVIEW

**Comment by phlax** [comment]
looking here @asedeno https://github.com/bazelbuild/rules_python/blob/b5ed3e4554b6e31fd2d5fe6b0b270d2f8adfa059/python/private/py_repositories.bzl#L56-L61

i think we _might_ need to set the same version - we should test with new `rules_python` release - ill open pr now ..

**Comment by asedeno** [comment]
Do we want a python_rules update as part of this PR? I did a spot check with 0.40.0 and it worked, but I have not investigated thoroughly yet. 1.0.0 did not work, but I also didn't investigate that before just trying 0.40.0.

**Comment by phlax** [comment]
i just want to make sure it doesnt stop us from updating rules_python

**Comment by phlax** [comment]
theres an open pr to update to an earlier rules_python version here https://github.com/envoyproxy/envoy/pull/37201

if we can at least make it work that far that would be good - there some other issues with 1.0.0

cant find it rn - but i read a discussion previously basically suggesting that the versions set for rules_cc were required - but not sure how hard a requirement in terms of min/max

**Comment by asedeno** [comment]
(while I iterate locally on the `use_category` markings for `rules_cc`…)
Stacking PRs is not fun. Do we land this and then rebase that on it to see if it breaks? Can we rebase onto this PR for testing purposes? This is why I was asking about just making the change on a commit on this PR, once it's passing tests.

I'm also working on a patches commit to deal with the new warnings, which can come in here or in a separate PR, as desired.

**Comment by phlax** [comment]
i rebased https://github.com/envoyproxy/envoy/pull/37201 to here for testing - need to clock off - but feel free to open a testing pr or use this one etc if it doesnt work

**Comment by asedeno** [comment]
It occurs to me that since we're bringing in our own `rules_cc` now, we could patch out the deprecation warning in its `cc_proto_library`, and maintain the delegation to `com_google_protobuf` even if it gets removed. Better to not have to, but that would be only one thing to patch instead of several. Thoughts?

**Comment by phlax** [comment]
seems this works for rules_python=1.0.0 also

**Review by phlax — APPROVED** [review]
lgtm, thanks @asedeno

**Pull request merged**
