### PR TITLE
ci: Only run mobile jobs in the Envoy repo

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @jpsim this is fairly urgent as mirror repos are trying to run all of the mobile tests and failing

the solution is far from ideal - having to exclude at the job level - after trawling through the docs and design decisions here i have come to the firm conclusion that github/ms' intention is to trigger as much unwanted CI as they can get away with

**Review by jpsim — APPROVED** [review]
+1 to unblock, however we should consider doing the same for the other GitHub Actions CI jobs like CodeQL.

Also, do we have something similar in place for the Azure Pipelines CI?

**Comment by phlax** [comment]
i think we do this already for ~all of the existing gh jobs - in the case of azp we want them to run in current mirror

**Comment by phlax** [comment]
> ...  in the case of azp we want them to run in current mirror

so actually this is slightly more complex - azp has to be setup for a repo for it to trigger at all - so i think the file is harmless if that is not set up, and ~needed if it is

fwiw, triggers in the file are mostly ignored in favour of web config even where it is set up

**Pull request merged**
