### PR TITLE
[dev/1.24] repo: Dev v1.24.11

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by botengyao** [comment]
Thanks! Do we need to update 1.23? Will 1.23 be supported after 1.27.0 is released?

**Review by botengyao — APPROVED** [review]
lgtm, thanks!

**Comment by phlax** [comment]
> Do we need to update 1.23? Will 1.23 be supported after 1.27.0 is released?

no, the 1.23 branch is now closed to dev - we released a patch within our (extended) support window but there wont be any further official dev

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
