### PR TITLE
Fix fuzz OSS-issue-21276

### PR DESCRIPTION
**Pull request by jianwen612**
Commit Message:
Additional Description:
The issue can be found here:
https://oss-fuzz.com/testcase-detail/4863920725819392

The issue happened because in "regex_rewrite {}" field of the config input, there is a "substitution" field but there is no "pattern" field.

The fix is to add "required" to "RegexMatcher pattern" field of api/envoy/type/matcher/v3/regex.proto.

Risk Level: low
Testing: Passed all with the existing corpus and with this failed test case.

[Optional Fixes #Issue] 
fuzz OSS-issue-21276
https://oss-fuzz.com/testcase-detail/4863920725819392
backup report:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21276

/cc @asraa 
/cc @samkerner

### CODE REVIEW

**Comment by asraa** [comment]
Yes!! Thank you! Could you add the bug report from monorail as the link to fixes issue https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21276? The testcase will eventually disappear, but the bug report will remain. I think the corpus entry got dropped somewhere along the way, too.

**Comment by jianwen612** [comment]
> Yes!! Thank you! Could you add the bug report from monorail as the link to fixes issue https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21276? The testcase will eventually disappear, but the bug report will remain. I think the corpus entry got dropped somewhere along the way, too.

Thanks for this advice! I added this link in the content.

**Comment by htuch** [comment]
This is technically a PGV annotation strengthening, but no objections as the contract would have been implied previously.

**Pull request merged**
