### PR TITLE
oauth2: on refresh, replace instead of append cookies

### PR DESCRIPTION
**Pull request by bplotnick**
Commit Message: oauth2: on refresh, replace instead of append cookies
Additional Description:
The [issue](https://github.com/envoyproxy/envoy/issues/32771) has most of the context, but in short when we refresh the access token we aren't removing the existing access token cookie and instead are appending the new cookie, which is not valid.
Risk Level: low
Testing: unit testing. wrote the failing test first
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
fixes https://github.com/envoyproxy/envoy/issues/32771
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by Alexcei88** [comment]
@bplotnick , thank you for the fix.  it looks good for me. I agree with changes and it will resolve the issue.

**Review by KBaichoo — COMMENTED** [review]
Thank you for finding and fixing this. Can you add release notes?

I suspect this must have not have been used much for as it'd run into issues of duplicate cookies discussed in https://github.com/envoyproxy/envoy/issues/32771. As such it might not need a runtime guard.

/assign @mattklein123

**Review by KBaichoo — APPROVED** [review]

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
