### PR TITLE
rate_limit: Add time unit week

### PR DESCRIPTION
**Pull request by stefansedich**
Commit Message: rate_limit: Add time unit week
Additional Description: 

Following on from https://github.com/envoyproxy/envoy/pull/24070 and adding support for week as a unit of time for ratelimits as this is something my team currently needs and WEEK felt sad as it was missing the protobuf party.

Ideally we would have something like https://github.com/envoyproxy/envoy/issues/33277 but in the interim it makes sense to add WEEK here since we have every other period already except week.

Risk Level: Low
Testing: Added unit test coverage
Docs Changes: n/a
Release Notes: added
Platform Specific Features: n/a

### CODE REVIEW

**Comment by wbpcode** [comment]
So, the week is 7 days rather than a nature week, right? If is that way, please add a comment to document it clearly. Thanks.

**Comment by stefansedich** [comment]
> So, the week is 7 days rather than a nature week, right? If is that way, please add a comment to document it clearly. Thanks.

First I have ever heard of a "nature week" 😸 hopefully that comment is what you were after!

**Comment by wbpcode** [comment]
> > So, the week is 7 days rather than a nature week, right? If is that way, please add a comment to document it clearly. Thanks.
> 
> 
> 
> First I have ever heard of a "nature week" 😸 hopefully that comment is what you were after! I guess it is also fitting that the enum value is also `7` here...

Sorry, I didn't make it clear. But never mind, I just realized that the YEAR here is also not natural year.

So, it's fine, will take a more detailed check tomorrow

**Review by ggreenway — CHANGES_REQUESTED** [review]
This is failing coverage; please add a test that exercises this.

/wait

**Comment by stefansedich** [comment]
> This is failing coverage; please add a test that exercises this.
> 
> /wait

Ok no problems let me see what I can add, had followed the PR that added month/year as a guide which did not add coverage but happy to add something.

**Comment by stefansedich** [comment]
@ggreenway have added a test here, but couple points:

1. I have not touched c++ in 15+ years
2. I have no idea what I am doing

Still working to get my local environment running to run the test suite as I am not sure this will even work.

**Comment by stefansedich** [comment]
```
[----------] Global test environment tear-down
[==========] 12 tests from 1 test suite ran. (2 ms total)
[  PASSED  ] 12 tests.
```

@ggreenway coverage added, let me know if you have any issues/suggestions with what I did.

**Review by wbpcode — APPROVED** [review]

**Review by wbpcode — APPROVED** [review]

**Comment by wbpcode** [comment]
ci still not happy

/wait

**Comment by stefansedich** [comment]
> ci still not happy
> 
> /wait

Thanks @wbpcode I saw those failures and was not sure as some of them looked like they flaked for unlrelated issues, let me know if I have missed something obvious.

**Comment by wbpcode** [comment]
> > ci still not happy
> > /wait
> 
> Thanks @wbpcode I saw those failures and was not sure as some of them looked like they flaked for unlrelated issues, let me know if I have missed something obvious.

let me retry the ci

**Review by wbpcode — APPROVED** [review]

**Comment by wbpcode** [comment]
cc @ggreenway

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
