### PR TITLE
mobile: replace `envoy_mobile_copts` with `envoy_mobile_defines`

### PR DESCRIPTION
**Pull request by jpsim**
This is more correct and will work with upcoming changes to enable Swift and C++ interop.

Signed-off-by: JP Simard <jp@jpsim.com>

Commit Message:
Additional Description:
Risk Level: Medium.
Testing: Existing.
Docs Changes: None.
Release Notes: None.
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by keith — APPROVED** [review]
when possible it is preferred to use copts for things that don't need to be consumed by upstream consumers, but i know some of these do and im not sure if it's worth trying to split out those that do vs don't

**Comment by jpsim** [comment]
> when possible it is preferred to use copts for things that don't need to be consumed by upstream consumers

Yes, that's exactly what's being done now. Only the defines needed by upstream (Envoy Mobile) consumers are in `envoy_mobile_defines`. Everything else is still in `envoy_cc_library` copts.

**Pull request merged**
