### PR TITLE
router: introduces a hash policy to mutate hash on retry

### PR DESCRIPTION
**Pull request by zuercher**
Consistent hashing generally causes retried requests to be resent
to the same upstream. In cases where this is undesirable, allow
the retry count to mutate the hash used for selecting hosts.

Risk Level: low, opt-in config
Testing: unit, integration tests
Docs Changes: documented in proto
Release Notes: updated

Signed-off-by: Stephan Zuercher <zuercher@gmail.com>

### CODE REVIEW

**Comment by zuercher** [comment]
In this [discussion](https://envoyproxy.slack.com/archives/C78HA81DH/p1584737013257300) it was suggested that modifying the host retry predicate to do this would be better.

I think I can modify the LoadBalancerContext interface to allow access to the retry count (the existing `hostSelectionRetryCount` is max retries) and pass that count down to ThreadAwareLoadBalancerContextImpl::HashingLoadBalancer. This would allow a load-balancer-specific adjustment to be made. e.g. in ring hash it might be better to act as if the host were not in the ring and fall through to the next host.

@snowp do you have any thoughts on this?

**Comment by snowp** [comment]
What would the strategy for selecting another host be when using the host predicate? It's a bit unclear to me how you would select another host from the ring if not by modifying the hash function, and if we're modifying the hash function I think it makes sense to do it outside the load balancer?

In general it would be nice if the host retry predicates integrated with the load balancers (better guarantees around selecting a desirable host, less wasted cycles), but its not clear to me how it would help with hashing LBs.

**Comment by zuercher** [comment]
The ThreadAwareLoadBalancer would need to be modified to use `LoadBalancerContext::shouldSelectAnotherHost`. At that point it can either tweak the hash based on attempt count for `ThreadAwareLoadBalancerBase::HashingLoadBalancer::chooseHostOnce(uint64_t)` itself or pass the selection attempt count into the underlying LB (the latter is probably more efficient and would produce better results).

For other LBs, we could pass the attempt count as a second parameter to `chooseHostOnce`.

Pros:
* the ring-hash LB can probably make a better fallback choice with an attempt count (in the current impl, there's some chance that with manipulated hashes it'll still pick the same host over and over).
* enabling this for consistent-hashing LBs via retry predicate vs. hash policy is perhaps more obvious than what I've done in this PR (but I also think we can just document this and be ok)
* In theory this lets the other host retry predicates work for consistent-hashing LBs (though it's not clear they make sense)

Cons:
* I don't think passing attempt count down helps existing non-consistent-hashing LBs: they either choose hosts at random (random, least conn in p2c mode) or they have an ordering and they'll just follow that order (round robin, least conn with weights).
* even for consistent-hashing LBs, on every retry they'll iterate through the same sequence of hosts and will have to retry the hosts that were already attempted

**Comment by snowp** [comment]
I think if we can get this to work with the host predicates that would probably be the better approach, mainly because it seems like the more obvious way to configure this. I think both of the cons you listed holds, but its no worse than what we already have for the other LB strategies (besides the fact that other LBs have some random element, so it might not be the same list of bad hosts every time).

I think if there is a need to avoid iterating over all the bad hosts it should be expressed as passive hc/outlier detection: our mechanism for excluding hosts is to mark them unhealthy, so I think we should be using that to model bad hosts.

I think most of the time these retries will be kicking in before health checking has caught up, so ideally you're not doing this all the time. That said, I'm sure there are cases where this code path is hit on every call, perhaps if some hosts are unable to handle a specific request, but aren't bad enough to trigger hc failure/autotermination/whatever that's supposed to take it out of rotation.

**Comment by zuercher** [comment]
I think I'm going to close this in favor of #10559, which uses the retry host predicate.

**Pull request closed without merging**
