### PR TITLE
examples: Fix deprecations/warnings in configs

### LINKED ISSUE #13467: front-proxy example emits configuration warning on startup
*Description*:
Several helpful examples are provided in the `examples` directory of this project. When running the `examples/front-envoy` example I am observing warnings in the log to do with *Configuration does not parse cleanly as v3.*. 

It would be very helpful for this example to use the most up-to-date config so that new users (such as myself) can create a usable deployment without warnings.

*Repro steps*:
In project:

1. `cd examples/front-proxy`
1. `docker-compose up --build`

Observe the below warning in the log output

*Logs*:
```
front-envoy_1  | [2020-10-09 15:01:12.982][7][warning][misc] [source/common/protobuf/utility.cc:294] Configuration does not parse cleanly as v3. v2 configuration is deprecated and will
 be removed from Envoy at the start of Q1 2021: envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
```

The expectation is that this warning should not be emitted.

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: examples: Fix deprecations/warnings in configs
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #13467
[Optional Deprecated:]

### CODE REVIEW

**Review by mattklein123 — APPROVED** [review]
Great thanks. cc @htuch it would be good to understand why this wasn't failing by default in config checking.

**Comment by phlax** [comment]
@mattklein123 there are some further warnings left, im happy to land this and address after (if tests pass) - or i can go through the remaining ones

**Comment by mattklein123** [comment]
We can just land this. I would still like to understand why we are not failing on these warnings in the config test, but we can look into that separately.

**Comment by moderation** [comment]
There are still dangling references to v2 in the examples. These should be bumped to v3.

```
examples/zipkin-tracing/service2-envoy-zipkin.yaml
17:                "@type": type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
19:                collector_endpoint: "/api/v2/spans"

examples/zipkin-tracing/front-envoy-zipkin.yaml
18:                "@type": type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
20:                collector_endpoint: "/api/v2/spans"

examples/jaeger-native-tracing/front-envoy-jaeger.yaml
18:                "@type": type.googleapis.com/envoy.config.trace.v2.DynamicOtConfig

examples/jaeger-native-tracing/service2-envoy-jaeger.yaml
17:                "@type": type.googleapis.com/envoy.config.trace.v2.DynamicOtConfig

examples/zipkin-tracing/service1-envoy-zipkin.yaml
17:                "@type": type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
19:                collector_endpoint: "/api/v2/spans"
53:                "@type": type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
55:                collector_endpoint: "/api/v2/spans"

examples/jaeger-native-tracing/service1-envoy-jaeger.yaml
45:                "@type": type.googleapis.com/envoy.config.trace.v2.DynamicOtConfig

examples/mysql/envoy.yaml
16:          "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy

examples/redis/envoy.yaml
12:          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProxy

examples/jaeger-tracing/service2-envoy-jaeger.yaml
17:                "@type": type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
19:                collector_endpoint: "/api/v2/spans"

examples/jaeger-tracing/front-envoy-jaeger.yaml
18:                "@type": type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
20:                collector_endpoint: "/api/v2/spans"

examples/jaeger-tracing/service1-envoy-jaeger.yaml
17:                "@type": type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
19:                collector_endpoint: "/api/v2/spans"
54:                "@type": type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
56:                collector_endpoint: "/api/v2/spans"

examples/fault-injection/envoy.yaml
33:              "@type": type.googleapis.com/envoy.config.filter.http.fault.v2.HTTPFault
```

**Comment by phlax** [comment]
@moderation cool, ill update...

**Comment by mattklein123** [comment]
(Would still like to figure out why this is not failing by default)

**Comment by htuch** [comment]
@mattklein123 are you asking:
1. Why aren't we failing in config examples when there is _any_ warning?
2. Why aren't we rejecting v2 configs by default?
For (2), this is on my TODO for the next week. For (1) I don't think we have support but it might make sense to add.

**Comment by phlax** [comment]
see #13542

**Comment by mattklein123** [comment]
I'm fairly sure that (1) has been implemented already for using deprecated fields. I know @alyssawilk fixed this to fail by default at some point, but I'm guessing it's somehow not working for the typed_config warnings for v2 types.

For (2) I'm just suggesting that if we are using a deprecated typed_config we should fail the config_test by default like we do for other deprecated config.

**Comment by phlax** [comment]
@mattklein123 @htuch please can we move to the ticket - rather than a landed PR, thanks

**Pull request merged**
