### PR TITLE
trace overall sampling bugfix

### PR DESCRIPTION
**Pull request by chrisxrepo**
Signed-off-by: Chris Xin xinchuantao@qq.com

Commit Message:
   trace overall sampling support less than 1%

Example:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9090
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          tracing:
            overall_sampling:
              value: 0.1
            provider:
              name: envoy.tracers.zipkin
              typed_config:
                "@type": type.googleapis.com/envoy.config.trace.v3.ZipkinConfig
                collector_cluster: zipkin-cluster
                collector_endpoint: "/api/v2/spans"
                collector_endpoint_version: HTTP_JSON
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: service_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: test_cluster
          http_filters:
          - name: envoy.filters.http.router
            typed_config: {}

  clusters:
  - name: test_cluster
    connect_timeout: 0.250s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: test_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
               address: 127.0.0.1
               port_value: 8000

  - name: zipkin-cluster
    connect_timeout: 1s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: zipkin-service 
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1 
                port_value: 9411
```
if set  overall_sampling=0.1(1/1000), i can not got any trace

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by alyssawilk** [comment]
Beyond CI needing some checks can you add a regression test for the issue you're trying to fix?  thanks!
/wait

**Review by alyssawilk — COMMENTED** [review]
Again I think this doesn't really regression test your change.
Is the problem you're trying to solve a precision issue, where sampling would be off for very small fractions before and works now?  Again if so it'd be good to have a test.
thanks!
/wait

**Comment by chrisxrepo** [comment]
yeah,  i try to solve a precision issue

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
