### PR TITLE
ecds: deprecate top-level stats guard

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

Commit Message: Deprecate and remove stats prefix guard for ECDS.
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes: yes
Fixes: https://github.com/envoyproxy/envoy/issues/23604

### CODE REVIEW

**Comment by kyessenov** [comment]
Flake https://github.com/envoyproxy/envoy/issues/23618
/retest

**Review by jmarantz — DISMISSED** [review]

**Review by jmarantz — COMMENTED** [review]
/assign-from @envoyproxy/senior-maintainers

**Comment by jmarantz** [comment]
needs main merge

/wait

**Review by jmarantz — APPROVED** [review]

**Review by lizan — APPROVED** [review]

**Comment by jmarantz** [comment]
needs main merge; then we should be good to go.

**Review by jmarantz — APPROVED** [review]

**Review by jmarantz — DISMISSED** [review]

**Comment by jmarantz** [comment]
docs failure looks real. snippet:
```
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 1, column 1:
    date: Pending
    ^
expected <block end>, but found '-'
  in "<unicode string>", line 67, column 1:
    - area: eds
    ^
"""

```

**Comment by kyessenov** [comment]
@jmarantz Thanks, git merge did a bad merge, manually fixed it.

**Review by jmarantz — APPROVED** [review]

**Comment by jmarantz** [comment]
please ping me if you see this passes so I can merge before it grows another conflict on the release notes.

**Comment by kyessenov** [comment]
@jmarantz I should be able to merge it with your approval.

**Comment by kyessenov** [comment]
"abandoned" coverage job, restarting

**Pull request merged**
