### PR TITLE
Update validation in Inline DNS table

### LINKED ISSUE #11893: DNS: name length of 2 seems arbitrary
https://github.com/envoyproxy/envoy/blob/master/api/envoy/data/dns/v3/dns_table.proto#L62
has a validation stating that the DNS name length must be atleast 2 characters which seems very arbitrary. Consider a kubernetes pod (or even a local network). It is certainly possible to create services like a, b, c and they can all be resolved using the single character short names, within the k8s namespace, while cross namespace resolution uses a.<ns>, b.<ns>. Yes, it sounds weird but its possible theoretically.

cc @abaptiste

### PR DESCRIPTION
**Pull request by rshriram**
Commit Message:
hostname can be single character when trying to resolve within the local domain. Minimum DNS ttl is set to 30s instead of 60s (30 seems to be the lowest that is allowed)
fixes #11893 

Additional Description:
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by htuch** [comment]
@rshriram can you fix format?
@abaptiste does this make sense to you?

**Comment by abaptiste** [comment]
LGTM.  I don't have an issue with the change.

**Comment by rshriram** [comment]
done

**Comment by htuch** [comment]
@rshriram format is still failing.

**Comment by rshriram** [comment]
fixed it properly this time

**Comment by PiotrSikora** [comment]
@rshriram claims that without this, a lot of DNS stuff is broken.

/backport

**Pull request merged**
