### PR TITLE
router:  add header format support for DOWNSTREAM_LOCAL_PORT

### LINKED ISSUE #10378: Support extracting downstream Port in header variables
*Title*: *Support extracting downstream Port in header variables*

*Description*:

Add support for extracting/injecting Port information of the downstream local address in the header formater. Similarly to %DOWNSTREAM_LOCAL_ADDRESS% and %DOWNSTREAM_LOCAL_ADDRESS_WITHOUT_PORT%, but for Port only.

Our use case: We inject a set of custom headers and heavily rely on envoy to extract/inject information about TLS and downstream addresses into those headers. In order to fully support our scenario we need to be able to extract downstream port information without the downstream address itself.  

[optional *Relevant Links*:]
- https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers.html?highlight=downstream_local_address#custom-request-response-headers

### PR DESCRIPTION
**Pull request by nikolay-pshenichny**
Description:
Adding support for %DOWNSTREAM_LOCAL_PORT% header variable that extracts/injects downstream local Port.
This PR fixes - https://github.com/envoyproxy/envoy/issues/10378

Risk Level: Low
Testing: Unit test
Docs Changes: Updated the related documentation in the same PR

Release Notes:
[Fixes #10378]

### CODE REVIEW

**Comment by zuercher** [comment]
Could you add support in `source/common/access_log/access_log_formatter.c` for access log formatters as well, please? It's open issue to unify these, but until that happens we'd like to keep these synced up.

**Comment by nikolay-pshenichny** [comment]
@zuercher , sure! will try to push an update today.

**Comment by zuercher** [comment]
Thanks!

**Comment by nikolay-pshenichny** [comment]
@zuercher , sorry for the delay. I pushed the changes, please take a look when you have a chance.
I tried following the existing pattern in the `access_log_formatter.cc`, let me know if that's ok or if i should simplify something.

Thank you!

**Comment by zuercher** [comment]
Don't worr about the macOS build -- that failure's not related.

**Pull request merged**
