### PR TITLE
deps: bump boring ssl

### PR DESCRIPTION
**Pull request by tyxia**
Signed-off-by: tyxia <tyxia@google.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@tyxia probs worth co-ordinating with @RyanTheOptimist on this (https://github.com/envoyproxy/envoy/pull/25273)

**Comment by tyxia** [comment]
> @tyxia probs worth co-ordinating with @RyanTheOptimist on this (#25273)

Thanks for info and pointer @phlax! Yes I did reach out to Ryan offline. He ran into the same issue before but the new static_patch from boringSsl team fixed the dependence issue. So I just updated my PR with this patch to see if it will fix my issue as well :)

**Comment by RyanTheOptimist** [comment]
> @tyxia probs worth co-ordinating with @RyanTheOptimist on this (#25273)

Yeah, we chatted internally. I'm not planning to actually land my PR. It's using a *brand* *new* BoringSSL as an experiment for the BoringSSL team to make sure it passes Envoy CI. But it's not the version of BoringSSL that we use in the project as it's ahead of what's used in Chrome. So I think we should proceed with this PR from @tyxia

**Comment by ggreenway** [comment]
We need to wait until after the security release on tuesday feb 7th before merging this.

/wait

**Comment by ggreenway** [comment]
@tyxia should we move forward with this PR?

**Comment by tyxia** [comment]
> @tyxia should we move forward with this PR?

I was thinking wait a bit so that reporting interface in boring ssl is ready. But yes I will take care of boring ssl version bump.

**Pull request closed without merging**
