### PR TITLE
Adding shebang: Using bash shell to interpret the script

### PR DESCRIPTION
**Pull request by truongnh1992**
Signed-off-by: Nguyen Hai Truong <nguyenhaitruonghp@gmail.com>

For an explanation of how to fill out the fields, please see the relevant section 
in [PULL_REQUESTS.md](./PULL_REQUESTS.md)

*Description*:
*Risk Level*:
*Testing*:
*Docs Changes*:
*Release Notes*:
[Optional Fixes #Issue]
[Optional *Deprecated*:]

### CODE REVIEW

**Comment by htuch** [comment]
It would be good to describe the motivation in the commit message. Today, everywhere we use this script, it's sourced via `.`, so doesn't need this.

**Comment by truongnh1992** [comment]
> 
> 
> It would be good to describe the motivation in the commit message. Today, everywhere we use this script, it's sourced via `.`, so doesn't need this.

Hi @htuch, cc: @mattklein123 
I add `#!/usr/bin/env sh` in order to indicate that scripts use **sh** shell for interpreting.

**Comment by htuch** [comment]
I don't think that's a good reason in this case; this script is never intended to be interpreted directly.

**Comment by truongnh1992** [comment]
> I don't think that's a good reason in this case; this script is never intended to be interpreted directly.

Thank you. I will close the PR.

**Pull request closed without merging**
