### PR TITLE
extensions: Shift validator to py checker format

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:  extensions: Shift validator to py checker format
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
coverage is here https://storage.googleapis.com/envoy-pr/16744/tooling/index.html

**Review by moderation — DISMISSED** [review]

**Comment by alyssawilk** [comment]
looks like this needs a main merge but otherwise @htuch can you take a look?

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
