### PR TITLE
mongo_proxy: decode update and delete messages

### PR DESCRIPTION
**Pull request by venilnoronha**
*Description*: This enhances the mongo proxy by decoding OP_UPDATE and OP_DELETE messages and generating useful stats and dynamic metadata.
*Risk Level*: Low
*Testing*: Added/updated several tests
*Docs Changes*: Added new stats to the list
*Release Notes*: Added a note about the change

### CODE REVIEW

**Comment by mattklein123** [comment]
These messages are only used by ancient versions of MongoDB. Do you have an actual use case that requires this? I'm not sure it's worth the churn.

**Comment by venilnoronha** [comment]
I don't have a direct use-case; however, the dynamic metadata can be leveraged within Istio for RBAC.

**Comment by mattklein123** [comment]
My point is I think it's extremely unlikely any user is ever going to hit this case. I don't remember the last version of Mongo to use these messages but it's very old. Definitely older than 2.6.

**Comment by venilnoronha** [comment]
Okay, I don't mind closing this unless someone else finds this useful.

**Comment by mattklein123** [comment]
I would recommend closing this and if you want to spend time on Mongo, I would look at https://github.com/envoyproxy/envoy/pull/5053 and maybe do a follow on PR to that to parse out extra information, as if Mongo moves to using OP_MSG for everything the filter is going to lose a lot of value as is.

**Comment by venilnoronha** [comment]
@mattklein123 will do, thanks!

**Comment by shiponcs** [comment]
What is the status here? Any update on #5053?

**Pull request closed without merging**
