### PR TITLE
Update link of "life of a request"

### LINKED ISSUE #13397: Doc update: "life of a request"
*Title*: Doc update: "life of a request"

*Description*:

* Reading the STYLE doc https://github.com/envoyproxy/envoy/blob/master/STYLE.md
* Has a link to "Life of a Request" which is 404
* Should go to https://github.com/envoyproxy/envoy/blob/master/docs/root/intro/life_of_a_request.rst
* Also that fie has broken images, so the links there need to be updated.

### PR DESCRIPTION
**Pull request by mk46**
Signed-off-by: Manish Kumar <manish.kumar1@india.nec.com>

Commit Message: Updated link of "life of a request" in `STYLE.md`
Additional Description: Updated link of "life of a request" in `STYLE.md`. Currently redirecting to 404. 
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
Fixes #13397

### CODE REVIEW

**Review by phlax — DISMISSED** [review]
lgtm. thanks @mk46 

i think this is the second correction of this link ive seen. im wondering if there are any more/similar

**Comment by htuch** [comment]
Thanks. Grep says there is another in `PULL_REQUESTS.md`, so if you could fix that in this PR it'd be great, thanks!

**Comment by mk46** [comment]
@htuch Thanks for pointing another broken link.

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
