### PR TITLE
repo: Update `protoc-gen-validate` links -> bufbuild

### LINKED ISSUE #23424: Update references `envoyproxy/protoc-gen-validate` -> `bufbuild/protoc-gen-validate`
As the repo has moved we should use the canonical repo reference

### PR DESCRIPTION
**Pull request by phlax**
Fix #23424 

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
this updates all references to the pgv repo, with the exception of those in repository_locations which can be updated here #23347

**Comment by phlax** [comment]
seems as tho the go modules have not been shifted yet

**Comment by phlax** [comment]
it may be that the go deps just have new hashes - either way ive reverted for now

**Comment by phlax** [comment]
this should be good for merge now i think

**Review by RyanTheOptimist — COMMENTED** [review]
/lgtm deps

**Pull request merged**
