### PR TITLE
admin: improve test coverage and increase the coverage-percent threshold

### PR DESCRIPTION
**Pull request by jmarantz**
Commit Message: Adds a missing test for recent lookups now that there are no more fake symbol tables. Adds tests for a variety of override methods defined in admin.h that were previously hard to hit.

Adds a benchmark test to establish a baseline for the speedups in https://github.com/envoyproxy/envoy/pull/19693 
```
------------------------------------------------------------------
Benchmark                        Time             CPU   Iterations
------------------------------------------------------------------
BM_AllCountersText            1760 ms         1760 ms            1
BM_UsedCountersText            118 ms          118 ms            6
BM_FilteredCountersText       4290 ms         4289 ms            1
BM_AllCountersJson            5221 ms         5218 ms            1
BM_UsedCountersJson            152 ms          152 ms            5
BM_FilteredCountersJson       4303 ms         4302 ms            1
```
Additional Description: The downside of having a low test coverage expectation is that it is expressed as a percent, and as the line-count grows the number of lines we allow to go untested grows proportionally, when really we should try to hit all the new lines of code.
Risk Level: low
Testing: //test/...
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Review by junr03 — APPROVED** [review]
lgtm

**Comment by jmarantz** [comment]
Thanks! This does touch some prod code (removing dead code, very simple refactor for testability and a small name change), so  I'll wait for a senior maintainer pass.

/assign-from https://github.com/orgs/envoyproxy/teams/senior-maintainers

**Comment by jmarantz** [comment]
Greg can you do a senior maintainer pass? thanks!

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
