### PR TITLE
build: adding an disable_exceptions (which does not yet work)

### PR DESCRIPTION
**Pull request by alyssawilk**
The new build option simply compiles out all try/catch code, while leaving in the exceptions.   This can not yet be successfully used as it turns up fno-exceptions which chokes on throw statements.  This is by design as if we compiled out throw as well, config failures would be fatal instead of gracefully handled.

Risk Level: low
Testing: manual testing 
Docs Changes: n/a
Release Notes: n/a
Part of https://github.com/envoyproxy/envoy/issues/27412

### CODE REVIEW

**Comment by alyssawilk** [comment]
raven I seem to remember the parity of build options sometimes biting y'all.  This is a no-op by default which I think is what you need but throwing it your way to confirm :-)

**Comment by ravenblackx** [comment]
I think this is unproblematic, because it's both defaulting to disabled *and* also behaving disabled if the config value is entirely unset (which is where we were bitten before). Thanks for thinking of me. :)

**Comment by alyssawilk** [comment]
/wait I think format is broken =P

**Review by RyanTheOptimist — DISMISSED** [review]
Very exciting!

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
