### PR TITLE
hcm: revert to deferred logging

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

Commit Message: Reverts https://github.com/envoyproxy/envoy/pull/12850. There's been multiple changes added on top, so it's not a clean revert. There's a report of significant performance degradation, so this is an attempt to recover while we figure out what's wrong. This will bring back Wasm crash under high load unfortunately https://github.com/envoyproxy/envoy-wasm/issues/615
Additional Description:
Risk Level: medium
Testing: unit
Docs Changes: none
Release Notes: 
Platform Specific Features:

### CODE REVIEW

**Comment by snowp** [comment]
CI seems broken

Do you have any more information about the performance degradation?

**Comment by kyessenov** [comment]
Yes, sorry some tests now need fixing, too :(
The degradation is not easily explainable, so the revert is a quick mediation until it is understood.
cc @jmarantz

**Comment by jmarantz** [comment]
I can't explain yet why this change is a problem, but we have isolated the cause of a degradation in our internal load tests to this PR, and need time to understand and remedy.

**Comment by mattklein123** [comment]
My guess is this is blocking the event loop in a way that it did not before (like causing a delay before bytes get written or something else)? It would be nice to have some better understanding before reverting though?

**Comment by kyessenov** [comment]
Still working on test failures (flakes?)... It's difficult to explain because it requires a load simulation plus a different build of envoy with filters. It doesn't show up on flame charts.

**Comment by jmarantz** [comment]
I understand Matt's concern here. Can we instead make this behavior a command-line flag? We could then revert the flag once we have everything both fast and functional.

**Comment by mattklein123** [comment]
> Can we instead make this behavior a command-line flag?

Prefer runtime if we go this route.

**Comment by jmarantz** [comment]
runtime works for me.

Can you try manually ensuring that tests pass with the runtime setting both ways?

**Comment by kyessenov** [comment]
Sure, I can make it a flag. I'm really confused by fuzzing test failure:

```c++
    #2 0xd0b3f7d in Envoy::StreamInfo::StreamInfoImpl::onRequestComplete() /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/stream_info/_virtual_includes/stream_info_lib/common/stream_info/stream_info_impl.h:116:5
    #3 0xe0f26b0 in Envoy::Http::ConnectionManagerImpl::ActiveStream::completeRequest() /proc/self/cwd/source/common/http/conn_manager_impl.cc:662:32
    #4 0xe0f182f in Envoy::Http::ConnectionManagerImpl::doDeferredStreamDestroy(Envoy::Http::ConnectionManagerImpl::ActiveStream&) /proc/self/cwd/source/common/http/conn_manager_impl.cc:233:10
    #5 0xe0f0d3d in Envoy::Http::ConnectionManagerImpl::doEndStream(Envoy::Http::ConnectionManagerImpl::ActiveStream&) /proc/self/cwd/source/common/http/conn_manager_impl.cc:208:5
    #6 0xe13cc57 in Envoy::Http::ConnectionManagerImpl::ActiveStream::endStream() /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/http/_virtual_includes/conn_manager_lib/common/http/conn_manager_impl.h:256:27
    #7 0xe13d6fc in non-virtual thunk to Envoy::Http::ConnectionManagerImpl::ActiveStream::endStream() /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/http/_virtual_includes/conn_manager_lib/common/http/conn_manager_impl.h
    #8 0xeaeff8d in Envoy::Http::FilterManager::maybeEndEncode(bool) /proc/self/cwd/source/common/http/filter_manager.cc:1134:31
    #9 0xeae2cd8 in Envoy::Http::FilterManager::encodeData(Envoy::Http::ActiveStreamEncoderFilter*, Envoy::Buffer::Instance&, bool, Envoy::Http::FilterManager::FilterIterationStartState) /proc/self/cwd/source/common/http/filter_manager.cc:1094:3
    #10 0xeb001f7 in Envoy::Http::FilterManager::sendLocalReplyViaFilterChain(bool, Envoy::Http::Code, std::basic_string_view<char, std::char_traits<char> >, std::function<void (Envoy::Http::ResponseHeaderMap&)> const&, bool, std::optional<long>, std::basic_string_view<char, std::char_traits<char> >)::$_6::operator()(Envoy::Buffer::Instance&, bool) const /proc/self/cwd/source/common/http/filter_manager.cc:819:13
```

with the following minimal change:

```
diff --git a/source/common/http/conn_manager_impl.cc b/source/common/http/conn_manager_impl.cc
index fb87ebfa1f..b56fa6e1cd 100644
--- a/source/common/http/conn_manager_impl.cc
+++ b/source/common/http/conn_manager_impl.cc
@@ -215,6 +215,10 @@ void ConnectionManagerImpl::doEndStream(ActiveStream& stream) {
   checkForDeferredClose();
 }

+ConnectionManagerImpl::ActiveStream::~ActiveStream() {
+  filter_manager_.destroyFilters();
+}
+
 void ConnectionManagerImpl::doDeferredStreamDestroy(ActiveStream& stream) {
   if (stream.max_stream_duration_timer_) {
     stream.max_stream_duration_timer_->disableTimer();
@@ -230,8 +234,6 @@ void ConnectionManagerImpl::doDeferredStreamDestroy(ActiveStream& stream) {
   stream.filter_manager_.onStreamComplete();
   stream.filter_manager_.log();

-  stream.filter_manager_.destroyFilters();
-
   read_callbacks_->connection().dispatcher().deferredDelete(stream.removeFromList(streams_));

   if (connection_idle_timer_ && streams_.empty()) {
diff --git a/source/common/http/conn_manager_impl.h b/source/common/http/conn_manager_impl.h
index 280f61ab0b..368580e74c 100644
--- a/source/common/http/conn_manager_impl.h
+++ b/source/common/http/conn_manager_impl.h
@@ -156,6 +156,7 @@ private:
                         public ScopeTrackedObject,
                         public FilterManagerCallbacks {
     ActiveStream(ConnectionManagerImpl& connection_manager, uint32_t buffer_limit);
+    ~ActiveStream() override;
     void completeRequest();

     void chargeStats(const ResponseHeaderMap& headers);
```

It looks I hit an assertion in unrelated part of the code, and I can't explain why it is affecting it.

**Comment by kyessenov** [comment]
After thinking more, I split `onStreamComplete` to be called without deferral and `onLog` to be deferred. This way filters can have both options to be invoked with or without deferral.

**Comment by kyessenov** [comment]
h2 fuzzer is still flaking. It seems that stream info is aliased somewhere so that its `onRequestComplete` is called twice.

**Comment by jmarantz** [comment]
Can you merge main? Maybe there was a problem unrelated to the PR that's now been fixed?

**Comment by kyessenov** [comment]
@jmarantz Merging main does not help. I can try looking into h2 fuzzer flake but my knowledge of h2 fuzzing is limited.

**Comment by jmarantz** [comment]
@asraa would you be able to help Kuat with an h2 fuzzing problem in this PR?

**Comment by kyessenov** [comment]
I think this is because `doDeferredStreamDestroy` is called twice on the same stream. There only two places this can happen from in the codec.

**Comment by kyessenov** [comment]
@snowp This a codec issue, but I'm out of my depth in h2 codec. It seems that the guards in determining whether the stream is reset are not correct.

**Comment by asraa** [comment]
The closest I can get is that avoiding the call to `destroyFilters` avoids resetting upstream requests, and like Kuat says, it results in incorrectly deciding the stream hasn't been reset. 
I can't tie this cause and effect together concretely.

**Comment by mattklein123** [comment]
cc @antoniovicente the last few comments. This may or may not be related to a few of the issues we have been discussing recently.

**Comment by kyessenov** [comment]
@antoniovicente Let me know if I can help root causing this further. I think it's fairly reproducible at >50% rate.

**Comment by antoniovicente** [comment]
> cc @antoniovicente the last few comments. This may or may not be related to a few of the issues we have been discussing recently.

I'm not sure what issues you're thinking of, but I spent some time debugging and found some interesting interaction between connections that does result in an attempt to double delete the stream object.  I need to look at the rest of the PR to see if there's something here that makes that issue more likely.

I tried a hack in the the dispatcher that seems to eliminate the issue.  I can try to get that cleaned up and think of other possible edge case interactions which could cause troubles.

**Comment by antoniovicente** [comment]
The difference in performance may be related to changes to logging pattern and that somehow increasing contention on the lock used by AccessLogFileImpl::write

**Comment by yanavlasov** [comment]
> The difference in performance may be related to changes to logging pattern and that somehow increasing contention on the lock used by AccessLogFileImpl::write

It is quite likely. The change make it so a lot of logging is done at the end of the dispatcher iteration rather than logging little by little during iteration.

**Pull request closed without merging**
