### PR TITLE
Throw if client certs are required when using QUIC

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
Since TLS client auth is not currently support with QUIC, add a throw EnvoyException if require_client_certificates is true.

Fixes: #23809

Signed-off-by: Ryan Hamilton <rch@google.com>

Risk Level: Low
Testing: New unit tests
Docs Changes: None
Release Notes: None

### CODE REVIEW

**Review by alyssawilk — COMMENTED** [review]
Thanks for picking this up.  can we throw on config ingress instead?  That way we'd reject the config rather than having a live data plane crash
/wait

**Comment by RyanTheOptimist** [comment]
> Thanks for picking this up. can we throw on config ingress instead? That way we'd reject the config rather than having a live data plane crash /wait

Oh, I thought this was on config ingress as it was creating the Factory. But clearly not. :) Were you thinking this should go in QuicServerTransportSocketConfigFactory::createTransportSocketFactory()? or something else?

**Comment by RyanTheOptimist** [comment]
> > Thanks for picking this up. can we throw on config ingress instead? That way we'd reject the config rather than having a live data plane crash /wait
> 
> Oh, I thought this was on config ingress as it was creating the Factory. But clearly not. :) Were you thinking this should go in QuicServerTransportSocketConfigFactory::createTransportSocketFactory()? or something else?

Hm. After talking to Dan and digging around the code, I still think this is config ingress. That being said to make this a bit clearer I moved the check from the QuicServerTransportSocketFactory constructor to the createTransportSocketFactory() method. I also change the code from RELEASE_ASSERT to throw which seems to be the right way to reject a config, based on some spelunking I did.

I wonder if we should tweak STYLE.md. I read the following advice as suggesting I should treat this invalid config as a fatal error (and hence RELEASE_ASSERT).

  Although we strongly recommend that any type of startup error leads to a fatal error, since this
  is almost always a result of faulty configuration which should be caught during a canary process,
    
In any case, if this is not the right approach I'd welcome any pointers to code I should cargo cult from :)

**Review by alyssawilk — APPROVED** [review]
Awesome, thanks.
cc @envoyproxy/api-shepherds - this rejects prior valid config but to avoid a crash so I think necessary

**Comment by adisuissa** [comment]
Did this previously resulted in a crash or just a feature that was silently ignored?
If this was always crashing, then it implies that no config that supplied that field could have worked, and so this change will not break users.
If, on the other hand, this was silently ignored, then a previously working config may now be rejected. In this case I suggest adding a runtime guard, so users can gradually move the configs.

**Comment by RyanTheOptimist** [comment]
> Did this previously resulted in a crash or just a feature that was silently ignored? If this was always crashing, then it implies that no config that supplied that field could have worked, and so this change will not break users. If, on the other hand, this was silently ignored, then a previously working config may now be rejected. In this case I suggest adding a runtime guard, so users can gradually move the configs.

Ah, yes good point. Previously this did not result in a crash, just silently ignoring the config. As per your suggestion, I switched to a runtime guard. Thanks!

**Pull request merged**
