### PR TITLE
backport: fix lua respond without headers (#22577)

### PR DESCRIPTION
**Pull request by ggreenway**
Signed-off-by: wangkai19 <wangkai19@corp.netease.com>
(cherry picked from commit b43730713621f17a592e931ca34edb114385016b)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by ggreenway** [comment]
This needs a changelog, and probably so does #22577 on main.

**Comment by phlax** [comment]
release branch -> dev PR is here #22962

**Comment by ggreenway** [comment]
This should be merged after #22962. That will cause a merge conflict in release notes.

**Comment by ggreenway** [comment]
@phlax this is hopefully ready to go now

**Review by phlax — APPROVED** [review]
lgtm, thanks @ggreenway

**Pull request merged**
