### PR TITLE
Change the return type of statusCode() in http parser

### PR DESCRIPTION
**Pull request by ZiyangXiao**
Commit Message: I saw there is a TODO for this, so I changed the return type of statuCode() in parser.h and do some related change for this. 
Additional Description:
Risk Level: low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by KBaichoo — APPROVED** [review]
Thanks for cleaning this up!

**Comment by ZiyangXiao** [comment]
Thanks for review @KBaichoo , but I don't know how to trigger the remaining test...would be happy if someone help to do that.

**Comment by KBaichoo** [comment]
@ZiyangXiao  can you try merging main and pushing again? We've been changing the CI and that might help fix it

**Pull request merged**
