### PR TITLE
mobile: Remove the Swift/C++ interop layer

### PR DESCRIPTION
**Pull request by abeyad**
Support for C++ features in the Swift/C++ interop layer is limited (e.g. optionals are not supported).
Part of our effort to reduce the number of copies made of response data between different buffers is
to remove the C types from Envoy Mobile. That requires directly using the C++ types, which becomes
very difficult when using the Swift/C++ interop layer given its limitations in C++ feature support.

Instead, this PR deletes the Swift/C++ interop layer, which does require going through an intermediate
Objective-C layer, but given the excellent support for C++ / Objective-C interop, this is the better
proposition, even if it ends up requiring adding more code for any added API in the Swift APIs.

### CODE REVIEW

**Review by fredyw — APPROVED** [review]
Nice work!

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
