### PR TITLE
ci: Fix yamllint

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by jpsim** [comment]
I wonder why the docs job isn't running anymore 🤔 https://app.circleci.com/pipelines/github/envoyproxy/envoy

@alyssawilk were you able to switch CircleCI's branch to `main` after https://github.com/envoyproxy/envoy/pull/24295 was merged?

**Review by jpsim — APPROVED** [review]
+1 thanks for fixing, although I wonder if the formatting changes caused CircleCI to fail to parse the config since I didn't see it run on this PR 🤔

**Comment by phlax** [comment]
> ... I wonder if the formatting changes caused CircleCI to fail to parse the config since I didn't see it run on this PR thinking

i checked the diff and im reasonably confident that this is the equivalent in terms of data - can we confirm its working elsewhere - i think we need this to stop prs etc from failing

**Comment by jpsim** [comment]
Yes please merge this and we'll sort out the job not running on CircleCI afterwards.

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
