### PR TITLE
dependabot: Updates

### PR DESCRIPTION
**Pull request by phlax**
Commit Message: dependabot: Updates
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by alyssawilk** [comment]
hey @phlax throwing this your way but if you want to dump instructions on how to do checks somewhere I'm happy to be a guinea pig for maintainer-on call doing checks.

**Comment by phlax** [comment]
> if you want to dump instructions on how to do checks somewhere...

not sure iiuc - but atm im happy to keep on top of the python deps - i know which ones are blocked etc and i have a reasonable knowledge of most of the packages

that said - it would be good to have this role codified

i guess its something like

- create a new (WIP) PR for updates if there is not one already
- for any blocked deps - shift these updates to related blocked pr
- for all others run ci with the proposed combination
- close all of the auto prs with a note about where the update is included
- check release notes etc on the deps if necessary
- if ci passes and you think its good to merge the changes - merge
- if not, put some in a block queue and try merging the rest, etc

roughly

**Comment by phlax** [comment]
i guess it could be kinda scripted

**Comment by alyssawilk** [comment]
If you're good with it I'm happy to let you do it :-)

Tossed these instructions in the maintainers doc just in case you want to load shed or we want to address next you're out :-)

**Comment by phlax** [comment]
@alyssawilk i unassigned myself as i cant approve my own pr so i need a maintainer review

**Review by alyssawilk — APPROVED** [review]

**Comment by alyssawilk** [comment]
note to self: do not do github triage before morning caffeine ;-)

**Pull request merged**
