### PR TITLE
bazel: Force python 2 for host tools

### PR DESCRIPTION
**Pull request by keith**
https://github.com/bazelbuild/bazel/issues/8626

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

Risk Level: Low

### CODE REVIEW

**Comment by keith** [comment]
I'm not 100% sure this will work for us, but I want to see what CI thinks

**Comment by mattklein123** [comment]
Do we know where we are not Python 3 compliant? Can we make sure we have an issue to track fixing that? IIRC I thought we could potentially also somehow just force this on specific broken tests which would make it easier to track. cc @lizan

**Comment by lizan** [comment]
@mattklein123 https://github.com/envoyproxy/envoy/pull/7305 was trying to fix it in particular tests but didn't work.

@keith I'm going to merge this to see if bazel ci works. Can you create an issue for tracking?

**Comment by keith** [comment]
https://github.com/envoyproxy/envoy/issues/7342

**Pull request merged**
