### PR TITLE
tools: create //tools/config_validation:textproto2yaml helper

### PR DESCRIPTION
**Pull request by sergiitk**
Commit Message: tools: create //tools/config_validation:textproto2yaml helper
Additional Description: A helper than can convert textproto files to yaml, and format them as `// .. validated-code-block:: yaml` fragments.

Usage example:

```sh
bazel run //tools/config_validation:textproto2yaml -- --as_fragment \
  envoy.config.bootstrap.v3.Bootstrap \
  $PWD/tools/testdata/config_validation/input.textproto
```

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@sergiitk my reservation with this PR is that im strongly discouraging use of `code-block` validated or otherwise for config snippets in the docs - encouraging instead the use of `literalinclude` and full boostrap configs

the reasons being:

- a full (bootstrap) config is almost always more useful to an enduser (ie avoids yaml indent hell)
- in Envoy CI boostrap yaml config files are more fully validated (they are run through a server start in addition to protobuf validation)

**Comment by sergiitk** [comment]
@phlax It seems that the failing presubmit is irrelevant to this change I'm making. Let me know if there's anything else I can to do to help with reviewing this.

**Comment by phlax** [comment]
will review more thoroughly tomorrow...

**Review by phlax — CHANGES_REQUESTED** [review]
@sergiitk thanks for this it looks like a useful addition

i remembered my other aversion `validated-code-block` - it slows down the docs build massively - anyhow i think this is more generally useful than for just creating validate-code-blocks

**Comment by sergiitk** [comment]
Yes, a bit busy at the moment. I'll try to get back to this next week.

**Comment by sergiitk** [comment]
Planning to follow up on this tomorrow.

**Comment by sergiitk** [comment]
Unfortunately, `validate_fragment.py` evolved way to far for this PR to be useful. Most of the refactoring I had is now useless because message parsing / yaml loading is moved to https://github.com/envoyproxy/pytooling/blob/0a6f245fb0f7424e22d9e8dfa6339c944c5584ca/envoy.base.utils/envoy/base/utils/abstract/protobuf.py.

Now it might make more sense to start over and redo this using new APIs provided in `envoy.base.utils`. I'm going to need to find more time to come back to this.

**Pull request closed without merging**
