### PR TITLE
access log: add a benchmark test for the log formatter

### PR DESCRIPTION
**Pull request by brian-pane**
*Description*:
This change adds a benchmark program to measure the speed of the access log formatter. I plan to use it to validate some performance improvements for #2879 that I'll submit as a follow-up PR.

*Risk Level*: Low

*Testing*:
After building, I ran the benchmark program and confirmed that it reported plausible numbers. I also profiled it with `perf` on Linux to verify that the mock objects were not using enough CPU time to overshadow the formatter being tested.

*Docs Changes*: N/A
*Release Notes*: N/A
*API Changes*: N/A

Signed-off-by: Brian Pane <bpane@pinterest.com>

### CODE REVIEW

**Comment by mattklein123** [comment]
@brian-pane cool, LGTM. Can you push an empty commit to try to kick the DCO bot?

**Comment by brian-pane** [comment]
@mattklein123 I pushed a couple of empty commits to try to get the DCO bot to respond, but it's still broken.

**Comment by mattklein123** [comment]
@brian-pane I'm not sure. Just rebase and force push and see if that fixes it. Sigh.

**Comment by brian-pane** [comment]
As less drastic fixes haven't appeased the DCO bot, I'm going to recreate my fork of the repo and generate a new PR.

**Pull request closed without merging**
