### PR TITLE
examples: Fix flask import

### LINKED ISSUE #20037: CI: Verify examples failing
CI: Verify examples failing

*Description*:
See CI runs for the following PRs: [19944](https://dev.azure.com/cncf/envoy/_build/results?buildId=101877&view=results), [19868](https://dev.azure.com/cncf/envoy/_build/results?buildId=101889&view=results), [20017](https://dev.azure.com/cncf/envoy/_build/results?buildId=101918&view=results)

All end with
```
run_examples@ /home/vsts/work/1/s/ci/verify_examples.sh :39 (./locality-load-balancing)
 
 > main@ /home/vsts/work/1/s/ci/verify_examples.sh :44
 
The STDIO streams did not close within 10 seconds of the exit event from process '/bin/bash'. This may indicate a child process inherited the STDIO streams and has not yet exited.


```

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:

Currently verify_examples is failing due to a problem with flask dependencies

I tested this with various versions of flask and all below v2 seem to have the problem - i have therefore updated all the examples to current latest 2.0.3

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #20037
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by KBaichoo — APPROVED** [review]
lgtm (pending CI), thanks for addressing this so quick!

**Review by kfaseela — APPROVED** [review]

**Comment by KBaichoo** [comment]
think we might have missed a spot: 


```
2022-02-18T15:55:01.4164580Z Step 3/7 : RUN pip3 install -q flask
2022-02-18T15:55:01.4439901Z  ---> Running in 1882c74386dd
2022-02-18T15:55:03.4737356Z [91mCommand "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-4844tumf/MarkupSafe/
2022-02-18T15:55:03.6958841Z [0mThe command '/bin/sh -c pip3 install -q flask' returned a non-zero code: 1
2022-02-18T15:55:03.6960504Z Service 'service' failed to build : Build failed
2022-02-18T15:55:03.7889972Z ERROR: starting brotli .
```

**Comment by phlax** [comment]
arrgghh - i tested one of the examples with the updated dep - i hoped it would just work, but a couple of failed, ill debug locally and update...

**Comment by KBaichoo** [comment]
```
[04:29:14] kbaichoo:envoy:0 $grep -ir "pip3 .* Flask" examples/
examples/win32-front-proxy/Dockerfile-service:RUN pip3 install -q Flask==0.11.1 requests==2.18.4
examples/cors/frontend/Dockerfile-service:RUN pip3 install -q Flask==0.11.1
examples/cors/backend/Dockerfile-service:RUN pip3 install -q Flask==0.11.1
examples/csrf/samesite/Dockerfile-service:RUN pip3 install -q Flask==0.11.1
examples/csrf/crosssite/Dockerfile-service:RUN pip3 install -q Flask==0.11.1
examples/load-reporting-service/Dockerfile-http-server:RUN pip3 install -q Flask==0.11.1
examples/cache/Dockerfile-service:RUN pip3 install -q Flask==0.11.1 pyyaml
examples/ext_authz/upstream/service/Dockerfile:RUN pip3 install -q Flask==0.11.1
examples/brotli/Dockerfile-service:RUN pip3 install -q flask
examples/front-proxy/Dockerfile-jaeger-service:RUN pip3 install -q Flask==0.11.1 requests==2.18.4
examples/front-proxy/Dockerfile-service:RUN pip3 install -q Flask==0.11.1 requests==2.18.4
examples/double-proxy/Dockerfile-app:RUN pip3 install -q Flask==0.11.1 requests==2.18.4 psycopg2-binary
examples/gzip/Dockerfile-service:RUN pip3 install -q flask
```

so just gzip and brotli need update?

**Comment by phlax** [comment]
yep, should work now

**Review by KBaichoo — APPROVED** [review]

**Pull request merged**
