### PR TITLE
owners: swapping out some entries

### PR DESCRIPTION
**Pull request by alyssawilk**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by alyssawilk** [comment]
overall gaps:

need maintainer owner:
/*/extensions/filters/http/jwt_authn @taoxuy 
/*/extensions/transport_sockets/tls/cert_validator/spiffe @mathetake @botengyao
/*/extensions/transport_sockets/starttls @cpakulski @botengyao 
/*/extensions/filters/network/sni_cluster @rshriram 
/*/extensions/filters/network/sni_dynamic_forward_proxy @rshriram 
/*/extensions/formatter/metadata @cpakulski

can have non-maintainer owner:
/*/extensions/filters/listener/original_dst @kyessenov
/*/extensions/common/dubbo @wbpcode 
/*/extensions/http/early_header_mutation/header_mutation @wbpcode 
/*/extensions/string_matcher/ @ggreenway 
/contrib/client_ssl_auth/ 
/contrib/dynamo/ 
/*/extensions/rate_limit_descriptors/expr @kyessenov
/*/extensions/matching/input_matchers/runtime_fraction @ravenblackx 
/*/extensions/matching/actions/format_string @kyessenov 
/*/extensions/io_socket/user_space @kyessenov 

wasm:
/*/extensions/access_loggers/wasm @mpwarres 
/*/extensions/bootstrap/wasm @mpwarres 
/*/extensions/filters/http/wasm @mpwarres 
/*/extensions/filters/network/wasm @mpwarres
/*/extensions/common/wasm @mpwarres 
/*/extensions/wasm_runtime/ @mpwarres 
/*/extensions/stat_sinks/wasm @mpwarres

**Comment by alyssawilk** [comment]
cc @sergkir85 Raven suggested you as a reviewer for runtime_fraction - hopefully not a surprise but lmk if you have concerns.

**Comment by lambdai** [comment]
Can I take these two as non-maintainer owner ?
extensions/io_socket/user_space
extensions/filters/listener/original_dst

**Comment by alyssawilk** [comment]
that'd be great, thanks!

**Comment by alyssawilk** [comment]
cc @cpakulski @tyxia

**Review by tyxia — APPROVED** [review]
LGTM, Thanks!

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
