### PR TITLE
fix format on main

### PR DESCRIPTION
**Pull request by alyssawilk**

### CODE REVIEW

**Comment by alyssawilk** [comment]
I think this is broken?  could be PEBKAC

**Comment by PiotrSikora** [comment]
Yeah, it looks that 345ffe37148b7a35b6e8e04db0300463689e3ff1 was wrong (perhaps a different version of `clang-format` running locally?). cc @tonya11en

**Comment by alyssawilk** [comment]
yep, and we already tagged, so it's point release time :-(

**Comment by alyssawilk** [comment]
closing in favor of https://github.com/envoyproxy/envoy/pull/16020

**Pull request closed without merging**
