### PR TITLE
http1: enable reads when final pipeline response received

### PR DESCRIPTION
**Pull request by mattklein123**
Previously we were doing this when we create a new stream, but on
a reused connection this can lead to us missing an upstream
disconnection when the connection is placed back in the pool.

Fixes https://github.com/envoyproxy/envoy/issues/6190

Risk Level: Medium. Scary stuff but well tested.
Testing: Modified existing UT.
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by duderino** [comment]
This is great.   What's the story for http2?

**Comment by alyssawilk** [comment]
H2 doesn't read disable, it marks the stream flow control blocked, and the used window is reclaimed on stream destruction:
https://github.com/envoyproxy/envoy/blob/master/source/common/http/http2/codec_impl.cc#L177

**Comment by iandyh** [comment]
@duderino Hello. Which istio release we are expecting to include this fix? Thank you.

**Comment by ldemailly** [comment]
reminiscing of #1895 and #2715 - hopefully this is the final fix ! 🥂

**Pull request merged**
