### PR TITLE
tooling: Updates (including new check for `RUNTIME_GUARDS`)

### LINKED ISSUE #20211: docs: check that new reloadable flags are mentioned in release notes
any new code with RUNTIME_GUARD should have a corresponding entry in docs/root/version_history/current.rst

### PR DESCRIPTION
**Pull request by phlax**
Fix #20211

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:

Also updates `envoy.base.utils` to use async changelog data, hence hacks on version_history code

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by htuch** [comment]
@phlax which bit is checking for `RUNTIME_GUARD`?

**Comment by phlax** [comment]
the guard check is part of `envoy.code.check` - here https://github.com/envoyproxy/pytooling/blob/main/envoy.code.check/envoy/code/check/abstract/runtime_guards.py

in order to add it i had to refactor the `Project.changelogs` code - which is why this also required an update to docs/version history code - i can separate out that - the only change required to bring the runtime guards check is the upgrade to `envoy.code.check`

**Comment by phlax** [comment]
> i can separate out that 

actually i cant separate that out - the change in base.utils is breaking for code.check so it has to be updated at the same time - ill update the title of the PR...

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
