### PR TITLE
Breaking long word to stop content overflow.

### LINKED ISSUE #10726: docs: content width issue
Page doesn't cover the full width and few big words get out content. 

image

If we increase width then contents cover inside.

### PR DESCRIPTION
**Pull request by mk46**
Signed-off-by: Manish Kumar <manish.kumar1@india.nec.com>

 Fixed #10726

### CODE REVIEW

**Comment by mattklein123** [comment]
Thanks this is great. Do we want to bump the width slightly also? I would be fine with a small increase without going full screen. @moderation @lucperkins wdyt?

**Comment by mk46** [comment]
@mattklein123 Default width is 800px. May I increase it to 1000px or other values?

**Comment by mattklein123** [comment]
@mk46 yeah let's try 1000? @moderation WDYT?

**Comment by moderation** [comment]
In the era of wide screens I'd vote for 1200 but would settle for 1000 as a first try :smile:

**Comment by mattklein123** [comment]
Can you fix DCO? Sorry.

/wait

**Pull request merged**
