### PR TITLE
examples: fix go-control-plane code after API breakage

### PR DESCRIPTION
**Pull request by snowp**
https://github.com/envoyproxy/go-control-plane/pull/475 added a param to NewSnapshot

Signed-off-by: Snow Pettersen <snowp@lyft.com>

Risk Level: Low, example only
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by snowp** [comment]
fyi @alecholmez @Xunzhuo

**Review by phlax — APPROVED** [review]
lgtm pending ci, thanks @snowp

**Comment by alecholmez** [comment]
Ah thank you, I missed the example stuff

**Comment by phlax** [comment]
@snowp this seems to have fixed bringing up g-c-p but not the example itself, not sure why:

https://dev.azure.com/cncf/envoy/_build/results?buildId=83954&view=logs&j=f1a49366-51c0-540f-0294-f73c2bb311a9&t=7fd036c9-61ec-5b59-3645-e90950dc67a6&l=2680

**Comment by snowp** [comment]
Hmm I can't really tell either, perhaps it's failing when cleaning up the Docker network?

/retest

**Comment by phlax** [comment]
its not able to curl the test page afaict - ie envoy's not getting updated or something

**Comment by snowp** [comment]
@phlax I added a sleep and that seems to have done the trick /shrug

**Review by phlax — APPROVED** [review]
wfm, thanks @snowp

**Pull request merged**
