### PR TITLE
Update QUICHE from 74aa2867d to 9e822e949

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
https://github.com/google/quiche/compare/74aa2867d..9e822e949

$ git log 74aa2867d..9e822e949 --date=short --no-merges --format="%ad %al %s"

2022-06-17 haoyuewang Restart bandwidth BOW-response triggered bandwidth resumption experiment.
2022-06-17 haoyuewang Internal change
2022-06-17 wub In QuicConnection::ScopedPacketFlusher::~ScopedPacketFlusher,  early return if connection is disconnected after FlushPackets.
2022-06-17 haoyuewang Inline ShouldDestroySessionAsynchronously as it has only one behavior.
2022-06-15 quiche-dev Automated g4 rollback of changelist 455242321.
2022-06-15 bnc Remove QpackDecodedHeadersAccumulatorResetReason.
2022-06-15 haoyuewang Rename kBWR1 to kBWI1 due to a typo.
2022-06-14 wub Add inplace constructors for QuicheMemSlice and QuicheMemSliceImpl and use them in quic::WriteGfeMemSliceSpanToStream and video_streaming::QuicExternalRequest::WriteBody.
2022-06-14 vasilvv Add a poll(2)-based event loop implementation.
2022-06-14 wub - Remove all experiments that tunes blackhole detection delay or path degrading delay, and - Ensure network blackhole delay is at least path degrading delay plus 2 PTOs.
2022-06-14 bnc Deprecate --gfe2_reloadable_flag_quic_abort_qpack_on_stream_reset.
2022-06-13 quiche-dev Log SNI on QUIC_BUG(quic_crypto_send_buffer_overflow)
2022-06-13 martinduke Attempt to fix an ASAN error in //third_party/quic/core/http:end_to_end_test
2022-06-13 vasilvv Move CongestionControlTypeToString() into quic_types.h header
2022-06-13 quiche-dev Add feature flag to disable Legacy Version Encapsulation in QUIC.
2022-06-13 quiche-dev Fix QUIC connection retransmission stats
2022-06-10 quiche-dev Internal change

Signed-off-by: Ryan Hamilton <rch@google.com>

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
@wu-bin FYI

**Review by wu-bin — COMMENTED** [review]
Thanks Ryan, the MemSlice changes LGTM.

**Review by danzh2010 — APPROVED** [review]

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
