### PR TITLE
Remove Support of hidden_envoy_deprecated_UNSUPPORTED_REST_LEGACY

### PR DESCRIPTION
**Pull request by ankatare**
Signed-off-by: Abhay Narayan Katare <abhay.katare@india.nec.com>

Commit Message: Remove Support of hidden_envoy_deprecated_UNSUPPORTED_REST_LEGACY
Additional Description: Another PR of type remove_v2_support. first PR is #16274
Risk Level: LOW
Testing: bazel test on test/common/config/..
Docs Changes: NA
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by ankatare** [comment]
@tyxia PTAL
cc @htuch

**Comment by tyxia** [comment]
> @tyxia PTAL
> cc @htuch

Thanks for working on this! 

@htuch and I have discussed about this before and we have decided to keep this code. We want to keep this exception to force graceful rejection to any invalid configuration.  

Later when we get rid of generated_api_version we can then either use a PGV annotation or the DEPRECATED_AND_UNAVAILABLE_DO_NOT_USE name to perform such rejection.

So this PR can be closed. Please let me know if you have any questions. Thanks!

**Comment by ankatare** [comment]
@tyxia Ok and thanks for quick review. Just waiting signal from @htuch to decide.

**Comment by mattklein123** [comment]
Instead of just closing the PR, can you revert the code change and add a comment so that someone doesn't come along and try deleting it again?

/wait

**Comment by tyxia** [comment]
> Instead of just closing the PR, can you revert the code change and add a comment so that someone doesn't come along and try deleting it again?
> 
> /wait

I agree. Good idea!

**Comment by tyxia** [comment]
> @tyxia Ok and thanks for quick review. Just waiting signal from @htuch to decide.

Hi @ankatare, I think we don't need to wait for the signal from @htuch as he already made the call in the other PR here #17804

As @mattklein123 suggested, Could you go ahead to add the comment to explain why we want to keep it? The comment could be something like `Keep this exception to force graceful rejection to any invalid configuration. Later when we get rid of generated_api_version, we can then either use a PGV annotation or the `DEPRECATED_AND_UNAVAILABLE_DO_NOT_USE` name to perform such rejection`.

Thanks!

**Comment by ankatare** [comment]
> Instead of just closing the PR, can you revert the code change and add a comment so that someone doesn't come along and try deleting it again?
> 
> /wait

@mattklein123 Sure. Will do it ASAP

**Comment by ankatare** [comment]
> > @tyxia Ok and thanks for quick review. Just waiting signal from @htuch to decide.
> 
> Hi @ankatare, I think we don't need to wait for the signal from @htuch as he already made the call in the other PR here #17804
> 
> As @mattklein123 suggested, Could you go ahead to add the comment to explain why we want to keep it? The comment could be something like `Keep this exception to force graceful rejection to any invalid configuration. Later when we get rid of generated_api_version, we can then either use a PGV annotation or the DEPRECATED_AND_UNAVAILABLE_DO_NOT_USE name to perform such rejection`.
> 
> Thanks!

@tyxia Sure.

**Comment by ankatare** [comment]
seems some local git issues. please DO NOT review it. i will push changes again ASAP.

**Comment by ankatare** [comment]
@tyxia i need your help to revert changes as suggest by @mattklein123 . please ping me on slack as soon you are avilable

**Comment by tyxia** [comment]
> @tyxia i need your help to revert changes as suggest by @mattklein123 . please ping me on slack as soon you are available

I don't see your message in the slack...
What is your issue with revert? In general, for staged files you can `git reset HEAD <file>…`​ to unstage. I guess your issue is with the change has been pushed, you can `git checkout HEAD^ -- /path/to/file` to previous version OR `git checkout [commit-ref] -- /path/to/file` to specified version.

Take a look at links below and hope they help:
https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things
https://stackoverflow.com/questions/18357511/git-remove-committed-file-after-push/18357621
https://stackoverflow.com/questions/215718/how-can-i-reset-or-revert-a-file-to-a-specific-revision

**Comment by ankatare** [comment]
@tyxia thanks for your comments and help .. i am not well from couple of days :( . I will do it tomorrow !!!

**Comment by ankatare** [comment]
@tyxia I am really sorry for delay. just wondering i can see commit e59db5baae506ad6de16dabd23ab24079b4cfaa3 with same commit message, have you done this already  ?

**Comment by htuch** [comment]
Can you merge with https://github.com/envoyproxy/envoy/pull/18091?

**Comment by tyxia** [comment]
> @tyxia I am really sorry for delay. just wondering i can see commit [e59db5b](https://github.com/envoyproxy/envoy/commit/e59db5baae506ad6de16dabd23ab24079b4cfaa3) with same commit message, have you done this already ?

I haven't done this yet but I am happy to do this PR if you are OK. Just let me know :)

**Comment by ankatare** [comment]
@tyxia Thanks. Let me check this now. I will ping you to take further if found any issues.

**Comment by ankatare** [comment]
seems this is already incorporated by @htuch in commit `b0e15260326d0d6175bc2271fb712f2f1efb029e`.  so we can close this issue now.

**Comment by ankatare** [comment]
closing this PR  as code changes done already.

**Pull request closed without merging**
