### PR TITLE
router: removing envoy.reloadable_features.outlier_detection_support_for_grpc…

### LINKED ISSUE #8845: envoy.reloadable_features.outlier_detection_support_for_grpc_status deprecation
#7942 (Outlier Detection: use gRPC status code for detecting failures) introduced a runtime guarded feature. This issue tracks source code cleanup.
cc @ZhouyihaiDing

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: Low (deprecated since October)
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
fixes #8845

### CODE REVIEW

**Comment by alyssawilk** [comment]
As an aside to @envoyproxy/maintainers do we think we should have warnings for folks potentially setting runtime guards to false?  I feel like we have enough documentation for each guard "this is going away" and "this is temporary", and they're mainly in case anyone has an issue, that I'm inclined to not bother until/if someone complains, but it occurred to me to ask.

**Comment by mattklein123** [comment]
> but it occurred to me to ask.

I think this would be a really nice thing to do, but I don't think it should block the cleanups. Maybe track as an issue?

**Comment by alyssawilk** [comment]
SG, will do as a follow-up and add these 2 in

**Comment by alyssawilk** [comment]
oh nice catch - I usually discourage documenting the transient guards.  Fixed!

**Comment by asraa** [comment]
Thank you!

**Pull request merged**
