### PR TITLE
tls-tests: updating the auto-generated certs for TLS tests

### LINKED ISSUE #35780: Certificate creation script for TLS test data is broken
Currently some tests in the TLS directory are failing. Example:
```
Executing tests from //test/common/tls:context_impl_test
...
[ RUN      ] SslContextImplTest.TestExpiringCert
unknown file: Failure
C++ exception with description "bad_optional_access" thrown in the test body.
...
```
and:
```
Executing tests from //test/common/tls/cert_validator:default_validator_test
...
[ RUN      ] DefaultCertValidatorTest.WithVerifyDepth
[test/common/tls/cert_validator/default_validator_test](http://test/common/tls/cert_validator/default_validator_test).cc:667: Failure
Expected equality of these values:
  X509_verify_cert(store_ctx.get())
    Which is: 0
  1
Stack trace:
  0x2086e56: Envoy::Extensions::TransportSockets::Tls::DefaultCertValidatorTest_WithVerifyDepth_Test::TestBody()
  0x549646b: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x5485a7a: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x54714e3: testing::Test::Run()
  0x5471e94: testing::TestInfo::Run()
... Google Test internal frames ...

[test/common/tls/cert_validator/default_validator_test](http://test/common/tls/cert_validator/default_validator_test).cc:668: Failure
Expected equality of these values:
  X509_STORE_CTX_get_error(store_ctx.get())
    Which is: 10
  0
Stack trace:
  0x2086fe8: Envoy::Extensions::TransportSockets::Tls::DefaultCertValidatorTest_WithVerifyDepth_Test::TestBody()
  0x549646b: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x5485a7a: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x54714e3: testing::Test::Run()
  0x5471e94: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] DefaultCertValidatorTest.WithVerifyDepth (361 ms)
...
```

I've tried to update the certs by running [certs.sh](https://github.com/envoyproxy/envoy/blob/main/test/common/tls/test_data/certs.sh) which failed because large negative days are not supported. This is easy to fix (modifying the `days` argument to "-1" instead of "-365").

However, there's a problem that now the certs.sh script doesn't create the entirely required output.
Specifically #35513  added `TEST_*_CHAIN_*_HASHES` in https://github.com/envoyproxy/envoy/blob/e37ffcf469495562139abe8db9320df531a69c56/test/common/tls/test_data/no_san_cert_info.h#L6C16-L6C49 that do not exist after executing the script.
Need to automatically create these fields.

### PR DESCRIPTION
**Pull request by adisuissa**
Commit Message: tls-tests: updating the auto-generated certs for TLS tests
Additional Description:
Some tests are broken due to out of date. Previous refresh was in #22792.
Most changes were the output of `test/common/tls/test_data/certs.sh`.
3 non-automatic modifications:
1. `test/common/tls/test_data/certs.sh` - updated because openssl x509 days argument no longer accepts days that are < -1.
2. `test/common/tls/ssl_socket_test.cc` - introduced new fields that are not automatically generated. Fixed the tests to 
fetch the info from the source of truth.
3. `test/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator_test.cc` - a test has exact expectations on the dates in the certificates.

Need to think about [Matt's comment](https://github.com/envoyproxy/envoy/pull/22792#issuecomment-1224375364) and see if we can avoid checking in the certs.

Risk Level: low - tests only
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
Fixes #35780

### CODE REVIEW

**Review by jmarantz — APPROVED** [review]

**Review by tyxia — APPROVED** [review]
Thanks!

**Comment by phlax** [comment]
@adisuissa there is a ticket to address the committed certs here https://github.com/envoyproxy/envoy/issues/23912

i just didnt get round to looking at it yet

i think this needs ...

/backport

**Comment by adisuissa** [comment]
> @adisuissa there is a ticket to address the committed certs here #23912
> 
> i just didnt get round to looking at it yet
> 
> i think this needs ...
> 
> /backport

Yep... it needs to be backported.
I can do that (essentially I think it should contain all the changed files other than the `test/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator_test.cc` modifications. LMK if you want me to take point on this.

**Comment by phlax** [comment]
i backported it already as it was failing branch ci - not 100% if i did it correctly but it seems to have worked on all but 1.28

fwiw only 1.30 and 1.31 were actually failing so not clear whether it was needed on 1.28 (or 1.29)

**Pull request merged**
