### PR TITLE
SMTP Network Filter in Envoy contrib

### PR DESCRIPTION
**Pull request by VishalDamgude**
Commit Message: Smtp Network Filter in contrib

Additional Description: 
This smtp network filter has been developed as per RFC 5321 (https://www.rfc-editor.org/rfc/rfc5321) and supports STARTTLS extension. It will parse SMTP commands and responses as per the SMTP protocol and provide protocol specific metrics.
The downstream starttls is supported by default. When smtp client sends STARTTLS, the filter will start secure transport on downstream connection. The upstream encryption is configurable. If enabled and if TLS handshake fails during upstream TLS negotiation, the filter responds to the client with error and closes the connection. If upstream TLS handshake succeeds, both the downstream and upstream connections are encrypted for secure smtp mail transfer.

Risk Level: Low
Testing: Unit, Manual testing
Docs Changes:
Release Notes:
Platform Specific Features: No
[Optional Runtime guard:]
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/24219
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by cpakulski** [comment]
@VishalDamgude It seems that DCO signature is missing. Please refer to https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md#dco-sign-your-work. I suggest that you install hooks, so it is automatically added each time you do a commit.

**Comment by VishalDamgude** [comment]
Hi @cpakulski @wbpcode ,
Will create another PR. Closing this one. It seems the branch is all messed up while adding DCO signature.

**Comment by cpakulski** [comment]
I was about to suggest closing and opening a new one ... Thanks.

**Pull request closed without merging**
