### PR TITLE
http: move HTTP Datagram support check to constructor.

### PR DESCRIPTION
**Pull request by jeongseokson**
Commit Message:
Moved the runtime flag check for HTTP Datagram support to QUIC session constructors. This will eliminate the repeated runtime flag check, saving some CPU cycles.
Additional Description:
Risk Level: Low, the change is protected with the runtime flag.
Testing: Existing unit tests and integration tests cover this change.
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by jeongseokson** [comment]
/assign @danzh2010

Hi Dan, can you review this PR? Thank you!

**Review by danzh2010 — APPROVED** [review]

**Comment by jmarantz** [comment]
Please merge main & fix CI. Thanks!

/wait

**Comment by adisuissa** [comment]
Assigning Greg as !Google and senior-maintainer reviewer.
/assign @ggreenway

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
