### PR TITLE
uhv: add http-parser permissive parsing for h1 codec

### LINKED ISSUE #19750: uhv: http-parser: add option to skip header validation
As part of the unified header validation component, the http-parser library will be modified to add an option to disable header validation on a per-request basis. The intent is that header validation will be performed by the UHV and not by each codec / library. 

http-parser currently controls how header validation is performed on the compile-time [`HTTP_PARSER_STRICT`](https://github.com/nodejs/http-parser/blob/main/http_parser.h#L50) preprocessor definition, which is enabled by default. This issue will change http-parser to make this configurable at runtime via a new option.

This is blocked until #19749 is completed.

### PR DESCRIPTION
**Pull request by ameily**
Commit Message: uhv: add http-parser permissive parsing for h1 codec

Additional Description: Honor the new `uhv_enabled` build flag to disable strict parsing within the H1 parsing library (http-parser). This is a reworking of the previous PR, #20528, but this time using the new compile-time option instead of making it configurable at runtime.

Risk Level: Low

Testing:

Docs Changes:

Release Notes:

Platform Specific Features:

Fixes #19750

### CODE REVIEW

**Comment by ameily** [comment]
@yanavlasov This should be good for review.

**Review by yanavlasov — APPROVED** [review]

**Comment by yanavlasov** [comment]
@alyssawilk this is special UHV build for H/1 parser with header validation disabled, using existing #define

**Comment by ameily** [comment]
@alyssawilk I have confirmed that removing the early `return` in both `protocol_integration_test` and `http_inspector_test` results in both failing when UHV is enabled:

```
[  FAILED  ] Protocols/DownstreamProtocolIntegrationTest.BadRequest/IPv4_HttpDownstream_HttpUpstreamNghttp2NoDeferredProcessing
[  FAILED  ] HttpInspectorTest.MultipleReadsHttp1BadProtocol (156 ms)
```

**Review by alyssawilk — APPROVED** [review]
Awesome, thanks for confirming.
cc @snowp for !Googler pass

**Review by snowp — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
