### PR TITLE
tools: remove unused buildozer in check_format.py

### PR DESCRIPTION
**Pull request by spacewander**
Commit Message: remove unused buildozer in check_format.py
Additional Description:
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by phlax — COMMENTED** [review]
i believe this is required by the `envoy_build_fixer.py` script

**Comment by spacewander** [comment]
The CI failure is caused by the network problem:
```
ERROR: An error occurred during the fetch of repository 'com_github_unicode_org_icu':
   Traceback (most recent call last):
	File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/unicode-org/icu/archive/release-72-1.tar.gz] to /build/bazel_root/base/external/com_github_unicode_org_icu/temp18178779363271786173/release-72-1.tar.gz: java.net.SocketTimeoutException: Read timed out
```
https://dev.azure.com/cncf/envoy/_build/results?buildId=144633&view=logs&jobId=8c169225-0ae8-53bd-947f-07cb81846cb5&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=4d0399a5-fd0d-5446-d022-32daa00183cc

**Comment by spacewander** [comment]
> i believe this is required by the `envoy_build_fixer.py` script

Got it. Thanks!

**Comment by phlax** [comment]
> The CI failure is caused by the network problem:

its caused by a failure of the "cache-warming" run - i have kicked it

**Pull request closed without merging**
