### PR TITLE
[WIP] python: Set line length to 80 chars

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: python: Set line length to 80 chars
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by mattklein123** [comment]
I will defer to @htuch and you to sort this out, but it's 2021, do we really need to do 80? Can we do 100 like the C++ code? That would be my preference. :)

**Comment by phlax** [comment]
> it's 2021, do we really need to do 80?

80 is the standard - perhaps originally from a legacy of low resolution consoles - but i think adopted in python more to discourage overly-nested code

i vote 80, but happy to keep/implement/go with the consensus

i raised this pr mostly to get the autoformat fixes and see what it would do

**Comment by phlax** [comment]
also even if we do go with this change, i would like to finish other linting issues first

**Comment by htuch** [comment]
@phlax my vote would be to go with 100 for consistency with C++; this is basically an opinionated decision Envoy has made that is inconsistent with everyone else anyway. 

I'd be persuaded otherwise if there are implications of not doing 80 in terms of tooling or IDEs.

It's not a hill I'm going to die on though :)

**Comment by phlax** [comment]
closing as it seems the consensus is to keep the 100 limit

**Pull request closed without merging**
