### PR TITLE
cryptomb: fix poll delay being set to zero if it is shorter than 1 ms in the config

### PR DESCRIPTION
**Pull request by VillePihlava**
Commit Message:

Change API to require cryptomb poll delay values to be set to at least 1ms.

Additional Description:

Setting the poll delay value of cryptomb to a value smaller than 1 ms previously meant that the poll delay was set to 0. The poll delay should be a value greater than 0 and at least 1ms. I changed the API to only allow poll delay values greater than or equal to 1ms.

Risk Level: Low
Testing: Unit tests, manual tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: CryptoMb private key provider requires Intel 3rd generation Xeon Scalable server processor for the AVX-512 IFMA instruction set.

### CODE REVIEW

**Review by ipuustin — APPROVED** [review]
The fix itself looks good to me. However one thing I'm missing is why the poll delay <1ms gets zeroed out -- is it due to a conversion or does the timer lack granularity or what happens? I'm just thinking could this affect also other parts of the codebase.

**Comment by VillePihlava** [comment]
I think the reason is this:

https://github.com/envoyproxy/envoy/blob/658f789529f538f25bcceefc5b075ff09d8ecb84/contrib/cryptomb/private_key_providers/source/cryptomb_private_key_provider.cc#L527-L528

It converts the poll delay value duration into milliseconds and when a duration <1ms is given it outputs a zero. When the poll delay in milliseconds gets converted to microseconds later on it is already zero.

Another option for this fix would be to convert the poll delay to microseconds if that is necessary but 1ms is probably a short enough shortest value.

**Review by KBaichoo — APPROVED** [review]
looks good, thanks

**Pull request merged**
