### PR TITLE
support Apache SkyWalking tracer v8.6.0

### PR DESCRIPTION
**Pull request by Shikugawa**
Signed-off-by: Shikugawa <rei@tetrate.io>

Commit Message: This PR updates cpp2sky to 0.2.2 and enable to use Apache SkyWalking v8.6.0
Additional Description:
Risk Level: Low
Testing: N/A
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by moderation** [comment]
Dependencies look OK but CI is failing on SkyWalking tests
/lgtm deps

**Review by moderation — COMMENTED** [review]
Dependencies look OK but your CI SkyWalking tests are failing

**Comment by Shikugawa** [comment]
@lizan Could you take a look?

**Comment by moderation** [comment]
LGTM from a deps point of view. Will need @lizan or senior maintainer to merge.

**Review by lizan — APPROVED** [review]

**Pull request merged**
