### PR TITLE
mobile: Remove support for YAML in the mobile APIs

### PR DESCRIPTION
**Pull request by abeyad**
As part of this change, a new EngineBuilder `setUpstreamTlsSni()` API was added for all the language bindings,
so that the upstream TLS socket's SNI can be overridden for test servers where the cert is created with a particular
hostname but we don't access the server via that hostname (instead, we use local address and local port).

### CODE REVIEW

**Comment by abeyad** [comment]
yes, sorry, i'm still working on figuring out the QuicTestServerTest and put it on the backburner Friday for other stuff.  I didn't realize this was assigned to you, let me reassign to myself until its ready

**Comment by fredyw** [comment]
It looks like the CI is still failing.
/wait on CI

**Review by fredyw — DISMISSED** [review]
Nice! Thanks for working on this.

**Review by fredyw — DISMISSED** [review]

**Review by fredyw — APPROVED** [review]

**Pull request merged**
