### PR TITLE
conn_handler: extend filter status to include StopIterationAndWaitForData

### LINKED ISSUE #35079: How to deal with maxReadBytes appropriately when adding listener filters after tls inspector?
*Title*: *How to deal with maxReadBytes appropriately when adding listener filters after tls inspector?*

*Description*:

I have a use case that several listener filters are added after tls inspector, and these listener filters don't need to peek any data, but only need to return `Network::FilterStatus::StopIteration` in `Filter::onAccept`, wait for asynchronous response from some other services, and resume when response is ready.
https://github.com/envoyproxy/envoy/blob/caaafa1ca69b10ed0c56739f64885259e7bae65a/source/common/listener_manager/active_tcp_socket.cc#L121-L133
The `maxReadBytes` of tls inspector is `TLS_MAX_CLIENT_HELLO` by default, and can be adjusted dynamically by setting `initial_read_buffer_size` in proto config. In order for these listener filters to wait for response by returning `StopIteration`, `maxReadBytes` of them must be set to `TLS_MAX_CLIENT_HELLO`, or even need to be synced dynamically with result of `requested_read_bytes_` of tls inspector when `initial_read_buffer_size` is set, so that it doesn't break below assertion.
https://github.com/envoyproxy/envoy/blob/caaafa1ca69b10ed0c56739f64885259e7bae65a/source/common/listener_manager/active_tcp_socket.cc#L85-L92

May I know what is the suggestion on dealing with `maxReadBytes` for listener filters which don't need to peek any data but need to wait for asynchronous response from other services? Can I also get some advice from you @soulxu? Since I see your discussions and contributions around `ListenerFilterBufferImpl`, Thanks.

### PR DESCRIPTION
**Pull request by zhaoyangli311**
Commit Message: extend filter status to include StopIterationAndWaitForData
Additional Description: For listener/network filters, currently there are 2 filter status, `Continue` and `StopIteration` respectively.
And especially for listener filters, a `ListenerFilterBufferImpl` is shared by all listener filters which need to read data on the wire. So there are several cases can be covered as below by adding a new filter status StopIterationAndWaitForData.

- `Continue`: Filter continues to execute
- `StopIteration`: Filter which is not interested in data on the wire, stops executing and waits for callback to recover execution
- `StopIterationAndWaitForData`: Filter needs to read data and share `ListenerFilterBufferImpl`

Risk Level: low
Testing: unit test and manual test
Docs Changes:
Release Notes: N/A
Platform Specific Features: N/A
Fixes #35079

### CODE REVIEW

**Comment by zhaoyangli311** [comment]
/assign @soulxu 

Could you please take a look? This PR solves the problem mentioned in linked issue

**Comment by wbpcode** [comment]
I think after `StopIteration` is returned, the data will still be read and the onData() will be called again?

**Comment by zhaoyangli311** [comment]
Yes that's the current behavior. However, my use case is that there are several listener filters which may need to wait for asynchronous response in onAccept, and they are not interested in onData. Adding a new filter status which separates different use cases not only helps with some maxReadBytes() issues but also eliminates unnecessary data peek

**Comment by wbpcode** [comment]
Thanks for your contribution. I taken a quick check to the original requirement and your current implementation.

First, we shouldn't change the behavior of `FilterStatus::StopIteration` directly. In most of cases, if we want to change our API/behavior, we will hope the change result in the third-parties' forks compile error (or guard it with runtime flag if possible). The compile error could force the forks to fix their code. And this PR introduced a key behavior change quietly which is not recommended.

Second, considering the Network::FilterStatus is shared by listener filter and network filter, and the new status make no sense for our network filters for now (but will bring much more confusion to our developers/readers). Rather than adding new status, I will recommend to enhance the `ListenerFilterBufferImpl` to handle the special case where listener filter wants to stop filter chain but needn't any more data.

**Review by wbpcode — CHANGES_REQUESTED** [review]
Thanks for your contribution. I taken a quick check to the original requirement and your current implementation.

First, we shouldn't change the behavior of `FilterStatus::StopIteration` directly. In most of cases, if we want to change our API/behavior, we will hope the change result in the third-parties' forks compile error (or guard it with runtime flag if possible). The compile error could force the forks to fix their code. And this PR introduced a key behavior change quietly which is not recommended.

Second, considering the `Network::FilterStatus` is shared by listener filter and network filter, and the new status make no sense for our network filters for now (but will bring much more confusion to our developers/readers). Rather than adding new status, I will recommend to enhance the `ListenerFilterBufferImpl` to handle the special case where listener filter wants to stop filter chain but needn't any more data.

**Comment by wbpcode** [comment]
cc @soulxu

**Comment by zhaoyangli311** [comment]
Thanks for your suggestions. Then does that mean

1. There is no plan to decouple listener and network filter/filter status
2. Network filter status can't be extended as Http filter status

Please also let me know if I need to create a new PR to handle special case, thanks!

**Comment by wbpcode** [comment]
Resp to 1: Yeah, for now, we have no related plan. But it's possible if there is a very strong reason.
Resp to 2: It's possible to extend the network filter status. But there should be a strong reason and the extension shouldn't break exist behavior.

> Please also let me know if I need to create a new PR to handle special case, thanks!

Feel free to create new PR or change current PR.

**Comment by soulxu** [comment]
> Thanks for your contribution. I taken a quick check to the original requirement and your current implementation.
> 
> First, we shouldn't change the behavior of `FilterStatus::StopIteration` directly. In most of cases, if we want to change our API/behavior, we will hope the change result in the third-parties' forks compile error (or guard it with runtime flag if possible). The compile error could force the forks to fix their code. And this PR introduced a key behavior change quietly which is not recommended.
> 

For our API (xds API) yes, it shouldn't be changed with incompatible way. But for the extension interface, I remember I asked this question long time before, we doesn't have a strong rule for it. Just like I rewrite the listener filter interface, it already change the interface. But yes, I guess we should avoid break people's code without strong reason. Just discussion case by case I guess.

If we don't think this is worth to change the ext interface, then this can be an option https://github.com/envoyproxy/envoy/issues/35079#issuecomment-2212776709

**Comment by wbpcode** [comment]
Yeah, we actually have no strong rules about the code/binary interface. But basically big or key behavior change should be avoided if possible. Or at least we should guard it by a runtime flag.

And specific to this problem/requirement, I think enhance the listener buffer is a not bad choice, esp compared to adding a new enum value directly or adding a new status type for listener filter.

**Comment by zhaoyangli311** [comment]
Enhancing listener buffer looks like a better idea, I create a new PR which better describes the change https://github.com/envoyproxy/envoy/pull/35394

**Comment by soulxu** [comment]
@zhaoyangli311 If we are going to https://github.com/envoyproxy/envoy/pull/35394, then we can close this PR.

**Pull request closed without merging**
