### PR TITLE
format fix 

### PR DESCRIPTION
**Pull request by zhangbo1882**
tools/code_format/check_format.py fix

### CODE REVIEW

**Comment by adisuissa** [comment]
This tool is being run by CI.
If you have different results, it may be due to not using the right clang version.
I'm using Clang v12, and don't receive these diffs. Can you check on your end?
/wait

**Comment by zhangbo1882** [comment]
> This tool is being run by CI. If you have different results, it may be due to not using the right clang version. I'm using Clang v12, and don't receive these diffs. Can you check on your end? /wait

Thanks. @adisuissa . After the clang-format is upgraded to clang-format-12, the issue is gone. 
Can we add this information in some doc so that the beginner can avoid such issue in future

**Comment by phlax** [comment]
>  Can we add this information in some doc so that the beginner can avoid such issue in future

@zhangbo1882 there is some info here already:

https://github.com/envoyproxy/envoy/tree/main/bazel

its probably not very explicit about versions etc - so if you wanted to raise a pr to clarify that would be helpful i think

its not the first time i have seen these changes in a PR and may have even raised one myself as a result of similar confusion

**Comment by zhangbo1882** [comment]
> > Can we add this information in some doc so that the beginner can avoid such issue in future
> 
> @zhangbo1882 there is some info here already:
> 
> https://github.com/envoyproxy/envoy/tree/main/bazel
> 
> its probably not very explicit about versions etc - so if you wanted to raise a pr to clarify that would be helpful i think
> 
> its not the first time i have seen these changes in a PR and may have even raised one myself as a result of similar confusion

Thanks @phlax , I will try to raise a PR to add more in the doc https://github.com/envoyproxy/envoy/tree/main/bazel,

**Comment by zhangbo1882** [comment]
raise a PR for doc modification. https://github.com/envoyproxy/envoy/pull/20197

**Pull request closed without merging**
