### PR TITLE
Revert "Fixes #2943 - implements shared grpc connection per multiple …

### LINKED ISSUE #2943: Optimize EDS stream allocation
Today, EDS attempts to open one stream per cluster to the management server when not being multiplexed over ADS. EDS streams support subscribing to more than one cluster, so this should not be necessary if the `ApiConfigSource` points to the same management server.

This is actually very noticeable when we have a large number of clusters. It shows up as stream resource exhaustion in H2 (https://github.com/envoyproxy/envoy/issues/2941) as well as in internal performance benchmarks of configuration scalability.

The fix seems pretty easy, just need to do some level of aggregation similar to what ADS does.

### PR DESCRIPTION
**Pull request by adilhafeez**
*Description*:

While rolling out envoy/master at Lyft we found out that xDS was having issues making outbound grpc calls to fetch cluster information. We are still investigating the root case. This commit seems to be the suspect.

This reverts commit a08597467917c3d982755ea45075e05106b92dd7.

*Risk Level*: Low
*Testing*: tested on lyft staging environment
*Docs Changes*: n/a
*Release Notes*: n/a

Signed-off-by: Adil Hafeez <ahafeez@lyft.com>

### CODE REVIEW

**Comment by zuercher** [comment]
Please fill out the PR as described in https://github.com/envoyproxy/envoy/pull/PULL_REQUESTS.md -- I'm not sure why you want to revert this commit.

**Comment by zuercher** [comment]
@adilhafeez please amend your commit to have the DCO signoff. Adding text in the form `Signed-off-by: your name <youremail@example.com>` is sufficient.

**Comment by mattklein123** [comment]
@adilhafeez @lita @junr03 @tonya11en has this commit been verified to be faulty via bisecting/revert? Has any basic debugging been done? If we know this commit is faulty we can revert but it would we should 100% confirm this commit is at fault.

**Comment by adilhafeez** [comment]
We did verify this as faulty commit in staging today. We can go ahead and
merge it.

**Comment by narehayrapetyan** [comment]
@mattklein123 this commit caused a stream of 503 no healthy upstream hosts which stopped when we reverted this commit.

**Comment by mattklein123** [comment]
cc @dmitri-d that we are reverting https://github.com/envoyproxy/envoy/pull/5026 which appears to break EDS fetches at Lyft. @junr03 should be able to help debug next week if you want to contact him on Slack. cc @htuch

**Comment by adilhafeez** [comment]
I added text that @zuercher recommended. Isnt that enough?

**Comment by mattklein123** [comment]
> I added text that @zuercher recommended. Isnt that enough?

No, as the DCO bot is still failing. Please see the bot failure and the contributing guide to see how to work with DCO.

**Comment by adilhafeez** [comment]
Will fix the DCO. Thanks

**Comment by dmitri-d** [comment]
Is there a failing test case for this?

**Comment by adilhafeez** [comment]
@dmitri-d no, but we should have test case to ensure that we don't break EDS fetch next time

**Comment by adilhafeez** [comment]
@mattklein123 DCO bot is happy now

**Comment by dmitri-d** [comment]
@adilhafeez: I'm happy to help with a testcase(s), but would need more details re: how EDS fetch fails.

**Comment by adilhafeez** [comment]
@dmitri-d can we revert this PR as it is and work on writing test case in a separate PR? I'm not sure how and what came in play that broke the EDS and would require more investigation. @junr03 and I can work together to dig more details about the failure.

**Comment by dmitri-d** [comment]
@adilhafeez: yes, I think reverting the commit is the way to go. Let me know if I can help with the investigation.

**Comment by mattklein123** [comment]
@dmitri-d, @junr03 will be able to help to help debug and describe to you the problem next week so that you can fix it. @adilhafeez Yes, we will obviously have a test case for whatever is broken when it is fixed.

**Comment by htuch** [comment]
OK, we should definitely have a dedicated EDS gRPC xDS integration test; today we have a combined gRPC ADS integration test and an EDS xDS from filesystem. We could build on the work done in https://github.com/envoyproxy/envoy/pull/5228 to add a dedicated EDS gRPC test here.

**Comment by dmitri-d** [comment]
I'll add EDS integration test while I'm at it.

**Comment by mattklein123** [comment]
@dmitri-d yeah I would go ahead and just do that as a change on top of current master. It's possible that test will fail when you un-revert the change and then we don't need to debug at Lyft.

**Pull request merged**
