### PR TITLE
extensions: Improve error handling for missing extension category

### LINKED ISSUE #15081: Poor error message when extension category missing
```
Traceback (most recent call last):
  File "./docs/generate_extension_db.py", line 86, in <module>
    extension_db[extension] = GetExtensionMetadata(target)
  File "./docs/generate_extension_db.py", line 70, in GetExtensionMetadata
    ('[' in categories or '(' in categories) else [categories])
  File "/usr/lib/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Name object at 0x7fa20d053518>
```

when the `category` field is missing from `envoy_cc_extension` target.

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: extensions: Improve error handling for missing extension category
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #15081
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/master/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@snowp

**Review by snowp — APPROVED** [review]
Thanks!

**Comment by junr03** [comment]
@phlax the coverage issue is fixed on main. Do you mind merging main?

**Comment by phlax** [comment]
@junr03 updated

**Pull request merged**
