### PR TITLE
lua: support body setBytes with header content length set automatically

### PR DESCRIPTION
**Pull request by StarryVae**
Signed-off-by: wangkai19 <wangkai19@corp.netease.com>

Commit Message: This patch modifies body setBytes API to make the header content length can be set automatically, which can avoid error when you forget set header content length in lua script and make the setBytes API more convenient for users.

Risk Level: Low
Testing: ut, integration
Docs Changes: N/A

### CODE REVIEW

**Comment by wbpcode** [comment]
@dio

**Comment by StarryVae** [comment]
@dio PTAL :)

**Review by dio — COMMENTED** [review]
@StarryVae Thank you for working on this. A good idea really. Could you update the docs as well? Currently, we have a sample requiring setting the `content-length` post modifying the content. 

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter.html?highlight=lua#script-examples

**Comment by StarryVae** [comment]
> @StarryVae Thank you for working on this. A good idea really. Could you update the docs as well? Currently, we have a sample requiring setting the `content-length` post modifying the content.
> 
> https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter.html?highlight=lua#script-examples



> @StarryVae Thank you for working on this. A good idea really. Could you update the docs as well? Currently, we have a sample requiring setting the `content-length` post modifying the content.
> 
> https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter.html?highlight=lua#script-examples

done! PTAL again, thank you!

**Comment by StarryVae** [comment]
> @StarryVae Thank you for working on this. A good idea really. Could you update the docs as well? Currently, we have a sample requiring setting the `content-length` post modifying the content.
> 
> https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter.html?highlight=lua#script-examples

@dio done, PTAL again, thank you!

**Review by dio — APPROVED** [review]
Awesome. Thanks!

**Comment by StarryVae** [comment]
@dio @lizan @yanavlasov It seems that this patch is blocked by "First-time contributors need a maintainer to approve running workflows" ? please help, thank you!

**Pull request merged**
