### PR TITLE
stream_info: wire the request and the connection infos

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

Description: pass the connection-level stream info to the request-level stream info. Initialize connection stream info with the right life span. Expose the filter state as mutable to the child filter state.
Risk Level: low
Testing: tests pass
Docs Changes: none
Release Notes: none

### CODE REVIEW

**Comment by kyessenov** [comment]
/retest
clang got killed

**Comment by kyessenov** [comment]
Gentle ping @dio.

**Comment by kyessenov** [comment]
Anything I can do to move this forward?

**Comment by dio** [comment]
Sorry, a question, re: Expose the filter state as mutable to the child filter state. What is the motivation of doing this?

**Comment by kyessenov** [comment]
@dio Sorry, this fell off my radar. The reason for the mutable filter state is the following change how the request and connection filter state interacted:

Before:
- request filter state would receive a null shared pointer owned by connection handler as the connection-level filter state.
- connection stream info filter state is not hooked into request stream info filter state.

After:
- request filter state receives the actual filter state from the connection stream info.
- connection filter state is correctly assigned the life span `DOWNSTREAM_CONNECTION`.

To allow writes from request stream info to connection stream info, the filter state needs to be exposed as mutable.

**Pull request closed without merging**
