### PR TITLE
Extension of PR #17087 (To Remove include )

### PR DESCRIPTION
**Pull request by ankatare**
Signed-off-by: Abhay Narayan Katare <abhay.katare@india.nec.com>

Commit Message: removing some more include from docs. 
Additional Description: Extension of work.  original PR #17087  
Risk Level: LOW
Testing: Yes
Docs Changes: Yes
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@ankatare why not just include this in #17087 ?

**Comment by ankatare** [comment]
@phlax some issues in my local branch and also changes were bit more so  pushed in different PR. is that Okay ?

**Comment by phlax** [comment]
>  is that Okay ?

i guess - but i think it would be easier for people reviewing any changes to have these together

**Comment by ankatare** [comment]
@phlax humm. i agree.  i linked both PRs for visibility , please review this time. **will tc**.

**Review by phlax — APPROVED** [review]
lgtm - thanks @ankatare 

iiuc this PR contains all of the fixes - so will #17087 close now ?

**Comment by ankatare** [comment]
@phlax yes, please close

**Comment by ankatare** [comment]
thanks for your help on this and quick review @phlax

**Pull request merged**
