### PR TITLE
bazel: remove rules_apple dependency

### PR DESCRIPTION
**Pull request by keith**
This appears unused

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Comment by keith** [comment]
going to see what fails here

**Comment by moderation** [comment]
Possible this is used in Envoy Mobile?

**Comment by keith** [comment]
If that's the only place it's used it would probably be nicer for them to define this dep upstream instead. I don't see any references to it in this repo, but it looks like it's a transitive dep of grpc somehow

**Comment by moderation** [comment]
Agree it would be nice to remove here. Re: grpc the reference is https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl#L372-L380

**Comment by keith** [comment]
It looks to me like the codepaths that use that in grpc are unused here, but that doesn't actually help us unless we broke that connection upstream. We can live with this for now and maybe revisit with bzlmod in the future

**Pull request closed without merging**
