### PR TITLE
tools: Use `Union` instead of `|` for Python 3.9 support

### PR DESCRIPTION
**Pull request by jpsim**
Commit Message: tools: Use `Union` instead of `|` for Python 3.9 support
Additional Description: 3.9 is the default installed on macOS, so this makes it a bit easier to run the script
Risk Level: Low
Testing: Local
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

Signed-off-by: JP Simard <jp@jpsim.com>

### CODE REVIEW

**Review by phlax — DISMISSED** [review]
lgtm, thanks @jpsim

**Review by keith — APPROVED** [review]

**Comment by phlax** [comment]
@jpsim you will need to run the code check tool (the other one)

i run it so...

```console
$ bazel run //tools/code:check -- --fix
```

**Comment by phlax** [comment]
...or grab the diff from the azure pipeline

**Review by kyessenov — APPROVED** [review]
Thanks, this bothered me, too.

**Review by phlax — APPROVED** [review]

**Pull request merged**
