### PR TITLE
redis-proxy: support eval_ro, evalsha_ro command

### PR DESCRIPTION
**Pull request by dlunch**
Commit Message: redis-proxy: support eval_ro, evalsha_ro command
Additional Description: Support `eval_ro` and `evalsha_ro` command
Risk Level: Low
Testing: Unit tests added
Docs Changes: Yes
Release Notes: Yes
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by kyessenov** [comment]
CC @weisisea @mattklein123 if you can review it.
/wait-any

**Comment by dlunch** [comment]
anyone can take a look on this?

**Review by weisisea — COMMENTED** [review]
LGTM

**Comment by weisisea** [comment]
@mattklein123 The changes look good to me. Please help merge the PR if they also look good to you. Thanks!

**Pull request closed without merging**
