### PR TITLE
build: declare original IP detection factories

### PR DESCRIPTION
**Pull request by goaway**
Commit Message: build: declare original IP detection factories
Risk Level: Low
Testing: Local & CI

Signed-off-by: Mike Schore <mike.schore@gmail.com>

### CODE REVIEW

**Comment by goaway** [comment]
cc @phlax

**Comment by phlax** [comment]
cc @rgs1

**Review by rgs1 — APPROVED** [review]
Is this something that can be checked by CI to avoid future factories from missing this? Thanks for the fix.

**Comment by goaway** [comment]
@rgs In theory one could probably introduce a dependency between the definitions of `REGISTER_FACTORY` and `DECLARE_FACTORY` that would cause the former to fail statically when the latter is missing.

**Review by snowp — APPROVED** [review]
Thanks!

**Pull request merged**
