### PR TITLE
build: Update WAMR to get performance improvement

### LINKED ISSUE #19834: Newer release available `org_llvm_releases_compiler_rt`: llvmorg-13.0.1 (current: llvmorg-12.0.1)
Package Name: org_llvm_releases_compiler_rt@12.0.1
Current Version: llvmorg-12.0.1@2021-07-09
Available Version: llvmorg-13.0.1@2022-02-02
Upstream releases: https://github.com/llvm/llvm-project/releases

### PR DESCRIPTION
**Pull request by leyao-daily**
Signed-off-by: Le Yao <le.yao@intel.com>

Commit Message: Update WAMR to get performance improvement
Additional Description: WAMR has a potential performance improvement based on the newer llvm/compiler-rt
Fixes #19834
Risk Level: Low
Testing: WIP
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by keith — DISMISSED** [review]

**Comment by moderation** [comment]
Dependency update looks OK but CI error look real

**Comment by leyao-daily** [comment]
> Dependency update looks OK but CI error look real

Yes. The fix is WIP. Thanks.

**Comment by wrowe** [comment]
/retest
to validate that this isn't transitory. Merging main again may be required.

**Comment by wrowe** [comment]
/retest
to validate that compile_time_options error isn't transitory

**Comment by wrowe** [comment]
The main branch is now stable, please merge main @leyao-daily and we'll see where this stands.

/wait

**Comment by leyao-daily** [comment]
Sorry to cause annoying review request.

**Comment by mattklein123** [comment]
CI looks broken to me. PTAL.

/wait

**Comment by leyao-daily** [comment]
Hi, I have check the CI log and found that the errors reduces based on current latest PR compared with the last time main branch.

**Comment by leyao-daily** [comment]
merged with PR https://github.com/envoyproxy/envoy/pull/22157, close now.

**Pull request closed without merging**
