### PR TITLE
bazel: improve rules_foreign_cc bootstrapping

### PR DESCRIPTION
**Pull request by keith**
This allows rules_foreign_cc to build make, cmake, and ninja itself, so
that it always has the same version across all developers. Previously
this didn't work with Apple Silicon but that was fixed by https://github.com/bazelbuild/rules_foreign_cc/pull/814

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Comment by wrowe** [comment]
Rechecking, @keith, nothing I can offer here, please mind the failures or convert to draft to continue experimenting.

**Comment by keith** [comment]
ok now CI has a real issue, I will have to investigate more since it doesn't repro locally

**Comment by keith** [comment]
https://github.com/envoyproxy/envoy/pull/19760

**Pull request closed without merging**
