### PR TITLE
build: move to C++14

### PR DESCRIPTION
**Pull request by mattklein123**
We now require GCC5+ for C++14 support. This will get us R/W mutexes,
heterogeneous containers, make_unique, nd a few other niceties.

Signed-off-by: Matt Klein <mklein@lyft.com>

### CODE REVIEW

**Comment by mattklein123** [comment]
@envoyproxy/maintainers 

cc @PiotrSikora for your SNI PR.

**Comment by moderation** [comment]
Does this line https://github.com/envoyproxy/envoy/blob/master/bazel/unix_cc_configure.bzl#L182 need to change too?

**Comment by mattklein123** [comment]
> Does this line https://github.com/envoyproxy/envoy/blob/master/bazel/unix_cc_configure.bzl#L182 need to change too?

Dunno. @htuch ?

**Comment by htuch** [comment]
Not sure. Run `bazel build -s`, dump an example compilation of regular `.o` into a comment and we can see :)

**Comment by mattklein123** [comment]
I did, it's using C++14. I tried a c++14 only feature.

**Comment by moderation** [comment]
I think this section needs to be updated - https://github.com/envoyproxy/envoy/blob/master/source/common/common/compiler_requirements.h#L6-L9

**Comment by mattklein123** [comment]
@moderation fixed, thank you

**Pull request merged**
