### PR TITLE
minor perf: no empty space chars' replace in the set response code details method

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: minor perf: no empty space chars' replace in the set response code details method

Additional Description:

To prevent the response code details from breaking the access log format, we replace all whitespace chars of detail string in the `setResponseCodeDetails` method. Related issue: #13423.

However, **most code details do not contain whitespace chars, and it is unnecessary to make every setResponseCodeDetails call perform an additional absl::StrReplaceAll.**

We just need to require that the caller of `setResponseCodeDetails` must ensure that the detail string does not contain whitespace chars.

Risk Level: Low.
Testing: Partial
Docs Changes: N/A.
Release Notes: N/A.

### CODE REVIEW

**Comment by yanavlasov** [comment]
Does it actually impact performance? The #13423 would only impact local responses, which I do not think is part of the benchmark you have used.
I think the PR is problematic as it will allow some cases to still go through, if they were not covered by tests as it relies on ASSERT. I would leave this as is for now, since there is currently no data that indicates this this specific code is causing a slowdown.

**Review by yanavlasov — COMMENTED** [review]
Thanks for explanation. I think it makes sense. Come to think about it more the ASSERT you have put in place should be enough. It should be good to go pending format fix.

/wait

**Comment by wbpcode** [comment]
@yanavlasov We need to modify a lot of files to correct all the detail string. I'm not sure it's worth it for this tiny optimization. But I can't think of a cleaner implementation at the moment. 🤔

**Review by yanavlasov — APPROVED** [review]

**Comment by alyssawilk** [comment]
IMO this one was worth a release note and possibly an email announcement, since anyone with custom filters is liable to have tests break.

**Comment by wbpcode** [comment]
@alyssawilk 🤔 You are right. It is my omission. I will create new PR to add release note.
If some one create an custom filter and no test covered it's custom response code detail, then in the worst case, the access log of envoy will be affected. I am not sure if an email announcement is required. If it is really necessary, can you please guide me to complete it?

**Pull request merged**
