### PR TITLE
UDP listener filter ECDS experiments---draft only

### PR DESCRIPTION
**Pull request by yanjunxiang-google**
UDP listener filter ECDS experiments---draft only

This is continue for issue: https://github.com/envoyproxy/envoy/issues/20049

UDP listener filter chain is created during listener creation. Thus ECDS may not work in UDP listener.

Created this draft PR so folks can discuss on it.

Signed-off-by: Yanjun Xiang <yanjunxiang@google.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by yanjunxiang-google** [comment]
This PR is for folks involved to discuss ECDS on UDP listener.
Some experiments shows the config update to UDP ECDS listener filter is ignored due to UDP listener filter chain is created during listener creation. Thus config update is not taken in actual traffic handling.  This may mean ECDS may not applicable to UDP listener filter.

Any way, throw this PR out so folks can refer this when discussing.

**Comment by soulxu** [comment]
I think the major issue is that the ActiveUDPListener only creates the UDP listener filter factory in the beginning
https://github.com/envoyproxy/envoy/blob/607b2987565aba652c2f2fdaaa1f6085c0aa59ef/source/server/active_udp_listener.cc#L94-L102

And never recreate those factories again, which means those factories will keep using the old config.

This is different from TCP, ActiveTcpListener will create a new listener filter factory for each new connection, which means when the ECDS updates the config, then the new connection can use the new config by creating the new factory.

https://github.com/envoyproxy/envoy/blob/607b2987565aba652c2f2fdaaa1f6085c0aa59ef/source/server/active_stream_listener_base.h#L85-L87

We probably need some ways to trigger a recreation of the UDP listener filter when the config is updated.

**Comment by yanjunxiang-google** [comment]
> > This PR is for folks involved to discuss ECDS on UDP listener. Some experiments shows the config update to UDP ECDS listener filter is ignored due to UDP listener filter chain is created during listener creation. Thus config update is not taken in actual traffic handling. This may mean ECDS may not applicable to UDP listener filter.
> > Any way, throw this PR out so folks can refer this when discussing.
> 
> How about to recreate the udp listener filter when the ECDS updates the config?

Currently UDP listener filter chain is created during Envoy instance creation:
https://github.com/envoyproxy/envoy/blob/64a45c4c8261b94a7ba57b87ed631643ae8fac51/source/server/active_udp_listener.cc#L90

If we recreated the UDP listener filter chian whenever ECDS updates received, which could be frequently,  could this cause data loss? For example, when the UDP listener filters are processing live traffic, and ECDS updates received, what should Envoy do with that traffic?

**Pull request closed without merging**
