### PR TITLE
deps: bump `rules_apple` -> 1.1.2

### LINKED ISSUE #23153: Newer release available `build_bazel_rules_apple`: 1.1.2 (current: 1.0.1)
Package Name: build_bazel_rules_apple@1.0.1
Current Version: 1.0.1@2022-06-17
Available Version: 1.1.2@2022-09-16
Upstream releases: https://github.com/bazelbuild/rules_apple/releases

### PR DESCRIPTION
**Pull request by RiverPhillips**
Signed-off-by: river phillips <riverphillips1@gmail.com>

Resolves #23153

Commit Message: deps: bump `rules_apple` -> 1.1.2
Additional Description:
Risk Level: low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by keith — APPROVED** [review]

**Review by phlax — APPROVED** [review]
/lgtm deps

thanks @RiverPhillips

**Comment by phlax** [comment]
@RiverPhillips thanks for taking on updating these deps - its a game of whack a mole - so there is usually plenty of these to follow up on if you are able to do any more

are you on the Envoy slack channel ?

**Comment by RiverPhillips** [comment]
@phlax no worries, happy to pick up more.

I'm not at the moment but I'll join if you send me an invite

**Comment by phlax** [comment]
i think you need to browse to here https://envoyproxy.io/slack - i think the invites are auto

**Comment by RiverPhillips** [comment]
Cheers @phlax

**Pull request merged**
