### PR TITLE
access_logs: extract commands parsing to a separate method

### PR DESCRIPTION
**Pull request by ohadvano**
Additional Description: Small refactor by extracting the part that parses formatters config in ``SubstitutionFormatStringUtils`` to a separate method, and using it in ``fromProtoConfig``. The motivation for this is allowing to create formatters and logger in cases the configuration does not use ``SubstitutionFormatString`` and would directly list the formatters config. Specifically this is meant for supporting formatters in Fluentd access logger (next PR).
Risk Level: low
Testing: unit tests
Docs Changes: none
Release Notes: none
Platform Specific Features: none

### CODE REVIEW

**Comment by ohadvano** [comment]
/assign @wbpcode 
Will appreciate your review, thanks

**Review by wbpcode — APPROVED** [review]

**Comment by wbpcode** [comment]
LGTM. Thanks.

**Pull request merged**
