### PR TITLE
coverage: update coverage for compression targets

### PR DESCRIPTION
**Pull request by junr03**
Commit Message:  update coverage for compression targets
Additional Description: I believe some of the targets were outdated. I have updated limits that I believe are now not necessary and added one more test were it was missing. I'll work with @rojkov  on the http compressor filter coverage which according to the last master run is in fact 84%.
Risk Level: low, increasing coverage!
Testing: I want to see results in the CI run.

Signed-off-by: Jose Nino <jnino@lyft.com>

### CODE REVIEW

**Comment by junr03** [comment]
cc @alyssawilk  Thanks for doing this work!

waiting to see if my understanding is right with the CI run here.

**Comment by alyssawilk** [comment]
Huh, that's weird - it should have listed the failed directories.  I'll test locally and figure out what went wrong.

**Comment by alyssawilk** [comment]
Also pass or fail, thank you for removing the now extraneous targets and improving test coverage.  Huzzah!  :-)

**Comment by alyssawilk** [comment]
yep, failed with
Code coverage for extension source/extensions/filters/http/decompressor is lower than limit of 97.0 (96.7)
as expected.

Still, awesome that 5 other directories are up to 97%!

**Comment by junr03** [comment]
Yep I haven’t increased the coverage yet. I just added the error setting we discussed. I’ll update today!

**Comment by junr03** [comment]
@alyssawilk green :)

**Pull request merged**
