### PR TITLE
subset-lb: fixing a mismatch between checked and returned lb config

### PR DESCRIPTION
**Pull request by adisuissa**
This was approved for a public repo fix because the PR causing the issue was merged 4 days ago.

Commit Message: subset-lb: fixing a mismatch between checked and returned lb config
Additional Description:
PR #24905 optimized the memory used for clusters. However it introduced a subtle bug when Least-Request LB is used, which results in returning the default config for that policy.

Risk Level: Low
Testing: This is a private method that is not easy to validate.
Docs Changes: N/A.
Release Notes: N/A.
Platform Specific Features: N/A.
Fixes commit #24905
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

Signed-off-by: Adi Suissa-Peleg <adip@google.com>

### CODE REVIEW

**Comment by adisuissa** [comment]
Two open questions:
1. Tests for this are hard to add, because the method is private and no easy access to the generated object.
2. Should I add a release note?

**Comment by adisuissa** [comment]
cc @KBaichoo

**Comment by KBaichoo** [comment]
> Tests for this are hard to add, because the method is private and no easy access to the generated object.

https://github.com/envoyproxy/envoy/pull/25112/files#diff-5789d0f7635142c87cc64c724c475ba691543b41b5859b7cbac953dc3cf9ddfbR435 Seems to be a test class friend, could that also be leveraged in this case to check this?

> Should I add a release note?

I think probably posting to envoy-announce would be better as an FYI to folks running near head.

**Comment by adisuissa** [comment]
> https://github.com/envoyproxy/envoy/pull/25112/files#diff-5789d0f7635142c87cc64c724c475ba691543b41b5859b7cbac953dc3cf9ddfbR435 Seems to be a test class friend, could that also be leveraged in this case to check this?

Added test (and renamed the friend test-class).

> I think probably posting to envoy-announce would be better as an FYI to folks running near head.

We can send this after the PR is merged (also sending sha range).

**Review by KBaichoo — APPROVED** [review]
Thank you for catching this!

**Pull request merged**
