### PR TITLE
json: Fix error message parsing of non-parse json errors

### PR DESCRIPTION
**Pull request by adisuissa**
Commit Message:  Fix error message parsing of non-parse json errors.
Additional Description:
The nlohmann json parser uses the `parser_error` method to notify on all errors, and not just parsing errors.
This PR handles non-parsing errors, and avoids the ENVOY_BUG call in this case.

Risk Level: low - changing error format.
Testing: Added unit test, and the fuzz test that caused the issue.
Docs Changes: N/A.
Release Notes: N/A.
Platform Specific Features: N/A.
Fixes fuzz issue 42480.

Signed-off-by: Adi Suissa-Peleg <adip@google.com>

### CODE REVIEW

**Review by yanavlasov — APPROVED** [review]

**Review by alyssawilk — APPROVED** [review]
@yanavlasov once you're done reviewing please remember to explicitly assign or assign-from senior maintainers so reviews don't stall out!

**Comment by alyssawilk** [comment]
@adisuissa looks like this needs a main merge, sorry

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
