### PR TITLE
route: move virtualHost() to Route from RouteEntry

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: route: move virtualHost() to Route from RouteEntry
Additional Description:

Move the virtualHost() method to the Route from RouteEntry. By this way, the filters could access the virtual host even it has no valid routeEntry().

Move the virtualCluster() to the VirtualHost from RouteEntry because similar reason.

For example, in pevious implementation, when the users want to log the metadata of vh by `%METADATA(VIRTUAL_HOST)%`, if direct response is used in the matched route, then users cannot access the metadata of vh. This PR make it's possbile.

Risk Level: low.
Testing: n/a.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
Hah, I found @zuercher has no activities recently. Seem he is busy.

/un-assign @zuercher

**Comment by htuch** [comment]
Seems fine, but just for posterity, can you comment on the situations in which we encounter a resolved virtual host without a resolved route entry?

**Comment by wbpcode** [comment]
> Seems fine, but just for posterity, can you comment on the situations in which we encounter a resolved virtual host without a resolved route entry?

I added an example scenario in the PR description. Hope it make sense.

**Review by htuch — APPROVED** [review]

**Pull request merged**
