### PR TITLE
Revert "udp_session_filters: add HTTP capsule filter (#29569)"

### PR DESCRIPTION
**Pull request by ggreenway**
This reverts commit e95324541b0e1cbfa07b43cbf87490cff7383f27.

This change broke the compile_time_options CI job.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by ggreenway** [comment]
cc @ohadvano 

This broke CI. I don't know why it passed in the PR and fails on the postsubmit job, but I'm reverting to get things working again. You can re-submit your PR with a fix for the CI failure.

CI failure: https://dev.azure.com/cncf/envoy/_build/results?buildId=149694&view=logs&j=e969334a-0e55-5c18-ac96-8b546753391e&t=32392586-69f5-5768-4caa-e00e8d4cc47e

P

**Review by adisuissa — APPROVED** [review]
Reverts a recent commit that breaks CI.
/lgtm api

**Comment by ohadvano** [comment]
It looks like a build failure that only happens in post-submit?
Can we consider forward fixing this?

**Comment by ohadvano** [comment]
I ran the presubmit again for testing, and it's failing presubmit too now.
Weird stuff, but anyways I'll create a new PR to fix this, thanks

**Comment by ggreenway** [comment]
Yeah, I really don't understand why it passed the PR checks. I was able to reproduce the failure locally with `bazel build  --config=clang --config=compile-time-options //:envoy`

**Pull request merged**
