### PR TITLE
Revert "listener filter: hide envoy internals from ListenerFilterCallbacks interface (#22732)

### PR DESCRIPTION
**Pull request by soulxu**
Signed-off-by: He Jie Xu <hejie.xu@intel.com>

Commit Message: Revert "listener filter: hide envoy internals from ListenerFilterCallbacks interface (#22732)
Additional Description:
https://envoyproxy.slack.com/archives/C78HA81DH/p1665661946626769 there is a case showing up, people still need a way to trigger the listener filter iteration in the listener filter.

This reverts commit 350c7f947149fcff41c4bdeac633aab80ae207fe.

Risk Level: low
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by soulxu** [comment]
cc @mattklein123 @ggreenway

**Comment by soulxu** [comment]
/wait

need to ensure that case is valid first.

**Comment by soulxu** [comment]
Or I should just expose the continueFilterChain again instead of revert this PR if the `dispatch()` consider as not expose the listener filter.

**Comment by soulxu** [comment]
@mattklein123 looking for feedback on this. This is removed in 1.24 release, if we think it is a valid case, we can add it back before the release. I can also submit a PR and only add that method back since the original PR did some cleanup and refactoring. But if we rush the time, it is also ok to revert this PR.

**Comment by soulxu** [comment]
cc @phlax also, in case we want to bring this in before the release

**Comment by KBaichoo** [comment]
@soulxu I think given this wasn't release blocking, and has some other improvements we can just enable the use case vs reverting all of this. Thank you for handling this!

**Comment by soulxu** [comment]
> @soulxu I think given this wasn't release blocking, and has some other improvements we can just enable the use case vs reverting all of this. Thank you for handling this!

got it, thanks! I will add another pr enable this.

**Pull request closed without merging**
