### PR TITLE
configs: add connect_timeout to envoy-demo.yaml

### PR DESCRIPTION
**Pull request by WineChord**
Commit Message: The envoy binary currently requires the 'connect_timeout' field to be specified; otherwise, the error 'error initializing configuration 'envoy-demo.yaml': Field 'connect_timeout' is missing in: name: "service_envoyproxy_io"' will occur.
Additional Description:
Risk Level: Low
Testing: 
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@WineChord which version of Envoy are you using? i think this is incorrect

**Comment by WineChord** [comment]
```
$ envoy --version

envoy  version: d362e791eb9e4efa8d87f6d878740e72dc8330ac/1.18.2/clean-getenvoy-76c310e-envoy/RELEASE/BoringSSL

```

Downloaded using [install](https://www.envoyproxy.io/docs/envoy/latest/start/install#install-envoy-on-rpm-based-distros).

**Comment by phlax** [comment]
unfortunately - that pathway to install seems defunct

version 1.18 has not been supported for a long time - there are archived docs for that tho

the easiest method way to run Envoy is in a container, but if you want to run in some other environment then as long as you have a compatible glibc you can fish the binary out of the container (that is what the installation method you pointed to did previously)

either way - i think this PR needs to close - i would be happy to review any updates to docs

**Comment by WineChord** [comment]
Do you mean the [page](https://www.envoyproxy.io/docs/envoy/latest/start/install) should be updated using github release links rather than rpm etc.?

**Comment by phlax** [comment]
yeah - i think that page needs an overhaul 

we have binaries and debs on our release page

an apt repo is ~pending and so hopefully should be set up in the coming months

rpms are not really supported at the moment - but would be helpful would be to give indications of which versions are compatible with which distro versions at least

**Comment by phlax** [comment]
@WineChord im going to close this as it may be misleading (ie `connect_timeout` has not been required for some time)

if you open a ticket (or PR) to address install docs issues i would be happy to follow up

**Pull request closed without merging**
