### PR TITLE
backport to 1.17: cluster: destroy on main thread (#14954)

### PR DESCRIPTION
**Pull request by cpakulski**
Commit Message:
Always destroy cluster info object on the master thread.
Fixed SDS churn and a rare crash case.
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
Fixes:
#13209
istio/istio#30199
istio/istio#28315
[Optional Deprecated:]
[Optional API Considerations:]

### CODE REVIEW

**Comment by cpakulski** [comment]
@lambdai Would you mind reviewing this backport?

**Review by lambdai — APPROVED** [review]
LGTM. Thanks!

**Comment by lambdai** [comment]
@cpakulski May I ask why `Dispatcher: keeps a stack of tracked objects. (#14573)` is included? Is it a piece of the dependency?

**Comment by cpakulski** [comment]
@lambdai Yes, your changes were done on top of Dispatcher's commit https://github.com/envoyproxy/envoy/pull/15197/commits/d7bd1365d80888d44d5f871678a8c668b0a39785. 
I got tons of conflicts after cherry-picking your commit. After including Dispatcher's commit everything went smooth.

**Comment by Shikugawa** [comment]
@cpakulski Could you merge release/v1.17?

**Pull request merged**
