### PR TITLE
moving original_dst cluster to extensions

### PR DESCRIPTION
**Pull request by alyssawilk**
Any Envoy users who customize their pre-built extensions will need to evaluate if they need this cluster.

Risk Level: medium
Testing: n/a
Docs Changes: n/a
Release Notes: inline

### CODE REVIEW

**Review by mattklein123 — DISMISSED** [review]
Nice

**Review by kyessenov — APPROVED** [review]

**Review by yanavlasov — APPROVED** [review]

**Comment by yanavlasov** [comment]
Windows test failure seems legit, although I do not understand why it is failing for Windows only.

**Comment by alyssawilk** [comment]
Passing CI finally but needs an API stamp again :-(
cc @adisuissa mind helping out?

**Review by adisuissa — COMMENTED** [review]
/lgtm api

**Review by KBaichoo — APPROVED** [review]
thank you!

**Pull request merged**
