### PR TITLE
bazel: fix presubmit CI

### PR DESCRIPTION
**Pull request by keith**
Fixes https://github.com/envoyproxy/envoy/issues/26913

### CODE REVIEW

**Comment by keith** [comment]
testing here https://buildkite.com/bazel/envoy/builds/2378#0187b489-2202-4a9c-882c-f6f1daed28b1

**Comment by keith** [comment]
versus main https://buildkite.com/bazel/envoy/builds/2379

**Comment by keith** [comment]
new test https://buildkite.com/bazel/envoy/builds/2380#0187b4c2-3bb8-420b-ac75-61723e9d43ca

**Comment by keith** [comment]
looks good in that build

**Review by phlax — APPROVED** [review]
lgtm, thanks @keith

**Pull request merged**
