### PR TITLE
lint: add more linters for using absl:: over std::

### PR DESCRIPTION
**Pull request by rebello95**
Follow up to https://github.com/envoyproxy/envoy/pull/13040. Some of these examples are based on [absl docs](https://github.com/abseil/abseil-cpp/blob/3c8b5d7587dc8ecf730ce9996c89e156e408c3ed/absl/types/variant.h#L405-L428) and C++ docs.

These linters are here to prevent additional breakages of Envoy Mobile on iOS due to usages of `std::` types/functions that are not supported on iOS 11. More discussion in https://github.com/envoyproxy/envoy/issues/12341.

Risk Level: Low
Testing: In PR

Signed-off-by: Michael Rebello <me@michaelrebello.com>

### CODE REVIEW

**Comment by mk46** [comment]
Sorry, format check fails and run `ci/run_envoy_docker.sh 'ci/do_ci.sh fix_format'` to fix it.

**Comment by htuch** [comment]
LGTM modulo format fix.

**Comment by rebello95** [comment]
Thanks. Running the docker command didn't work for me but I fixed locally and pushed

**Review by ggreenway — CHANGES_REQUESTED** [review]
I think we should add the entire (commonly used) API for variants, which unfortunately for this purpose are free functions, not members, so they all need a linter entry: 

```
std::holds_alternative
std::get
std::monostate
std::get_if
```

**Comment by mattklein123** [comment]
Also, while you are in here did we ever add a linter for string_view? We need that also.

**Comment by rebello95** [comment]
Done, added additional linters / test cases.

**Review by ggreenway — DISMISSED** [review]
Thank you!

**Comment by rebello95** [comment]
Hm, looks like there are a lot of usages of `std::get` in the codebase today, which is why the linter is failing. Are you sure we need that one @ggreenway?

**Comment by ggreenway** [comment]
> Hm, looks like there are a lot of usages of `std::get` in the codebase today, which is why the linter is failing. Are you sure we need that one @ggreenway?

Huh, `std::get` is used for both tuples and variants. We want to lint for only the uses with variant, not tuple, probably. But that's well into the realm of needing clang-tidy. So for now, I'd say remove the `std::get` one.

**Comment by rebello95** [comment]
Sounds good, removed.

**Comment by rebello95** [comment]
Looks like we also have existing usages of `string_view` which don't seem to be breaking Envoy Mobile @mattklein123: https://dev.azure.com/cncf/envoy/_build/results?buildId=50922&view=logs&jobId=9fd74226-df5b-5f29-39da-76fc341cc763&j=9fd74226-df5b-5f29-39da-76fc341cc763&t=068b98b1-acf0-52d0-fc6e-f6d1a5b1d5ef

**Comment by mattklein123** [comment]
I thought we had decided somehow that string_view doesn't work on Envoy Mobile? I'm confused. cc @junr03 @goaway

**Comment by junr03** [comment]
@rebello95 looks like those uses are all in extensions code we don't include/compile into Envoy Mobile. Hence why they are in the codebase here but causes no trouble to Envoy Mobile.

But yes, the decision was to _not_ use std::string_view, so the linter change here to prohibit it is great, thanks!

**Comment by rebello95** [comment]
Thanks for confirming @junr03! I pushed a change to fix the violations from the main branch.

**Review by mattklein123 — APPROVED** [review]
Awesome, thank you!

**Comment by rebello95** [comment]
Coverage failure looks unrelated

**Comment by mattklein123** [comment]
I think coverage on main branch is broken somehow due to recent limit changes. I will merge this and we can sort it out there.

**Review by mattklein123 — APPROVED** [review]

**Comment by rebello95** [comment]
Thanks!

**Pull request merged**
