### PR TITLE
deps: yaml-cpp: Updating to latest main version

### LINKED ISSUE #20762: Update yaml-cpp
*Title*: Update yaml-cpp

*Description*:
Recent additions to yaml-cpp help with some fuzz issues corner cases (example, #20544).
The yaml-cpp lib in Envoy was last updated in July 2021, and we should upgrade it to the latest [main sha](https://github.com/jbeder/yaml-cpp/commit/7d066556112e6899783608ef917b9b326fb6497a)

### PR DESCRIPTION
**Pull request by adisuissa**
Commit Message: deps: yaml-cpp: Updating to latest main version
Additional Description:
Risk Level: Low.
Testing: N/A.
Docs Changes: N/A.
Release Notes: N/A.
Platform Specific Features: N/A.
Fixes #20762

Signed-off-by: Adi Suissa-Peleg <adip@google.com>

### CODE REVIEW

**Comment by moderation** [comment]
Windows CI error looks real

/lgtm deps

**Comment by phlax** [comment]
they dont seem obviously related - other than yaml issues - but there is a failing windows test on the latest dependabot pr to update jinja2 here https://dev.azure.com/cncf/envoy/_build/results?buildId=104760&view=logs&j=4afecb4c-71c7-5b5c-ab99-a70ed4c927ad&t=4cd2fc51-3314-5d69-4df3-f765ae0c08dc&l=1698

**Comment by adisuissa** [comment]
The related failures seem to be due to changes by this PR https://github.com/jbeder/yaml-cpp/pull/1045
That PR was previously reverted, and this introduced a similar fix.
It seems that there was a further issue with PR 1045, described here: https://github.com/jbeder/yaml-cpp/pull/1063
This was later fixed in https://github.com/jbeder/yaml-cpp/pull/1064.

I'll keep digging.

**Comment by adisuissa** [comment]
> Any chance of having this change made upstream so we don't have to carry a patch? And please add a `TODO(adisuissa): ...` on what needs to happen to remove the patch.
> 
> /cc @envoyproxy/dependency-shepherds

Yes.
Unfortunately I don't have access to a windows build machine, so using CI for building/testing.
Once we have a good version, I'll send the patch to the yaml-cpp repo.

**Comment by moderation** [comment]
Related: https://github.com/envoyproxy/envoy/pull/20805

**Comment by jmarantz** [comment]
Adi do you want to merge main to see if that solves the CI issue?

/wait

**Comment by adisuissa** [comment]
This is also being worked on in: #20805
The issue is a broken build of the windows yaml-cpp with Bazel. Still working on reproducing this using a windows VM.

**Comment by vehre-x41** [comment]
#20805 is now superceeded by #20886 ,which merges main but also had to fix yaml_cpp again. I will try to get the required fixes into yaml_cpp once the build is passing and really everything is fixed...

**Comment by adisuissa** [comment]
Closing in favor of: #20886

**Pull request closed without merging**
