### PR TITLE
docs: fix word repetition and grammar.

### PR DESCRIPTION
**Pull request by agrawalnishant**
Signed-off-by: agrawalnishant <root.nishi@gmail.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by agrawalnishant** [comment]
@phlax , hope this is good. Thank you!

**Comment by daixiang0** [comment]
@agrawalnishant thanks for your contribution, could you add commit in last pr rather than open a new one?

**Comment by phlax** [comment]
> could you add commit in last pr rather than open a new one?

for future reference this is probably best - but this is a small change and im happy to just land it

**Review by phlax — APPROVED** [review]
lgtm, thanks @agrawalnishant

**Comment by agrawalnishant** [comment]
> > could you add commit in last pr rather than open a new one?
> 
> for future reference this is probably best - but this is a small change and im happy to just land it

Sure thing @phlax and @daixiang0 . Thank you!

**Pull request merged**
