### PR TITLE
access log: add JSON logging mode

### LINKED ISSUE #2692: how to generate a json format log from envoy? like nginx (escape=json)
i want to get a json format log like nginx(escape=json),any plan to support it?

### PR DESCRIPTION
**Pull request by aa-stripe**
These are the code changes to add a JSON access logging mode. I am working on the docs/release notes, but wanted to get started on code review!

Description:
- Add a new config option under `access_log` called `json_format`. This is a single level dictionary that contains strings as keys, and envoy access log format specifiers (such as `%PROTOCOL%`) as values. The specifiers will be replaced with actual values at logging time. I call this dictionary the "format dictionary" (as opposed to "format string").
- You can specify only one of `format` (format string) or `json_format` (format dictionary). If neither are there, we fall back to the default string format.
- Add the correct plumbing inside the configuration parsing to handle this.
- Add a new access log formatter class that is instantiated with the format dictionary. It maintains the mapping of dictionary keys to loggers
- Create a new class called `FormatterProvider`, to distinguish things that actually *extract* the information from a request. The things that *combine together* a bunch of `FormatterProvider`s are still called `Formatter`s. This is primarily a semantic/naming difference, but imo these are two conceptually separate things. There is, however no API difference, and if people are truly opposed to this, I could just merge them back into one `Formatter` class. This also provides a better foundation for adding more log formats in the future.
- At present, only one specifier per key in the format dictionary is allowed. This is because the whole point of JSON logging is to make logs easily machine-parseable. If you can include multiple formats in the same field, then you'll be right back to parsing those manually
- At present, only top-level keys are allowed in the format dictionary. This is validated at config load time. In the future, we can expand this to have nested dictionaries.

Risk Level: 
Low. It's an optional feature that has to be explicitly enabled.

Testing:
Unit testing for the actual formatter, and config load. Also manually tested using an example config file.

Docs:
Will have to add docs. Could someone please advise on how to preview the docs so that I can make sure they are good as I write them?

Release Notes:
Will have to add Release notes

Fixes #2692

### CODE REVIEW

**Comment by aa-stripe** [comment]
Working on getting this building again. The recent `RequestInfo`->`StreamInfo` change messed things up a little.

**Comment by zuercher** [comment]
You can build the docs via `./docs/build.sh`. I believe it will install the necessary python packages automatically. The docs are generated into generated/docs/.

**Comment by aa-stripe** [comment]
Yeah, I fixed the StreamInfo issue, but things got real screwed up when I did the signoff rebase. I'm trying to fix this now. Thanks @zuercher, I'll get that running locally

**Comment by aa-stripe** [comment]
Closing in favor of https://github.com/envoyproxy/envoy/pull/4693

**Pull request closed without merging**
