### PR TITLE
golang fitler: use Router::StringAccessor instead of GoStringFilterState.

### LINKED ISSUE #34183: Unable to access filter state from with Golang filter
*Title*: *Unable to access filter state from with Golang filter*

*Description*:
Hi team, facing a strange issue attempting to access filter state from within the golang http filter. We have a listener filter which sets keys in both both dynamic metadata and filter state which is successfully accessed by other c++ filters in the chain. When attempting to access these same keys from within the http golang filter, dynamic metadata is empty and the keys do not exist in the filter state.

Any pointers would be appreciated.

[optional *Relevant Links*:]

https://github.com/envoyproxy/envoy/blob/416cd425d50d3bc54c18ea134835a07ec21370d7/contrib/golang/filters/http/source/go/pkg/http/filter.go#L306

### PR DESCRIPTION
**Pull request by doujiang24**
fix #34183 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by doujiang24** [comment]
@StarryVae @spacewander PTAL, thanks. The ci failure is unrelated.

**Review by spacewander — APPROVED** [review]

**Comment by StarryVae** [comment]
LGTM, Thanks!

**Review by tyxia — APPROVED** [review]
Both code owners @StarryVae @spacewander have approved

**Pull request merged**
