### PR TITLE
Fix Windows debug and fastbuild builds and config test

### PR DESCRIPTION
**Pull request by wrowe**
Commit Message: Fix Windows debug and fastbuild builds and config test

Additional Description:
- Modify luajit and moonjit build scripts to properly build static debug library against C debug runtime
- Enables lua extension, previously disabled as it did not compile in debug mode (upstream patches to be submitted)
- //test/config_test:example_configs_test passes
  - Avoid freebind config fixture
  - Avoid parts of test config fixtures that involve the tracing extensions which are excluded on windows
- Avoid debug flags for fastbuild targets, bazel uses the release runtime to achieve compilation and link speed by using the smaller release objects

Note: Linking envoy-static (and tests) consumes too much memory in our current RBE configuration. To enable dbg in CI we would need to reserve more memory (no plans for CI at the moment)

Risk Level: low
Testing: local on windows in dbg and fastbuild
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
cc @envoyproxy/windows-dev

**Comment by sunjayBhatia** [comment]
Still fixing up the luajit/moonjit patches

/wait

**Comment by sunjayBhatia** [comment]
seeing if we can enable the lua tests

/wait

**Comment by wrowe** [comment]
This should go green and now be ready for review.

@lizan you typically help manage yaml-cpp and luajit component dependencies, if you could take a look at these resolutions of lua and yaml so we enable the corresponding tests (and can move on to diagnosing lua test quirks.) Or tag an appropriate assignee?

**Comment by lizan** [comment]
I have no idea what the luajit/moonjit patch does here, comments?

**Comment by wrowe** [comment]
> I have no idea what the luajit/moonjit patch does here, comments?

Envoy injects a build.py script to handle compilation on Linux (and on Windows) and on Unix, we patch their Linux src/Makefile to toggle the various flags for our preferences to build static luajit library.

On Windows, there is literally no makefile, it's a msvcbuild.bat shell script. Somewhat horrid, really, but that's where we are starting from.

That script failed to consider which sort of compilation (/MD to use the library runtime .dll files, /MT to link the library runtimes statically to the resulting .exe file), combined with with whether the sources are built for release or debugging (debugging indicated by an additional 'd' as in /MDd or /MTd).

The addition to the patches treats a 'debug' parameter to msvcbuild.bat and/or the 'static' parameter into one sensible compile time flag of /M(D|T)[d] which corresponds to those two command line arguements. We harvested the 'debug' toggle in build.py from the envvars, so that it was easily passed from the external bazel build arguments.

Without these patches, this library cannot be linked in -c dbg builds in bazel.

**Comment by wrowe** [comment]
A long-term fix would look more like adding a CMakeFiles.txt script appropriately for creating the two build-time binaries and the runtime library/executable, which would work on any platform and cut out this entire mess. But we hadn't added this dependency, we are just trying to make forward progress to zero test failures for an alpha candidate, so that project is out of scope for this immediate patch. It doesn't show up as a problem in CI today, because 1. we had disabled the lua extension in the short-term, and 2. it is a problem in the dbg target, but not an issue in the opt or fastbuild targets.

**Comment by wrowe** [comment]
@lizan hopefully my patch change explanation was sufficient? I'm happy to clarify anything that is still obscure. Any remaining questions about this change set? It does give us 5 more previously skipped windows tests now passing, and three others which we continue to mark as failing due to research required on the underlying causes, but this PR is pretty much stand-alone forward progress.

**Comment by lizan** [comment]
@wrowe yeah, thanks, is there anyway to upstream part of the patch, for example: static library handling / debug handling from environment vairable?

**Comment by wrowe** [comment]
> is there anyway to upstream part of the patch

While anything is possible, I don't perceive this as a useful or productive exercise. Any solution should eliminate the entire patch, or don't bother at all. That suggests one of two slightly more complex solutions;

 * Offer and have accepted a CMakeLists.txt template which deals correctly with host build (build-time tools) as well as target architecture library and command line binary build. This eliminates all three files in the patch set.

 * Offer and have accepted a bazel BUILD file, which deals correctly with the host build (build-time tools) as well as target architecture library and command line binary build. This also eliminates all three files in the patch set.

If anyone wants to promote the .bat file patch upstream, that's fine, but I find the entire thing so distasteful; it doesn't even begin to get at compiling with clang-cl in lieu of msvc cl.exe. It was a straight-line approach to solving an immediate problem at Envoy. Note that build has never been a priority of the lua community which doesn't include a build schema, from which luajit is forked (moonjit is simply a fork of luajit forked from lua, both stuck back at lua 5.1->5.2 API). 

My own preferred solution of lua - applicable to the luajit fork, looks more like this;, https://github.com/appsuite/oss-httpd-build/blob/58ceffa2db3e0966b44723b1e6eb60680a419b5a/mak/Makefile.build-win#L638

**Pull request merged**
