### PR TITLE
mobile: Set the default DNS timeout to 5s & allow overriding in Cronvoy

### PR DESCRIPTION
**Pull request by abeyad**

### CODE REVIEW

**Review by alyssawilk — COMMENTED** [review]
Nice!  Let's fix
library/swift/EngineBuilder.swift 
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
basically all the 25 at once
/wait

**Comment by abeyad** [comment]
> Nice! Let's fix library/swift/EngineBuilder.swift library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt basically all the 25 at once /wait

thanks for catching, totally slipped my mind!  done

**Comment by abeyad** [comment]
> > Nice! Let's fix library/swift/EngineBuilder.swift library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt basically all the 25 at once /wait
> 
> thanks for catching, totally slipped my mind! done

BTW, thankfully, swift and kotlin already had a function to allow modifying the dns timeout setting.  Cronvoy just didn't, so I added a method to its builder API

**Review by alyssawilk — APPROVED** [review]
LGTM ci willing :-)

**Pull request merged**
