### PR TITLE
Windows: Enable direct_response_integration_test

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Commit Message:
Windows: Enable direct_response_integration_test

- The test is flaky as it is possible for the connection to be closed on the
  server side before the data written by the client is transmitted
  - This causes `WSAECONNABORTED` on Windows (`An established connection was aborted by the software in your host computer, possibly due to a data transmission time-out or protocol error.`)
  - Instead, just have the test establish a connection and check the response from Envoy
- Also allow filter to half close connection
  - We know the content is fully written and the filter is a terminal
    one so we can enable the connection to be half closed and shut down
    the write end
  - Otherwise, the read in the client can get a connection reset error
    and on Windows may not have received all the data it should
  - See: https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-shutdown#remarks
    - `To assure that all data is sent and received on a connected
      socket before it is closed, an application should use shutdown to
      close connection before calling closesocket.`
- Also enables route_fuzz_test and echo_integration_test as they now
  compile and pass

Additional Description:
It may be worth some larger discussion about this filter, and if the way it closes the connection immediately is desirable
Risk Level: Low
Testing: No changes to tests, enables a few on Windows, verified locally+RBE on Windows
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
Turns out this test is flaky in RBE, working on it

**Comment by sunjayBhatia** [comment]
@zuercher since you are a co-owner on this filter, would love to get your thoughts on this test

**Comment by wrowe** [comment]
@envoyproxy/senior-maintainers would one of you be available to evaluate this quick fix forcing direct_response filter to half-close in order to flush that response to the network?

**Pull request merged**
