### PR TITLE
test: reinit connection_data_ when called poolReady at Tcp::Connection::MockInstance

### PR DESCRIPTION
**Pull request by qinggniq**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

I want use `Tcp::ConnectionPool::MockInstance`  to mock a tcp connection pool , but I found at https://github.com/envoyproxy/envoy/blob/bd05ab7b74c2ee288aea9772a03d521cd761bd59/test/mocks/tcp/mocks.cc#L59 when called `poolReady(connection)` , the `connection_data_`  will be moved and become nullptr base on the implementation of `onPoolReady `, so the function could not be called twice, this makes it hard when program want to test the situation when want get more than one connection from tcp connection pool. I decide reassign a `new MockConnectionData` to `connection_data_`.

I think this change is compatible, and is well suited for the behavior of real Tcp::ConnectionPool::Instance.

Commit Message: reinit connection_data_ when called poolReady at Tcp::Connection::MockInstance
Additional Description:
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by zuercher — COMMENTED** [review]
Are you working on another PR that will require this change?

**Comment by qinggniq** [comment]
@zuercher Yes, #15485. I'm not sure whether this change is belong to that pr, base on *One Pull Request. One Concern*, I give this pull request.

**Review by zuercher — APPROVED** [review]
That's fine. I just wanted to be sure this would be exercised somewhere in the Envoy code base in the near future. Thanks!

**Pull request merged**
