### PR TITLE
stream_info: removing what looks like dead code

### PR DESCRIPTION
**Pull request by alyssawilk**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by kyessenov** [comment]
There is some desire to provide standard types for the filter state in #29844. We can probably move this uint64 accessor into extension code, not core though.

**Comment by alyssawilk** [comment]
unsure where it should live as no Envoy extensions appear to use it.  Are there istio extensions which do?

**Comment by kyessenov** [comment]
Istio isn't using it. In any case, doesn't seem to right to have it in envoy headers, so we can delete it now, and then resurrect in some other place.

**Comment by ohadvano** [comment]
I hope it makes a diff, but I'm using this in custom external extension...
I think it's a pretty common thing to have, and similar to UInt32Accessor in the same directory

**Pull request closed without merging**
