### PR TITLE
Fix http cache crash on config reload (part 1)

### PR DESCRIPTION
**Pull request by ravenblackx**
Commit Message: Fix http cache crash on config reload (part 1)
Additional Description:
With the presence of a queue, it is no longer enough for a cache to outlive the filter, it must also outlive the queue that can outlive the filter.

This was already a problem for file_system_http_cache because it already contained a queue that could outlive the filter, but it has just been noticed in #29064 which I guess is the first time the cache has been used in conjunction with a dynamic configuration that causes the cache instance to be removed and re-added.

This change fixes it so that a cache shared pointer is persisted into the queue object, ensuring its lifetime is long enough for all actions to complete. The cleanup in which file_system_http_cache's now redundant queue is removed will still need to happen before the reported crash is no longer a risk.

Risk Level: Low; a small impact change to a WIP extension.
Testing: Added validation that the shared_ptr lives on in the queue.
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Review by jmarantz — DISMISSED** [review]

**Review by jmarantz — DISMISSED** [review]
optimistically re-approving assuming the re-test works :)

**Comment by ravenblackx** [comment]
/retest
(a build error in `test/extensions/filters/network/redis_proxy/router_impl_test.cc` doesn't seem related.)

**Comment by ravenblackx** [comment]
/retest
(now that #29221 has reverted the problem)

**Comment by ravenblackx** [comment]
/retest
*You're* a context deadline exceeded, repokitteh.

**Review by jmarantz — APPROVED** [review]

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
