### PR TITLE
Fix issue with Windows container image

### PR DESCRIPTION
**Pull request by davinci26**
Add Envoy to the path of all users.

Signed-off-by: Sotiris Nanopoulos <sonanopo@microsoft.com>

### CODE REVIEW

**Review by wrowe — APPROVED** [review]

**Comment by wrowe** [comment]
Please merge master to get past linux coverage, thx @davinci26

**Comment by wrowe** [comment]
If any @envoyproxy/senior-maintainers want to merge this in spite of the broken coverage check, this PR is unrelated to to the recent coverage breakage and introduces no coverage changes. I don't have such karma.

**Comment by wrowe** [comment]
Sorry I can't take this further. Push merge is appropriate

**Comment by davinci26** [comment]
Picked up main to see if it helps

**Review by zuercher — APPROVED** [review]
I can't bypass the merge restriction either. I think only a few people have that permission (e.g, Matt and Harvey, but possibly others.)

**Comment by davinci26** [comment]
I am up to date with main. let me try to retest

**Comment by davinci26** [comment]
(previous failure was related to an external download)

**Pull request merged**
