### PR TITLE
backport to v1.15: connection: Remember transport socket read resumption requests and replay them when re-enabling read. (#13772)

### PR DESCRIPTION
**Pull request by antoniovicente**
Fixes SslSocket read resumption after readDisable when processing the SSL record that contains the last bytes of the HTTP message

Signed-off-by: Antonio Vicente <avd@google.com>

### CODE REVIEW

**Review by cpakulski — APPROVED** [review]
LGTM.

I have seen tsan CI failure in other backports, but not in all.
Does not seem to be related to the code here anyways.

**Comment by antoniovicente** [comment]
> LGTM.
> 
> I have seen tsan CI failure in other backports, but not in all.
> Does not seem to be related to the code here anyways.

I searched for vhds_integration_test and found https://github.com/envoyproxy/envoy/pull/12067 and https://github.com/envoyproxy/envoy/pull/12134

It may be worth disabling that test under TSAN in the v1.15 release branch.

I wasn't able to find past reports of problems or fixes for integration:tcp_proxy_integration_test

/retest

**Comment by antoniovicente** [comment]
> > LGTM.
> > I have seen tsan CI failure in other backports, but not in all.
> > Does not seem to be related to the code here anyways.
> 
> I searched for vhds_integration_test and found #12067 and #12134
> 
> It may be worth disabling that test under TSAN in the v1.15 release branch.
> 
> I wasn't able to find past reports of problems or fixes for integration:tcp_proxy_integration_test
> 
> /retest

https://github.com/envoyproxy/envoy/pull/14217

**Comment by lizan** [comment]
Can you resolve version_history conflict?

**Comment by antoniovicente** [comment]
Flake due to timeout during coverage run.

/retest

**Comment by antoniovicente** [comment]
> Can you resolve version_history conflict?

Done and CI looks happy.

**Review by lizan — APPROVED** [review]

**Pull request merged**
