### PR TITLE
deps: Remove opentracing

### PR DESCRIPTION
**Pull request by phlax**
As explained here https://github.com/envoyproxy/envoy/issues/9958#issuecomment-1537414327 the opentracing build is currently broken due to cmake being removed from the host environment, and is due to be removed.

This should have been scheduled for deprecation a long time ago as there was a public conversation and some shared expectation among dep-shepherds that this would be removed

We can postpone this landing until after the next release if we can find a solution to  https://github.com/envoyproxy/envoy/pull/27244, but currently the build is broken (eg for anyone building locally without an existing cache) so probably the better thing is to land this and revert temporarily if someone provides an adequate fix

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
seems the only thing that is depending on the opentracing lib is jaeger-native example for its config

this example uses a binary of uncertain origin so has always been problematic, and not overly helpful as an example

im wondering if we want to keep it and fix the config, or just remove this also (mho is probably the latter)

**Comment by phlax** [comment]
/wait on outcome of conversations in #9958 and/or #27244

**Comment by Oberon00** [comment]
So from this PR alone, the context for why this change should happen is completely missing and there is also no issue linked in the PR description (only later in the comment thread are #27244 and https://github.com/envoyproxy/envoy/issues/9958 mentioned.
I think there should be a good summary for why you remove this, if you decide to remove this.

I would prefer you kept it, as we at Dynatrace rely on the dynamic_ot tracer to inject our agent. There is no equivalent replacement available that would allow us to execute code that gathers additional process metrics in-process and use our custom exporter/protocol code. Even though we are working on a replacement based on the OpenTelemetry exporter (which is also not yet available in with the OTel-spec-defined default HTTP transport), we would be thankful if you could manage to carry the feature a bit longer.

**Comment by phlax** [comment]
@kyessenov can we land this for now so we unbreak local devs

im happy to assist readding as explained before the next release if necessary - we can also open a ticket to track

**Comment by Oberon00** [comment]
Can you explain how this breaks local dev? I tried to build from main 1bd16ecb51a641f6823a243ed8e3b516cb7dca0a on Ubuntu (WSL 2) with LLVM 14 and it worked fine for me. What are you using that breaks?

**Comment by phlax** [comment]
can you post your build command please

**Comment by Oberon00** [comment]
I just used what was described in the readme: ` bazel build envoy`

**Comment by phlax** [comment]
are you using the `ci/run_envoy_docker.sh` container ?

**Comment by Oberon00** [comment]
No, I couldn't get the VS Code devcontainer to work for me due to networking issues, probably related to WSL 2, so I didn't even try that other one. From what I understand, I might accidentally work around the problem by having CMake installed in my environment?

**Comment by phlax** [comment]
> I might accidentally work around the problem by having CMake installed in my environment?

correct - or induce the problem we are trying to fix depending on pov

**Comment by Oberon00** [comment]
Is that the "expected" error?

```
$ ci/run_envoy_docker.sh
Unable to find image 'envoyproxy/envoy-build-ubuntu:818d28832abf2a7c0cb2bff00435be231729a0bf' locally
818d28832abf2a7c0cb2bff00435be231729a0bf: Pulling from envoyproxy/envoy-build-ubuntu
ca1778b69356: Already exists
b432f54f75b7: Already exists
ed06dd65c63d: Already exists
66a08b852327: Already exists
Digest: sha256:9b04e1cb04fc579142dd820da4583823413b486928941a6c557752a9bcad0608
Status: Downloaded newer image for envoyproxy/envoy-build-ubuntu:818d28832abf2a7c0cb2bff00435be231729a0bf
No cmake here!
bash: -c: line 1: syntax error: unexpected end of file
```

**Comment by phlax** [comment]
> Is that the "expected" error?

if you dont give it any commands

probs it could handle this better

**Comment by Oberon00** [comment]
Thanks, I just found https://github.com/envoyproxy/envoy/tree/main/ci#on-linux, I will look into that

**Comment by phlax** [comment]
closing this as the immediate issue has been resolved in #27400

there is still the intention to deprecate and remove this lib - but i will open a separate ticket to track that

**Pull request closed without merging**
