### PR TITLE
move pfcount to hashMultipleSumResultCommands

### PR DESCRIPTION
**Pull request by littlegreyzhang**
Signed-off-by: littlegreyzhang <826999015@qq.com>

Commit Message: move pfcount to hashMultipleSumResultCommands & writeCommands
@Agent-Tao @mattklein123

Additional Description:
https://redis.io/commands/pfcount
> When called with multiple keys, returns the approximated cardinality of the union of the HyperLogLogs passed, by internally **_merging_** the HyperLogLogs stored at the provided keys into a temporary HyperLogLog.

> Note: as a side effect of calling this function, it is possible that the HyperLogLog is modified, since the last 8 bytes encode the latest computed cardinality for caching purposes. So PFCOUNT is technically a **_write command_**.

#12608

Risk Level: Low
Testing: New and existing tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by junr03** [comment]
@HenryYYang do you mind taking a look here?

**Comment by Agent-Tao** [comment]
even though pfcount may  modify HyperLogLog, but I think it is still a read command.
this is  because for users, they don't want to modify this the value, they will use pfadd to modify.  for some   technically reason, maybe performance ,   pfcount may modify  HyperLogLog which should not be modifyed.
beside, read commands and write commands are incompatible， see
‘’‘
  static bool isReadCommand(const std::string& command) {
    return !writeCommands().contains(command);
  }
’‘’
I think it's read attributes are more than write

**Comment by littlegreyzhang** [comment]
> even though pfcount may modify HyperLogLog, but I think it is still a read command.
> this is because for users, they don't want to modify this the value, they will use pfadd to modify. for some technically reason, maybe performance , pfcount may modify HyperLogLog which should not be modifyed.
> beside, read commands and write commands are incompatible， see
> ‘’‘
> static bool isReadCommand(const std::string& command) {
> return !writeCommands().contains(command);
> }
> ’‘’
> I think it's read attributes are more than write

I think you're right. But I don't know if mirroring requests will cause data differences.

```
Common::Redis::Client::PoolRequest* makeSingleServerRequest(
    const RouteSharedPtr& route, const std::string& command, const std::string& key,
    Common::Redis::RespValueConstSharedPtr incoming_request, ConnPool::PoolCallbacks& callbacks) {
  auto handler =
      route->upstream()->makeRequest(key, ConnPool::RespVariant(incoming_request), callbacks);
  if (handler) {
    for (auto& mirror_policy : route->mirrorPolicies()) {
      if (mirror_policy->shouldMirror(command)) {
        mirror_policy->upstream()->makeRequest(key, ConnPool::RespVariant(incoming_request),
                                               null_pool_callbacks);
      }
    }
  }
  return handler;
}
```

**Comment by Agent-Tao** [comment]
> > even though pfcount may modify HyperLogLog, but I think it is still a read command.
> > this is because for users, they don't want to modify this the value, they will use pfadd to modify. for some technically reason, maybe performance , pfcount may modify HyperLogLog which should not be modifyed.
> > beside, read commands and write commands are incompatible， see
> > ‘’‘
> > static bool isReadCommand(const std::string& command) {
> > return !writeCommands().contains(command);
> > }
> > ’‘’
> > I think it's read attributes are more than write
> 
> I think you're right. But I don't know if mirroring requests will cause data differences. Read commands may not mirror the request.
> 
> ```
> Common::Redis::Client::PoolRequest* makeSingleServerRequest(
>     const RouteSharedPtr& route, const std::string& command, const std::string& key,
>     Common::Redis::RespValueConstSharedPtr incoming_request, ConnPool::PoolCallbacks& callbacks) {
>   auto handler =
>       route->upstream()->makeRequest(key, ConnPool::RespVariant(incoming_request), callbacks);
>   if (handler) {
>     for (auto& mirror_policy : route->mirrorPolicies()) {
>       if (mirror_policy->shouldMirror(command)) {
>         mirror_policy->upstream()->makeRequest(key, ConnPool::RespVariant(incoming_request),
>                                                null_pool_callbacks);
>       }
>     }
>   }
>   return handler;
> }
> ```
> 
> ```
> bool MirrorPolicyImpl::shouldMirror(const std::string& command) const {
>   if (!upstream_) {
>     return false;
>   }
> 
>   std::string to_lower_string = absl::AsciiStrToLower(command);
> 
>   if (exclude_read_commands_ && Common::Redis::SupportedCommands::isReadCommand(to_lower_string)) {
>     return false;
>   }
> 
>   if (default_value_.has_value()) {
>     return runtime_.snapshot().featureEnabled(runtime_key_, default_value_.value());
>   }
> 
>   return true;
> }
> ```

for mirroring request,  I thank commands user want to write like  pfadd should be mirrored, because user want to modify, if miss, the result will be unexpected.   not matter how many pfcount is  invoked  mixed up with pfadd, they should not influence the final result.  so from this point of view,  It seems pfcount should not be mirrored.
but we would better to check the hyperloglog implementation,  to check why pfcount will modify it. it seems that pfcount may modify the cache in hyperloglog for performance. the real data seems  not be modified.

**Comment by littlegreyzhang** [comment]
@Agent-Tao Yes, I think pfcount will only change the last 8 bytes that encode the latest computed cardinality for caching purposes. But this does not affect the result.

http://antirez.com/news/75
> So our data structure has an additional tail of 8 bytes representing a 64bit unsigned integer in little endian format. If the most significant bit is set, then the precomputed value is stale and requires to be recomputed, otherwise PFCOUNT can use it as it is. PFADD just turns on the “invalid cache” bit when some register is modified.

**Comment by littlegreyzhang** [comment]
These two commands require that all keys belong to the same redis node, and I will resubmit a PR for modifications.

**Pull request closed without merging**
