### PR TITLE
filter: add ability to resetIdleTimer

### PR DESCRIPTION
**Pull request by junr03**
Commit Message: allow filters to reset the stream idle timer.
Risk Level: low
Testing: UT and integration.

### CODE REVIEW

**Comment by junr03** [comment]
cc @goaway

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks this LGTM. Can you try to quickly add an integration test? Using simulated time it should be pretty easy to prove that this works with a very small integration test filter. (Basically advance time before decodeData to just before the timeout, reset the idle timer in decode data, and then advance time past the timeout, and make sure the stream is not reset, then advance beyond the timeout and make sure it is reset.)

/wait

**Comment by junr03** [comment]
sg, writing up!

**Comment by junr03** [comment]
@mattklein123 done!

**Comment by mattklein123** [comment]
Nice. Looks like CI issue though.

/wait

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
