### PR TITLE
zipkin: fix verbose mode

### PR DESCRIPTION
**Pull request by jamesmulcahy**
When verbose mode is true, Zipkin tracers need to serialize the data
collected by Span::log() as annotations.

Co-authored-by: Dhi Aurrahman <dio@tetrate.io>

Signed-off-by: James Mulcahy <jmulcahy@netflix.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message: When verbose mode is true, Zipkin tracers need to serialize the data
collected by Span::log() as annotations.
Additional Description: **This PR was originally contributed by @dio, in PR #12541**.  Full credit goes to Dhi.  Unfortunately, that PR didn't get merged, and the documented functionality remains broken in the main branch.  I've verified this patch still fixes the issue, and am hoping we can get this merged as is.
Risk Level: Low
Testing: Includes additional unit tests, and has also been manually verified as emitting the additional span annotations when deployed in a real environment.
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:] N/A
[Optional Fixes #Issue] N/A (No issue exists to track this bug)
[Optional Deprecated:] N/A
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):] N/A

### CODE REVIEW

**Comment by jamesmulcahy** [comment]
cc/ @junr03 @dio @snowp 

The conversation on slack petered out, so I thought I'd (re-)open a PR to try and drive this forward.  I have limited cycles for making the test enhancement that @junr03 was originally looking for, but given that the bug remains main, and this improves things, perhaps we can compromise here?  It'd be nice to get this working again in time for the 1.18 release.

Please let me know your thoughts.

**Comment by jamesmulcahy** [comment]
Related slack thread: https://envoyproxy.slack.com/archives/C78M4KW76/p1596768743383400

**Comment by dio** [comment]
@jamesmulcahy Thanks! I think the issue with the PR was to provide a complete "golden" file for Zipkin to have all possibilities taken care of. IMO, let's have this merged since I'll rewrite the serializer using the new JSON lib, hence we can write test more easily since the new lib is deterministic in terms of serialization. https://github.com/envoyproxy/envoy/issues/10411

**Comment by snowp** [comment]
Can we add a release note to this and we'll get this merged? Thanks

**Review by snowp — APPROVED** [review]
Thanks!

**Pull request merged**
