### PR TITLE
http2: updates a test utility to use QUICHE instead of nghttp2.

### PR DESCRIPTION
**Pull request by birenroy**
Signed-off-by: Biren Roy <birenroy@google.com>

The test utility just packs a METADATA frame, and is used in Envoy unit tests. Cleanup related to https://github.com/envoyproxy/envoy/issues/23596.

Commit Message: Updates a test utility to use QUICHE instead of nghttp2.
Additional Description:
Risk Level: Low
Testing: ran unit tests locally
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Review by diannahu — APPROVED** [review]
Nice update!

**Comment by birenroy** [comment]
/assign @KBaichoo 
/assign @yanavlasov 

FYI, this is ready to merge.

**Review by KBaichoo — APPROVED** [review]

**Pull request merged**
