### PR TITLE
test: disable tcpdump ssl_integration_test

### PR DESCRIPTION
**Pull request by mattklein123**

### CODE REVIEW

**Review by dio — DISMISSED** [review]
Thank you @mattklein123!

**Comment by mattklein123** [comment]
Hmm. Still failing. I'm mostly OOO tomorrow but will try to take a look unless someone gets to it first.

**Comment by mattklein123** [comment]
I think the issue is somehow related to the tapping part of the ASAN run, trying to look into it:

https://github.com/envoyproxy/envoy/blob/c318156496edc46c844822a3d1f107ee496fa449/ci/do_ci.sh#L225-L233

I'm guessing some of the tap files are pretty big and we might need to just use a test that doesn't generate much traffic. cc @htuch

**Comment by mattklein123** [comment]
Hmm, now that I look at it more, the actual failure seem to be: 
```tcpdump: Permission denied```

So I guess there is some issue spinning up tcpdump in the failing case.

**Comment by mattklein123** [comment]
I'm able to repro the permission denied issue via ```bazel test //test/extensions/transport_sockets/tls/integration:ssl_integration_test --config=clang-asan -c dbg --run_under=@envoy//bazel/test:verify_tap_test.sh --runs_per_test=100```, which makes me think the test is not working as expected. I will discuss with @htuch next week.

**Review by jmarantz — APPROVED** [review]

**Comment by mattklein123** [comment]
I talked to @htuch offline. No one has time to debug this right now so I'm going to temporarily disable this part of the test and will file a tracking issue to re-enable.

**Comment by mattklein123** [comment]
Opened https://github.com/envoyproxy/envoy/issues/13391 to turn this test back on.

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
