### PR TITLE
Generalize the gRPC access logger base classes

### PR DESCRIPTION
**Pull request by itamarkam**
Commit Message: Generalize the gRPC access logger base classes
Additional Description: Some of the general logging logic was in the classes implementing the gRPC access logger interface (GrpcAccessLoggerImpl and GrpcAccessLoggerCacheImpl). Putting all the (soon to be) shared logic in the base class should make it very easy to create new loggers (see "source/extensions/access_loggers/grpc/grpc_access_log_impl.h/cc" for example).
While moving these things around and chancing some dependencies, I also went ahead and fixed some unused/indirect dependencies.
Risk Level: Low (refactoring)
Testing: Unit tests moved the implementation tests to the base class tests (now that the logic lies there) and simplified the implementing classes' tests.
Docs Changes: None
Release Notes: None
Platform Specific Features: None
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

@omriz @edrukh @yanavlasov @htuch

### CODE REVIEW

**Review by yanavlasov — APPROVED** [review]

**Comment by itamarkam** [comment]
@yanavlasov seems like presubmits are still failing (doesn't seem related to my change) - can you please re-run them.
I don't have permissions to do so.

**Review by yanavlasov — DISMISSED** [review]

**Comment by yanavlasov** [comment]
@itamarkam would you be able to merge master into this please? Just to see if it fixes the build issue.

**Comment by itamarkam** [comment]
> @itamarkam would you be able to merge master into this please? Just to see if it fixes the build issue.

Done.

**Comment by yanavlasov** [comment]
@itamarkam would you be able to merge master again please? I think the coverage issue was fixed.

**Comment by itamarkam** [comment]
Rebased on the master again.

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
