### PR TITLE
deps: Bump `rules_apple` -> 0.33.0

### LINKED ISSUE #19658: Newer release available `build_bazel_rules_apple`: 0.33.0 (current: 0.32.0)
Package Name: build_bazel_rules_apple
Current Version: 0.32.0@2021-10-29 20:38:24
Available Version: 0.33.0@2022-01-22 02:15:10
Upstream releases: https://github.com/bazelbuild/rules_apple/releases

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #19658
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
this one seems to be fighting with `rules_swift` - not sure if that means they need to be updated together, or i have missed a patch or somesuch

```console
	File "/build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/build_bazel_rules_swift/swift/internal/build_settings.bzl", line 73, column 34, in <toplevel>
		build_setting = config.string(
Error in string: string() got unexpected keyword argument 'allow_multiple'

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=99822&view=logs&j=1c04237c-5f52-5959-5f83-5522b3556331&t=db3f3889-c922-566b-fa2e-4bc4948bc467&l=217

**Comment by phlax** [comment]
cc @junr03

**Comment by phlax** [comment]
actually this seems to be failing for bazel 5 related reasons - its not recognizing lambdas which are only added in bazel 5 as part of the starlark syntax

**Comment by keith** [comment]
Yep we'll have to update to bazel 5.x first

**Review by keith — APPROVED** [review]

**Comment by phlax** [comment]
@wrowe i think this one is ready to land

**Pull request merged**
