### PR TITLE
cleanup: apply structured binding feature to give meaningful names to .first and .second

### PR DESCRIPTION
**Pull request by stedsome**
This PR aims to improve readability through naming previously .first and .second variables. The changes in this PR should be entirely cosmetic.

Commit Message:
Additional Description:
Risk Level: Low, as there is no intended changes in mechanics.
Testing: All existing tests have passed. 
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by stedsome** [comment]
> Hey, thanks for the readability improvement. I do see a bunch of places where we're substituting .first .second for key, val. I think on the whole we're better off preserving git history here, unless we're really getting clarity improvements on what the keys and values are, such that the code is easier to read.

I see. What about I get rid of these cases and only keep instances where I believe there is a real readability improvement.

**Comment by alyssawilk** [comment]
So I definitely see some changes which look like improvements in there, but the problem is that the changes span so much of the code base it's going to be hard to get review sign off on it, as no one maintainer is familiar enough with each area of code to sign off on all of it.  Generally we encourage clarity renames and extra commenting when you're working in an area of code, but bulk clean up like this often isn't quite helpful enough to readability to justify someone digging through unfamiliar areas of the code.  If anyone from @envoyproxy/maintainers volunteers to do the digging I'd be happy to see this go forward though!

**Comment by asraa** [comment]
> So I definitely see some changes which look like improvements in there, but the problem is that the changes span so much of the code base it's going to be hard to get review sign off on it, as no one maintainer is familiar enough with each area of code to sign off on all of it. 

Alyssa what do you think about a tracking issue explaining the cleanup, and a plan to separate the fix into sub-components that hopefully a single maintainer can take on, and that won't cover as many files all at once? I'm thinking upstream definitely separate from router and http, utilities like protobuf/json can be bundles, etc.

**Comment by alyssawilk** [comment]
Yeah, if you want to mentor breaking it into a few PRs (not one per file, that'd be too noisy, but maybe a few?)  and doing first pass on making sure it's more readable, that'd be great!

**Comment by asraa** [comment]
Sounds good! 
@stedsome Can you open an issue about this? We can comment on there and bucket the changes into reasonable sizes and over components.

**Comment by stedsome** [comment]
> Sounds good!
> @stedsome Can you open an issue about this? We can comment on there and bucket the changes into reasonable sizes and over components.

np

**Pull request closed without merging**
