### PR TITLE
tcp: not calling watermark callbacks in delay close

### LINKED ISSUE #6872: possible delayed close watermark bug
Saw the below crash on a production box. I haven't done much investigation but my guess is that we still raise watermark callbacks during delayed close, which I don't think we should do. 

cc @AndresGuedez @alyssawilk 

```
Backtrace:
#0  0x0000000000000018 in ?? ()
#0  0x0000000000000018 in ?? ()
#1  0x00000000007d06be in virtual thunk to Envoy::Http::Http2::ConnectionImpl::onUnderlyingConnectionBelowWriteBufferLowWatermark() () at bazel-out/k8-opt/bin/external/envoy/source/common/http/_virtual_includes/codec_helper_lib/common/http/codec_helper.h:22
#2  0x000000000067b8ba in Envoy::Network::ConnectionImpl::onLowWatermark (this=<optimized out>) at external/envoy/source/common/network/connection_impl.cc:435
#3  0x00000000004786e5 in Envoy::Extensions::TransportSockets::Tls::SslSocket::doWrite (this=0x18fe36e0, write_buffer=..., end_stream=<optimized out>) at external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:212
#4  0x000000000067af59 in Envoy::Network::ConnectionImpl::onWriteReady (this=0x22891400) at external/envoy/source/common/network/connection_impl.cc:558
#5  0x000000000067baf2 in Envoy::Network::ConnectionImpl::onFileEvent (this=0x22891400, events=779607392) at external/envoy/source/common/network/connection_impl.cc:476
#6  0x0000000000676b05 in operator() (this=0x15479898, __args=2) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/std_function.h:706
#7  operator() (this=<optimized out>, what=<optimized out>, arg=0x2ebdbc00) at external/envoy/source/common/event/file_event_impl.cc:65
#8  Envoy::Event::FileEventImpl::assignEvents(unsigned int)::$_0::__invoke(int, short, void*) (what=<optimized out>, arg=0x2ebdbc00) at external/envoy/source/common/event/file_event_impl.cc:49
#9  0x0000000000975add in event_process_active_single_queue ()
#10 0x0000000000974080 in event_base_loop ()
#11 0x00000000006758bd in Envoy::Event::DispatcherImpl::run (this=<optimized out>, type=Envoy::Event::Dispatcher::Block) at external/envoy/source/common/event/dispatcher_impl.cc:178
#12 0x000000000066ff22 in Envoy::Server::WorkerImpl::threadRoutine (this=0x4eb8b80, guard_dog=...) at external/envoy/source/server/worker_impl.cc:104
#13 0x0000000000b09a65 in operator() (this=0x15479898) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/std_function.h:706
#14 operator() (this=<optimized out>, arg=0x2e77dd60) at external/envoy/source/common/common/posix/thread_impl.cc:39
#15 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::function<void ()>)::$_0::__invoke(void*) (arg=0x2e77dd60) at external/envoy/source/common/common/posix/thread_impl.cc:38
#16 0x0000000000c7c104 in start_thread (arg=0x7ff3d59c9700) at pthread_create.c:312
#17 0x0000000000d2e989 in clone ()
```

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: low
Testing: new unit test
Docs Changes: n/a
Release Notes: n/a
Fixes #6872

### CODE REVIEW

**Comment by alyssawilk** [comment]
We could arguably future-proof a little better by moving all the callbacks to delay_close_callbacks, and only  doing raiseEvent for disconnects on those.  I figured this was both simpler and safer so went with this for now.

**Comment by mattklein123** [comment]
Per https://github.com/envoyproxy/envoy/issues/6872#issuecomment-494522845 I agree with you that I'm not sure this is the actual problem. Should we hold on this until I can look at an actual core dump and debug a bit more?

**Comment by alyssawilk** [comment]
I picked it up anyway, because even if it's not causing seg-faults I feel like after the connection has been delay-closed we shouldn't be using the callbacks for anything other than raising the actual close.  If there were something buffered in the HCM (like the h2 codec had its own control frame buffer) I don't think we'd want to be draining more at the L7 layer.  If you disagree I'm happy to close this out though.

**Comment by mattklein123** [comment]
> If you disagree I'm happy to close this out though.

I could go either way on this and don't feel strongly about it. One one hand, maybe it makes sense for the connection owner to be notified of buffer drain even during delayed closing processing, on the other hand, I agree this is probably fine and simple. Although, I don't think going about high watermark should ever happen during delay close, right? Should we cover that case also?

**Comment by alyssawilk** [comment]
We can close it out until we have a handle on that crash

**Pull request closed without merging**
