### PR TITLE
bump cel-cpp

### PR DESCRIPTION
**Pull request by asedeno**
Update cel-cpp to `HEAD` as of when this PR was made, and drop the now-obsolete patches.

https://github.com/google/cel-cpp/commit/b03438ae95cac305d672b56c35472894a09fba19

Risk Level:
Testing: CI

### CODE REVIEW

**Comment by asedeno** [comment]
This PR will complete and obsolete #36167 and #35514. (cc: @kyessenov)

**Comment by asedeno** [comment]
We've got a gcc build issue; I'm working on fixing that upstream.

**Comment by phlax** [comment]
@asedeno this (re-) adds a bit of noise to the build

```console
external/com_google_cel_cpp/common/internal/reference_count.cc:83:33: warning: offset of on non-standard-layout type 'cel::common_internal::(anonymous namespace)::ReferenceCountedString' [-Winvalid-offsetof]
    internal::SizedDelete(that, offsetof(ReferenceCountedString, data_) + size);
                                ^                                ~~~~~
/opt/llvm/lib/clang/14.0.0/include/stddef.h:104:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^                     ~
```

```console

INFO: From Compiling internal/well_known_types.cc:
In file included from external/com_google_cel_cpp/internal/well_known_types.cc:15:
external/com_google_cel_cpp/internal/well_known_types.h:1133:52: warning: private field 'fields_key_field_string_type_' is not used [-Wunused-private-field]
  google::protobuf::FieldDescriptor::CppStringType fields_key_field_string_type_;
```

```console
 INFO: From Compiling common/type_factory.cc:
external/com_google_cel_cpp/common/type_factory.cc:25:6: warning: unused function 'IsValidMapKeyType' [-Wunused-function]
bool IsValidMapKeyType(const Type& type) {
     ^
1 warning generated.
```

can we resolve upstream or failing that patch it out?

**Comment by asedeno** [comment]
> @asedeno this (re-) adds a bit of noise to the build

Working on it now; which specific build(s) did you pull these from? I want to cross-reference against `HEAD` to see what new warnings have popped up.

**Comment by phlax** [comment]
iirc the `./ci/do_ci.sh release.test_only` in prechecks

**Comment by phlax** [comment]
https://github.com/envoyproxy/envoy/actions/runs/11391229612/job/31694585390#step:12:583

**Comment by asedeno** [comment]
The warnings have been resolved upstream.

**Review by phlax — APPROVED** [review]
lgtm, thanks @asedeno

**Pull request merged**
