### PR TITLE
[balsa] Use OnHeader() for header parsing.

### PR DESCRIPTION
**Pull request by bencebeky**
In BalsaParser, call ParserCallbacks::onHeaderField() and
onHeaderValue() when the newly added BalsaVisitorInterface::OnHeader()
[1] is called, that is, immediately as the headers and trailers are
parsed, instead of waiting for the ProcessHeaders() or ProcessTrailers()
call with the entire header block.  This will be necessary to fix
certain tests in
//test/common/http/http1:codec_impl_test that operate on incomplete
input and rely on an error being signalled as soon as the incorrect
header or trailer is parsed.

This change, however, does not make any tests from codec_impl_test pass
with BalsaParser on its own.

[1]
https://github.com/google/quiche/commit/b159ae36aec18154f8de547be7637a024f58ca1c

Signed-off-by: Bence Béky <bnc@google.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by bencebeky** [comment]
/assign @diannahu @birenroy 

PTAL

**Review by diannahu — APPROVED** [review]
A nice simplification in its own right!

**Review by KBaichoo — APPROVED** [review]
thanks, lgtm!

**Pull request merged**
