### PR TITLE
upstream: Fix a bug in trace output from the ring hash lb

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
upstream: Fix a bug in trace output from the ring hash lb in which the ring hash value contained uninitialized data

Signed-off-by: Ryan Hamilton <rch@google.com>

Risk Level: Low?
Testing: Unit tests pass
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by lizan — APPROVED** [review]

**Comment by RyanTheOptimist** [comment]
I verified that this fix was correct by running //test/common/upstream:ring_hash_lb_test and looking at the trace output (which I manually turned into error output. Without this fix there were various control characters in some test output. With this fix there were none. Not sure if there is a better way to verify this, but this worked for me :)

**Comment by jmarantz** [comment]
lgtm with 1 quick question: is it easy to write a unit test for this?

**Review by jmarantz — APPROVED** [review]
oh...based on an internal chat I thought this might have been a deeper problem affecting the data structures.

This is just a trace log so never mind about the unit test.

**Comment by RyanTheOptimist** [comment]
> oh...based on an internal chat I thought this might have been a deeper problem affecting the data structures.
> 
> This is just a trace log so never mind about the unit test.

Yes, I thought the same thing too! When my "fix" didn't work I kinda went crazy trying to figure out why until I realized it was an inappropriate use of `.data()`. *facepalm*

**Comment by RyanTheOptimist** [comment]
Thanks for the reviews!

**Pull request merged**
