### PR TITLE
bootstrap/runtime: remove support for v2 bootstrap runtime field.

### PR DESCRIPTION
**Pull request by htuch**
This is the first PR in a series to remove v2 API support from Envoy.

The process is as follows:
1. Identify uses of a hidden_envoy_deprecated_* field in source/.
2. Remove implementation support for occurences identified in (1).
3. Remove any tests in test/ covering (1). It is necessary to validate
   manually that other tests exist for replacement functionality; in
   some cases the deprecated test might be providing functional coverage
   not applied to the deprecated feature's replacement.
4. Wash, rinse and repeat.

Risk level: Low
Testing: Added a unit test to cover otherwise missing behaviors in
runtime.

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

**Comment by ankatare** [comment]
Thanks a lot for @htuch .. let me check this

**Comment by ankatare** [comment]
would like to work on this with you...  :) . please suggest how to proceed ?

**Comment by htuch** [comment]
@ankatare follow the set of steps 1-4 described in the commit message above.

**Review by ggreenway — APPROVED** [review]

**Comment by ankatare** [comment]
@htuch Just thinking if we have any  milestone set for this activity ?

**Comment by htuch** [comment]
@ankatare I'd hope we could have all v2 dependencies gone by next release.

**Comment by ankatare** [comment]
@htuch Ok. Gt it. Thanks

**Comment by ankatare** [comment]
@htuch @tyxia just thinking if below code also need to be removed ? 

https://github.com/envoyproxy/envoy/blob/main/source/common/protobuf/utility.cc#L372-L396

please suggest.

**Comment by htuch** [comment]
I think so, but we might want to wait until `generated_api_shadow/` is gone to be sure; I'll be doing the PR for this in the next week.

**Comment by tyxia** [comment]
> @htuch @tyxia just thinking if below code also need to be removed ?
> 
> https://github.com/envoyproxy/envoy/blob/main/source/common/protobuf/utility.cc#L372-L396
> 
> please suggest.
@ankatare  

Yea, this is being worked on in PR #17924, but as htuch suggested we will wait for the `generated_api_shadow/` removal first.

**Comment by ankatare** [comment]
@tyxia @htuch cool. Thanks for Confirmation 👍

**Comment by ankatare** [comment]
Hi @tyxia cc @htuch i Could see some pending work in my local main. Please let me know if you are working on those OR i can take anyone if not.
**/envoy$ grep -rnw ./source/ -e 'hidden_envoy_deprecated_.*'**
./source/extensions/tracers/zipkin/span_buffer.cc:53:        "hidden_envoy_deprecated_HTTP_JSON_V1 has been deprecated. Please use a non-default "
./source/common/protobuf/utility.cc:372:      if (absl::StartsWith(field.name(), "hidden_envoy_deprecated_")) {
./source/common/protobuf/utility.cc:380:              "Illegal use of hidden_envoy_deprecated_ V2 field '", field.full_name(),

**Comment by ankatare** [comment]
also under **test/** Directory as below
envoy$ grep -rnw ./test/ -e 'hidden_envoy_deprecated_.*'
./test/extensions/tracers/zipkin/span_buffer_test.cc:469:      "hidden_envoy_deprecated_HTTP_JSON_V1 has been deprecated. Please use a non-default "
./test/proto/deprecated.proto:41:  string hidden_envoy_deprecated_is_deprecated = 2 [deprecated = true];
./test/proto/deprecated.proto:42:  string hidden_envoy_deprecated_is_deprecated_fatal = 3 [deprecated = true];
./test/proto/deprecated.proto:45:    string hidden_envoy_deprecated_inner_deprecated = 2 [deprecated = true];
./test/proto/deprecated.proto:46:    string hidden_envoy_deprecated_inner_deprecated_fatal = 3 [deprecated = true];
./test/proto/deprecated.proto:48:  InnerMessage hidden_envoy_deprecated_deprecated_message = 4 [deprecated = true];
./test/proto/deprecated.proto:51:  repeated InnerMessage hidden_envoy_deprecated_deprecated_repeated_message = 7 [deprecated = true];
./test/proto/deprecated.proto:56:    hidden_envoy_deprecated_DEPRECATED_DEFAULT = 0 [deprecated = true];
./test/proto/deprecated.proto:58:    hidden_envoy_deprecated_DEPRECATED_NOT_DEFAULT = 2 [deprecated = true];
./test/server/server_corpus/clusterfuzz-testcase-minimized-config_fuzz_test-5702999713513472:196:  hidden_envoy_deprecated_config {
./test/server/server_corpus/crash-ac725507195d840cdb90bed3079b877e6e9419e3:6:hidden_envoy_deprecated_runtime {
./test/server/server_corpus/clusterfuzz-testcase-minimized-config_fuzz_test-5186283155750912:40:        hidden_envoy_deprecated_disable_overprovisioning: true
./test/server/server_corpus/clusterfuzz-testcase-minimized-config_fuzz_test-5186283155750912:51:  hidden_envoy_deprecated_config {
./test/common/protobuf/utility_test.cc:1889:      hidden_envoy_deprecated_is_deprecated: hidden_field1
./test/common/protobuf/utility_test.cc:1900:      "Illegal use of hidden_envoy_deprecated_ V2 field "
./test/common/protobuf/utility_test.cc:1901:      "'envoy.test.deprecation_test.UpgradedBase.hidden_envoy_deprecated_is_deprecated'");

**Comment by ankatare** [comment]
@tyxia would you please look on my above comments.

**Comment by ankatare** [comment]
i am seeing below WI is pending.. please suggest if i can take this to mark "`remove v2 support` "as finished 

envoy$ grep -rnw ./source/ -e 'hidden_envoy_deprecated_.*'
./source/extensions/tracers/zipkin/span_buffer.cc:53:        "hidden_envoy_deprecated_HTTP_JSON_V1 has been deprecated. Please use a non-default "

**Comment by ankatare** [comment]
@htuch Need your inputs on this remaining WI.

**Comment by ankatare** [comment]
@htuch @tyxia Sorry, It's My Bad :( .
i can see, now there is no pending WI for V2 support removal. Above cases are just exceptions which is required to handle the cases.

**Comment by tyxia** [comment]
> @htuch @tyxia Sorry, It's My Bad :( . i can see, now there is no pending WI for V2 support removal. Above cases are just exceptions which is required to handle the cases.

@ankatare Yea, the remaining `hidden_envoy_deprecated*`s are either used for exceptions to catch invalid configs or used to skip unused cases . So, in short I think there is no pending work for removing `hidden_envoy_deprecated*`. There are a few cleanup works though and I have a draft CL.

**Comment by ankatare** [comment]
@tyxia Great, Thanks for update.

**Pull request merged**
