### PR TITLE
deps: Bump `com_github_bufbuild_buf` -> v1.3.1

### LINKED ISSUE #20610: Newer release available `com_github_bufbuild_buf`: v1.3.1 (current: v0.53.0)
Package Name: com_github_bufbuild_buf@0.53.0
Current Version: v0.53.0@2021-08-25
Available Version: v1.3.1@2022-03-31
Upstream releases: https://github.com/bufbuild/buf/releases

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #20610
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @adisuissa

**Comment by moderation** [comment]
I need to dig into why we need this dependency

/lgtm deps

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Comment by adisuissa** [comment]
Tracking the re-enablement of the tool in #20746.

**Pull request merged**
