### PR TITLE
Dependencies: dataplane (Thrift) move to pip3 + SHA256 pinning of pip…

### PR DESCRIPTION
**Pull request by moderation**
Signed-off-by: moderation michael@sooper.org

Risk Level: Low
Testing:
- `bazel --nohome_rc test //test/extensions/filters/network/kafka/...`
- `bazel --nohome_rc test //test/extensions/filters/network/thrift_proxy/...`

/cc @htuch, @antoniovicente in case this triggers for Thrift the same issue you had with the Kafka transition to pip3 and @zuercher, @rgs1 because Thrift. I tried to convert the Twitter Thrift stuff to pip3 but couldn't make it work. The code is super old and deprecated. Couldn't get the Finagle protocol bits to be seen by `client.py` and `server.py`.

Docs Changes:
- TODO `DEPENDENCY_POLICY.md` if we think this approach is OK (https://github.com/envoyproxy/envoy/issues/12951#issuecomment-685890459)
- TODO `docs/generate_external_dep_rst.py` as we lose CPE metadata when moving from `bazel/repository_location.bzl` to pip3 import

Release Notes: none required

Comment: I've included CPE metadata as comments in `bazel/repositories_extra.bzl`. I thought this would be better for programmatic inclusion in `docs/generate_external_dep_rst.py`

### CODE REVIEW

**Review by zuercher — APPROVED** [review]
Thrift part looks good to me. Thanks!

**Comment by moderation** [comment]
assign @htuch

**Review by htuch — APPROVED** [review]
Awesome, thanks!

**Comment by htuch** [comment]
@moderation LGTM, should I merge this or do you want to do any of the TODOs?

**Comment by moderation** [comment]
Merge please and I'll do follow up PRs for the TODOs

**Pull request merged**
