### PR TITLE
bring in circleci module

### PR DESCRIPTION
**Pull request by itayd**
Signed-off-by: Itay Donanhirsh <itay@bazoo.org>

*Description*:
Bring in repokitteh's circleci module. This will allow people to `/retest` their change in CI.

*Risk Level*:
Low.

*Testing*:
See this PR.

*Docs Changes*:
Upcoming PR.

*Release Notes*:
None.

### CODE REVIEW

**Comment by itayd** [comment]
I'd like to get this in, then make a demo PR, then write docs that point to it. Will be much less noisier on the demo PR.

**Comment by mattklein123** [comment]
OK SGTM

**Pull request merged**
