### PR TITLE
docs: Add admin section back to quick-start demo (Fix #14811)

### LINKED ISSUE #14811: quick start demo file doesn't enable admin
https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/run-envoy says that starting envoy with the given demo config `envoy-demo.yaml` should result in:

> The Envoy admin endpoint should also be available at http://localhost:9901

It doesn't seem to working, as the admin section is not enabled in the config.

### PR DESCRIPTION
**Pull request by sandipb**
Makes the config file consistent with the documentation.

Fixes #14811

Signed-off-by: Sandip Bhattacharya <sandipb@showmethesource.org>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/master/api/review_checklist.md):]

### CODE REVIEW

**Review by phlax — APPROVED** [review]
lgtm, thanks @sandipb

**Comment by phlax** [comment]
@sandipb if you add "Fix #14811" to the description it should auto close your bug when it is merged

**Comment by sandipb** [comment]
> @sandipb if you add "Fix #14811" to the description it should auto close your bug when it is merged

I was not sure which description you meant :) I updated the pull request description. Or do you think the git commit itself should have it in the description?

**Comment by phlax** [comment]
either should work - the pr is probs best so it is obvious to reviewers

**Comment by phlax** [comment]
see this section in description:

>  [Optional Fixes #Issue]

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
