### PR TITLE
Add experimental_compiler_features filter

### PR DESCRIPTION
**Pull request by martinezlucas98**
The purpose of this filter is to serve as a basis (or example) for
writing filters with experimental features such as new features
from C++20.

This filter should be considered as optional.

Issue: #15874

Note:
Since (at this time) not all compilers fully support C++20, the use
of preprocessor conditional compilation directives is a must.
For more information about features macro name you could visit:
https://en.cppreference.com/w/cpp/feature_test

Risk Level:  Low or medium (small optional feature / new filter)

Testing:  Unit test

Signed-off-by: martinezlucas98 <lucasoctaviom@gmail.com>

### CODE REVIEW

**Comment by martinezlucas98** [comment]
I'm aware that this filter still needs a maintainer owner on CODEOWNERS, who should I add?
Any other recommendations or comments are more than welcome, thanks!.

**Comment by mattklein123** [comment]
I see that you put a lot of work into this, and I'm sorry to say this, but I don't see the value that this adds. 
1) In and of itself it doesn't add value to Envoy and will create maintenance burden
2) I'm still against adding C++20 support for C++20 sake. What compiler feature is really necessary right now?

If we are going to add a filter with C++ 20 support please add a filter or extension that people would actually want to use.

/wait

**Comment by martinezlucas98** [comment]
Sure, I agree with you that at this moment there is no much need for C++20 to be implemented.
This filter is meant to be an example for those interested in creating their custom filters -or simply experimenting- using newer C++ versions.
Thank you for your time @mattklein123

**Comment by mattklein123** [comment]
> This filter is meant to be an example for those interested in creating their custom filters -or simply experimenting- using newer C++ versions.

Sounds good, let's link this to the tracking issue and people can refer to this as needed. Thank you!

**Pull request closed without merging**
