### PR TITLE
bazel: transport sockets: Update grpc to 1.19.1

### PR DESCRIPTION
**Pull request by mrostecki**
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

Description: Update grpc to 1.19.1
Risk Level: Low
Testing: Unit tests
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by moderation** [comment]
I'd suggest adding a TODO to the ALTS change indicating that ALTS should be updated for the function calls rather than adding nullptr - see https://github.com/envoyproxy/envoy/issues/5461

**Comment by lizan** [comment]
I think we need to fix ALTS build issue with latest gRPC, @JimmyCYJ @htuch?

**Comment by htuch** [comment]
Yep, please do fix ALTS properly for this. Thanks for the contribution @mrostecki.

**Comment by mrostecki** [comment]
@htuch @moderation Thanks for pointing that out! I will fix ALTS properly.

**Pull request closed without merging**
