### PR TITLE
codeql: improve Ubuntu dependency installation

### PR DESCRIPTION
**Pull request by jpeach**
Commit Message:

If apt can't update the package index, it doesn't exit with an error
by default, so add the `--error-on=any` flag to force an error.

Pass the `--yes` flag to the install to force non-interactive mode.

Additional Description: This change ought to make the CI error in #16541 more obvious.
Risk Level: Low
Testing: None
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by jpeach** [comment]
CI checks failed with this error:
```
ERROR: ./docs/root/version_history/current.rst:68: Version history not in alphabetical order (http vs crash support): please check placement of line
```
 which I believe will be fixed by #16555

**Comment by phlax** [comment]
@jpeach its wierd that this didnt fail anyway - on the azure build it also hit this issue but did fail

relatedly im wondering whether we should remove (with sed i guess) the ms packages source - afaiaa its unused in both cases

**Comment by jpeach** [comment]
> @jpeach its wierd that this didnt fail anyway - on the azure build it also hit this issue but did fail
> 
> relatedly im wondering whether we should remove (with sed i guess) the ms packages source - afaiaa its unused in both cases

Yeh, I'm not sure why the other PR gets the failure. It looks like the apt install fails but still exits 0 and I'm not sure why that happens. I think the changes in this PR are a slight improvement, but not sure whether they will fix the issue fully.

**Comment by phlax** [comment]
im not sure that this change is necessary and/or will have any effect

my guess re the reason its not failing is that its not being run `-e` - if that is the case `--error-on` wont have any effect

regarding the `--yes` flag - im kinda surprised that it works normally without this - either way i dont think it will have any bearing on the failure

**Comment by jpeach** [comment]
GitHub documents the bash shell as being run with `-e`.

I think this change is a slight improvement. It's more explicit and passes the right flags to get the behavior we want, but whether it fixes the actual problem seen in other PRs? Probably have to suck it and see :)

**Comment by zuercher** [comment]
@phlax is worth giving this a try?

**Comment by phlax** [comment]
> is worth giving this a try?

perhaps - the `-y` flag certainly wont hurt - and i guess neither will the `--error-on` flag - im just not convinced that it changes anything - i dont want to block it tho

**Review by lizan — APPROVED** [review]

**Pull request merged**
