### PR TITLE
kafka: upgrade dependencies to 3.5.1

### PR DESCRIPTION
**Pull request by adamkotwasinski**
Commit Message: kafka: upgrade dependencies to 3.5.1
Additional Description: upgrade dependencies, the newest message type is not supported because I still need to deliver some more code there; should be safe to backport (because it's only Kafka protocol)
Risk Level: Low
Testing: integration testing with full stack; manual testing with [envoy-kafka-tests](https://github.com/adamkotwasinski/envoy-kafka-tests/pull/9)
Docs Changes: version numbers
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by adamkotwasinski** [comment]
Weirdness. Repokitteh didn't restart my builds. Here we go again.

**Comment by phlax** [comment]
https://github.com/envoyproxy/envoy/issues/28934

**Comment by adamkotwasinski** [comment]
Ready for review - it finally builds!

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
