### PR TITLE
[balsa] Add config field to enable custom methods.

### PR DESCRIPTION
**Pull request by bencebeky**
This is no behavioral change by default: only methods from a hard-coded list (that matches the list hard-coded in http-parser, and is slightly different from the one that will be used by UHV) are accepted.

Then the new knob is true, BalsaParser does the exact same validation as UHV will by default: method has to be non-empty and only contain allowed characters.

When UHV method validation logic is turned on in the future, all validation can be removed from BalsaParser. When non-UHV mode is deprecated, this new proto field can be removed.

This is reverting the part of #25714 that allows custom headers unconditionally if ENABLE_ENVOY_UHV is defined. This compile time option will be rolled out first in the process of launching UHV, and it is important not to introduce behavioral changes with it.

Tracking issue: #21245

Commit Message: [balsa] Add config field to enable custom methods.
Additional Description:
Risk Level: low, changed code is protected by existing default-false runtime flag.
Testing: //test/common/http/http1:codec_impl_test
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a
Runtime guard: envoy.reloadable_features.http1_use_balsa_parser

### CODE REVIEW

**Comment by mattklein123** [comment]
LGTM at a high level. Assigning over to @yanavlasov for review/merge as area owner.

**Comment by bencebeky** [comment]
/assign @alyssawilk 
Alyssa: please verify that this PR achieves what we are aiming for.

**Review by yanavlasov — APPROVED** [review]

**Comment by bencebeky** [comment]
> Thinking more about this. Do we need this functionality ahead of UHV?

Making this functionality available costs exactly as much as landing this PR, and deprecating the field in the future in the same PR that deprecates the adjactent Balsa field. Given the projected timeline of Balsa rollout and UHV rollout, I think this is a reasonable cost for bringing this ahead.

**Comment by alyssawilk** [comment]
@yanavlasov I agree on this - UHV isn't even landed and I suspect will remain months behind balsa, so adding a removable knob seems pretty cheap to me.

**Comment by adisuissa** [comment]
@yanavlasov gentle ping.

**Review by alyssawilk — APPROVED** [review]

**Comment by yanavlasov** [comment]
We have some internal discussions about this change. Will update PR when we sort it out.

**Pull request merged**
