### PR TITLE
Add Platform Specific Feature guidance to PR template

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Commit Message: Add Platform Specific Feature guidance to PR template
Additional Description: The intent of this change is to ensure platform specific features or features that a contributor PRs without for example Windows support fully implemented get a tracking issue and specific consideration from that fact from reviewers. This will help some of the platform-specific contributor groups to discover the gaps that need to be filled on a given platform without having to follow each PR.
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Review by htuch — COMMENTED** [review]
LGTM, @envoyproxy/maintainers for visibiltiy

**Review by junr03 — COMMENTED** [review]
Thanks! I was looking forward to this after you discussed it in this morning's community meeting. This will also be relevant for Apple and Android specific changes (as we have had in the past driven by needs in Envoy Mobile).

**Review by mattklein123 — APPROVED** [review]
Awesome, thanks!

**Review by ggreenway — APPROVED** [review]
LGTM

**Pull request merged**
