### PR TITLE
LB: edf by timer wheel

### PR DESCRIPTION
**Pull request by lambdai**
Commit Message:
Add an experimental edf scheduler powered by timer wheel.
Additional Description:

With the naive timer wheel the cost of pick/peek/add host is reduced.
Almost constant cost regardless of the number of hosts is tens or thousands.  
No bias toward the earlier host because `current_time_` is not bumped when adding new hosts except when the first host is added.
We move unweighted to udf if the timer wheel cost is acceptable.

The trade-off includes 
RR is not that strict. All the entries in the same slot are FIFO when picking(but not adding). Could be mitigated by carefully select the per slot time range.
Sparse slots can hamper the performance. Can be mitigated by a hierarchical time wheel to handle a very low weight host.

Performance: `wheel` is the new and `heap` is the current. The parameter is the number of hosts.
Each iteration in the row runs 1 million `pickAndAdd`. The existing heap or priority queue implementation adds 15-20ms when the hosts are 8x.
``` 
------------------------------------------------------
Benchmark            Time             CPU   Iterations
------------------------------------------------------
heap/1            73.0 ms         73.0 ms           10
heap/8            89.0 ms         89.0 ms            8
heap/64            109 ms          109 ms            6
heap/512           130 ms          130 ms            5
heap/4096          151 ms          151 ms            5
heap/10000         158 ms          158 ms            4
wheel/1           71.5 ms         71.5 ms           10
wheel/8           70.6 ms         70.6 ms           10
wheel/64          70.7 ms         70.7 ms           10
wheel/512         71.4 ms         71.4 ms           10
wheel/4096        77.6 ms         77.6 ms            9
wheel/10000       79.9 ms         79.9 ms            9
```
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
TimerWheel (1)

### CODE REVIEW

**Comment by mattklein123** [comment]
@lambdai see also https://github.com/envoyproxy/envoy/pull/14681 that @tonya11en is working on. Stepping back, we have had a lot of conversations recently about changes to EDF. Can you provide some background on where this change is coming from? I want to make sure we are all working towards the same goals.

**Comment by lambdai** [comment]
I am offline during the past month and I am catching up with the update...

This time wheel implementation is inspired by `Hierarchical Time Wheels` but non-hierarchical is showing great improvement on the dataset. See paper http://www.cs.columbia.edu/~nahum/w6998/papers/ton97-timing-wheels.pdf

I had a quick glance at @tonya11en's #14681 and I find that one work better if the weight is predefined.

This time wheel impl is more flexible on weight value set. Yet it's degrading if the weight set has outlier values...

**Comment by tonya11en** [comment]
> This time wheel impl is more flexible on weight value set. Yet it's degrading if the weight set has outlier values...

Can you elaborate more on this? At first glance, it seems similar to the interleaved weighted round-robin (IWRR) approach I looked at in https://github.com/tonya11en/envoy/pull/1#issuecomment-744085044. The behavior was sensitive to the weight values in that a full "cycle" was dictated by those values. How is this HHWheel approach affected by weight values exactly?

**Comment by lambdai** [comment]
@tonya11en Thank you for the link! I read the implementation of IWRR. Yes, it's quite similar. If the timer wheel has only two slots, the timer wheel implementation degrade to IWRR, where the first bucket has the name "curr_weights_" and the next bucket is named "weights_".

So both implementation do RR if entries are in the same bucket, until the budget within the entry runs out.

The major divergence is how the budgets refill.
In IWRR, if a small double value weight (e.g 0.3 ) is decreased by 1, ideally it should be erased in next round instead refill it with 0.3. So weight = 0.3 acts exactly as weight = 1.

I am pretty sure you can add more states into per entry, but you will encounter the next thing: only part of the entries will be selected into the next generation of "curr_weights". To address these optimizations, the solution may get closer to the timer wheel.

Timer wheel maintains a smoother budget refill as was in the priority queue. Comparing to priority queue, it's always a small portion are selected as the next round, which is the next "non empty bucket". Not any operator<() is needed. (Half true, since there is a future pool which maintains the entries which have very large deadline)

**Comment by tonya11en** [comment]
Could you update the benchmarks with the pathological weights, just so we can get a sense of the differences?

**Comment by lambdai** [comment]
close for now

**Pull request closed without merging**
