### PR TITLE
ci: Optimize shebang of bash scripts to enhance compatibility

### LINKED ISSUE #33426: ci/do_ci.sh reports an error when /bin/bash version less than 4.0
*Title*: 
`ci/do_ci.sh` reports an error when /bin/bash version less than 4.0

*Description*:
`ci/do_ci.sh` reports an error when /bin/bash version less than 4.0 since `;&` is available in versions higher than Bash 4.0
```bash
$ NUM_CPUS=9 ./ci/do_ci.sh  api.go
ENVOY_SRCDIR=/Users/zehuan.szh/work/code/asm-dep/envoy
ENVOY_BUILD_TARGET=//source/exe:envoy-static
ENVOY_BUILD_ARCH=arm64
BUILD_DIR not set - defaulting to ~/.cache/envoy-bazel
Setting test_tmpdir to /Users/zehuan.szh/.cache/envoy-bazel/tmp.
LLVM_ROOT not found, not setting up llvm.
Skip setting up Envoy Filter Example.
building using 9 CPUs
building for arm64
CI_TARGET=api.go
./ci/do_ci.sh: line 285: syntax error near unexpected token `;'
```
which is pointed this line:
```bash
        ...
              -c fastbuild @envoy_api//envoy/...
        if [[ -n "$ENVOY_API_ONLY" ]]; then
            exit 0
        fi  
        ;& <----- the ;& is available after bash 4.0.

    api.go)
        setup_clang_toolchain
        GO_IMPORT_BASE="github.com/envoyproxy/go-control-plane"
        GO_TARGETS=(@envoy_api//...)
        ...
```

*Repro steps*:
This problem is easy to reproduce on Mac OS. As of MacOS 14.4, the version of /bin/bash is 3.2.57.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

If this should be fixed, I'd happy to take it.

### PR DESCRIPTION
**Pull request by xocodergit**
Commit Message:
Replace `#!/bin/bash` with `#!/usr/bin/env bash` in bash scripts to ensure they execute with the bash specified by the local environment(#33426)
Additional Description:

Risk Level: Low
Testing: Unit & Integration
Docs Changes: 
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
Fixes #33426 
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@xocodergit could you fix DCO please

**Comment by xocodergit** [comment]
> CodeQL/push / CodeQL-Build (pull_request)

Done. Does the CodeQL analysis fail because there are no C++ code changes? Should this PR skip CodeQL analysis?

**Comment by phlax** [comment]
> Should this PR skip CodeQL analysis?

yeah - it diffs the files and is supposed to skip if none match

here

https://github.com/envoyproxy/envoy/blob/a9ba9187f6b567d0432d1325d65bb791eb2554c6/.github/workflows/codeql-push.yml#L39-L64

**Review by phlax — APPROVED** [review]
lgtm, thanks for following up on this @xocodergit

**Comment by phlax** [comment]
re codeql - seems there is a small bug there

afaict the issue is that changes to shell scripts in `//source/common/...` are triggering the change

for this PR we can push through i think

**Pull request merged**
