### PR TITLE
tools: Enable the proto format script to use bazelisk

### PR DESCRIPTION
**Pull request by abeyad**
If bazelisk is installed, tools/proto_format/proto_format.sh will use
it; if bazelisk is not installed, bazel will be used.

Signed-off-by: Ali Beyad <abeyad@google.com>

### CODE REVIEW

**Comment by phlax** [comment]
@abeyad i guess the motivation here is at least partly as it is triggered by the git hooks - im wondering if we should make any change there

**Comment by abeyad** [comment]
> @abeyad i guess the motivation here is at least partly as it is triggered by the git hooks - im wondering if we should make any change there

@phlax I actually ran into this issue trying to run the script on my local machine, which is why I thought this change would be convenient for whichever environment the script runs in.  Which git hooks are you referring to?

**Comment by phlax** [comment]
> Which git hooks are you referring to?

the ones in the Envoy repo - partly the reason for keeping this is a script is that it is used there - the other is that it is used in CI

i guess my reluctance is that this script itself might be made to a bazel target so it doesnt feel like the right place to be checking for bazel/isk 

the common use case outside of running it directly is with the build container

mostly i run it directly - but in an env with some stuff set up already

i guess the other possibility is having something set up locally to check for bazel/isk as that seems to be more of an issue with the local env, given that so much else of the repo requires the use of bazel - that wouldnt go through this script

**Comment by abeyad** [comment]
> i guess my reluctance is that this script itself might be made to a bazel target so it doesnt feel like the right place to be checking for bazel/isk

Ah ok, so I think what you're saying is that we should just run the bazel target that the script invokes directly if we're running it locally (and then we can use bazelisk instead of bazel if we want)?

> i guess the other possibility is having something set up locally to check for bazel/isk as that seems to be more of an issue with the local env, given that so much else of the repo requires the use of bazel - that wouldnt go through this script

But if we set up something locally to check for bazelisk, how would we get the scripts to use that without changing the scripts too?

**Comment by phlax** [comment]
i was thinking just doing what envoy-build-tools does and making the bazelisk script available at `/usr/local/bin/bazel` or similar

**Comment by abeyad** [comment]
> i was thinking just doing what envoy-build-tools does and making the bazelisk script available at `/usr/local/bin/bazel` or similar

Ah ok, that's an interesting idea.  I can give that a try.  I believe bazelisk installs the different versions of bazel that it uses in different directories than /usr/local/bin so hopefully it won't cause a conflict.

**Comment by phlax** [comment]
see here https://github.com/envoyproxy/envoy-build-tools/blob/0f17a22c7902e21e5e003f5296adb628d2f16b2f/build_container/build_container_common.sh#L62-L66

**Comment by abeyad** [comment]
> see here https://github.com/envoyproxy/envoy-build-tools/blob/0f17a22c7902e21e5e003f5296adb628d2f16b2f/build_container/build_container_common.sh#L62-L66

Yup, I did something similar in my environment and it works well :) 
I'm good with closing this PR if you think that's best.

**Pull request closed without merging**
