### PR TITLE
Enables the new HTTP/2 codec wrapper API by default.

### PR DESCRIPTION
**Pull request by birenroy**
Signed-off-by: Biren Roy <birenroy@google.com>

Commit Message: Enables the new HTTP/2 codec wrapper API by default.
Additional Description: At least two major users of Envoy (Pinterest and Google) have run with the feature enabled in production since December.
Risk Level: Medium
Testing: Integration tests already run with the feature enabled.
Docs Changes:
Release Notes:
[Runtime guard:] envoy.reloadable_features.http2_new_codec_wrapper

### CODE REVIEW

**Review by adisuissa — COMMENTED** [review]
Code changes LGTM, thanks for following up.
@alyssawilk other than us, has anyone else enabled this flag, and have you heard of any problems?

**Comment by alyssawilk** [comment]
Pinterest did, and had issues with logspam.  @birenroy just to check 2 things before approving, we did the import fixing that?  And should there be any regression test or was that really something we wouldn't expect to see again?

**Comment by birenroy** [comment]
> Pinterest did, and had issues with logspam. @birenroy just to check 2 things before approving, we did the import fixing that? And should there be any regression test or was that really something we wouldn't expect to see again?

From what I can tell, that QUICHE import hasn't happened yet. I'm happy to wait for that before requesting that this pull request be merged.

**Comment by alyssawilk** [comment]
Yeah I think we don't want to default this on with the level of logspam reported, so let's wait for that merge
/wait

**Comment by birenroy** [comment]
> Yeah I think we don't want to default this on with the level of logspam reported, so let's wait for that merge /wait

Looks like the QUICHE import happened earlier today:
  https://github.com/envoyproxy/envoy/commit/d9f3fcb813364c449131af5d9bc8c51f45dce986

Note especially:
> 2022-01-14 quiche-dev Moves another noisy log to QUICHE_VLOG(1).
> 2022-01-13 quiche-dev Removes an error log for an event generated by the wrapper API.

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
