### PR TITLE
aws: add sigv4/a test corpuses

### PR DESCRIPTION
**Pull request by nbaws**
This patch adds around 160 test cases based on the aws signer test corpus from https://github.com/awslabs/aws-c-auth/tree/main/tests/aws-signing-test-suite

Adding these test cases uncovered the following bugs, which have also been fixed in this patch:
- Incorrect handling of UTF8 encoded parameters
- Incorrect path canonicalisation of paths containing /./
- Incorrect date calculation (missing seconds from the date formatter)
- Invalid handling of tilde within query parameters (also reported by Animal Logic leading to this patch)
- Invalid handling of other query parameter encodings

Commit Message: aws: add sigv4/a test corpuses and test cases
Additional Description:
Risk Level: Low
Testing: Unit
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by nbaws** [comment]
@phlax where do I find the configuration to ignore paths from code checker for test data?

**Comment by nbaws** [comment]
@mattklein123 @alyssawilk any thoughts on code checker exclusions? 

Also, this patch includes AWS test files sourced under Apache 2.0 license. I am guessing that wont be an issue, however the volume of test data included (while small in size) is a reasonable change, so keen to get an acknowledgement.

**Comment by phlax** [comment]
@nbaws apologies - i missed this question initially

the failing code checker doesnt currently use a config (altho probably should and will do at some point) - so for now its a case of adding an exclusion using the `-x` flag here https://github.com/envoyproxy/envoy/blob/bb28dda78d462851c1810047a4b1488a5a69279a/tools/code/BUILD#L62-L64

in this case tho - im wondering whether we should add the corpus to the envoy repo at all given they are published in a repository elsewhere

would it not be better to add the upstream as a (bazel) repo and read the corpus from there?

**Comment by nbaws** [comment]
works for me. i'll give that a try. thanks!

**Comment by nbaws** [comment]
> would it not be better to add the upstream as a (bazel) repo and read the corpus from there?

@phlax have done this via external dependency. Am not great at bazel, so there may be a much better way to do this, please let me know if so.

**Comment by phlax** [comment]
thanks @nbaws corpus inclusion looks correct to me

/lgtm deps

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
