### PR TITLE
docs: optimize bazel runs

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Comment by mattklein123** [comment]
This is a big improvement, but when I run the docs build and then fix format on protos, it is recompiling protobuf again so I think we need to unify the options between the tools also?

```
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/mklein/Source/envoy/tools/bazel.rc
INFO: Reading 'startup' options from /home/mklein/Source/envoy/.bazelrc: --host_jvm_args=-Xmx2g
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from /home/mklein/Source/envoy/.bazelrc:
  'build' options: --workspace_status_command=bazel/get_workspace_status --experimental_local_memory_estimate --experimental_strict_action_env=true --host_force_python=PY2 --action_env=BAZEL_LINKLIBS=-l%:libstdc++.a --action_env=BAZEL_LINKOPTS=-lm --host_javabase=@bazel_tools//tools/jdk:remote_jdk11 --javabase=@bazel_tools//tools/jdk:remote_jdk11 --enable_platform_specific_config --define absl=1 --action_env=CC --action_env=CXX --action_env=LLVM_CONFIG --action_env=PATH --test_env=HEAPCHECK=normal --test_env=PPROF_PATH
INFO: Reading rc options for 'build' from /home/mklein/Dropbox/linux_backup/.bazelrc:
  'build' options: --config=local --announce_rc
INFO: Found applicable config definition build:local in file /home/mklein/Dropbox/linux_backup/.bazelrc: --action_env=CXX=clang++ --action_env=CC=clang --action_env=PATH=/opt/llvm/bin:/usr/sbin:/usr/bin:/sbin:/bin --experimental_local_memory_estimate=true --jobs=7 --config=libc++
INFO: Found applicable config definition build:libc++ in file /home/mklein/Source/envoy/.bazelrc: --config=clang --action_env=CXXFLAGS=-stdlib=libc++ --action_env=LDFLAGS=-stdlib=libc++ --action_env=BAZEL_CXXOPTS=-stdlib=libc++ --action_env=BAZEL_LINKLIBS=-l%:libc++.a:-l%:libc++abi.a:-lm --define force_libcpp=enabled
INFO: Found applicable config definition build:clang in file /home/mklein/Source/envoy/.bazelrc: --action_env=BAZEL_COMPILER=clang --linkopt=-fuse-ld=lld
INFO: Found applicable config definition build:linux in file /home/mklein/Source/envoy/.bazelrc: --copt=-fPIC
Loading: 
Loading: 0 packages loaded
INFO: Build options --//tools/api_proto_plugin:default_type_db_target, --action_env, and --host_force_python have changed, discarding analysis cache.
Analyzing: target //tools/type_whisperer:api_build_file (0 packages loaded, 0 targets configured)
INFO: Analyzed target //tools/type_whisperer:api_build_file (4 packages loaded, 1512 targets configured).
INFO: Found 1 target...
```

**Comment by mattklein123** [comment]
I guess in `proto_format.sh`. @lizan @htuch wdyt?

**Comment by htuch** [comment]
I'm not sure if we should have a common `action_env` across all these tools. How come Bazel caching can't include `action_env` in the key? Is this a Bazel bug/feature?

As a hack, I guess we could thread a common `action_env` around, but it seems kind of hokey.

**Comment by htuch** [comment]
@dslomov do you have any idea why changing `--action_env` should cause cache invalidation? I understand you might need to build twice the first time around for two builds with different `--action_env`, but ideally these would then be cached for the future.

**Comment by mattklein123** [comment]
FWIW I think this changed somehow between bazel 2.0 and bazel 2.2. I did not see this behavior previously.

**Comment by dslomov** [comment]
> @dslomov do you have any idea why changing `--action_env` should cause cache invalidation? I understand you might need to build twice the first time around for two builds with different `--action_env`, but ideally these would then be cached for the future.

@meteorcloudy could you take a look?

**Comment by meteorcloudy** [comment]
Hey @htuch , I tried to reproduce this issue. But it seems Bazel 2.2.0 works as expected.
Both builds with and without an additional `--action_env=FOO=BAR` finished with full cache hit.

I suspect something else changed that caused the protobuf rebuild?

```
pcloudy@PCLOUDY2-W MSYS ~/workspace/my_tests/bazel
$ bazel build src/main/cpp:client
INFO: Invocation ID: 857b2972-d154-46e7-bdda-18bcedb6026f
INFO: Reading 'startup' options from c:\tools\msys64\home\pcloudy\.bazelrc: --output_user_root=C:/src/tmp
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=299
INFO: Options provided by the client:
  'build' options: --python_path=C:/Python36/python.exe
INFO: Reading rc options for 'build' from c:\tools\msys64\home\pcloudy\.bazelrc:
  'build' options: --curses=yes --color=yes --verbose_failures --announce_rc --disk_cache=C:/src/tmp/bazel_disk_cache
...
Target //src/main/cpp:client up-to-date:
  bazel-bin/src/main/cpp/client.exe
INFO: Elapsed time: 2.832s, Critical Path: 1.43s
INFO: 515 processes: 515 remote cache hit.
INFO: Build completed successfully, 517 total actions

pcloudy@PCLOUDY2-W MSYS ~/workspace/my_tests/bazel
$ bazel build src/main/cpp:client --action_env=FOO=BAR
INFO: Invocation ID: c9b158a6-d71c-44c0-b88d-8e0ce130b973
INFO: Reading 'startup' options from c:\tools\msys64\home\pcloudy\.bazelrc: --output_user_root=C:/src/tmp
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=299
INFO: Options provided by the client:
  'build' options: --python_path=C:/Python36/python.exe
INFO: Reading rc options for 'build' from c:\tools\msys64\home\pcloudy\.bazelrc:
  'build' options: --curses=yes --color=yes --verbose_failures --announce_rc --disk_cache=C:/src/tmp/bazel_disk_cache
...
Target //src/main/cpp:client up-to-date:
  bazel-bin/src/main/cpp/client.exe
INFO: Elapsed time: 3.133s, Critical Path: 1.40s
INFO: 515 processes: 515 remote cache hit.
INFO: Build completed successfully, 517 total actions

pcloudy@PCLOUDY2-W MSYS ~/workspace/my_tests/bazel
$ bazel version
Build label: 2.2.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Mar 3 09:28:29 2020 (1583227709)
Build timestamp: 1583227709
Build timestamp as int: 1583227709
```

**Comment by meteorcloudy** [comment]
@mattklein123 Does the rebuild still happen consistently?

**Comment by mattklein123** [comment]
Yes I can easily repro this. It must have something to do with the actual bazel commands we are using. We are using a bunch of complicated stuff around aspects, etc. Can you give me any tips on gathering debug info for you?

**Comment by meteorcloudy** [comment]
@mattklein123 Can you give me some instructions on how to reproduce this? A minimal repo could really help. If that's too complicated, can you provide the log, including what exact bazel command did you run.

**Comment by mattklein123** [comment]
@meteorcloudy the minimal repro would be:
1) Checkout envoy
2) Run `docs/build.sh` (note that you are likely to have to install various dependencies, which should be listed out here: https://github.com/envoyproxy/envoy/tree/master/bazel#quick-start-bazel-build-for-developers
3) Expect that on initial checkout, protobuf compiles once. Without the patch in this PR, it will compile multiple times (at least for me).
4) With this PR, protobuf compiles once and then does not recompile on subsequent docs builds.
5) Now run `tools/proto_format/proto_format.sh fix`. The expectation is that protobuf does not recompile. Even with this PR, it does recompile at least once. And then after it recompiles, `docs/build.sh` also causes recompilation.

**Comment by mattklein123** [comment]
I think the issue is that the bazel options here: https://github.com/envoyproxy/envoy/blob/34fcdef99633947543070d5eadf32867e940694e/tools/proto_format/proto_format.sh#L33-L35

Are you invalidating the cache and it needs to be made consistent as with docs/build.sh, or we might determine that Bazel is being too strict.

**Comment by mattklein123** [comment]
@lizan this additional diff "fixes" the problem for me:
```
diff --git a/tools/proto_format/proto_format.sh b/tools/proto_format/proto_format.sh
index 656e6466c..649f50efd 100755
--- a/tools/proto_format/proto_format.sh
+++ b/tools/proto_format/proto_format.sh
@@ -28,11 +28,10 @@ fi
 declare -r PROTO_TARGETS=$(bazel query "labels(srcs, labels(deps, @envoy_api_canonical//versioning:active_protos))")
 
 # This is for local RBE setup, should be no-op for builds without RBE setting in bazelrc files.
-BAZEL_BUILD_OPTIONS+=" --remote_download_outputs=all"
+BAZEL_BUILD_OPTIONS+=" --remote_download_outputs=all --host_force_python=PY3"
 
 bazel build ${BAZEL_BUILD_OPTIONS} --//tools/api_proto_plugin:default_type_db_target=@envoy_api_canonical//versioning:active_protos \
-  @envoy_api_canonical//versioning:active_protos --aspects //tools/protoxform:protoxform.bzl%protoxform_aspect --output_groups=proto \
-  --action_env=CPROFILE_ENABLED=1 --host_force_python=PY3
+  @envoy_api_canonical//versioning:active_protos --aspects //tools/protoxform:protoxform.bzl%protoxform_aspect --output_groups=proto
 
 TOOLS=$(dirname $(dirname $(realpath $0)))
 # to satisfy dependency on api_proto_plugin
```

With that I get no extra protobuf recompiles when I switch back and forth between docs and proto format. AFAICT the action_env is slightly different, but for whatever reason that is not causing a rebuild. I think the different host python versions was though and this fixes at all to use Python 3.

If this looks good can you add ^ to your PR and we can ship?

**Comment by mattklein123** [comment]
Although, I should note that when I then go back and compile prod code, it compiles protobuf there, because we set `--host_force_python=PY2` in .bazelrc. Can we potentially just make 3 the default?

**Comment by mattklein123** [comment]
Per offline convo I will take this over.

**Comment by meteorcloudy** [comment]
Oh, yes. Changing `--host_force_python=PY2` will indeed cause a rebuild, glad you figured that out! ;)

**Pull request closed without merging**
