### PR TITLE
router: minor cleanup

### PR DESCRIPTION
**Pull request by derekargueta**
Description:
1. `make_unique` should be preferred here
2. Use `explicit` for single-parameter constructors
3. Make applicable members of `CorsPolicyImpl` `const` and created via member initializer list
Risk Level: Low
Testing: Existing
Docs Changes: N/A
Release Notes: N/A

Signed-off-by: Derek Argueta <dereka@pinterest.com>

### CODE REVIEW

**Comment by derekargueta** [comment]
huh, the envoy-macos build succeeded but the Github check is stuck on "in progress"

https://dev.azure.com/cncf/envoy/_build/results?buildId=6649

**Comment by codesuki** [comment]
Agree with @dschaller, looks good. Thanks!

**Pull request merged**
