### PR TITLE
Remove docker prune after verify examples tests

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: Remove docker prune after verify examples tests
Additional Description: 

Prevents `docker system prune` after each test as it is not required

Risk Level: low
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue] Partial fix for #13084 
[Optional Deprecated:]

### CODE REVIEW

**Review by asraa — DISMISSED** [review]
Thanks! Change seems right to me. Based on the issue itself, maybe there needs to be a filter if you want to cleanup this particular one?

pass to senior maintainer @envoyproxy/senior-maintainers for merge

**Comment by phlax** [comment]
> Based on the issue itself, maybe there needs to be a filter

i dont think the pruning is necessary, so my feeling is its better to just remove it.

i think there is a more general point in the original issue about making it safer to run these tests - which download and build a lot of docker images. I think the resolution there is to document how to run the script and potentially how to wrap it so the images etc are cleaned up after

**Comment by phlax** [comment]
@asraa i just noticed that there is another place where it does `container prune` - perhaps that was what you meant.

ill add something for this now...

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
