### PR TITLE
[balsa] Process request trailers.

### PR DESCRIPTION
**Pull request by bencebeky**
Call framer_.set_balsa_trailer() not only for responses but also for
requests.  Support for this has been added to Balsa recently at
https://github.com/google/quiche/commit/4fddcf2647c4f9f5a397dc3d6d1bc790ca977a82

This change reduces the number of tests in http1:codec_impl_test failing
with BalsaParser from 22 to 18.

Signed-off-by: Bence Béky <bnc@google.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by bencebeky** [comment]
/assign @diannahu @birenroy

PTAL

**Review by diannahu — APPROVED** [review]
LGTM, nice!

**Pull request merged**
