### PR TITLE
matcher: fix bad type URL for response trailers

### PR DESCRIPTION
**Pull request by kyessenov**
Commit Message: Fix a typo in bad type URL for the response trailer matcher input. Matching on response trailers is rather weird, so that explains why we did not detect this earlier. To prevent accidents like this, add a release assert to dis-allow conflicting type names. Updated test filters whenever collision occurs.
Additional Description:
Risk Level: low
Testing: 
Docs Changes:
Release Notes:
Ref: https://github.com/envoyproxy/envoy/issues/20476

### CODE REVIEW

**Comment by mattklein123** [comment]
Can you add a test that would have broken?

/wait

**Comment by kyessenov** [comment]
Changed to RELEASE_ASSERT on double registration which would have caught it. I think since the new default is type lookup, we can start enforcing that.

**Comment by mattklein123** [comment]
Check CI?

/wait

**Comment by kyessenov** [comment]
Sorry, yes, I'm planning to address the test type URL collisions. Will post it when done.

**Review by mattklein123 — DISMISSED** [review]
Thanks!

**Comment by kyessenov** [comment]
/retest
(time-out)

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
