### PR TITLE
deps: update absl, googleapis, cel-cpp

### PR DESCRIPTION
**Pull request by kyessenov**
Commit Message: update absl, googleapis, cel-cpp
Risk Level: low

### CODE REVIEW

**Comment by phlax** [comment]
@kyessenov this adds 100s of lines of warnings to most of our builds

can we either fix this upstream before merging or patch out the warnings if they are not important

**Comment by kyessenov** [comment]
@phlax, yeah I can fix upstream. There's work to do here with various static asserts too.

**Comment by moderation** [comment]
Deps looks good and will check back when CI errors are fixed

**Comment by abeyad** [comment]
@kyessenov regarding the iOS/macOS failures, if I change the Abseil library to be the previous one, i.e.
```
version = "20230802.1",
sha256 = "987ce98f02eefbaf930d6e38ab16aa05737234d7afbab2d5c4ea7adbe50c28ed",
```

then it builds properly.  It seems like this version of the Abseil library has issues in its macOS/iOS target build?

**Comment by kyessenov** [comment]
@abeyad macOS build failure is distinct - it's something about alignment difference. I am not sure how iOS build error is triggered - is it using clang 14 or some strange compiler version?

**Comment by kyessenov** [comment]
Sigh, I don't have a Mac. And it's also quic code. Any way to proceed debugging besides Googling for some other reports of a build failure?

**Comment by yanavlasov** [comment]
I see two problems:
1. Link failure with undefined `_FLAGS_v` in `quic::QuicCryptoClientConfig::CachedState::Initialize` - IOS and Android are likely the same problem. My guess it is produced by `QUIC_DVLOG(1)` but, I'm unsure what needs to be logged to make it work. I'll ping the QUIC team to assist.
2. Alignment error in CEL for macOS build. Not sure about this one.

**Comment by phlax** [comment]
ci fails look real

/wait

**Comment by asedeno** [comment]
For the macOS failure: https://github.com/google/cel-cpp/issues/831

**Comment by asedeno** [comment]
The macOS build failure should be fixed by bumping CEL to https://github.com/google/cel-cpp/commit/aafa026e4c8c7177ef1364bbcee92992ba7fbb61.

**Comment by asedeno** [comment]
I'd like to decouple the absl update from the cel update, just to untangle the various build failures. Was `20240116.2` chosen over `20240722.0` for any particular reason? It was pretty new when this PR was opened.

**Comment by phlax** [comment]
@asedeno i tried updating absl on its own previously and iirc came to the conclusion that it would need a CEL update also - at least without patching

**Comment by asedeno** [comment]
@phlax, I'm a bit late to this party and also arriving to the same conclusion. I might poke at it some more just to satisfy my own curiosity.

**Pull request closed without merging**
