### PR TITLE
Windows compilation: expected_span_name is not captured by the lambda with MSVC

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Commit Message: Ensure expected_span_name is captured by lamda with MSVC
Additional Description: MSVC's lambda capture rules are more strict, it seems in this case this variable has to be explicitly captured or captured with the capture default
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
If it is more desirable to explicitly capture the variable, I can make that change, just used the capture default since it was less verbose and wouldn't cause future breakages

**Comment by mattklein123** [comment]
This line has changed back and forth several times. Can you work with @marcomagdy to figure out the path forward here? Also, until we run the tests in Windows CI I'm not sure it makes sense to keep fixing small things like this.

**Comment by sunjayBhatia** [comment]
@marcomagdy is the lambda change here a consequence of something that fixes coverage or potentially a merge conflict resolution issue: https://github.com/envoyproxy/envoy/commit/5dcfa7b44999f8493a343796ba9dc7194c9f05c4#diff-4d36e44b2a9f6b2cde56e3832154d528

**Comment by mattklein123** [comment]
Please merge master to fix CI.

/wait

**Comment by sunjayBhatia** [comment]
@mattklein123 regarding your point about CI: agreed, these small fixes seem to be occurring less and less often while we work to get CI going with larger workers/RBE etc. but we can batch them up more while we're working to get tests passing, it was not a great time catching up when we had a huge batch of compilation issues to sort out so we've just been trying to avoid that again

**Pull request merged**
