### PR TITLE
ci: Remove docker (by default) and capabilities from build container

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
currently the build container is completely insecure - the non-root user inside the container can trivially use docker to get root on the host - which means that all of the scripts etc that it runs can also do the same

(for ref - inside the container ...)

```console
$ docker run -it --rm -v /:/tmp/hostroot debian:bullseye-slim
```


im not clear at all why docker was added into the build container (https://github.com/envoyproxy/envoy/commit/bbae4a7366a12df61afc37fd4465e7b557244ffb)

i dont see it used anywhere (apart from possibly in the distrib verification)  - so i think at very least we should make this configurable if not remove altogether

iirc you can get root on a host with just netcap so we might want to look at the other capabilities also

**Comment by phlax** [comment]
cc @mattklein123 @htuch afaict the capabilities were added for `tcpdump` for an asan test that has been disabled for a long time

**Comment by phlax** [comment]
ptrace can be used to root the host i think https://blog.pentesteracademy.com/privilege-escalation-by-abusing-sys-ptrace-linux-capability-f6e6ad2a59cc

**Comment by phlax** [comment]
i wasnt able to completely remove the docker config as it is required by the arm package verification job

the reason for needing it is kinda arbitrary - it needs a compiler for some of the python deps

i tried using the arm-large image but that also lacks a compiler, so even after installing bazel it didnt work 

if we added bazel and build-essential into an arm self-hosted image we could remove this altogether

**Comment by phlax** [comment]
cc @lizan

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
