### PR TITLE
[backport/v1.23] tools, github: Add error handling and update README

### PR DESCRIPTION
**Pull request by dio**
Commit Message: This makes sure we are not rate-limited when calling GitHub API 

Cherry-picked from:

- ceb45a32da8c9886c0eb87f8723068b6cd96c5f8
- 36fc1ccc1de30b79594ca5ef9d8f0799a0f399a0
- 3ea63d73407f5af8992e20e1bf0fb4b481b71d13

Risk Level: Low
Testing: Manual
Docs Changes: N/A
Release Notes: N/A
Platform-Specific Features: N/A

### CODE REVIEW

**Comment by phlax** [comment]
most likely we will need to backport the same fix/es to this branch also

**Comment by dio** [comment]
Gotcha. Will do.

**Comment by dio** [comment]
waiting for: https://github.com/envoyproxy/envoy/pull/23837

**Review by phlax — APPROVED** [review]
lgtm, thanks @dio

**Pull request merged**
