### PR TITLE
[backport/1.26] tls: fix handshake failure when both private key provider and cert validation are set

### PR DESCRIPTION
**Pull request by zhxie**
Signed-off-by: Xie Zhihao <zhihao.xie@intel.com>

Commit Message: tls: fix handshake failure when both private key provider and cert validation are set
Additional Description: See #29002
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Comment by phlax** [comment]
@zhxie the coverage fail looks like it could be real:

```console
Code coverage for source/common/quic is lower than limit of 93.4 (93.3)
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=147062&view=logs&j=4930ecaf-18f4-5b3c-dea3-309729c3b3ae&t=ab5bd5c9-001f-56ff-77c8-09b6370b2489&l=4768

if you want to update the commit to adjust the coverage please do - rather keep a single commit tho - so you will need to force push

**Comment by phlax** [comment]
the clang-tidy fail looks like it could also be real - but is less of a concern

**Comment by zhxie** [comment]
Not know why the QUIC coverage and clang-tidy fails, I will retest first.
/retest

**Review by phlax — APPROVED** [review]
lgtm, thanks @zhxie

**Pull request merged**
