### PR TITLE
[TESTING] repokitteh - please ignore

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by phlax** [comment]
@itayd i followed through the tutorial and get the general gist of how repokitteh works

im not unfortunately blessed to test  this PR - so im not sure i can test things further

i guess in terms of the tickets i opened, the questions i have are:

- is there an event emitted when  a circleci job has successfully completed (like building docs) ?
- can we emit a custom event in a (circleci) job - eg when docs have changed/been rebuilt ?

**Comment by phlax** [comment]
@mattklein123 (or others) could you "bless" this PR (`/rk-bless`) so i can use it for testing the bot

**Comment by ggreenway** [comment]
Looks like I don't have permission

**Comment by phlax** [comment]
blaa /woof blaa

**Comment by phlax** [comment]
woof

**Comment by phlax** [comment]
&sol;woof

**Comment by phlax** [comment]
&#47;woof

**Comment by phlax** [comment]
bark: \n /woof

**Pull request closed without merging**
