### PR TITLE
test: replace mock_methodn macros with mock_method

### PR DESCRIPTION
**Pull request by akonradi**
Commit Message: Replace MOCK_METHODn with MOCK_METHOD
Additional Description:
This is a continuation of #13186, but with an additional format check to prevent
additions of MOCK_METHODn invocations in the future.
Risk Level: low
Testing: built affected targets
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: none

### CODE REVIEW

**Review by alyssawilk — APPROVED** [review]
nice!

**Comment by akonradi** [comment]
@alyssawilk can you merge?

**Comment by alyssawilk** [comment]
yeah, sorry, CI wasn't done when you got your LGTM :-)

**Comment by akonradi** [comment]
I figured, just wanted to knock this one off before the long weekend. Thanks!

**Pull request merged**
