### PR TITLE
[bp/1.29] deps: Bump com_github_nghttp2_nghttp2 -> 1.60.0 (#33002)

### PR DESCRIPTION
**Pull request by birenroy**
* deps: Bump com_github_nghttp2_nghttp2 -> 1.60.0

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Review by RyanTheOptimist — DISMISSED** [review]

**Comment by birenroy** [comment]
Well, I'm going to need some help figuring out what is going on with `//test/extensions/http/cache/file_system_http_cache:file_system_http_cache_test`. Does that test name ring any bells?

**Comment by birenroy** [comment]
/retest

Let's see if the flakes can be pacified.

**Comment by phlax** [comment]
i suspect that there is some infra change that is causing this - ive raised on appropriate channel

im guessing this wont be able to pass on this branch without a lot of luck (ie getting workers that work) and caching the results

**Comment by phlax** [comment]
@birenroy im gonna push this through on the basis that the ci fails are unrelated

**Comment by birenroy** [comment]
> @birenroy im gonna push this through on the basis that the ci fails are unrelated

Thanks! I have an idea for fixing `//test/extensions/http/cache/file_system_http_cache:file_system_http_cache_test` that I'll try in a separate PR.

**Pull request merged**
