### PR TITLE
dependencies: patch policy.

### PR DESCRIPTION
**Pull request by htuch**
Clarify the conditions under which patches may be used on external deps.

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

**Comment by htuch** [comment]
CC @wrowe

**Review by mattklein123 — APPROVED** [review]
Nice, thanks.

**Comment by moderation** [comment]
LGTM

**Comment by wrowe** [comment]
We will have a lengthy discussion about the chromium msvc-cl deliberate breakage on it's own thread, per the new policy. Well summarized, thanks @htuch

**Pull request merged**
