### PR TITLE
api: Removed duplicate links.

### LINKED ISSUE #15191: Remove duplicated links to extensions/categories
### Description

Now that we have automated linking between categories/extensions we need to remove the duplicated hard-coded existing links

### PR DESCRIPTION
**Pull request by mk46**
Signed-off-by: Manish Kumar <manish.kumar1@india.nec.com>

Commit Message: Removed duplicate links from extensions/categories. 
Additional Description: Removed duplicate links from extensions/categories. 
Risk Level: 
Testing: Format
Docs Changes:
Release Notes:
Platform Specific Features:
Fixes #15191

### CODE REVIEW

**Comment by mk46** [comment]
@phlax

**Comment by phlax** [comment]
redirect to current docs build 

https://storage.googleapis.com/envoy-pr/15307/docs/index.html

**Comment by phlax** [comment]
so im looking at the docs overall and wondering how we can make it a bit clearer - i think if you didnt understand the typed_config etc already it would be quite confusing

heres a screenshot of how it looks to me now:

access_log-typed_config

**Comment by phlax** [comment]
worth mentioning - the next part of the plan is to add some example configs into the tip box - so we should probably bear that in mind as we update...

**Comment by phlax** [comment]
for the `name` im thinking maybe change the text to something like:

```
The name of the access log extension to instantiate.

The name must match one of the compiled in loggers.

See the :ref:`extensions listed in typed_config below <extension_category_envoy.access_loggers>` for the default list of available loggers.
```

**Comment by mk46** [comment]
I think we need to also remove the list  typed_config because already in the tip box. WDYT?

**Comment by phlax** [comment]
yep, for sure was just typing that and trying to think of alternative...

**Comment by phlax** [comment]
perhaps, something like

```
Custom configuration that must be set according to the access logger extensions being instantiated
```

**Comment by phlax** [comment]
one thing im noticing is that the links to the extensions link to the link back rather than the extension itself (hope this makes sense!)

wondering how we can improve that

**Comment by phlax** [comment]
@mk46 main is failing atm - once #15310 has landed merging main should fix tests

**Comment by htuch** [comment]
Thanks @mk46. I agree with @phlax that we should make sure that the docs read cleanly, probably just some lightweight rewording can be done so that they make sense in conjunction with the new extension linkages.

@phlax can you let me know when this looks good to you?

**Review by phlax — APPROVED** [review]
@mk46 thanks for this

i think there is quite a bit of further work to do with the docs <> extensions etc

i created a pr to generate docs and check through here:

https://storage.googleapis.com/envoy-pr/75068a5/docs/search.html?q=EXTENSION_CATEGORY_TRACER&check_keywords=yes&area=default

but in terms of the scope of this PR all of the duplicate category information is cleared up, so lgtm

**Comment by phlax** [comment]
@htuch lgtm

**Review by mattklein123 — APPROVED** [review]
Nice!

**Pull request merged**
