### PR TITLE
cel: update runtime

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

Description: update CEL runtime. Improves activation interface, fixes string_view from null violation, includes a new (and not used here) parser.
Risk Level: low
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by kyessenov** [comment]
It looks like gcc build does not have `-std=c++14` set. Any clue how to add that @lizan ?

**Comment by lizan** [comment]
@kyessenov Seems it is missing from cel-cpp bazel rules, by default it is built with -std=c++0x. I'll probably change that with toolchain config for c++17 though.

**Comment by kyessenov** [comment]
Set copts in BUILD rules upstream.

**Pull request merged**
