### PR TITLE
remove invalid corpus that contains use_tcp_for_dns_lookup in bootstrap proto

### PR DESCRIPTION
**Pull request by chaoqin-li1123**
Signed-off-by: chaoqin-li1123 <chaoqinli@google.com>

Commit Message: #16237 deprecate the use_tcp_for_dns_lookup field in bootstrap.proto, which makes these corpus invalid.
Additional Description:N/A
Risk Level:low
Testing:remove fuzz corpus
Docs Changes:N/A
Release Notes:N/A
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by ggreenway** [comment]
@asraa can you take this? I'm unsure whether we should modify these to exclude that option now, make them use the replacement option, or delete entirely.

**Review by asraa — COMMENTED** [review]
Hmmm what stops the fuzzer from crashing on this input again?

Does the fuzzer crash on this input? Does it throw a deprecation error that isn't caught (that it should be catching)?

**Comment by chaoqin-li1123** [comment]
> Hmmm what stops the fuzzer from crashing on this input again?
> 
> Does the fuzzer crash on this input? Does it throw a deprecation error that isn't caught (that it should be catching)?

We still have support for this deprecated field in the code base, so it won't crash on the input.

**Comment by lizan** [comment]
@asraa ?

**Comment by asraa** [comment]
So is this just a cleanup removing deprecated fields from testcases? Why not just remove the field instead of the corpus entry?

**Comment by chaoqin-li1123** [comment]
> So is this just a cleanup removing deprecated fields from testcases? Why not just remove the field instead of the corpus entry?

yeah, we can remove only the deprecated field.

**Pull request closed without merging**
