### PR TITLE
backport to 1.15: http: fix datadog and squash handling of responses without body (#13328)

### PR DESCRIPTION
**Pull request by cpakulski**
Commit Message: Fixing bugs in datadog and sqaush where unexpected bodyless responses would crash Envoy
Risk Level: low
Testing: new unit tests
Docs Changes: n/a
Release Notes: inline

### CODE REVIEW

**Comment by cpakulski** [comment]
I renewed expired certificates as part of this PR. If you think it should be split into 2 separate PRs, I can close this one and create 2 PRs: one to renew certs and one for backport. Otherwise it is ready for review and merge.

**Review by jmarantz — APPROVED** [review]
Thanks for doing this.

I think I'll let a @envoyproxy/senior-maintainers merge as though this is just the backport I'm not sure exactly what the plan is for how these backports are to be done, and in particular the issue of renewing test certs.

**Review by alyssawilk — APPROVED** [review]
I think it'd be mildly cleaner to land separately but as it's test certs it's more of a nice to have than needed.  Let's land it to unblock the other backport PRs

**Pull request merged**
