### PR TITLE
Add // IWYU: export to log_level.h

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
Add // IWYU: export to log_level.h in order to fix a clang-tidy error which shows up internally.

Signed-off-by: Ryan Hamilton <rch@google.com>

### CODE REVIEW

**Review by abeyad — APPROVED** [review]

**Comment by jpsim** [comment]
Is this a false positive in clang-tidy? Is the header actually used?

**Comment by RyanTheOptimist** [comment]
> Is this a false positive in clang-tidy? Is the header actually used?

Ah. So clang-tidy complains in some code we have internally which includes log_level.h and then attempts to use LogLevel which is defined on line 10. I think it's a legit warning. Or alternatively, we could get rid of that "using" and instead just use the enum from source/common/common/base_logger.h directly (and have callers include that file).

WDYT?

**Comment by mjbshaw** [comment]
Yeah, clang-tidy sees that `mobile/library/cc/log_level.h` exports the type `LogLevel`, so if that's all I use then there are no complaints. But the enum constants are not defined in that header, so if I do something like `LogLevel::off` then clang-tidy will complain that I'm not including `#include "source/common/common/base_logger.h"`.

**Comment by jpsim** [comment]
> WDYT?

Fine with me, I was just trying to understand a bit better. Thanks for explaining!

**Pull request merged**
