### PR TITLE
clean up: save one comparison of thrift compact protocol

### PR DESCRIPTION
**Pull request by JuniorHsu**
Commit Message:
minor 
Additional Description:
Risk Level: low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by zuercher — APPROVED** [review]

**Comment by JuniorHsu** [comment]
ci is finally happy after 4 retest and 3 merge main 😿

**Review by zuercher — APPROVED** [review]

**Pull request merged**
