### PR TITLE
redis: add stat for  exists redis health check failure

### PR DESCRIPTION
**Pull request by ramaraochavali**
~~Currently the redis health check failure based on EXISTS, treats the failure as "ACTIVE". However this is equivalent to `x-envoy-immediate-health-check-fail` for Http. This PR implements that change. This is needed to distinguish stats based this failure vs. network failure.~~

Commit Message: add stat for exists redis health check failure
Risk Level: Low
Testing: Updated
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by ramaraochavali** [comment]
If this change, makes sense - I will update docs + release notes.

**Comment by mattklein123** [comment]
> Is n't this same as marking a node unhealhy by calling /healthcheck/fail?

Yes.

Sorry I'm still a little confused. Can you provide more context on the problem and what you are trying to achieve? Thank you.

/wait-any

**Comment by ramaraochavali** [comment]
> Sorry I'm still a little confused. Can you provide more context on the problem and what you are trying to achieve? Thank you.

I am trying to distinguish between active health check failures caused by network failures vs. caused by server setting a specific key. So we mark this as 'PASSIVE' and get `health_check.passive_failure` is incremented. 

It is not a big deal. If you think it is confusing, I can close this.

**Comment by mattklein123** [comment]
In general, PASSIVE is associated with outlier detection, and ACTIVE is associated with the active health checker. I think it's going to be pretty confusing to swap them. Would adding additional configuration or functionality to the redis health checker help solve whatever issue you are facing?

**Comment by ramaraochavali** [comment]
> Would adding additional configuration or functionality to the redis health checker help solve whatever issue you are facing?

May be. Let me think about that and come back with the proposal. For now, I will close this.

**Comment by ramaraochavali** [comment]
@mattklein123 WDYT about adding another stat `health_check.non_retriable_failures` to indicate that health check failed because it is a non retriable error (EXISTS check in this case)?

**Comment by mattklein123** [comment]
Would this have some parallel in the other health checkers or is it redis specific? Mainly wondering if the stat should just be dedicated to the redis health checker.

**Comment by ramaraochavali** [comment]
I think it could be generic but there are no use case around it now. We can make it redis specific though

**Comment by ramaraochavali** [comment]
And If we make it redis specific, I think we can be direct in the stat naming `health_check.redis.exists_failures` - that may be less confusing?

**Comment by mattklein123** [comment]
Sure sg

**Comment by ramaraochavali** [comment]
@mattklein123 added the stat. PTAL

**Review by mattklein123 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
