### PR TITLE
match_delegate: move to extensions

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: low: still linked to binary
Testing: n/a
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by wbpcode** [comment]
finally, happy to see this moving. 😄

**Comment by tyxia** [comment]
@yanjunxiang-google is adding some features to this filter https://github.com/envoyproxy/envoy/pull/33013 (which is close to mergeable state). Thus we probably need to sync up to figure out a plan to avoid the conflicts.

Also. I am happy to be the code owner from Google side, as i have designed/reviewed PR https://github.com/envoyproxy/envoy/pull/27088 and contributed some other PRs(#26735, #27621)

**Comment by yanjunxiang-google** [comment]
> Thanks for working on this (long awaited movement)!
> 
> @yanjunxiang-google is adding some features to this filter #33013. Thus we probably want to sync up to figure out a plan to avoid the conflicts.
> 
> Also. I am happy to be the code owner from Google side, as i have designed/reviewed PR #27088 and contributed some other PRs(#26735, #27621)

Good point!  

If this refactoring is not super urgent, can we hold it off until #33013 merged?

**Comment by wbpcode** [comment]
This PR seems good to me. should I pending it until #33013 is merged?

**Comment by alyssawilk** [comment]
merging with @yanjunxiang-google offline OK

**Review by wbpcode — APPROVED** [review]

**Pull request merged**
