### PR TITLE
network: declare factory for default client connection factory

### PR DESCRIPTION
**Pull request by snowp**
The change to use a default factory broke Envoy Mobile as the static init pattern doesn't work unless the TU is considered actively used. This adds the factory declaration to the header, allowing EM to call the forceRegister* function to ensure that this class is registered.

Risk Level: Low
Testing: n/a
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Review by lambdai — APPROVED** [review]
LGTM. Sorry for introducing this.

**Comment by zuercher** [comment]
@snowp does this need a master merge to fix tests?

**Pull request closed without merging**
