### PR TITLE
mobile: testing drain on reresolve

### PR DESCRIPTION
**Pull request by alyssawilk**
"unfortunately" I think this is WAI :-/

### CODE REVIEW

**Comment by abeyad** [comment]
/assign @RyanTheOptimist 

for Envoy maintainer review of test_resolver.h

**Comment by abeyad** [comment]
@alyssawilk just curious, what do you mean by this comment:

> "unfortunately" I think this is WAI :-/

Or is it just that the test shows that the re-resolve on drain works properly, so it's a dead-end in terms of our investigation of DNS errors?

**Comment by alyssawilk** [comment]
yeah I was hoping to find something buggy =P

**Comment by alyssawilk** [comment]
Also diligence appreciated but I'm going to claim your review of pure test code shutdown cleanup is Ok :-)

**Pull request merged**
