### PR TITLE
Removes usage of deprecated http2_protocol_options from Cluster in configs

### PR DESCRIPTION
**Pull request by davinci26**
Signed-off-by: Sotiris Nanopoulos <sonanopo@microsoft.com>

Commit Message:

Removes usage of deprecated http2_protocol_options from Cluster in configs. See #15559

Additional Description:

This patches the underlying issue that these configs should have caused tests to fail. This PR does not address this.
Required for https://github.com/envoyproxy/envoy/pull/15461

Risk Level: Low (test only)
Testing: Tests
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by davinci26** [comment]
@phlax @alyssawilk @mattklein123 all of you are involved in the issue discussion so you might want to also do the review.

**Important:** this does not fix the underlying issue, the tests should have been failing when we use a deprecated property but this PR does not fix it.

**Comment by phlax** [comment]
hi @davinci26 this pr raises a few issues

firstly the example configs. I did a quick check and i think in most case we can just use `HTTP/1.1` for the examples. I think this is preferable as the config to switch is complicated and mostly the examples want to just focus on what is exemplary.

im guessing some time in the future `http2` will become the default and we wont need to set this at all to use `HTTP/2.0`

the other issue is not addressed in (or caused by) this PR - but it does raise the issue.

replacing `http2_protocol_options` with 

```
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
```
doesnt seem very user-friendly to me. 

Especially as with this config the user is not actually setting any http2 options - they are switching http protocol. Despite the word `options` appearing in the config 4 times, the options are actually `{}`

**Comment by phlax** [comment]
the other issue is docs - reading the http2_protocol_option here:

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto.html

its not clear/obvous that this has been deprecated, or how to upgrade

**Comment by davinci26** [comment]
> firstly the example configs. I did a quick check and i think in most case we can just use HTTP/1.1 for the examples. I think this is preferable as the config to switch is complicated and mostly the examples want to just focus on what is exemplary.

I see what you are saying. No strong opinion here. I just wanted my change to not affect the behavior. Also from a quick search in the repository, I see that there are many configs that already use the new verbose way of setting it.

> replacing http2_protocol_options with <yaml blob> doesnt seem very user-friendly to me.

I can see your argument but I am not well versed here to have an opinion. Would an issue be better to discuss this?


> the other issue is docs - reading the http2_protocol_option here: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto.html its not clear/obvous that this has been deprecated, or how to upgrade

The link in there is broken. We should patch this (I can do this in a separate PR)

**Comment by phlax** [comment]
> Also from a quick search in the repository, I see that there are many configs that already use the new verbose way of setting it.

in terms of reverting to http1, i think im mostly concerned about the configs in the examples/sandboxes - just because they should be kept as simple as possible

> The link in there is broken, that makes it really confusing. We should patch this (I can do this in a separate PR)

yep. i think we also need a really standout way of flagging deprecation and perhaps new/old ways of doing things - beyond the scope of this PR tho, so sorry for hijacking it 8/

**Review by mattklein123 — APPROVED** [review]
Let's merge this to unblock @davinci26. I agree with @phlax that we can improve the documentation and simplify things, and I also agree that this new config is not very user friendly, but so it goes.

In terms of fixing the underlying reason it wasn't caught previously, we should have a way of not allowing parsing as v2 at all, but I'm not sure it's worth investing in that as we are about to delete v2 anyway.

So, let's merge and figure out doc improvements separately.

**Pull request merged**
