### PR TITLE
runtime: removing singleton access from validator

### PR DESCRIPTION
**Pull request by alyssawilk**
This does make the deprecation stats have the same problem as the WIP stats, which is that using getStrictValidationVisitor doesn't update deprecation stats.   I could do the same trick in source as I did in test and cast-and-set if we have concerns about that.

Risk Level: low
Testing: existing tests
Docs Changes: n/a
Release Notes: n/a
Part of https://github.com/envoyproxy/envoy/issues/19847

### CODE REVIEW

**Review by daixiang0 — APPROVED** [review]

**Comment by alyssawilk** [comment]
huh, the failing test seems unrelated.  I'll try a main merge in case something else changed.

**Review by KBaichoo — APPROVED** [review]
lgtm, thanks!

**Review by mattklein123 — APPROVED** [review]
Thanks this makes sense to me. Happy to merge this as I will have to merge this into https://github.com/envoyproxy/envoy/pull/20111. Thank you for slogging through this!

**Pull request merged**
