### PR TITLE
http local_ratelimit filter: added custom response body

### PR DESCRIPTION
**Pull request by zengyuxing007**
Commit Message:
    Http local_ratelimit filter add custom response body
Additional Description:
     xRef: #21513

Risk Level: low
Testing: unit , integration.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by mattklein123** [comment]
Can't you use https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/custom_response_filter? 

/wait

**Comment by zengyuxing007** [comment]
> Can't you use https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/custom_response_filter?
> 
> /wait

Thanks for your reply.

I know custom_response_filter, but maybe other users don't. Considering the complexity of using the user side, I think it would be better if we could solve this problem within the local_ratelimit filter itself, we can see that http.local_ratelimiter (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/local_rate_limit_filter)  already has a custom response header under the current definition, this "custom return body" just makes the existing interface definition look more complete, and is obviously a very small change.

**Comment by mattklein123** [comment]
I don't think it makes sense to add duplicate functionality like this when the custom rely filter is more robust. I'm going to go ahead and close this PR. Feel free to open a documentation PR to guide readers to the custom reply filter, thanks.

**Comment by zengyuxing007** [comment]
> I don't think it makes sense to add duplicate functionality like this when the custom rely filter is more robust. I'm going to go ahead and close this PR. Feel free to open a documentation PR to guide readers to the custom reply filter, thanks.

@mattklein123 

For users who use local_ratelimit (and require a custom return body), using custom_response_filter requires more ，and more complicated configuration, which may be too cumbersome for them.

**Comment by jdomag** [comment]
> I don't think it makes sense to add duplicate functionality like this when the custom rely filter is more robust. I'm going to go ahead and close this PR. Feel free to open a documentation PR to guide readers to the custom reply filter, thanks.

I'm totally with @zengyuxing007 on this one. Since there is an option to set response code and custom headers directly in the rate limit, why not to add custom response body to it as well? 
I've spent hours of digging how to use custom_response_filter on responses coming from rate limit service and I was not able to configure it properly.

**Comment by phpzxh** [comment]
I agree with you. 

> > I don't think it makes sense to add duplicate functionality like this when the custom rely filter is more robust. I'm going to go ahead and close this PR. Feel free to open a documentation PR to guide readers to the custom reply filter, thanks.
> 
> I'm totally with @zengyuxing007 on this one. Since there is an option to set response code and custom headers directly in the rate limit, why not to add custom response body to it as well? I've spent hours of digging how to use custom_response_filter on responses coming from rate limit service and I was not able to configure it properly.

**Pull request closed without merging**
