### PR TITLE
mobile: Remove unused extension function

### PR DESCRIPTION
**Pull request by fredyw**
`EngineBuilder.enableHttp3` extension function shadows `EngineBuilder.enableHttp3(Boolean)`, which means it will never be used due to the way extension functions work and it also does the same thing as `EngineBuilder.enableHttp3(Boolean)`.

The warning:
```
library/kotlin/io/envoyproxy/envoymobile/EngineBuilderHTTP3Util.kt:13:21:
warning: extension is shadowed by a member: public final fun enableHttp3(enableHttp3: Boolean): EngineBuilder
fun EngineBuilder.enableHttp3(doEnableHttp3: Boolean): EngineBuilder {
```

Risk Level: low (code clean up)
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: mobile

### CODE REVIEW

**Comment by phlax** [comment]
> The warning:

fyi, this was fixed in #30216 

no objections to this pr tho

i have a suspicion that this pr will actually create said warning as i think the class this was overriding has the same issue (not sure)

**Comment by fredyw** [comment]
> > The warning:
> 
> fyi, this was fixed in #30216
> 
> no objections to this pr tho
> 
> i have a suspicion that this pr will actually create said warning as i think the class this was overriding has the same issue (not sure)

I don't think that PR fixed it. If you read the warning in the PR description, it's still complaining about the same thing. In Kotlin, extension functions are resolved statically, which means the non-extension function `EngineBuilder.enableHttp3` will win against the extension function `EngineBuilder.enableHttp3`.  See [this](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS44LjIxIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiY2xhc3MgRm9vIHtcbiAgICBmdW4gZG9Gb28oYTogSW50KSA9IHByaW50bG4oXCJGb29cIilcbn1cblxuZnVuIEZvby5kb0ZvbyhiOiBJbnQpID0gcHJpbnRsbihcIkZvbyBleHRlbnNpb25cIilcblxuZnVuIG1haW4oKSB7XG5cdEZvbygpLmRvRm9vKDEwMClcbn0ifQ==) as an example.

**Review by abeyad — APPROVED** [review]
nice find!  so does this mean enableHttp3 on EngineBuilder didn't work, and the only reason HTTP/3 was used is b/c it's `true` by default?

**Comment by fredyw** [comment]
> nice find! so does this mean enableHttp3 on EngineBuilder didn't work, and the only reason HTTP/3 was used is b/c it's `true` by default?

It worked, but it will always the one defined in https://github.com/envoyproxy/envoy/blob/1b0b3e2c2b15d7e34e034f6ac41f278d2c866ab0/mobile/library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt#L357-L366 (the non-extension function).

**Comment by phlax** [comment]
> I don't think that PR fixed it. 

you are right  - apologies for noise

**Comment by fredyw** [comment]
> > I don't think that PR fixed it.
> 
> you are right - apologies for noise

no worries :)

**Pull request merged**
