### PR TITLE
deps: integrate and use local copy of http-parser library

### LINKED ISSUE #19749: uhv: move http-parser to envoy
Envoy will need to use a modified version of http-parser as part of the unified header validation component. The first step would be to bring in http-parser into Envoy. Then, as part of a separate issue, http-parser will be modified to add a configuration setting that skip header validation.

Right now,  [http-parser](https://github.com/envoyproxy/envoy-setec/blob/main/bazel/external/http-parser.BUILD) is built as an [external library](https://github.com/envoyproxy/envoy/blob/bbcd487bd178ef5254545941ac369d944da41913/bazel/repositories.bzl).

### PR DESCRIPTION
**Pull request by ameily**
**Commit Message:** deps: integrate and use local copy of http-parser library

**Additional Description:** As part of the unified header validation component, Envoy will need to eventually modify the http-parser behavior based on the active configuration (see #19750  and #19757). This PR covers the first step of that goal by bringing http-parser into the Envoy repository and get it building with Bazel. This PR contains the http-parser code, without any modifications, from the commit nodejs/http-parser@4f15b7d510dc7c6361a26a7c6d2f7c3a17f8d878.

**Risk Level:** Low

**Testing:** Build Envoy and run the HTTP protocol integration tests.

**Docs Changes:** None

**Release Notes:** None

**Platform Specific Features:** None

Fixes #19749

### CODE REVIEW

**Comment by ameily** [comment]
For context, we are supporting the unified header validation component and have been coordinating our work with @yanavlasov

**Comment by phlax** [comment]
just from pov of cve noise from nodejs this would be good

@ameily you need to do some format fixing - diff is available in the artefacts here https://dev.azure.com/cncf/envoy/_build/results?buildId=100606&view=results

cc @htuch for approval on including this in Envoy code base

**Comment by ameily** [comment]
> you need to do some format fixing - diff is available in the artefacts here https://dev.azure.com/cncf/envoy/_build/results?buildId=100606&view=results

Sorry about that, I apparently didn't have my virtualenv setup properly so the test wasn't running locally. It should be fixed now.

**Comment by htuch** [comment]
I'm on the fence on this one. I think we decided not to fork http-parser and we're pursuing a strategy of moving to a QUICHE-based parser. @yanavlasov do you have an ETA for when we will have a replacement parser? I'd feel more comfortable if we could say "this is just for 4 months and then we will switch to default QUICHE.

**Comment by yanavlasov** [comment]
@htuch balsa integration into Envoy will not start until H2. We will need to make some changes to http-parser in the interim to move forward with the unified header validation. Hence this fork. This is temporary until http-parser can be ditched for balsa.

**Comment by htuch** [comment]
Ack, no objection then.

**Review by htuch — COMMENTED** [review]
/lgtm deps

**Comment by phlax** [comment]
@ameily looks like you have some remaining issues with clang-tidy:

https://dev.azure.com/cncf/envoy/_build/results?buildId=100614&view=logs&j=b7634614-24f3-5416-e791-4f3affaaed6c&t=21e6aa7d-f369-5abd-5e4e-e888cac18e9c&l=3859

**Comment by phlax** [comment]
> My initial assumption was that this is non-Envoy code that we know works within Envoy so don't change it.

yep, agreed

**Review by phlax — APPROVED** [review]
lgtm, thanks @ameily

**Pull request merged**
