### PR TITLE
Integration tests for local rate limit http filter

### PR DESCRIPTION
**Pull request by gokulnair**
Commit Message:
We currently do not have any integration tests for the local rate limit http filter.
This PR adds integration tests to it. 

Additional Description:
We added new functionality to the local rate limit filter in the form of connection specific rate limiting under PR #15843. Since this filter was lacking integration tests, it was decided to have a follow up task to address this gap.

Risk Level: Low

Testing:
Added integration tests.

Docs Changes:
Release Notes:

### CODE REVIEW

**Comment by gokulnair** [comment]
Integration tests for local rate limit http filter as follow up task of #15843 :-)
cc @antoniovicente @alyssawilk @rgs1

**Comment by yanavlasov** [comment]
Thanks for making this change. The tests look good. I'm unsure if it possible to add flake free tests with token refreshes using `BaseIntegrationTest::time_system_`

Maybe @jmarantz have any suggesting for that. Otherwise LGTM

**Comment by alyssawilk** [comment]
Drive by "_thank you_!" for the follow up tests  :-)

**Review by rgs1 — APPROVED** [review]
Thank you!

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
