### PR TITLE
backport 1.16: container: Only drop privs if user is root (#15115)

### PR DESCRIPTION
**Pull request by Shikugawa**
Signed-off-by: Ryan Northey <ryan@synca.io>
Signed-off-by: Shikugawa <rei@tetrate.io>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by phlax — APPROVED** [review]
lgtm

**Comment by phlax** [comment]
@Shikugawa afaict this hasnt been merged to the 1.16 branch yet - is that correct ?

**Comment by Shikugawa** [comment]
@lizan Could you approve this?

**Comment by phlax** [comment]
@dmitri-d it would be great if we can add this to the 1.16 branch as i think it was causing some users (openshift users iirc) some pain

@lizan any objections on backporting this ?

**Comment by dmitri-d** [comment]
> it would be great if we can add this to the 1.16 branch

@phlax: did you mean another branch? This PR is against 1.16...

**Comment by phlax** [comment]
> @phlax: did you mean another branch? This PR is against 1.16...

im thinking it would be helpful to backport it to 1.16 - not sure why it didnt land before

i think the original reporter had issue on 1.17, but i think this would be helpful more generally (see https://github.com/envoyproxy/envoy/issues/14141 for discussion)

**Pull request closed without merging**
