### PR TITLE
bazel: fix gcc 12+ warning

### PR DESCRIPTION
**Pull request by keith**
I'm not sure why just moving this into a cc file seems to be enough, but with this I can no longer reproduce the warning. If the warning does still appear in this case, we can add `--per_file_copt` to disable it in a single place, which isn't possible with a header which causes the warning to happen in each file it's included by.

Fixes: https://github.com/envoyproxy/envoy/issues/23783

### CODE REVIEW

**Comment by yanavlasov** [comment]
I do not think this will work. Compiler needs to have complete definition of the constructor to generate it at the point of template instantiation. The warning looks weird to be sure. It could be a problem in absl::InlinedVector or gcc bug.

I would try most recent version of absl to see if it fixes things with gcc.

**Comment by adisuissa** [comment]
Waiting on fixing CI and addressing a comment.
/wait

**Comment by keith** [comment]
It stills repros on absl@4ffaea74c1f5408e0757547a1ca0518ad43fa9f1 (current HEAD)

**Comment by keith** [comment]
yea pushed that option instead, we'll see

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
