### PR TITLE
network: log immediate connect error details rather than just the err…

### PR DESCRIPTION
**Pull request by daixiang0**
…or number

Signed-off-by: LL <loong.dai@intel.com>

Commit Message:
Additional Description: Since the log is shown when debug, it is safe enough.
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA] #20313
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by ggreenway — APPROVED** [review]
LGTM.

There are CI failures, but they're caused by flakes unrelated to this PR. Hopefully should be resolved today sometime, then you'll need to merge main.

**Comment by daixiang0** [comment]
> LGTM.
> 
> There are CI failures, but they're caused by flakes unrelated to this PR. Hopefully should be resolved today sometime, then you'll need to merge main.

Thanks for your review, I have rebased the main.

**Pull request merged**
