### PR TITLE
Add new field in the RateLimitRequest message

### PR DESCRIPTION
**Pull request by PeterL328**
Commit Message: Add is_reporting field in the RateLimitRequest message
Additional Description: Rate limit requests can optionally specify if the request should still increase the number of hits a request adds to the matched limit even when the request is over limit. If the value is not set in the message, this defaults to false and a request does not increase the matched limit when the request is over limit. This may be useful for scenarios where the client wants to provide an update the rate limit counter without being concerned about whether the request is over limit.
Risk Level: Low
Testing: N/A
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by yanavlasov** [comment]
How would Envoy use this new field? Can you create an Issue with the description of the problem you are trying top solve, please?

/wait-any

**Comment by PeterL328** [comment]
@yanavlasov Created an issue here https://github.com/envoyproxy/envoy/issues/29161

**Comment by phlax** [comment]
@yanavlasov i think this awaiting further review

/wait-any

**Comment by yanavlasov** [comment]
@PeterL328  I've asked some question on #29161 Will continue review after I understand the problem better.

**Comment by PeterL328** [comment]
Hi @yanavlasov,
I did some testing with the ratelimit sidecar and found that actually the current behavior of the sidecar is what we already want.

i.e if we configured 80 requestsPerUnit as configuration for one descriptor in ratelimit sidecar.

If we send a sequence of requests within the minute, 
Start with a request of 50 hits_addend, remaining goes down to 30
sending another request of 50 hits_addend, we get overlimit (but remaining actually goes down to 0)
sending another request of 30 hits_addend, we get overlimit

so I will close this issue. Sorry for confusion

**Pull request closed without merging**
