### PR TITLE
[1.21] backport #19971 SDS: reduce cost of secret update

### PR DESCRIPTION
**Pull request by lambdai**
Commit Message:
Backport #19971 
Signed-off-by: Yuchen Dai <silentdai@gmail.com>

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by ggreenway — APPROVED** [review]

**Comment by lambdai** [comment]
disabled the AllWorkersAreHandlingLoad on macos as it is flaky here and on main

**Comment by ggreenway** [comment]
Can you add that as a separate PR so we can track where all the cherry-picks are coming from?

**Comment by lambdai** [comment]
> Can you add that as a separate PR so we can track where all the cherry-picks are coming from?

The reason I add the patch is that the CI is failing consistently on the AllWorkersAreHandlingLoad test case.

I think we used to stack these flaky mitigation changes in a bug fix in the back port

**Comment by lambdai** [comment]
reverted the unrelated test case in https://github.com/envoyproxy/envoy/pull/20189/commits/cbce9059d2a8ffe8395b118402ca716f268dfafc

**Comment by lambdai** [comment]
Lucky! all tests pass including the flaky one

**Pull request merged**
