### PR TITLE
Update com_github_nlohmann_json: v3.10.5 (current: v3.10.4)

### LINKED ISSUE #19371: Newer release available `com_github_nlohmann_json`: v3.10.5 (current: v3.10.4)
Package Name: com_github_nlohmann_json
Current Version: v3.10.4@2021-10-16 12:49:30
Available Version: v3.10.5@2022-01-03 05:40:13
Upstream releases: https://github.com/nlohmann/json/releases

### PR DESCRIPTION
**Pull request by kfaseela**
Signed-off-by: Faseela K <faseela.k@est.tech>

Fixes #19371

### CODE REVIEW

**Comment by kfaseela** [comment]
cc @phlax

**Comment by kfaseela** [comment]
@phlax review this one?

**Comment by phlax** [comment]
@kfaseela i think all should be good but im gonna leave it for the assigned maintainer

**Comment by alyssawilk** [comment]
@wrowe ping!

**Review by alyssawilk — APPROVED** [review]

**Comment by alyssawilk** [comment]
@kfaseela you OK waiting on merge until late Wednesday?  Looks like a year's worth of changes so I'd be inclined to merge after we cut the release.

**Comment by kfaseela** [comment]
> @kfaseela you OK waiting on merge until late Wednesday? Looks like a year's worth of changes so I'd be inclined to merge after we cut the release.

Yes fine for me!

**Comment by moderation** [comment]
Hmm. I'm building on Google RBE, Raspberry Pi and MacOS M1 without issue

**Comment by RyanTheOptimist** [comment]
> Huh, my compiler is choking on this update. CI looks fine so arguably I should track down and fix why my env is pickier but generally when I've seen these errors the warning is fairly legit.

@adisuissa @danzh2010 @KBaichoo and I are all seeing the same errors. However after much investigation it definitely appears to be an issue with the local environment. The following .cc file fails to build with clang, but succeeds with gcc:

```
#include <unordered_map> // unordered_map 
#include <valarray> // valarray
int main(int argc, char** argv) { return 0; }
```

More investigation needed, but this PR is off the hook.

**Comment by adisuissa** [comment]
After debugging with @RyanTheOptimist and @KBaichoo (Thanks for the joint debug session!), we think the problem is due to a recent update to the `libstdc++-11-dev` in our machines to version 11.2.0-12.
It seems that the bug will be solved in the next update (more details [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000398)).

For now the workaround is to either build using RBE, or build locally using the `--config=clang --config=libc++` bazel flags.

**Pull request merged**
