### PR TITLE
http_11_proxy: Allow for configuration via endpoint metadata

### PR DESCRIPTION
**Pull request by tonya11en**
Previously the only way to configure the HTTP/1.1 proxy transport socket
was by adding information to the streamInfo metadata via an intermediate
filter. This patch adds the ability to configure proxy addresses using
endpoint or locality metadata.

The metadata key is `envoy.http11_proxy_transport_socket.proxy_address`.
Configuration can be set in the metadata associated with
`LocalityLbEndpoints`. The metadata associated with each individual
endpoint overrides this value and the original method of configuration
(filter state metadata) takes precedence above all. The format of the
value must be a valid `config::core::v3::Address`.

Risk Level: Low. Alpha feature.
Testing: Unit test.
Docs Changes: Done.
Release Notes: Done.

### CODE REVIEW

**Comment by tonya11en** [comment]
The TSAN failure is unrelated:
```
SUMMARY: ThreadSanitizer: signal-unsafe call inside of a signal /tmp/tmp.OZoeltcI3e/llvm-project-llvmorg-14.0.0/libcxxabi/src/stdlib_new_delete.cpp:30:17 in operator new(unsigned long)
==================
[2024-07-31 22:40:17.737][16][critical][backtrace] [./source/server/backtrace.h:119] #0: Envoy::SignalAction::sigHandler() [0x944982b]
[2024-07-31 22:40:17.836][16][critical][backtrace] [./source/server/backtrace.h:119] #1: __tsan::CallUserSignalHandler() [0x34ea182]
================================================================================
INFO: Elapsed time: 3636.203s, Critical Path: 1025.80s
INFO: 26425 processes: 9400 remote cache hit, 11601 internal, 1 local, 5423 remote.
//test/integration:quic_http_integration_test                            FAILED in 567.7s
```

**Comment by tonya11en** [comment]
Merging main to see if that QUIC test passes on the latest.

**Comment by mattklein123** [comment]
LGTM.

/retest

**Review by mattklein123 — DISMISSED** [review]

**Comment by tonya11en** [comment]
looks like the coverage failure is unrelated:
```
tar: de0d32bdab0c4acc8ebdbc9a6c7eceda_archive.tar: Cannot write: No space left on device
tar: Error is not recoverable: exiting now
ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session 28a8148b-9ad4-4ce1-b3c1-32111c9e8861
##[error]Process returned non-zero exit code: 2
Finishing: Cache (coverage)
```

/retest

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
