### PR TITLE
access_log_formatter: timezone fix

### PR DESCRIPTION
**Pull request by mrice32**
*Description*:
A little background - we noticed that [this expect case](https://github.com/envoyproxy/envoy/blob/master/test/common/access_log/access_log_formatter_test.cc#L365) fails when we run it internally.  This is because the test expects that a `time_t` passed into the `fromTime()` method will show up exactly in the format in place of a `%s`.  Because `gmtime_r` is used to convert to `struct tm`, but `strftime` uses `mktime` (which reverses the `localtime_r` conversion, not `gmtime_r`) to convert back to `time_t` in the case of a `%s`.  This causes us to see an 8 hour difference in the timestamps in this test when we run internally.  I think there are a few solutions here:

1.  Move to using `localtime_r` as is done in this PR.
2.  Modify the expectations of `fromTime()` to incorporate this behavior, and update the test to take the time zone into account.

I'm curious what others think, and I'm open to other suggestions as to how to fix this issue.

*Risk Level*: Low

### CODE REVIEW

**Comment by mattklein123** [comment]
I would need to refresh my memory on all these time conversion functions, but I think we need to be careful about switching to localtime_r since I think this is a behavior change for people that do not set their machines to GMT in production. In general I think we should be keeping gmtime_r and outputting GMT.

Beyond that I don't have a lot to offer here unless I dug in more so maybe some other people who are more immediately familiar can weigh in?

**Comment by mrice32** [comment]
@mattklein123, that makes sense.  Rather than modify the behavior (despite the fact that it seems a little strange IMO), I've just changed the test to account for differences in timezones.  PTAL.

**Comment by mattklein123** [comment]
@mrice32 I suspect you will find split opinions on whether force logging GMT vs. local time is the correct thing. I think it's perfectly reasonably to make that a config option if you think people want the other way. Please open an issue to track.

**Comment by mrice32** [comment]
Gotcha.  I'll open an issue.  However, the thing that confused me was converting one way using gmtime, but using the equivalent of localtime to convert back (as opposed to preferring one over the other).  But this may just be my misunderstanding of the objective of the formatter code or the c time conversion functions.

**Comment by mattklein123** [comment]
@mrice32 it's possible there is a bug in the use of time conversion code. I have to refresh my memory every time I look at it. So if you feel there might be a bug I would take a look.

**Comment by mrice32** [comment]
@mattklein123 I say let's go ahead and get this update to the test in, and I'll see if I can come up with a separate test to clearly demonstrate that something unintended is happening.

**Pull request merged**
