### PR TITLE
build/image: Update to `56f235b`

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by ravenblackx — APPROVED** [review]
Yes all those strings of noise are definitely the right strings of noise and I have personally verified each and every one of them.

**Comment by phlax** [comment]
> ...  I have personally verified each and every one of them...

so this pr pulls in the image we tested

if you pull the pr/commit and then rebuild vscode container it will let you test the proposition

**Comment by phlax** [comment]
@ravenblackx i had to bump the image again for an unrelated reason (also hadnt been done 100% correct first time)

**Comment by phlax** [comment]
added a tool to make this a bit easier #29648

**Review by ravenblackx — APPROVED** [review]
Yes, these strings of noise are definitely good and correct strings of noise that I have verified with my human eyes to be the intended strings of noise, by comparing them against literally nothing.

**Comment by phlax** [comment]
> ... intended strings ...

image name/sha taken from here https://hub.docker.com/layers/envoyproxy/envoy-build-ubuntu/56f235b141079013e64912d676fe7da981368402/images/sha256-490fd4a8e4f7ec119f6cef33b6930e170414a2deb18b37fa6598e6a8d6b8afe2?context=explore

docker shasums derived by running `buildx imagetools inspect`

**Pull request merged**
