### PR TITLE
Refactor out libevent dependency from `source/common/buffer`

### PR DESCRIPTION
**Pull request by gopkarthik**
Commit Message: Remove libevent dependency in `source/common/buffer`
Additional Description:
Risk Level: Low
Testing: Bazel build
Docs Changes: None
Release Notes:
Platform Specific Features: None
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by tyxia** [comment]
@gopkarthik  Please fix the format and any CI failures, the i can loop in the reviewers. Thanks!

**Review by jmarantz — APPROVED** [review]

**Comment by gopkarthik** [comment]
Thanks for the review! I'll fix the CI failures including formatting issues.

**Pull request closed without merging**
