### PR TITLE
deps: update cel-cpp

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

Commit Message: Update cel-cpp. The protobuf fix for CEL will be released with 3.14, and cel-cpp will be updated then.
Additional Description:
Risk Level: low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Comment by kyessenov** [comment]
FYI ld suddenly started complaining about duplicate statusor definitions:
```
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/third_party/statusor/_objs/statusor_lib/statusor.pic.o: multiple definition of 'absl::internal_statusor::Helper::HandleInvalidStatusCtorArg(absl::Status*)'
/usr/bin/ld.gold: bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/status/_objs/statusor/statusor.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/third_party/statusor/_objs/statusor_lib/statusor.pic.o: multiple definition of 'absl::internal_statusor::Helper::Crash(absl::Status const&)'
/usr/bin/ld.gold: bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/status/_objs/statusor/statusor.pic.o: previous definition here
```

I removed the forked version.

**Comment by lizan** [comment]
Can we split out the StatusOr removal into another PR?

**Comment by kyessenov** [comment]
@lizan Sure, https://github.com/envoyproxy/envoy/pull/13988/files

**Review by lizan — APPROVED** [review]

**Pull request merged**
