### PR TITLE
dependabot: Group updates

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @mmorel-35 

testing this in our staging repo and it doesnt help much at all - we really need to fix the tool so we can group across directories

**Comment by mmorel-35** [comment]
If dependabot doesn't fit maybe [renovate](https://github.com/renovatebot/renovate) will.
Have you considered this alternative ?

**Comment by phlax** [comment]
>  Have you considered this alternative ?

vaguely - in the context of looking for bazel dep update support - at the time it didnt look great so added envoy.dependency.checker instead to handle bazel and continued with dependabot

dependabot is not so bad other than the volume of updates

**Comment by phlax** [comment]
so re renovate im not opposed but if we go down that path i want to test it quite a bit and be clear advantages/tradeoffs

we have a staging repo that can be used for this - if you can ping me on envoy slack i can give you access and we could try it out

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
