### PR TITLE
examples: fix Env. variable

### PR DESCRIPTION
**Pull request by Mrchopa**
Commit Message: JAEGER environment variable name change
Additional Description: Fix example 'jaeger-tracing' that does not work due to the Jaeger environment variable name change.
Risk Level: Low
Testing: manual testing : run docker-compose
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by phlax** [comment]
hi @Mrchopa thanks for this

im wondering why its not picked up by tests if its not working atm. ill have a look more...

**Comment by phlax** [comment]
related https://github.com/jaegertracing/jaeger/blob/master/CHANGELOG.md

the version in which this changes is `1.22.0`

not sure which version `latest` is using the hash of current `jaegertracing/all-in-one` is

8b50927a1a75faf4962871d3af7b27440bfd8e7b631742217009c540c4fc5009

although i dont see which version that uses or any other images with the same hash

we will need this once the jaeger image gets updated

**Comment by phlax** [comment]
iiuc we will need to change this at some point so ive added #nostale

**Comment by daixiang0** [comment]
Check the latest codes, it has been corrected.

**Comment by daixiang0** [comment]
@Mrchopa  Thanks for your contribution! Since it is fixed, I will close this, feel free to discuss here and reopen if necessary.

**Pull request closed without merging**
