### PR TITLE
Remove feature flag upstream_allow_connect_with_2xx

### LINKED ISSUE #31984: envoy_reloadable_features_upstream_allow_connect_with_2xx deprecation
Your change #27974 (Allow connect with 2xx status codes) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.
cc @vikaschoudhary16

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
Commit Message: fixes #31984 
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by adisuissa — COMMENTED** [review]
Please add a release note.

**Review by soulxu — APPROVED** [review]
LGTM

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
