### PR TITLE
test: add assertion that onDestroy is always called on filters

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by kyessenov** [comment]
This shows that Envoy does not always call onDestroy. This can potentially lead to leaks in third-party (or Wasm) filters that hook into onDestroy.

**Comment by mattklein123** [comment]
That seems bad. cc @snowp @alyssawilk. Can we look at which places do not call it? I find it surprising there would be cases like this but we definitely need to fix them.

**Comment by kyessenov** [comment]
HttpConnectionManagerImplTest.100ContinueResponseWithEncoderFiltersProxyingDisabled fails, although I don't know is special about this particular test.

**Comment by mattklein123** [comment]
We should see if it's a test bug or not, but anyway thanks for adding this!

**Comment by alyssawilk** [comment]
Unfortunately HCM unit tests don't really reflect production, so I'd guess it's a test bug.  In production streams get torn down because they're reset, they finish with an end stream, or there's a disconnect.  In unit tests, they can be arbitrarily deleted because the ownership isn't from the underlying connection.  I cleaned up a ton of HCM tests here: https://github.com/envoyproxy/envoy/pull/12228/files to cl.  Looking at the test in question it doesn't get an end stream or get reset, so I think it's simply not prod-realistic and if you raiseEvent in the offending test(s) it'll be all good.

**Comment by kyessenov** [comment]
I patched all the unit tests to explicitly close the connection. Let's see if this is going to work out and not flake.

**Comment by kyessenov** [comment]
I think this is safe to merge now.

**Comment by snowp** [comment]
Merging for now, I'll file an issue to handle code duplication in the tests

**Pull request merged**
