### PR TITLE
router: add retry policy logging

### PR DESCRIPTION
**Pull request by snowp**
In order to aid debugging retry behavior, add a debug log line that
prints the retry policy used for a given URL.

*Risk Level*: Low, debug log line
*Testing*: n/a
*Docs Changes*: n/a
*Release Notes*: n/a

### CODE REVIEW

**Comment by ggreenway** [comment]
This has a test failure. I re-ran them once and hit the same failure again, but it's not obvious to me why it's failing.

**Comment by dnoe** [comment]
@snowp Does the CI test failure clear up after merging master?

**Comment by snowp** [comment]
Coverage test is still failing with master merged in. I'm gonna get a Linux VM set up so I can run the test locally

**Comment by snowp** [comment]
Running this locally the test failures seems to be issues binding to `0.0.0.0:0`, gonna try to rerun CI

**Comment by snowp** [comment]
I'm gonna close this out for now because debugging this is taking forever and I don't have the time to see this through.

**Pull request closed without merging**
