### PR TITLE
deps: bump `com_github_wasmtime` -> 1.0.0

### LINKED ISSUE #23193: Newer release available `com_github_wasmtime`: v1.0.0 (current: v0.39.1)
Package Name: com_github_wasmtime@0.39.1
Current Version: v0.39.1@2022-07-21
Available Version: v1.0.0@2022-09-20
Upstream releases: https://github.com/bytecodealliance/wasmtime/releases

### PR DESCRIPTION
**Pull request by RiverPhillips**
Commit Message: deps: bump `com_github_wasmtime` -> 1.0.0
Additional Description: Resolves #23193
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @kfaseela

**Comment by moderation** [comment]
/lgtm deps

This looks like it is passing without some of the normal adjacent dependency updates

**Review by mattklein123 — APPROVED** [review]

**Comment by phlax** [comment]
> This looks like it is passing without some of the normal adjacent dependency updates

not sure it that is cause for concern cc @PiotrSikora

**Comment by PiotrSikora** [comment]
Wasmtime (well, it's Bazel rules) is tracked and updated in [Proxy-Wasm C++ Host](https://github.com/proxy-wasm/proxy-wasm-cpp-host). The only thing updated in this PR are the C API files used in [bazel/external/wasmtime.BUILD](https://github.com/envoyproxy/envoy/blob/1edd65f80bd8ded5cb2c0ebeec818784ebd76bfb/bazel/external/wasmtime.BUILD), but `@proxy_wasm_cpp_host//bazel/cargo/wasmtime` dependency there still points at Wasmtime v0.39.1.

Tests passed, because the C API didn't change between v0.39.1 and v1.0.0, but this PR didn't update Wasmtime.

It might be worth documenting this somewhere in `bazel/repository_locations.bzl`. cc @mpwarres

**Comment by kfaseela** [comment]
@RiverPhillips Will you be interested in pushing the corresponding PR in [Proxy-Wasm C++ Host](https://github.com/proxy-wasm/proxy-wasm-cpp-host) ? Some info on how to do the update can be seen at https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/194#issuecomment-937968294

**Pull request merged**
