### PR TITLE
[bp/1.29] Backport deps: updates QUICHE to incorporate fixes

### LINKED ISSUE #32401: Intermittent HTTP/2 Connection Hangs and Timeouts Post-Upgrade to v1.29
## Description

We have observed a significant increase in the occurrence of **408** status codes accompanied by `max_duration_timeout` responses during the transition from version **1.28** to **1.29**. Our suspicion is that this issue is related to **oghttp2**, as disabling it using the reloadable flag `http2_use_oghttp2 = false` resolves the problem.

The observed behavior entails requests from clients hanging for the entire duration of the `stream_timeout` on the individual routes, with no activity detected on the connection. Ultimately, this results in a **408** status code with `max_duration_timeout`.

image

We switched to **v1.29** from **v1.28** on **01/23** and turned off `oghttp2` on **02/10**.

## Repro Steps

Though the issue is intermittent and lacks a consistent reproduction scenario, our analysis from the access logs provides some insights:
- Downstream connections use HTTP/2.
- Upstream connections comprise a mixture of HTTP/2 and HTTP/1.1.
- All the requests that become stuck are of the `:method` type **POST**.
- Access logs indicate that no body is received from the client, with the number of [bytes received](https://arc.net/l/quote/rxxiatlo) reported as **0**.
- The number of [bytes sent](https://arc.net/l/quote/rmqamgdl) as always **27** i.e. the length of `max_duration_timeout`.
- The [upstream request attempt count](https://arc.net/l/quote/kghgydqo) get reported as **1**.

### PR DESCRIPTION
**Pull request by birenroy**
This change updates the QUICHE dependency to incorporate fixes for https://github.com/envoyproxy/envoy/issues/32401.

Commit Message: deps: updates QUICHE to incorporate fixes
Additional Description:
Risk Level: low
Testing: ran unit and integration tests locally
Docs Changes:
Release Notes:
Platform Specific Features:
Fixes #32401

### CODE REVIEW

**Review by RyanTheOptimist — CHANGES_REQUESTED** [review]
Oh, actually, can up update the changelog to mention this issue is fixed?

**Comment by phlax** [comment]
> Oh, actually, can up update the changelog to mention this issue is fixed?

pref on main first please

also seems there is a DCO issue

**Comment by RyanTheOptimist** [comment]
Looks like this needs a DCO fix. And please update the changelog as well.

**Comment by birenroy** [comment]
> Oh, actually, can up update the changelog to mention this issue is fixed?

I added a note in the v1.29.1 changelog. Should I also add it to the v1.29 one? I'm not familiar with how these releases are structured.

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
