### PR TITLE
quiche: update tar to 88c8d5903d851744410ea9840201b6507feae981

### PR DESCRIPTION
**Pull request by danzh2010**
Commit Message: update QUICHE tar ball to commit 88c8d5903d851744410ea9840201b6507feae981. Purge deprecated platform implementations. 

Risk Level: low
Testing: existing tests

### CODE REVIEW

**Review by alyssawilk — APPROVED** [review]

**Comment by moderation** [comment]
Single QUICHE tar dependency looks OK to me from a metadata point of view

**Comment by alyssawilk** [comment]
doing a main merge should fix the docs failure

**Comment by danzh2010** [comment]
> doing a main merge should fix the docs failure

done

**Comment by danzh2010** [comment]
Need upstream fix for the GCC error.

**Comment by danzh2010** [comment]
@DavidSchinazi

**Review by alyssawilk — APPROVED** [review]
needs a main merge for CI, but othrewise looks good!

**Comment by moderation** [comment]
Ready to run my `h3spec` tests when this lands :smile:

**Comment by alyssawilk** [comment]
Hahaha awesome.
I don't think this one improves compliance noticeably (dan can correct me) but it's nice to have the extra validation of corner cases working :-)

**Comment by danzh2010** [comment]
My experience is that such PR is more likely to cause compiler in-compliance.

**Comment by danzh2010** [comment]
@mattklein123 Alyssa is out tomorrow, can you help merge it?

**Comment by danzh2010** [comment]
Thanks!

**Comment by moderation** [comment]
Slight improvement on the `h3spec` tests. Failures have gone from 14 to 13. Looks like the new passing test is:

`MUST send PROTOCOL_VIOLATION if PATH_CHALLENGE in Handshake is received [Transport 17.2.4]`

image

**Comment by DavidSchinazi** [comment]
@moderation FWIW it's perfectly fine to ignore these h3spec errors. This tool is not authoritative in any way and handling some of these unrealistic cases would reduce the performance of the stack.

**Comment by moderation** [comment]
@DavidSchinazi definitely understand the tests aren't authoritative. But they are a fun way to see any behavior changes as the h3 / quic code improves.  The test suite did help @danzh2010 and @alyssawilk fix a crash last week

**Comment by DavidSchinazi** [comment]
@moderation thanks, that makes total sense to me. I just want to make sure we don't use h3spec as a yardstick to measure the quality of QUICHE :)

**Pull request merged**
