### PR TITLE
Add http-parser and BalsaParser tests for "Connection: close".

### PR DESCRIPTION
**Pull request by bencebeky**
Commit Message: Add http-parser and BalsaParser tests for "Connection: close".
Additional Description: new tests
Risk Level: low
Testing: //test/common/http/http1:codec_impl_test
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by yanavlasov** [comment]
Is this difference in behavior only relevant for tests? I would think Envoy should close the connection with the `connection: close` header on both request and response paths regardless of the H/1 codec it uses.

/wait-any

**Comment by bencebeky** [comment]
> Is this difference in behavior only relevant for tests? I would think Envoy should close the connection with the `connection: close` header on both request and response paths regardless of the H/1 codec it uses.
> 
> /wait-any

Yes, I agree with you, there is more work to be done in future PRs here. UHV or ConnectionImpl is probably a better place for the proposed change to close the connection than the codecs themselves.

This issue came up in a discussion and Kirti asked me to confirm the difference in behavior between the two codecs. I wrote these tests to answer the question.

**Comment by krajshiva** [comment]
Thanks for testing the behavior @bencebeky . We stumbled upon this while working on a FR. I think we all agree on behavior to be [RFC compliant](https://www.rfc-editor.org/rfc/rfc9112.html#name-tear-down)

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
