### PR TITLE
tls: remove legacy socket BIOs and runtime guard

### LINKED ISSUE #16013: envoy.reloadable_features.tls_use_io_handle_bio deprecation
Your change #12911 (tls: use custom instead of socket based bio) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

### PR DESCRIPTION
**Pull request by florincoras**
Signed-off-by: Florin Coras <fcoras@cisco.com>

Fixes #16013 

Risk Level: Low
Testing: n/a
Docs Changes: n/a
Release Notes: removed envoy.reloadable_features.tls_use_io_handle_bio runtime guard

### CODE REVIEW

**Review by ggreenway — DISMISSED** [review]
Looks good, but there's a merge conflict and a test failure.

**Comment by florincoras** [comment]
Merged main so conflict should be solved now. As for the test, this should not change default logic, so could it be a flake?

**Comment by ggreenway** [comment]
> Merged main so conflict should be solved now. As for the test, this should not change default logic, so could it be a flake?

Yeah, could be a flake. Let's see what happens with this CI run.

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
