### PR TITLE
docs: Fix subtitle format

### PR DESCRIPTION
**Pull request by luckyxiaoqiang**
Signed-off-by: luckyxiaoqiang <xiaoqiangding@126.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message: docs: Fix subtitle format
Additional Description: Fix format of subtitle in `original_dst_filter.rst`.  To view the old wrong format we can view [this page](https://www.envoyproxy.io/docs/envoy/v1.18.3/configuration/listeners/listener_filters/listener_filters) . Subtitle `Linux` and `Windows` should be child of `Original Destination`.
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@luckyxiaoqiang could you fix DCO please - change looks good

**Comment by luckyxiaoqiang** [comment]
> @luckyxiaoqiang could you fix DCO please - change looks good

Fixed.

**Review by phlax — APPROVED** [review]
lgtm - thanks @luckyxiaoqiang

**Comment by phlax** [comment]
aargghhh

/retest

**Pull request merged**
