### PR TITLE
v1.18 fix examples

### LINKED ISSUE #20360: verify_examples is broken on v1.18
verify_examples for cache and dynamic-config-cp are both broken on v1.18. I tried to cargo-cult my way around these issues in #20223 but wasn't able to get it across the finish line. 

https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/103180/logs/249

### PR DESCRIPTION
**Pull request by phlax**
Fix #20360

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] 
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @RyanTheOptimist

**Comment by phlax** [comment]
seems like just the macos issue left - coverage fixed itself

**Review by RyanTheOptimist — APPROVED** [review]
Awesome! Thanks for doing this.

FYI: There is an open issue about the mac failure on 1.18 and 1.19 so hopefully that'll get resolved shortly.

**Comment by phlax** [comment]
cc @mattklein123 to merge past the macos fail

**Pull request merged**
