### PR TITLE
test: use static functions rather than static data for std::string constants for config fragments

### PR DESCRIPTION
**Pull request by jmarantz**
Description: There are several static std::string constants in integration tests that violate our no-non-trivial-statics policy, and moreover are annoying when debugging tests. This just changes them from static strings to static functions returning non-static strings, and the changes are pretty surgical.
Risk Level: low
Testing: //test/...
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by jmarantz** [comment]
OK it's ready now. There is a lot of test flakage unfortunately but I do not believe it is due to this PR.

**Comment by mattklein123** [comment]
The clang-tidy issue look legit. Can you fix them? We need to burn through pre-existing issues on master. Thank you!

/wait

**Comment by jmarantz** [comment]
OK this is ready for another look.

**Pull request merged**
