### PR TITLE
[http] fix http1.0 drain cause delay close.

### PR DESCRIPTION
**Pull request by pyrl247**
When we have the following situation:
 A --http1.0 request--> envoy --http1.1 request--> B
 A <--http1.0 response-- envoy <-- http1.1 response chunked-- B

Envoy response to A will not have content-length, the response will be framed by connection close.
When listener are draining, the drain timeout will cause connection delay close,and A will stop receiving response until connection close.
Since http1.0 is short-lived connections,maybe we don't need drain when use http10?
Signed-off-by: GuangYang <pyrl247@gmail.com>

Risk Level: Low
Testing:
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by alyssawilk** [comment]
Thanks for looking into this.  I thought this was already handled though - if the response is HTTP/1.1 framed by connection close, we should be force-closing on end stream here:

https://github.com/envoyproxy/envoy/blob/main/source/common/http/conn_manager_impl.cc#L257

I don't think that we need to change code other than that.  If you think that isn't sufficient could you write an integration test which exhibits the lag which we can use as a regression test?
/wait

**Comment by pyrl247** [comment]
Oh,It seems already solve the problem.My local code was several versions behind main;I didn't notice this change before.Thanks!!

**Comment by pyrl247** [comment]
@alyssawilk Sorry to bother .
 https://github.com/envoyproxy/envoy/blob/main/source/common/http/conn_manager_impl.cc#L257  .
This maybe not handled the situation when drain_state_ == DrainState::Draining.
https://github.com/envoyproxy/envoy/blob/main/source/common/http/conn_manager_impl.cc#L1312

**Comment by alyssawilk** [comment]
could you just add an e2e test which shows the connection not delay closing in the circumstances you describe?  Once you have that and can show the test fails prior to a change I'd be happy to review.
thanks!
/wait

**Pull request closed without merging**
