### PR TITLE
[1.18] Windows ci add bazel args (#16643)

### PR DESCRIPTION
**Pull request by dmitri-d**
This is a port of https://github.com/envoyproxy/envoy/pull/16643

* Windows: Expand functionality of ci/windows_ci_steps.sh

- Watch for //source/exe:envoy-static or empty args to trigger the build
- Treat arbitrary args as bazel test directives

This allows forms such as;

  ci/windows_ci_steps.sh //source/exe:envoy-static   - build the binary, nothing else
  ci/windows_ci_steps.sh //test/...                  - test everything with exceptions and flake processing

The default (no args) does both of the above, and checks unused deps under bazel/... that are not skip_on_windows

  ci/windows_ci_steps.sh //test/common/...           - test everything with no exceptions below common
  ci/windows_ci_steps.sh //test/common/... --test_tag_filters=-skip_on_windows
- same as above, avoiding broken components under common

* Update bazel/README.md

- If building an 18 month old envoy, an 18 month old copy of this document
  is present in that source tarball
- Offer a more recognizable symlink/path advisory based on current Python release

* Clarify windows_build_steps.sh and windows docker invocation

* Skip three longest windows test names for the month

- Bazel before 5.0.0 fails to shorten executable path names of a specific length.
- SymInitialize() fails to load the executable paths of a specific length
- abesil tries to prepare for crash analysis and silently continue on failure
- grps tries and abruptly aborts the program if symbols cannot be loaded

Fix is in for the next bazel rolling release of the 5.0.0 series

Signed-off-by: William A Rowe Jr <wrowe@vmware.com>
Signed-off-by: Dmitri Dolguikh <ddolguik@redhat.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by wrowe — APPROVED** [review]
No impact on linux, these changes make sense since 1.18 is the first "GA" branch for Windows. LGTM, rekicked to see if quic integration test will pass or flake under clang-cl, expecting it to flake. We should merge either way, this patch didn't touch that.

**Comment by wrowe** [comment]
FYI @davinci26

**Comment by wrowe** [comment]
Not sure how to take this to another maintainer who is in office this week

**Comment by wrowe** [comment]
Matt is OOO, if you could take this @PiotrSikora? It will help pre-flight the 1.18.4 binary-only build to prep for a clean 1.19.0

**Review by PiotrSikora — APPROVED** [review]

**Comment by PiotrSikora** [comment]
> Matt is OOO, if you could take this @PiotrSikora? It will help pre-flight the 1.18.4 binary-only build to prep for a clean 1.19.0

I have no merge permissions, I think you're looking for @envoyproxy/senior-maintainers.

**Pull request merged**
