### PR TITLE
router: remove route-action level header manipulation

### PR DESCRIPTION
**Pull request by derekargueta**
_Description:_ These features were deprecated in https://github.com/envoyproxy/envoy/pull/3838 and resolves https://github.com/envoyproxy/envoy/issues/4616
_Risk Level:_ Low (may break anyone who is still using route-action header add/removal)
_Testing:_ Updated - route-action configs were either removed or bumped to the route level
_Docs Changes:_ N/A - documentation was already removed when deprecated.
_Release Notes:_ Added

Signed-off-by: Derek Argueta <dereka@pinterest.com>

### CODE REVIEW

**Comment by mattklein123** [comment]
@derekargueta do you mind merging master?

/wait

**Comment by derekargueta** [comment]
hmmm, `//test/extensions/transport_sockets/alts:alts_integration_test` failed on that last run.

**Pull request merged**
