### PR TITLE
Update prometheus/client_model version

### PR DESCRIPTION
**Pull request by ZymoticB**
Commit Message: Update prometheus/client_model version
Additional Description: This is a WIP change to update the version of https://github.com/prometheus/client_model to pick
up the new protobuf filename. I think the process is to run `./tools/proto_format/proto_format.sh fix`
but this fails:
```
io/prometheus/client/metrics.proto: File not found.
envoy/service/metrics/v2/metrics_service.proto:7:1: Import "io/prometheus/client/metrics.proto" was not found or had errors.
envoy/service/metrics/v2/metrics_service.proto:43:12: "io.prometheus.client.MetricFamily" is not defined.
Aspect //tools/protoxform:protoxform.bzl%protoxform_aspect of @envoy_api_canonical//versioning:active_protos failed to build
```

It seems to be using the old version of the repository, but I am not sure how to proceed.

Risk Level: Low; the protobuf types are not changing at all.
Testing: proto_format and tests
Docs Changes: 
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Comment by snowp** [comment]
I pushed a commit to get this working, needed to update the generated_api_shadow version of the repo file as well.

/retest

**Comment by snowp** [comment]
@envoyproxy/api-shepherds 
@envoyproxy/dependency-shepherds

**Comment by ZymoticB** [comment]
Thanks @snowp ! I wasn't sure if I should update the generated directory or of the proto_format tool was supposed to do that for me.

**Review by lizan — APPROVED** [review]

**Pull request merged**
