### PR TITLE
move http HeaderString to common code tree for common usage

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: move http HeaderString to common code tree for common usage
Additional Description:

See #23327 for background.

Risk Level: Low.
Testing: n/a.
Docs Changes: n/a.
Release Notes: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
cc @yanavlasov here.

**Comment by yanavlasov** [comment]
Sounds good. You also need to refactor unit tests, to pass coverage.

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
