### PR TITLE
repokitteh: pin modules to git SHAs.

### PR DESCRIPTION
**Pull request by htuch**
The main goal here is to improve stability via hermetic description of RK dependencies.

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

**Comment by htuch** [comment]
@itayd can you update my RK perms to support this? Thanks.

**Comment by itayd** [comment]
@htuch are you going to update this?

**Comment by htuch** [comment]
@itayd looks like it now works with the hash SHA syntax, thanks.

**Pull request merged**
