### PR TITLE
Add option to access upstream connection

### PR DESCRIPTION
**Pull request by gargnupur**
We have upstream filters now, and thus need a way to access upstream connection by downstream filters to access filterstate/streaminfo on upstream connection.

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:Add option to access upstream connection
Risk Level:Low
Testing:Added unite test for TCP
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by kyessenov** [comment]
I think the idea is carry over filter state from upstream filter to downstream filter. We probably need to use shared pointer for the filter state and just copy that to the downstream stream info.

**Comment by gargnupur** [comment]
@mattklein123 : Thanks for the quick response. As @kyessenov pointed it out, we need access of upstream filter state in downstream filter. I tried by sharing the filter state between upstream and downstream connections but because of thread local stuff I think, it didn't work. Have more details on this in https://github.com/envoyproxy/envoy-wasm/issues/291 here.
The only approach that seemed less invasive was making ClusterInfo mutable. I also, tried adding upstream connection accessor to HostDescription too but it involved making HostDescription and Host mutable at places.
Please let me know if you have any other ideas..

**Comment by mattklein123** [comment]
I think you will need to look at the `onPoolReady` callback (for HTTP) and somehow send back the info you need at that point. Unfortunately this is super hacky as there is no connection at that level of abstraction. It's all streams, but potentially sending back some type of const stream info, filter data, etc. might work.

**Comment by gargnupur** [comment]
@mattklein123 : Thanks for the pointer... taking a look...

**Comment by mattklein123** [comment]
I'm going to close this PR. @gargnupur can you open an issue once you have a design proposal and we can discuss before we do any implementation? Thank you.

**Pull request closed without merging**
