### PR TITLE
test: add process_object_ to BaseIntegrationTest

### LINKED ISSUE #6969: Proposal: ProcessContext
*Title*: *Allow users to pass data to filters via e.g. ProcessContext*

*Description*:
This is a hand-wavy feature request. Design ideas welcome.

We run Envoys in a binary with other serving threads. We'd like some of our filters to behave differently based on the lameduck status of those other serving threads. However, there's not a great way currently to get state from those threads/servers to the filters, short of a global variable.

This hypothetical ProcessContext could provide an API for information to flow from those other servers/serving threads to the filter factories. Envoy would be given a ProcessContext at startup, and would hand it to factories as needed.

A really naive implementation (note: my former Abseil colleagues might disown me if we actually implemented this version):

```
class ProcessContext {
 public:
  ProcessContext(void* process_data) : process_data_(process_data) {}
  void* get() { return process_data_; }

 private:
  void* process_data_;
};

// In e.g. a filter factory:
Envoy::Http::FilterFactoryCb MyFilter::createFilter(
    const std::string& stat_prefix,
    Envoy::Server::Configuration::FactoryContext& context,
    ProcessContext& process_context) {
  MyServerData* server_data = reinterpret_cast<MyServerData*>(process_context.get());
  return [&server_data](Envoy::Http::FilterChainFactoryCallbacks& callbacks) {
    callbacks.addStreamDecoderFilter(std::make_shared<MyFilter>(server_data));
  };
}

// Now MyFilter has a pointer to MyServerData
```

Thoughts?

cc @mergeconflict @htuch

### PR DESCRIPTION
**Pull request by ahedberg**
Signed-off-by: Ashley Hedberg <ahedberg@google.com>

Description: Adds a process_object_ member to BaseIntegrationTest. If an integration test subclassing from BaseIntegrationTest sets this member, the envoy server will be started with a ProcessContext referencing that object.
Risk Level: low (test-only, defaults to nullopt)
Testing: bazel test //test/... - not sure if stats_integration_test failures were related. Also not sure where to add a test for this, but happy to do so (I have an internal test that proves this does what I wanted it to).
Docs Changes: none
Release Notes: n/a
Fixes #6969

### CODE REVIEW

**Comment by ahedberg** [comment]
Friendly ping @junr03?

**Comment by junr03** [comment]
Sorry, I have been flying yesterday and today. I took a look at the code and it looks reasonable. I feel the same way about this as mine and Alyssa's comments [here](https://github.com/envoyproxy/envoy/pull/6797#pullrequestreview-235242361). @jmarantz might have a good suggestion for where to drop a test that exercises this.

**Comment by ahedberg** [comment]
Test added, PTAL. Thanks!

**Comment by ahedberg** [comment]
Ping @junr03 ? Or @htuch who reviewed the PR adding this feature?

**Comment by ahedberg** [comment]
Ping @junr03

**Comment by ahedberg** [comment]
Thanks for the review! Harvey is out of office until Thursday--Alyssa, mind doing the final pass?

/assign @alyssawilk

**Pull request merged**
