### PR TITLE
Update data-plane-api (second attempt)

### PR DESCRIPTION
**Pull request by kyessenov**
*title*: Update data plane API to pick refactoring

*Description*:
Applies refactoring of packages to Envoy code.

*Risk Level*: Medium (previous attempt caused problems rolling out changes due to incompatibility with the management servers)

*Testing*:
No functional change.

*Docs Changes*:
https://github.com/envoyproxy/data-plane-api/pull/438#issuecomment-360943120

*Release Notes*:

### CODE REVIEW

**Comment by kyessenov** [comment]
I cannot reproduce ASAN failure: `bazel test -c dbg --config=asan //test/integration:metrics_service_integration_test` passed

**Comment by htuch** [comment]
Yes, this is a flake in my recent change. I'm going to roll it back while I fix.

**Comment by mattklein123** [comment]
@kyessenov I suspect this is related to @htuch change but not sure. He can take a look.

**Comment by mattklein123** [comment]
LGTM once we get the merge conflicts and flake sorted out.

**Comment by mattklein123** [comment]
@junr03 can you manually test this branch at Lyft very quickly just to make sure it works. Would just like a quick sanity test.

**Pull request merged**
