### PR TITLE
ci: Make stage dependencies configurable

### PR DESCRIPTION
**Pull request by phlax**
This should allow postsubmit to run precheck + build simultaneously.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
this looks like a bigger change than it is - it mostly moves `pipelines.yml` -> `stages.yml` (with some alterations) and then `pipelines.yml` calls `stages.yml` with pipeline config

**Comment by phlax** [comment]
> Trust you copied the file since it's hard to review.

thanks - yep - i was pretty careful - and im going go to iterate this code so will monitor

**Comment by phlax** [comment]
arggh - this didnt quite work - every undergraduate CS student should be sent to microsoft to learn how not to handle booleans

ill test a fix

**Comment by kyessenov** [comment]
No worries, let me know if you want to revert or fix forward.

**Comment by phlax** [comment]
we can fix forward - the configurability is there now, just need to configure it better for postsubmit

**Pull request merged**
