### PR TITLE
header_to_metadata: support coping metadata to header

### PR DESCRIPTION
**Pull request by yangminzhu**
For the 2nd point in https://github.com/envoyproxy/envoy/issues/7771

@lizan @kyessenov @rgs1 @zuercher @mattklein123 @htuch 
Before working on the actual code change, I would like to get agreements on the API for this. PTAL and let me know what do you think, thank you.

- Option 1
  The [commit](https://github.com/envoyproxy/envoy/commit/81aa376d943dfc836e62f27a0116615180ccb98c) adds a new standalone metadata_to_header filter
  - Pros
    - Cleaner, we don't need to deprecate any thing in the header_to_metadata filter.
  - Cons
    - Duplicate the current filter API and implementation.

- Option 2
  The [commit](https://github.com/envoyproxy/envoy/commit/bdc9dfab6979d5ad979259e5497ba477781bc621) incrementally change the header_to_metadata API by deprecating the old fields.
  - Pros
    - Reuse the current filter API and implementation
    - More powerful as we can support the case for header-to-header and metadata-to-metadata, but not sure if this will be useful.
  - Cons
    - Need to deprecate the current header_to_metadata API.

- Other options
  Please let me know if you have suggestions for other options, thank you.

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level: Low
Testing: N/A (will add after API approved)
Docs Changes: N/A (will add after API approved)
Release Notes: N/A (will add after API approved)
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by htuch** [comment]
Thanks for this contribution. I have a few thoughts:

1. How come we are still using dynamic metadata? It was my understanding that the typed filter state was the direction we want to take filter state sharing. It seems a solution to what you want to do that takes us towards that is preferable.

2. However you structure the filters, the API can share messages, we do't need to repeat the value encoding fields etc.

3. I think it's reasonable to structure as two distinct filters, these are complementary.

**Comment by kyessenov** [comment]
@htuch, regarding 1: for a dynamic script support, untyped metadata is beneficial. Think about how we would obtain a shared filter value from a Lua script. It would be hard to do that without having to write a filter-specific accessor for the filter state. If a filter object could provide a generic traversal method, that would make it usable, but right now it appears to be a an opaque C++ type without any interface.

**Comment by lizan** [comment]
> How come we are still using dynamic metadata? It was my understanding that the typed filter state was the direction we want to take filter state sharing. It seems a solution to what you want to do that takes us towards that is preferable.

I don't think we had consensus with moving toward C++ typed filter state, instead we documented clearly which are known dynamic metadata from in-tree filter. The flexibility of dynamic metadata is inevitable for filters like RBAC and ext_authz.

**Comment by kyessenov** [comment]
@htuch @lizan Could we mandate the use of protobuf messages as filter objects? There is a generic reflection-based accessor for protobuf objects. Struct has a very annoying issue with inability to represent ints as ints.

**Comment by yangminzhu** [comment]
@htuch 
Regarding 1: In addition to Lizan and Kuat's comments, the other thing is I'm following the current convention in the `header-to-metadata` filter, it seems more natural to have the counterpart as `metadata-to-header` instead of `filter_state-to-header`.

Regarding 2: We could share some of the common APIs but I'm not sure if it worth the extra work for sharing only some simple messages and enums. It requires change in both Envoy and control plane.

Regarding 3: I'm slightly leaning to option 2 (incrementally change the current filter) as it seems cleaner and more flexible. But I'm okay with either way. @lizan @rgs1 @zuercher @mattklein123 @kyessenov Any thoughts on this? I really appreciate if we can get this decided soon so I can update the PR with the actual code change, thank you.

**Comment by lizan** [comment]
> @htuch @lizan Could we mandate the use of protobuf messages as filter objects? There is a generic reflection-based accessor for protobuf objects. Struct has a very annoying issue with inability to represent ints as ints.

Do we now have a generic enough reflection-based accessor for protobuf? IIRC when we had the discussion last time, the one in OSS isn't enough to handle repeated fields etc.

**Comment by kyessenov** [comment]
I don't recall this discussion in the past, but I've run into some reflection limitations before. There is a [dirty-but-working](https://github.com/google/cel-cpp/blob/master/eval/eval/field_backed_map_impl.cc#L12) hack in CEL around accessing maps.

**Comment by htuch** [comment]
Yeah, so let's continue the filter state discussion in https://github.com/envoyproxy/envoy/issues/4929. For this PR, let's unblock as it's the inverse of an existing filter that is already relying on dynamic metadata anyway.

I'd still advocate sharing common messages between filters. You should not have to make any breaking changes, just reference the existing messages.

**Comment by yangminzhu** [comment]
Quick update: based on the feedback, I will go with Option 1 and update the PR soon. Thanks!

**Pull request closed without merging**
