### PR TITLE
bazel: fix macOS build

### PR DESCRIPTION
**Pull request by keith**
It seems that some combination of macOS Monterey and Xcode 13 started
causing a build issue. The problem is that `mach/boolean.h` adds macros
for `TRUE` and `FALSE` which conflicts with some of Envoy's own uses of
these. We never import this directly so it's possible these macros are
not new, but just exposed through headers in a new way.

The core fix here is to update cel-cpp to fix https://github.com/google/cel-cpp/issues/121

The secondary fix is to remove this macro as envoy already did for
windows. This stops any code that imports the platform header from
hitting this in the future.

This fixes: https://github.com/envoyproxy/envoy/issues/18842

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Comment by belyalov** [comment]
Confirm, it does complete on M1-Pro

**Comment by yanavlasov** [comment]
@moderation can you LGTM deps, please?

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
