### PR TITLE
honor connection_pool_per_downstream_connection in tcp_conn_pool

### PR DESCRIPTION
**Pull request by Pawan-Bishnoi**
Commit Message: this flag is already supported by httpConnPool. Adding to tcpConnPool as well so that thrift_proxy etc can use this feature.
Risk Level: low
Fixes https://github.com/envoyproxy/envoy/issues/34762

### CODE REVIEW

**Comment by Pawan-Bishnoi** [comment]
duplicate of this pr -> https://github.com/envoyproxy/envoy/pull/34763 to give CI a fresh chance.
Will close the other one if this goes through.

**Comment by KBaichoo** [comment]
FWIW https://github.com/envoyproxy/envoy/pull/35231 is an attempt to fix the codeQL disk issue

**Comment by phlax** [comment]
> FWIW https://github.com/envoyproxy/envoy/pull/35231 is an attempt to fix the codeQL disk issue

that PR currently only handles the push CI rather than for PRs - i can update it now - i wasnt aware that this was failing on PRs also

**Comment by yanavlasov** [comment]
@Pawan-Bishnoi please merge main to fix CI problem.

**Pull request closed without merging**
