### PR TITLE
[fuzz] fix oss fuzz crashes due to validation 

### PR DESCRIPTION
**Pull request by samflattery**
Commit Message: Fix OSS fuzz crashes due to validation issues
Additional Description:

- add validation that an enum is within range
- add validation that a header is well formed

Risk Level: low
Testing: passes added regression tests
Docs Changes: N/A
Release Notes: N/A
Fixes: 
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23879
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23881

### CODE REVIEW

**Comment by htuch** [comment]
@samflattery can you `fix_format`?

**Comment by samflattery** [comment]
Forgot to merge master to there were some files that weren't formatted, should be good to go now

**Comment by asraa** [comment]
@htuch quick lgtm api?

**Pull request merged**
