### PR TITLE
tls_inspector: update the security posture - robust against untrusted upstreams

### PR DESCRIPTION
**Pull request by adisuissa**
Commit Message: tls_inspector: update the security posture - robust against untrusted upstreams
Additional Description:
Prior to this PR the [tls_inspector filter](https://github.com/envoyproxy/envoy/blob/0e53ab5bb59548d04c75035d896b630c5c22fe05/source/extensions/filters/listener/tls_inspector/tls_inspector.h#L80) security posture was robust against untrusted downstreams.
This PR updates the security posture to be robust also against untrusted upstreams, because:
1. The filter only parses events coming from the downstream.
2. The filter does not connect to any upstream to perform its functionality.

Risk Level: low - no code changes
Testing: N/A.
Docs Changes: N/A.
Release Notes: Added.

### CODE REVIEW

**Review by KBaichoo — DISMISSED** [review]

**Review by botengyao — APPROVED** [review]
Thanks Adi!

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by adisuissa** [comment]
Assigning Greg for !Google review
/assign @ggreenway

**Review by ggreenway — DISMISSED** [review]

**Comment by RyanTheOptimist** [comment]
/wait
Needs merge

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
