### PR TITLE
ci: Only trigger release CI if explicitly set

### LINKED ISSUE #26830: Ensure scheduled runs dont mess up releases
During the recent 1.26 release i switched off the scheduled run as it wasnt clear what would happen

### PR DESCRIPTION
**Pull request by phlax**
This is a better tested version of what #28535 hoped to achieve

Fix #26830 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
actually - this could resolve #26830 ...

**Review by adisuissa — COMMENTED** [review]
LGTM, thanks!

**Comment by phlax** [comment]
argh - just spotted error - will update ...

**Comment by phlax** [comment]
done

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
