### PR TITLE
bazel: enable rules_foreign_cc vendored tools

### PR DESCRIPTION
**Pull request by keith**
This reverts commit fed3d12fa8abad35162583c2d935789baf3e14b7.

The original change had an issue with macOS 12.3 removing the default python version.

https://github.com/bazelbuild/rules_foreign_cc/pull/900
https://github.com/ninja-build/ninja/pull/2118

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Comment by keith** [comment]
no changes here yet, partially waiting to see what happens on the linked PRs

**Comment by jsharpe** [comment]
@keith note that the automake example in rules_foreign_cc is not usable yet as it depends on the autoconf build which doesn't work because it does generate relocatable output so I don't have a good way yet of making the autotools set of build tools hermetic yet.

Also worth noting that if you end up building cmake from source rather than using one of the precompiled binaries then openssl support is missing at the moment.

**Comment by keith** [comment]
> @keith note that the automake example in rules_foreign_cc is not usable yet as it depends on the autoconf build which doesn't work because it does generate relocatable output so I don't have a good way yet of making the autotools set of build tools hermetic yet.

Thanks for the context, if we're not calling this directly that shouldn't affect us right? I only see make + cmake + ninja atm

> Also worth noting that if you end up building cmake from source rather than using one of the precompiled binaries then openssl support is missing at the moment.

hrm good to know, I can probably look but what conditions would we build it, and when would we need openssl?

**Comment by keith** [comment]
i need to update this once there's a new release of these rules

**Pull request closed without merging**
