### PR TITLE
server: allowing network filters to be exception free

### PR DESCRIPTION
**Pull request by alyssawilk**
Also making HCM exception free

Risk Level: low
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
https://github.com/envoyproxy/envoy-mobile/issues/176

### CODE REVIEW

**Comment by wbpcode** [comment]
Seems this PR only update the interface and doesn't change any logic of exist network filters?

**Comment by alyssawilk** [comment]
Also updating the HCM, updated PR description

**Comment by alyssawilk** [comment]
cc @yanavlasov for import awareness

**Review by wbpcode — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
