### PR TITLE
ci: Reorganize release pipelines

### PR DESCRIPTION
**Pull request by phlax**
This PR

- merges the `docker` and `publish` stages in CI
- splits the `distribution` jobs between `publish` and `verify`

partial fix for issues raised in #25426 

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@lizan this is the first of several PRs to move towards publishing from the release branch rather than the tagged commit

**Comment by phlax** [comment]
this will need some changes to the github `required` jobs and may cause some temporary disruption on prs

**Comment by phlax** [comment]
in order for azp to be able to evaluate stages that contain jobs with references to securefiles in presubmit (even if the job is disabled in presubmit) i have had to do some convoluted things:

- add an empty key for presubmit
- add a pipeline variable to presubmit pointing to the empty key
- add a pipeline variable to postsubmit pointing to the real key

**Comment by phlax** [comment]
this is going to be a bit of a challenge backporting - but i think its important that we do for 1.23+ so we can continue to update the publishing code together, and be using/maintaining similar pipelines

**Review by lizan — APPROVED** [review]

**Pull request merged**
