### PR TITLE
fix ci LINUX_DISTRO variable name, also change centos:devtoolset-6-toolchain-centos7 to centos:7

### PR DESCRIPTION
**Pull request by jwfang**

### CODE REVIEW

**Comment by jwfang** [comment]
testing CI build_imange in #1724

**Comment by jwfang** [comment]
while testing CI, found another issue: centos/devtoolset-6-toolchain-centos7 is lately updated, cause g++ version check failed.

i changed from centos/devtoolset-6-toolchain-centos7 to centos:7 and install devtoolset-4 manully.

sorry for the trouble, i should have tested the CI earlier.

**Comment by mattklein123** [comment]
Thanks @jwfang LGTM. Let's see if this works.

**Comment by mattklein123** [comment]
@jwfang I had to fix a few docker things, but looks good: https://hub.docker.com/r/lyft/envoy-build-centos/tags/

**Pull request merged**
