### PR TITLE
http1_codec_impl_fuzz_test: rename for OSSfuzz

### PR DESCRIPTION
**Pull request by robertfemmer**
This http1_codec_impl_fuzz_test has a name collision with an existing fuzzer. OSS-fuzz seems to not
support this and does not run this fuzzer.
This PR renames this fuzzer, s.t. it will be run in OSS-fuzz.

### CODE REVIEW

**Comment by phlax** [comment]
@bencebeky would you mind taking a look

**Review by bencebeky — APPROVED** [review]
LGTM

**Comment by phlax** [comment]
@robertfemmer looks like this requires a main merge

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
