### PR TITLE
test: fixing a test flake

### PR DESCRIPTION
**Pull request by alyssawilk**
Before: failed 11/8000, after passes all of 8000

Commit Message: n/a
Additional Description: n/a
Risk Level: n/a
Testing: lots
fixes https://github.com/envoyproxy/envoy/issues/18881

### CODE REVIEW

**Review by asraa — APPROVED** [review]
Thank you so so much!

Honestly a little confused why git isn't showing the diff removing the lines disabling coverage on this test...

**Comment by alyssawilk** [comment]
Ahh, i hadn't pulled in the disable because I hadn't seen we'd done that.  Fixed!

**Review by asraa — DISMISSED** [review]

**Comment by alyssawilk** [comment]
/wait well that's weird this fixes the flake locally.  will dig more

**Comment by alyssawilk** [comment]
oh joy, it failed without actually logging what went wrong.
I can't repro this failure locally.  trying again on CI and converting this to draft so we don't merge accidentally.

**Pull request merged**
