### PR TITLE
Remove runtime guard `copy_response_code_to_downstream_stream_info`

### PR DESCRIPTION
**Pull request by jbohanon**
Fixes https://github.com/envoyproxy/envoy/issues/33615
Commit Message: Remove runtime guard `copy_response_code_to_downstream_stream_info`
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Comment by jbohanon** [comment]
cc @yanavlasov (as approver of original PR) have a chance to look at this?

I'll fix the changelog once I have the approvals; no need to thrash CI until then

**Comment by adisuissa** [comment]
Author requested Yan's approval:
/assign @yanavlasov

**Comment by yanavlasov** [comment]
LGTM. Please resolve merge conflict.

/wait

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Review by yanavlasov — APPROVED** [review]

**Comment by jbohanon** [comment]
Can someone with write access please merge? @adisuissa @yanavlasov

**Pull request merged**
