### PR TITLE
Fix order of destruction for DnsFilterResolver to prevent crashes during c-ares queries

### PR DESCRIPTION
**Pull request by lobkovilya**
Commit Message: destroy `resolver_` before `lookups_` so that callback registered in `resolver_` could write to `lookups_` without crashing.
Additional Description: the order of members is important. If the `lookups_`'s destructor is called before the `resolver_`'s destructor and some c-ares queries were in progress, then the DnsFilterResolver's callback function may try to write to the `lookups_` hash map, which could cause Envoy crash. To avoid this problem, the `resolver_` should be destroyed before the `lookups_`.
Risk Level: low
Testing: manual
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by htuch — COMMENTED** [review]
Looks right to me, but @mattklein123 to verify.

**Comment by mattklein123** [comment]
LGTM can you fix format?

/wait

**Review by mattklein123 — APPROVED** [review]

**Comment by itsLucario** [comment]
Hi @lobkovilya , 
We had a similar proxy crash issue with c-ares DNS resolution callback. 
Do you think this would fix the issue mentioned here?
https://github.com/istio/istio/issues/45045  

Any info would be appreciated!

**Comment by nmnellis** [comment]
We believe we are hitting this issue in 1.24. Before upgrading to a more recent version of envoy we would like to verify that this fix will solve our issue. Any idea how we could potentially trigger this issue? do we need to do many DNS lookups? or potentially fill the pending lookups bucket?

**Pull request merged**
