### PR TITLE
bazel: Remove cl.exe compiler workarounds for googleurl

### PR DESCRIPTION
**Pull request by keith**
The issue linked to this was closed over a year ago https://github.com/envoyproxy/envoy/issues/11974

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Comment by keith** [comment]
cc @dio, if I'm reading this right this is probably safe? I want to see what CI says either way

**Comment by dio** [comment]
@keith seems like so. Thanks for the cleanup!

**Review by htuch — APPROVED** [review]
wh00t, thanks!
/lgtm deps

**Comment by keith** [comment]
Hrm maybe the comments were outdated:

```
# Execution platform: @envoy_build_tools//toolchains:rbe_windows_msvc_cl_platform
external/com_googlesource_googleurl\base/compiler_specific.h(11): fatal error C1189: #error:  "Only clang-cl is supported on Windows, see [https://crbug.com/988071"](https://crbug.com/988071%22)
```

**Pull request closed without merging**
