### PR TITLE
[WIP/bp/1.25] Kafka + deps

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by adamkotwasinski** [comment]
LGTM 👍 as in https://github.com/envoyproxy/envoy/pull/29171#issuecomment-1687076386

**Comment by RyanTheOptimist** [comment]
Looks like clang-tidy is failing.
/wait

**Comment by adamkotwasinski** [comment]
hey @phlax & @RyanTheOptimist - I think the easier way to solve that would be to backport just the Kafka stuff and not the feature (filter) stuff; IIRC there were some .cc changes too that's why it's harder to port.
So TLDR I'll take a look into backporting only the smaller piece - but in about 1 or 2 weeks (sorry kinda busy IRL right now). Is that ok?

**Comment by phlax** [comment]
closing in favour of #29825

**Pull request closed without merging**
