### PR TITLE
test: remove the manual declarations of TestThread and figure it out from the platform.

### PR DESCRIPTION
**Pull request by jmarantz**
Commit Message: Earlier attempts to integrate a requirement to manually declare TestThread made it too hard to integrate with other repos that depend on Envoy, but not on all its test infrastructure.

Instead, this PR uses platform-specific mechanisms to determine whether the current thread is the 'test' thread (ie the thread in main()). This makes it unnecessary to declare TestThread anywhere. However, the TestThread empty struct is left in the codebase for now to avoid adding more conflicts with other repos. It can be removed in a month or so.

A new RAII construct `SkipAsserts` is added as an escape for scenarios where we are integrating Envoy code in a context where the thread-checking is not relevant.

Additional Description:
Risk Level: low
Testing: //test/...
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by jmarantz** [comment]
Ah glad I got some feedback on this before pushing forward.

The problem with the prior state where TestThread was declared by the test infrastructure is that we had a ton of tests that included Envoy code, but not its test infrastructure. But we could OR that all together and let you still declare a manual TestThread if you want to. Do you need to declare multiple distinct TestThread objects at the same time? Or do you just instantiate TestThread around a call that might do some checking?

**Comment by snowp** [comment]
The way it works right now is that we just wrap offending code with `TestThread`, which seems to do the trick. We haven't had an issue with having to declare it multiple times, but I can imagine it being a thing down the line. 

I think ideally we'd have something like a `IgnoreThreadChecks` handle that lets us do what we do with TestThread today, but without issues of there being multiple threads needing to bypass thread checks. I think with that we could have the real test thread be inferred via the logic in this PR, while also giving us an easy way for us to bypass these thread checks - kinda like a "i know what I'm doing, let me skip these checks".

**Review by snowp — APPROVED** [review]
Thanks!

**Pull request merged**
