### PR TITLE
deps: Bump com_github_c_ares_c_ares

### PR DESCRIPTION
**Pull request by moderation**
Commit Message: Bump com_github_c_ares_c_ares
Additional Description: Update from `1.19.1` to `1.22.1`
Risk Level: Low
Testing: `bazel --nohome_rc test //test/...`
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by moderation** [comment]
Wondering if timeout changes in `1.20.0` are the cause of the failures - https://c-ares.org/changelog.html#1_20_0

> [Default per-query timeout has been reduced to 2s with a 3x retry count](https://github.com/c-ares/c-ares/pull/542)

**Comment by htuch** [comment]
Example failure at https://dev.azure.com/cncf/envoy/_build/results?buildId=156269&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=d1a98671-b7ba-5fbf-f06c-ff337c010df4. I'm thinking this isn't a test flake or a timeout thing, and probably worth some dedicated debugging.

**Comment by moderation** [comment]
Going to try `1.23.0`

**Pull request closed without merging**
