### PR TITLE
tls: add the missing wrapper around SlotImpl allocation.

### PR DESCRIPTION
**Pull request by stevenzzzz**
Description: Add Wrapper around newly allocated SlotImpl.
 This was missed in PR 8135. Which means newly created TLS are deallocated in the old way( destructed on owner destruction possible race, but the race window is really small, see issue #7902 )
Risk Level: Medium 
Testing: N/A
Docs Changes:  N/A
Release Notes: N/A

### CODE REVIEW

**Comment by mattklein123** [comment]
Please add a test that covers whatever bug this is. Thank you!

/wait

**Comment by stevenzzzz** [comment]
/nostale
Sorry, this is on my radar. I have some cycles now, still adding test.

**Comment by stevenzzzz** [comment]
/assign mattklein123
Have to add the test as a friend.
PTAL.

**Comment by stevenzzzz** [comment]
thx!

**Pull request merged**
