### PR TITLE
Removes most references to getenvoy

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Commit Message: Removes most references to getenvoy

Additional Description:
This removes the website links of getenvoy for everything except system
packages which #16867 will solve.

It also removes the section about nightlies as I don't think they are being
maintained and certainly won't be moving forward.

Risk Level: Low
Testing: None
Docs Changes: Only Docs
Release Notes: No
Platform Specific Features: No

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
@phlax once #16866 is also solved, there should be no confusion left around getenvoy especially as I'll be following up to change the website and remove content except CLI usage.

**Comment by phlax** [comment]
@codefromthecrypt can we keep this as is for now - im hoping we can resolve most of the issues you have posted so far fairly quickly

**Comment by codefromthecrypt** [comment]
@phlax the main problem is people are coming to getenvoy because of these links and looking for support and we can't give it to them. So, I think it is probably better to remove the links. The ones removed here are completely redundant to upstream. Make sense?

**Comment by phlax** [comment]
yep, i see - let me look over this a bit further later today

**Comment by codefromthecrypt** [comment]
I know there's often confusion, but there's basically no more work happening on these repos, and there is no plan to do anything except archive them. There is no plan for example, to migrate these redundant repos to CNCF. So, we should remove the links to the tetrate repos especially ones that cause confusion (the redundant ones)

**Comment by codefromthecrypt** [comment]
fyi this is follow-up as we're pretty much good except getenvoy website edits after the various things I raised https://github.com/tetratelabs/getenvoy-package/issues/119

much appreciate the support @phlax!

**Review by phlax — APPROVED** [review]
lgtm - we  can iterate the messaging here as we develop

thanks @codefromthecrypt

**Pull request merged**
