### PR TITLE
http: remove runtime guard envoy.reloadable_features.no_chunked_encoding_header_for_304

### PR DESCRIPTION
**Pull request by boringuy**
Signed-off-by: Andy Fong <boringuy@gmail.com>

Commit Message: http: remove runtime guard envoy.reloadable_features.no_chunked_encoding_header_for_304 (#19508)
Additional Description:
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] #19508
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]  envoy.reloadable_features.no_chunked_encoding_header_for_304 runtime guard
[Optional [API Considerations]:]

### CODE REVIEW

**Comment by boringuy** [comment]
The build failed with this with not much detail:
`(good) api-v2/type/tracing/v2/custom_tag.proto.html --> api-v3/type/tracing/v3/custom_tag.proto.html
BUILD FAILED
Target //docs:html failed to build
INFO: Elapsed time: 253.583s, Critical Path: 98.56s
INFO: 1244 processes: 1174 remote cache hit, 69 internal, 1 processwrapper-sandbox.
##[error]Bash exited with code '1'.
Finishing: Generate docs
`
and it builds successfully locally for me. Can someone see if they can restart the build?

**Comment by boringuy** [comment]
Now that the build passed. Should I keep resolving the conflicts with new changes in main or wait until review is completed and do a single resolve?

**Review by KBaichoo — APPROVED** [review]
LGTM, can you merge please? Thanks!

**Comment by boringuy** [comment]
just merged the latest main into my branch. Waiting for test to finish.

**Pull request merged**
