### PR TITLE
deps: Update gRPC to version v1.40.0

### PR DESCRIPTION
**Pull request by yanavlasov**
Commit message:
Disable layering check in gRPC BUILD file to prevent build errors against Envoy's cmake dependencies.

Additional Description:
Bump to the first version that needed some changes to the dependencies. Next version needs more work, which is in progress.

Risk Level: Low
Testing: Unit Tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

Signed-off-by: Yan Avlasov <yavlasov@google.com>

### CODE REVIEW

**Comment by phlax** [comment]
headsup that current grpc version is 1.48

**Comment by yanavlasov** [comment]
> headsup that current grpc version is 1.48

We have failing tests due to changes in gRPC code starting with 1.41, which I'm trying to figure out. This may take some time and going to 1.40 is the best we can do at the moment.

**Comment by phlax** [comment]
yep, ive tried to update this a couple of times myself and hit similar issues

**Review by phlax — APPROVED** [review]
/lgtm deps

thanks @yanavlasov

**Pull request merged**
