### PR TITLE
build: Update ICU and googleurl

### LINKED ISSUE #12015: build: Update unicode-org/icu to the latest release
The current icu BUILD file is adapted from Tensorflow project, which is stable to use. However since org_unicode_icuuc has newer release, need to update it.

### PR DESCRIPTION
**Pull request by dio**
Commit Message: This patch updates ICU to 67.1 and googleurl to https://quiche.googlesource.com/googleurl/+/ef0d23689e240e6c8de4c3a5296b209128c87373. This reduces `bazel/external/googleurl.patch` to only handling MSVC quirks.

Please note that googleurl direction for Windows is to use clang-cl, while we still use msvc-cl (hence the patch). 

Risk Level: Low
Testing: Existing
Docs Changes: N/A
Release Notes: N/A
Fixes #12015

### CODE REVIEW

**Comment by dio** [comment]
@danzh2010 could you help to provide the googleurl static snapshot for https://quiche.googlesource.com/googleurl/+/ef0d23689e240e6c8de4c3a5296b209128c87373, please? Thank you!

**Comment by danzh2010** [comment]
Up loaded to
https://storage.googleapis.com/quiche-envoy-integration/googleurl_ef0d23689e240e6c8de4c3a5296b209128c87373.tar.gz
checksum: d769283fed1319bca68bae8bdd47fbc3a7933999329eee850eff1f1ea61ce176

**Comment by dio** [comment]
@lizan when you have time could you PTAL? Thanks!

**Pull request merged**
