### PR TITLE
Clean up version number and history following the v1.20.2 release

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
Leaves the branch ready for a potential subsequent v1.20.3 release.

Signed-off-by: Ryan Hamilton <rch@google.com>

### CODE REVIEW

**Review by mattklein123 — APPROVED** [review]

**Comment by rojkov** [comment]
The examples check went bitrotten in this and in all the other release branches, it seems. Should we merge it anyway?

**Comment by phlax** [comment]
there was some discussion offline about backporting the examples/verify fix

cc @daixiang0 as i think you are working on adding missing hashes to example pip deps, which should prevent this problem

**Pull request merged**
