### PR TITLE
Quiche roll 20220506110612

### PR DESCRIPTION
**Pull request by danzh2010**
Update QUICHE from a05cb99d0 to 3f73c4a23
    https://github.com/google/quiche/compare/a05cb99d0..3f73c4a23
    
    $ git log a05cb99d0..3f73c4a23 --date=short --no-merges --format="%ad %al %s"
    
    2022-05-09 danzh Internal change
    2022-05-06 birenroy Adds a test demonstrating that metadata is not sent if queued immediately before trailers.
    2022-05-06 vasilvv Move all of HTTP/2 test tools into http2/test_tools.
    2022-05-05 bnc Add missing QUICHE_EXPORT_PRIVATE at a few places.
    2022-05-05 quiche-dev Fixes for C++20 support.
    2022-05-05 haoyuewang Internal change
    2022-05-05 bnc Move IsInvalidHeaderKeyChar() from balsa_frame.cc anonymous namespace to header_properties.
    2022-05-05 vasilvv Merge third_party/http2/tools into third_party/http2/test_tools.
    2022-05-04 vasilvv Make packet_dropping_test_writer not depend on epoll-related code.
    2022-05-04 vasilvv Move SPDY test tools into //third_party/spdy/test_tools/...
    2022-05-04 bnc Use uint8_t instead of char for array indexing in quiche::header_properties.
    2022-05-04 vasilvv Fix QuicheBufferAllocatorTest
    2022-05-04 vasilvv Actually export quiche_file_utils test files.
    2022-05-04 quiche-dev Flip restart flags for staging and gfe-dev-co production locations.
    2022-05-04 bnc Use unsigned type as index for array.
    2022-05-04 bnc Change flags type in Http2FrameHeaderTypeAndFlagTest.
    2022-05-04 birenroy Uses uint8_t for an array index value.
    2022-05-04 bnc Pretty print Http2FrameHeaderTypeAndFlagTest params.
    2022-05-03 bnc Do not recalculate BalsaHeaders::iterator_base::value_ unless necessary.
    2022-05-03 fayang Log more info when retransmittable-on-wire deadline is in the past.
    2022-05-02 birenroy Adds a mode to HeaderValidator that accepts `obs-text`, and makes it the default for OgHttp2Session.
    2022-05-02 bnc Make BalsaHeaders::iterator_base and const_header_lines_iterator copy constructor implicit.
    2022-05-02 wub Deprecate --gfe2_restart_flag_quic_tls_server_support_client_cert.
    2022-05-02 bnc Remove header policy tests from public QUICHE.
    2022-05-02 dschinazi Add two vulnerable ports to QUIC blocked list
    2022-05-02 bnc Do not use old-style cast in balsa_frame_test.cc.
    2022-05-02 bnc Use EXPECT_QUICHE_BUG in BalsaHeadersTest.
    2022-05-02 bnc Remove http2_flags.h and http2_flag_utils.h.
    2022-05-02 bnc Fix signed-unsigned comparison.
    2022-05-02 wub Add three variants of selective resumption behavior, controlled by connection option 'GSR1', 'GSR2' and 'GSR3'.
    2022-05-02 bnc Remove http2_logging.h.
    2022-05-02 wub Pass TLS read/write secrets by absl::Span instead of a byte vector.
    2022-04-30 fayang Remove TLP and RTO retransmissions by deprecating gfe2_restart_flag_quic_default_on_pto2.
    2022-04-29 haoyuewang False deprecate --gfe2_reloadable_flag_quic_set_burst_token. The flag roll-back change cr/440139064 has been fully rolled out.
    2022-04-29 bnc Rename QuicheTest implementation to QuicheTestImpl.
    2022-04-28 wub Remove an unused parameter from quic::SerializeTransportParameters.
    2022-04-28 bnc Remove QuicGetTestMemoryCachePath().
    2022-04-28 bnc Remove empty quic_containers.h.
    2022-04-28 bnc Use QuicheSmallOrderedSet instead of QuicSmallOrderedSet.
    2022-04-28 bnc Remove quic_stream_buffer_allocator.h.
    2022-04-28 dschinazi Default-enable qbone_server_use_messages
    2022-04-28 haoyuewang Fix flaky EndToEndTest_LargeResponseBandwidthEstimate by: (1) Convert int32 bytes_pert_second to uint64 before converting it to bits_per_second. (2) Fix an error in BandwidthToCachedParameterBytesPerSecond for which an unsigned upper bound is incorrectly used.
    2022-04-28 bnc Remove http2_bug_tracker.h.
    2022-04-28 bnc Export balsa_frame_test.cc and balsa_headers_test.cc publicly.
    2022-04-28 bnc Do not use string_view_utils.h or stringpiece_ssize_type in balsa_headers.cc.
    2022-04-28 vasilvv Remove unnecessary QUIC_EXPORT directive.
    2022-04-28 bnc Remove GFE2-specific comments from Balsa.
    2022-04-27 bnc Use QUICHE_*LOG() in Balsa.
    2022-04-27 haoyuewang Internal change
    2022-04-27 bnc Make BalsaBuffer constructors public.
    2022-04-26 vasilvv Split out google3-specific bits of crypto_test_utils into //net/quic.
    2022-04-26 ericorth Prepare for toy QUIC CONNECT proxy server
    2022-04-26 bnc Add two QuicheMemSliceTests.
    2022-04-25 vasilvv Provide default Abseil-based implementation for QuicheStackTrace.
    2022-04-25 vasilvv Make QUICHE_EXPORT macros add default visibility attribute in google3.
    2022-04-25 vasilvv Improve ProofSourceX509 enough so that it can be used to run all of QUICHE unit tests.
    2022-04-25 quiche-dev Deprecate --gfe2_reloadable_flag_always_use_strict_header_names.
    2022-04-25 bnc Use identical argument names in declaration and definition for two BalsaHeaders methods.

Risk Level: low
Testing: existing tests pass
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Review by RyanTheOptimist — DISMISSED** [review]
Wow, that was a big one!

**Review by mattklein123 — DISMISSED** [review]

**Comment by bencebeky** [comment]
From passing presubmit on https://github.com/envoyproxy/envoy/pull/21213 but failing presubmit on https://github.com/envoyproxy/envoy/pull/21214 it seems like the culprit is https://github.com/google/quiche/commit/73a2457c60d2b6bc33e529acfbc41ceb9f972270.  I drafted https://github.com/envoyproxy/envoy/pull/21220 with a proposed solution and am waiting for presubmits to run.

**Comment by RyanTheOptimist** [comment]
Oh, that's interesting! That sounds plausible. Thanks for the fix in #21220! Should we land that PR, or merge it into this PR?

**Comment by danzh2010** [comment]
clang-tidy failure is a spurious one: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/./source/common/common/logger.h:15:10: error: 'source/common/common/logger_impl.h' file not found [clang-diagnostic-error]
#include "source/common/common/logger_impl.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

17193 warnings and 1 error generated.
Error while processing /source/source/common/quic/platform/quiche_stack_trace_impl.h.

Clang-tidy fails to understand strp_include_prefix magic.

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by RyanTheOptimist** [comment]
> clang-tidy failure is a spurious one: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/./source/common/common/logger.h:15:10: error: 'source/common/common/logger_impl.h' file not found [clang-diagnostic-error] #include "source/common/common/logger_impl.h" ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 17193 warnings and 1 error generated. Error while processing /source/source/common/quic/platform/quiche_stack_trace_impl.h.
> 
> Clang-tidy fails to understand strp_include_prefix magic.

I think we've seen this before:
https://envoyproxy.slack.com/archives/G79D81J7Q/p1647619041791919
@mattklein123 can you for submit through this?

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
