### PR TITLE
Update QUICHE from 4506f8d26 to 4d58dae4e

### PR DESCRIPTION
**Pull request by ericorth**
https://github.com/google/quiche/compare/4506f8d26..4d58dae4e

```
$ git log 4506f8d26..4d58dae4e --date=short --no-merges --format="%ad %al %s"

2023-06-06 danzh Make QuicConnection to do reverse path validation based on IETF version instead of bool validate_client_addresses_.
2023-06-06 vasilvv Remove WebTransport version header check on the server side.
2023-06-05 quiche-dev Fixes for third party anonymous tokens directory that allow all tests to pass with bazel which will lead to test coverage in the github repo.
2023-06-05 quiche-dev Update phosphor and token spend apis to expose and accept binary public metadata
2023-06-05 martinduke ECN support for several QuicPacketWriter implementations.
2023-06-05 vasilvv Replace uses of std::function inside QUICHE.
2023-06-05 vasilvv Switch uses of std::function to QUICHE callback aliases as appropriate.
2023-06-05 renjietang Add a test on multi-port path receiving stateless reset.
2023-06-02 quiche-dev Remove second QUICHE_EXPORT for SignatureChanger
2023-06-02 danzh Document about deprecation of QUIC connection option RVCM.
2023-06-02 danzh Remove quic connection option `RVCM` everywhere given IETF style connection migration is no longer guarded by it since cl/527045730.
2023-06-02 martinduke QUIC v2 has been published as RFC 9369. Rename all identifiers from "v2 draft 08" to "rfc v2". No behavior change. Also renames the not-enabled flag gfe2_reloadable_flag_quic_enable_version_2_draft_08 to gfe2_reloadable_flag_quic_enable_version_rfcv2.
2023-06-01 quiche-dev Fix test failures in CryptoUtilsTest
2023-06-01 haoyuewang Let RecordingProofVerifier use the underlying verifier_ (if not null) to VerifyCertChain.
2023-05-31 vasilvv Replace uses of std::function with quiche::UnretainedCallback where appropriate
2023-05-31 junyer Update Quiche to RE2 release `2023-06-01`.
2023-05-31 quiche-dev Use ANON_TOKENS_ASSERT_OK_AND_ASSIGN in crypto_utils_test.cc
2023-05-31 vasilvv Fix stand-alone QUICHE build
2023-05-30 quiche-dev Function that DER-encodes the public key of RSA Blind Signature - Probabilistic Signature Scheme algorithm.
2023-05-30 quiche-dev Add `--ignore_errors` option to quic_client.
2023-05-30 vasilvv Create quiche_callbacks.h
2023-05-30 birenroy Adds a basic fuzzer for Http2DecoderAdapter.
2023-05-30 birenroy Adds a basic fuzzer for Http2FrameDecoder.
2023-05-25 danzh Add QUIC connection options `MCS1`, `MCS2` and `MCS3` to adjust GFE allowed max concurrent streams.
2023-05-25 birenroy Validates request paths according to RFC 3986 Section 3.3.
2023-05-25 birenroy Adds HeaderValidator unit tests for valid and invalid path characters.
2023-05-25 birenroy Adds a unit test demonstrating that oghttp2 will accept request paths with space or tab.
```

Risk Level: Low
Testing: Existing tests pass
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
Looks like real test failures:

```
//test/integration:quic_protocol_integration_test                        FAILED in 8 out of 12 in 138.9s
...
[2023-06-06 20:05:30.013][55][error][envoy_bug] [source/common/http/filter_manager.cc:1289] envoy bug failure: false. Details: Invalid response data
```

**Comment by ericorth** [comment]
Timeouts in a couple tests like //test/integration:quic_protocol_integration_test and still occurring locally on my machine after a merge from upstream, so this seems like a real failure.  I'll try to figure this out, but if anybody more familiar than me with these integration tests also wants to take a look, that would be appreciated.

**Comment by ericorth** [comment]
And timeout still occurs if I go and change the timeout to five minutes.  So something is actually broken here, not just slow.  I'm going to play with bisecting the QUICHE changes and see where things go wrong.

**Comment by ericorth** [comment]
Winner is https://github.com/google/quiche/commit/3c69c2dab5eac964d15286bbef4732eab320752d, which adds additional validation for allowed path characters.  Failing test is one messing with URI fragments in the path header, which uses a '#' character which is now a disallowed path character, so I'll bet that's getting treated as an invalid path character and doing something the test doesn't expect like abrupt termination.  Not sure though how QUICHE or Envoy expect to deal with fragments.

I'm signing off for the day and will continue looking at this tomorrow.

**Comment by ericorth** [comment]
Determined that the added path validation in that QUICHE change results in Envoy doing a stream reset when http2 receives a request with such an invalid path, including URI fragments in path ("some/path#fragment").  This is the correct behavior, to my understanding of the RFCs.  But per the logic added to Envoy in https://github.com/envoyproxy/envoy/commit/90f16e3f38a0e41ea8f23b585e41c18721dcb203, Envoy expects to either return HTTP 400 for such fragment-in-path requests or strip the fragment out and continue.  Thus the test failure on the changed behavior.  We're figuring out a fix in QUICHE to allow Envoy to keep doing what it wants to do, and will have to pick this PR back up or create a new one once that fix is ready.

**Comment by KBaichoo** [comment]
/wait

Seems like this is pending QUICHE changes / might be closed in lieu of a another update PR.

**Comment by RyanTheOptimist** [comment]
I think this has been overtaken by the most recent QUICHE merge, so I'll go ahead and close this one.

**Pull request closed without merging**
