### PR TITLE
jwt_authn: make from_cookies JWT removal behaviour similar to from_params

### PR DESCRIPTION
**Pull request by theshubhamp**
jwt_authn: make from_cookies JWT removal behaviour similar to from_params

Removal of params or cookies after authentication is not implemented as of today.

authenticator.cc calls the removeJwt(...) if forward is set to false (default)
and this leads to an assertion failures caused by NOT_IMPLEMENTED_GCOVR_EXCL_LINE.

Changed removeJwt(...) for JwtCookieLocation to be empty, added test coverage
and updated proto doc to call-out this caveat.

Risk Level: Low
Testing: Tests
Docs Changes: Added caveat to proto docs.
Release Notes: None.
Platform Specific Features: None

Follow up for #17424

Signed-off-by: Shubham Patil <theshubhamp@gmail.com>

### CODE REVIEW

**Comment by theshubhamp** [comment]
cc @lizan, PTAL whenever you can!

**Comment by theshubhamp** [comment]
Ping! Can someone review this PR ?

**Comment by qiwzhang** [comment]
First commit is good.  The second one after the merge seems getting a lot of unrelated changes. Please fix it.

**Comment by theshubhamp** [comment]
Thanks for taking a look! 

> The second one after the merge seems getting a lot of unrelated changes. Please fix it.
The second commit shows unrelated changes because it is a merge commit. I had to merge `main` back into this branch to resolve conflicts (in `generated_api_shadow` which was removed on main recently)

Actual changes are only in 3 files and only those should end up on main as a single commit after merge.

**Comment by qiwzhang** [comment]
LGTM

**Review by lizan — APPROVED** [review]

**Pull request merged**
