### PR TITLE
alpha matching: support generic action factory context

### PR DESCRIPTION
**Pull request by snowp**
Prior to this PR the MatchTreeFactory required a FactoryContext in
order to pass this to the action factories. This is not available in all
contexts, and there are other possible use cases where we might need
to pass additional information to the match tree factory (e.g. the
router might need to pass the parent vhost configuration).

This PR introduces a parametrized action context, allowing each usage of
the MatchTree to define its own data that should be presented to the
action factories. This also has the nice benefit of partitioning the
action factories per context: each unique ActionFactoryContext defines a
new factory type, ensuring that actions defined for a HTTP filter
context won't be conflated with actions defined for another context.

Signed-off-by: Snow Pettersen <snowp@lyft.com>

Risk Level: Medium
Testing: Existing tests
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by snowp** [comment]
cc @aguinet, this will change the match interface again somewhat if this lands before your PRs

**Comment by aguinet** [comment]
Thanks for the heads up @snowp ! I'll keep an eye on it!

**Comment by alyssawilk** [comment]
@snowp want me to find another reviewer or does it make sense to wait until Matt gets back?

**Review by mattklein123 — APPROVED** [review]
Makes sense to me!

**Comment by paul-r-gall** [comment]
Hi, I think this PR broke this extension: https://github.com/envoyproxy/envoy/blob/6cd6a0cab68c757c785e62e0d73d881f57c97839/source/extensions/matching/input_matchers/ip/config.h#L20

**Comment by mattklein123** [comment]
I'm looking into fixing, but it's not so easy and @snowp is out so I'm just going to revert this and let him fix.

**Comment by mattklein123** [comment]
https://github.com/envoyproxy/envoy/pull/17191

**Pull request merged**
