### PR TITLE
WiP stats: Force enable stats

### LINKED ISSUE #14051: stats: prevent disabling some stats
*Description*:
>Some stats can potentially be used for functional purposes during operation. However, the fact that they can be disabled via a stats matcher expression makes that an anti-pattern currently. We should have a mechanism to mark a stat as being immune from disabling. Since the disabling happens during stat instantiation, this would need to occur during stat construction.

*Relevant Links*:
> https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/stats.proto#config-metrics-v3-statsmatcher

### PR DESCRIPTION
**Pull request by jmarantz**
Commit Message: Adds a creation-mode enum to methods to construct stats. The enum includes a ForceEnable which makes a stat ineligible for exclusion via a StatsMatcher configuration. This in turn allows for use of stats functionally during operation in the proxy.
Additional Description: We are debating whether this added complexity is worth the benefit, but maybe it makes sense just to open it up for review. I'm OK leaving this on hold until there's a compelling use-case.
Additional Description: See https://docs.google.com/document/d/1CnyeIi5hMBqXZRKm-0_yW3yy69HM80BHg-EGwkJb-qw/edit?usp=sharing for a more detailed discussion.
Risk Level: low 
Testing: //test/...
Docs Changes: needed before submitting, as we should describe in the StatsMatcher doc that the intent can be overridden by functional needs.
Release Notes: n/a
Platform Specific Features: n/a
Fixes #14051

### CODE REVIEW

**Comment by mattklein123** [comment]
@jmarantz I think we should have a discussion on whether we want to do this at all. I'm of 2 minds here. One hand I think it's pragmatic as there may be significant duplication if we assume we can never use stats for logic. On the other hand it feels pretty hacky.

@envoyproxy/maintainers any thoughts on this?

**Comment by jmarantz** [comment]
I'm ok either way... It is mostly working but it is just another layer of hack.

**Comment by jmarantz** [comment]
@mattklein123 this is mostly ready to go if we decide it makes sense to proceed. I will update doc if it looks like we want to go in that direction, but I think the code is mostly in shape now.

**Comment by mattklein123** [comment]
My thinking is to put this on hold unless we have a use case we know we want to do? I know there are open issues with features not working because of this underlying issue, but I'm not sure if we should just fix them or go down this path. Would definitely like to hear from others on this.

**Comment by jmarantz** [comment]
Sgtm

**Comment by mattklein123** [comment]
@jmarantz wdyt about putting together a short doc on our options for dealing with this issue that we can circulate? I think we probably need to go through a design phase for this one?

/wait

**Pull request closed without merging**
