### PR TITLE
Range utils

### PR DESCRIPTION
**Pull request by capoferro**
(Formerly https://github.com/envoyproxy/envoy/pull/17872)

Commit Message: Move range logic into range utils and remove range-specific statuses from CacheEntryStatus
Risk Level: Low (refactor)
Testing: Existing

### CODE REVIEW

**Comment by capoferro** [comment]
mklein attempted to reopen #17872, but Github said no. Here's a new PR with the same content and commit history.

**Review by jmarantz — COMMENTED** [review]
Can someone on the caching team be assigned to review this for caching semantics first and then I'll do a maintainer pass? 

Thanks!

**Comment by jmarantz** [comment]
Oh...I guess the source of this PR was reviewed by @RyanTheOptimist -- I think he can actually finish the review then?

**Review by RyanTheOptimist — APPROVED** [review]
As the PR description states, this is the same content as #17872 which I previously approved, so approving again :) @jmarantz, it might still be worth having someone from the caching team take a look?

**Comment by capoferro** [comment]
@penguingao would probably be the next choice after me for cache team review.

**Comment by penguingao** [comment]
This LGTM.

**Review by snowp — APPROVED** [review]
Thanks!

**Pull request merged**
