### PR TITLE
tracer: fix skywalking layer always shows unknown

### PR DESCRIPTION
**Pull request by zirain**
Commit Message: fix skywalking layer always shows unknown
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by wbpcode — APPROVED** [review]
Although the tracer maybe used by other protocols, but, anyway, HTTP is better than unknow. So I am OK to this change for now.

**Comment by zirain** [comment]
> Although the tracer maybe used by other protocols, but, anyway, HTTP is better than unknow. So I am OK to this change for now.

I asked @wu-sheng, he's OK with this change.

**Comment by wbpcode** [comment]
oh, retest didn't work. Could you kick the CI by an empty commit? Thanks.

/wait

**Comment by zirain** [comment]
> oh, retest didn't work. Could you kick the CI by an empty commit? Thanks.
> 
> /wait

I kicked it with merge main, but seem not working, @phlax can you take a look?

**Comment by wu-sheng** [comment]
> Although the tracer maybe used by other protocols, but, anyway, HTTP is better than unknow. So I am OK to this change for now.

HTTP is used for HTTP 1.x and HTTP2(gRPC included).

**Comment by phlax** [comment]
ci kicked

**Comment by wbpcode** [comment]
> > Although the tracer maybe used by other protocols, but, anyway, HTTP is better than unknow. So I am OK to this change for now.
> 
> HTTP is used for HTTP 1.x and HTTP2(gRPC included).

We have dubbo, and various private protocols. But it's OK for me for now. :)

**Comment by zirain** [comment]
kindly ping @wbpcode

**Pull request merged**
