### PR TITLE
http2: merges identical implementations of ConnectionImpl::trackInboundFrames()

### PR DESCRIPTION
**Pull request by birenroy**
Hoists (Client|Server)ConnectionImpl::trackInboundFrames() to the base class, since they are identical.

Commit Message: http2: merges identical implementations of ConnectionImpl::trackInboundFrames()
Additional Description:
Risk Level: none
Testing: ran unit and integration tests locally
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Review by diannahu — APPROVED** [review]
Nice merging!

**Comment by RyanTheOptimist** [comment]
Is this a failure from this PR? https://dev.azure.com/cncf/envoy/_build/results?buildId=160816&view=logs&jobId=8bf29878-a4cc-50f7-4e84-2255e6fd4065&j=8bf29878-a4cc-50f7-4e84-2255e6fd4065&t=150a3762-112b-5713-0d28-af1eb6c2fbf4

**Review by RyanTheOptimist — APPROVED** [review]
This sure looks like a no-op and a nice cleanup! I'm curious about the test failure though.

**Comment by birenroy** [comment]
That test passes locally, so I'm guessing it's a flake.

/retest

**Pull request merged**
