### PR TITLE
Parameterized SocketOptionTestHarness with IPVersion.

### PR DESCRIPTION
**Pull request by kmyerson**
Signed-off-by: Kyle Myerson <kmyerson@google.com>

tests: Parameterized SocketOptionTestHarness with IPVersion.

SocketOptionTestHarness previously assumed IPv4, which causes tests to fail in an Ipv6 only environment. This change updates SocketOptionTestHarness to respect ENVOY_IP_TEST_VERSIONS.

Risk Level: Low

### CODE REVIEW

**Comment by mattklein123** [comment]
@kmyerson can you check the coverage build?

**Comment by kmyerson** [comment]
@mattklein123 Yes, I'm looking into it now :) sorry about that.

**Comment by kmyerson** [comment]
The root cause of the coverage build breakage was that the tests depended on MockListenSocket::fd() returning 0 by default, which worked when running the test normally, but not in the coverage build. #3232 goes into.

**Comment by kmyerson** [comment]
Looks like its passing now :D , @mattklein123 could you PTAL?

**Pull request merged**
