### PR TITLE
kafka: add missing unit tests

### PR DESCRIPTION
**Pull request by adamkotwasinski**
Commit Message: kafka: add missing unit tests
Additional Description: missing coverage for kafka serialization code
Risk Level: Low
Testing: unit tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by adamkotwasinski** [comment]
Ready for review

**Comment by moderation** [comment]
I'm hijacking into this PR but any thought to bumping the Kafka deps?
- https://github.com/apache/kafka now at 2.6.0
- https://github.com/dpkp/kafka-python now at 2.0.2
- https://mirrors.gigenet.com/apache/kafka/2.6.0/

**Comment by adamkotwasinski** [comment]
@moderation good idea, I'll try to do that after (unrelated) mesh-filter work; gonna take some time there first though...

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
