### PR TITLE
stats: Remove Scope's counter(), gauge(), and histogram() interfaces, renaming them to counterFromString et al.

### PR DESCRIPTION
**Pull request by jmarantz**
Description: There were no longer any production calls to those methods, but there are test-calls. It is still valid to call them in a test that uses a Stats::TestUtil::TestStore, which also takes care of making that work regardless of whether they are matching production stats that were created with dynamic segments.

There are still a few calls in tests to Scope::counter() etc, and those had to be changed to Scope::counterFromString() etc.

Note that this changes an interface which may be called from outside Envoy's source control, and will require some renaming or refactoring there, outside this PR

Risk Level: primary risk is calls to those APIs outside of this repo; those will all have to be changed.
Testing: //test/...
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by jmarantz** [comment]
@snowp friendly ping

**Comment by jmarantz** [comment]
@mattklein123 do you want to take a pass?

**Comment by mattklein123** [comment]
Oops sorry looks like you need a master merge.

/wait

**Comment by jmarantz** [comment]
i think this is ready for another look; clang-tidy passing now.

**Pull request merged**
