### PR TITLE
comptiable with openmetrics that removing blank line on prometheus metrics 

### PR DESCRIPTION
**Pull request by Patrick0308**
Signed-off-by: 白泽 <patrickjiang0530@gmail.com>

Commit Message:
Additional Description: comptiable with openmetrics that removing blank line on prometheus metrics 
Risk Level: Low
Testing: Unit Tests
Docs Changes: None
Release Notes: Added
Platform Specific Features:

### CODE REVIEW

**Comment by zuercher** [comment]
Is this change compatible with existing prometheus collectors?

There appear to be other tests that check for the newline you removed.

**Comment by Patrick0308** [comment]
@zuercher Yes, it's compatible. It just remove blank line.

**Comment by phlax** [comment]
related #22130

**Comment by Patrick0308** [comment]
On istio if app's metrics is openmetrics  pilot-agent will process envoy metrics to remove blank line and merge with app's metrics. This is not good for performance. https://github.com/istio/istio/blob/1aca7a67afd7b3e1d24fafb2fbfbeaf1e41534c0/pilot/cmd/pilot-agent/status/server.go#L494

**Review by zuercher — APPROVED** [review]

**Review by zuercher — APPROVED** [review]

**Pull request merged**
