### PR TITLE
quiche: update QUICHE DEPS

### PR DESCRIPTION
**Pull request by RenjieTang**
Signed-off-by: Renjie Tang <renjietang@google.com>

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]
LGTM!

**Comment by alyssawilk** [comment]
Hm, looks like CI needs a look?
/wait

**Comment by RyanTheOptimist** [comment]
> Hm, looks like CI needs a look?
> /wait

Ah! @RenjieTang this is the result of a QUICHE change I landed:
```
Execution platform: @rbe_ubuntu_clang_libcxx//config:platform
source/extensions/filters/http/alternate_protocols_cache/filter.cc:58:71: error: no member named 'max_age' in 'spdy::SpdyAltSvcWireFormat::AlternativeService'
          time_source_.monotonicTime() + std::chrono::seconds(alt_svc.max_age);
```
You'll need to change max_age to max_age_seconds.

@alyssawilk, if this PR lands before https://github.com/envoyproxy/envoy/pull/18189 then you'll need to make the corresponding change there too.

**Comment by RyanTheOptimist** [comment]
> @alyssawilk, if this PR lands before #18189 then you'll need to make the corresponding change there too.

Ah! That just landed. So @RenjieTang you'll need to to a merge, and make the another max_age => max_age_seconds change.

**Review by alyssawilk — APPROVED** [review]
LGTM, though this may need a main merge to fix the coverage flake.
@yanavlasov if this passes with retest or main can you merge for me later today?
/retest

**Comment by RyanTheOptimist** [comment]
@moderation can you re-approve for deps

**Pull request merged**
