### PR TITLE
config: ensure Config::Utility::getAndCheckTransportVersion is called on main thread.

### PR DESCRIPTION
**Pull request by htuch**
During the v2 -> v3 migration, some uses of this were added inside filter factory lambdas and could
occur on worker threads, rejecting config on the data plane.

Relevant to #10943
Fixes https://github.com/envoyproxy/envoy/issues/15083

Risk level: Low
Testing: New assertion in method caused existing tests to fail, fix addresses these. Also manually
  audited via grep.

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

**Review by mattklein123 — DISMISSED** [review]
Thanks!

**Comment by mattklein123** [comment]
@htuch I think this needs a main merge, there is a conflict.

/wait

**Comment by htuch** [comment]
@jmarantz `filter_fuzz_test` keeps flaking on a symbol table ASSERT in `linux_x64 gcc`, see https://dev.azure.com/cncf/envoy/_build/results?buildId=69835&view=logs&j=8bf29878-a4cc-50f7-4e84-2255e6fd4065&t=3267cd16-a387-57e0-0ef4-d7a4d1c6c089. This seems totally unrelated to this change, but keeps popping up when I kick CI. Any thoughts?

**Comment by jmarantz** [comment]
Which assert? I didn't see any obvious assert logs when I clicked through
that link.

My first guess it that something in the test is allowing a SymbolTable
while some of the stats are still being referenced.

**Comment by jmarantz** [comment]
Also there are several filter_fuzz_test targets in the hierarchy. Which one
is failing for you?

**Comment by htuch** [comment]
@jmarantz https://dev.azure.com/cncf/envoy/_build/results?buildId=69835&view=logs&j=888abee3-c02a-5003-35d7-00d8a08073af&t=56bc2ef4-1c05-5cf3-f47e-10b7657dd6c5&l=13241 (this time with line numbers)

**Comment by jmarantz** [comment]
That assert is just saying that there are outstanding symbols when the symbol table was destructed. The stack-trace tells us that the symbol-table was being destructed from the factory-context.

Is it possible that that this test was flaking with or without this PR's changes?

**Comment by jmarantz** [comment]
Is it possible that the fuzz test is holding onto a reference to a stat in a thread that persists pass the destruction of the factories?

**Comment by htuch** [comment]
The only test that I can believe might be affected is the rate limit HTTP filter, since this is an HTTP filter fuzz test. The change there seems innocuous. @asraa for an extra pair of eyes. I'll get it replicating and go deeper as next step.

**Comment by asraa** [comment]
> The change there seems innocuous. @asraa for an extra pair of eyes. 

About this and lifetime, can you repro it locally? 
Trying to brainstorm... the filters are destroyed at the end of fuzz iteration, so I'd be skeptical if Rate limit filter was holding on to some stats.

ACTUALLY (fortunately i procrastinated pressing comment)! maybe something is exiting early from `fuzz` and not running that `reset()` I just mentioned above
https://github.com/envoyproxy/envoy/blob/1d1b708c7bf6efa02c41d9ce22cbf1e4a1aeec2c/test/extensions/filters/http/common/fuzz/uber_filter.cc#L89

what if you try adding a reset in the try/catch early return or adding it to the filter fuzzer destructor?

**Comment by htuch** [comment]
@asraa why is https://github.com/envoyproxy/envoy/blob/main/test/extensions/filters/http/common/fuzz/filter_fuzz_test.cc#L53 setup for persistence? I think for the unit test style fuzzers (rather than e2e ones), we would be better off with non-persistence if possible to allow earlier detection of these issues. I can repro locally and digging further into this one.

**Comment by jmarantz** [comment]
Also that's a non-pod-static violation, fwiw.

**Comment by htuch** [comment]
Well, the good news is I have a fix, the bad news is I don't understand why it works; see https://github.com/envoyproxy/envoy/pull/15548/commits/1e1ac2a7b8928860cc8b6a2e4f50512f379f8fb2. Basically, `filter_config` (a shared pointer) seems to be sensitive to the exception after having its reference count bumped for the lambda capture. I'm not sure what I'm missing here around behavior of lambda capture, initializer and exceptions, but it seems kind of magical.

**Comment by mattklein123** [comment]
> Well, the good news is I have a fix, the bad news is I don't understand why it works; see 1e1ac2a. Basically, filter_config (a shared pointer) seems to be sensitive to the exception after having its reference count bumped for the lambda capture. I'm not sure what I'm missing here around behavior of lambda capture, initializer and exceptions, but it seems kind of magical.

I'm no expert but I think lambda captures are not deterministic (C++ sigh), so I think the way to make it deterministic is to pre-capture into a struct and then pass that. I know @lambdai has been fixing similar issues so might be worth doing that here?

**Comment by htuch** [comment]
Still not sure how that relates though; even if non-deterministic, if we take the ref count, it should safely destruct presumably and decrement, if we don't take it then there should not be an issue.

**Comment by mattklein123** [comment]
> Still not sure how that relates though; even if non-deterministic, if we take the ref count, it should safely destruct presumably and decrement, if we don't take it then there should not be an issue.

Honestly I think you are hitting a compiler bug. Given that lambda capture order is not deterministic I would probably just switch to a struct anyway and be done with it, but up to you.

**Comment by asraa** [comment]
> @asraa why is https://github.com/envoyproxy/envoy/blob/main/test/extensions/filters/http/common/fuzz/filter_fuzz_test.cc#L53 setup for persistence?

MIssed this but worth the comment: this class just contains mock objects that could persist (and state's meant to be reset at the end for this class) for speed reasons.

**Pull request merged**
