### PR TITLE
protodoc: Fix aspect and speedup api/rst build

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
closing this in favour of #21579

**Comment by phlax** [comment]
given that we are keeping aspects, i think this change is desirable

**Comment by phlax** [comment]
cc @htuch i think it would be good to get this one out of the way - its a pretty straight fix to expectation

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
