### PR TITLE
fuzz: reactivate xds_fuzz_test

### PR DESCRIPTION
**Pull request by samflattery**
Signed-off-by: Sam Flattery <samflattery@google.com>

Commit Message: Reactive xds_fuzz_test
Additional Description:

- passes locally with `--config=clang-tsan --runs_per_test=1000` without tsan failures

Risk Level: low
Testing: passes
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by samflattery** [comment]
Failing `lua_filter_test` but passes locally on `--runs_per_test=100`, might be flaky?

**Comment by asraa** [comment]
I tried lua_filter_test for 2000 runs locally and it passed :( I think there's something odd about arm64 builds, because the flake doesn't repro on my x64 machine.

**Comment by samflattery** [comment]
Is this a known flake?

**Comment by asraa** [comment]
Not that I saw on issues -- although I do keep seeing arm64 flakes in other places as well, let's see if this fails on CI now and make an issue about it if it does. I believe it was ImportPublicKey that failed

**Comment by samflattery** [comment]
Sure sounds good!

**Comment by samflattery** [comment]
@asraa arm seems to be passing now

**Pull request merged**
