### PR TITLE
repo: Release 1.25.0

### PR DESCRIPTION
**Pull request by KBaichoo**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by KBaichoo** [comment]
google apt is failing in the examples, I __think__ it's a transient failure. 

/retest

**Comment by phlax** [comment]
@KBaichoo ive added a PR (to this one) with some cleanups here https://github.com/KBaichoo/envoy/pull/475 - and a pr to test it #24989

**Review by phlax — APPROVED** [review]
lgtm, thanks @KBaichoo

**Pull request merged**
