### PR TITLE
Revert "Add createPath to Filesystem abstraction (#26609)"

### PR DESCRIPTION
**Pull request by phlax**
This reverts commit 7b18ae855ab2605234420d85b5d6e3ada808ff55.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by Augustyniak — APPROVED** [review]
Approving since it's a simple revert and it fixes Envoy Mobile CI.

**Comment by phlax** [comment]
lets wait on a nod or better fix from @ravenblackx before landing

**Comment by ravenblackx** [comment]
... or, now that I've looked into it more, looks like hopefully it will be just revert the revert with no changes, after the mobile CI environment is updated. Unless it's intentionally supporting old versions.

**Pull request merged**
