### PR TITLE
[1.17] apple dns: fix crash on invalid dns name (#16028)

### PR DESCRIPTION
**Pull request by dmitri-d**
Cherry-pick of https://github.com/envoyproxy/envoy/pull/16028

### CODE REVIEW

**Comment by junr03** [comment]
This diff can still crash. This is the final patch: https://github.com/envoyproxy/envoy/pull/16369

**Comment by dmitri-d** [comment]
Cherry-picked https://github.com/envoyproxy/envoy/pull/16369 instead of the original https://github.com/envoyproxy/envoy/pull/16028

**Review by junr03 — APPROVED** [review]

**Pull request merged**
