### PR TITLE
typo in envoyproxy_io_proxy_http3_downstream.yaml

### PR DESCRIPTION
**Pull request by nwtgck**
Thank you so mush for great project! I fixed a simple typo.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by giantcroc** [comment]
Hi, I think you should add "signed off", just do like in [envoy support](https://github.com/envoyproxy/envoy/blob/main/support/README.md#support-tools).

**Review by phlax — APPROVED** [review]
Thanks for correction @nwtgck

**Comment by phlax** [comment]
@nwtgck just realized you need to fix DCO - see here for more info https://github.com/envoyproxy/envoy/pull/19610/checks?check_run_id=4868707405

**Comment by phlax** [comment]
@nwtgck if you can fix DCO we can land this

/wait

**Comment by nwtgck** [comment]
Thank you for the wait. I made another PR which is the same content: https://github.com/envoyproxy/envoy/pull/19690.

**Pull request closed without merging**
