### PR TITLE
dns cache: time to resolution histogram

### PR DESCRIPTION
**Pull request by junr03**
Commit Message: add time to resolution histogram to get information about dns cache behavior.
Additional Description:
Risk Level: low. New metric on already existing functionality.
Testing: pending
Docs Changes: pending
Release Notes: pending

### CODE REVIEW

**Comment by junr03** [comment]
@goaway I opened a draft to propose an approach but open to ideas of what measurement would be most useful. Right now the histogram would aggregate all resolutions (i.e., for different urls). This might be enough to gauge behavior. Other ideas I had were:
- distinguish between first resolution and subsequent resolutions
- distinguish between different URLs

cc @DavidSchinazi

**Comment by DavidSchinazi** [comment]
Nice! Do we support both IPv4 and IPv6 resolutions? If we do we could split the stats by IP address family?

**Comment by goaway** [comment]
Can we count cache hits and misses? (Are only misses captured here?)

**Comment by junr03** [comment]
@DavidSchinazi and @goaway I somehow missed that you commented here:

> Nice! Do we support both IPv4 and IPv6 resolutions? If we do we could split the stats by IP address family?

@DavidSchinazi Yes, we support both. I could split them.

> Can we count cache hits and misses? (Are only misses captured here?)

@goaway This effectively measures only cache misses, i.e., when the DNS resolver actually had to contact a dns server and get IP addresses for a hostname. I am not sure we are particularly interested in timing hits, wdyt?

**Comment by goaway** [comment]
With respect to timing, I think only recoding lookups (i.e. cache misses) is fine. I do think it would still be interesting to count cache misses and hits.

**Comment by jmarantz** [comment]
Looks pretty straightforward; ping when out of draft mode.

/wait

**Comment by alyssawilk** [comment]
Just to be aware, we've been making some improvements to Envoy tooling for more prompt reviews, but draft PRs are not included in the tooling.  I'm updating the contribution guidelines to make that clear (https://github.com/envoyproxy/envoy/pull/17063/files) , but as this PR predates the repokitteh warning I just want to call out that draft PRs are likely not going to get fast turnaround. Please consider marking this as ready for review if it stalls, and you want the assignee to take a look!

**Comment by junr03** [comment]
closing for now until we reprioritize

**Pull request closed without merging**
