### PR TITLE
gzip: drop deprecated filter

### PR DESCRIPTION
**Pull request by rojkov**
Commit Message: gzip: drop deprecated filter
Additional Description:
The HTTP Gzip filter has been disabled in v1.17 by default. Now we can remove it completely. Also the code common for the gzip filter and for the generic compressor filter is moved to `source/extensions/filters/http/compressor`.

Risk Level: Low
Testing: unit tests
Docs Changes: removed the page about the Gzip filter
Release Notes: added a note about the removal to current.rst

### CODE REVIEW

**Comment by rojkov** [comment]
I guess this PR should wait until API v2 is completely dropped to make the API check pass.

**Comment by htuch** [comment]
@rojkov you can't delete protos from the APIs, even after the v2 turndown. But you can remove proxy-side support.

**Comment by rojkov** [comment]
@htuch I put all the protos back (v2 and v3), but now protodoc is failing when I run `./docs/build.sh` with "Did you forget to add 'envoy.filters.http.gzip' to source/extensions/extensions_build_config.bzl?"

Should I put an empty `BUILD` as a stub for the removed extension?

**Comment by htuch** [comment]
@rojkov this is probably the first time we've removed an extension that still has API coverage. @phlax could you help @rojkov with this one? I feel this belongs in the docs ownership wheelhouse ;-)

**Comment by phlax** [comment]
hi @rojkov 

> I guess this PR should wait until API v2 is completely dropped to make the API check pass.

i have just started working on that here #16077 - although im not sure how quickly it will land

**Comment by rojkov** [comment]
@phlax Thanks! No hurry, it's a tech debt PR.

**Comment by phlax** [comment]
> now protodoc is failing  ... Should I put an empty BUILD as a stub for the removed extension?

im not sure exactly how best to keep the proto files around but not include them (mho is that they should be removed as historical versions of the repo still contain them)

how they would be kept *before* they should be included is by adding a `not-implemented-hide` annotation - might work - not sure what the post-deprecation policy is for these yet

**Comment by phlax** [comment]
@rojkov im not totally understanding - is gzip support removed completely?

there is a pr here #16440 to demonstrate gzip usage which i had approved - im wondering if this pr makes it obsolete

**Comment by phlax** [comment]
ah wait i see - there is still a gzip extension - its just been removed from http.filters - ill check the pr again for compat

**Comment by rojkov** [comment]
@phlax gzip support (through the generic compressor filter) is still there. This PR removes the old gzip filter, deprecated long time ago.

**Comment by phlax** [comment]
got it - thanks - seems like the pr should be gtm - ill merge it now

**Comment by rojkov** [comment]
@markdroth Could you please have a look? This PR seems to be ready for review.

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
