### PR TITLE
build: Update RBE toolchain config with 8Mb stack ulimit

### LINKED ISSUE #16196: gcc build is failing for test targets that depend on //source/exe:envoy_common_lib
The //source/exe:envoy_common_lib target builds all extensions and as a result creates a huge list of virtual include paths to each extension directory (which by themselves are also long).
In this case gcc fails to spawn its frontend:

`gcc: fatal error: cannot execute ‘/usr/lib/gcc/x86_64-linux-gnu/9/cc1plus’: execv: Argument list too long`

As a short term solution the three test targets have been modified to depend on the //source/exe;envoy_common_with_core_extensions_lib which only includes core extensions. Two tests in question do not need all extensions, and one is enough to test on clang.

Going forward I'm engaging with the bazel team to see how this can be addressed.
Plan B is to ask RBE team to increase `ulimit -s` on RBE VMs.

### PR DESCRIPTION
**Pull request by yanavlasov**
Increase ulimti -s to 8Mb to allow large command lines for gcc.

Fixes #16196

Signed-off-by: Yan Avlasov <yavlasov@google.com>

### CODE REVIEW

**Comment by yanavlasov** [comment]
This actually still not working. Figuring out why

**Comment by phlax** [comment]
@yanavlasov not sure if it will fix anything but can you also update the container hashes

see 22351ae2574a0e3b6ba7d48f1653ba4c6659da70 for example of what else needs to update

**Comment by yanavlasov** [comment]
Well, we did not change build container images. There are actually no new images in the repo. The last tag is 55d9e4719d2bd0accce8f829b44dab70cd42112a

**Comment by moderation** [comment]
The deps look OK but if this is not working there isn't a need for deps approval. I'll keep an eye on this PR

**Pull request closed without merging**
