### PR TITLE
golang filter extension: implement the Range method.

### PR DESCRIPTION
**Pull request by doujiang24**
Commit Message: golang filter extension: implement the Range method.
Additional Description:
Risk Level: low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by wangfakang — APPROVED** [review]
Thanks. LGTM

**Comment by doujiang24** [comment]
friendly ping @wbpcode

**Review by wbpcode — APPROVED** [review]
Thanks. LGTM.

**Pull request merged**
