### PR TITLE
Rollback #22036 due to crash

### PR DESCRIPTION
**Pull request by KBaichoo**
Signed-off-by: Kevin Baichoo <kbaichoo@google.com>

Commit Message: Rollback #22036 due to crash
Additional Description: See https://github.com/envoyproxy/envoy/pull/22036#discussion_r1044579979
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Comment by yanavlasov** [comment]
Please see https://github.com/envoyproxy/envoy/pull/22036/files#r1044579979 for the rollback reason.

**Comment by yanavlasov** [comment]
Please see https://github.com/envoyproxy/envoy/pull/22036/files#r1044579979 for the rollback reason.

**Comment by yanavlasov** [comment]
@LuyaoZhong  please add nullptr check and tests that validate this condition.

**Review by adisuissa — APPROVED** [review]
/lgtm api

**Pull request merged**
