### PR TITLE
fix network wasm example doc

### PR DESCRIPTION
**Pull request by StarryVae**
Commit Message: fix network wasm example doc
Additional Description: N/A
Risk Level: low
Testing: N/A
Docs Changes: wasm
Release Notes: N/A

### CODE REVIEW

**Review by phlax — COMMENTED** [review]
@StarryVae thanks for raising this

any chance we could move this into an envoy boostrap yml with a `literalinclude`

it just means this would stay fixed

**Comment by StarryVae** [comment]
thanks, but i have no idea how to move this into an envoy boostrap yml with a `literalinclude`, is there any example?

**Comment by StarryVae** [comment]
oh, i think i know what you mean, i will try to move this, thanks @phlax

**Comment by phlax** [comment]
yep - if do

```console

$ git grep literalinclude docs/

```

you should find quite a few - some have more than others - preferably we want a caption with download link

you might also want to only show certain lines, or highlight some

**Comment by phlax** [comment]
the only issue you might hit is the location of the bin - in the config test it puts it in a certain place - i think there is an existing config with example, but lmk if you hit any problem

**Comment by StarryVae** [comment]
> the only issue you might hit is the location of the bin - in the config test it puts it in a certain place - i think there is an existing config with example, but lmk if you hit any problem

ok, thanks.

**Comment by StarryVae** [comment]
@phlax i tried to add `literalinclude`, PTAL, thanks.

**Review by phlax — APPROVED** [review]
lgtm, thanks for doing this properly @StarryVae

**Comment by phlax** [comment]
@StarryVae it seems like this broke the server config test (there are a couple)

not sure how it got past CI but we should revert or fix forward

cc @adisuissa

**Comment by adisuissa** [comment]
I see the failure here: https://dev.azure.com/cncf/envoy/_build/results?buildId=135580&view=logs&jobId=1439b9f7-a348-5b50-b5fe-ea612ea91241&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=4d0399a5-fd0d-5446-d022-32daa00183cc

If the fix is straightforward we can fix-forward (seems like a mock function error).
However, to be prudent, we should probably rollback as there may be other failures.

**Comment by phlax** [comment]
> not sure how it got past CI

#27051

**Pull request merged**
