### PR TITLE
Bump fmtlib and spdlog

### LINKED ISSUE #18322: Newer release available com_github_gabime_spdlog: v1.9.2
*WARNING* com_github_gabime_spdlog has a newer release than v1.7.0@<2020-07-09 17:45:54>:v1.9.2@<2021-08-12 11:10:50>

### LINKED ISSUE #19439: Newer release available `com_github_fmtlib_fmt`: 8.1.1 (current: 7.0.3)
Package Name: com_github_fmtlib_fmt
Current Version: 7.0.3@2020-08-07 13:39:57
Available Version: 8.1.1@2022-01-06 22:35:15
Upstream releases: https://github.com/fmtlib/fmt/releases

### PR DESCRIPTION
**Pull request by krnowak**
Commit Message:
This updates fmtlib to 8.1.1 and spdlog to 1.9.2.

Additional Description:
Looks like fmtlib isn't formatting enumeration types as ints any more, so I'm explicitly casting them to ints. Without that, the build fails.

Risk Level:
Medium, logging library update.

Testing:
In CI only - I couldn't build the whole project as it takes too much space…

Docs Changes:
No.

Release Notes:
Not sure if dependency update is release-notes-worthy.

Platform Specific Features:
None.

Fix #18322 Fix #19439

### CODE REVIEW

**Comment by krnowak** [comment]
Looks like it's ready for review. Question though: `static_cast<int>` or `enumToInt`? The latter will turn an enumeration value to unsigned integer, so for cases where enumeration has negative values, the logs will show numbers around `UINT32_MAX`. That's why I went with `static_cast<int>`.

**Comment by moderation** [comment]
Thanks for updating these!

/lgtm deps

**Comment by krnowak** [comment]
Just remembered - another thing I updated was a test for text formatting of stats - the updated fmtlib does not print the `.0` any more. Not sure if there's a way of telling fmtlib to use precision 1 or more, so it always would be showing at least one digit after the decimal point.

**Comment by moderation** [comment]
> Just remembered - another thing I updated was a test for text formatting of stats - the updated fmtlib does not print the `.0` any more. Not sure if there's a way of telling fmtlib to use precision 1 or more, so it always would be showing at least one digit after the decimal point.

Does this change make it a breaking change and require a changelog entry? /cc @htuch, @phlax . Would be good to land this from a dependency point of view

**Comment by htuch** [comment]
My $0.02 is that this isn't a breaking change, since any parsing code should be robust to this difference when interpreting a float. I can imagine contrived corner cases when not, but the likelihood of breakage seems low.

**Comment by phlax** [comment]
+1 re parsing this value as float/int

**Comment by krnowak** [comment]
Merged the main branch to see if it still builds. But I see that the bot reverted some decisions (removed waiting and readded deps), sorry about that.

**Review by phlax — COMMENTED** [review]
/lgtm deps pending CI

**Comment by phlax** [comment]
@krnowak you can add the waiting label at any time with `/wait`

**Pull request merged**
