### PR TITLE
Breaking links and typos

### LINKED ISSUE #11215: Broken links and typos
Found following issues in docs.

1. Broken links:  **404 error** in below path:
File:  https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md
section: Runtime guard -> contributing doc link.

2. Typos in below path:
File : https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/fault_injection
Step-3 - > Terminal-2 Section
Typo in : Fauilt injection is configured in **Evoy** but turned off (i.e. affects 0% of requests).

### PR DESCRIPTION
**Pull request by ankatare**
Commit Message: to fix broken link and typos in docs
Additional Description:
Risk Level:Low
Testing: Unit and format check
Docs Changes: Yes
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #11215
[Optional Deprecated:]

### CODE REVIEW

**Comment by ggreenway** [comment]
Thank you for finding and fixing small things like this. It's greatly appreciated!

I see you have a separate PR open for config fragments, and I think this PR contains some of the same change as that one. Did you mean for just the lastest commit in this PR to be included here?

**Comment by ankatare** [comment]
@ggreenway Hi , Yes. those PRs for separate issues #10843  i am working on.

**Comment by jmarantz** [comment]
@ankatare it might be easier if you could specify which PR should be reviewed first, if they are overlapping.

**Comment by ankatare** [comment]
@jmarantz really sorry for any confusion here, this particular PR is intended for fixing docs issues.

**Comment by ggreenway** [comment]
> @jmarantz really sorry for any confusion here, this particular PR is intended for fixing docs issues.

If you look at the diff of this PR, it currently includes the v2->v3 config changes, as well as the doc fixes. To move forward, please separate the two, so this PR only contains the diffs for the doc fixes.

**Comment by ankatare** [comment]
@ggreenway Should i close this PR and create fresh one so that it contains changes wrt doc fixes only. OR is there any other way to proceed with this PR.

**Comment by ggreenway** [comment]
> @ggreenway Should i close this PR and create fresh one so that it contains changes wrt doc fixes only. OR is there any other way to proceed with this PR.

That is probably easiest.

**Comment by ankatare** [comment]
@ggreenway Ok, Thanks. will do the same

**Comment by ankatare** [comment]
closing this PR due to confusions from commits. will push changes in new PR.

**Pull request closed without merging**
