### PR TITLE
mobile ci: cancel ongoing mobile CI jobs when new SHA pushed to PR

### LINKED ISSUE #24982: mobile ci: cancel ongoing mobile ci jobs when a new SHA is pushed to a PR
*Title*: *cancel ongoing mobile ci jobs when a new SHA is pushed to a PR*

*Description*:
Canceling ongoing CI jobs in the case of a new SHA being pushed to a given PR should help us the limit the usage of CI that's used to run mobile checks (quite a limited resource). It would be a nice chance no matter whether we decide to eventually run mobile CI checks (instead of returning early from them) or not. Github actions - which are currently used to coordinate mobile CI checks - have an API that should allow us to implement what we want here.

### PR DESCRIPTION
**Pull request by glokta1**
Signed-off-by: glokta1 <rafeyahmad@protonmail.com>

Commit Message: [mobile ci: cancel ongoing mobile CI jobs when new SHA pushed to PR](https://github.com/glokta1/envoy/commit/ff707a607086cb32cd82ecde3d3d8d03bd0a5a9a)

Additional Description:  Added the `concurrency` key to all workflows which had a `pull_request` event attached. Some workflows are also additionally triggered on push to main, so added a fallback variable `github.run_id` to avoid syntax errors.

I was a little confused on whether to cancel the workflows that are run by cronjobs like  `codeql-daily.yml` but still include a `pull_request` event in some step. I have set it to cancel but let me know if this needs to be changed.

Fixes #24982

### CODE REVIEW

**Comment by yanavlasov** [comment]
Looks like format check is unhappy with TAB characters.

**Comment by glokta1** [comment]
@yanavlasov fixed!

**Review by jpsim — APPROVED** [review]
Thanks so much for tackling this.

Based on my understanding of [GitHub Actions contexts](https://docs.github.com/en/actions/learn-github-actions/contexts) this seems to be a reasonable implementation.

**Review by jpsim — CHANGES_REQUESTED** [review]
Actually I was wrong. I was wondering why only some of the GH Actions CI jobs actually ran on this PR, and I'm now realizing that every job currently shares the same concurrency group per PR.

I think we need to combine the `github.head_ref` with `github.action`. Maybe like this?

```yaml
concurrency:
  group: ${{ github.head_ref-github.action || github.run_id }}
  cancel-in-progress: true
```

**Comment by glokta1** [comment]
@jpsim Oh yeah, you're absolutely right. I completely missed that! I would suggest appending `github.workflow` instead of `github.action` to the group expression, since we're defining the concurrency key at the workflow level. 

From the docs:
`github.action`
> The name of the action currently running, or the [id](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsid) of a step.

`github.workflow`
> The name of the workflow. If the workflow file doesn't specify a name, the value of this property is the full path of the workflow file in the repository.

From my understanding, If we use `github.action`, the new workflow file will not cancel the old one if it's on a different step.

**Review by glokta1 — COMMENTED** [review]
@jpsim Oh yeah, you're absolutely right. I completely missed that! I would suggest appending `github.workflow` instead of `github.action` to the group expression, since we're defining the concurrency key at the workflow level. 

From the docs:
`github.action`
> The name of the action currently running, or the [id](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsid) of a step.

`github.workflow`
> The name of the workflow. If the workflow file doesn't specify a name, the value of this property is the full path of the workflow file in the repository.

From my understanding, If we use `github.action`, the new workflow file will not cancel its corresponding old one if it's on a different step/job.

**Comment by jpsim** [comment]
`github.workflow` sounds good.

**Review by jpsim — APPROVED** [review]
LGTM

Might need https://github.com/envoyproxy/envoy/pull/25148 for the ios_tests jobs to pass though.

**Pull request merged**
