### PR TITLE
build: exempting a failing test on windows

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: n/a
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
part of #11841

### CODE REVIEW

**Comment by alyssawilk** [comment]
examples
https://dev.azure.com/cncf/envoy/_build/results?buildId=43679&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=168f295b-0553-5364-35f7-923225ecd8b3
https://dev.azure.com/cncf/envoy/_build/results?buildId=43613&view=logs&j=800c766b-cf7f-545c-6b0a-ae5b31f2fdcf&t=a6bf9757-d7ab-5bb3-95e6-da7f4df1466d

**Comment by alyssawilk** [comment]
FWIW seems like this test flakes a bit on other builds, and is just particularly likely to fail on windows.

**Comment by alyssawilk** [comment]
cc @wrowe

**Comment by wrowe** [comment]
This appears to be resolved now on Windows with the work on simtime, proposing to reenable the test on windows with https://github.com/envoyproxy/envoy/pull/12695

**Pull request merged**
