### PR TITLE
build: Fix whitespace in flaky test script's output

### PR DESCRIPTION
**Pull request by rmiller14**
Commit Message:
The flaky test script currently uses tabs to line up columns in its output.  In Slack, tabs are converted to 4 spaces, so the columns are not aligned.  This PR fixes that by replacing the tabs with spaces.

Signed-off-by: Randy Miller <rmiller14@gmail.com>

Risk Level: None
Testing: Ran the script a few times.

### CODE REVIEW

**Comment by rmiller14** [comment]
cc @davinci26

**Review by antoniovicente — APPROVED** [review]

**Review by antoniovicente — APPROVED** [review]
Thanks for the improvements to #test-flaky slack reports.

**Comment by antoniovicente** [comment]
Seems like CI found some format failures, please look into them.

**Comment by rmiller14** [comment]
> Seems like CI found some format failures, please look into them.

Ok, just pushed a commit addressing those.  We'll see if it finds anything else.

**Comment by antoniovicente** [comment]
Please merge main and resolve conflicts with your other changes to ci/flaky_test/process_xml.py

**Review by antoniovicente — APPROVED** [review]
Thanks.

Will merge once CI is green.

**Pull request merged**
