### PR TITLE
ci: disable fuzzit

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Comment by lizan** [comment]
@yevgenypats The fuzzit running time keeps growing, do you have any plan to add the ability to limit the number of corpus (or time) running on each PR? or add test sharding ability to fuzzit CLI.

**Comment by lizan** [comment]
hmm, seems it is not just timeout, investigating.

**Comment by mattklein123** [comment]
I think you have a merge issue here?

/wait

**Comment by lizan** [comment]
@mattklein123 yeah was testing revert specific commit, the merge conflict is resolved.

**Pull request merged**
