### PR TITLE
router: rate_limit descriptor fix

### LINKED ISSUE #10124: Envoy skips calling rate limiting service when request header is not present
We have configured the rate limiting service with three request headers actions like 

```
        "rate_limits": [
         {
          "stage": 0,
          "actions": [
           {
            "source_cluster": {}
           },
           {
            "destination_cluster": {}
           },
           {
            "request_headers": {
             "header_name": ":authority",
             "descriptor_key": "authority"
            }
           },
           {
            "request_headers": {
             "header_name": ":path",
             "descriptor_key": "path"
            }
           },
           {
            "request_headers": {
             "header_name": "custom-header",
             "descriptor_key": "custom"
            }
           },
          ]
         }
        ]
       }
      ]
```
If in a request the `custom-header` does not have a value, Envoy skips calling the rate limiting service.

Debugging it further, found that if any of the `populateDescriptor` call here returns false it skips adding the descriptor

https://github.com/envoyproxy/envoy/blob/5be15b31aa46e3c3776a15fd3d399c67ac432598/source/common/router/router_ratelimit.cc#L121

and 

 `populateDescriptor`  implementation of `RequestHeadersAction` returns false if there is no value

https://github.com/envoyproxy/envoy/blob/5be15b31aa46e3c3776a15fd3d399c67ac432598/source/common/router/router_ratelimit.cc#L41

Since the descriptor list is empty, rate limit service is not called.

Is this expected behaviour? Should we not call rate limiting service with two headers as descriptor entries which have values rather than completely skipping it? 

Should we simply add a descriptor if it has atleast one entry?

### PR DESCRIPTION
**Pull request by rohan07**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description: It resolves - https://github.com/envoyproxy/envoy/issues/10124 by ensuring the descriptors get populated if there is one matching header in the request.
Risk Level: low
Testing: unit test added
Docs Changes: N/A
Release Notes: N/A
[Optional Fixes #Issue] Fixes #10124 
[Optional Deprecated:]

### CODE REVIEW

**Comment by yuval-k** [comment]
IIUC, this breaks the current semantics of current RL protocol. currently each rate-limit is essentially a tuple. it is important that the size of the tuple is always the same as it matches a co-responding configuration on the server.

After this change the size of the tuple is not guaranteed any more. Taking the configuration of the test for example, the size of the tuple is between 0 and 2.

perhaps adding default value support to `request_headers` will work for your use case?

cc @mattklein123 as the subject matter expert.

**Comment by ramaraochavali** [comment]
@yuval-k  

>> it is important that the size of the tuple is always the same as it matches a co-responding configuration on the server.

Do you mean configuration on the rate limit server implementation? Sorry, I was n't aware of this expectation. @mattklein123 / @junr03  would be able to confirm if that is the case?

**Comment by mattklein123** [comment]
I would need to fully page all of this back in, but I don't think there is any requirement that the configuration yield the same number of descriptors. IIRC the reference implementation at https://github.com/lyft/ratelimit should work fine with a partial set of passed descriptors? @yuval-k @rohan07 @ramaraochavali can you verify? cc @junr03 who might have more info paged in.

**Comment by ramaraochavali** [comment]
@mattklein123 I have verified and could not find any such requirement that both should match. But I may be missing some thing.

Let us wait for @junr03 for feedback and review - He might know if there is one.

**Comment by yuval-k** [comment]
the way the filter works today, each rate limit will yield one shape for the resulting descriptor.
after this change there will be 2^n possible resulting shapes for the descriptor.

IIUC the way that the reference server resolves its configuration (https://github.com/lyft/ratelimit/blob/403b5b5c5c6715a76a5bbe43499c82c7d241fbf1/src/config/config_impl.go#L244) is to iterate the sent descriptor in order and match them with its configuration.
i.e. the shape of the descriptor is taken to account - so after this change you will need matching 2^n configurations on the server.

# Example

The following rate limit:
```
- request_headers:
    header_name: x-header-name
    descriptor_key: my_header_name
- request_headers:
    header_name: x-header
    descriptor_key: my_header 
```
will yield 3 possible descriptors shapes:
```
(x-header-name, value1)
(x-header, value2)
(x-header-name, value1)(x-header, value2)
```
of which, only one i sent to the server. the server has no way of knowing they originate from the same rate limit config.

if the server was previously configured like so:
```
descriptors:
  - key: x-header-name
    value: value1
    descriptors:
      - key: x-header
        rate_limit:
          unit: day
          requests_per_unit: 5
```

will now have to be modified to take to account the new descriptor shapes:
```
descriptors:
  - key: x-header-name
    value: value1
      rate_limit:
        unit: day
        requests_per_unit: 5
  - key: x-header
      rate_limit:
        unit: day
        requests_per_unit: 5
  - key: x-header-name
    value: value1
    descriptors:
      - key: x-header
        rate_limit:
          unit: day
          requests_per_unit: 5
```

This is what I mean by calling this semantics change, and not just a bug fix. IMHO if this change is desired, it should be considered a breaking change.

**Comment by ramaraochavali** [comment]
@yuval-k Thanks for the detailed explanation. As I mentioned earlier, I am not fully familiar with that expectation.

**Comment by mattklein123** [comment]
@yuval-k yes I see what you are saying and why you suggested another option is a default value if the header does not exist.

TBH I think I could go either way on this. On one hand, it seems like even with the reference server, the user can understand the possible permutations and set up the config as they wish, though I agree this might be considered a breaking change.

@ramaraochavali @rohan07  maybe we should config guard this behavior somehow and have clear documentation? I think that with a config guard that defaults to off, as long as the user understands what might happen, they can engineer their server config to match. The other option would be a default header value (or potentially both). WDYT?

**Comment by ramaraochavali** [comment]
@mattklein123 Yes. I am fine with a config guard default to current behaviour. I am assuming the config guard you are suggesting in filter config?

**Comment by mattklein123** [comment]
Yeah either on the filter itself or in the header descriptor config somehow. Up to you.

**Comment by ramaraochavali** [comment]
@mattklein123  Sorry for the delay. I think it is better to add a new flag called `skip_if_absent` in RequestHeaders https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/route/route_components.proto#L1322, which will be defaulted to `false` (current behaviour). If set to true, rate limiting ignore that descriptor and call rate limiting service even if there is no value. This will give max flexibility at the header level.

Let me know if there are any objections/suggestions.

**Comment by mattklein123** [comment]
@ramaraochavali SGTM!

**Comment by ramaraochavali** [comment]
not state

**Pull request closed without merging**
