### PR TITLE
deps: Bump `com_googlesource_code_re2` -> 2022-12-01

### LINKED ISSUE #24287: Newer release available `com_googlesource_code_re2`: 2022-12-01 (current: 2022-06-01)
Package Name: com_googlesource_code_re2@2022-06-01
Current Version: 2022-06-01@2022-05-31
Available Version: 2022-12-01@2022-11-30
Upstream releases: https://github.com/google/re2/releases

### PR DESCRIPTION
**Pull request by phlax**
Fix #24287 

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by moderation** [comment]
Bump @phlax - I think this PR is good to go

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
