### PR TITLE
Add `:scheme` to H1 downstream headers

### PR DESCRIPTION
**Pull request by rgs1**
It'd be handy to have `headers.Scheme()` work for filters in both H2
and H1. Given that `:authority` is already added in the HTTP1 codec
and that `:scheme` is added to upstream requests for H1 & H2 [0],
this should makes things more consistent for filter writers.

[0] https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.cc#L91

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

### CODE REVIEW

**Comment by dio** [comment]
Thanks, @rgs1! From a quick look, this is fine. Let's have @alyssawilk to help to review this.

**Comment by alyssawilk** [comment]
Hm, I can see where the consistency would be helpful but I don't think we want Envoy forwarding H2 headers over H1.  What if we had a utility function that you could do getScheme(request_headers) and it would infer?  

Alternately, are you looking for scheme (the security of the last hop) or X-Forwarded-Proto (the security of the client-to-front-proxy-connection)?  I suspect you want the former (it's useful even if you are the first hop) and so downstream_headers.ForwardedProto() might do what you're looking for, and it exists for both the first and for subsequent hops.

**Comment by rgs1** [comment]
> Hm, I can see where the consistency would be helpful but I don't think we want Envoy forwarding H2 headers over H1. What if we had a utility function that you could do getScheme(request_headers) and it would infer?
> 
> Alternately, are you looking for scheme (the security of the last hop) or X-Forwarded-Proto (the security of the client-to-front-proxy-connection)? I suspect you want the former (it's useful even if you are the first hop) and so downstream_headers.ForwardedProto() might do what you're looking for, and it exists for both the first and for subsequent hops.

Thanks for the quick reply @alyssawilk!

Don't we already forward `:scheme` per:

https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.cc#L91

This just makes it available for filters, upstreams are already seeing it regardless no?

Yes, we are looking for the security of the last hop, but when I read the code my first reaction was that we might as well make `headeres.Scheme()` available since we are already setting it for upstreams. This is also true for internal redirects:

https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.cc#L82

**Comment by lizan** [comment]
> Don't we already forward :scheme per:
> https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.cc#L91

No, that is setting `:scheme` based on upstream config, not forwarding downstream scheme.

**Comment by rgs1** [comment]
> > Don't we already forward :scheme per:
> > https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.cc#L91
> 
> No, that is setting `:scheme` based on upstream config, not forwarding downstream scheme.

ah true, it is done for internal redirects tho.

**Comment by rgs1** [comment]
> > > Don't we already forward :scheme per:
> > > https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.cc#L91
> > 
> > 
> > No, that is setting `:scheme` based on upstream config, not forwarding downstream scheme.
> 
> ah true, it is done for internal redirects tho.

actually, not true for internal redirects either since the scheme comes from the upstream's location header.

@alyssawilk yeah probably `downstream_headers.ForwardedProto()` is enough.

cc: @jparise

**Comment by alyssawilk** [comment]
Cool, glad that's a helpful header.  Anything else to do here then, or should we close this one off?

**Comment by rgs1** [comment]
All good, thanks!

**Pull request closed without merging**
