### PR TITLE
Add a script for checking that PR descriptions have all the required fields

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
tools: Add a script for checking that PR descriptions have all the required fields. Shows up as a check called "check-pr-description / Check PR Description (pull_request) "

Risk Level: Low - tool only
Testing: Manual testing
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

Signed-off-by: Ryan Hamilton <rch@google.com>

### CODE REVIEW

**Comment by phlax** [comment]
@RyanTheOptimist im afraid im pretty -1 to this - i think its fine having these fields, but for many PRs its just not relevant, so should also be fine to not fill them in

it also adds a load of overhead for reviewers, if the intention that all these fields are then copied out when the PR lands 

mho is that this will add an unnecessary burden all round - essentially its fixing something that is not broken

**Comment by RyanTheOptimist** [comment]
> @RyanTheOptimist im afraid im pretty -1 to this - i think its fine having these fields, but for many PRs its just not relevant, so should also be fine to not fill them in

Oh, interesting! My understanding was that these fields were always required as part of the PR description. The PULL_REQUEST_TEMPLATE marks some as optional (hence the non-optional fields are required). The instructions for how to fill them out don't seem to contain any carve outs for omitting them. But I asked about this on #envoy-maintainers and my take-away was that folks DO think these fields are required. @mattklein123 was supportive of building a tool like this which is how this PR started. 

But if these fields should NOT be required, then I think it would be a good idea for us to be clear about what the policy is with these fields. Is there a forum other than #envoy-maintainers which would be a good place to sort out what the consensus is?

> it also adds a load of overhead for reviewers, if the intention that all these fields are then copied out when the PR lands

From the discussion on #envoy-maintainers (and from looking at git log output), it is NOT the intention that these fields be copied into the commit message.

**Comment by jmarantz** [comment]
I've been using N/A for non-optional fields that I don't want to fill in. I've been deleting optional fields.

**Comment by RyanTheOptimist** [comment]
> I've been using N/A for non-optional fields that I don't want to fill in. I've been deleting optional fields.

Makes sense. That's what I've been doing as well. (The script in this PR only checks for the presence of the non-optional fields, fwiw)

**Comment by rojkov** [comment]
What would be the next action for this PR? Personally I'm in favor of this change, but #18781 also seems to be waiting for comments on the topic.
/wait-any

**Pull request closed without merging**
