### PR TITLE
deps: Update c-ares to 1.21.0

### PR DESCRIPTION
**Pull request by yanavlasov**
Commit message:
c-ares changes that affected tests:

- resolution with empty name results in immediate error - tests were adjusted to use a bogus name to start resolution that will result in an error.
- timeout of 0 no longer implies "fail immediately". It is replaced with the default 5 seconds timeout. Tests were adjusted to make DNS server never respond thus triggering resolution timeout.
- fix flakiness in the test that waits for 2 resolutions to complete. The flakiness was pre-existing although very low probability. With the new c-ares version it has increased, most likely due to some changes to how responses are read from the socket.

Risk Level: Low
Testing: Unit tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by RyanTheOptimist — DISMISSED** [review]
Sweet!

**Comment by phlax** [comment]
there is also https://github.com/envoyproxy/envoy/pull/35195 which was trying to address https://github.com/envoyproxy/envoy/issues/33138

**Comment by yanavlasov** [comment]
> there is also #35195 which was trying to address #33138

There seems to be a lot of changes to c-ares, so upgrading one by one may make it easier to diagnose problems.

**Comment by botengyao** [comment]
cc @adisuissa, with this version update, I think we can remove the patch added by this https://github.com/envoyproxy/envoy/pull/35487 based on c-ares [change-log 1.21.0](https://c-ares.org/changelog.html#1_21_0)

**Comment by adisuissa** [comment]
> cc @adisuissa, with this version update, I think we can remove the patch added by this #35487 based on c-ares [change-log 1.21.0](https://c-ares.org/changelog.html#1_21_0)
> 
> **update**: nvm, saw the patch is already deleted in this PR, thanks!

Yeah, the patch was introduced as part of v1.21.0, and I just cherry-picked it. Upgrading to a new version of c-ares is more challenging as there are some big upgrades that are introduced across versions.

**Pull request merged**
