### PR TITLE
yaml: use protobuf to parse float/double

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

Description:
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18977

Risk Level: Low
Testing: unit test, fuzz
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by lizan** [comment]
https://dev.azure.com/cncf/envoy/_build/results?buildId=20047 mac CI passed but not reflected in GH.

**Comment by LisaLudique** [comment]
Hey @lizan we think this resulted in a bug at Lyft. Circuit breaker values (max_connections, max_requests) are being parsed as floats but should be ints, so envoy cannot startup. Would it be possible to revert this change?

cc @mattklein123

**Comment by mattklein123** [comment]
@LisaLudique I'm a little confused what is going on here. We can definitely revert if needed but if possible can you take a look at the code and try to see where the bug is and/or provide a failing example that we can debug?

**Comment by LisaLudique** [comment]
We did some investigating yesterday and think it could be due to how we parse/dump YAML/JSON when generating configs, so I don't think this change needs to be reverted. 

A couple of users were trying to disable circuit breaking for their services as recommended in the docs by setting `max_connections` and `max_requests` to very high values (100000000 and 1000000000). The resultant envoy error upon startup is ```Unable to parse JSON as proto (INVALID_ARGUMENT:(static_resources.clusters[0].circuit_breakers.thresholds[0].max_connections.value): invalid value "100000000.0" for type TYPE_UINT32)```. We still need to find where float parsing happens on our side, but strangely this error didn't surface until this commit was brought in.

**Comment by mattklein123** [comment]
OK thanks for the update @LisaLudique. Definitely open a new issue if there are things we could improve here.

**Comment by lizan** [comment]
@LisaLudique @mattklein123 Yes, if you previously had a JSON or YAML with `10000.0` without the quotation, the previous implementation did parse it leniently because we do convert YAML to JSON once and JSON doesn't differentiate float and integer. After this change the parser doesn't allow that anymore. I don't think this is a bug behavior because the defined proto field is an integer type, you shouldn't emit `10000.0` for those types.

**Comment by LisaLudique** [comment]
Got it, that makes sense - thanks for the context!

**Pull request merged**
