### PR TITLE
aws: add nbaws as aws codeowner

### PR DESCRIPTION
**Pull request by nbaws**
Commit Message: aws: add nbaws as aws codeowner
Additional Description: @suniltheta 
Risk Level: N/A
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by adisuissa** [comment]
@suniltheta @lavignes for current codeowners review

**Comment by adisuissa** [comment]
Assigning Matt for the extension's senior-maintainer LGTM.
/assign @mattklein123

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
