### PR TITLE
redis: Add support for ASKING command

### PR DESCRIPTION
**Pull request by deveshkandpal1224**
Commit Message: Add support for ASKING command in redis_proxy
Additional Description: Today if ASKING command is sent, proxy replies back with unsupported command. https://redis.io/commands/asking/
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by mattklein123 — CHANGES_REQUESTED** [review]
I'm not sure this makes sense. I think we would need to actually implement https://redis.io/docs/reference/cluster-spec/#ask-redirection properly? Can you provide more info?

**Comment by deveshkandpal1224** [comment]
@mattklein123 - let me move the discussion to a github issue with details around what we are trying to solve for.

**Pull request closed without merging**
