### PR TITLE
thrift: fix test tooling for python3

### PR DESCRIPTION
**Pull request by zuercher**
Applies a patch to the python libraries used in
test to enable python3 compatibility. Related
to #10701 and #4552.

Risk Level: low, test only
Testing: n/a
Docs Changes: n/a
Release Notes: n/a

Signed-off-by: Stephan Zuercher <zuercher@gmail.com>

### CODE REVIEW

**Comment by zuercher** [comment]
So evidently there's some more stuff in the python that's compatible with whatever version of python3 I tested against and what's used in most of our CI, but not the version used in coverage. Will try to make time to revisit this again later.

**Comment by phlax** [comment]
@zuercher was there a reason for abandoning this PR ?

we are looking at this again with a view to removing the dependency on six

**Pull request closed without merging**
