### PR TITLE
api: include v1alpha1 in proto_sync.py

### PR DESCRIPTION
**Pull request by derekargueta**
Description: Follow-up to #8133, these likely escaped detection since they're versioned "v1alpha1" and the cloning script only searches for the last major version. This should be a one-off to get these caught up so I'm not modifying the tooling to accommodate these.
Risk Level: low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A

Signed-off-by: Derek Argueta <dereka@pinterest.com>

### CODE REVIEW

**Comment by htuch** [comment]
@derekargueta I think we do need to have the tools do this, since these APIs might gain new fields before we do the v3 cut. I think it's fairly easy to do, check out `tools/type_whisperer/typedb_gen.py` and `tools/proto_sync.py`, look for references to v2alpha.

**Comment by derekargueta** [comment]
I didn't want to add one-off logic but since we already handling vNalphaN for v2 in `tools/proto_sync.py` I feel less bad :) will push an update.

**Comment by derekargueta** [comment]
@htuch tooling updated. I _believe_ it's is working as expected. When running with some debug prints, I verified it picks up the v1alpha1 bazel targets but hits [this line](https://github.com/envoyproxy/envoy/pull/9175/files#diff-81c2f1424a9f922f7db5466d175dd6a0L117) because (IIUC) there are no deprecated fields in v1alpha1 for these two protos so there's nothing to modify.

**Comment by htuch** [comment]
@derekargueta ah yeah. So, I think your tool changes make sense, but then we shouldn't have the actual protos in v3alpha. We're only upgrading packages that have either had a breaking change or transitively depend on a package that has been upgraded. We basically have a DAG of versions.

**Pull request merged**
