### PR TITLE
listener: 2nd attempt create per network filter chain stats scope

### PR DESCRIPTION
**Pull request by lambdai**
Commit Message:
This is the 2nd attempt of https://github.com/envoyproxy/envoy/pull/17931
The goal is to fix some stats leak described in  #17690

The above PR is reverted because the shared grpc logger can reference a destroyed stat scope and that behavior is amplified by the above PR.
The grpc logger issue is fixed by https://github.com/envoyproxy/envoy/pull/18067

In case further improper behaviors are detected at a network filter or any extension, 
`envoy.reloadable_features.per_network_filter_chain_factory_context` is added here so we don't have to revert this PR.

Signed-off-by: Yuchen Dai <silentdai@gmail.com>

Additional Description:
Risk Level: Mid
Testing: Tests and runtime flag behavior test.
Docs Changes:
Release Notes:
Platform Specific Features:
Runtime guard: envoy.reloadable_features.per_network_filter_chain_factory_context
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by lambdai** [comment]
> if people see crashes we are just going to revert this anyway and try again.
> 

Thank you for the feedback. I am not sure if I understand the piece. Isn't the goal of that runtime is to avoid revert, instead, we disable the runtime feature at a smaller penalty than revert.

I am fine and be prepared to revert though.

**Comment by mattklein123** [comment]
> Thank you for the feedback. I am not sure if I understand the piece. Isn't the goal of that runtime is to avoid revert, instead, we disable the runtime feature at a smaller penalty than revert.

Yes, in general, but we don't typically do it for small changes like this. More like large changes where we might not know the implications for a long time, might be difficult to revert, etc. For this, I think we are going to know pretty quickly whether it works or not, so I would recommend just trying the fix again directly without the cleanup overhead?

**Comment by lambdai** [comment]
I see. Make sense to me. Thank you for the explanation.

I clean up the runtime related code and test. PTAL

**Pull request merged**
