### PR TITLE
[1.22] repo: Release v1.22.8

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
this is the last of the manual release branches so once it lands i will still have to wait for CI and then manually create the tag

**Review by mattklein123 — APPROVED** [review]

**Comment by phlax** [comment]
forcing this through on the basis that it can pass the release testing, but the coverage keeps on failing - should be good enough to release

**Pull request merged**
