### PR TITLE
[WIP] Add upstream network RBAC filter

### PR DESCRIPTION
**Pull request by surki**
- Reuses the RBAC downstream filter, introduces new matcher/fields for
  upstream ip and port
- Propagates information from upstream filter back to downstream context if
  any

TODO:

- Downstream context is not available in upstream filter, find a way to
  propagate (so we can say `application with IP 1.2.3.4 can talk to upstream
  IP 4.5.6.7` etc)
- RBAC rule should be enforced before connection establishment, currently
  does it after establishment
- Documentation

Signed-off-by: Suresh Kumar <sureshkumar.pp@gmail.com>

Example usage:

```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 1234
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: example_cluster
                  timeout: 1500s
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: example_cluster
    type: LOGICAL_DNS
    connect_timeout: 5s
    dns_lookup_family: V4_ONLY
    respect_dns_ttl: true
    dns_refresh_rate: 3000s
    load_assignment:
      cluster_name: example.com|8080
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: example.com
                port_value: 8080
    filters:            
    - name: envoy.filters.network.rbac
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC
        stat_prefix: rbac_upstream
        rules:
          action: DENY
          policies:
            "loopback":
              principals:
              - any: true
              permissions:
              - upstream_destination_ip:   
                  address_prefix: 127.0.0.1
                  prefix_len: 8
```

Commit Message: Adds new upstream network RBAC filter
Additional Description:
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA] #21178
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by surki** [comment]
@mattklein123 @snowp @yanavlasov @markdroth Please provide feedback on this, wondering if you can do a quick skim through and see if this  approach (using same filter/config in both downstream and upstream filters) is acceptable?

Additionally, need some input on how to do the following:

1. Currently there seems to be no callback in filter before the connection is established. Did I miss it somewhere? I want to enforce  RBAC rules even before the connection is established
2. I want to pass the information from downstream connection into upstream filter context (so we can say `application with IP 1.2.3.4 can talk to upstream cluster with IP 4.5.6.7` etc). Wondering if you can provide some input on how I can go about it.

**Comment by zhxie** [comment]
> Additionally, need some input on how to do the following:
> 
> 1. Currently there seems to be no callback in filter before the connection is established. Did I miss it somewhere? I want to enforce  RBAC rules even before the connection is established
> 2. I want to pass the information from downstream connection into upstream filter context (so we can say `application with IP 1.2.3.4 can talk to upstream cluster with IP 4.5.6.7` etc). Wondering if you can provide some input on how I can go about it.

Reply questions:

1. Can you check if `Network::ReadFilter::onNewConnection()` satisfies your needs? The method will get called when the connection between downstream and Envoy established.
2. For every connection/request, a corresponding network filter/HTTP filter will be established. So you can just save everything you need in the filter on downstream connection and use them later.

**Comment by surki** [comment]
> > Additionally, need some input on how to do the following:
> > 
> > 1. Currently there seems to be no callback in filter before the connection is established. Did I miss it somewhere? I want to enforce  RBAC rules even before the connection is established
> > 2. I want to pass the information from downstream connection into upstream filter context (so we can say `application with IP 1.2.3.4 can talk to upstream cluster with IP 4.5.6.7` etc). Wondering if you can provide some input on how I can go about it.
> 
> Reply questions:
> 
> 1. Can you check if `Network::ReadFilter::onNewConnection()` satisfies your needs? The method will get called when the connection between downstream and Envoy established.
`onNewConnection` is called after the connection is established. I guess we would have to introduce a new callback, something along the line of "onAccept" callback, so we can enforce rules before the connection is established.

> 2. For every connection/request, a corresponding network filter/HTTP filter will be established. So you can just save everything you need in the filter on downstream connection and use them later.
I guess I wasn't clear enough: since there are two "connections" involved (`connection one` being "client to envoy listener" and `connection two` being "envoy to upstream host"), in the `connection two` context (which is where the upstream filter would be instantiated), I will need access to the information about `connection one`. Just went through [router.cc](https://github.com/envoyproxy/envoy/blob/e5ef611dd9a0e840681cd6e99c6cffc97ecb47b5/source/common/router/router.cc#L686), we don't seem to pass anything about downstream to upstream_request object, so was wondering if this is already being passed somewhere else.

**Comment by zhxie** [comment]
> > > Additionally, need some input on how to do the following:
> > > 
> > > 1. Currently there seems to be no callback in filter before the connection is established. Did I miss it somewhere? I want to enforce  RBAC rules even before the connection is established
> > > 2. I want to pass the information from downstream connection into upstream filter context (so we can say `application with IP 1.2.3.4 can talk to upstream cluster with IP 4.5.6.7` etc). Wondering if you can provide some input on how I can go about it.
> > 
> > 
> > Reply questions:
> > 
> > 1. Can you check if `Network::ReadFilter::onNewConnection()` satisfies your needs? The method will get called when the connection between downstream and Envoy established.
> 
> `onNewConnection` is called after the connection is established. I guess we would have to introduce a new callback, something along the line of "onAccept" callback, so we can enforce rules before the connection is established.
> 
> > 2. For every connection/request, a corresponding network filter/HTTP filter will be established. So you can just save everything you need in the filter on downstream connection and use them later.
> 
> I guess I wasn't clear enough: since there are two "connections" involved (`connection one` being "client to envoy listener" and `connection two` being "envoy to upstream host"), in the `connection two` context (which is where the upstream filter would be instantiated), I will need access to the information about `connection one`. Just went through [router.cc](https://github.com/envoyproxy/envoy/blob/e5ef611dd9a0e840681cd6e99c6cffc97ecb47b5/source/common/router/router.cc#L686), we don't seem to pass anything about downstream to upstream_request object, so was wondering if this is already being passed somewhere else.

1. I think `onNewConnection` will be called after the connection between downstream and Envoy gets established. And I think what you need is to avoid establishing connection between Envoy and upstream. There is no need to add something like `onAccept`.

2. Which way? From Envoy to the upstream (like connects to which cluster), you can use metadata. From the upstream to Envoy, you can just use any contexts in the filter.

**Comment by surki** [comment]
> > > 1. Can you check if `Network::ReadFilter::onNewConnection()` satisfies your needs? The method will get called when the connection between downstream and Envoy established.
> > 
> > 
> > `onNewConnection` is called after the connection is established. I guess we would have to introduce a new callback, something along the line of "onAccept" callback, so we can enforce rules before the connection is established.
> > > 2. For every connection/request, a corresponding network filter/HTTP filter will be established. So you can just save everything you need in the filter on downstream connection and use them later.
> > 
> > 
> > I guess I wasn't clear enough: since there are two "connections" involved (`connection one` being "client to envoy listener" and `connection two` being "envoy to upstream host"), in the `connection two` context (which is where the upstream filter would be instantiated), I will need access to the information about `connection one`. Just went through [router.cc](https://github.com/envoyproxy/envoy/blob/e5ef611dd9a0e840681cd6e99c6cffc97ecb47b5/source/common/router/router.cc#L686), we don't seem to pass anything about downstream to upstream_request object, so was wondering if this is already being passed somewhere else.
> 
> 1. I think `onNewConnection` will be called after the connection between downstream and Envoy gets established. And I think what you need is to avoid establishing connection between Envoy and upstream. There is no need to add something like `onAccept`.

Right, we need to check (via upstream RBAC filter) and potentially stop envoy establishing upstream connection. What's the right filter API/callback to do this? (`onNewConnection` is too late for it, the connection is already established, I don't see any filter callbacks in `ClientConnectionImpl::connect()` or before that).

> 2. Which way? From Envoy to the upstream (like connects to which cluster), you can use metadata. From the upstream to Envoy, you can just use any contexts in the filter.

Not sure I understood this completely, can you please give a pointer to code somewhere that does it? Just to be on the same page: this RBAC filter is instantiated in upstream connection context (so `router.cc` -> `upstream_request.cc` -> `ClientConnectionImpl` etc), once I get a callback in, say `onData`, how do I refer to the downstream listener side connection context? (which I suppose could be on completely another  threadpool, with its own lifecycle etc)

**Comment by zhxie** [comment]
> > > > 1. Can you check if `Network::ReadFilter::onNewConnection()` satisfies your needs? The method will get called when the connection between downstream and Envoy established.
> > > 
> > > 
> > > `onNewConnection` is called after the connection is established. I guess we would have to introduce a new callback, something along the line of "onAccept" callback, so we can enforce rules before the connection is established.
> > > > 2. For every connection/request, a corresponding network filter/HTTP filter will be established. So you can just save everything you need in the filter on downstream connection and use them later.
> > > 
> > > 
> > > I guess I wasn't clear enough: since there are two "connections" involved (`connection one` being "client to envoy listener" and `connection two` being "envoy to upstream host"), in the `connection two` context (which is where the upstream filter would be instantiated), I will need access to the information about `connection one`. Just went through [router.cc](https://github.com/envoyproxy/envoy/blob/e5ef611dd9a0e840681cd6e99c6cffc97ecb47b5/source/common/router/router.cc#L686), we don't seem to pass anything about downstream to upstream_request object, so was wondering if this is already being passed somewhere else.
> > 
> > 
> > 
> > 1. I think `onNewConnection` will be called after the connection between downstream and Envoy gets established. And I think what you need is to avoid establishing connection between Envoy and upstream. There is no need to add something like `onAccept`.
> 
> Right, we need to check (via upstream RBAC filter) and potentially stop envoy establishing upstream connection. What's the right filter API/callback to do this? (`onNewConnection` is too late for it, the connection is already established, I don't see any filter callbacks in `ClientConnectionImpl::connect()` or before that).
> 
> > 2. Which way? From Envoy to the upstream (like connects to which cluster), you can use metadata. From the upstream to Envoy, you can just use any contexts in the filter.
> 
> Not sure I understood this completely, can you please give a pointer to code somewhere that does it? Just to be on the same page: this RBAC filter is instantiated in upstream connection context (so `router.cc` -> `upstream_request.cc` -> `ClientConnectionImpl` etc), once I get a callback in, say `onData`, how do I refer to the downstream listener side connection context? (which I suppose could be on completely another threadpool, with its own lifecycle etc)

1. No, when `onNewConnection` gets called, the upstream connection has not been established yet.
2. For example, you can check the how this variable is used in local rate limit HTTP filter. https://github.com/envoyproxy/envoy/blob/e5ef611dd9a0e840681cd6e99c6cffc97ecb47b5/source/extensions/filters/http/local_ratelimit/local_ratelimit.h#L163

**Comment by surki** [comment]
> > > > > 1. Can you check if `Network::ReadFilter::onNewConnection()` satisfies your needs? The method will get called when the connection between downstream and Envoy established.
> > > > 
> > > > 
> > > > `onNewConnection` is called after the connection is established. I guess we would have to introduce a new callback, something along the line of "onAccept" callback, so we can enforce rules before the connection is established.
> > > > > 2. For every connection/request, a corresponding network filter/HTTP filter will be established. So you can just save everything you need in the filter on downstream connection and use them later.
> > > > 
> > > > 
> > > > I guess I wasn't clear enough: since there are two "connections" involved (`connection one` being "client to envoy listener" and `connection two` being "envoy to upstream host"), in the `connection two` context (which is where the upstream filter would be instantiated), I will need access to the information about `connection one`. Just went through [router.cc](https://github.com/envoyproxy/envoy/blob/e5ef611dd9a0e840681cd6e99c6cffc97ecb47b5/source/common/router/router.cc#L686), we don't seem to pass anything about downstream to upstream_request object, so was wondering if this is already being passed somewhere else.
> > > 
> > > 
> > > 
> > > 1. I think `onNewConnection` will be called after the connection between downstream and Envoy gets established. And I think what you need is to avoid establishing connection between Envoy and upstream. There is no need to add something like `onAccept`.
> > 
> > 
> > Right, we need to check (via upstream RBAC filter) and potentially stop envoy establishing upstream connection. What's the right filter API/callback to do this? (`onNewConnection` is too late for it, the connection is already established, I don't see any filter callbacks in `ClientConnectionImpl::connect()` or before that).
> > > 2. Which way? From Envoy to the upstream (like connects to which cluster), you can use metadata. From the upstream to Envoy, you can just use any contexts in the filter.
> > 
> > 
> > Not sure I understood this completely, can you please give a pointer to code somewhere that does it? Just to be on the same page: this RBAC filter is instantiated in upstream connection context (so `router.cc` -> `upstream_request.cc` -> `ClientConnectionImpl` etc), once I get a callback in, say `onData`, how do I refer to the downstream listener side connection context? (which I suppose could be on completely another threadpool, with its own lifecycle etc)
> 
> 1. No, when `onNewConnection` gets called, the upstream connection has not been established yet.

true in downstream context, but not in upstream filter context. (and there is no reliable way in downstream filter context to check/enforce policy on upstream connections: dns lookups, retries etc happen later...)

> 2. For example, you can check the how this variable is used in local rate limit HTTP filter. https://github.com/envoyproxy/envoy/blob/e5ef611dd9a0e840681cd6e99c6cffc97ecb47b5/source/extensions/filters/http/local_ratelimit/local_ratelimit.h#L163

This is only referring current context, not the upstream.

**Comment by zhxie** [comment]
Sorry, I am still not clear about your requests, maybe seniors can answer your questions.

BTW, if you just want to check upstream IP and port, does not [RBAC upstream IP and port matcher](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/rbac/matchers/upstream_ip_port/v3/upstream_ip_port_matcher.proto.html) satisfy your needs?

**Comment by surki** [comment]
> BTW, if you just want to check upstream IP and port, does not [RBAC upstream IP and port matcher](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/rbac/matchers/upstream_ip_port/v3/upstream_ip_port_matcher.proto.html) satisfy your needs?

thanks @zhxie. `UpstreamIpPortMatcher` is what we are currently using, but it is not safe to use, it is susceptible to the confused-deputy/dns-rebinding attack, please see [here](https://github.com/envoyproxy/envoy/pull/21196/files). Based on the discussions on that, it appears the safest way to check/enforce the policy is to have an upstream filter (which is instantiated during the upstream connection establishment...). This PR is to add that feature. We are trying to re-use the code as much as possible between the downstream and upstream RBAC filters.

**Comment by surki** [comment]
> yeah fwiw I have a series of changes which should largely do away with commonserverfactorycontext and replace with serverfactorycontext which should fix up a lot of the class changes here

Thanks, will wait for your changes.
@alyssawilk Wondering if you are also setting up infra to pass the downstream information to upstream request context (which is needed for upstream filters)?

**Comment by alyssawilk** [comment]
not yet, no.  I think @kyessenov _may_ have done some of that?  But if you want to work on that as a standalone that'd be helpful

**Comment by kyessenov** [comment]
I have done sharing with upstream only for the filter state. Some basic fields like SSH info need separate plumbing (and answer how we handle sharing of upstream connections by multiple downstream connections).

**Pull request closed without merging**
