### PR TITLE
build: Update RBE toolchan config

### PR DESCRIPTION
**Pull request by yanavlasov**
Additional Description:
Transition RBE toolchain config to the new one generated by the RBE config utility.
Risk Level: Low
Testing: RBE Builds
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

Signed-off-by: Yan Avlasov <yavlasov@google.com>

### CODE REVIEW

**Comment by yanavlasov** [comment]
> Can we, do we have a 4.2 tag to capture, to see if that routes around the problem?

We do not at this point, I will have to rebuild the toolchain. Which I can. I'm however not even sure what difference this would make, since 3.7.2 and 4.1.0 directories for windows clang are identical.

**Review by lizan — APPROVED** [review]

**Comment by junr03** [comment]
@yanavlasov do you want to merge this?

**Comment by wrowe** [comment]
The present release today is 4.2.1. @yanavlasov could you bump this again?

**Comment by moderation** [comment]
> The present release today is 4.2.1. @yanavlasov could you bump this again?

Should https://github.com/envoyproxy/envoy/blob/main/.bazelversion#L1 be updated to `4.2.0` as per prior PR in this space https://github.com/envoyproxy/envoy/pull/16644/files?

Similarly https://github.com/envoyproxy/envoy/pull/16644/files should be bumped to `4.2.0`

**Comment by yanavlasov** [comment]
Closing for now. The platform targets are incorrectly set to use toolchains for bazel 3.7.1 only. I'm fixing this right now on build-tools. Will reopen once it is fixed.

Also bazel version on main is 4.1.0 not 4.2.0. bazel version will be bumped separately, I want to make sure the existing config is fully functional first.

**Review by wrowe — CHANGES_REQUESTED** [review]
You omitted the updates of the other references to toolchain image 55d9e4719d2bd0accce8f829b44dab70cd42112a

Please correct. (I'm checking this out locally.)

**Comment by wrowe** [comment]
> Also bazel version on main is 4.1.0

Actually, the envoy build containers in use in CI are 3.7.2 only, from 55d9e4 on May 6th. New toolchains with bazel 4.1 were generated with commit 78588b on May 25th, but these build containers never went live.

**Comment by lizan** [comment]
@yanavlasov need to update image references in bunch of places otherwise ci script fails to detect clang locations.

**Comment by yanavlasov** [comment]
Obsoleted by PR #18220

**Pull request closed without merging**
