### PR TITLE
Cherry-pick of tracing: fix zipkin annotation timestamp serialization issue to 1.18

### PR DESCRIPTION
**Pull request by dmitri-d**
Cherry-pick of https://github.com/envoyproxy/envoy/pull/16073

### CODE REVIEW

**Comment by dmitri-d** [comment]
ping @lizan

**Comment by lizan** [comment]
Can you resolve conflicts? https://github.com/envoyproxy/envoy/pull/16089 had to be merged first.

**Comment by dmitri-d** [comment]
ping @lizan

**Pull request merged**
