### PR TITLE
cluster_manager: Make ClusterEntry a class instead of a struct

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
cluster_manager: Make 
Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl::ClusterEntry a class instead of a struct since it inherits from the class Upstream::ThreadLocalCluster. Made all members and two helper methods private. Private members required moving two small pieces of logic from ClusterManagerImpl::ThreadLocalClusterManagerImpl into helper methods of ClusterEntry, but the behavior is completely unchanged.

Also noticed that a method 'connPool' should have had an 'http' prefix to be parallel with the 'tcpConnPool' method. Finally, after doing this rename noticed that there were two methods named httpConnPool and two named tcpConnPool, but with different signatures. Renamed two of these to tcpConnPoolImpl and httpConnPoolImpl to make them easier to distinguish and make their intent clear.

Risk Level: Low - No behavior change
Testing: Existing tests because no behavior changed
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by DavidSchinazi — APPROVED** [review]
Nice cleanup!

**Review by alyssawilk — APPROVED** [review]
Nice clean up!

**Pull request merged**
