### PR TITLE
mobile: remove Python deps

### PR DESCRIPTION
**Pull request by jpsim**
These are no longer required because Envoy Mobile's Python bindings were removed in https://github.com/envoyproxy/envoy/pull/25479.

Commit Message:
Additional Description:
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @dependabot

**Comment by jpsim** [comment]
Marking as draft until I remove more Python things to fix the build.

**Pull request merged**
