### PR TITLE
bazel: Patch m1 support for v8

### PR DESCRIPTION
**Pull request by keith**
I've submitted this upstream as well, but this unblocks us temporarily.

Fixes https://github.com/envoyproxy/envoy/issues/19916

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Review by PiotrSikora — APPROVED** [review]
Thanks! Did you verify that Wasm tests pass with this build?

**Comment by keith** [comment]
WASM builds actually still fail for me, but this is one step closer. I'll have to debug the other issues another time

**Review by wrowe — APPROVED** [review]
Patch is fine, push this through to further refine wasm build troubleshooting

**Comment by wrowe** [comment]
It doesn't appear we are unique in fighting this; see slack for bazel;
https://bazelbuild.slack.com/archives/CGA9QFQ8H/p1647019715258589

**Pull request merged**
