### PR TITLE
http2: more cleanup in preparation for removing nghttp2 callbacks

### PR DESCRIPTION
**Pull request by birenroy**
This PR removes a few references to the `nghttp2_frame` type in codec API methods.

Commit Message: http2: more cleanup in preparation for removing nghttp2 callbacks
Additional Description:
Risk Level: low; refactoring, no functional change intended
Testing: ran unit and integration tests locally
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]
Nice cleanup

**Review by diannahu — APPROVED** [review]
Nice!

**Comment by birenroy** [comment]
Sorry, had to run the format fix script.

**Comment by birenroy** [comment]
I think this needs a final approval by a committer.

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by RyanTheOptimist** [comment]
> I think this needs a final approval by a committer.

*sigh* I enabled auto-merge but I guess I didn't re-approve. Done,

**Pull request merged**
