### PR TITLE
ossf: provide env-dependencies-policy

### PR DESCRIPTION
**Pull request by mmorel-35**
This completes https://clomonitor.io/docs/topics/checks/#dependencies-policy

Commit Message: Add policy-url for env-dependencies-policy
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by phlax — APPROVED** [review]
lgtm, thanks @mmorel-35

**Comment by mmorel-35** [comment]
cc @phlax ,
The next point I see would be to provide Software bill of materials (SBOM), see : https://github.com/ossf/security-insights-spec/blob/v1.0.0/specification.md#dependencies
Is it already possible or is this something to build ?

**Review by kfaseela — APPROVED** [review]

**Comment by phlax** [comment]
@kfaseela you were working on SBOM istio previously iirc - any guidance towards adding here?

**Comment by kfaseela** [comment]
> @kfaseela you were working on SBOM istio previously iirc - any guidance towards adding here?

Istio uses https://github.com/kubernetes-sigs/bom for generating sboms, but I think it supports only golang projects, and may not be useful for envoy. We might have to find out whether there are tools available with cpp support

**Comment by phlax** [comment]
ideally something using bazel - i think i looked at this before - there is an upstream ticket for adding support https://github.com/bazelbuild/bazel/issues/16331

**Pull request merged**
