### PR TITLE
ci: Fix flaky coverage limit

### PR DESCRIPTION
**Pull request by phlax**
this can currently fail in builds that dont change anything

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by jpsim — COMMENTED** [review]
+1 to unblock PRs but if we're at 96.0 already this just kicks the can very slightly down the road. Shouldn't we give more of a buffer like `95.0`?

**Review by jpsim — APPROVED** [review]

**Comment by phlax** [comment]
> Shouldn't we give more of a buffer like 95.0

probably yes - altho there is an intention of constantly pushing it up - not sure what leeway we should add

cc @alyssawilk

**Comment by jpsim** [comment]
I think Alyssa's out today so let's unblock at 96.0 and resume the discussion about how much buffer we should have next week.

**Comment by alyssawilk** [comment]
if we're seeing flakes I think we improve coverage not drop the bar 1% :-(

**Comment by jpsim** [comment]
> if we're seeing flakes I think we improve coverage not drop the bar 1% :-(

I don't think it was flaky, I think there were two PRs which individually were over 96.1 that when they were both merge to `main` went under 96.1.

**Comment by alyssawilk** [comment]
yeah I wasn't responding to this PR, which was a fix to a deterministic failure, I was responding to @jmarantz suggesting we drop a full point.
Do we know which 2 PRs they were so we can ask for more  unit testing?

**Comment by jpsim** [comment]
> I was responding to @jmarantz suggesting we drop a full point.

That was me in https://github.com/envoyproxy/envoy/pull/24320#pullrequestreview-1202759861

> Do we know which 2 PRs they were so we can ask for more unit testing?

I don't know which PRs reduced code coverage, but a motivated person could bisect `main` with code coverage with higher accuracy to see what changes increased vs decreased coverage.

Personally, I don't think it's realistic to say that no change can lower the code coverage amount, but that's my 2 cents.

**Comment by alyssawilk** [comment]
oh we regularly allow tweaks due to refactors that say remove code (and thus lower coverage)
what I don't like about this is it lowers coverage for each individual directory rather than exempting whatever was causing the underlying problem, which means we permanently lower the bar for the whole project.  I'll try to throw together a change I like better :-)

**Pull request merged**
