### PR TITLE
ci: fix CodeQL-build by removing deprecated set-env command

### LINKED ISSUE #14047: (ci) CodeQL-Build is failing in PR tests
*Title*: CodeQL-Build is failing in PR tests

*Description*: Tests seem to be failing for PRs with failures like [this](https://github.com/envoyproxy/envoy/pull/14025/checks?check_run_id=1408306295)
>Error: Unable to process command '::set-env name=BUILD_TARGETS::' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

*Repro steps*:
Create a new PR

### PR DESCRIPTION
**Pull request by tbarrella**
Commit Message:

ci: fix CodeQL-build by removing deprecated set-env command
    
Signed-off-by: Taylor Barrella <tabarr@google.com>

Additional Description: Tests seem to be failing for PRs with failures like [this](https://github.com/envoyproxy/envoy/pull/14025/checks?check_run_id=1408306295). Followed the example [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#example-6) to try to fix
Risk Level: Low
Testing: See if tests pass for this PR
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
Fixes #14047

### CODE REVIEW

**Review by asraa — COMMENTED** [review]
Thanks for fixing this! I think to test you can patch in the PR of failure (or make a modification in a source/common/http file to trigger a build), wait for codeql to pass that step, and then revert the commit.

**Comment by tbarrella** [comment]
Thank you! The failing step has been failing in all recent PRs I checked and was already run for this PR and succeeded; would the step run differently if I modified one of those files?

**Comment by asraa** [comment]
Yes that's correct -- the codeql build analyzes which files in the PR have changed, if it's one of the core files (like in source/common/http) it will build and analyze the changed target.
So this PRs codeql build is "empty"

**Comment by tbarrella** [comment]
Thank you! Looks like it's building all right, although the build step is taking a while; maybe it's ok to revert now?

**Comment by asraa** [comment]
Sounds good to me! Looks like its past the build step.

**Review by asraa — DISMISSED** [review]

**Comment by tbarrella** [comment]
Reverted. Thank you!

**Review by asraa — APPROVED** [review]

**Comment by tbarrella** [comment]
Marking this so that tests can pass in 1.16 backports, although maybe it's not a high priority
/backport

**Pull request merged**
