### PR TITLE
deps: Bump curl -> 7.79.0

### LINKED ISSUE #18051: com_github_curl has a newer release curl-7_78_0
*WARNING* com_github_curl has a newer release than curl-7_77_0@<2021-05-26 06:32:21>:curl-7_78_0@<2021-07-21 06:44:54>

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: deps: Bump curl -> 7.79.0
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #18051 
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by moderation** [comment]
Deps look fine. The patch we carry for Curl is a lot smaller than it used to be but was a prior source of Windows CI failures. Not sure if similar problems are being encountered here

**Comment by phlax** [comment]
ah, thanks, i didnt notice the patch, ill update

**Comment by phlax** [comment]
its the curl test that is failing https://dev.azure.com/cncf/envoy/_build/results?buildId=88066&view=logs&j=b840a642-5ff3-5357-2e4b-e06e40b0cffd&t=67965174-5100-5631-9dc0-68b9f0aacb53&l=1542

afaict the patch applies cleanly tho so its beyond my immediate understanding as to what is failing

**Comment by moderation** [comment]
@phlax 7.79.0 is out https://github.com/curl/curl/releases/tag/curl-7_79_0. Maybe you could bump to that version and see where CI is at?

**Comment by phlax** [comment]
seems to fall over for the same reason/s

checking the windows ci, afaict the test log publishing seems to be broke - ie it says there are test logs, but they dont get uploaded

its not clear exactly what happens with the test uploads, but it provides a link that 404s

cc @wrowe @davinci26

**Comment by asraa** [comment]
I think it's failing on this outstanding TODO
https://github.com/envoyproxy/envoy/blob/19a4823908b8e1952aae3c54e2cf4b08203112f4/test/dependencies/curl_test.cc#L33-L36

Maybe to remove that windows if/else? See https://github.com/envoyproxy/envoy/pull/13063/files

**Comment by phlax** [comment]
> Maybe to remove that windows if/else? 

thanks, ill give it a whirl

**Review by asraa — APPROVED** [review]
Pending CI

**Pull request merged**
