### PR TITLE
deps: update yaml-cpp to latest master

### PR DESCRIPTION
**Pull request by snowp**
This brings in some error message improvements that should simply envoy-mobile development, which relies heavily
on YAML anchors for configuration generation.

Signed-off-by: Snow Pettersen <snowp@lyft.com>

Commit Message:
Additional Description:
Risk Level: Low
Testing: Existing tests
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by moderation** [comment]
@snowp Was going to ask to use the latest release `0.7.0` but it looks like you are picking up a commit after that release? https://github.com/jbeder/yaml-cpp/compare/yaml-cpp-0.7.0...master

If we do want this post-release commit can we go to the latest https://github.com/jbeder/yaml-cpp/commit/b591d8ae2ad1ff373273c3e05973adf6c46abfa8 ?

**Comment by snowp** [comment]
Yeah I was trying to bring in this commit that landed recently, after the latest release. I think this is the latest commit on master? The one you linked seems to be related the commit released with the most recent release

**Comment by moderation** [comment]
Your commit is the latest. I just can't determine sorting order :smile: 

/lgtm deps

**Comment by snowp** [comment]
@asraa ptal when you get a chance

**Review by asraa — APPROVED** [review]
LGTM, feel free to merge!

**Pull request merged**
