### PR TITLE
Header2

### PR DESCRIPTION
**Pull request by bootsieh**
Commit Message: Adding a header for grpc-message-type to CustomHeaderValues.
Additional Description: N/a
Risk Level: low
Testing: unit 
Docs Changes: N/a
Release Notes: N/a
Platform Specific Features: N/a

### CODE REVIEW

**Review by ZiyangXiao — COMMENTED** [review]
Hi, just confused, when the code was looked at the code review side, why is there a strange character "" after the “;” ?

**Comment by bootsieh** [comment]
Ah thanks for catching that, removed the extra character.

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
