### PR TITLE
http: memory and perf fix for header appending

### PR DESCRIPTION
**Pull request by alyssawilk**
*Description*:
Fixes a bug where addViaMove wasn't clearing memory properly.
Also a perf improvement to addCopy(_, int)

*Risk Level*: Low 
*Testing*: regression integration test
*Docs Changes*: n/a
*Release Notes*: n/a

### CODE REVIEW

**Comment by alyssawilk** [comment]
Sure.  I'll whip up a fix to that right away, but I'd prefer to land it
separately in case someone else is depending on the old behavior of move.

**Comment by alyssawilk** [comment]
Ah, if we're going to want to have this assert, we either need to 
1) exclude reference HeaderStrings from the assert (which makes it dubiously useful IMO)
2) change HeaderString::clear() to always clear, not to exempt reference string or
3) write a different clear utility which actually clears reference strings.

I'd lean towards 2 because I find it weird that I can be handed a HeaderString, clear() it, and have empty() be false, but I also think it's a fairly dangerous change and this is clearly not my week.  Matt, any preference on your side?

**Comment by mattklein123** [comment]
> I'd lean towards 2 because I find it weird that I can be handed a HeaderString, clear() it, and have empty() be false, but I also think it's a fairly dangerous change and this is clearly not my week. Matt, any preference on your side?

Hmm, yeah. OK that makes sense. Yeah agreed there is no easy answer here. I'm OK skipping and just going w/ the integration test for coverage. Probably not worth the risk of another change? WDYT?

**Comment by alyssawilk** [comment]
Yeah, I think we should revisit how HeaderString works (again the fact that append just fails to work for reference HeaderStrings means folks have to really understand the internals before using it at all) but I think I'll save it for another day.

**Pull request merged**
