### PR TITLE
tls: Remove additional tracking on SSL_ERROR_SYSCALL

### PR DESCRIPTION
**Pull request by tyxia**
Even though this tracking of `SSL_ERROR_SYSCALL ` works well in `RsaKeyUsageVerificationEnforcementOn` test case, it seems cause some noise for the case that connection close error should be reported elsewhere in connection metrics.

Overall, this rsa_key_usage enforcement only affects client connection and `KEY_USAGE_BIT_INCORRECT` error is already correctly populated and checked in the test. i.e., server connection error in the test is not the focus.

Fix: #28415

### CODE REVIEW

**Review by ggreenway — APPROVED** [review]

**Comment by ggreenway** [comment]
@tyxia it looks like a build agent died and `retest` isn't re-triggering it. Can you push another commit (maybe merge main) to make CI run again?

**Comment by tyxia** [comment]
@phlax  That will be appreciated if you can help us re-trigger this presubmit failure (https://dev.azure.com/cncf/envoy/_build/results?buildId=147457&view=logs&s=4f7d954b-a765-565f-91a2-c04870dab43f&j=4930ecaf-18f4-5b3c-dea3-309729c3b3ae)

I have tried merge main but new CI failure shows up.

**Comment by phlax** [comment]
thanks for letting me know - i had hoped that this problem was resolved by an infra fix, but seems not (at least not totally)

i kicked ci - `/retest` should now work again btw

**Comment by phlax** [comment]
i see - it didnt work earlier - ill try and track why

**Comment by phlax** [comment]
> ill try and track why

nothing obvious - the bot didnt think anything needed retesting - ill watch and see if i can see a pattern

https://github.com/envoyproxy/envoy/actions/runs/6001902677/job/16277087230

**Comment by tyxia** [comment]
> > ill try and track why
> 
> nothing obvious - the bot didnt think anything needed retesting - ill watch and see if i can see a pattern
> 
> https://github.com/envoyproxy/envoy/actions/runs/6001902677/job/16277087230

Thank you for prompt response and help as always. Appreciate it!

**Pull request merged**
