### PR TITLE
Make backtrace logs a single log entry

### PR DESCRIPTION
**Pull request by ravenblackx**
Commit Message: Make backtrace logs a single log entry
Additional Description: Backtrace logs are often made unnecessarily hard to read by the fact that they are written as multiple log entries, which often ends up interleaved with other log entries from other threads. This change makes it so the backtrace is logged as a single multi-line log entry.
Before:
```
[2023-12-07 17:13:41.532][562126][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2023-12-07 17:13:41.532][562126][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: 0/1.29.0-dev/test/DEBUG/BoringSSL
[2023-12-07 17:13:41.570][562126][critical][backtrace] [./source/server/backtrace.h:96] #0: Envoy::Quic::ActiveQuicListenerFactory::createActiveQuicListener() [0x2bd7c60]
[2023-12-07 17:13:41.608][562126][critical][backtrace] [./source/server/backtrace.h:96] #1: Envoy::Quic::ActiveQuicListenerFactory::createActiveUdpListener() [0x2bd7b39]
[2023-12-07 17:13:41.645][562126][critical][backtrace] [./source/server/backtrace.h:96] #2: Envoy::Server::ConnectionHandlerImpl::addListener() [0x2a7549a]
[2023-12-07 17:13:41.684][562126][critical][backtrace] [./source/server/backtrace.h:96] #3: Envoy::Server::WorkerImpl::addListener()::$_3::operator()() [0x1d18157]
[etc.]
```
(these lines may be interleaved with other log entries and even other backtraces)
After:
```
[2023-12-07 17:13:41.532][562126][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
Envoy version: 0/1.29.0-dev/test/DEBUG/BoringSSL
#0: Envoy::Quic::ActiveQuicListenerFactory::createActiveQuicListener() [0x2bd7c60]
#1: Envoy::Quic::ActiveQuicListenerFactory::createActiveUdpListener() [0x2bd7b39]
#2: Envoy::Server::ConnectionHandlerImpl::addListener() [0x2a7549a]
#3: Envoy::Server::WorkerImpl::addListener()::$_3::operator()() [0x1d18157]
[etc.]
```
(or in json logs, multiple entries vs one entry)

Risk Level: Very low. May be a problem if there is a log entry size cap, or if some user has a log parser that relies on backtraces appearing in a specific format. (May merit a release note?) The apparent risk for some user having a log parser that relies on every newline-separation being followed by the full date-etc. log line is likely a non-issue since there exists other log output that contains newlines already. A cursory look at `stack_decode.py` suggests it would be equally able to parse either version.
Testing: Existing test passes.
Docs Changes: n/a
Release Notes: Not yet.
Platform Specific Features: n/a

### CODE REVIEW

**Comment by soulxu** [comment]
@ravenblackx do you have an example what the backtrace log looks like in the end? thanks!

**Comment by ravenblackx** [comment]
> @ravenblackx do you have an example what the backtrace log looks like in the end? thanks!

Added to the PR description.

**Comment by soulxu** [comment]
Yea, it indeed looks good! thanks!

I don't think user should depend on log parser. but it seems we have some test depends on it.

**Review by alyssawilk — APPROVED** [review]
but 
/wait on CI
which looks like a plausible real failure.

**Comment by ravenblackx** [comment]
I don't know what's up with the arm64 failing signals test - if I run that test in normal x64 debug mode in a dev container it fails on some absl mutex checker (before or after my change), and if I run it with `-c opt` it passes (before or after my change).

**Pull request closed without merging**
