### PR TITLE
contrib-sipproxy: Fix TRA Ut

### PR DESCRIPTION
**Pull request by durd07**
Signed-off-by: Felix Du <durd07@gmail.com>

Commit Message: Fix TRA Ut
Additional Description:
Risk Level: Low
Testing: Ut
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by daixiang0** [comment]
@phlax now we do not run contrib tests in CI, if codes only cover changes under contrib, how about only test format and skip unit tests since all unit tests are not changed.

**Comment by phlax** [comment]
not sure if i follow entirely @daixiang0 - either way i will leave it to @ggreenway as i believe he will have a better understanding of what is being changed and any necessity or otherwise

**Comment by durd07** [comment]
@ggreenway Could you please help to review?
Thanks in advance.

**Comment by durd07** [comment]
@ggreenway

**Comment by adisuissa** [comment]
@ggreenway can you PTAL?

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
