### PR TITLE
entensions/filters/http/ext_authz: Added connection level metadata

### LINKED ISSUE #25762: envoy.filters.http.ext_authz: ability to pass connection metadata in authz request
*Title*: *Add ability to pass connection metadata in authz request*

*Description*:
External Authorization http extension currently supports passing dynamic filter metadata related to http request. I would like to propose a capability to pass downstream connection dynamic metadata typically added by transport socket extensions.

A particular problem I'm trying to solve is propagation of `envoy.transport_socket.peer_information/peer_identity` from [extensions.transport_sockets.alts.v3.Alts ](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/alts/v3/alts.proto.html#extensions-transport-sockets-alts-v3-alts) to the authorization checks.

I see 2 options: 
1. In [ext_authz.cc](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/ext_authz/ext_authz.cc#L46-L66) walk through both `decoder_callbacks_->streamInfo().dynamicMetadata()` and `decoder_callbacks_->connection()->streamInfo().dynamicMetadata()` to populate `filter_metadata` and `typed_filter_metadata` fields in authz request. Request metadata should take precedence in an *unlikely case* when the same namespace is present in both connection metadata and requests metadata. Optionally this behaviour can be only enabled using an extra flag in configuration.

1. Add `connection_metadata_context_namespaces` and `connection_typed_metadata_context_namespaces` fields to [extensions.filters.http.ext_authz.v3.ExtAuthz proto](https://github.com/envoyproxy/envoy/blob/bfa849bc598870033dbbc11ae17c9abb273e19e5/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L87-L107); and add `connection_metadata_context` field to the [auth attribute_context proto](https://github.com/envoyproxy/envoy/blob/42f82c257a049589b5c15788c774342268124921/api/envoy/service/auth/v2/attribute_context.proto#L160).

Happy to implement it myself after discussing the options above.

*Relevant Links*:
- `metadata_context_namespaces` in https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#extensions-filters-http-ext-authz-v3-extauthz

### PR DESCRIPTION
**Pull request by derpferd**
Commit Message: Added connection level metadata. Fixes #25762
Additional Description: Took the approach outlined as option 2 in #25762
Risk Level: low
Testing: Unit tests added and manually ran local end to end test.
Docs Changes: Updated proto comment
Release Notes: Updated
Platform Specific Features: N/A

Related to #27612 which implemented option 1

### CODE REVIEW

**Comment by derpferd** [comment]
@tyxia and @adisuissa have the best context to review this PR since they already looked at #27612

**Comment by tyxia** [comment]
/wait

@derpferd The CD/CI failures seems to be legit. Please take a look first

**Comment by derpferd** [comment]
Sorry for the delay, fixed the CD/CI failures. @tyxia

**Comment by wbpcode** [comment]
cc @adisuissa could you take a look this PR for the API when you have free time?

**Comment by alyssawilk** [comment]
@adisuissa ping?

**Review by tyxia — APPROVED** [review]
LGTM Thanks!

**Pull request closed without merging**
