### PR TITLE
deps: Bump `ubuntu-build-image:base` -> 458cb49ca

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
this should fix the missing `run-clang-tidy.py` issue cc @KBaichoo @adisuissa 

cc @jpsim for mobile updates

**Review by KBaichoo — DISMISSED** [review]

**Review by jpsim — DISMISSED** [review]
+1

Either here or I can do as a followup, we should update the `mobile-f52df4a4e1e2ecbcda42eb2f27a1550b6c53eef0` tags to point to `mobile-458cb49ca2013c0ccf057d00ad1d4407920c4e52` so the next time we go to bump, we find all of them when grepping.

**Comment by phlax** [comment]
@jpsim updated, hopefully correctly

**Review by jpsim — APPROVED** [review]
+1, CI willing

**Pull request merged**
