### PR TITLE
util: move the LockGuards out of the pure thread interface, and into their own library.

### PR DESCRIPTION
**Pull request by jmarantz**
*Description*:
>Seemed wrong that all the lock guard variants were in the interface.  They couldn't go into source/common/common/thread.h due to a cyclic dependency with logging.  It also meant that lock-guards can't have ASSERTs in them, which I think is still true.  But that may be fixable by moving one single-use LockGuard variant out of lock_guard.h and into logging.cc.

> This helps set the stage for adding a CondVar support into the system, so we can annotate mutexes that are used with condvars.

*Risk Level*: Low
*Testing*: //test/...
*Docs Changes*: N/A
*Release Notes*: N/A

### CODE REVIEW

**Comment by zuercher** [comment]
@jmarantz let me know if you want help debugging the mac build failure

**Comment by zuercher** [comment]
It uses Apple's version of clang from Xcode They've both modified it from the public release and also obscure what that version is.

**Comment by jmarantz** [comment]
I wonder if it's better to just ifdef out the thread annotations on Mac then?  I understand why it's complaining about that line, and I suspect we are really operating here on the edge of what we expect the static analysis framework to discover, in the presence of unlock() calls inside an if-statement.  Rather than debug this with multiple clang variants, do you think it makes sense to just rely on the mainline CI to detect any issues?

And really do not understand why it was successful analyzing these prior to this PR, and not now.

**Comment by zuercher** [comment]
Ah, yes. The back of my mind was trying to remind we that we ran into this before:

https://github.com/envoyproxy/envoy/blob/master/source/common/common/thread_annotations.h

**Comment by zuercher** [comment]
I got it to compile by copying the ifdef from thread_annotations.h into `include/envoy/thread.h` (to make sure it was applied in all cases). Given the right include ordering it'll fix the error.

**Comment by jmarantz** [comment]
ok that makes sense.  that must have been getting pulled in before, and not now.  will fix.

**Comment by jmarantz** [comment]
That worked, @zuercher -- thanks!

**Pull request merged**
