### PR TITLE
ci: running E-M CI on workflow changes

### PR DESCRIPTION
**Pull request by alyssawilk**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by alyssawilk** [comment]
oh wait @phlax we won't run with new files in any case, right?

**Comment by phlax** [comment]
yeah - thats correct - it would trigger the ci but not with the updated config

i considered doing this myself - but then thought better of it

atm the best place to test workflow changes is in staging - i have a vague idea about adding some kinda label - something like ci/trusted - so that it does read these files - but it adds quite a lot of complexity and would be less secure

**Comment by alyssawilk** [comment]
ah ok.  I think I need a different change then.

you know how we pulled all the bazelrc options out so that we could have CI run when we changed bazel flags?

the file removals in mobile perf
https://github.com/envoyproxy/envoy/blob/main/.github/workflows/mobile-perf.yml#L66
are pretty important to test with the CLs that change them.  Would you be able to throw together a PR to move that file list out of .github/workflows/ and into mobile/somethingorother so it will auto-trigger CI and run with new removals?  If it's not something you can easily do offhand I'll look into it.

**Comment by phlax** [comment]
> move that file list out of .github/workflows/ and into mobile/somethingorother

it wouldnt trigger - github workflows **have** to be in `.github/workflows`

**Comment by phlax** [comment]
> you know how we pulled all the bazelrc options out so that we could have CI run when we changed bazel flags?

also just to clarify - the main motivation for doing this (there were a few) is that `.bazelrc` is **read** by the PR CI - not just triggered by change

its very much by design that the CI doesnt allow you to change anything in `.github` (other than build images in config.yml) as this is what secure the secrets that they can access

**Comment by alyssawilk** [comment]
> > move that file list out of .github/workflows/ and into mobile/somethingorother
> 
> it wouldnt trigger - github workflows **have** to be in `.github/workflows`

sorry I think I didn't explain well.  I want the workflow file to stay where it is.  I want the
"rm file A B C"  logic linked to be moved out of the workflow file so when we want to also `rm D`, the workflow runs removing D.
make sense?

**Comment by phlax** [comment]
not sure how best to resolve that - in envoy we have do_ci.sh which kinda allows for more to be done as part of a job (ie beyond the bazel command)

perhaps we could put that source script into `mobile/remove-files-for-ci.sh` or similar and just trigger that from there

**Pull request closed without merging**
