### PR TITLE
ci: Improve release publishing

### PR DESCRIPTION
**Pull request by phlax**
This PR adds a job to create a tarball containing the signed binaries for publishing

The tarball is then passed in a subsequently to the actual release/publishing job, which passes it to the python publishing tool for upload to the github release

In non-release CI, the above steps are followed, but the python tool is in "dry run" mode

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
i kinda wanted to land the verify pr first, as this will slightly increase ci time otherwise, but i think this is gtg so probs best to land it first

**Comment by phlax** [comment]
for ref this adds 2 new jobs

the first signs the binaries in prs/ci/etc 

```console
PackageSigningRunner WARNING No GPG name/email supplied, signing with first available key
PackageSigningRunner NOTICE Signing bins (Envoy CI <envoy-ci@for.testing.only>) /tmp/tmpb1d9s3ty/bin
PackageSigningRunner NOTICE Sign package (bin): envoy-contrib-aarch_64 034a96e09f6e4e56486dd7105bcb4e73d37c38a21180528970253f6ce7d6b3ae
PackageSigningRunner NOTICE Sign package (bin): envoy-x86_64 7abfa9046ae29175bfcf3da8e6738c80fb5cd91427b56b7533f3bf58bc7a7ba2
PackageSigningRunner SUCCESS Successfully signed packages: bazel-out/k8-fastbuild/bin/distribution/release.signed.tar.zst
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

034a96e09f6e4e56486dd7105bcb4e73d37c38a21180528970253f6ce7d6b3ae  /tmp/tmpb1d9s3ty/bin/envoy-contrib-aarch_64
7abfa9046ae29175bfcf3da8e6738c80fb5cd91427b56b7533f3bf58bc7a7ba2  /tmp/tmpb1d9s3ty/bin/envoy-x86_64
610b7cc2f579642b64294a610c8bbcac1b7a4d0f718daee81e9db7e9dc00f953  /tmp/tmpb1d9s3ty/bin/envoy-contrib-x86_64
0333fdb850bfa99bdcf827a212c2ea5a211b822a84d8aeb3eb9b91a29c819e90  /tmp/tmpb1d9s3ty/bin/envoy-aarch_64
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEpvNs9941tiJvg33TH/NucDTA5NMFAmRrtw4ACgkQH/NucDTA
5NOw/A//VgR3CVYHPmwc1WtvhsvVC+nrV/zRDmzlrK7zJkxBy5JtFc9j5xN3sRSS
BavWlbiJIlJz3RkKkVkvLRpBJQOsANWnl9OP7gOu+iMxGh10PQNw8By5rrG+KB3y
jXsZBIUstdsK+L/nAZ/NKEOslEGz3UGUKzgCncUgFEl1j5Zk6NkkzhZPn5rSgC5l
RjFQg1+v7XZIKkzYaGG+1U1tuuAq7pI08oCTZMkhW+AS0ptuaXPb4pP69ZtJqQN6
XcGElXEwAAZVAKwXhrzOdUj8xRKNzLheVlGek1s5jMtLEIGez0n618rBKcEmb3Hx
tV0P8NECSoBB7i8WlXsXMobM/KBB5lZUUGQ6VYLF4wDkMFCPySCTxX+bauFBIq4r
NWlL4thbr+rV5n7SRnw/mvX302VMfpHzDS7M4pa/qNr0oLl3mCMcjnfyOWSpKXqB
JAKDKLHwjUPF7ZhIzSlGsK4A+pFvgkBQ9v5bhDKi3Ll4l0He6GY481rwAy3DK1qv
4/NtxyCTVGZJN/bZXYGDOEir4AGYFmagsjWIahj1i52tE9VNMaB7+MW/RA/B/uTd
xRU0PX2Qu1N13RP/3fXtl+fDcIDOrUAkmsv5ZnAEs7ZG6OPCt9biEc8FKpzKL1wm
s2mleZ5JMAwDJ/jQTupSewgF05hd6NP5RIwA/4oWDyzbHZHARck=
=reK5
-----END PGP SIGNATURE-----

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=138056&view=logs&j=0863746b-e40a-55de-f6e1-18e52fb62c37&t=3494e404-9a97-50ce-fe9c-bffb3b40b387&l=63


and the second exercises the release code (dry run for prs/non-release) 

```console

ProjectRunner SUCCESS [release] Release (v1.27.0.dev0) created (dry run) from branch/commit: d3e2d2a21690f365bcaa8cbb237e35f1e19de1b4
ProjectRunner SUCCESS [release] Artefact uploaded (dry run): envoy-contrib-x86_64 -> test://releases/v1.27.0.dev0/assets/envoy-contrib-x86_64
ProjectRunner SUCCESS [release] Artefact uploaded (dry run): checksums.txt.asc -> test://releases/v1.27.0.dev0/assets/checksums.txt.asc
ProjectRunner SUCCESS [release] Artefact uploaded (dry run): envoy-x86_64 -> test://releases/v1.27.0.dev0/assets/envoy-x86_64
ProjectRunner SUCCESS [release] Artefact uploaded (dry run): envoy-aarch_64 -> test://releases/v1.27.0.dev0/assets/envoy-aarch_64
ProjectRunner SUCCESS [release] Artefact uploaded (dry run): envoy-contrib-aarch_64 -> test://releases/v1.27.0.dev0/assets/envoy-contrib-aarch_64
ProjectRunner NOTICE Repo published (dry run): test://releases/v1.27.0.dev0

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=138056&view=logs&j=c3151471-55a8-5b61-e074-57a04a750451&t=ce30ed27-269d-526f-b086-9584a29f4a67&l=43

**Review by htuch — COMMENTED** [review]
LGTM, but two things:
1. Can you add a detailed commit message to explain what is going on? The "improve" here is not super descriptive.
2. Given the sensitivity here around this being about signed releases, can you manually verify if you haven't that we see the same before / after artifacts?

**Comment by htuch** [comment]
(for (2) I'm really talking about the place we did some refactoring for the GPG stuff, not the new stuff)

**Comment by phlax** [comment]
> Given the sensitivity here around this being about signed releases, can you manually verify if you haven't that we see the same before / after artifacts?

there was no artefact before this PR, other than those published to the github release

This separates out the signing as its own part of the pipeline that produces signed binaries. This was done partly as when a release fails currently its non-trivial to complete by hand - this will make it so, altho, as it will also be tested more fully, i suspect that this will no longer be necessary so often

the sensitivity here is that in non-release, postsubmit ci, it will produce signed `-dev` binaries (cf #27179 )

**Comment by phlax** [comment]
fwiw the gpg refactoring was mostly completed in #27080 

as a result the gpg signing mechanism is now well-tested in existing CI

there are some iterations i want to make to this pr, esp involving the signed artefact that is produced, but these require further toolshed dev, or are pretty much standalone changes (include deb files in the signed bins eg) - so ive kept these as iterations

**Review by wbpcode — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
