### PR TITLE
xds: don't allow multiple instances of a locality in the same priority

### PR DESCRIPTION
**Pull request by markdroth**
Signed-off-by: Mark D. Roth <roth@google.com>

Commit Message: xds: don't allow multiple instances of a locality in the same priority
Additional Description: This is a documentation-only change.  gRPC is a bit more restrictive here than Envoy is.  This changes the documented requirement to match gRPC's restriction but does not change Envoy's implementation, with the goal being to converge on the more restrictive behavior in the long term but not break anything in the short term.
Risk Level: Low
Testing: N/A
Docs Changes: Included in PR
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by wrowe** [comment]
/retest

If this does not resolve, @markdroth please merge main (even an empty commit should trigger a new build which will cause a CI run against the current main.)

**Comment by adisuissa** [comment]
@markdroth is there an issue tracking the convergence to the restrictive behavior?

**Comment by markdroth** [comment]
No, there isn't, but feel free to create one.

The main thing I'm after here is defining the API semantics such that the same locality does not repeat in the same priority.  If Envoy's implementation is a bit more permissive than the API spec, that's not the end of the world.  I just don't want new people implementing their xDS servers in a way that doesn't work for gRPC clients.

**Comment by adisuissa** [comment]
> No, there isn't, but feel free to create one.
> 
> The main thing I'm after here is defining the API semantics such that the same locality does not repeat in the same priority. If Envoy's implementation is a bit more permissive than the API spec, that's not the end of the world. I just don't want new people implementing their xDS servers in a way that doesn't work for gRPC clients.

Opened #20768 to track this.

**Review by adisuissa — APPROVED** [review]
/lgtm api

Should be merged once CI is green.

**Pull request merged**
