### PR TITLE
Fix a small typo

### PR DESCRIPTION
**Pull request by hs0210**
Signed-off-by: Hu Shuai <hus.fnst@fujitsu.com>

Commit Message: Fix a small typo
Additional Description: agression --> aggression

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by RyanTheOptimist** [comment]
@snowp this is trivial and I'd be inclined to merge it myself, but my understanding is that Sr. Maintainer review is always required, so over to you :)

**Comment by yanavlasov** [comment]
> @snowp this is trivial and I'd be inclined to merge it myself, but my understanding is that Sr. Maintainer review is always required, so over to you :)

@RyanTheOptimist senior maintainer review is not required. If you feel like the PR is good to go, just merge it. I only request additional review if I'm uncertain about the change and need second opinion.

**Pull request merged**
