### PR TITLE
Add clang-tidy rule to enforce lower camelCase naming of function

### PR DESCRIPTION
**Pull request by marcomagdy**
Description:
clang-tidy v9 added more identifier name checks. FunctionCase is one of the newer ones that will avoid churn during code reviews.
When running clang-tidy locally, it caught one file with PascalCase functions in the benchmark tests. The fix for that file is part of this patch.

Risk Level: Low
Testing: local run of clang-tidy
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by mattklein123** [comment]
Note that clang-tidy CI is actually broken right now. See https://github.com/envoyproxy/envoy/issues/9512. I would really love to get this fixed but I'm not sure what the current status is.

**Comment by marcomagdy** [comment]
Until we fix `clang-tidy` CI, this PR is still helpful if you're running `clangd` with your IDE.

**Comment by marcomagdy** [comment]
ping @lizan can we merge this one now?

**Comment by lizan** [comment]
Let's run this on fixed clang-tidy pipeline :)

**Comment by marcomagdy** [comment]
`test/common/buffer/buffer_speed_test.cc:5:10: error: 'benchmark/benchmark.h' file not found [clang-diagnostic-error]` Is this something that would be fixed by merging from master?

**Comment by marcomagdy** [comment]
@derekargueta @lizan ping

**Comment by derekargueta** [comment]
yeah merge master to pick up clang-tidy fixes. I'm not 100% sure about `benchmark.h`, but merging master is a safe operation. If it doesn't work with the clang-tidy fixes we can debug further.

**Pull request merged**
