### PR TITLE
deps: Bump `aspect_bazel_lib` -> 1.24.2

### LINKED ISSUE #25301: Newer release available `aspect_bazel_lib`: v1.24.2 (current: v1.23.3)
Package Name: aspect_bazel_lib@1.23.3
Current Version: v1.23.3@2023-01-17
Available Version: v1.24.2@2023-02-02
Upstream releases: https://github.com/aspect-build/bazel-lib/releases

### PR DESCRIPTION
**Pull request by phlax**
Fix #25301 

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
/assign @adisuissa

... for maintainer stamp

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
