### PR TITLE
Updates the default value of StreamDataFrameSource::send_fin_ to false

### PR DESCRIPTION
**Pull request by birenroy**
This addresses error logs from the oghttp2 library such as the following:
```
external/com_github_google_quiche/quiche/http2/adapter/oghttp2_session.cc:996] DataFrameSource will send fin, preventing trailers!
```

Tested via:
```
$ bazel test --nocache_test_results //test/integration/... test/common/http/http2/...
INFO: Invocation ID: f484fe47-be31-4370-a7f1-1b4bc3ce7e2c
INFO: Analyzed 422 targets (0 packages loaded, 639 targets configured).
INFO: Found 320 targets and 102 test targets...
INFO: Elapsed time: 459.412s, Critical Path: 457.71s
INFO: 185 processes: 186 remote.
INFO: Build completed successfully, 185 total actions

Executed 102 out of 102 tests: 102 tests pass.
```

The log line reproduced in //test/integration:filter_integration_test. I was able to find instances when running the test via:
```
$ bazel test //test/integration:filter_integration_test --test_filter='*DecodeTrailers*' --test_arg="-l trace"
```

Before:
```
[2023-11-15 19:12:42.646][19][trace][connection] [source/common/network/raw_buffer_socket.cc:70] [Tags: "ConnectionId":"20"] write returns: 110
[2023-11-15 19:12:42.646][19][trace][connection] [source/common/network/connection_impl.cc:529] [Tags: "ConnectionId":"20"] writing 1033 bytes, end_stream false
[2023-11-15 19:12:42.646][19][trace][http2] [source/common/http/http2/codec_impl.cc:1209] [Tags: "ConnectionId":"20"] sent frame type=0, stream_id=1, length=1024
[2023-11-15 19:12:42.646][19][trace][connection] [source/common/network/connection_impl.cc:614] [Tags: "ConnectionId":"20"] socket event: 2
[2023-11-15 19:12:42.646][19][trace][connection] [source/common/network/connection_impl.cc:737] [Tags: "ConnectionId":"20"] write ready
[2023-11-15 19:12:42.646][19][trace][connection] [source/common/network/raw_buffer_socket.cc:70] [Tags: "ConnectionId":"20"] write returns: 1033
[2023-11-15 19:12:42.646][19][trace][connection] [source/common/network/connection_impl.cc:529] [Tags: "ConnectionId":"20"] writing 1033 bytes, end_stream false
[2023-11-15 19:12:42.646][19][trace][http2] [source/common/http/http2/codec_impl.cc:1209] [Tags: "ConnectionId":"20"] sent frame type=0, stream_id=1, length=1024
[2023-11-15 19:12:42.646][19][trace][connection] [source/common/network/connection_impl.cc:614] [Tags: "ConnectionId":"20"] socket event: 2
[2023-11-15 19:12:42.646][19][trace][connection] [source/common/network/connection_impl.cc:737] [Tags: "ConnectionId":"20"] write ready
[2023-11-15 19:12:42.646][19][trace][connection] [source/common/network/raw_buffer_socket.cc:70] [Tags: "ConnectionId":"20"] write returns: 1033
[2023-11-15 19:12:42.646][19][error][quic] [external/com_github_google_quiche/quiche/http2/adapter/oghttp2_session.cc:996] DataFrameSource will send fin, preventing trailers!
[2023-11-15 19:12:42.646][19][trace][http2] [source/common/http/http2/codec_impl.cc:1316] [Tags: "ConnectionId":"20"] about to send frame type=1, flags=5
[2023-11-15 19:12:42.646][19][trace][http2] [source/common/http/http2/codec_impl.cc:1338] [Tags: "ConnectionId":"20"] send data: bytes=20
[2023-11-15 19:12:42.646][19][trace][connection] [source/common/network/connection_impl.cc:529] [Tags: "ConnectionId":"20"] writing 20 bytes, end_stream false
[2023-11-15 19:12:42.646][19][trace][http2] [source/common/http/http2/codec_impl.cc:1209] [Tags: "ConnectionId":"20"] sent frame type=1, stream_id=1, length=11
[2023-11-15 19:12:42.646][19][debug][client] [source/common/http/codec_client.cc:141] [Tags: "ConnectionId":"20"] encode complete
```

After:
```
[2023-11-15 19:27:00.823][18][trace][connection] [source/common/network/raw_buffer_socket.cc:70] [Tags: "ConnectionId":"20"] write returns: 110
[2023-11-15 19:27:00.823][18][trace][connection] [source/common/network/connection_impl.cc:529] [Tags: "ConnectionId":"20"] writing 1033 bytes, end_stream false
[2023-11-15 19:27:00.823][65][trace][http2] [source/common/http/http2/codec_impl.cc:1819] Codec does not have Metadata frame support.
[2023-11-15 19:27:00.823][18][trace][http2] [source/common/http/http2/codec_impl.cc:1209] [Tags: "ConnectionId":"20"] sent frame type=0, stream_id=1, length=1024
[2023-11-15 19:27:00.823][18][trace][connection] [source/common/network/connection_impl.cc:614] [Tags: "ConnectionId":"20"] socket event: 2
[2023-11-15 19:27:00.823][18][trace][connection] [source/common/network/connection_impl.cc:737] [Tags: "ConnectionId":"20"] write ready
[2023-11-15 19:27:00.823][18][trace][connection] [source/common/network/raw_buffer_socket.cc:70] [Tags: "ConnectionId":"20"] write returns: 1033
[2023-11-15 19:27:00.823][18][trace][connection] [source/common/network/connection_impl.cc:529] [Tags: "ConnectionId":"20"] writing 1033 bytes, end_stream false
[2023-11-15 19:27:00.823][18][trace][http2] [source/common/http/http2/codec_impl.cc:1209] [Tags: "ConnectionId":"20"] sent frame type=0, stream_id=1, length=1024
[2023-11-15 19:27:00.823][18][trace][connection] [source/common/network/connection_impl.cc:614] [Tags: "ConnectionId":"20"] socket event: 2
[2023-11-15 19:27:00.823][18][trace][connection] [source/common/network/connection_impl.cc:737] [Tags: "ConnectionId":"20"] write ready
[2023-11-15 19:27:00.823][18][trace][connection] [source/common/network/raw_buffer_socket.cc:70] [Tags: "ConnectionId":"20"] write returns: 1033
[2023-11-15 19:27:00.823][18][trace][http2] [source/common/http/http2/codec_impl.cc:1316] [Tags: "ConnectionId":"20"] about to send frame type=1, flags=5
[2023-11-15 19:27:00.823][18][trace][http2] [source/common/http/http2/codec_impl.cc:1338] [Tags: "ConnectionId":"20"] send data: bytes=20
[2023-11-15 19:27:00.823][18][trace][connection] [source/common/network/connection_impl.cc:529] [Tags: "ConnectionId":"20"] writing 20 bytes, end_stream false
[2023-11-15 19:27:00.824][18][trace][http2] [source/common/http/http2/codec_impl.cc:1209] [Tags: "ConnectionId":"20"] sent frame type=1, stream_id=1, length=11
[2023-11-15 19:27:00.824][18][debug][client] [source/common/http/codec_client.cc:141] [Tags: "ConnectionId":"20"] encode complete
```

Commit Message: fixes an integration issue with oghttp2 in codec_impl.cc.
Additional Description:
Risk Level: low
Testing: $ bazel test //test/integration/... test/common/http/http2/...
Docs Changes:
Release Notes:
Platform Specific Features: n/a

### CODE REVIEW

**Comment by birenroy** [comment]
FYI @JuniorHsu I think this PR should fix the logging issue you're seeing.

**Review by RyanTheOptimist — DISMISSED** [review]
Wow, awesome! Thanks for doing this. Can you clarify if this is a behavior change at all, or simply a logging change? I think it's the latter...

**Review by alyssawilk — DISMISSED** [review]
LGTM modulo I'd like a tracking bug for at least a unit test - maybe we can find one which currently has the log and EXPECT_LOG it?

**Comment by birenroy** [comment]
> LGTM modulo I'd like a tracking bug for at least a unit test - maybe we can find one which currently has the log and EXPECT_LOG it?

Done. Please see https://github.com/envoyproxy/envoy/pull/30980 which adds the log expectation without changing functionality. This PR then updates the expectation.

**Review by alyssawilk — DISMISSED** [review]

**Comment by RyanTheOptimist** [comment]
Looks good, though it looks like it needs a main merge?

**Comment by birenroy** [comment]
> Looks good, though it looks like it needs a main merge?

Done, thank you.

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by abscondment** [comment]
Hey folks: can you confirm that this is a behavior change/bugfix?

Should it be backported to v1.28? As of 63b0cb8a0aff65bcfa118f6bea4af147d6771fd3, it's not part of that release branch.

**Comment by birenroy** [comment]
> Hey folks: can you confirm that this is a behavior change/bugfix?
> 
> Can/should it be backported to v1.28? As of [63b0cb8](https://github.com/envoyproxy/envoy/commit/63b0cb8a0aff65bcfa118f6bea4af147d6771fd3), it's not part of that release branch.

It is a bugfix for oghttp2. In the v1.28 default configuration, oghttp2 is not enabled, so I don't expect this to affect many deployments. There have been other oghttp2 fixes since then, so hopefully anyone enabling oghttp2 will be running v1.29 or tip of tree.

**Comment by abscondment** [comment]
@birenroy thanks for the clarification.

So it sounds like oghttp2 bugfixes are not being backported to the active major release branches. Bummer.

I've been evaluating enabling oghttp2 in an istio v1.20 / envoy v1.28 deployment, since the option `http2_use_oghttp2=true` is available, and appears to resolve an ongoing issue we're experiencing with nghttp2. That seems a lot riskier to me now.

**Comment by alyssawilk** [comment]
As as @birenroy pointed out offline, it's kinda tricky to do this as some of the fixes are in Envoy's dependencies.  I think we'll focus on making sure all the fixes make the upcoming release due in 3-4 weeks, and you can try flipping oghttp2 on in that one.

**Pull request merged**
