### PR TITLE
doc: update doc on original destination lb

### LINKED ISSUE #11664: How is original destination lb being supported by v3?
In v2 API, to use original destination lb, one needs to set both:
cluster.lb_policy -> ORIGINAL_DST_LB
cluster.type -> ORIGINAL_DST

Now in v3 API, ORIGINAL_DST type is still available, but ORIGINAL_DST_LB is not in lb_policy anymore.

Is this feature still supported in v3? If so, how should one configure?

BTW, the doc says: "Original destination service discovery must be used with the original destination load balancer. "
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery#arch-overview-service-discovery-types-original-destination

### PR DESCRIPTION
**Pull request by fuqianggao**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes #11664 
cc/ @junr03 @mattklein123

### CODE REVIEW

**Comment by mattklein123** [comment]
Sorry this is still not working for some reason, and DCO is broken. Please squash/rebase onto current master and force push and let's try that?

**Comment by mattklein123** [comment]
@fuqianggao it's still not running. Please squash all commits into a single commit and rebase onto current master. You are 38 commits behind.

/wait

**Comment by fuqianggao** [comment]
> @fuqianggao it's still not running. Please squash all commits into a single commit and rebase onto current master. You are 38 commits behind.
> 
> /wait

sorry about that. Done.

**Comment by mattklein123** [comment]
I am at a loss of why Circle is not running the jobs. @lizan any idea?

**Comment by mattklein123** [comment]
@fuqianggao I tried locally and this patch fails the doc build. Can you verify it works locally and open a fresh PR that is fully up to date? Hopefully that will work.

**Pull request closed without merging**
