### PR TITLE
fix problematic link

### PR DESCRIPTION
**Pull request by cuishuang**
Original link 404, use the latest

### CODE REVIEW

**Review by phlax — APPROVED** [review]
lgtm, thanks @cuishuang

**Comment by ramaraochavali** [comment]
@cuishuang curious are you using s2a with Envoy? We are evaluating s2a for
a use case where we want to offload Tls termination.  So curious to learn
any experience?

**Comment by phlax** [comment]
@adisuissa would you mind giving this an api stamp

**Review by phlax — APPROVED** [review]
landing this as its a minor docs-only change and i believe correct

lgtm, thanks @cuishuang

**Pull request merged**
