### PR TITLE
router: HeaderFormatter -> CustomHeaderFormatter

### PR DESCRIPTION
**Pull request by auni53**
router: HeaderFormatter -> CustomHeaderFormatter
* Rename this to avoid confusion with other formatters. All of this code is specific to custom headers.

Risk-level: Low
Testing: No dependencies on these libraries outside of router tests

See #11321.

### CODE REVIEW

**Comment by mattklein123** [comment]
Sorry just so I'm clear, how is this related to "custom" headers? Also, if we are going to move, can we move into the new formatters directory structure that @qiwzhang just made with the hope of ultimately unifying this code as much as possible? Thank you!

/wait

**Comment by mattklein123** [comment]
> I thought about whether it should be moved to a common folder, but this is all very specific to the router, custom header lookups aren't handled anywhere else in the codebase. What do you think?

I suspect we will end up using this elsewhere, potentially even in the local reply system. For example, why not allow people to send headers in local replies that have substitutions? Additionally, there is a mountain of code here that I think can be shared with the other substitution formatter. My preference is to move it even if we don't clean up duplication yet. @qiwzhang wdyt?

**Comment by auni53** [comment]
That's fine by me, I just don't really have the context about who would use it in the future and all. If I can get some input on location and naming that would be helpful. Like would they still be called custom headers in the local reply context? Would something like HeaderExpander or HeaderVariables be clearer?

**Comment by mattklein123** [comment]
I think we should move here: https://github.com/envoyproxy/envoy/tree/master/source/common/formatter, and probably just keep calling it header_formatter, but I don't feel that strongly about it.

Either way you will see that there is a lot of overlap with the other substitition formatter/string already in that directory, some TODOs to merge would be nice.

**Comment by qiwzhang** [comment]
Agreed with @mattklein123 , just move the code to "source'common/formatter" folder first, and we can do the rename later.

**Comment by auni53** [comment]
Should [header_parser.cc](https://github.com/envoyproxy/envoy/blob/master/source/common/router/header_parser.cc) be moved too?

**Comment by mattklein123** [comment]
@auni53 yes I would move it also. There is a lot of related work that can be merged in these two systems including moving to a real parser grammar, sharing code, etc.

**Pull request closed without merging**
