### PR TITLE
ci/deps: Fix ci failure due to upstream repo issues

### LINKED ISSUE #29926: Dependency checker appears to have broke
annoyingly i was testing related ci and was initially confounded as to what i had broke

it seems that it may be an issue with one of our deps disappearing or somesuch - not sure - as i have not been able to repro locally so far, but more ci seems to be failing

### PR DESCRIPTION
**Pull request by phlax**
Currently the dep checker fails as our ref to the edenhill lib uses an expired redirect

this updates the ref, and also the dep checker which now has better err handling for this situation

Fix #29926 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by ravenblackx — APPROVED** [review]

**Comment by phlax** [comment]
arggh - this still breaks:

```console
 DependencyChecker ERROR [releases] Check disabled, `preload_releases` failed: Although you appear to have the correct authorization credentials, the `confluentinc` organization has an IP allow list enabled, and your IP address is not permitted to access this resource.
```

this is a pretty major problem cc @adamkotwasinski

**Comment by phlax** [comment]
it may be that only the release info is restricted - my immediate panic is that we have lost access to tarballs etc - but not sure - if its only release info then perhaps less of an issue, but still would be good to access

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by phlax** [comment]
im gonna spin an uncached run to check we havent lost access to the tarballs

assuming we havent, ill update the checker to make the no-release-info a warn and revert the name changes - its a bit hacky but at least it will get ci passing

if we have - we really do have an issue with this dep

**Comment by phlax** [comment]
i think this pr is running uncached - so if it can pass in azp we should be good

**Comment by phlax** [comment]
k, reverted to plan b - hopefully should work for now

**Comment by phlax** [comment]
this seems to be magically fixed - we probs still want this update in case we have similar issues in the future

**Pull request merged**
