### PR TITLE
http local rate limit: note token bucket is shared

### PR DESCRIPTION
**Pull request by rgs1**
Follow-up to #13517.

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

### CODE REVIEW

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Awesome thanks. Do you mind adding this same note for the L4 one as well per your comment?

/wait

**Review by nitgoy — APPROVED** [review]
Thanks!

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Comment by nitgoy** [comment]
@mattklein123 @rgs1 A previous note in docs/root/configuration/listeners/network_filters/local_rate_limit_filter.rst says:
"In the current implementation each filter and filter chain has an independent rate limit."

It seems to conflict with the note added in this PR.

**Pull request merged**
