### PR TITLE
test: use semantic network filter names

### PR DESCRIPTION
**Pull request by kyessenov**
Description: exercise semantic names for network filter extensions. Follow up to https://github.com/envoyproxy/envoy/pull/10071. 
Risk Level: low. there is a change to properly support type URL inside typed structs (stripping `type.googleapis.com`)
Testing: unit tests
Docs Changes: none
Release Notes:
/assign @zuercher

### CODE REVIEW

**Comment by kyessenov** [comment]
I have another PR finishing the rename for all extensions. I think it's a good idea to keep it separate to make the review easier.

**Comment by kyessenov** [comment]
Yeah, the `envoy.router` extension continues to use by-name lookup, since it's easier to type than the whole path to the extension API.

**Comment by zuercher** [comment]
I'm worried that we'll eventually excise all those and end up with an untested path without realizing it, and that it might stop working before the point where we intentionally delete it.

**Comment by kyessenov** [comment]
I share the concern. Given that the typed config type URL takes precedence, we can only exercise the non-typed lookup for filters with no config, really. Router is one of them and we should keep it that way. The code path for all extension lookups is the same, so until we merge #10130 , we're safe from the risk. I should add a test case to #10130 to make sure we keep the empty-config lookup by name functional.

**Comment by kyessenov** [comment]
@zuercher Do you think we can get this in, and I'll work on the follow-up #10130.

**Comment by kyessenov** [comment]
Hi! Can we merge this or is there something else that needs to be done?

**Pull request merged**
