### PR TITLE
Disable kotlin_experimental_app

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
kotlin_experimental_app seems broken 
#26470

Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by Augustyniak** [comment]
I know what the root cause is. Will follow up shortly.

**Comment by Augustyniak** [comment]
Experimental app should be fixed in https://github.com/envoyproxy/envoy/pull/26482

**Comment by RyanTheOptimist** [comment]
Closing as the root cause has been addressed in https://github.com/envoyproxy/envoy/pull/26482/files

**Pull request closed without merging**
