### PR TITLE
add envoy-build-centos

### PR DESCRIPTION
**Pull request by jwfang**
same as #1690 , with DCO fix.

### CODE REVIEW

**Comment by mattklein123** [comment]
@jwfang FYI it's not working: https://travis-ci.org/envoyproxy/envoy/jobs/278460500

Can you take a look?

**Comment by jwfang** [comment]
@mattklein123 i am on it

**Comment by jwfang** [comment]
@mattklein123 

the *LINUX_DISTO* should be *LINUX_DISTRO* here:
https://github.com/envoyproxy/envoy/blob/2ddcec61d7e3ed545dc5f2b0652c360bcd16e958/ci/build_container/docker_build.sh#L7

i made a commit in my *jwfang:build-devtoolset3* branche, but didn't know how to get it in ?

**Comment by mattklein123** [comment]
@jwfang just make a new PR.

**Comment by jwfang** [comment]
@mattklein123 made PR #1723

**Pull request merged**
