### PR TITLE
repo: Cleanup typos and grammar

### PR DESCRIPTION
**Pull request by CMcCudden**
Signed-off-by: CMcCudden <calebmccudden@.com>

Commit Message: Docs: Fix grammar and spelling issues; adjusted cell spacing on tables where applicable.
Additional Description:
Risk Level: Low
Testing:
Docs Changes: Fix grammar and spelling issues; adjusted cell spacing on tables where applicable.
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
Quick question... Should we first fix the docs on main and then cherry-pick that fix to v1.21 instead of fixing on v1.21 directly? Otherwise we'll have the same issues with 1.22?

**Comment by phlax** [comment]
> Should we first fix the docs on main and then cherry-pick that fix to v1.21 i

yep, i wondered the same - but the pr is tagged to master, and is not related to docs or versions afaict

ive renamed the PR to try and make that clearer

**Comment by phlax** [comment]
@CMcCudden copying out the CI advice

```
##[error]: TESTS FAILED:
##[error]:  main@ /source/ci/format_pre.sh :47 (glint)
##[error]:      Please fix your editor to ensure:
##[error]:        - no trailing whitespace
##[error]:        - no mixed tabs/spaces
##[error]:        - all files end with a newline
```

also, you need to fix DCO

**Pull request closed without merging**
