### PR TITLE
Revert "factory context refactor: refactor the transport factory cont…

### PR DESCRIPTION
**Pull request by wbpcode**
…ext (#27081)"

This reverts commit 5b5d13955d576369b5593f6ec29e3cfe42ef9fff.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by wbpcode** [comment]
cc @phlax wait ci to pass before merge it avoid any possible error.

**Review by phlax — APPROVED** [review]
lgtm, thanks @wbpcode

**Comment by phlax** [comment]
Flagging this should fix CI asan errors with SSL context tests

**Comment by wbpcode** [comment]
All failed tests for now are stopped by the external signal in duration ~120s.
Not sure what changed and where is the duration limitation. 🤣

**Comment by phlax** [comment]
> Not sure what changed and where is the duration limitation.

we added the `--test_verbose_timeout_warnings` flag (i dont think this is the cause of issue) which ideally should tell us which tests are too big or small

atm it doesnt seem to work very well as we dont get the warnings afaict unless there is actually an error - in this case we did get a warning, but confusingly it seems to suggest making the test smaller

**Pull request merged**
