### PR TITLE
wasm: register verify_signature as foreign function

### LINKED ISSUE #31615: Support FIPs crypto from WASM plugin
Support FIPs crypto from WASM plugin

Extend envoy capabilities to allows wasm filter use fips compliant crypto APIs

Related 
https://github.com/envoyproxy/envoy-wasm/issues/188
https://github.com/WebAssembly/wasi-crypto

### PR DESCRIPTION
**Pull request by patricio78**
Commit Message: register verify_signature to wasm
Additional Description: Registers ffi verify_signature to wasm filters with the same signature used for lua filters. https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#verify-signature
Risk Level: low. New function added.
Testing: unit.
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a
Fixes #31615

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@kyessenov @PiotrSikora PTAL

**Comment by alyssawilk** [comment]
@lizan PTAL

**Review by lizan — COMMENTED** [review]
This generally looks good to me. Can you add a release note? @PiotrSikora can you also take a look on the crypto part?

**Comment by patricio78** [comment]
> This generally looks good to me. Can you add a release note? @PiotrSikora can you also take a look on the crypto part?
Added a release note

**Comment by bayareaunicorn** [comment]
Thanks for your contribution..

**Pull request merged**
