### PR TITLE
Fix proto_sync.py

### PR DESCRIPTION
**Pull request by wzshiming**
Fix path in proto_sync.py generated comments and regenerate

Risk Level: Low
Testing: manual testing

Signed-off-by: wzshiming <wzshiming@foxmail.com>

### CODE REVIEW

**Comment by dio** [comment]
@wzshiming could you fix DCO? Thanks!

**Comment by dio** [comment]
@wzshiming thank you. I think you need to fix all of the relevant files. The list of failing format checks can be found at the end of this log: https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/46998/logs/7.

**Comment by htuch** [comment]
@wzshiming can you update the top-level GitHub comment to provide a full commit message? Thanks.

**Comment by wzshiming** [comment]
@htuch Yes, definitely -- done

**Comment by dio** [comment]
Pushing an empty commit probably helps here. Seems like circle is stuck.

**Comment by wzshiming** [comment]
@dio push again, but still the same.

**Comment by dio** [comment]
cc. @lizan do you know what makes circle stuck this way?

**Comment by dio** [comment]
@lizan Is it because of the PR initiated from GitHub UI?

```
fatal: Couldn't find remote ref pull/12434/head/head
```

**Comment by lizan** [comment]
I tried to manually trigger the job but it didn't go well. I think we can just force merge. @htuch or @mattklein123 ?

**Pull request merged**
