### PR TITLE
source: add option to exclude zero values in statsd metrics

### LINKED ISSUE #6205: Allow option to not emit statsd metrics when reporting a `0` value
We store the statsd metrics envoy emits in a SAAS metrics tool that charges us based on the number of measurements we store at a particular reporting interval. Some of the metrics we are recording are consistently `0`, with occasional spikes when something happens. Here's an example:

image 2019-03-07 at 11 54 16 am

I can see the value in using a 0 value to report "nothing is happening", but our monitoring bill has doubled as a result of adopting envoy(!), and continues to grow as we add more clusters, so we'd like to save some money by not recording measurements we can mostly infer from an absence of data.

That said, the zero values were very helpful when were spiking into adopting envoy, as it allowed us to see which metrics we could expect from envoy. Maybe this should be a configuration option in the [`StatsMatcher` proto](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/metrics/v2/stats.proto#config-metrics-v2-statsmatcher)?

### PR DESCRIPTION
**Pull request by ananda1066**
Description: Added option to statsd and dogstatsd configurations to exclude metrics outputting values of zero. 
Risk Level: Low
Testing: Manual tests were done and work correctly but I don't have the bandwidth at this time to add unit testing - help wanted to complete this PR.
Docs Changes: Inline comment in API proto for statsd and dogstatsd.
Release Notes: Added note about new option for statsd.

Fixes #6205

### CODE REVIEW

**Comment by junr03** [comment]
Thanks for the contribution @ananda1066. I am going to wait to review until tests are green.

/wait

**Comment by ananda1066** [comment]
Sounds good! I unfortunately don’t have the bandwidth to continue work on the PR at this time - I believe the source code is essentially complete with a few needed formatting changes and testing needs to be added. I hope someone will be able to complete it!

**Comment by junr03** [comment]
In that case would you mind if I update #6205 saying that an interested person can take over this PR, and close this until a person does so?

**Comment by ananda1066** [comment]
Sure!

**Pull request closed without merging**
