### PR TITLE
protos: Cleanup unused imports

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: protos: Cleanup unused imports
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by adisuissa — APPROVED** [review]
/lgtm api

**Comment by phlax** [comment]
@zuercher could i get a stamp for this one - its pretty straightforward cleanup

**Review by zuercher — APPROVED** [review]

**Comment by phlax** [comment]
wow 4s that was fast turnaround!

**Comment by zuercher** [comment]
Everybody clicking on this at the same time. 😂

**Pull request merged**
