### PR TITLE
deps: update proxy-wasm-cpp-host

### PR DESCRIPTION
**Pull request by keith**
Fixes https://github.com/envoyproxy/envoy/issues/23390

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Comment by keith** [comment]
not sure what I'm in for here

**Comment by phlax** [comment]
cc @kfaseela

**Comment by dio** [comment]
@phlax do we want to land this before https://github.com/envoyproxy/envoy/pull/23434?

**Comment by keith** [comment]
I removed the v8 version bump from this one to only take that bazel fix, if we can land yours instead w/o other blockers we should do that and close this one

**Comment by phlax** [comment]
> @phlax @keith did we finish updating proxy-wasm-cpp-host first?

im not sure - previously i believe there was a need to update these deps together (and do some cargo-fu)

it seems like they are not in sync now - altho maybe the important deps are

Envoy's version of wasmtime:

https://github.com/envoyproxy/envoy/blob/7a4bbb3c5b52b84625ad0626f916be1c99399ba8/bazel/repository_locations.bzl#L982-L996

which is using a recent hash version (maybe we should switch to a releaese version there)

current wasmtime upstream

https://github.com/bytecodealliance/wasmtime/releases/tag/v1.0.1

but it doesnt seem like the wasmtime crates have been updated:

https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/master/bazel/cargo/wasmtime/BUILD.bazel#L44

**Comment by keith** [comment]
There are only 2 commits being pulled in with this change https://github.com/proxy-wasm/proxy-wasm-cpp-host/compare/4fcf895fa2433a1cdf20704926b8b7e4039a6a04...25d6a99de9378e65a6bb6a56a2ca5073870ddc3c so if the other change is blocked on anything I would think updating this would be pretty safe

**Review by PiotrSikora — APPROVED** [review]
> it seems like they are not in sync now - altho maybe the important deps are

They are not. Wasmtime is out-of-sync and it only works by accident because there were no breaking changes in Wasmtime's C API (updated in #23232), but Envoy is now using C API from a version different than Wasmtime core.

@RiverPhillips is working on fixing that in https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/309, and hopefully we can land it and merge into Envoy before the next release.

Regarding this PR, it can be either merged as-is or it could be dropped in favor of #23434, which also contains those changes and was opened first.

**Comment by htuch** [comment]
Maybe just do https://github.com/envoyproxy/envoy/pull/23434?

**Comment by keith** [comment]
https://github.com/envoyproxy/envoy/pull/23434

**Pull request closed without merging**
