### PR TITLE
only set hot restart related stats when it is enabled

### PR DESCRIPTION
**Pull request by ramaraochavali**
Commit Message: only set hot restart related stats when it is enabled - without this envoy marks these stats as "used". StatsSinks send to the backends and backends inject in to metrics system - all of that is unnecessary processing.
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Review by adisuissa — COMMENTED** [review]
Thanks!
This may need a release note if it is use facing.

Assigning Josh for stats review, and Raven for hot-restart review.
/assign @jmarantz @ravenblackx

**Review by jmarantz — COMMENTED** [review]
lgtm modulo release note

**Review by ravenblackx — APPROVED** [review]

**Comment by ravenblackx** [comment]
Looks like `change` needs to be outdented by one to satisfy the yaml.

**Review by jmarantz — APPROVED** [review]

**Comment by jmarantz** [comment]
@RyanTheOptimist for senior stamp

**Review by RyanTheOptimist — COMMENTED** [review]
The change looks nice and clean. Woo hoo. One question... Should we protect this change by a runtime guard? I'm not sure if this change might cause problems with the monitoring for some users?

**Comment by ramaraochavali** [comment]
> Should we protect this change by a runtime guard? I'm not sure if this change might cause problems with the monitoring for some users?

IMO - it should not. If you are not using hot restart, you should not care about these stats.

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
