### PR TITLE
deps: update cel-cpp to 2023-05-19

### PR DESCRIPTION
**Pull request by kyessenov**
Commit Message: update cel-cpp
Additional Description: needs protoc >=22, adding a patch temporarily until protobuf update merges to convert to strings from string_views. Disabled on Windows due to the stale build tools.
Risk Level: low
Testing: regression
Docs Changes: none
Release Notes: none

### CODE REVIEW

**Comment by moderation** [comment]
Why not bump the proto version? Would the reduce the size or remove the need for the big patch?

https://github.com/envoyproxy/envoy/blob/main/bazel/repository_locations.bzl#L3

**Comment by kyessenov** [comment]
@moderation Sigh, it's not easy, @yanavlasov is tracking it.

**Comment by phlax** [comment]
the c-t-options/gcc/windows fails look real

also may be worth waiting for #28075

**Comment by kyessenov** [comment]
Skip-on-Windows option is hard to carve out since RBAC depends on CEL, will continue after protobuf update is done.

**Pull request closed without merging**
