### PR TITLE
fixes for compiling Envoy on IBM Power processor

### PR DESCRIPTION
**Pull request by rshriram**
Signed-off-by: Shriram Rajagopalan <shriram@us.ibm.com>

### CODE REVIEW

**Comment by rshriram** [comment]
Do not merge yet. Making sure there are no bazel surprises over all on power machine

**Comment by rshriram** [comment]
This test consistently fails:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
WARNING: Perftools heap leak checker is active -- Performance may suffer
[==========] Running 41 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 29 tests from Http1ServerConnectionImplTest
[ RUN      ] Http1ServerConnectionImplTest.EmptyHeader
[       OK ] Http1ServerConnectionImplTest.EmptyHeader (1 ms)
[ RUN      ] Http1ServerConnectionImplTest.Http10
[       OK ] Http1ServerConnectionImplTest.Http10 (0 ms)
[ RUN      ] Http1ServerConnectionImplTest.Http10AbsoluteNoOp
[       OK ] Http1ServerConnectionImplTest.Http10AbsoluteNoOp (1 ms)
[ RUN      ] Http1ServerConnectionImplTest.Http10Absolute
[       OK ] Http1ServerConnectionImplTest.Http10Absolute (1 ms)
[ RUN      ] Http1ServerConnectionImplTest.Http11AbsolutePath1
[       OK ] Http1ServerConnectionImplTest.Http11AbsolutePath1 (0 ms)
[ RUN      ] Http1ServerConnectionImplTest.Http11AbsolutePath2
[       OK ] Http1ServerConnectionImplTest.Http11AbsolutePath2 (1 ms)
[ RUN      ] Http1ServerConnectionImplTest.Http11AbsolutePathWithPort
[       OK ] Http1ServerConnectionImplTest.Http11AbsolutePathWithPort (1 ms)
[ RUN      ] Http1ServerConnectionImplTest.Http11AbsoluteEnabledNoOp
[       OK ] Http1ServerConnectionImplTest.Http11AbsoluteEnabledNoOp (0 ms)
[ RUN      ] Http1ServerConnectionImplTest.Http11InvalidRequest
[       OK ] Http1ServerConnectionImplTest.Http11InvalidRequest (1 ms)
[ RUN      ] Http1ServerConnectionImplTest.Http11AbsolutePathNoSlash
[       OK ] Http1ServerConnectionImplTest.Http11AbsolutePathNoSlash (0 ms)
[ RUN      ] Http1ServerConnectionImplTest.Http11AbsolutePathBad
terminate called after throwing an instance of 'Envoy::Http::CodecProtocolException'
  what():  http/1.1 protocol error: invalid url in request line
[2017-10-04 17:30:13.262][13][critical][backtrace] bazel-out/local-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:101] Caught Aborted, suspect faulting address 0xd
[2017-10-04 17:30:13.262][13][critical][backtrace] bazel-out/local-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:76] Back trace attempt failed
Aborted
```

Any idea why ?

**Comment by htuch** [comment]
If you fix the stack walker for PPC, we will be able to see why :)

**Comment by rshriram** [comment]
```
#0  Envoy::SignalAction::sigHandler (sig=6, info=0x3fffb78bfd78, context=0x3fffb78bf000) at source/exe/signal_action.cc:23
#1  <signal handler called>
#2  0x00003fffb7a0edb0 in __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:54
#3  0x00003fffb7a11270 in __GI_abort () at abort.c:89
#4  0x00003fffb7cbc304 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
#5  0x00003fffb7cb8b34 in ?? () from /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
#6  0x00003fffb7cb8bf0 in std::terminate() () from /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
#7  0x00003fffb7cb9034 in __cxa_throw () from /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
#8  0x0000000010600c24 in Envoy::Http::Http1::ServerConnectionImpl::handlePath (this=0x11da0b40, headers=..., method=1) at source/common/http/http1/codec_impl.cc:459
#9  0x0000000010600e2c in Envoy::Http::Http1::ServerConnectionImpl::onHeadersComplete(std::unique_ptr<Envoy::Http::HeaderMapImpl, std::default_delete<Envoy::Http::HeaderMapImpl> >&&) (
    this=0x11da0b40,
```
This is as far as I got

**Comment by htuch** [comment]
I wonder if exception handling on PPC is working correctly, maybe you need some special flags in the build or something. The test does expect an exception to be thrown, but catches it with a `EXPECT_THROW`. Also, why is the stack depth limited?

**Comment by mattklein123** [comment]
It seems more likely that the signal handler and the debugger are not playing well together. I would compile out the signal handler and run under gdb.

**Comment by mattklein123** [comment]
@rshriram I'm just going to close this for now. Please reopen once you debug all the Power issues and want to merge.

**Pull request closed without merging**
