### PR TITLE
config: finish warming only after named response

### PR DESCRIPTION
**Pull request by ramaraochavali**
Description: This PR changes the way cluster warming works and finishes warming only after a named response i.e a `ClusterLoadAssginment` response for the cluster being warmed. This happens consistently both in init/updated warming cases.
Risk Level: Medium
Testing: Added automated tests to test the new behaviour.
Docs Changes: N/A
Release Notes: Updated
Fixes https://github.com/envoyproxy/envoy/issues/5168

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Document where this approach was discussed https://docs.google.com/document/d/1Ca4YX9XNnV9rjTR7U0_xyCxUDKfoSun8pWSUNO9N-tY/edit?ts=5c79affc

**Comment by ramaraochavali** [comment]
@mattklein123  @htuch  @snowp  implemented as discussed in the doc. PTAL.

Regarding doc updates, I think the cluster warming section here https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/cluster_manager.html?highlight=cluster%20warming#cluster-warming correctly represents the expected behaviour.

I will update xDS protocol doc (including guidance on renaming) in a follow-up PR.

**Comment by htuch** [comment]
Looks good code wise. A few things to consider:
1. Should we config guard? It does change behavior.
2. Can you add references to https://github.com/envoyproxy/envoy/issues/4485 and the rollback to your commit message, so we have a commit trail.
3. We need to get @rfaulk looped in on this, to make sure his concerns are addressed. He is a Googler, so I will reach out to him internally and bring this to his attention.

**Comment by ramaraochavali** [comment]
> Should we config guard? It does change behavior.

My personal opinion - I think we should not because this is the desired behavior we want. But open to it if others feel it is the right way to do.

> Can you add references to #4485 and the rollback to your commit message, so we have a commit trail.

Sorry this is not clear to me. Do you want me to push a empty commit with references to this?

> We need to get @rfaulk looped in on this, to make sure his concerns are addressed. He is a Googler, so I will reach out to him internally and bring this to his attention.

Thank you. That makes sense.

**Comment by ramaraochavali** [comment]
nm on 2, added references.

**Comment by htuch** [comment]
I chatted with @rfaulk and we're good to go with this PR, we'll make the required changes internally to deal with this. @costinm FYI, this may have Pilot side implications, unclear.

I don't feel that strongly about config guarding, I'll let @alyssawilk who is our new config guard police provide thoughts.

**Comment by ramaraochavali** [comment]
@htuch Thank you.

**Pull request merged**
