### PR TITLE
api: Remove confusing line about auto-generation

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: api: Remove confusing line about auto-generation
Additional Description:

afaiaa this file is not auto-generated (grepping code appears to confirm that)

i think these messages are present in the api directory so that they are copied over to generated_api_shadow - or perhaps were copied from there at some stage

either way - im pretty sure the message removed here is wrong

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @htuch @mattklein123

**Review by htuch — APPROVED** [review]

**Comment by mattklein123** [comment]
This file is auto generated: https://github.com/envoyproxy/envoy/blob/110559f09c62175aa3cefb742ae2c66e953b6597/tools/proto_format/proto_format.sh#L66-L68

**Comment by phlax** [comment]
> This file is auto generated: 

is that not for comparison - to check there is no diff ?

**Comment by phlax** [comment]
one thing im a bit concerned about is that when any api changes its going to expect that header at the top that was removed

i kinda meant this pr more as an rfc to try and clarify the situation

ill experiment further with api changes

**Comment by mattklein123** [comment]
> is that not for comparison - to check there is no diff ?

No, I don't think so. I'm still trying to sort through all of this. It's incredibly confusing and contrib makes it more so.

**Comment by mattklein123** [comment]
FYI, this line gets re-added for me locally, so, it's going to get re-added in the next commit that changes API I would imagine.

**Comment by phlax** [comment]
ive opened a pr to revert #17548 

mostly i was trying to demonstrate that while proto_format enforces a *format* and does a comparison with `generated_api_shadow` its not used in any way building the docs (or for anything else i think) - its a formatting/integrity test

the docs run in presubmit before this is run, and in postsubmit independently

**Comment by phlax** [comment]
i guess i can see how it might be regarded as auto-generated

my own thinking is that its auto-generated in the way that eg gofmt auto-generates files, altho i guess in this case its formatting from the actual deps, etc

i think it comes down to a matter of perspective, personally i edit this file when making related changes, but if you followed a workflow of make changes, run proto_format, then it would be auto-generated

really not trying to cause any confusion, just again trying to emphasize that from envoy source this is not part of the pipeline to build anything

**Pull request merged**
