### PR TITLE
bazel: update to 6.0.0rc4

### PR DESCRIPTION
**Pull request by keith**
This reverts commit dede92e6e5888cdf27320bf3b6bc9987657d6e22. Originally this was reverted because of https://github.com/envoyproxy/envoy/issues/23985

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Comment by keith** [comment]
hoping CI will catch with https://github.com/envoyproxy/envoy/pull/24203

**Comment by keith** [comment]
ci did catch the coverage issue, working on the fix here

**Comment by keith** [comment]
I bisected the coverage change to https://github.com/bazelbuild/bazel/commit/943e8cfb9970ca86f88ba60c944601573b366db5

**Comment by keith** [comment]
@phlax want to look at this one too?

**Review by phlax — APPROVED** [review]
/lgtm deps

thanks @keith

**Pull request merged**
