### PR TITLE
api: remove generated_api_shadow

### LINKED ISSUE #9479: Remove shadow artifacts from API tree
As part of https://github.com/envoyproxy/envoy/issues/8082, we introduced shadow protos for Envoy internal use (see https://docs.google.com/document/d/1mGO9LtVo7t4Lph7WlmyGCxXye3h6j29z3JZvIBbs_D0/edit# for rationale). 

Ultimately, we should not be checking into the repository these generated artifacts. If we want to keep shadowing (for convenience), we should be using `protoxform` to generate the desired shadows prior to invoking PGV, to generate shadows.

Preferably, we handle future deprecations without the need for shadowing, in v4+.

### PR DESCRIPTION
**Pull request by htuch**
This PR eliminates the generated_api_shadow/ tree and allows direct references to the api/ directory from Envoy source. Along the way:
* Cleaned up vestigial hidden_envoy_deprecated_ references.
* Removed stale v1/2 tech debt from TCP proxy 
* Removed active-shadow merging and next version upgrades in protoxform.

There is still some further work to do in retiring v2, major items include (these are deferred to later PRs, this PR is already quite large):
* Updating BUILD file generation to remove all v3 -> v2 references.
* Simplify / cleanup / eliminate (?) type whisperer and database
* Cleanup pass on protoxform/protosync/protoformat to simplify.

Risk level: Medium (it's unlikely but possible that some of the proto changes introduce issues, e.g. with enum defaults)
Testing: CI (also manual inspection of docs / format fixes)

Fixes #9479

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

**Comment by htuch** [comment]
@ggreenway I did the TCP proxy implementation cleanup in this PR, since it was using `DeprecatedV1` protos internally, so it made sense to just get that out of the way.

Once this is passing CI it should be good to go for review.

CC @envoyproxy/api-shepherds

**Review by ggreenway — APPROVED** [review]
Awesome! Looks good!

**Review by mattklein123 — DISMISSED** [review]
Amazing!!!

**Comment by mattklein123** [comment]
Looks like we need a main merge. If you want to freeze main to get this in we can do that.

/wait

**Review by mattklein123 — APPROVED** [review]
Yay! :tada:

**Pull request merged**
