### PR TITLE
build: modify include paths to be more bazel friendly

### LINKED ISSUE #16196: gcc build is failing for test targets that depend on //source/exe:envoy_common_lib
The //source/exe:envoy_common_lib target builds all extensions and as a result creates a huge list of virtual include paths to each extension directory (which by themselves are also long).
In this case gcc fails to spawn its frontend:

`gcc: fatal error: cannot execute ‘/usr/lib/gcc/x86_64-linux-gnu/9/cc1plus’: execv: Argument list too long`

As a short term solution the three test targets have been modified to depend on the //source/exe;envoy_common_with_core_extensions_lib which only includes core extensions. Two tests in question do not need all extensions, and one is enough to test on clang.

Going forward I'm engaging with the bazel team to see how this can be addressed.
Plan B is to ask RBE team to increase `ulimit -s` on RBE VMs.

### PR DESCRIPTION
**Pull request by yanavlasov**
Commit Message:
Make Envoy include structure more bazel friendly to make it possible to build Envoy using gcc toolchain.
1. Move include/envoy one level up. 'git mv include/envoy envoy'.
2. Use full path when including files in the 'source/' directory.

Risk Level: Low (but it will break external repos that depend on Envoy)
Testing: Unit Tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
Fixes #16196

### CODE REVIEW

**Comment by htuch** [comment]
Cool! Thanks for looking into making things less magic with includes.

For at least the `include/envoy` directory, can we just `git mv include/envoy envoy`? This would then avoid having to change any source files and not have the awkward `#include "include/envoy/..."` pattern.

**Comment by jmarantz** [comment]
I like `git mv include/envoy envoy`.

**Comment by jmarantz** [comment]
totally didn't mean to do that.

**Comment by alyssawilk** [comment]
eh, while I don't like changing 1000 paths, I like source vs include.  If we're going to move files I'd be inclined to nix the envoy and have source paths reflect include paths (include/common/http) but that's probably too much of a pain

**Review by mattklein123 — APPROVED** [review]
Thanks for slogging through this.

**Pull request merged**
