### PR TITLE
Fix the release note

### PR DESCRIPTION
**Pull request by tyxia**
Move ext_proc observability mode support and grpc flow control to correct place: new feature

### CODE REVIEW

**Comment by phlax** [comment]
@tyxia i think this needs a `main` merge

**Comment by tyxia** [comment]
> @tyxia i think this needs a `main` merge

Thanks! PTAL

**Review by phlax — APPROVED** [review]
@tyxia this shifts 2 changelogs - is that the intention?

if so - lgtm, thanks @tyxia

**Comment by tyxia** [comment]
> @tyxia this shifts 2 changelogs - is that the intention?
> 
> if so - lgtm, thanks @tyxia

Yes, I just went ahead correct two changelogs. Sorry it will need you approval stamp again as I just fixed a format issue :)

Thanks @phlax

**Review by phlax — APPROVED** [review]

**Pull request merged**
