### PR TITLE
Migrate v2 thrift_filter to v3 api and corresponding docs changes.

### PR DESCRIPTION
**Pull request by ankatare**
Signed-off-by: Abhay Narayan Katare <abhay.katare@india.nec.com>

Commit Message: document changes for #12841 
Additional Description:
Risk Level: LOW
Testing: Unit
Docs Changes: yes
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
part of #12841

### CODE REVIEW

**Comment by ggreenway** [comment]
docs build is broken

/wait

**Comment by ankatare** [comment]
@ggreenway humm. some issues in my local env. checking it.

**Comment by ankatare** [comment]
@ggreenway not able to find  failure reason from logs  :( .  Even in my local env it is passing. 
please help me !!!

**Comment by ggreenway** [comment]
`generating indices... /source/generated/rst/configuration/other_protocols/thrift_filters/router_filter.rst:10: WARNING: undefined label: envoy_v3_api_msg_extensions.filter.thrift.router.v3.router (if the link has no caption the label must precede a section header)`

**Comment by ankatare** [comment]
@ggreenway ok. checking it. Thanks !!!

**Comment by ggreenway** [comment]
Build still failing

/wait

**Comment by ankatare** [comment]
@ggreenway humm. seems some env issue. will check ASAP

**Comment by ggreenway** [comment]
Doc build errors due to undefined labels aren't quite at the bottom of the output. If you scroll up a bit you'll see:

`rated/rst/configuration/other_protocols/thrift_filters/router_filter.rst:10: WARNING: undefined label: envoy_v3_api_msg_extensions.filters.network.thrift_proxy.v3.router (if the link has no caption the label must precede a section header)`

**Comment by ankatare** [comment]
still working on fixing issues in my local env. will try to close it ASAP

**Comment by ankatare** [comment]
seems this PR is dependent on #13814 . i will fix as soon code merge in main base line.

**Comment by ankatare** [comment]
@htuch done. please review

**Comment by htuch** [comment]
@ankatare LGTM but please update the title/commit message to reflect what is actually done here (it's not doc changes).

**Comment by ankatare** [comment]
@htuch ok. sure . actually initially it was only doc changes but now in order to pass this PR i need to made changes in code as well.

**Comment by ankatare** [comment]
@htuch done

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
