### PR TITLE
build: update cares to 1.17.1

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Commit Message: Update c-ares to latest release 1.17.1. https://c-ares.haxx.se/changelog.html#1_17_1
Risk Level: Low/Medium
Testing: Existing tests.

### CODE REVIEW

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Comment by moderation** [comment]
`release_date` not updated to the correct value of `2020-11-19` - https://github.com/envoyproxy/envoy/pull/14213/files#diff-a2ca502474bb8ec5f092176f7ee6d2f11fc395ebb00e1717d6fbad9b16ee8fd8R109. I'll clean up in a follow up PR but I thought that this should fail CI? /cc @htuch

**Comment by asraa** [comment]
Thank you for the catch @moderation!

**Comment by htuch** [comment]
Fixed in https://github.com/envoyproxy/envoy/pull/14216

**Pull request merged**
