### PR TITLE
connection_impl: Use early returns to reduce nested code in connection_impl.cc

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
connection_impl: Use early returns to reduce nested code in connection_impl.cc

No code change, just refactoring.

Risk Level: Low
Testing: N/A - no code change
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
Github is having a hard time with the diffs so I recommend using "Ignore white space" to make it clear what is (or really what isn't) changing.

**Comment by RyanTheOptimist** [comment]
@DavidSchinazi I forgot that Renjie is OO this week. Can you take a look? Should be fast.

**Review by DavidSchinazi — APPROVED** [review]
Thanks for the suggestion about whitespace-only changes :)

**Review by alyssawilk — APPROVED** [review]
code LGTM.  Passing over to someone else to make the call if it's worth the churn esp near release.

**Comment by mattklein123** [comment]
Yeah probably worth holding until after the release which should be today hopefully or tomorrow.

**Pull request merged**
