### PR TITLE
[backport/1.22] repo: Dev `1.22.7`

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
requires coverage adjustment

**Comment by phlax** [comment]
i think this branch is particularly flakey

/retest

**Review by alyssawilk — APPROVED** [review]
FWIW I'm also fine just killing per file coverage limits for branches if it makes your life easier

**Comment by phlax** [comment]
i think the coverage issue/s are ~resolved what is blocking is failing on the arm release is the `tap_filter_integration_test`

error is here https://dev.azure.com/cncf/envoy/_build/results?buildId=122468&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&s=b2710bd9-3b3a-5a17-3102-13ba462a848c&t=1fb0b72f-6293-562d-a4d1-bb649223eaca&l=4345

ive reported is previously here #24140

**Pull request merged**
