### PR TITLE
[WIP] deps: Bump `com_google_absl` -> 20230125.3

### LINKED ISSUE #27202: Newer release available `com_google_absl`: 20230125.3 (current: 9bff2a9)
Package Name: com_google_absl@9bff2a9302
Current Version: 9bff2a9@2022-12-07
Available Version: 20230125.3@2023-05-04
Upstream releases: https://github.com/abseil/abseil-cpp/releases

### PR DESCRIPTION
**Pull request by phlax**
Fix #27202 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @kyessenov

**Comment by yanavlasov** [comment]
Looks like we are bumping into the cel-cpp ability to upgrade a bit harder now. I will ping the team that maintains it. We currently can not upgrade it due to build errors in cel-cpp.

**Comment by kyessenov** [comment]
Ah, I forgot about this PR and opened another one. I think we should patch cel-cpp temporarily since the new cel-cpp needs the new absl and we shouldn't couple the upgrade together.

**Comment by phlax** [comment]
not sure i follow exactly - feel free to close

**Comment by kyessenov** [comment]
@phlax CEL wasn't syncing for awhile (~270 commits) - so if we want the head of it, we'd need to bump absl/re2/protoc together. I think it's better to bump each one separately.

**Comment by kyessenov** [comment]
CEL also needs the newest protoc... That one might be tricky.

**Pull request closed without merging**
