### PR TITLE
otlp_stat_sink: mitigate test flakes

### PR DESCRIPTION
**Pull request by ohadvano**
Additional Description: This change will mitigate the test flakes as described in #29518. Requires further investigation to understand root cause
Risk Level: low

### CODE REVIEW

**Comment by alyssawilk** [comment]
to be clear did you verify this reduced the flake or is it just a guess?  Often changes like this just lengthen the test time without reducing flakiness.  thanks!
/wait-any

**Comment by ohadvano** [comment]
Verified - ran 1000 times, no failures. Without the change - failed ~15/100 runs

**Review by alyssawilk — APPROVED** [review]
awesome, thanks for confirming

**Pull request merged**
