### PR TITLE
Add TestUtility::ipVersionToString().

### PR DESCRIPTION
**Pull request by bencebeky**
Signed-off-by: Bence Béky <bnc@google.com>

Commit Message: Add TestUtility::ipVersionToString().
Additional Description: n/a
Risk Level: low, test-only
Testing: test-only change
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by bencebeky** [comment]
Kevin: PTAL.  This is a test-only refactor with no behavior change.  I'm open to alternate naming suggestions, naming is hard.  Note that Http2Impl (oghttp2 and nghttp2) is both for parsing and serializing, whereas Http1ParserImpl (Balsa and http-parser) is only for parsing, hence the name difference.  Thank you.

**Comment by bencebeky** [comment]
Note that the comment https://github.com/envoyproxy/envoy/pull/24146#discussion_r1033605725 also applies here.  However, this issue is pre-existing, also adding a new IP version is even less likely than adding a new HTTP/1 parser.

**Review by KBaichoo — COMMENTED** [review]
I think there are some additional opportunities to use this in some of the following files:

```
test/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator_integration_test.h
test/extensions/transport_sockets/tls/cert_validator/default_validator_integration_test.h
test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc
test/extensions/filters/http/grpc_json_transcoder/grpc_json_transcoder_integration_test.cc
test/extensions/http/header_formatters/preserve_case/preserve_case_formatter_reason_phrase_integration_test.cc
test/extensions/http/header_formatters/preserve_case/preserve_case_formatter_integration_test.cc
test/common/quic/test_utils.h
test/common/grpc/grpc_client_integration.h
test/integration/multiplexed_integration_test.cc
test/integration/http2_flood_integration_test.cc
test/integration/sds_dynamic_integration_test.cc
test/integration/ads_integration.h
```

Thank you for the refactor, looks great otherwise

**Comment by bencebeky** [comment]
> I think there are some additional opportunities to use this in some of the following files:
> 
> ```
> test/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator_integration_test.h
> test/extensions/transport_sockets/tls/cert_validator/default_validator_integration_test.h
> test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc
> test/extensions/filters/http/grpc_json_transcoder/grpc_json_transcoder_integration_test.cc
> test/extensions/http/header_formatters/preserve_case/preserve_case_formatter_reason_phrase_integration_test.cc
> test/extensions/http/header_formatters/preserve_case/preserve_case_formatter_integration_test.cc
> test/common/quic/test_utils.h
> test/common/grpc/grpc_client_integration.h
> test/integration/multiplexed_integration_test.cc
> test/integration/http2_flood_integration_test.cc
> test/integration/sds_dynamic_integration_test.cc
> test/integration/ads_integration.h
> ```
> 
> Thank you for the refactor, looks great otherwise

Done.  It turns out there are three files on this list that this PR has not touched yet until the last commit: the ones in test/extensions/transport_sockets/tls/.

**Review by KBaichoo — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
