### PR TITLE
Add GrpcClient to filter callback to unnecessary hashing in dataplane

### PR DESCRIPTION
**Pull request by DiazAlan**
Commit Message: This PR adds the Grpc Client to the filter callback, previously it would hash the GrpcService proto on every request which caused overhead.
Additional Description: Something worth discussing is if we want to implement this within the Envoy Grpc section of the code. It already looks quite similar but I wanted to get feedback from the community first.
Risk Level: Low
Testing: Changed test to have a GoogleGrpc version that expects the getClient method only 5 times

### CODE REVIEW

**Review by ggreenway — COMMENTED** [review]
Do you have data on how much overhead the lookup in the lru cache is adding?

One downside to this approach is that the connection can no longer be removed from the async client manager's lru cache; this client will live as long as the ext_authz filter is configured.

/wait-any

**Comment by DiazAlan** [comment]
The lookup is about 4%-5% of our dataplane usage as it hashes on every single request.

**Comment by ggreenway** [comment]
> The lookup is about 4%-5% of our dataplane usage as it hashes on every single request.

Yikes!

I'd assume we take the same perf hit on any other filter/extension that does a grpc call per request: ext_proc, grpc access logging, rate limit, etc. Can we just make `getOrCreateRawAsyncClient()` more efficient so that all uses get the benefit? Maybe change the API so that the caller can precompute the hash and store it, instead of hashing for each call?

/wait-any

**Comment by DiazAlan** [comment]
Could that be something done in a follow up PR?

**Comment by ggreenway** [comment]
> Could that be something done in a follow up PR?

I'd rather figure out the correct API first, rather than put in a one-off that we have to back out later.

**Comment by pradeepcrao** [comment]
> > The lookup is about 4%-5% of our dataplane usage as it hashes on every single request.
> 
> Yikes!
> 
> I'd assume we take the same perf hit on any other filter/extension that does a grpc call per request: ext_proc, grpc access logging, rate limit, etc. Can we just make `getOrCreateRawAsyncClient()` more efficient so that all uses get the benefit? Maybe change the API so that the caller can precompute the hash and store it, instead of hashing for each call?
> 
> /wait-any

That sounds like a good solution. We just need to be careful that the precomputed hash is invalidated when the corresponding raw async client is evicted when the eviction timer fires. Should be doable.

**Comment by ggreenway** [comment]
Yes, I was thinking of an API that takes both the proto config, and a pre-computed hash. If the hash isn't found in the LRU cache, the config is used to (re-)create it. If it is found, then we don't need to use the proto config. But I'm not sure how to handle hash-collisions. Is an equality check on a protobuf as expensive as hashing it?

**Comment by DiazAlan** [comment]
Closed in favor of [#29199](https://github.com/envoyproxy/envoy/pull/29199)

**Pull request closed without merging**
