### PR TITLE
envoy.reloadable_features.use_observable_cluster_name deprecation

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Loong <loong.dai@intel.com>

Commit Message: 

#15139 ([cluster] Use alt_stat_name for general observability purposes (access log, tracing, admin)) introduced a runtime guarded feature, which has been 6 months since the new code has been exercised by default, so remove the old code path.

Additional Description:

Risk Level: Low
Testing:
Docs Changes:
Release Notes: Deprecate envoy.reloadable_features.use_observable_cluster_name.
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] #18447
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by adisuissa — CHANGES_REQUESTED** [review]
Thanks for cleaning this!
Changes LGTM, please add release notes.

/wait

**Comment by daixiang0** [comment]
@adisuissa thanks for quick review, I will do it.

**Review by adisuissa — CHANGES_REQUESTED** [review]
/lgtm api
Please add an entry to the release notes (https://github.com/envoyproxy/envoy/blob/main/docs/root/version_history/current.rst).

/wait

**Comment by daixiang0** [comment]
@adisuissa added, thanks.

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!
/assign-from @envoyproxy/senior-maintainers

**Review by zuercher — APPROVED** [review]

**Pull request merged**
