### PR TITLE
Removed mutexes from AllMuxesState singletons used by muxes.

### PR DESCRIPTION
**Pull request by dmitri-d**
Muxes always execute on the main thread, no thread synchronization is required.

Signed-off-by: Dmitri Dolguikh <ddolguik@redhat.com>

ping @ggreenway, @htuch.

### CODE REVIEW

**Comment by htuch** [comment]
This seems right based on the rationale that muxes are only used for xDS config fetch and that should always be on the main thread. We do have gRPC clients that aren't on the main thread, but they don't use muxes. @ggreenway WDYT?

**Comment by dmitri-d** [comment]
@KBaichoo: any chance you could take a look at the tsan failure? It looks like a FakeUpstream is still handling the reset when the test (ResettingStreamUnregistersAccount, http2) calls its dtor. Perhaps the test should wait for upstream to see the reset?

**Comment by KBaichoo** [comment]
will take a look at it

**Comment by yanavlasov** [comment]
LGTM will wait for tsan to green on main

**Review by ggreenway — APPROVED** [review]
LGTM

**Comment by dmitri-d** [comment]
The tsan failure should be fixed in https://github.com/envoyproxy/envoy/pull/17609.

**Pull request merged**
