### PR TITLE
lint: forbid the use of absl::string_view?

### PR DESCRIPTION
**Pull request by stedsome**
Signed-off-by: Yifan Yang <needyyang@google.com>

This is a follow-up to the related discussion on https://github.com/envoyproxy/envoy/issues/12341, as I believe we have left the fate of absl::string_view v.s. std::string_view undecided. Just want to throw this PR out here and see how people feel about this change.

A little note on the huge number of whitelisted files of absl::string_view. This is created in order to pass the presubmit format check hook where the check format script is run against the entire envoy directory. Granted, this is not a perfect solution as it permits new use of absl::string_view in the whitelisted files and it adds a lot of text to the check_format script. But this is the cleanest solution I can think of among the alternatives. 

Commit Message:
Additional Description:
Risk Level: Low, as it is intended to be entirely cosmetic. absl::string_view should be redirected to std::string_view with the current envoy build configuration. 
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by mattklein123** [comment]
FWIW I'm -1 on this change. The size of the allow list makes it almost meaningless and I don't see how it matters whether we use absl or std string view in practice. I would actually rather just outright block std::string_view and then at some point in the future do a bulk replace.

cc @envoyproxy/maintainers for thoughts

**Comment by jmarantz** [comment]
Yeah just a big PR to fix everything all at once and enforce cleanly is what I'd recommend as well.

**Comment by junr03** [comment]
> I would actually rather just outright block std::string_view and then at some point in the future do a bulk replace.

I agree with @mattklein123 and @jmarantz per my comments here: https://github.com/envoyproxy/envoy/issues/12341#issuecomment-667394461. Being in a middle state with both usages in the codebase seems more confusing and hard to track for little to no benefit.

**Comment by stedsome** [comment]
In that case, I will go ahead and close this.

**Pull request closed without merging**
