### PR TITLE
Cleanup clangtidy issues related to function name: createListenerFilterFactoryList_

### PR DESCRIPTION
**Pull request by yanjunxiang-google**
ClangTidy CI scripts is reporting below errors:

/build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/source/server/listener_manager_impl.h:279:48: error: invalid case style for function 'createNetworkFilterFactoryList_' [readability-identifier-naming,-warnings-as-errors]

  static std::vector<Network::FilterFactoryCb> createNetworkFilterFactoryList_(

                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

                                               createNetworkFilterFactoryList

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by adisuissa** [comment]
I can confirm that modifying `source/server/listener_manager_impl.h`, and running `ci/run_envoy_docker.sh 'ci/do_ci.sh bazel.clang_tidy'` causes the following error:
```
Running clang-tidy-diff against d88f31b39e6502d85ecc6fd6ebb2cc170624750a (d88f31b39e6502d85ecc6fd6ebb2cc170624750a), current HEAD (d88f31b39e6502d85ecc6fd6ebb2cc170624750a)
/build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/source/server/listener_manager_impl.h:49:48: error: invalid case style for function 'createNetworkFilterFactoryList_' [readability-identifier-naming,-warnings-as-errors]
  static std::vector<Network::FilterFactoryCb> createNetworkFilterFactoryList_(
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                               createNetworkFilterFactoryList
```

@phlax @lizan Can you think what could have caused this error?

**Review by lizan — APPROVED** [review]

**Comment by lizan** [comment]
@adisuissa clang-tidy operates on diff and that check was added after this function is named. So a change will trigger that being reported.

**Pull request merged**
