### PR TITLE
references rephrase

### PR DESCRIPTION
**Pull request by ankatare**
Signed-off-by: Abhay Narayan Katare <abhay.katare@india.nec.com>

Commit Message: Rephrase references 
Additional Description:
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/setup#install-git
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/setup#curl
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/setup#jq
Risk Level: LOW
Testing:
Docs Changes: Yes
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]
part of #11027

### CODE REVIEW

**Comment by phlax** [comment]
i dont have a huge objection to this but im not sure its an improvement - i used the longer sentence for the link because it gives a bigger target to aim for

what was the rationale for changing ?

**Comment by ankatare** [comment]
@phlax i thought to make it consistence across docs as many places it has been used as shorter sentences like
https://www.envoyproxy.io/docs/envoy/latest/start/install#install-envoy-on-mac-osx.

e.g. for docker it is https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/setup#install-docker
for curl and jq it is... 
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/setup#curl
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/setup#jq

**Comment by ankatare** [comment]
please suggest.

**Comment by phlax** [comment]
> please suggest.

no strong feelings about this other than a vague opinion and an explanation as to why it was done that way

**Comment by mattklein123** [comment]
Yeah I agree with @phlax that I'm not sure this is an improvement so I'm going to close.

**Pull request closed without merging**
