### PR TITLE
http: removes nghttp2 from a utility library

### PR DESCRIPTION
**Pull request by birenroy**
Signed-off-by: Biren Roy <birenroy@google.com>

Commit Message: Rewrites Http::Common::Utility to avoid use of nghttp2 types.
Additional Description:
Risk Level: low
Testing: ran Envoy tests locally
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Comment by moderation** [comment]
/lgtm deps

Can `nghttp2` be removed as a dependency? https://github.com/envoyproxy/envoy/blob/main/bazel/repository_locations.bzl#L454-L467

**Review by KBaichoo — APPROVED** [review]
lgtm, thank you.

@moderation  I don't think nghttp2 can be removed yet? But I think we're making great progress towards it.

**Pull request merged**
