### PR TITLE
deps: Fix dependency checker (return code) + date fixes

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
/wait for #22502 as it is required for this to pass

**Comment by phlax** [comment]
i have combined the date fix(es) into this PR

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
