### PR TITLE
Maglev: Compact maglev table

### PR DESCRIPTION
**Pull request by KBaichoo**
Commit Message: Fix PR#25149 for Envoy Mobile.
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks for fixing this. Testing by building with this command now and will report back when that finishes:

```
./bazelw build --fat_apk_cpu=x86 //:android_dist
```

**Comment by KBaichoo** [comment]
:P this doesn't have the fix yet, was going to rely on CI compaining about the error so then I know if I add the fix that CI will catch it

**Comment by jpsim** [comment]
> :P this doesn't have the fix yet, was going to rely on CI compaining about the error so then I know if I add the fix that CI will catch it

Ah sorry I saw the PR was marked "ready for review" but should have checked the code.

CI won't catch this because we don't build for x86 in this repo (we should, but CI capacity has been an issue that we're trying to balance).

CI would catch this if you changed it: https://github.com/envoyproxy/envoy/blob/463e978518f75ba4bb8d372666e2bab12efcf06c/.github/workflows/android_build.yml#L44

Change that to `--fat_apk_cpu=x86_64,x86` and it should complain.

**Comment by KBaichoo** [comment]
Thanks @jpsim got the CI reproduction: https://github.com/envoyproxy/envoy/actions/runs/4198234281/jobs/7281596002!

**Review by jpsim — APPROVED** [review]

**Review by adisuissa — DISMISSED** [review]
IIUC the addition to #25149 is in [760406](https://github.com/envoyproxy/envoy/pull/25609/commits/760406faf7b60bf325733b2ec540ccbec658f6b7).
The fix LGTM.

Assigning previous senior-maintainer for final review.
/assign @mattklein123

**Review by jpsim — APPROVED** [review]

**Review by adisuissa — APPROVED** [review]

**Pull request merged**
