### PR TITLE
ext_proc: generalize ext proc mock client for http service configs

### PR DESCRIPTION
**Pull request by antoniovleonti**
Commit Message: generalize ext proc mock client for http service configs
Additional Description:

There's a fuzz bug caused by an http service being configured in the ext_proc filter.  This is because the mock client currently dereferences the stream parameter since it was written assuming the ext_proc was a grpc service. With the introduction of http services, the mock client can no longer blindly dereference the stream.

Risk Level: none
Testing: fixing fuzz test
Docs Changes: none
Release Notes: none
Platform Specific Features: none

### CODE REVIEW

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!
Off to @tyxia for code-owner's review and merge.

**Review by tyxia — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
