### PR TITLE
server: initialize runtime loader singleton so that deprecations fails validate mode

### PR DESCRIPTION
**Pull request by zuercher**
Prior to this change the config validation mode (--mode validate) would not detect
deprecated fields in used in the bootstrap config.

Risk Level: low (increases correctness of config validation)
Testing: existing smoke tests + manual verification with a relevant config
Docs Changes: n/a
Release Notes: n/a

Signed-off-by: Stephan Zuercher <zuercher@gmail.com>

### CODE REVIEW

**Comment by yanavlasov** [comment]
@zuercher please merge master to clear out clang-tidy error.

**Comment by zuercher** [comment]
(I had already merged master and the clang-tidy failure was a download error, so I'm going to let it retry.)

**Comment by zuercher** [comment]
I originally balked on writing a test because any test of deprecated features would quickly go out of date. But I realized that I just need to test that the runtime loader is in place. I think this covers it.

**Comment by mattklein123** [comment]
Oops clang-tidy looks legit. You mind fixing?

/wait

**Pull request merged**
