### PR TITLE
http2: reenables oghttp2 by default

### PR DESCRIPTION
**Pull request by birenroy**
Flips the runtime feature `envoy_reloadable_features_http2_use_oghttp2` to be true by default.

Commit Message:
Additional Description:
Risk Level:
Testing: ran unit and integration tests locally, ran load tests exercising Envoy with oghttp2
Docs Changes:
Release Notes: Changes the default HTTP/2 codec from nghttp2 to oghttp2. Can be reverted by setting "envoy_reloadable_features_http2_use_oghttp2" to false.
Platform Specific Features:

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]
Let's go!

**Review by adisuissa — COMMENTED** [review]
This should probably have a release note (similar to #31086).

**Comment by RyanTheOptimist** [comment]
> This should probably have a release note (similar to #31086).

Oh, that's a very good point. @birenroy can you add one?

**Comment by birenroy** [comment]
> > This should probably have a release note (similar to #31086).
> 
> Oh, that's a very good point. @birenroy can you add one?

Done, thank you both.

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
