### PR TITLE
ci/tests: Re-issue test certs

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by soulxu — APPROVED** [review]
LGTM, thanks

**Comment by phlax** [comment]
headsup for future selves - the script to rebuild the certs (`test/config/integration/certs/certs.sh`) requires openssl 1.1 - so failed my initial attempts at using openssl from my host machine which is much newer

not sure what is required to make this work with newer versions, but for now using openssl from docker build image seems to work

**Comment by phlax** [comment]
cc @ggreenway

**Pull request merged**
