### PR TITLE
Make only once abort or delay decision

### PR DESCRIPTION
**Pull request by wbpcode**
Signed-off-by: wbpcode <comems@msn.com>

Description:

In the original logic of fault filter, when the header contains the `x-envoy-downstream-service-cluster`, fault filter will execute the decision whether to abort or delay twice. As a result, the actual abort or delay ratio does not meet expectations. The expectations is `p` and the actual value will be `2p-p^2`.

For example, when the abort ratio is configured as 50%, if the header contains `x-envoy-downstream-service-cluster`, the actual abort ratio is 75%.

This problem can be reproduced by enabling `add_user_agent`. The current PR fixes this problem.

@alyssawilk 
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by alyssawilk** [comment]
Let me know when this is ready and I'll take a look!

**Comment by wbpcode** [comment]
It is ok and only a few lines of code have been modified. @alyssawilk

**Comment by alyssawilk** [comment]
the tests appear to be failing though.  Mind taking a look?

**Comment by wbpcode** [comment]
This is my negligence, I forgot to fix the test and check the results of the test. It's ok now.

**Comment by wbpcode** [comment]
It is done.

**Pull request merged**
