### PR TITLE
http: abort filter chain after reset stream was called

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: http: abort filter chain after reset stream was called
Additional Description:

To close https://github.com/envoyproxy/envoy/issues/26994. The #26994 is caused by that the filter chain still continue and try to send reply after the whole stream is closed. We should abort the filter chain to avoid any possible further logic after the stream is reset.

Also see https://github.com/envoyproxy/envoy/pull/30835 for more context.

Risk Level: low.
Testing: integration.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
cc @kyessenov @soulxu @vikaschoudhary16 @phlax

**Review by alyssawilk — COMMENTED** [review]
This looks like a good change.  Please runtime guard just in case though, include on release notes and tag both if we should backport, and if we think this needs to land before the release
/wait

**Comment by alyssawilk** [comment]
cc @phlax @RyanTheOptimist @yanavlasov for release context

**Comment by wbpcode** [comment]
It take too much time to run these tests on my PC. Let the ci check it. orz

**Review by alyssawilk — APPROVED** [review]

**Comment by alyssawilk** [comment]
hmmm, I  just realized it's possible we need to do the same here for the 2 other resetStream calls in the filter_manager so have
https://github.com/envoyproxy/envoy/blob/main/source/common/http/filter_manager.cc#L966
and 
https://github.com/envoyproxy/envoy/blob/main/source/common/http/filter_manager.cc#L1007
call your newly enhanced resetStream function rather than call the filter manager callbacks directly.  

You want to fix or shall I?
h/t @fredyw for making me look at this code today =P

**Comment by wbpcode** [comment]
@alyssawilk I knew that code when I doing the fix.

**The change is optional** because the sendLocalReply self will handle the status correctly.

Basically, I treat the `resetStream` and `sendLocalReply` of `FilterManager` as two independent methods and will handle the status and reset behaviour by itself.

**Pull request merged**
