### PR TITLE
ci: use azp to generate docs

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Comment by lizan** [comment]
test commit generated: https://github.com/envoyproxy/envoyproxy.github.io/commit/f6745848940a33a524ffe6d098af3d2a146851b2

**Comment by mattklein123** [comment]
Very nice. Did you test a tag build also? Would like to make sure that still works for the next release(s). Also, we should backport this, right?

/wait-any

**Comment by lizan** [comment]
@mattklein123 yes, https://github.com/envoyproxy/envoyproxy.github.io/commit/c749f00630fd94aef63a18f02b2273693049983d

**Review by mattklein123 — APPROVED** [review]
Nice! I will force merge and fix the required checks.

**Pull request merged**
