### PR TITLE
mobile/ci: Fix flaky start Android emulator step

### PR DESCRIPTION
**Pull request by fredyw**
This is an attempt to fix multiple timeout failures when starting the Android emulator by doing the following:
- Update the system image to Android 30 ATD image instead of 29. The ATD image is a headless system image that consumes less CPU and memory. 
- Use a specific hardware profile, i.e. Pixel 4 instead of the default hardware profile since the default hardware profile only has 128MB.

This also adds some logging when starting the emulator instead of redirecting everything to `/dev/null` to make debugging easier.

Risk Level: low
Testing: CI
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by phlax** [comment]
@fredyw i wondered about this previously - im not sure if increasing the timeout is helpful or just slows things down

like when its successful (eg here https://github.com/envoyproxy/envoy/actions/runs/6576983948/job/17870664914) it only takes 4-5 mins to start the emulator, so not sure if its timing out or just hanging for some other reason

**Comment by fredyw** [comment]
> @fredyw i wondered about this previously - im not sure if increasing the timeout is helpful or just slows things down
> 
> like when its successful (eg here https://github.com/envoyproxy/envoy/actions/runs/6576983948/job/17870664914) it only takes 4-5 mins to start the emulator, so not sure if its timing out or just hanging for some other reason

Yeah, I'm only experimenting with this. Increasing the timeout didn't seem to fix it, but at least now we have some logging, which can hopefully help us to debug this issue.

**Comment by phlax** [comment]
@fredyw would you mind pushing an empty commit or similar so i can see a fresh ci run

**Comment by fredyw** [comment]
> @fredyw would you mind pushing an empty commit or similar so i can see a fresh ci run

Done. Re-running the CI now.

**Review by phlax — APPROVED** [review]
lgtm, thanks @fredyw 

now we have decent logging im wondering about increasing the timeout - maybe we should increase some - seems it can take ~10 mins - and at least with this we will be able to see the output

also wondering about the `nil` device and whether that is causing startup issues and/or can be resolve

**Comment by fredyw** [comment]
> lgtm, thanks @fredyw
> 
> now we have decent logging im wondering about increasing the timeout - maybe we should increase some - seems it can take ~10 mins - and at least with this we will be able to see the output
> 
> also wondering about the `nil` device and whether that is causing startup issues and/or can be resolve

Good idea on increasing the timeout. I noticed that, too. I will send a PR to increase it to 15 mins. As for the `nil` device, it's normal. It will stop once the emulator is fully booted up as in https://github.com/envoyproxy/envoy/blob/dc841d18fd45ff8043dcc0d3bb9e7f8e84768d55/mobile/ci/start_android_emulator.sh#L13

**Comment by phlax** [comment]
hmm maybe we should supress that output, its not very helpful

**Pull request merged**
