### PR TITLE
Add test coverage for json package

### PR DESCRIPTION
**Pull request by tommyp1ckles**
Improving test line coverage for json tests
Signed-off-by: Tom Hadlaw <tomhadlaw@gmail.com>

Additional Description: Adding more tests to increase line coverage for json package. Adding coverage for missing code paths by testing various loadFromString inputs.
Risk Level: Low
Testing: Added tests to json_loader_test
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

This PR seeks to improve this issue: https://github.com/envoyproxy/envoy/issues/1963

### CODE REVIEW

**Comment by phlax** [comment]
@tommyp1ckles CI failures seem genuine

**Comment by tommyp1ckles** [comment]
Indeed, the behaviour of the non-legacy and legacy json decode seems to diverge in some cases, such as in handling empty objects/arrays.

**Comment by htuch** [comment]
@alyssawilk @asraa can we remove the legacy JSON parser now? We've had both paths for a year, but only default enabled in Nov https://github.com/envoyproxy/envoy/pull/18861. Or do we want to do this after cutting the release?

**Comment by htuch** [comment]
@tommyp1ckles thanks for the contribution. For posterity could you describe the quantitative improvement in coverage of the file in question or overall coverage? Happy to merge with that.

**Comment by tommyp1ckles** [comment]
@htuch Sure, the PR increases line coverage in [json_internal.cc](https://github.com/envoyproxy/envoy/blob/main/source/common/json/json_internal.cc#L291 ) by adding test cases covering various missing code paths through the `buildJsonDocument` function relating to different json field types.   

This takes the line coverage for json_internal.cc from [88.5%](https://storage.googleapis.com/envoy-postsubmit/main/coverage/source/common/json/json_internal_legacy.cc.gcov.html) to [92.1%](https://storage.googleapis.com/envoy-pr/374ce72/coverage/source/common/json/json_internal_legacy.cc.gcov.html).

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Comment by alyssawilk** [comment]
@htuch I think not quite yet.  The new version was off by default and while we had a TODO to flip it on it was lost with asraa's transfer.  I noticed it while doing the last release and flipped in in https://github.com/envoyproxy/envoy/pull/18861 but we haven't had a release cut with the new version so I think removal of the old is premature.  That said now we've flipped it on by default, the tooling will remind us when it's safe to remove.

**Pull request merged**
