### PR TITLE
listener: deprecate use_proxy_proto

### PR DESCRIPTION
**Pull request by tbarrella**
Commit Message:

listener: deprecate use_proxy_proto
    
Signed-off-by: Taylor Barrella <tabarr@google.com>

Additional Description:
Risk Level: Low
Testing: grep for occurrences of use_proxy_proto
Docs Changes: Updated references to use_proxy_proto to refer to the listener filter instead, as well as sample configuration
Release Notes:
#14085
Deprecated: envoy_v3_api_field_config.listener.v3.FilterChain.use_proxy_proto was deprecated because the proxy protocol listener filter can/should be added at the listener level instead

### CODE REVIEW

**Review by lizan — APPROVED** [review]
/retest

**Comment by tbarrella** [comment]
Hey @lizan it seems one of the tests has been stuck for hours, what do I do?

**Comment by tbarrella** [comment]
Opened #14445 although that unstuck this one too (is there a way for me to do that without opening a new PR?)

**Comment by mattklein123** [comment]
Can you try merging main into this PR?

**Comment by tbarrella** [comment]
(just a heads up that I plan to be taking a break from tomorrow to 1/4)

**Pull request merged**
