### PR TITLE
[Wasm] Remove js glue code for linking

### PR DESCRIPTION
**Pull request by bianpengyuan**
Remove js glue code since it is not needed since emscripten 2.0.5:
```
- The WebAssembly table is now created and exported by the generated wasm
  module rather then constructed by the JS glue code.  This is an implemention
  detail that should not affect most users, but reduces code size. (#12296)
```

And remove `envoy_wasm_cc_binary` since we no longer need to deal with js files

cc @lizan @PiotrSikora 

Signed-off-by: Pengyuan Bian <bianpengyuan@google.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Review by PiotrSikora — DISMISSED** [review]
Nice!

**Comment by lizan** [comment]
Nice, I thought you're moving wasm_cc_library to proxy-wasm-cpp-sdk, if that's the case it might make sense to keep envoy_wasm_cc_binary wrapper.

**Comment by bianpengyuan** [comment]
Yeah I am moving it there: https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/pull/68. Js library seems to be the only reason why we have `envoy_wasm_cc_rule`, not sure why we'd need this indirection? Is it for consistency with other envoy_* rules?

**Comment by PiotrSikora** [comment]
Yes, JS glue was the only reason for `envoy_*` rule.

But if we're moving everything to C++ SDK, then we should probably wait until it's merged there and update the C++ SDK SHA in this PR.

**Comment by bianpengyuan** [comment]
Ok sg, will wait for the sdk PR merged then.

**Comment by lizan** [comment]
I needed this (but not removing envoy_* rules) to enable Windows/Arm64 wasm, https://github.com/envoyproxy/envoy/pull/14114

**Comment by bianpengyuan** [comment]
@lizan updated the proxy wasm cpp sdk sha and cpp wasm build is using the rule there now.

**Comment by bianpengyuan** [comment]
Close this in favor of https://github.com/envoyproxy/envoy/pull/14114

**Pull request closed without merging**
