### PR TITLE
add gtest_repeat to reproduce the flake issue 

### PR DESCRIPTION
**Pull request by zhangbo1882**
https://github.com/envoyproxy/envoy/issues/25607

### CODE REVIEW

**Comment by phlax** [comment]
@zhangbo1882 so that fails on arm and windows (not sure how it passes on the x64 build)

i would next set the timeout to the default and see if just repeated running can trigger in CI

if we are lucky and it does - then lets increase the timeout

**Comment by zhangbo1882** [comment]
@phlax ,  do you know why it did not print the failure logs as before ?

**Comment by phlax** [comment]
too many errors/log lines (i think they should be uploaded as artefacts, not sure)

**Comment by phlax** [comment]
still failing on windows https://dev.azure.com/cncf/envoy/_build/results?buildId=130169&view=logs&j=b840a642-5ff3-5357-2e4b-e06e40b0cffd&t=67965174-5100-5631-9dc0-68b9f0aacb53&l=1510

**Comment by zhangbo1882** [comment]
It seems that the default timeout for a integration test case is 5 minutes. (https://bazel.build/reference/be/common-definitions). So it is not good to repeat one test case 1000 times which may exceed 5 minutes.

**Comment by phlax** [comment]
ah - yep - so was that the win fail? - the log has gone now

**Comment by mattklein123** [comment]
Please use the instructions here to reproduce flakes: https://github.com/envoyproxy/envoy/tree/main/test/integration#reproducing-test-flakes. We aren't going to merge this again until a maintainer verifies there are no obvious flakes so please work on it locally. We will also verify that the tests don't take a very large amount of time to run. I will close this in the interim.

**Comment by zhangbo1882** [comment]
@mattklein123 ,  I have tried many times locally as https://github.com/envoyproxy/envoy/tree/main/test/integration#reproducing-test-flakes .  But I cannot reproduce  it.
So I change the default timeout value from default 10s to 1ms and it can be reproduced.  @phlax and I suspect the failure CI is caused by the resource outage so that it can not reponse in time. 
```
test_server_->waitForCounterEq("cluster.cluster_1.health_check.success", 2, std::chrono::milliseconds(1));
```
What I plan to do is change the timeout value  from 10s to 30s.

**Comment by mattklein123** [comment]
My point is you have to refactor the test to not rely on response time. So look at what the test is doing and please figure out a way to test what you need to do without sleeps/delays.

**Pull request closed without merging**
