### PR TITLE
quic: Fix crash bug with QUIC upstream + X.509v1 certificates

### PR DESCRIPTION
**Pull request by RyanTheOptimist**
quic: Fix crash bug with QUIC upstream + X.509v1 certificates

When `EnvoyQuicProofVerifier::VerifyCertChain()` is called with a v1 certificate, it uses `CertificateView::ParseSingleCertificate()` to parse this certificate, and assumes (via `ASSERT`) that the result is non-null. However, [this method only supports X.509v3 certificates](https://quiche.googlesource.com/quiche/+/refs/heads/main/quiche/quic/core/crypto/certificate_view.cc#387). If it encounters an X.509v1 certificate, it will return `nullptr`. When this happens in release mode, the ASSERT is skipped and the subsequent call to `cert_view->public_key()` crashes.

This was reported via envoy-security@ by Claire Lui (claireecf@gmail.com)

Risk Level: Low
Testing: New tests
Docs Changes: N/A
Release Notes: Updated

### CODE REVIEW

**Review by RyanTheOptimist — COMMENTED** [review]
/assign @danzh

**Review by danzh2010 — APPROVED** [review]
Thanks for the fix!

**Review by alyssawilk — APPROVED** [review]
Literally no ideas on how to make this PR better than it is =P
Thanks for the quick, clean, well tested fix!

**Comment by alyssawilk** [comment]
/wait on CI just to get it off my dashboard =P

**Comment by alyssawilk** [comment]
(or lmk if you want forcemerge)

**Pull request merged**
