### PR TITLE
http_connection_manager: support multiple SAN URIs for XFCC

### LINKED ISSUE #20723: XFCC in APPEND_FORWARD or SANITIZE_SET only uses the first URI present
*Title*: XFCC in APPEND_FORWARD or SANITIZE_SET only uses the first URI present

*Description*:

Presently only the first SAN URI is preserved in XFCC headers. For users that have multiple SAN URIs no information is propagated in the `By=` and `URI=` portion of the XFCC header.

While some users use `spiffe://` and `spiffe://` only there are others that need other URI information.

[optional *Relevant Links*:]

[Envoy XFCC docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#enum-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-forwardclientcertdetails)

### PR DESCRIPTION
**Pull request by jacob-delgado**
Commit Message:

...when using APPEND_FORWARD and SANITIZE set.

Currently XFCC only keeps the first URI in a certificate or a header presented
to it.

This works fine for most use cases, however, not everyone uses a single
URI (typically spiffe:// only).

Add every URI present to the 'By=' portion as well as the 'URI=' portion of an
XFCC header.

Additional Description:
Risk Level: Low
Testing: Unit and integration tests
Docs Changes: Yes. The appropriate http_connection_managers configuration section.
Release Notes: Yes
Fixes #20723

### CODE REVIEW

**Comment by jacob-delgado** [comment]
The core requirement we are asked is to support is `URI=`. However, as I was reviewing the code I stumbled on `By=` also just looking at the code. I'm not sure if this was intentional or not.

I can put this behind a feature toggle if needed to get this merged. I would also like for this to be as a feature toggle in Envoy 1.19-1.21 as well, if possible. Thoughts?

**Review by lizan — APPROVED** [review]
Looks good and I don't feel strongly we need a toggle for main branch.

Though I don't think we should backport either even with a toggle but backports are up to stable maintainer @pradeepcrao

**Pull request merged**
