### PR TITLE
Add release target to copy binary after build server_only

### PR DESCRIPTION
**Pull request by keithmattix**
Add a release target to opt into behavior before #29646 was merged, specifically the copying of the final binary to something akin to `envoy_binary.tar.gz`

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by phlax — COMMENTED** [review]
@keithmattix thanks for following up and working on this

the first thing im wondering about is the name

not sure what is best but i would probably err towards `release.server_only.binary`

the next thing is that im trying to remove the `bazel_envoy_binary_build` fun

i had a look at what this builds for comparison to our newer bazel code path

this is what this target builds:

```console
$ find linux/amd64/
linux/amd64/
linux/amd64/build_envoy_release_stripped
linux/amd64/build_envoy_release_stripped/envoy
linux/amd64/build_envoy_release
linux/amd64/build_envoy_release/envoy.dwp
linux/amd64/build_envoy_release/schema_validator_tool
linux/amd64/build_envoy_release/su-exec
linux/amd64/build_envoy_release/envoy

```

whereas the newer path builds the following (in a tarball)

```console
$ tar tf ~/Downloads/release.tar.zst 
dbg/
dbg/envoy
dbg/envoy-contrib
dbg/envoy-contrib.dwp
dbg/envoy.dwp
envoy
envoy-contrib
utils/
utils/su-exec

```

essentially the difference being that it does include contrib, and doesnt include the `schema_validator_tool` - not sure what is best for that possibly adding a separate ci target

im happy to land this for now (pending name update) but would like to iterate so that it uses the newer code path - i will update it to make contrib optional

at that point it will output a tarball - the current `linux/xxx` paths were used previously for the docker build and that is not the case any longer (not in this way anyhow) so im thinking this is probably not something envoy's ci should continue doing

**Comment by phlax** [comment]
pasting ci advice

```console
  Please fix your editor to ensure:

      - no trailing whitespace
      - no preceding mixed tabs/spaces
      - all files end with a newline
```

**Comment by keithmattix** [comment]
@phlax Thanks for the review! That plan SGTM

**Pull request merged**
