### PR TITLE
thrift_proxy: migrate from v2alpha to v2

### PR DESCRIPTION
**Pull request by rgs1**
We've been using this in prod for a couple of months and for
a few different services.

A few critical bugs have been fixed (#9089 and #6549) and some
necessary stats/features have been added (#9203 and #8994), so
it's probably a good time to graduate this filter.

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

### CODE REVIEW

**Comment by rgs1** [comment]
> We already boosted this into v3 (without `alpha`), I think you can just migrate to v3 configs instead of migrating v2alpha to v2?

and then what happens to v2alpha? It stays around until v2 is deprecated?

**Comment by mattklein123** [comment]
> and then what happens to v2alpha? It stays around until v2 is deprecated?

Right.

**Comment by rgs1** [comment]
> > and then what happens to v2alpha? It stays around until v2 is deprecated?
> 
> Right.

Ok -- that works. I'll send a simpler PR then to just mark the filter as non-alpha.

**Comment by rgs1** [comment]
Follow-up in #9903.

**Pull request closed without merging**
