### PR TITLE
hds: support custom health check port

### PR DESCRIPTION
**Pull request by tony612**
Commit Message: hds: support custom health check port
Additional Description: This is an supplement for this issue https://github.com/envoyproxy/envoy/issues/439
Risk Level: Low
Testing: unit test
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/master/api/review_checklist.md):]

### CODE REVIEW

**Review by htuch — COMMENTED** [review]
Thanks, this is great. Do you think there is any value in having a test in `hds_integration_test`? I'm thinking this would show we actually use the configured port e2e.

**Comment by tony612** [comment]
@htuch I added two integration tests, do you think if they are enough? Please review, thanks.

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Comment by htuch** [comment]
@tony612 this looks great, one last thing, could you add something to `docs/root/version_history/current.rst`? Thanks!

**Comment by tony612** [comment]
@htuch Added. (force-pushed for DCO)

**Comment by htuch** [comment]
@tony612 can you get format to pass? Thanks. It's probably complaining about lexical ordering. Good to go otherwise.

**Comment by tony612** [comment]
@htuch Done.

**Review by htuch — APPROVED** [review]

**Pull request merged**
