### PR TITLE
move ssl impl dependent common/crypto to extensions

### PR DESCRIPTION
**Pull request by bdecoste**
Signed-off-by: William DeCoste <bdecoste@gmail.com>

Description: Moving common/crypto to extensions as the package is now dependent on the ssl implementation
Risk Level: Low
Testing: Standard tests pass
Docs Changes: None
Release Notes: None

### CODE REVIEW

**Comment by htuch** [comment]
I thought the original code was fairly independent of the actual SSL implementation, did something change?

**Comment by PiotrSikora** [comment]
@htuch if by "independent of the actual SSL implementation" you mean "works with both: BoringSSL and OpenSSL", then that's still the case, AFAIK, though it's a bit of a stretch to call it that.

But maybe @bdecoste ran into some issues that aren't obvious from simply looking at the code?

**Comment by htuch** [comment]
Yes, I mean it doesn't rely on the specifics of any given implementation. If this is still true, I vote not to move, but if we have implementation specific changes to how it works, then it makes sense.

**Comment by bdecoste** [comment]
These lines make common/crypto ssl impl dependent and will not compile with OpenSSL (Cannot instantiate EVP_MD_CTX this way)
https://github.com/envoyproxy/envoy/blob/master/source/common/crypto/utility.cc#L6
https://github.com/envoyproxy/envoy/blob/master/source/common/crypto/utility.cc#L

In general anything that imports openssl/* should be considered ssl impl dependant imo. 

Please let me know how to proceed and/or correct. Thanks

**Comment by PiotrSikora** [comment]
@bdecoste perhaps you could make it work with both? I'm not sure what's the exact error and which version of OpenSSL are you compiling against, but this code should work.

**Comment by bdecoste** [comment]
OK, I'll put in a new PR that fixes the EVP_MD_CTX instantiation to use EVP_MD_CTX_new() and frees the *ctx pointer. The problem with the way it's currently instantiated is that the underlying structures in openssl are not exposed and you get an incomplete structure error with "EVP_MD_CTX ctx;". With openssl you have to use the functions for everything and cannot access the underlying structures.

**Comment by bdecoste** [comment]
ERROR: /home/root/workspaces/envoy/source/common/crypto/BUILD:11:1: C++ compilation of rule '//source/common/crypto:utility_lib' failed (Exit 1) envoy_cc_wrapper failed: error executing command /home/root/workspaces/cache/bazel/base/external/local_config_cc/extra_tools/envoy_cc_wrapper -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 96 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
source/common/crypto/utility.cc: In static member function 'static std::vector<unsigned char> Envoy::Common::Crypto::Utility::getSha256Digest(const Envoy::Buffer::Instance&)':
source/common/crypto/utility.cc:16:14: error: aggregate 'EVP_MD_CTX ctx' has incomplete type and cannot be defined
   EVP_MD_CTX ctx;
              ^

**Comment by bdecoste** [comment]
https://github.com/envoyproxy/envoy/pull/5877

**Comment by htuch** [comment]
@bdecoste should we close this one our now?

**Pull request closed without merging**
