### PR TITLE
remove unused variables

### PR DESCRIPTION
**Pull request by giantcroc**
Signed-off-by: giantcroc <1204449533@qq.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by daixiang0** [comment]
lgtm

/cc @phlax need start a clean process for this case? I guess there are some `-Wunused-but-set-parameter` warnings left.

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
