### PR TITLE
c-ares gRPC library: fix a bug impacting gRPC's use of c-ares

### PR DESCRIPTION
**Pull request by adisuissa**
Commit Message: c-ares gRPC library: fix a bug impacting gRPC's use of c-ares
Additional Description:
When a GoogleGrpc service is configured with a domain name and using C-Ares as a resolver results in an immediate disconnect.
The fix (https://github.com/c-ares/c-ares/commit/a070d7835d667b2fae5266fe1b790677dae47d25) is being imported as a patch until c-ares can be upgraded.

Risk Level: low
Testing: N/A
Docs Changes: N/A
Release Notes: Added
Platform Specific Features: N/A

### CODE REVIEW

**Review by botengyao — COMMENTED** [review]
Thanks @adisuissa! This LGTM.

I am wondering if we can upgrade c-ares to [1.21.0](https://c-ares.org/changelog.html#1_21_0) that includes this fix.

**Review by botengyao — APPROVED** [review]

**Comment by adisuissa** [comment]
> Thanks @adisuissa! This LGTM.
> 
> I am wondering if we can upgrade c-ares to [1.21.0](https://c-ares.org/changelog.html#1_21_0) that includes this fix.

It may be, but seeing that later versions were broken, I think it might be better to solve the current issue, and later upgrade to a new version of c-ares.

**Comment by adisuissa** [comment]
/assign @phlax 

Context: users of Envoy v1.31 experienced an issue using a GoogleGrpc service, when the gRPC service needed to resolve a domain name. We tracked it down to a bug in C-Ares that was fixed in [this PR](https://github.com/c-ares/c-ares/commit/a070d7835d667b2fae5266fe1b790677dae47d25).
We decided on cherrypicking this to avoid any complications in upgrading C-Ares to a new version.
After this is merged we will backport the fix to version 1.31.

**Review by phlax — APPROVED** [review]
lgtm, thanks @adisuissa

**Pull request merged**
