### PR TITLE
move common/crypto to extensions for openssl

### PR DESCRIPTION
**Pull request by bdecoste**
Description: Moves all of the ssl api apecific code out of the core code and into extensions. The intent is to keep all of the ssl specific logic in extensions to support simplified plugability of the ssl implementation (e.g. boringssl vs openssl)
Risk Level: Low
Testing: Passes all standard tests
Docs Changes: None
Release Notes: None
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by bdecoste** [comment]
Sure, I think that will work. The problem we keep running into is that boringssl-specific code keeps getting introduced into the common/crypto implementation and breaking openssl. If we can isolate at least the implementation to extensions it becomes much easier to plug in openssl.

**Comment by lizan** [comment]
> The problem we keep running into is that boringssl-specific code keeps getting introduced into the common/crypto implementation and breaking openssl. If we can isolate at least the implementation to extensions it becomes much easier to plug in openssl.

Right, so I think the way to go is to have some sort of plugin mechanism (not relying on existing transport socket) to plug utilities like this. Since this is just utilities, it could be registered as a singleton of the interface definition.

**Comment by bdecoste** [comment]
I agree that transport_sockets is not an ideal place to locate this type of utility code and relocating it to another place just moves the problem so either 1) just leave it where it is and this will just have to be another place that needs to be modified when plugging in openssl or 2) move the impl to something like extensions/common/crypto. At least with #2 it's a little more obvious that this is a pluggable implmentation. What do you think? Thanks.

**Comment by lizan** [comment]
I'm fine either way, up to you. Also I'm curious how much is the deviation from existing BoringSSL implementation to your OpenSSL implementation. If the only diffs are bssl::UniquePtr / bssl::ScopedMD_CTX, then perhaps you can just replace them with Envoy::CSmartPtr?

**Pull request closed without merging**
