### PR TITLE
load balancer: added maglev/ring hash load balancer extension

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: load balancer: added maglev/ring hash load balancer extension
Additional Description:

Further work of #23472. Part of #20634.

Risk Level: Low.
Testing: unit, integration.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
**This is not ready for merge, we need handle the locality correctly first.**

**Review by mattklein123 — APPROVED** [review]
LGTM, thanks.

**Comment by wbpcode** [comment]
Main is merged and conflicts are resolved. cc @mattklein123 could you give a new LGTM?

**Review by mattklein123 — DISMISSED** [review]

**Comment by wbpcode** [comment]
@mattklein123 conflict resolved again. orz. Please give a LGTM again, thanks. orz 🙏

**Comment by wbpcode** [comment]
hmmm, ci is flaky because the wasm.

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
