### PR TITLE
[fuzz] remove tcp proxy from network fuzzers

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Commit Message: Remove tcp-proxy from network fuzzer because the upstream connection isn't set up and we fail on this ASSERT:
https://github.com/envoyproxy/envoy/blob/280654be74c4760a7f61f3658b035e4800f2deca/source/common/tcp_proxy/tcp_proxy.cc#L558
Risk Level: Low

### CODE REVIEW

**Comment by antoniovicente** [comment]
Do we need some further ASSERTs in the TCP proxy filter like possibly: ASSERT(upstream_ != nullptr);

**Comment by asraa** [comment]
> Do we need some further ASSERTs in the TCP proxy filter like possibly: ASSERT(upstream_ != nullptr);

It is possible the `upstream_` was destroyed already, so this is exactly what this ASSERT is capturing. Do you mean for clarity's sake?
https://github.com/envoyproxy/envoy/blob/280654be74c4760a7f61f3658b035e4800f2deca/source/common/tcp_proxy/tcp_proxy.cc#L552-L554

**Comment by antoniovicente** [comment]
> > Do we need some further ASSERTs in the TCP proxy filter like possibly: ASSERT(upstream_ != nullptr);
> 
> It is possible the `upstream_` was destroyed already, but then we should not be reading. This is exactly what this ASSERT is capturing. Do you mean for clarity's sake?
> https://github.com/envoyproxy/envoy/blob/280654be74c4760a7f61f3658b035e4800f2deca/source/common/tcp_proxy/tcp_proxy.cc#L552-L554

I wonder if the ASSERT and reset of the idle timer belong in the body of the "if (upstream_)"

I think you get to keep the fuzz test in that case.

Are there plans to improve these fuzz tests by introducing an upstream connection?

**Comment by asraa** [comment]
> Are there plans to improve these fuzz tests by introducing an upstream connection?

Yes, I should have mentioned -- we are having a CNCF contractor make dedicated TcpProxy fuzzers (hence why this one isn't as critical). Keeping the fuzz test with this issue may give a false sense of security, but I guess you still get configuration fuzzing.

Hmmm maybe I don't see something, but I think the ASSERT is useful there to validate that if there should be no reads when there is no upstream.

**Review by antoniovicente — APPROVED** [review]

**Pull request merged**
