### PR TITLE
[WIP] deps: Bump `com_github_zlib_ng_zlib_ng` -> 2.1.2

### LINKED ISSUE #27869: Newer release available `com_github_zlib_ng_zlib_ng`: 2.1.2 (current: 2.0.7)
Package Name: com_github_zlib_ng_zlib_ng@2.0.7
Current Version: 2.0.7@2023-03-17
Available Version: 2.1.2@2023-06-07
Upstream releases: https://github.com/zlib-ng/zlib-ng/releases

### PR DESCRIPTION
**Pull request by phlax**
Fix #27869 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
patch removed as it seems the required changes have been upstreamed

cc @PiotrSikora

**Comment by phlax** [comment]
fail looks real - not immediately apparent what, but it seems to be something to do with interaction with `envoy-filter-example`

**Comment by PiotrSikora** [comment]
> patch removed as it seems the required changes have been upstreamed
> 
> cc @PiotrSikora

Yes, I believe so.

> hmm - more likely just an issue with wasm/wamr build i think

I don't think so, `compile_time_options` with `wasm=wamr` is simply the first target that's build with `zlib=ng`, and the tests that are failing are unrelated to Wasm.

**Comment by phlax** [comment]
> is simply the first target that's build with zlib=ng

i see thanks

fail is defo real - seems to be related to checksumming - its failing for both de/compression

**Comment by phlax** [comment]
im not certain but it looks like an issue with cmake build flags here https://github.com/envoyproxy/envoy/blob/8df16ca90db93379670a2f15b77245ada1180c8a/bazel/foreign_cc/BUILD#L534-L537

im guessing that turning off SSE4 no longer fixes it

possibly related https://github.com/zlib-ng/zlib-ng/commit/cd37e12f72e8b4265bf890072c2c1193991c6890sca  - altho my attempts at bisecting didnt get past the compile stage using commit versions or the the last beta release

**Comment by phlax** [comment]
and github links are borken - trying again with upstream link https://github.com/zlib-ng/zlib-ng/commit/cd37e12f72e8b4265bf890072c2c1193991c6890

**Comment by phlax** [comment]
fwiw - the breaking change is actually here https://github.com/zlib-ng/zlib-ng/commit/e128537d4db2a4bec431d75b92b7b8e01fbf8bd7

**Comment by phlax** [comment]
i have naively tried to resolve this but its beyond my immediate c++ skills - i managed to get fix the compressor test with

```diff
diff --git a/test/extensions/compression/gzip/compressor/zlib_compressor_impl_test.cc b/test/extensions/compression/gzip/compressor/zlib_compressor_impl_test.cc
index 2e4670913b..6cebc127a0 100644
--- a/test/extensions/compression/gzip/compressor/zlib_compressor_impl_test.cc
+++ b/test/extensions/compression/gzip/compressor/zlib_compressor_impl_test.cc
@@ -184,7 +184,7 @@ TEST_F(ZlibCompressorImplTest, CallingChecksum) {
   TestUtility::feedBufferWithRandomCharacters(buffer, 4096);
   compressor.compressThenFlush(buffer);
   expectValidFlushedBuffer(buffer);
-
+  compressor.finish(buffer);
   drainBuffer(buffer);
   EXPECT_TRUE(compressor.checksum() > 0);
 }

```

not sure whether that is a correct fix or not - but im struggling to pull any similar trick with decompression

the cmake flags have changed so ive also tried updating/experimenting with them but get the same results

**Pull request closed without merging**
