### PR TITLE
mobile: Upgrade XCode version to 15.3

### PR DESCRIPTION
**Pull request by abeyad**
This also requires upgrading to the macos-14 runners, as the macos-12 runners do not support XCode 15.3.

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
Will the mobile CI jobs for this PR use the new Xcode version or is this one of those "CI runs the old version" kinds of changes?

**Comment by abeyad** [comment]
> Will the mobile CI jobs for this PR use the new Xcode version or is this one of those "CI runs the old version" kinds of changes?

Looks like CI is failing with `xcode-select: error: invalid developer directory '/Applications/Xcode_15.3.app'`, so it picked up the right XCode version.  But we probably need to make sure 15.3 is available on the CI machines.

**Comment by fredyw** [comment]
> > Will the mobile CI jobs for this PR use the new Xcode version or is this one of those "CI runs the old version" kinds of changes?
> 
> Looks like CI is failing with `xcode-select: error: invalid developer directory '/Applications/Xcode_15.3.app'`, so it picked up the right XCode version. But we probably need to make sure 15.3 is available on the CI machines.

For GitHub runner, we just need to switch from `macos-12` to `macos-14`: https://github.com/actions/runner-images/issues/9459

I don't know if the EngFlow machines support it, though, but worth checking.

**Comment by ravenblackx** [comment]
I think this is currently failing tests so doesn't need any nagging from the on-call?

/wait

**Pull request closed without merging**
