### PR TITLE
build: add support for pip3_import from rules_python.

### PR DESCRIPTION
**Pull request by htuch**
Provide an Envoy build system styled way of loading arbitrary pip3
packages as py_{library,binary} dependencies.

Part of https://github.com/envoyproxy/envoy/issues/11085 (to fetch
PyYAML).

Risk level: Low (build system)
Testing: Manual validation that the test utility loads PyYAML at the
  correct version (different to my system version).

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

**Comment by htuch** [comment]
CC @adamkotwasinski

**Comment by lizan** [comment]
seems windows CI is failing? LGTM otherwise

**Comment by htuch** [comment]
@lizan this is ready for LGTM/merge.

**Comment by htuch** [comment]
(and thanks a ton to @wrowe and @sunjayBhatia  for helping update the Windows Docker base image!)

**Pull request merged**
