### PR TITLE
quic: enable headers validation in QUICHE

### PR DESCRIPTION
**Pull request by danzh2010**
Commit Message: flip quic_reloadable_flag_quic_act_upon_invalid_header in QUICHE to enable request and response headers validation.

Additional Description: QUICHE reports invalid headers in callback `OnInvalidHeaders()` and Envoy will act based on configuration. Some invalid requests will be reset immediately instead of receiving 400 response.

Risk Level: high, request pipeline changed
Testing: existing tests 
Docs Changes: N/A
Release Notes: changed.
Platform Specific Features: N/A
Runtime guard: envoy.reloadable_features.FLAGS_envoy_quic_reloadable_flag_quic_act_upon_invalid_header

### CODE REVIEW

**Review by adisuissa — COMMENTED** [review]
Thanks, overall LGTM!
Will it make sense to add a test the disables `envoy.reloadable_features.FLAGS_quic_reloadable_flag_quic_act_upon_invalid_header` (to ensure that the disable works as intended)?

Assigning Ryan who may have more context here.
/assign @RyanTheOptimist

**Comment by danzh2010** [comment]
> Thanks, overall LGTM! Will it make sense to add a test the disables `envoy.reloadable_features.FLAGS_quic_reloadable_flag_quic_act_upon_invalid_header` (to ensure that the disable works as intended)?
> 

done

**Comment by RyanTheOptimist** [comment]
This LGTM, too. Though I wonder how this intersects with UHV, since UHV wants to do all of the header validation locally. I would like to make sure @yanavlasov gives a thumbs up. (Though I think you two may have spoken offline)

/assign @yanavlasov

**Comment by danzh2010** [comment]
> This LGTM, too. Though I wonder how this intersects with UHV, since UHV wants to do all of the header validation locally. I would like to make sure @yanavlasov gives a thumbs up. (Though I think you two may have spoken offline)
>

They should be able to change the override in OnInvalidHeaders() to do nothing based on UHV macro.

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
