### PR TITLE
configs: Fix proto validation

### PR DESCRIPTION
**Pull request by phlax**
Commit Message: configs: Fix proto validation
Additional Description:

This fixes example configs in the repo to ensure that they pass protobuf validation

The validation code is PR ed separately (#15284 ) 

As there are a lot of config file updates required i separated them to here to make #15284 easier to review

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by mattklein123** [comment]
Can I ask a probably silly question? Don't we load all of these configs into Envoy as part of the example verification tests? Wouldn't they fail there? What kind of validation is this doing that Envoy isn't?

**Comment by phlax** [comment]
> Can I ask a probably silly question? Don't we load all of these configs into Envoy as part of the example verification tests? Wouldn't they fail there? What kind of validation is this doing that Envoy isn't?

so firstly this PR doesnt add the validation code - just fixes the validation of the config files

the missing validation is protobuf validation.

currently - yep, we do validate that these files will load correctly in envoy - so they are in a sense valid (but only i guess in the sense that a page with malformed html will still load in a browser)

the problem is that envoy is more tolerant than the protobuf spec and this leads to inconsistencies (it confused me on several occasions that the working examples didnt seem to match the spec)

mostly i think we want to make sure all of the examples are correctly validated - there are some cases where maybe the spec is too strict - eg enums of capitalized options

**Comment by mattklein123** [comment]
OK but what code is doing the validating that Envoy isn't doing? That's the part that confuses me.

**Comment by phlax** [comment]
> OK but what code is doing the validating that Envoy isn't doing? That's the part that confuses me.

there are 2 validation paths

- start envoy with the config file (triggered in c++ i believe, but same as starting envoy in validation mode on cli)
- python protobuf validation used for fragment validation

**Comment by mattklein123** [comment]
So the Python code is stricter?

**Comment by phlax** [comment]
yep - matches the `.proto` spec

**Comment by mattklein123** [comment]
OK got it, thanks.

**Comment by phlax** [comment]
@mattklein123 could we land this?

they are all example configs, and are validated by the existing path

it will make #15284 easier to work on

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
