### PR TITLE
v3 packages updates for omit_canary_hosts proto

### PR DESCRIPTION
**Pull request by ankatare**
Commit Message: v3 packages updates for omit_canary_hosts proto.
Additional Description:
Risk Level: LOW
Testing: unit ( proto_format and docs )
Docs Changes: NA
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
part of #12841

### CODE REVIEW

**Comment by dio** [comment]
Seems like you need to update your `./tools/proto_format/proto_format.sh`?

**Comment by ankatare** [comment]
@dio Thanks for your inputs. let me check this.

**Comment by ankatare** [comment]
@dio strange !!! seems my local env is updated with master. and i also double checked `./tools/proto_format/proto_format.sh` and seems it is also in sync. seems something else is the issue :(

**Review by htuch — COMMENTED** [review]
Thanks, see comments 2/3 in https://github.com/envoyproxy/envoy/pull/13814#issuecomment-732261614.

**Comment by ankatare** [comment]
@htuch  Thanks for quick review. i will update and get back ASAP

**Comment by dio** [comment]
Looks good. But this requires @envoyproxy/api-shepherds approval.

**Comment by ankatare** [comment]
@dio Ok.

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
