### PR TITLE
http2: moves some frame accounting to onBeforeFrameReceived.

### PR DESCRIPTION
**Pull request by birenroy**
This is refactoring in preparation for removing the nghttp2_callback API layer.

Commit Message: http2: moves some frame accounting to onBeforeFrameReceived.
Additional Description:
Risk Level: low; refactoring, no functional change intended
Testing: ran unit and integration tests locally
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Review by RyanTheOptimist — COMMENTED** [review]
Is this a behavior change at all? Do we end up with a keep alive timer set when we otherwise wouldn't (or vice versa?)

**Comment by birenroy** [comment]
> Is this a behavior change at all? Do we end up with a keep alive timer set when we otherwise wouldn't (or vice versa?)

I'm attempting to avoid changing behavior. My local run of http2 and integration tests passed without any modifications.

**Review by RyanTheOptimist — APPROVED** [review]
LGTM, but please wait for Dianna's review.

**Review by diannahu — APPROVED** [review]

**Comment by RyanTheOptimist** [comment]
Is this a real failure, do you think? https://dev.azure.com/cncf/envoy/_build/results?buildId=160040&view=logs&jobId=767be981-567e-57d8-68c3-2140ede0a0bd&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=2181edf2-f610-59f2-c43a-04bb9d0bca00 or just a flake?

**Pull request merged**
