### PR TITLE
quic: remove server-preferred-address config WIP status

### PR DESCRIPTION
**Pull request by ggreenway**
Commit Message: These configs have been around for a few releases, and seem to be stable. Removing this status so that Envoy no longer warns when they are used.
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by ggreenway** [comment]
@danzh2010 and @RyanTheOptimist the comment says to discuss before removing the WIP status, so what do you guys think?

**Comment by RyanTheOptimist** [comment]
This sounds fine to me. From the comment it sounds like we should ping API shepherds?

**Comment by RyanTheOptimist** [comment]
/wait
CI looks red.

**Review by abeyad — APPROVED** [review]
/lgtm api

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by ggreenway** [comment]
I'm assuming that signoff from @abeyad should be sufficient consent from api-shepherds. And we're 2.5 months from the next release, so if anyone feels strongly about this, we can revert.

**Pull request merged**
