### PR TITLE
document change

### PR DESCRIPTION
**Pull request by dichen16**
Description: Fix Document issue #8549
Risk Level: Low
Testing: 
Docs Changes: Yes
Release Notes:
[Optional Fixes #Issue]  Document issue #8549
[Optional Deprecated:]

### CODE REVIEW

**Comment by dichen16** [comment]
Hi @jmarantz 

After the change, I compiled Envoy successfully on Fedora 30. Otherwise will have issue #8549.

**Comment by jmarantz** [comment]
Sounds good. Is this true for other Fedora releases? Or is 30 the most recent one?

**Comment by dichen16** [comment]
I am not sure about other release, and 30 is the latest one.

**Comment by jmarantz** [comment]
Maybe update the doc to reflect that these instructions work on Fedora 30?

**Comment by dichen16** [comment]
I find the issue also exists in Fedora 29

**Comment by jmarantz** [comment]
I think your change is basically fine but i have to wonder why whoever wrote the fedora instructions got it wrong. That's why I thought maybe it's version-specific?

**Comment by dichen16** [comment]
Yes, understood, but I think the other release will have the same problem :), I will try to find out

**Comment by dichen16** [comment]
Hi @jmarantz , other releases have same problem, I think we can just add this library to the dependencies list

**Comment by dichen16** [comment]
Hi, 
I just start to contribute Envoy, my environment is pretty clean. I am sure about that. I found this issue when I tried to deploy and test in my first time.
The final patch related to another patch #8642

**Pull request merged**
