### PR TITLE
health check: allow request header formatting for HTTP health check request

### LINKED ISSUE #3835: health_check: request header formatting does not use dynamic request info
*Title*: *health_check: request header formatting does not use dynamic request info*

*Description*:
Using the [command operators](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#custom-request-response-headers) in [http_health_check.request_headers_to_add](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/health_check.proto#core-healthcheck-httphealthcheck) will not work as intended. Specifically, for `%UPSTREAM_METADATA()%`, the lookup will fail and be replaced with an empty string.

For `%DOWNSTREAM_LOCAL_ADDRESS%` it segfaults... but this one (and the other DOWNSTREAM ones) doesn't actually make sense because there is no downstream for healthchecks (or the downstream is envoy itself?)

The problem boils down to the fact that the `RequestInfo` object is never populated with the current request info. https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/health_checker_impl.cc#L159

(I haven't confirmed this, but based on the reading of the code `%START_TIME%` will also be wrong. It will always be the time that the REQUEST_INFO object was constructed)

*Repro steps*:
The simplest repro is to add the header to the health checker tests:

```diff
diff --git a/test/common/upstream/health_checker_impl_test.cc b/test/common/upstream/health_checker_impl_test.cc
index dc041e7..a8befdc 100644
--- a/test/common/upstream/health_checker_impl_test.cc
+++ b/test/common/upstream/health_checker_impl_test.cc
@@ -290,6 +290,9 @@ public:
             key: user-agent
             value: CoolEnvoy/HC
           append: false
+        - header:
+            key: downstream-local-address
+            value: "%DOWNSTREAM_LOCAL_ADDRESS%"
     )EOF";

     health_checker_.reset(new TestHttpHealthCheckerImpl(*cluster_, parseHealthCheckFromV2Yaml(yaml),
```

A more realistic repro is to use `UPSTREAM_METADATA` with EDS endpoints that actually have metadata.

### PR DESCRIPTION
**Pull request by dio**
*Description*: 
This PR enables the use of header formatting pattern for HTTP health check request.
And while at this, the hostname initialization is moved to the `HttpActiveHealthCheckSession`'s constructor for consistency.

*Risk Level*: Low.
*Testing*: Unit test.
*Docs Changes*: Updated.
*Release Notes*: Added.

Fixes #3835

Signed-off-by: Dhi Aurrahman <dio@rockybars.com>

### CODE REVIEW

**Comment by bplotnick** [comment]
Thanks for doing this! I tried this branch out and it definitely fixed my issue (injecting upstream metadata)

**Comment by dio** [comment]
@bplotnick thank you for verifying this! 

@zuercher, thanks for the review. Updated the doc and release note in here: 75d1be9.

**Comment by dio** [comment]
@zuercher is there anything else that I need to look at? Thanks

**Comment by zuercher** [comment]
@alyssawilk do you have time to take a look?

**Pull request merged**
