### PR TITLE
UNCLEANTLY Revert " notifier: adding basic oncall notifications (#298…

### PR DESCRIPTION
**Pull request by alyssawilk**
…20)"

This reverts commit c495291414deb23d132b93bf4a4eff00aca4da4c.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by jmarantz — APPROVED** [review]
blindly approving with no idea of context.

**Comment by phlax** [comment]
as commented offline - i think this is not needed - i believe the ci issue should be fixed (i dont think it ran again yet)

**Review by phlax — CHANGES_REQUESTED** [review]
please dont land w/out confirming its not fixed!

**Review by phlax — APPROVED** [review]
lgtm, thanks @alyssawilk

**Pull request merged**
