### PR TITLE
http: fixing the EM build broken by a namespacing problem

### PR DESCRIPTION
**Pull request by alyssawilk**

### CODE REVIEW

**Comment by alyssawilk** [comment]
Given I tested this locally I'm inclined to force merge once I pass format checks.  Speak now if you object :-P

**Comment by RyanTheOptimist** [comment]
> Given I tested this locally I'm inclined to force merge once I pass format checks. Speak now if you object :-P

SGTM. I might suggest fleshing out the PR description though as it's currently empty.

Any idea why this is broken in EM but fine in Envoy?

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by alyssawilk** [comment]
I think EM was pulling this file from Envoy::Extensions::Http and then it looked for Envoy::Extensions::Http::Callbacks instead of Envoy::Http::Callbacks ?

**Comment by RyanTheOptimist** [comment]
> I think EM was pulling this file from Envoy::Extensions::Http and then it looked for Envoy::Extensions::Http::Callbacks instead of Envoy::Http::Callbacks ?

Oh! Yeah, that makes sense. Thanks!

**Pull request merged**
