### PR TITLE
router: Remove envoy.reloadable_features.consume_all_retry_headers

### LINKED ISSUE #14639: envoy.reloadable_features.consume_all_retry_headers deprecation
Your change #11913 (router: consume all retry related headers) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.
cc @numerodix

### PR DESCRIPTION
**Pull request by numerodix**
Commit Message: router: Remove envoy.reloadable_features.consume_all_retry_headers
Additional Description: This patch removes the
envoy.reloadable_features.consume_all_retry_headers runtime flag. Fixes #14639 
Risk Level: Low
Testing: bazel test //test/common/router/...
Docs Changes: n/a
Release Notes: yes
[Optional Runtime guard:] Removed envoy.reloadable_features.consume_all_retry_headers

Signed-off-by: Martin Matusiak <numerodix@gmail.com>

### CODE REVIEW

**Review by snowp — DISMISSED** [review]
Thanks!

**Comment by snowp** [comment]
Can you merge master to resolve the conflict? Thanks

**Comment by mattklein123** [comment]
Needs a main merge. :(

/wait

**Comment by snowp** [comment]
Can you check CI?

**Comment by numerodix** [comment]
@snowp CI keeps failing on things unrelated to the PR:

>    cached = json.loads(zlib.decompress(data).decode("utf8"))
> zlib.error: Error -5 while decompressing data: incomplete or truncated stream

And:

> WARNING: Download from https://github.com/apache/kafka/archive/2.4.1.zip failed: class java.io.IOException Tried to reconnect at offset 1,474,560 but server didn't support it
> ERROR: An error occurred during the fetch of repository 'kafka_source':

I'll keep trying hoping for more luck.

**Review by asraa — APPROVED** [review]
Thanks!

**Review by snowp — APPROVED** [review]
Thanks!

**Pull request merged**
