### PR TITLE
Only download go sdk when not using host sdk

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Review by htuch — APPROVED** [review]
Hmm, this reliance on host version seems to non-hermetic, why do we have this?

CC @phlax

**Comment by jwendell** [comment]
In downstream builds we override the `go_version` variable setting it to `host`, so that we can use our version of the `go` binary, not the upstream/community vanilla compiler.

**Comment by phlax** [comment]
>  ... override the go_version variable setting it to host

no objections to allowing this - but i think the point remains - why build non-hermetically?

**Comment by jwendell** [comment]
Well, this is subjective, I think. Our builder environment has a very stable set of packages, including the golang compiler. Building using the host tooling (clang, java, go, etc) is a hard requirement for us.

**Review by phlax — APPROVED** [review]

**Pull request merged**
