### PR TITLE
Add dynamic metadata to MatchingData

### PR DESCRIPTION
**Pull request by ashishb-solo**
Commit Message: Add dynamic metadata to MatchingData objects
Additional Description: Enable accessing dynamic metadata in filter_chain_matcher matcher_tree input nodes
Risk Level: low
Testing: unit tests
Docs Changes: none
Release Notes: none
Platform Specific Features: none
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by kdorosh — APPROVED** [review]
lgtm

**Comment by kyessenov** [comment]
Looks fine to me, but please fix the build&tests first.

**Comment by ashishb-solo** [comment]
It looks like the build failed with a tsan issue in CI. I'm not familiar with how to resolve this - if you have a moment, could you please take a quick look and advise on what the problem (and potential fix) might be?

**Review by kdorosh — APPROVED** [review]

**Review by kdorosh — APPROVED** [review]
ci is passing, lgtm. @kyessenov can we take a look at this? thanks in advance

**Pull request merged**
