### PR TITLE
build: use rules_cc

### PR DESCRIPTION
**Pull request by lizan**
Description:
Partially address #9488. Almost generated change by applying `buildifier -lint=fix`.

Risk Level: Low
Testing: local
Docs Changes: N/A
Release Notes: N/A

Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Comment by htuch** [comment]
@lizan can you do a distinct PR with the buildifier linting and add that check to CI? That will make this PR much faster to review.

**Comment by lizan** [comment]
@htuch I tried to add that to check format but it doesn't play nice with the envoy_build_fixer.py (around load/license order etc).

**Comment by lizan** [comment]
@htuch FYI only `bazel/repositories.bzl` and `bazel/repository_locations.bzl` are manual change.

**Comment by htuch** [comment]
@lizan `envoy_build_fixer.py` is using Buildozer. Is this not compatible with `buildifier`? Are there CLI flags to better align them? We could always add a `buildifier` pass at the end of `envoy_build_fixer.py`.

**Pull request closed without merging**
