### PR TITLE
Correct Windows build defects noted with recent version updates

### PR DESCRIPTION
**Pull request by wrowe**
Description:
Picks up from https://github.com/envoyproxy/envoy/pull/10433
windows build regression...

- Pick up curl-7_69_1
- Patch curl to revert change to cmake_minimum_required
  - latest version of curl added a maximum version of cmake 3.16
- Pick up cares-1_16_0
- Toggle crosstool build to avoid possibly injecting wrongly assumed
  flags (/MD or -MD dynamic linkage override of our /MT static build)
- Note that some issues were pre-existing but not previously triggered

Risk Level: Low
Testing: Local on MSVC
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by mattklein123** [comment]
Assigning to @junr03 to potentially help sort out the c-ares issues.

**Comment by junr03** [comment]
From the ASAN failure in https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/35151/logs/68

It looks to me that this is a bug in c-ares:

https://github.com/c-ares/c-ares/blob/077a587dccbe2f0d8a1987fbd3525333705c2249/ares_getaddrinfo.c#L548-L553

`end_query` frees `hquery` but the code then proceeds to keep using `hquery`. Which is exactly what the ASAN run is catching.

**Comment by wrowe** [comment]
@mattklein123 this patch makes no changes to affecting quiche or the ActiveQuicListenerTest, as OS/X reports. We should move ahead with this patch to unblock the curl update.

**Comment by moderation** [comment]
This PR didn't end up updating c-ares from the looks of it @wrowe :
```
    com_github_c_ares_c_ares = dict(
        sha256 = "de058ad7c128156e2db6dc98b8a359924d6f210a1b99dd36ba15c8f839a83a89",
        strip_prefix = "c-ares-1.16.0",
        urls = ["https://github.com/c-ares/c-ares/releases/download/cares-1_16_0/c-ares-1.16.0.tar.gz"],
    ),
```

**Comment by wrowe** [comment]
You are correct. We began by updating c-ares in the same lot as curl. However, as noted above, c-ares 1.16 introduced new regressions that must be addressed before it is ready for master.

**Comment by wrowe** [comment]
(From the comments above, it appears c-ares regressions are upstream code defects, not envoy's use of the library.)

**Pull request merged**
