### PR TITLE
Undeprecate use_original_dst

### PR DESCRIPTION
**Pull request by tbarrella**
Commit Message:

Undeprecate use_original_dst

Signed-off-by: Taylor Barrella <tabarr@google.com>

Additional Description: See https://github.com/envoyproxy/envoy/issues/5355#issuecomment-742905855 and above for context
Risk Level: Low
Testing: Listener unit tests, grep
Docs Changes: Generated documentation for the proto field
Release Notes:
#5355

### CODE REVIEW

**Comment by htuch** [comment]
LGTM, but I'm confused why CI checks are stuck and RepoKitteh hasn't flagged this as an API review.

**Comment by htuch** [comment]
@itayd do you know why RK didn't run here?

**Comment by itayd** [comment]
i think that the ci didn't run as expected is telling - github probably suffered some transient failure at least with this pr.
rk pings, and it looks like it's receiving hooks. also no errors reported on my side.

can you close and recreate this pr?

**Comment by tbarrella** [comment]
Sure, https://github.com/envoyproxy/envoy/pull/14397

**Pull request closed without merging**
