### PR TITLE
coverage: revert workarounds that are no longer neccessary

### LINKED ISSUE #10108: coverage_tests fail in specific order
when running coverage_tests as of 1223a2b4aef6eb90f3e34eebf496aead4930c4ab in shard 27 of 50:

backtrace from gdb:
```
#0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x000000000f7c8f1e in Envoy::SignalAction::sigHandler(int, siginfo_t*, void*) ()
#2  <signal handler called>
#3  0x000000000e00f98f in grpc_core::LockfreeEvent::SetReady() ()
#4  0x000000000e0067e2 in fd_become_readable ()
#5  0x000000000e008e7e in pollable_process_events(grpc_pollset*, pollable*, bool) ()
#6  0x000000000e006bf1 in pollset_work ()
#7  0x000000000dffd034 in pollset_work(grpc_pollset*, grpc_pollset_worker**, long) ()
#8  0x000000000e010105 in grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, long) ()
#9  0x000000000e04af5a in cq_next(grpc_completion_queue*, gpr_timespec, void*) ()
#10 0x000000000e04a0ce in grpc_completion_queue_next ()
#11 0x000000000dde24ba in grpc_impl::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) ()
#12 0x000000000dd9dbd1 in grpc_impl::CompletionQueue::Next(void**, bool*) ()
#13 0x000000000dd95bd5 in Envoy::Grpc::GoogleAsyncClientThreadLocal::completionThread() ()
#14 0x000000000dd9b91c in Envoy::Grpc::GoogleAsyncClientThreadLocal::GoogleAsyncClientThreadLocal(Envoy::Api::Api&)::$_0::operator()() const ()
#15 0x000000000dd9b8b1 in _ZNSt3__18__invokeIRZN5Envoy4Grpc28GoogleAsyncClientThreadLocalC1ERNS1_3Api3ApiEE3$_0JEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOS9_DpOSA_ ()
#16 0x000000000dd9b831 in void std::__1::__invoke_void_return_wrapper<void>::__call<Envoy::Grpc::GoogleAsyncClientThreadLocal::GoogleAsyncClientThreadLocal(Envoy::Api::Api&)::$_0&>(Envoy::Grpc::GoogleAsyncClientThreadLocal::GoogleAsyncClientThreadLocal(Envoy::Api::Api&)::$_0&) ()
#17 0x000000000dd9b7f1 in std::__1::__function::__alloc_func<Envoy::Grpc::GoogleAsyncClientThreadLocal::GoogleAsyncClientThreadLocal(Envoy::Api::Api&)::$_0(std::__1::allocator<std::__1::allocator>, void ())>::operator()() ()
#18 0x000000000dd9a213 in std::__1::__function::__func<Envoy::Grpc::GoogleAsyncClientThreadLocal::GoogleAsyncClientThreadLocal(Envoy::Api::Api&)::$_0(std::__1::allocator<std::__1::allocator>, void ())>::operator()()
    ()
#19 0x00000000054bb1be in std::__1::__function::__value_func<void ()>::operator()() const ()
#20 0x00000000054bb0a9 in std::__1::function<void ()>::operator()() const ()
#21 0x000000000f78bbf6 in Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::operator()(void*) const ()
#22 0x000000000f78bbb5 in Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::__invoke(void*) ()
#23 0x00007efe89c6e6db in start_thread (arg=0x7efe83068700) at pthread_create.c:463
#24 0x00007efe8999788f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Reproduce steps:
```
HEAPCHECK= TEST_SRCDIR=bazel-out/k8-fastbuild/bin/test/coverage/coverage_tests.runfiles TEST_TMPDIR=/tmp GTEST_TOTAL_SHARDS=50 GTEST_SHARD_INDEX=26 ENVOY_IP_TEST_VERSIONS=v4only bazel-bin/test/coverage/coverage_tests
```

### PR DESCRIPTION
**Pull request by ggreenway**
Description: Turn off 'Flaky' for coverage tests.
Risk Level: Low

Signed-off-by: Greg Greenway <ggreenway@apple.com>

### CODE REVIEW

**Comment by lizan** [comment]
@ggreenway coverage test is not always to fail, it depends how gtest shard tests into 50 runs, i.e. adding/removing test change the sharding. At some point it will break. It is always better to shuffle test order to detect flakiness / unintended dependencies between tests.

**Comment by ggreenway** [comment]
Hmm. What I was trying to fight is inconsistent coverage results between runs. Are we better off closing this so the tests don’t get stuck in a broken state?

**Comment by mattklein123** [comment]
Can we potentially keep the shuffle but remove the flaky tag so it runs once? We have fixed a bunch of things and also have stack traces now so it should be easier to understand what happens if it fails during the flake run?

**Comment by ggreenway** [comment]
Sounds reasonable to me. @lizan wdyt?

**Comment by lizan** [comment]
SGTM

**Comment by mattklein123** [comment]
The irony: coverage failed. Sigh. Maybe we shouldn't shuffle and just deal with whatever issues show up?

**Comment by ggreenway** [comment]
I'm confused. For that coverage run, there were no failures, but it says coverage was only 96.5%. The SHUFFLE shouldn't affect the overall coverage, just whether it passes/fails, right?

**Comment by mattklein123** [comment]
> I'm confused. For that coverage run, there were no failures, but it says coverage was only 96.5%. The SHUFFLE shouldn't affect the overall coverage, just whether it passes/fails, right?

I'm actually not sure this is the case. I could see the order mattering in terms of the calculations, especially wrt to death tests and other strange things.

**Comment by ggreenway** [comment]
I'm fine with removing the SHUFFLE and seeing how it goes from there.

**Pull request merged**
