### PR TITLE
deps: Bump `com_github_nghttp2_nghttp2` -> 1.55.1

### LINKED ISSUE #28345: Newer release available `com_github_nghttp2_nghttp2`: v1.55.0 (current: v1.53.0)
Package Name: com_github_nghttp2_nghttp2@1.53.0
Current Version: v1.53.0@2023-05-10
Available Version: v1.55.0@2023-07-12
Upstream releases: https://github.com/nghttp2/nghttp2/releases

### LINKED ISSUE #28417: Newer release available `com_github_nghttp2_nghttp2`: v1.55.1 (current: v1.53.0)
Package Name: com_github_nghttp2_nghttp2@1.53.0
Current Version: v1.53.0@2023-05-10
Available Version: v1.55.1@2023-07-14
Upstream releases: https://github.com/nghttp2/nghttp2/releases

### PR DESCRIPTION
**Pull request by phlax**
Fix #28345
Fix #28417 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by alyssawilk — DISMISSED** [review]

**Comment by phlax** [comment]
this one needs to

/wait for #28367

**Comment by phlax** [comment]
This now updates to the fixed upstream, and removes our custom patch

cc @yanavlasov @htuch

**Review by htuch — APPROVED** [review]

**Pull request merged**
