### PR TITLE
http: Header-map updating remove_if to an O(n) operation for lazy-headermap

### PR DESCRIPTION
**Pull request by adisuissa**
Signed-off-by: Adi Suissa-Peleg <adip@google.com>

Commit Message: http: Header-map updating remove_if to an O(n) operation for lazy-headermap
Additional Description:
The `remove_if` operation had an O(n^2) time complexity when using the lazy-headermap.
This PR changes `remove_if` by traversing the headermap either using underlying list (if no lazy map is used), or by traversing the lazy-map (and removing elements from the list).
This has now linear time complexity.

Risk Level: Medium - changes to header-map
Testing: Updated the unit tests to use different threshold levels.
Docs Changes: None.
Release Notes: None.

### CODE REVIEW

**Comment by adisuissa** [comment]
/cc @mattklein123 @htuch 
@htuch noted that the current implementation had an O(n^2) time complexity.
This update should make it linear. PTAL

**Review by mattklein123 — CHANGES_REQUESTED** [review]
LGTM, thanks. Can you check tidy?

/wait

**Comment by adisuissa** [comment]
> LGTM, thanks. Can you check tidy?
> 
> /wait

Renaming `remove_if` to `removeIf` should fix clang-tidy.

**Comment by adisuissa** [comment]
/retest
Windows test failure (//test/extensions/transport_sockets/tls:handshaker_test) seems unrelated.

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
