### PR TITLE
bump grpc-httpjson-transcoding

### PR DESCRIPTION
**Pull request by asedeno**
Updating to a version which is more amenable to future protobuf updates.

Risk Level: low
Testing: 
```
$ bazel test                                                \
//test/extensions/filters/http/grpc_json_transcoder/...     \
//test/extensions/filters/http/grpc_field_extraction/...    \
//test/extensions/filters/http/proto_message_extraction/...
```

### CODE REVIEW

**Comment by asedeno** [comment]
Carving off more of #36167; this is a new upstream version of grpc-httpjson-transcoding with the series of eight patches I was testing merged in.

**Review by phlax — APPROVED** [review]
lgtm, thanks @asedeno

**Pull request merged**
