### PR TITLE
Update Datadog tracer version to v1.0.1

### PR DESCRIPTION
**Pull request by cgilmour**
Signed-off-by: Caleb Gilmour <caleb.gilmour@datadoghq.com>

Description: Updates dd-opentracing-cpp from v0.4.2 to v1.0.0
Fairly minor changes/fixes/features under the hood.
Tiny update to the datadog tracer code in envoy, because it made too much noise with debug enabled.

Risk Level: Low.
Testing: No changes. Passed unit tests and manual E2E tests.
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by cgilmour** [comment]
I'll check into the CI errors.

**Comment by dio** [comment]
@cgilmour yeap. To be clear, macOS failure seems like to be real.

**Comment by cgilmour** [comment]
@dio correct, they're both real and directly related.
Been working on fixes and making sure I can verify locally before pushing an update.

**Comment by cgilmour** [comment]
Note: this is not ready for merging yet.

I've made code changes to clear the original CI issues, and verified locally using `./ci/run_envoy_docker.sh`. To double-check, I've made this PR point to a specific commit of dd-opentracing-cpp and make sure it got a green result.
I'll ship a patch release of dd-opentracing-cpp and change this PR to use the tagged version.

**Comment by cgilmour** [comment]
I've made the updates described in the previous comment.
Everything's passing and working fine in E2E retest.

**Pull request merged**
