### PR TITLE
golang filter: no pseudo header called :protocol

### PR DESCRIPTION
**Pull request by spacewander**
There is not such a header called :protocol, see the RFC: https://datatracker.ietf.org/doc/html/rfc9113#section-8.3.1

Therefore this method only returns an empty string.

To get the protocol, please use GetProperty("request.protocol") instead.

Commit Message: no pseudo header called :protocol
Additional Description:
Risk Level: Low, remove a method that doesn't work
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by doujiang24** [comment]
it's following the Envoy request header map, it's introduced in this PR: https://github.com/envoyproxy/envoy/pull/4188/files#diff-ed541c4cb7ed24441c259e4f72039395c4c244fecabbd1b2a43d1871859873e6R38
and this draft rfc: https://datatracker.ietf.org/doc/html/draft-mcmanus-httpbis-h2-websockets

I think it's better to align up Envoy core, thoughts?

**Comment by yanavlasov** [comment]
The `:protocol` should never be observed in the header map by filters. The HTTP/2 extended CONNECT is changed to HTTP/2 upgrade request here: https://github.com/envoyproxy/envoy/blob/83c66e18e7a32c77cf084dc8bb797c84a3e84bec/source/common/http/http2/codec_impl.cc#L597

**Review by doujiang24 — APPROVED** [review]
Oh, thanks @yanavlasov  , no doubts, lgtm～

**Comment by adisuissa** [comment]
> Oh, thanks @yanavlasov , no doubts, lgtm～

Hi @doujiang24 I assume you approve this change.
If so, and if @wbpcode has no other comments, I think this is good to go.

**Comment by adisuissa** [comment]
@spacewander please update the release notes (changelogs).

**Comment by spacewander** [comment]
@adisuissa 
Thanks for your notice. Change log added.

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
