### PR TITLE
udp_proxy_filter: Fix crash when accepting dynamic cds for UDP. Fixes #34195.

### LINKED ISSUE #34195: Envoy crash using CDS with dynamic configuration from filesystem
I have a crash when using CDS with UDP, it is completely reproducible on Kubernetes CI

## How to reproduce

1. Crete the cds.yaml and lds.yaml files
2. Start envoy with the following configuration

```
node:
  cluster: cloud-provider-kind
  id: cloud-provider-kind-id

dynamic_resources:
  cds_config:
    resource_api_version: V3
    path: /home/envoy/cds.yaml
  lds_config:
    resource_api_version: V3
    path: /home/envoy/lds.yaml

admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
```
3. Modify the cds.yaml and lds.yaml two times with the configurations below (changing only the ports)

## Details

https://github.com/kubernetes/kubernetes/pull/124729

Crashdump on CDS
```
[2024-05-16 07:11:34.464][1][info][upstream] [source/common/upstream/cds_api_helper.cc:32] cds: add 1 cluster(s), remove 0 cluster(s)
[2024-05-16 07:11:34.465][1][info][upstream] [source/common/upstream/cds_api_helper.cc:71] cds: added/updated 1 cluster(s), skipped 0 unmodified cluster(s)
[2024-05-16 07:11:43.483][101][critical][backtrace] [./source/server/backtrace.h:127] Caught Segmentation fault, suspect faulting address 0x18
[2024-05-16 07:11:43.483][101][critical][backtrace] [./source/server/backtrace.h:111] Backtrace (use tools/stack_decode.py to get line numbers):
[2024-05-16 07:11:43.483][101][critical][backtrace] [./source/server/backtrace.h:112] Envoy version: 816188b86a0a52095b116b107f576324082c7c02/1.30.1/Clean/RELEASE/BoringSSL
[2024-05-16 07:11:43.483][101][critical][backtrace] [./source/server/backtrace.h:114] Address mapping: 5585541ca000-558556b72000 /usr/local/bin/envoy
[2024-05-16 07:11:43.483][101][critical][backtrace] [./source/server/backtrace.h:121] #0: [0x7f9a5f4e1520]
[2024-05-16 07:11:43.483][101][critical][backtrace] [./source/server/backtrace.h:121] #1: [0x5585548d4caa]
[2024-05-16 07:11:43.483][101][critical][backtrace] [./source/server/backtrace.h:121] #2: [0x5585548d2bbf]
[2024-05-16 07:11:43.483][101][critical][backtrace] [./source/server/backtrace.h:121] #3: [0x5585561ed36d]
[2024-05-16 07:11:43.484][101][critical][backtrace] [./source/server/backtrace.h:121] #4: [0x5585561f1600]
[2024-05-16 07:11:43.484][101][critical][backtrace] [./source/server/backtrace.h:121] #5: [0x55855651bcc1]
[2024-05-16 07:11:43.484][101][critical][backtrace] [./source/server/backtrace.h:121] #6: [0x55855651998f]
[2024-05-16 07:11:43.484][101][critical][backtrace] [./source/server/backtrace.h:121] #7: [0x55855651ab2f]
[2024-05-16 07:11:43.484][101][critical][backtrace] [./source/server/backtrace.h:121] #8: [0x5585561f0fa6]
[2024-05-16 07:11:43.484][101][critical][backtrace] [./source/server/backtrace.h:121] #9: [0x5585561f0d4e]
[2024-05-16 07:11:43.484][101][critical][backtrace] [./source/server/backtrace.h:121] #10: [0x5585562ea081]
[2024-05-16 07:11:43.484][101][critical][backtrace] [./source/server/backtrace.h:121] #11: [0x5585562eb62d]
[2024-05-16 07:11:43.484][101][critical][backtrace] [./source/server/backtrace.h:121] #12: [0x55855653bd40]
[2024-05-16 07:11:43.484][101][critical][backtrace] [./source/server/backtrace.h:121] #13: [0x55855653a681]
[2024-05-16 07:11:43.484][101][critical][backtrace] [./source/server/backtrace.h:121] #14: [0x558555b79f9f]
[2024-05-16 07:11:43.484][101][critical][backtrace] [./source/server/backtrace.h:121] #15: [0x5585565b7d03]
[2024-05-16 07:11:43.484][101][critical][backtrace] [./source/server/backtrace.h:121] #16: [0x7f9a5f533ac3]

```

Config applied
LDS
```
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener_IPv4_80_UDP
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 80
      protocol: UDP
  udp_listener_config:
    downstream_socket_config:
      max_rx_datagram_size: 9000
  listener_filters:
  - name: envoy.filters.udp_listener.udp_proxy
    typed_config:
      '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
      access_log:
      - name: envoy.file_access_log
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
      stat_prefix: udp_proxy
      matcher:
        on_no_match:
          action:
            name: route
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
              cluster: cluster_IPv4_80_UDP
      upstream_socket_config:
        max_rx_datagram_size: 9000
```
CDS
```
resources:
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: cluster_IPv4_80_UDP
  connect_timeout: 5s
  type: STATIC
  lb_policy: RANDOM
  health_checks:
  - timeout: 5s
    interval: 3s
    unhealthy_threshold: 2
    healthy_threshold: 1
    no_traffic_interval: 5s
    always_log_health_check_failures: true
    always_log_health_check_success: true
    event_log_path: /dev/stdout
    http_health_check:
      path: /healthz
  load_assignment:
    cluster_name: cluster_IPv4_80_UDP
    endpoints:
      - lb_endpoints:
        - endpoint:
            health_check_config:
              port_value: 10256
            address:
              socket_address:
                address: 192.168.8.4
                port_value: 32557
                protocol: UDP
      - lb_endpoints:
        - endpoint:
            health_check_config:
              port_value: 10256
            address:
              socket_address:
                address: 192.168.8.2
                port_value: 32557
                protocol: UDP

```

_Originally posted by @aojea in https://github.com/envoyproxy/envoy/issues/14866#issuecomment-2114250647_
            
I've tried with all the latest stable images and it still crashes.

Found https://github.com/envoyproxy/envoy/pull/33824 that seems related, but after trying with a dev image that should contain the fix the crash still happens

```
 9dce75e79df0   envoyproxy/envoy:dev-190f9e0cfe16e779f622c16dce8e833600e5fb45   "/docker-entrypoint.…"   About a minute ago   Exited (1) About a minute ago                               kindccm-FIVC6DYE7XD6AIEWUYSGG4EXHENYBGTPO4KYLJLD
```

### PR DESCRIPTION
**Pull request by railwaycat**
Commit Message: udp_proxy_filter: Fix crash when accepting dynamic cds for UDP. Fixes #34195.
Additional Description:
Please see #34195 and #26206 for details. This change fixes a usage of cluster info resource after the udp cluster be destroyed. 

I've got an approval from envoy-security list for the fix.
Risk Level: Low
Testing: mentioned in both tickets
Docs Changes: N/A
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by yanavlasov** [comment]
@railwaycat can you add tests that validate this condition, please?

/wait-any

**Comment by railwaycat** [comment]
Hi @yanavlasov Sorry for the delay! I updated the UDP Proxy filter test case `ClusterDynamicInfoMapUpdate` to cover the case that an UDP cluster with active sessions be removed.

**Comment by yanavlasov** [comment]
Is the issue that the [cluster_](https://github.com/envoyproxy/envoy/blob/517ceb18c115de3ff5ef4d8bab2ba292cdbee1ab/source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h#L864) reference becomes dangling when CDS updates the cluster?

If so then this change fixes the problem only partially. There are still uses of the cluster_ reference not related to the cluster info. Lie this: https://github.com/envoyproxy/envoy/blob/517ceb18c115de3ff5ef4d8bab2ba292cdbee1ab/source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc#L310

These will crash as well.

Looking at the code, to support dynamic clusters UDP proxy must avoid "capturing" thread local cluster at the filter creation reference and instead lookup the thread local cluster then it is needed and deal with the possibility that it may be not present. Similar to what the router filter does. I understand it is a much bigger change, however this smaller change does not address the underlying cause and may still produce the crash.

/wait-any

**Comment by railwaycat** [comment]
This PR fixes the misusing of `cluster_.info()` more than fix the dangling `cluster_` reference. 

By the description in this comment https://github.com/envoyproxy/envoy/blob/a0504e87c5a246cb097b37049b1e4dc7706c2a90/envoy/upstream/cluster_manager.h#L326 store the pointer to cluster information for using later is safe. 

Before this PR, UDP cluster uses a stored `cluster_` reference to access cluster information by `info()` method which is not safe and will result a crash when `cluster_` no longer valid. This PR replaces it with a stored cluster information pointer and avoid using any `cluster_` reference, as the comment suggests.

I agree the dangling `cluster_` in UDP cluster is a bigger issue but we may fix it in another PR.

**Review by yanavlasov — APPROVED** [review]

**Comment by aojea** [comment]
@yanavlasov not familiar with envoy releases, can you tell me which releases will get this fix?

**Pull request merged**
