### PR TITLE
mobile: Add debug logging in the Swift tests

### PR DESCRIPTION
**Pull request by fredyw**
This PR adds debug logging in the Swift tests to make debugging test failures easier.

Risk Level: low
Testing: CI
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Review by abeyad — DISMISSED** [review]

**Review by abeyad — APPROVED** [review]

**Review by abeyad — APPROVED** [review]

**Comment by fredyw** [comment]
@abeyad this is now ready for review.

**Review by abeyad — APPROVED** [review]

**Pull request merged**
