### PR TITLE
docs: replace old Lyft URLs (NFC)

### PR DESCRIPTION
**Pull request by keith**
Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Comment by moderation** [comment]
Can you add

- https://github.com/envoyproxy/envoy/blob/main/api/envoy/service/discovery/v2/ads.proto#L23
- https://github.com/envoyproxy/envoy/blob/main/api/envoy/service/discovery/v3/ads.proto#L24

`s/lyft/envoyproxy/`

**Review by adisuissa — APPROVED** [review]
/lgtm api

**Review by phlax — APPROVED** [review]
lgtm, thanks @keith

**Pull request merged**
