### PR TITLE
examples: updating docker-compose version

### PR DESCRIPTION
**Pull request by cpaika**
Description:
Upgrading the version of docker-compose for the front proxy example to be up to date with the latest (3.7).  Not too many changes other than some feature adds, and removals of things that aren't being used in this docker-compose file.  [Docs for upgrading docker-compose from 2.x to 3.x](https://docs.docker.com/compose/compose-file/compose-versioning/#version-3) 
Risk Level: Low
Testing:
Manual testing, starting and hitting the example services after upgrading the version of docker-compose
Docs Changes:
N/A
Release Notes:
N/A

### CODE REVIEW

**Comment by cpaika** [comment]
Not sure why the tests failed - seems like my changes are unrelated to the test files.  Not sure if the main pipeline is broken, or the tests that failed are flaky?

**Comment by mattklein123** [comment]
cc @moderation can you take a quick look?

**Comment by moderation** [comment]
This looks fine to me and my local tests work. Looking at Circle CI output I think this is test flakes.

/retest

**Comment by moderation** [comment]
@cpaika it would be nice to propagate this change to the rest of the examples docker-compose files. Extra points if while at it we rename all *.yml file to *.yaml for consistency throughout the repo AND update the 4 RST documentation files that refer to them.

```
rg -e 'version: \'2\''
examples/jaeger-tracing/docker-compose.yml
1:version: '2'

examples/zipkin-tracing/docker-compose.yml
1:version: '2'

examples/lua/docker-compose.yaml
1:version: '2'

examples/grpc-bridge/docker-compose.yml
1:version: '2'

examples/redis/docker-compose.yaml
1:version: '2'

examples/fault-injection/docker-compose.yml
1:version: '2'

examples/jaeger-native-tracing/docker-compose.yml
1:version: '2'

examples/cors/backend/docker-compose.yml
1:version: '2'

examples/cors/frontend/docker-compose.yml
1:version: '2'
```

```
rg 'docker-compose.yml'
docs/root/start/sandboxes/jaeger_native_tracing.rst
25:by docker compose (see :repo:`/examples/jaeger-native-tracing/docker-compose.yml`). Notice that

docs/root/start/sandboxes/zipkin_tracing.rst
14:by docker compose (see :repo:`/examples/zipkin-tracing/docker-compose.yml`). Notice that

docs/root/start/sandboxes/jaeger_tracing.rst
14:by docker compose (see :repo:`/examples/jaeger-tracing/docker-compose.yml`). Notice that

docs/root/start/sandboxes/front_proxy.rst
19:(see :repo:`/examples/front-proxy/docker-compose.yml`). Moreover, notice
```

**Comment by cpaika** [comment]
@moderation Thanks for giving me a next step to get into the codebase more!  I was in the middlef of trying to see where I could get involved thats a perfect next baby step haha.  I’ll get on it 👍

**Pull request merged**
