### PR TITLE
owners: promote Dmitry to maintainer

### PR DESCRIPTION
**Pull request by mattklein123**

### CODE REVIEW

**Comment by mattklein123** [comment]
Thank you @rojkov for all your work so far and your future performance work! :tada: 

cc @envoyproxy/maintainers

**Review by ggreenway — APPROVED** [review]
Welcome!

**Comment by rojkov** [comment]
Thank you! I feel honored :)

**Review by alyssawilk — APPROVED** [review]
+1, welcome :-)

**Review by snowp — APPROVED** [review]
Welcome! :)

**Comment by jmarantz** [comment]
+1000 welcome, Dmitry!

**Pull request merged**
