### PR TITLE
test: Separate test/integration/integration.h into 3 different classes

### PR DESCRIPTION
**Pull request by foreseeable**
Commit Message: Separate test/integration/integration.h into 3 different classes
Additional Description: 
According to my bazel compilation profile analyze results, there are 31 tests which have action "Compiling test/integration/integration.cc" as performance bottleneck. (https://gist.github.com/foreseeable/dbf0eb8fe38a01792e8a9a9d6eb3878d)
`test/integration:integration_lib` is a huge test library, separate it into different class headers and then refactor its usage will help to improve envoy building performance
Risk Level: low
Testing: existing tests
Docs Changes: N/A
Release Notes: no

### CODE REVIEW

**Comment by ahedberg** [comment]
Is the eventual plan to separate these into separate build targets? Or do your profiles show that just separating the headers/source files is enough?

**Comment by foreseeable** [comment]
> Is the eventual plan to separate these into separate build targets? Or do your profiles show that just separating the headers/source files is enough?

It's not enough by just separating these. First we need to separate them into separate targets, then we need to replace `#include "test/integration/integration.h"` with used class headers (which will be done in follow up PR)

**Comment by ahedberg** [comment]
> > Is the eventual plan to separate these into separate build targets? Or do your profiles show that just separating the headers/source files is enough?
> 
> It's not enough by just separating these. First we need to separate them into separate targets, then we need to replace `#include "test/integration/integration.h"` with used class headers (which will be done in follow up PR)

Sorry, I think my question was unclear. Do we need to split up the build target as well as the headers? Or is splitting up the headers and replacing the `#include` lines with smaller headers (while still depending on the monolithic build target) sufficient?

**Comment by foreseeable** [comment]
@ahedberg Yes the build target should be divided as well as the headers. Just forget to do that

**Comment by foreseeable** [comment]
> CI failure looks like a flaky timeout.

@ahedberg I think so, I have re-runned the CI tasks

**Comment by ahedberg** [comment]
@junr03 @foreseeable 's last day is tomorrow - would appreciate any comments on this PR so we can address them before he returns to school. Thanks!

**Pull request merged**
