### PR TITLE
chore(deps): bump `rules_rust` -> 0.35.0

### PR DESCRIPTION
**Pull request by RiverPhillips**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] chore(deps): bump `rules_rust` -> 0.35.0
[Optional Fixes commit #PR or SHA]  #31538
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
for ref - prior art https://github.com/envoyproxy/envoy/pull/31344 - happy to close that one - this one requires some patch-fu and i think might not work out of the box

**Comment by phlax** [comment]
(just saw you have done the patch-fu - nice!)

**Comment by phlax** [comment]
retest is a bit flakey atm :confused:

**Comment by phlax** [comment]
```console
Dependency validation failed, please check metadata in bazel/repository_locations.bzl
Observed dataplane core deps {'com_github_nlohmann_json', 'com_github_google_quiche', 'utf8_range', 'com_github_zlib_ng_zlib_ng', 'boringssl_fips', 'com_github_jbeder_yaml_cpp', 'rules_foreign_cc', 'com_github_nghttp2_nghttp2', 'com_googlesource_code_re2', 'com_github_gabime_spdlog', 'com_google_protobuf_protoc_osx_aarch_64', 'com_googlesource_googleurl', 'com_google_protobuf', 'com_github_libevent_libevent', 'com_google_protobuf_protoc_osx_x86_64', 'rules_license', 'com_github_fmtlib_fmt', 'com_google_protobuf_protoc_linux_aarch_64', 'net_zlib', 'com_google_absl', 'prometheus_metrics_model', 'com_github_grpc_grpc', 'opencensus_proto', 'boringssl', 'com_google_protobuf_protoc_linux_x86_64', 'com_envoyproxy_protoc_gen_validate', 'com_google_googleapis', 'com_google_protobuf_protoc_win64', 'com_github_cyan4973_xxhash', 'com_github_cncf_xds', 'com_github_google_perfetto', 'io_bazel_rules_go', 'com_github_openhistogram_libcircllhist', 'rules_cc'} is not covered by "use_category" implied core deps {'com_github_bufbuild_buf', 'com_github_nlohmann_json', 'com_github_google_quiche', 'utf8_range', 'com_github_zlib_ng_zlib_ng', 'boringssl_fips', 'com_github_jbeder_yaml_cpp', 'rules_foreign_cc', 'com_github_nghttp2_nghttp2', 'com_googlesource_code_re2', 'com_github_openzipkin_zipkinapi', 'com_github_gabime_spdlog', 'com_google_protobuf_protoc_osx_aarch_64', 'com_googlesource_googleurl', 'com_google_protobuf', 'com_github_libevent_libevent', 'com_google_protobuf_protoc_osx_x86_64', 'rules_license', 'com_github_fmtlib_fmt', 'com_google_protobuf_protoc_linux_aarch_64', 'net_zlib', 'com_google_absl', 'com_github_c_ares_c_ares', 'prometheus_metrics_model', 'bazel_skylib', 'com_github_grpc_grpc', 'com_github_google_tcmalloc', 'opencensus_proto', 'com_github_axboe_liburing', 'boringssl', 'com_google_protobuf_protoc_linux_x86_64', 'com_envoyproxy_protoc_gen_validate', 'opentelemetry_proto', 'com_google_googleapis', 'com_google_protobuf_protoc_win64', 'rules_proto', 'com_github_cyan4973_xxhash', 'com_github_cncf_xds', 'com_github_google_perfetto', 'com_github_gperftools_gperftools', 'io_bazel_rules_go', 'com_github_openhistogram_libcircllhist'}: {'rules_cc'} are missing

```

i think my pr may have resolved this

**Comment by phlax** [comment]
seems not, i might have a fix locally - ill try and dig it out

**Comment by phlax** [comment]
@RiverPhillips i couldnt find the fix locally - so maybe im confusing with another dep - the error is usually not too hard to resolve other than the tool thats erroring being a bit resource-hungry and annoying to run

**Comment by RiverPhillips** [comment]
I ran it locally and get the same error relating to `rules_cc`, bit strange considering I didn't change it. Will do some more digging

**Comment by phlax** [comment]
i think the dep tree just shifed a little so another dep needs to be marked as used somewhere

**Comment by adisuissa** [comment]
Waiting on a fix
/wait

**Comment by phlax** [comment]
hmm, so @RiverPhillips this seems a bit more complicated after all - its `rules_cc` that is missing as an explicit dep i think

probs we need to add it - seems a bit odd that we havent already as we do use it - i think its pulled in implicitly by `rules_foreign_cc` (fwiw that one is already marked as `dataplane_core`)

**Pull request merged**
