### PR TITLE
stream options: add tracing options

### PR DESCRIPTION
**Pull request by cainelli**
Commit Message: stream options: add tracing options
Additional Description:  Move tracing options from `RequestOptions` to `StreamOptions` to allow tracing context in bidi grpc streams. It simplifies https://github.com/envoyproxy/envoy/pull/33665 as it does not require changes in class/method signatures ([context](https://github.com/envoyproxy/envoy/pull/33665/files#r1574260031)). We'd still have `parent_span` as parameter in `AsyncRequestImpl` and other `send` methods which might not be clear what is being used, the one from options or the one from parameters.

Risk Level: Low
Testing: Tested on [local setup](https://github.com/cainelli/envoy-grpc/tree/main) tracing propagation using extauthz, ratelimit (GRLS), lua and jwtauthn ([setChildSpanName](https://github.com/nareddyt/envoy/blob/ecf90111beecb3f6f8f2ec72d7046211989e236a/source/extensions/filters/http/common/jwks_fetcher.cc#L60)).

image

image

Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by wbpcode** [comment]
Thanks for your contribution. This is LGTM to me. Will let @mattklein123 take a look.

**Comment by wbpcode** [comment]
I am not clear to the history of the `StreamOptions` and `RequestOptions` and didn't know why the span related options is placed in the `RequestOptions`.
I initially think it's because a stream may have longer lifetime than the single request. So, we didn't put the request level span related options into the `StreamOptions`. But seems now we have set the `ParentContext` to the `StreamOptions`, so my guess should be off the charts.

cc @mattklein123  Could you take a quick look when you have free time? Thanks.

**Review by mattklein123 — APPROVED** [review]

**Comment by mattklein123** [comment]
This LGTM but is there any test that can cover this or is this needed for a different change? If so would it be better to just merge this into the other change as it is really small?

/wait-any

**Comment by cainelli** [comment]
There are existing tests covering `RequestOptions` [[1]](https://github.com/envoyproxy/envoy/blob/720b4c1552f2c5bf5af12204e1302edb98775fbe/test/extensions/filters/http/common/jwks_fetcher_test.cc#L168-L169) [[2]](https://github.com/envoyproxy/envoy/blob/ff264b6485a5e4c2e128525b506a54e167a12ae4/test/common/http/async_client_impl_test.cc#L436), not yet through `StreamOptions` as it will be used in https://github.com/envoyproxy/envoy/pull/33665. I'm happy either way.

**Comment by mattklein123** [comment]
> There are existing tests covering RequestOptions [[1]](https://github.com/envoyproxy/envoy/blob/720b4c1552f2c5bf5af12204e1302edb98775fbe/test/extensions/filters/http/common/jwks_fetcher_test.cc#L168-L169) [[2]](https://github.com/envoyproxy/envoy/blob/ff264b6485a5e4c2e128525b506a54e167a12ae4/test/common/http/async_client_impl_test.cc#L436), not yet through StreamOptions as it will be used in https://github.com/envoyproxy/envoy/pull/33665. I'm happy either way.

I would just close and merge into the other PR. Thanks.

**Pull request closed without merging**
