### PR TITLE
Fix for fuzz tests failing due to invalid corpus paths

### PR DESCRIPTION
**Pull request by dmitri-d**
Risk Level: low

Signed-off-by: Dmitri Dolguikh <ddolguik@redhat.com>

### CODE REVIEW

**Review by mattklein123 — APPROVED** [review]
Thanks for fixing but how did this start breaking?

**Comment by dmitri-d** [comment]
>  how did this start breaking?

Not really sure, tbh. Perhaps something in the ci image changed?

**Comment by mattklein123** [comment]
OK let's merge this to unblock, but we must be using something that is not pinned which seems a bit scary. cc @envoyproxy/dependency-shepherds

**Comment by dmitri-d** [comment]
I don't think the failures were due to a change in our repositories, I couldn't find anything that would cause such a failure. Perhaps bazel pulled in an updated dependency?

**Pull request merged**
