### PR TITLE
caching: Improved the tests and coverage of the CacheFilter tree

### LINKED ISSUE #9872: CacheFilter: Cache::Utils methods need more tests
The tests for Cache::Utils are too thin, and should be enhanced, though some of this may be supplanted by #9833.

### PR DESCRIPTION
**Pull request by yosrym93**
Commit Message: Improved the tests and coverage of the CacheFilter tree.
Signed-off-by: Yosry Ahmed <yosryahmed@google.com>

Additional Description:
- Improved the quality of the tests and added test cases covering a wider variety of scenarios.
- Raise the coverage of the cache tree from 85% to about 94%.
- Various tests cleaning up.
- Fixed the cache_filter_integration_test failure on windows and removed the `fails_on_windows` tag. 

Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Fixes #9872 as a side effect.

### CODE REVIEW

**Comment by yosrym93** [comment]
@jmarantz is there anything that I need to do before this is ready for you to take a look?

**Comment by mattklein123** [comment]
Needs a main merge. Thank you.

/wait

**Comment by yosrym93** [comment]
@mattklein123 done!

**Comment by yosrym93** [comment]
@mattklein123 After merging master the `cache_filter_integration_test` fails on Windows with:
`[critical][assert] [test/integration/integration.cc:500] assert failure: 0. Details: Timed out waiting for listeners.`

Which is weird because that test was not changed in the merge commit and it did not have any conflicts. Are there any recent changes to the integration tests framework that may cause this?

**Comment by mattklein123** [comment]
It's a flake. We are working on fixing this. You can ignore for now!

**Comment by yosrym93** [comment]
Alright then, the checks are done. This is the only failure.

**Comment by yosrym93** [comment]
> It's a flake. We are working on fixing this. You can ignore for now!

Alright then, the checks are done. This is the only failure.

**Pull request merged**
