### PR TITLE
proto_format: Shift `min_bytes` check

### LINKED ISSUE #25208: Some proto format checks have been orphaned when shifting `code_format` -> `proto_format`
Some time ago the protobuf checks in `check_format.py` were removed/disabled on the basis that it was replicating the functionality of the `proto_format` check (which creates an "idealized" version of the proto files and compares them rather than linting)

The file discovery in `check_format.py` was altered to ignore the `.proto` files altogether, but there are still some code paths in that file where its expecting to run more-lint style checks on discovered proto files - specifically for the `min_bytes` deprecated field

im wondering if we can pick this up with `buf`.

Its  also possible we can have `proto_format` just do a direct replacement `min_bytes` -> `min_length` if the fields are directly equivalent and that would then appear as errors with diffs in the `proto_format` check

if not i can think of some other more/less hacky ways we could pick this up - ill do some grepping now to see if there are other cases that have been missed

### PR DESCRIPTION
**Pull request by phlax**
Fix #25208 

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @htuch im not entirely clear if this the best place to do this but it works 8/

**Comment by phlax** [comment]
follow up from #25198

**Comment by phlax** [comment]
```console
Format check failed, try apply following patch to fix:
diff --git a/api/contrib/envoy/extensions/filters/http/golang/v3alpha/golang.proto b/api/contrib/envoy/extensions/filters/http/golang/v3alpha/golang.proto
index b6cfe82..01aa4ce 100644
--- a/api/contrib/envoy/extensions/filters/http/golang/v3alpha/golang.proto
+++ b/api/contrib/envoy/extensions/filters/http/golang/v3alpha/golang.proto
@@ -51,7 +51,7 @@ message Config {
   // and can be used to associate :ref:`route and virtualHost plugin configuration
   // <envoy_v3_api_field_extensions.filters.http.golang.v3alpha.ConfigsPerRoute.plugins_config>`.
   //
-  string plugin_name = 3 [(validate.rules).string = {min_bytes: 1}];
+  string plugin_name = 3 [(validate.rules).string = {min_len: 1}];
 
   // Configuration for the Go plugin.
   //
```
https://dev.azure.com/cncf/envoy/_build/results?buildId=126471&view=logs&j=f0537f27-2e39-530f-1fd2-a5ecd0924017&t=388a504b-3b8d-52aa-33e0-1e12bca05378&l=154

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
