### PR TITLE
googleurl: further fixes

### PR DESCRIPTION
**Pull request by alyssawilk**
Fixing one remaining missing arm include

### CODE REVIEW

**Review by keith — COMMENTED** [review]
https://quiche-review.googlesource.com/c/googleurl/+/11280 we should merge this one

**Review by keith — APPROVED** [review]

**Comment by RyanTheOptimist** [comment]
> https://quiche-review.googlesource.com/c/googleurl/+/11280 we should merge this one

I've merged this change to chromium and have uploaded it to the google storage bucket. Instead of patching the googleurl in Envoy, should we consider just updating the googleurl dep to this new version?

**Comment by alyssawilk** [comment]
@RyanTheOptimist if your change includes both the arm files (not just the first one) feel free to send a PR out and close this one.

**Comment by RyanTheOptimist** [comment]
> @RyanTheOptimist if your change includes both the arm files (not just the first one) feel free to send a PR out and close this one.

Yup, it should. I sent out https://github.com/envoyproxy/envoy/pull/23824

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
