### PR TITLE
fix pip3 not found error

### PR DESCRIPTION
**Pull request by yiyan-wish**
fix pip3 not found error

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/master/api/review_checklist.md):]

### CODE REVIEW

**Comment by yiyan-wish** [comment]
branch release/v1.12 and release/v1.14 also has this problem

**Comment by lizan** [comment]
Can you fix CI? cc @phlax

**Comment by phlax** [comment]
afaict this has already been fixed on main https://github.com/envoyproxy/envoy/blob/main/examples/front-proxy/Dockerfile-service#L3

not sure if we want to backport the fix to older alpine-dev images  - it woulld make the docs work i think

cc @Shikugawa

**Comment by phlax** [comment]
actually not sure if it would make any difference looking at the docs

https://www.envoyproxy.io/docs/envoy/v1.14.6/start/sandboxes/front_proxy#running-the-sandbox

they suggest checking out current `HEAD` to run the examples

**Pull request closed without merging**
