### PR TITLE
replace miscellaneous usages of query param data structure with new version

### PR DESCRIPTION
**Pull request by turettn**
Commit Message:

replace miscellaneous usages of query param data structure with new version

Additional Description:

In #24054, a new data structure for storing query parameters was introduced. In that PR, I committed to going through and ripping out all usage of the old data structure (cc @ggreenway).

This PR swaps out the old structure for the new one in a couple small, self-contained usages. No behavior changed.

Once this PR is merged, there will be one large PR to remove the old data structure from the admin server (where it is used heavily), then one more to remove the data structure itself.

Risk Level: Low
Testing: Existing unit tests appear to provide sufficient coverage.
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by zuercher — APPROVED** [review]
lgtm

Since it wasn't obvious to me, I'll note this here:
The old implementation of QueryParams iterates over the query params string and calls std::map::emplace on each name/value pair in turn. I expected that meant that the resulting map would contain the last value of a multi-value params (e.g. a=2 when given `"?a=1&a=2"`). That's not true. The emplace call doesn't modify the map if the key already exists. So this looked like a change in behavior from "use last value" to "use first value" (e.g. in xds_resource.cc) but it's not.

**Comment by zuercher** [comment]
/assign-from @envoyproxy/envoy-maintainers 

for a second set of eyes

**Comment by turettn** [comment]
@lizan @zuercher Just giving this a small bump - I looked through the comments and don't see anything requiring changes.  Please let me know if there's anything I can do to get this merged.

**Review by lizan — APPROVED** [review]

**Pull request merged**
