### PR TITLE
[TESTING/WIP] deps/rust: Rename wasm32-wasi -> wasm32-wasip1

### PR DESCRIPTION
**Pull request by phlax**

### CODE REVIEW

**Comment by phlax** [comment]
requires resolution to https://github.com/bazelbuild/rules_rust/issues/2782

/wait

**Review by mattklein123 — DISMISSED** [review]

**Comment by phlax** [comment]
seems like this needs a fix in proxy-wasm-rust-sdk

ive tested https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/277 but that still gives the same warnings so probs more is needed there

**Comment by PiotrSikora** [comment]
[proxy-wasm/proxy-wasm-rust-sdk#277](https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/277) only changes its own CI and text in examples, so it won't have any effect on Envoy.

But what are you trying to fix? I don't see any Wasm or Rust tests failing in this PR.

If you're trying to get rid of warnings about `wasm32-wasi` being deprecated, than that needs to be fixed in `rules_rust`, since it maps `@rules_rust//rust/platform:wasi` to `wasm32-wasi` and not `wasm32-wasip1`.

**Comment by phlax** [comment]
> But what are you trying to fix? ...

yeah - trying to resolve the warnings

i initially came to the conclusion that it needed to be resolved in rules_rust - but after updating that with what i thought should fix still seeing the same

**Comment by phlax** [comment]
> Do you mean ...

yeah - mostly as it closed https://github.com/bazelbuild/rules_rust/issues/2782 which i thought was the issue

**Comment by PiotrSikora** [comment]
Try https://github.com/bazelbuild/rules_rust/pull/2967?

**Comment by phlax** [comment]
requires a cpp-host update at least i think

**Comment by PiotrSikora** [comment]
> requires a cpp-host update at least i think

I don't think so? There is nothing host-related in there, at least if you ignore Wasmtime.

In any case, you forgot to update checksum, which is why the tests are failing.

**Comment by phlax** [comment]
apologies - i didnt push my latest local change - this was the error about cpp-host

```console
ERROR: Error computing the main repository mapping: at /src/workspace/envoy/bazel/repositories_extra.bzl:4:6: at /home/worker/.cache/bazel/_bazel_worker/f704bab1b165ed1368cb88f9f49e7532/external/proxy_wasm_cpp_host/bazel/cargo/wasmtime/remote/crates.bzl:15:6: Every .bzl file must have a corresponding package, but '@rules_rust//crate_universe/private:crates_vendor.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
Loading:
```

i didnt look too far what caused it

**Pull request closed without merging**
