### PR TITLE
quiche: disable quic_http_integration_test under coverage

### PR DESCRIPTION
**Pull request by danzh2010**
Signed-off-by: Dan Zhang <danzh@google.com>

Commit Message: this test flakies in coverage CI: https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/75714/logs/287

### CODE REVIEW

**Comment by antoniovicente** [comment]
Related issues: https://github.com/envoyproxy/envoy/issues/16493 and https://github.com/envoyproxy/envoy/issues/16335

**Comment by antoniovicente** [comment]
Please look at and update coverage expectations.

```
2021-05-17T22:40:40.7123374Z Per-extension coverage failed:
2021-05-17T22:40:40.7124459Z Code coverage for source/common is lower than limit of 96.3 (96.2)
2021-05-17T22:40:40.7125142Z Code coverage for source/common/quic is lower than limit of 87.4 (84.9)
2021-05-17T22:40:40.7125625Z Code coverage for source/common/network is lower than limit of 95.0 (94.9)
2021-05-17T22:40:40.7126123Z Code coverage for source/extensions/resource_monitors is lower than limit of 96.6 (95.8)
2021-05-17T22:40:40.7126643Z Code coverage for source/extensions/resource_monitors/common is lower than limit of 96.6 (70.0)
2021-05-17T22:40:40.7127653Z Code coverage for source/server is lower than limit of 94.4 (94.2)
```

**Comment by alyssawilk** [comment]
(coverage is still failing)
Is this the same test failing on tsan? can we disable specific test cases instead of the entire thing?

**Comment by danzh2010** [comment]
> (coverage is still failing)
> Is this the same test failing on tsan? can we disable specific test cases instead of the entire thing?

Disabling the whole test suite lower the coverage a lot. I changed to disable the giant request/response tests instead. These likely were the ones that caused the coverage CI to fail.

**Comment by antoniovicente** [comment]
> (coverage is still failing)
> Is this the same test failing on tsan? can we disable specific test cases instead of the entire thing?

We're having trouble getting info on which test cases were failing in the coverage build.  Would be good to gather more information about failing test cases if possible.

**Review by antoniovicente — APPROVED** [review]
Looks good.

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
