### PR TITLE
add stream filter callbacks to cache factory

### PR DESCRIPTION
**Pull request by EItanya**
Signed-off-by: Eitan Yarmush <eitan.yarmush@solo.io>

Commit Message: add stream filter callbacks to cache factory
Additional Description: Stream Filter Callbacks contain scope and span information needed for cache implementation.
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by jmarantz — DISMISSED** [review]
lgtm -- i'll wait till @capoferro approves before merging.

**Comment by capoferro** [comment]
This merits some discussion, actually. 

I am working on a solution to flesh out where we provide encoder/decoder callbacks via CachePolicyInterface, but, thanks to a bunch of boring reasons, I haven't pushed the code that puts them in to use yet.

https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/cache/cache_policy.h#L28-L33

The way CachePolicyInterface is intended to be implemented can be seen in this (very WIP) PR here: https://github.com/capoferro/envoy/pull/122/files

I am actively working on getting the above PR and several others ready for review, though it might take some time. (My next PR is currently blocked on https://github.com/envoyproxy/envoy/pull/16854 getting merged)

Do you think that CachePolicyCallbacks might work for you, or can we work to find a solution that incorporates your requirements better?

**Comment by EItanya** [comment]
That could potentially work for me. However, I mostly need access to the following values for this particular extension:
https://github.com/envoyproxy/envoy/blob/b2a9429952492e99df090b8f306614656e8e6fc7/envoy/http/filter.h#L274-L288.

So if we could add those to the callbacks that should work fine. WDYT? @capoferro

**Comment by EItanya** [comment]
> This merits some discussion, actually.
> 
> I am working on a solution to flesh out where we provide encoder/decoder callbacks via CachePolicyInterface, but, thanks to a bunch of boring reasons, I haven't pushed the code that puts them in to use yet.
> 
> https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/cache/cache_policy.h#L28-L33
> 
> The way CachePolicyInterface is intended to be implemented can be seen in this (very WIP) PR here: https://github.com/capoferro/envoy/pull/122/files
> 
> I am actively working on getting the above PR and several others ready for review, though it might take some time. (My next PR is currently blocked on #16854 getting merged)
> 
> Do you think that CachePolicyCallbacks might work for you, or can we work to find a solution that incorporates your requirements better?

How is the `CachePolicyInterface` going to interact with the `LookupContext` and `InsertContext`?  Mostly I need the `StreamFilterCallbacks` available  in those objects to access the `Scope` `Span`, and logging capabilities. Those functions essentially act as factories for those types, so it felt like the most sensible place. How are you imagining accessing those objects from the `Contexts`?

**Comment by capoferro** [comment]
The intent of CacheFilterPolicyInterface implementations is to serve as an intermediary between HttpCache and CacheFilter to evaluate both cacheability of requests and responses as well as usability of entries in a cache. It's provided as an interface to provide an extension point for custom cache logic that needs to override RFC-standard logic or otherwise extend the way cache entries are evaluated.

In that case, what I have may not work for you, unless the work you are doing can be contained within the cacheability or usability checks in the CachePolicy.

Which bits of logic in the context objects will need to access the callbacks? It could be those bits are moving to the CachePolicy, and, if so, all is well, but if not, this PR might be what we need.

**Comment by EItanya** [comment]
The `LookupContext` needs access to the span and scope for network calls during `::getHeaders`, and `InsertContext` needs access to the snap and scope for the same reason during the `::commit`.

I don't think the changes in the PR you linked will solve this specific problem.

**Comment by capoferro** [comment]
ok, that makes sense to me. I'll puzzle over ways to unify where we give access to callbacks I get my PR ready, if it's possible.

**Review by capoferro — DISMISSED** [review]
Thanks for talking this through!

**Comment by jmarantz** [comment]
main merge needed :)

**Comment by EItanya** [comment]
> main merge needed :)

I'll handle that right now!

**Comment by EItanya** [comment]
@jmarantz and @capoferro this should be good to go now!

**Review by jmarantz — APPROVED** [review]
I think @capoferro has essentially approved so I'll go ahead and merge; he can correct whatever's needed in his next PR.

**Pull request merged**
