### PR TITLE
mobile: Remove Mobile/Core CI

### PR DESCRIPTION
**Pull request by fredyw**
This PR removes `Mobile/Core` since everything has been covered by `Mobile/CC`. This should help to free up some runners.

Risk Level: low
Testing: CI
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Review by alyssawilk — APPROVED** [review]
I'd be mildly inclined to go the other way and call this cc tests and delete core, but no strong feelings.

remove cc bazelrc in a follow-up?

**Comment by fredyw** [comment]
> I'd be mildly inclined to go the other way and call this cc tests and delete core, but no strong feelings.
> 
> remove cc bazelrc in a follow-up?

I decided to remove `Mobile/Core` and keep `Mobile/CC`. The `bazelrc` removal will be done in a follow up PR.

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
