### PR TITLE
dep: update com_github_google_perfetto: v22.1 (current: v21.0)

### LINKED ISSUE #19216: Newer release available `com_github_google_perfetto`: v22.1 (current: v21.0)
Package Name: com_github_google_perfetto
Current Version: v21.0@2021-11-02 23:48:06
Available Version: v22.1@2021-12-07 20:37:08
Upstream releases: https://github.com/google/perfetto/releases

### PR DESCRIPTION
**Pull request by kfaseela**
Signed-off-by: Faseela K <faseela.k@est.tech>

Fixes #19216

### CODE REVIEW

**Comment by moderation** [comment]
@htuch @rojkov we should add an owner for Perfetto to https://github.com/envoyproxy/envoy/blob/main/CODEOWNERS

This change look OK? If so I'll approve the deps

**Review by rojkov — APPROVED** [review]
Thank you!
Yes, the change looks good to me.

**Comment by rojkov** [comment]
Heh, I accidentally enabled auto-merge in my github mobile app and the PR got happily merged despite the deps label.

**Comment by phlax** [comment]
> the PR got happily merged despite the deps label.

i thought we had fixed it to not do that

**Comment by phlax** [comment]
in this case i  thought/hoped i had fixed this specific issue

see here https://github.com/envoyproxy/envoy/pull/18814#issuecomment-953752906

**Pull request merged**
