### PR TITLE
Add a ext_authz fuzzer for the http client

### PR DESCRIPTION
**Pull request by antoniovleonti**
Commit Message: Add a ext_authz fuzzer for the http client
Additional Description: This PR creates a new fuzzer under the ext_authz directory that uses the ext_authz http client. It moves shared code between the new http fuzzer and the existing grpc fuzzer into a fuzzer utils library.
I also "smuggled in" some tiny improvements to the ext_authz code where I found some redundant copies of shared_ptr variables.
Risk Level: n/a
Testing: test-only PR
Docs Changes: none
Release Notes: none
Platform Specific Features: none
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by antoniovleonti** [comment]
Half the commits in this PR are already merged into main. This is because I started working on this PR before #32859 was finished. I tried to remove them, but I don't know how nor do I know if it matters.

**Comment by htuch** [comment]
@yanjunxiang-google can you take a first pass? @ggreenway can provide senior maintainer coverage and owner.

**Comment by yanjunxiang-google** [comment]
> Half the commits in this PR are already merged into main. This is because I started working on this PR before #32859 was finished. I tried to remove them, but I don't know how nor do I know if it matters.

It's hard to review a PR with changes already merged into main.  Maybe you can create a fresh git workspace and a fresh child branch, and just have your new changes there then send out a PR for it?  That will help us to understand what's changed.

**Comment by antoniovleonti** [comment]
Attempting to clean up commit history with another PR as Yanjun said.

**Pull request closed without merging**
