### PR TITLE
Disallow specifying custom resolver name for STRICT and LOGICAL dns

### LINKED ISSUE #3553: prevent the use of custom resolvers for DNS discovery types
When cluster type is STRICT_DNS or LOGICAL_DNS, report an error when if a custom resolver is set on the endpoint Address to guide users to the correct configuration.

See discussion here: https://github.com/envoyproxy/envoy/pull/3261/files#r188243657

### PR DESCRIPTION
**Pull request by sumukhs**
Description: An exception is thrown to the user if a custom resolver name is specified when using strict or logical dns in the address section of the endpoints.

Risk Level: Low

Testing: //test/...

Docs Changes: This is a behavior change in an error condition. Would documenting this change in the proto file be sufficient?

Release Notes: n/a

Fixes #3553

### CODE REVIEW

**Comment by zuercher** [comment]
Thanks for picking this up. I think you should definitely document this in address.proto and I think it deserves an entry in the release notes (version_history.rst) as well.

**Comment by sumukhs** [comment]
>I think you should definitely document this in address.proto and I think it deserves an entry in the release notes (version_history.rst) as well.

Makes sense. Will post an update.

**Comment by sumukhs** [comment]
@zuercher - Pushed a new update.

**Pull request merged**
