### PR TITLE
Rename value_bytes to raw_value to avoid java proto issues.

### PR DESCRIPTION
**Pull request by yanjunxiang-google**
This is to address issue: https://github.com/envoyproxy/envoy/issues/28243

The value_bytes proto is added by https://github.com/envoyproxy/envoy/pull/27865.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by adisuissa — APPROVED** [review]
/lgtm api
LGTM, thanks for the quick fix!

**Comment by wbpcode** [comment]
No objection, but only a suggesion for reference.

> Maybe just rename it to raw_value . I think we have some similar thing in the ext_authz/ext_proc. Like body and raw_body .

**Comment by wbpcode** [comment]
And please check the CI, thanks.

**Comment by yanjunxiang-google** [comment]
> > @envoyproxy/api-shepherds Please advise whether we should change the name into raw_value.
> 
> I'm slightly inclined towards keeping consistency with [Auth](https://github.com/envoyproxy/envoy/blob/0e5e94f6356cf774ff39b0927231bb7ab501ef86/api/envoy/service/auth/v3/attribute_context.proto#L155), but could be convinced otherwise if there's a better reason.

SG. Changed to raw_value.

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!
/lgtm api

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
