### PR TITLE
Add weisisea as redis extension owner

### PR DESCRIPTION
**Pull request by weisisea**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by wbpcode** [comment]
Please fix the DCO. Thanks.

**Comment by weisisea** [comment]
Ack, working on fixing the DCO

**Review by KBaichoo — APPROVED** [review]
Thanks for fixing DCO and taking this on

**Comment by weisisea** [comment]
Thanks Kevin and Matt!

**Pull request merged**
