### PR TITLE
repo: Release `1.22.5`

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by soulxu** [comment]
Is it worth waiting for this https://github.com/envoyproxy/envoy/issues/22449 ? I'm working on the fix

**Comment by phlax** [comment]
@soulxu any ideas how long it will take ?

**Comment by soulxu** [comment]
> @soulxu any ideas how long it will take ?

It seems not possible in this week, I can work out a fix this week, then want to wait for the issue reporter to do a test, plus the review time, at least next week I think.

**Comment by phlax** [comment]
i think it is worth waiting - but it is delaying the next 1.23 release so there is some urgency

**Review by mattklein123 — DISMISSED** [review]

**Comment by phlax** [comment]
@mattklein123 this should be ready to land (and once it goes green tag)

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
