### PR TITLE
test: fix typos in test code

### PR DESCRIPTION
**Pull request by tuanvcw**
This PR fixes various typos in test code.

### CODE REVIEW

**Comment by mattklein123** [comment]
Legit test failure. Please fix. Thank you!

/wait

**Comment by tuanvcw** [comment]
Hi @alyssawilk, thank you for updating the title.
I'll make sure to follow the title rule next time.

Hi @mattklein123, thanks for your comment.
I've just updated the patch.

Wish you both a great day ahead :)

**Comment by alyssawilk** [comment]
Looks like CI is still unhappy.  I believe you can't change the expected output without changing the actual output.

/wait

**Comment by tuanvcw** [comment]
Thank you very much, @alyssawilk.
I've just made an update. Hopefully CI is happy now :smile:

**Pull request merged**
