### PR TITLE
Update CI build image to 42485dd6111408d43a911a5b1126316ef3151798.

### PR DESCRIPTION
**Pull request by jmillikin-stripe**

### CODE REVIEW

**Comment by mattklein123** [comment]
The image build job failed on your master commit. Can you look at that first?

**Comment by jmillikin-stripe** [comment]
> The image build job failed on your master commit. Can you look at that first?

Looking now. I don't understand why it fails at master but passed the PR checks.

**Comment by mattklein123** [comment]
We don't build the image on every PR currently since it takes a lot of resources. Now that we are on Circle I think we potentially could do this on every PR and have it quick exit. Let me look into this.

**Comment by mattklein123** [comment]
@jmillikin-stripe do you mind bumping this to the SHA that built?

**Comment by jmillikin-stripe** [comment]
Updated to 2beecade45d07faed4ff1770c50a347b0e2f5f74, which has the CI and MacOS build fixes. It's still building, though.

**Comment by mattklein123** [comment]
Ah ok, thanks. You will need to kick this when it builds.

**Comment by mattklein123** [comment]
@jmillikin-stripe I think you might need to push a dummy commit to kick this.

**Comment by jmillikin-stripe** [comment]
Pushing a dummy commit didn't help. I can't pull the image from my laptop, did it actually get pushed?

```
$ docker pull lyft/envoy-build:2beecade45d07faed4ff1770c50a347b0e2f5f74
Error response from daemon: manifest for lyft/envoy-build:2beecade45d07faed4ff1770c50a347b0e2f5f74 not found
```

**Comment by mattklein123** [comment]
Looks like it did not push: https://hub.docker.com/r/lyft/envoy-build/tags/. Let me try to re-run it.

**Comment by mattklein123** [comment]
@jmillikin-stripe I think you exposed a bug in our rebuild process. Right now we only rebuild when files change in certain directories: https://github.com/envoyproxy/envoy/blob/master/ci/build_container/docker_push.sh#L18

I think now you probably need to rebuild when bazel directory changes also? Can you fix that check? That should correctly build a new image when bazel things change also.

**Comment by mattklein123** [comment]
Closing in favor of https://github.com/envoyproxy/envoy/pull/1882

**Pull request closed without merging**
