### PR TITLE
docs: Cleanup version histories

### LINKED ISSUE #20963: Intersphinx mapping is not enforcing local refs strictly
This is a regression of a problem that we previously had workaround code to deal with

Essentially intersphinx dynamically looks up any refs that are not found in the current doctree in the mapped inventories. This can lead to a situation where an author intends to link to something in current doctree, but uses an incorrect ref that happens to exist in another doctree.

Specifically i noticed that this was again a problem as there was a link in the version histories with a ref that no longer exists 

- https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.22.0 (grep `ipv4_compat`)
- https://github.com/envoyproxy/envoy/blob/main/docs/root/version_history/v1.22.0.rst (`` :ref:`ipv4_compat <envoy_api_field_core.SocketAddress.ipv4_compat>`) ``)

This results in the ref linking to v1.9.1 docs

I have rendered current docs and checked for any other issues - afaict the issue is restricted to version_histories - and this is the only one i found so far

i will do some further testing on the intersphinx extension, but we may want/need to add back the workaround that we had previously (at least in some form). This would enforce that linking to other doctrees has to be explicit - any "bare" refs not in the current doctree would cause the docs bulid to fail

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #20963
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
docs rendered here: https://storage.googleapis.com/envoy-pr/20961/docs/index.html

**Comment by phlax** [comment]
this will conflict with #20958

/wait

**Review by alyssawilk — APPROVED** [review]
should we have a step in the release which adds these prefixes?  right now we just copy current to version.number.rst

**Comment by phlax** [comment]
> should we have a step in the release which adds these prefixes? right now we just copy current to version.number.rst

probably yes

rst is not the easiest thing to parse and replace with, i think its doable but not trivial

**Comment by alyssawilk** [comment]
eh, even if we say "do it manually" it's better than you doing it every few months.  cc @RyanTheOptimist who can maybe include it when he moves things from governance to releases

**Comment by phlax** [comment]
> even if we say "do it manually"

ah yep, my brain is just in what-can-be-automated mode

**Comment by phlax** [comment]
> should we have a step in the release which adds these prefixes?

following up on this - it needs to happen at the correct time and for the correct docs...

i have posted a lengthier description of the current steps that are afaict required here https://github.com/envoyproxy/envoy/pull/20851#issuecomment-1109735000

**Pull request merged**
