### PR TITLE
Revert enable_full_scan

### PR DESCRIPTION
**Pull request by kyessenov**
Commit Message: Reverts https://github.com/envoyproxy/envoy/pull/29873 and https://github.com/envoyproxy/envoy/pull/30794

Multiple concerns about the effect of a full scan on LEAST_REQUEST have been raised.
See previous discussions in https://github.com/envoyproxy/envoy/issues/11004 and https://github.com/envoyproxy/envoy/pull/11006.

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Review by lizan — APPROVED** [review]

**Comment by wbpcode** [comment]
So, my previous reverting didn't resolve your problem? Now it should do nothing if you didn't set it explicitly?

**Review by htuch — APPROVED** [review]

**Comment by wbpcode** [comment]
cc @kyessenov may need to kick the ci?

**Comment by jkirschner-hashicorp** [comment]
Hi all - I'm an external observer who was interested in `enable_full_scan` and hoping to use it in Envoy 1.29 when I saw the original PR go through.

Given this reversion PR, what is the thinking about when/if this functionality might be reintroduced?

I looked through the references (#11004, #11006) to try to understand why it is being reverted. It seems like the original PR https://github.com/envoyproxy/envoy/pull/29873 introduced a subtle/minor breaking change that was fixed in https://github.com/envoyproxy/envoy/pull/30794. Per [this comment](https://github.com/envoyproxy/envoy/pull/30768#discussion_r1387373303), are we concerned about it still being a breaking change even after #30794, so we're pulling it for now (since it's too late to introduce breaking changes in the 1.29 release cycle)? Or is the reversion due to some other technical concern that I may have overlooked when reading through the references?

Thanks everyone!

**Comment by tonya11en** [comment]
It won’t be a problem to introduce a full scan option that defaults to off. The problem here was the behavioral change to the default that was rolled into the same patch.

**Comment by jkirschner-hashicorp** [comment]
Ah, got it. I may have misunderstood https://github.com/envoyproxy/envoy/pull/30794, which I thought removed the "default to on (if host num < choice count)" behavior.

**Comment by tonya11en** [comment]
@kyessenov I think you'll need to fix formatting to make it pass CI now.

**Comment by KBaichoo** [comment]
I think this is waiting on you @kyessenov .

/wait

**Comment by barroca** [comment]
Hello, I have the PR #31146 that start the selection from a random index for the full scan preventing the choice of the same index when the number of requests is the same. Perhaps we can merge it instead of revert?

**Comment by kyessenov** [comment]
Merged main. Sorry, I forgot to get this over the finish line.
@barroca I think we should combine the reverted code with the fix in a new PR. It's not a big change. We can review it again.

**Comment by barroca** [comment]
> Merged main. Sorry, I forgot to get this over the finish line. @barroca I think we should combine the reverted code with the fix in a new PR. It's not a big change. We can review it again.

No worries, I believe the PR wasn't approved and need some discussion. Hopefully we can come with an agreement.

**Comment by tonya11en** [comment]
Are we good to merge?

**Comment by kyessenov** [comment]
@wbpcode or @htuch to approve this, so I don't have to keep merging main :)

**Comment by wbpcode** [comment]
/lgtm

let's revert this first and then I think @tonya11en has some work to land. At last,  we will have a tool to evaluate our new lb feature.

**Comment by wbpcode** [comment]
@kyessenov feel free to merge this after resolved conflict and CI.

**Review by wbpcode — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
