### PR TITLE
docs: fix broken links in fault-injection, lua, and mysql examples

### PR DESCRIPTION
**Pull request by peterj**
Noticed other links were broken as well (of course, right after the previous PR was merged).

Description: Links in fault-injection, lua, and mysql were pointing to 404 page
Risk Level: Low
Testing: manually checked the links
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by peterj** [comment]
I looked in other folders under `examples`, but didn't see any RST files. Were you thinking of moving the examples text over to the `/docs` and then link back to the Github repo for the example files or you had something else in mind?

**Comment by mattklein123** [comment]
I guess the landing page was already moved to RST for all the examples: https://www.envoyproxy.io/docs/envoy/latest/start/start#sandboxes

Can we maybe just try to kill all the README files and point back to the public docs?

**Comment by mattklein123** [comment]
Sorry w/ more detail this time: if you look at the link above you will see that some of the sandbox RST files just link to the MD files, and some do it inline. It would be fantastic to just normalize them all to RST. If you could do that I would really appreciate it! If you don't have time we can still merge this. Thank you!

/wait-any

**Comment by peterj** [comment]
Got it! I'll make the change tonight/tomorrow!

**Comment by peterj** [comment]
I moved everything over to rst and updated the `README.md` files to point back to the docs. I built the docs locally and was able to verify no warnings/errors and that the links are correct.

**Comment by mattklein123** [comment]
Sorry the format error looks legit, can you check it?

/wait

**Comment by peterj** [comment]
Looks like I am over-enthusiastic with spaces :D Fixed. More details below.

The issue was in the output of the `docker-compose ps` where the command is truncated using `...   ` (dots + 2 spaces), and `check_format.py` considers that as over-enthusiastic. Probably not worth fixing it, but that rule could be ignored if the offending line is part of the code block.

**Pull request merged**
