### PR TITLE
quiche: updating deps

### PR DESCRIPTION
**Pull request by alyssawilk**
Signed-off-by: Alyssa Wilk <alyssar@chromium.org>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by alyssawilk** [comment]
FYI I needed the test change as the QUIC test got way flakier failing a client side assert that the handshake is finalized before we tried port migration.  Not sure why, but waiting for handshake completion seemed reasonable so I went with that.

**Comment by RenjieTang** [comment]
> FYI I needed the test change as the QUIC test got way flakier failing a client side assert that the handshake is finalized before we tried port migration. Not sure why, but waiting for handshake completion seemed reasonable so I went with that.

Drive-by: I noticed the same thing when I write tests for my port migration PR. And yeah the tests should wait for handshake confirmed to performa port migration anyway.

**Comment by danzh2010** [comment]
> > FYI I needed the test change as the QUIC test got way flakier failing a client side assert that the handshake is finalized before we tried port migration. Not sure why, but waiting for handshake completion seemed reasonable so I went with that.
> 
> Drive-by: I noticed the same thing when I write tests for my port migration PR. And yeah the tests should wait for handshake confirmed to performa port migration anyway.

Probably a recent QUICHE update flips connection migration related flags that disallows peer address change before handshake gets confirmed.

**Review by danzh2010 — APPROVED** [review]
LGTM along aside mac CI failure.

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
