### PR TITLE
[1.18] apple dns: fix crash on invalid dns name (#16028)

### PR DESCRIPTION
**Pull request by dmitri-d**
This is a cherry-pick of https://github.com/envoyproxy/envoy/pull/16028

### CODE REVIEW

**Comment by junr03** [comment]
This diff can still crash. This is the final patch: https://github.com/envoyproxy/envoy/pull/16369

**Comment by dmitri-d** [comment]
Cherry-picked https://github.com/envoyproxy/envoy/pull/16369 instead of the original https://github.com/envoyproxy/envoy/pull/16028

**Comment by junr03** [comment]
@dmitri-d missing the assert deletion: https://github.com/envoyproxy/envoy/blob/b0cdfcb78b178e32b7aebf19250e79a053ef050e/source/common/network/apple_dns_impl.cc#L305

**Review by junr03 — APPROVED** [review]

**Comment by junr03** [comment]
@envoyproxy/security-team can someone with permissions merge?

**Pull request merged**
