### PR TITLE
build: Bump build image to a4bc794b2b

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: build: Bump build image to b51ac7a0f
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
removing pyyaml from the env has broken llvm's clang_tidy_diff script which checks for it being installed and works differently accordingly

as the script is not run from a bazel task, and has no other way of depending on yaml, the easiest is to put it back for now...

**Comment by phlax** [comment]
https://github.com/envoyproxy/envoy-build-tools/pull/146

**Comment by wrowe** [comment]
Holler when this is ready for review.

**Comment by phlax** [comment]
tracking issue added here https://github.com/envoyproxy/envoy-build-tools/issues/147

**Review by wrowe — CHANGES_REQUESTED** [review]
I think you want to do one more bump here to catch up with @yanavlasov 

https://github.com/envoyproxy/envoy-build-tools/commits/main

b6bc66636f16870b8390b400c2d2bc0160c71f73

**Review by wrowe — CHANGES_REQUESTED** [review]
We now understand why this is the correct tag, for now, and this patch is comprehensive.

However, we are still fighting the missing versions.bzl with or without @yanavlasov's last updated toolchain fix. That toolchain fix does (mostly) work on the older May 6 build container.
```
Starting local Bazel server and connecting to it...
ERROR: error loading package '': in C:/source/bazel/dependency_imports.bzl: in C:/build/tmp/external/envoy_build_tools/toolchains/rbe_toolchains_config.bzl: cannot load '@envoy_build_tools//toolchains:configs/windows/versions.bzl': no such file
```

Are we missing other related bazel bumps here to function without versions.bzl? Or did we need to regenerate the build images with the new build-tools refactoring?

**Comment by yanavlasov** [comment]
My change to use RBE generator has removed the [command that created that version.bzl](https://github.com/envoyproxy/envoy-build-tools/blob/edbec0b7a298045bc4f3adbb2c04a3a2d257ccf5/toolchains/regenerate.sh#L28)

If we can disable clang-cl in CI if we can commit PR #17716 I'll leave this decision up to the Windows team
If we can not we need to rollback my two changes in envoy-build-tools so we can start using new build images.

**Comment by wrowe** [comment]
> My change to use RBE generator has removed the [command that created that version.bzl](https://github.com/envoyproxy/envoy-build-tools/blob/edbec0b7a298045bc4f3adbb2c04a3a2d257ccf5/toolchains/regenerate.sh#L28)

We should be able to proceed on the clang-cl issue, updating llvm to 12.0.1 to get around the optimizer crash.

What's more concerning, please fix the resulting chaos from dropping versions.bzl (which should cause the build images to be regenerated for re-testing) here;

https://github.com/envoyproxy/envoy-build-tools/blob/b6bc66636f16870b8390b400c2d2bc0160c71f73/toolchains/rbe_toolchains_config.bzl#L4-L5

**Comment by phlax** [comment]
closing this as it has been superseded by #18220

**Pull request closed without merging**
