### PR TITLE
redis: handle percentage in key in redis key formatter

### PR DESCRIPTION
**Pull request by ramaraochavali**
Commit Message:  handle percentage in key in redis key formatter
Additional Description: When the redis formatter has %KEY% and the key as '%' symbol, the substitution formatter interprets it as a command and fails with the exception "Incorrect configuration: {}. Couldn't find valid command at position {}". This PR handles that case.
Risk Level: Low
Testing: Updated
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Review by wbpcode — DISMISSED** [review]
LGTM. Thanks. cc @mattklein123 for final review or merge.

**Comment by adisuissa** [comment]
Per comment above, assigning Matt.
/assign @mattklein123

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Can you add a release note? Thank you.

/wait

**Comment by ramaraochavali** [comment]
@mattklein123 added release notes. PTAL.

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
