### PR TITLE
remove exception to status legacy code from http codec

### PR DESCRIPTION
**Pull request by chaoqin-li1123**
Signed-off-by: chaoqin-li1123 <chaoqinli@google.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message: exceptionToStatus is used in the migration from C++ exception to error status in http codec. since the exception is no longer used, remove the exception and the exceptionToStatus utility function from the codebase. This is also part of the effort to remove exception from data plane. (#14320)
Additional Description:
Risk Level:low
Testing:none
Docs Changes:none
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by asraa — APPROVED** [review]
Awesome! Thank you for the cleanup.

BTW Got worried in case there were random other EnvoyExceptions floating through some helper methods in the dispatch callstack, but just saw they would have been uncaught and we would have seen them.

Thank you!

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Awesome, thanks. Can we remove `innerDispatch()` also as I don't think it's needed anymore?

/wait

**Comment by chaoqin-li1123** [comment]
> Awesome, thanks. Can we remove `innerDispatch()` also as I don't think it's needed anymore?
> 
> /wait

Sure, that sounds reasonable.

**Comment by asraa** [comment]
Thanks for catching that Matt!

**Review by mattklein123 — APPROVED** [review]
Awesome!

**Pull request merged**
