### PR TITLE
dynamic_modules: switch to crate_universe to remove manual bindgen

### PR DESCRIPTION
**Pull request by mathetake**
Commit Message: dynamic_modules: switch to crate_universe to remove manual bindgen
Additional Description:
This is a follow up on #35914 which ended up requiring a manual
step to generate the binding for the ABI headers.
This switches to use crate_universe and use the bindgen as a dev-dependency.
As a result, we can adopt the build.rs script to generate the C bindings at build
time instead of the manual bindgen step.

This also allows us to freely add a crate dependency when it becomes necessary.

Risk Level: N/A
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by mathetake** [comment]
cc @phlax - i am trying to enable crate_universe here which I think doesn't work for gcc and compiletime_options jobs. let's see

**Comment by mathetake** [comment]
so crate_universe itself seems to be working. The next is to see whether the bindgen actually works or not

**Comment by mathetake** [comment]
i think it's all good now 🤞

**Review by mattklein123 — APPROVED** [review]
Awesome, thanks.

**Comment by asedeno** [comment]
NB: it appears this broke the [s390x build](https://ibmz-ci.osuosl.org/job/Envoy_IBMZ_CI/).

**Pull request merged**
