### PR TITLE
Update c-ares to 1.17.2

### PR DESCRIPTION
**Pull request by yanavlasov**
Risk Level: Low
Testing: All tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

Note: needs backporting to stable branches.

Signed-off-by: Yan Avlasov <yavlasov@google.com>

### CODE REVIEW

**Comment by moderation** [comment]
I think this is the issue with CI - https://github.com/c-ares/c-ares/commit/d5146a6a4d9469ab0ee7252abda92db842ea49c2

**Comment by ggreenway** [comment]
Windows break is a real failure.

/wait

**Review by moderation — CHANGES_REQUESTED** [review]
Wondering if the if then statement at https://github.com/envoyproxy/envoy/blob/main/test/common/network/dns_impl_test.cc#L34-L39 can now be removed due to this commit which is part of the release - https://github.com/c-ares/c-ares/commit/c2f32353e31f97ae7e3fc431de5467f40426368d ?

You'd end up with just
```
#include "ares_nameser.h"
```

**Comment by yanavlasov** [comment]
We will then have to define HAVE_ARPA_NAMESER_H and push the problem into the BUILD file. Maybe it is better. I will leave it  as is for now.

> Wondering if the Windows specific `if` `then` statement at https://github.com/envoyproxy/envoy/blob/main/test/common/network/dns_impl_test.cc#L34-L39 can now be removed due to this commit which is part of the release - [c-ares/c-ares@c2f3235](https://github.com/c-ares/c-ares/commit/c2f32353e31f97ae7e3fc431de5467f40426368d) ?
>

**Comment by wrowe** [comment]
Leaving it as-is seems better from a backporting perspective, the cleanup can live exclusively on main.

> We will then have to define HAVE_ARPA_NAMESER_H and push the problem into the BUILD file. Maybe having it in the BUILD file better. I will leave it as is for now though.
> 
> > Wondering if the Windows specific `if` `then` statement at https://github.com/envoyproxy/envoy/blob/main/test/common/network/dns_impl_test.cc#L34-L39 can now be removed due to this commit which is part of the release - [c-ares/c-ares@c2f3235](https://github.com/c-ares/c-ares/commit/c2f32353e31f97ae7e3fc431de5467f40426368d) ?

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
