### PR TITLE
build: enable code coverage for contrib extension

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Loong <loong.dai@intel.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] #19729
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by mattklein123** [comment]
I don't think we want to spend CI time on this. It would be nice to have a documented way to generate this locally though.

/wait

**Comment by daixiang0** [comment]
https://github.com/envoyproxy/envoy/tree/main/ci has mentioned the target, but not clear to comment with contrib, is it a good place to comment?

**Comment by mattklein123** [comment]
> https://github.com/envoyproxy/envoy/tree/main/ci has mentioned the target, but not clear to comment with contrib, is it a good place to comment?

Sure SGTM!

**Comment by daixiang0** [comment]
@mattklein123 sorry for slow response due to Chinese New Year, I will do it ASAP, thanks :)

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
