### PR TITLE
gcp_authn: Modify the token time constraint check

### PR DESCRIPTION
**Pull request by tyxia**
`VerifyTimeConstraint()` interface is correct for the token consumer. However, as the token producer here, we should instead include the clock skew as the part of the `now` time up front to account for the clock skew on the consumer side where the token will be consumed. Also, in this way, we can avoid changing the third-party library interface `VerifyTimeConstraint()` (which might requires longer turnaround time)

Signed-off-by: Tianyu Xia <tyxia@google.com>

### CODE REVIEW

**Comment by fiadliel** [comment]
One way of looking at this is that people/services expect a provided token to not expire _immediately_, so some positive time addition is better than none. And as these tokens generally have a lifetime of an hour, there's a big buffer to work with; no need to use a token right up to the last second.

What that extra amount should be is a judgment call; `kClockSkewInSecond` is probably as good as any. I think this would solve the issue in the Google environment (where, also, most systems are running NTP, so there's very little actual skew).

**Comment by tyxia** [comment]
> One way of looking at this is that people/services expect a provided token to not expire _immediately_, so some positive time addition is better than none. And as these tokens generally have a lifetime of an hour, there's a big buffer to work with; no need to use a token right up to the last second.
> 
> What that extra amount should be is a judgment call; `kClockSkewInSecond` is probably as good as any. I think this would solve the issue in the Google environment (where, also, most systems are running NTP, so there's very little actual skew).
> 
> (so, TLDR, LGTM)

Thanks for the review! Yes, as I commented in the code the clock skew here actually can be configurable by client in the future if it is needed.

**Comment by tyxia** [comment]
/assign @yanavlasov 

Could you take a look at this PR when you have free time? Thanks!

**Review by yanavlasov — APPROVED** [review]

**Review by yanavlasov — CHANGES_REQUESTED** [review]
Just realized that we do not have unit tests for this code. The return statement on line 96 (token is valid) is not covered by tests.

Can you add unit tests for the TokenCacheImpl class please? I think it would be good to have tests that cover the skew.

/wait

**Comment by yanavlasov** [comment]
> > Just realized that we do not have unit tests for this code. The return statement on line 96 (token is valid) is not covered by tests.
> > Can you add unit tests for the TokenCacheImpl class please? I think it would be good to have tests that cover the skew.
> > /wait
> 
> Good point! I have verified the token cache locally before but because the token expiration is timing related we can not have deterministic behavior in test over time (i.e., token will be expired eventually). I will figure out the way of testing it (e.g., generating the token on each test run by leveraging time source etc). Per offline discussion, currently I left this as TODO so that we can check in this change unblock the customer side. The token related functionalities are verified by the test in jwt library itself.

You have control over system time with the TimeSource class. There are tests that do what you need to do in the test/extensions/filters/http/jwt_authn/jwt_cache_test.cc. You can use one of the token strings from the test and manipulate the tests system time object to set the time to what you need.

/wait-any

**Comment by KBaichoo** [comment]
ping @yanavlasov  PTAL

**Comment by phlax** [comment]
cc @yanavlasov i think this is waiting on your review

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
