### PR TITLE
build: bump rules_foreign_cc to pickup shell toolchain fix

### PR DESCRIPTION
**Pull request by cmluciano**
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>

The current rules_foreign_cc dependency does not respect architectures other
than x86_64. The new patch fixes the compilation on ppc64le and should fix
ARM builds as well.

For an explanation of how to fill out the fields, please see the relevant section 
in [PULL_REQUESTS.md](./PULL_REQUESTS.md)

Risk Level: Medium
Testing: bazel build //source/envoy-static on both clang & libc++
Docs Changes: N/A
Release Notes: N/A
Related #5196

### CODE REVIEW

**Comment by cmluciano** [comment]
cc @clnperez

**Comment by moderation** [comment]
I've suggest moving to the latest commit
```python
    rules_foreign_cc = dict(
        sha256 = "e1b67e1fda647c7713baac11752573bfd4c2d45ef09afb4d4de9eb9bd4e5ac76",
        strip_prefix = "rules_foreign_cc-8648b0446092ef2a34d45b02c8dc4c35c3a8df79",
        # 2019-02-14
        urls = ["https://github.com/bazelbuild/rules_foreign_cc/archive/8648b0446092ef2a34d45b02c8dc4c35c3a8df79.tar.gz"],
```

**Comment by lizan** [comment]
+1 to latest master, which I did in #6007 but reverted.

**Comment by clnperez** [comment]
tested internally with bazel 0.23 and this got me around a build failure i was seeing on ppc64le :+1:

**Pull request merged**
