### PR TITLE
SNI dynamic forward proxy: Support saving resolved upstream address

### PR DESCRIPTION
**Pull request by santbl**
Commit Message: Save resolved upstream address in filter state in SNI dynamic forward proxy
Additional Description:
Risk Level: Low
Testing: Added unit tests and am also consuming this change from filter state in a subsequent filter
Docs Changes: Fixed a typo in doc and added new field to proto
Release Notes: Added a description in change log
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by soulxu — DISMISSED** [review]
LGTM, thanks

**Comment by soulxu** [comment]
@santbl could you merge it with main? Then we can merge it.

**Comment by santbl** [comment]
> @santbl could you merge it with main? Then we can merge it.

@soulxu, merged latest main into the branch. Please take a look. Thanks.

**Review by soulxu — APPROVED** [review]
LGTM, thanks

**Pull request merged**
