### PR TITLE
deps: Bump `Python` -> 3.11.4 

### PR DESCRIPTION
**Pull request by namrata-ibm**
Commit Message: Upgraded Python version which supports s390x, ref [here](https://github.com/indygreg/python-build-standalone/releases/tag/20230726)
Additional Description: This helps in completion of build on s390x and envoy binary is generated successfully.
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by phlax — COMMENTED** [review]
thanks for this @namrata-ibm - wondering if we should update to latest 3.11.x - which i think is 3.11.9

**Comment by namrata-ibm** [comment]
Sure, Please let me know if I can go ahead and update this PR to 3.11.9 version.

**Comment by phlax** [comment]
yeah - i think lets update to latest

**Review by phlax — APPROVED** [review]
lgtm, thanks @namrata-ibm

**Pull request merged**
