### PR TITLE
Patch flaky VeryLargeRequestHeadersRejected test

### PR DESCRIPTION
**Pull request by davinci26**
Commit Message:

As discussed in #16214 there is a case when flow control blocks and
as a result the reponse gets truncated.

To deflake the test we reduce the size of the headers and the limit.

Validated with no flakes in 10k test runs.

Signed-off-by: Sotiris Nanopoulos <sonanopo@microsoft.com>

### CODE REVIEW

**Comment by davinci26** [comment]
Note that this a remedy and not a complete fix. But since the test is flaking quite a bit and creates noise, I think the remedy adds value.

I think it will be good to have a follow up issue for the actual root cause

**Comment by antoniovicente** [comment]
> Commit Message:
> 
> As discussed in #16214 there is a case when flow control blocks and
> as a result the reponse gets truncated.
> 
> To deflake the test we reduce the size of the headers and the limit.
> 
> Validated with no flakes in 10k test runs.

Were you able to measure the original flake rate?

**Comment by davinci26** [comment]
> Were you able to measure the original flake rate?

I don't have the actual number but it was almost every time (70%+)

**Review by antoniovicente — APPROVED** [review]
Changes look good.  Waiting for successful CI run.

Thanks for helping reduce flaky test rates.

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
