### PR TITLE
srds: remove scope from scope_name_by_hash_ in case the scope key changes

### PR DESCRIPTION
**Pull request by pianiststickman**
Commit Message: srds: remove scope from scope_name_by_hash_ in case the scope key changes
Additional Description:
When a SRDS resource is updated such that its scope key changes, the scope_name_by_hash_ map used to detect scope key conflicts keeps the resource around under the old hash. This may cause spurious conflicts if the resource is removed and/or a resource is added with the old key, as demonstrated in the included tests.
Risk Level: low
Testing: CI, also added a DeltaXDS version of the test
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by mattklein123** [comment]
Thanks please add a release note for this fix.

/wait

**Review by mattklein123 — APPROVED** [review]

**Comment by mattklein123** [comment]
@phlax we can't seem to get this to pass CI? What is the recommended action?

**Comment by phlax** [comment]
main merge should fix the checks/tsan issue

the other needs to switch  `kv_store_xds_delegate_integration_test` - `6gig` -> `2core`

**Comment by phlax** [comment]
https://github.com/envoyproxy/envoy/pull/36834

**Comment by phlax** [comment]
landed - `main` merge should fix these issues

**Comment by phlax** [comment]
coverage fail is real, but not 100% if your PR is cause

/coverage

**Comment by pianiststickman** [comment]
I think (hope?) it's unrelated, CI all passed when I opened this PR :)

/retest

**Comment by phlax** [comment]
apologies - we migrated to a new RBE backend and its been a case of juggling the worker allocations - it should be getting more stable now

**Comment by pianiststickman** [comment]
No worries, thanks for all your help on this!

**Comment by pianiststickman** [comment]
@mattklein123 could you re-approve and merge please? Thank you!

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
