### PR TITLE
doc: update doc on original destination lb.

### PR DESCRIPTION
**Pull request by fuqianggao**
Signed-off-by: Fuqiang Gao <fuqianggao@google.com>

Update doc on original destination lb

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes issue #11664

### CODE REVIEW

**Comment by fuqianggao** [comment]
@junr03 ci/ failed. Looks like it is somehow using my personal account and failed due to: "This job has been blocked because resource-class:xlarge is not available on your plan. Please upgrade to continue building."

I am not sure how to fix this.

**Comment by junr03** [comment]
Not sure what is happening. Do you mind merging master, and seeing what happens?

**Comment by fuqianggao** [comment]
Still doesn't work. I will close this one and create a new PR.

**Pull request closed without merging**
