### PR TITLE
tls:remove unimplemented options from one of description

### PR DESCRIPTION
**Pull request by ramaraochavali**
Commit Message: remove unimplemented options from one of description
Additional Description:
Risk Level: N/A
Testing: N/A
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by ravenblackx** [comment]
Review SLA ping @lizan

**Review by adisuissa — COMMENTED** [review]
I think this was added in #17201, and these options may be in-use by gRPC.
If so, a note can be added describing which fields are relevant for Envoy.

@markdroth can you PTAL?

**Comment by markdroth** [comment]
That's correct, gRPC does implement the `tls_certificate_provider_instance` field, and it is mutually exclusive with the other two, so the comment is correct as-is.  If you want to add a note that Envoy does not yet support that field, that's fine.

**Comment by ramaraochavali** [comment]
If there is a plan for Envoy to support that in future, I think we can close this.

**Pull request closed without merging**
