### PR TITLE
xds-failover: adding support for legacy SotW and delta

### PR DESCRIPTION
**Pull request by adisuissa**
Commit Message: xds-failover: adding support for legacy SotW and delta

Additional Description:
This is a breakdown of #34417 to multiple PRs.
In this PR we introduce the `envoy.restart_features.xds_failover_support` runtime flag which defaults to false.
We also modify the legacy GrpcMux SotW and Delta implementations to use the GrpcMuxFailover object instead of the GrpcStream object when the runtime flag is set to true.

Next is updating the Unified Sotw/Delta GrpcMux implementation, and plumbing the API through to use the xDS-Failover.

Risk Level: medium if the runtime flag is set to true.
Testing: Updated the test cases (parameterized).
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by adisuissa** [comment]
@nezdolik can you please take the !Google reviewer role?
/assign @nezdolik

**Review by htuch — APPROVED** [review]
LGTM, thanks for breaking it up in this way, very easy to review. @nezdolik this should hopefully be a quick review when you get a chance.

**Review by nezdolik — APPROVED** [review]
lgtm!

**Pull request merged**
