### PR TITLE
bazel/build: Extend `no-int` workaround to `pkgconfig` for all builds

### PR DESCRIPTION
**Pull request by phlax**
This extends the workaround that was added to macos to other builds

The need for the workaround wasnt macos specific - it relates more to the llvm/clang version used

fix #32426 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@ggreenway not sure if we really want to do this for all builds - there was some previous attempts at making this specific to the `foreign_cc` builds and also an attempt to do so upstream

**Comment by phlax** [comment]
original (reverted) workaround is here https://github.com/envoyproxy/envoy/pull/33227

upstream attempt is here https://github.com/bazelbuild/rules_foreign_cc/issues/1186

cc @zirain

**Comment by phlax** [comment]
hmm this is triggering the liburing issue that i posted offline - cc @soulxu

**Comment by ggreenway** [comment]
I don't think we want to add these settings globally. I think it would be fine for the host_actions, but we do not want to remove these warnings when we're compiling code that lives in the envoy repo. Applying to all dependencies that we fetch would probably be fine, but I'm sure that's much more complicated to do in the build system.

/wait-any

**Comment by phlax** [comment]
yeah - i suspected as much - its also not working - it throws a liburing error

afaict the reason for the liburing error is because its resetting the CXXFLAGS option - so i reckon i can resolve that but wondering what the correct solution is

maybe we can do something similar to what @zirain originally did - ie append but just in the `foreign_cc` builds

**Comment by phlax** [comment]
actually @zirain's patch was even more targeted i think - to just the pkgconfig build - which is what we want

**Comment by ggreenway** [comment]
Unassigning myself; this is beyond my knowledge of bazel

**Review by mattklein123 — APPROVED** [review]

**Comment by jorsol** [comment]
This should be fixed in https://github.com/bazelbuild/rules_foreign_cc/releases/tag/0.11.1

**Pull request merged**
