### PR TITLE
http: reinstating prior connect timeout behavior

### LINKED ISSUE #14394: Classifying connection timeouts as local reset
*Title*: *Classifying connect timeouts as local reset*

*Description*:
For a few months we've been seeing occasional 503 errors in our client side sidecars with the `LR` response flag, and the latency on these calls was always equal to the connect timeout we set. It looks like the router filter classifies connect timeouts this way: https://github.com/envoyproxy/envoy/blob/master/source/common/router/upstream_request.cc#L340

I believe this was changed in April in https://github.com/envoyproxy/envoy/commit/6aee60364ef1bb539e19abc68d1e6cbe93c41512#diff-b61a05a18225decb27f5620aefda1646c259e314547a7d985c369f62a684c12bR305, before that PR I believe that would have been considered a connection failure.

I can understand the rationale for considering it a local reset, but one side effect of that change is that a retry policy that specifies to retry `connect-timeout` and not `reset` will now fail to retry that case. Furthermore, if a request is not idempotent it's not an option to retry on `reset` because that can include cases where the server has already processed the request. I've also seen some confusion on the Envoy slack about this with other folks seeing `LR` start to show up after an Envoy upgrade. I'm not sure anything needs to change here but just wanted to raise that issue.

### PR DESCRIPTION
**Pull request by alyssawilk**
https://github.com/envoyproxy/envoy/pull/10854 inadvertently changed the behavior of connect timeouts.  This reinstates prior behavior.

Risk Level: Low (reinstating prior behavior)
Testing: added regression test
Docs Changes: n/a
Release Notes: inline
Fixes #14394

### CODE REVIEW

**Comment by alyssawilk** [comment]
I think the only question for me is if we should runtime guard - it is reinstating prior behavior but the prior behavior was changed last spring.  I'll leave it up to reviewers - it's easy enough to slap on a guard and copy-paste-runtime-flip the test.

**Comment by snowp** [comment]
Since runtime guarding is so easy I think there's no reason not to? Seems like the safe thing to do since we're changing behavior here

**Review by snowp — DISMISSED** [review]
Thanks!

**Review by snowp — APPROVED** [review]
Thanks!

**Comment by PiotrSikora** [comment]
/backport

Apparently, this breaks retries. cc @howardjohn @lambdai

**Comment by lambdai** [comment]
impact version v1.15 (included)

**Comment by Shikugawa** [comment]
@PiotrSikora @alyssawilk  I think that makes sense to backport this. But I have a pretty concern to treat `envoy.reloadable_features.treat_upstream_connect_timeout_as_connect_failure` as enabled by default because It is an unexpected breaking change.

**Comment by PiotrSikora** [comment]
Almost all bug fixes are breaking changes. This fixes a regression that happened a while ago, but I don't think this could break anybody.

**Pull request merged**
