### PR TITLE
Kick-off release 1.20.1

### PR DESCRIPTION
**Pull request by mathetake**
Should've done this before https://github.com/envoyproxy/envoy/pull/18421 merged.

### CODE REVIEW

**Comment by lambdai** [comment]
@mathetake There is another blocking the istio from picking up envoy 1.20. See https://github.com/envoyproxy/envoy/issues/18616

As far as I can tell, It impacts listener in place update which occurs on both istio gateways and sidecar proxies.

Do you want to hold 1.20.1 until that fix is landed?

**Comment by lambdai** [comment]
> Yeah but this PR is not for releasing 1.21, but about just cleaning up release notes for 1.20 so this must be merged prior to that anyway.

Got it. Thanks! 
By `1.21` you mean `1.20.1`, right?

**Comment by lobkovilya** [comment]
Hello @lizan @mathetake!
Could you please help me to figure out what is the timeline for Envoy 1.20.1?

**Comment by lizan** [comment]
@lobkovilya we don't cut point release unless there's a security fix, so there's no ETA for 1.20.1. meanwhile you can use latest commit of v1.20 branch or v1.20-latest tag from docker.

**Pull request merged**
