### PR TITLE
docs: Fix Deprecated Tap Request Examples

### PR DESCRIPTION
**Pull request by DavidPeet8**
**Commit Message:** 
Update the Tap documentation to avoid use of `match_config` as this is deprecated and use of this field causes errors in CI.

Signed-off-by: David Peet <davidpeet@tutanota.com>

**Additional Description:** n/a
**Risk Level:** low
**Testing:** n/a
**Docs Changes:** Update documentation for Tap filter to use `match` instead of `match_config`
**Release Notes:** n/a
**Platform Specific Features:** n/a
**Fixes:** #20190

### CODE REVIEW

**Review by phlax — COMMENTED** [review]
with these inline configs that tend to go stale - i generally ask/recommend that we move them into separate yaml files so that they are tested 

i would be happy to follow up tho, if we just fix them in this pr

**Comment by phlax** [comment]
...or advise on how to do so

**Comment by DavidPeet8** [comment]
> i generally ask/recommend that we move them into separate yaml files so that they are tested

@phlax Is that testing automatic or is the thought that separate yaml files for these code snippets will make developers more likely to test them as they are more obvious? If these tests are automatic, are there any additional changes I need to make to set them up?

**Comment by phlax** [comment]
testing is automatic - if you grep for `literalinclude` you will find other examples of config that has been separated out to full (bootstrap) configs

**Comment by phlax** [comment]
hi @DavidPeet8 would be good to progress this

copying out the error (config validation)

```console

ERROR: some configuration files (1) failed to validate

ERROR (validation failed): docs/root/configuration/http/http_filters/_include/tap-filter.yaml
Failed to parse static_resources field: Failed to parse listeners field: Failed to parse filter_chains field: Failed to parse filters field: Failed to parse http_filters field: Failed to parse common_config field: Message type "envoy.extensions.common.tap.v3.AdminConfig" has no field named "tap_config".
 Available Fields(except extensions): ['configId']......
```

**Comment by DavidPeet8** [comment]
Hi @phlax I won't have much capacity to look into the validation errors on the documents for a few weeks. Is it alright if I return to this then?

**Comment by phlax** [comment]
>  Is it alright if I return to this then?

sure, of course, lmk if i can help resolving the remaining issues

/wait

**Comment by DavidPeet8** [comment]
Hey @phlax - just an FYI, I'm an intern at Uber right now and my term ends at the end of next week. At that point I'll lose access to my dev environment for Envoy. I'm not sure if I'll have the time to look into why the docs are failing builds before then, so feel free to commandeer this change to get it in.

**Pull request closed without merging**
