### PR TITLE
access log: support request_tx_duration filed in access log configuration.

### PR DESCRIPTION
**Pull request by JaredTan95**
Signed-off-by: JaredTan95 <jian.tan@daocloud.io>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message: support request_tx_duration filed in access log configuration
Additional Description: 
calculate the duration from the start time to the last byte of the request sent to the upstream.
related issue : https://github.com/envoyproxy/envoy/issues/16188
Risk Level: N/A
Testing: unit test
Docs Changes: 
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by yanavlasov** [comment]
Which PR is it going to be, this one or #16207 ?

**Comment by JaredTan95** [comment]
this PR is ready to review.

**Comment by WeavingGao** [comment]
#16207 submit earlier, I think it should be more reasonable. @yanavlasov

**Comment by JaredTan95** [comment]
`lastDownstreamTxByteSent` -  `lastDownstreamRxByteReceived` is the real request tx duration, right?

**Comment by JaredTan95** [comment]
> `lastDownstreamTxByteSent` - `lastDownstreamRxByteReceived` is the real request tx duration, right?

And we've already used this logic in envoy 1.17.1.

**Comment by WeavingGao** [comment]
It has nothing to do with how to implement it. If you think there is a problem with that implementation, I think you should raise it in the original issue instead of quietly submitting a new pull request. 

If others act like this, it is likely to throw the community into chaos.

**Comment by JaredTan95** [comment]
Or, I can submit another PR to fix you logical after your PR merged. :-P

**Comment by JaredTan95** [comment]
co-author： https://github.com/WeavingGao/envoy/pull/1

**Pull request closed without merging**
