### PR TITLE
oauth2 filter: saving id_token and refresh_token in the cookie if they are provided

### PR DESCRIPTION
**Pull request by Alexcei88**
Commit Message:
oauth2 filter: saving id_token and refresh_token in the cookie if they are provided
Additional Description:
https://github.com/envoyproxy/envoy/issues/17808
Risk Level:
Testing:
Docs Changes:

Need to update doc about oath2_filter. The filter will send over cookies BearerToken, IdToken, RefreshToken to the upstream
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter

Release Notes:

oauth2: handling IdToken, RefreshToken fields if they are provided by IDP provider

Platform Specific Features:

### CODE REVIEW

**Comment by mattklein123** [comment]
Needs a DCO fix. cc @snowp to review.

/wait

**Comment by rgs1** [comment]
> @rgs1 I see you offered to review this, wanna take this one? :)

Yup I can look.

/assign rgs1

**Comment by Alexcei88** [comment]
Before last merging all test passed. After the merging there is a one failed test. I took a look in changes and it is not clear for me why it became to failed. I need help. Could anyone look failed test?

**Comment by jamesmulcahy** [comment]
This is great, we needed similar functionality. Thanks @Alexcei88 -- I appreciate the contribution and am looking forward to seeing it merged!

**Comment by Alexcei88** [comment]
Guys, I am sorry, but is there a chance to speed up PR? It need for our project.

**Review by snowp — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
