### PR TITLE
Revert ext_proc: send attributes #30781

### PR DESCRIPTION
**Pull request by yanjunxiang-google**
Description:

After the commit of #30781 , ext_proc filter unit test fuzzer is reporting crashes.
We suspect there is lifetime issues in the cel expression initialization code during filter config parsing.  The crash can be simply reproduced by below command with the two crash input files committed with this PR:

bazel test --config asan-fuzzer //test/extensions/filters/http/ext_proc/unit_test_fuzz:ext_proc_unit_test_fuzz --test_timeout=300

Revert the PR for now.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by yanjunxiang-google** [comment]
#30781 is causing an ext_proc fuzzer crash, which can be simply reproduced by:

bazel test --config asan-fuzzer //test/extensions/filters/http/ext_proc/unit_test_fuzz:ext_proc_unit_test_fuzz

**Comment by jbohanon** [comment]
Is this not a part of a required check? Is there a way to diagnose the test failure without reverting the feature immediately? What is the blast radius of the issue that the fuzz test is revealing?

**Review by tyxia — APPROVED** [review]
LGTM, Thanks

@jbohanon  I left comment here https://github.com/envoyproxy/envoy/pull/30781/files#r1402254604.

It is not probably related to that specific crash here but I think it is wrong usage pattern of CEL. Also, given it is close to holiday it is a good idea that we revert it first, investigate second.

**Comment by yanjunxiang-google** [comment]
> Is this not a part of a required check? Is there a way to diagnose the test failure without reverting the feature immediately? What is the blast radius of the issue that the fuzz test is revealing?

We are a little bit concerned this may cause Envoy crash if someone accidentally configured request_attributes.  So reverting it is safer.

Once we have a good root cause and fix, we can commit them back in.

**Review by botengyao — APPROVED** [review]

**Comment by wbpcode** [comment]
#30781 was merged at 2 days ago. So, it is ok to revert it.

/lgtm api

**Comment by yanavlasov** [comment]
The reason to revert is that invalid config can cause data plane crash. This is to risky to keep this PR. It seems like validation of CEL expression is missing, but I'm not sure. It is better to investigate the crash without having added risk in the codebase.

**Comment by tyxia** [comment]
> The reason to revert is that invalid config can cause data plane crash. This is to risky to keep this PR. It seems like validation of CEL expression is missing, but I'm not sure. It is better to investigate the crash without having added risk in the codebase.

AFAIU, it is not invalid config but the fuzzer issue instead. cced @adisuissa who figured out this.

Back to revert of this CL, my 2 cents is that we should address the [issue](https://github.com/envoyproxy/envoy/pull/30781/files#r1402254604) i mentioned before merging it.

**Comment by adisuissa** [comment]
> > The reason to revert is that invalid config can cause data plane crash. This is to risky to keep this PR. It seems like validation of CEL expression is missing, but I'm not sure. It is better to investigate the crash without having added risk in the codebase.
> 
> AFAIU, it is not invalid config but the fuzzer issue instead? cced @adisuissa who figured out this.
> 

The fuzz-issue was fixed in https://github.com/google/oss-fuzz/pull/11258 by enabling instrumentation in the CEL code.
AFAIK there are no open fuzz issues related to ext_proc and CEL.

**Comment by yanjunxiang-google** [comment]
> > > The reason to revert is that invalid config can cause data plane crash. This is to risky to keep this PR. It seems like validation of CEL expression is missing, but I'm not sure. It is better to investigate the crash without having added risk in the codebase.
> > 
> > 
> > AFAIU, it is not invalid config but the fuzzer issue instead? cced @adisuissa who figured out this.
> 
> The fuzz-issue was fixed in [google/oss-fuzz#11258](https://github.com/google/oss-fuzz/pull/11258) by enabling instrumentation in the CEL code. AFAIK there are no open fuzz issues related to ext_proc and CEL.

So, with the fix of https://github.com/google/oss-fuzz/pull/11258, the ext_proc fuzz crash is still observed with the change of  #30781, right?

**Comment by adisuissa** [comment]
> I am running the ext_proc unit test fuzzer and see whether there is any crash in ext_proc code.

This is not an oss-fuzz crash, and I believe it has to do something with the build flags that are used for `asan-fuzzer` compared with `asan`. Unfortunately I don't have cycles to debug what are the flags that cause this, but "oss-fuzz" should be considered as the source-of-truth. Do you have cycles to debug what is causing this?

**Comment by yanjunxiang-google** [comment]
> > I am running the ext_proc unit test fuzzer and see whether there is any crash in ext_proc code.
> 
> This is not an oss-fuzz crash, and I believe it has to do something with the build flags that are used for `asan-fuzzer` compared with `asan`. Unfortunately I don't have cycles to debug what are the flags that cause this, but "oss-fuzz" should be considered as the source-of-truth. Do you have cycles to debug what is causing this?

I suspect there is some variable life-time issues in this function: FilterConfig::initExpressions,  as @tyxia pointed out earlier. But I could be wrong.  We should debug this after reverting this PR first.

**Review by yanavlasov — APPROVED** [review]

**Comment by adisuissa** [comment]
I think it is an issue with Envoy's building flags when using `asan-fuzzer` and calling CEL's Parser functions.
FWIW, it is not reproducible in oss-fuzz.

**Comment by jbohanon** [comment]
@yanavlasov @yanjunxiang-google @tyxia since this failure is unrelated to net-new code would you mind looking at https://github.com/envoyproxy/envoy/pull/31090

**Comment by yanjunxiang-google** [comment]
ext_proc unit test fuzzer is the main one protect ext_proc code.  If we commit this back in now, it will leave the fuzzer in broken state.  

Can we spend a little bit more time on the root cause, or at least skip the asan-fuzzer test for if request_attributes is in the fuzzer input?

https://github.com/envoyproxy/envoy/blob/d4ed8d4f6e071d0022a9f342110335d8a3c16ba5/test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc#L52

**Pull request merged**
