### PR TITLE
[fuzz] Add metadata and dispatching_actions to codec_impl_fuzz_test

### PR DESCRIPTION
**Pull request by asraa**
This adds an `encodeMetadata` action in the codec_impl_fuzz_test since we don't have any coverage over the metadata code yet. We can specify sending metadata in the form of a map `test.fuzz.Metadata` in requests or responses.

This also adds `dispatching_actions` that can be specified in a request stream action. These will apply a response directional action while request headers, data, or trailers are dispatching.

This won't pass CI until #9996 is merged.

Testing: Added a corpus entry for metadata
Added the bug fixed by #9996 
Risk: Low

### CODE REVIEW

**Comment by asraa** [comment]
/review @mkbehr I was trying to repro the extra frame / memory underflow failures from #9996 you were seeing with this test, but I was struggling to produce a corpus entry that would trigger the crash. Would you be able to look at the `codec_impl_corpus/metadata` test case and comment if you have any suggestions to translate the crash in to a sequence of actions? I may need to modify the test.

**Comment by mkbehr** [comment]
The crash will only trigger if the metadata is sent on a connection that's dispatching data (i.e. if encodeMetadata is called somewhere up the call stack from the stream's ConnectionImpl::dispatch()). It doesn't look like that's possible from the fuzzer here. You could probably hit the crash if you set the response decoder to simulate an early reply when it gets data, but I don't know what the most realistic setup there would look like.

Also keep in mind that right now, the crash is undefined behavior if debug asserts aren't compiled in, so if you're running the fuzzer in fastbuild or opt mode, it might not crash 100% of the time.

**Comment by asraa** [comment]
> The crash will only trigger if the metadata is sent on a connection that's dispatching data (i.e. if encodeMetadata is called somewhere up the call stack from the stream's ConnectionImpl::dispatch()). It doesn't look like that's possible from the fuzzer here. You could probably hit the crash if you set the response decoder to simulate an early reply when it gets data, but I don't know what the most realistic setup there would look like.

Hm... That's what I was afraid of. It's possible we might want to refactor to simulate these scenarios and catch more errors. I'd rather refactor tests to handle more cases than to write new fuzzers for specific scenarious.

> Also keep in mind that right now, the crash is undefined behavior if debug asserts aren't compiled in, so if you're running the fuzzer in fastbuild or opt mode, it might not crash 100% of the time.

Yep, running in fuzz mode with `--config asan-fuzzer` is debug mode, debug asserts will cause a crash.

**Comment by asraa** [comment]
I was able to repro the error as well  by adding `dispatching_actions` to occur while request dispatch headers, data, or trailers. This won't pass CI until https://github.com/envoyproxy/envoy/pull/9996 is merged for the fix!

**Pull request closed without merging**
