### PR TITLE
Fix race condition in mobile cds_integration_test

### PR DESCRIPTION
**Pull request by caschoener**
This test had a race condition, because clusters may initially be in the warming state and not active in which case the comparison would fail.  Waiting for cluster count to increase guarantees success

### CODE REVIEW

**Comment by caschoener** [comment]
This was reverted in https://github.com/envoyproxy/envoy/pull/25432. I can't repro the failures locally, so making another PR to trigger CI

**Review by abeyad — APPROVED** [review]

**Review by jpsim — APPROVED** [review]

**Pull request merged**
