### PR TITLE
Make change to well known names for SRDS stats

### PR DESCRIPTION
**Pull request by DiazAlan**
Commit Message: Add new tag extractor for Srds Stats
Additional Description:
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Review by adisuissa — DISMISSED** [review]
LGTM, thanks!

**Comment by adisuissa** [comment]
Assigning @ggreenway for !Google senior-maintainer review.
/assign @ggreenway

**Review by ggreenway — APPROVED** [review]

**Review by ggreenway — CHANGES_REQUESTED** [review]
Please add release note

Example from a similar change previously: https://github.com/envoyproxy/envoy/blob/770fa7ba2b61e11b267e27b0d4c4861c4b20c11a/changelogs/1.29.0.yaml#L26

/wait

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
