### PR TITLE
bazel: update bazel-toolchains to 5.1.2

### PR DESCRIPTION
**Pull request by keith**
Fixes https://github.com/envoyproxy/envoy/issues/22758

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Review by lizan — COMMENTED** [review]
Let's update the docker image as well? Otherwise we're using different build image in RBE vs non-RBE.

**Comment by keith** [comment]
Since one wasn't built for my change, are you suggesting just updating to the latest built one, or forcing a build somehow?

**Comment by lizan** [comment]
A new one is built on my PR to envoy-build-tools. Follow https://github.com/envoyproxy/envoy/blob/main/.bazelrc#L292 to update those SHA references.

**Comment by phlax** [comment]
theres a few places to update - https://github.com/envoyproxy/envoy/commit/b67521d8baec98da07304ab3062c3660d61bb3f9 has them all i think

**Comment by keith** [comment]
Updated update to https://github.com/envoyproxy/envoy-build-tools/commit/b0ff77ae3f25b0bf595f9b8bba46b489723ab446

**Review by lizan — APPROVED** [review]

**Pull request merged**
