### PR TITLE
doc:fix cache filter sandbox example output inconsistent

### PR DESCRIPTION
**Pull request by xu1zhou**
fix cache filter sandbox example output inconsistent

Signed-off-by: yizhou.xu@intel.com

Commit Message: fix cache filter sandbox example output inconsistent
Additional Description:  Since start command of sandbox image have changed, command output message will changed respectively
Testing: N/A
Risk Level: low
Docs Changes: Yes
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional API Considerations:]

### CODE REVIEW

**Comment by leyao-daily** [comment]
please signed-off your all commits

**Comment by xu1zhou** [comment]
> please signed-off your all commits

done.

**Review by leyao-daily — APPROVED** [review]
LGTM.

**Review by phlax — APPROVED** [review]
lgtm, thanks @xu1zhou

**Pull request merged**
