### PR TITLE
Replace `envoy_restart_features_enable_execution_context` by runtime value `envoy.enable_execution_context`

### PR DESCRIPTION
**Pull request by wu-bin**
Also add `ExecutionScope` to allow servers to do something at the start and end of a scope, where the scope can be an active tracing span or a stream filter.

Commit Message: Replace `envoy_restart_features_enable_execution_context` by runtime value `envoy.enable_execution_context`.
Additional Description:
Risk Level: Low. It is no op in open source code.
Testing: Unit test in test/common/common/execution_context_test.cc.
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by wu-bin** [comment]
@wbpcode : Sorry for the late reply, I just came back from vacation.

> Seems this PR did an additional enhancement to this execution context feature?
> 
Yes, this adds two hooks (aka `ExecutionScope`) to Envoy. One allows an Envoy binary to do arbitrary things when the tracing span becomes active/inactive in the current thread,  the other allows the same when the http filter becomes active/inactive.

> I will strong recommend to make this feature to have a compile flag (like ENVOY_PERF_ANNOTATION). And we can create some macros to help to simplify the code. I believe google has internal fork, this new compile flag shouldn't make things more complex. cc @alyssawilk
> 
> /wait

Thanks for the suggestion, but I'm not a fan of macro-based conditional compilation like this:
```
#ifdef ENVOY_PERF_ANNOTATION
  /* conditional code here */
#endif
```

However I'm open to macros that wrap long statements to simply code, if you have a concrete suggestion.

IIRC, the main motivation for a macro like `ENVOY_PERF_ANNOTATION` is cpu cost? I personally would not worry about that because all
```
auto filter_scope =
        ExecutionContext::makeScopeForFilter(executionContext(), (*entry)->filter_context_);
```
does is to
1) Call `executionContext()`, which does nothing but return `nullptr` if `envoy.enable_execution_context` is false. And
2) Call `ExecutionContext::makeScopeForFilter`, which returns a no-op `ExecutionScope` since the `executionContext` is `nullptr`.

When `envoy.enable_execution_context` is false, the cpu cost of both should be negligible thanks to branch prediction.

Thoughts?

**Comment by wbpcode** [comment]
@wu-bin But we actually has a new problem. But the E-M, we cannot assume the are only one server. That's say the runtime flag should have server-wide scope (except the flags that defined in the runtime_features.cc). This PR break the rule.

> Yes, this adds two hooks (aka ExecutionScope) to Envoy. One allows an Envoy binary to do arbitrary things when the tracing span becomes active/inactive in the current thread, the other allows the same when the http filter becomes active/inactive.

Please make it an independent PR if you actually need it. But I am inclined don't to do that except we can find a clean way.

> However I'm open to macros that wrap long statements to simply code, if you have a concrete suggestion.

If back the start of the story, I will inclined to split the whole feature out from `ScopeTrackerScopeState`. We needn't let every `ScopeTrackedObject` to implement an `executionContext()` method.

And all related features will be implemented in a independent file. A helper macro like RECORD_EXECUTON_CONTEXT(conn) could be used to access the connection attributes directly.

A macro like `ENVOY_ENABLE_EXECUTON_CONTEXT` could be used to control if the RECORD_EXECUTON_CONTEXT will execute actual logic.

/wait-any

**Comment by wu-bin** [comment]
> @wu-bin But we actually has a new problem. But the E-M, we cannot assume the are only one server. That's say the runtime flag should have server-wide scope (except the flags that defined in the runtime_features.cc). This PR break the rule.
> 

It seems we don't have an option that is both performant and acceptable by policy, given the following constraints:
- We don't want a permanent `FALSE_RUNTIME_GUARD` in runtime_features.cc, and
- `runtime().snapshot().getBoolean` is too costly to be called every time we need the executionContext.
- Latching the result of `runtime().snapshot().getBoolean` in a global boolean variable breaks server-wide-scope rule.

@alyssawilk : Any suggestion how to proceed? Is it possible to keep `envoy_restart_features_enable_execution_context` as a permanent `FALSE_RUNTIME_GUARD` in `runtime_features.cc`?

> > Yes, this adds two hooks (aka ExecutionScope) to Envoy. One allows an Envoy binary to do arbitrary things when the tracing span becomes active/inactive in the current thread, the other allows the same when the http filter becomes active/inactive.
> 
> Please make it an independent PR if you actually need it. But I am inclined don't to do that except we can find a clean way.
> 

Sure, I can separate it out, after we agree on a path to move forward.

> > However I'm open to macros that wrap long statements to simply code, if you have a concrete suggestion.
> 
> If back the start of the story, I will inclined to split the whole feature out from `ScopeTrackerScopeState`. We needn't let every `ScopeTrackedObject` to implement an `executionContext()` method.
> 
> And all related features will be implemented in a independent file. A helper macro like RECORD_EXECUTON_CONTEXT(conn) could be used to access the connection attributes directly.
> 

Other ways to implement are certainly possible, but I think `ScopeTrackedObject` and `ScopeTrackerScopeState` are pretty helpful because they saved *a lot* of plumbing needed by ExecutionContext. Everywhere a `ScopeTrackerScopeState` object is used, the ExecutionContext is activated and deactivated. If someone adds a new `ScopeTrackerScopeState`, the ExecutionContext will work automatically as long as the `ScopeTrackedObject` implements the `executionContext()` method.

The fact that I'm piggybacking the plumbing from `ScopeTrackedObject` doesn't mean we can't also use a macro like RECORD_EXECUTON_CONTEXT(conn).  If we have a `Connection` and don't have a `ScopeTrackedObject` at hand, we can certainly still use RECORD_EXECUTON_CONTEXT(conn), but so far I have not encountered such cases.

WDYT?

> A macro like `ENVOY_ENABLE_EXECUTON_CONTEXT` could be used to control if the RECORD_EXECUTON_CONTEXT will execute actual logic.
> 
> /wait-any

**Comment by wu-bin** [comment]
@alyssawilk: Thanks! I can do that in a separate change.

@wbpcode: I've separated the `ENVOY_EXECUTION_SCOPE` change into https://github.com/envoyproxy/envoy/pull/36056. Could you take a look? Thanks.

@ravenblackx: I'll separate this PR into two and close this one.

**Pull request closed without merging**
