### PR TITLE
Fix exclude bug in check_visibility

### PR DESCRIPTION
**Pull request by silverstar194**
Commit Message:
Fix exclude bug in check_visibility

Additional Description:
It's a python concatenation issue. Currently the exclude list looks like ["item", ... "itemN"] it should be without [ ] like"item", ... "itemN"

Risk Level:
Low. Could only break test. No product changes.

Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
@phlax can you take a look at this?

**Review by phlax — APPROVED** [review]
lgtm, thanks @silverstar194 

relatedly im wondering why it doesnt catch the error (or rather why the `1` returncode is ignored)

```python
 1095             if (e.returncode != 0 and e.returncode != 1):
```

**Comment by silverstar194** [comment]
> lgtm, thanks @silverstar194
> 
> relatedly im wondering why it doesnt catch the error (or rather why the `1` returncode is ignored)
> 
> ```python
>  1095             if (e.returncode != 0 and e.returncode != 1):
> ```

It doesn't catch it because the `git diff` makes this to only run when there are changes to the extension directories. I think I'm the first one to do that after this change went through

**Pull request merged**
