### PR TITLE
xds: define precedence between TLS cert fields

### PR DESCRIPTION
**Pull request by markdroth**
Commit Message: api: define precedence between TLS cert fields
Additional Description: Instead of requiring fields to be mutually exclusive as was originally done in #17201, define precendence between them, to be consistent with the API guidance updated in #30851.  Note that this should not affect Envoy's implementation, since Envoy does not yet support CertificateProviders.
Risk Level: Low
Testing: N/A
Docs Changes: Included in PR
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by abeyad — APPROVED** [review]
/lgtm api

**Comment by abeyad** [comment]
@markdroth looks like a legitimate formatting error: s/precendence/precedence

**Review by abeyad — APPROVED** [review]
/lgtm api

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
