### PR TITLE
stats: update circlhist version dependency

### PR DESCRIPTION
**Pull request by jmarantz**
Commit Message: update circlhist
Additional Description:
Risk Level: low
Testing: //test/...
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

**Comment by jmarantz** [comment]
@moderation @ramaraochavali FYI

This seemed to pass //test/... on my dev box. @moderation suggested there was an incompatibility but I didn't see it in our tests so far. Maybe CI will be more thorough.

**Comment by moderation** [comment]
This PR, as it is, only changes the metadata and doesn't include the latest commit. Try
```python
    com_github_circonus_labs_libcircllhist = dict(
        project_name = "libcircllhist",
        project_desc = "An implementation of OpenHistogram log-linear histograms",
        project_url = "https://github.com/openhistogram/libcircllhist",
        version = "95f8f6b089fc4e8dc215ed903221f9f55d4813b3",
        sha256 = "0712445bec6ab71a2ad386f96b3e8fd8777ecaf5264f144e49236ea343fc2e96",
        strip_prefix = "libcircllhist-{version}",
        urls = ["https://github.com/circonus-labs/libcircllhist/archive/{version}.tar.gz"],
        use_category = ["controlplane", "observability_core", "dataplane_core"],
        release_date = "2022-12-15",
        cpe = "N/A",
        license = "Apache-2.0",
        license_url = "https://github.com/openhistogram/libcircllhist/blob/{version}/LICENSE",
    ),

```
In my testing that will cause tests for histograms to fail

**Comment by jmarantz** [comment]
Yeah I thought so. I'm going to pause working on this; I don't want to pick up this dependency hacking stuff. I was looking to see if we could upgrade to a slightly more recent libcirclhist but not one that added the cdflib dependency.

**Comment by pradeepcrao** [comment]
> Yeah I thought so. I'm going to pause working on this; I don't want to pick up this dependency hacking stuff. I was looking to see if we could upgrade to a slightly more recent libcirclhist but not one that added the cdflib dependency.

Do we just need to update the BUILD file ? https://github.com/envoyproxy/envoy/blob/main/bazel/external/libcircllhist.BUILD#L5

I can take a stab at this today.

**Comment by moderation** [comment]
@pradeepcrao I think you are right. I testing a couple of months ago I think I got this compiling with those changes. But then the histogram tests started failing and I bailed

**Comment by jmarantz** [comment]
Pradeep if you are set with this I'll close this PR and defer to you

**Pull request closed without merging**
