### PR TITLE
backport 1.14: http: fixing a bug with IPv6 hosts

### PR DESCRIPTION
**Pull request by Shikugawa**
Signed-off-by: alyssawilk <alyssar@chromium.org>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by Shikugawa** [comment]
@cpakulski ping

**Review by antoniovicente — APPROVED** [review]

**Comment by cpakulski** [comment]
@Shikugawa Just fix the naming to make clang_tidy happy and it should be fine.

**Comment by cpakulski** [comment]
Created #14595 to bring TLS changes and make fake_upstream to use localhost.

**Review by antoniovicente — APPROVED** [review]

**Pull request merged**
