### PR TITLE
deps: Revert PyJWT update to 1.7.1

### PR DESCRIPTION
**Pull request by Shikugawa**
This reverts commit 7abb83cc208a60206505f8058e2cec6cc8d5734b.

Signed-off-by: Shikugawa <rei@tetrate.io>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message: Downgrade PyJWT to 1.7.1. It breaks dependency checking with the required PyJWT version mismatch. For more detail https://dev.azure.com/cncf/envoy/_build/results?buildId=70789&view=logs&jobId=1c04237c-5f52-5959-5f83-5522b3556331&j=1c04237c-5f52-5959-5f83-5522b3556331&t=db3f3889-c922-566b-fa2e-4bc4948bc467
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by phlax — CHANGES_REQUESTED** [review]
rather than reverting all of these could you just revert the package in question please

**Comment by phlax** [comment]
also this doesnt revert the breaking package

**Comment by phlax** [comment]
@Shikugawa i think it makes more sense to just open a new pr to downgrade the one breaking package - pyJWT - also if it breaks under a certain condition - perhaps trigger that if possible to ensure it is working

**Comment by Shikugawa** [comment]
@phlax For now pushed PyJWT downgrade. Could you take a look?

**Comment by phlax** [comment]
looks good - but to ensure this works - could you cherry-pick this commit (temporarily) onto the other PR which broke to ensure this fixes it ?

**Comment by Shikugawa** [comment]
@phlax It works fine. https://github.com/envoyproxy/envoy/pull/15782/checks?check_run_id=2233740511

**Review by phlax — APPROVED** [review]
lgtm, thanks @Shikugawa

**Comment by phlax** [comment]
perhaps change the title 

> deps: Revert PyJWT update from 1.7.1

> deps: Revert PyJWT update **to** 1.7.1

**Review by moderation — APPROVED** [review]

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
