### PR TITLE
[release/v1.17] listener: match rebalancer to listener IP family type

### PR DESCRIPTION
**Pull request by jacob-delgado**
Commit Message:

Cherry-pick of 19e7879ddacebea93ad54217406f2b9263bbc03c into release/v1.17. It is not enabled by default, but instead the user must choose to opt-in.

Additional Description:

When getting a rebalancer by address and a wild card match is being
used, the first match in the list is returned. However, if there are
listeners with addresses "0.0.0.0" and "::" then the first active
listener found will be used, irrespective of the IP family type. Change
the behavior to always return the listener of the same IP family type as
the rebalancer.

Risk Level: Low
Testing: Unit tests added to demonstrate that code path is unchanged unless option is enabled
Docs Changes: Added
Release Notes: Added
Platform Specific Features: N/A
[Optional Runtime guard:] envoy.reloadable_features.listener_wildcard_match_ip_family (not turned on by default)
Fixes: #16804

Co-authored-by: yingchun.cai@volunteers.acasi.info
Signed-off-by: Jacob Delgado <jacob.delgado@volunteers.acasi.info>

### CODE REVIEW

**Comment by jacob-delgado** [comment]
cc @ycai-aspen @nrjpoddar @ggreenway @lambdai 

I'm not sure about Envoy's policy regarding cherry-picks. Hopefully this is able to be merged into 1.17. Let me know what I can do to get this merged in.

**Comment by dmitri-d** [comment]
looks like The build failure is due to pip import failing to retrieve kafka's network filter dependency `MarkupSafe-1.1.1`: it gets an unexpected checksum. I verified it manually and I'm getting the same checksum too.

**Comment by dmitri-d** [comment]
I opened a PR to resolve the build failure: https://github.com/envoyproxy/envoy/pull/17263

**Comment by snowp** [comment]
Please merge in 1.17 to pick up the build fix

**Comment by snowp** [comment]
Not sure what the current build failure is, seems like an issue running a qemu command?  cc @phlax @dmitri-d if either of you know what's going on

**Comment by phlax** [comment]
> ...if either of you know what's going on

its hard to tell from the logs - im guessing a transient failure - i think the qemu part is just the prefix to the running command - so im thinking its not qemu related in any way

hopefully it will pass retest

**Comment by jacob-delgado** [comment]
cc @dmitri-d @snowp Anything else I need to do to get this merged?

**Review by snowp — APPROVED** [review]

**Pull request merged**
