### PR TITLE
http: fix HttpDatagramHandler object lifetime issue.

### PR DESCRIPTION
**Pull request by jeongseokson**
Commit Message:
stream_decoder_ member variable must outlive the HttpDatagramHandler. Previously, stream_decoder_ became a dangling pointer when the stream is reset before OnHttp3Datagram is called.
I made Envoy QUIC stream unregister the HTTP/3 Datagram visitor when the stream is reset to ensure the lifetime assumption.
Additional Description:
Risk Level: Low, this is a bug fix.
Testing: Unit tests and integration tests.
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by jeongseokson** [comment]
/assign @RyanTheOptimist 

Could you review this PR, Ryan? Thank you.

**Comment by alyssawilk** [comment]
This broke the E-M build.  I'm fixing but as a follow-up @jeongseokson can you add a compile time options build that builds H3 but not datagrams so we catch this in CI in future?

**Comment by alyssawilk** [comment]
https://github.com/envoyproxy/envoy/pull/31650 fixes

**Comment by phlax** [comment]
afaiaa no mobile tests are triggered by source changes

**Comment by jeongseokson** [comment]
> This broke the E-M build. I'm fixing but as a follow-up @jeongseokson can you add a compile time options build that builds H3 but not datagrams so we catch this in CI in future?

My bad. @alyssawilk Could you point me to the file I should modify for this? I think i did something similar before upon your request (https://github.com/envoyproxy/envoy/pull/25925/files), but .github/workflows/compile_time_options.yml no longer exists.

**Comment by phlax** [comment]
there is a `.github/workflows/mobile-compile_time_options.yml` but the best place to put anything is in `.bazelrc` changes to the `.github` folder dont take affect until after the PR has landed

**Comment by alyssawilk** [comment]
@phlax I agree mobile tests don't run on normal changes but they used to
see https://github.com/envoyproxy/envoy/pull/29931
most of the linux builds (cc tests, core tests etc) ran, but the "expensive" ones (ios, mobile emulators) did not.

**Comment by phlax** [comment]
ok - i think i see the issue - 2 of the tests - at least one of which was added just before the update did not have the conditions appied that the other jobs did - so yep were running on every pr

we can do that if that is what we want - i think it makes sense - but small warning about implications of increased rbe usage

**Comment by phlax** [comment]
3 of the tests https://github.com/envoyproxy/envoy/blob/5c4b0d653626122096b7b1dd0713f2d24aaf093d/.github/workflows/mobile-compile_time_options.yml#L24-L107

**Comment by phlax** [comment]
https://github.com/envoyproxy/envoy/pull/31652

**Pull request merged**
