### PR TITLE
docs: add note about building docs without docker

### PR DESCRIPTION
**Pull request by kenjenkins**
Commit Message: docs: add note about building docs without docker
Additional Description:
Risk Level: low
Testing: none
Docs Changes: README
Release Notes: n/a
Platform Specific Features: n/a
#30077

### CODE REVIEW

**Comment by phlax** [comment]
@kenjenkins im in 2 minds about it for the reasons i explained before

having said that im not adverse to adding documentation on using bazel directly

i think i would prefer if we couched it in a warning about containers/isolation - and suggesting that these commands can be run inside a container (as well as on host at own risk)

**Comment by phlax** [comment]
> If building docs outside of the docker build environment is not supported, this line of the README should also be updated, as it is no longer accurate:

agreed this could/should be worded better

> it also might make sense to fold the docs README sections "Building in an existing Envoy development environment" and "Using the Docker build container to build the documentation" into one.

kinda makes sense - as i said i think there is some value in providing direct bazel instructions, but not sure how best to structure it

> I'm not sure I understand the concern about isolation. 

mostly i prefer not to run any outside code on my host (even my own tbh) - so i tend to _any_ dev in a docker env

bazel provides some isolation - eg with sandboxing etc, but it doesnt really preclude something bad from happening

> ...  do feel free to close it.

i totally understand where you are coming from and would rather we update/improve than close - mostly along the lines of your suggestion above

the truth is the developer docs are desperately in need of some attention

i have had other priorities recently, but this is pretty high

one of the things we are pondering is how best to structure them - currently they are spread around the repo and its very hard to find anything useful unless you know in advance where it is - one idea is using a wiki, another is moving to rst, not sure on that, but any help here would be hugely appreciated

**Comment by phlax** [comment]
related #29957

**Comment by alyssawilk** [comment]
@phlax unclear to me what the status is on this one.  Author said you could close if you didn't want to merge - should this be merged, closed, or wait-on-something?

**Review by phlax — APPROVED** [review]
lgtm, thanks @kenjenkins

**Pull request merged**
