### PR TITLE
ci: Use `x64-large` ami/pool for x64 release/build/test

### PR DESCRIPTION
**Pull request by phlax**
This resolves ongoing disk issues (at least for this job), and also provides a pretty big speedup to CI

Partial fix for #25737 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@mattklein123 @lizan im not sure what the cost considerations of this are, but it both resolves the disk space issue and halves the time for this job to run

if possible, it would be good to do similar for the docker_ci and verify_examples jobs as they both suffer from the disk space issue, and in the latter case slow down CI a lot

**Review by mattklein123 — APPROVED** [review]

**Comment by lizan** [comment]
If we want to do more jobs for this, we might want setup an medium pool that doesn't have this much of CPU/RAM. They are still using RBE so it shouldn't require as much as coverage jobs.

**Comment by phlax** [comment]
> we might want setup an medium pool that doesn't have this much of CPU/RAM

yep makes sense

that said - the speed boost to the x64 build job is really nice from a waiting-on-ci pov

the docker_ci job is pretty fast now and a fair amount of the time is net io so in that case it definitely makes sense

ive tried to test the `x64-large` image with the verify examples job, which im guessing could speed up quite a lot - but it requires (amonst other things) `docker-compose` and i havent figured a way to add that (other than using docker to root the vm)

**Comment by phlax** [comment]
relatedly ive added a PR to add in some utils that are required in CI jobs https://github.com/envoyproxy/ci-infra/pull/13

ive also raised a ticket about sudoing powers in the self-hosted amis https://github.com/envoyproxy/ci-infra/issues/14

**Comment by phlax** [comment]
>  i havent figured a way to add that

switching to `docker compose` should make the problem moot as well as fix a bunch of others (and speed up verify)

#25973

**Comment by phlax** [comment]
> ...the verify examples job, which im guessing could speed up quite a lot ...

turns out not to make that much difference - i guess because it builds/runs one image/sandbox at a time and the `RUNs` which take most of the time, are mostly single core and/or net io (ie apt-get)

i have a PR which i hope to revive fairly soon that makes the example verify jobs run in parallel - iirc that gave a fairly big speed boost even just with the standard agent - im guessing on a large ami more so

**Pull request merged**
