### PR TITLE
Updat-2 searchtools.js DOM text reinterpreted as HTML

### PR DESCRIPTION
**Pull request by Shivam7-1**
Additional Description: By using innerText, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML.

### CODE REVIEW

**Comment by Shivam7-1** [comment]
Hii @phlax Could You Please Review This PR 
Thanks

**Comment by Shivam7-1** [comment]
Hii @phlax 
Thanks For Reviewing this PR From Your Time :) 
Instead of replacing innerHTML with innerText, could we use DOMPurify here?
 It sanitizes the content and renders the HTML without modifying the original HTML structure.

Let me know your thoughts!

**Comment by Shivam7-1** [comment]
Hii @phlax Thanks for your suggestion. I’ll try to raise this with the Sphinx project as you recommended. I understand the priority and will focus on suggesting a fix for new content moving forward.

**Comment by phlax** [comment]
closing this as #wontfix

**Pull request closed without merging**
