### PR TITLE
[http] Remove legacy codecs

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Commit Message: Removes legacy codecs.
Risk Level: Low, already default.
Testing: All existing tests remain the same, no functional changes.
Release Notes: added notice runtime flag and legacy code paths were removed.
Fixes: https://github.com/envoyproxy/envoy/issues/10878

### CODE REVIEW

**Comment by yanavlasov** [comment]
LGTM. I think clang-tidy is pre-existing

**Comment by asraa** [comment]
Still getting a clang-tidy error despite `//source/common/event:real_time_system_lib` appearing in the deps of `test_time_lib`. I believe this is a flake/clang-tidy mistake? People have seen this before, not sure why. @lizan 
```
Diagnostics:
- DiagnosticMessage:
    FileOffset: 23
    FilePath: ./test/test_common/test_time.h
    Message: '''common/event/real_time_system.h'' file not found'
    Replacements: []
  DiagnosticName: clang-diagnostic-error
```

**Comment by yanavlasov** [comment]
This looks like fixing the issue.
```
diff --git a/test/common/http/http2/BUILD b/test/common/http/http2/BUILD
index 8d8d149d1..8dca77e67 100644
--- a/test/common/http/http2/BUILD
+++ b/test/common/http/http2/BUILD
@@ -47,6 +47,7 @@ envoy_cc_test_library(
     external_deps = ["abseil_optional"],
     deps = [
         "//source/common/http/http2:codec_lib",
+        "//test/mocks:common_lib",
     ],
 )
 ```

**Comment by asraa** [comment]
Wow, thanks -- I should have scrolled more through the logs to see the pointer to test util. Fixed.

**Review by yanavlasov — APPROVED** [review]

**Comment by mattklein123** [comment]
Congratulations @asraa!!! Very nicely done. :tada:

**Comment by asraa** [comment]
Lots of code removed! Hope it goes smooth :)

**Pull request merged**
