### PR TITLE
config: log the affected cluster/destination for xDS failures

### PR DESCRIPTION
**Pull request by ggreenway**
Signed-off-by: Greg Greenway <ggreenway@apple.com>

Commit Message: When multiple xDS servers are configured, it is helpful to log which one the event is related to.
Additional Description:
Risk Level: Low
Testing: Modified existing test; the change only affects logging so minimal testing required
Docs Changes: none
Release Notes: none
Platform Specific Features: none
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by kyessenov — APPROVED** [review]
Random thought: we could follow https://github.com/grpc/grpc/blob/master/doc/naming.md and define target_uri for Envoy's client.

**Comment by adisuissa** [comment]
CI error seems legit

**Pull request merged**
