### PR TITLE
Quiche roll 20220420104315

### PR DESCRIPTION
**Pull request by danzh2010**
Update QUICHE from 8864d08f6 to af2e52ab5
    https://github.com/google/quiche/compare/8864d08f6..af2e52ab5
    
    $ git log 8864d08f6..af2e52ab5 --date=short --no-merges --format="%ad %al %s"
    
    2022-04-20 danzh Deprecate --gfe2_reloadable_flag_quic_count_bytes_on_alternative_path_seperately.
    2022-04-20 dschinazi Remove support for CONNECT-FOO methods
    2022-04-19 birenroy Removes C++20-style designated initializers from nghttp2_adapter_test.cc.
    2022-04-19 birenroy Removes C++20-style designated initializers from adapter_impl_comparison_test.cc.
    2022-04-19 birenroy Removes C++20-style designated initializers from nghttp2_test_utils.h.
    2022-04-19 fayang Add QuicPingManager to manage the PING alarm.
    2022-04-19 ramosalex Deliver INITIAL packets before other packets.
    2022-04-19 danzh While sending PATH_CHALLENGE, make sure QuicConnection flushes probing packet on alternative path before bundling ACK.
    2022-04-19 bnc Remove extraneous newline from the end of huffman_spec_tables.cc.
    2022-04-19 bnc Deprecate --gfe2_reloadable_flag_quic_limit_encoder_dynamic_table_size.
    2022-04-18 bnc clang-format third_party/http2
    2022-04-18 vasilvv Export four currently unexported HTTP/2 tests.
    2022-04-18 fayang In QuicConnection, rename ping_timeout_ to keep_alive_ping_timeout_. Remove two getters ping_timeout() and initial_retransmittable_on_wire_timeout().
    2022-04-18 bnc Add QUICHE_EXPORT_PRIVATE and QUICHE_NO_EXPORT as necessary.
    2022-04-18 bnc Remove connection close-related QUIC_BUGs.
    2022-04-18 bnc Remove unused PushId and struct MaxPushIdFrame.
    2022-04-18 bnc Deprecate --gfe2_reloadable_flag_quic_ignore_max_push_id.
    2022-04-18 bnc clang-format third_party/quic
    2022-04-17 dschinazi Remove legacy MASQUE mode
    2022-04-16 bnc Use QUICHE_BUG instead of GFE_BUG in Balsa.
    2022-04-15 quiche-dev Internal change
    2022-04-15 dschinazi Remove datagram context registration
    2022-04-15 bnc clang-format rest of //third_party/quiche/
    2022-04-15 dschinazi Remove HTTP Datagram contexts
    2022-04-14 bnc clang-format //third_party/spdy/
    2022-04-14 vasilvv Add a missing QUICHE_EXPORT_PRIVATE to spdy_protocol.h
    2022-04-14 vasilvv Export quiche_file_utils.h test data into QUICHE
    2022-04-14 wub Change quic::test::ServerThread to take a std::unique_ptr<QuicServer> instead of a raw pointer.
    2022-04-14 bnc clang-format //third_party/http2/
    2022-04-14 bnc clang-format //third_party/http2/
    2022-04-14 bnc clang-format //third_party/http2/
    2022-04-13 bnc clang-format rest of //third_party/quic/
    2022-04-13 vasilvv Fix Chromium build.
    2022-04-13 quiche-dev Deprecate --gfe2_reloadable_flag_enable_tcp_session_security_policy_id_logging.
    2022-04-13 vasilvv Rename quic_transport_test_utils.h to web_transport_test_utils.h
    2022-04-13 bnc Remove VERIFY_AND_RETURN_SUCCESS.
    2022-04-13 martinduke Use Span in QUIC-LB EncryptionPass()
    2022-04-13 bnc Fix some includes in third_party/http2 tests.
    2022-04-13 bnc Add QUICHE_EXPORT_PRIVATE as necessary.
    2022-04-13 martinduke Add benchmark tests to QUIC-LB library
    2022-04-13 bnc clang-format QUICHE
    2022-04-13 bnc clang-format QUICHE
    2022-04-13 bnc clang-format QUICHE
    2022-04-13 bnc clang-format QUICHE
    2022-04-13 bnc clang-format QUICHE
    2022-04-13 bnc clang-format QUICHE
    2022-04-13 bnc clang-format QUICHE
    2022-04-13 birenroy Removes http2_test_helpers.h from //third_party/http2/platform/api.
    2022-04-13 bnc Use std::tuple and std::get instead of testing:: aliases in QUICHE.
    2022-04-13 bnc clang-format QUICHE
    2022-04-13 bnc clang-format QUICHE
    2022-04-13 vasilvv Unexport quic_transport.
    2022-04-12 bnc clang-format QUICHE
    2022-04-12 vasilvv Import of QUIC trace library from GitHub using workflow squash_head.
    2022-04-12 bnc clang-format QUICHE
    2022-04-12 bnc clang-format QUICHE
    2022-04-12 bnc clang-format QUICHE
    2022-04-12 vasilvv Remove or narrow down some unnecessary includes.
    2022-04-12 vasilvv Provide the default implementation of QuicheTestLoopback
    2022-04-12 bnc clang-format QUICHE
    2022-04-12 bnc clang-format QUICHE
    2022-04-12 fayang Internal change
    2022-04-12 bnc clang-format QUICHE
    2022-04-12 bnc clang-format QUICHE
    2022-04-12 bnc clang-format QUICHE
    2022-04-11 birenroy Updates QpackHeaderTable to use QuicheCircularDeque rather than std::deque.
    2022-04-11 bnc Edit and clang-format third_party/quic/core/crypto/crypto_framer_test.cc.
    2022-04-11 diannahu Validate that received GOAWAY last-stream-ID fields are non-increasing in oghttp2.
    2022-04-11 birenroy Migrates HpackHeaderTable from std::deque to quiche::QuicheCircularDeque.

Risk Level: low
Testing: existing tests pass 
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]
Wow, that is a LOT of QUICEH changes!

**Comment by phlax** [comment]
@moderation would you mind having a look as dep-shepherd

**Comment by danzh2010** [comment]
Ping for merge?

**Pull request merged**
