### PR TITLE
Updates to mobile/third_party/rbe_configs/cc/

### PR DESCRIPTION
**Pull request by asedeno**
This updates files containing paths to older versions of the docker container being used in CI. This matters when clang modules are being used and some dependency (looking at absl) turns on layering checks. Not updating these files prevents abseil from including many standard headers.

These files should be regenerated whenever our base docker container or toolchain is updated.

These files were regenerated following the instructions in https://github.com/bazelbuild/bazel-toolchains

Specifically:

```
$ ./rbe_configs_gen \
  --bazel_version="6.5.0" \
  --toolchain_container="docker.io/envoyproxy/envoy-build-ubuntu:f94a38f62220a2b017878b790b6ea98a0f6c5f9c" \
  --exec_os="linux" \
  --target_os="linux" \
  --output_src_root="/path/to/envoy-mobile" \
  --output_config_path="third_party/rbe_configs" \
  --cpp_env_json=clang.json \
  --generate_java_configs=False
$ cat clang.json
{"CC": "/opt/llvm/bin/clang", "CXX": "/opt/llvm/bin/clang++"}
```

Other files were also regenerated, but this commit only contains changes to files with paths.

Risk Level: low
Testing: CI, since this specifically affects the CI.

### CODE REVIEW

**Comment by phlax** [comment]
> These files should be regenerated whenever our base docker container or toolchain is updated.

the code for updating the build image is here https://github.com/envoyproxy/envoy/blob/d7394605f0f530349c1c9fca6c6b7b975d8a7cf0/.github/workflows/envoy-dependency.yml#L126-L225

perhaps we can add something there to do toolchain regeneration at the same time

**Comment by asedeno** [comment]
I can look into that, with two caveats.
1) You may be able to deal with faster than I can, as I'm still getting up to speed on how all this works.
2) I'd like to get _this_ change in sooner rather than later, and not block fixing the broken thing on automating fixing it.

I'm not sure what the automation should look like yet, given the resource exhaustion experienced in #36172. Also, that PR had a series of patches undoing some of the generated changes, some of which were just tidying up, and some of which may not have been needed.

**Comment by phlax** [comment]
for sure, out of scope for current change - was more following up on your comment

happy to assist if you want to delve into our ci system

this is one of the easier workflows to change/test/etc so probably not crazy hard to do

**Review by phlax — APPROVED** [review]
lgtm, thanks @asedeno

**Pull request merged**
