### PR TITLE
upgrade rules_go to v0.27.0 (#16065)

### PR DESCRIPTION
**Pull request by QIvan**
in the resent version of rules_go, the issue https://github.com/bazelbuild/rules_go/issues/2771 was fixed. 
It should address the bazel build issue on some Linux or MacOS (https://github.com/bazelbuild/bazel/issues/12986)

### CODE REVIEW

**Comment by moderation** [comment]
I've been running this in my environments since it was released
/lgtm deps

**Comment by moderation** [comment]
Might be too late but might be good to bump the Go version to `1.16.3` as part of this change - https://github.com/envoyproxy/envoy/blob/main/bazel/dependency_imports.bzl#L14

**Comment by QIvan** [comment]
@moderation done (see the last commit)

**Comment by QIvan** [comment]
hmmmm...  after go upgrade it complains like 
```bash 
ERROR: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/com_github_lyft_protoc_gen_star/BUILD.bazel:3:11: GoCompilePkg external/com_github_lyft_protoc_gen_star/protoc-gen-star.a failed (Exit 1): builder failed: error executing command 
  (cd /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy && \
  exec env - \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=linux \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=/opt/llvm/bin:/usr/bin:/bin \
  bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src external/com_github_lyft_protoc_gen_star/artifact.go -src external/com_github_lyft_protoc_gen_star/ast.go -src external/com_github_lyft_protoc_gen_star/build_context.go -src external/com_github_lyft_protoc_gen_star/comment.go -src external/com_github_lyft_protoc_gen_star/debug.go -src external/com_github_lyft_protoc_gen_star/docs.go -src external/com_github_lyft_protoc_gen_star/entity.go -src external/com_github_lyft_protoc_gen_star/enum.go -src external/com_github_lyft_protoc_gen_star/enum_value.go -src external/com_github_lyft_protoc_gen_star/extension.go -src external/com_github_lyft_protoc_gen_star/field.go -src external/com_github_lyft_protoc_gen_star/field_type.go -src external/com_github_lyft_protoc_gen_star/field_type_elem.go -src external/com_github_lyft_protoc_gen_star/file.go -src external/com_github_lyft_protoc_gen_star/generator.go -src external/com_github_lyft_protoc_gen_star/init_option.go -src external/com_github_lyft_protoc_gen_star/message.go -src external/com_github_lyft_protoc_gen_star/method.go -src external/com_github_lyft_protoc_gen_star/module.go -src external/com_github_lyft_protoc_gen_star/name.go -src external/com_github_lyft_protoc_gen_star/node.go -src external/com_github_lyft_protoc_gen_star/oneof.go -src external/com_github_lyft_protoc_gen_star/package.go -src external/com_github_lyft_protoc_gen_star/parameters.go -src external/com_github_lyft_protoc_gen_star/persister.go -src external/com_github_lyft_protoc_gen_star/post_process.go -src external/com_github_lyft_protoc_gen_star/proto.go -src external/com_github_lyft_protoc_gen_star/service.go -src external/com_github_lyft_protoc_gen_star/source_code_info.go -src external/com_github_lyft_protoc_gen_star/wkt.go -src external/com_github_lyft_protoc_gen_star/workflow.go -arc 'github.com/golang/protobuf/proto=github.com/golang/protobuf/proto=bazel-out/host/bin/external/com_github_golang_protobuf/proto/proto.x' -arc 'github.com/golang/protobuf/protoc-gen-go/plugin=github.com/golang/protobuf/protoc-gen-go/plugin=bazel-out/host/bin/external/io_bazel_rules_go/proto/wkt/compiler_plugin_go_proto.x' -arc 'github.com/golang/protobuf/protoc-gen-go/descriptor=github.com/golang/protobuf/protoc-gen-go/descriptor=bazel-out/host/bin/external/io_bazel_rules_go/proto/wkt/descriptor_go_proto.x' -importpath github.com/lyft/protoc-gen-star -p github.com/lyft/protoc-gen-star -package_list bazel-out/host/bin/external/go_sdk/packages.txt -o bazel-out/host/bin/external/com_github_lyft_protoc_gen_star/protoc-gen-star.a -x bazel-out/host/bin/external/com_github_lyft_protoc_gen_star/protoc-gen-star.x -gcflags '' -asmflags '')
Execution platform: @rbe_ubuntu_clang_libcxx//config:platform
compilepkg: missing strict dependencies:
	/b/f/w/external/com_github_lyft_protoc_gen_star/init_option.go: import of "github.com/spf13/afero"
	/b/f/w/external/com_github_lyft_protoc_gen_star/persister.go: import of "github.com/spf13/afero"
No dependencies were provided.
```


seems like it's not an easy change. I'll revert the last commit

**Comment by moderation** [comment]
I'm guessing this is a change in module handling in Go 1.16. I'm building the API and the binary and it works but it is with a subset of extensions compiled in.

Can we bump to 1.15.11 which is the latest Go version  that should be compatible?

**Review by membphis — APPROVED** [review]

**Review by lizan — APPROVED** [review]

**Comment by QIvan** [comment]
@moderation sorry, didn't get in time with the change...

**Pull request merged**
