### PR TITLE
quic: remove runtime guard and code for legacy cert handling

### LINKED ISSUE #36612: envoy_restart_features_quic_handle_certs_with_shared_tls_code deprecation
Your change #32260 (quic: support cert selection by SNI, non-PEM formats) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

### PR DESCRIPTION
**Pull request by ggreenway**
Fixes #36612

### CODE REVIEW

**Review by mattklein123 — DISMISSED** [review]

**Comment by ggreenway** [comment]
`Code coverage for source/common/quic is lower than limit of 93.6 (93.3)` because I removed some covered code. I'll resolve. /wait

**Review by alyssawilk — APPROVED** [review]
Well that's some awesome clean up!  Bummer about the coverage but legit lowering, so LGTM

**Comment by alyssawilk** [comment]
may need a main merge for CI though
/retest

**Comment by alyssawilk** [comment]
ooh crud I was going to ask for a main merge for https://github.com/envoyproxy/envoy/pull/36762 too
@mattklein123 if you see a permafail due to these two conflicting lmk and I'll fix

**Pull request merged**
