### PR TITLE
move UpdateAck to its own compilation unit; add PausableAckQueue::pop…

### PR DESCRIPTION
**Pull request by wgallagher**
…Front()

Signed-off-by: Bill Gallagher <bgallagher@lyft.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description: part 1 of the delta/sotw PR breakup
Risk Level: low, should be no behavior changes
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by wgallagher** [comment]
Co-authored-by: fredlas@google.com

**Comment by jmarantz** [comment]
Looks reasonable so far; can you add unit tests?

Also, can you avoid force-pushing? that loses review context. It should be fine to just merge master, without rebasing as well, FYI

**Comment by wgallagher** [comment]
sorry about the force push, i'll add some unit tests @gkleiman @mattklein123

**Comment by mattklein123** [comment]
Generally LGTM. Per @jmarantz is there any worthwhile unit testing to be done here?

/wait-any

**Comment by htuch** [comment]
We probably want to wait until we do v3alpha --> v3 before doing much more here, should happen in next couple of days.

**Pull request merged**
