### PR TITLE
build: Bump Bazel to 3.7.0

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Commit Message: Bump Bazel to 3.7.0
Additional Description: Build container bumps MSVC toolchain for Windows, helps us move forward to enable clang-cl which requires LLVM 11.0.0 (requires a bug fix backported to Bazel 3.7.1 and in 4.0.0)
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by moderation — APPROVED** [review]

**Comment by sunjayBhatia** [comment]
coverage differences in `test/common/network`

master: https://storage.googleapis.com/envoy-postsubmit/master/coverage/source/common/network/socket_impl.cc.gcov.html

PR: https://storage.googleapis.com/envoy-pr/9f7beaf/coverage/source/common/network/socket_impl.cc.gcov.html

**Comment by lizan** [comment]
> coverage differences in `test/common/network`
> 
> master: https://storage.googleapis.com/envoy-postsubmit/master/coverage/source/common/network/socket_impl.cc.gcov.html
> 
> PR: https://storage.googleapis.com/envoy-pr/9f7beaf/coverage/source/common/network/socket_impl.cc.gcov.html

I've seen same in different PR as well, might not related to the bump but might be some flakes (and being cached)

**Comment by wrowe** [comment]
@sunjayBhatia is taking the entire week, but I'm available to tweak commits, or you can do so yourself.

My 2c, let's take this if it is convenient before Tuesday, just to have greater confidence in the 3.7.1 bump.

**Comment by lizan** [comment]
all fuzz_coverage tests are failing and it's obviously broken, so we need to fix that and I don't think it will be fixed in 3.7.1 either.

**Comment by wrowe** [comment]
> we need to fix that and I don't think it will be fixed in 3.7.1 either

Have you identified this as bazel's or envoy's defect, @lizan? There's still a window today to note the regression at https://github.com/bazelbuild/bazel/issues/12188 if this represents a 3.6.0 regression.

**Comment by sunjayBhatia** [comment]
Bumps to Bazel 3.7+ are blocked on https://github.com/bazelbuild/bazel/issues/12545

**Comment by sunjayBhatia** [comment]
closing in favor of https://github.com/envoyproxy/envoy/pull/14134, though we will need a 3.7.2 to fix the regression reported in https://github.com/bazelbuild/bazel/issues/12545

**Pull request closed without merging**
