### PR TITLE
Turn ext_proc into API stable.

### PR DESCRIPTION
**Pull request by yanjunxiang-google**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by htuch — DISMISSED** [review]
I think it's time, thanks. @gbrail @mattklein123 FYI.

**Review by tyxia — APPROVED** [review]
LGTM, Thanks

**Comment by yanavlasov** [comment]
I think the status in source/extensions/extensions_metadata.yaml needs update too.

/wait-any

**Comment by tyxia** [comment]
> I think the status in source/extensions/extensions_metadata.yaml needs update too.

@yanavlasov  My understanding is that the status in `extensions_metadata.yaml` represents the extension status while here is ext_proc's API status that we will avoid breaking API change going forward. 
We are not fully ready to change extension status yet as we are re-designing the grpcCall.
Or do you think those two status are basically same?

**Comment by htuch** [comment]
We can graduate the API to stable before the implementation.

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
