### PR TITLE
Add createPath to Filesystem abstraction

### PR DESCRIPTION
**Pull request by ravenblackx**
Commit Message: Add createPath to Filesystem abstraction
Additional Description: createPath support is a prerequisite of [file_system_http_cache](https://sourcegraph.com/github.com/envoyproxy/envoy/-/blob/api/envoy/extensions/http/cache/file_system_http_cache/v3/file_system_http_cache.proto?L130)'s `create_cache_path` support.

This is a revert of a [revert](https://github.com/envoyproxy/envoy/pull/26675/files); more tests were added, and firmer specifications, but it's using std::filesystem again as the insufficient dependencies when it landed before have been updated.
Risk Level: Very low, change is not used yet.
Testing: Covered.
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: Identical std::filesystem implementation for Windows and Posix.

### CODE REVIEW

**Comment by yanavlasov** [comment]
CI failures look legit

**Comment by RyanTheOptimist** [comment]
@alyssawilk is out, but the test/per_file_coverage.sh change LGTM.

**Comment by yanavlasov** [comment]
New tests failing on Windows.

/wait

**Comment by alyssawilk** [comment]
Clang-tidy looks like it's failing.  not sure ifit's real or not
/retest
@yanavlasov can you do first pass here?  I'm still digging out of vacation debt

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
