### PR TITLE
quic: add QuicNetworkConnectivityObserver and EnvoyQuicNetworkObserverRegistry interfaces

### PR DESCRIPTION
**Pull request by danzh2010**
Commit Message: Introduce a new classes `QuicNetworkConnectivityObserver` and `EnvoyQuicNetworkObserverRegistry`/`EnvoyQuicNetworkObserverRegistryFactory` in Envoy to register each QUIC connection for network changes. An `EnvoyQuicNetworkObserverRegistryFactory` object can be passed into `ClusterManager::createNetworkObserverRegistries()` interface to create a thread local EnvoyQuicNetworkObserverRegistry object. Each new Quic connection will register its own QuicNetworkConnectivityObserver to this registry.

Additional Description: `QuicNetworkConnectivityObserver` currently has an empty implementation. And `createNetworkObserverRegistries()` will be called by Envoy Mobile with its own network change aware implementation of the registry factory.

Risk Level: low, new interface not in use
Testing: added new unit tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by RyanTheOptimist — APPROVED** [review]
Looks great! Thanks for doing this.

**Comment by RyanTheOptimist** [comment]
Is this a real test failure?

https://dev.azure.com/cncf/envoy/_build/results?buildId=178930&view=logs&jobId=b6a93b2f-c9eb-5004-2b80-f11f3e41d6df&j=b6a93b2f-c9eb-5004-2b80-f11f3e41d6df&t=b9aeef91-fdf0-5be6-08f0-d544c00fc771

**Comment by danzh2010** [comment]
> Is this a real test failure?
> 
> https://dev.azure.com/cncf/envoy/_build/results?buildId=178930&view=logs&jobId=b6a93b2f-c9eb-5004-2b80-f11f3e41d6df&j=b6a93b2f-c9eb-5004-2b80-f11f3e41d6df&t=b9aeef91-fdf0-5be6-08f0-d544c00fc771

It also happen on main, so not related. I will debug into it.

**Comment by abeyad** [comment]
> > Is this a real test failure?
> > https://dev.azure.com/cncf/envoy/_build/results?buildId=178930&view=logs&jobId=b6a93b2f-c9eb-5004-2b80-f11f3e41d6df&j=b6a93b2f-c9eb-5004-2b80-f11f3e41d6df&t=b9aeef91-fdf0-5be6-08f0-d544c00fc771
> 
> It also happen on main, so not related. I will debug into it.

@danzh2010 I wonder if this relates to https://github.com/envoyproxy/envoy/pull/35652 ?  Running the test locally with `--runs_per_test=100` doesn't fail for me though..

**Pull request merged**
