### PR TITLE
test: use semantic names for all extensions

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

Description: Follow-up to #10122 . Changes the names for all extension configs that have typed configs with a URL. Contains two additional changes: 1) use typed config URL when type URL is specified, not when value is specified, 2) turn health checker factories into typed factories
Risk Level: low
Testing: unit
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by zuercher** [comment]
I think this looks good, modulo the conflict with my inflight PR and the version_integration_test failure.

**Comment by kyessenov** [comment]
Note that I preserved `name: envoy.filters.http.router` in most (but not all) cases to make sure we continue supporting config without type URLs.

**Pull request merged**
