### PR TITLE
Tap sink typed extension

### PR DESCRIPTION
**Pull request by ashishb-solo**
Commit Message: add TypedExtensionConfig output sink to tap filter
Additional Description: enable Envoy extensions to write custom output sinks by hooking into the filter via the custom_sink output sink object
Risk Level: medium
Testing: in progress
Docs Changes: N/A
Release Notes: to be completed
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by mattklein123 — CHANGES_REQUESTED** [review]
LGTM, thanks. Please add a release note.

/wait

**Comment by ashishb-solo** [comment]
@mattklein123 Thanks for the review! Changelog has been added

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
