### PR TITLE
cluster: Lazy initialization of update callbacks in PrioritySetImpl

### PR DESCRIPTION
**Pull request by tpetkov-VMW**
Commit Message: Initialize PrioritySetImpl callbacks only when needed, in order to save memory
Additional Description: Encapsulate host_set_ - related callbacks inside a separate structure, which initializes its callbacks only when a callback is added via addPriorityUpdateCb. Initialize member_update_cb_helper_ lazily
Risk Level: Medium
Testing: Unit test (test/common/...)
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
#19332 
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by wbpcode** [comment]
Thanks for working for this. I agree that we need to try to reduce some memory overhead. 

But at the same time we also need to consider ROI. `if (xxx == nullptr) { xxxxx = {} } xxxx.method()` can eliminates lots of memory for objects that are not in the critical path. But it also make the code more complex and bring some `if check` overhead.
So when we use this pattern, the following two points must be considered: 
1. Is the corresponding object really not on the critical path? In other words, is this object really rarely used? `addPriorityUpdateCb` is important for the LB/EDS and almost always be called. The same can be said for `addMemberUpdateCb`.
2. Is the corresponding objects really bring lots of memory overhead? I haven't evaluated it carefully, but most of the overhead should be reasonable.

**Comment by tpetkov-VMW** [comment]
I think I can extract some examples showing that there are indeed use cases in which we'd save memory, and the benefits would be per-thread and per-cluster. 
I wanted to push the latest changes, because I managed to shave off some redundant nullptr checks and make the lazy parts a bit more contained.
To give a broader perspective, we don't use any load balancers at all, and we really don't want to have the extra memory overhead.

@wbpcode  - do you have any alternatives in mind? 
Considering that this patch doesn't add a large performance overhead, would any overhead for the LB case be considered unacceptable?

**Comment by wbpcode** [comment]
> To give a broader perspective, we don't use any load balancers at all, and we really don't want to have the extra memory overhead.

It should be impossible. Envoy will always create a load balancer instance for every thread local cluster. Or you edit the basic codes of Envoy upstream.

**Comment by wbpcode** [comment]
> Considering that this patch doesn't add a large performance overhead, would any overhead for the LB case be considered unacceptable?

For most of case and most of users, this patch does not have the effect of reducing memory overhead, but it does bring minor performance overhead for everyone and make the codes more complex.

So I think it should be reconsidered.

**Comment by wbpcode** [comment]
May be we can create a separate issue to discuss the problem of upstream clusters memory comsumption and analyze which data structures take up more memoy, and finally decide the directions of subsequent opts.

**Comment by wbpcode** [comment]
> > May be we can create a separate issue to discuss the problem of upstream clusters memory comsumption and analyze which data structures take up more memoy, and finally decide the directions of subsequent opts.
> 
> I've been using #19332 for that.
> 
> > For most of case and most of users, this patch does not have the effect of reducing memory overhead, but it does bring minor performance overhead for everyone and makes the codes more complex.
> 
> Did some testing, and we don't even get the reduced memory for our own use cases... as far as I can tell, this worked in v1.21.0, but haven't had the time to do more thorough investigation. I'll close this PR, but will investigate the other proposed patches in #19332

Thanks for your patience and works.

**Pull request closed without merging**
