### PR TITLE
[TESTING/WIP/backport/1.23] multiple addresses: add integration tests (#22081)

### PR DESCRIPTION
**Pull request by phlax**
Commit Message: multiple addresses: add integration tests Additional Description:
Risk Level: low
Testing: integration tests
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a
Part of #11184

Signed-off-by: He Jie Xu <hejie.xu@intel.com>
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by soulxu** [comment]
`MultipleLdsUpdatesSharingListenSocketFactory` doesn't test the multiple addresses. So I'm not sure this will fix the flaky.

I checked the log, all the major code merged in 1.23, (only integration test and release in 1.24) it should be safe to backport the integration tests.

**Comment by phlax** [comment]
> MultipleLdsUpdatesSharingListenSocketFactory doesn't test the multiple addresses. So I'm not sure this will fix the flaky.

any ideas what would - it seesm to happen quite a bit and ive not seen it testing 1.24 so seems like something changed

**Comment by phlax** [comment]
checking azp analytics i can see one failure for this test in the last 30 days on `main` so either the problem is just lessened or it was resolved in the last month

the ux is pretty poor so im struggling to glean any more info

**Comment by phlax** [comment]
this only happens on arm so im wondering if lack of rbe/cache or similar is related

**Comment by phlax** [comment]
worth noting it didnt fail here

**Comment by alyssawilk** [comment]
yeah it's a race with fast connect so less likely to happen with trace on.  Glad I managed to repro (after you helpfull shared build options) so we didn't get to debug by touching random files :-P

**Comment by phlax** [comment]
addressed in https://github.com/envoyproxy/envoy/pull/24071

**Pull request closed without merging**
