### PR TITLE
deps: Bump `opencensus_proto` -> 0.4.1

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
ive given this a swerve as i was ~aware that we are deprecating use

the current version is pretty old, and it spews a load of logs suggesting it uses an old version of protobuf so probably better to update if we can (not sure if it will fix those issues)

**Comment by moderation** [comment]
/lgtm deps

I'm looking forward to removing this dependency

**Review by wbpcode — APPROVED** [review]
LGTM. Thanks. 😄

**Pull request merged**
