### PR TITLE
deps: Specify emscripten dependency

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @PiotrSikora i think this may be why we keep seeing caches "blowing" and a seeming lack of hermeticity - the version is not specified so basically grabbing the latest altho i would have expected that to be hard coded by the emscripten dep itself so maybe this is wrong

iiuc then this will downgrade our version,. maybe ?

**Comment by PiotrSikora** [comment]
I don't think so. `@emsdk` is pinned to v3.1.7, so the default `"latest"` version from it's `revisions.bzl` file is always `3.1.7`.

**Comment by phlax** [comment]
thats what i would have expected but we are getting a lot of errors like this one 

```console
INFO: Repository nodejs_linux_amd64 instantiated at:
  /source/WORKSPACE:25:25: in <toplevel>
  /source/bazel/dependency_imports.bzl:60:20: in envoy_dependency_imports
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/emsdk/emscripten_deps.bzl:29:26: in emscripten_deps
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl:54:15: in node_repositories
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl:76:18: in _maybe
Repository rule node_repositories defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/build_bazel_rules_nodejs/nodejs/repositories.bzl:709:36: in <toplevel>
WARNING: Download from https://nodejs.org/dist/v16.6.2/node-v16.6.2-linux-x64.tar.xz failed: class java.io.IOException GET returned 500 Internal Server Error
ERROR: An error occurred during the fetch of repository 'nodejs_linux_amd64':
   Traceback (most recent call last):
	File "/build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/build_bazel_rules_nodejs/nodejs/repositories.bzl", line 705, column 19, in _nodejs_repo_impl
		_download_node(repository_ctx)
	File "/build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/build_bazel_rules_nodejs/nodejs/repositories.bzl", line 280, column 40, in _download_node
		repository_ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://nodejs.org/dist/v16.6.2/node-v16.6.2-linux-x64.tar.xz] to /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/nodejs_linux_amd64/bin/nodejs/temp867775646175649933/node-v16.6.2-linux-x64.tar.xz: GET returned 500 Internal Server Error
ERROR: /source/WORKSPACE:25:25: fetching node_repositories rule //external:nodejs_linux_amd64: Traceback (most recent call last):
	File "/build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/build_bazel_rules_nodejs/nodejs/repositories.bzl", line 705, column 19, in _nodejs_repo_impl
		_download_node(repository_ctx)
	File "/build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/build_bazel_rules_nodejs/nodejs/repositories.bzl", line 280, column 40, in _download_node
		repository_ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://nodejs.org/dist/v16.6.2/node-v16.6.2-linux-x64.tar.xz] to /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/nodejs_linux_amd64/bin/nodejs/temp867775646175649933/node-v16.6.2-linux-x64.tar.xz: GET returned 500 Internal Server Error
ERROR: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/nodejs/BUILD.bazel:18:6: @nodejs//:node_files depends on @nodejs_linux_amd64//:node_files in repository @nodejs_linux_amd64 which failed to fetch. no such package '@nodejs_linux_amd64//': java.io.IOException: Error downloading [https://nodejs.org/dist/v16.6.2/node-v16.6.2-linux-x64.tar.xz] to /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/nodejs_linux_amd64/bin/nodejs/temp867775646175649933/node-v16.6.2-linux-x64.tar.xz: GET returned 500 Internal Server Error
ERROR: Analysis of target '//test/extensions/bootstrap/wasm:config_test' failed; build aborted: 
INFO: Elapsed time: 77.068s

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=134020&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=00ade0d6-ffae-5af0-b5e0-e33b1813c8bc&l=64

previously i put it down to release CI - which we _did_ run yesterday, so may be related, but we are still seeing it today so not sure

seems to happen both RBE and local (bazel-remote) cache

**Comment by PiotrSikora** [comment]
It's clearly because of the `nodejs.org` errors:
```
WARNING: Download from https://nodejs.org/dist/v16.6.2/node-v16.6.2-linux-x64.tar.xz failed: class java.io.IOException GET returned 500 Internal Server Error
```

**Comment by phlax** [comment]
> It's clearly because of the nodejs.org errors:

the point is why isnt it usiing the cache ?

**Comment by phlax** [comment]
> No idea, but I don't see how this PR would fix that.

if for some reason that dep was either being cachekeyed differently or the version itself was changing

tbh its clutching at straws, we are cutting a release - probs tomorrow - and this is a pretty endemic problem

perhaps trying to use/find a mirror would be a better solution

**Review by mattklein123 — APPROVED** [review]

**Comment by phlax** [comment]
ill land this on the basis that its not gonna hurt, but ill see if i can find a better mirror also - would be good to know the root cause of the cache issue tho

**Comment by phlax** [comment]
looking at the source for this version i still dont see how it would be non-deterministic:

https://github.com/emscripten-core/emsdk/blob/71b737e82f6611b894ba7cb57c4d9771017446b3/bazel/emscripten_deps.bzl#L5-L6

altho im never sure exactly how starlark <> python works

most likely a coincidence (ie related to #26632) but landing this triggered a CI run as it saw it as a deps change that ran CI in record time

**Comment by phlax** [comment]
https://dev.azure.com/cncf/envoy/_build/results?buildId=134097&view=logs&s=fbb7e3ed-ed2b-5ffd-2e3f-9e68630afbc3

**Comment by phlax** [comment]
following up on this i now understand better the reasons we were seeing the "caching" issue so frequently

essentially the deps are not being cached in the `repository_cache` and so we dont currently cache them

on top of that the deps are huge and mirrors flakey so it was giving a fairly frequent flake

i have raised a PR to address that separately here #26870 

it would be still good to update the empscripten deps, and by extension proxy-wasm-cpp-sdk but the build seems good 

the only other reason i suspected there was a hermetic problem with the dep was because release branch tests went stale, but there could be any number of reasons for that, and the build looks good from combing the exec log

cc @mpwarres

**Pull request merged**
