### PR TITLE
build: remove explicit PY2/PY3 references.

### PR DESCRIPTION
**Pull request by htuch**
Now that we are Python 3 everywhere, remove explicit python_versions. I haven't made this change yet
to the Thrift extension, as it has explicit PY2/PY3 overrides that I'm guessing relate to external
libs.

Risk level: Low (tooling only)
Testing: bazel.api

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

**Comment by htuch** [comment]
@zuercher do you know what's needed to move https://github.com/envoyproxy/envoy/blob/master/test/extensions/filters/network/thrift_proxy/driver/BUILD#L19 to Python 3? This is the last straggler in the Python 3 everywhere push.

**Comment by zuercher** [comment]
@htuch I don't remember off the top of my head. I can try to take a look later this week.

**Comment by moderation** [comment]
The Kafka extension specifies PY2. Despite my local tests passing my PR failed again with Kafka and the Jinja update - https://github.com/envoyproxy/envoy/pull/10594. I plan on taking the Jinja updates our of this PR. No response from @adamkotwasinski on Twitter or Slack

**Comment by mattklein123** [comment]
Merge master to fix CI?

/wait

**Pull request merged**
