### PR TITLE
fix potential risk of multiple listener info objects for single listener

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: fix potential risk of different listener info objects
Additional Description:

This revert part of changes of https://github.com/envoyproxy/envoy/pull/31067. In the #31067, we moved listener proto config to the `ListenerInfoImpl` object. But note that the `ListenerInfoImpl` will also be owned by the factory context and 
 the factory context will used by the new listener directly when we doing the in-place listener updating.
Finally, in the new listener, there are two listener info objects, one contain latest config and one keep the old proto config.

I think this is not what we want.

In the new implementation, the lifetime of the only one listener info object will be managed only by the factory context, just like what we do to the listener scope.

And the proto listener config will be owned by the listener object directly.

Risk Level: mid.
Testing: unit.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
Hi, @kyessenov could you take a first pass when you have free time? Thanks.

**Review by kyessenov — APPROVED** [review]
Good catch. I was aware of the dual listener info issue with the in-place update, but didn't realize the config proto is probably wasteful to duplicate. IMHO the config proto for in-place updated listener _should_ be the same, but we haven't broken down the config dump code path to properly place filter chain protos into filter chains, and the rest in the listener factory context.

**Comment by wbpcode** [comment]
friendly ping @alyssawilk for a final pass because this is core code change.

**Review by alyssawilk — CHANGES_REQUESTED** [review]
LGTM modulo you signing up to write a test which would have triggered with the bad code path :-)  If you file a tracking issue and one of you takes it on that's good enough for me to land the fix.

**Comment by wbpcode** [comment]
Let's take a look to see how to add a test for it. :)

**Comment by wbpcode** [comment]
A unit test is added to guard the case.

**Review by alyssawilk — APPROVED** [review]
awesome thanks!

**Pull request merged**
