### PR TITLE
docs: fix indent

### PR DESCRIPTION
**Pull request by shou1dwe**
Commit Message: corrected indentation for list items
Additional Description: N/A
Risk Level: Low
Testing: N/A
Docs Changes: fix indentation
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by RyanTheOptimist** [comment]
@shou1dwe You will need to fix the DCO issue in order to land this change. You can click "Details" next to the DCO check for more instructions, but in any case here is the direct link.

https://github.com/envoyproxy/envoy/pull/19090/checks?check_run_id=4310135596

**Review by phlax — APPROVED** [review]
lgtm, thanks for this @shou1dwe 

can you fix DCO and we can land, thanks

**Pull request closed without merging**
