### PR TITLE
[WIP] stats: add histogram for request and response body size

### LINKED ISSUE #3621: Feature request: statistics on request and response body size
As far as I can tell, envoy does not output request and response body sizes in bytes as separate histogram metrics.

Would be nice if it output those metrics the same way it does downstream_rq_time and upstream_rq_time.

### PR DESCRIPTION
**Pull request by ranjithkumar007**
Signed-off-by: Ranjith Kumar <ranjith.dakshana2015@gmail.com>

Commit Message: stats: add histogram for request and response body size
Additional Description:
Risk Level: Low
Testing:
Docs Changes: yes
Release Notes:
Fixes #3621

### CODE REVIEW

**Comment by ranjithkumar007** [comment]
Based on [idea](https://github.com/envoyproxy/envoy/pull/4433#issuecomment-425978289) suggested in #4433 by @zuercher

**Comment by ranjithkumar007** [comment]
cc @nezdolik

**Comment by jmarantz** [comment]
you may need to merge master to pass CI, among other things.

**Comment by ranjithkumar007** [comment]
Can we merge this with #11559? It would be more redundant work otherwise to maintain consistency in docs.

**Comment by jmarantz** [comment]
sgtm

**Pull request closed without merging**
