### PR TITLE
repo: Dev `1.19.5`

### PR DESCRIPTION
**Pull request by phlax**
- set VERSION -> dev
- cp current.rst -> v1.19.4.rst
- merge v1.19.2.rst -> v1.19.3.rst (due to failed build)

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
checking that the merge 1.19.2 -> 1.19.3 is correct - afaict yes - 25dbd02cddb95673de48312616391d14c883fd65

ill update envoy main with the missing changelog

**Comment by phlax** [comment]
This PR essentially again opens the `release/v1.19` branch up to backporting.

It will also allow us to test the branch (as a dev branch)

**Review by pradeepcrao — COMMENTED** [review]
LGTM wrt correctness regarding backports

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
