### PR TITLE
(do not merge) Investigation of coverage failures in Kafka codec

### PR DESCRIPTION
**Pull request by adamkotwasinski**
*Do not merge this PR*
Related to coverage build failures https://github.com/envoyproxy/envoy/pull/4950
Want to run them on CI infrastructure, as I have noticed that locally the issues might disappear when I disable the tests (running on mac introduces yet another variable too)

### CODE REVIEW

**Comment by mattklein123** [comment]
@adamkotwasinski I'm not sure what the issue is exactly, but if the generated files are giving you issues, can you just exclude them from coverage?

**Comment by adamkotwasinski** [comment]
post mortem

resolution:
* issue was fixed by putting all generated files in paths containing `external`, what causes them to be ignored by gcovr

possible cause:
* it looks like gcovr has problems resolving normal (hand-written) headers while processing generated header
* it is possible that gcovr would have succeeded if there were no such references (includes?) - basically trivial structures that have no complex api
* passing an argument from hand-written code / inheriting hand-written superclass caused issues - see be63c1ac1db5ff0c8baeae7a2827c38cce79861c

**Pull request closed without merging**
