### PR TITLE
repokitteh: maintainer PR checklist.

### LINKED ISSUE #12949: RepoKitteh-based PR checklists
We can have RK automatically label any change to `source/` or `api/` without a change to `current.rst` with a `release-notes` blocker, requiring manual confirmation from maintainers that the release notes step has been satisfied. Similarly this could work for documentation checks, i.e. validate that at least some change has happened in `docs/`. 

I'd propose that we take the existing `ownerscheck.star` and add a path expression that suppresses a given check. That should be all that is needed for release notes or docs.

@envoyproxy/maintainers are there other common review checklist items that RK could help with?
CC @itayd

### PR DESCRIPTION
**Pull request by htuch**
After this PR merges, RepoKitteh will enforce the following presubmit
checks:

* pr/release: block submit unless current.rst is modified
  for any change to source/ or api/. A maintainer may override with
  "/lgtm pr/release".

* pr/docs: block submit unless docs/ is modified for any change to
  source/. A maintainer may override with "/lgtm pr/docs".

* pr/tests: block submit unless test/ is modified for any change
  to source/. A maintainer may override with "/lgtm pr/tests".

Fixes #12949

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

**Review by ggreenway — CHANGES_REQUESTED** [review]
Can we create a .md somewhere which lists the available rk commands? I'm starting to lose track. Just a quick-reference.

**Comment by htuch** [comment]
@ggreenway will add to https://github.com/envoyproxy/envoy/blob/master/source/docs/repokitteh.md

**Comment by snowp** [comment]
This is super cool, thanks! 

Only comment besides what Greg suggested is that the names are bit long for typing, any option of aliasing them? `/lgtm pr/test` or something? 

I'm guessing its tied up with the label name so if its hard to do we can iterate on it later.

**Comment by htuch** [comment]
@snowp good idea, done.

**Comment by htuch** [comment]
@itayd I think `github.pr_list_files()` is providing a list of files that changes since the last PR push, rather than the global list of files that have changed, at least based on the behaviors I'm observing from RK around 380eabb and 3ac1a64.

I think we need a GH API that does both:
1. List files changed in the last GitHub push. We need this to retag folks after a PR is `/lgtm <label>` and then a file is modified again.
2. List files changed vs. the PR baseline. We need this to figure out, for the `exclude_paths` added in this patch, whether certain files exist or don't.

WDYT?

**Comment by itayd** [comment]
@htuch i need to look into it more, but will this do the job?

https://developer.github.com/v3/repos/commits/#compare-two-commits

a pr is related to a branch. in git a branch is just a pointer to commit (sort of).

**Comment by htuch** [comment]
@itayd yeah that could possibly help. I guess it would be good to have two distinct methods exported from the RK API, one to compare against the HEAD of the target branch the PR is opened against for files change, and another to provide the list of files changed in the last commit on the source branch.

**Comment by htuch** [comment]
@itayd any progress on ^^?

**Pull request closed without merging**
