### PR TITLE
proto: add tds dummy

### PR DESCRIPTION
**Pull request by goaway**
Description: Creates dummy target for tds to force linking (see comment).
Risk Level: low
Testing: compiled and ran locally

### CODE REVIEW

**Comment by goaway** [comment]
note this is thanks to @mattklein123

**Comment by mattklein123** [comment]
@goaway don't you want to add this to the link hacks file also?

**Comment by goaway** [comment]
yep you're totally right, one sec :p

**Comment by htuch** [comment]
FWIW, there is already a `Runtime` message in this file, so we could have just used that in `protobuf_link_hacks.h`.

**Comment by goaway** [comment]
@htuch Would that be preferable to the explicit dummy? (I sorta liked the explicit dummy since its purpose is clear, even if the whole thing is kind of a hack.)

**Comment by htuch** [comment]
It's fine as is, just wanted to let you know for future purposes.

**Pull request merged**
