### PR TITLE
Happy Eyeballs for EDS clusters

### PR DESCRIPTION
**Pull request by pradeepcrao**
Commit Message:
Additional Description:

This change adds the ability to associate multiple IP addresses with one host for an EDS cluster. The connection to the upstream will be made using Happy Eyeballs if the Endpoint has more than one address.

The primary use case for this is to allow dual-stack (i.e. with both IPv4 and IPv6 addresses) endpoints as a means to migrate from IPv4 to IPv6 backends. See https://docs.google.com/document/d/1AjmTcMWwb7nia4rAgqE-iqIbSbfiXCI4h1vk-FONFdM/edit#heading=h.xzptrog8pyxf for a more detailed description.

Risk Level: Low 
Testing: Added test
Docs Changes: Added Doc
Release Notes: Added release note
Platform Specific Features: N/A

### CODE REVIEW

**Review by RyanTheOptimist — DISMISSED** [review]
Nice! Though I find the idea of Happy Eyeballs without DNS to be a bit mind blowing :)

**Comment by pradeepcrao** [comment]
> Nice! Though I find the idea of Happy Eyeballs without DNS to be a bit mind blowing :)

Thank you so much for the review @RyanTheOptimist !

**Review by mattklein123 — DISMISSED** [review]
Neat!

**Review by adisuissa — APPROVED** [review]
Changes LGTM!

Can you please add a comment next to the `address_list_` [data member](https://github.com/envoyproxy/envoy/blob/fe290c2c7601b4951bff2f3695ede775bc620830/source/common/upstream/upstream_impl.h#LL314C8-L314C8), stating the underlying assumption that the first entry in the list must be the same host as `address_` (better yet, add this as an assertion somewhere if possible).

**Comment by pradeepcrao** [comment]
> > Changes LGTM!
> > Can you please add a comment next to the `address_list_` [data member](https://github.com/envoyproxy/envoy/blob/fe290c2c7601b4951bff2f3695ede775bc620830/source/common/upstream/upstream_impl.h#LL314C8-L314C8), stating the underlying assumption that the first entry in the list must be the same host as `address_` (better yet, add this as an assertion somewhere if possible).
> 
> The following `ASSERT` fails for me in the `ProtocolIntegrationTest.LogicalDns` test. It appears that this assumption is not valid for `LOGICAL_DNS`
> 
> ```
>     void setAddressList(const std::vector<Network::Address::InstanceConstSharedPtr>& address_list) {
>       address_list_ = address_list;
>       ASSERT(address_list_.empty() ||
>              std::find(address_list_.begin(), address_list_.end(), address_) != address_list_.end());
>     }
> ```

Never mind, I should be dereferencing the shared_ptrs for comparison because of how these are [constructed](https://github.com/envoyproxy/envoy/blob/main/source/extensions/clusters/logical_dns/logical_dns_cluster.cc#L124-L127)

**Review by adisuissa — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
