### PR TITLE
Windows build: Enable RBE build in Windows CI

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Commit Message:
Enable RBE build in Windows CI

- Bumps envoy-build-tools and bazel-toolchains
- Bumps envoy-build-ubuntu image tag
  - Running Windows CI via docker uses the same mechanism as Linux to find the image tag, the tags are the same for Windows and Linux images
- Temporarily adds a patch to fix rules_go for Windows RBE issue executing batch scripts, see https://github.com/envoyproxy/envoy/issues/11657
- Tags/fixes some additional tests that fail in CI

Additional Description: N/A
Risk Level: Low, but we may observe differences in performance of Windows CI running remotely, we may need to adjust the worker pool accordingly
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Fixes https://github.com/envoyproxy/envoy/issues/10619

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
This PR will be turned into a reviewable PR once https://github.com/envoyproxy/envoy-build-tools/pull/64 is merged

**Comment by sunjayBhatia** [comment]
This causes format to fail for most PRs since the CI image is bumped to one with llvm 10 (and clang-format 10). If that is undesirable as part of this change, we can submit another to bump that dependency separately.

**Comment by sunjayBhatia** [comment]
just waiting on https://github.com/envoyproxy/envoy-build-tools/pull/70 to help us generate an updated toolchain config

**Comment by wrowe** [comment]
Unclear whether the released 3.2.0 bazel version will be compatible; the final post-3.1.2 tag which picked up the the windows path fixes was;
```
        sha256 = "5d48b13686081f5d07dbba1271595d1bb2b5fa1d2f8c049ef15011bd4e6bdd19",
        strip_prefix = "bazel-toolchains-834b89b3f608a9aa4c212e7ee4a05b323b980a85",
        # 2020-05-21
        urls = ["https://github.com/bazelbuild/bazel-toolchains/archive/834b89b3f608a9aa4c212e7ee4a05b323b980a85.tar.gz"],
```

**Comment by wrowe** [comment]
Note that this bump of the docker windows -and- linux images should be synchronized with the clang-10 fixes described in https://github.com/envoyproxy/envoy/pull/11222

**Comment by sunjayBhatia** [comment]
The last Windows run successfully build envoy-static, built failing tests, and tested remaining tests in 1h 29m 55s, merging master to see how long that diff takes to build

**Comment by sunjayBhatia** [comment]
See https://github.com/envoyproxy/envoy/pull/11316#issuecomment-642675562

the latest master refresh has broken some windows test compilation due to the quiche update

**Comment by wrowe** [comment]
Need to retest, once https://github.com/envoyproxy/envoy/pull/11562 is merged

**Comment by sunjayBhatia** [comment]
Build failure currently:
```
ERROR: C:/_eb/external/go_sdk/BUILD.bazel:43:1: GoToolchainBinaryCompile external/go_sdk/builder.exe.a failed (Exit 1): builder.exe.bat failed: error executing command 
  cd C:/_eb/execroot/envoy
  SET GOROOT=external/go_sdk
  bazel-out/host/bin/external/go_sdk/builder.exe.bat
Execution platform: @rbe_windows_msvc_cl//config:platform
'bazel-out' is not recognized as an internal or external command,
operable program or batch file.
```

Not occurring locally with the latest container image

**Comment by sunjayBhatia** [comment]
Looks like the recent `rules_go` bump from https://github.com/envoyproxy/envoy/pull/11581 is the culprit

**Comment by sunjayBhatia** [comment]
Blocked on https://github.com/bazelbuild/rules_go/pull/2542

**Comment by sunjayBhatia** [comment]
Blocked by PR https://github.com/envoyproxy/envoy/pull/11719

**Comment by sunjayBhatia** [comment]
> Blocked on [bazelbuild/rules_go#2542](https://github.com/bazelbuild/rules_go/pull/2542)

No longer blocked on the rules_go PR, we have a patch in this PR for rules_go and an open issue here to track figuring out the true root cause: https://github.com/envoyproxy/envoy/issues/11657

**Comment by sunjayBhatia** [comment]
cc @nigriMSFT @davinci26 if you weren't aware of this one

**Comment by wrowe** [comment]
We have rolled up all regression fixes into a single distinct PR.  https://github.com/envoyproxy/envoy/pull/11719 needs to be applied before this one.

**Comment by sunjayBhatia** [comment]
Assuming no more test flakes, this PR should be ready for review @lizan

**Comment by sunjayBhatia** [comment]
https://dev.azure.com/cncf/envoy/_build/results?buildId=43158&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=168f295b-0553-5364-35f7-923225ecd8b3 represents a Windows build where all tests are compiled and the ones known to pass are run

**Comment by sunjayBhatia** [comment]
@lizan the TSAN failure seems to also be occurring on master, it should not be related to this change

**Comment by dio** [comment]
@sunjayBhatia merge master will help I think. Since https://github.com/envoyproxy/envoy/pull/11760 is merged.

**Comment by sunjayBhatia** [comment]
@dio Sure, will do

Can we get a review on this soon so we don't slip behind the newly merged PRs that might cause Windows breakages again?

**Pull request merged**
