### PR TITLE
owners: Remove abaptiste from xray tracer and dns filter

### PR DESCRIPTION
**Pull request by suniltheta**
Commit Message:
Additional Description: abaptiste stopped working on Envoy associated project for a while.
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Comment by abaptiste** [comment]
LGTM

**Comment by suniltheta** [comment]
Hi @mattklein123, this change is ready for your review. Thanks again.

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
