### PR TITLE
[release/v1.23] repo: Sync

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by jmarantz** [comment]
fix CI?

/wait

**Comment by phlax** [comment]
> fix CI?

blocked by #22701

**Review by jmarantz — APPROVED** [review]

**Comment by jmarantz** [comment]
looks like this needs an update.

**Pull request merged**
