### PR TITLE
GrpcFieldExtraction: Supports extracting fields of type `map<string, string>` in addition to string

### PR DESCRIPTION
**Pull request by sissisuna**
Commit Message: GrpcFieldExtraction: Supports extracting fields of type `map<string, string>` in addition to string
Additional Description: 
Risk Level: Low
Testing: Unit test
Docs Changes: Inline with the filter API proto.
Release Notes: This change is backward compatible and no behavior change is expected for existing users.
Platform Specific Features:

### CODE REVIEW

**Review by mattklein123 — CHANGES_REQUESTED** [review]
LGTM. Please add a release note, thanks.

/wait

**Comment by sissisuna** [comment]
> LGTM. Please add a release note, thanks.
> 
> /wait

Thanks for reviewing the change! The release notes are already part of the description as "Release Notes: This change is backward compatible and no behavior change is expected for existing users.", can you please let me know if anything else is missing or if I need to add it to an additional place?

**Review by abeyad — DISMISSED** [review]
/lgtm api

**Review by mattklein123 — CHANGES_REQUESTED** [review]
You need to add a release note here: https://github.com/envoyproxy/envoy/blob/main/changelogs/current.yaml

Please look at other changes and the contributing guide to learn more.

/wait

**Review by mattklein123 — DISMISSED** [review]

**Comment by mattklein123** [comment]
Sorry please merge main.

/wait

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
