### PR TITLE
deps: update com_google_cel_cpp

### PR DESCRIPTION
**Pull request by kyessenov**
Commit Message: update CEL runtime
Additional Description: address fuzzing issues caused by incomplete implementation of `ListKeys` by returning `NotImplemented` since it is unlikely to be used on wrappers (only needed for equality comparison)
Risk Level: low
Testing: added
Docs Changes: none
Release Notes: none
Fixes: https://github.com/envoyproxy/envoy/issues/21621

### CODE REVIEW

**Comment by kyessenov** [comment]
Fixing upstream instead of local patch...

**Comment by phlax** [comment]
/lgtm deps

@lizan would you mind reviewing

**Comment by kyessenov** [comment]
@lizan are you going to look at this PR? Should we re-assign?

**Comment by kyessenov** [comment]
Looking for any maintainer to stamp the dep update addressing fuzzing issues here.
@RyanTheOptimist

**Comment by kyessenov** [comment]
@lizan Can you please review this?

**Comment by jmarantz** [comment]
@phlax can you review this?

Thanks!

**Review by phlax — APPROVED** [review]
on the basis that other have reviewed already the c++ parts - lgtm

thanks @kyessenov

**Pull request merged**
