### PR TITLE
deps: Bump `edenhill_librdkafka` -> 2.1.1

### LINKED ISSUE #27145: Newer release available `edenhill_librdkafka`: v2.1.1 (current: v1.8.2)
Package Name: edenhill_librdkafka@1.8.2
Current Version: v1.8.2@2021-10-18
Available Version: v2.1.1@2023-05-02
Upstream releases: https://github.com/edenhill/librdkafka/releases

### PR DESCRIPTION
**Pull request by phlax**
Fix #27145 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by htuch — APPROVED** [review]

**Comment by adamkotwasinski** [comment]
Thanks for the heads-up @phlax !
The thing won't compile until you uptake https://github.com/phlax/envoy/pull/124 , so feel free to merge it to this branch, and then merge this into envoy main.
Tested the version with fixes: automated tests, manual tests with real clients.

**Comment by phlax** [comment]
brilliant! thanks @adamkotwasinski - ill update now ...

**Comment by phlax** [comment]
@adamkotwasinski this seems to fail the `configs_test` (maybe others)

```console
ld.lld: error: duplicate symbol: cJSON_GetErrorPtr
>>> defined at cJSON.c
>>>            cJSON.o:(cJSON_GetErrorPtr) in archive bazel-out/k8-opt/bin/external/envoy/bazel/foreign_cc/librdkafka_build/lib/librdkafka.a
>>> defined at cJSON.c:95 (/b/f/w/external/com_github_fdio_vpp_vcl/src/vppinfra/cJSON.c:95)
>>>            cJSON.c.o:(.text.cJSON_GetErrorPtr+0x0) in archive bazel-out/k8-opt/bin/contrib/vcl/source/external/libvppinfra.a

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=138108&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=4d0399a5-fd0d-5446-d022-32daa00183cc&l=597

**Comment by adamkotwasinski** [comment]
Prolly something more I need to kick out. Will be back with another PR.

**Comment by adamkotwasinski** [comment]
on my dev box
before
```
[envoy]$ objdump -t ./bazel-bin/contrib/exe/envoy-static | grep cJSON | wc -l
       0
```
after
```
[envoy]$ objdump -t ./bazel-bin/contrib/exe/envoy-static | grep cJSON | wc -l
      79
```
aaa

**Comment by adamkotwasinski** [comment]
I can't get the VCL extension (which contributes conflicting libvppinfra.a) to compile on my Mac.
So instead of using time on that, let's do the blunt way and just get rid of non-critical cJSON from librdkafka - could you please merge https://github.com/phlax/envoy/pull/125 and let's see the builds. Thanks!

**Comment by phlax** [comment]
seems we got green @adamkotwasinski - thanks for help!!!

im wondering if there is anything else we can trim on the cmake build - ive been going through all the `foreign_cc` builds gradually to see what we can trim

**Comment by phlax** [comment]
... relatedly

currently the `CMAKE_BUILD_TYPE` is ~enforced as `Bazel` which i think generally just triggers the default build - whereas many have better options - eg `Release`

for this reason, we added a way to override this recently - not sure if that is helpful here

**Comment by phlax** [comment]
@htuch this is failing some mobile CI that is now fixed - so once it gets an approval i think we can just land

**Review by htuch — APPROVED** [review]
<insert usual grumble about introducing patch files and maintenance burden but reluctantly accepting this is the lesser evil>

**Comment by adamkotwasinski** [comment]
Thanks for getting this merged! 🎉

**Pull request merged**
