### PR TITLE
bazel: update rules_rust

### PR DESCRIPTION
**Pull request by keith**
This gets us on rust 1.60

Closes https://github.com/envoyproxy/envoy/issues/21009

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Review by phlax — APPROVED** [review]
lgtm, thanks @keith

**Review by alyssawilk — APPROVED** [review]
lgtm modulo shephards approval

**Comment by alyssawilk** [comment]
automerge is on but looks like it needs a 
/retest

**Pull request merged**
