### PR TITLE
http: Add metric for active outbound frames

### PR DESCRIPTION
**Pull request by deveshkandpal1224**
Signed-off-by: deveshkandpal1224 <deveshkandpal1224@gmail.com>

- Want to add the ability to detect current number of active outbound frames. 
- While `outbound_frame_flood` counter helps us understand how many connections were destroyed but without knowing about what's the current value for active frames, its hard to tune `max_outbound_frames`.

**Commit Message**: Add metric for active outbound frames / control frames
**Additional Description**: Want to add the ability to detect current number of active outbound frames. While `outbound_frame_flood` counter helps us understand how many connections were destroyed but without knowing about what's the current value for active frames, its hard to tune `max_outbound_frames`.
**Risk Level**: Low
**Testing**: Unit Test added
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by yanavlasov** [comment]
Thanks you for making this change. Can you also add validation of this counter to this place https://github.com/envoyproxy/envoy/blob/df2f00a7e2e5b841d1032ca4c2607b5e939c47bf/test/integration/http2_flood_integration_test.cc#L216 to make sure it works correctly, please?

**Comment by deveshkandpal1224** [comment]
@yanavlasov - apologies for the delay, I've been away for a bit, will get back to addressing your comment towards the end of this week. Appreciate your time!

**Comment by yanavlasov** [comment]
The failure in the https://source.cloud.google.com/results/invocations/06020acc-a148-4fa2-990e-843e2d2e4971/targets/%2F%2Ftest%2Fintegration:http2_flood_integration_test/tests looks due to this PR

**Pull request closed without merging**
