### PR TITLE
access_log: add feature

### PR DESCRIPTION
**Pull request by WeavingGao**
Signed-off-by: gaoweiwen <gaoweiwen@kuaishou.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message: add %REQUEST_TX_DURATION% to the access log (#16188)
Additional Description: see issue #16188 
Risk Level: Low
Testing: Unit test
Docs Changes: Access Log doc updated
Release Notes: N/A
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by rojkov — COMMENTED** [review]
Thank you! This looks good. Could you please add a line to `docs/root/version_history/current.rst` about the added feature?

**Comment by WeavingGao** [comment]
> Thank you! This looks good. Could you please add a line to `docs/root/version_history/current.rst` about the added feature?

done

**Comment by rojkov** [comment]
The lines should be ordered alphabetically.

**Review by rojkov — APPROVED** [review]
Thank you! Looks good to me.

**Comment by WeavingGao** [comment]
Can you take a look? @yanavlasov

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
