### PR TITLE
mobile: Fixes the StatFlushIntegrationTest test

### LINKED ISSUE #24657: mobile: StatsFlushIntegrationTest failing on the flush test
`mobile/test/kotlin/integration/StatFlushIntegrationTest.kt` is failing after merging https://github.com/envoyproxy/envoy/pull/24645.  CI for https://github.com/envoyproxy/envoy/pull/24645 didn't catch it, but now CI reliably fails as well as locally via `bazelisk test  //test/kotlin/integration:stat_flush_integration_test`.

### PR DESCRIPTION
**Pull request by abeyad**
This commit makes sure the CountDownLatch is set up *before* flushStats(), but await() is called *after* flushStats(), so that we don't miss any updates from the TestStatsdServer and we don't block on a condition that never gets triggered.

Fixes #24657

Testing: `bazelisk test --config=test-android --define=signal_trace=disabled --test_output=streamed --cache_test_results=no --test_arg="-l info" test/kotlin/integration:stat_flush_integration_test --runs_per_test=100`

### CODE REVIEW

**Review by RyanTheOptimist — DISMISSED** [review]
Ooooo! Great catch!

**Review by alyssawilk — APPROVED** [review]
nice catch!

**Pull request merged**
