### PR TITLE
route: fix a timing issue and remove assertion.

### PR DESCRIPTION
**Pull request by botengyao**
Remove debug assertion and add more checks for assessing upstream_requests related to timing.

Commit Message:
Additional Description:
Risk Level: low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by alyssawilk — COMMENTED** [review]
Awesome change, thanks!  I'd runtime guard just in case, and I think it'd be better if we can have an e2e test as well if possible.
/wait

**Comment by botengyao** [comment]
> Awesome change, thanks! I'd runtime guard just in case, and I think it'd be better if we can have an e2e test as well if possible. /wait

Thanks! added runtime guard. Tried a lot of runs, but actually it is kind of hard to simulate this with e2e tests :<.

**Review by alyssawilk — DISMISSED** [review]

**Comment by alyssawilk** [comment]
LGTM modulo coverage warning, which looks plausibly real

**Comment by alyssawilk** [comment]
maybe just add a deprecated code test with the flag flipped?
/wait

**Review by alyssawilk — APPROVED** [review]

**Pull request merged**
