### PR TITLE
ci: Add scheduled garbage collection (and fix retest)

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @mum4k

**Review by mum4k — COMMENTED** [review]
LGTM, thank you for spinning this up in such a short time!

**Comment by mum4k** [comment]
I know we discussed offline that Salvo doesn't run automatically yet, but would it hurt us in any way to include its pool here?

**Comment by phlax** [comment]
added remaining pools

**Comment by phlax** [comment]
and added update to fix/update retest

NOTE: i need to land this as it requires an update to the azp token

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
