### PR TITLE
docs: updating 100-continue docs

### LINKED ISSUE #14008: When will envoy return "100-continue" to the client and write it into access log?
In our production environment, we recently noticed there are some access log record showing envoy return `RESPONSE_CODE:100` to the client. But from client side, we got confirmed they never send any `Expect: 100-continue` header. Also I have tried if I added the `-H "Expect: 100-continue"` in the `curl` command with `-v`, I can see the response including a HTTP 100 response code followed by a HTTP 200 response code (as below `curl` output). And in the access log, this request is recorded as `RESPONSE_CODE:200`. Then it is confusing what triggered envoy return and record status code 100?

```
... ...
> POST /v1/foo/bar HTTP/1.1
> Host: foo.bar.net
> User-Agent: curl/7.58.0
> Accept: */*
> Expect: 100-continue
> Authorization: Bearer <tooooo long>
> Content-Type: application/json
> Content-Length: 332
>
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 100 Continue
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* We are completely uploaded and fine
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 200 OK
< server: foo-bar-server
< date: Thu, 12 Nov 2020 01:01:54 GMT
< content-type: application/json
... ...
```

Thanks!

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: n/a (test, docs only)
Testing: new tests of 100-continue + logging
Docs Changes: docs of how 100-continue works with logging
Release Notes: n/a
Fixes #14008

### CODE REVIEW

**Comment by alyssawilk** [comment]
alternately we could just not log the 100-continue even if it's the last header.  WDYT?

**Comment by mattklein123** [comment]
> alternately we could just not log the 100-continue even if it's the last header. WDYT?

Hmm. Not sure I have a strong opinion on this one. If you pushed me on it I would say don't log it as in general I think people don't view 100-continue as a "real thing," but I definitely don't feel strongly about it.

**Review by mattklein123 — APPROVED** [review]
LGTM unless you want to not log the header at all.

**Comment by alyssawilk** [comment]
yeah, I don't have strong feelings either way - I think that never logging the 100 as the response code, but indicating if a 100 is sent would be optimal, but I don't have the cycles for it for now, so I figure documenting the current behavior is better than nothing :-P

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
