### PR TITLE
WIP: playing with sharding coverage runs

### PR DESCRIPTION
**Pull request by alyssawilk**
This results in coverage test runtime being 5x faster.

*Risk Level*: Low (if there's test flakes, send 'em my way)
*Testing*: works locally: testing on CI now.
*Docs Changes*: n/a
*Release Notes*: n/a

### CODE REVIEW

**Comment by alyssawilk** [comment]
Argh, coverage scripts run streaming.  Needs more work

**Comment by htuch** [comment]
We're working on switching to native Bazel coverage FWIW. Need to figure out why the native Bazel coverage support dies in CI.

**Comment by alyssawilk** [comment]
yeah, but 1.5 months later I'm still sitting here waiting on one hour 40+ minute coverage runs.
Testing upstream to see if turning off streamed output helps any.

**Comment by alyssawilk** [comment]
goodness gracious, over an hour for build alone.  will close this back off again and maybe reopen if you haven't bazel natived by the time I get back :-P

**Pull request closed without merging**
