### PR TITLE
delta-xds: add control_plane to DeltaDiscoveryResponse (v3 up)

### PR DESCRIPTION
**Pull request by stevenzzzz**
Commit Message: Add control_plane to DeltaDiscoveryResponse.
Additional Description:
https://github.com/envoyproxy/envoy/issues/14891

Risk Level: LOW (only adding new field)
Testing:
Docs Changes: Add control_plane to DeltaDiscoveryResponse.
Release Notes: Add control_plane to DeltaDiscoveryResponse. (code not implemented).
Platform Specific Features:

### CODE REVIEW

**Comment by stevenzzzz** [comment]
/assign htuch
PTAL!

**Comment by htuch** [comment]
@stevenzzzz what is the plan around implementation?

**Comment by stevenzzzz** [comment]
It's on me I guess. :D

**Comment by stevenzzzz** [comment]
> @stevenzzzz what is the plan around implementation?

will do in follow up PZR

**Review by lambdai — COMMENTED** [review]
Expecting your next move!

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Comment by htuch** [comment]
Not sure why verify_examples is failing on websocket test: @phlax thoughts?

I'm going to squash-merge as this is pure API.

**Comment by phlax** [comment]
> Not sure why verify_examples is failing on websocket test: @phlax thoughts?

nothing obvious - some kinda flake i guess - i havent been able to repro it on pr with merged main - the ws warnings are present in other successful runs, so they are unrelated i think

**Pull request merged**
