### PR TITLE
ci use azp to sync filter example

### PR DESCRIPTION
**Pull request by lizan**

### CODE REVIEW

**Comment by lizan** [comment]
test commit generated at https://github.com/envoyproxy/envoy-filter-example/tree/master-ci-test

**Comment by mattklein123** [comment]
Merge main?

/wait

**Review by mattklein123 — DISMISSED** [review]
Thanks! Let me know when you are ready and I can force merge and fix required checks.

**Review by mattklein123 — APPROVED** [review]

**Comment by lizan** [comment]
@mattklein123 this is ready to be merged.

**Pull request merged**
