### PR TITLE
[mobile] Prefer IPv6 over IPv4 address for iOS

### PR DESCRIPTION
**Pull request by RenjieTang**
Commit Message: Prefer IPv6 over IPv4 address for iOS
Additional Description: This matches Android behavior https://github.com/envoyproxy/envoy/blob/97bc67a06a3908821c933b437f9268886383d210/source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc#L76
Risk Level: Low
Testing: existing tests
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: iOS only

### CODE REVIEW

**Review by fredyw — COMMENTED** [review]
The change looks reasonable to me, but since this code is not in the mobile directory, let's get someone else from the Envoy Core to approve.

**Review by RyanTheOptimist — DISMISSED** [review]

**Review by fredyw — DISMISSED** [review]

**Comment by RyanTheOptimist** [comment]
Oh, I missed that this was just mobile only. We should probably have a runtime guard for this change, since it's potentially visible to other users.

**Review by RyanTheOptimist — DISMISSED** [review]
Thanks for adding the guard!

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
