### PR TITLE
api: add ProtoMessageLogging http filter proto

### PR DESCRIPTION
**Pull request by TAOXUY**
Commit Message: add the proto for the new http filter ProtoMessageLogging we are going to contribute.
Additional Description: please see the proto comments for this filter's behavior. Thanks @yanavlasov'e help reviewing our design inside google.

### CODE REVIEW

**Comment by TAOXUY** [comment]
@yanavlasov

**Comment by TAOXUY** [comment]
@dchakarwarti

**Comment by mattklein123** [comment]
Makes sense to me at a high level. Do you have a sponsor for this extension?

**Comment by TAOXUY** [comment]
> Makes sense to me at a high level. Do you have a sponsor for this extension?

@yanavlasov is our sponsor.

**Comment by yanavlasov** [comment]
LGTM, but needs proto format fix: https://dev.azure.com/cncf/envoy/_build/results?buildId=159547&view=logs&j=c95d62a5-6bb9-58f0-2a02-7575fd482a15&t=0e0c603d-b36e-5219-51ff-456f7c984195&l=97

/wait

**Comment by TAOXUY** [comment]
> LGTM, but needs proto format fix: https://dev.azure.com/cncf/envoy/_build/results?buildId=159547&view=logs&j=c95d62a5-6bb9-58f0-2a02-7575fd482a15&t=0e0c603d-b36e-5219-51ff-456f7c984195&l=97
> 
> /wait

Thanks Yan! Done.

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
