### PR TITLE
logger api refactoring: unified two methods to one to use factory context

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: logger api refactoring: unified two methods to one to use factory context
Additional Description:

Part of factory context refactoring and clean up. This patch merged two createAccessLogInstance method to one and take the `FactoryContext` as the parameter directly.

Risk Level: low. (Parameter type only update and didn't change any logic).
Testing: n/a.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
There is an another PR following closely to clean up remaining `CommonFactoryContext`. Then we can refactor the `FactoryContext` to avoid inheriting from `CommonFactoryContext`.

**Comment by wbpcode** [comment]
This patch doesn't change any behavior but may break compiling of third party forks. Sorry for that.

**Review by alyssawilk — APPROVED** [review]
SUCH GOOD CLEANUP :-)

**Comment by alyssawilk** [comment]
> There is an another PR following closely to clean up remaining `CommonFactoryContext`. Then we can refactor the `FactoryContext` to avoid inheriting from `CommonFactoryContext`.

I also love that this was my only question I was going to ask during review and you already answered it :-P

**Pull request merged**
