### PR TITLE
wasm: fix wasm callouts with xff

### PR DESCRIPTION
**Pull request by StarryVae**
Signed-off-by: wangkai19 <wangkai19@corp.netease.com>

Commit Message: fix wasm callouts with xff
Additional Description: N/A
Risk Level: low
Testing: ut
Docs Changes: N/A
Release Notes: N/A

### CODE REVIEW

**Comment by StarryVae** [comment]
issue #22201

**Comment by StarryVae** [comment]
> issue #22201

@PiotrSikora PTAL, thanks. 

i simply make a `httpCall` to `/anything` of `httpbin`, and this is the result of the original packet capture:
image

this is current result, the `X-Forwarded-For` header has been removed:
image

**Review by PiotrSikora — APPROVED** [review]
LGTM, cc @mpwarres for another pair of eyes.

**Comment by StarryVae** [comment]
ping @mpwarres

**Review by mpwarres — APPROVED** [review]
Sorry, lost this in the shuffle. LGTM, thanks!

**Review by kyessenov — APPROVED** [review]
Reviewed by extension maintainers.

**Pull request merged**
