### PR TITLE
flip RUNTIME_GUARD 'envoy.reloadable_features.thrift_connection_draining' to true

### PR DESCRIPTION
**Pull request by xianggao001**
Commit Message: flip RUNTIME_GUARD 'envoy.reloadable_features.thrift_connection_draining' to true
Additional Description: Pinterest introduced this runtime_guard before. We've done tests in house and they were looking good, so we feel it is safe now to flip it to default true. We plan to remove this runtime_guard and make the feature default in half a year. 
Risk Level: low
Testing: done in house
Docs Changes: none
Release Notes: none
Platform Specific Features:  none
[Optional Runtime guard:] envoy.reloadable_features.thrift_connection_draining
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by zuercher — APPROVED** [review]
Test failure looks like  a flake. Re-running again now.

**Comment by zuercher** [comment]
Sorry, I've been out sick. I think this needs a release note to indicate that the feature flag got flipped to true in changelogs/current.yaml and then we can merge it.

**Comment by xianggao001** [comment]
@zuercher hope you recover soon! I read changelogs/current.yaml before and it seems say only creating or deleting a flag needs a release note. But if you think it is necessary I'll do it of course.

**Comment by zuercher** [comment]
I think the common pattern is for new runtime flags to be enabled by default, so we have a changelog entry that notes the behavior change and how to revert to the old behavior. Here it's been defaulted off for two versions, now we're turning it on by default which is a behavior change, but can be reverted.

**Comment by xianggao001** [comment]
@zuercher  I'm a first time contributor, I wonder if you need to unblock me for above tests?  ` First-time contributors need a maintainer to approve running workflows.`     Thanks!

**Comment by xianggao001** [comment]
is this normal that the CI/CD failed for 10+ times for me? .....

**Comment by xianggao001** [comment]
@zuercher finally all tests passed!

**Comment by xianggao001** [comment]
the tests were all passed before, not sure why 3 of them are "expected" now...

**Comment by xianggao001** [comment]
@lizan Hi, I rerun the CI tests and it needs approval from reviewers.

**Review by lizan — APPROVED** [review]

**Pull request merged**
