### PR TITLE
[WIP] filter manager: fix bug with double continue on data after `inject*DataToFilterChain()` call

### PR DESCRIPTION
**Pull request by nareddyt**
## DO NOT SUBMIT

Still broken. I commented out my attempted fix for now.

## DO NOT SUBMIT

Commit Message: 
filter manager: fix bug with double continue on data after `inject*DataToFilterChain()` call

Additional Description: 

With the original code, the `EndStreamAtTrailersRealisticFilters` fails with `upstream_reset_before_response_started{connection_termination}`. This failure occurs when a filter:

1) Stops iteration of body and trailers.
2) Calls `injectDecodedDataToFilterChain()` to inject body to the next filter (implicitly continuing iteration of the body).
3) Calls `continueDecoding()` to continue iteration of the trailers.

After further debugging, I found the filter manager is calling `decodeData` on the following filter twice, once in step 2 and again in step 3. This leads to data duplication and messes up internal filter state. Same bug exists on encoder path via `injectEncodedDataToFilterChain()`.

Fix is to keep track of the implicit continuation of data in step 2 and prevent double continuation in step 3.

Risk Level: 
low, only affects callers of `injectDecodedDataToFilterChain()` and `injectEncodedDataToFilterChain()`

Testing: 
- New integration test passes
- All pre-existing tests that use these `inject*DataToFilterChain()` calls pass

Docs Changes:
None, this is an internal bug fix that conforms to the pre-existing docs

Release Notes: 
None

Platform Specific Features:
None

Ref: https://github.com/envoyproxy/envoy/issues/22064

### CODE REVIEW

**Comment by nareddyt** [comment]
Test failures:

```
[ RUN      ] StreamingProtocols/StreamingIntegrationTest.PostAndProcessStreamedRequestBody/IPv4_EnvoyGrpc_NoDeferredProcessing
test/extensions/filters/http/ext_proc/streaming_integration_test.cc:287: Failure
Value of: client_response_->waitForEndStream()
  Actual: false (Timed out waiting for end stream
)
Expected: true
Stack trace:
  0xa2d4e9: Envoy::Extensions::HttpFilters::ExternalProcessing::StreamingIntegrationTest_PostAndProcessStreamedRequestBody_Test::TestBody()
  0x1c5761c: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x1c574dd: testing::Test::Run()
  0x1c58737: testing::TestInfo::Run()
... Google Test internal frames ...

```

```
[ RUN      ] Protocols/FileSystemBufferIntegrationTest.RequestAndResponseWithGiantBodyBuffer/IPv4_HttpDownstream_Http2UpstreamNghttp2NoDeferredProcessing
[2022-07-07 21:08:52.003][18][critical][assert] [test/integration/http_integration.cc:551] assert failure: result. Details: Timed out waiting for end of stream.
[2022-07-07 21:08:52.003][18][critical][backtrace] [./source/server/backtrace.h:104] Caught Aborted, suspect faulting address 0xfffe00000012
[2022-07-07 21:08:52.003][18][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2022-07-07 21:08:52.003][18][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: 0/1.23.0-dev/test/RELEASE/BoringSSL
[2022-07-07 21:08:52.003][18][critical][backtrace] [./source/server/backtrace.h:96] #0: __restore_rt [0x7fd5f563b980]
[2022-07-07 21:08:52.007][18][critical][backtrace] [./source/server/backtrace.h:96] #1: Envoy::HttpIntegrationTest::sendRequestAndWaitForResponse() [0xa6b80b]
[2022-07-07 21:08:52.010][18][critical][backtrace] [./source/server/backtrace.h:96] #2: Envoy::HttpIntegrationTest::testRouterRequestAndResponseWithBody() [0xa6cdb8]
[2022-07-07 21:08:52.013][18][critical][backtrace] [./source/server/backtrace.h:96] #3: Envoy::(anonymous namespace)::FileSystemBufferIntegrationTest_RequestAndResponseWithGiantBodyBuffer_Test::TestBody() [0xa11005]
[2022-07-07 21:08:52.016][18][critical][backtrace] [./source/server/backtrace.h:96] #4: testing::internal::HandleExceptionsInMethodIfSupported<>() [0x1bf363c]
[2022-07-07 21:08:52.020][18][critical][backtrace] [./source/server/backtrace.h:96] #5: testing::Test::Run() [0x1bf34fd]
[2022-07-07 21:08:52.023][18][critical][backtrace] [./source/server/backtrace.h:96] #6: testing::TestInfo::Run() [0x1bf4757]
[2022-07-07 21:08:52.026][18][critical][backtrace] [./source/server/backtrace.h:96] #7: testing::TestSuite::Run() [0x1bf5519]
[2022-07-07 21:08:52.029][18][critical][backtrace] [./source/server/backtrace.h:96] #8: testing::internal::UnitTestImpl::RunAllTests() [0x1c02a4f]
[2022-07-07 21:08:52.033][18][critical][backtrace] [./source/server/backtrace.h:96] #9: testing::internal::HandleExceptionsInMethodIfSupported<>() [0x1c024bc]
[2022-07-07 21:08:52.036][18][critical][backtrace] [./source/server/backtrace.h:96] #10: testing::UnitTest::Run() [0x1c0233f]
[2022-07-07 21:08:52.039][18][critical][backtrace] [./source/server/backtrace.h:96] #11: Envoy::TestRunner::RunTests() [0x14c02d1]
[2022-07-07 21:08:52.043][18][critical][backtrace] [./source/server/backtrace.h:96] #12: main [0x14bece2]
[2022-07-07 21:08:52.043][18][critical][backtrace] [./source/server/backtrace.h:96] #13: __libc_start_main [0x7fd5f5259c87]
```

```
[ RUN      ] UpstreamProtocols/ProtocolIntegrationTest.ContinueHeadersOnlyInjectBodyFilter/IPv4_Http2Downstream_Http3UpstreamNghttp2NoDeferredProcessing
test/integration/protocol_integration_test.cc:323: Failure
Value of: response->waitForEndStream()
  Actual: false (Timed out waiting for end stream
)
Expected: true
Stack trace:
  0xa68760: Envoy::ProtocolIntegrationTest_ContinueHeadersOnlyInjectBodyFilter_Test::TestBody()
  0x1cbe82c: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x1cbe6ed: testing::Test::Run()
  0x1cbf947: testing::TestInfo::Run()
... Google Test internal frames ...
```

```
[ RUN      ] UpstreamProtocols/ProtocolIntegrationTest.StopIterationHeadersInjectBodyFilter/IPv6_Http2Downstream_Http3UpstreamNghttp2NoDeferredProcessing
test/integration/protocol_integration_test.cc:349: Failure
Value of: response->waitForEndStream()
  Actual: false (Timed out waiting for end stream
)
Expected: true
Stack trace:
  0xa691f7: Envoy::ProtocolIntegrationTest_StopIterationHeadersInjectBodyFilter_Test::TestBody()
  0x1cbe82c: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x1cbe6ed: testing::Test::Run()
  0x1cbf947: testing::TestInfo::Run()
... Google Test internal frames ...
```

**Comment by wrowe** [comment]
Please mark as draft, subject [WIP] for the time being?

/wait

**Comment by wrowe** [comment]
/assign @alyssawilk 

Could you take a look please?

**Comment by nareddyt** [comment]
Hi @alyssawilk , can you help with this when you have a chance? Or is there another expert for the filter manager you'd recommend me asking? Thanks

**Comment by nareddyt** [comment]
Thanks @alyssawilk. There is currently a bug in the filter manager, where it continues the HTTP data twice on the same filter when `injectEncodedDataToFilterChain()`/`injectDecodedDataToFilterChain()` are called with `continueEncoding()`/`continueDecoding()`. 

This bug is described in https://github.com/envoyproxy/envoy/issues/22064. This PR adds a test case to reproduce the problem: Run `test/integration/http_async_inject_body_test.cc` and the test case `EndStreamAtTrailersRealisticFilters` fails.

In https://github.com/envoyproxy/envoy/issues/22064, I proposed a new filter API so that filters can overcome the double-continue on data. However, there may be a way to fix this bug in the filter manager itself without introducing a new filter API. I need help deciding on this - I don't have enough experience with the filter manager's handling of data to understand why the double continue occurs. I tried introducing a hacky boolean tracking variable in this PR to fix it, but it breaks a few other tests, so I reverted that portion.

Can you take a quick look at the problem and see if it warrants the new filter API I proposed? Or do you think there is a way to fix this in filter manager directly?

**Comment by alyssawilk** [comment]
Ok, so I agree there's a bug, and I agree with Matt that adding a new API is not the right solution.  I think we need a real fix which is going to involve someone spelunking in the filter chain code to actually fix the underlying issue without breaking anything.  If you want to give that a shot I'd suggest spending some time with GDB and the working tests, and seeing if you can sort it out.  If not you could ask @krajshiva if it'd fit on his team's slate at some point because it's a complicated area of code and I don't think anyone on the maintainers team is going to be able to suggest a fix without spending a few hours poking around the code themselves and as it's tagged help wanted, it indicates no one has the cycles to go and do that right now.

**Comment by nareddyt** [comment]
(no stalebot)

**Pull request closed without merging**
