### PR TITLE
Docs updates and cleanups

### PR DESCRIPTION
**Pull request by phlax**
- Update grpc-bridge documentation
    - Fixes: #12231

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: Docs updates and cleanups
Additional Description:
Risk Level: low
Testing: see https://github.com/phlax/envoy-examples
Docs Changes: yes
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]  #12231
[Optional Deprecated:]

### CODE REVIEW

**Comment by zuercher** [comment]
Is this ready for review?

**Comment by phlax** [comment]
not quite - should be ready in a day or 2

**Comment by zuercher** [comment]
Thanks. That all looks good to me. When you're ready, hit the "ready for review" button and the rest of the tests will run and we can get this approved.

**Comment by phlax** [comment]
@zuercher apologies for the delay - there were some things i had wanted to finish off

**Comment by zuercher** [comment]
You'll need to fix the DCO, and there's a format error:
```
check_format...
ERROR: From ./docs/root/start/sandboxes/grpc_bridge.rst
ERROR: ./docs/root/start/sandboxes/grpc_bridge.rst:98: over-enthusiastic spaces
ERROR: ./docs/root/start/sandboxes/grpc_bridge.rst:100: over-enthusiastic spaces
ERROR: check format failed. run 'tools/code_format/check_format.py fix'
```

Otherwise, I think it looks good.

**Pull request merged**
