### PR TITLE
[balsa] Call ParserCallback::OnStatus() with reason-phrase.

### PR DESCRIPTION
**Pull request by bencebeky**
When receiving 200 OK, call OnStatus() with "OK", not with "200". This is for consistency with legacy http-parser.

See RFC9112 Section 4 for status line and reason-phrase.

Also parametrize
//test/extensions/http/header_formatters/preserve_case:preserve_case_formatter_reason_phrase_integration_test,
which fails for BalsaParser without this change.

Tracking issue: #21245

Signed-off-by: Bence Béky <bnc@google.com>

Commit Message: Call ParserCallback::OnStatus() with reason-phrase.
Additional Description:
Risk Level: low, changed code protected by existing default-false runtime flag.
Testing: //test/extensions/http/header_formatters/preserve_case:preserve_case_formatter_reason_phrase_integration_test
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a
Runtime guard: envoy.reloadable_features.http1_use_balsa_parser

### CODE REVIEW

**Review by diannahu — APPROVED** [review]
Nice!

**Comment by bencebeky** [comment]
Kevin, PTAL.
Dianna, thank for the review.

/assign @KBaichoo

**Review by KBaichoo — APPROVED** [review]

**Pull request merged**
