### PR TITLE
docs: Cleanups for 1.18.0 release

### LINKED ISSUE #14995: Docs are showing an empty dictionary in places
### description

seems like there is an issue with protodoc that is causing an empty dictionarry to be added to some of the generated docs

for example:

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/filter/thrift/router/v2alpha1/router.proto#config-filter-thrift-router-v2alpha1-router

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: docs: Cleanups for 1.18.0 release
Additional Description:

- picks fixes from #15766 
- re-removes the admin section from the demo config and fixes docs
- fixes some more literal include lines
- prevent empty json dicts (see #14995)

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #14995
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
re admin section, the reasoning for not including the admin section in the default config is that it exposes the server and i felt it was better to make adding the admin section explicit - so i added an admin section in getting started to compensate

i mistakenly approved #14833 that added this back when the better fix would have been to fix the docs

there is still the admin section in the actual docker image which we may want to follow up and remove

**Comment by phlax** [comment]
docs rendered here https://storage.googleapis.com/envoy-pr/15983/docs/index.html

**Comment by phlax** [comment]
@htuch ive added a fix to prevent the empty `json` dicts for extensions that dont have config

not sure if this is the correct fix - but its certainly better than what it does currently (at least where i have checked)

**Comment by phlax** [comment]
cc @mattklein123

**Review by mattklein123 — APPROVED** [review]
Nice, thanks!

**Pull request merged**
