### PR TITLE
Sets an oghttp2 config option to allow different "host" and ":authority" values

### PR DESCRIPTION
**Pull request by birenroy**
This resolves a codec difference between nghttp2 and oghttp2.

Repro test case in multiplexed_integration_test.cc originally by @yanavlasov.

Commit Message: Sets an oghttp2 config option to allow different "host" and ":authority" values
Additional Description:
Risk Level: low
Testing: added integration test coverage for the codec difference
Docs Changes:
Release Notes:
Platform Specific Features:

### CODE REVIEW

**Review by diannahu — APPROVED** [review]
Nice!

**Review by yanavlasov — APPROVED** [review]

**Comment by yanavlasov** [comment]
@birenroy the failure in the compile time options does not seem related to this PR. https://source.cloud.google.com/results/invocations/a881aa18-7dc9-4fac-b2dc-8ce62636766f/log

Maybe it needs main merge?

/wait

**Pull request merged**
