### PR TITLE
bazel: remove pch dep when disabled

### PR DESCRIPTION
**Pull request by keith**
This should break some unnecessary rebuilding in the case you don't actually use the pch feature.

### CODE REVIEW

**Comment by phlax** [comment]
small diff required to get it to work:

```diff
diff --git a/bazel/envoy_library.bzl b/bazel/envoy_library.bzl
index 46bd80293b..37f2cef18b 100644
--- a/bazel/envoy_library.bzl
+++ b/bazel/envoy_library.bzl
@@ -129,12 +129,11 @@ def envoy_cc_library(
         deps = deps + [envoy_external_dep_path(dep) for dep in external_deps] + [
             repository + "//envoy/common:base_includes",
             repository + "//source/common/common:fmt_lib",
-            envoy_pch_deps(repository, "//source/common/common:common_pch"),
             envoy_external_dep_path("abseil_flat_hash_map"),
             envoy_external_dep_path("abseil_flat_hash_set"),
             envoy_external_dep_path("abseil_strings"),
             envoy_external_dep_path("fmtlib"),
-        ],
+        ] + envoy_pch_deps(repository, "//source/common/common:common_pch"),
         alwayslink = alwayslink,
         linkstatic = envoy_linkstatic(),
         strip_include_prefix = strip_include_prefix,
diff --git a/source/common/common/BUILD b/source/common/common/BUILD
index 6f0f7a885e..75ca5d230f 100644
--- a/source/common/common/BUILD
+++ b/source/common/common/BUILD
@@ -221,6 +221,9 @@ envoy_cc_library(
     name = "base_logger_lib",
     srcs = ["base_logger.cc"],
     hdrs = ["base_logger.h"],
+    external_deps = [
+        "spdlog",
+    ]
 )
 
```

Using a test lib as a guide to the change:

before:

```console
$ bazel cquery 'deps(//test/test_common:global_lib)'  | wc -l                                                                                  
...                                                                                                                      
10447
```

after:

```console
$ bazel cquery 'deps(//test/test_common:global_lib)'  | wc -l                                                                                  
...                                                                                                                      
553
```

**Comment by phlax** [comment]
```diff
diff --git a/test/tools/schema_validator/BUILD b/test/tools/schema_validator/BUILD
index 6e911ac1af..bb5ec7785d 100644
--- a/test/tools/schema_validator/BUILD
+++ b/test/tools/schema_validator/BUILD
@@ -34,6 +34,7 @@ envoy_cc_test_library(
         "//source/common/stats:isolated_store_lib",
         "//source/common/version:version_lib",
         "//test/test_common:utility_lib",
+        "//test:test_pch",
         "@envoy_api//envoy/config/bootstrap/v3:pkg_cc_proto",
         "@envoy_api//envoy/config/route/v3:pkg_cc_proto",
         "@envoy_api//envoy/service/discovery/v3:pkg_cc_proto",
```

**Comment by keith** [comment]
we shouldn't have to add the pch directly to any target, if we do it might be missing a dep on something ?

**Comment by phlax** [comment]
i added spdlog which i think is what is failing now

probs schema_validator needs something - maybe not what i added

**Comment by yanavlasov** [comment]
Looks like some tests lost dependencies on core extensions.

/wait

**Comment by phlax** [comment]
i think this is probably closer to what we want:

```diff
diff --git a/test/tools/schema_validator/BUILD b/test/tools/schema_validator/BUILD
index 6e911ac1af..643fb12b79 100644
--- a/test/tools/schema_validator/BUILD
+++ b/test/tools/schema_validator/BUILD
@@ -35,7 +35,10 @@ envoy_cc_test_library(
         "//source/common/version:version_lib",
         "//test/test_common:utility_lib",
         "@envoy_api//envoy/config/bootstrap/v3:pkg_cc_proto",
+        "@envoy_api//envoy/config/cluster/v3:pkg_cc_proto",
+        "@envoy_api//envoy/config/core/v3:pkg_cc_proto",
         "@envoy_api//envoy/config/route/v3:pkg_cc_proto",
+        "@envoy_api//envoy/extensions/filters/network/http_connection_manager/v3:pkg_cc_proto",
         "@envoy_api//envoy/service/discovery/v3:pkg_cc_proto",
     ],
 )
```

**Review by phlax — APPROVED** [review]
lgtm, thanks @keith ... pending CI ...

**Pull request merged**
