### PR TITLE
quic: enable certificate compression/decompression

### PR DESCRIPTION
**Pull request by ggreenway**
QUIC servers are limited in how much data they can send to clients in the ServerHello before the client is validated (see https://www.rfc-editor.org/rfc/rfc9000.html#section-8). If too much data needs to be sent, an extra network round trip is needed.

One way to reduce the size of the ServerHello data is to compress the certificates. This can, in some situations, remove an extra round trip.

Risk Level: Low
Testing: Added unit and integration tests
Docs Changes:
Release Notes: Added
Platform Specific Features:
Runtime guard: `envoy.reloadable_features.quic_support_certificate_compression`

### CODE REVIEW

**Comment by ggreenway** [comment]
@RyanTheOptimist this PR isn't ready for full review yet, but I wanted to get an early opinion on if there are any issues with how I'm implementing this, in terms of if this is a reasonable way to interact with the SSL_CTX that QUICHE lets us access.

Assuming this looks ok, I'll add config knob, tests, cleanup code, etc before further review.

**Comment by RyanTheOptimist** [comment]
> @RyanTheOptimist this PR isn't ready for full review yet, but I wanted to get an early opinion on if there are any issues with how I'm implementing this, in terms of if this is a reasonable way to interact with the SSL_CTX that QUICHE lets us access.
> 
> Assuming this looks ok, I'll add config knob, tests, cleanup code, etc before further review.

Yeah, I think this looks like a solid approach. Thanks for doing this! I ran this past one of my colleagues who pointed out that Chrome only supports brotli for cert compression, not zlib. So we might want to add support for brotli too?

**Comment by ggreenway** [comment]
As it turns out, the clients I care about only support zlib for now. Once this is added, it should be straightforward to also add brotli. 

I think it's probably sufficient to just add a single config knob for "support cert compression" and let the two sides negotiate it (which BoringSSL does for us). Do you think we need to add config support for supporting one algorithm but not the other?

**Comment by RyanTheOptimist** [comment]
> As it turns out, the clients I care about only support zlib for now. Once this is added, it should be straightforward to also add brotli.

Makes sense.

> I think it's probably sufficient to just add a single config knob for "support cert compression" and let the two sides negotiate it (which BoringSSL does for us). Do you think we need to add config support for supporting one algorithm but not the other?

I think that sounds reasonable, but I have some vague recollection about brotli not being supported in every Envoy build configuration. But that being said, we can just #ifdef the brotli variant out and that's fine. Honestly, I'm not sure if we need a config knob here at all. I kinda wonder if we should just always do this (or maybe have a knob to opt-out, if we really think we need some config for this).

**Comment by ggreenway** [comment]
> Honestly, I'm not sure if we need a config knob here at all. I kinda wonder if we should just always do this (or maybe have a knob to opt-out, if we really think we need some config for this).

Sounds good to me. I'll add a runtime flag to disable in case of issues.

**Comment by ggreenway** [comment]
I did a speedtest, and depending on the host run on, got between 30us and 70us per compression. I think that's fast enough (at least for now) to not bother with a compression cache. The rest of the TLS handshake should take quite a bit longer.

**Review by RyanTheOptimist — APPROVED** [review]
Sweet! Thanks for doing this!

**Comment by ggreenway** [comment]
/wait

One more leak, and coverage is too low

**Comment by ggreenway** [comment]
Coverage is lower because I don't know any way to trigger the ENVOY_BUG cases: https://storage.googleapis.com/envoy-pr/82efd1a/coverage/source/common/quic/cert_compression.cc.gcov.html

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
