### PR TITLE
Changed Profile Action to have a per-process limit rather than per thread

### PR DESCRIPTION
**Pull request by KBaichoo**
Signed-off-by: Kevin Baichoo <kbaichoo@google.com>

Commit Message: Simplified Profile Action to have a per-process limit rather than a per thread limit which simplifies disk-filling concerns.
Additional Description: We want to prevent the profiler from filling the disk, and using a per thread limit creates more complexity and profiles (i.e. for the "global" limit would be `#threads * limit per thread` vs `limit per process`. The former is harder to reason about.
Risk Level: low
Testing: unit tests
Docs Changes: N/A
Release Notes: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by htuch** [comment]
Can you add some motivation for this to the commit message? API changes LGTM, since this is v3alpha.

**Review by antoniovicente — APPROVED** [review]
Thanks for the fix!

**Comment by KBaichoo** [comment]
PTAL @envoyproxy/senior-maintainers

**Comment by htuch** [comment]
@snowp can you assign a non-Googler senior maintainer? Thanks.

**Review by ggreenway — APPROVED** [review]

**Pull request merged**
