### PR TITLE
redis-proxy: support echo command

### LINKED ISSUE #31459: [Redis] Add support for ECHO command
https://redis.io/commands/echo/

### PR DESCRIPTION
**Pull request by danielnorberg**
Commit Message: redis proxy: add support for echo command
Additional Description: 
Risk Level: Low
Testing: Unit test added
Docs Changes: Added
Release Notes: Added
Platform Specific Features: None
Fixes #31459

### CODE REVIEW

**Comment by ravenblackx** [comment]
Please do the [DCO thing](https://sourcegraph.com/github.com/envoyproxy/envoy/-/commit/d72eaaf6d1905f7d478ab80cc7163684fc271fd9) (which will require a force-push), and fix the presubmit format errors.

**Comment by danielnorberg** [comment]
It seems that Redis returns a bulk string for `ECHO`, whereas this PR responds with a simple string.

PR behavior:
```
ECHO hello
+hello
```

Redis behavior:
```
ECHO hello
$5
hello
```

Also, Redis does not require `AUTH` before responding to `ECHO`.

I'll try to reconcile the PR behavior with Redis.

**Comment by danielnorberg** [comment]
Just changing the response type to `BulkString` seems to do the trick.

**Comment by danielnorberg** [comment]
Force pushed again to retry CI flake due to failing bazel download.

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
