### PR TITLE
mobile: Add an RTDS integration test with dfp_mixed_scheme

### PR DESCRIPTION
**Pull request by abeyad**
As part of this change, a new test Runtime was added: `TestScopedStaticReloadableFeaturesRuntime`.
It should be used in build environments, like Envoy Mobile, where the admin layer is not available (which
is required by TestScopedRuntime).

### CODE REVIEW

**Comment by phlax** [comment]
ah - conflict - i saw the pr failing request and was worried - i can add some fail handling for that - but i think all good

**Review by RyanTheOptimist — DISMISSED** [review]

**Review by RyanTheOptimist — DISMISSED** [review]

**Comment by RyanTheOptimist** [comment]
Looks like a real test failure?

https://github.com/envoyproxy/envoy/actions/runs/7201881774/job/19618907200

**Comment by abeyad** [comment]
> Looks like a real test failure?
> 
> https://github.com/envoyproxy/envoy/actions/runs/7201881774/job/19618907200

yep it is, I was debugging this and found another issue that needs fixing.

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
