### PR TITLE
docs: move example configs to load_assignment

### PR DESCRIPTION
**Pull request by derekargueta**
Move example CDS configs from `hosts` to `load_assignment`

Description: 
Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A

Signed-off-by: Derek Argueta <dereka@pinterest.com>

### CODE REVIEW

**Comment by derekargueta** [comment]
relates to #4618 cc @dio

**Comment by derekargueta** [comment]
hmm will take a look at the test failure tomorrow morning, wasn't sure where the tests were for the example configs

**Comment by moderation** [comment]
@derekargueta As I mentioned at https://github.com/envoyproxy/envoy/pull/6346#issuecomment-475365285 the template YAML files need a bunch of changes to move from v1 to v2 and not just load_assignment. I'm happy to take a stab at fully re-mediating if you like.

**Comment by dio** [comment]
Thanks! Please ping me when it is ready.

**Comment by derekargueta** [comment]
@moderation ah didn't see that thread. Yeah happy to let you finish that out.

**Pull request closed without merging**
