### PR TITLE
doc: update doc on original destination lb

### LINKED ISSUE #11664: How is original destination lb being supported by v3?
In v2 API, to use original destination lb, one needs to set both:
cluster.lb_policy -> ORIGINAL_DST_LB
cluster.type -> ORIGINAL_DST

Now in v3 API, ORIGINAL_DST type is still available, but ORIGINAL_DST_LB is not in lb_policy anymore.

Is this feature still supported in v3? If so, how should one configure?

BTW, the doc says: "Original destination service discovery must be used with the original destination load balancer. "
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery#arch-overview-service-discovery-types-original-destination

### PR DESCRIPTION
**Pull request by fuqianggao**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes #11664 
/cc @junr03

### CODE REVIEW

**Comment by junr03** [comment]
@fuqianggao do you mind merging master?

**Comment by fuqianggao** [comment]
> @fuqianggao do you mind merging master?

Done.

**Comment by mattklein123** [comment]
@fuqianggao sorry for some reason CircleCI is not running the docs job and my close/reopen trick did not work. Can you open a fresh PR and hopefully that will work? Sorry for the trouble.

**Comment by fuqianggao** [comment]
> @fuqianggao sorry for some reason CircleCI is not running the docs job and my close/reopen trick did not work. Can you open a fresh PR and hopefully that will work? Sorry for the trouble.

Sure. Will close this one and create a new one.

**Pull request closed without merging**
