### PR TITLE
upstream: refactor the ClusterFactoryContext to return ServerFactoryContext ref

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: upstream: refactor the ClusterFactoryContext to return ServerFactoryContext ref
Additional Description: 

First PR of #26476. This PR refactor the `ClusterFactoryContext`. Now, the `ClusterFactoryContext` will return a `ServerFactoryContext` reference and all server-wide resource (except the cluster manager and some others unpopulated field, see #26653) access should be handled by this reference.

Risk Level: mid. Core upstream code refactor.
Testing: unit/integration.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

**Comment by wbpcode** [comment]
/wait

I will review my change again to ensure all changes are safe.

**Comment by yanavlasov** [comment]
Thanks for this change. Waiting for build failures to be resolved.

/wait

**Comment by alyssawilk** [comment]
Code coverage for source/server/config_validation is lower than limit of 83.8 (83.7)
 looks legit?

also can you walk the code and make sure we're not changing the stats scope used anywhere?  

/wait

**Comment by wbpcode** [comment]
> also can you walk the code and make sure we're not changing the stats scope used anywhere?

This pr only changed the `ClusterFactoryContext` and only root stats scope is used for the cluster creation.

**Comment by RyanTheOptimist** [comment]
> image image
> 
> The coverage rate decreasion is because the statistical issue. This PR reduced one line code and changed the computing result.

Would it be possible to add an additional test which improves coverage of some currently un-covered lines?

**Comment by wbpcode** [comment]
> > image image
> > The coverage rate decreasion is because the statistical issue. This PR reduced one line code and changed the computing result.
> 
> Would it be possible to add an additional test which improves coverage of some currently un-covered lines?

I will check it this week.

**Comment by tyxia** [comment]
Hi @wbpcode  I was told that you are refactoring factory context related stuff.

I am wondering if issue#26845 is in the scope of your refactoring work or if you have any insights on that issue? 

Thanks!

**Comment by wbpcode** [comment]
it could be. But in fact, it's related to common xds manager. We need refactor the xds subscriptions and route configuration loading.

**Comment by wbpcode** [comment]
See https://github.com/envoyproxy/envoy/issues/24773

and

**Comment by wbpcode** [comment]
friendly ping @yanavlasov

**Review by yanavlasov — APPROVED** [review]

**Comment by wbpcode** [comment]
I will merge this PR. I have done a check again and there should no anything be broken. (And it's long time untill next release, we have enough time to ensure the correctness.

**Pull request merged**
