### PR TITLE
build: Fix name conflict in files generated from semantic_version.proto

### PR DESCRIPTION
**Pull request by zyfjeff**
Signed-off-by: tianqian.zyf <tianqian.zyf@alibaba-inc.com>

Description: Fix name conflict in files generated from semantic_version.proto
Risk Level: low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
[Optional Fixes #Issue] #9630

### CODE REVIEW

**Comment by yanavlasov** [comment]
@zyfjeff can you clarify what is causing conflicts and where?

**Comment by htuch** [comment]
Yeah, we can't just change field names, this is a wire breaking change (for JSON/YAML). Since the SemVer proto is so new, it might be OK, but needs strong motivation.

**Comment by zyfjeff** [comment]
> @zyfjeff can you clarify what is causing conflicts and where?

This issue #9630  describes the name of the conflict and some related details

**Comment by zyfjeff** [comment]
@htuch 
> Yeah, we can't just change field names, this is a wire breaking change (for JSON/YAML). Since the SemVer proto is so new, it might be OK, but needs strong motivation.

Agree with you, this [comment](https://github.com/protocolbuffers/protobuf/issues/4654#issuecomment-391457742) describes some of the motivations for my change, if not enough, I can choose other ways to solve the problem, such as undefine the name of the conflict in advance when generating semantic_version.pb.cc

**Comment by lizan** [comment]
@htuch I think we should get this in before SemVer is in any stable version. https://github.com/protocolbuffers/protobuf/issues/4654#issuecomment-391457742 describes the motivation of this PR: having field name conflicts with system library is PITA. Especially it's glibc that cannot easily workaround.

**Comment by htuch** [comment]
Ack, let's do it then, thanks for the clarification @zyfjeff and @lizan.

**Pull request merged**
