### PR TITLE
ci/fuzz: Ensure fuzz check is included in code check

### PR DESCRIPTION
**Pull request by phlax**
address one of the issues raised here https://github.com/envoyproxy/envoy/pull/27610#issuecomment-1561577553

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @vehre-x41 this now fails - not 100% clear whether an issue with the tool or whether the count is now wrong - ill debug locally to figure

either way, i think what this tool really needs to be useful is not just a count, but a comparison, so the error can tell the user what is missing

**Comment by phlax** [comment]
> not 100% clear whether an issue with the tool or whether the count is now wrong

turns out, both

**Comment by phlax** [comment]
afaict `envoy.filters.network.tcp_proxy` is what it detects as missing

which is commented out

the original algo may have been picking up an extra match - not sure - but i think we just need to add `--extensions_fuzzed_not_counted` flag pending a better solution that dumps the actual problem

**Comment by phlax** [comment]
> either way, i think what this tool really needs to be useful is not just a count, but a comparison, so the error can tell the user what is missing

#27617

**Review by mattklein123 — APPROVED** [review]

**Comment by phlax** [comment]
apologies @mattklein123 i pushed just as you approved

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
