### PR TITLE
[http codec] case-insensetive transfer-encoding checks

### LINKED ISSUE #10041: Transfer-Encoding value is case-insensitive by RFC.
Envoy [rejects](https://github.com/envoyproxy/envoy/blob/acdc6c7658638891253b2a49e74535de11984a72/source/common/http/http1/codec_impl.cc#L582-L592) requests having "Transfer-Encoding: **C**hunked" with `unsupported transfer encoding` error.

Per [RFC7230: Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing](https://tools.ietf.org/html/rfc7230#section-4) transfer-coding names are case-insensitive:
>All transfer-coding names are case-insensitive and ought to be
   registered within the HTTP Transfer Coding registry, as defined in
   Section 8.4.  They are used in the TE (Section 4.3) and
   Transfer-Encoding (Section 3.3.1) header 

*Expected behavior*: all transfer-encoding comparisons are case-insensitive.
 
*Logs*:
```
D0213 02:23:06.031513 33976 http [external/envoy/source/common/http/conn_manager_impl.cc:278] [C516843051] dispatch error: http/1.1 protocol error: unsupported transfer encoding
```

### PR DESCRIPTION
**Pull request by veshij**
Signed-off-by: Oleg Guba <oleg@dropbox.com>
Description: Per RFC7230: Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing transfer-coding names are case-insensitive:

>All transfer-coding names are case-insensitive and ought to be
registered within the HTTP Transfer Coding registry, as defined in
Section 8.4. They are used in the TE (Section 4.3) and
Transfer-Encoding (Section 3.3.1) header

Risk Level: Low
Testing: unit test
Docs Changes: None
Release Notes: None
Fixes #10041

### CODE REVIEW

**Comment by veshij** [comment]
> Can you merge master? caseCompare just got removed in place of an absl utility function. Otherwise LGTM. Thank you!
> 
> /wait

done

**Comment by andrijaperovic** [comment]
@mattklein123 do you know if this fix will be merged into `release-1.6` branch? I see the commit is only on `release-1.5`.

**Comment by howardjohn** [comment]
@andrijaperovic `release-1.6` is an Istio thing - not envoy. But it is, see https://github.com/istio/envoy/commit/7a8e9da60b

**Comment by andrijaperovic** [comment]
@howardjohn I see tags `1.7.0-alpha.2` for the commit you shared, also it is present on `master`. Should I expect to see a `1.6.x` tag as well?

**Comment by howardjohn** [comment]
We didn't tag istio/envoy until recently. You can look at the git logs though

**Pull request merged**
