### PR TITLE
ci: support custom TEST_TMPDIR and clang-format

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long Dai <long0dai@foxmail.com>

Commit Message:

Fix hardcode val for TEST_TMPDIR and llvm.

Additional Description:
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by jmarantz** [comment]
Drive-by comment: what's broken about the current support for TEST_TMPDIR and clang-format?

**Comment by rgs1** [comment]
> Drive-by comment: what's broken about the current support for TEST_TMPDIR and clang-format?

I think it's probably two things:

a) being able to set TEST_TMPDIR externally (at call time maybe)
```
export TEST_TMPDIR="${TEST_TMPDIR:-BUILD_DIR/tmp}"
```

b) This ensures LLVM's binaries are actually in $PATh
```
export LLVM_ROOT="${LLVM_ROOT:-/opt/llvm}"
export PATH=${LLVM_ROOT}/bin:${PATH}
```

**Review by rgs1 — DISMISSED** [review]
This looks reasonable to me, once CI passes.

**Comment by daixiang0** [comment]
@rgs1 yep, what you said is what I mean!

**Review by phlax — APPROVED** [review]
lgtm, thanks @daixiang0

**Pull request merged**
