### PR TITLE
dns: don't respond with FORMERR if message has ID 0

### LINKED ISSUE #35097: Envoy's DNS filter fails to handle DNS messages with an ID equal to 0
*Description*:
We've configured the DNS filter and we're seeing

```
Unable to parse query buffer from '127.0.0.1' into a DNS object
```

intermittently. With DEBUG logs enabled we can also see we're hitting

```
    ENVOY_LOG(debug, "No ID in DNS query");
```

[here in the DNS parser](https://github.com/envoyproxy/envoy/blob/a1214c87854071d0cd5de6286af0425cc1ef131f/source/extensions/filters/udp/dns_filter/dns_parser.cc#L220).

As far as we can tell [from RFC 1035 though, an ID of `0` is perfectly valid](https://datatracker.ietf.org/doc/html/rfc1035#section-4.1.1).

*Repro steps*:
We're making the DNS queries using [`lua-resty-dns` which constructs queries](https://github.com/openresty/lua-resty-dns/blob/8bb53516e2933e61c317db740a9b7c2048847c2f/lib/resty/dns/resolver.lua#L873) potentially [with an ID of 0](https://github.com/openresty/lua-resty-dns/blob/8bb53516e2933e61c317db740a9b7c2048847c2f/lib/resty/dns/resolver.lua#L786).

*Admin and Stats Output*:
None to include

*Config*:
Will work on getting this if necessary

*Logs*:
As mentioned above we have

```
Unable to parse query buffer from '127.0.0.1' into a DNS object
No ID in DNS query
```

### PR DESCRIPTION
**Pull request by michaelbeaumont**
Commit Message:
dns: don't respond with FORMERR if message has ID 0

Additional Description:
0 is a valid ID according to RFC 1035

Risk Level:
Low

Testing:
`./ci/run_envoy_docker.sh './ci/do_ci.sh dev'`

Docs Changes:
N/A

Release Notes:
dns: don't respond with FORMERR if message has ID 0

Platform Specific Features: N/A

Fixes #35097

### CODE REVIEW

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Can you add a release note for this one? Otherwise LGTM, thanks.

/wait

**Comment by yanjunxiang-google** [comment]
LGTM modulo open comments and CI. Thanks for fixing this.

**Comment by michaelbeaumont** [comment]
Could the current CI failures be unrelated to this change? Having a bit of trouble running them locally but they seem quite unlikely to be caused by this

**Review by slonka — APPROVED** [review]

**Comment by michaelbeaumont** [comment]
@yanjunxiang-google @mattklein123 anything still needed for this? it's starting to run into conflicts with `main`

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
