### PR TITLE
WIP: xDS mux unification

### LINKED ISSUE #11477: Converge [New]GrpcMuxImpl
We have two distinct gRPC mux impls for xDS, which impacts velocity as we need to do the same thing twice when working with the xDS transport and will be a source of inconsistency long term. This is some hangover from earlier work on delta xDS.

CC @wgallagher @fredlas

### PR DESCRIPTION
**Pull request by dmitri-d**
Fixes #11477, reintroduces changes in #8974. and supersedes work in https://github.com/envoyproxy/envoy/pull/14496.

* Unified mux implementation (located in source/common/config/unified_mux dir) is completely in parallel to the original muxes, and leaves the latter virtually untouched
*  Unified muxes are disabled by default. To enable. set `envoy.reloadable_features.unified_mux` runtime flag set to true.
* Tests that required minimal changes in order to test unified muxes (these were integration-level tests, fuzz- and performance-tests) were modified to include unified muxes.
 * Tests specific to unified muxes have `unified` prepended to their names (test/common/config/unified_grpc_mux_impl_test.cc is one of those)
 
 TODOs:
 * document the runtime flag
 * More delta mux-specific unit tests are needed

Signed-off-by: Dmitri Dolguikh <ddolguik@redhat.com>

### CODE REVIEW

**Comment by dmitri-d** [comment]
ping @htuch, @asraa. 

I know you asked to break up the work into smaller chunks, but the only bits I could break out are the factory and interface changes, which are pretty trivial changes. The bulk of work is unified mux implementation + tests (new and updated). All unified mux code is now in `source/common/config/unified_mux` dir, and is completely independent of existing mux implementation. All tests specific to unified mux work are in `test/common/config` and have `unified_` prefix. Additional notes on implementation:

* source/common/config/subscription_factory_impl.cc and source/common/upstream/cluster_manager_impl.cc are the places where unifed muxes are intantiated (based on the value of `envoy.reloadable_features.unified_mux`). 
* I had to touch current implementation of muxes, but only to add stubs for new interfaces, which aren't being used anywhere.

**Comment by dmitri-d** [comment]
> Can you give some details on the control plane facing changes that enabling/disabling this flag causes?

I'll try documenting the changes next week. in the meantime `test/integration/ads_integration_test.cc` should illustrate the main differences. 

ping  @howardjohn
@howardjohn

**Review by howardjohn — COMMENTED** [review]
So looks like the main changes:
* if we send CDS v1, then CDS v2 while v1 is still warming, we don't get an ACK for both - just for v2 once its done warming
* If we send CDS while CDS is paused, we will get 2 duplicate ACKs
?

**Comment by htuch** [comment]
@dmitri-d @adisuissa is going to take a first pass.

**Comment by dmitri-d** [comment]
ping @adisuissa, any chance you'll have time to take a look at this in the near future?

**Comment by dmitri-d** [comment]
Ping @adisuissa: any chance you could spend some time on this? I'm concern that changes to current muxes need to be ported here, which in turn makes the review harder...

**Review by adisuissa — COMMENTED** [review]
Thanks for working on this!
I’ve done a few iterations over the code, trying to understand what can be done to make sure we are not missing some functionality, and not breaking current functionality.
The runtime feature is a great step to make sure we don’t break anything w/o the ability to go back to things that work.
It's still challenging to see what was added and why, because of the amount of code that was changed, and I'm trying to compare the original to the unified and to the other variant (delta to SotW).

Regarding how to make this PR more digestible, by making a series of small PRs. If we can have incremental changes, each with additional functionality, it would make it easier to understand what was changed and why. An alternative is to add things in the following order: SubscriptionState, GrpcMux, and then GrpcSubscription (these can be split into SotW and delta sub-PRs). If you’ve got other ideas on how to break this down even further this would be really helpful.

Tests: I suggest making the delta and the unified-delta use the same tests, and the sotw and unified-sotw use the same tests (as much as possible). The idea is to make sure any change in one component doesn’t negatively impact the other, and that all tests are written in a single place.

A couple of general things:
- the use of `void*` in some place where it should be Delta/Discovery{Request/Response}. It might be possible to avoid them by using templates in the base class, and specializing it in the derived class.
- Some of the code is added to allow the unified variant to work well, and will be removed when the legacy code is removed.This should be documented (add TODOs).

**Comment by htuch** [comment]
Sorry, I've been OOO, will take a look in the next couple of days.

**Comment by dmitri-d** [comment]
@htuch: I started breaking up this PR into smaller ones, https://github.com/envoyproxy/envoy/pull/16486 is the one that needs reviews.

**Pull request closed without merging**
