### PR TITLE
upstream: stats scope for dual filters

### PR DESCRIPTION
**Pull request by alyssawilk**
https://github.com/envoyproxy/envoy/blob/main/source/docs/upstream_filters.md calls out how to convert filters to dual filters and notes that init_manager and stats must come from DualInfo

This pr actually adds stats to DualInfo for use in https://github.com/envoyproxy/envoy/pull/23071 and updates docs for filter conversion

Risk Level: low
Testing: updated unit test
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

**Comment by alyssawilk** [comment]
I'm also going to update the docs in this PR, so the other is a clean example and doesn't include spurious files.

**Comment by wbpcode** [comment]
Please resolve the conflict in the docs. Thanks.

**Comment by wbpcode** [comment]
And a minor spelling error:

> Either the filter does not access streamInfo in a non-cost way  # non-cost -> non-const

**Comment by wbpcode** [comment]
And could you check following snippet of doc:

```
  * Add ``UpstreamMyFilterFactory = MyFilterFactory;`` and
    ``DECLARE_FACTORY(UpstreamMyFilterFactory`` in your config.h file and
    ``REGISTER_FACTORY(UpstreamMyFilterFactory,
                     Server::Configuration::UpstreamHttpFilterConfigFactory){"envoy.my_filter"};`` to
    your config.cc file.
```

Seems it lost something like `usinig` or `);`.

And if `DECLARE_FACTORY` is necessary? I didn't find it in the #23071.

**Review by wbpcode — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
