### PR TITLE
dependencies: update protobuf to 3.8.0

### PR DESCRIPTION
**Pull request by asraa**
In addition to updating protobuf to 3.8.0, this PR also
1) Removes old protobuf patch now included in 3.8.0
2) Patches https://github.com/protocolbuffers/protobuf/pull/6333 that fixes a UBSAN error in the protobuf library.
3) Patches protobuf's BUILD to depend on foreign_cc zlib 

Risk level: low/medium
Testing: bazel test //test/...

### CODE REVIEW

**Comment by moderation** [comment]
With 3.8.0 changing the zlib handling again and your changes in this PR I'm wondering if zlib is required in `bazel/repository_locations.bzl` any more? https://github.com/envoyproxy/envoy/blob/master/bazel/repository_locations.bzl#L141-L148

**Comment by asraa** [comment]
> With 3.8.0 changing the zlib handling again and your changes in this PR I'm wondering if zlib is required in `bazel/repository_locations.bzl` any more? https://github.com/envoyproxy/envoy/blob/master/bazel/repository_locations.bzl#L141-L148

Hm, I saw your comment in the bzl file. Is zlib required besides as a dependency for protobuf? If not, I think you're right, perhaps it's not needed and we can use protobuf_deps() instead.
https://github.com/protocolbuffers/protobuf/blob/master/protobuf_deps.bzl

**Comment by moderation** [comment]
> Hm, I saw your comment in the bzl file. Is zlib required besides as a dependency for protobuf? If not, I think you're right, perhaps it's not needed and we can use protobuf_deps() instead.
> https://github.com/protocolbuffers/protobuf/blob/master/protobuf_deps.bzl

I _think_ that the compressor, decompressor and quiche use zlib.
- https://github.com/envoyproxy/envoy/blob/master/source/common/compressor/BUILD#L15
- https://github.com/envoyproxy/envoy/blob/master/source/common/decompressor/BUILD#L15
- https://github.com/envoyproxy/envoy/blob/master/bazel/external/quiche.BUILD#L1612

If it's possible to have these reference the zlib brought in for protobuf it would mean one less dependency to maintain but it would also wouldn't be as clear.

**Comment by htuch** [comment]
I think we should stick with our own `zlib` rather than anything from `protobuf`, since we might want to rev versions independently. Also, I think `foreign_cc` is a bit cleaner than the artisinal BUILD file in protobuf third_party.

**Comment by htuch** [comment]
@asraa the `api` CI failure looks like it's potentially related to this change, maybe the precision or handling of floats has somehow changed in protobuf? You might want to update the test.

**Comment by moderation** [comment]
Timed out on macOS network listener tests
```
//test/common/network:listener_impl_test                                TIMEOUT in 301.0s
  /private/var/tmp/_bazel_vsts/c4c3c293a43c83b45613c302d61e9e23/execroot/envoy/bazel-out/darwin-fastbuild/testlogs/test/common/network/listener_impl_test/test.log
//test/common/network:udp_listener_impl_test                            TIMEOUT in 301.2s
  /private/var/tmp/_bazel_vsts/c4c3c293a43c83b45613c302d61e9e23/execroot/envoy/bazel-out/darwin-fastbuild/testlogs/test/common/network/udp_listener_impl_test/test.log
```
Flake?
/retest

**Comment by moderation** [comment]
LGTM

**Pull request merged**
