### PR TITLE
[1.20] backport #19971 SDS: reduce cost of secret update

### PR DESCRIPTION
**Pull request by lambdai**
Commit Message:
Backport #19971
Signed-off-by: Yuchen Dai silentdai@gmail.com

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by lambdai** [comment]
@oschaaf @ggreenway Do we need to fix anything regarding .github/workflows/codeql-push.yml / CodeQL-Build (pull_request)   or we just let it go?

**Comment by lambdai** [comment]
Is it fine to ignore codeQL ? If so this pr is good to be reviewed @ggreenway

**Review by ggreenway — APPROVED** [review]

**Comment by lambdai** [comment]
Thank you @ggreenway

**Pull request merged**
