### PR TITLE
quic: finer reset error code mapping

### PR DESCRIPTION
**Pull request by danzh2010**
Commit Message: change the mapping between `quic::QuicRstStreamErrorCode` and `StreamResetReason` to be more specific.

Currently all Envoy reset() will error will by default mapped to `quic::QUIC_BAD_APPLICATION_PAYLOAD`. This change will enumerate through all enum values of StreamResetReason to specifically map them to a quic reset error code.  This can enforce developers to manually pick a proper quic reset error for each newly added StreamResetReason values. 

This change also change the mapping from QUICHE level stream reset error `quic::QuicRstStreamErrorCode` to `StreamResetReason` to a finer granular. 

Risk Level: low, only affect error reporting
Testing: existing test passed
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Review by RyanTheOptimist — COMMENTED** [review]
Looks good, though CI is failing?

**Comment by RyanTheOptimist** [comment]
/wait 
Looks like CI is still complaining

**Comment by danzh2010** [comment]
cc @abeyad

**Comment by RyanTheOptimist** [comment]
/wait
CI

**Review by RyanTheOptimist — APPROVED** [review]

**Comment by danzh2010** [comment]
cc @RenjieTang

**Pull request merged**
