### PR TITLE
runtime: no longer upping stats for deprecated v2 APIs

### PR DESCRIPTION
**Pull request by alyssawilk**
Part of https://github.com/envoyproxy/envoy/issues/19847

### CODE REVIEW

**Review by adisuissa — COMMENTED** [review]
Code changes LGTM.

@htuch I think it's ok to remove the deprecated feature usage counter, but would like to have your take on this as well.

**Review by htuch — DISMISSED** [review]
Don't we want this as part of minor versioning? I.e. the ability to count features that are in use but deprecated?

**Comment by alyssawilk** [comment]
Minor versioning isn't supported yet right?  When it is I think we can work on adding stats which aren't using a to-be-deprecated global variable.

**Comment by adisuissa** [comment]
Yes I agree that the stats plumbing can be achieved differently.

**Comment by htuch** [comment]
I guess what I'm wondering about is whether users should have to change their monitoring systems or we would reuse the same stat name here. If we plan to reuse the stat name, that is fine.

**Comment by alyssawilk** [comment]
either way if the stat isn't relevant now, and the usage relies on illegal singleton access, can we remove and revisit adding back when it's relevant?

**Comment by htuch** [comment]
Yes, but please keep in mind reuse of the stat name in teh future.

**Review by mattklein123 — CHANGES_REQUESTED** [review]
This is used for current deprecated features, right? Even apart from minor versioning? I think we need to keep this as people are likely alerting/monitoring on this as a way to see configs that need to be updated?

/wait

**Comment by alyssawilk** [comment]
I don't think this is used by deprecated features, if you look at the code it only branches on v2 APIs. AFIK all those docs are out of date as I believe support for feature deprecation was removed when we revved to v3, and has not been added back since.
Adi will be the developer adding it back which is why I gave him first review pass as I figured if he's fine adding it back later, that would be good enough?

**Review by mattklein123 — APPROVED** [review]
Thanks LGTM

**Pull request merged**
