### PR TITLE
extension: enable tracing for the external authorization HTTP client implementation.

### LINKED ISSUE #6520: B3 HTTP headers not propagated to ext_authz server in 1.10.0
*B3 HTTP headers are not propagated to ext_authz server*

*Description*:
Upgrading from Envoy 1.9.0 to 1.10.0 omits the Zipkin trace context propagation (B3 headers) to an external HTTP authorization server and hence is not visible in a distributed trace.

Using Envoy 1.9.0 the following config propagates B3 trace context (x-b3-traceid and x-b3-spanid headers) to an external auth server so it can join a distributed trace.
```
- name: envoy.ext_authz
     config:
       http_service:
         server_uri:
           uri: http://authorization-service:8080
           cluster: ext-authz
           timeout: 2s
         allowed_request_headers: ["x-b3-traceid", "x-b3-spanid"]
```

With Envoy 1.10.0 this configuration has changed (see https://www.envoyproxy.io/docs/envoy/v1.10.0/intro/version_history) and the corresponding config looks like
```
- name: envoy.ext_authz
     config:
       http_service:
         server_uri:
           uri: http://authorization-service:8080
           cluster: ext-authz
           timeout: 2s
         authorization_request:
           allowed_headers:
             patterns:
               prefix: "x-b3"
```
However, in 1.10.0 none of the x-b3-* keys are added in HTTP headers and hence the external authz. server can't be part of the trace. I've tried several patterns (exact, prefix, regex) to see if there are any issues with the StringMatcher but without any luck :(

Note that it is only the external auth.server that doesn't get the HTTP headers, I can see the trace which is initiated by Envoy in my tracing UI (Jeager) but without the external auth.server so some parts of the trace is working as expected.

### PR DESCRIPTION
**Pull request by gsagula**
Description: 
This PR adds tracing support to the HTTP client in the external authorization filter. So far, only gRPC client was able to trace requests from the filter to an authorization service.

Risk Level: Low
Testing: yes
Docs Changes: N/A
Release Notes: Added
Fixes #6520 

Signed-off-by: Gabriel Linden Sagula <gsagula@gmail.com>

### CODE REVIEW

**Comment by dio** [comment]
@gsagula please let me know when this is ready/need hands for this 🙂

**Comment by gsagula** [comment]
Looking into this one.

**Comment by gsagula** [comment]
I'm on the road now. I fix the config test later.

**Comment by dio** [comment]
@gsagula could you resolve the conflict?

**Comment by gsagula** [comment]
@dio Done.

**Comment by lizan** [comment]
can you merge master again to pick up latest CI changes?

**Comment by gsagula** [comment]
@dio Thanks for looking into it. I addressed the issues but I will need to resubmit this PR since the Datawire repo is now private.

**Comment by dio** [comment]
@gsagula please let me know which path do you want to take on progressing this PR. Thanks!

**Comment by gsagula** [comment]
> @gsagula please let me know which path do you want to take on progressing this PR. Thanks!
I addressed the comments above. I will open a new PR for this change.

**Comment by dio** [comment]
@gsagula should we close this one? In favor of https://github.com/envoyproxy/envoy/pull/8142.

**Comment by gsagula** [comment]
Yes, thanks! :)

**Pull request closed without merging**
