### PR TITLE
increase stats coverage

### PR DESCRIPTION
**Pull request by zirain**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
nice, thanks!

probs this will make #33410 unnecessary

**Comment by zirain** [comment]
> nice, thanks!
> 
> probs this will make #33410 unnecessary

CI is happy now.

**Comment by phlax** [comment]
> CI is happy now.

the problem here is that its flakey - it only failed postsubmit once afaict and only on a scheduled run (rather than push to main) which is due to the fact that all tests are rerun

**Comment by zirain** [comment]
I hope this will unblock https://github.com/envoyproxy/envoy/pull/33281.

**Review by phlax — APPROVED** [review]
lgtm, thanks @zirain

**Pull request merged**
