### PR TITLE
docs: Update sphinx

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: docs: Update sphinx
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
waiting for https://github.com/executablebooks/sphinx-tabs/issues/113

**Comment by phlax** [comment]
also need to check that the intersphinx hack works - touch #16181

**Comment by phlax** [comment]
intersphinx extension worked - but updated to base it on latest from upstream

**Review by moderation — APPROVED** [review]

**Review by htuch — APPROVED** [review]

**Pull request merged**
