### PR TITLE
docs: fix hardcoded docker image names

### PR DESCRIPTION
**Pull request by mattklein123**

### CODE REVIEW

**Comment by mattklein123** [comment]
cc @phlax

**Comment by phlax** [comment]
looks good - i had thought to generate the csv - but this has the advantage that we can reuse this substitution

**Comment by phlax** [comment]
also afaict the content in the csv is not searchable - so i think this way should fix that

**Comment by phlax** [comment]
lgtm once format is fixed 

https://storage.googleapis.com/envoy-pr/6d91ebf/docs/start/install.html?highlight=bionic#pre-built-envoy-docker-images

**Comment by mattklein123** [comment]
@phlax should be fixed, thanks.

**Review by alyssawilk — APPROVED** [review]

**Review by phlax — APPROVED** [review]
arrgghh CI !!!

lgtm

**Pull request merged**
