### PR TITLE
test: Split huge monolith mock header(test/upstream/mocks.h) to speed up test compilation

### PR DESCRIPTION
**Pull request by foreseeable**
Signed-off-by: Muge Chen <mugechen@google.com>

Commit Message: breakdown `test/mocks/upstream/mocks.h` into different mock classes
Additional Description:  `test/mocks/upstream/mocks.h` is a wide-used mock header included by various test files. However it's very huge and most test files only used a small portion of it. Splitting it up into different mock classes will be helpful to reduce compilation time. (similar to #11797 )
Risk Level: low
Testing: existing tests
Docs Changes: N/A
Release Notes: no
Related Issues: #10917

### CODE REVIEW

**Comment by foreseeable** [comment]
\cc @ahedberg @bbarenblat

**Comment by htuch** [comment]
@junr03 can you take a look at this as non-Googler? Thanks!

**Comment by junr03** [comment]
> @junr03 can you take a look at this as non-Googler? Thanks!

Yep, will take a look with fresh eyes on monday

**Comment by foreseeable** [comment]
Friendly ping @junr03

**Comment by foreseeable** [comment]
> Thanks for your patience, specially because reviewing this PR is actually not time consuming.
> 
> One question: is the intention to break apart the mock target here, and then update usage in a subsequent PR? Is that why this PR still has the massive target that now includes all the broken up targets?
> 
> One request: can you update the title of the PR to mention that this is for the upstream mocks, similar to how we did for the header inclusion reduction PRs?
> 
> Thanks!

Yes I will then update usage in subsequent PRs. 

The title has been changed, thanks for your suggestion.

**Pull request merged**
