### PR TITLE
ci: Download minimal for release tests

### PR DESCRIPTION
**Pull request by phlax**
This more than halves the time to run the arm build/release tests

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
prior art #26031 #22017

**Comment by phlax** [comment]
for verification that it is still downloading the test information (just not all the bins) - comparison of artefacts in this PR with another:

- https://dev.azure.com/cncf/envoy/_build/results?buildId=131424&view=artifacts&pathAsName=false&type=publishedArtifacts
- https://dev.azure.com/cncf/envoy/_build/results?buildId=131437&view=artifacts&pathAsName=false&type=publishedArtifacts

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Comment by phlax** [comment]
this may have broken `main`
 
https://dev.azure.com/cncf/envoy/_build/results?buildId=131505&view=logs&j=7b6d60aa-b5de-5f9b-678c-063d31881e76&t=e6b65f99-8be0-5160-6876-20812695ac3b&l=2237

if it happens again ill revert

**Pull request merged**
