### PR TITLE
ext_proc: runtime guard for timeout error

### PR DESCRIPTION
**Pull request by tyxia**
Commit Message: https://github.com/envoyproxy/envoy/pull/34856 fixs the timeout error but it is a behavior change that could cause the customer surprises. Adding runtime guard.
Risk Level: Runtime guard
Testing: Integration test
Docs Changes: N/A
Release Notes: Yes
Platform Specific Features: N/A

### CODE REVIEW

**Comment by tyxia** [comment]
cc @cainelli

**Review by alyssawilk — APPROVED** [review]
thanks!

**Review by cainelli — APPROVED** [review]
Makes sense, thank you and will keep in mind for the next time :)

**Pull request merged**
