### PR TITLE
Added missing changelogs/1.27.2.yaml

### PR DESCRIPTION
**Pull request by tsaarni**
**Commit Message:** Added missing changelogs/1.27.2.yaml
**Additional Description:**

Release 1.27.2 is missing from latest docs https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history

This change adds changelog entry for `1.27.2`  by copying `https://github.com/envoyproxy/envoy/blob/v1.27.2/changelogs/current.yaml` to` changelogs/1.27.2.yaml`

**Risk Level:** Low
**Testing:** N/A
**Docs Changes:** N/A
**Release Notes:** N/A
**Platform Specific Features**: N/A

### CODE REVIEW

**Comment by phlax** [comment]
@tsaarni this is not really necessary - we have tooling to automate this process, and there are some additional steps

i havent run the tooling as im working on adding it as a workflow atm

**Comment by tsaarni** [comment]
@phlax ah ok!   And it also works "retroactively"? The changelog entry seemed "lost" to me, from `main` branch perspective. The 1.27.2 info was once in `current.yaml` but nowhere to be found naymore.

**Comment by phlax** [comment]
yeah, for ref the command to sync _all_ version history is

```console
$ bazel run @envoy_repo//:sync
```

im literally just about to add it as workflow so it can be automated
`
relatedly, i just landed a small fix to the commit message (https://github.com/envoyproxy/toolshed/pull/887)

**Comment by tsaarni** [comment]
Closing the PR since not needed.

**Pull request closed without merging**
