### PR TITLE
Issue 4546: Refactor FD with a general I/O Handle

### PR DESCRIPTION
**Pull request by sbelair2**
*Description*:

Introduce an abstract I/O Handle and one derivative for sockets, the IoSocketHandle.
Preserve fd semantics in all socket-related system calls with ioHandle->fd(). In this
initial PR, all calls which take an fd retain their same parameters.

*Risk Level*:

Low

*Testing*:

Everything covered by bazel test //test...

### CODE REVIEW

**Comment by sbelair2** [comment]
@mattklein123 It looked like the circle:mac test passed. I couldn't view the cicrleci:ipv6 test, so Im not sure what the issue is there. Please review.

**Comment by htuch** [comment]
@sbelair2 it seems there have been a lot of PRs opened/closed for this patch. It's kind of hard to reason across this chain; can you try and stick to one PR per change? If you need git assistance, happy to help out here or on Slack.

**Comment by sbelair2** [comment]
@htuch Yes, I totally botched previous PR attempts. I then hit issues with check_repositories, which I did post on slack. As of this posting of this PR last night, there were no conflicts and the diffs presented were final. I really am not sure how you would prefer the next steps to be- I thought that the state of the PR was fine in that the diffs represent the final outcome of the PR. What would you suggest?

**Comment by mattklein123** [comment]
@sbelair2 I think we are just trying to understand whether you have figured out your workflow issues before we start reviewing. This PR already needs a master merge. Can you do that to make sure that workflow works for you? Thanks.

**Comment by sbelair2** [comment]
@mattklein123 I have basically figured out my workflow issues, thanks to Ed Warnicke's help (don't know his GitHub handle). I am working on the master merge as we speak. The several consecutive pushes to my fork were a result of my fetching upstream, merging upstream changes with my changes, and then pushing. Once pushed, I see that I was out of sync again, and again. Is the issue for the reviewers that there were several pushes to my fork? In which case, a squash is required? My code changes are indeed in a final state, but I appear to be chasing the parade of changes here. Feel free to advise- thank you.

**Comment by sbelair2** [comment]
@mattklein123 Understood. Closing this PR and coming back with another correct one.

**Comment by mattklein123** [comment]
@sbelair2 you didn't need to close this PR ... Just merge master ... I would really commend syncing up with someone a little bit about git or maybe looking at a GitHub tutorial?

**Comment by sbelair2** [comment]
@mattklein123 I did as you suggested: merged with master and eventually pushed. Hopefully the DCO will still be ok after the merge.

**Comment by sbelair2** [comment]
@mattklein123 As suspected, there was an issue with DCO after the merge. I tried "git commit --amend --signoff" after the merge completed, but it has no affect. Note that the DCO was correct previously. Please advise.

**Comment by mattklein123** [comment]
@sbelair2 I don't think you actually did a merge commit. Can I kindly ask that you find someone to help you with git and GitHub? Unfortunately we don't have the resources to help with this.

**Comment by sbelair2** [comment]
@mattklein123 I do have someone I can ask, I'm not going it alone here. I did a "git merge upstream/master", which worked fine except for the signoff (It appears that the --signoff flag can now be included with merge). Is the only issue the missing DCO signoff, or are there other issues that you see? If other issues, I can close the PR and open a new one that fixes them, Thank you.

**Comment by jmarantz** [comment]
I have a higher level question on the plan with this PR -- there have been a few other attempts to abstract network handles, and I think it's a very achievable, beneficial project.  However there are a couple of complexities that at first glance this PR does not tackle:

 - on some OS's an 'int' is not the most appropriate representation for a network handle, and it should not be exposed on the abstract interface.
 - There are some interactions with libevent that would need to be abstracted as well, since libevent has knowledge of int FDs.

It might be helpful to start with a design doc and iterate on that.

**Comment by jmarantz** [comment]
Ah I see that you were one of the authors of the earlier PRs: #4579 -- sorry for the confusion.

**Comment by mattklein123** [comment]
@sbelair2 I'm sorry I'm not sure where you went wrong with the DCO. You can fix by rebasing and force pushing. Please do not open new PRs.

**Comment by alyssawilk** [comment]
I don't think DCO is the only remaining issue.   If you look at the files view, I see many changes which aren't yours, which indicates something else has gone wrong :-/

**Comment by sbelair2** [comment]
@alyssawilk Correct! I see 89 files. changed, whereas my commit involved 41 files. Can this PR be salvaged?

**Comment by alyssawilk** [comment]
Yep, if you git rebase correctly (normally strongly discouraged but no one has reviewed this so it should be fine) and force push per Matt's earlier advice you should be able to correct this.

**Comment by sbelair2** [comment]
@alyssawilk I've been looking at the extra files in this PR, and those are all the files that have been pulled from upstream/master and are being pushed into my fork- it would be incorrect to exclude them. I do think that DCO is the only apparent issue. Do you agree?

**Comment by sbelair2** [comment]
@alyssawilk Got it- makes sense. Thanks!

**Comment by danzh2010** [comment]
@sbelair2, envoy quic also need this IoHandle interface. Do you mind to add some interfaces we need into this PR? Please check https://github.com/envoyproxy/envoy/pull/5171 for your reference.

**Pull request closed without merging**
