### PR TITLE
Update googleurl to the latest version.

### LINKED ISSUE #14743: deps: Adopt patch free Chromium URL library
When we have upstream Chromium to give us an IDN-free optional build we can adopt Chromium URL library without patching it.

Context: https://github.com/envoyproxy/envoy/pull/14583#discussion_r559660170

### PR DESCRIPTION
**Pull request by vasilvv**
A newer version of googleurl also supports building without ICU, so we
can remove the patch that created an Envoy-specific build target.

Signed-off-by: Victor Vasiliev <vasilvv@google.com>

Risk Level: Low
Testing: Dependency change; should be covered by existing tests.
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
Fixes #14743

### CODE REVIEW

**Review by RyanTheOptimist — DISMISSED** [review]
Nice!

**Comment by moderation** [comment]
/lgtm deps

Looks like there are Windows CI failures

**Comment by phlax** [comment]
its looking like the windows fail is real

**Comment by RyanTheOptimist** [comment]
I'm surprised not to see any explanation of the error in the log. Am I missing something? I see:

```
ERROR: C:/build/tmp/external/com_googlesource_googleurl/url/BUILD:12:11: Compiling url/gurl.cc failed: (Exit 2): cl.exe failed: error executing command 
  cd /d C:/build/tmp/execroot/envoy
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET TEMP=C:\Windows\Temp
    SET TMP=C:\Windows\Temp
    SET TMPDIR=C:\Windows\Temp
    SET USE_CLANG_CL=
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe @bazel-out/x64_windows-opt/bin/external/com_googlesource_googleurl/url/_objs/url/gurl.obj.params
# Configuration: 687b7bbc43ec17c5339d1311fd33d44a9b0752f1f826ecaa5010a57b81b441c7
# Execution platform: @envoy_build_tools//toolchains:rbe_windows_msvc_cl_platform
```
But it doesn't explain *why* it failed?

**Comment by RyanTheOptimist** [comment]
Oh, I can't read. This is the error:

```
external/com_googlesource_googleurl\base/memory/raw_ptr.h(34): fatal error C1083: Cannot open include file: 'base/win/windows_types.h': No such file or directory
```

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
