### PR TITLE
Granular Connection Failure Reason

### PR DESCRIPTION
**Pull request by KBaichoo**
Commit Message: Replace Coarse Connection Failure with Granular Connection failure to make failure more transparent.
Additional Description: 
Risk Level: medium -- should hold off until release
Testing: Fixed test
Docs Changes: n/a
Release Notes: included
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by KBaichoo** [comment]
@yanavlasov PTAL, will fix the merge conflict after the review

**Comment by yanavlasov** [comment]
LGTM, needs main merge.

/wait

**Comment by KBaichoo** [comment]
friendly ping @yanavlasov

**Review by yanavlasov — APPROVED** [review]

**Pull request merged**
