### PR TITLE
Revert "bazel: update to 6.0.0rc1 (#23678)"

### LINKED ISSUE #23985: CI: Coverage is currently broken
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

CI: Coverage pages 404

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

404 when going to GCS bucket for coverage report using the link given by CI.

*Repro steps*:
> Go to  recent coverage CI output to see the uploaded coverage report. For example: https://github.com/envoyproxy/envoy/pull/23935, we'd get linked to https://storage.googleapis.com/envoy-pr/87dbffb/coverage/index.html which encounters the error below:

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: envoy-pr/87dbffb/coverage/index.html</Details>
</Error>
```

### PR DESCRIPTION
**Pull request by phlax**
Fix #23985 

This reverts commit 84df237d6576341299ab8c5cca9741e6e1f32008.

Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
fixing the coverage here exposes that the coverage has not been checked recently and is therefore not matching current per-file expectations

i was about to adjust the coverage when i noticed that one is off by a lot

```console

Code coverage for source/extensions/clusters/common is lower than limit of 96.6 (68.2)
Code coverage for source/extensions/filters/http/cache/simple_http_cache is lower than limit of 96.0 (95.9)
Code coverage for source/extensions/filters/network/thrift_proxy/filters/payload_to_metadata is lower than limit of 96.6 (96.2)
Code coverage for source/server/admin is lower than limit of 97.5 (97.4)

```

**Comment by phlax** [comment]
cc @alyssawilk

**Comment by phlax** [comment]
cc @keith

**Comment by RyanTheOptimist** [comment]
This PR is marked as draft. Are you still working on it, or is it ready for review?

**Review by keith — APPROVED** [review]
Fine to merge and I can debug after the holidays

**Comment by phlax** [comment]
> This PR is marked as draft. 

it was - i think i already deWIPPed it

> Are you still working on it, or is it ready for review?

it needs the per-file coverage to be adjusted - i can do that but in the case of the clusters code this is a big drop

```console

Code coverage for source/extensions/clusters/common is lower than limit of 96.6 (68.2)
```

i guess we want to just adjust coverage and fix that separately - ill update

**Comment by keith** [comment]
I think the solve for this might be this flag:

--experimental_fetch_all_coverage_outputs

**Comment by phlax** [comment]
let me give that a whirl on a test PR ...

**Comment by phlax** [comment]
https://github.com/envoyproxy/envoy/pull/24105/files#diff-544556920c45b42cbfe40159b082ce8af6bd929e492d076769226265f215832fR170

**Comment by keith** [comment]
Guess we should also make this stuff fail when it breaks

**Comment by phlax** [comment]
that doesnt seem to have worked

```console
-r-xr-xr-x 1 envoybuild envoygroup    0 Nov 21 18:07 **_coverage_report.dat**
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=121183&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=e00c5a13-c6dc-5e9a-6104-69976170e881&l=2478

**Comment by phlax** [comment]
i reckon lets land this for now and address the bazel/update/coverage issue separately

**Comment by phlax** [comment]
dont-break-coverage ticket is here https://github.com/envoyproxy/envoy/issues/24119

**Comment by phlax** [comment]
missing-coverage ticket https://github.com/envoyproxy/envoy/issues/24120

**Review by jmarantz — APPROVED** [review]

**Pull request merged**
