### PR TITLE
Revert "delta-xds: perform resource state tracking after resource ing…

### PR DESCRIPTION
**Pull request by mattklein123**
…estion (#23214)"

This reverts commit 6e6a3a17e4c1890b20b8832280a81385f3eb8573.

Coverage is failing on main.

### CODE REVIEW

**Comment by mattklein123** [comment]
cc @adisuissa let's see if this fixes coverage on main. Feel free to fix forward also if you want.

**Review by RyanTheOptimist — APPROVED** [review]
LGTM, assuming coverage passes

**Review by adisuissa — APPROVED** [review]
Ack, let's revert for now.

**Comment by RyanTheOptimist** [comment]
> Ack, let's revert for now.

SG. I've enabled auto-merge, so if this passes CI it'll land automatically.

**Pull request merged**
