### PR TITLE
Quiche roll 20241104183156

### PR DESCRIPTION
**Pull request by fredyw**
Update QUICHE from 5621f6366 to aaf48d2e5
 
https://github.com/google/quiche/compare/5621f6366..aaf48d2e5
    
```
$ git log 5621f6366..aaf48d2e5 --date=short --no-merges --format="%ad %al %s"
     
2024-11-04 asedeno MASQUE: add tap bridging support for CONNECT-ETHERNET
2024-11-04 quiche-dev Fix the issue that -Wrange-loop-construct higlighted in quiche.
2024-11-01 martinduke Send raw counts of reported ECN marks in QUIC ACK frames to the debugger.
2024-11-01 wub No public description
2024-11-01 quiche-dev Mark sec-authenticated-request-headers as a repeated header
2024-10-31 ricea Remove a stray semi-colon from quiche_protocol_flags_list.h
2024-10-31 birenroy Adds unit tests for clients handling END_STREAM after 1xx headers without final response headers.
2024-10-29 wub Add transport parameter 'discard' to QUIC and switch connection option `CHP1` and `CHP2` to use it.
2024-10-29 rch Record stats when forward progress is made on a QUIC connection after changing the flow label on PTO.
2024-10-29 vasilvv Implement QuicAlarmMultiplexer.
2024-10-28 wub Deprecate gfe2_reloadable_flag_quic_add_ssl_error_stack_to_error_detail.
2024-10-28 martinduke Parser/Framer for MoQT FETCH Stream messages.
2024-10-28 martinduke Delete Subscribe ID from MoQT Object headers
```

### CODE REVIEW

**Review by vanessareimer — APPROVED** [review]

**Comment by RyanTheOptimist** [comment]
Is this failure real?
//test/swift/integration/proxying:http_request_using_proxy_test          FAILED in 45.7s

**Comment by fredyw** [comment]
> Is this failure real? //test/swift/integration/proxying:http_request_using_proxy_test FAILED in 45.7s

No, it's unrelated but I'm fixing it in https://github.com/envoyproxy/envoy/pull/36980. It's been failing in the main:
- https://github.com/envoyproxy/envoy/actions/runs/11671611154/job/32500065249
- https://github.com/envoyproxy/envoy/actions/runs/11670461951/job/32494723883

I'll fix the Swift proxy test first before sending this PR ready for review.

**Comment by fredyw** [comment]
I have fixed the failing `//test/swift/integration/proxying:http_request_using_proxy_test` in https://github.com/envoyproxy/envoy/pull/36980. CI is happy now.

**Review by RyanTheOptimist — APPROVED** [review]

**Pull request merged**
