### PR TITLE
tls: remove SHA-1 cipher suites from the defaults on the server-side

### PR DESCRIPTION
**Pull request by derekguo001**
Signed-off-by: derekguo001 <dong.guo@intel.com>

Commit Message: tls: remove SHA-1 cipher suites from the defaults on the server-side
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes: tls: remove SHA-1 cipher suites from the defaults on the server-side
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/5400
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by wrowe** [comment]
Per #5401 - @PiotrSikora can you confirm it's time to land this deprecation, and that the changes entry is sufficient?

**Review by PiotrSikora — APPROVED** [review]
This change looks fine, but as usual, I'd recommend merging it after release instead of right before it.

**Comment by wrowe** [comment]
/wait on the quarterly release coming up mid-April

**Comment by wrowe** [comment]
> I'd recommend merging it after release instead of right before it.

Agreed, moving it forward once it clears CI.

/retest

**Review by wrowe — APPROVED** [review]

**Pull request merged**
