### PR TITLE
kafka: add header support to mesh-filter

### PR DESCRIPTION
**Pull request by adamkotwasinski**
Commit Message: kafka: add header support to mesh-filter
Additional Description: Add header support.
Risk Level: Low
Testing: TBD
Docs Changes: Minimal - mesh filter .rst
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by adamkotwasinski** [comment]
It works, but `KafkaProducer::send` takes 6 parameters so I'll change that one too.

**Comment by adamkotwasinski** [comment]
remove waiting label

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
