### PR TITLE
Revert "io_uring: add io_uring socket handle (#32946)"

### PR DESCRIPTION
**Pull request by soulxu**
This reverts commit 45fa977549cee38791d6dd42c73968f7487f7844.

This still break the mobile-perf ci https://github.com/envoyproxy/envoy/actions/runs/8415388996/job/23040500092#step:8:612

### CODE REVIEW

**Comment by soulxu** [comment]
cc @phlax @zhxie

**Comment by zhxie** [comment]
@phlax we have [tested](https://github.com/envoyproxy/envoy/actions/runs/8351882573) removing the corresponding file in mobile-perf.yml to ensure the file would not be built in Android. And from the commit CI we can guess that changes to CI YAML would not take effect until merging. Is that right?

As a result, we can conclude that Android will also build files with `//bazel:linux` selected. Do you have any idea to avoid including files in Android.

**Comment by soulxu** [comment]
> @phlax we have [tested](https://github.com/envoyproxy/envoy/actions/runs/8351882573) removing the corresponding file in mobile-perf.yml to ensure the file would not be built in Android. And from the commit CI we can guess that changes to CI YAML would not take effect until merging. Is that right?
> 
> As a result, we can conclude that Android will also build files with `//bazel:linux` selected. Do you have any idea to avoid including files for Android?

Maybe we should follow what admin_html doing here: https://github.com/envoyproxy/envoy/blob/45fa977549cee38791d6dd42c73968f7487f7844/mobile/.bazelrc#L11

**Comment by zhxie** [comment]
I prefer to try the following first.

```bazel
select({
    "//bazel:android": [],
    "//bazel:linux": [
        "io_uring_socket_handle_impl.cc",
    ],
    "//conditions:default": [],
}),
```

Maybe phlax can give some advice if it would work...

**Comment by phlax** [comment]
trying to understand why it managed to get through CI when we explicitly tested - i broke mobile-perf at end of last week so maybe related

im thinking lets land the revert and test again properly

**Review by phlax — APPROVED** [review]
lgtm, thanks @soulxu

**Pull request merged**
