### PR TITLE
[WIP] deps: Bump `com_github_grpc_grpc` -> 1.45.1

### LINKED ISSUE #19715: Newer release available `com_github_grpc_grpc`: v1.43.2 (current: a3ae8e0)
Package Name: com_github_grpc_grpc
Current Version: a3ae8e0@2021-06-07 22:24:54
Available Version: v1.43.2@2022-01-26 18:24:34
Upstream releases: https://github.com/grpc/grpc/releases

### LINKED ISSUE #20639: Newer release available `com_github_grpc_grpc`: v1.45.1 (current: a3ae8e0)
Package Name: com_github_grpc_grpc@a3ae8e00a2
Current Version: a3ae8e0@2021-06-07
Available Version: v1.45.1@2022-04-01
Upstream releases: https://github.com/grpc/grpc/releases

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #20639 
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by moderation** [comment]
`1.44.0` is out - https://github.com/grpc/grpc/releases/tag/v1.44.0

**Comment by phlax** [comment]
ill update altho i havent managed to get this update working previously

**Comment by phlax** [comment]
tried again with this dep - got a little further by adding the `upb://reflection` dep but still failing with

```
ERROR: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/com_github_grpc_grpc/BUILD:3923:16: no such target '//external:libcrypto': target 'libcrypto' not declared in package 'external' defined by /source/WORKSPACE and referenced by '@com_github_grpc_grpc//:grpc_jwt_credentials'
ERROR: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/com_github_grpc_grpc/BUILD:3989:16: no such target '//external:libcrypto': target 'libcrypto' not declared in package 'external' defined by /source/WORKSPACE and referenced by '@com_github_grpc_grpc//:grpc_external_account_credentials'
ERROR: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/com_github_grpc_grpc/BUILD:4240:16: no such target '//external:libcrypto': target 'libcrypto' not declared in package 'external' defined by /source/WORKSPACE and referenced by '@com_github_grpc_grpc//:tsi_ssl_credentials'
ERROR: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/com_github_grpc_grpc/BUILD:4180:16: no such target '//external:libcrypto': target 'libcrypto' not declared in package 'external' defined by /source/WORKSPACE and referenced by '@com_github_grpc_grpc//:tsi_alts_credentials'

```

@keith any ideas if/how we need to add libcrypto as an external lib ?

**Comment by keith** [comment]
It looks like we don't call `grpc_deps` (maybe better that way) so we don't get this `bind` 

https://github.com/grpc/grpc/blob/08451810a673fa892f08e4d00b2cc59cc6b80f90/bazel/grpc_deps.bzl#L78-L81

I guess we can add this one ourselves since we have boringssl already? It doesn't look like anything depends on `boringssl//:crypto` yet tho.

OTOH if we don't actually use (do we?) the libraries that are failing here maybe we can create some dev/null target just to silence this instead

**Comment by phlax** [comment]
adding the llibcrypto bind and updating the upb version this gets further, but its still failing with a zlib issue

```console

external/com_github_grpc_grpc/src/core/lib/compression/message_compress.cc:25:10: error: module @com_github_grpc_grpc//:grpc_base does not depend on a module exporting 'zlib.h'

```

ive had a poke around the grpc setup but its not obvious to me what the issue is exactly

**Comment by moderation** [comment]
`zlib` and `grpc` integration has changed a fair bit over the releases. Is this relevant?

https://github.com/envoyproxy/envoy/blob/main/bazel/repositories.bzl#L410-L414=

It is done differently in `grpc`

https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl#L83-L86=

**Pull request closed without merging**
