### PR TITLE
[backport/1.22] ocsp: rotate certs of test data to fix flaky tests (#23635)

### PR DESCRIPTION
**Pull request by dcillera**
* ocsp: rotate certs of test data

Signed-off-by: wbpcode <wangbaiping@corp.netease.com>

* fix format

Signed-off-by: wbpcode <wangbaiping@corp.netease.com>

Signed-off-by: wbpcode <wangbaiping@corp.netease.com>

### CODE REVIEW

**Comment by phlax** [comment]
i think most likely this will also need the infra fix - if you check this PR - #23817 - you can see the other commit that is likely required

**Comment by dcillera** [comment]
Fixed DCO problem by performing suggested procedure.

**Review by phlax — DISMISSED** [review]
lgtm, thanks @dcillera

**Comment by phlax** [comment]
arggh - seems like time has warped on this branch and one of the dependencies was released on a different date

https://dev.azure.com/cncf/envoy/_build/results?buildId=119875&view=logs&j=1c04237c-5f52-5959-5f83-5522b3556331&t=db3f3889-c922-566b-fa2e-4bc4948bc467&l=969

im just looking at this branch so im happy to fix - but if you add the fix here first i will land

**Comment by dcillera** [comment]
I think the following commit is also missing. Do you think we should add it to this PR?

commit b1f5e92d850cec6629a0ae1efab20b5453dff175
Author: Xie Zhihao <zhihao.xie@intel.com>
Date:   Fri Sep 23 18:13:47 2022 +0800

    deps: fix mismatch release date in OpenCensus Proto (#23220)
    
    Signed-off-by: Xie Zhihao <zhihao.xie@intel.com>

**Comment by phlax** [comment]
yep - that looks like the fix i think

**Comment by phlax** [comment]
i just hit a similar problem trying to update the 1.21 branch https://github.com/envoyproxy/envoy/pull/23852#issuecomment-1305498699

**Comment by phlax** [comment]
testing a fix for codeql here - https://github.com/envoyproxy/envoy/pull/23859

**Comment by phlax** [comment]
@dcillera the codeql problem is caused by the ubuntu image not being pinned - ie its set to `ubuntu-latest`

im going to fix that on main so its explicit which version its using which should prevent this happening in the future

for this PR do you want to add the following diff/commit:

```diff

diff --git a/.github/workflows/codeql-daily.yml b/.github/workflows/codeql-daily.yml
index 612fa1722e..0c37880c7d 100644
--- a/.github/workflows/codeql-daily.yml
+++ b/.github/workflows/codeql-daily.yml
@@ -11,7 +11,7 @@ jobs:
       fail-fast: false
 
     # CodeQL runs on ubuntu-latest and windows-latest
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-18.04
 
     steps:
     - name: Checkout repository
diff --git a/.github/workflows/codeql-push.yml b/.github/workflows/codeql-push.yml
index bb31007938..b6a42b8f7b 100644
--- a/.github/workflows/codeql-push.yml
+++ b/.github/workflows/codeql-push.yml
@@ -17,7 +17,7 @@ jobs:
       fail-fast: false
 
     # CodeQL runs on ubuntu-latest and windows-latest
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-18.04
     if: github.repository == 'envoyproxy/envoy'
 
     steps:

```

ill test it now - but im fairly confident this is the required fix

**Comment by phlax** [comment]
the release bug in CI looks like a genuine fail

```console
`[2022-11-07 12:57:38.820][17][error][envoy_bug] [source/extensions/transport_sockets/tls/context_impl.cc:443] envoy bug failure: value_stat_name != fallback. Details: Unexpected ssl.ciphers value: unexpected
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=119887&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=6b0ace90-28b2-51d9-2951-b1fd35e67dec&l=4175

**Comment by phlax** [comment]
im wondering if this commit 6d39a4e9dfcfb8a27e73da795426025ff5add6d2 is related to the tls failures - merging requires some conflict resolution and not 100% certain if its the issue/fix but looks like it to me

**Comment by phlax** [comment]
hmm seems like my suggestion was either incorrect or incomplete - did you have any joy debugging locally ?

**Comment by phlax** [comment]
re codeql - i have just backported the fix from `main` to the 1.23 and 1.24 branches - #23878 and #23879

**Comment by phlax** [comment]
@wbpcode @daixiang0 could you help out here

we are trying to update the 1.22 branch with recent fixes from `main` 

if we add just https://github.com/envoyproxy/envoy/pull/23635

we are getting an error:

```console

test/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator_test.cc:560:59: error: member reference base type 'size_t' (aka 'unsigned long') is not a structure o
r union                                                                                                                                                                           
  EXPECT_EQ(19956, validator().daysUntilFirstCertExpires().value()); 

```

i then tried picking https://github.com/envoyproxy/envoy/pull/20581 and https://github.com/envoyproxy/envoy/pull/21428

but that then throws other errors - as i think the code had changed on `main` differently to this branch - altho looks like easy fixes, beyond my immediate skills

any help would be much appreciated!

its important to get this branch functioning again

**Comment by wbpcode** [comment]
cc @phlax could just run the refresh script in the 1.22 rather than cherry-pick?

**Comment by phlax** [comment]
> cc @phlax could just run the refresh script in the 1.22 rather than cherry-pick?

i could - thanks!

i guess i can find it - but ftr - how do you do that ?

**Comment by wbpcode** [comment]
cc @phlax 
```
$ cd test/extensions/transport_sockets/tls/ocsp/test_data
# ./certs.sh
```

**Comment by dcillera** [comment]
I've launched the script but got an error:
```
$ ./certs.sh
Certificate request self-signature ok
subject=C = US, ST = California, L = San Francisco, O = Lyft, OU = Lyft Engineering, CN = ca
**Cannot use both -key/-signkey and -CA option**
```

**Comment by phlax** [comment]
openssl version perhaps ?

might be worth trying in a container with a different version

**Comment by wbpcode** [comment]
Maybe you can try to run the command in the envoy build container `envoyproxy/envoy-build-ubuntu:142e6d5662b98277a84c327da26ed266ab0e3191`.

**Comment by phlax** [comment]
should be possible to use `run_envoy_docker.sh` i think

**Comment by phlax** [comment]
ive added a commit here https://github.com/envoyproxy/envoy/pull/23914/commits/ad0705ad17c06ea9d1c8c1d68231b6e58fe6b751 with a possible fix for certs as i wanted to test other backports on this branch - lets see if it works

**Comment by phlax** [comment]
arggh - it didnt but from scan it looks like another openssl version issue - i think i may need to rerun using the envoy build container (and not my dev container)

**Comment by phlax** [comment]
@wbpcode if i just update the certs with the script i hit this:

```console
test/extensions/transport_sockets/tls/context_impl_test.cc:156: Failure
Expected equality of these values:
  context->daysUntilFirstCertExpires()
    Which is: 0
  days_until_expiry
    Which is: -19

```

which is i think the same problem i had when picking the change from other branch

@daixiang0 any ideas on this - i know you fixed some related issues on main

**Comment by wbpcode** [comment]
cc @phlax Seems like the certs for `tls` is also outdated, not just `oscp`.

**Comment by phlax** [comment]
i thought that was what i was trying to fix - this branch already has the oscp update i think - is there a different command we need to run or commit to pick ?

**Comment by wbpcode** [comment]
See #22792 and #22811

**Comment by wbpcode** [comment]
You can update them by the following commands:
```
$ cd test/extensions/transport_sockets/tls/test_data
# ./certs.sh
```

**Comment by phlax** [comment]
that is what i did - which is not working

im realising tho that the ocsp cert fix is the same - im wondering if removing that _and_ running the script will fix - ill try on my other branch ...

**Comment by wbpcode** [comment]
I am running the commands and tests in my local env. It need take some times.

**Comment by wbpcode** [comment]
cc @phlax It should be fixed by above two refresh commends (one for tls one for ocsp). And a minor test code update is necessary.

I create a new pr to run the complete CI. See #23931

**Comment by phlax** [comment]
thanks for tracking that down @wbpcode 

@dcillera - hopefully the commit in #23842 should fix the certs issue/s

**Review by phlax — APPROVED** [review]
lgtm, thanks @dcillera for persevering on this

**Pull request merged**
