### PR TITLE
thrift proxy: don't charge response for Oneway calls

### LINKED ISSUE #16617: thrift-proxy: response timing should exclude one way calls
We missed a spot in #16261 while fixing charging response times. We still need to exclude Oneway calls from the response time histograms. The problem starts here:

https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/thrift_proxy/router/router_impl.cc#L208

which then will call `chargeResponseTiming()`, and `chargeResponseTiming()` doesn’t bail on `metadata_->messageType() == MessageType::Oneway` when it actually should. For deployments doing Oneway calls, this means their stats will be lower/better than they actually are. 

cc: @fishcakez @williamsfu99

### PR DESCRIPTION
**Pull request by rgs1**
Commit Message:
This is a follow-up to #16261.

Additional Description:
Fixes #16617.

Risk Level: Low.
Testing: Added.
Docs Changes: Not needed (I think).
Release Notes: NA.
Platform Specific Features: None.

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

### CODE REVIEW

**Comment by rgs1** [comment]
I take this back, docs actually say that one way is included:

```
Histogram, total rq time from rq complete to resp complete; includes oneway messages.
```

It's a bit weird, but if it's documented it's fine.

**Comment by rgs1** [comment]
Hmm, maybe we do want this and we want to update the docs accordingly. Maybe we even want an additional histogram that only computes request time (which would include Oneway).

I'll wait for @williamsfu99 to weight in.

**Comment by zuercher** [comment]
My original intention was to measure the end-to-end time that Envoy participates in a request, which is why I included one-way (which just has no response part). I'm fine to have these split out separately, but I think it should probably be one PR to split the stats and update the docs.

**Comment by zuercher** [comment]
@rgs1 is this still in progress or do you want to close it?

**Comment by rgs1** [comment]
> @rgs1 is this still in progress or do you want to close it?

Closing it for now.

**Pull request closed without merging**
