### PR TITLE
hcm: use optional<iter> instead of iter end

### PR DESCRIPTION
**Pull request by silentdai**
Description: 
The pattern iterator::end() as pivot is less expressive than an
optional. Fix all the occurrences in HCM

Risk Level: LOW
Testing: existing test

### CODE REVIEW

**Comment by mattklein123** [comment]
Thanks for the contribution. This seems a bit like change for change sake and not worth the regression risk. What's the rationale for the change?

/wait-any

**Comment by silentdai** [comment]
Thank you for the comment!

- Regression concern: 
All the changes are limited to stack variables so the existing tests should cover.


What's the hunch when you see `trailers_added_entry == encoder_filters_.end()`? 
Reaching the end of the iterator, or it is never assigned to a legit value, especially in a 150-line function `ConnectionManagerImpl::ActiveStream::decodeHeaders(HeaderMapPtr&& headers, bool end_stream)`?

We need the everlasting refactors to make the semantic more straightforward, don't we?

**Comment by mattklein123** [comment]
@silentdai OK I think I understand the intent of the change now, sounds good on the optional part. Please revert the other parts with the ternary operator as this will conflict with ongoing @soya3129 change and generally seems like change for change sake. Thank you.

/wait

**Comment by silentdai** [comment]
Thanks! I agree with your that the ternary operator does bring much values: only save a default constructor invoke which is nothing here. I revert it and keep only optional type.

**Comment by silentdai** [comment]
I am not saying there is any bug in existing code. Otherwise I would throw a test case.
The idea is that `continue_data_entry` valued `end()` has *readability issue* although it is semantically *correct*.
I understand that this code was authored when absl::optional is not announced yet.

I read beyond this code and the vagueness is no longer an issue to me. I am fine if you don't accept. 
I just hope with this PR the future contributors could understand it easier when they encounter `continue_data_entry` at their first time.

**Comment by mattklein123** [comment]
OK let's close for now as I don't think the optional is really any better than initializing to `end()`. We can reopen if this comes up again.

**Pull request closed without merging**
