### PR TITLE
[backport 1.27] Fix intermittent cpu spike in grpc async client (#30123)

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
Commit Message:
backport of https://github.com/envoyproxy/envoy/pull/30123
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by phlax — DISMISSED** [review]
lgtm, thanks @vikaschoudhary16

**Comment by vikaschoudhary16** [comment]
> @vikaschoudhary16 just realized this has no changelog - would you mind adding - wondering about the 1.28 bp and main

hey, release notes were not added on main PR and hence neither on 1.28 bp and this one. Please let me know if I should add.

**Comment by phlax** [comment]
> Please let me know if I should add.

probably yes - if the change warrants backporting then it should be in the changelog

**Review by phlax — APPROVED** [review]
lgtm, thanks @vikaschoudhary16

**Pull request merged**
