### PR TITLE
ci: Dont remove packages in ci jobs

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: ci: Dont remove packages in ci jobs
Additional Description:

This isnt necessary in terms of disk space - afaict, it will save ~1~ 2-3mins across a lot of jobs

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
actually this seems to give a pretty huge speedup - more like 2-3 minutes per linux x86 job

**Comment by lizan** [comment]
AZP base image changes over time, I think we're good for now but they only guarantees 10 GB of free space. Do we want to remove these script for now?

**Review by lizan — APPROVED** [review]

**Comment by phlax** [comment]
> AZP base image changes over time, I think we're good for now but they only guarantees 10 GB of free space. Do we want to remove these script for now?

yep - we can add back for specific jobs if we need to - its a lot of disk io that just slows down ci otherwise

**Comment by lizan** [comment]
sgtm

**Pull request merged**
