### PR TITLE
common: fix errors from -Wrange-loop-analysis rule

### PR DESCRIPTION
**Pull request by rebello95**
With Xcode 12, `-Wrange-loop-analysis` becomes active and yields errors preventing Envoy Mobile from building. This PR fixes the errors in Envoy code yielded by this rule.

Unfortunately, I was unable to enable this rule in Envoy's build because of third party violations, but that is now being tracked in https://github.com/envoyproxy/envoy/issues/13154.

Fixes https://github.com/envoyproxy/envoy/issues/13139.

Risk Level: Low
Testing: Existing unit tests

Signed-off-by: Michael Rebello <me@michaelrebello.com>

### CODE REVIEW

**Comment by rebello95** [comment]
CI failure looks unrelated:

```
Updated Homebrew from 484c2b4fa to 871abe8b9.
Error: 767: unexpected token at '{
  "java11": "homebrew/core",
}
'
```

**Comment by rebello95** [comment]
cc @yanavlasov @lizan based on context in https://github.com/envoyproxy/envoy/issues/11949

**Comment by rebello95** [comment]
Hmm, it looks like there are some external violations:

```
bazel-out/darwin-fastbuild/bin/external/com_googlesource_quiche/quiche/spdy/core/hpack/hpack_header_table.cc:258:19: error: loop variable 'it' of type 'const std::__1::pair<const std::__1::basic_string_view<char, std::__1::char_traits<char> >, const spdy::HpackEntry *>' creates a copy from type 'const std::__1::pair<const std::__1::basic_string_view<char, std::__1::char_traits<char> >, const spdy::HpackEntry *>' [-Werror,-Wrange-loop-analysis]
  for (const auto it : static_name_index_) {
                  ^
bazel-out/darwin-fastbuild/bin/external/com_googlesource_quiche/quiche/spdy/core/hpack/hpack_header_table.cc:258:8: note: use reference type 'const std::__1::pair<const std::__1::basic_string_view<char, std::__1::char_traits<char> >, const spdy::HpackEntry *> &' to prevent copying
  for (const auto it : static_name_index_) {
       ^~~~~~~~~~~~~~~
bazel-out/darwin-fastbuild/bin/external/com_googlesource_quiche/quiche/spdy/core/hpack/hpack_header_table.cc:266:19: error: loop variable 'it' of type 'const std::__1::pair<const std::__1::basic_string_view<char, std::__1::char_traits<char> >, const spdy::HpackEntry *>' creates a copy from type 'const std::__1::pair<const std::__1::basic_string_view<char, std::__1::char_traits<char> >, const spdy::HpackEntry *>' [-Werror,-Wrange-loop-analysis]
  for (const auto it : dynamic_name_index_) {
                  ^
bazel-out/darwin-fastbuild/bin/external/com_googlesource_quiche/quiche/spdy/core/hpack/hpack_header_table.cc:266:8: note: use reference type 'const std::__1::pair<const std::__1::basic_string_view<char, std::__1::char_traits<char> >, const spdy::HpackEntry *> &' to prevent copying
  for (const auto it : dynamic_name_index_) {
       ^~~~~~~~~~~~~~~
2 errors generated.
```

Is there a way to apply this rule only for Envoy code or do we need to fix each dependency?

**Comment by mattklein123** [comment]
cc @danzh2010. We will need to fix QUICHE also since ultimately xcode will end up complaining there also.

**Comment by rebello95** [comment]
Looks like Envoy Mobile does not depend on QUICHE code right now, so the fixes in this PR are sufficient for getting Envoy Mobile to compile again. I dropped the build rule change and instead filed an issue to enable that separately: https://github.com/envoyproxy/envoy/issues/13154

@mattklein123 mind taking another look?

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Comment by rebello95** [comment]
I believe remaining CI failures are unrelated

**Comment by mattklein123** [comment]
Please merge main to fix CI.

/wait

**Comment by moderation** [comment]
In addition the quiche issues the following is required to build in MacOS
```diff
diff --git a/source/extensions/filters/http/common/compressor/compressor.cc b/source/extensions/filters/http/common/compressor/compressor.cc
index 4e0a1b48c..e8e604295 100644
--- a/source/extensions/filters/http/common/compressor/compressor.cc
+++ b/source/extensions/filters/http/common/compressor/compressor.cc
@@ -224,7 +224,7 @@ CompressorFilter::chooseEncoding(const Http::ResponseHeaderMap& headers) const {
   }

   // Find all encodings accepted by the user agent and adjust the list of allowed compressors.
-  for (const auto token : StringUtil::splitToken(*accept_encoding_, ",", false /* keep_empty */)) {
+  for (const auto& token : StringUtil::splitToken(*accept_encoding_, ",", false /* keep_empty */)) {
     EncPair pair =
         std::make_pair(StringUtil::trim(StringUtil::cropRight(token, ";")), static_cast<float>(1));
     const auto params = StringUtil::cropLeft(token, ";");
```

**Comment by rebello95** [comment]
Thanks @moderation - added that as a task for https://github.com/envoyproxy/envoy/issues/13154

**Pull request merged**
