### PR TITLE
Bump coverage in the HCM config test

### PR DESCRIPTION
**Pull request by yanavlasov**
Risk Level: Low
Testing: Unit Test
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

Signed-off-by: Yan Avlasov <yavlasov@google.com>

### CODE REVIEW

**Comment by phlax** [comment]
wondering if this will allow us to revert (at least part of) #24569

**Comment by yanavlasov** [comment]
Not sure.
There are missing coverage for EarlyHeaderMutationFactory errors, which contributes a lot of lines.

However more importantly there is no negative test cases for `upgrade_dependency_manager.validDecodeDependencies()`. It is only one line, but seems like an important case is untested.

**Comment by yanavlasov** [comment]
#24590 for the EarlyHeaderMutationFactory coverage

**Comment by yanavlasov** [comment]
#24591 for dependency checker

**Review by mattklein123 — APPROVED** [review]

**Pull request merged**
